### ISSUE TITLE
新規会員登録のときはユーザー名で日本語が登録できないようにする

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1000]
そして、ユーザー名をアカウントに変える。

**Comment by wawawatataru** [comment]
@machida 
ユーザー名(変更後:アカウント)に使用可能な文字は半角英数字のみという認識で問題ないでしょうか?

↑の場合、画像の下線部のテキストは`半角英数字のみが使用できます。`に変更
エラーメッセージ(画像の枠内)は`アカウントは半角英数字のみが使用できます`
で問題ないでしょうか。

ご確認をお願いします 🙇 

![image](https://user-images.githubusercontent.com/2524168/66467541-8efb5580-eabf-11e9-820e-b856fa9a54fc.png)

**Comment by machida** [comment]
GitHubのアカウントと同じにしたいですー！
アンスコとかは使えるようにしたいです。

**Comment by wawawatataru** [comment]
> GitHubのアカウントと同じにしたいですー！

承知しました!!

GitHubが
* 半角英数字とハイフンのみ
* 最初と最後にハイフン不可
* 連続でハイフン不可

のようなのでそれに合わせちゃいます。

アンダースコア使えないのが意外でした… :flushed:
