### ISSUE TITLE
誤表記の修正: receiver ->reciever

### ISSUE THREAD

**Issue by matt-note** [fjordllc/bootcamp#1003]
以下の点が誤表記なのではと思います。
意図的に receiver を使っている場合は、この Issue は close しようと思います。
* https://github.com/fjordllc/bootcamp/blob/master/app/models/notification.rb#L103-L106
* https://github.com/fjordllc/bootcamp/blob/master/app/models/report_callbacks.rb#L12-L14

**Comment by machida** [comment]
@matt-note こういう具体的なタイポの修正は、勝手にPRを作ってしまう方が早いので、issueは作らずにPRを作ってしまって大丈夫です。もし、意図的に receiver を使っている場合はPRがcloseされるので。

ファイルを修正して、git commit -m"誤表記の修正: receiver ->reciever" で済むので issueを作るのよりも手間をかけずに価値を与えることができます。

**Comment by matt-note** [comment]
@machida さん
コメント、ありがとうございます。

> 勝手にPRを作ってしまう方が早い
この場合では、PRを作って、判断してもらう、というように進めていこうと思います。

**Comment by machida** [comment]
@matt-note ありがとうございます！よろしくお願いします🙏

**Comment by matt-note** [comment]
PRを作成しました。
* https://github.com/fjordllc/bootcamp/pull/1004
