### ISSUE TITLE
他の人の日報においてWatchをオンにしていても通知が来ない

### ISSUE THREAD

**Issue by wai-doi** [fjordllc/bootcamp#1006]
## 概要
自分以外の他の人が書いた日報と提出物に対してWatchがオンの状態であるが、その日報と提出物にコメントが書かれたことを知らせる通知が来ない。

## 再現手順

1. Aさんが日報を提出する。
2. BさんがAさんの日報にコメントする。
3. Aさんの日報に対してBさんのWatchが、自動的にオンになる。
4. Bさんのコメントに対してAさんがコメントを返す。
5. 「Aさんの日報にコメントが書かれた」ということを知らせる通知が、Bさんに来ない。

- 日報が提出物であった場合でも同様だった
- 日報を書いた本人には、Watchをオンにしていなくてもコメントが書かれたことを知らせる通知が来る

## 修正すべき内容
いまの状態だとWatch機能の意味がなく、自分のコメントに返してくれたことに反応ができない。

Watchしている日報、提出物にコメントが書かれたら、コメントが書かれたことを知らせる通知が来てほしい。

**Comment by UsaMomokawa** [comment]
@wai-doi 
報告ありがとうございます！

> 日報を書いた本人には、Watchをオンにしていなくてもコメントが書かれたことを知らせる通知が来る

テストでは、本人の日報に対して通知が来るかどうか検証していたので、
まずはテストを直してみて検証しますね。

修正時期については、
watch機能をvuejs化するissueが進行していますので、そこで一緒に直します。

**Comment by wai-doi** [comment]
@UsaMomokawa 
よろしくお願いします🙏

**Comment by wai-doi** [comment]
@UsaMomokawa 
[日報](https://bootcamp.fjord.jp/reports/5658)を見ました。バグの修正を進めていただきありがとうございます。

一つ気づいたことですが

https://github.com/fjordllc/bootcamp/blob/master/app/models/comment_callbacks.rb#L9

```ruby
  def after_create(comment)
    if comment.sender != comment.reciever
      notify_comment(comment)
      notify_to_watching_user(comment)
      create_watch(comment)
    end

    notify_admin(comment)
  end
```
このifの条件`if comment.sender != comment.reciever`についてですが
「"コメントを書いた人"と"日報を書いた人"が異なる場合」という意味に思えます。

再現手順の４「Bさんのコメントに対してAさんがコメントを返す。」では、
ここでコメントを書く人はAさん、日報を書いた人はAさんなので、この条件が偽となると思います。
なので`notify_to_watching_user(comment)`などは実行されないことになります。

つまり、他の人のCさんがコメントを書いた場合はこの条件が真になり、`notify_to_watching_user(comment)`などが実行されます。

このif条件についての話が日報に書かれていなかったようにみえたので、不安になりました。
これについて認識されてるでしょうか。

こちらの理解が間違っていたらすみません。

**Comment by UsaMomokawa** [comment]
@wai-doi 

日報を見てくださってありがとうございます！すごくありがたいです！
ご指摘の通りです。日報作成者がコメントを返した場合、通知されない原因となっていました。

(まだレビューをいただいていないため暫定ですが)
現在は下記のように書き換え、バグ再現のテストを通してあります。
日報にも追記しておきますね！

```
  def after_create(comment)
    if comment.sender != comment.reciever
      notify_comment(comment)
    end

    if [Report, Product, Question].include?(comment.commentable.class)
      create_watch(comment)
      notify_to_watching_user(comment)
    end

    notify_admin(comment)
  end
```

**Comment by wai-doi** [comment]
@UsaMomokawa 
すでに修正なさってたんですね。よかったです😀
引き続き、修正をお願いします🙏

**Comment by UsaMomokawa** [comment]
＠wai-doi

「日報作成者のAさんがコメントを返した時、ウォッチ通知がBさんに来ない」バグについて、
修正をおこないました。さきほど本番環境に適用されました🙇‍♀️

**Comment by wai-doi** [comment]
@UsaMomokawa 
ありがとうございました👏
