### ISSUE TITLE
研修生が日報をWIPで保存すると、slackの会社チャンネルに日報を提出した通知が飛んでしまう

### ISSUE THREAD

**Issue by wai-doi** [fjordllc/bootcamp#1007]
## 概要
研修生が日報をWIPで保存すると、「日報を提出しました」というメッセージがSlackの会社チャンネルに送られてしまう。

## 再現手順
Slackのフィヨルドワークスペースには研修生Aさんの会社チャンネルがある状態

1. 研修生のAさんがトップページにある日報作成ボタンを押す。
1. 日報作成ページに行く。
1. 日報を途中まで書く。（何が必須項目かわかってません）
1. WIPボタンを押す。
1. Slackの会社専用チャンネルに、「Aさんが日報を提出しました」というメッセージが送られる。

<img width="722" alt="Slack_-_FJORD__LLC" src="https://user-images.githubusercontent.com/29339636/59147585-8a9f2d00-8a38-11e9-8991-0724fccd92e8.png">

## 修正すべき内容
WIPボタンを押すときはまだ日報が未完成な状態なので、そのタイミングでメッセージは送られてほしくない。

「日報を提出しました」のメッセージは、提出ボタンを初めて押したときに送られてほしい。WIPボタンを初めて押したときは送られてほしくない。

**Comment by komagata** [comment]
#1034と重複
