### ISSUE TITLE
日報作成で、学習日の入力フィールドをクリックすると、項目選択がはずれない

### ISSUE THREAD

**Issue by wai-doi** [fjordllc/bootcamp#1018]
## 概要
日報作成で、学習日の入力フィールドをクリックするとフィールドから項目選択の状態がはずれない

## 再現手順
1. 日報作成のページへ
1. 学習日の入力フィールドをクリック
1. 学習日の入力フィールド以外の場所をクリック（灰色の部分など）
1. フィールド選択の状態から抜け出せない（カーソルの形状がポインタのまま）

## 試したこと
クリックする場所によっては、学習日フィールド選択の状態から抜け出せる
- 左の青い部分
- 学習時間のフィールド
- 日報本文を書くフィールド
- ピヨルドのアイコンや検索バーがある白い部分
<img width="1433" alt="日報作成___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/29339636/59450654-a47bae00-8e44-11e9-90ac-b6d793de083b.png">

## 期待する動作
学習日の入力フィールド以外の場所をクリックすると、フィールド選択状態から抜け出せるようにしたい

**Comment by sanfrecce-osaka** [comment]
これどうも下記っぽいです。
原因まではまだ追っていないです。

## 発生のトリガー
学習日のフィールドの上にマウスオーバーすること

## 現象
学習日のフィールドの上にマウスオーバー後、テキストフィールド(プラクティス・タイトル・学習日)の挙動がおかしくなる

**Comment by sanfrecce-osaka** [comment]
[![Image from Gyazo](https://i.gyazo.com/66632201e9066365d1806c47a605722f.gif)](https://gyazo.com/66632201e9066365d1806c47a605722f)

**Comment by wai-doi** [comment]
#1019 
修正されました。ありがとうございます。
