### ISSUE TITLE
WIPでも企業Slackに日報が飛んでしまう

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1034]
- 初めてWIPから公開になった時１度だけSlackに通知する。
  - 公開後にWIPに戻して再度公開しても通知されないようにする。

## 実装案

日報にpublished_atカラムを用意して、初回公開時に日付を入れる。
上記を見て２度目以降は通知しない。

**Comment by tararico** [comment]
Ref: #1038

**Comment by tararico** [comment]
@komagata 
久しぶりすぎて、本番で確認する前にcloseしてしまいました。すみません。
こちら、企業アカウントユーザーで日報を作成して本番で確認していただいてもよろしいでしょうか？
よろしくお願いします。

**Comment by komagata** [comment]
@tararico 本番でアカウント作って大丈夫ですので確認おねがいしますー。
あとで連絡いただければそのあと削除します。

**Comment by tararico** [comment]
@komagata ありがとうございます。動作確認できました。
問題ありませんでしたので、アカウント削除をお願いします。

**Comment by komagata** [comment]
@tararico 削除しましたー
