### ISSUE TITLE
本の貸し借り管理機能

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1035]

**Comment by matt-note** [comment]
Ref: https://github.com/fjordllc/bootcamp/pull/1036

**Comment by matt-note** [comment]
TODO

**方針**
* Book モデルを作成して、CRUD機能を作成して、書籍の管理をできるようにする。
* User と Book の関連は、多対多になるので、中間モデルとして Rental モデルを作成する。
* gem を使って書籍に貼り付ける QR コードを作成する。
* QR コードで読み取った URL から、書籍を借りることができるようにする。
