### ISSUE TITLE
日報作成ページで誤って学習時間の削除ボタンを押すと学習時間を入力できない

### ISSUE THREAD

**Issue by matt-note** [fjordllc/bootcamp#1047]
↓ gif です。
![Peek 2019-07-12 23-30](https://user-images.githubusercontent.com/39484102/61135785-47375300-a4fd-11e9-8eba-e829b475364b.gif)

**Comment by komagata** [comment]
@matt-note そこにある学習時間追加ボタンを押してもだめですか？

**Comment by matt-note** [comment]
@komagata 学習時間追加ボタンを押したところ、入力できるようになりました。失礼しました。アプリとしては問題ないようなので close した方が良いでしょうか？

**Comment by matt-note** [comment]
本番環境で確認できたので、close します。
