### ISSUE TITLE
他人を退会させられてしまう

### ISSUE THREAD

**Issue by shita1112** [fjordllc/bootcamp#1053]
## 内容
退会手続きの画面(`/users/:user_id/retirement/new`)で、他ユーザーのidを指定して退会手続きを進めると、そのユーザーを退会させられます。

development環境で検証しました。

## 解決方法
URL設計がまずい気がするので、そこから作り直すと良さそうです。

**Comment by komagata** [comment]
うわ、やばいですねこれ、レビューでチェックできてなかったすいません・・・

**Comment by shita1112** [comment]
本番環境でのテストが終わったので、close
