### ISSUE TITLE
日報の学習時間を複数つけた場合に、時間範囲が時系列順に並んでほしい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1062]
## 現状の動作
学習時間を登録した順番と同じ順番で表示されてしまう

<img width="773" alt="kimura2___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/29339636/61783791-6d38ed80-ae43-11e9-890b-0b6e3fe0d773.png">

## 期待する動作
時系列順に表示されてほしい

<img width="752" alt="kimura2___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/29339636/61784079-fea85f80-ae43-11e9-8a2d-37670ba805ec.png">

**Comment by wai-doi** [comment]
本番環境で確認できたのでcloseします
