### ISSUE TITLE
markdownでコードブロックを書くときに言語を指定しても、プレビューにシンタックスハイライトが反映されない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1063]
## 概要

日報の本文にコードブロックを書いたときにプレビューにシンタックスハイライトが反映されてほしい。

## 再現手順

日報の新規作成や編集を開く。

本文に
```ruby
a = 1
```
のような言語を指定したコードブロックを書く。
右側のプレビューには色付けされたシンタックスハイライトされずに、シンプルな表示になってしまう。

## 期待される振る舞い
/reports/idの日報の画面のような、コードブロックのプレビューに色付けされたシンタックスハイライトが表示されてほしい。

## スクリーンショット
現状のプレビューはシンプルな表示

<img width="1344" alt="日報編集___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/29339636/62260473-01f7a880-b44d-11e9-975c-7a16c7c1f488.png">

理想は、
/reports/idの日報の画面のように表示されてほしい

<img width="762" alt="b___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/29339636/62260353-a88f7980-b44c-11e9-995c-231f16fe6e10.png">

## 環境
 - ブラウザ: chrome

**Comment by wai-doi** [comment]
コメントのプレビューの場合は黒背景だが色付けはされてない

<img width="802" alt="b___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/29339636/62260870-7848da80-b44e-11e9-952d-a02d6e948381.png">

**Comment by JunichiIto** [comment]
> コメントのプレビューの場合は黒背景だが色付けはされてない

これ、僕も気になりました。

**Comment by bbbbruno** [comment]
@komagata 
こちらの問題は`textarea-markdown`に問題があることが分かったので、プルリクを作成させていただきました。
https://github.com/komagata/textarea-markdown/pull/1

ただ、https://github.com/fjordllc/bootcamp/pull/1537で説明した通り、`langPrefix`に`language-`または`lang`を使用すると、全てが`token`に置き換わってしまいます。
`lng-`に変更することで解決できるのですが、どうすればよいでしょうか？

**Comment by komagata** [comment]
@bbbbruno PRありがとうございます！

#1537 にコメントしました〜

**Comment by bbbbruno** [comment]
> @bbbbruno PRありがとうございます！
> 
> #1537 にコメントしました〜

**Comment by bbbbruno** [comment]
@komagata 
今のままではまだプレビュー時にシンタックスハイライトが効かないので、こちら(komagata/textarea-markdown#1)も確認お願いします！

**Comment by ima1zumi** [comment]
マージ済ですのでCloseします〜
