### ISSUE TITLE
プラクティス一覧画面が遅い

### ISSUE THREAD

**Issue by shita1112** [fjordllc/bootcamp#1071]
## 内容
プラクティス一覧画面（`/courses/1/practices`）の表示が遅い。3~4秒かかる。よく使う画面なので速くしたい。

## 解決方法
N+1っぽいのでeager loadingしてあげればよさそう。

**Comment by machida** [comment]
これ直したいですね！
https://github.com/flyerhzm/bullet
これ導入するとよかったりしますか？

**Comment by shita1112** [comment]
bulletいいと思います！

ただ、結構他の所でもN+1の警告が出そうな気がするので、もしかしたら他の方達の開発時にノイズになるかもです。
JSのalertでの警告でなく、ログに吐くよう設定できたと思うので、それなら邪魔にならないかなー、どうなんだろう。。。

N+1潰すのに役立つので、可能なら導入したいです。

**Comment by sanfrecce-osaka** [comment]
横からすみません。
以下、個人的意見です。
以前個人的にbootcampにbullet導入しようとひっそりやってたんですが結構修正必要な箇所あった気がします。(うろ覚えですが)
その時はエラー画面出す設定にしていたんですがそれだと影響範囲大きそうですね・・・。
それか全箇所洗い出して徹底的にN+1撲滅していくとか・・・？
ただいずれにしても、N+1については他の方たちも知っておいた方がいい知識なのではという気がするのでなんとか他の方たちにも気づいてもらえる形で通知できるようにしたいですね・・・。(ログだと気づきにくいという気も・・・？)

**Comment by shita1112** [comment]
速度向上による恩恵はかなり大きいと思うので、ここでN+1を全部潰しておいて、今後はN+1を作らないようにbulletで画面に警告出すのがいいかなーと思います。

さっき実際にbullet入れて確認したのですが、N+1かなりありました。ざっと見ただけでも10箇所以上はあります。影響範囲も大きいし、修正が大変な箇所もあると思いますが、やる価値はありそうです。

**Comment by komagata** [comment]
@shita1112 いいとおもいますー！

**Comment by machida** [comment]
@komagata @shita1112 

> N+1かなりありました

一旦それぞれを別issueにしたいですね。一気にやるのは大変なのと、早くサイトを速くしたいので、小出しにマージしていきたいです。

**Comment by shita1112** [comment]
@machida 

了解ですー。
とりあえずN+1洗い出してみます。

**Comment by shita1112** [comment]
N+1の修正が必要な箇所を洗い出しました。

画面17箇所とパーシャル2箇所の計19箇所です。
1画面に複数のN+1を含む場合も多いです。

<table>
  <tr>
    <th>分類</th>
    <th>画面</th>
    <th>URL</th>
  </tr>

  <tr><td rowspan="2">パーシャル</td><td>右サイドバーの日報一覧</td><td>http://localhost:3000/ 等<br>ファイルはreports/recent_reports.html.slim</td></tr>
  <tr><td>日報等に付く足跡一覧</td><td>http://localhost:3000/reports/91657736 等<br>ファイルはfootprints/footprints.html.slim</td></tr>

  <tr><td rowspan="8">/</td><td>ダッシュボード</td><td>http://localhost:3000/</td></tr>
  <tr><td>ユーザー一覧</td><td>http://localhost:3000/users</td></tr>
  <tr><td>Q&A一覧</td><td>http://localhost:3000/questions</td></tr>
  <tr><td>お知らせ一覧</td><td>http://localhost:3000/announcements</td></tr>
  <tr><td>通知一覧</td><td>http://localhost:3000/notifications</td></tr>
  <tr><td>提出物一覧</td><td>http://localhost:3000/products</td></tr>
  <tr><td>提出物一覧（未チェックのみ）</td><td>http://localhost:3000/products/unchecked</td></tr>
  <tr><td>プラクティス一覧（学習内容）</td><td>http://localhost:3000/practices</td></tr>

  <tr><td rowspan="5">users</td><td>指定ユーザーの、プロフィール</td><td>http://localhost:3000/users/459775584</td></tr>
  <tr><td>指定ユーザーの、ポートフォリオ一覧</td><td>http://localhost:3000/users/459775584/portfolio</td></tr>
  <tr><td>指定ユーザーの、日報一覧</td><td>http://localhost:3000/users/609827778/reports</td></tr>
  <tr><td>指定ユーザーの、コメント一覧</td><td>http://localhost:3000/users/459775584/comments</td></tr>
  <tr><td>指定ユーザーの、提出物一覧</td><td>http://localhost:3000/users/609827778/products</td></tr>

  <tr><td rowspan="1">practices</td><td>指定プラクティスの、提出物一覧</td><td>http://localhost:3000/practices/577419917/products</td></tr>

  <tr><td rowspan="1">courses</td><td>指定コースの、プラクティス一覧</td><td>http://localhost:3000/courses/86912251/practices</td></tr>

  <tr><td rowspan="2">admin</td><td>adminの、ユーザー一覧</td><td>http://localhost:3000/admin/users</td></tr>
  <tr><td>adminの、会社一覧</td><td>http://localhost:3000/admin/companies|</td></tr>

</table>

**Comment by shita1112** [comment]
issueの粒度はどうしましょう？
画面毎だとIssueが多すぎるので、分類毎がいいかなーと思います。（自分が適当に作った分類ですが）

**Comment by shita1112** [comment]
分類ごとにissue切るとしたら、こんな感じで計6つのissueになります。

| 分類       | ポイント(予想) |
|----------|--------------|
| パーシャル |            3 |
| courses     |            2 |
| /          |            5 |
| users      |            3 |
| practices  |            2 |
| admin      |            2 |

（わかりにくい分類ですみません😭coursesとかusersは親リソースでまとめた感じです。）

上から優先度順で並べていて、よく使われるであろう画面を先に潰していきます。

想像以上にN+1が多かったので、合計17ポイント(予想)もあります・・・。N+1潰しは`preload`や`eager_load`を追加するだけで終わる場合も多いですが、修正が結構面倒な場合もありそうです。ちゃんとコード読まないとわからないので、この時点だとちょっと正確なポイントは読みにくいです。

これで問題ないようだったらissue切って修正始めますー。

**Comment by komagata** [comment]
ありがとうございます！お願いしますー！

**Comment by shita1112** [comment]
6つのissueに分割しましたー。このissueはcloseします。
