### ISSUE TITLE
現在、所属企業が必須になっていて、一般ユーザーはフィヨルド所属になっているが、所属企業の必須をやめて、一般ユーザーは所属なしにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1088]
`- unless user.company.id == 1`

（フィヨルドのidが1）

と対応しているのがキモいので、止めたい。

**Comment by s4na** [comment]
## 作業

- [ ] バリデーションについて調査中

**Comment by s4na** [comment]
@komagata 

質問です！

1. 本番環境のDBをマイグレーションで操作したい場合、どうすればいいのでしょうか？
   マイグレーションファイルを作成すれば適応されるのでしょうか？
1. 既存のユーザーの `company_id` の値を修正するにはどうすればいいのでしょうか？
   例：フィヨルド生の所属を`1`（フィヨルド）から`nil`（なし）に変更

**Comment by komagata** [comment]
@s4na 

> 1.

本番へのデプロイ時に`rails db:migrate`が可能な状態であれば実行されます。

> 2.

本番のデータの話でしょうか、それとも開発環境の話でしょうか。

開発環境であれば`rails db:seed`が動いてデータが設定されるのでその辺りのファイルを見るとわかると思いますー

**Comment by s4na** [comment]
@komagata 

ありがとうございます！

> 本番のデータの話でしょうか、それとも開発環境の話でしょうか。

本番環境です！

> 開発環境であればrails db:seedが動いてデータが設定されるのでその辺りのファイルを見るとわかると思いますー

見てみます！
