### ISSUE TITLE
お知らせに、「全員に通知」、「現役生にだけ通知」と、通知の範囲を選択できるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1101]

**Comment by wawawatataru** [comment]
@machida 
全員にお知らせと現役生にお知らせのユーザーの決め方について確認いただきたいです。


**全員にお知らせ（今までのお知らせ通知の対象と同じ）**
* リタイアしていない( `retired_on` が `nil` )

---

**現役生にお知らせ**
* 管理者ユーザー( `admin` が `true` )
または以下の条件をすべて満たすユーザー
* リタイアしていない( `retired_on` が `nil` )
* 会社に属していない(`company_id`が`nil`)
* アドバイザーでない(`adviser`が`false`)
* メンターでない(`mentor`が`false`)
* 研修生でない(`trainee`が`false`)
* 卒業していない(`graduated_on`が`nil`)

以上で問題ないでしょうか。
確認をお願いします🙇‍♂️

**Comment by machida** [comment]
@wawawatataru わかりやすくまとめていただきありがとうございます！！

@komagata 
これでいいと思うのですが、何か抜けとかないでしょうか？

**Comment by komagata** [comment]
> 会社に属していない(company_idがnil)

traineeがfalseの方で判断できるのでこれはいらないです〜

他はOKだと思いますー！

**Comment by wawawatataru** [comment]
@machida @komagata 
確認ありがとうございます。
承知しました！！

**Comment by wawawatataru** [comment]
@komagata 
本番でご確認をお願いします。
