### ISSUE TITLE
プラクティス「cssの基本を理解する」内のリンクエラー

### ISSUE THREAD

**Issue by fksgshota** [fjordllc/bootcamp#1113]
## 概要

参考：レスポンシブデザイン参照
- [CSS3 Media Queriesを使って、Webサイトをスマートフォンに対応させるときの注意書き](http://webdesignrecipes.com/web-design-for-mobile-with-css3-media-queries/)

## 再現手順

1. https://bootcamp.fjord.jp/practices/54にアクセス。
2. リンクをクリック。
3. エラーが表示される。

## 期待される振る舞い

リンク先の正常な表示

## スクリーンショット

![image](https://user-images.githubusercontent.com/41514564/63310311-24d2f980-c335-11e9-96ed-e1899e777507.png)

## 環境

 - OS: [macOS Mojave]
 - ブラウザ: [chrome, safari]

**Comment by komagata** [comment]
@fksgshota @s4na Issueありがとうございます。

上記リンクを削除しました。

プラクティス内のリンクは僕らが管理画面からすぐ直すのでIssueにせずSlackなどで行っていただければ大丈夫です〜
