### ISSUE TITLE
Webアプリケーションのプラクティスの参考サイトのリンクが切れている

### ISSUE THREAD

**Issue by chihaso** [fjordllc/bootcamp#1143]
## 概要

[Webアプリケーション：Sinatra を使ってWebアプリケーションの基本を理解する](https://bootcamp.fjord.jp/practices/157)プラクティスの、[はじめてのSinatra](https://www.slideshare.net/frog377/sinatra-44667587)のリンクが切れている。

## 再現手順

1. [Webアプリケーション：Sinatra を使ってWebアプリケーションの基本を理解する](https://bootcamp.fjord.jp/practices/157)にアクセス。
2. [はじめてのSinatra](https://www.slideshare.net/frog377/sinatra-44667587)をクリック。
3. 404が返る。

## 期待される振る舞い

目的のページが表示される。

## スクリーンショット

<img width="1440" alt="404_error__Page_Not_Found_" src="https://user-images.githubusercontent.com/48672932/65562725-523d4380-df82-11e9-9d87-9bc4e9b1fdef.png">

## 環境
 - OS: macOS Mojave 10.14.6
 - ブラウザ: chrome
 - バージョン: 76.0.3809.132

**Comment by ima1zumi** [comment]
解決済のためCloseします。
