### ISSUE TITLE
書籍のシール一括印刷したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1145]

**Comment by s4na** [comment]
## 作業リスト

- [ ] QRコードを複数画面表示できるようにする
- [ ] QRコードを改行できるようにする
- [ ] QRコードを選択できるようにする

**Comment by s4na** [comment]
@komagata 
質問です！

1. いままでQRコードの印刷は`admin/books/books_id/qrcode`だったのですが、これからは複数選択での印刷が前提となりそうなので（1毎であっても選択してから印刷するイメージ）、`admin/qrcodes`に全部移行したいと思うのですがよろしいでしょうか？
2. 上記1の場合、`qrcode.XXX`は全て、`qrcodes.XXX`ににリネームして作成してもよろしいのでしょうか？
（例えば`qrcode.sass`は`qrcodes.sass`にリネーム）
3. QRコードの印刷時、印刷指定したいQRコードはgetのクエリパラメータにIDを追加するのか、postに持たせるのかどちらがWeb開発では一般的なのでしょうか？

QRコードを複数表示させるというイメージであればgetだと思うのですが、QRコードが複数表示される画面を生成するというイメージであればpostなのかなと思います。

**Comment by komagata** [comment]
@s4na 

> 1

他にもQRコードがあるかもということを考えると（例えばネームカードとか）、`/books/qrcodes`とかの方がいいかもです。

> 2

はい。

> 3. QRコードの印刷時、印刷指定したいQRコードはgetのクエリパラメータにIDを追加するのか、postに持たせるのかどちらがWeb開発では一般的なのでしょうか？

どちらでもなく、全て印刷するならパラメーターは必要ないかもです。

> 画面を生成するというイメージであればpostなのかなと思います。

画面を生成するというイメージだと全てのWebページがPOSTになってしまうのでGETだと思います。

**Comment by s4na** [comment]
@komagata 
ありがとうございます！

> どちらでもなく、全て印刷するならパラメーターは必要ないかもです。

把握しました
