### ISSUE TITLE
Github を GitHub Projects に変更したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1147]

**Comment by s4na** [comment]
@machida 
名称に関して質問です！

> Github を Github Projects に変更したい

とありますが、正式名称はGitHubであり、bootcampもそうなっていたので、変更する名称はGitHub Projectsにしてよろしいでしょうか？

**Comment by machida** [comment]
@s4na ごめんなさい、`GitHub Projects` でお願いします！！

**Comment by s4na** [comment]
@machida 
かしこまりました😊
