### ISSUE TITLE
座席予約を管理したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1148]
まず運用スタートできる最小限を目指す。
機能追加などは別Issue。

## 作るもの

- 席
  - 席のCRUD（管理者画面で管理者だけがいじれる）
- 予約（ログインユーザーのみ）
  - 予約の作成
  - 予約の編集
  - 予約の削除
  - 予約の一覧

## 細かい仕様

- 一ヶ月先まで登録できる。

**Comment by s4na** [comment]
## 作業工程

- [ ] 座席・予約URL決定
- [ ] 座席CRUD作成
- [ ] 予約CRUD作成
- [ ] 座席テストデータ作成
- [ ] テスト作成
- [ ] 予約のValidation作成

**Comment by s4na** [comment]
@machida 

確認させてください！

画面イメージはこういう感じで進めてよろしいでしょうか？
※色などは他の画面に合わせて適宜修正します

<img width="548" alt="スクリーンショット 2019-10-16 18 06 29" src="https://user-images.githubusercontent.com/42843963/66904823-b746ff00-f03f-11e9-853b-ed7f4f9c835c.png">

**Comment by machida** [comment]
予約ボタンがあるよりも、テーブルのマスをクリックすると、日付と席名が選択されてるフォームに飛ぶのがいいですね、
