### ISSUE TITLE
お知らせの投稿を削除した場合はそれの通知も削除されてほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1155]
通知テーブルのURLをみて、削除したお知らせと一致するものを削除する。

既に提出物の削除で同じことをやっているので参考にする。

**Comment by s4na** [comment]
## 作業
- [ ] 本番での確認

**Comment by komagata** [comment]
@s4na 本番環境で動作することを確認しました。ありがとうございます。
