### ISSUE TITLE
Adminメニューにスポンサーウィッシュリストのリンクを置きたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1156]
アンカーテキスト: ウィッシュリスト
リンク先: https://www.amazon.jp/hz/wishlist/ls/3I571CQISBFR6?ref_=wl_share
target_blank を付ける。

ここの下から二番目に配置。
![image](https://user-images.githubusercontent.com/168265/66453479-711df880-ea9f-11e9-9425-516e6e59af88.png)

**Comment by wawawatataru** [comment]
@komagata 
本番環境でご確認をお願いします 🙇‍♂️

**Comment by komagata** [comment]
@wawawatataru 本番環境で動作していることを確認しました。ありがとうございます。
