### ISSUE TITLE
対応カードブランドを表記したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1160]
対応カードブランド：Visa、Master、Diners、Amex

↑という表記をカード登録画面とカード編集画面に追加する。

デザインも必要なのでそこは@machidaと相談してやってもらう。

**Comment by wawawatataru** [comment]
@machida 
対応カードブランドの表記ですが、どこに表示すればよいでしょうか。

* フォームのラベル
* フォームの下
* `notice`の中
かなと考えてます。

![貼り付けた画像_2019_10_09_17_33](https://user-images.githubusercontent.com/2524168/66465170-522d5f80-eabb-11e9-8a0d-f1762e2b2285.png)

**Comment by wawawatataru** [comment]
@machida 
こちらってどうでしょう  🤔

**Comment by wawawatataru** [comment]
フォームのラベルに追加する

**Comment by wawawatataru** [comment]
本番環境で確認しました 👌
