### ISSUE TITLE
何の課題の提出物を提出したかわかるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1165]
![image](https://user-images.githubusercontent.com/168265/66792627-8b8b2280-ef34-11e9-812f-f16ac3bee3de.png)

この部分。

**Comment by wawawatataru** [comment]
@komagata 
本番で確認をお願いします🙇‍♂️

**Comment by komagata** [comment]
@wawawatataru 本番環境で動いていることを確認しました。ありがとうございます。
