### ISSUE TITLE
ユーザーに読み仮名の項目を追加したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1172]
必須

**Comment by wawawatataru** [comment]
@machida 
何点か質問させてください。
* ふりがなは「ひらがな」のみで問題ないでしょうか。
* 下記画像のテキストで指定があればお願いします

<img width="575" alt="貼り付けた画像_2019_10_17_9_52" src="https://user-images.githubusercontent.com/2524168/66969277-f6b72f00-f0c3-11e9-9b7f-0f72c7278dac.png">

* プロフィール画面にもふりがな載せたほうがいいでしょうか
  * 載せる場合は下記画像のフルネームの下？
<img width="459" alt="komagataのプロフィール___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/2524168/66969409-58779900-f0c4-11e9-89dc-03fe17b118cd.png">

**Comment by wawawatataru** [comment]
@machida 
確認をお願いします。
* フォームのラベルや補足テキストは下記画像で問題ないでしょうか。
<img width="601" alt="貼り付けた画像_2019_10_18_11_31" src="https://user-images.githubusercontent.com/2524168/67061324-ed4cc600-f19a-11e9-9cd4-0e07dbef6423.png">

* プロフィール画面に読み方は表示して問題ないでしょうか。
(CSSの`h2.user-profile__full-name`と`h2.user-profile__kana-full-name`(追加分))の調整が必要になりそうです。)
<img width="443" alt="komagataのプロフィール___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）-3" src="https://user-images.githubusercontent.com/2524168/67061347-02295980-f19b-11e9-8412-30837ebd7c7b.png">

**Comment by machida** [comment]
読み方は表示して大丈夫です。とりあえずはユーザーの個別にだけ出しましょう。一覧には不要です。出す場所は今のところで大丈夫です。ふりがなを出す準備はしてなかったので、僕が対応します。一旦コードだけレビューをもらってください。

**Comment by wawawatataru** [comment]
![image](https://user-images.githubusercontent.com/2524168/68274258-f818bd80-00ab-11ea-9009-f49bf2c11121.png)
本番で確認しました!!
