### ISSUE TITLE
住んでいる都道府県を追加したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1173]
非必須

jp_prefecture gemが便利

**Comment by wawawatataru** [comment]
@machida 
何点か質問させてください。
1. 都道府県の項目はどこにするか（現状「プラグラミング経験」の下に追加）
1. プルダウンの下の文言はどうするか（現状、以下の文言 : 都道府県を選択すると就職活動時に企業紹介の目安となります。現在のお住まいと就職活動をする地域が異なる場合はお知らせください。）
1. ユーザープロフィールには非表示で問題ないか
![image](https://user-images.githubusercontent.com/2524168/66932434-921fb400-f072-11e9-8d37-8c5f477a9b32.png)

**Comment by machida** [comment]
> 1. 都道府県の項目はどこにするか（現状「プラグラミング経験」の下に追加）

- 主な学習場所の下にお願いしたいです。
- ラベルを「都道府県」 -> 「お住まいの都道府県」にしていただきたいです。

> 1. プルダウンの下の文言はどうするか（現状、以下の文言 : 都道府県を選択すると就職活動時に企業紹介の目安となります。現在のお住まいと就職活動をする地域が異なる場合はお知らせください。）

- 就職先企業の紹介やテック系イベントの紹介時の参考にします。この情報は他のフィヨルドブートキャンプ参加者にも公開されますが、選択必須ではありません。

> 1. ユーザープロフィールには非表示で問題ないか

これは表示しましょう。近くに住んでる他のブートキャンプ生がいたら、一緒にイベントに参加できたりするので（お互い誘い合ったりできる）。

**Comment by wawawatataru** [comment]
@machida 
ありがとうございます 😺
諸々修正しますー

**Comment by wawawatataru** [comment]
@machida 
たびたびすみません。
* プロフィールに表示する位置どこがいいでしょうか。
* プロフィールに表示する際は「お住いの都道府県」だと冗長な気がするので、プロフィールの表示は「都道府県」のほうがいいですかね？

![image](https://user-images.githubusercontent.com/2524168/66972282-1d2e9780-f0cf-11e9-9469-db488ab9a476.png)

**Comment by machida** [comment]
いえいえ、何度でも全然大丈夫ですー

> プロフィールに表示する位置どこがいいでしょうか。

これ迷いますねー。。。
とりあえず今の位置でお願いしたいです。

> プロフィールに表示する際は「お住いの都道府県」だと冗長な気がするので、プロフィールの表示は「都道府県」のほうがいいですかね？

はい！都道府県でお願いしたいですー

**Comment by wawawatataru** [comment]
@machida 
ありがとうございます。
承知しましたー!!👌

**Comment by wawawatataru** [comment]
本番で確認できました
<img width="419" alt="スクリーンショット 2019-10-23 20 54 24" src="https://user-images.githubusercontent.com/2524168/67390333-70c14980-f5d7-11e9-9b33-22b3773fcbe9.png">
