### ISSUE TITLE
みんなのブログを外す

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1179]
- [x] `/feeds` `feeds.atom`関連のコードを消す
- [x] atomフィードを表示するのに使っていた（feedjira）gemを消す

**Comment by wawawatataru** [comment]
ユーザー情報からはRSSフィードの入力欄は外さない

**Comment by wawawatataru** [comment]
`/feeds`が404になっていること
`head`タグ内にあった不要な記述が消えているのを確認しました。
![Uploading スクリーンショット 2019-10-23 21.59.27.png…]()
