### ISSUE TITLE
アンチハラスメントポリシーのページを用意する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1180]
仮でRubyKaigi関連のサイトからコピーしておく。後で他の人が正式な文章とデザインを入れます。

urlはcoc。home_controllerのメソッドとして用意する。

- [x] ページを用意する
- [x] トップページ（/welcome）のフッターにリンクを用意する

**Comment by shoynoi** [comment]
本番環境で、ページの確認ができたのでCloseしました
