### ISSUE TITLE
入力欄がないのに「現在の所属組織を入力してください」と表示される

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1190]
[\[001\] 学習の準備 \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/reports/7867)

こちらで報告いただきました。

**Comment by s4na** [comment]
下記コードが原因っぽいです

```
module RequiredFieldsHelper
  def required_fields

  # 中略
    if !current_user.organization?
      messages << "#{link_to "現在の所属組織を入力してください。", edit_current_user_path, class: "card-list__item-link"}".html_safe
    end
```

`organization`を全コード検索しても、Viewで使っているところがなさそうなので、今は使われていない機能なのかもしれません

もしそうであれば、関連する箇所（organizationを使っているところは他にも何箇所かありそう）を消すだけで解決できそうです

**Comment by komagata** [comment]
@shoynoi こちら本番にアップして確認してOKだったらIssueもCloseお願いします。

**Comment by shoynoi** [comment]
失礼しました。[[001] 学習の準備 | FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/reports/7867)のコメント欄でバグの報告を頂いた方から修正されたとの確認がとれたのでCloseします
