### ISSUE TITLE
日報の編集でエラー

### ISSUE THREAD

**Issue by sdk-quadra** [fjordllc/bootcamp#1191]
## 概要
自分の日報の「プラクティス」を修正して保存しようとすると、herokuのエラー画面が出る。
（以下スクリーンショット参照）

## 再現手順
1.https://bootcamp.fjord.jp/reports/7877 にアクセス
2. 「プラクティス」の内容を修正（何でもいい）
3. 保存すると、1分ほど経った後、エラー画面

## 期待される振る舞い
保存時にエラー画面が出ない。

## スクリーンショット
<img width="1065" alt="スクリーンショット 2019-10-28 8 31 35" src="https://user-images.githubusercontent.com/39234092/67643773-5af8af00-f95e-11e9-813d-790e7ad4a81e.png">

## 環境

 - OS: macOS High Sierra 10.13.2
 - ブラウザ: [chrome]
 - バージョン: [77.0.3865.120（Official Build） （64 ビット）]

**Comment by ima1zumi** [comment]
herokuではなくなったのでCloseします。
