### ISSUE TITLE
提出物のタイトルタグを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1192]
![image](https://user-images.githubusercontent.com/168265/67646344-06126400-f971-11e9-81cc-f42d64d254b3.png)

何の提出物かを出す（課題名を出す）。

**Comment by komagata** [comment]
@shoynoi こちら本番にアップして確認してOKだったらIssueもCloseお願いします。

**Comment by shoynoi** [comment]
本番環境で適切に変更されていることを確認しましたのでCloseします

![image](https://user-images.githubusercontent.com/37890305/69061333-4179ed00-0a5c-11ea-8b1e-3a8c9d911f61.png)
