### ISSUE TITLE
日報で1日の学習時間が24時間以上となる場合がある

### ISSUE THREAD

**Issue by imaizumimr** [fjordllc/bootcamp#1194]
## 概要
学習時間：00:15〜01:15で日報を保存したところ、学習時間が25時間と表示された。
以下の手順を行って解消した。その後同様の操作を行ったがバグは再現しなかった。

## バグ発生〜解消した手順
1. 学習時間：00:15〜01:15で日報を保存すると、学習時間が25時間と表示された
ユーザーページから見ても学習時間が+25時間されていた
2. 学習時間を修正しても24時間＋登録した時間で表示された
例：00:15〜00:30で登録すると、24時間30分と表示される
3. 学習時間を全削除してWIPで保存ボタンを押した
4. 0時間では保存できない旨のメッセージが出力された
5. 00:15〜01:15で学習時間を登録
6. 学習時間が1時間となった
その後バグは再現できなかった

## 期待される振る舞い
正しい学習時間が表示される。

## 環境
- OS: MacOS Catalina 10.15
- ブラウザ: chrome
- バージョン: 77.0.3865.120

**Comment by shoynoi** [comment]
#1267 との関連issueについて、本番環境での修正が確認できたのでcloseしますー
