### ISSUE TITLE
日報一覧が投稿日時順になって欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1196]

**Comment by komagata** [comment]
@shoynoi こちら本番にアップして確認してOKだったらIssueもCloseお願いします。

**Comment by shoynoi** [comment]
こちら、日報を新規作成して学習日順でかつ作成日時順であることを確認しましたので、Closeします

![image](https://user-images.githubusercontent.com/37890305/69209929-6aa19700-0b9c-11ea-8e25-98d0f0e33252.png)
