### ISSUE TITLE
ユーザー名ホバーで氏名が出て欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1216]
氏名を確認するためだけにユーザーページに行くことが非常に多いため。

**Comment by machida** [comment]
まずは、title タグに 名前を入れるで対応

**Comment by komagata** [comment]
@machida 最終形もそれ想定なのでだいじょうぶです〜

**Comment by machida** [comment]
```slim
= link_to "", class: "クラス名", title: "ここに氏名" do
    | あああああああ
```

こんな感じ

**Comment by env-gp** [comment]
minitestで詰まっていることがあり相談させてください。
link_toにtitleタグを付けてtooltipは出るようになりました。
app/views/reports/show.html.slim
```
          .thread-header__upper-side
            = link_to @report.user, class: "thread-header__author", title: @report.user.full_name do
              = @report.user.login_name
```

以下のテストを追加したのですが、エラーになります。
/test/system/reports_test.rb
```
  test "hover fullname" do
    user   = users(:komagata)
    report = user.reports.first
    visit report_path(report)
    find(".thread-header__author").hover
    sleep 2.0
    assert_text user.full_name
  end
```

`HEADED=1 bin/rails test test/system/reports_test.rb`で目視確認してもtooltip自体は出ています。

エラー内容
```
Failure:
ReportsTest#test_hover_fullname [/Users/komatsu.hiroyuki/fjordllc/bootcamp/test/system/reports_test.rb:314]:
expected to find text "Komagata Masaki" in "お知らせ\nプラクティス\n5\n日報\n8\n提出物\n7\nQ&A\nDocs\n席予約\nユーザー\n管理者\nすべて\nお知らせ\nプラクティス\n日報\nQ&A\nDocs\nAdmin\nMenu\n4\n通知\n2017年01月03日 の日報\n日報作成\n日報一覧\nkomagata\n2017年01月03日 の日報\n学習週3日目\n確認済\n2019/12/11\nmachida\nWatchする\nRaw\n今日は CSS の勉強をしました。デザイン難しい。。。\n内容修正\nコピー\n削除\n日報の確認を取り消す\n前の日報\n日報一覧\nコメント\nkomagata\n2019年12月11日(水) 11:07\nどういう教材がいいんでしょうかね？\n👍1\n❤️2\n編集\n削除\nmachida\n2019年12月11日(水) 11:07\nhttps://github.com/fjordllc/csstutorial/tree/master とかですかねー。\nコメント\nプレビュー\nコメントする\n作業週1日目\n2019年12月11日\n学習週1日目\n2019年12月11日\nWIP\nWIPの日報\n2019年12月11日\n作業週2日目\n2019年12月11日\nテストの日報\n2019年12月11日\n学習週2日目\n2019年12月11日\n研修の日報\n2019年12月11日\n学習週3日目\n2019年12月11日\n初日報です\n2019年12月11日\n学習週3日目\n2019年12月11日\nFjord Bootcamp で Bootstrap のバージョン更新\n2019年12月11日\nテストの日報\n2019年12月11日\nもっと見る". (However, it was found 1 time including non-visible text.)
```

[こちら](https://www.rubydoc.info/github/jnicklas/capybara/Capybara/Minitest/Assertions#assert_field-instance_method)を参考にinstance_methodを色々試してみたのですが、解決しませんでした。


そもそもtooltipをテストすることはできるのでしょうか。

**Comment by komagata** [comment]
@env-gp コードについて聞く場合は、WIPでPRを作ってそこで聞くのが手っ取り早いかもです。

今回は重大な機能では無いのでテストしなくても大丈夫です。

ただ`tooltip capybara`で検索してみると解決方法が色々あるみたいです。

[tooltip capybara \- Google 検索](https://www.google.com/search?rlz=1C5CHFA_enJP723JP725&sxsrf=ACYBGNS3yvCym-arTASIHBkVzNsKj2g0JA%3A1576031826787&ei=UlbwXYLSL5GwmAXInYZY&q=tooltip+capybara&oq=tooltip+capybara&gs_l=psy-ab.3..0i8i30.45209.49076..49309...0.0..0.153.1952.3j14......0....1..gws-wiz.......35i39j0i67j0i4j0i131i67j0i131j0j0i203j0i30j0i5i30j0i19j0i13i30i19j0i13i5i30i19.wDgfA5XhzaA&ved=0ahUKEwiCw8KJyKzmAhURGKYKHciOAQsQ4dUDCAs&uact=5)

**Comment by env-gp** [comment]
@komagata
返信いただきありがとうございます。Draft Pull Requestの運用、勉強になりました。
今回はテストなしで対応します。
