### ISSUE TITLE
カナが空だと退会できない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1226]
<img width="1158" alt="screenshot2" src="https://user-images.githubusercontent.com/16577/68440360-2a423080-020e-11ea-969e-06b8fe122992.png">

**Comment by wawawatataru** [comment]
@komagata 
本番でご確認をお願いします。

**Comment by s4na** [comment]
@komagata

GitHub上で担当状況がわかりにくい状態になっていたので、 Assigneesに追加させていただきました。

**Comment by komagata** [comment]
修正済み。
