### ISSUE TITLE
全体の進捗の%に含む、含まないをそれぞれのプラクティスで設定したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1233]

**Comment by chihaso** [comment]
@komagata PR #1479のレビューありがとうございます！😆
本件、本番環境での確認は管理者権限が必要となります。
よろしければ、ご確認をお願いいたします。

**Comment by komagata** [comment]
@chihaso 本番環境で動作することを確認しました。
（そして就職活動・発展編は進捗に含まないように設定しました）
