### ISSUE TITLE
イベント出欠席管理

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1236]

**Comment by shoynoi** [comment]
@komagata @machida イベント出欠席管理機能についていくつか質問があります。

機能を作成するに当たり、以下のようにテーブルを作成しようと考えています。

Event

| カラム名 | 役割 | データ型 | NULLを許可するか | デフォルト値 |
| --- | --- | --- | --- | --- |
| title | イベント名 | string | false | なし |
| description | 説明文 | text | false | なし |
| location | 開催場所 | string | false | なし |
| capacity | 定員 | integer | false | なし |
| start_at | 開始日時 | datetime | false | なし |
| end_at | 終了日時 | datetime | false | なし |
| open_start_at | 募集開始日時 | datetime | true | なし |
| open_end_at | 募集終了日時 | datetime | true | なし |
| user_id | 主催者 | integer | false | なし |
| fee | 参加費 | integer | false | 0 |

Participation

| カラム名 | 役割 | データ型 | NULLを許可するか | デフォルト値 |
| --- | --- | --- | --- | --- |
| user_id | 参加者 | integer | false | なし |
| event_id | 参加イベント | integer | false | なし |

- 募集開始日時/終了日時や参加費は現段階で必要でしょうか
    - 参加費についてはもし徴収するようなイベントがある場合、支払うユーザーとそうでないユーザーを分ける枠を設ける必要があると考えています
- キャンセルについてはどう扱うべきでしょうか
    - connpassのように参加者・補欠者・キャンセルしたユーザーが表示されるように実装すべきでしょうか
- 通知機能についてもこのissueに含まれているという認識で良いでしょうか
    - その場合、会社説明会等の受講生のみに通知してほしいイベントがあると思うので、以前七五三さんが実装されたような通知するターゲットを分けるような機能が必要になると思うのですが、いかがでしょうか

**Comment by komagata** [comment]
@shoynoi 

> 募集開始日時/終了日時や参加費は現段階で必要でしょうか

はい

> 参加費についてはもし徴収するようなイベントがある場合、支払うユーザーとそうでないユーザーを分ける枠を設ける必要があると考えています

feeはいらないです。

> キャンセルについてはどう扱うべきでしょうか

とりあえず、キャンセルは応募自体を削除でOKです。

> 通知機能についてもこのissueに含まれているという認識で良いでしょうか

イベントがある場合、お知らせで知らせるのでまずは通知機能は無しで良いです。

**Comment by shoynoi** [comment]
ありがとうございます!
この方向で進めていきたいと思いますー
