### ISSUE TITLE
長文のコメントを編集するときにテキストエリアの縦幅が狭い

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1241]

**Comment by pat1543** [comment]
## 進捗報告
- textareaの高さを自動で広くしているのは[textarea-autosize](https://github.com/javierjulio/textarea-autosize)というライブラリであることがわかった。
- textareaのREADMEを読むと、もしSPAのようにページがロードされた後に値が与えられる場合はtriggerでinputイベントを発火させないといけない、というようなことが書かれていたので``$('textarea').textareaAutoSize().trigger('input')``のように書いてみたが、何も変わらなかった。
- 編集ボタンを押した後に、textareaを下に動かすと全て表示されるので、編集ボタンを押した後にfocusを当てればいいのでは、と考え試してみたが、focusが当たるだけでダメだった。最終行にfocusを当ててもダメだった。

## 質問
- DOMの操作で他に考えられるものはありますでしょうか？

**Comment by pat1543** [comment]
@komagata 
質問のご確認、お忙しくないときにお願いいたします。

**Comment by pat1543** [comment]
## その後試したこと
- とりあえず問題を分割して、まずは編集ボタンを押したときにそのコメントのtextareaにfocusが移るようになることを目指した。(focusは発火に成功していることがわかりやすいので)
- 編集ボタンを押すとeditCommentメソッドが呼ばれるようになっていたので(``@click="editComment"``)、このメソッド内に``${要素}.trigger('focus')のようなコードを書こうとした。
- まず``${'textarea'}.trigger('focus')``とやってみたが、こうすると新規コメント入力欄にfocusが当たってしまった。どうしてtextareaが一意に新規コメント欄として解釈されるのかがイマイチよくわかっていません。
![image](https://user-images.githubusercontent.com/50227745/74396883-aa53e400-4e56-11ea-89a8-097081fa56bc.png)

- そこで、編集コメント欄を指定しようとしましたが、以下のことを試してもfocusが移らなかった。他にもクラス指定やid指定など試しましたが、どれもうまくいかなかった。
 - ``$('.comment-id-1064126235').trigger('focus')``

![image](https://user-images.githubusercontent.com/50227745/74396731-403b3f00-4e56-11ea-97ea-41c379850d4b.png)

## お聞きしたいこと
- editCommentメソッドに手を加える、という方向性で合っているのでしょうか？
- 編集コメント欄にfocusが移らない理由として、考えられることはありますでしょうか？

よろしくお願いいたします。

なお、こちらですとクローズですので、パブリックなQ&Aのほうに書いた方がいいようでしたら、そちらに書き直します。

**Comment by pat1543** [comment]
setTimeoutを指定することで成功しました！
動的に生成させる要素の場合、指定のタイミングを遅らせてあげないと認識してくれないようでした。
