### ISSUE TITLE
フォームのヘルプテキストが適切ではない？

### ISSUE THREAD

**Issue by tosite** [fjordllc/bootcamp#1251]
## 概要

🍠 ユーザー登録時はパスワードが必須なので `パスワードを変更する場合のみ入力してください。` というメッセージは表示しないほうがいいのでは？と思いました。

## 再現手順

1. `/users/new` へアクセスする

## スクリーンショット

![image](https://user-images.githubusercontent.com/24952964/69424933-2fa28d80-0d6d-11ea-8797-29b8b60aaae4.png)

**Comment by tosite0345** [comment]
https://github.com/fjordllc/bootcamp/pull/1252 にて対応中。

**Comment by machida** [comment]
対応ありがとうございました！！
Closeし忘れていたので、今しましたー
