### ISSUE TITLE
何人かのユーザーだけ、アイコン画像が表示されない

### ISSUE THREAD

**Issue by s4na** [fjordllc/bootcamp#1299]
## 概要

何人かのユーザーだけ、アイコン画像が表示されない

## 再現手順

1. /reportsにアクセス。
2. アイコン画像が表示されない

デベロッパーツールのエラーメッセージ
> Failed to load resource: the server responded with a status of 404 ()

## 期待される振る舞い

みんなのアイコンが見られるようになっている

## スクリーンショット

<img width="1548" alt="スクリーンショット 2019-12-11 15 47 05" src="https://user-images.githubusercontent.com/42843963/70598237-ba203380-1c2d-11ea-833b-7a46b32dd92c.png">

**Comment by komagata** [comment]
すみません、画像リサイズに伴う予定していた動作でした。もう表示されていると思います。
