### ISSUE TITLE
領収書をBootCampで自動生成したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1326]

**Comment by komagata** [comment]
:memo: Stripeで自動て飛んでいる領収書に会社名を反映させられれば解決するかも

**Comment by machida** [comment]
参考: https://support.stripe.com/questions/jp-email-receipts

**Comment by imaharu** [comment]
`https://dashboard.stripe.com/settings` の 「アカウントの詳細」から公開ビジネス情報を編集すればOKなはずです...

<img width="1108" alt="スクリーンショット 2021-02-02 午後8 07 35" src="https://user-images.githubusercontent.com/23719154/106592038-59bb2680-6592-11eb-885e-90123e6936b9.png">
<img width="650" alt="スクリーンショット 2021-02-02 午後8 06 54" src="https://user-images.githubusercontent.com/23719154/106592039-5aec5380-6592-11eb-8734-40adf9430bab.png">

**Comment by komagata** [comment]
@imaharu 情報ありがとうございます。

現状でも上記の領収書は送られているのですが、研修に使ってるユーザーのためにStripeに会社名を登録させて領収書にも反映させたいと思っております〜
