### ISSUE TITLE
httpsを強制した方がよい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1349]
## 概要

「あなたがウォッチしている【 「JavaScript環境の設定」の提出物 】にコメントが投稿されました。」のような通知メール内に張られているリンクが非SSL（http）になっている。
このリンクをクリックするとそのまま非SSLで接続される。

以下の対応をして常にSSL接続にした方がよさそう。

- メール内のリンクをhttpsにする
- httpでアクセスされたら強制的にhttpsに変更する

## 再現手順

1. メール内のリンクをクリックする
2. ブラウザのURL入力欄を確認する

## 期待される振る舞い

URLがhttpsになっている（🔒アイコンが表示される）

## スクリーンショット

<img width="382" alt="Screen Shot 2020-02-06 at 8 16 04 1" src="https://user-images.githubusercontent.com/1148320/73891981-f0d69b00-48b8-11ea-8cce-1a76b655c14d.png">

## 環境

 - OS: macOS 10.15.3
 - ブラウザ: Chrome 
 - バージョン: 80

**Comment by machida** [comment]
@JunichiIto ご指摘ありがとうございます！助かります🙏対応します！！

**Comment by JunichiIto** [comment]
修正されていることを確認しました！対応ありがとうございました〜。
