### ISSUE TITLE
全体的に画面遷移が重たい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1357]
Chromeで見ると、どのページも表示に1.5秒〜4秒ぐらいかかっていて、サクサク動いているとは言いがたい。
ページ移動はそれなりの頻度で行うので、平均1秒以下になると嬉しい。

が、もしHerokuを使っていたら限界があるかな〜？
（AWSのTokyoリージョンとかにすれば、それだけでかなり改善されそうですが）

<img width="944" alt="Screen Shot 2020-02-08 at 8 38 44" src="https://user-images.githubusercontent.com/1148320/74073819-0a115000-4a4f-11ea-8622-e81f8674a3a4.png">

**Comment by komagata** [comment]
時間があるときにGoogle Cloud Runに移行したいと思っています〜

**Comment by JunichiIto** [comment]
> 時間があるときにGoogle Cloud Runに移行したいと思っています〜

期待しています！😆

**Comment by JunichiIto** [comment]
これ、チリツモでメンターも生徒さんもかなり時間の損失がありそう、てか、結構日常的にストレスフルなので早めに対応してもらえると嬉しいです〜。

**Comment by komagata** [comment]
こちらプラスビジョンさんに依頼したところです。

**Comment by bluerabbit** [comment]
町田さんから`https://bootcamp.fjord.jp/practices/:id/products`をよく使うけど重いと聞いた

**Comment by bluerabbit** [comment]
`/announcements/:id`で同じリクエストが複数回実行されている

<img width="1020" alt="SS 2020-08-17 13 34 32" src="https://user-images.githubusercontent.com/45971/90479667-fd8e5280-e169-11ea-97c3-c48fa02173da.png">

**Comment by bluerabbit** [comment]
ごめんなさい。私がクローズ忘れてたようです 🙇
