### ISSUE TITLE
提出物一覧で誰がコメントしたかわかるようにしたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1363]
（メンターとしてのリクエストです）

## 困っていること

現状、提出物一覧はコメント数が表示されるが、誰がコメントしたかはわからない。

<img width="505" alt="Screen Shot 2020-02-11 at 9 53 45" src="https://user-images.githubusercontent.com/1148320/74203927-95d7e600-4cb4-11ea-8404-4151e99cab80.png">

上の画像に表示されている「コメント数=1」は、受講生本人が「提出しました」のコメントを入れたものである。

メンターとしては「他のメンターがまだコメントしていない提出物」をチェックしたいが、コメント数だけだと受講生本人のコメントか、メンターのコメントか、区別が付かない。

## 改善案

現状「確認したメンター」として表示されているアイコンを、コメントした人のアイコンに変える。

<img width="485" alt="Screen Shot 2020-02-11 at 9 59 36" src="https://user-images.githubusercontent.com/1148320/74204135-4c3bcb00-4cb5-11ea-9d28-66f880104f26.png">

「確認したメンター」はスタンプを見ればわかるので、「確認したメンター」のアイコンは必ずしも必要ない。

ただし、この場合、アイコンの意味が変わってしまう問題点がある。
他によいアイデアがあれば、この解決策にはこだわらない。

**Comment by JunichiIto** [comment]
これに加えて、最後にコメントしたユーザーと最後にコメントした日時もわかると嬉しいです。

たとえば、最後にコメントしたユーザーがメンターであれば「たぶん受講生の修正待ちだな」という推測ができます。
反対に受講生であれば「メンターの確認待ちだな」と推測できます。

また、最終コメント日時がたとえば1週間前になってると、「あれ、この提出物はやりとりが止まったままになってるぞ」と気づけます。
1〜2日前であれば「ちょっと忙しいのかな？まだ待っても良さそう」と思えます。

提出物一覧、メンターからするとちょっとかゆいところに手が届いていない感が強いので、早めに対応してもらえるとありがたいです 🙏

**Comment by JunichiIto** [comment]
1つ上のコメントと少し重複しますが、やはり最終コメント日時は表示してほしいです。
たとえば、以下の赤線の提出物は2月8日提出されています。
今日は4/11なので、ずっと放置されているのかな？と思いましたが、中を覗いてみると最新のコメントは4/9でした。つまり放置されていませんでした。

<img width="1447" alt="Screen Shot 2020-04-11 at 10 32 37" src="https://user-images.githubusercontent.com/1148320/79032285-39277780-7be0-11ea-8e1d-817d6fa79eb8.png">

最終コメント日時が表示されていれば、中を覗かなくても放置されてないことがわかるので、非常に助かります 🙏

**Comment by hasehiro25** [comment]
@JunichiIto 
こちらの実装に取り掛かってます@hasehiro25です
機能の追加に時間がかかってしまい申し訳ありません🙇‍♂️

一応最終的に以下のような画面になる予定です。
<img width="1339" alt="スクリーンショット_2020-04-11_11_58_32" src="https://user-images.githubusercontent.com/10154448/79034641-8dd3ee00-7bf2-11ea-8d92-c153a663acc4.png">

- 最終コメントが投稿された日付を表示する
- 「確認したメンターのアイコン」をなくし、「コメント投稿した人のアイコン」を投稿順に並べて表示する
  - コメントに誰が参加して誰が最後にコメントしたかを明確にするため
  - 確認したメンターはスタンプで把握できるため
  - 同一ユーザーが複数コメントした場合、一番新しいコメントのみを参照して表示の重複をなくす

アイコン表示も、誰が提出物に関わったかわかりやすくするために今回同時に実装しました。
また、全く同じ機能をコメント一覧でも導入する予定です。

現在実装そのものは完成しており、コードレビューとその修正が終わり次第、本番に反映できると思います。

もし何か要望、改善、気になる点がありましたらご指摘ください🙇‍♂️

**Comment by JunichiIto** [comment]
@hasehiro25 
> 機能の追加に時間がかかってしまい申し訳ありません

いえいえ、全然！ベストエフォートで大丈夫ですよ😄

スクショ見ました。これ、素晴らしいですね！！文句なしの出来かも！
リリースが待ち遠しいです😆

**Comment by hasehiro25** [comment]
@JunichiIto 
ありがとうございます🙇‍♂️

machidaさんのおかげで、すごいわかりやすいレイアウトに仕上がりました！
もうしばしお待ちをいただけますと👍
