### ISSUE TITLE
「役に立つ日報のやりとり」をいい感じに共有したい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1366]
ふわっとしすぎていて要件が固まっていませんが、こういうことが実現できたらいいな、と思います。

https://fjord.slack.com/archives/C024R13RP/p1581515607296700

> この日報でのやりとりがとても勉強になりました！
https://bootcamp.fjord.jp/reports/10520
こういう良い日報って自分が読んでラッキー、って終わってしまうことが多かったので、もっと色々な人が読めるように、良いと思った日報が共有できる仕組みがあると便利かなと思いました。
プラクティスごとに検索かけることが多いと思うので、いいねの数が多い日報ほど上に来るようにするなどすれば、救われる人も多くなるかも？
以上はただの感想ですので、読み流してくださって結構です〜。

頑張ってシステム化しなくても、最初は全員で「運用でカバー」みたいにしてもいいかもしれません。（役に立つと思ったら誰でもいいから都度Slackに貼り付ける、とか）

**Comment by komagata** [comment]
- リアクションが多いコメントを表示する何かを作る
- メンターだけが押せる「ピックアップ」ボタンをコメントにつけて、該当するプラクティスのページに、「ピックアップ一覧」を作る

とかかなぁ〜

**Comment by machida** [comment]
運用でカバー、役に立つ日報をプラクティスに貼るとかすると良さそうですね。

リアクションの多い順に並ぶのはいつか実装したいと考えてました。
リアクションが並び順に影響する機能が入ることで、役に立ったと思ったものに対してのリアクションが増えてコミュニケーションが活発になるのも期待したいです。

**Comment by komagata** [comment]
ただリアクション多い順にすると初日の多分日報が上の方にくるんですよね😅

**Comment by bluerabbit** [comment]
知り合いがこういうののランキングぽいものを出すときに下記の２つの軸でポイント付することで解決してるって話聞いたことありますね。

- いいね数でポイント付
- 作成日(新しさ）でポイント付

古くなるとポイントが減って上位には出にくくなるみたいな感じです。
もう一つ計算式の変数があった気がするけど 😅

**Comment by JunichiIto** [comment]
Discordの名作チャンネルで代用できてそうなのでclose
