### ISSUE TITLE
通知メールのリンクをクリックしたら、コメント欄まで画面をスクロールしてほしい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1367]
通知メール内の「この日報へ」ボタンをクリックしたときの挙動を変更したい

<img width="689" alt="Screen Shot 2020-02-13 at 10 12 46" src="https://user-images.githubusercontent.com/1148320/74392199-b2595700-4e49-11ea-8d47-714cedbf01d8.png">

- 現在：そのページの先頭を表示（なので、コメント欄までスクロールが必要）
- 改善後：最初からそのコメント欄までスクロール済み（なので、さっと返信がしやすい）

ただし、スクロールが手間で手間で仕方がない、というレベルではないので、優先度は低めでもいいかも。（でもさっと実装できるなら、対応してもらえると嬉しい）

**Comment by JunichiIto** [comment]
ブートキャンプのサイト上ではコメントまでスクロールできるようになったっぽいので、あとはメールのリンクを修正すれば実現可能かも？

例 https://bootcamp.fjord.jp/products/3477#comment_22337

**Comment by masamune17** [comment]
テスト状況
- [ ]日報へのコメント通知メール
- [ ]Q&Aへの回答通知メール
- [ ]回答したQ&Aがベストアンサーに選ばれた時の通知メール
- [ ]watch中のコンテンツに対するコメント通知メール
