### ISSUE TITLE
ブートキャンプのURLを貼ったときにいい感じにプレビューしたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1369]
https://fjord.slack.com/archives/C024R13RP/p1581559705309100 で書かれている内容です。

<img width="812" alt="Screen Shot 2020-02-14 at 11 21 30" src="https://user-images.githubusercontent.com/1148320/74495804-295f2000-4f1c-11ea-93a7-d6397fb887a7.png">

工数にもよりますが、実現できると楽しそうだな〜と思います。

**Comment by june29** [comment]
「実際に進めるとしたらどんな感じになるの？」をイメージしやすくなるように、先行事例を貼っておきます :memo:

Closedなesaの記事URLをSlackに貼ったら展開されるようにした
https://inside.pixiv.blog/fromatom/5684

**Comment by JunichiIto** [comment]
できたらいいな〜、と思うので残しておきます。

**Comment by Aseiide** [comment]
`#日報`ではこんなふうに出ているので、URLを共有したときに、種別(日報,提出物,Q&A)とタイトルがわかると良さそうです。
![スクリーンショット_2022-04-22_11_19_04](https://user-images.githubusercontent.com/45246171/164584015-c38997e8-be62-48e8-9c20-23c2169cd84d.png)
