### ISSUE TITLE
Adminでログインしたときに、プラクティス一覧のカテゴリーのそばにカテゴリー修正ページのリンクを置きたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1373]

**Comment by JunichiIto** [comment]
参考リンク
https://bootcamp.fjord.jp/reports/10579

**Comment by hasehiro25** [comment]
実装内容を忘れないようにするための個人メモです。
- 実装内容
<img width="1383" alt="スクリーンショット_2020-02-19_16_15_38" src="https://user-images.githubusercontent.com/10154448/74810845-99faa800-5333-11ea-813e-d6a83e57c9f7.png">

- リンク先画像
<img width="1402" alt="スクリーンショット 2020-02-19 16 15 51" src="https://user-images.githubusercontent.com/10154448/74810961-de864380-5333-11ea-82f1-f18b62421c63.png">
リンク先：　admin -> 管理ページ　-> カテゴリー -> 該当の鉛筆マーク
