### ISSUE TITLE
ヒストリバックで戻るとコメント入力欄に他人にコメントが入っている

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1374]
## 概要

ブートキャンプ内の外部リンクをクリックし、外部ページからブートキャンプへブラウザのヒストリバックで戻ると、コメント欄に他人のコメントが入っている。

## 再現手順

1. https://bootcamp.fjord.jp/products/3064 にアクセスする
2. ページ内のgistリンクをクリックする
3. gistからブートキャンプへヒストリバックで戻る
4. コメント欄に駒形さんのコメントがデフォルトで入力されている

## 期待される振る舞い

ヒストリバックで戻ったときはコメント入力欄が空のままになっている。

## スクリーンショット

![uIZZAqfMlL](https://user-images.githubusercontent.com/1148320/74692049-d097cc00-5228-11ea-921a-7c7c830451b6.gif)

## 環境

 - OS: macOS 10.15.3
 - ブラウザ: Chrome
 - バージョン: 80

**Comment by sanfrecce-osaka** [comment]
自分もさっきこれ踏みました
自分の場合はユーザー詳細ページに飛んだ後ヒストリバックで戻った際に発生したので外部ページかどうかは関係ないかもです 🤔

## 再現手順
1. https://bootcamp.fjord.jp/reports/10760 にアクセスする
1. リンクから https://bootcamp.fjord.jp/users/597 へ遷移
1. ヒストリバックで https://bootcamp.fjord.jp/reports/10760 に戻る
1. コメント欄に @s4na さんのコメント(最も古いコメント)がデフォルトで入力されている
1. リロードするとコメント欄は空になる
