### ISSUE TITLE
メールにSPF/DKIMを設定する

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1380]
現状ではSPF/DKIMを設定していないせいか、メール受信時に"via sendgrid.me"のような表示が出ている。

<img width="454" alt="Screen Shot 2020-02-19 at 9 52 49" src="https://user-images.githubusercontent.com/1148320/74791401-b11ea300-52fd-11ea-9c9f-a1488a301d55.png">

SPF/DKIMを設定すれば迷惑メール扱いされるリスクが多少減るので、以下の日報のように「メールが届かない」というトラブルも防げるかもしれない。（現時点では迷惑メール扱いされていた、という結論はまだ出ていないが）

https://bootcamp.fjord.jp/reports/10743

**Comment by komagata** [comment]
設定しました。
