### ISSUE TITLE
イベントで補欠から繰り上がったら通知が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1381]
- 繰り上がるタイミング
  - キャンセルが出た時
  - 定員が増えた時

通知は既にある通知の仕組みを使う。

**Comment by machida** [comment]
@NMP300 https://github.com/fjordllc/bootcamp/pull/1388 こちらのブランチからブランチを作ってこのブランチにPRをお願いします🙏

**Comment by NMP300** [comment]
@machida 承知しました🙇‍♂️

**Comment by komagata** [comment]
@koheitakahashi Issueの完了・Closeは本番にアップされて、本番上で動作確認が終わった時でお願いします〜

**Comment by koheitakahashi** [comment]
@komagata 
勘違いしてしまいました、すいません💦
issue再びオープンしました🙇‍♂️
