### ISSUE TITLE
turbolinks復活！turbolinks復活！turbolinks復活！

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1386]

**Comment by hasehiro25** [comment]
:memo:
一部Turbolinksで実装が難しいところがあるので導入を断念
WikiにDocを作って次取り掛かる人が実現できるよう記録を残す
- 何ができなかったかをまとめる
- どういう風に調べて、どういう理由でできかったをまとめる
  - こういうキーワードで調べ、こんな議論があったのでやらない方がよいなど）
