### ISSUE TITLE
リンク切れの有無を定期的にチェックする

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1396]
## 課題
たまにプラクティスでリンク切れが発生している。
（ここのissueでも"リンク切れ"で検索するといくつか過去のissueが上がってくる）
サービス提供者としては受講生から報告を受ける前に、検知して修正できるようにしておきたい。
（リンク切れがあると受講生のスムーズな学習を阻害する恐れがある）

## 解決策（案）
1日に一回程度、プラクティス内のリンクを検査し、もしリンク切れがあればメールで管理者に通知する。（リンク切れを効率良く検知し、修正できる仕組みになっていれば、解決策はなんでもOK）

**Comment by ima1zumi** [comment]
リンク切れチェッカーの運用が始まっていると思うので、こちらはCloseします〜
