### ISSUE TITLE
Markdown で チェックリストを使いたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1400]

**Comment by vinhactindi** [comment]
@machida 
明けましておめでとうございます！
こちらの新機能について聞きたいこと1点があります。
* プルリクに機能しましたが、Markdownのチェクリストは全部のマークダウンは必要ですか？今の導入した部分は`Announcement Answer Comment Page Report` です。（後：`Article Event Product Practice Work`）

**Comment by komagata** [comment]
:memo: Discord上で下記のように答えました。

「まずは`Report`と`Product`だけで良いです」
