### ISSUE TITLE
メンションをしてもリンクにならないユーザーがいる

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1418]
## 概要

コメント欄等でメンションをしてもリンクにならないユーザーがいる。
（英数字でないから？スペースが含まれるから？）

## 再現手順

1. https://bootcamp.fjord.jp/products/3002 にアクセスしてコメント欄を確認する。
2. 「@はるぐち　ゆうま」がリンクになっていない

## 期待される振る舞い

「@はるぐち　ゆうま」がリンクになっている。
（またはユーザー名を英数字だけに制限する？）

（もし通知メールも飛んでいない、つまり根本的にメンションとして扱われていないようなら、そちらも要対応）

## スクリーンショット

<img width="880" alt="Screen Shot 2020-02-26 at 4 52 54" src="https://user-images.githubusercontent.com/1148320/75282359-47018300-5854-11ea-8acf-13fff7c8a099.png">

## 環境

 - OS: macOS 10.15
 - ブラウザ: Chrome
 - バージョン: 80

**Comment by ima1zumi** [comment]
https://github.com/fjordllc/bootcamp/pull/1163 の対応でこの問題は発生しなくなったためCloseします〜
