### ISSUE TITLE
お知らせの送信先の選択に「就職希望者のみ」を追加したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1419]

**Comment by hasehiro25** [comment]
@komagata  @machida 
こちら1点確認したいことがあります。
コードを読むと「現役生へのお知らせ」の通知先に`admin`が含まれてるのですが、
今回の就職希望者へのお知らせも`admin`に通知が行くという認識で問題ないでしょうか？

**Comment by machida** [comment]
@machida すいません、adminの対応が抜けてました。adminにも通知が行くという認識で問題ないですー。

**Comment by hasehiro25** [comment]
@machida 
承知致しました！
ご確認ありがとうございます🙏
