### ISSUE TITLE
日報のコメントでメンションされてもメールが届かない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1433]
## 概要

表題の通り、日報のコメントでメンションされてもメールが届かない。

## 再現手順

下記2件のメンションについて、通知メールが届かなかった。
（Watch中であること、迷惑メールに入っていないことは確認済み）

<img width="623" alt="Screen Shot 2020-03-02 at 5 25 28" src="https://user-images.githubusercontent.com/1148320/75633207-50209480-5c46-11ea-9b40-3e5c8bea7778.png">

[wc コマンドを作るの提出物 \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/products/3140)

[UNIX・Linux Linuxゲリラ戦記\(53\-79\) \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/reports/10982)

## 期待される振る舞い

メンションがあるとメールが届く。（以前は届いていたはず？）

**Comment by JunichiIto** [comment]
すでに直っているかも？

https://github.com/fjordllc/bootcamp/issues/1674#issuecomment-647435200

**Comment by komagata** [comment]
すでに治っているのでClose。
