### ISSUE TITLE
Q&Aに質問が投稿されると通知が来るようにしたい

### ISSUE THREAD

**Issue by mikihito-h** [fjordllc/bootcamp#1447]
## 概要
Q&Aに新規の質問が投稿されると以前までは通知が来ていたのですが、来なくなってしまいました。
以前のように、通知が来るようにしたいです。

## 期待される振る舞い
日報や課題がメンターの方にチェックされた時に通知が届くのと同様に、Q&Aが投稿されると画面右上の通知マークが更新されるようにしたい。

## スクリーンショット

![image](https://user-images.githubusercontent.com/53965479/76197112-e0ef0580-622e-11ea-8ea6-dc40fe8288ff.png)

**Comment by NMP300** [comment]
@mikihito-h 

今日、開発ミーティングで議題に挙げさせていただきました。
実は、Q&Aの通知に関しては、送る対象が多すぎてか、落ちてしまっており、一旦Q&A通知機能を止めたそうです。

正確な原因の調査も必要なため、解決まで暫くお待ちください🙇‍♂️

**Comment by mikihito-h** [comment]
@NMP300 
そおだったんですね！
教えていただきありがとうございます😊

**Comment by JunichiIto** [comment]
@komagata これ、解決済みかも？

**Comment by komagata** [comment]
@JunichiIto ご指摘ありがとうございます。確かに解決済みなのでCloseします。

**Comment by mikihito-h** [comment]
@komagata 

僕(生徒)の方には通知が来ていないのですが、バグではなくそういう仕様なのでしょうか？

**Comment by komagata** [comment]
@kimihito すみません、僕が間違っていました。再度Openします。

**Comment by mikihito-h** [comment]
@komagata 

メンション先が間違っているみたいです！
@mikihito-h です👍

**Comment by komagata** [comment]
@mikihito-h すみません、修正しました。

**Comment by kasai441** [comment]
@komagata 
過去の変更をみたところ、
1. [> 実は、Q&Aの通知に関しては、送る対象が多すぎてか、落ちてしまっており、一旦Q&A通知機能を止めたそうです。](https://github.com/fjordllc/bootcamp/issues/1447#issuecomment-597474369)

2. #1379 にてMentorのみの通知に変更
3. 当Issueオープン
4. その後Q&Aの不具合調査の進展は？

という経過と把握しています。Issueの課題そのものは2の変更を元に戻せばできそうですが、もともとの不具合の解決がどうなっているのか分かりませんでした。何かご存知でしょうか、あるいはどのように作業を進めれば良いか教えてください。

**Comment by komagata** [comment]
:memo: 現状でいいのでCloseします。
