### ISSUE TITLE
ユーザーページのコメントタブにQ&Aの質問, 回答が表示されない

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#1459]
## 関連Issue
Ref: #1456

**Comment by machida** [comment]
@unstoppa61e

ユーザー個別ページのコメントタブを開くと、

<img width="1120" alt="貼り付けた画像_2021_12_08_13_19" src="https://user-images.githubusercontent.com/168265/145147569-1421c453-29da-4d0d-bdd9-2bbe181b7a87.png">

現在、Q&Aで回答したコメントは含んでいません。
Q&AのAはコメントに似てるけど別物の answer だからだと思われます。
answer も含めて表示されるようにしてほしいです。

**Comment by unstoppa61e** [comment]
@machida @komagata 
こちらの実装内容について、ご相談です。
ユーザー視点での感想なのですが、Q&A の回答は「コメント」カテゴリーに含めるよりも、「質問」カテゴリーに含めた方が良さそうな気がしています。
その方が、該当ユーザーの Q&A での活動具合が分かりやすく、関連 issue である #1456 での目的にも沿っているように思います。
ただ、もしそうする場合、「コメント」カテゴリーと「質問」カテゴリーとでは形式が異なるのが難しい点であるとは感じているのですが…。
いかがでしょうか？

**Comment by machida** [comment]
@unstoppa61e

コメントに入れるか、質問にいれるか迷いますね〜
#1456 については今の時点では置いておいて大丈夫です。

ユーザーが、このページに行った際にどのタブをクリックすると、その人が回答してきたQ&AのAの投稿があると予測するか？に沿った場所に置きたいと思ってます。

で、考えてみました。
仕様を以下のように変更をお願いします。

1. 質問というタブ名だと投稿した質問があることしか予測ができないので、質問に入れる場合は、タブ名を質問ではなく Q&A にしたいですね。
1. その中に、すべて（Q&A）、質問（Q）、回答・コメント（A）で絞り込む機能が欲しいですね。

今回の Issue ですが、将来的に 2 までやりたいのですが、2は別Issueにして、

- タブを質問から Q&A に変更
- タブを開いたら 質問と回答・コメントが混ざって表示される

ここまでをお願いしたいです。

見た目に関しては、質問 or 回答・コメント どちらであるかがすぐわかるような見た目にしたいと思っています。
こちらは machida がやりますー

**Comment by komagata** [comment]
@machida @unstoppa61e 僕は「回答」と「コメント」に分けた方がいいように思いました。

見た目は似ていますが、元々「回答」と「コメント」は機能が違う別の物として設計しているからです。
モデル的にも別のものになってるので混ぜて表示するのもちょっと苦労があるかもです。

**Comment by unstoppa61e** [comment]
@komagata
ご意見をお聞かせくださり、ありがとうございます！

@komagata @machida 
どちらの案でも対応させて頂けますので、お二方でお決め頂いて大丈夫です！

なお、現状をお伝えさせて頂きますと、まだコードが汚くはあるのですが、当初の「Q&A」案での実装がほぼ終了しました。
次のような状態になっています。
1) 表示のタイトルやアバターなどの情報は、「質問」のもの
![スクリーンショット 2021-12-13 13 45 01](https://user-images.githubusercontent.com/46347198/145754918-e4b090c4-dd19-4e73-8ebe-2833b8043f1d.png)

2) 情報として、「質問」の場合は「回答・コメント数」が表示され、「回答」の場合は、その内容が表示される
![スクリーンショット 2021-12-13 13 45 18](https://user-images.githubusercontent.com/46347198/145754523-15c5828d-ca0d-45a4-8d8a-ffa7d511aa48.png)

この方針でよろしいのでしたら、あとは、できれば、ベストアンサーの回答に「ベストアンサー」のハンコを表示できれば良いかな、という形です。
Question モデルの場合と Answer モデルの場合とで、場合分けがなされておりますので、「コメント」カテゴリーの中で、「提出物」と「日報」が、色の異なる丸いアイコンで区別されているような感じで、「質問」と「回答」で見た目を変えて頂けるかと思います。

ちなみに、ユーザーの一人の意見としては、Q&A 案、「回答」カテゴリー案、どちらでも良いかと思います。この Q&A 案でも、質問も回答も、そんなに数多くするものでもないので、混じって不都合があるということはあまりないように思います。

**Comment by machida** [comment]
@unstoppa61e 実装ありがとうございます！！これでOKですー 見た目をいじって、パッと見で質問 or 回答がわかるようにしたいと思います。PRにデザインを入れるようにします。デザインとレビューは同時進行でお願いします。

**Comment by machida** [comment]
@unstoppa61e @komagata 

ちなみに、QとAを混ぜた一覧を作ることで何か今後起きそうな不都合って予想できますでしょうか？もし、それがある場合は、今の時点で、

- QとAを混ぜた一覧はつくらない
- Q の一覧とAの一覧のみにし、切り替えが出来るタブを付ける

というようにしたいと思います。

**Comment by unstoppa61e** [comment]
@machida 
僕は、特に思い浮かびません。

**Comment by machida** [comment]
@unstoppa61e @komagata

すいません、仕様を変更したいと思います。
このページは就活にとって結構重要になるので、ぱっと見でその人の活動がわかりやすくするのがいいと思いました。
なので、大きいタブで回答タブを付けたいと思います。

<img width="989" alt="貼り付けた画像_2021_12_14_13_29" src="https://user-images.githubusercontent.com/168265/145933271-9cd8ed9b-9678-4441-ad97-84c888403fc2.png">

こうすることで、この人はよく質問をする人、よく回答をする人、というのがわかりやすくなるからです。
タブが増えるのが気になりますが、一旦その人の活動をひと目見てわかることを優先して、これでお願いしたいと思います。

**Comment by komagata** [comment]
@machida @unstoppa61e 

最終的に @machida さんがおっしゃってる、コメント、質問、回答を分ける案が僕もいいと思います〜。

ただ、上記の流れだと、町田さんが問答無用で決めてるような流れになっているように思うので、全体を見て実装側のことも考える必要があるので今後は少し相談いただければありがたいです〜。
