### ISSUE TITLE
分報（Twitterみたいなの）が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1461]
- みんなのタイムライン
- 個人のタイム

**Comment by NMP300** [comment]
@komagata @machida 

分報機能について、最初のPRで実装したい基本的な機能と、後のPRで追加したい機能を以下のように考えました🙇‍♂️
前者は、実用可能な最小限の機能を実装することを考えて、以下のようにしました。

初めての大きい機能の実装ということで、勝手が分かっておりませんが、分報機能についてご意見いただければと思います🙇‍♂️

## 最初のPRで実装したい機能
- ログインユーザーが分報を投稿・編集・削除することができる。
  - 投稿する際は、投稿専用画面に飛ぶのではなく、タイムラインと同じ画面に投稿フォームがあり、そこに入力することで、投稿できるようにする。
  - 分報には、ユーザーのアイコンと、名前と投稿日時、投稿内容が表示される。
- 他の人の分報を見ることができる。
  - ブートキャンプ受講生全員の分報が逐次表示される「みんなのタイムライン」と、ユーザー個別の分報のみが表示される「個人のタイムライン」を見ることができる。
  - ユーザーのアイコンや名前をクリックすることでユーザーの個別タイムラインに飛ぶことができる。
- 分報が投稿されたのと同時にタイムラインに表示される。

## 後々追加したい機能
- 他の人の分報に対してemojiでリアクションすることができる。
- メンションをつけることができる。
- 他の人の分報にコメントすることができる。
- 分報が1日単位で自動的に「2020年3月17日の分報」とまとめられて、そのURLを取得することができる。
- 画像を投稿することができる。
- 分報を、キーワードで検索することができる。

**Comment by komagata** [comment]
@NMP300 いいと思います、進めちゃってください。

ミーティング時に話していた、「タイムラインをリアルタイムに表示したい」と言うのを追加でお願いします〜

**Comment by NMP300** [comment]
@komagata 
ありがとうございます🙇‍♂️
承知しました💪

**Comment by koheitakahashi** [comment]
ミーティングで、最初のPRでは「みんなのタイムライン」のみを表示するというようになりました。「個人のタイムライン」は後のPRで実装することになりました。
仕様に関する上記コメントの内容も変更しました🙇‍♂️

**Comment by JunichiIto** [comment]
Discordがあるから不要、ではないんですかね？
