### ISSUE TITLE
検索結果の情報が少ない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1466]
検索結果の一覧を見ても、そこから「自分のほしい情報」を絞り込むのに苦労する。

<img width="897" alt="Screen Shot 2020-03-12 at 8 18 20" src="https://user-images.githubusercontent.com/1148320/76472902-419e5e00-643a-11ea-8864-de710b372f53.png">

具体的には以下の情報を知りたい。

- いつ投稿された情報か？
- 誰が投稿した情報か？
- 一覧は何順で並んでいるのか？（日付の新しい順に並んでいてほしいが、一覧を見てもソート順がわからない）

参考：Qiitaだとこんな感じで、上に挙げた情報がすべて含まれている。

<img width="803" alt="Screen Shot 2020-03-12 at 8 21 43" src="https://user-images.githubusercontent.com/1148320/76473017-96da6f80-643a-11ea-8af5-8ecca7c7641d.png">

**Comment by komagata** [comment]
:memo: 

- 作成者を表示する
- created_atを表示する
- created_atの逆順にソートする
