### ISSUE TITLE
Q&Aコメントのプレビューが機能しない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1469]
## 概要

Q&Aコメントのプレビューが機能しない。
（consoleを見てもJSエラーは出ていない）

## 再現手順

1. https://bootcamp.fjord.jp/questions/477 にアクセス。
2. コメントを入力。
3. プレビュータブをクリック。

## 期待される振る舞い

プレビューが表示される

## スクリーンショット

![57b0hfYKbn](https://user-images.githubusercontent.com/1148320/76583533-c792d580-651c-11ea-9e08-4896eb7348a9.gif)

## 環境

 - OS: macOS 10.15.3
 - ブラウザ: Chrome
 - バージョン: Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by JunichiIto** [comment]
Command+RETURN でコメントを投稿するショートカットも動いていませんでした。
これも同じ原因でしょうか？
もし無関係であれば別途issueを作ります〜。

**Comment by tetishi** [comment]
@JunichiIto 
コメントありがとうございます。
上記、原因が同じかどうか調べます。

**Comment by komagata** [comment]
@JunichiIto @tetishi Command+RETURNは元々こちらには実装されてない感じです〜

**Comment by tetishi** [comment]
@komagata @JunichiIto 
なるほど、実装されていないんですね。
では私の方から、Q&Aでコメントを投稿する時にCommand + Returnのショートカットを使用できるようにするというIssueを作成してみてもよろしいでしょうか？

**Comment by JunichiIto** [comment]
@tetishi 助かります！お願いします〜。

**Comment by JunichiIto** [comment]
Q&Aコメントのプレビュー機能、対応に時間が掛かりそうなら、いったん「プレビュー」のタブ表示を隠してしまった方がいいかも、と思いました。

<img width="402" alt="Screen Shot 2020-05-18 at 8 29 18" src="https://user-images.githubusercontent.com/1148320/82162742-c5187780-98e1-11ea-9fdc-755edf122f6f.png">

**Comment by tetishi** [comment]
@JunichiIto 
かしこまりました。
Q&Aコメントのプレビュー機能のPRがマージされるまで、いったんプレビューのタブ表示を隠してみます。

@komagata 
よろしいでしょうか？

**Comment by komagata** [comment]
@tetishi はい、OKです〜！

**Comment by tetishi** [comment]
@komagata 
お返事ありがとうございます。
かしこまりました。
