### ISSUE TITLE
ページャーで表示したページのリダイレクト設定

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1474]
キャプチャのように、ページャーが表示した先にコンテンツがなかった場合、
一つ前（※）にリダイレクトしたい。
![image](https://user-images.githubusercontent.com/168265/76715492-f94faa80-676f-11ea-8327-5ede8cb36f91.png)

※一つ前とは、

https://bootcamp.fjord.jp/notifications/unread?page=6

?page=6 にコンテンツがなかったら、?page=5にリダイレクト。

**Comment by komagata** [comment]
@machida Webアプリのステータスとしては、勝手にリダイレクトすると意味合いが変わっちゃうので、該当するコンテンツが無いという意味で404にするか、もしくはページャーも隠した上で「通知がありません」と表示した上でリンクを出すとかがの方が良いかもです。
