### ISSUE TITLE
検索結果にコメントを含めたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1480]
- コメントを検索結果に含めるが、検索結果の表示としては日報とか提出物になる。
- 自分がみることのできない提出物は一覧に本文を表示しない。

**Comment by chihaso** [comment]
@komagata @machida 
検索結果の仕様について、確認させてください。🙌
1. 本文とコメントの両方でキーワードがマッチした場合　→　検索結果に両方とも表示する
2. 複数のコメントでキーワードがマッチした場合　→　検索結果にマッチした数だけ表示する

という感じでよろしいでしょうか？🤔

**Comment by komagata** [comment]
@chihaso 

> 1. 本文とコメントの両方でキーワードがマッチした場合　→　検索結果に両方とも表示する

👌

> 2. 複数のコメントでキーワードがマッチした場合　→　検索結果にマッチした数だけ表示する

> 検索結果にマッチした数だけ表示する

ちょっとこの部分がよくわからなかったです。どういう意味でしょうか？

> 他のcommentableなオブジェクト（「提出物」「イベント」）も検索対象として選べるようにするのが自然だと思うのですが、そのようにしてもいいでしょうか？

はい。ただ別Issueでやるのがいいと思うので、Issueを作成していただければありがたいです。

**Comment by chihaso** [comment]
@komagata 
>> 検索結果にマッチした数だけ表示する

>ちょっとこの部分がよくわからなかったです。どういう意味でしょうか？

例えば日報に複数のコメントがついていて、それぞれのコメントに同じ文字列が含まれていたとします。下図のイメージです。
<img width="1440" alt="test___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/48672932/77612055-73e7a980-6f6a-11ea-8551-99d7e7833deb.png">
上図の状況で「コメント」で検索した場合、コメントが２件ともマッチしますが、その２件をどちらも検索結果に表示していいでしょうか？

現在の検索結果はマッチした文書のタイトル(上図で言うと「test」）が表示される仕様です。
マッチしたものを全て表示すると、コメントが複数マッチしたとき同じタイトルが複数並ぶことになり、ちょっと分かりづらくなりそうだなぁと思っています。

**Comment by komagata** [comment]
@chihaso なるほど、よくわかりました。

まずは完成させることを優先してそのまま（二件表示される状態）で大丈夫です。後から修正もしやすいと思うので。

**Comment by chihaso** [comment]
@komagata 
ご回答ありがとうございます 🙌
それでは２件とも表示するように作ります🏃‍♂️
