### ISSUE TITLE
WIPの提出物をダッシュボードに表示したい（未提出の日報機能と同じ）

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1482]
未提出の日報と同じような箱の中に出したい。

**Comment by kotakanazawa** [comment]
@komagata さん、イメージの確認をさせてください〜！
「未提出の日報と同じ箱の中に出したい」とは次のイメージでしょうか？

![スクリーンショット 2020-05-25 10 14 34](https://user-images.githubusercontent.com/28076271/82769721-b6493c00-9e70-11ea-92c5-89562c260896.jpg)

**Comment by komagata** [comment]
@kotakanazawa はい、そうです〜

**Comment by kotakanazawa** [comment]
@komagata かしこまりました〜！
