### ISSUE TITLE
プラクティスにメンター向けのメモ欄を追加したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1493]
プラクティスにmemo欄を追加したい。
memo欄はmentorだけに表示される。

編集できるのは管理者のみ。

閲覧できるのはmentor。

**Comment by kotakanazawa** [comment]
@komagata @machida 
以下のようなイメージで作ろうと考えています。
イメージは合っていますでしょうか？

## プラクティス詳細画面

<img width="746" alt="プラクティス詳細画面" src="https://user-images.githubusercontent.com/28076271/82546300-dfc54780-9b92-11ea-83a1-e14cf83673e5.png">

## プラクティス編集画面

![プラクティス編集画面](https://user-images.githubusercontent.com/28076271/82546312-e653bf00-9b92-11ea-8635-da1f6d5cbe7c.jpg)

**Comment by komagata** [comment]
@kotakanazawa はい、あっています〜

**Comment by kotakanazawa** [comment]
@komagata 
ありがとうございます！！

**Comment by machida** [comment]
あってます〜

**Comment by kotakanazawa** [comment]
@machida 
ありがとうございます！！
