### ISSUE TITLE
「コメントが投稿されました」の通知メールに改行が反映されていない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1495]
## 概要

「コメントが投稿されました」の通知メールに改行が反映されていない。

## 再現手順

「メンションがありました」のメール本文
<img width="632" alt="Screen Shot 2020-03-25 at 9 58 33" src="https://user-images.githubusercontent.com/1148320/77490960-c5673a00-6e7f-11ea-8026-57be88c2f2d9.png">

「コメントが投稿されました」のメール本文
<img width="619" alt="Screen Shot 2020-03-25 at 9 58 42" src="https://user-images.githubusercontent.com/1148320/77490914-a8326b80-6e7f-11ea-9ed8-74d732d8bfc7.png">

## 期待される振る舞い

「メンションがありました」のメール本文と同じ見た目になる

## 環境

 - OS: macOS
 - ブラウザ: Chrome
 - バージョン: 80

**Comment by Daichi831** [comment]
#2871 
上記のissueと関連しているため#2871と同時に確認し改善されていたらcloseする

**Comment by machida** [comment]
@Daichi831 こちら、本番から届いたメールで改行が確認できたのでcloseしますー
