### ISSUE TITLE
Q&Aの「解決にする」ボタンを「ベストアンサーにする」ボタンに変える

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1496]
## 現状の問題点

Q&Aの「解決にする」ボタンは「私の疑問点は解決されました」に変更するボタンだと勘違いされる可能性がある。
（自分のコメントに対してベストアンサーを付ける恐れがある）

参考
<img width="757" alt="Screen Shot 2020-03-25 at 13 45 10" src="https://user-images.githubusercontent.com/1148320/77502961-b0020800-6e9f-11ea-8791-8b5ae91ba1b2.png">

## 改善案

一番役に立ったコメントをベストアンサーに選ぶ必要がある。
また、UI上は「ベストアンサー」でキーワードを統一した方がよい。

なので、現在の「解決にする」ボタンは、ラベルを「ベストアンサーにする」ボタンに変更する。
（もしくはベストアンサーを選ぶことをわかりやすく表現したラベルを付ける）

## 参考1
現状のボタン（ベストアンサーの選択と解除でキーワードが異なっている）

<img width="859" alt="Screen Shot 2020-03-25 at 13 44 30" src="https://user-images.githubusercontent.com/1148320/77502923-9c56a180-6e9f-11ea-912d-00de730d839f.png">

<img width="799" alt="Screen Shot 2020-03-25 at 13 44 57" src="https://user-images.githubusercontent.com/1148320/77502936-a1b3ec00-6e9f-11ea-8f9e-ecad823899ff.png">

## 参考2
「解決します。よろしいですか？（このコメントがベストアンサーとして選ばれます）」みたいなダイアログを出すのもいいかも。（Teratail方式）

https://teratail.com/questions/140558

**Comment by JunichiIto** [comment]
@kotakanazawa 対応ありがとうございました！😄

**Comment by kotakanazawa** [comment]
@JunichiIto とんでもありません💦良い学びになりました！
