### ISSUE TITLE
提出物やイベントも検索できるようにしたい

### ISSUE THREAD

**Issue by chihaso** [fjordllc/bootcamp#1499]
issue #1480 で、コメントを検索結果に含める。
そうであれば、commentableなものも全て検索対象に含めたい。
<img width="421" alt="イベント___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/48672932/77651219-cc8d6580-6faf-11ea-80e2-540da032fac8.png">

**Comment by ima1zumi** [comment]
こちらマージ済ですのでCloseします〜
