### ISSUE TITLE
「完了したプラクティス」が100%を超えることがある

### ISSUE THREAD

**Issue by koheitakahashi** [fjordllc/bootcamp#1506]
## 概要

ユーザー個別ページ、ユーザー一覧ページ表示される「完了したプラクティス」のパーセンテージが100%を超えているユーザーが存在しています。

## 期待される振る舞い

「完了したプラクティス」のパーセンテージの上限は100%にしてほしい。

## スクリーンショット

「完了したプラクティス」の進捗が101%になっているユーザー。

[![Image from Gyazo](https://i.gyazo.com/01637686edce1728f412ebeb36989fb4.png)](https://gyazo.com/01637686edce1728f412ebeb36989fb4)

## 関連Issue

Ref: #1233

**Comment by komagata** [comment]
@shibaaaa ご指摘ありがとうございます。クローズします。
