### ISSUE TITLE
検索結果に出てくる日報のユーザー名と日時が直感に反する

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1507]
## 概要

検索結果の一覧にユーザー名や作成日時が表示されるようになったが、日報のコメントが検索に引っかかるとコメントの発言者と発言日時が表示される。

が、ユーザーとしては日報の投稿者と投稿日時を表示してほしい。

## 再現手順

1. "rspec"で検索
2. 検索結果に出てくる[lsコマンド修正,wcコマンド\#3](https://bootcamp.fjord.jp/reports/11768)の内容を確認する

## 期待される振る舞い

日報の投稿者と投稿日時を表示する。

## スクリーンショット

一瞬、「あれ？りほやんが日報書いてるの！？」と思った。

<img width="999" alt="Screen Shot 2020-04-01 at 19 23 36" src="https://user-images.githubusercontent.com/1148320/78127519-4493d980-744f-11ea-8781-d57f2db5b60e.png">

どうも"rspec"というキーワードがこのコメントに引っかかったせいっぽい。

<img width="887" alt="Screen Shot 2020-04-01 at 19 26 07" src="https://user-images.githubusercontent.com/1148320/78127556-54abb900-744f-11ea-9d04-fcef1b79e5f1.png">

## その他

日報以外の検索結果でも同じ現象が起きているかも（未確認）

## 関連Issue

Ref: https://github.com/fjordllc/bootcamp/pull/1485

**Comment by ima1zumi** [comment]
> 期待される振る舞い
> 日報の投稿者と投稿日時を表示する。

日報の投稿者と投稿日時が表示されると、自分は少し違和感があります。投稿者の名前は出ていてほしいと思います 🤔 
現在「日報」と書いてある丸の中身を「コメント」にすると分かりやすくなると思いました。

**Comment by JunichiIto** [comment]
> 現在「日報」と書いてある丸の中身を「コメント」にすると分かりやすくなると思いました。

なるほど、たしかに〜。
もっと欲を言うと「コメント（日報）」「コメント（提出物）」みたいに、何のコメントかという点も明示されていると嬉しいです。

**Comment by machida** [comment]
@Paru871 
こちらアサインさせていただきました🙏

コメントの表示は、このようにしたいです（デザインは町田がやります）。

<img width="1179" alt="貼り付けた画像_2021_12_22_23_25" src="https://user-images.githubusercontent.com/168265/147108238-d0379fb0-9343-4c15-a04b-4435a67c2a02.png">

上記は日報のコメントですが、

- 提出物のコメントのときは日報を提出物に
- Q&AのAのときは、日報を質問に

お願いします🙏

**Comment by Paru871** [comment]
@machida 
アサインいただきありがとうございます🙏かしこまりました。

**Comment by Paru871** [comment]
本番環境で確認できましたのでクローズさせていただきます。ありがとうございましたー🙏🏻
