### ISSUE TITLE
日報のページで提出物が選択状態になる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1509]
<img width="396" alt="スクリーンショット 2020-04-04 16 18 13" src="https://user-images.githubusercontent.com/16577/78421082-020d0f80-7690-11ea-80be-3d7c1772bbcb.png">

**Comment by tetishi** [comment]
@komagata 
日報のページで提出物が選択状態になるというのは、global-navの日報のリンクがアクティブになっている時に、global-navの提出物のリンクもアクティブになっているということでしょうか？

[未チェックの提出物のときにglobal-navの提出物のリンクがアクティブになってない。](https://github.com/fjordllc/bootcamp/pull/1472)、こちらのIssueでは、以下のスクリーンショットのように未チェックの提出物が１つ以上あるときは提出物タブを選択していない場合でも提出物タブがアクティブになるようにコードを書きました。（未チェックの提出物が０だと提出物タブを選択しない限り、提出物タブはアクティブになりません。）

# 未チェックの提出物がある場合
## お知らせ選択時
![お知らせ___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）_and_bootcamp_—_fsevent_watch_◂_localhost_3000___bootcamp__rvm_bin_path__Users_tetsuroishida__rvm_bin_TERM_PROGRAM_Apple_Terminal_—_80×24_and_Slack_____learning___FJORD__LLC](https://user-images.githubusercontent.com/44915479/78469605-cb052f80-775d-11ea-8f6d-06c4ab4ea181.png)

## プラクティス選択時
![Rails_Webプログラマーコースのプラクティス___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/78469616-e839fe00-775d-11ea-8752-0b6bc9171929.png)

## 日報選択時
![未チェックの日報___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）_and_bootcamp_—_fsevent_watch_◂_localhost_3000___bootcamp__rvm_bin_path__Users_tetsuroishida__rvm_bin_TERM_PROGRAM_Apple_Terminal_—_80×24_and_Slack_____learning___FJORD__LLC](https://user-images.githubusercontent.com/44915479/78469628-01db4580-775e-11ea-8568-8c3bf4487185.png)

## 提出物選択時
![未チェックの提出物___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/78469644-2c2d0300-775e-11ea-95d1-d751b908a655.png)

#  未チェックの提出物がない場合
## お知らせ選択時
![お知らせ___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/78469983-b4140c80-7760-11ea-9ebd-a1f88cf079c5.png)

## プラクティス選択時
![Rails_Webプログラマーコースのプラクティス___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/78470001-e32a7e00-7760-11ea-9bfd-a8d0953c3805.png)

## 日報選択時
![未チェックの日報___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）_and_bootcamp_—_fsevent_watch_◂_localhost_3000___bootcamp__rvm_bin_path__Users_tetsuroishida__rvm_bin_TERM_PROGRAM_Apple_Terminal_—_80×24_and_Slack_____learning___FJORD__LLC](https://user-images.githubusercontent.com/44915479/78470019-005f4c80-7761-11ea-93ae-0dabfb0081ee.png)

## 提出物選択時
![未チェックの提出物___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/78470033-1bca5780-7761-11ea-8286-41f4e06b6d11.png)


しかし、上記は間違いで、本当はただ単純に、提出物タブを選択するとアクティブになり、提出物があるかどうかは関係なく日報などの他のタブを選択すると提出物タブのアクティブ状態は解除されるべきということでしょうか？

よろしくお願いします🙇‍♂️

**Comment by komagata** [comment]
@tetishi すみません、ちょっとおっしゃっている意味がわからないです。

正しい状態は下記です。

- 黄色になるリンクは常に一つだけ
- 今いるページが黄色くなる（提出物のページにいるなら提出物リンクだけが黄色くなる）

**Comment by tetishi** [comment]
@komagata 
ご説明ありがとうございます。

> 黄色になるリンクは常に一つだけ
未チェックの何かがあるかどうかはボタンが黄色くなるかどうかには関係ありません。

なるほど。理解いたしました。
すみません、私が勘違をしてコードを書いていたようです。

上記修正いたします。
