### ISSUE TITLE
複数キーワードで検索したい

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/bootcamp#1510]
## 概要
現行の検索機能の仕様では、複数キーワードでの絞り込みに対応しておらず、キーワード全体と一致するものを検索結果として返している
そのため、単一のキーワードで検索した後に別のキーワードを追加して検索結果を絞り込むという使い方ができない
そのため Google の検索のように、複数のキーワードをスペースで区切って検索できるようにしたい

## 現行の仕様
スペースを含めたキーワード全体と完全一致しているものを検索結果として返す

## 期待される振る舞い
スペースで区切られたキーワードは別のキーワードみなし、全てのキーワードを含むものを検索結果として返す(== AND検索)

### 検索対象
1. "メンター 就職の話をします。"
1. "メンターと就職の話をします。"

### 検索キーワード
"メンター 就職"

#### 現行の仕様
- 検索対象1 は検索結果に **含まれる**
- 検索対象2 は検索結果に **含まない**

#### 期待される振る舞い
- 検索対象1 は検索結果に **含まれる**
- 検索対象2 は検索結果に **含まれる**

**Comment by komagata** [comment]
@sanfrecce-osaka これはPRをいただけるという前振りですね？

**Comment by sanfrecce-osaka** [comment]
@komagata 

はい、後日PR出す予定です〜:pray:(現役生の課題にもいいかなと思ったのですがやり始めてしまったので自分で出しちゃいます:bow:)

関連: https://github.com/fjordllc/bootcamp/pull/1487
