### ISSUE TITLE
プラクティス編集画面にある 「進捗の計算に含むようにする場合はチェック」  が機能していない

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1512]

**Comment by hasehiro25** [comment]
@machida
こちらバグ内容の認識が正しいか確認していただけますと幸いです🙇‍♂️
### バグの再現
1. 新しいプラクティス作成をし、「進捗の計算に含むようにする場合はチェック」のチェックはオフにする
2. 作成後、同じプラクティスの編集画面へ移動する
3. 「進捗の計算に含むようにする場合はチェック」にチェックが入ってる
### 期待される動作
進捗に含めないように設定してるプラクティスは、編集画面でもチェックを外す


進捗の計算は正常に動いてるものの、プラクティス編集画面の「進捗の計算に含むようにする場合はチェック」が常にチェックが入ってしまうバグを直すという認識で合ってますでしょうか？

**Comment by komagata** [comment]
@hasehiro25 解ってることは「進捗が100％以上の人がいる」ってことだけだった感じです〜

**Comment by machida** [comment]
@hasehiro25 

> プラクティス編集画面の「進捗の計算に含むようにする場合はチェック」が常にチェックが入ってしまうバグを直す

ちょっと整理すると、

プラクティス編集画面の「進捗の計算に含むようにする場合はチェック」のチェックを外しても、またチェックが入ってしまうバグを直す、ということになります。

プラクティスを作成した時点でデフォルトでチェックが入っているのはOKです。ただ、意図的にプラクティスの編集者がチェックを外した場合に、その外した状態は維持されてほしいです。

現在はチェックを外した状態が維持されないので、プラクティス編集画面の「進捗の計算に含むようにする場合はチェック」のチェックを外しても、またチェックが入ってしまうバグを直す、ということになります。

**Comment by hasehiro25** [comment]
@machida 
了解しました！
ありがとうございます🙇‍♂️
