### ISSUE TITLE
コメント機能のシステムテストが失敗する

### ISSUE THREAD

**Issue by koheitakahashi** [fjordllc/bootcamp#1513]
## 概要

ローカルではテストが成功するのですが、CircleCI上ではコメントのURLをクリップボードにコピーする機能のテストが失敗します。

## エラーログ

https://circleci.com/gh/fjordllc/bootcamp/3607#artifacts/containers/0

```
Error:
CommentsTest#test_comment_url_is_copied_when_click_its_updated_time:
Selenium::WebDriver::Error::InvalidArgumentError: invalid argument: Unknown permission type: clipboardRead
  (Session info: headless chrome=81.0.4044.92)
    test/system/comments_test.rb:142:in `block in <class:CommentsTest>'


rails test test/system/comments_test.rb:141
```

## 期待される振る舞い

上記のエラーを解決して、テストが失敗しないようにしたいです。

## 環境

 - OS: macOS Catalina version 10.15.3 
 - ブラウザ: chrome

## 関連Issue

Ref: #1462

**Comment by koheitakahashi** [comment]
解決に向けて、調査中です🙇‍♂️

**Comment by JunichiIto** [comment]
僕のローカルではこれでパスしました。

```ruby
  test "comment url is copied when click its updated_time" do
    visit "/reports/#{reports(:report_1).id}"
    first(:css, ".thread-comment__created-at").click
    # テキストエリアにペーストして、URLが正しくコピーされていることを検証する
    # ペーストの方法は以下のページを参考にした
    # https://stackoverflow.com/a/57955123/1058763
    find('#js-new-comment').send_keys [:shift, :insert]
    clip_text = find('#js-new-comment').value
    assert_equal current_url + "#comment_#{comments(:comment_1).id}", clip_text
  end
```

**Comment by JunichiIto** [comment]
ちなみに "clipboardRead permission might be removed in 81" らしいので、これまでの方法は使えなさそうでした。

参考 https://gitmemory.com/issue/marp-team/marp-cli/190/564376272

**Comment by chihaso** [comment]
@JunichiIto 自分がこのコード書いてたとき、`send_keys [:ctrl, :v]`みたいに書いても貼り付けてくれなかったので、`send_keys`ではクリップボード操作できないものだと思ってました！！
キーを変えればよかったんですね・・・😅

**Comment by JunichiIto** [comment]
@chihaso 僕も最初 ctrl-v や command-v を試してダメだったので "selenium paste mac ruby" みたいなキーワードでググって、 https://stackoverflow.com/a/57955123/1058763 を見つけました〜😄

**Comment by ima1zumi** [comment]
こちらマージ済ですのでCloseします〜
