### ISSUE TITLE
ニコニコカレンダーの日付を誤認識しやすい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1514]
プロフィールページのニコニコカレンダーは、赤丸部分が4/1だが、慣習的につい、青丸の部分を4/1だと認識してしまう。

<img width="712" alt="Screen Shot 2020-04-09 at 9 44 33" src="https://user-images.githubusercontent.com/1148320/78846589-38a7a900-7a47-11ea-9fe9-3462c8f8ea5d.png">

日常的に使うカレンダーのように、月単位で表示を切り替えるか、もしくは下のリスト形式のようにするなど、全面的に表示形式を改善した方がいいのではないか？

- 04/09（木）×
- 04/08（水）🙂
- 04/07（火）×
- （略）
- 03/10（火）🙂

**Comment by bluerabbit** [comment]
> 月単位で表示を切り替える

👍

**Comment by komagata** [comment]
@JunichiIto @bluerabbit 今これをどう改善するのか話し合っていました。

そもそも最近の数件の30日分のメンタルの状況がみたかった。
カレンダーにするとすると、全ての年・月をみれるようにする？そうなるとSPA化する？そこまで重要じゃないのでやりすぎな気もする。　←　イマココ

**Comment by JunichiIto** [comment]
@komagata ふむふむなるほど。

> 全ての年・月をみれるようにする？そうなるとSPA化する？そこまで重要じゃないのでやりすぎな気もする

たしかにその点はagreeです。

> そもそも最近の数件の30日分ぐらいのメンタルの状況がみたかった。

「最近の30日分だけ見られれば良い」という要件はそのままでもいいので、あとは見た目の問題ですかねえ？
今の表示形式があまりにも「一般のカレンダーのイメージ」に近すぎるのが問題な気がします。
代替案はぱっとでないのですが、 @machida さんとかと話合って、「直近の30日だけですよ」というのが一見して分かるデザインにできないでしょうか？

**Comment by obregonia1** [comment]
@machida 
急にアサインされたんですが #2886 で解決されたと思うのでこのIssueは #2840 と同じタイミングでcloseしてもいいですか？

**Comment by machida** [comment]
@obregonia1 ごめんなさい、関連Issueなので、リリースされたらcloseをお願いしようと思ってアサインさせていただきましたー。連絡しようとしてて忘れてました🙇‍♂️

**Comment by obregonia1** [comment]
#2886 で解決できたのでcloseします。
