### ISSUE TITLE
Command + Returnのショートカットキーを使用しQ&Aでコメントを投稿できるようにしたい

### ISSUE THREAD

**Issue by tetishi** [fjordllc/bootcamp#1520]
Q&Aでコメントを投稿する時`Command + Return`のショートカットキーを使用し投稿できるようにしたい

## 以下はQ&Aでコメントを投稿する時、`Command + Return`のショートカットキーが使用できない様子

[![Screenshot from Gyazo](https://gyazo.com/decea758c6b8a17cccab062273bbe3d7/raw)](https://gyazo.com/decea758c6b8a17cccab062273bbe3d7)

### Q&Aでも以下のようにしたい

[![Screenshot from Gyazo](https://gyazo.com/81dc44960f2d8e3e5c503fec09fe55dc/raw)](https://gyazo.com/81dc44960f2d8e3e5c503fec09fe55dc)

**Comment by ima1zumi** [comment]
対応済のためCloseします〜
