### ISSUE TITLE
URLからコメントが検索できてしまう

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/bootcamp#1528]
## 概要
`/searchables?document_type=comments` でアクセスするとコメントを検索できてしまい、未完了の提出物のコメントも検索結果として表示されてしまっている
ただし、description は未完了の場合はマスクされている

## 再現手順

1. `/searchables?document_type=comments` にアクセス
2. コメントの検索結果が表示される

## 期待される振る舞い
許可されていない document_type での検索の場合はエラーとなること

## スクリーンショット
[![Image from Gyazo](https://i.gyazo.com/fb780bf7c8bbe69b8421d8d37ccb3c95.png)](https://gyazo.com/fb780bf7c8bbe69b8421d8d37ccb3c95)

## 関連Discussion

Ref: https://github.com/fjordllc/bootcamp/pull/1521#discussion_r407127186

**Comment by sanfrecce-osaka** [comment]
@komagata 
関連Discussion で @JunichiIto さんと話した結果、閲覧されては困るコメントはマスクされているので問題ないかなーと思いますが、@komagata さんへの確認・Discussion のために issue を立てました
本件に関して、どうでしょうか？:thinking:

**Comment by JunichiIto** [comment]
> 許可されていない document_type での検索の場合はエラーとなること

本論とは外れますが、

https://bootcamp.fjord.jp/searchables?document_type=commentsxxx

みたいなデタラメなtypeを指定すると500エラーになりますね。
この場合は「リクエストした側が悪い」ので、400系のエラーにするのが適切な気がします。
もしくはしれっと「全タイプを対象にして結果を返す」とかでもいいかも。

**Comment by ima1zumi** [comment]
こちらマージ済ですのでCloseします〜
