### ISSUE TITLE
日報のコメント欄のシンタックスハイライトが効かない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1529]
## 概要

日報のコメント欄のシンタックスハイライトが効かない

## 再現手順

1. https://bootcamp.fjord.jp/reports/12017#comment_22754 にアクセス。
2. シンタックスハイライトをしているはずだが、シンタックスハイライトが効いていない。（編集中にプレビューしたときも同様）

<img width="786" alt="Screen Shot 2020-04-17 at 8 38 46" src="https://user-images.githubusercontent.com/1148320/79516619-e0942680-8086-11ea-8503-94a8a5f2c6a7.png">

## 期待される振る舞い

シンタックスハイライトが有効になる。

## 関連Issue

Ref: https://github.com/fjordllc/bootcamp/issues/1063#issuecomment-517091896

上でも報告されていますが、なかなか対応されないようなので、別issueとしてあげてみました。
（簡単に直せそうなら、こっちだけ先に直してもらえるかも？？）

**Comment by ima1zumi** [comment]
こちらマージ済ですのでCloseします〜

**Comment by JunichiIto** [comment]
@ima1zumi 数々の過去のissueのclose、どうもありがとうございました！
