### ISSUE TITLE
検索結果に何もヒットしない場合の画面が不親切

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1530]
検索を実行しても何もヒットしなかった場合には「データがありません」等の文言がひと言ほしい。
今のUIだと、何か内部エラーが発生して処理が中断されたような印象を受ける。
<img width="981" alt="Screen Shot 2020-04-17 at 17 04 59" src="https://user-images.githubusercontent.com/1148320/79546767-ed883880-80cd-11ea-8f8f-021687afb694.png">

**Comment by hituzi-no-sippo** [comment]
私の要望としては何もヒットしない場合、検索ボックスの下に何もヒットしないことを表示して検索結果のページに移動せず、ページはそのままでいて欲しいです。また、検索ボックスにフォーカスを合わせたままにして欲しいです。

私はソースコードを読んでないので実装できるかどうかや難しいかわかりません。

**Comment by JunichiIto** [comment]
@hituzi-no-sippo 
> 私の要望としては何もヒットしない場合、検索ボックスの下に何もヒットしないことを表示して検索結果のページに移動せず、ページはそのままでいて欲しいです。また、検索ボックスにフォーカスを合わせたままにして欲しいです。

これって「このページと同じです」みたいな見本ってあります？文字だけだといまいちイメージがわかず・・・。

あと、その仕様を求める背景や動機も何かあれば知りたいです。（単なる個人の好みなのか、それとも他の人にもメリットがある仕様なのか等を判断するため）

**Comment by hituzi-no-sippo** [comment]
> これって「このページと同じです」みたいな見本ってあります？文字だけだといまいちイメージがわかず・・・。

ご指摘ありがとうございます。改めて自分のコメント読んだら、その部分自分でもわかりにくいと感じています 😅

こんな感じで、青色部分はポップアップウィンドウのイメージです。

![2020-11-23 11 41 13 bootcamp fjord jp 9782b65b1b78](https://user-images.githubusercontent.com/43565959/99925381-4cf3a880-2d81-11eb-8525-996852783755.png)

> あと、その仕様を求める背景や動機も何かあれば知りたいです。（単なる個人の好みなのか、それとも他の人にもメリットがある仕様なのか等を判断するため）

自分の好みで、自分が考えているメリットは次のとおりです。

* ページ移動しない
  前回の検索結果を見たいときにブラウザの戻るボタンを押さなくていい
* 検索ボックスにフォーカスを合わせたまま
  連続で検索するときに1回1回フォーカスしなくて良いので操作しやすい

考え直したら上のコメントで書いている要望は1つではなく、次の2つに分かれますね。

* 検索時にデータがヒットしない場合はページ移動をせず、検索ボックスの下にヒットするデータがないことを表示してほしい
* 検索ボックスにフォーカスをあわせた状態で検索を実行し、ページ移動した場合、検索ボックスにフォーカスをあわせたままでいてほしい

検索機能はあまり使わない印象がありますので、優先順位は両方とも低めでいいと自分は考えています。

**Comment by ima1zumi** [comment]
@JunichiIto 

> 検索を実行しても何もヒットしなかった場合には「データがありません」等の文言がひと言ほしい。

これと同じような画面を出すイメージですかね？ 🤔 
これは https://bootcamp.fjord.jp/users?target=followings でフォローが0件のときの画面です。
![image](https://user-images.githubusercontent.com/52617472/99932493-8e914d00-2d9b-11eb-8af2-1bc002a517c4.png)

**Comment by ima1zumi** [comment]
@hituzi-no-sippo 
> 検索時にデータがヒットしない場合はページ移動をせず、検索ボックスの下にヒットするデータがないことを表示してほしい

画面イメージ作ってみました。
これは「rspec assert_text」（ヒットあり）を検索したあとに「rspec assert_css」（ヒットなし）で検索した場合のイメージです。「rspec assert_css」では検索結果がゼロ件なので、「rspec assert_text」の検索結果が残っています。

この表示結果は「rspec assert_css」でヒットしたかのように見えるので、ちょっと紛らわしい気がします 🤔 

![image](https://user-images.githubusercontent.com/52617472/99934357-1f1e5c00-2da1-11eb-8926-6da1a87e1d35.png)



> 検索ボックスにフォーカスをあわせた状態で検索を実行し、ページ移動した場合、検索ボックスにフォーカスをあわせたままでいてほしい

これはあると便利そうですが、issueの表題とは少し違う話題になっている気がします。
この機能が欲しい場合は別issueで立ててもらえると検討・対応しやすくなるのでご検討ください :smile:

**Comment by JunichiIto** [comment]
@hituzi-no-sippo 説明ありがとうございます〜。

> 検索時にデータがヒットしない場合はページ移動をしない機能

これ、実装方法を想像すると、検索文字列を入力するたびにJSがサーバーサイドに検索結果を問い合わせたり、検索実行（リターンキーでキーワードを決定）したときもまずJS側で検索結果のあり・なしをサーバーから受け取ってから、画面遷移する・しないを判断しなきゃいけないと思うので、かなり面倒くさそうですね。。
費用対効果にフォーカスすれば、あまり凝ったことはせずに、まずは普通に画面遷移あり＋「データ無し」のメッセージを表示、とする方がいいんじゃないかな〜と個人的には思いました。
もちろん、hituziさんが自力で実装してPRを送れば歓迎されると思います！😆

@ima1zumi

> これと同じような画面を出すイメージですかね？

はい、そんなイメージです〜。

**Comment by hituzi-no-sippo** [comment]
@JunichiIto 

> 普通に画面遷移あり＋「データ無し」のメッセージを表示、とする方がいいんじゃないかな〜と個人的には思いました。

自分もそれで大丈夫です。
 "画面遷移なし + 検索ボックスの下に「データなし」のメッセージを表示" が ""画面遷移あり＋「データ無し」のメッセージを表示" と同じくらい実装が簡単なら、画面遷移無しの方を実装して欲しいため別issueを作成せず、こちらにコメントしました。(最初にこのこと書けば良かったです)

> hituziさんが自力で実装してPRを送れば歓迎されると思います！😆

RailsとVueのプラクティスがまだ終わってない為、自分で実装できるか判断できませんが、実装できたらやりたいですね。あと、忘れそうなので画面遷移無し版のissueも作成しておきます。

@ima1zumi 

> この機能が欲しい場合は別issueで立ててもらえると検討・対応しやすくなるのでご検討ください 😄

了解です。欲しくなったらissue作成します。

**Comment by ima1zumi** [comment]
#2351 でマージ済のためCloseします。
