### ISSUE TITLE
Q&Aを削除できなくする（または削除を思いとどまらせる）

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1531]
自己解決した際にQ&Aの投稿を削除する生徒がいるが、自己解決した場合も知見を共有した方がよい。

## 案1

- Q&Aは削除できなくする（必ずベストアンサーを決定してクローズする）

## 案2

- 「自己解決した場合は削除せずに回答を書き込んでください。本当に削除しますか？」のようなプロンプトを出して削除を思いとどまらせる

## 参考

<img width="761" alt="Screen Shot 2020-04-20 at 19 06 59" src="https://user-images.githubusercontent.com/1148320/79740144-26c4e080-833a-11ea-8a5b-2270ace141a1.png">

**Comment by JunichiIto** [comment]
これ、あった方がいいかも。

**Comment by machida** [comment]
admin以外はQuestionの削除リンクは非表示にする。

**Comment by komagata** [comment]
:memo: ミーティングで案2で行こうということになった。

**Comment by ai-24** [comment]
@komagata @machida 
お疲れ様です。
お忙しいところ申し訳ありませんが、「プロンプトを出す」の認識が曖昧でして確認させください。
プロンプトを出す＝下記のような確認画面を出すのだと認識しているのですが、
現在の仕様はQ＆Aの削除ボタンを押すと以下のプロンプトが表示されています。
今回の実装はこちらの文言を変更するという事でよろしいでしょうか？
<img width="849" alt="スクリーンショット 2022-06-08 0 08 09" src="https://user-images.githubusercontent.com/76685187/172416226-b720577d-f7bf-4199-824a-03c92af9c4d7.png">

**Comment by ai-24** [comment]
上記の質問ですが文言の変更でOKとの事をMTGで確認し解決しました！

**Comment by ai-24** [comment]
本番環境での動作確認ができましたのでcloseします！
