### ISSUE TITLE
issueの棚卸しをする

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1534]
issueを検索すると「すでに終わっているのでは？」と思われるissueがちらほら存在する。

以下は"Q&A"で検索した例。下の方にあるissueはすでに対応が終わってそう。

<img width="1027" alt="Screen Shot 2020-04-20 at 19 23 10" src="https://user-images.githubusercontent.com/1148320/79741600-7efce200-833c-11ea-9dde-09ed3b622056.png">

その他にも重複しているissueや、「これはもう必要ないのでは」「結局誰も困ってなさそう」みたいなissueも積極的にクローズして、issueを数十件に抑えたい。（多すぎると優先順位付けも大変になりそう）

**Comment by ima1zumi** [comment]
あげます！

**Comment by JunichiIto** [comment]
まさにこの目的でstale botが導入されました 🎉 
というわけでclose。
