### ISSUE TITLE
提出物一覧のユーザーアイコンにroleを示す枠線が出ていない

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1545]

**Comment by kotakanazawa** [comment]
@machida さん、Issue内容の確認をさせてください🙇🏻‍♂️

「画像1のような枠線を、提出物一覧ページ（画像2）のアイコンにも表示する」ということでよろしいでしょうか？

画像1（提出物詳細ページ）
![スクリーンショット_2020-05-18_9_35_42](https://user-images.githubusercontent.com/28076271/82164406-65bf6500-98eb-11ea-9df5-d6aae76b2f32.png)

画像2（提出物一覧ページ）
![スクリーンショット_2020-05-18_9_35_27](https://user-images.githubusercontent.com/28076271/82164402-61934780-98eb-11ea-97fa-498966ed85f5.png)

**Comment by machida** [comment]
わかりにくくてすいません。
以下で示したアイコンアイコン画像のところになりますー

## 日報一覧

枠線がある
https://bootcamp.fjord.jp/reports?page=325

<img width="936" alt="貼り付けた画像_2020_05_18_11_04" src="https://user-images.githubusercontent.com/168265/82167644-6d850680-98f7-11ea-9a83-0e032e826198.png">


## 提出物一覧

枠線がない
https://bootcamp.fjord.jp/products?page=60

<img width="1089" alt="貼り付けた画像_2020_05_18_11_05" src="https://user-images.githubusercontent.com/168265/82167668-7b3a8c00-98f7-11ea-969b-2d2b38304e75.png">

## やりたいこと

提出物一覧も、日報一覧のように、ユーザーアイコンにclassをつけたい（classを付けると枠線が出る）。

### 日報一覧の画像のhtml

![image](https://user-images.githubusercontent.com/168265/82167754-b472fc00-98f7-11ea-871a-d73d9b32a38a.png)

### 提出物一覧の画像のhtml

![image](https://user-images.githubusercontent.com/168265/82167774-bfc62780-98f7-11ea-8100-e60c64f38925.png)

**Comment by kotakanazawa** [comment]
@machida 
なるほど、理解しました〜！ありがとうございます！！

**Comment by machida** [comment]
よろしくお願いしますー！！
