### ISSUE TITLE
未読の通知がゼロになっても通知一覧にジャンプしたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1555]
未読の通知がゼロ件になると 🔔 アイコンをクリックしても反応がなくなってしまう。
たまに既読の通知一覧を確認したくなるときがあるので、なんらかの方法で通知一覧に移動する方法があると嬉しい。

<img width="97" alt="Screen Shot 2020-05-13 at 18 38 05" src="https://user-images.githubusercontent.com/1148320/81797001-2a1e4700-9549-11ea-96c2-b197b23acc28.png">

今は https://bootcamp.fjord.jp/notifications というURLをブラウザに手入力しています。
「運用で回避」できてるので、優先順位はそこまで高くないかも。

**Comment by machida** [comment]
確かにこれありますね！
Issueありがとうございますー
こちら対応しました！！

**Comment by JunichiIto** [comment]
@machida 迅速な対応、ありがとうございます！助かります〜😄

**Comment by komagata** [comment]
@machida ありがとうございます！
