### ISSUE TITLE
secret_key_baseが公開されているのを辞める

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1557]

**Comment by komagata** [comment]
📝 Cloud Run移行時に対応される予定。

**Comment by bluerabbit** [comment]
これ単にhttps://github.com/fjordllc/bootcamp/pull/1813/commits/434cf5d50fa041e73bb027a6f94ac9edfab6f5de するだけなので先にこの対応だけ入れた方がいいかも

**Comment by bluerabbit** [comment]
📝 これ実際には公開されているsecret_key_baseは使われておらずherokuでは環境変数からsecret_key_baseを設定していたので意味のない値でした。なのでセーフ 👮‍♂️
