### ISSUE TITLE
コードブロックが折り返されずに横スクロールが発生する

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1569]
## 概要

コードブロックが折り返されずに横スクロールが発生する

## 再現手順

1. https://bootcamp.fjord.jp/reports/13558 にアクセス。
2. `search?q=%E3%83%97...`で始まるコードブロックが折り返されずに表示される

## 期待される振る舞い

白い枠をはみ出しそうになったら折り返す

## スクリーンショット

<img width="942" alt="Screen Shot 2020-05-20 at 8 36 12" src="https://user-images.githubusercontent.com/1148320/82388614-fb3a3080-9a74-11ea-99e9-6864574a055d.png">

## 環境

 - OS: macOS 10.15.4
 - ブラウザ: Chrome
 - バージョン: 81

**Comment by komagata** [comment]
@machida 英語で空白も無い文字列が続いた場合に文字を壊さず折り返すのは難しいと思うので、横幅を超える場合は`overflow: scroll;`みたいな動きでも良いと思います。
