### ISSUE TITLE
Q&Aの解決したQには解決済スタンプを表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1574]

**Comment by HiroVodka** [comment]
@komagata 
解決済みの質問には「解決済み」という文字を表示させることは出来たのですが、この状態で町田さんにデザインを依頼すればよろしいでしょうか？？
![image](https://user-images.githubusercontent.com/58872020/88180510-73d18f00-cc68-11ea-8b2e-f3e8c88769e8.png)

**Comment by HiroVodka** [comment]
@komagata こちらいかがでしょうか？

**Comment by komagata** [comment]
@HiroVodka はい、デザインの依頼をお願いします。

**Comment by HiroVodka** [comment]
@komagata 承知しました！
