### ISSUE TITLE
料金説明のお試し期間・支払日を動的に生成したい

### ISSUE THREAD

**Issue by tosite** [fjordllc/bootcamp#1577]
## 概要
![image](https://user-images.githubusercontent.com/24952964/82565922-2710ff80-9bb6-11ea-8f59-696ede08cf6d.png)

----

ここの部分に今日の日付から動的に「お試し期間終了日」や「支払日」などの情報を生成・表示するようにしたいです。

**Comment by ima1zumi** [comment]
Merge済のためCloseします。
