### ISSUE TITLE
質問があるプラクティスには、質問タブのところに質問の件数を表示したい

### ISSUE THREAD

**Issue by mikihito-h** [fjordllc/bootcamp#1589]
プラクティスを進める上で、過去に投稿された質問の内容がとても参考になることが多いのですが、現在の仕様では質問がない場合でも質問タグを押して質問があるかチェックしなければいけません。
質問の件数が表示されていた方が、過去の質問をうっかり見逃すことが減るのと、上記の手間も省けるので良いのではと思いました。

## イメージ
![image](https://user-images.githubusercontent.com/53965479/82869837-e1638680-9f69-11ea-85a3-7e6b8788c086.png)

**Comment by komagata** [comment]
@mikihito-h 確かにですね！

**Comment by masamune17** [comment]
@komagata さんご確認です
質問タブに表示する質問の個数は、未解決と解決済みの合計の個数でよろしいでしょうか？
