### ISSUE TITLE
リンク切れチェックをしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1591]
下記の中のURLのリンク先がアクセスできるかチェックする。

- 全てのプラクティスの本文と完了条件
- 全てのDocsの本文

アクセスできないURLの一覧を`info@fjord.jp`にメールする。（アクセスできれば送らない）

プログラムはrakeタスクとして用意する。

いつ実行するなどのHeroku schedulerの設定は @komagata の方でやります。

**Comment by mikihito-h** [comment]
@komagata 
リンク切れを見つけた際にメールに掲載する情報について質問があります。

要件に「アクセスできないURLの一覧をinfo@fjord.jpにメールする。」と書かれていますが、他にメールに載せるべき情報はありますでしょうか？？

現在、リンク切れを発見した場合に送るメールは下記のようになっています。
![image](https://user-images.githubusercontent.com/53965479/83329955-33d4d800-a2c7-11ea-9fca-07cab22d8c10.png)

**Comment by mikihito-h** [comment]
@komagata 
度々すみません。
上記のメールの仕様についての質問いかがでしょうか？？🙇‍♀️

**Comment by machida** [comment]
@mikihito-h 
そのリンクがどのページにあるか、そのリンクがあるページのURLも一緒にお知らせしてくれると助かりますー

**Comment by mikihito-h** [comment]
@machida 
了解です！
リンク切れURLがあるページのURLも載せるようにします。
