### ISSUE TITLE
参考書籍の一覧が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1592]
- プラクティスに複数の参考書籍を登録できるようにしたい。
- 参考書籍は下記のカラムが最低限欲しい。
  - タイトル
  - ASIN
- プラクティスに参考書籍を登録できるようにしたい。
- プラクティスの個別ページにそのプラクティスの参考書籍を一覧できるようにしたい。

**Comment by kotakanazawa** [comment]
@komagata 

「参考書籍テーブル」について、以下の内容で作成する方向で考えておりますが、テーブル名やカラム名などおかしな点があればご指摘いただけると幸いです。

- reference_books
    - title:string
    - asin:integer
    - description:text
    - owned:boolean

`owned`に関しては、「フィヨルドオフィスにあるかどうか？」の情報を保存する意図で追加しました。
というのも、下記ページの参考書籍欄に「フィヨルドオフィスにあります。」という文章が3つあり、重複しているためです。
[Ruby初級 \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/26)

**Comment by kotakanazawa** [comment]
↑2020/06/12 質問・雑談ルームにて相談したことのメモ

- ひとまずは `title`と`asin`だけで作る
- asinはstring型でOK

**Comment by kotakanazawa** [comment]
@komagata 

参考書籍を登録するページまでの流れについて、以下のどちらがいいのか考えています。

## 1．管理者ページから登録

![管理者ページから登録](https://user-images.githubusercontent.com/28076271/85104372-742ed280-b243-11ea-9f74-c048b15beec0.jpg)

## 2．プラクティス詳細ページから登録

![プラクティス詳細ページから登録](https://user-images.githubusercontent.com/28076271/85104412-84df4880-b243-11ea-9594-c6c4972cf128.jpg)

個人的には2）のプラクティス詳細ページから登録できたほうが楽だと思うのですが、いかがでしょうか？

**Comment by komagata** [comment]
@kotakanazawa 日報のページと同じように登録ページ・編集ページで追加・編集・削除ができるようにしたいです。

**Comment by kotakanazawa** [comment]
@komagata 
かしこまりました！
また、導線をどうしたらいいのかわからずにいます。以下の2パターンで迷っていました。

- 各プラクティス詳細ページ → 参考書籍登録・編集ページ
- 各プラクティス詳細ページ → 管理者メニューページ → 参考書籍登録・編集ページ

UIがうまく想像できません…。

**Comment by komagata** [comment]
@kotakanazawa 参考書籍登録・編集ページが個別に存在するのではなく、日報の学習時間と同じように日報の登録・編集ページに参考書籍の登録・編集・削除機能がある感じでお願いしたいです。

**Comment by kotakanazawa** [comment]
@komagata 
イメージ的には、以下のような感じでしょうか？

![管理者メニューページ](https://user-images.githubusercontent.com/28076271/85250501-b64d5380-b491-11ea-87f6-d911c16cf538.jpg)

- 各プラクティスの管理者メニューページで参考書籍とASINの登録、編集、削除ができる
- 複数の書籍を登録できる

**Comment by komagata** [comment]
@kotakanazawa 入力枠は横並びになるイメージです。

**Comment by kotakanazawa** [comment]
@komagata 承知いたしました！
