### ISSUE TITLE
卒業制作一覧のページが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1597]
## なぜ？

フィヨルドブートキャンプの卒業生のレベルをこれから入学を検討している方、就職先の企業様に知ってもらうため。

## やること

- ポートフォリオの作品（Work）に卒業制作かどうかのチェック項目をもつ。
- 上記が覧できるページを作る。

[![Image from Gyazo](https://i.gyazo.com/e13c7b9efcd6e6702abab7b9daf511bd.png)](https://gyazo.com/e13c7b9efcd6e6702abab7b9daf511bd)

**Comment by tetishi** [comment]
@komagata 
卒業制作が一覧できるページをどこに作るのか確認したいです。
以下のスクリーンショットのように提出物の右側に新たに卒業制作のタブを追加し、それをクリックすると卒業制作が一覧できるページに飛ぶという感じで大丈夫でしょうか？

![machidaのプロフィール___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/85195776-3d72be00-b310-11ea-94a2-cbf86fa82ee6.png)

**Comment by komagata** [comment]
入学を検討している人（ログインしてない人）向けのページなのでトップページにだけリンクがあるイメージでいいと思います。

`/graduation_works`

みたいな感じで。

**Comment by tetishi** [comment]
@komagata 
わかりました！
回答ありがとうございます。
