### ISSUE TITLE
Chromeで日報を編集すると学習日の上にカレンダーマークが表示される

### ISSUE THREAD

**Issue by kotakanazawa** [fjordllc/bootcamp#1605]
## 概要

- Chromeブラウザで日報を編集すると、学習日の上にカレンダーマークが表示される。
- ブラウザをリロードしても消えない。
- safariだと表示されない。

## 再現手順

- 日報作成ページを開く
- カレンダーマークが表示される

## 期待される振る舞い

カレンダーマークが表示されないこと。

## スクリーンショット

![スクリーンショット 2020-06-01 9 46 33](https://user-images.githubusercontent.com/28076271/83366957-1306a280-a3ed-11ea-9bee-4a1db8014c6d.jpg)

## 環境

 - Mac OS X 10.14.6
 - ブラウザ
     - chrome
         - バージョン: 83.0.4103.61（Official Build） （64 ビット）
     - safari
         - バージョン: 13.1 (14609.1.20.111.8)

**Comment by machida** [comment]
ありがとうございます！Chromeのアップデートで何かあったのかも
僕対応します

**Comment by kotakanazawa** [comment]
ありがとうございます🙇🏻‍♂️
