### ISSUE TITLE
今日、席を予約していたら予約している席をダッシュボードに表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1624]
- 今日席を予約してたのでオフィスに来た。
- オフィス到着
- どの席を予約してたっけ？
- ブートキャンプアプリを開く
- 席予約ページへ移動
- 今日の日付を確認し、自分の名前が入ってる枠を探す

...というのが面倒なので、このように表示したい。

<img width="742" alt="貼り付けた画像_2020_06_04_15_50" src="https://user-images.githubusercontent.com/168265/83724411-334b9100-a67b-11ea-8bd3-98c6b13366ca.png">

**Comment by mikihito-h** [comment]
@machida 

仕様の確認をしたいのですが、こんな感じ👇でいいでしょうか？？

![image](https://user-images.githubusercontent.com/53965479/83830836-0a7dd700-a721-11ea-91d9-06b529d9c288.png)

**Comment by machida** [comment]
@mikihito-h はい！そこでお願いしますー 表示のデザインは僕の方でやります

**Comment by mikihito-h** [comment]
@machida 

ダッシュボード画面の他に、ユーザーのプロフィール画面にも表示するようにしますか？

**Comment by machida** [comment]
@mikihito-h 

ダッシュボード画面の他に、ユーザーのプロフィール画面にも表示することは考えてませんでした。ただ、僕が考えてなかったからといって無くすのではなく、@mikihito-h さんがなぜダッシュボード画面の他に、ユーザーのプロフィール画面にも表示したいと思ったのかが知りたいです。僕が見落としていたユーザーの動きなどがあるかもしれないので確認したいです。

僕が想定していたユーザーの動きは、

---

- 今日席を予約してたのでオフィスに来た。
- オフィス到着
- どの席を予約してたっけ？
- ブートキャンプアプリを開く
- 席予約ページへ移動
- 今日の日付を確認し、自分の名前が入ってる枠を探す

...というのが面倒なので、このように表示したい。

---

というものでした。ユーザーは座席に着く前なので、スマホで席を確認することを想定しています。

**Comment by mikihito-h** [comment]
@machida 

> スマホで席を確認することを想定しています。

自分はパソコンで確認することを想定してたんですけど、よく考えたら、座席に着く前だったらスマホで確認しますよね😅

結論から言うと、僕がプロフィール画面にも表示させようとした理由は、全て勘違いから生まれていました。

まず、ダッシューボード画面というのは新しくログインした時にのみ表示されるもので、ログイン後にダッシュボードに飛べるリンクはないと思っていました。なので、一度ログインしていると検索バーに`https://bootcamp.fjord.jp/`を直接入力するか、ログアウトしてからまたログインし直さないとダッシュボードは確認できないものと思ってました。なので、プロフィールページにも座席を表示させた方がユーザーが確認しやすいのではと思いました。

しかし先ほど、画面左上のピヨルドマークを押せばダッシュボード画面に飛べるということに初めて気づきました😭
![image](https://user-images.githubusercontent.com/53965479/83932657-09ab7a80-a7df-11ea-9e30-5db233b9c796.png)

といった感じで、プロフィール画面にも表示させようと思った理由は僕の勘違いによるものでした。

**Comment by komagata** [comment]
なるほど〜と思ったのでIssue作りました〜 #1634
