### ISSUE TITLE
卒業生のダッシュボード、その卒業生のユーザー個別ページにはニコニコカレンダーを非表示にしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1627]

**Comment by sasabo-git** [comment]
@machida 
すみませんが、１点確認させて下さい。
ダッシュボードもニコニコカレンダーを非表示にするということですが、もともとダッシュボードにはニコニコカレンダーは表示されていないようです。このissueは個別ページからニコニコカレンダーを削除すれば良いでしょうか？

**Comment by machida** [comment]
@sasabo-git すいません、僕の勘違いでした！個別ページで非表示をお願いします🙏

**Comment by sasabo-git** [comment]
↑承知しました！
