### ISSUE TITLE
メニューに「ダッシュボード」「自分のプロフィール」というリンクが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1634]

**Comment by sdk-quadra** [comment]
すいません、聞き逃していたかもしれません。
* 「ダッシュボード」「自分のプロフィール」のリンクの位置は、メニューのどこがいいでしょうか？
@komagata 

![image](https://user-images.githubusercontent.com/39234092/86449925-cd265c80-bd53-11ea-894a-ea0c1ca8f9c0.png)

**Comment by komagata** [comment]
@machida こちらどこがいいでしょうか、このままでいいですかね〜？

**Comment by ima1zumi** [comment]
Merge済みなのでCloseします。
