### ISSUE TITLE
emojiとその入力数の表示が重なっている

### ISSUE THREAD

**Issue by kotakanazawa** [fjordllc/bootcamp#1635]
## 概要

- Chromeブラウザ上で、emoji とその入力数の表示が重なっている
- safariだと正常に表示される

## 再現手順

- 日報、お知らせ、Q&Aなど、emoji が入力されているページにアクセスする
- emoji の入力数の表示を確認する

## 期待される振る舞い

emoji とその入力数の表示が重ならないこと。

## スクリーンショット

https://bootcamp.fjord.jp/reports/14143

Chrome
![chrome](https://user-images.githubusercontent.com/28076271/83958637-0e3f6400-a8af-11ea-8c81-b385e3994e7f.jpg)

safari
![safari](https://user-images.githubusercontent.com/28076271/83958641-23b48e00-a8af-11ea-9d58-aa984995728c.jpg)

## 環境

 - Mac OS X 10.14.6
 - ブラウザ
     - chrome
         - バージョン: 83.0.4103.61（Official Build） （64 ビット）
     - safari
         - バージョン: 13.1 (14609.1.20.111.8)

**Comment by ima1zumi** [comment]
直ってるように見えるのでCloseします。
