### ISSUE TITLE
[分報]分報でidobataみたいにページングしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1638]
初めは最新の数件（20件ぐらい？）を表示しておいて、スクロールしたらそれ以前の20件を出す。さらにスクロールしたら・・・という風にしたい。

現状は全ての投稿を表示するようになっているため、すぐに画面が重くなってしまうため。

**Comment by kaitoyoshioka** [comment]
- MTGで決まったこと
  - 分報は上から下に最新順で並ぶ
  - 分報ページにいくと、まず、最新20件の分報が読み込まれ、ボトムにスクロールすると、さらに20件読み込まれる。(無限スクロール)
