### ISSUE TITLE
イベント申し込みページにgoogleカレンダーへのリンクがほしい

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#1643]
## 概要

イベント申し込みページからgoogleカレンダーへ飛べるようになってほしい。
タイトル・日時・URLを登録できるようになってほしい。

イメージ
![image](https://user-images.githubusercontent.com/52617472/84150813-5d4aec00-aa9d-11ea-814c-e106d18adfcd.png)

**Comment by machida** [comment]
これいいですね！！

**Comment by machida** [comment]
参考
https://naoyashiga.hatenablog.com/entry/2013/07/07/194028

**Comment by HiroVodka** [comment]
> 参考
> https://naoyashiga.hatenablog.com/entry/2013/07/07/194028

参考にします！！
ありがとうございます🙇‍♂️🙇‍♂️

**Comment by komagata** [comment]
@HiroVodka 本番で動作確認してOKだったら「IssueのClose + カンバンで完了へ移す」という作業をお願いします〜

**Comment by HiroVodka** [comment]
@komagata 承知しました〜！
