### ISSUE TITLE
プラクティス一覧で、カテゴリに紐づくすべてのプラクティスを終えたら、そのカテゴリに完了マークを表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1645]
<img width="713" alt="貼り付けた画像_2020_09_24_14_42" src="https://user-images.githubusercontent.com/168265/94105440-352ca080-fe74-11ea-8634-44bed7b77dfa.png">

こんな感じで出したい

**Comment by MashioSano** [comment]
本番環境でPRの反映を確認できましたのでクローズします。
