### ISSUE TITLE
プラクティスの日報一覧画面で、提出日が最新の日報が一番上に表示されるようにしたい

### ISSUE THREAD

**Issue by mikihito-h** [fjordllc/bootcamp#1656]
## 概要
プラクティスごとの日報一覧画面の日報の順番が、現状では更新日時順になっている。
日報には更新日時が表示されないようになり( #1587 )、何順に表示されているかわかりにくいので提出日順にすると良いのではと思いました。

## 期待される振る舞い
提出日が最新の日報が一番上に表示されるようにしたい。

## 現状のスクリーンショット

![image](https://user-images.githubusercontent.com/53965479/84298127-982a4e00-ab89-11ea-80f0-b8fc052b042a.png)

**Comment by komagata** [comment]
確かにっすね。

**Comment by ima1zumi** [comment]
未解決
