### ISSUE TITLE
本名は管理者のみが見れるようにしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1657]
就職活動していることが会社にばれたくない人もいるため。

**Comment by JunichiIto** [comment]
%s/管理者飲み/管理者のみ/

**Comment by tetishi** [comment]
@komagata 
すみません、修了証明書に書き出される名前は本名のままで良いでしょうか？それともユーザー名に変えた方が良いでしょうか？
![Kimura_Tadasiの卒業証書](https://user-images.githubusercontent.com/44915479/87756529-0676c600-c844-11ea-971c-47f3a56e5333.png)

**Comment by komagata** [comment]
@tetishi 修了証明書は削除予定なのでそのままでいいです。

**Comment by tetishi** [comment]
@komagata 
承知しました。
お返事ありがとうございます。
