### ISSUE TITLE
コメントと同時に確認済みにするボタンを用意する

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1664]
## 困っていること

日報や提出物にメンターがコメントする際、本当は「確認済み」にしなければいけないのに、コメントを入れるだけで満足して離脱してしまうケースがある。

例

- https://bootcamp.fjord.jp/products/3991
- https://bootcamp.fjord.jp/products/4001

## 解決策（案）

pull requestのClose pull requestボタンのように「コメントと同時に確認済みにするボタン」を追加する。

<img width="353" alt="Screen Shot 2020-06-17 at 19 28 29" src="https://user-images.githubusercontent.com/1148320/84887511-ce5b5680-b0d0-11ea-994d-5e5e2f4c503f.png">

ただし、これはこれで押し間違いすると問題なので、誤爆を防止する工夫が必要かも。（特に提出物）

**Comment by sdk-quadra** [comment]
* 「コメントして確認済にする」ボタンの設置場所とデザイン、文言の確認をしたいです。
    *   ボタンの文言に「確認済」という単語を使うと、確認済のスタンプが押されたとみなされテストが落ちるので、「コメントして確認OKにする」=> githubの「close pull request」を倣って短く、「確認OKにする」という語でもいいでしょうか。
    * 設置場所もgithubと同じように、「コメントする」の左側の方がいいでしょうか。
    * ボタンは緑でいいでしょうか。（ページ内に色が多くなるのが少し気掛かりです）

![image](https://user-images.githubusercontent.com/39234092/89370640-3961fa80-d71c-11ea-8cf5-99d3658f83a5.png)

* 提出物で「確認OKにする」場合は「本当に確認OKにしますか？」のalert鳴らす、という仕様でいいでしょうか。
* 確認済みの場合は、「確認OKにする」のボタンは非表示でいいでしょうか？
￼
![image](https://user-images.githubusercontent.com/39234092/89370651-3ebf4500-d71c-11ea-99a0-268f6ea00c05.png)

@komagata 
@machida

**Comment by ima1zumi** [comment]
こちらマージ済ですのでCloseします〜
