### ISSUE TITLE
ユーザーのプロフィールのHTMLがエスケープされていない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1666]
<img width="420" alt="スクリーンショット 2020-06-17 23 53 52" src="https://user-images.githubusercontent.com/16577/84913882-f3ae8b80-b0f5-11ea-941f-73aea84b229e.png">

https://bootcamp.fjord.jp/users/620

「好きなHTMLタグ`<blink></blink>`です」と書いてあるのがHTMLタグがそのまま出てしまっている。

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/issues/1665
この実装でお願いします
