### ISSUE TITLE
全未チェックの日報をタブで開くボタンが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1675]
<img width="695" alt="スクリーンショット 2020-06-24 13 24 36" src="https://user-images.githubusercontent.com/16577/85500283-3274a200-b61e-11ea-982f-62b96aadd5a0.png">

メンターとしてチェックするときに毎回全部を一個づつタブで開いているので一気に開くボタンが欲しい。JSでかけそう。

そのボタンはmentorのみ表示したい。

ページャーがあったとしてもそのページのリンクだけを開くのでOK。

**Comment by mh-mobile** [comment]
**7/22(水)の振り返りMTGで決まったこと**

* 提出物の未返信画面にも開くボタンを追加する。
* 提出物の未チェック画面では開くボタンは使われないが、開くボタンは残したままで良い。
* 通知の未読画面にも開くボタンを追加する。
* 開くボタンのデザインは現状のままで良い。

**Comment by mh-mobile** [comment]
@komagata 

こちらのIssueの本番デプロイが成功しているため、
管理者権限にて本番確認をお願いします。

![image](https://user-images.githubusercontent.com/13811034/88767177-3747eb00-d1b4-11ea-9b34-bfe126a82db4.png)
