### ISSUE TITLE
プラクティスに所要時間の項目が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1676]
プラクティスの個別ページに下記のような表記を追加したい。

所要時間: n時間 (i)

(i)をクリックするとホバーで「過去に完了した人の中央値を表示しています。」と出る。

（(i)の部分はそれっぽいアイコンなどをいれる）

**Comment by komagata** [comment]
📝 実際の数値を出してもらった結果、その数字を採用して問題なさそうだった

**Comment by komagata** [comment]
@sdk-quadra 数値を見た結果、それを採用して問題なさそうでしたので、こちらお願い致します。（中央値でお願いします）

**Comment by sdk-quadra** [comment]
* 所要時間の表示位置についてです。タイトル周りで考えました。
    * 以下のEでいいでしょうか？

## A
* 悪くはないが、タイトルが2行以上になった場合バランスが悪い
![image](https://user-images.githubusercontent.com/39234092/91838251-2a715800-ec88-11ea-8d27-9656b28c9ff7.png)

## B
* 悪くはないが、タイトルの上の空白が気になる
![image](https://user-images.githubusercontent.com/39234092/91838259-2f360c00-ec88-11ea-9e6a-e6c68e61227f.png)

## C
* タイトルの長さによっては所要時間が改行される
![image](https://user-images.githubusercontent.com/39234092/91838272-33622980-ec88-11ea-80f1-c1b5d235730e.png)

## D
* バランスに問題
![image](https://user-images.githubusercontent.com/39234092/91838278-35c48380-ec88-11ea-9da4-5cc75ed2f0d3.png)

## E
* バランスはいいが、タイトルより目立つ（いい位置にいる）
    * 小さく、色を薄くしてタイトルの方を目立たせる事で対応
![image](https://user-images.githubusercontent.com/39234092/91838288-38bf7400-ec88-11ea-86a4-694cf0d02f36.png)

---------------

* 所要時間の表示形式についてです。
    * > 所要時間: n時間 (i)
    * という指定でしたが、小数点は四捨五入などではなく、切り上げでいいでしょうか？
        * この場合、`15分`は`1時間`と表示しますが、ざっと見た感じ生徒はプラクティスのほとんどに30分以上掛かっています。
        * `2時間20分`は`3時間`と表示しますが、生徒に早く終わらせようと焦らないで欲しい、という意図です。

------------------

* ホバー時の挙動についてです。
    * > (i)をクリックするとホバーで「過去に完了した人の中央値を表示しています。」と出る。
    * という指定でしたが、クリックするとホバー、の部分がよく理解できず、以下のようにカーソルを乗せたらテキストを表示、というように作りましたがこれでOKでしょうか？

![image](https://user-images.githubusercontent.com/39234092/91838299-3c52fb00-ec88-11ea-8099-c437940b9809.png)

@komagata 
@machida

**Comment by sdk-quadra** [comment]
### meeting memo:
* mobileにはhoverがない。
* modalにして画面中央で表示。
* modal以外をクリック（タップ）するとmodalが消える。
* [icon例](https://fontawesome.com/icons/info-circle?style=light)

**Comment by sdk-quadra** [comment]
こんな感じで一旦作ってみたんですが、上記も含めデザイン周りに関してアドバイスをいただきたいですー

https://gyazo.com/f787e164c20f6041b59230abfb16c209

@machida

**Comment by machida** [comment]
了解です！

**Comment by machida** [comment]
@sdk-quadra 
確認しました！一旦これでマージお願いしますー！！

**Comment by komagata** [comment]
@machida @sdk-quadra 完全に黒でオーバーレイしてのmodalだとちょっと大袈裟な感じがするのでできれば一般的なmodal windowとは別の下記のようなtooltip的なものができるといいなと思いました。

[![Image from Gyazo](https://i.gyazo.com/d73faa993f3038ed873e6619a43f99c7.gif)](https://gyazo.com/d73faa993f3038ed873e6619a43f99c7)

[Tooltip \| Bulma\-Extensions](https://wikiki.github.io/elements/tooltip/)
