### ISSUE TITLE
docsの内容を変更した際に変更履歴を保存・表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1678]

**Comment by komagata** [comment]
@machida ものすごく複雑になっちゃいそうなので、アプリのメイン機能でなければあまりやりたくない感じがしちゃいます。

**Comment by JunichiIto** [comment]
UIを用意するかは別として、paper-trails gemを入れて履歴を保存するだけならコストは低いかも？

https://github.com/paper-trail-gem/paper_trail

この間「日報を間違って消しちゃった」という人もいたので、このgemを入れておけば比較的簡単に復活できます。（rails consoleから）
「何かあったときの保険としてDocsや日報の変更履歴を残しておく」という程度でお茶を濁すのはどうでしょうか。
（余裕があればUIで確認できるようにすると完璧ですが）

**Comment by komagata** [comment]
@JunichiIto paper_trail gemが便利なのは知ってるんですが、アプリの本質的な複雑性を増やしたくないという思いがあります。

Docs（Wiki）の機能はおまけ的なもので基本的にはブログ機能が公開されたら教材はそこに移して公開していきたいと思っています。

**Comment by JunichiIto** [comment]
> データのバージョン管理というのは僕はよく作ってしまいがちな不要な機能の筆頭のように捉えちゃっています。

たしかにー・・・なんですが、つい先日、業務の本番環境でうっかり消してはいけないデータを消してしまって真っ青になっていたところ、たまたまpaper_trailで履歴を取っていたので、そこからすぐに復旧できた、という経験がありまして。
そのとき初めて「あって良かった、paper_trail！！」と思いました。

とはいえ、町田さんのリクエストは別に保険を用意しておきたいというものでもないので、駒形さんのジャッジを採用する、でも問題ないと思います〜 🙆‍♂️
