### ISSUE TITLE
クリックしたら画像を拡大 or オリジナルサイズで見たい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1683]
日報や提出物にスクリーンショットが画像として貼られている場合があるが、縮小されて読みづらいときは、ワンクリックでぱっと確認できるようにしたい。

画像をクリックすると拡大されたり、オリジナルサイズの画像が別タブで開いたりすると嬉しい。

今は画像の上で右クリック→画像を別タブで開くを選択している。

<img width="637" alt="Screen Shot 2020-06-26 at 8 20 44" src="https://user-images.githubusercontent.com/1148320/85804967-feb48c00-b785-11ea-904c-cd8f3018843e.png">

**Comment by JunichiIto** [comment]
これ、地味に不便なので早く対応してくれると嬉しいです〜 🙏

**Comment by komagata** [comment]
完了。
