### ISSUE TITLE
画面幅を狭くするとdocsの著者アイコンがタイトルに被る

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#1686]
## 概要

![image](https://user-images.githubusercontent.com/52617472/85881300-5ac7f080-b818-11ea-94cd-35977fc471d5.png)

## 期待される振る舞い

![image](https://user-images.githubusercontent.com/52617472/85881567-c4e09580-b818-11ea-84eb-52717149789d.png)

**Comment by machida** [comment]
こちら対応しましたー
