### ISSUE TITLE
データがないときはその旨表示してほしい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1688]
メンターとして左サイドメニューの日報アイコンをクリックすると、「未チェックの日報」一覧が開く。
このとき、未チェックの日報が1つもないと、以下のように一覧画面がのっぺらぼうになる。

<img width="467" alt="Screen Shot 2020-06-29 at 14 16 08" src="https://user-images.githubusercontent.com/1148320/85981283-eb701d80-ba1e-11ea-9757-e4b3eeb64474.png">

たまにJSの描画が遅くて一覧が表示されるまで数秒待たされるときがあるので、反射的に数秒間画面をぼーっと眺めてしまい、それから「あ、データがないのか」と気づいた。

データがないときは「データがありません」というメッセージを標示してくれた方がユーザーフレンドリーじゃないかなーと思います。（日報以外の画面でも同じ問題が起きる可能性あり）

**Comment by machida** [comment]
こちら一通りの画面で0件のときの表示を入れたので一旦closeにさせていただきます。
未対応のページを発見しましたら、別Issueで対応していきますー
