### ISSUE TITLE
Wherebyのリンク先

### ISSUE THREAD

**Issue by sdk-quadra** [fjordllc/bootcamp#1691]
## 概要
* リンク先が適切でない。

## 再現手順

* プラクティス「[開発に参加するための準備をする](https://bootcamp.fjord.jp/practices/159)」内にあるリンク
「Wherebyを使おう」のリンク先が[Google Hangout](https://bootcamp.fjord.jp/pages/181)になっている。

## 期待される振る舞い
* ページの下部では、[適切なURL](https://fjord.whereby.com/meeting)なので、これに統一すべき。
* スクラムに初参加する時に、上記の間違ったリンク先で紹介されているURLでずっと待機していて、かなり焦った。

**Comment by komagata** [comment]
@sdk-quadra 申し訳ありません、上記修正しました。
