### ISSUE TITLE
GitHubの草が途中で途切れている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1693]
<img width="584" alt="スクリーンショット 2020-07-02 15 35 47" src="https://user-images.githubusercontent.com/16577/86324640-d5aa6480-bc79-11ea-96b4-0eec30d14060.png">

**Comment by komagata** [comment]
@machida こちらお手隙でお願いします〜（急ぎではないです〜）

**Comment by ima1zumi** [comment]
モバイル版も切れているので、合わせて修正可能であれば修正していただけるとありがたいです🙇‍♂️

**Comment by mh-mobile** [comment]
解決済みのためクローズします。
