### ISSUE TITLE
「Pull Request を行う」プラクティスの提出物が消えている

### ISSUE THREAD

**Issue by shibaaa647** [fjordllc/bootcamp#1694]
## 概要
- 「Pull Request を行う」プラクティスの提出物一覧が1人の生徒のみで、他の生徒の提出物が消えている。
- 個人のページがら提出物一覧をみても「Pull Request を行う」プラクティスの提出物が消えている。

## 再現手順

1. プラクティス一覧から「Pull Request を行う」のプラクティスにアクセス。
1. 「提出物」タブにアクセス。

## 期待される振る舞い

提出した提出物を見れるようにしたい。

## スクリーンショット

[![image](https://user-images.githubusercontent.com/56685224/86426852-b23bf400-bd23-11ea-8b0c-88abbab304bb.png)](https://user-images.githubusercontent.com/56685224/86426852-b23bf400-bd23-11ea-8b0c-88abbab304bb.png)

**Comment by kotakanazawa** [comment]
[Pull Request を行う \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/124)

こちらのプラクティス、現在だとそもそも提出物がないプラクティスですね〜。
同じユーザーで、以下プラクティスでも同様の現象が起きています。
[Git の基本を理解する \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/48)

もしかして、現在は提出物がないプラクティスでも昔は「こちら読みました〜」みたいな感じで提出物的なものがあったっぽい？
提出物がないプラクティスだとそれが確認できます。
- [フィヨルドブートキャンプへようこそ！ \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/138/products)
- [GitHubへの登録 \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/128/products)

よって、バグではなく仕様ですかね？

## 提案

「提出物がないプラクティスでは、提出物タブを非表示にする」

こうするとユーザーが迷わなくて済むのかなと思いました。

**Comment by komagata** [comment]
このプラクティスは提出物が不要なプラクティスになっているので、提出物が見えないと言うのは問題無いですが、過去の提出物が表示されてるのは問題ですね。

途中で提出物の有無が変更された場合を考慮できていなかったです。

別途、提出物が不要なプラクティスでは提出物のタブを非表示にするIssueを作成します。

**Comment by shibaaa647** [comment]
@kotakanazawa 
>こちらのプラクティス、現在だとそもそも提出物がないプラクティスですね〜。

なるほど、バグだと思ってしまいましたが僕の早とちりでした🙇‍♂️

@komagata 
>別途、提出物が不要なプラクティスでは提出物のタブを非表示にするIssueを作成します。

駒形さんご対応ありがとうございます。

**Comment by komagata** [comment]
#1695 で対応することになったのでこちらはClose
