### ISSUE TITLE
Docsにタグを付けて、タグに紐づくDocsの一覧を出すようにし、Docsを探しやすくしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1704]
- Docsの登録、編集画面にタグの入力を追加
- Docsについているタグの一覧ページ作成
- タグに紐づくDocsの一覧ページ作成
- よく使われているタグの一覧を出すというのもやりたい（要議論）

**Comment by sasabo-git** [comment]
@machida さん　仕様について確認させて下さい🙏
> Docsについているタグの一覧ページ作成

これはDocsの一覧ページにタグを表示すれば良いのでしょうか？（下記イメージ参照）
それとも、タグのみの一覧が表示されるページが必要ということでしょうか？

![tag_sample](https://user-images.githubusercontent.com/60720255/87618310-81f94a00-c754-11ea-8376-c4ef561b5d62.png)

> よく使われているタグの一覧を出すというのもやりたい（要議論）

こちらはこのIssueで対応しますか？

**Comment by machida** [comment]
@sasabo-git 

ここにタグの一覧を出すところまではこのIssueでやりたいと思います。

<img width="1413" alt="貼り付けた画像_2020_07_16_11_14" src="https://user-images.githubusercontent.com/168265/87618737-883bf600-c755-11ea-9985-d7d800af4b00.png">

今後、タグを自由に使うと、タグの数が膨大になる可能性があります。もし、そうなった場合は、記事の多いタグ（よく使われてるタグ）だけを表示し、全てのタグは別ページにしようと思ってるのですが、それは別Issueでいいかと思ってますー

**Comment by machida** [comment]
タグにはスペースやカンマなどは使えなくしたいですね。

**Comment by machida** [comment]
https://yaireo.github.io/tagify/
このIssueには含めないですが、こういうのを入れてからのリリースにしたいと考えてます。

**Comment by sasabo-git** [comment]
承知いたしました！ご確認ありがとうございました！作ってみます〜
