### ISSUE TITLE
メンターのダッシュボードに今日のオフィス利用者の一覧を出したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1706]
アイコン、ユーザー名、本名、座席名を表示。

**Comment by sdk-quadra** [comment]
* 位置や文言など、以下のような感じでいかがでしょうか。
  * 位置：adminだったら表示する、という「就活中のユーザー」の記述の近くに書きました。

<img width="987" alt="スクリーンショット 2020-07-09 12 20 08" src="https://user-images.githubusercontent.com/39234092/86993446-fffea380-c1de-11ea-9888-a8891fd2fc7a.png">

@komagata 
@machida

**Comment by komagata** [comment]
@sdk-quadra いいとおもます！

**Comment by ima1zumi** [comment]
オフィス使用しなくなったのでCloseします
