### ISSUE TITLE
各プラクティスにかかっている時間の平均を出す

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1707]
アプリに組み込むのではなく、その数字が全うかどうかまず見たいので管理者だけが見れるようにプラクティスのタイトルの横にその数字をそれぞれ出す。

プラクティスにかかっている時間 = そのプラクティスに紐づいた日報の合計時間

平均値と中央値が見たい。

複数のプラクティスを一つの日報でやっている場合、その時間をプラクティスの数で割った時間をそのプラクティスにかかった時間とする。

**Comment by sdk-quadra** [comment]
* > タイトルの横にその数字をそれぞれ出す。
  * タイトルの横なので、以下のBのイメージで大丈夫でしょうか？

### A
<img width="1023" alt="スクリーンショット 2020-07-10 17 30 25" src="https://user-images.githubusercontent.com/39234092/87137638-2e13de80-c2d8-11ea-89d3-9472133741eb.png">

### B
<img width="1030" alt="スクリーンショット 2020-07-10 18 01 06" src="https://user-images.githubusercontent.com/39234092/87137627-2b18ee00-c2d8-11ea-8ab4-96c8f0e11e7f.png">

@komagata 
@machida

**Comment by komagata** [comment]
@sdk-quadra はい、大丈夫です〜！

**Comment by masuyama13** [comment]
#1741 で対応済みなのでcloseします〜
