### ISSUE TITLE
書籍一覧に貸出中の書籍一覧を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1714]
全てと貸出中をタブで切り替えられるようにする。

<img width="1705" alt="貼り付けた画像_2020_07_14_12_04" src="https://user-images.githubusercontent.com/168265/87379043-46327900-c5ca-11ea-92c4-98f2516bed67.png">

**Comment by mh-mobile** [comment]
マージ済み かつ 本番動確済みのため、クローズします。
