### ISSUE TITLE
コメント欄にコメントが入力しづらい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1716]
## 概要

コメント欄に長文を入力すると勝手に画面がスクロールして快適にテキストを入力できない。

## 再現手順

1. https://bootcamp.fjord.jp/reports/15445 にアクセス。
2. コメント欄に長いテキストを入力していく。

何かキーを押下した瞬間に勝手に画面がスクロールする↓

![3WHnLH60Hh](https://user-images.githubusercontent.com/1148320/87612501-b285b780-c745-11ea-9358-e152ab263166.gif)

文字入力中に画面が小刻みに上下する↓

![ynGm91beiI](https://user-images.githubusercontent.com/1148320/87612502-b6193e80-c745-11ea-9950-e899122e4b82.gif)

画面が勝手にスクロールした結果、入力中のテキストが完全に隠れてしまって何を入力しているのわからない↓

![CdxCJQmnZC](https://user-images.githubusercontent.com/1148320/87612505-b9142f00-c745-11ea-8d3a-1f06bb5b6100.gif)

## 期待される振る舞い

昨日は普通に動いていた気がするので、以前の動きに戻す。

## 環境

 - OS: macOS 10.15.5
 - ブラウザ: Chrome
 - バージョン: 84.0.4147.89

**Comment by komagata** [comment]
なんだろう？僕の環境では再現できてないです。

- OS: macOS 10.15.5
- ブラウザ: Chrome 83.0.4103.116

**Comment by JunichiIto** [comment]
僕の環境だとSafariやFirefoxでも発生します。

- Firefox = 78.0.2
- Safari = 13.1.1

Chrome extensionのせい？とか思ってシークレットモードのChromeでも試してみましたが、結果は同じでした。

以下のテキストをコピペして、それから文末に追記しようとしても発生しませんか？

```
> 「倒す」のですね笑

AとBという選択肢がある場合、「熟考の末、Aを選択する」という意味で「Aに倒す」という言い方をすることがありますね。
棒をA側に倒す、みたいなニュアンスですかね〜。
（弊社ソニックガーデンだけかな？）

> Javaなら可能なのか

Javaの世界から離れてかなり経つので最新のトレンドはよく変わりませんが、Java界隈やScala界隈はそういう傾向が強い印象があります。
RubyでもRailsじゃないフレームワーク（Hanamiとか？）を使うと、オブジェクト中心のプログラムが組めるのかな〜？そうすると今度はデータベースとの連携で問題が出てきそうですが。

ああ、[インピーダンスミスマッチ](https://www.atmarkit.co.jp/ait/articles/0404/13/news075.html)・・・・。
```

**Comment by komagata** [comment]
@JunichiIto 僕の環境だと上記をコピペして文末に追記しようとしても何も起きないみたいです。

**Comment by JunichiIto** [comment]
あれ〜、おかしいなあ。
あと違いとしてあるとすれば、OSの言語設定とか？（僕は英語）
でもそういう違いが影響しそうな気はしないですしねえ。

Slackで他に再現する人がいないか聞いてみます〜。

**Comment by mikihito-h** [comment]
日報や提出物でも長文を入力すると同じ現象が発生します。

**Comment by june29** [comment]
最初に試したときは再現しなかったのですが、使用しているブラウザの Brave のアップデートがあると気付き、下記バージョンにアップデートしたら再現しました。

>バージョン: 1.11.97 Chromium: 84.0.4147.89（Official Build） （64 ビット）

**Comment by JunichiIto** [comment]
Chrome 84のバグかもしれませんね。駒形さんはChrome 83みたいなので。
ということは84に上げたら駒形さんも再現するかも・・・。（生産性が爆下がりするので要注意💦）

**Comment by udzura** [comment]
Firefoxでは以前からこの現象が起こっている記憶があります！
今のバージョンは78.0.2(64bit)でした
MacOSは諸事情で10.13.6（HighSierra）です。

**Comment by machida** [comment]
これは、応急処置でも対応を入れたいですね。。。

**Comment by machida** [comment]
今まで html タグ（ページ全体）のスクロールをオフにし、メインコンテンツの部分だけにスクロールを表示することで、

<img width="1699" alt="貼り付けた画像_2020_07_20_11_34" src="https://user-images.githubusercontent.com/168265/87894194-fe559b00-ca7c-11ea-9e98-ddf56eecd5dc.png">

このような見た目にしてたのですが、それが今回の不具合の原因になってました。

<img width="1762" alt="貼り付けた画像_2020_07_20_11_35" src="https://user-images.githubusercontent.com/168265/87894258-3b219200-ca7d-11ea-92e1-e0f58f59b801.png">

メインコンテンツのスクロールをオフにし、html タグ（ページ全体）のスクロールをオンにして、手元で確認したところ、不具合が回避されたのが確認できました。

**Comment by JunichiIto** [comment]
@machida おお、今試してみたら直ったかも！
