### ISSUE TITLE
コメントを投稿した後、URLのアンカーを削除したい、もしくはURLのアンカーを自分が投稿したコメントのIDにしてほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1725]
自分へのメンションがあり、それが通知された場合、その通知のリンク先は、

![image](https://user-images.githubusercontent.com/168265/87886154-a48daa80-ca55-11ea-8c5a-cd6b3c1462e5.png)

このようなURLになる。

そのページで自分がコメントを投稿した際、

<img width="394" alt="貼り付けた画像_2020_07_20_6_53" src="https://user-images.githubusercontent.com/168265/87886173-cf77fe80-ca55-11ea-893d-653ea07a6f56.png">

このアンカーが消えて欲しい。

もしくは、URLのアンカーを自分が投稿したコメントのIDにしてほしい。

**Comment by komagata** [comment]
何のタイミングでURLが変わるのか悩ましいっすね〜
