### ISSUE TITLE
メンションがあったときの通知メールにメッセージが表示されない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1726]
## 概要

メンションがあったときの通知メールにメッセージが表示されない。
もしかすると意図的な仕様かもしれないが、他の通知メールにはメッセージが表示されるので不自然。
もし仕様なのであれば「（このメールにはメッセージは表示されません）」みたいな但し書きがほしい。

## スクリーンショット

<img width="706" alt="Screen Shot 2020-07-20 at 7 31 37" src="https://user-images.githubusercontent.com/1148320/87886920-af4b3e00-ca5b-11ea-8ab2-081a2ec6d9dc.png">

ちなみに「このメンションへ」をクリックすると以下のURLに遷移する。

https://bootcamp.fjord.jp/products/4276#comment_28702

**Comment by JunichiIto** [comment]
これ、個人的には早く対応してもらえると嬉しいです。
メールを開くだけで内容を確認できるので。
なにとぞ〜 🙏

**Comment by machida** [comment]
@shibaaaa 

こちらお願いします！！
メンションの本文もメール内に表示されるようにお願いします🙏

**Comment by JunichiIto** [comment]
@shibaaaa  上にも書いたけど、ブートキャンプで今一番欲しい機能なので何卒〜！！ 🙏

**Comment by shibaaaa** [comment]
@machida 
> メンションの本文もメール内に表示されるようにお願いします🙏

承知いたしました！
こちらはデザインを依頼する必要はございますでしょうか？

**Comment by shibaaaa** [comment]
@JunichiIto 
実装頑張ります💪

**Comment by komagata** [comment]
> こちらはデザインを依頼する必要はございますでしょうか？

@shibaaaa やってみて必要そうだったら依頼お願いします〜

**Comment by shibaaaa** [comment]
@komagata 
承知いたしました！

**Comment by shibaaaa** [comment]
@JunichiIto 
こちらのIssueの対応PRがmasterにマージされ、本番環境でメールにメンションの詳細が表示されるようになりました🙌

#### メール画面(僕のGmailの仕様でメールデザインの一部が色味違います)
![image](https://user-images.githubusercontent.com/56685224/94243379-4946cf80-ff52-11ea-937b-a2d85c6707ba.png)

**Comment by JunichiIto** [comment]
@shibaaaa おかげさまでとてもわかりやすくなりました！！どうもありがとうございます〜！ 🎉
