### ISSUE TITLE
参加申し込みしてるイベントでコメントが合った場合は、お知らせから通知されてほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1730]
参加申し込みしてるイベントは自動でwatch が on になる。

**Comment by HiroVodka** [comment]
@machida @komagata こちらのIssueは#1733が終了してから手をつける方が良いのでしょうか？？

**Comment by machida** [comment]
@komagata デザインは #1733 にあとでデザインを入れるので、このIssueは着手しちゃって大丈夫ですが、デザイン以外の面から見てどうでしょう？

**Comment by HiroVodka** [comment]
@komagata こちらいかがでしょうか？？

**Comment by komagata** [comment]
@HiroVodka はい、そのようにお願いします。

**Comment by HiroVodka** [comment]
@komagata 
何度もすいません💦
#1733 がmasterにmargeされて本番環境で使えるようになったらこちらのIssueに着手すればよろしいということでしょうか？？

**Comment by komagata** [comment]
@HiroVodka はいそうです。ただ厳密にはmasterにmergeされたらOKで、本番環境で使えるようになってなくても（デプロイされてなくても）OKです。

**Comment by HiroVodka** [comment]
@komagata 承知しました！それでしたらmergeされるまで手が空いているので別のIssue割り振って頂いてよろしいでしょうか？？

**Comment by HiroVodka** [comment]
＠komagata 承知しました！
