### ISSUE TITLE
DocsのタグにUIをよくするgem/npmを導入する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1732]
![47f894df82180df872afb848553d391d](https://user-images.githubusercontent.com/16577/88144236-99907100-cc33-11ea-8ee2-bddd23d8344c.png)

https://yaireo.github.io/tagify/

こういうやつ。

**Comment by mh-mobile** [comment]
# 候補のnpmパッケージ
* [Tagify](https://www.npmjs.com/package/@yaireo/tagify)
  * 週間ダウンロード: 13646
  * 最終更新: 2 day ago
* [vue-input-tag](https://www.npmjs.com/package/vue-input-tag)
  * 週間ダウンロード数: 4492
  * 最終更新: 4month ago
* [vue-tags-input](https://www.npmjs.com/package/@johmun/vue-tags-input)
  * 週間ダウンロード数: 14224
  * 最終更新:  a year ago

人気度からいえば、Tagfyだろうか

**Comment by mh-mobile** [comment]
@komagata 

こちらのIssueは[Docs(page)にタグを追加 #1718](https://github.com/fjordllc/bootcamp/pull/1718)のPRを
引き継ぐ形でよろしいでしょうか？

**Comment by komagata** [comment]
@mh-mobile 引き継ぐ形ではなく、そこ（add_tag_to_docブランチ）から派生ブランチを作成してadd_tag_to_docに対してPRを出す形でお願いします。

**Comment by mh-mobile** [comment]
@komagata 

なるほど、承知しました！
ありがとうございます！

**Comment by mh-mobile** [comment]
#### TagifyのVueコンポーネントのデモページ
[https://codesandbox.io/s/tagify-tags-component-vue-example-l8ok4?file=/src/App.vue](https://codesandbox.io/s/tagify-tags-component-vue-example-l8ok4?file=/src/App.vue)

#### Tagifyを使う場合の実装の考慮点
* タグ用の配列をVueコンポーネントに持ち、タグの追加・削除のイベントでタグ用の配列を操作する。
* タグ用の配列のカンマ付き文字列をinputのhidden属性として持たせる
  * カンマ付き文字列は算出プロパティでバインディングすれば良さそう。

**Comment by mh-mobile** [comment]
```add_tag_to_doc```ブランチに正常にマージ済みのため、クローズします。
(ローカルでも動確済み)
