### ISSUE TITLE
新着のDocsをすぐに気づけるようにしたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1739]
Docsに新しい記事が投稿されても、自分でDocsを見に行かない限り記事の存在に気づけない。

通知欄に「○○さんがDocsに○○を投稿しました」というような通知が出ると、きちんと情報共有できそう。（今は出てないですよね？）

**Comment by komagata** [comment]
📝 WIPの機能があるので、「WIP」から初めて「提出」した時にのみ通知されるように実装する必要がある。その辺りは日報などの類似機能を参照。

📝 メールは非同期で送らないと大量の時間がかかってタイムアウトする

:memo: 現役生とメンターにのみ通知を送る。

**Comment by komagata** [comment]
📝 Slack通知も必要
