### ISSUE TITLE
DocsにWIPの機能が欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1742]

**Comment by mh-mobile** [comment]
# WIP対応の要件整理
* docs詳細画面でwipの場合はタイトルにWIPを付ける
* 作成時にwipでない場合は、Slackに通知する
  * 作成完了後は、noticeメッセージを表示する
* 更新時にwipでない場合は、Slackに通知しない？
  * 更新完了後は、noticeメッセージを表示する
* ダッシュボードにWIPのdocsを表示する
* docs詳細画面のフォーム画面にWIPのボタンを追加する。
* docs一覧画面にWIPの場合はWIPをつける

**Comment by mh-mobile** [comment]
@komagata 

DocsのWIP対応の要件について確認させてください。

日報や提出物では保存時にSlackに通知する機能がございますが、Docsの場合も同様にSlack通知する機能は
必要でしょうか？
また、もし必要な場合は、Slack通知の動作はどのようになりますでしょうか？

以下のIssueとの関連も気になっています。
[新着のDocsをすぐに気づけるようにしたい #1739](https://github.com/fjordllc/bootcamp/issues/1739)

**Comment by komagata** [comment]
@mh-mobile Slack通知は #1739 で実装するということで大丈夫です。（そちらに追記しておきました）

**Comment by mh-mobile** [comment]
本番同格OK
