### ISSUE TITLE
docの作者を変更できるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1751]
管理者は変更できる。

作者を選ぶときは、日報で使ってるライブラリを使って、ユーザーから絞り込みができるようにしたい。
ライブラリ: https://select2.org/

![image](https://user-images.githubusercontent.com/168265/99202159-97a97980-27f1-11eb-8ad4-33bf04c6a082.png)

**Comment by universato** [comment]
今日のミーティングで、machidaさんから本番での変更を確かめられた旨を聞いたので、閉じます。
