### ISSUE TITLE
タグを補完したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1754]

**Comment by mh-mobile** [comment]
# Tagifyの補完デモ

`Advance Options`のデモが実現したいことに近い

[https://yaireo.github.io/tagify/#section-extra-properties](https://yaireo.github.io/tagify/#section-extra-properties)

![image](https://user-images.githubusercontent.com/13811034/89383238-1bee5a00-d737-11ea-8afc-49aa9a2d9798.png)

**Comment by mh-mobile** [comment]
Tagifyのライブラリにおいて、全角のIME確定時にタグ入力が確定するバグが存在している模様

**Comment by mh-mobile** [comment]
日本語のIMEの問題は、Issueで報告済みであるようだが、未解決のままクローズされている。
[Input is confirmed with the enter key pressed during character transliteration(IME)](https://github.com/yairEO/tagify/issues/539)

**Comment by mh-mobile** [comment]
@komagata 

すみません、タグのUI用のnpmライブラリとしてTagifyを導入しましたが、タグ補完時に日本語入力の問題が発生するため、
別のnpmライブラリの[@johmun/vue-tags-input](https://www.npmjs.com/package/@johmun/vue-tags-input)を導入してもよろしいでしょうか？

日本語入力の問題としては、以下の事象が発生します。
* IME入力を確定したときに、確定した文字列がタグになる。
→ IME入力後に、確定した文字列をもとに候補となるタグを選択したい
* IME入力の候補とタグの候補が同時に表示されてしまう。
→ IME入力を確定した後に、タグの候補を表示したい

一旦、自分の方でTagifyのライブラリをフォークして、問題の解消を試みましたが、
内部処理が複雑で問題の解消が難しそうです。


別案として、npmライブラリの[@johmun/vue-tags-input](https://www.npmjs.com/package/@johmun/vue-tags-input)を組み込んで
動かしたところ、特に日本語の問題は発生しませんでした。

ただし、タグ補完時のUIがTagifyとは異なり、入力フォームの下部に候補が一覧表示されるUIになります。

[タグ補完のデモ](http://www.vue-tags-input.com/#/examples/autocomplete)

![image](https://user-images.githubusercontent.com/13811034/89615966-84b60d80-d8c2-11ea-9810-3cbc8f3d8a81.png)

**Comment by mh-mobile** [comment]
add_tag_to_docブランチに正常にマージ済みのため、クローズします。
(ローカルでも動確済み)
