### ISSUE TITLE
「全ての通知」のリンク先を未読の通知にしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1759]
<img width="391" alt="スクリーンショット 2020-08-08 22 31 21" src="https://user-images.githubusercontent.com/16577/89711727-11e28a80-d9c7-11ea-882d-2f77387b2a8b.png">

「既読を含めた通知一覧」よりも「未読の通知一覧」を見るユースケースが圧倒的に多いため。

**Comment by JunichiIto** [comment]
最近実は「既読を含めた通知一覧」の方がいいかな、とかも思ったり・・・。
通知メール経由で一回読んだけど、返信はまだ、みたいな通知も一緒にチェックしたいことがあるので。

両方リンクがあると一番嬉しいです！
