### ISSUE TITLE
イベント詳細のURLがリンクになってほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1767]
<img width="709" alt="貼り付けた画像_2020_08_11_16_34" src="https://user-images.githubusercontent.com/168265/89870287-8f3d1380-dbf0-11ea-8f41-dd46f3812d9c.png">

ここがリンクになるようになってほしい。

**Comment by komagata** [comment]
📝 これを使うと良さそう

https://github.com/tenderlove/rails_autolink
