### ISSUE TITLE
イベント一覧に参加者、補欠者の数字を出したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1769]
<img width="847" alt="スクリーンショット 2020-08-26 14 51 40" src="https://user-images.githubusercontent.com/16577/91264819-af9dce00-e7ab-11ea-8f5a-bc4fabe0d1d9.png">

**Comment by gogutan** [comment]
@machida @komagata 

- 参加者数と補欠者数をそれぞれ表示

<img width="498" alt="イベント___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/91666013-9d69ba00-eb34-11ea-9962-a4dd6febb3c3.png">

- 参加者数と補欠者数を足した数字のみ表示

<img width="498" alt="イベント___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/91666022-a65a8b80-eb34-11ea-9280-549f0e4d03e8.png">

以上、2パターンのプロトタイプを作ってみました。後者の足した数字のみ表示版の方が、

- コメント数と同様に表示が簡潔で、画面全体の見た目がスッキリする

- 前者よりも処理が少し軽そう

といった理由から良さそうだなと考えているのですが、いかがでしょうか。

**Comment by komagata** [comment]
@machida こちらどちらがいいですかね？

僕は後者かなーと思いました。
