### ISSUE TITLE
提出物にOKをもらえたらプラクティスのステータスを完了にしてほしい

### ISSUE THREAD

**Issue by kotakanazawa** [fjordllc/bootcamp#1771]
## 現状

提出物に確認済スタンプをもらった後、受講生ユーザーは自分でプラクティスのステータスを「完了」にする必要がある。
ほんの少しだが、ユーザーの手間になっている。

## 提案

提出物に確認済スタンプをもらった後、自動でプラクティスのステータスが「完了」になってほしい。

**Comment by komagata** [comment]
お、これはkanazawaさんがやってくださるフラグ！？🤭

**Comment by kotakanazawa** [comment]
ぼ、ぼくはとても優しい人間なので、お手軽なIssueを今後チーム開発をする方に用意して差し上げました😇

**Comment by JunichiIto** [comment]
> 提出物に確認済スタンプをもらった後、自動でプラクティスのステータスが「完了」になってほしい。

これは僕もそう思いました！
