### ISSUE TITLE
Q&Aでベストアンサーが決まったら通知してほしい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1776]
Q&Aでベストアンサーが決まったら通知してほしいです。（🔔 マーク欄の通知だけでOK。Slack通知もできたらほしい。メール通知はたぶん不要。）

理由：どんな回答が入っていたのか、それまでの議論を読むことも生徒さんの勉強になりそうだから。（通知がないとたぶん回答をチェックしないはず）

ref: [Q&AのQが投稿されたらSlackに通知されて欲しい · Issue \#1464 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/1464)

**Comment by JunichiIto** [comment]
これ、「ウォッチしているQ&Aのベストアンサーが決まったら通知」みたいに実装されるとうれしいな〜。
メール通知いらない、って書いてたけど、やっぱりメール通知もほしいです😅

**Comment by rikuba** [comment]
本番環境で動作を確認できたためcloseします。
