### ISSUE TITLE
Slackアカウントをプロフィールページに載せてほしい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1777]
ユーザー一覧にはSlackアカウントが表示されるが、各人のプロフィールページには表示されない。

https://bootcamp.fjord.jp/users?target=mentor
<img width="260" alt="Screen Shot 2020-08-16 at 8 58 24" src="https://user-images.githubusercontent.com/1148320/90323636-e4857600-df9e-11ea-8076-c111ffffb7fc.png">

https://bootcamp.fjord.jp/users/676
<img width="308" alt="Screen Shot 2020-08-16 at 8 58 52" src="https://user-images.githubusercontent.com/1148320/90323633-ddf6fe80-df9e-11ea-939a-564fd746eb83.png">

たまにSlackアカウントがわからない人もいるので、プロフィールページにも載っていると嬉しい。

**Comment by komagata** [comment]
:memo: 表示されてはいるがわかりづらいので表示方法を改良する。

**Comment by machida** [comment]
こちら、一覧と個別を同じ表示にしましたー
