### ISSUE TITLE
参加登録したさいにGoogle Analyticsにイベントを飛ばしたい

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#1792]
Google Analyticsで、ページを閲覧した人の中からどれくらいの人が参加したかを追いたいので
https://bootcamp.fjord.jp/users/new から参加登録した際にGoogle Analyticsにイベントを飛ばしてほしいです。

Action名は `registration_complete` でお願いします！

**Comment by komagata** [comment]
@rlho こういうのを使ってサーバーサイド（ruby）からイベントを飛ばす感じですかね？

[Measurement Protocol の操作  \|  アナリティクス Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide)

**Comment by bluerabbit** [comment]
登録完了ページにga仕込んだりする方法もありそう。

**Comment by komagata** [comment]
:memo:サーバーサイドから送るならこれ便利そう。

[tpitale/staccato\-rails: Seamless Rails integration with Staccato](https://github.com/tpitale/staccato-rails)

ただcookieやipなどをちゃんと渡してあげないと一緒のsessionにならないので気を付ける。
