### ISSUE TITLE
日報のエクスポート機能がほしい

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#1808]
自分の日報のmarkdownファイルを全部まとめてエクスポートできるようになってほしい。

- ダッシュボードに自分の全日報エクスポートボタンが欲しい。
- 日報をmarkdown形式でzipにまとめてダウンロードできる。

**Comment by komagata** [comment]
@ima1zumi 1つの日報でしたらMarkdown表示機能がありますが、これは厳密にはどういう日報が欲しいのでしょうか。

自分の日報を全部まとめてエクスポートしたいという感じかな？

**Comment by ima1zumi** [comment]
@komagata 
言葉が足りずすみません。自分の日報を全部まとめてエクスポートしたいという感じです！
issue本文も修正しておきました。

**Comment by komagata** [comment]
@ima1zumi 自分の日報を全部まとめてエクスポートは具体的にはどういう形を想定していますかね？

1日報＝markdownファイルにしてzipで固めたものをダウンロードできるとかでしょうか？

**Comment by ima1zumi** [comment]
@komagata 
> 1日報＝1markdownファイルにして全日文をzipで固めたものをダウンロードできるとか

そのイメージです。

用途としては、卒業した後に自分の全日報をローカルのMarkdownエディタ（具体的にはNotion）に取り込み、手元で全文検索できるようにしたいです。

**Comment by komagata** [comment]
なるほど〜

**Comment by kawase-k** [comment]
メモ: rubyzipというgemが入りそう、もしくはzipruby
https://github.com/rubyzip/rubyzip

**Comment by kawase-k** [comment]
@komagata さん
こちら実装まで一通りできたのですがレビュー前に仕様の確認をさせてください。

- zipさせるために一度すべての日報を1markdownファイルにしているのですが、それを仮置きしておくようのディレクトリはどこに作成すればいいでしょうか？現時点ではtmp直下にexportsディレクトリを作成してそこに仮置きしています。
- エクスポートしてダウンロードした後は、不要なファイル（日報のmarkdownファイルとzipファイル）は削除するようにしているのですが問題ないでしょうか？

お手数おかけしますがご確認のほどよろしくお願いいたします🙇‍♂️

**Comment by kawase-k** [comment]
@machida さん
こちら実装まで一通りできたのですがデザインに関わりそうなところがあるので確認をさせてください。

- レビューの際にエクスポートボタンのデザインをお願いしてもよろしいでしょうか？
- エクスポートした日報の雛形については、[自分が記載した全ての日報を一気にダウンロードできるようにする](https://github.com/fjordllc/bootcamp/issues/2665)のmarkdownファイルのフォーマット通りに実装してみたのですが問題ないでしょうか？



お手数おかけしますがご確認のほどよろしくお願いいたします🙇‍♂️

**Comment by machida** [comment]
@kawase-k 連絡ありがとうございますー 

ボタンのデザイン了解です！！

> フォーマット通りに実装してみた

はい、まずはそれでリリースして、要望が出たら別Issueで対応にしたいと思います！

**Comment by komagata** [comment]
@kawase-k 

> zipさせるために一度すべての日報を1markdownファイルにしそれを仮置きしておくためのディレクトリを作成しているのですが、これはどこへ作成するのが適切でしょうか？現時点ではtmpフォルダ直下にexportsディレクトリを作成してそこに仮置きするようにしています。

極力一時的ファイルは作らない方がステートレスでいいのですが、必須であればRubyにテンポラリファイルやテンポラリディレクトリを作る機能を使ってみてください〜

> エクスポートした日報の雛形については、自分が記載した全ての日報を一気にダウンロードできるようにするのmarkdownファイルのフォーマット通りに実装してみたのですが問題ないでしょうか？

ありがとうございます！それでリリースできればと思います！

**Comment by kotakawase** [comment]
こちら本番環境で確認を行い問題なかったのでCloseします！
長い間ありがとうございました🙇‍♂️
