### ISSUE TITLE
ユーザーIDを絞り込んで検索できるようになってほしい

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#1809]
自分の書いた日報の中から検索したいことがある。
ユーザーIDもしくはユーザーネームで絞り込みをかけて検索できる機能がほしい。

## 仕様

`user:komagata`という感じでユーザーを絞り込んで検索できるようにする。

日報に限らない。

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/95948680-fb740780-0e2b-11eb-8cb2-28e9e9384149.png)

**Comment by ima1zumi** [comment]
📝 デザインは別issueにする。
📝  似たようなgemがあるかも？
📝 後から別の検索オプションを柔軟に追加できる設計にすると嬉しい。

**Comment by ima1zumi** [comment]
:memo:
`practice` に `user_id` が紐付いていないため検索結果にプラクティスが全件表示されてしまっている。直す。
