### ISSUE TITLE
Slackのようにリアクション一覧が表示されてほしい

### ISSUE THREAD

**Issue by mh-mobile** [fjordllc/bootcamp#1810]
## 概要

自分の投稿にリアクション（絵文字をつける）されたことに気づかないため、Slack（メンション&リアクションの一覧画面）のようにリアクションの一覧が表示されてほしい。

### 課題
他人の日報の自分のコメントに誰かがリアクションした場合に、他人の日報画面の自分のコメントを表示しないとリアクションされたことに気づくことができない。

**Comment by JunichiIto** [comment]
関連？ https://github.com/fjordllc/bootcamp/issues/1532

**Comment by mh-mobile** [comment]
@JunichiIto 

>関連？ #1532

あっ、同様のissueが既にあったんですね。前も同じことがあったので、
次はissueもあらかじめ検索したいと思います。

そして、issueの内容に関しては、確かに課題に感じている部分は同じかと思います！

解決方法としては、大量にリアクションがあった場合に通知蘭が大変になるので、同じく既存の通知蘭は使用しない方法が良いと思いました。また、既存の通知とは異なり、未読管理も不要かと思っています。

このissueで提示した方法としましては、現在のSlackのリアクション一覧のような表示になります。

### リアクション一覧の表示

* ```XXXさんとYYYさんがリアクションしました```や```何人かのメンバーがリアクションしました```などの誰がリアクションしたことが分かること。
  * リアクションした人数が多い場合は、```何人かのメンバー```のようにまとめる。
* リアクション対象のメッセージの一部が表示されること。
* リアクションされた絵文字が表示されること。
* リアクションの通知をタップすると、リアクションされたメッセージの画面に遷移すること。

### リアクション一覧の画面

以下のSlackのスマホアプリの画面（スクリーンショット）のようなイメージです。
<img src="https://user-images.githubusercontent.com/13811034/91158321-6abd5d00-e701-11ea-8267-2b2fec190fee.png" width="300"/>

**Comment by mh-mobile** [comment]
同じ課題なので、 #1532 の一つの案として、本issueの#1810を載せる形で良いと思います。

**Comment by JunichiIto** [comment]
@mh-mobile たしかにSlackのUIを参考にすれば解決しそうな気がしますね！
issueの統合はどっちを残す形でも大丈夫です〜。

**Comment by machida** [comment]
おお、これは欲しいですね！！

**Comment by komagata** [comment]
#1532 と重複しているのでCloseしちゃいます〜
