### ISSUE TITLE
プラクティス一覧でgogutanさんのアイコンが二つ出ている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1817]
<img width="313" alt="スクリーンショット 2020-08-26 16 07 08" src="https://user-images.githubusercontent.com/16577/91272420-a9611f00-e7b6-11ea-9b05-3b80d1bf423e.png">

- 本番データを修正したのでデータとしては直っている。
- [x] ユニークインデックスを作ってこういうデータが2件できないようにする。
- [x] 登録時にすでにあるかどうか確認してから登録する処理を追加する。

**Comment by komagata** [comment]
:memo: DBを直接触って重複していたデータを削除した。

そもそも二個登録されないように修正が必要。

**Comment by gogutan** [comment]
![doubled_icon](https://user-images.githubusercontent.com/50437473/91272932-7bc8a580-e7b7-11ea-940c-8b656a286a4a.gif)
重複している時に、ステータスを変更しようとした時の挙動です。

**Comment by komagata** [comment]
@lamp7600 こちら後ほどお願いします〜

**Comment by lamp7600** [comment]
@komagata 了解です！

**Comment by lamp7600** [comment]
@komagata 質問です。
> - ユニークインデックスを作ってこういうデータが2件できないようにする。
> - 登録時にすでにあるかどうか確認してから登録する処理を追加する。

1つ目のユニークインデックスはできたのですが、2つめのやり方が分かりません。Learningモデルにバリデーションをつければいいのかと思ったのですが、すでに一意性のバリデーションはありました。

```ruby
class Learning < ApplicationRecord
  enum status: { unstarted: 0, started: 1, submitted: 2, complete: 3 }
  belongs_to :user, touch: true
  belongs_to :practice
  after_save LearningCallbacks.new
  after_destroy LearningCallbacks.new

  validates :user_id, presence: true
  validates :practice_id,
    presence: true,
    uniqueness: { scope: :user_id }
  validate :startable_practice

  private
    def startable_practice
      if started? && Learning.exists?(user_id: self.user_id, status: "started")
        errors.add :error, "すでに着手しているプラクティスがあります。\n提出物を提出するか完了すると新しいプラクティスを開始できます。"
      end
    end
end

```

**Comment by komagata** [comment]
@lamp7600 僕が勘違いしていました。validationがあるなら2つ目の処理は不要です。

**Comment by lamp7600** [comment]
@komagata [このissueに関連するPR](https://github.com/fjordllc/bootcamp/pull/1936)はマージ済みなのですが、本番環境での動作確認のやり方が分かりません。完了にしても大丈夫でしょうか？

**Comment by komagata** [comment]
@lamp7600 そういう場合は komagataかmachidaに確認依頼をしてください。
