### ISSUE TITLE
autoprefixer-railsがDEPRECATEDなのに対応する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1821]
[Deprecated · ai/autoprefixer\-rails Wiki](https://github.com/ai/autoprefixer-rails/wiki/Deprecated)

@machida さんと話して決める必要がありそう。

**Comment by machida** [comment]
お、ブートキャンプではみんなChromeからしかアクセスしてないので、gem を削除しちゃいましょう。トップページなどでもし個別のブラウザの対応が必要な際は、手動で対応したいと思います。

**Comment by bluerabbit** [comment]
えーautoprefixer-railsがDEPRECATEDなのか。 😱

**Comment by komagata** [comment]
@machida 対応方法としては単純にこのgemを外すだけでOKな感じですかね？

**Comment by machida** [comment]
@komagata はい！外すだけでOKですー

**Comment by komagata** [comment]
@machida ありがとうございます！！
