### ISSUE TITLE
課題を進める上での購入必須の技術書と、購入必須ではない参考書を見える化して欲しい

### ISSUE THREAD

**Issue by yuna627** [fjordllc/bootcamp#1822]
## 概要
課題を進める上での購入必須の技術書と、購入必須ではない参考書を見える化して欲しい。
このリクエストは私自身の[日報](https://bootcamp.fjord.jp/reports/16982)に投稿したものです。(@imaharu さんから参考書籍一覧機能を作成中とのことを伺ったのですが、カリキュラムを進める上で購入必須かそうでないかの区別はないということで、投稿させていただきます！)

## きっかけ
フィヨルドで勉強を始めた際に書籍をまとめて注文したのですが、その際は課題を全て開いて終了条件に記載がある書籍を全て購入しました。今回【データーベース設計の基本を理解する】に取り掛かった際に、終了条件には含まれていない、でも文面からすると購入&学習がマストである参考書があることに気が付き注文しました。

カリキュラムが進むタイミングで本を注文している方もいると思いますが、私のようにまとめ買いしている方もいると思ったので、カリキュラムを進める上で購入必須の参考書かそうでないかを見える化してくれると大変助かります🙇‍♀️

**Comment by yuna627** [comment]
こちらバグラベルがついていますが、バグではないです！
すみません、ラベルのはずし方がわかりません🙇‍♀️

**Comment by bluerabbit** [comment]
> ラベルのはずし方

![licecap](https://user-images.githubusercontent.com/45971/91366669-5c755b00-e83f-11ea-8b35-7eca8bb69e07.gif)

**Comment by yuna627** [comment]
@bluerabbit さん
タグ外し&解説ありがとうございます🙇‍♀️!!
Labelsと赤いタグはクリックしてみたのですが、設定ボタンを試していませんでした、大変助かりました🙇‍♀️
