### ISSUE TITLE
質問のコメントが付いた時のメール通知が二種類届きます

### ISSUE THREAD

**Issue by ksmxxxxxx** [fjordllc/bootcamp#1825]
## 概要

掲題通りで、コメントが付いた瞬間にメールで送られる通知が2種類（コメントの内容は同じ）のメールが届きます。

## 再現手順

1. 質問にコメントを付ける
2. メールを確認すると2種類のメールが届いている。（メールのタイトルは別で、コメントの内容は同じ）

## 期待される振る舞い

この挙動が期待通りのものなのかはわかりませんが、使い手としては、1つ来ていればいいかなと思っているところです。

## スクリーンショット

![image](https://user-images.githubusercontent.com/5976902/91409518-7b481180-e880-11ea-8b37-90445d02cf4a.png)

![image](https://user-images.githubusercontent.com/5976902/91409576-8c911e00-e880-11ea-8d1f-152250e06efe.png)

## 環境

 - OS: macOS
 - ブラウザ: Chrome
 - バージョン: 最新版（84.0.4147.135）

## 関連Issue

Ref: #関連Issue番号

**Comment by machida** [comment]
📝 
直ってるかもしれないので、要調査

**Comment by JunichiIto** [comment]
参考：よく似たissue

- https://github.com/fjordllc/bootcamp/issues/4709

**Comment by isshi-hasegawa** [comment]
ローカル環境にて以下のように調査を行いましたが、再現できないことを確認しました。
「なぜ再現できないのか」「直ったとしたら、一体いつどの変更で直ったのか」をコードをもとにお伝えするべきですが、通知関係のコードのロジックが非常に複雑で、現時点ではそこまで分析できておりません🙏

## 調査手順

1.  `bin/rails s`してサーバーを起動、`http://localhost:3000`にアクセスして`hajime`でログイン
2. `http://localhost:3000/current_user/edit`にアクセスし、`hajime`のメール通知をオンにして保存
3. `hajime`で質問を投稿
4. Chromeのシークレットウィンドウで`http://localhost:3000`にアクセスして`mentormentaro`でログイン
5. 3で投稿された質問に回答
6. `http://localhost:3000/letter_opener/`にアクセスし、`hajime@fjord.jp`宛のメール件数が1件のみであることを確認

<img width="1919" alt="_development__LetterOpenerWeb" src="https://user-images.githubusercontent.com/53898556/168949260-27a4c73e-c34a-4a50-b690-e55c7e1606e4.png">

**Comment by isshi-hasegawa** [comment]
Closeいたします〜
