### ISSUE TITLE
お問い合わせへの導線が欲しい

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#1827]
## 概要
お問い合わせへの導線が現在外部向けの`/welcome`にしか存在しない。
内部からのお問い合わせへの導線も設置しておきたい。

**Comment by komagata** [comment]
@rlho @machida どこにどのようにおくのがいいですかね〜

**Comment by rlho** [comment]
@komagata @machida 
いまfooterがないのでfooterを設置してその中にリンクがあれば良いかなと思いましたがどうでしょう？

**Comment by komagata** [comment]
@riho 設置場所などを考えるのにIssueの「なぜ」の部分がわかると考えやすいのですが、お問い合わせへの導線が欲しい理由ってなんでしょうか。

**Comment by machida** [comment]
相談部屋機能ができたのでクローズしますー
