### ISSUE TITLE
（再）未読の通知がゼロになっても通知一覧にジャンプしたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1830]
https://github.com/fjordllc/bootcamp/issues/1555 が元に戻った？

通知ゼロのときにアイコンをクリックしても何も起きません。

<img width="82" alt="Screen Shot 2020-08-28 at 9 08 54" src="https://user-images.githubusercontent.com/1148320/91506825-1f2bce80-e90e-11ea-818c-20a87bb61162.png">

**Comment by komagata** [comment]
Done
