### ISSUE TITLE
【提案】メンターの場合、提出物がデフォルトでWatch中になるのをやめる

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1857]
**何故この機能が必要なのか**

提出物がデフォルトでWatch中になっていても、役に立ったと思うときより、各種の通知がノイズに感じることの方が多いから。

**機能の説明**

- メンターの場合、提出物がデフォルトでWatch中になるのをやめる
- コメントを入れたり、明示的に"Watchする"を選んだときだけWatch中になる

**Comment by u1tnk** [comment]
僕は「日報or提出物への新規コメントの通知で自分がコメントを付けているものかどうか区別が付くようにして欲しい」というissueを立てようと思ってたのですが、このissueが対応されたら不要になりそうなので、こちらお願いしたいです！

あと、提出物だけじゃなくて日報も同じ仕様と思うので、日報も対応希望です。

**Comment by machida** [comment]
@JunichiIto @u1tnk

ありがとうございます！
確かに、前はブートキャンプ内で何が起きているかを把握しようとこのようにしていたのですが、さすがに今はノイズになってしまいますね。僕も通知を切りたいと思ってました。
伊藤さんが挙げていただいた仕様に変更したいと思います。
