### ISSUE TITLE
メンターの方への提出物リマインド機能が欲しい

### ISSUE THREAD

**Issue by shibaaaa** [fjordllc/bootcamp#1860]
提出物を提出してから数日経過してもメンターの方から何もリアクションがない場合、こちらからコメント等で催促等をするのは憚られます...。
提出物が提出されてから所定の日数（例えば3日）経過してもコメントや確認等のリアクションがない場合に自動でリマインドがされたり、生徒側からリマインドボタンを押せる等、何かアクションが起こせるようになって欲しい。

**Comment by shibaaaa** [comment]
@komagata 
> メンター全員での作業が追いついてない状態です。

すみません、そのような状況だと知らずにこちらの機能追加を提案させていただきましたが、メンターの方々への失礼に当る発言でした。いつもお世話になっております、ありがとうございます。

>生徒の方からみて何日以内には返答して欲しいというのは感覚値としてどのくらいが許容でいる感じでしょうか

あくまで私の感覚で申し上げますと、提出してから3日以上経過しても何もリアクションがない場合は「この提出物は本当に提出状態として正常にメンターの方々に通じているのだろうか...」「こちらから何か催促した方がいいのだろうか...」といろいろ考えてしまいます。

特に先日は提出物にメンターの方の閲覧履歴（ページ下の「見たよ」の部分）がついてから2,3日経過後も何もリアクションが頂けず、「コードを読んで頂いてレビューをまとめて頂いてる時間」なのか「単に後回しにされて忘れられているのか」なのか分からず、催促すれば良いのか、判断が難しいと感じました。仮に「コードを読んで頂いてレビューをまとめて頂いてる時間」だとすると催促するのは失礼だと思いましたので...。
そのような経緯がありこちらのissueを上げさせて頂いた所存です。

ですので私の感覚では提出してから3日以内にリアクションが頂けると嬉しいですが、メンターの方々がご多忙でリアクションが難しい場合はその提出物に対するメンターの状態・状況(例えば忙しいのでレビューまで時間がかかる、など)が簡単にでも分かると安心かなと思いました。

以上、レビューを頂いている立場で大変恐縮ですが、何卒宜しくお願い致します。

**Comment by komagata** [comment]
@shibaaaa 

> メンターの方々への失礼に当る発言でした。

失礼なんてことは全然ありません。ご指摘ありがとうございます。

> ですので私の感覚では提出してから3日以内にリアクションが頂けると嬉しいですが、

なるほど、ありがとうございます。大変参考になります。これを踏まえてメンター陣で対応策について話し合ってみようと思います。

**Comment by shibaaaa** [comment]
@komagata 
> これを踏まえてメンター陣で対応策について話し合います。

恐れ入ります。ご検討ありがとうございます。

**Comment by shibaaaa** [comment]
@JunichiIto 
恐縮です🙇‍♂️
こちらのissueはメンターの方々を責めるような内容に捉えられてもおかしくないですし(単なるクレームともとれる)、僕の立場的にもレビューを頂いている身なのでissueにあげるのにかなり勇気を振り絞りました。
ですが駒形さんや伊藤さんにこうして温かく受け取って頂き、勇気を振り絞って良かったと思いました！
ありがとうございます！

**Comment by u1tnk** [comment]
メンターが見る、自分がコメントしていて確認されてないプラクティス一覧とかあると良い気がします。
メンターのコメントが最後だとしても詰まっているのが分かりますし。
