### ISSUE TITLE
使われていないルーティングを削除する

### ISSUE THREAD

**Issue by mh-mobile** [fjordllc/bootcamp#1861]
## 概要

使われていないルーティングが存在するため削除する。

以下は、[amatsuda/traceroute](https://github.com/amatsuda/traceroute)のgemを使って、使われていないルーティングを検出した結果です。

結果の中には、使われているルーティング（おそらく誤検出）もありますが、commentsやwatchesのコントローラは削除されているため、comments#indexやwatches#indexなどのルーティングは到達しない状態です。
※ commentsやwatchesのコントローラはAPIに移行したためと推測

```
Unused routes (34):
  welcome#tos
  welcome#law
  admin/seats#show
  courses#show
  comments#index
  comments#create
  comments#new
  comments#edit
  comments#show
  comments#update
  comments#update
  comments#destroy
  watches#index
  watches#create
  watches#new
  watches#edit
  watches#show
  watches#update
  watches#update
  watches#destroy
  answers#create
  answers#edit
  answers#update
  answers#update
  answers#destroy
  questions/correct_answer#update
  questions/correct_answer#update
  questions/correct_answer#create
  static_pages#thanks
  static_pages#retire
  rails/conductor/action_mailbox/inbound_emails#edit
  rails/conductor/action_mailbox/inbound_emails#update
  rails/conductor/action_mailbox/inbound_emails#update
  rails/conductor/action_mailbox/inbound_emails#destroy
```

**Comment by komagata** [comment]
@mh-mobile amatsuda/tracerouteってあるんですね、参考になります、ありがとうございます。

**Comment by mh-mobile** [comment]
@komagata @machida 

本Issueですが、既に @bluerabbit さんが以下のPRで対応しているように見えるため、クローズしても良い気がします。

gem tracerouteで使われていないroutesやControllerのactionを調べてCIでチェックできるようにした #1891

**Comment by bluerabbit** [comment]
> 使われていないルーティングを削除する

に関してはクローズでいいと思います。

下記のcontrollerでroutesに無いのにpublicなmethodが存在してしまっているのは対応が必要です（可能なら）。これは別Issueか一旦ほっとくかかな。
https://github.com/fjordllc/bootcamp/pull/1891/files#diff-51a00b02fcb5cd5e98178a9fc0499b0cR5-R21
