### ISSUE TITLE
リロードするたびに通知の未読・既読状況が不規則に変わる

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1862]
## 概要

https://bootcamp.fjord.jp/notifications を開くと既読にしたはずの通知が未読に戻っている。
ブラウザをリロードすると、通知が不規則に既読になったり未読になったりする。

## 再現手順

1. https://bootcamp.fjord.jp/notifications にアクセス。
2. ブラウザをリロードする
3. 通知が不規則に既読になったり未読になったりする。

## 期待される振る舞い

既読にした通知は既読のままになる。

## スクリーンショット
何度かブラウザをリロードさせたときの様子です↓

![1vs1mZyeex](https://user-images.githubusercontent.com/1148320/92044775-ed0ce780-edb9-11ea-90e5-ae0aa2ad2e5f.gif)

## 環境

 - OS: macOS
 - ブラウザ: Chrome
 - バージョン: 85.0.4183.83 (Official Build) (64-bit)

## 関連Issue

キャッシュの扱いに不具合がある？

**Comment by JunichiIto** [comment]
この件、最近はリロードしてもずっと既読にしたはずの通知が未読状態で表示されています。
下のスクショはすべて既読になっているはずの通知です。

![img](https://user-images.githubusercontent.com/1148320/96194379-2e7dde80-0f85-11eb-80b0-0c4c18565eae.jpg)

「全て」の通知タブで既読・未読を横断的にチェックすることもよくやるので、早めにこの問題が解消されると助かります 🙏

**Comment by hituzi-no-sippo** [comment]
@JunichiIto 
このバグですが今も発生しますか?
私の開発環境(commit: 1ce8c4b700a333fe9d6ba117ca268b7bed77a452)では問題を再現できない状態でいます。

> この件、最近はリロードしてもずっと既読にしたはずの通知が未読状態で表示されています。
> 下のスクショはすべて既読になっているはずの通知です。
> ...

このコメントの投稿日が5ヶ月以上前で、今も @JunichiIto さんの方で現象が確認できるか教えて欲しいです。

今年の1月に通知一覧のページはVue化( fbcc0558c0b8ae469dffbc38a0a97d7d5145da )されており、この変更で修正されたかもしれないと考えています。

**Comment by JunichiIto** [comment]
たしかに最近はあまり気にしたことがない気がしますね。もしかすると直ったのかもしれません。
いったんクローズしておきます。
ご連絡ありがとうございました！
