### ISSUE TITLE
提出物作成のflashに文言を追加する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1863]
「提出物を提出しました。7日以内にメンターがレビューしますので、次のプラクティスにお進みください。7日以上待ってもレビューされない場合は、気軽にメンターにメンションを送ってください。」

**Comment by JunichiIto** [comment]
「X日以上待ってもレビューされない場合は、気軽にメンターにメンションを送ってください。」みたいな文言を付け加えてもいいかも。
（あまり文章を長くしすぎるのも問題かもしれませんが）

**Comment by imaharu** [comment]
> 気軽にメンターにメンションを送ってください

提出物を出した時点で、メンターの誰がレビューするのか決まってないので、誰にメンションしていいか混乱するかな〜と思いました。

生徒さんがメンター全員に、メンションできる仕組みが必要ですかね？ (具体的なHowは、スクラムチームが決めるのでいいと思います〜)

**Comment by machida** [comment]
確かに、メンターへのメンション欲しいですね！
