### ISSUE TITLE
お知らせ作成の「通知ターゲット」のデフォルトを現役生のみにする

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1871]
お知らせの通知は使用頻度が一番高い（と勝手に思っている）「現役生のみ」をデフォルトにするのが良いのではないか？
（全員にすると卒業生にまで通知が飛んでしまうのでは？）

<img width="821" alt="Screen Shot 2020-09-07 at 20 45 34" src="https://user-images.githubusercontent.com/1148320/92384679-74a47e80-f14b-11ea-82d8-f6c360edfab9.png">

**Comment by lamp7600** [comment]
@JunichiIto @komagata @machida 本番環境での確認をお願いします🙏

**Comment by machida** [comment]
@lamp 

確認しました！！🙆🏻‍♂️

![image](https://user-images.githubusercontent.com/168265/94242659-5adba780-ff51-11ea-981b-83e9ce2b8e1a.png)

**Comment by lamp7600** [comment]
@machida ご確認ありがとうございます！
