### ISSUE TITLE
同期一覧ページが欲しい

### ISSUE THREAD

**Issue by harukus** [fjordllc/bootcamp#1876]
**何故この機能が必要なのか**
自分の同期を知るため。
自分のプロフィールに「○○期生」とあり、他に同じ時期に入った人を知りたいためです！

**Comment by machida** [comment]
## リンクの場所

<img width="532" alt="貼り付けた画像_2020_09_24_14_33" src="https://user-images.githubusercontent.com/168265/94104803-ddda0080-fe72-11ea-970e-1da4663a44fa.png">

一旦、ここをリンクにして、これをクリックすると、その同期のユーザー一覧ページへ遷移する。

## XX期のユーザー一覧

このページは、リタイアユーザー以外のロール全員を表示

## 今後

期のリンク先はユーザー一覧にも出すかも。
仕様が決まったら別Issueで。
