### ISSUE TITLE
githubログインしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#188]
githubオンリーでよい

**Comment by hattori6789** [comment]
担当して大丈夫でしたらやります🙋

**Comment by hattori6789** [comment]
@komagata 担当して大丈夫でしたらやります🙋

**Comment by komagata** [comment]
@hattori6789 ぜひお願いします。

最終的に全員githubログイン必須にしたいです。（サイト固有のログインはなくなっても良い）

**Comment by hattori6789** [comment]
@komagata 承知しました！
