### ISSUE TITLE
今のseedになにかの何かのプラクティスに着手中のユーザーがいないので、ステータスが着手中を持つユーザーを作る

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1880]

**Comment by shibaaaa** [comment]
すいません、こちらのissueについて確認させて頂きたい点がございます。
現在のseed内にすでに「何かのプラクティスに着手中のユーザー」と思しきユーザーデータが存在しており、ローカル上でもプラクティスに着手中であることを確認しました。
## 該当コード
https://github.com/fjordllc/bootcamp/blob/71c05edd4a978867d3be0e419a05bf766dc31e89/test/fixtures/learnings.yml#L1-L4

## ローカルで立ち上げた際の画面
<img width="853" alt="komagataのプロフィール___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/56685224/93564456-ab3c8d80-f9c4-11ea-8c2b-03fcc3acc469.png">

以上を踏まえまして、確認させて頂きたい点は以下の2つです。
- 上記のkomagataさんのページ上で「進行中のプラクティスが存在すること」と、「何かのプラクティスに着手中のユーザー」は同じ意味と解釈してよろしいのでしょうか？
- 上記のユーザー(komagataさん)以外で、「何かのプラクティスに着手中のユーザー」の作成をご所望という解釈でよろしいのでしょうか？

何卒ご確認頂けますと幸いです🙇‍♂️

**Comment by komagata** [comment]
@machida こちらどういう状態になれば良い感じでしょうか

**Comment by shibaaaa** [comment]
2020/9/20 町田さんに上記を確認致しました。
komagataさん以外で、且つAdminでないユーザー2人を「何かのプラクティスに着手中」の状態にするということで仕様が固まりました。
