### ISSUE TITLE
docsの最終編集者を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1883]
- 最後に編集した人を出す。カラムとしては `last_updated_user`を追加する。
- 誰でも編集できるよう編集ボタンを出す。

**Comment by lamp7600** [comment]
@machida docsの編集について現在は以下の仕様であっていますでしょうか？
- 駒形さんと町田さんは誰が作成したものでも削除、編集できる。
- それ以外の人は自分が作ったdocsのみ削除、編集ができる。

**Comment by machida** [comment]
@lamp7600 
docsは誰でも編集ができるようになってますー

**Comment by lamp7600** [comment]
@machida  なるほど、ボタンを新規作成すればいいのですね。
本人が編集した場合は本人は除く仕様でいいでしょうか？
例えば僕がdocsを作ってAさんとBさんが編集したとすると、編集した人：Aさん　Bさん　のように表示するイメージです。

**Comment by komagata** [comment]
@machida Issue割り当てありがとうございます。
「編集した人の一覧ど表示したい」だとちょっと大事になっちゃうのでやめた方がいいかな〜と思います。

例えば別Issueとして「管理者がdocsを編集できるようにする」

**Comment by komagata** [comment]
:memo: 最後に編集した人を出す。

カラムとしては `last_updated_user`を追加する。
