### ISSUE TITLE
ユーザーの最終アクセス日時をプロフィール画面に表示したい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1893]
**何故この機能が必要なのか**

最後の日報 or 提出物を出してからしばらく音信不通のとなっている生徒さんが、ブートキャンプページにアクセスだけはしているのか、アクセスすらしていないのかを確認するため。（その後、必要に応じてメンターからフォローを入れる）

**機能の説明**

- ユーザーがブートキャンプページ（全ページ対象）にアクセスしたら、その日時を最終アクセス日時としてDBに保存する
- 最終アクセス日時はユーザーのプロフィール欄に表示する
- 最終アクセス日時を確認できるのはメンターのみとする

**その他**

- 1ヶ月以上（期間は要検討）アクセスがなければ、ダッシュボードにそのユーザーが表示される（ただしメンターのみ）、というような機能もあるとさらに良いかも。

**Comment by machida** [comment]
@takopom 

こちらをお願いします🙏

## ユーザープロフィールの最終活動日時の表示

<img width="575" alt="貼り付けた画像_2020_09_23_11_05" src="https://user-images.githubusercontent.com/168265/93956299-ccb6c400-fd8c-11ea-88fe-cae9a5964fd4.png">

現在、最終ログイン日時はプロフィールに表示されてるのですが、これの表示を変えたいと思います。

- メンターだけに表示される
- 「最終活動日時」を「最終ログイン日時」に変更
- 最終ログイン日時が一ヶ月前の場合、目立つようにしたいので、最終ログイン日時の文字に `is-important` というclassを付ける

このようにお願いします。
表示の仕方の変更は僕の方で行います。

## ユーザー一覧の最終活動日時の表示

現在、最終活動日時が一ヶ月前の場合、

![貼り付けた画像_2020_09_23_12_10](https://user-images.githubusercontent.com/168265/93962403-c11bcb00-fd95-11ea-9740-5de6a73d5449.png)

このように inactive というclass が付くようになっていますが、これを削除お願いします。

<img width="393" alt="貼り付けた画像_2020_09_23_12_11" src="https://user-images.githubusercontent.com/168265/93962516-f1fc0000-fd95-11ea-97d2-55a15ddd5150.png">

この部分に、1ヶ月ログインがありません、的な文字を表示したいと思います。
この文字は、メンターにだけ見えるようにお願いします。

## メンターのダッシュボード

メンターのダッシュボードに、1ヶ月以上ログインのないユーザーの一覧を表示をお願いします。
後でいじるかもしれないですが、一旦、「3日連続😢のユーザー」と同じ表示でお願いします。

---

上記3つのページの変更をお願いします🙏

**Comment by komagata** [comment]
@machida 詳細の情報ありがとうございます〜

**Comment by takopom** [comment]
@machida 
「ユーザー一覧の最終活動日時の表示」について、ご確認です🙇‍♀️
`inactive`のclassを削除してみて気が付いたのですが、
`active`のclassについても、削除しても差し支えないでしょうか？
HTMLを見ると、`active`の有無で活動状況が分かってしまうかも…と思ったためです💦

**Comment by machida** [comment]
@takopom ありがとうございます！確かに、activeも不要ですね。こちらも削除でお願いします🙏

**Comment by takopom** [comment]
@machida ご確認ありがとうございます。承知いたしました！
