### ISSUE TITLE
涙マークの日報が2回続いた場合は通知が欲しい（3日を2日に変更）

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#1894]
**何故この機能が必要なのか**
現状、日報のニコニコマークはユーザーのもやもやした気持ちを一番表していると思っています。
涙マークの日報が続いたユーザーに対して、メンターからのアクションを行うことでモチベーションの低下を防ぐことができるのではという仮説があり試してみたいです。
ここでいうメンターからのアクションについてはslackやペアプロでのサポートを検討していますがまだ固まってはいません。
続いた回数については2回か3回か迷ったんですが一旦閾値低くやって様子見していきたいと思ってます。

**機能の説明**
日報が投稿された時に、一つ前の日報を確認し涙マークの日報であれば通知に追加する。
通知対象はメンターだけでよいとおもってます。(全員に通知すると涙マークの心理的なハードルが上がるため)

**Comment by komagata** [comment]
@rlho 現状3日連続は実装されてますね〜

**Comment by rlho** [comment]
@komagata 
あれ、そうなんですね！把握しておらず失礼しました。
現状だとサポート不足かなと感じているので、閾値を2日連続(2日というか2日報連続)に変えていただきたいです！

**Comment by machida** [comment]
- [ ] 2日連続Sadのユーザーがいたらメンターへの通知する
- [ ] メンターダッシュボードの3日連続Sadのユーザーを2日連続に変更する
