### ISSUE TITLE
プラクティス「着手」状態から提出物を提出すると、ステータスが「提出」に変更されない。

### ISSUE THREAD

**Issue by gogutan** [fjordllc/bootcamp#1899]
## 概要

プラクティス「着手」状態から提出物を提出すると、ステータスが「提出」に変更されない。

## 再現手順

1. プラクティスのステータスを「着手」に変更
2. 提出物を提出
3. プラクティスのトップ画面でステータスを確認すると「着手」のまま

## 期待される振る舞い

ステータスが「提出」に変更される

### 「着手」に変更
<img width="827" alt="OS_X_Mountain_Lionをクリーンインストールする___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/93565994-3a4aa500-f9c7-11ea-8a6e-367f52d653da.png">

### 提出
<img width="715" alt="提出物作成___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/93566018-48002a80-f9c7-11ea-89eb-cec4fa4edc37.png">

### 「着手」のまま
<img width="827" alt="OS_X_Mountain_Lionをクリーンインストールする___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/93565994-3a4aa500-f9c7-11ea-8a6e-367f52d653da.png">

## 該当すると思われる箇所

https://github.com/fjordllc/bootcamp/blob/87e0266042ac8123a364a778057f0d95d2dbb877/app/models/product.rb#L74-L80

別のステータスに変更しようとした時に`Learning`が`find`で見つからず`new`されており、`save`されない。

**Comment by komagata** [comment]
@ima1zumi こちら後ほどお願いします〜
