### ISSUE TITLE
提出物をWIP状態から提出すると、ステータスが「提出」に変更されない、アドバイザーに通知されない

### ISSUE THREAD

**Issue by gogutan** [fjordllc/bootcamp#1900]
## 概要

提出物をWIP状態から提出すると、ステータスが「提出」に変更されない。
またアドバイザーに通知されず、アドバイザーのWatchステータスも`Watch中`に変更されない。

## 再現手順

1. 提出物を「WIP」で保存
2. 提出物を提出
3. プラクティスのステータスが「提出」に変更されない
4. アドバイザーに通知されず、Watchもされていない

## 期待される振る舞い

プラクティスのステータスが「提出」に変更される。
またアドバイザーに通知され、アドバイザーのWatchステータスも`Watch中`に変更される。

### 「WIP」で保存

<img width="907" alt="提出物作成___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/93567584-d4135180-f9c9-11ea-8064-9427f2bf73a1.png">

### 提出物を提出

<img width="917" alt="Terminalの基礎を覚えるの提出物___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/93567613-e1304080-f9c9-11ea-8714-63f4bed9501a.png">

<img width="912" alt="提出物編集___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/93567679-fa38f180-f9c9-11ea-9fc3-12a71289bc1a.png">

### 「未着手」のまま

<img width="701" alt="Terminalの基礎を覚える___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/93567932-63b90000-f9ca-11ea-9426-8ebd61b61b54.png">

### アドバイザーに通知されず、Watchもされていない

<img width="939" alt="ダッシュボード___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/93568018-86e3af80-f9ca-11ea-8630-1fa238a1ee96.png">

<img width="921" alt="Terminalの基礎を覚えるの提出物___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/93568445-25701080-f9cb-11ea-8d19-5468c1165905.png">

## 該当すると思われる箇所

https://github.com/fjordllc/bootcamp/blob/2045c332e46bf47f29c3a7723a2c5da875fd431e/app/models/product_callbacks.rb#L3-L19

WIPからの提出時は `after_create` 処理がされないため、`after_update` で同じような処理が必要？ただし、「**提出状態から再提出した場合は処理しない**」など、条件分岐について考慮する必要がありそうです。

## 備考

ステータスは、押し直せばいいので軽微なバグと思われます。（#1899 も同様）
ただし通知とWatchについては、通知できていないことに気付かず通知し直すこともできないので、早めに直した方が良さそうです。

**Comment by komagata** [comment]
@takopom こちら後ほどお願いします〜

**Comment by takopom** [comment]
@komagata 承知しました！
