### ISSUE TITLE
（アプリ全体）削除ボタンのデザインを控えめにする

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1901]
削除ボタンが大きく目立つデザインなので間違ってクリックしそうになる（実際クリックした人もいるらしい）。

<img width="523" alt="Screen Shot 2020-09-20 at 19 29 43" src="https://user-images.githubusercontent.com/1148320/93709257-d6b3a980-fb77-11ea-9593-86fd7d37554b.png">

画面表示を見直して、隅の方に小さくゴミ箱のアイコンを表示する、ぐらいのデザインでいいのではないか？

**Comment by masuyama13** [comment]
マージ済みなのでcloseします〜
