### ISSUE TITLE
フォローしたユーザーの日報が投稿されたら通知される機能がほしい

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#1902]
**何故この機能が必要なのか**

この人の日報が投稿されたら毎回読みたい、と思うことがある。
気になっている人の投稿を読むと、この人頑張ってるな〜と思いモチベーションアップにも繋がる。
現在は毎回手作業で見に行っているため、新しい日報が投稿されたら通知されるようになってほしい。

**機能の説明**

ユーザーをフォローすると日報提出時に通知が送られる。
自分がフォローしている人は分かるようになってほしい。
他の人が誰をフォローしているか・誰が誰にフォローされているかは分からないようにしたい。

**Comment by machida** [comment]
- フォロー何人は出ないで欲しい
- フォローされてることは知られないようにしたい
- 自分のフォロー一覧は見えるようにしたい

**Comment by ima1zumi** [comment]
@komagata @machida 

実装可能かどうか詰めきっていませんが、このような機能・画面で開発しようと考えています。
気になるところがあるかどうかご確認お願いします 🙇 

## 機能
- ユーザーはユーザーをフォロー・フォロー解除できる
- フォローすると日報が投稿されたときに通知が来る
    - 更新時には通知が来ない
    - コメントは通知が来る（デフォルトで `watch中` になる）
- 自分のフォロー一覧を見ることができる
    - 他人からは見ることができない

## 画面イメージ
### フォローする
ユーザーの個別ページからフォローできる
<img src="https://user-images.githubusercontent.com/52617472/94943938-73c8f780-0513-11eb-874d-2f72641365c1.png" width="300px">

### フォロー一覧を見る
ボタンの位置ここでいいのか悩んでます 🤔 

<img src="https://user-images.githubusercontent.com/52617472/94948782-da9ddf00-051a-11eb-9b0b-511c069b7d8f.png" width="300px">

### フォロー一覧
<img src="https://user-images.githubusercontent.com/52617472/94950683-fb1b6880-051d-11eb-9057-333144328613.png">

**Comment by komagata** [comment]
@ima1zumi いいと思います！

**Comment by ima1zumi** [comment]
📝 
- フォロー or フォロー解除しても相手に通知が飛ばない、相手からはフォローされているかどうか分からない ということを分かりやすく伝える
    - 実装後初回はお知らせで、それ以降はプラクティスのどこかに文言を入れて周知する？
- docsに使い方を書く
