### ISSUE TITLE
メンターメモをメンターのときだけ、提出物のページに表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1903]

**Comment by machida** [comment]
@shibaaaa こちらをお願いします。
提出物個別ページに、メンターでログインしている場合は、そのプラクティスのメンターメモを表示する様にしてください。
ちょっと複雑なレイアウトにする予定なので、デザインは僕がやります。

このIssueは、最終的に別のページ遷移なく編集のIssueと合わせリリースするので、メンターメモが空でも表示お願いします。

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/issues/1904
これと組み合わせます

**Comment by shibaaaa** [comment]
@machida 
アサイン頂きありがとうございます！
仕様について確認させて頂きたい点がございます。
- 提出物個別ページでメモ入力蘭とメモの表示部分を実装すると考えていますが、これは提出物に対するコメントを投稿する場合と同じような実装でよろしいのでしょうか？
- 登録してあるメモの編集・削除ができるのはメンター全員でしょうか、それともそのメモを残したメンターの方のみでしょうか？

ご確認の程、よろしくお願い致します🙇‍♂️

**Comment by komagata** [comment]
@machida いきなりVue.jsでの実装は難しいのでまずは表示部分だけやるというのはいかがでしょう？

**Comment by shibaaaa** [comment]
📝 2020/9/23　振り返りMTGで仕様を確認。
- 現状はプラクティス詳細ページにのみメンターメモがあるので、それをそのプラクティスの提出物ページ上でも表示/編集ができるようにする。
- 1メモ/1プラクティス。
- 編集できるのはメンター全員。
- このissueを実装後に #1904 を実装して本番にリリースする。
