### ISSUE TITLE
docs個別ページからタグを付けられるようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1909]

**Comment by shibaaaa** [comment]
@machida 
僕の勉強不足で恐縮なんですが、こちらの仕様の画面イメージがどのようにすべきかイメージできずにおります...。

Docsの編集ページ(editアクション)ではなくDocs個別ページ(showアクション)でのタグの追加・編集ができるようにする、という解釈でおりますが、サンプルになりそうなページ等ございましたら教えて頂けると幸いです🙇‍♂️

**Comment by shibaaaa** [comment]
こちら雑談ルームにて駒形さんに確認いたしました。
Docs個別ページのタグ欄にタグ追加用のボタンを用意し、そちらをクリックすることでテキストエリアが表示されるような仕様で進めていきます🙏

**Comment by machida** [comment]
@shibaaaa 反応が遅れてすいません🙇‍♂️

> Docs個別ページのタグ欄にタグ追加用のボタンを用意し、そちらをクリックすることでテキストエリアが表示されるような仕様で進めていきます🙏

はい！それでお願いしますー
