### ISSUE TITLE
モバイル版から検索できるようになってほしい

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#1912]
**何故この機能が必要なのか**

現在のモバイル版には検索フォームが表示されておらず、検索することが出来ない。
モバイル版から検索したいことがあるため、検索できるようになってほしい。

**機能の説明**

モバイル版に検索フォームが表示され、PC版と同様に検索できる。

**参考**
GitHub モバイル版ではハンバーガーメニューから検索できるようになっている

<img src="https://user-images.githubusercontent.com/52617472/93993845-30abad80-fdca-11ea-8472-52d549c7aaab.jpeg" width="300">

**Comment by ima1zumi** [comment]
ほしい。。。

**Comment by machida** [comment]
検索できるようにしましたー
