### ISSUE TITLE
日報をコピーした時のフラッシュメッセージが欲しい

### ISSUE THREAD

**Issue by lamp7600** [fjordllc/bootcamp#1913]
## 何故この機能が必要なのか
日報のテンプレートを個人で持っていて、前日の日報をコピーしている人が多いと思います。
しかし、コピーは編集ボタンの隣にあります。いったん編集画面に入るとコピーした日報なのか否かが分かりません。

提出済みの日報をコピーと間違えて中身を削除してしまう事故が200回くらい日報を書いている中で3回くらいありました。
この事故を無くしたいです。

## 機能の説明

日報をコピーして編集画面に遷移するときにフラッシュメッセージを表示します。

**Comment by machida** [comment]
@lamp7600 おおー、これ必要です！！お願いしますー🙏
