### ISSUE TITLE
卒業したらSlackに通知を送りたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1920]
#fjord チャンネルに送りたい。

卒業に伴う処理を @togo さんや @komagata がするので。

**Comment by hogucc** [comment]
@komagata 
こちらのissueについて2点確認させてください。

①slackへする内容はメッセージ（例えば、「◯◯さんが卒業しました！おめでとうございます🎉」といった内容）で良いですか。
合っている場合は文言の案等ありましたらご連絡いただけると助かります🙇‍♀️
違う場合は通知内容を教えていただけますでしょうか。

②slackに#fjordチャンネルが見当たらなかったのですが、こちら未作成のチャンネルという認識で合っていますか？
合っているという前提で、チャンネルは駒形さんに作成を依頼すれば良いでしょうか。私の方で作って良いか不明だったので確認させていただきました。

**Comment by machida** [comment]
チャンネルについては、非公開で既に存在してますー

**Comment by hogucc** [comment]
@machida 
ご回答ありがとうございます。
チャンネルは既に存在してるとのこと、承知しました！

**Comment by hogucc** [comment]
@komagata 
> ①slackへ通知する内容はメッセージ（例えば、「◯◯さんが卒業しました！おめでとうございます🎉」といった内容）で良いですか。
合っている場合は文言の案等ありましたらご連絡いただけると助かります🙇‍♀️
違う場合は通知内容を教えていただけますでしょうか。

お手隙の際こちらについてご回答いただけると助かります🙇‍♀️
よろしくお願いいたします。

**Comment by komagata** [comment]
@hogucc はい、そちらで大丈夫です。この通知は内部のメンバー（管理者）しか見れないチャンネルなので卒業した人がわかればOKです〜

ついでにその人のユーザーページへのリンクを含めていただけるとその後、卒業処理をする人が楽なのでお願いできれば〜

**Comment by hogucc** [comment]
@komagata 
ご回答ありがとうございます！
承知しました！通知にユーザーページへのリンクも含めるように実装します💪
