### ISSUE TITLE
ポートフォリオ一覧ページが欲しい

### ISSUE THREAD

**Issue by gogutan** [fjordllc/bootcamp#1923]
**何故この機能が必要なのか**

現状では他の人のポートフォリオを参考にしようと思った時に、

1. ユーザー一覧を開く
2. ポートフォリオを作っていそうな人を開く
（その人のポートフォリオが無ければ 1 に戻る）
3. ポートフォリオページを開く

というステップを踏む必要がある。
最近はLT会なども盛んでポートフォリオを活用している人が増えてきたため、ポートフォリオの一覧ページがあると嬉しい。

**機能の説明**

ポートフォリオに1つ以上の作品を登録している人の

- ユーザー名
- ユーザーアイコン
- 作品タイトル一覧

が一覧で表示される。

![gogutanのポートフォリオ___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/50437473/94225724-c19c9900-ff30-11ea-9367-1e70354c7d99.png)

個人的には、**左側のサイドバーにもリンクがあるといいのかな**と思っています。自分はプラクティスの後半でLT会資料やnpmモジュールなどを作る機会があり、その時に初めて「そうだ、他の方のポートフォリオも見てみよう」と考えました。それまで、他の方の日報や提出物は参考にさせていただいたものの、ポートフォリオ機能についてはあまり気にかけたことがなかったのです😇
目立つ場所にポートフォリオ一覧ページがあると、**プラクティスを始めたばかりでも気軽にいろいろなポートフォリオを見ることができ、今後の学習のイメージが膨らむ**のではないかと思います。

**Comment by SuzukaHori** [comment]
@komagata @machida 

お疲れさまです。
これからこちらの実装に取り組みますが、現時点でのイメージに問題がないかを確認したいです🙏
よろしくお願いいたします。

## 実装のイメージ
### /users/user_id/portfolio
各ユーザのポートフォリオページに、ポートフォリオ一覧ページへのリンクを追加します。
![スクリーンショット 2024-02-01 12 03 05](https://github.com/fjordllc/bootcamp/assets/129706209/ae3ba843-de44-4668-bef5-d3ebc5f6132b)

### /portfolio
全員のポートフォリオ一覧を新規に作り、ポートフォリオの情報と「作品を追加」ボタンを追加します。
![スクリーンショット 2024-02-01 11 56 02](https://github.com/fjordllc/bootcamp/assets/129706209/afdc8c92-1342-4010-840d-9fc03feebe10)

## お聞きしたいこと
- 一覧ページのURLについて
日報一覧ページなどを参考に`/portfolio`と考えました。ご意見を伺いたいです。
- 表示する情報について
「タイトル・アイキャッチ・ユーザアイコン・ユーザ名」が必要ではないかと考えました。こちらについてご意見を伺いたいです。
ちなみに日報一覧やブログ一覧には、以下のような情報がありました。
  - 登録日：ポートフォリオに登録した日と実際に活動した日はイコールでないので、不要と考えました。
  - 説明文の最初：タイトル・アイキャッチを見れば大体内容がわかるので、不要と考えました。

- その他、文言やアイコンを追加する位置など、現時点で認識が異なる部分があればご指摘いただきたいです🙇‍♀️

**Comment by machida** [comment]
@SuzukaHori イメージの共有ありがとうございます！！いい感じですー
これでお願いします🙏

**Comment by SuzukaHori** [comment]
@machida 
ご確認ありがとうございます🙏🙏
一旦こちらで進めて、また不明点がありましたら質問させていただきます！

**Comment by machida** [comment]
了解です！！
よろしくお願いしますー

**Comment by komagata** [comment]
@SuzukaHori 

> /users/user_id/portfolio
> /portfolio

Portfolioとは複数の紙を入れる書類入れ（というより画家が複数の紙の絵を挟んでおく紙ばさみ・折りカバン）のことだそうです。

１人が作った複数の作品を集めたものは単数系の`portfolio`でいいと思いますが、複数人の`portfolio`を集めたものは複数形の`portfolios`が良さそうです〜。

**Comment by SuzukaHori** [comment]
@komagata 
ご返信ありがとうございます🙏
なるほど、そういう使い分けがされていたのですね！一覧ページは`/portfolios`として進めます。

**Comment by SuzukaHori** [comment]
@machida
お疲れさまです！
こちらイメージをもとに実装中ですが、うまくいかなかった部分があるため、方針を相談したいです🙇‍♀️

---
元から使用しているポートフォリオページでは、`app/views/works/_work.html.slim`の部分テンプレートを使っています。ただ、こちらは今回追加する一覧ページと項目が異なるため、**似たような部分テンプレートが2つ存在している状態**になっています。

- 元からある個別のポートフォリオページ
「アイキャッチ・タイトル・説明文」が表示されている。
<img width="1151" alt="スクリーンショット 2024-02-02 21 36 59" src="https://github.com/fjordllc/bootcamp/assets/129706209/8fe2ad78-3fb2-4150-ae4d-47106efd4c27">

- 新しく作成のポートフォリオ一覧ページ
「アイキャッチ・タイトル・ユーザアイコン・ユーザ名」が表示されている。
<img width="1155" alt="スクリーンショット 2024-02-02 21 34 45" src="https://github.com/fjordllc/bootcamp/assets/129706209/07d4a722-febf-4fd0-8ff1-8d71d382beda">

既存の実装では、ユーザごとのページと一覧ページが同じ項目・体裁のものがいくつかありました。
（例：日報一覧ページとユーザごとの日報ページには、どちらも日報名・ユーザ名・ユーザアイコンが表示されている）

そのため、ポートフォリオページの実装の方針を伺いたいです🙇‍♀️
- ユーザごとのページと一覧ページの項目を揃えて、同じ部分テンプレートを使う。
- ユーザごとのページと一覧ページの項目を揃えず、共通化できる部分のみ共通化する。

個人的な意見ですが、「アイキャッチ・タイトル・ユーザアイコン・ユーザ名」で揃えて共通化した方がコードを簡潔に書け、メンテナンスの手間が省けるかなと思いました。

ご検討のほど、よろしくお願いいたします🙏

**Comment by machida** [comment]
@SuzukaHori 

> ユーザごとのページと一覧ページの項目を揃えて、同じ部分テンプレートを使う。

これで行きたいと思いますー。
今回はユーザーごと、全ての一覧は同じ表示にしますが、もし、ユーザーごとだけユーザーを非表示にするなど、微妙に違う表示になったときは、同じテンプレート内で分岐したいと思います。

**Comment by SuzukaHori** [comment]
@machida 
ご返信ありがとうございます🙏
微妙な表示の違いは同じテンプレート内で条件分岐をすれば対応できるのですね、勉強になりました。

同じテンプレートを使用し、ユーザーページ・一覧ページで同じ項目を表示するようにして進めます！

**Comment by SuzukaHori** [comment]
本番環境で動作確認できましたので、IssueをCloseします！
