### ISSUE TITLE
N+1問題（プラクティス一覧画面）

### ISSUE THREAD

**Issue by gogutan** [fjordllc/bootcamp#1926]
# 1つ目
https://github.com/fjordllc/bootcamp/blob/8148a2986ad926a290b99b5d803fbcf24a4c3975/app/controllers/courses/practices_controller.rb#L9
修正案
`.includes(practices: [{ started_students: { avatar_attachment: :blob } }, :learning_minute_statistic])`

# 2つ目
https://github.com/fjordllc/bootcamp/blob/8148a2986ad926a290b99b5d803fbcf24a4c3975/app/controllers/api/reports/recents_controller.rb#L6
修正案
`.includes(user: [{ avatar_attachment: :blob }, :company])`

1番表示に時間のかかりそうなプラクティス一覧画面のN+1問題はこれだけのようですが、前回のN+1問題一斉点検（#1071）から1年ほどが経過し、他のページにもいくつかN+1があるようです。
前回と同様に、分類ごとにN+1問題を洗い出して順々にマージするのが良いでしょうか？

**Comment by gogutan** [comment]
雑談タイムで相談させてもらい、ぜひやってくださいとのことでしたので進めさせていただきます🙆‍♂️

**Comment by shibaaaa** [comment]
マージ済なのでクローズしておきます〜
