### ISSUE TITLE
メンターへのメンションが特別な記法であることを強調したい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1932]
https://github.com/fjordllc/bootcamp/pull/1919 で実装されたメンターへのメンション記法だが、本文には普通のテキストとして表示されるので、何かしらの方法で強調されるとUXがよくなると思った。（今のままだと本当にメンションされているか不安になるかも）

<img width="131" alt="Screen Shot 2020-09-27 at 9 45 30" src="https://user-images.githubusercontent.com/1148320/94352965-c8e5b300-00a6-11eb-9ef9-b43b94b58a34.png">

たとえば以下のURLにリンクを貼るとか。

https://bootcamp.fjord.jp/users?target=mentor

**Comment by cafedomancer** [comment]
本番環境で動作していることを確認したので close します。
