### ISSUE TITLE
[Markdown]コードブロック内に `@mentor` の文字列があるとメンションの通知が送信されてしまう

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1938]
## 概要

コードブロック内に `@mentor` の文字列があるとメンションの通知が送信されてしまう

## 再現手順

1. 日報の本文に `@mentor` の文字列を含むコードブロックを記述する（[参考](https://bootcamp.fjord.jp/reports/18663)）
2. 「投稿」をクリック。
3. メンターに通知が飛ぶ。

## 期待される振る舞い

- コードブロック内の`@mentor`は通知対象外とする。

## その他

`@mentor`以外のメンション（`@komagata`など）も同じように通知されるかもしれない。（未検証）

## 関連Issue

Ref: https://github.com/fjordllc/bootcamp/pull/1919

**Comment by JunichiIto** [comment]
修正済みかどうかは未確認だが、最近発生してない気がする（そもそもユースケースとして滅多に発生しなさそう）のでいったんクローズ。

**Comment by JunichiIto** [comment]
@machida  これ、やっぱり発生してるかも？
（2022/9/5のメンターミーティング議事録参照）

**Comment by machida** [comment]
@JunichiIto こちら優先度上げますー

**Comment by machida** [comment]
📝 

コードブロックの中、

```
@menrtor
```

インラインのコードの中

`@mentor`

の＠はメンションにならないようにする。

**Comment by komagata** [comment]
@niikz こちらいかがでしょうか？
もし「チーム開発おかわり」自体が今後作業が難しそうであればおっしゃっていただければと思います〜。

**Comment by niikz** [comment]
@komagata 
遅くなり申し訳ございません。

**Comment by komagata** [comment]
@niikz かしこまりました。ではIssueの担当から外させていただきますね。

**Comment by reckyy** [comment]
本番確認できたので、closeします。
