### ISSUE TITLE
たまに落ちるシステムテストがある（コメント通知編）

### ISSUE THREAD

**Issue by gogutan** [fjordllc/bootcamp#1951]
コメント通知関連でよく落ちるシステムテストがあります。
（下記いずれも過去2週間以内に[test/system/notification/watches_test.rb](https://github.com/fjordllc/bootcamp/blob/master/test/system/notification/watches_test.rb)で落ちている）

https://app.circleci.com/pipelines/github/fjordllc/bootcamp/797/workflows/716616f0-2062-464e-9669-c43e07f99a42/jobs/4512
https://app.circleci.com/pipelines/github/fjordllc/bootcamp/825/workflows/b1c280b8-fcb2-4c1a-b6f6-2663ec96ee76/jobs/4543
https://app.circleci.com/pipelines/github/fjordllc/bootcamp/881/workflows/a4913ed1-c2f2-4dd2-b03c-4b73464218ef/jobs/4604
https://app.circleci.com/pipelines/github/fjordllc/bootcamp/890/workflows/8ad09fc7-502f-48c8-83a8-8be56a366d72/jobs/4614

[「bootcampのテストが一部パスしない」のQ&A](https://bootcamp.fjord.jp/questions/468)の関連だと思うのですが、下記のようにVueで実装されているコメントの表示を待つような仕組みを試してみたところ、ローカル環境のシステムテストでは落ちなくなりました。

**[test/application_system_test_case.rb](https://github.com/fjordllc/bootcamp/blob/master/test/application_system_test_case.rb)に下記を追加**
```Ruby
COMMENT_WAIT_SECOND = (ENV["COMMENT_WAIT_SECOND"] || 5).to_i
def wait_for_last_comment(comment)
  Timeout.timeout(COMMENT_WAIT_SECOND) do
    loop do
      break if all(".thread-comment__description")&.last.has_text?(comment)
    end
  end
end
```

**[test/system/notification/watches_test.rb](https://github.com/fjordllc/bootcamp/blob/master/test/system/notification/watches_test.rb)の一部**
```Ruby
within(".thread-comment-form__form") do
  fill_in("answer[description]", with: "Vimチュートリアルがおすすめです。")
end
click_button "コメントする"
# 下記を追加
wait_for_last_comment("Vimチュートリアルがおすすめです。")
```

なお、[test/system/notifications_test.rb](https://github.com/fjordllc/bootcamp/blob/master/test/system/notifications_test.rb)、[test/system/mention/comments_test.rb](https://github.com/fjordllc/bootcamp/blob/master/test/system/mention/comments_test.rb)、[test/system/notification/answers_test.rb](https://github.com/fjordllc/bootcamp/blob/master/test/system/notification/answers_test.rb)、[test/system/notification/comments_test.rb](https://github.com/fjordllc/bootcamp/blob/master/test/system/notification/comments_test.rb)にもコメント通知関連のテストがあるため、ここでもコメントの表示を待ちたいです。

この解決方法がCircleCI上でも有効かどうか定かではないのですが、これでシステムテストが落ちる頻度を下げられるか試してみたいと考えています、どうでしょうか？

**Comment by gogutan** [comment]
@komagata 
ありがとうございます、[「bootcampのテストが一部パスしない」のQ&A](https://bootcamp.fjord.jp/questions/468)と合わせてもう一度確認しました。
処理開始時と完了時において見た目上の変化がないケースもあるため、Vue.jsの処理を待つテストでは共通して https://github.com/fjordllc/bootcamp/blob/master/test/application_system_test_case.rb#L27 の`wait_for_vuejs`を使っている、と理解しました。今回のケースもこの方法で問題なさそうです。

今回は新たなメソッドを追加せず、「コメントする」をクリック後に`wait_for_vuejs`するのみで対応したいと思いますが、この方針で問題ありませんでしょうか？

**Comment by komagata** [comment]
@gogutan 本当はcapybaraの各種メソッドが待つ処理に対応してるのでそれで対応できたら最高なのですが、なぜそれで対応できないか僕も調べられてないので、上記でOKです〜

**Comment by gogutan** [comment]
了解しました！該当するテストに`wait_for_vuejs`を入れてPR作成します。

**Comment by gogutan** [comment]
マージ後18日間のシステムテストを確認したところ、頻繁に失敗していた [test/system/notification/watches_test.rb](https://github.com/fjordllc/bootcamp/blob/master/test/system/notification/watches_test.rb) で落ちたケースは1度もないようなので、こちらのIssueはCloseします。
今後、`wait_for_vuejs`を使わずCapybaraの各種メソッドで対応可能なことが判明した場合は、新たにPRを作成します。
