### ISSUE TITLE
docsを更新すると投稿者が〜を投稿しましたと通知が来る

### ISSUE THREAD

**Issue by lamp7600** [fjordllc/bootcamp#1953]
## 概要
画像のようにlampがkomagataさんの投稿を編集するとkomagataさんが投稿しました。という通知が来ます。

![image](https://user-images.githubusercontent.com/60137763/94568261-3bbd7c80-02a7-11eb-96f1-838f31bd5fea.png)

## 期待される振る舞い
xxさん(編集した人)がooを更新しました。のような通知が適切ではないでしょうか？

## 追記
バグというより通知の仕様でした。

**Comment by machida** [comment]
published_at が入ってないからかな？
何かしら published_at に日付を入れるなどして、通知が飛ばないようにしたい。

**Comment by lamp7600** [comment]
@machida 
しかし先ほど編集されたこのdocsからは通知が来ませんでした。
![image](https://user-images.githubusercontent.com/60137763/94784481-2eb89e80-0409-11eb-94fb-46c650a8d15a.png)

**Comment by machida** [comment]
@lamp7600 これはすでに過去更新されたことがあって、published_at が空ではなかったからもしれないです（よく編集するページなので）。どうだろう？

**Comment by lamp7600** [comment]
@machida docsの作成後に`published_at`に作った日付が入り、更新すると`published_at`が空なら通知が来るコードになっていました！

**Comment by machida** [comment]
@lamp7600 なるほど、調査ありがとうございます！

**Comment by lamp7600** [comment]
@machida こちら閉じて大丈夫でしょうか？

**Comment by machida** [comment]
@lamp7600 これはまだ解決されていないので、そのままでお願いします。問題を整理すると、published_at のカラムが出来る前に作られた doc は編集をした時点で通知が飛んでしまう、というバグがあります。なので、published_at が空の doc に対して、created_at の値を入れるなどの対応をしたいと思います。

**Comment by lamp7600** [comment]
@machida 了解です！

**Comment by ima1zumi** [comment]
#2111 で対応済のためCloseします。
