### ISSUE TITLE
メールの背景を白くしたい（ダークモードだと黒いので）

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1958]

**Comment by KishiKyousuke** [comment]
@komagata @machida 
ダークモードで色が変わってしまう部分にあたる、mailerのlayoutファイルmailer.erb.html内の`<div>`に`background-color: white;`を適用したのですが、Macのメールアプリ上で確認する方法がわかりません😥
本番環境で試しにメールを受け取ってみて確認するという形式をとったほうが良いのでしょうか❓

**Comment by KishiKyousuke** [comment]
@komagata @machida
雑談ルームで町田さんからお答えをいただきました❗
letter openerでディベロッパーツールを使用して背景を黒に変更した状態で確認を行ってみます💪
ありがとうございました❗😊

**Comment by KishiKyousuke** [comment]
@komagata @machida 
プルリクエストmerge後、受信したメールの表示を確認してみましたが背景は黒のままでした😓
背景色を白に変更するだけでは表示は変わらないようです💦

![image](https://user-images.githubusercontent.com/59789739/95145919-692e8c80-07b7-11eb-80ce-ce00dd2f12ae.png)

ちなみに「表示→メッセージ→明るい背景で表示」を選択すると通常の色でメールの内容を表示することができるようです。

![image](https://user-images.githubusercontent.com/59789739/95146501-f1616180-07b8-11eb-973b-b3899349a94f.png)

![image](https://user-images.githubusercontent.com/59789739/95146533-050cc800-07b9-11eb-9a7f-7ea09b5e89b1.png)

**Comment by komagata** [comment]
@KishiKyousuke もうちょっと解決方法を調べてみてください〜

**Comment by KishiKyousuke** [comment]
自分のIPhoneでのメールの表示画像を貼っておきます。
ダークモードだと以下のように背景が透けてしまいタイトルが読めない状態になってしまいます。

![image](https://user-images.githubusercontent.com/59789739/95305324-c82bf880-08c0-11eb-8770-508107d71d0f.png)

**Comment by ima1zumi** [comment]
対応が難しいという話だったと思うので一旦Closeしちゃいます。

@KishiKyousuke 補足があればコメントお願いします！
