### ISSUE TITLE
提出物一覧画面で確認済みのスタンプが表示されない。

### ISSUE THREAD

**Issue by mh-mobile** [fjordllc/bootcamp#1959]
## 概要

既に確認済みの提出物で、提出物詳細画面では確認済みスタンプが表示されるが、
提出物一覧画面では確認済みスタンプが表示されない。

※ シークレットモードでも再現するため、ブラウザキャッシュの問題ではなさそうです

## 再現手順

* [ペーパープロトタイプを作る](https://bootcamp.fjord.jp/practices/174/products)の提出物一覧画面に遷移する。

## 期待される振る舞い

* 提出物一覧画面でも、提出物詳細画面と同様に、確認済みのスタンプが表示されること

## スクリーンショット

* 提出物一覧画面

![スクリーンショット_2020-09-30_17_42_10-2](https://user-images.githubusercontent.com/13811034/94668741-5c3f1280-034b-11eb-88ee-6d6d0085b6d4.png)

* 提出物詳細画面

![スクリーンショット 2020-09-30 17 41 38](https://user-images.githubusercontent.com/13811034/94666276-3e23e300-0348-11eb-8452-506ef58d985a.png)

* プラクティス詳細画面 
![スクリーンショット 2020-09-30 17 44 01](https://user-images.githubusercontent.com/13811034/94666307-4845e180-0348-11eb-9e16-1ce1ba886aad.png)

* プラクティス一覧画面 
![スクリーンショット 2020-09-30 17 42 48](https://user-images.githubusercontent.com/13811034/94666379-5dbb0b80-0348-11eb-813e-bf40ee8dc056.png)

## 環境

 - OS: [MacOS Catalina 10.15.5]
 - ブラウザ: [Chrome, Safari]

**Comment by mh-mobile** [comment]
今見ると表示されていたので、クローズします。

![image](https://user-images.githubusercontent.com/13811034/94707253-3121e680-037e-11eb-8998-ce86205b4146.png)

**Comment by universato** [comment]
これは自分も2-3週間以上前に1度経験していて、タイムラグが生じるときがあるのかもしれないですね。

**Comment by universato** [comment]
[ボウリングのスコア計算プログラム](https://bootcamp.fjord.jp/practices/210/products)や[ペーパープロトタイプを作る](https://bootcamp.fjord.jp/practices/174/products)でも11日確認済みとなっているものについて15日現在表示されていないものがあり、同じ事象が生じていますね。スーパーリロードしてもダメだったので、再オープンしても良さそうと思いました。

**Comment by mh-mobile** [comment]
なるほどですね、再オープンしておきます。
あとで内部のロジックもみてみます。

**Comment by mh-mobile** [comment]
メモ：

プラクティスの提出物の一覧表示で、コレクションキャッシュが利用されている。

```slim
        = render partial: "products/product",
          collection: @products,
          as: :product,
          cached: true
```
[https://github.com/fjordllc/bootcamp/blob/master/app/views/practices/products/index.html.slim#L21-L24](https://github.com/fjordllc/bootcamp/blob/master/app/views/practices/products/index.html.slim#L21-L24)

提出物のパーシャルでは、提出物に関連づいたCheckオブジェクトがあれば、確認済みスタンプを表示する処理になっている。

```slim
    - if product.checks.any?
      .stamp.stamp-approve
        h2.stamp__content.is-title 確認済
        time.stamp__content.is-created-at
          = l product.checks.last.created_at.to_date, format: :short
        .stamp__content.is-user-name
          = product.checks.last.user.login_name
```
[https://github.com/fjordllc/bootcamp/blob/master/app/views/products/_product.html.slim#L33-L39](https://github.com/fjordllc/bootcamp/blob/master/app/views/products/_product.html.slim#L33-L39)

Checkオブジェクトが生成されたときに、ChecksCallbacks#after_createメソッドが呼び出される。
この時に提出物のキャッシュの削除を行うdelete_product_cacheメソッドを読んでる。

```rb
class CheckCallbacks
  def after_create(check)
    if check.sender != check.receiver
      NotificationFacade.checked(check)
    end

    update_product_status(check)
    delete_report_cache(check)
    delete_product_cache(check)
  end

  def after_destroy(check)
    delete_report_cache(check)
    delete_product_cache(check)
  end

  private

    def update_product_status(check)
      if check.checkable_type == "Product"
        check.checkable.change_learning_status(:complete)
      end
    end

    def delete_report_cache(check)
      if check.checkable_type == "Report"
        Cache.delete_unchecked_report_count
      end
    end

    def delete_product_cache(check)
      if check.checkable_type == "Product"
        Cache.delete_not_responded_product_count
      end
    end
end
```

delete_product_cacheでは、Cache.delete_not_responded_product_countを呼び出している。

Cacheクラス自体は、以下を参照。
[https://github.com/fjordllc/bootcamp/blob/master/app/models/cache.rb](https://github.com/fjordllc/bootcamp/blob/master/app/models/cache.rb)

疑問点:
* 提出物のコレクションキャッシュはいつ削除されるのか？
  * 本番では、Redisが利用されているので、Redisのキャッシュの期限が切れるまで？？
* 確認済みのCheckオブジェクトが生成されたときに、提出物のコレクションのキャッシュを削除する処理が必要？

備考:
* 提出物詳細の確認済みスタンプの表示自体はVue.jsを使って処理しているため、提出物一覧の確認済みのスタンプの表示ロジックとは異なる。
