### ISSUE TITLE
休会機能が欲しい

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#1960]
**何故この機能が必要なのか**
仕事や個人的な都合で1-2ヶ月フィヨルドでの活動ができない場合、現在は退会しか手段がない。
退会から復活、ということもできなくはないが現状復活する人は少ない。
気持ちとして一度退会したものをもう一回入りなおすことは精神的にハードルが高いからではないかということを仮説として思っているため、休会機能が欲しい。

**機能の説明**
- ユーザーは休会を申請することができる
- 休会は申請した日から1ヶ月,2ヶ月と1ヶ月単位で休会できる期間を選択でき、最大2ヶ月まで休会可能（ここは変更してもいいと思います)
- 休会中は課金されない
- 休会中は復帰ボタンからいつでも復帰ができる(これはwantでもいいかも
- 一度休会した後は2ヶ月たった後でないと再度休会することができない（ここは変更してもいいと思います)

**Comment by komagata** [comment]
💬 仕様を検討中

- 「休会ボタン」「休会ページ」を作る。（今の退会ページのように色々事前説明が必要だと思うので）
- 休会している状態でログインしようとすると「復学ページ」にリダイレクトされる。
- 「復学ページ」には説明と「復学ボタン」がある。

### 休会のルール

- ６ヶ月以上休会していると退会になる。
- 休会すると２ヶ月は復帰できない。
