### ISSUE TITLE
メンターがコメントしているのに提出物一覧にメンターのアイコンが出ていない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#1966]
## 概要

メンターがコメントしているのに提出物一覧にメンターのアイコンが出ていない

## 再現手順

1. https://bootcamp.fjord.jp/products/not_responded にアクセス。
2. https://bootcamp.fjord.jp/products/5244 がメンターのアイコンが出ない（コメント0件として扱われている？）

## 期待される振る舞い

コメント件数やコメントしたメンターのアイコンが表示される。

## スクリーンショット

![Screen Shot 2020-10-02 at 9 30 51](https://user-images.githubusercontent.com/1148320/94876566-f8276600-0492-11eb-9618-313ca68b59c7.jpg)

**Comment by JunichiIto** [comment]
この現象、まだ引き続き発生しているようです。（ https://bootcamp.fjord.jp/products/5439 など）
提出物確認の効率が下がるので、早めに対応してもらえると助かります 🙏

**Comment by machida** [comment]
@komagata こちら対応できましたらお願いします🙏
