### ISSUE TITLE
Docsが更新された箇所を知りたい

### ISSUE THREAD

**Issue by kotakanazawa** [fjordllc/bootcamp#1967]
## 何故この機能が必要なのか

現状、Docsが更新されたらDocsページの上に来るようになっているが、そのページのどこが更新されたのかわからない。

## 機能の説明

Docs内でどこが更新されたのかひとめでパッと知りたい。
（更新された箇所に数秒の間色がつくなど）

**Comment by shibaaaa** [comment]
#1678 こちらのIssueと同様でしょうか？

**Comment by kotakanazawa** [comment]
@shibaaaa 同様ですね〜。こちらはクローズします〜！
