### ISSUE TITLE
新規ユーザー登録時の「主な学習場所」にオフィス閉鎖中の旨を書くか、項目を削除する

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#1972]
**なぜこの機能が必要なのか**
新規ユーザー登録時の「主な学習場所」という項目でフィヨルドブートキャンプオフィスか自宅を選択できますが、現在はオフィス閉鎖中です。
オフィス閉鎖中のリンク([7月18日からオフィス閉鎖へ](https://fjord.jp/articles/2020-07-16.html))を貼るか、今後オフィスを閉める予定であればこの項目自体をなくしたほうが良さそうです。

![image](https://user-images.githubusercontent.com/52617472/95153365-3b9f0e80-07ca-11eb-8784-21da1392e54a.png)

**Comment by machida** [comment]
おお、確かに！！

**Comment by gogutan** [comment]
https://bootcamp.fjord.jp/faq にもオフィスについての記述があるため、こちらも何か対応した方がいいかもしれないです！
![FAQ___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/50437473/95322175-0e8c5200-08d7-11eb-8ae3-cf2e2a53b068.png)

**Comment by machida** [comment]
@gogutan ありがとうございます！！貴重なポイント1のissue！

**Comment by machida** [comment]
gogutanさんの指摘は別Issueにしました。
https://github.com/fjordllc/bootcamp/issues/1986

**Comment by machida** [comment]
新規ユーザー登録時の「主な学習場所」の項目を削除にしたいと思います。
@komagata いかがでしょう？

**Comment by komagata** [comment]
@machida @gogutan まだもうオフィスを完全に生徒向けに閉鎖するという決断を下してないので、いろいろとそれからと考えていたんですが。

どうしますかね〜

**Comment by machida** [comment]
@komagata 

現状、この質問があるとユーザーを混乱させてしまうので、ここは早めに対応をしたいと思います。

対応としては、

- デフォルトの値をリモートにしてコメントアウト（必須項目のため）
- 項目の削除

があるかと思うのですが、削除でいきたいと思います。オフィスを復活することになったときには、受講生も入れ替ってると思うので、再度登録にしたいと思います。

（そのときは、ローカル、リモートの選択ではなく、ローカル希望の場合だけチェックボックスの対応にしたいと思います。）

**Comment by machida** [comment]
@KishiKyousuke 

こちらのIssueをお願いします🙏

「項目の削除」の削除（カラムもデータも削除）でお願いします🙏

**Comment by KishiKyousuke** [comment]
@komagata @machida 
主な学習場所の入力フォームは`_study_place.html.slim`に記載されていますが、コメントアウトしてファイルは残しておくべきでしょうか❓それともファイルごと削除するべきでしょうか❓

**Comment by komagata** [comment]
@KishiKyousuke 基本的にgitに履歴があるので不要なコードは全部削除で大丈夫です〜。コメントアウトしてると仕事で注意されてるってのがあるあるとしてあります。

**Comment by KishiKyousuke** [comment]
@komagata 
承知いたしました❗
削除で対応いたします👍
