### ISSUE TITLE
メンターとして登録できるようにしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1977]
今はアドバイザー登録した後でDBを変えてメンターにしている。

`/users/new?role=mentor`というURLで登録するとメンターになるようにしたい。

**Comment by JunichiIto** [comment]
> `/users/new?role=mentor`というURLで登録するとメンターになるようにしたい。

これ、誰でもできちゃうと問題ありな気がしますが、権限制御はかかりますかね？

**Comment by komagata** [comment]
特に何も制御していないです。現状でもadviserは登録できちゃうんですよね。

**Comment by JunichiIto** [comment]
そうなんですね。まあそんなことする人はいないと思いますが、この議論もソースコードも全体公開になっているので、悪意ある人に目を付けられたら一発アウトだよな〜というのがちょっと気になりました。

**Comment by komagata** [comment]
後ほど対策しようと思います。

**Comment by komagata** [comment]
@JunichiIto こちら現状のadviser登録に認証（TOKEN）が必要なように変更しました。

**Comment by JunichiIto** [comment]
@komagata tokenは駒形さんや町田さんしか知らない値なんですよね？それなら良いと思います！

**Comment by komagata** [comment]
@JunichiIto はい。
