### ISSUE TITLE
会社を指定してアドバイザー登録できるようにしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1978]
`/users/new/role=adviser&company_id=123`みたいなURLで登録するとID: 123のcompanyに所属した状態で登録される。

アドバイザーは大抵どこかの会社に所属しているため、現在は登録してもらった後に管理者が手動で会社を割り当てているため。（DAIMYOとか）

研修生（role=trainee）も同じく会社を指定できるようにしたい。（普通のユーザーで指定できてもOK）

`token`が必要になっているのでそれはそのまま行きたい。

**Comment by machida** [comment]
ユーザー登録のURL `https://bootcamp.fjord.jp/users/new` にパラメータを追加した、

- `https://bootcamp.fjord.jp/users/new/role=adviser&company_id=123` というURLでアクセスした場合
    - ユーザーロールは アドバイザー、所属企業は id: 123 の企業になるようにしたい
- `https://bootcamp.fjord.jp/users/new/role=trainee&company_id=123` というURLでアクセスした場合
    - ユーザーロールは研修生、所属企業は id: 123 の企業になるようにしたい

---

@komagata 

質問です。ユーザーロールが、アドバイザー、研修生の場合は、カード番号の入力は必要なく、課金はされない、となってましたっけ？

@ima1zumi 

上記の質問の結果、ユーザーロールとは別に、無料フラグがオンになっている必要がある場合は、それの対応もお願いします。

**Comment by komagata** [comment]
@machida 厳密に言うとそうはなっていません。

アドバイザー、研修生は専用の登録フローになっていて、クレジットカード入力が無く、freeフラグを持った状態で登録されるので課金されないという仕組みです。

**Comment by ima1zumi** [comment]
@komagata 
`company_id` はすでにDBに存在する値のみ受け付ける、といった入力値チェックは掛けた方がいいでしょうか？

**Comment by komagata** [comment]
@ima1zumi 入力値チェックは不要です〜

**Comment by ima1zumi** [comment]
@komagata ありがとうございます！承知しました〜
