### ISSUE TITLE
ユーザーハッシュタグ機能

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1979]
## 目的

- ユーザーが自分はこんな人です、と表現する敷居を低くするため。
- 自分と共通の趣味や経歴、立場のユーザーを探しやすくするため。
- ユーザーがどんな人なのかを知りやすくするため。

**Comment by machida** [comment]
## ユーザー編集画面にハッシュタグのフォームを追加

![image](https://user-images.githubusercontent.com/168265/95351046-c03d7a00-08fb-11eb-8f28-69b1d1c580ee.png)

- たくさん入れられるように、textareaでできると嬉しい（ライブラリが対応してなかったら後回し）
- すでに登録されているハッシュタグ（別のユーザーのも含む）を見て補完して欲しい

**Comment by machida** [comment]
## ユーザー一覧

- 登録したハッシュタグが全て表示される（今後、ユーザーの多いハッシュタグ10個だけを表示とかに変更があるかもしれないがそれは別Issueで対応）
- ハッシュタグをクリックすると、そのハッシュタグを持っているユーザーの一覧へ遷移する


![image](https://user-images.githubusercontent.com/168265/95351511-43f76680-08fc-11eb-84ca-5b16d0068071.png)

**Comment by machida** [comment]
## ユーザー個別

- この部分にこのユーザーが登録した全てのハッシュタグを表示（場所の変更の可能性あり）（ユーザー一覧と同じ表示方法）
- ハッシュタグをクリックすると、そのハッシュタグを持っているユーザーの一覧へ遷移する（ユーザー一覧と同じ）
- いずれ、XX期生などもハッシュタグの一つのような見せ方にするかもしれないが、それは別Issueで。

<img width="608" alt="貼り付けた画像_2020_10_08_0_23" src="https://user-images.githubusercontent.com/168265/95351905-a5b7d080-08fc-11eb-8a3c-e30fada53c6a.png">

**Comment by komagata** [comment]
@machida すでに他でタグ機能が使われているのでタグという表記でもいいかも？

**Comment by machida** [comment]
そうですね、タグにしましょう！

@takopom タグでお願いしますー

**Comment by takopom** [comment]
@machida @komagata タグですね。承知しました！🙆‍♀️

**Comment by takopom** [comment]
@machida 
同じタグを持つユーザーの一覧ページについて、ご確認です。

一覧に表示するユーザーの条件を「リタイアしていない かつ 卒業していない」としてみましたが、いかがでしょうか。
メンターやアドバイザーも含まれます。
<img width="500" alt="スクリーンショット 2020-11-26 5 54 30" src="https://user-images.githubusercontent.com/2003287/100280759-06ce5d00-2fac-11eb-8895-8b56bdd3a069.png">

ちなみに、ユーザー一覧のレイアウト構造と全く同じく、「現役生」「フォロー中」…などのフィルターも表示するのが良いでしょうか？
ご確認いただけると幸いです🙇‍♀️

**Comment by machida** [comment]
@takopom 
ユーザーのロールごとのフィルターは今回のIssueでは範囲外にしたいと思います。リリース後に必要になりましたら、別Issueで対応したいと思いますー

**Comment by takopom** [comment]
@machida 承知いたしました！そのようにいたします。ご確認ありがとうございます！🙏
