### ISSUE TITLE
カテゴリーに属するプラクティスを全て完了したらメダルかを付与しプロフィール画面に表示する

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#1987]
**何故この機能が必要なのか**
## 背景
ユーザーインタビューで、フィヨルドブートキャンプは卒業までの道のりがながくゴールが遠いマラソンをやっている気分になってしまうという意見をもらっています。
またフィヨルドのプラテクィスで、同じプラクティスにいる人が進んでいるのをみたりして人と比べてしまうとモチベーションが下がってしまうという意見ももらっています。
確実にこなしたプラクティス分実力が付いているはずなのに、サービス上では成長実感が感じられにくいことが問題と考えています。

自己肯定感をアップさせる手法として「スモールステップの原理」というものがあり、大きなステップを小さなステップに分解、1つの小さなステップをクリアするごとによくできたという成功体験を得ることで、人間の脳の報酬系を刺激しモチベーションを継続させる、というものです。まさにプラクティスのタスクばらしと一緒です
プラクティス全体でもこの原理を導入していけばモチベーション継続につながるのではと思い提案させていただきます

**機能の説明**
プラクティスのカテゴリーを全て完了した後に、メダル的なものを付与してプロフィールなど見えやすいところに表示する。
もしくはprogateのようなレベル機能をつけたい
(ここは @komagata さん、@machida  さんと相談したい)
現状ではプラクティスの完了率は表示されているがもっと成長実感するようなものがほしいです。

**Comment by udzura** [comment]
こう言うのめちゃいいですね 👍 

（モチベーションの維持のための仕掛け、DuolingoのUIとか各種取組みが色々参考になりそうだなーとか）
