### ISSUE TITLE
ユーザー登録があったらSlackに通知が欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#1995]
非公開のSlackチャネルを作り、そこにユーザー登録があったら通知がいくようにしたい。
不正なサインアップがあった際に気づけるようにするのが目的です。

#fjord チャンネルに通知する。

**Comment by masuyama13** [comment]
@machida @komagata
現在、ユーザー登録時には learning_notification チャンネルに通知されていますが、チャンネルの追加（#learning_notification に加えて #fjord にも通知する）ということでよろしいでしょうか？

また、文章はこのままでよろしいでしょうか？変更が必要であれば、内容をお知らせください🙇

<img width="591" alt="Screen Shot 2020-11-04 at 13 00 22" src="https://user-images.githubusercontent.com/58389623/98068025-436fd280-1e9e-11eb-8de3-d16b0e1b289a.png">

**Comment by komagata** [comment]
@masuyama13 #learning_notification から #fjord に変更でお願いします〜。
文言はそのままで大丈夫です。

**Comment by masuyama13** [comment]
@komagata 
承知しました！
チャンネルを変更します。
