### ISSUE TITLE
退会した時Discordからも退出する方法を調査したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1996]
現在、手動でdiscordの退会者の退出を行なっているのですが、discordのapiを使って自動化させたいです。可能かどうかの調査からお願いしたいです🙏

**Comment by maeda-m** [comment]
📝 [ふりかえり・計画ミーティング2023年01月25日](https://github.com/fjordllc/bootcamp/wiki/%E3%81%B5%E3%82%8A%E3%81%8B%E3%81%88%E3%82%8A%E3%83%BB%E8%A8%88%E7%94%BB%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B02023%E5%B9%B401%E6%9C%8825%E6%97%A5) よりメモ

表題のとおり調査までの議題となるため完了とする。プルリクエスト（ #6099 ）はも併せてクローズする（ブランチは残す）。

また実装については #6103 や #6102 にも関わるため実現方法について慎重に検討する必要がある。
なお #6099 は Gem を使用しておらず（search が実装されていなかったため） Web API とのやりとりは `app/models/discord_member.rb` を経由して `lib/discord/resource.rb` が行っている。
加えて #6099 は幅広な調査をしていないため https://discord.js.org/ などの実現方法が Web API との互換性有無や運用時のコスト想定の調査をしていません。
