### ISSUE TITLE
docを削除したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2003]
まずは、作者と管理者が消せるようにしたい。

**Comment by machida** [comment]
削除ボタンは一覧では非表示。個別ページにだけ表示でお願いします。

**Comment by KishiKyousuke** [comment]
@komagata @machida 
私の勘違いかもしれないのですが、docを削除する機能はすでに実装されているのではないでしょうか❓💦
以下のように作者・管理者はDocsの個別ページから削除が可能となっています。
別の機能のことを指しているのであればお教え頂けると幸いです🙇🏻‍♂️

**作成者の個別ページ画面**
![image](https://user-images.githubusercontent.com/59789739/95812563-a9aa7f00-0d50-11eb-9484-f943b41805c4.png)
**管理者の個別ページ画面**
![image](https://user-images.githubusercontent.com/59789739/95812624-cb0b6b00-0d50-11eb-9de5-c38e76bc7b7c.png)

**Comment by machida** [comment]
@KishiKyousuke あれ？すいません、なんか消せないdocがあったのですが、何かバグを引いたかもです。

試しに、docを作ってwipで保存、それから公開をすると消せないdocが作成されていました。

**Comment by machida** [comment]
@KishiKyousuke 
なので、このバグと関連してそうです。
このIssueもアサインさせていただきました。
https://github.com/fjordllc/bootcamp/issues/2002
こっちのバグを探っていただき、問題はこっちのバグにありましたら、このIssueはcloseでお願いします🙏

**Comment by machida** [comment]
@KishiKyousuke こちらもたまたま出会ってしまったバグのせいか、問題はなかったのでcloseにさせていただきます🙇‍♂️
