### ISSUE TITLE
QAのコメントで、大名エンジニアカレッジ研修生のアイコンの外周につく色が異なっている

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#2006]
## 概要

QAのコメントで、大名エンジニアカレッジ研修生のアイコンの外周につく色が異なっている。

## 再現手順

1. https://bootcamp.fjord.jp/questions/701 にアクセス。
2. neutral-kaori さんのアイコンの色が紫（企業からの研修生）になっている
3. [日報](https://bootcamp.fjord.jp/reports/19335)ではアイコンの色が黄緑になっている

## 期待される振る舞い

QAのコメントでも、アイコンの外周につく色が黄緑になる。

### QAのコメント
![image](https://user-images.githubusercontent.com/52617472/95806745-5da50d80-0d43-11eb-9cc4-6d36faa5ce20.png)

### 日報のコメント
![image](https://user-images.githubusercontent.com/52617472/95806973-02274f80-0d44-11eb-83ce-9f34f5f61163.png)

## 環境

 - OS: macOS Catalina 10.15.7
 - ブラウザ: Chrome
 - バージョン: 86.0.4240.75

**Comment by machida** [comment]
@ima1zumi こちら、vueで表示しているコメントのユーザーのアイコンに is-daimyo という class が付いてないのが原因です。そっちにも付くように対応をお願いします🙏
