### ISSUE TITLE
docsのタグ編集ができない

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#2012]
## 概要

docsでタグを入力して保存してもリロードすると消えてしまう

## 再現手順

1. https://bootcamp.fjord.jp/pages/293にアクセス。
2. 『タグ編集』をクリックしてタグを入力し『保存する』ボタンを押す
3. リロードする

## 期待される振る舞い

タグを保存するを押すと、リロードしてもタグが保存されている状態にしてほしい

## スクリーンショット

![ほんの読み方 mov](https://user-images.githubusercontent.com/5990045/96201248-1020de80-0f97-11eb-80d5-0e85977baa84.gif)

## 環境

 - OS: MacOS
 - ブラウザ: chrome
 - バージョン:  10.14.6

## 関連Issue

Ref: #関連Issue番号

**Comment by shibaaaa** [comment]
こちら、タグを入力後にエンターを押すとUIが変わるようになっているのですが、エンターを押さずに保存し、リロードすると保存されないようになっていました。
以下のgifではタグ入力後にエンターを押し、リロードしても保存されていました。

![](http://g.recordit.co/rEy0rrH9fY.gif)

UIが変わる機能はnpmで実装していますが、エンターを押す必要があることが分かりにくいUIになっているのが原因なのではないかと思いました😓

**Comment by rlho** [comment]
なるほど〜！説明ありがとうございます！
一度エンターを押してタグにする仕様なのですね…！
理解しました！バグではないのでこのissueはクローズしておきます！

**Comment by shibaaaa** [comment]
@rlho 
恐れ入ります🙏
