### ISSUE TITLE
プロフィール画像をリサイズする処理でエラーが発生し、システムテストが落ちることがある

### ISSUE THREAD

**Issue by hogucc** [fjordllc/bootcamp#2014]
プロフィール画像のresizeに関連するシステムテストが、稀に落ちることがあります。
https://app.circleci.com/pipelines/github/fjordllc/bootcamp/1033/workflows/dd5ed973-d25c-485f-b996-c15d2f504bb7/jobs/4782
https://app.circleci.com/pipelines/github/fjordllc/bootcamp/1040/workflows/e3bb8414-c5ad-490b-b8e6-c99ad9c83eea/jobs/4775
https://app.circleci.com/pipelines/github/fjordllc/bootcamp/1033/workflows/098f1a83-bb76-4991-b233-44eaf6d2b094/jobs/4768

落ちているテストはバラバラですが、共通して以下のエラーが出力されています。
ユーザーのプロフィール画像のリサイズ時にActiveStorage::FileNotFoundErrorが発生しています。

```
ActiveStorage::FileNotFoundError: ActiveStorage::FileNotFoundError
    app/models/user.rb:399:in `resize_avatar!'
    lib/bootcamp/setup.rb:12:in `block in attachment'
    lib/bootcamp/setup.rb:7:in `attachment'
    test/application_system_test_case.rb:22:in `block in <class:ApplicationSystemTestCase>'
```

ローカル環境では複数回テストを走らせても一度しか再現しませんでした。

**Comment by ima1zumi** [comment]
#2307 の修正でこのエラーでは落ちなくなってそうなのでCloseします。
