### ISSUE TITLE
ユーザーの日報一覧からも日報作成ができるようにしたい

### ISSUE THREAD

**Issue by KishiKyousuke** [fjordllc/bootcamp#2034]
## 何故この機能が必要なのか

日報のタイトルに「〇〇日目」という記載をしているため、ユーザーの日報一覧で前回書いた日報の日数を確認してから日報を作成したい。

## 機能の説明
ユーザーの日報一覧画面に日報作成のボタンを追加する。

![image](https://user-images.githubusercontent.com/59789739/96851777-5a242b80-1493-11eb-9ca7-6070157bc263.png)

**Comment by ima1zumi** [comment]
関連しそうなissueを貼っておきます〜
https://github.com/fjordllc/bootcamp/issues/1921

**Comment by universato** [comment]
ポートフォリオは右上と真ん中に作品追加のボタンがあるし、個人の日報一覧にも日報作成への導線があって自然なはずで、ないことにずっと違和感がありますね。自分は「〇〇日目」とか書いてないですが、個人の日報一覧にも追加ボタンがあると嬉しいです。

**Comment by universato** [comment]
これ、PR #2370で追加されたため、閉じます!
