### ISSUE TITLE
test/system/sign_up_test.rb で使うメールアドレスを決め打ちメールアドレスに変えると、 "sign up" テストが1回目しか通らない

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#2035]
## 概要

test/system/sign_up_test.rb で使うメールアドレスを決め打ちメールアドレスに変えると、 "sign up" テストが1回目しか通らない。

## 再現手順

1. 以下のテストを実行すると、1回目はテストをパスする
1. 2回目以降は「同じメールアドレスの顧客が既に登録済みです。」と表示され、テストをパスできない

```ruby
# frozen_string_literal: true

require "application_system_test_case"

class SignUpTest < ApplicationSystemTestCase
  test "sign up" do
    WebMock.allow_net_connect!

    visit "/users/new"
    within "form[name=user]" do
      fill_in "user[login_name]", with: "foo"
      fill_in "user[email]", with: "abc@example.com"
      fill_in "user[name]", with: "テスト 太郎"
      fill_in "user[name_kana]", with: "テスト タロウ"
      fill_in "user[password]", with: "testtest"
      fill_in "user[password_confirmation]", with: "testtest"
      select "学生", from: "user[job]"
      select "Mac", from: "user[os]"
      select "未経験", from: "user[experience]"
    end

    fill_stripe_element("4242 4242 4242 4242", "12 / 21", "111", "11122")

    click_button "利用規約に同意して参加する"
    sleep 1
    assert_text "サインアップメールをお送りしました。メールからサインアップを完了させてください。"

    WebMock.disable_net_connect!(
      allow_localhost: true,
      allow: "chromedriver.storage.googleapis.com"
    )
  end
end

```

## 期待される振る舞い

2回目以降実行してもテストが通る。

## スクリーンショット

![image](https://user-images.githubusercontent.com/52617472/96858503-4c72a400-149b-11eb-943b-ac7a56f55ce6.png)

## 原因の推測
WebMock.allow_net_connect!で本物のHTTPリクエストをStripeのテスト環境?に飛ばしているため、Stripeのテスト環境でemailが保存されてしまっているのではないか。

今まではemailをsecurerandomで生成していたためemailの重複が発生していなかったが、決め打ちメールアドレスに変更したため発生するようになった。

今の仕組みのまま行くなら、テストが終わるたびにStripeのテスト環境をクリアすれば問題解決するのではないか。

## 確認していただきたいこと

- Stripeのテスト環境にテスト用のemailが保存されているかどうか

## 関連Issue

Ref: #2025

**Comment by komagata** [comment]
@ima1zumi あ〜なるほど〜、確かにStripeのテスト環境に登録されてますね。

Stripeのテスト環境は削除するようなAPIがないので（サポートに確認済み）申し訳ないですが、重複しないようなメールアドレスを利用するように戻していただければと思います。

**Comment by ima1zumi** [comment]
Stripeのテスト環境にメールアドレスが保存されるテストは、決め打ちメールアドレスを使わずSecureRandomで生成することにしましたのでこちらcloseします。
ref: https://github.com/fjordllc/bootcamp/pull/2025
