### ISSUE TITLE
Markdownで表示している部分で、リンクのアンカーテキストに 「@」が含まれると userへのリンクになってしまう

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2037]
Markdownエディタで、

```md
@machida
```

と書くと、`<a href="/users/machida">@machida</a>` こんな感じのリンクになる。

ところが、

```md
[@machida](http://fjord.jp)
```

と書くと、

と書くと、`<a href="http://fjord.jp"><a href="/users/machida">@machida</a></a>` こんな感じのリンクになる。

リンクの中の `@` はリンクにならないようにしたい。

こうなるようにしたい。

 `<a href="http://fjord.jp">@machida</a>`

**Comment by komagata** [comment]
:memo: 多分この辺りが関係してる。

https://github.com/fjordllc/bootcamp/blob/main/app/javascript/markdown-it-mention.js
