### ISSUE TITLE
プラクティスの完了ボタンを押した時に『お疲れ様でした！』的なポップアップを表示しTwitterへのシェアボタンをつける

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#2045]
**何故この機能が必要なのか**
Twitterでのブートキャンプユーザー同士のつながりを作り、またTwitterを活用する機会を増やすためにプラクティスの完了ボタンを押した時にTwitterにシェアする導線を増やしたいです。
現在フィヨルドブートキャンプではSNS登録のプラクティスがあり登録は全員行うがその後Twitterを活用している人と活用できていない人がいます。
プラクティスに記載がある通り、Twitterで自分のことを発信したり生徒同士や他のエンジニアと繋がることは、勉強のモチベーションを維持したりエンジニアとして働く際に役に立って行くと思うのでどんどん活用して欲しいと思っています。
https://bootcamp.fjord.jp/practices/137

そこでTwitterを使う機会を増やし、また `#fjordbootcamp`のハッシュタグ投稿を増やすことにより生徒同士のゆるいつながりを促進させたいです。

**機能の説明**
プラクティスの完了ボタンを押した時にポップアップを表示させたい。
中身は、
『[プラクティス名]を修了しました！お疲れ様でした 🎉 ✨ (文言は変えても大丈夫です)』という文言を表示し、『Twitterにシェアする』リンクかボタンを設置。
リンクを押すと `#fjordbootcamp`がツイート文に入ったツイート投稿画面に移動させる

<img width="686" alt="スクリーンショット 2020-10-25 15 16 08" src="https://user-images.githubusercontent.com/5990045/97100286-4f58d900-16d5-11eb-9c60-21990695e427.png">

**Comment by machida** [comment]
@konaga-k @komagata 

文字のTweetだけでなく、画像もTweetされたいと思います。
https://qiita.com/codeq_official/items/848c705252075c631e29
こんな感じで画像が生成されるようにしたいです。

画像の出し方として、

- Tweetに画像の貼り付ける
- 完了しましたページを新たに作成し、そのOGPとして画像を設定する

この二種類の方法があるかと思います。
どちらにするか、MTGで話し合いたいと思います。

**Comment by machida** [comment]
@konaga-k

ちょっと駒形さんと話し合って仕様を考えました。

- それぞれのプラクティスごとに、プラクティス完了ページを作成する
- プラクティス完了ページはOGP画像（Twitterカード）を持つ（自動生成したい）
- プラクティス完了ページはログインできなくてもアクセスできる
- Tweetにプラクティス完了ページのURLが挿入される
- TweetにはOGP（Twitterカード）が表示される

このようにしたいと思います。

**Comment by konaga-k** [comment]
Tweetするための導線設計が難しいですね…。
現状プラクティスが完了する条件は2つあると思います。
- 受講生がプラクティスの完了ボタンを押す
- メンターが提出物を確認する

ただ、プラクティス完了のほとんどは後者で行われると思うんですよね（少なくとも自分はほとんど完了ボタンを押してない）。
なので @rlho さんの提案にある `プラクティスの完了ボタンを押した時にポップアップを表示させたい` だけだと気づかれない可能性があります。

@machida 
導線のアイディアって駒形さんと何か認識合わせできてるでしょうか？（もしくはこのissueではまだ実装不要でしょうか？）

自分で考えたのは以下の2案です。

A. メンターが提出物完了したときのサイト内通知をクリックしたとき、提出物のページではなく、プラクティス完了ページに飛ぶようにする
![2021-09-12_17-51](https://user-images.githubusercontent.com/54785890/132981395-9cdd1c9f-714d-4555-ba3d-e2c0d5a6b0c1.png)

B. 提出物確認後の提出物ページに、プラクティス完了ページへのリンク（もしくはTweetリンクを直接）を載せる
![2021-09-12_17-55](https://user-images.githubusercontent.com/54785890/132981495-720a249a-e799-4384-9481-6ce54a98ac11.png)

A案だと、受講生は完了ページの存在に気づきますが、メンターが提出物確認時に投稿したコメントに気づかなくなりそうです。
B案だと、受講生はメンターのコメントに気づきますが、完了ページの存在と、完了ページからTweetできることに気づかないかもしれません。

**Comment by konaga-k** [comment]
五月雨になっちゃいますが、C案として完了ページのタブを増やすというのがありました。
![2021-09-12_18-33](https://user-images.githubusercontent.com/54785890/132982611-591460b0-a814-480b-b3e2-62b5bd69a5b7.png)

Railsのリソース構成（practicesの下にreportsやproductions、新しく追加するcompletionを置く）と、
タブの構成（プラクティス詳細ページに日報や提出物、新しく追加する完了ページのタブがある）が一致するので、
個人的にはこれがやりやすいです。

**Comment by machida** [comment]
今回、完了ページに大きな意味は持っていないので、受講生はそこにアクセスする必要がないです。

なぜ完了ページを作成するかというと、Tweet に Twitterカード で画像を表示させる必要があるからです。

完了ページは Tweet に Twitterカード で画像を表示させるためのもので、そのURLにアクセスすることは重要ではありません。

イメージを共有しますね。

## 自分で完了にする場合

- 完了にしたら以下のようなポップアップが表示される。
- このポップアップは、提出物作成者にしか表示されない。
- このポップアップを消すと、自分で表示させようとするまで表示されることはない（ポップアップを消した後参照）。

![image](https://user-images.githubusercontent.com/168265/133386518-3174aa12-6ce3-4665-9419-195e11ee812b.png)

## メンターが完了にした場合

- メンターが完了にした後、提出者がその提出物作成ページにアクセスすると、以下のようなポップアップ（ポップアップの）が表示されている。
- このポップアップは、提出物作成者にしか表示されない。
- このポップアップを消すと、自分で表示させようとするまで表示されることはない（ポップアップを消した後参照）。

![image](https://user-images.githubusercontent.com/168265/133386518-3174aa12-6ce3-4665-9419-195e11ee812b.png)

## ポップアップを消した後

- ポップアップを消すと、自分で表示させようとするまで表示されることはない。
- 提出物がOKになったら、「完了Tweetする（仮）」ボタンが表示される。ボタンはもっと地味にする予定。
- 「完了Tweetする（仮）」ボタンをクリックすると、ポップアップが表示される。

![貼り付けた画像_2021_09_15_17_09](https://user-images.githubusercontent.com/168265/133395607-bd056b91-129b-4468-bf54-fa9f66ad345d.png)

## Tweetの内容

```
フィヨルドブートキャンプのプラクティス「Terminalの基礎を覚える」が完了しました🎉🎉🎉
https://bootcamp.fjord.jp/xxxxxx

#fjordbootcamp
```

<img width="590" alt="貼り付けた画像_2021_09_15_17_18" src="https://user-images.githubusercontent.com/168265/133400047-e4eaa5ab-110f-4912-916a-397f2df6481b.png">


- https://bootcamp.fjord.jp/xxxxxx これが完了ページのURLになる。
- おめでたい画像はTweetにTweetに画像が添付されるのではなく、完了ページのTwitterカードで表示される（つまり、完了ページはTwitterカードを持つ）。

## 完了ページ

Tweetに完了ページのURLが含まれているので、完了ページにアクセスすることが出来てしまう。
完了ページは以下のような簡単なページになる。

![image](https://user-images.githubusercontent.com/168265/133400954-385cd33e-f640-4d0a-9818-467fbd41a832.png)

**Comment by machida** [comment]
完了ページはプラクティス毎に異なりますが、
さらに、ユーザー毎に変えるか、全員共通にするかを検討しています。

なぜ、ユーザー毎に別の完了ページをもたせるかというと、ユーザー毎に完了ページを持つと、Twitterカードの画像にユーザーIDを含んだ文章を入れることができるからです。

MTGで話しましょう。

**Comment by konaga-k** [comment]
【メモ】
ユーザーごとの完了ページは無しになりました

**Comment by konaga-k** [comment]
【メモ】
ポップアップの初回表示フラグはDBに持たせる

**Comment by konaga-k** [comment]
【メモ】
- 提出物詳細ページにOGPアップロード機能を設ける
- OGP画像の自動生成は不要

**Comment by konaga-k** [comment]
@machida 
提出物がないプラクティスってあると思うんですが、その場合提出物ページが存在しないので、受講生が初回ポップアップのタイミングを逃すと完了ツイートできなくなると思います
これって問題ないでしょうか？
例: https://bootcamp.fjord.jp/practices/138

**Comment by machida** [comment]
@konaga-k

すいません、昨夜寝てしまいました🙇‍♂️返信遅れました💦
確かに！！

提案の通り、

- 提出物の詳細ページより、プラクティスの詳細ページに完了ツイートボタンを置く
- 提出物の詳細ページとプラクティスの詳細ページの両方に置く

取れる手段はこの二つですね。
今回は、プラクティスに関するページで完了後の初回はポップアップは出るということで、

「提出物の詳細ページとプラクティスの詳細ページの両方に置く」

こちらでお願いします🙏 どちらに出るようにしても、ユーザーは一度見たらもう出なくなるので、両方に出るのは邪魔と感じることはないと思う、というのがこちらを選んだ理由になります。Tweetボタンは地味に置いておくので、一旦両方に表示をお願いします。こちらは、もし邪魔になったらどちらか削除したいと思います。

> （追記）上と同じ理由で、OGPアップロード機能も提出物の詳細ページよりプラクティスの詳細ページに設けたほうがいいと思っています

はい！ログインしていない状態で見れるページ（TweetされるURL）は プラクティスの詳細ページ にお願いします🙏
