### ISSUE TITLE
他人のプラクティスの進捗を見えなくする機能

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#2047]
**何故この機能が必要なのか**

先日のLT会で、「プラクティス一覧ページを見ると落ち込むことがあるため、できるだけ見ないようにしていた」という話をしていた方がいた。見たくない人には見えないようにする機能があると良いと思ったため。

**機能の説明**

- プラクティスの進捗アイコンが見えなくなる。（`practice-started-users` に `display:none` を付けるイメージ）
    - 自分のアイコンも見えなくなる。
- 設定を保存できる。

**Comment by machida** [comment]
@ima1zumi 逆に見たいという人がいなかったら、メンターにだけ見れるようにしようかと思うのですが、どうですかねー？雑談タイムでも聞いてみようかな

**Comment by komagata** [comment]
@machida @ima1zumi  見たくないと言ってる人がいましたが、逆にそれがいい励みになってる方もいるかもしれず難しいですね。

**Comment by ima1zumi** [comment]
@machida 
雑談会で質問いいですね！
個人的には進捗が見えるメリット、デメリットは以下のように考えています😄
見えているメリットも大きいので、完全に見えなくするのはもったいないと思っています。

進捗が見えるメリット😊
- 同じプラクティスに取り組んでいる人がわかりやすい
  - 日報を参考にしやすい
  - 生徒同士でコミュニケーションをとるときに、同じプラクティスにいることが分かっていると話しやすい
- フィヨルド全体で誰がどのプラクティスに取り組んでいるのか分布を掴みやすい
- みんなやってる感がある
- プラクティスが終わったときにアイコンが移動して嬉しい
- 追い抜けると嬉しい

進捗が見えるデメリット😣
- 追い抜かれると辛い
- 他人の進捗が気になってしまう
- 見たくなくても見えてしまう

**Comment by masuyama13** [comment]
個人的にはアイコンが見えるメリットの方が大きいと感じているので、なくさないでほしいです。
基本的に ima1zumi さんと同じ意見です。
自分の普段の使い方を考えてみたら、ユーザー一覧を見ることはほとんどなくて、プラクティス情


一方で、見たくないという気持ちもわかるので、見られなくできる機能があるといいですね。
「着手」を押さないことでアイコンを表示させていない人もいるようです。

**Comment by machida** [comment]
@ima1zumi @komagata @masuyama13

なるほどー、ユーザーの意思で隠せる、というのが一番良さそうですね。
これは受講生ならではの要望でとても助かります。
システム的には一律にしたいとなってしまいがちなのですが、こういうユーザーの気持ちに合わせた機能が、プロダクトでこだわるべき細やかさだと思います。
これ入れましょう。

それとは別にこのアイコン問題はテーマとして気になるので、みんなの話を聞いてみたいですね。

**Comment by becolomochi** [comment]
私も表示非表示の切り替えがユーザー自身で選べるのがいいなと思いました…！

私自身は受講を始めた当初、表示されているのはちょっと気になりましたね。。
なんですが、今はここを見ることで「みんな頑張ってるな〜出来る人はどんどん進んでくれよな！」と思っていて（笑）、
モチベーションの維持につながっているので表示されていてほしいなと思っています。

（表示非表示は当人の考えで切り替えられるというのは、ちょっとズレますけどTwitterのミュート機能っぽいですね）

通りすがりにすみません🙋

**Comment by machida** [comment]
この辺にチェックボックスを用意。

<img width="1176" alt="貼り付けた画像_2020_11_16_10_50" src="https://user-images.githubusercontent.com/168265/99204713-d6433200-27f9-11eb-9841-c97f41ba4d00.png">

チェックを外すと、ユーザーのアイコンが消える。

<img width="740" alt="貼り付けた画像_2020_11_16_10_53" src="https://user-images.githubusercontent.com/168265/99204755-f7a41e00-27f9-11eb-8cc7-0586b1812c80.png">

表示・非表示の状態はDBに保存され、プラクティス一覧を表示した際は選択した表示・非表示の状態が引き継がれる。

---

## 補足

- デフォルトはチェックが入っている状態
- チェックボックスを変更したタイミングでDBに入っている値がページの読み込み無く更新される（Vue.jsで実装）。
- 非表示の際、可能だったらアイコン自体のDOM自体を削除してしまいたい（HTMLで非表示になる）。もし、その実装に大幅なコストがかかる場合は、HTML的には表示されていて、CSSで表示・非表示を切り替えるのでもOK。

**Comment by machida** [comment]
雑談タイムでのメモ

- Vue.js は使わずに、jsを使って、チェックボックスの値が変わったらページ遷移を発生させる。
- チェックボックスの値によって、`categories-items` に、`is-show-users`、`is-hidden-users` の class が付くようにする。
    - CSSで表示・非表示を実装する

categories-itemsはここ

![image](https://user-images.githubusercontent.com/168265/99224208-3bfae280-2829-11eb-9a4a-0cb1b39ea58d.png)
