### ISSUE TITLE
所属企業一覧ページが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2049]
企業詳細ページはすでにあるが、例えば「classiさんのページがみたい」と思った時にたどり着けないため。

右上のメニューに企業一覧のリンクを作る。

**Comment by masuyama13** [comment]
📝 計画MTG

- 企業アイコンも出す
- Menu 内の位置は「書籍一覧」の次

**Comment by masuyama13** [comment]
📝 雑談タイム

 - 企業一覧ページに、各企業の所属人数も出す

**Comment by masuyama13** [comment]
@machida @komagata 
マージされたので動作確認したところ、フィヨルド含め2社の企業ロゴが表示されていませんでした。
defaultとなっているので画像が未登録なのではないかと思いますが、ご確認いただけないでしょうか？
https://bootcamp.fjord.jp/companies

![Screen_Shot_2020-11-30_at_20_28_42](https://user-images.githubusercontent.com/58389623/100605244-025ac900-334b-11eb-94d4-a20fbee3ef47.jpg)

**Comment by komagata** [comment]
@masuyama13 二社とも画像が登録されていなかったので登録しました。

**Comment by masuyama13** [comment]
@komagata 
ありがとうございます！
