### ISSUE TITLE
Docsのタグ編集時に通知を送らないようにする

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#2054]
**何故この機能が必要なのか**

現状では、Docsにタグが追加されるとこのような通知が送られます。

<img src="https://user-images.githubusercontent.com/52617472/97530058-9fe17680-19f4-11eb-9168-dfa3d1cd34a1.png" width=300px>

**気になる点**
この通知からでは「タグが追加された」ということが分かりません。
また、個人的にはタグ追加であればDocsの内容が変わったわけではないため、通知は送られてほしくないと思いました。（タグ編集の通知が送られると嬉しい場合があれば通知されてもいいと思います 😄  ）

通知からタグの編集であることがわかるようにするか、Docsのタグ編集時には通知が送られないようになってほしいです。

**Comment by machida** [comment]
@komagata @ima1zumi 

https://github.com/fjordllc/bootcamp/issues/1953
これと同じ原因ですね。

- docにWIP機能が後から入ったので、publish_at が空のdocがある（WIP機能が追加される前に作られた doc）
- publish_at が空のdocに何かしらの編集をして、保存をすると、その日時が publish_at に入る。
- 空だった publish_at に日時が入ったタイミングで通知が飛んでしまう。

これを解決する手段として、

1. 既存のWIP以外のdocでpublish_at が空のものには何かしらの日時を一括で入れてしまう
1. Issue [Docを投稿した際に、このDocを投稿したことを通知をしない、という選択ができるようにしたい](https://github.com/fjordllc/bootcamp/issues/1878) を実装するか

の二択かなー、と思いました。
僕としては 1 がいいかと思ったのですが（2はこの問題の解決策として行うのではないとして）、駒形さんいかがでしょう？

**Comment by komagata** [comment]
@machida @ima1zumi 確認ありがとうございます。

僕も1がいいと思います。

正確にはdocにWIPを追加する時にそれをrake taskで実装すべきだったのでバグって感じですね。

**Comment by ima1zumi** [comment]
#2111 で対応済のためCloseします。
