### ISSUE TITLE
Q&Aの「解決」スタンプがズレている

### ISSUE THREAD

**Issue by shibaaaa** [fjordllc/bootcamp#2065]
## 概要
Q&Aの質問一覧ページにて「解決」スタンプがズレており、「タグ一覧」のカードの裏に表示されている。
<img width="850" alt="解決済みの質問一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/56685224/98071915-26400180-1ea8-11eb-9631-f0428ef6effa.png">

## 再現手順

1. https://bootcamp.fjord.jp/questions?solved=true にアクセス。

## 環境

 ブラウザ: chrome

**Comment by machida** [comment]
@shibaaaa 修正しましたー Issueありがとうございます！！

**Comment by shibaaaa** [comment]
@machida 
恐れ入ります、ご対応頂きありがとうございます！
