### ISSUE TITLE
ユーザーにメンターメモが欲しい（メンターしか入力ができない、メンターしか見れないメモ欄）。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2069]

**Comment by ima1zumi** [comment]
検討済でしたらすみません。
メンターの方が画面共有した際に、うっかり見えないような仕組みになっているとありがたいです :pray:

**Comment by JunichiIto** [comment]
> メンターの方が画面共有した際に、うっかり見えないような仕組みになっているとありがたい

これ、僕もレビュー動画作るときに少し気を遣うので、ワンクリックで表示非表示が切り替わったりすると嬉しいですね。（今はメンターメモ欄が表示されなくなるまでウインドウ幅を狭めた状態で動画を撮ってます）

**Comment by Chi-rr** [comment]
@komagata @machida 
Issueについて今一度認識合わせをさせてください🤲

## 質問と確認
- Issueの背景を教えてください

- 最終成果物のイメージ
  - ユーザーのプロフィールにメモを追加する
    - メンターのみに表示される
    - メンターのみが編集できる
  - 表示/非表示を切り替えることができる
    - こちらは今回のMVPではない気がするのですが、いかがでしょうか？🤔

- テキストエリア(メモ)の設置位置は、ユーザープロフィールのユーザー情報下
### イメージ画像
赤枠部分
![oMdwB3E](https://user-images.githubusercontent.com/52053239/100558866-8da87000-32f3-11eb-9d65-ce1464f72b28.png)

以上3点ご確認のほどよろしくお願いいたします！

**Comment by machida** [comment]
@JunichiIto @Chi-rr @ima1zumi @komagata 

ちょうどこれについて次回のMTGで話そうと思ってたところでした。

メンターモード機能を考えてました。
このブランチをフィーチャーブランチにして、メンターモード機能とこの機能を同時にリリースを考えています。

メンターモードとは、

![image](https://user-images.githubusercontent.com/168265/100563390-a15ad300-3301-11eb-83db-cdf54cf570c1.png)

メンターでログインした場合、ON・OFFスイッチを表示させて、それがONのとき以外は、メンターしか見れない情報は表示されない機能です。

実装的には、body に、`is-mentor-mode` というclassを付けたときだけ、`visible-only-mentor` というclassが付いたものが表示されることを考えています。メンターモードのON・OFFの状態は何かしらの方法（local storage?）で保存したいですね。

**Comment by machida** [comment]
@Chi-rr 

質問ありがとうございます！
答えさせていただきます。

> Issueの背景を教えてください

例えば、ユーザーによっては企業研修で参加していて、企業側からこのプラクティスとこのプラクティスをやるように指示をされている場合があります。そういった情報をメンター間で共有するのに使います。他には、Railsは初めてだけどXXの実務経験がある、などの情報が共有されていれば、レビューで指摘をする際の説明方法も変わってくるので、そういった情報共有にも使うことになると思います。

> メモの機能「表示/非表示を切り替えることができる」について

はい、その機能はこのIssueに含めなくて大丈夫です。
今回のIssueのPRを作っていただいたら、それをフィーチャーブランチとして、リリースは一旦しないで、今度は表示・非表示の機能を誰かに実装してもらいます。その機能ができたら、それをフィーチャーブランチにマージして、今回の機能と表示・非表示が実装された状態で本番にリリースをしたいと思っています。

> 確認

今のところはそこに表示だけでOKです。
今後、日報や提出物からそのメモをすぐに見れるようにする何かが必要になると思いますが、それは別Issueでの対応でいきたいと思います。

**Comment by JunichiIto** [comment]
@machida 

> 実装的には、body に、is-mentor-mode というclassを付けたときだけ、visible-only-mentor というclassが付いたものが表示される

Chromeデベロッパーツールなどでbodyをいじられたら、受講生に見えてはいけない情報が見えたりしないですかね？（サーバーサイドでも権限に応じてちゃんとHTMLの出し分けをしているなら大丈夫ですが）

**Comment by machida** [comment]
@JunichiIto すいません、言葉足らずでした。従来どおりメンター以外には、メンターしか見れない箇所のDOM自体が書き出されされることはなく、メンターが画面共有やキャプチャを撮る際に非表示にするための機能として、メンターモードの実装を考えています。

**Comment by JunichiIto** [comment]
@machida なるほど、了解です。それなら大丈夫そうですね 😃

**Comment by Chi-rr** [comment]
## 雑談タイムでの話合いメモ
- カラム名は`memo`とする
  - 提出物ページのメンターメモと統一
- Issueの背景には以下も含まれる
  - ユーザーの現状のような一時的な情報の共有をしたい
  - 障がい等個人情報の共有をしたい
