### ISSUE TITLE
メンション、絵文字の補完が遅い

### ISSUE THREAD

**Issue by u1tnk** [fjordllc/bootcamp#2072]
## 概要

メンション、絵文字の入力補完が遅くて補完を諦める事がよくある。特にメンションが遅い。

## 再現手順
はっきりしない。`@` 入力した瞬間に補完が始まる事もあるが入力が終わっても出てこない事もある。
負荷状況によるのかとは思うが、他に条件がある可能性はある。

## 期待される振る舞い
多少遅れても良いが数秒待てば出るぐらいにはなって欲しい。

## スクリーンショット

今やってみると再現しないので無し。

## 環境

 - OS: windows
 - ブラウザ: chrome
 - バージョン: : 86.0.4240.111
 
## 関連Issue

無し

**Comment by JunichiIto** [comment]
> メンション、絵文字の入力補完が遅くて補完を諦める事がよくある。特にメンションが遅い。

たしかに、最近反応悪いですね。
僕は絵文字でも反応が悪く感じることが多いです。

そして同じく再現手順がはっきりしません。。。
