### ISSUE TITLE
提出物に担当メンターを自分で設定できるようにする

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2073]
**何故この機能が必要なのか**

メンターが増えてきたので、タイミングによっては提出物のチェックがバッティングする可能性がある。
バッティングすると同じ提出物を複数のメンターがレビューすることになるので、メンターのリソースがもったいない。

**機能の説明**

各提出物のページに「私が見ます」ボタンを作る。
このボタンの仕様は以下のとおり。

- メンターにしか表示されない
- ボタンをクリックするとログインユーザー（メンター）がその提出物の担当者になる
- すでに担当者が設定されていたら、あとから担当者になることはできない（必ず先勝ちで担当者を設定する）
- 担当者を変えたいときは、「担当から外れる」ボタンをクリックして担当者から外れることができる

**現状の運用**

- 何も言わずに提出物をレビューする、またはSlackで「この提出物を見ます」と宣言してからレビューする

**このボタンがリリースされたあとの運用**

- 「私が見ます」ボタンをクリックしてからレビューを開始する（すでに誰かがボタンを押していたら、その旨通知される）
- 提出物一覧で「自分が担当している提出物」を一覧表示できるようになる
- 提出物一覧に「その提出物の担当者」が表示される

**Comment by hogucc** [comment]
@machida 
こちらのissuenの仕様について質問です。

「私が見ます」ボタンを押した後の遷移先として以下の二案を考えています。
1. クリックした提出物の詳細ページ（/products/{product_id}）に遷移する
1. ページ遷移は発生させない。非同期で「担当から外れる」ボタンに表示を切り替える

メリット・デメリットは以下のとおりです。
- 1は2より工数はかからないが、「私が見ます」ボタンを押すと提出物詳細ページの「見たよ」にアイコンが表示されるので、間違って押した場合やすぐに確認しない場合も見た履歴が残る
- 2は上記のようなことは起きないが、vue.jsでの実装になるので工数がかかる

履歴が残ることを気にしないのであれば1が良いと思ったのですが、どちらの案が良いか（またはもっと良い案があれば）ご意見いただきたいです。

**Comment by machida** [comment]
2 を想定していました（GitHubのレビュワーのアサインのような動作を想像していました）
こちら、vue.jsでの実装によりポイントが大幅に変わる場合は、1を検討したいと思います。
cc @komagata

**Comment by hogucc** [comment]
@machida 
ご回答ありがとうございます！
2を想定とのこと、承知しました。おそらくポイントが3から5に変わるほどではないと思っているのですが、komagataさんの意見を伺ってから1か2のどちらにするか決めたいです。

**Comment by komagata** [comment]
2がいいかもです

**Comment by hogucc** [comment]
@komagata 
承知しました！2で実装します。
