### ISSUE TITLE
ユーザー一覧ページに就活中のユーザーのタブが出ているので、メンター・アドバイザーで見たとき以外はタブを隠す

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2080]

**Comment by MashioSano** [comment]
@machida 
https://bootcamp.fjord.jp/users?target=job_seeking
メンター・アドバイザー以外のユーザーが、上記のリンクへ直接アクセスした場合、就活中のユーザーが表示されてしまうのですが、このissueで修正するべきでしょうか?

**Comment by machida** [comment]
@MashioSano
リンクを表示しないだけで大丈夫ですー
アクセスできなくするのは、別Issueにしますー

**Comment by MashioSano** [comment]
本番環境でPRの反映を確認できましたのでクローズします。
