### ISSUE TITLE
プラクティスの一覧をD＆Dで並び替えたい（Vue.js)

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2083]

**Comment by masuyama13** [comment]
@komagata 
こちらのIssue、 #2211 のバグを直してから取り掛かった方がよいと考えますがそのようにしてもよろしいでしょうか？

**Comment by komagata** [comment]
@masuyama13 こちらを直接やって大丈夫です。管理者にしか関係ない部分なので。

**Comment by masuyama13** [comment]
@komagata 
承知しました！

**Comment by masuyama13** [comment]
@komagata 
プラクティスの並び替えについて、先日雑談タイムで @machida さんに相談させていただきました。
プラクティス一覧をVue.js化すると影響範囲が広すぎるため、プラクティス並び替え用のページを新たに作成する方向で進めたいのですが、問題ないでしょうか？

![S_2021-01-15_at_22_07_43](https://user-images.githubusercontent.com/58389623/104732111-11bd9680-5780-11eb-9640-49a014367b68.jpg)

**Comment by komagata** [comment]
@masuyama13 はい、そちらでお願いします。
