### ISSUE TITLE
お知らせの一覧、個別に表示している日時をpublished_atを出し公開日: XX年XX月XX日と表示、並び順もpublished_atの古い順にしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2084]

**Comment by Chi-rr** [comment]
[誰でもお知らせを作成できるようにする #2016](https://github.com/fjordllc/bootcamp/pull/2016)のPRがマージされてから着手。
(`published_at`カラムが追加される為)

**Comment by Chi-rr** [comment]
@machida 
【前提】
今回のIssueでは「公開日」としてpublished_at値を表示することになっています。
>お知らせの一覧、個別に表示している日時をpublished_atを出し公開日: XX年年XX月XX日と表示

【質問】
PR #2121 にて、Docの日時表記が「公開日」ではなく「公開」になっているのですが、
お知らせも「公開」に合わせるべきできでしょうか？

ご確認お願いいたします！

**Comment by Chi-rr** [comment]
## 開発ミーティングでの決定事項
>お知らせも「公開」に合わせるべきできでしょうか？

- 日時表記「公開」にします。

- 暫定的に`published_at`順で並べます。
