### ISSUE TITLE
published_at が空の doc には、updated_at の値を入れる（rakeタスクで対応）

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2087]

**Comment by Chi-rr** [comment]
@machida 
【質問：空の値には、created_atではなくupdated_atを入れるのはいかがでしょうか？】
作成しているdocをWIPした後に、内容保存した場合、created_atの値はWIPした時点の日時になります。
現在のpublished_atの仕様では、同様にWIP後に内容保存した場合、
保存した時点の日時(=updated_at)と一致する日時が入ります。
そのためpublished_atの空の値には、updated_atの値を入れるのもいいかと思ったのですがいかがでしょうか？

**Comment by machida** [comment]
@Chi-rr 確かに！updated_at でお願いします🙏
