### ISSUE TITLE
【要検討】WIPの日報からメンション通知が届く

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2092]
WIP状態で日報を保存してもメンション通知が届くようです。
生徒さんによっては前日の日報をコピーしていったんWIPで保存することがあるようで、そこにメンションが含まれていると「あれ、その話は昨日読んだんだけど？？」と少し混乱してしまいます。

ただ、人によってはあえてWIPのままメンションを飛ばしたい、というユースケースがあるかもしれません。
なので、現状の動きを変えるか、そのままにするかは要検討かも。

**Comment by universato** [comment]
WIPのままメンションを飛ばしたいと思ったことはなく、WIPのままでもメンションが飛ぶ可能性によって「メンションしないように@は外しておこう」というインセンティブしか起きてないです。そのため、自分の経験からいえば、メンションが飛ぶタイミングは、メンションあって提出状態にしたときか、提出状態でメンションを書いて更新したか、どちらか1回にすべきだと思っています。
話を広げると、WIPは未完了で人に見せる状態になっていないものという認識なため、WIP状態で日報が見れること自体が不要と考えています(WIP自体を見られることはそこまで困らない)。右サイドバーでWIPの日報は流れなくなりましたが、日報の一覧ページでは見れる状況で、他の方々の日報を見ようと日報の一覧ページを見たときにWIPが数多く並ぶ状況は、未完成で見る予定のない日報が並ぶためデメリットの方が大きいと感じています。

**Comment by hituzi-no-sippo** [comment]
bootcampのソースコードを読んでおらず、実装できないことを書いているかもしれません。

## 日報のメンション通知

私は初めて提出したときの1回でいいと思います。提出した後に1回WIPして(修正時に間違ってWIP押しちゃう)再び提出したときや、日報を更新したときは通知は無くてもいいです。もし、提出後に通知飛ばしたいなら、メンションと伝えたい内容をその日報のコメント欄に書けばいいと感じています。

WIPの日報にメンション書いて通知を飛ばそうと考えたことはありません。特定の人に対して質問とかしたい場合、Q&Aの本文にメンション書いて作成すればいいと考えています。(Q&Aの本文にメンションを書くと通知飛ぶかは分かりません。)

## WIPの日報

WIPの日報については @universato さんの意見と一緒で、WIPは他人から閲覧できない&日報一覧から非表示でも良いと感じています。

---

他の人達にも大きく影響する変更なので、[モチベーションに関するアンケート](https://bootcamp.fjord.jp/announcements/273#comment_25262)のときみたいに、Google Forms使って皆さんの意見を聞いてから、どうするか決めるのも1つの手段だと思います。

**Comment by JunichiIto** [comment]
メモ = フォローしている場合もWIPの日報が投稿されると通知が飛ぶ様子。

**Comment by ima1zumi** [comment]
フォローしている日報はWIPでも通知飛んでしまってます。（issue 起こしてなくてすみません…）
`Report` のステータスを wip に更新するタイミングがよろしくないので、 slack通知 と `Notification` のタイミングを合わせるとよさそうです。とメモしておきます

**Comment by machida** [comment]
## wipの場合は通知しないように修正する

### メンション

日報の本文内にあるメンションが含まれている場合、

現在 → WIPで保存したタイミングでメンションの通知が飛んでしまう。
修正→ 日報が公開されたタイミングでメンションの通知が飛ぶようにする。

### フォロー

フォローをされている場合、

現在 → 日報をWIPで保存したタイミングでフォローしている人に通知が飛んでしまう。
修正 → 報が公開されたタイミングでフォローしている人に通知が飛ぶようにする。

**Comment by hituzi-no-sippo** [comment]
@machida @komagata

修正案ですが メンションとフォロー両方とも  "__初めて提出した時に通知する__" で認識あっていますか ❓ 

### 例

1. 日報をWIPで作成
2. 日報を提出する(初提出)
3. 日報をWIPに戻す
4. 日報を提出する

この場合、2のときに通知を送信できるように修正するで大丈夫ですか ❔ 

---

現在remoteにpushされているコード(#2480)のメンション通知は前述した修正案と違います。

pushした後、間違いに気づきました 😭 

現在remoteにpushされているコードのメンション通知は次のようになっています。

## 間違って実装したメンション通知

日報が提出(公開)状態で、メンションが追加されるたびに、追加されたメンション宛に通知する。

### 例

1. 本文に `@hituzi-no-sippo` を書き、提出(公開状態に)する
   hituzi-no-sippo にメンション通知される
2. 本文に `@kimura` を追加し、更新する
   kimuraにメンション通知されるが、hituzi-no-sippoには通知されない

### 問題点

WIPの状態で追加したメンションは通知されない

1. 本文に `@hituzi-no-sippo` を書き、WIPにする
   メンション通知はされない
2. 本文に `@kimura` を追加し、提出する
   kimuraにメンションが通知されるが、hituzi-no-sippoには通知されない
   期待する処理はここでhituzi-no-sippoにもメンション通知する。

これを修正するのは時間がかかります。

## 今後の作業予定

1. テストを追加
   今のテストだと、WIP時に通知がないかの確認だけで、初めて提出した時に通知があるかのテストをしていません。
1. メンション通知の修正
   初めて提出した時だけ通知するように修正する

## 余談

[初日報の更新のたびに通知やメールが飛ぶ不具合の修正(#2444)](https://github.com/fjordllc/bootcamp/pull/2444)の存在忘れて、初めて提出したか確認する機能をこっちでも実装してしまいました。
二度手間であまり良くないと考えていますが、 #2444 のレビュワーになったので、レビューに生かしていきたいです。

**Comment by komagata** [comment]
@hituzi-no-sippo 

> 修正案ですが メンションとフォロー両方とも "初めて提出した時に通知する" で認識あっていますか ❓

はい。

> 手順4のときは通知せず、手順2のときだけ通知するように修正するで大丈夫ですか 

はい、大丈夫です。

**Comment by hituzi-no-sippo** [comment]
@komagata 
回答ありがとうございます 😄 
それで実装していきます～
