### ISSUE TITLE
Docs、Doc 両方に表示する日付を、公開日（published_at）と最終更新日(updated_at) にしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2095]
提出物と同じでお願いします🙏

**Comment by Chi-rr** [comment]
@MashioSano 
[published_at が空の doc には、updated_at の値を入れる（rakeタスクで対応） #2087](https://github.com/fjordllc/bootcamp/issues/2087)のPRがマージされたので、`published_at`の値が全てのDocで取得できるようになったと思います！🙆‍♀️

**Comment by MashioSano** [comment]
@Chi-rr 
ありがとうございます!
ちょうどプルリクを作成するタイミングだったので助かりました😃

**Comment by MashioSano** [comment]
本番環境でPRの反映を確認できましたのでクローズします
