### ISSUE TITLE
リタイアしたユーザー一覧、就職活動中のユーザー一覧、リタイアしたユーザーを含んだ全てのユーザー一覧は管理者以外アクセスできないようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2097]
- /users?target=all
- /users?target=job_seeking
- /users?target=retired

このURLへのアクセスは管理者のみができるようにお願いします。

**Comment by universato** [comment]
本番で生徒側から、「全員」ボタンがクリックできなくなり、"all", "job_seeking", "retired"のURL直接入力で各項目にアクセスできなくなったことを確かめたため、Issueを閉じます。
