### ISSUE TITLE
[要検討]全日報の表示順の変更、WIPの非表示化

### ISSUE THREAD

**Issue by universato** [fjordllc/bootcamp#2118]
# 概要

日報のデフォルトの一覧で、WIPを非表示にして、最初の提出日時順に日報を流すようにする。

右サイドバーと全日報の一覧に関して、並び順を報告日順(reported_on)から提出日時(published_at ?)に変更して欲しいです。
この変更の場合、提出日時のないWIPは非表示にする必要があると思います。あるいは、後ろに持っていくかですが、機能的にはほぼ見れなくなることに変わりないです。

[サイトの右端に表示される日報の表示条件 \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/questions/674)
このQ&Aに並び順や要望がわかりますが、改めて要望を書きます。

## 何故この機能が必要なのか

今の並び順・WIPの表示だと、デメリットの方が大きいため。

### 今の報告日順(同日の場合は作成日時)のデメリット
- 日報の報告日より遅れて提出した場合、流れなくなる。
  流したい場合は、実際の報告日と異なる今日の日付で、提出しなおす必要がある。
- WIP保存してから提出日時までが遅い場合、流れなくなる。流したい場合は、新しく日報を作り提出する必要がある。
- 流れない日報があることで、読み手側がタイムリーに日報を見るチャンスを失う。

### WIPが表示されるデメリット
- 書き手の意図に反して、未完成のものを見られてしまう。
- テンプレートだけ書かれた内容のないWIPも並ぶ。
- 提出日時のないWIPを表示するせいで、日報を提出日時順にするのが難しい(?)

多くの人は提出された日報を見ていて、提出された日報さえ見れれば十分だと思われます。
メンターの方がタイムリーにWIPのタイミングで疑問点などを解消していればメリットが大きいでしょうが、
実際の大半のケースで見られるタイミングは提出後です。

WIPを見たい方や報告日順で見たい方がいれば、別のオプションでWIPを表示できるようにすべきだと思います。

### 今の並び順のメリット

今の日報の並び順・表示方法について総合的に否定的ですが、今の並び順のメリットを一応書きます。

- 意図的に流さないよう人の目に触れないようにすることが出来る。日報の内容がネガティブだったり内容がなければ日報を流したくないことはあると思いますが、別に機能を設けるべきだと思います。
- 反対に、日報の報告日を先日付などで書くことで、ずっと右サイドバーのトップに表示されるので目立たせられる。実際そういう風に目立たせようと使っている人は多分おらず、おそらく誤って1つ下の1週間後を選んで報告してしまうケース、翌日に日報を書き始めて報告日を誤っているケースが見られるように思います。
- WIPのままの日報に、他の方が気がつくことができる。これは、たとえ日報の書き手が意図的にWIPにしている場合でも同じ話で、意図的にWIPにしてるのに見れることは変だと思っています。

# 参考Issue

- [Issue#2092【要検討】WIPの日報からメンション通知が届く](https://github.com/fjordllc/bootcamp/issues/2092)
- [Issue#2017 未チェックの日報の表示順、提出日の表示](https://github.com/fjordllc/bootcamp/issues/2017)
  一緒でも良かったかもしれませんが、内容を読む限りメンター側の未チェックのIssueが主な内容で、既にWIPは非表示で、並び順も未チェックの中でどちらかといえば早い順の要望でしたので、本Issueとは切り離しました。

# 追記
日報の一覧は、技術的に楽なら、提出済みの日報を提出日時・WIPを作成日時(or更新日時)でソートしてもいいかもしれません。
WIPを見ない人にとって一覧がWIPで汚染されることよりも、提出された日報が流れず目に止まらないことをより問題視しているためです。

**Comment by komagata** [comment]
WIPの非表示かについては僕は反対です。

WIPという物自体が、作業中・生焼けの状態でもなるべく早くみんなに共有しよう、してもいいんだよという意味で生まれた文化なので、非表示はWIPの存在意義自体の否定になってしまうからです。

ブートキャンプとしてもプログラマーの業界にあるそういう文化をみんなに理解してもらうために表示したいです。

**Comment by universato** [comment]
日報が完成し提出されたタイミングで1度は、日報が表示順の上に来るように流れないと、完成物が日の目を見ないことを1番問題視していて、WIPの非表示化はそうした方が実装が楽そうだからという理由が先にあったものでした。
非表示化については、自分の中での優先順位はグッと下がるところです。
ただ、日報は多くの方が短期スパンで書いてると思う中で、「作業中のものを流す」ことにより「完成物が人の目に晒されにくくなる」という損益の大小については思うところがあるのも事実です。なお、自分の思う非表示化は全ユーザーの一覧から非表示を選べれば十分で、ユーザーごとの日報一覧からの非表示化までは求めていません。実際、日報に疑問などを書いていて、Slackでも共有するということは定期的に行われている印象なので、完全な非表示化はかえって悪い方向に進むと思っています。

**Comment by masuyama13** [comment]
Issue Close運動をしていて、WIPをDraft（下書き）に変えたい #988 というIssueを見つけたので参考までにはっておきます。

**Comment by universato** [comment]
不定期に誤って日報を未来日にしている方を見ます。
そうなるとその人が気がついて変更したりしないと、ずっと右側の｢最新の日報｣や｢全ユーザーの日報一覧｣に表示されています。

また、意図的にWIPのまま、未来日に設定されている方も見ます。
他者に見せる意図ではなく、自分のスケジュール用に作られているように思います。

以上のようなケースが1番先頭に来ることにより、本来見られたかもしれない日報の閲覧される機会が減少したりすると思うので、よくないと思います。
