### ISSUE TITLE
rubocop-fjordに対応したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2130]

**Comment by ima1zumi** [comment]
:memo:
- rubocop-fjord に段階的に対応していきたい. 
- 手が空いていたらやっていってもらえると嬉しい.
- rubocop todo みたいに細かく分けて順次対応していく機能がある. 
- ダブルクォートがシングルクォートになるのが一番気になる

**Comment by komagata** [comment]
#2191 でやっていただいたので完了。
