### ISSUE TITLE
検索結果のソート順はcreated_atだが、表示されている時刻はupdated_atである

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#2131]
## 概要

表題の通り。

## 再現手順

1. https://bootcamp.fjord.jp/searchables?document_type=all&word=%E8%BF%91%E6%B3%81 にアクセス。
2. 検索結果に表示されている日時と、データのソート順が一致していない。

## 期待される振る舞い

ソート順が一致する。

## スクリーンショット

![image](https://user-images.githubusercontent.com/52617472/99816147-a0ea6b80-2b8e-11eb-9f0f-c694fa8a93fa.png)

**Comment by ima1zumi** [comment]
@komagata @machida 
こちらは現在取り組み中の issue と合わせて修正しようと思います。
`updated_at` でソートされたほうがわかりやすいと思うのですが、 `updated_at` に統一してよいでしょうか？

**Comment by komagata** [comment]
@ima1zumi はい、大丈夫です。
