### ISSUE TITLE
QAにプラクティスを紐付ける

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#214]
プラクティスで絞り込みもできるようにする。

**Comment by machida** [comment]
日報と同じようにする

![image](https://user-images.githubusercontent.com/168265/34344212-8ea41e8c-ea26-11e7-88fb-f8b0d3ac381f.png)

**Comment by sanfrecce-osaka** [comment]
- プラクティスの選択はラジオボタン
- プラクティスの選択は必須ではない
- プラクティスページでのQ&A一覧機能も追加する

**Comment by sanfrecce-osaka** [comment]
@komagata @machida 
ユーザーページに質問一覧機能・アンサー一覧機能は追加しますか？
