### ISSUE TITLE
プロフィールの自己紹介を入力必須とする

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2140]
**何故この機能が必要なのか**

自己紹介文もない、SNSのリンクもない、というような人だと、その人の人となりがわからず、どういう素性の人がどういう目的で参加してきたのか不明で少し不安になるから。

**機能の説明**

https://bootcamp.fjord.jp/current_user/edit の自己紹介欄を入力必須に変更する。

<img width="533" alt="Screen Shot 2020-11-24 at 9 00 20" src="https://user-images.githubusercontent.com/1148320/100028985-8d136380-2e33-11eb-922c-c1c6e8917494.png">

**Comment by rlho** [comment]
フィヨルドブートキャンプはコミュニティの要素が強いので、この提案賛成です！
ですがそれを知らずに入ってくる方もいると思うので、『フィヨルドブートキャンプは学ぶだけでなくコミュニティ』で人となりを教えて欲しいということを入会前に伝えるというのも別でやりたいですね…！
