### ISSUE TITLE
ユーザーを検索したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2147]

**Comment by Chi-rr** [comment]
## ミーティング時メモ
- 検索対象に「ユーザー」項目を作成し、ユーザーの検索を可能にする
<img width="1325" alt="スクリーンショット_2020-12-16_14_40_53" src="https://user-images.githubusercontent.com/52053239/102311076-8e0d6000-3faf-11eb-8649-c5c9e9c9ed44.png">

**Comment by Chi-rr** [comment]
## ミーティングメモ(1/6)
### なぜ必要なのか
ユーザー数が増え、特定のユーザーのプロフィールを見つけるのが困難になったため

### どのような機能か
- メンターor管理者のみ閲覧できるユーザー一覧「全員」タブを選択した際に、表示される新規ユーザー検索フォーム
  - 検索フォームの位置は未定
- `login_name`で検索
  - 該当するユーザープロフィールを表示する
  
<img width="1069" alt="スクリーンショット_2021-01-06_16_15_41" src="https://user-images.githubusercontent.com/52053239/103740546-c6e2a700-503a-11eb-8151-7df0c9e0d4ab.png">

**Comment by Chi-rr** [comment]
@machida 
こちらのissueについて概要をまとめてみたのですが、認識はあっているでしょうか？👀
ご確認お願いいたします🤲

**Comment by machida** [comment]
**何故この機能が必要なのか**

「Aさんのユーザー情報が見たい」と思った場合、以下のような手順が必要になる。

1. ユーザー一覧を開く
2. ブラウザの検索機能でキーワード（ユーザー名等）を入れる
3. 見つからなければ次のページに進む
4. 再度ブラウザの検索機能を使う
5. 見つかるまでページ移動と検索の繰り返し

現役生だと人数が多いため、これだと手間がかかる。

**機能の説明**

ユーザー一覧からサクッと目的のユーザーを検索する機能があると嬉しい。
イメージとしてはGithubのリポジトリ検索が近い。
（キーワードを入力するとユーザー名やユーザーID、自己紹介文などから、合致するユーザーを絞り込む）

https://github.com/fjordllc
<img width="702" alt="Screen Shot 2021-01-06 at 12 04 12" src="https://user-images.githubusercontent.com/1148320/103724320-5fffc680-5017-11eb-9d7d-de1a533fd31d.png">

ユーザーをサクッと見つけられるのであれば上記の方法以外でも良い。

**Comment by Chi-rr** [comment]
@machida @JunichiIto 
ご確認ありがとうございます🤲
>検索はIDだけではなくて、名前、読み方、Slackアカウント、自己紹介文も含めて

承知いたしました！
ユーザー情報から取得できるなるべく多くのキーワードで、検索できるようにしたいと思います！

**Comment by ima1zumi** [comment]
この機能ほしかったので、ちろるさんがアサインされていることを確認せずにほぼ実装してしまいました…
もしちろるさんが未着手であれば、二度手間になってしまうのでこちらで対応できればと思うのですが、いかがでしょうか？

**Comment by Chi-rr** [comment]
@machida @ima1zumi 
>もしちろるさんが未着手であれば、二度手間になってしまうのでこちらで対応できれば

ほぼ未着手だったので、私の方は大丈夫です！

**Comment by machida** [comment]
@ima1zumi おおー、ありがとうございます！助かりますー こちらお願いしたいです🙏
@Chi-rr 別のIssueをアサインさせていただきますー

**Comment by ima1zumi** [comment]
@machida 
仕様についていくつか質問させてください 🙇 

## 質問
> メンターor管理者のみ閲覧できるユーザー一覧「全員」タブを選択した際に、表示される新規ユーザー検索フォーム

なぜメンターか管理者のみ検索可能にしたいという話になったのか教えていただけると助かります 🙏 
issueの内容を読むと検索可能なカラムは全員に公開されているため、通常のユーザが検索できてもいいかな、と思いました。

## 確認
検索可能なカラムについて、四角で囲ったところの情報を検索可能にするつもりです。
twitter など各種サービスのIDを含めるかどうか少し悩みましたが、slack ID は検索したいことがありそうだったので他のIDもあわせて追加しました。

![image](https://user-images.githubusercontent.com/52617472/104126739-a18acb80-53a1-11eb-80de-0f9740c3840f.png)

また、リタイヤした生徒は検索結果から除外しようと思っています。

気になる点があれば教えて下さい 🙏 

よろしくお願いします。

**Comment by machida** [comment]
@ima1zumi 

返信遅れてすいません🙇‍♂️

> メンターor管理者のみ閲覧できるユーザー一覧「全員」タブを選択した際に、表示される新規ユーザー検索フォーム

これ、コミュニケーションミスでした。
メンターor管理者のみでなく、全員を想定していました。こちら、全員でお願いしますー🙏

検索対象、ima1zumiさんが指定してくれているところでバッチリです👍
その仕様でお願いしますー

**Comment by ima1zumi** [comment]
@machida 
ありがとうございます😊承知しました！

**Comment by machida** [comment]
@ima1zumi 実装ありがとうございました🙏
