### ISSUE TITLE
「今日の気分」のsosoを暖色系（人間に近い色味）にしたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2155]
今日の気分が絵文字から画像に変わったが、sosoが緑色なので、日報やニコニコカレンダーを見たときに毎回ぎょっとしてしまう。（ピッコロ大魔王？宇宙人？？みたいな感覚）

sadはともかく、sosoとsmileは選択頻度も高いと思うので、人間っぽい色味に変更してほしい。

<img width="324" alt="Screen Shot 2020-11-26 at 8 37 59" src="https://user-images.githubusercontent.com/1148320/100292320-7ac82f80-2fc3-11eb-958a-7c7be07ff75a.png">

## 追記：表情ももう少しにこやかにしたい
sosoは「ふつう・まあまあ」というより、「つまらない顔」に見えます。

- soso = 🙂
- smile = 😄

ぐらいの表情がいいのではないでしょうか。

**Comment by machida** [comment]
なるほど、ありがとうございます！
僕としてはsmileではない、ということで soso はネガティブなものととして捉えてました。sosoの顔が笑顔になってしまうとほとんど全てがsosoになってしまいそうで、少しでもハッピーなら smile の方を選択してほしい、というのがありました。

色に関しては、選択する側ではなく、見る側の話になるのですが、顔の表情で見分けると解像度が高くないと見分けることが難しくなるので、シールで運用してるニコニコカレンダーに近づけて、色味ですぐわかることを目的にしたため、はっきりとした色を選択しました。

![image](https://user-images.githubusercontent.com/168265/100300152-b91c1980-2fd8-11eb-93f6-d818a09cc4a9.png)

...と、UIデザイン的にはこういう意図があったのですが、伊藤さんの立てていただいた指摘を導入したらいい感じになりました！！

![image](https://user-images.githubusercontent.com/168265/100300249-ee286c00-2fd8-11eb-8bef-11cc9c6bd9f8.png)

![image](https://user-images.githubusercontent.com/168265/100300381-452e4100-2fd9-11eb-8ae3-fc6cb50509a4.png)

元々絵文字でやっていたものからの急激な変化が違和感を感じたのと、グラフィカルなアイコンの方が雰囲気が楽しげでキャッチーでデザイン的にリッチな印象を感じる、というのがいい感じの理由だと思います。

**Comment by JunichiIto** [comment]
おお、さっそくの対応ありがとうございます！

> 僕としてはsmileではない、ということで soso はネガティブなものととして捉えてました。sosoの顔が笑顔になってしまうとほとんど全てがsosoになってしまいそうで、少しでもハッピーなら smile の方を選択してほしい、というのがありました。

その意図を聞くと「なるほど」と思うのですが、UIだけでは意図がくみ取れなかった、という感じですね。。

> 色味ですぐわかることを目的にしたため、はっきりとした色を選択しました。

そうですね、色味についてはたぶんそういう目的なんだろうな〜、とは思ったのですが、いかんせん「ピッコロ大魔王」感が出てしまってなんとも・・・という感じでした 💦 

で、新しいデザインはとてもよいですね！
"soso"ばかり選ばれてしまいそう、という問題はあるかもしれませんが、それは別件として改善に取り組むのがいいかな〜と思います。
