### ISSUE TITLE
「今日の気分」のsmileをhappyに変更したい（または日本語にしたい）

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2156]
sosoとsadは形容詞だがsmileは名詞なので一つだけ違和感がある。
形容詞でまとめるならhappyとかにした方が一貫性があると思う。

また受講生がほとんど日本人であることを考えると、ラベルも日本語で書いた方が直感的に選択しやすいと思う。
（sosoなんて普段使うことはないし）

日本語化の例

- sad = かなしい・ぴえん
- soso = ふつう・まあまあ
- happy = たのしい・うれしい

<img width="324" alt="Screen Shot 2020-11-26 at 8 37 59" src="https://user-images.githubusercontent.com/1148320/100292596-486b0200-2fc4-11eb-9574-b5e7888dd5cd.png">

**Comment by masuyama13** [comment]
修正済みなのでcloseします〜
