### ISSUE TITLE
「今日の気分」の並び方を変えたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2157]
現状 soso/sad/happy の順で並んでいるが、「ふつう(0)・悪い(-)・良い(+)」よりも 「悪い(-)・ふつう(±0)・良い(+)」のようにした方が自然な気がする。（数学の数直線と同じように並ぶので）

<img width="324" alt="Screen Shot 2020-11-26 at 8 37 59" src="https://user-images.githubusercontent.com/1148320/100292870-1f973c80-2fc5-11eb-874b-c45f10f37ac3.png">

**Comment by masuyama13** [comment]
マージ済みなのでcloseします〜
