### ISSUE TITLE
プラクティス詳細画面下部の『困ったときは、質問・雑談ルームを利用しよう！くわしくはこちら』のリンクを変更したい

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#2162]
**何故この機能が必要なのか**
ユーザーアンケートにより質問雑談タイムを仕事などの都合上で使用できない、敷居が高く感じる、どうしても頼らないとわからない時でないと参加できないという意見が複数あった。
質問力の大切さ、質問雑談ルーム以外にも複数質問をおこなる場所があることを明記したくリンク先を変更したいです。

**機能の説明**

現在プラクティス詳細画面の下部には↓のようなリンクが貼られている

<img width="1140" alt="スクリーンショット 2020-11-27 8 58 36" src="https://user-images.githubusercontent.com/5990045/100397759-d3b0ca00-308e-11eb-84ca-76f889bbc754.png">

この『くわしくはこちら』のリンク先が現在
https://bootcamp.fjord.jp/pages/242
になっているが
https://bootcamp.fjord.jp/pages/245
に変更したい

**Comment by machida** [comment]
@hisaotoriyama 

## 現在

困ったときは、質問・雑談ルームを利用しよう！くわしくはこちら https://bootcamp.fjord.jp/pages/242

## 変更後

わからないことがあったら質問をして解決しよう！くわしくはこちら https://bootcamp.fjord.jp/pages/245

----

上記のように変更をお願いします
