### ISSUE TITLE
開発環境でお知らせやDocを作成した際に、通知ターゲット数分のメール確認用タブが開かれるのを改善したい

### ISSUE THREAD

**Issue by Chi-rr** [fjordllc/bootcamp#2181]
## 改善したいこと
開発環境でお知らせやDocを作成すると、通知ターゲット数分のメール確認用のタブが開かれる。
そのため毎度、各タブを閉じる手間が発生するので改善したい。

### お知らせを作成する画面
<img width="1090" alt="スクリーンショット 2020-12-02 19 59 30" src="https://user-images.githubusercontent.com/52053239/100864245-17656280-34d9-11eb-8cda-19f58eb9fa4f.png">

### 通知ターゲット数分のメール確認用のタブが開かれる
<img width="1550" alt="スクリーンショット_2020-12-02_20_00_01" src="https://user-images.githubusercontent.com/52053239/100864496-68755680-34d9-11eb-8b31-39147450183f.png">

## 原因
`letter_opener`gemによる動作。

## 改善案
既存の`letter_opener`gemを、`letter_opener_web`gemで代替する。
それにより、複数のメール確認を1つのタブで管理することが可能となる。

【参考】
- [letter_opener](https://github.com/ryanb/letter_opener)
- [letter_opener_web](https://github.com/fgrehm/letter_opener_web)

**Comment by machida** [comment]
> 既存のletter_openergemを、letter_opener_webgemで代替する。

で行きたいと思いますー
