### ISSUE TITLE
Q&Aで、テンプレートを選べるようにしたい

### ISSUE THREAD

**Issue by imaharu** [fjordllc/bootcamp#2183]
**何故この機能が必要なのか**

日報やQ&Aの作成スキルによって、メンターや他生徒から回答をもらえる頻度や質が変わるのではないかという仮説がある。

フィーマットが決まっていることによって、誰でも一定の水準で日報やQ&Aを活用できるようになる

**機能の説明**

- GitHubのテンプレート機能のように、複数のテンプレートから一つを選ぶことができる

# Q&Aのテンプレート例

- 各種version
  - ruby, rails
- 自分がわかっていること
- 期待した結果
- 実際の挙動

**Comment by rlho** [comment]
私もこの機能ほしいです！

**Comment by imaharu** [comment]
初期の実装は、複雑な要件にせず `質問文` が空白ではなく、テンプレートで埋まっている状態にすれば良さそうです。

<img width="1443" alt="スクリーンショット 2021-06-15 23 29 46" src="https://user-images.githubusercontent.com/23719154/122071299-9a288c00-ce31-11eb-861a-f258e3b286f3.png">

**Comment by JunichiIto** [comment]
これはあった方がいいのでは？
