### ISSUE TITLE
ユーザー一覧で1ページに表示されるユーザーを12の倍数区切りにしてほしい

### ISSUE THREAD

**Issue by shimewtr** [fjordllc/bootcamp#2185]
![image](https://user-images.githubusercontent.com/2524168/124526228-203a6000-de3d-11eb-8365-39a85e91a504.png)

右下が空いてしまい表示が不自然に見える
表示領域を狭めていくと2, 3, 4列で表示するパターンがあるので、
1ページに表示されるユーザーを12の倍数にして最下部にスペースができないようにする

**Comment by shimewtr** [comment]
2,3,4列のパターンがあるので12の倍数が正しかったです…🙇‍♂️

**Comment by komagata** [comment]
:memo: まずは１ページに24個表示するようにしたい。

**Comment by sadanora** [comment]
本番で動作確認ができたのでcloseします。
