### ISSUE TITLE
初日報の更新のたびに通知やメールが飛ぶ

### ISSUE THREAD

**Issue by universato** [fjordllc/bootcamp#2205]
## 概要

日報が1つの状態で初日報を更新すると(保存し直すと)、その度に通知・メールが飛んでいる。

## 再現手順

1. 日報がないアカウントAで、初日報を投稿(保存)する。
2. 別のアカウントBで、通知がきて消えることを確かめる。
3. 再度アカウントAで、初日報を更新する(保存し直す)。
4. 再度アカウントBで、通知が来ている。

## 期待される振る舞い

初日報の保存し直しは、通知やメールが再度いかないようにしたい。
ケースバイケースでしょうが、1回投稿したあとに大幅な修正をすることはマレで、
誤字脱字の修正のたびに通知やメールが来るのは望ましくないと思われます。

## 環境

 - OS: Mac
 - ブラウザ: Chrome, Firefox

同じ方の初日報の通知が何度か来たことがあり、
開発環境で初日報の更新のたびに通知がいくか試したところ通知がいってました。
また、日報が2つあるときは、再度通知は行くことはありませんでした。

## 関連Issue

#1139 はじめての日報をWIPで書くと全体通知される（たぶん提出された時だけ通知されたい)

**Comment by hituzi-no-sippo** [comment]
#2400 内の

> 更新前、WIP or 非WIPだったか判定する方法があり、それを report.wip == false の代わりに利用すれば、問題解決できそうです。

の __WIP or 非WIPだったか判定する方法__ ですが

https://github.com/fjordllc/bootcamp/blob/7d022f465c94b55b49535e68de83fb89920abf57/app/controllers/reports_controller.rb#L69-L70

を次のようにすれば可能かなと思いました。

```ruby
  def update
     wip_before_update = @report.wip
     set_wip
     has_updated_to_published = !@report.wip && wip_before_update
```

ただ、 `has_updated_to_published` の値を

https://github.com/fjordllc/bootcamp/blob/7d022f465c94b55b49535e68de83fb89920abf57/app/models/report_callbacks.rb#L24-L28

に渡す方法は調べてないので分かりません。

また、これだと "提出 => WIP => 提出" だと "WIP => 提出" の間で通知が送信されます。

**Comment by SeijiNumata** [comment]
@hituzi-no-sippo 
コメントありがとうございます。
丁度このissueに取り組んでいるところです。まだ色々試行錯誤している段階なので、助かります。

> また、これだと "提出 => WIP => 提出" だと "WIP => 提出" の間で通知が送信されます。

これは改善する必要がありそうですね。

今試している中で、現時点で最もうまくいきそうな実装方針としては、「何回提出をしたかをカウントするカラムをReportテーブルに持ち、提出回数が２回以上であれな弾く」([日報](https://bootcamp.fjord.jp/reports/26653))なのですが、正直センスがないような気もするんですよね〜

真偽値でなんとかしたいという気持ちもあるので、@hituzi-no-sippo さんのご提案いただいた内容で、 "提出 => WIP => 提出" だと "WIP => 提出" の間で通知されない方法も考えてみます。

**Comment by SeijiNumata** [comment]
@komagata 
実装方針について相談です〜

現状、以下の案1の方法で実装しようと思っていますが、よろしいでしょうか？
他に良さそうな方法があれば教えて頂きたいです。
## 案1

`reportテーブル`に`published_countカラム`を作って、何回「提出」または「内容変更」をしたかを数え、２回以上であれば通知が行かないようにする。

reports_controller.rb
```ruby
  def set_published_count
    @report.published_count += 1 if params[:commit] == '提出' || params[:commit] == '内容変更'
  end
 ```
report_callbacks.rb
 ```ruby
 send_first_report_notification(report) if report.wip == false && report.user.reports.count == 1 && report.published_count < 2
 ```

***
わざわざcountせずに真偽値の判定のみでロジックが組めないか考えたのですが、提出→WIP→提出　などのパターンに対応することができず、このような方針になりました。(参考：https://github.com/fjordllc/bootcamp/issues/2205#issuecomment-792594749)

こちらの案１で作業を進めてしまって問題ないでしょうか？

**Comment by universato** [comment]
「提出 -> 提出」のパターンは、完成後して提出後に誤字の修正や気になった部分を更新することが主だと思っていて、自分も同じ日報に何度も連続で提出することがありました。対して、「提出 -> WIP -> 提出」の流れは稀だと思っていて、ここの通知の重複は対応しなくてもいいのかなと思いました。この「提出 -> WIP -> 提出」のパターンは、誤って未完成のまま最初に提出ボタンを押したけど、元に戻したいというときな気がしました。

**Comment by hituzi-no-sippo** [comment]
> 「提出 -> WIP -> 提出」の流れは稀だと思っていて、ここの通知の重複は対応しなくてもいいのかなと思いました。

同意見で、`提出 -> WIP -> 提出`  の `WIP -> 提出` で通知が送信されても別に問題ないと考えています。

理由としては次の2点です。

* `提出 -> 提出` の通知送信を止めるのがこのissueの内容
  "提出 -> WIP -> 提出" の "WIP -> 提出" で通知が送信される現象を今回のissueで止める必要はないと考えています。
* 初日報かつ "提出 -> WIP -> 提出" を行うのは非常に稀
   頻繁に発生して利用者がうるさいと感じるのであれば修正したほうがいいですが、非常に稀にしか発生しないので今すぐ修正する必要はない、優先度が非常に低いものという認識です。

"提出 -> WIP -> 提出" の "WIP -> 提出" の通知対応するメリットが低くても、単純&簡単な実装なら対応しても良いと考えています。ただ、案1は reportテーブルにpublished_countカラムを追加するため、単純&簡単な実装ではなく、小さなメリットのために行なう実装内容ではないと感じています。

---

私の次のコメントですが

> また、これだと "提出 => WIP => 提出" だと "WIP => 提出" の間で通知が送信されます。

"提出 -> WIP -> 提出" の "WIP -> 提出" の通知対応は必須という捉えることもできる記述で、言葉足らずでした。
気をつけるようにします。

**Comment by SeijiNumata** [comment]
@universato @hituzi-no-sippo 　CC @komagata 
コメントありがとうございます！
私もお二人の意見に納得です。
`"提出 -> WIP -> 提出"` の `"WIP -> 提出"`には対応しないで実装したいと思います。
***
実装について分からないところがあるので質問します。
https://github.com/fjordllc/bootcamp/issues/2205#issuecomment-792594749
こちらの実装方法で実装したいのですが、`reports_controller`で定義した変数の`has_updated_to_published`を、`reports_callbacks`に受け渡すが分かりません。

そのため対応策として、`has_updated_to_published`カラムを追加しようと思っています。

カラムを追加せずに実装できそうな方法があれば教えて頂けると嬉しいです。
よろしくお願いします。🙇‍♂️

**Comment by hituzi-no-sippo** [comment]
> そのため対応策として、has_updated_to_publishedカラムを追加しようと思っています。

あぁ、提出→WIP→提出 の通知対応するからカラム追加が必要で、対応しないならカラム追加必要ないという認識で[今朝のコメント](https://github.com/fjordllc/bootcamp/issues/2205#issuecomment-797138409)していました。

> カラムを追加せずに実装できそうな方法があれば教えて頂けると嬉しいです。

ごめんなさい 🙇‍♂️
私わからないです。

**Comment by SeijiNumata** [comment]
@hituzi-no-sippo 
返信ありがとございます！
結局カラム追加するのであれば、提出→WIP→提出にも対応できるようにカウントした方が良いって感じですかね？

もう少しコメントを待ってみて、変数をcallbacksに渡す方法がないか確認してみます。
なければ、提出回数をカウントするカラムを追加する方向で実装進めたいと思っております。

**Comment by universato** [comment]
> カラムを追加せずに実装できそうな方法があれば教えて頂けると嬉しいです。

[ActiveRecord6 の dirty attribute methods （will\_save\_change\_to\_\* とか）の挙動一覧 \- Qiita](https://qiita.com/mishiwata1015/items/a2df65c01f2fe6a562a5)
実際に試してないですが、こういうメソッドを使ったら、wipから変更されたかどうかなど追えるのではないか、と思いました。
ただ自分は詳しくないので、komagataさん等の意見を聞けるなら聞いた方がいいと思ってます。

> 結局カラム追加するのであれば、提出→WIP→提出にも対応できるようにカウントした方が良いって感じですかね？

自分はカラムに追加するしないにかかわらず、どちらかといえば、提出→WIP→提出は重複で通知した方がいいと思っている寄りです。WIPから提出に変更するタイミングが、見てもらいたいタイミングだと思うので。ただ、はじめての日報に限る中の稀な状況という認識なので、結局どちらでもいいのかもしれません。

**Comment by hituzi-no-sippo** [comment]
> 自分はカラムに追加するしないにかかわらず、どちらかといえば、提出→WIP→提出は重複で通知した方がいいと思っている寄りです。WIPから提出に変更するタイミングが、見てもらいたいタイミングだと思うので。

その考えありませんでした 👀 
提出→WIP→提出は重複で通知したままでいい寄りに変更します。

**Comment by komagata** [comment]
@SeijiNumata 「（WIPではなく）初めて提出にした時だけ〜」という処理は日報や提出物、お知らせに実装されているのでそちらを真似てみてください〜（published_atというカラムを追加してそれを使っている。）

**Comment by SeijiNumata** [comment]
@komagata 

published_atを追加しているメソッドで、`@noticeable`　というインスタンス変数が定義されていたので、それを使って実装できました！
[プルリク](https://github.com/fjordllc/bootcamp/pull/2444)

ありがとうございます〜
