### ISSUE TITLE
イベント一覧ページにイベント日時を載せたい

### ISSUE THREAD

**Issue by gogutan** [fjordllc/bootcamp#2206]
**何故この機能が必要なのか**

イベント詳細ページを開かなくても、イベント日時を知りたい。

**機能の説明**

現状はこんな感じです。
![イベント___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/50437473/102709477-6fc89c80-42ee-11eb-8731-1cf593cacb13.png)
これを、

- 最終更新日時とイベント日時を併記する
- イベント日時のみ記載する

とする2パターンがあって、私は後者がいいのかなと考えています。（併記はわかりにくそうなので😅）
イベント詳細ページには最終更新日時が記載されているし、「イベント日時のみ記載」で良さそうですが、どうでしょうか。

**Comment by SeijiNumata** [comment]
@komagata @machida 
このissueの仕様について、仕様の摺り合わせをお願いします。

A案：最終更新日時とイベント日時を併記する
B案：イベント日時のみ記載する
***
どちらも作ってみました。
**A案**
![image](https://user-images.githubusercontent.com/50447071/109962378-73d15b80-7d2e-11eb-949c-3d15b5543925.png)

**B案**
![image](https://user-images.githubusercontent.com/50447071/109960174-d1b07400-7d2b-11eb-85d8-4ff61372a183.png)
***
私の意見はgugutanさんと同じで、B案がシンプルで良さそうと思いますが、こちらいかがでしょうか？

以上、ご確認お願いいたします。

**Comment by komagata** [comment]
僕も @SeijiNumata さんのおっしゃる通りB案がいいかな〜と思いました〜

**Comment by SeijiNumata** [comment]
@komagata 
承知いたしました！
B案で実装を進めさせていただきます😁

ありがとうございます🙇‍♂️

**Comment by komagata** [comment]
@SeijiNumata こちらリリース後、本番環境で動作確認して完了していたらIssueのクローズもお願いします〜（僕がCloseしておきます〜）

**Comment by SeijiNumata** [comment]
@komagata 
承知しました。完了したら次からクローズさせます。
ありがとうございます。
