### ISSUE TITLE
ライセンスを明示した方がいいのでは？

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2207]
このbootcampアプリはpublicリポジトリとして外部に公開はされているものの、ライセンスが明記されていません。（載ってないですよね？）

純粋なOSSとして扱うのであれば、何かしらのOSS系のライセンスを明示した方がいいのではないかと思いました。

**Comment by kakutani** [comment]
89448f3e2776c3b2ac6aca592629ca05156cd94b でMITが入った 👀

**Comment by JunichiIto** [comment]
クローズしておきます〜。
