### ISSUE TITLE
プラクティスの並び替えがエラーになる（管理者の機能）

### ISSUE THREAD

**Issue by masuyama13** [fjordllc/bootcamp#2211]
## 概要

管理者でログインし、プラクティス一覧で並び替えボタンを押すとエラーになる。

![Screen_Shot_2020-12-23_at_14_43_06](https://user-images.githubusercontent.com/58389623/102963893-a0e2e000-452d-11eb-990e-49d8034c8368.jpg)

## 再現手順

1. 管理者でログイン
1. プラクティス一覧ページにアクセス
1. 各プラクティス右上の歯車マークをクリックして並び替えボタンを表示させる
1. 並び替えボタンのいずれかをクリック

## 期待される振る舞い

プラクティスが並び替えられる。

**Comment by machida** [comment]
こちら、masuyamaさんが並べ替えUI自体をリニューアルしてくれたのでclose
