### ISSUE TITLE
リリース時にデプロイが終わったらSlackで通知する

### ISSUE THREAD

**Issue by bluerabbit** [fjordllc/bootcamp#2212]
**何故この機能が必要なのか**

デプロイが終わったかは管理コンソールにログインできる @komagata しか確認できないので、デプロイ終わりましたか？みたいなやり取りが発生している。

**機能の説明**

デプロイ処理で処理が終わった時にSlackで通知するようにします。

**Comment by bluerabbit** [comment]
@komagata どのチャンネルに通知したら良いでしょうか。あとdiscordにも通知？

**Comment by komagata** [comment]
@bluerabbit bootcamp チャンネルでお願いできれば〜
Discordとかは今後なので僕がやります〜
