### ISSUE TITLE
滅多に使わないネガティブなリアクションを消す

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2214]
👎 や 😕 みたいなネガティブなリアクションはフィヨルドブートキャンプ内で使われることは滅多になさそう。
うっかりクリックすると人間関係がこじれそうなので、選択肢から消した方がいいのでは？
そのかわりに 🙏 とか 😢 みたいなリアクションに置き換えたい。（何に置き換えるのかは議論の余地がありそうですが）

<img width="247" alt="Screen Shot 2020-12-25 at 9 17 31" src="https://user-images.githubusercontent.com/1148320/103111632-7494a400-4692-11eb-8c27-451d1ab8f378.png">

**Comment by JunichiIto** [comment]
実際に 👎 を押してしまって生徒さんを混乱させてしまった事例が発生しているので、早めに対応した方がいいかもです。 (CC @u1tnk )

ref: https://github.com/fjordllc/bootcamp/issues/2303
ref: https://bootcamp.fjord.jp/reports/24873#comment_48451

**Comment by harukus** [comment]
@machida 
私がassignされたということは(準備ができたら)こちらのissueに取り組んだ方がいいということでしょうか？？:eyes:
(何もわからなくて申し訳ないのです🙇‍♂️)

**Comment by machida** [comment]
@harukus 次お願いする、というのを忘れないようにアサインさせていただきましたー。もし、手が空いたら着手お願いします🙏

不明点ややりとりはこのIssue上で進めていきたいと思います。ネガティブな絵文字を何にするか、考えていきましょう。アイディアがありましたらお願いします！

**Comment by harukus** [comment]
なるほどです！アサインありがとうございます。かしこまりました。

伊藤さんもおっしゃている通り、「🙏」も良いなと思いました。あとはそれに似ている🙇‍♂️も良いかなと思います。（どちらも押し間違えても誤解を与えることがないと思うので、、！）

**Comment by harukus** [comment]
それかネガティブな絵文字の代わりにポジティブなものに置き換える、というのはいかがでしょうか？
slackなどでよく使用される✨や🙌などがあるとポジティブな絵文字の選択肢が増えるので押された方も嬉しくなるかな、、、と！

**Comment by machida** [comment]
@harukus 

案、ありがとうございます！！

`🙇‍♂️` こっちは申し訳ございません的な意味を含んでしまっているので、コミュニティ的には「お互い様、気にしないでいこうよ」、というノリでいきたいので、「感謝！」の `🙏` こっちにしたいですね〜

`✨` 、 `🙌` いいですね！！
この2つのどっちかにしたいと思います！！
どちらにしても効果はあまり変わらないと思うのですが、僕としては、「万歳！！」の `🙌` がいいかと思いましたー

**Comment by JunichiIto** [comment]
🙏 と 🙌 、いいかも〜。

**Comment by harukus** [comment]
@machida @JunichiIto 
ありがとうございます。
そうしましたら「🙏 と 🙌 」に置き換えていく方向で進めていこうと思います！

**Comment by machida** [comment]
@harukus ありがとうございます！それでお願いしますー

**Comment by u1tnk** [comment]
お、アサインされてる！
私がやらかして 👎 を押してしまった人なので、改善を待ち望んでおりました！
@harukus  宜しくお願いします 🙏
