### ISSUE TITLE
日報で、ある特定の手順を踏むと確認ダイアログが出ずにタブを閉じてしまう

### ISSUE THREAD

**Issue by SeijiNumata** [fjordllc/bootcamp#2216]
## 概要

日報でエラーを出してから、更新せずに×ボタンを押すと確認ダイアログが出ずにタブを閉じてしまう
## 再現手順

1. 日報(https://bootcamp.fjord.jp/reports/new) を作成する
2. バリデーションに引っかかるようにして提出ボタンをクリックする。（何でも良いので下記画像のようにエラーを出す）
![image](https://user-images.githubusercontent.com/50447071/103165629-ab6ae580-485d-11eb-91dc-f80e5033cab0.png)
3. **内容を何も更新せずに**タブを閉じると、確認ダイアログが出ないままタブを閉じてしまう

## 期待される振る舞い
タブを閉じようとすると、下記画像のような確認ダイアログが出ること
![image](https://user-images.githubusercontent.com/50447071/103165642-d81efd00-485d-11eb-91bd-820481c19685.png)

**Comment by JunichiIto** [comment]
補足：
Seijiさんはがんばって書いた日報が消えてしまう、という悲劇に遭ってしまったそうです😢
https://bootcamp.fjord.jp/reports/22939
