### ISSUE TITLE
メンターがお知らせを公開するときのアクションの文言がおかしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2219]
<img width="619" alt="貼り付けた画像_2020_12_29_17_43" src="https://user-images.githubusercontent.com/168265/103271379-75646780-49fd-11eb-98c7-9ab8328ba944.png">

**Comment by gallardo16** [comment]
@komagata 
レビューありがとうございました。
本番環境での動作確認をお願いします！

**Comment by komagata** [comment]
@gallardo16 ありがとうございます！

**Comment by komagata** [comment]
@komagata 上で僕言ってることおかしいですねw
本番環境で確認しました。OKです。
