### ISSUE TITLE
アンフォロー時に、自分より先にそのユーザーをフォローしている人がいるとその人のフォローが外れる

### ISSUE THREAD

**Issue by shimewtr** [fjordllc/bootcamp#2220]
## 再現手順

1. ユーザーAがユーザーCをフォローする
2. ユーザーBがユーザーCをフォローする
3. ユーザーBがユーザーCをアンフォローする
4. ユーザーAがユーザーCをアンフォローしてしまう

## 期待される振る舞い

ユーザーBがユーザーCをアンフォローする

https://github.com/fjordllc/bootcamp/blob/4f47ea1b79bd9acfb63bc583f2ef0d99452ead60/app/models/user.rb#L488-L490
find_byに自分を含めるか
followingからfind_byする

**Comment by ima1zumi** [comment]
うわ、すみません！すぐ修正します。
ご報告ありがとうございます…！ 🙇
