### ISSUE TITLE
anyloginの使い方をREAMEに追記

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2230]
以下を

```md
- [Develop環境でログインする方法](https://github.com/fjordllc/bootcamp/wiki/Develop%E7%92%B0%E5%A2%83%E3%81%A7%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95)
```

ここに追加お願いしますー

<img width="601" alt="貼り付けた画像_2021_02_03_17_25" src="https://user-images.githubusercontent.com/168265/106718745-cb53ad00-6644-11eb-8a0c-77fe9cee1431.png">

**Comment by machida** [comment]
@harukus 

上記の内容でお願いしますー

**Comment by harukus** [comment]
@machida 
かしこまりました！
