### ISSUE TITLE
最終活動日時が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2231]
- sorceryのlast_activity_atを使う。
- 「最終ログイン」の代わりに「最終活動日時」を追加する。

<img width="365" alt="スクリーンショット 2022-06-24 16 11 06" src="https://user-images.githubusercontent.com/16577/175482606-d6903288-0e3f-4156-9f14-e5fd5403b7d8.png">

**Comment by imaharu** [comment]
そもそも最終活動日時って、必要なんだっけ？から考えた方がいいかも...と思いました (実際にタスク割り振られてた人の宿題？)

**Comment by machida** [comment]
> そもそも最終活動日時って、必要なんだっけ？

https://github.com/Sorcery/sorcery/wiki/Activity-logging

**Comment by komagata** [comment]
@machida 情報ありがとうございます。

**Comment by SatoshiHaramura** [comment]
【アップデート情報】
　■仕様 (6/27(月)に駒形さんに確認済み)
　　・「最終活動日時」に差し替える箇所は、usersテーブルの`updated_at`カラムを使用している箇所とする。
　　・`last_activity_at`の初期値は、`updated_at`カラムの値とする。

**Comment by SatoshiHaramura** [comment]
@komagata @machida 
お疲れ様です。
本番環境での動作確認を依頼させて頂きたいです🙏(管理者またはメンターのみ確認できるため)

以下の各箇所において、`最終活動日時`が`2022年07月07日(木) 15:35`となっていることを確認して頂きたいです。
(私(SatoshiHaramura)の最終アクセスは、15:35 に行いましたので)

1. [SatoshiHaramuraのユーザー詳細ページ](https://bootcamp.fjord.jp/reports/56785) の`最終活動日時`
2. [管理ページ](https://bootcamp.fjord.jp/admin/users)のSatoshiHaramuraの`最終活動日時`

また、以下のダッシュボードの場合は、表示されているユーザーの`最終活動日時`が1ヶ月以内であることを確認してほしいです。
併せて、SatoshiHaramuraが一覧に表示されていないことも確認して頂きたいです。
1. [ダッシュボード](https://bootcamp.fjord.jp/) の「1ヶ月以上ログインのないユーザー」の`最終活動日時`

**Comment by machida** [comment]
@SatoshiHaramura 確認しました！全てOKでしたー🙆‍♂️

**Comment by SatoshiHaramura** [comment]
本番環境で動作確認が完了しましたので、close致します。
