### ISSUE TITLE
プラクティスの並び順がおかしい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2232]
@komagata @machida 
https://github.com/fjordllc/bootcamp/pull/2186 の修正が
https://github.com/fjordllc/bootcamp/commit/bd1fdcedfbc5af3bc0ab29dd41c420979f1f47d7#diff-2db403b775622a9c16f7ead2f598d1b7c441cc1c8e580971b69733d7b3659f4fL48 
でrevertされてしまっているのが原因のようです。

**Comment by masuyama13** [comment]
修正済みなのでcloseします〜
