### ISSUE TITLE
日報の「今日の気分」が選択状態にならない

### ISSUE THREAD

**Issue by yana-gi** [fjordllc/bootcamp#2233]
## 概要

日報の「今日の気分」が画面上で選択状態にならない。
いずれかを選択してwipや投稿を押すと、遷移後の画面ではニコニコマークが表示されている。

### 日報の「今日の気分」が画面上で選択状態にならない
1.  /reports/newにアクセス
2. 今日の気分のラジオボタンをクリックする
3. 画面上で選択状態にならない

### いずれかを選択してwipや投稿を押すと、遷移後の画面ではニコニコマークが表示されている
1. /reports/newにアクセス
1. 今日の気分のラジオボタンをいずれかを選択し、wipを押す
1. 遷移後の`/reports/xxxx`ではニコニコマークが表示されている

## 期待される振る舞い

日報の「今日の気分」のラジオボタンをクリックすると選択状態になる。

## 環境

 - OS: Big Sur
 - ブラウザ: chrome
 - バージョン: 87.0.4280.88（Official Build） （x86_64）

**Comment by machida** [comment]
修正しましたー
