### ISSUE TITLE
プラクティスの順番を担保するテストを書く

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2234]
プラクティスの順番がおかしくなる不具合が立て続けに起きています。

参考 https://github.com/fjordllc/bootcamp/issues/2232

プラクティスの並び順は受講生が学習を進める上で重要な要素なので、これ以上再発しないようテストを書いて仕様を担保するのが望ましいと思います。

**Comment by machida** [comment]
@komagata 
こちらお願いします

**Comment by JunichiIto** [comment]
この問題、やっぱりちゃんとテスト書いておきたいですね〜。

**Comment by komagata** [comment]
@JunichiIto かしこまりました。ただ、今回の問題は本番上のデータでのみ起きる問題なのでテストでは防げなかったです。すみません。

**Comment by JunichiIto** [comment]
closeするのもおかしい気がするのでstaleを外しておきます。
