### ISSUE TITLE
日報の個別ページで、プラクティス部分の表示が崩れる

### ISSUE THREAD

**Issue by takopom** [fjordllc/bootcamp#2239]
## 概要

日報の個別ページを表示すると「プラクティス」部分の表示が左に寄ります。

（Slackの#bootcampにて @ksmxxxxxx さんからご報告いただいた内容です🙇‍♀️）

## 再現手順

1. /reports/{日報ID}にアクセス。

## スクリーンショット

<img width="300" alt="スクリーンショット 2021-01-08 4 52 07" src="https://user-images.githubusercontent.com/2003287/103939577-55f0db80-516f-11eb-8c93-a8f569b30331.png">

## 期待される振る舞い

以下のような表示になること。
<img width="300" alt="スクリーンショット 2021-01-08 4 54 59" src="https://user-images.githubusercontent.com/2003287/103939276-dcf18400-516e-11eb-8977-b0ec0764a7d7.png">

## 環境

 - OS: macOS Catalina
 - ブラウザ: Chrome
 - バージョン: 87.0.4280.88（Official Build） （x86_64）

## 関連Issue

こちらの機能をマージしていただいた後に発生しました🙇‍♀️
Ref: #2128

**Comment by komagata** [comment]
@takopom Issue登録ありがとうございます！

**Comment by machida** [comment]
修正しましたー
