### ISSUE TITLE
Q&Aでページを開いた瞬間に回答数がわかると嬉しい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2244]
**何故この機能が必要なのか**

一覧ページからではなく、直接Q&Aの質問・回答ページに遷移した場合、画面をスクロールしないと何件回答があったのかわからない。

件数が表示されていれば、

- ゼロ = まだ誰も回答してないのか
- 1〜2 = 誰かは回答してくれたみたいだな
- 3〜5 = ふむふむ、いい感じ
- 6以上 = 盛り上がっとるな

みたいなことがページを開いた瞬間に把握できる。

**機能の説明**

Teratailの画面が参考になるかも。

https://teratail.com/questions/247102

<img width="669" alt="Screen Shot 2021-01-10 at 11 03 01" src="https://user-images.githubusercontent.com/1148320/104112604-23dca680-5334-11eb-8550-202c0f3fd9dd.png">

**Comment by komagata** [comment]
@hisaotoriyama  こちらリリース後、本番環境で動作確認して完了していたらIssueのクローズもお願いします〜（僕がCloseしておきます〜）

**Comment by hisaotoriyama** [comment]
@komagata 
了解いたしました。ご指導ありがとうございます。今後励行します
