### ISSUE TITLE
ニコニコカレンダーが反映されていない日がある。

### ISSUE THREAD

**Issue by k-nakamura1984** [fjordllc/bootcamp#2261]
## 概要
日報を投稿しているが、ニコニコカレンダーが表示されていない日がある。
（初めてのバグレポートのため、不備箇所や参考情報がありましたらご教示いただけますと幸いです）

## 再現手順
投稿済みの日報を確認。
[k\-nakamura1984の日報 \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/users/1013/reports)

プロフィールのニコニコカレンダーを確認。1月13日、15日、16日のニコニコが表示されない。
[k\-nakamura1984のプロフィール \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/users/1013)

## 期待される振る舞い
日報を投稿した日のニコニコカレンダーが表示される。

## 環境
 - OS: Catalina 10.15.7
 - ブラウザ: chrome
 - バージョン: 87.0.4280.141（Official Build） （x86_64）

## 関連Issue

Ref: #関連Issue番号

**Comment by universato** [comment]
関連Issue: #2158「今日の気分」を入力必須にしたい

現状の日報は、気分(ニコニコマーク)を未選択の状態で投稿できてしまうので、
マーク未選択の日報があれば、カレンダーにもマークはなく日報の存在しない日と区別がつかない状況です。

気分(ニコニコマーク)を選択しても反映されないバグなのか、
(マーク未選択で)日報があるのにニコニコマークがないのが変なのか、
どちらを問題視しているのかわからないので、そのあたりが明らかになるといいと思いました。

**Comment by k-nakamura1984** [comment]
失礼しました…。
マークを選択していたと錯誤しておりました。
編集して、マーク選択したところ無事に反映を覚悟できました。

私の不備が発端であり恐縮ですが、マーク未選択時はアラートが出ると良いのかな、と思いました。
しかし、使い方は人それぞれなので固定化するのもよくないのかな、と感じました。
