### ISSUE TITLE
ユーザータグ機能のユーザー一覧ページに卒業生も表示してほしい

### ISSUE THREAD

**Issue by gogutan** [fjordllc/bootcamp#2262]
ref: #2128 

**何故この機能が必要なのか**

とても楽しい機能なので、現役生・メンター・アドバイザーの皆様のみならず卒業生も表示してほしいです！

**機能の説明**

<img width="1208" alt="ユーザー一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/104847109-811ebc00-5921-11eb-9e3f-6a32d6793a2f.png">

**Comment by eatplaynap** [comment]
こんにちは。昨日このissueを知らずに卒業生の方のタグをクリックしたら、"タグ「○○」のユーザーはいません"と表示されてしまい驚きました。[詳細](https://bootcamp.fjord.jp/reports/25472)
知らない人からはバグっぽく見えると思うので、ぜひご対応お願いします😢

**Comment by universato** [comment]
このIssueは2周間ほど前に解決済みで、本番でも卒業生が見えているので、クローズします。
