### ISSUE TITLE
ユーザータグ機能のユーザー一覧ページが、「現役生」でフィルタリングされているように見える

### ISSUE THREAD

**Issue by gogutan** [fjordllc/bootcamp#2263]
## 概要

現役生ではないユーザーも表示結果に含まれているが、上部のボタンを見ると「現役生」でフィルタリングされているように見える。

<img width="1211" alt="New_Issue_·_fjordllc_bootcamp_と_ユーザー一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/104847371-eaeb9580-5922-11eb-9834-71d9437c2bf3.png">

## 期待される振る舞い

フィルタリング機能がない間、上部のボタン一覧自体無くてよさそうです。

## 関連Issue

Ref: #2128

**Comment by machida** [comment]
ユーザータグに紐づくユーザー一覧の場合は、フィルターのパーツは表示されなくする。
