### ISSUE TITLE
test/system/course/practices_test.rb のテストが時々落ちる

### ISSUE THREAD

**Issue by Chi-rr** [fjordllc/bootcamp#2269]
## 概要
`test/system/course/practices_test.rb:13`が原因で、ローカル・circleciそれぞれで、時々テストが落ちてしまう
```
F

Failure:
Course::PracticesTest#test_show/hide_the_progress_of_others [/home/circleci/repo/test/system/course/practices_test.rb:22]:
Expected false to be truthy.


rails test test/system/course/practices_test.rb:13
```

## 再現手順
- ローカルでテストをする
- CIでテストをする

## 期待される振る舞い
テストが常に落ちない

## スクリーンショット
テストが失敗した際のスクリーンショット

![hide_the_progress_of_others__1_](https://user-images.githubusercontent.com/52053239/105273988-a9d3d980-5bdf-11eb-81a2-ed45deb28a8b.png)

## 関連Issue

Ref: #2152
Ref: #2246

**Comment by ima1zumi** [comment]
Merge済みのためCloseします。
