### ISSUE TITLE
入力中のテキストがあるときにページ移動するときは確認プロンプトを出す

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2272]
Q&Aのコメント欄を入力しているときにhistory back等でページ遷移してしまうと、入力中のテキストテキストが失われてしまう。

> コメント書いている途中でブログ記事に飛んだりしていたら内容が全部消えてしまった
> https://bootcamp.fjord.jp/questions/783#answer_2283

Q&Aのコメント欄に限らず、長文を入力する可能性がある入力欄はsubmit時以外のページ遷移で確認プロンプトを出した方がいいかも？

関連issue
https://github.com/fjordllc/bootcamp/issues/2216

**Comment by machida** [comment]
登録ありがとうございます！！
テキスト入力には入れてたのですが、コメントには抜けてたっぽいです。
これ、最優先で着手したいと思います💪

**Comment by haruguchi-yuma** [comment]
本番環境で動作確認しましたので、クローズします！
