### ISSUE TITLE
お知らせの『コピー』を押しても内容がコピーされない

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#2273]
## 概要

お知らせの『コピー』を押しても内容がコピーされない

## 再現手順

1. https://bootcamp.fjord.jp/announcements/396にアクセス。
2. 「コピー」をクリック。
3. エディタが開くが内容がコピーされていない

## 期待される振る舞い

コピーボタンを押すと内容が、元々の記事の内容がエディタの中に入っていて欲しい

## スクリーンショット

https://user-images.githubusercontent.com/5990045/105643648-65dd1f00-5ed4-11eb-958f-75834f7cbc08.mov

## 環境

 - OS: [MacOS]
 - ブラウザ: [chrome]
 - バージョン: [バージョン: 88.0.4324.96]

**Comment by Yu-kichi** [comment]
関連するものを見つけたので報告します。
開発環境から管理者でログインし、お知らせ一覧画面からコピーのアイコンを選択すると、コピーされず新規作成ページへ飛びます。

[![Image from Gyazo](https://i.gyazo.com/afd44c742faeb70afa1c19c5b8487953.gif)](https://gyazo.com/afd44c742faeb70afa1c19c5b8487953)

該当コードと思われるもの
app/views/announcements/_announcements.html.slim
```
- if admin_login? || current_user == announcement.user
    .thread-list-item__actions
       = link_to new_announcement_path(id: announcement), class: 'thread-list-item__actions-link' do
         i.fas.fa-copy
```
