### ISSUE TITLE
【メンター向け機能】提出物の担当者にアイコンが出ていると嬉しい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2274]
提出物一覧に表示される担当者欄に名前だけでなくアイコンも出ていると視認性が向上しそうです。

<img width="443" alt="Screen Shot 2021-01-25 at 7 08 34" src="https://user-images.githubusercontent.com/1148320/105645005-4fd35c80-5edc-11eb-97ee-7cc63ef7a833.png">

↓

<img width="443" alt="Screen Shot 2021-01-25 at 7 08 34" src="https://user-images.githubusercontent.com/1148320/105645057-99bc4280-5edc-11eb-950e-46574cfb582d.png">

**Comment by Daichi831** [comment]
@komagata 
こちらメンターのみ確認可能ですので確認をよろしくお願いします〜🙇

**Comment by Daichi831** [comment]
こちら本番環境で確認できたためcloseします〜
