### ISSUE TITLE
「完了済」に"馬から落馬"感がある

### ISSUE THREAD

**Issue by kakutani** [fjordllc/bootcamp#2276]
## 概要

プラクティスの「完了」がらみの表現に違和感をおぼえました。

## 再現手順

![image](https://user-images.githubusercontent.com/2160/105697788-5bf50380-5f48-11eb-9914-3d8476e9e347.png)

## 期待される振る舞い

* 「完了」は「《名・ス自他》完全におわること、おえること。」なので、完了が済んでいる(完了済) #とは という気持ちになる。
* 完了していない状態の表示が「完了」なので、たとえばこれを「完了させる」というアクションをあらわすラベルにして、「完了済」の状態を「(既に)完了しています」とするのはどうか。
* また「終了条件」の「終了」もおしまい、というニュアンスが感じられるので、より能動的に「完了条件」のような表記にするのはどうか
* 現状は「終了条件をクリアしたら完了にしてください」という但し書きがあるが、これも「完了条件を満たしていれば完了させてください」といった表記にすることで、上記との整合性をはかれるのではないか、と推察する。

…それはそれとして「Done」の訳語は2021年であれば「完了」よりは「完成」のほうが適切なように思うが(たとえば、スクラムガイドではDefinition of Doneは「完成の定義」という訳語になっている)、まあプラクティスそれぞれの記述をみると「完成」という語に合わせると、しっくりこないものもありそうなので「完了」でもいいかな、という気持ちではある。

## 関連Issue

あればご教示くださいませ

**Comment by machida** [comment]
@hisaotoriyama 
完了済 → 完了しています
に変更をお願いします🙏
