### ISSUE TITLE
日報の『プラクティス』を一度選択して保存すると、その後消しても反映されない

### ISSUE THREAD

**Issue by siroemk** [fjordllc/bootcamp#2277]
## 概要

日報の「プラクティス」を選択して保存すると、その後、「プラクティス」を削除して保存し直しても反映されない。

## 再現手順

1. https://bootcamp.fjord.jp/reports/24250にアクセス。
2. 「内容修正」ボタンを押す
3. プラクティスで選択されている「Ruby初級」の「×」を押して削除する
4. 「内容変更」ボタンを押す
5. 消したはずの「Ruby初級」が残ったままになっている

この日報は過去の日報をコピーして作ったものですが、新規で作った場合も一度プラクティスを選択すると削除できない。プラクティスの変更は可能。

## 期待される振る舞い

一度、日報の「プラクティス」を選択して「WIP」や「提出」ボタンを押した後でも、「プラクティス」を削除すると「プラクティス」が選択されていない状態で保存されて欲しい。

## スクリーンショット

https://user-images.githubusercontent.com/31835314/105795915-00bb2380-5fd1-11eb-9bfd-0ceef45969b9.mov

## 環境

 - OS: [MacOS]
 - ブラウザ: [chrome]
 - バージョン: [バージョン: 88.0.4324.96]

**Comment by komagata** [comment]
@siroemk バグ登録ありがとうございます！

**Comment by hisaotoriyama** [comment]
@Yu-kichi 
確認遅くなり失礼しました。週末に対応させてください。ごめんなさい

**Comment by Yu-kichi** [comment]
@hisaotoriyama 
いえいえ〜お忙しいところありがとうございます🙇‍♂️
