### ISSUE TITLE
ボウリングの旧ルール・新ルールという言葉・説明がわかりにくい

### ISSUE THREAD

**Issue by universato** [fjordllc/bootcamp#2279]
## 概要

ボウリングの「旧ルール」「新ルール」(特に「旧ルール」)という表記に違和感があり、わかりにくい。

この「旧ルール」とされるものは今現在も一般的なルールのはずで、
「旧ルール」という表記だと読み手に「今は使われていない」という印象を与えてしまい、事実と異なった印象を与える。
そして、「ボウリング 旧ルール スコア」などで検索しても、該当のルールはヒットしない。
問題説明にあたって、ミスリードな言葉を使っている。

また、「新ルール」とされるカレントフレームスコア計算は、確かに新しいだろうが、一部の世界大会で採用されているに過ぎず、まだ一般的ではなく、新しくできた特殊なルールという立ち位置に収まっており、旧ルールとの対比で持ち出すには違和感がある。

その他、｢旧ルール｣と｢新ルール｣とあったときに、旧ルールの方を計算させることに不思議な感じがある。

[英語版のWikipediaのボウリングの説明](https://en.wikipedia.org/wiki/Ten-pin_bowling#Scoring)でも、Traditional scoringとThe World Bowling scoring system(current frame scoring)という対比で説明している。なお、日本語版には、まだカレントフレームスコアシステムの説明はなかった。このことからも、カレントフレームスコアシステムは、まだ一般的でないことが伺える。

## 期待

「旧ルール」という表記は、「従来型のルール」「従来ルール」「従来の一般的なルール」「一般的なルール」などに置きかえるべき、と考える。

また、従来式とカレントフレームスコア式の立ち位置や背景の説明が簡単にあると嬉しいように思えた。

## スクリーンショット

[![Image from Gyazo](https://i.gyazo.com/f93eb78638c126cfe0e1ca2cf1c6996f.png)](https://gyazo.com/f93eb78638c126cfe0e1ca2cf1c6996f)

「基本的には、一般的なボウリングのルールをベースにします」という表現も、スコア計算の例外はなさそうで、ひっかかる。
「ルール及びスコア計算は、新しいカレントフレームスコアシステムではなく、従来の一般的なものとします」あたりだと考える。

## 関連URL

[ボウリングのスコア計算プログラム](https://bootcamp.fjord.jp/practices/210)
[ボウリングのスコア計算プログラムオブジェクト指向版](https://bootcamp.fjord.jp/practices/215)
[ボウリングのスコア計算（カレントフレームシステム)](https://bootcamp.fjord.jp/pages/249)

**Comment by universato** [comment]
タグの使い分けがよくわかっていないので、自分がタグを決めることでもないかと思い、いったん外しました。

**Comment by obregonia1** [comment]
自分もプラクティスに取り組むときに少し戸惑ったので、変更した方が分かりやすいと思います！
