### ISSUE TITLE
担当していないのに自分の担当タブが表示される

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2284]
![image](https://user-images.githubusercontent.com/16577/106227534-b3d38900-622c-11eb-8ecd-224eeb12272a.png)

Ref: https://fjord.slack.com/archives/GTK0NEH37/p1611883100058300

**Comment by machida** [comment]
@gallardo16 (cc @hogucc )

担当が0なのに「2」という数字が出てるので、これを修正していただきたいです。

<img width="262" alt="貼り付けた画像_2021_02_02_11_55" src="https://user-images.githubusercontent.com/168265/106545874-81d46680-654d-11eb-95ac-849488babb40.png">

0 の場合でも全部表示でお願いしたいです↓

- 0 の場合も数字は出し、タブも表示されるようにしたいです。
- 0 の場合は目立たない見た目にしたいのですが、そこは僕のほうで対応します。

**Comment by komagata** [comment]
@gallardo16 このコメントの流れだと問題が解決してないのにCloseされているように見えるので、もしGitHub以外（口頭やSlackなど）で問題が解決していたらこちらにその流れを書いていただければありがたいです〜。
（「修正お願いします」「了解しました」みたいなコメントがないのでわからなくなっているかも？）

例：

:memo: ミーティングでやりとりしてやらないことになった。

**Comment by gallardo16** [comment]
@komagata 
すみません、流れを書いておきます。

**Comment by gallardo16** [comment]
このissueの経過報告
- バグを修正したので完成にしました。
- 「0 の場合は目立たない見た目にしたい」というデザインは別issueで対応。
