### ISSUE TITLE
Q&Aのコメント欄からメンションを送ると通知されない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2285]
## 概要
Q&Aのコメント欄からメンションを送っても通知されない。（メール、Web画面上の通知欄とも）

## 再現手順

1. https://bootcamp.fjord.jp/questions/636 にアクセス。
2. コメント欄で特定のユーザーにメンションを送る
3. 待てど暮らせど通知が届かない

## 期待される振る舞い

メンションされたユーザーに通知が届く

## スクリーンショット

Slack上のやりとりです。

<img width="436" alt="Screen Shot 2021-01-30 at 17 54 14" src="https://user-images.githubusercontent.com/1148320/106352133-34c17c00-6324-11eb-8bb2-342b782968a4.png">

**Comment by ima1zumi** [comment]
ローカルで試したところ、Q&Aのクエスチョンでも通知されませんでした。

**Comment by JunichiIto** [comment]
これ、Closeでいいと思います！というわけでクローズ！（ガラガラ〜）

**Comment by SeijiNumata** [comment]
ありがとうございます！

**Comment by ima1zumi** [comment]
間違えました🙇‍♂️
