### ISSUE TITLE
開発で簡単にログインできるやつの右の履歴選択欄が見えない

### ISSUE THREAD

**Issue by universato** [fjordllc/bootcamp#2287]
## 概要

開発で簡単にログインできる便利なAnyLoginの右のHistory(履歴?)が見えにくい。

[![Image from Gyazo](https://i.gyazo.com/63e5ff72d742fc5d56908ef0dfe49c50.png)](https://gyazo.com/63e5ff72d742fc5d56908ef0dfe49c50)

## 再現手順

1. 開発環境を立ち上げまず
2. 画面の左下の人のマークをクリックして、広げます

## 期待される振る舞い

右のHistoryの選択欄が真っ黒で見にくいです。
あるいは、komagataさんかmachidaさんのログインを必ず出して欲しいです

履歴が見えにくく存在を忘れてしまうことが問題というより、
開発にあたって権限の大きいアカウントで作業したいときに、
左の「Select User」で権限の大きいアカウントがすぐにでないのが少々面倒に思っています。

ランダムなのか何か原理があるのかわかりませんが、
「Select User」のアカウントに権限の大きいユーザーが表示されないのが不便です。
(権限の大きいユーザーと小さいユーザーの両方があって欲しい)

## 環境

 - OS: Mac
 - ブラウザ: Chrome, Chrome

## 備考

その他のログイン方法

1 パスワード testtestでも普通の方法でログインできる
  ログアウトが必要になったりして、少し面倒。
https://github.com/fjordllc/bootcamp/blob/eb9869986e4494c3e1e05c77828586732c778ff4/test/fixtures/users.yml#L4

2  URLからユーザーIDを確かめて、ユーザーID指定の入力でもログインできる。

**Comment by komagata** [comment]
@universato なるほど、右の方が見えづらいからよくわからない状態だったんですね（僕も）

**Comment by universato** [comment]
(9日ほど前に)変更してもらえたので、このIssueを閉じます > PR #2295
[![Image from Gyazo](https://i.gyazo.com/dc2f886ed83c211b397e5c8499eaae77.png)](https://gyazo.com/dc2f886ed83c211b397e5c8499eaae77)
