### ISSUE TITLE
GitHubの草が真っ黒

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2293]
## 概要

ダッシュボードページやプロフィールページに表示されるGitHubの草が真っ黒になっている。

<img width="483" alt="Screen Shot 2021-02-04 at 8 18 13" src="https://user-images.githubusercontent.com/1148320/106822039-ab160380-66c1-11eb-8096-4234526b67a5.png">

[GitHub API](https://www.githubstatus.com/history)の異常はなさそう。（2021-02-04 8:19時点）

<img width="1018" alt="Screen Shot 2021-02-04 at 8 19 45" src="https://user-images.githubusercontent.com/1148320/106822107-d3056700-66c1-11eb-8076-b5aa97245ff9.png">

## 再現手順

1. https://bootcamp.fjord.jp/ にアクセス。
2. GitHubの草が真っ黒になっている。

## 期待される振る舞い

GitHub上の活動状況が適切に可視化される

## スクリーンショット

上記参照

## 環境

 - OS: macOS 11.2
 - ブラウザ:　Chrome
 - バージョン: Version 88.0.4324.146 (Official Build) (x86_64)

**Comment by JunichiIto** [comment]
[僕のブログ](https://blog.jnito.com/)のサイドバーも真っ黒になっていたので、 https://grass-graph.moshimo.works/ の問題かも。

<img width="250" alt="Screen Shot 2021-02-04 at 9 02 05" src="https://user-images.githubusercontent.com/1148320/106825275-e3204500-66c7-11eb-8a13-2d7dee05daab.png">

**Comment by JunichiIto** [comment]
@machida  Twitterで原因を教えてもらいました〜。

https://twitter.com/a_know/status/1357191346583310342

**Comment by komagata** [comment]
去年のハロウィンでも同じ状態になりましたね。
