### ISSUE TITLE
unfollow したときに過去の Watch を外す

### ISSUE THREAD

**Issue by eatplaynap** [fjordllc/bootcamp#2297]
**何故この機能が必要なのか**

現在はユーザーのフォローを外しても、かつてフォローしていたときWatch中になっていた日報のWatchが外されないため、更新通知が届いています。フォローを外している以上、昔の日報の更新通知は必要ないと思います。

**機能の説明**

フォローを解除したら、それ以前に投稿されていた日報のWatch中も外す。
@JunichiIto さんよりSlackで、下記の実装の問題だとご説明いただきました。
https://github.com/fjordllc/bootcamp/pull/2015/files#diff-5e34c70e5e7565d22fa7abf9dabef9ba3e6e0f6f49db4b606fdcf4fb413d8673R18
https://github.com/fjordllc/bootcamp/pull/2015/files#diff-5e34c70e5e7565d22fa7abf9dabef9ba3e6e0f6f49db4b606fdcf4fb413d8673R52

**Comment by JunichiIto** [comment]
issueの登録ありがとうございます〜。

この件ですが、実は現状の実装では対応が難しいのでは？と思っています。

というのも「フォローを解除したら、それ以前に投稿されていた日報のWatch中も外す」という動きだと、外してほしくないWatch中まで外してしまうかもしれないからです。

外してほしくないWatch中としては、日報上でコメントのやりとりをしている（自分もコメント投稿者になっている）ケースです。
この場合はフォロー解除時にWatch中が外れると、新しい返信コメントが入っても通知されない恐れがあります。

また、あまり活用されていないかもしれませんが、画面上からWatch中を選択する場合もあります。
フォローを開始する前にすでに明示的にWatch中にしていた場合は、「それはフォローを開始する前からWatchしてたんだから、勝手にUnwatchしないで！」というユーザーが出てくるかもしれません。

・・・といった様々なユースケースを考慮し、複雑な処理を実装していくよりも、プログラムは現状のままにしておいて、「フォローを解除しても以前の日報はWatch中のままです。過去の日報の通知が不要な場合はその日報をUnwatchしてください」と周知する方が個人的にはいいんじゃないかな〜と思っています。

**Comment by eatplaynap** [comment]
> 「フォローを解除しても以前の日報はWatch中のままです。過去の日報の通知が不要な場合はその日報をUnwatchしてください」と周知する方が個人的にはいいんじゃないかな〜と思っています。

確かに、原因が分からずに通知が来てたのが個人的に不可解だったので、原因が周知されていれば通知が来ること自体には害がないですね(興味がなければ見ないor Watchを取り消す)。
