### ISSUE TITLE
リアクション絵文字で不要な :-1: を消す

### ISSUE THREAD

**Issue by u1tnk** [fjordllc/bootcamp#2303]
**何故この機能が必要なのか**

![image](https://user-images.githubusercontent.com/279240/107049313-4a93dd00-680d-11eb-8016-b722b6aa567d.png)

👎 と:+1: が隣あっていて形も似ており、間違って 👎 を押してしまう事があるが、bootcampに 👎 を押す事はほぼ無いのに、間違ったときに相手に与える印象が違い過ぎていて怖い為。

**機能の説明**

使わない 👎 を消す。もしくは押せないようにする。もしくは間違えないように 👍 と離せれば良いです。
😄 の右の顔も消して良さそうです。

**Comment by universato** [comment]
https://github.com/fjordllc/bootcamp/issues/2214 滅多に使わないネガティブなリアクションを消す
こちらでも同様のIssueがあがっていますが、使われておらず誤って押したくない絵文字は不要だろうと自分も思っています。

**Comment by u1tnk** [comment]
@universato 

おお、絵文字とかで検索したんですが、見つからなかったです。
ご指摘ありがとうございます。 closeします。
