### ISSUE TITLE
moment.jsで書かれた処理を day.jsに置き換える

### ISSUE THREAD

**Issue by MashioSano** [fjordllc/bootcamp#2306]
moment.jsはメンテナンスモードに入り、代替ライブラリへの移行を推奨しているため
https://mag.osdn.jp/20/09/18/113400

**Comment by komagata** [comment]
@MashioSano Issue作成ありがとうございます。

**Comment by machida** [comment]
@MashioSano おおー、ありがとうございます！これ使ってる他のプロジェクトにも教えてあげよう

**Comment by misosoup160** [comment]
本番環境確認しました。
