### ISSUE TITLE
/notifications の未読のタブが空だった場合に、未読の通知はありません、と表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2312]

**Comment by MashioSano** [comment]
@machida  @Yu-kichi 
すいません。
僕が作成したPRで、/notifications の未読のタブが空だった場合に、未読の通知はありませんと表示されるように実装したのですが、こちらのIssueの内容と同じような気がしたのでコメントしました。
https://github.com/fjordllc/bootcamp/pull/2260
![スクリーンショット 2021-02-10 16 22 02](https://user-images.githubusercontent.com/52710925/107478011-1d07b480-6bbc-11eb-82a5-ee3f4d623d52.png)
お手隙の際に確認していただけると助かりますー。


該当するコード
https://github.com/fjordllc/bootcamp/blob/notifications-vue/app/javascript/notifications.vue#L65

**Comment by machida** [comment]
@MashioSano おおー、すいません、かぶらせてしまってました！！連絡ありがとうございます！助かりました！！

**Comment by machida** [comment]
@Yu-kichi @MashioSano すいません、Issueをかぶらせてしまったので、こちらは close しますー
