### ISSUE TITLE
メニューから書籍一覧を削除

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2320]
オフィス閉鎖で本の貸し出しがなくなったため、削除

<img width="328" alt="貼り付けた画像_2021_02_10_22_50" src="https://user-images.githubusercontent.com/168265/107518511-6e329b00-6bf2-11eb-9006-21d9e8f789bb.png">

**Comment by komagata** [comment]
@machida issue作成ありがとうございます！
