### ISSUE TITLE
AdminのナビゲーションからWishlistを削除

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2322]
ミートアップがオンラインになったため、スポンサー企業からのビールの提供が不要になったので削除

<img width="259" alt="貼り付けた画像_2021_02_10_22_56" src="https://user-images.githubusercontent.com/168265/107519156-41cb4e80-6bf3-11eb-8320-0de7820456af.png">

**Comment by komagata** [comment]
@SeijiNumata こちら完了していたらIssueのクローズもお願いします〜（僕がCloseしておきます〜）

**Comment by SeijiNumata** [comment]
@komagata 
承知しました。完了したら次からクローズさせます。
ありがとうございます。
