### ISSUE TITLE
キャプチャのショートカットの誤り訂正

### ISSUE THREAD

**Issue by tommy1038** [fjordllc/bootcamp#2327]
## 概要
[日報、wiki、提出物、コメントにキャプチャを貼る方法](https://bootcamp.fjord.jp/pages/23)にて、部分的なキャプチャの貼り方のショートカットが違うように感じました。

## 期待される振る舞い
現状: `shift` + `control` + `command` + `space` + `4`
改善案: `shift` + `control` + `command` + `4`

### 現状のサイトの表記
![image](https://user-images.githubusercontent.com/19229241/107601453-23546a00-6c6a-11eb-88e6-cc91a90344ca.png)

### Macデフォルトのショートカット
![image](https://user-images.githubusercontent.com/19229241/107601751-e63ca780-6c6a-11eb-9782-140423911bd2.png)

## 関連Issue

Ref: #関連Issue番号

## 環境
- OS: macOS Catalina
- ブラウザ: Chrome
- バージョン: 88.0.4324.146（Official Build） （x86_64）

**Comment by komagata** [comment]
@tommy1038 ご指摘ありがとうございます！該当部分を修正しました〜
