### ISSUE TITLE
「このタグを自分に追加」ボタンに謎のアニメーションが発生する

### ISSUE THREAD

**Issue by universato** [fjordllc/bootcamp#2334]
## 概要

本番環境のChromeで、「このタグを自分に追加」ボタンに2回に1回大きくなる謎のアニメーションがつく。
(アニメーションという言葉が適切か、そのあたり詳しくない)

## 再現手順

1. 本番環境のChromeで、/users/tags/モバイルにアクセス

2. 「モバイル」タグをクリック。(2回に1回ぐらいで大きくなる)

 [![Image from Gyazo](https://i.gyazo.com/35976e3e4deaf6ffb266741c4df18c99.gif)](https://gyazo.com/35976e3e4deaf6ffb266741c4df18c99)
(追記: よく見ると追加ボタン以外のタグの部分も同じ現象が発生していた)

## 期待される振る舞い

自分がいれた暫定のデザインのままの状態であり、
不自然なアニメーションがつくことがあるので、
デザインが入った上で、(静的にせよ動的にせよ)常に同じような振る舞いであって欲しい。

## 環境

- OS: macOS Catalina 
- ブラウザ: Chrome (Firefoxや開発環境だと再現せず)

## 関連PR

PR #2304

## その他・参考

お知らせのページでも、開発環境と本番環境で、デザインが異なっている。
本番環境では問題ないが、開発環境の方でアイコンが枠線を下にはみ出してしまっている。

[![Image from Gyazo](https://i.gyazo.com/b38a0d574d535ed3a04d79ddd74170b7.png)](https://gyazo.com/b38a0d574d535ed3a04d79ddd74170b7)

**Comment by machida** [comment]
@universato Issueありがとうございます！原因を調査します！！

**Comment by mh-mobile** [comment]
少し調べたメモ。


Google Chrome Toolsでアニメーションの計測を実施したところ、初期ロード時にアニメーションのトランジションが発生する。
![image](https://user-images.githubusercontent.com/13811034/109513840-d89b7480-7ae8-11eb-936c-6972377b92f7.png)

application.cssの読み込み処理を 以下のスクリプトよりも上にもっていくことで、アニメーションのトランジションが発生しなくなった。

```
<script>
  var currentUser = ...
</script>
<script>
  var availableEmojis = ...
</script>
<script>
  var stripePublicKey = ...
</script>
```


![image](https://user-images.githubusercontent.com/13811034/109514599-8b6bd280-7ae9-11eb-8517-809541a82a06.png)


cssの読み込みの順番が初期レンダリングに影響しているのかもしれない。

**Comment by mh-mobile** [comment]
たぶん、FCP(First Contentful Paint)とかその辺が関係してそう

**Comment by universato** [comment]
現在、タグそのものにアニメーションは生じているものの、1番目立っていた「このタグを自分に追加」ボタンは、デザインの変更とともに、アニメーションがでないように解決済みなで、自分から見て今は気にならないのでこのIssue自体を閉じてもいいのかな、とも考えています。
mhさんが書いてるような根本的な部分での解決はしてなさそうですが。
