### ISSUE TITLE
Q&Aページの回答の表示がワンテンポ遅い

### ISSUE THREAD

**Issue by kotakanazawa** [fjordllc/bootcamp#2346]
## 概要

- Q&Aページの回答がワンテンポ遅れて表示される

## 再現手順

- https://bootcamp.fjord.jp/questions/807 にアクセス
- 回答が遅れて表示される

https://bootcamp.fjord.jp/questions/808 など、Q&Aの本文が短い場合はコメント表示の遅さが顕著になる。

## 期待される振る舞い

コメントが遅れることなく表示される。

## スクリーンショット

![Kapture 2021-02-13 at 10 20 07](https://user-images.githubusercontent.com/28076271/107837908-8f5bdd00-6de6-11eb-8445-28c2dc0d0ba2.gif)

## 環境

 - OS: macOS
 - ブラウザ: chrome 
 - バージョン: 88.0.4324.150（Official Build） （x86_64）

## 備考

- お知らせページのコメントも同様にワンテンポ遅れて表示されるかもしれない
    - https://bootcamp.fjord.jp/announcements/401
- Wi-Fi回線、下り250mbpsでアクセスしているのでインターネット速度の遅さ以外の原因が考えられる

**Comment by universato** [comment]
> お知らせページのコメントも同様にワンテンポ遅れて表示されるかもしれない

日報のコメントも同様に遅れて表示されるので、コメント全体の現象みたいですね。

**Comment by kakutani** [comment]
本文と読み込みのタイミングが異なるのかなあ。lazy load的なことをしているのなら、表示されるまでの間のplaceholderがあるとよさそう。
