### ISSUE TITLE
ドットのあるタグをクリックすると、エラー等になる

### ISSUE THREAD

**Issue by universato** [fjordllc/bootcamp#2350]
## 概要

`Vue.js`等のドット記号が使われているタグをクリックすると、エラー等になる

## 再現手順

1. Q&Aで「Vue.js」のようにドット記号のあるタグをクリックする。
  (Q&A以外のユーザータグ等でも同じことが起こる模様)
2. 謎のページが表示されるか、Routing Errorになる。
  (途中にドットがあると謎のページが表示され、ドット始まりのタグだとRouting Errorとなるようです)

 [![Image from Gyazo](https://i.gyazo.com/aca8789df5069744df24631459588f10.gif)](https://gyazo.com/aca8789df5069744df24631459588f10)

## 期待される振る舞い

ドットのあるタグでも、ドットのないタグと同じような振る舞いをすることが期待される。

## 環境

 - OS: macOS
 - ブラウザ: Chrome

**Comment by komagata** [comment]
@universato Issue登録ありがとうございます。

**Comment by hituzi-no-sippo** [comment]
日報のコピペです。

**Comment by hituzi-no-sippo** [comment]
@komagata
次の表のように実装する方針でいます。確認お願いします 🙏 

| tag名                           | 修正方法   | 修正前のクリック時の動作
| ----------------------------------- | ---------- | ---------------
|ドットのみ                           | `.` を生成できるのがおかしいので、 `.` を生成できないようにする | `params` が正常に作動せず、 `UserController#index` ではなく、 `UserController#show` が動作する。
|先頭と最後がドット、ドットが2つ以上  | [routeに `constraints` option](https://railsguides.jp/routing.html#%E3%82%BB%E3%82%B0%E3%83%A1%E3%83%B3%E3%83%88%E3%82%92%E5%88%B6%E9%99%90%E3%81%99%E3%82%8B)を設定して、ルーティングにマッチさせる。 | ルーティングにマッチせず `Routing Error` が発生
|メディアファイルの拡張子で終わる     | [routeに `format` option](https://railsdoc.com/routes#resource)でHTMLを返すように設定する | HTMLではなく拡張子のメディアファイルを返そうとし、そのメディアのテンプレートがないため `missing a template` が発生
|`.js` で終わる                       | [routeに `format` option](https://railsdoc.com/routes#resource)でHTMLを返すように設定する | HTMLではなく `js` ファイルを返すため `app/views/layouts/application.html.slim` を読みこんでいない `app/users/index.html.slim` がレスポンスと返される

現在と実装予定のコードのdiff

```diff
diff --git a/config/routes.rb b/config/routes.rb
index 851cbe05..73ba5e15 100644
--- a/config/routes.rb
+++ b/config/routes.rb
@@ -164,13 +164,13 @@ Rails.application.routes.draw do

   resources :generations, only: %i(show index)

-  get "articles/tags/:tag", to: "articles#index", as: :tag
-  get "pages/tags/:tag", to: "pages#index", as: :pages_tag
-  get "questions/tags/:tag", to: "questions#index", as: :questions_tag
-  get "users/tags/:tag", to: "users#index", as: :users_tag
+  get "articles/tags/:tag", to: "articles#index", as: :tag, tag: /[^\/]+/, format: 'html'
+  get "pages/tags/:tag", to: "pages#index", as: :pages_tag, tag: /[^\/]+/, format: 'html'
+  get "questions/tags/:tag", to: "questions#index", as: :questions_tag, tag: /[^\/]+/, format: 'html'
+  get "users/tags/:tag", to: "users#index", as: :users_tag, tag: /[^\/]+/, format: 'html'

   namespace :users do
-    post "tags/:tag", to: "tags#update"
+    post "tags/:tag", to: "tags#update", tag: /[^\/]+/
   end

   get "login" => "user_sessions#new", as: :login
```

前述した表の実装でOKの場合、2点質問があります。

* `.` のタグを生成しないようする際、一緒にASCII文字1文字(e.g. `a`, `%`)だけのタグも生成できないようにしたほうがいいですか?
* `post "tags/:tag", to: "tags#update", tag: /[^\/]+/` ですが`tags#update` は `redirect` するので `format` optionを追加する必要がないと考えていますが、 `format: 'html'` 追加したほうがいいですか?

## 補足

API(`/api/tags`)はドットのタグが含まれても動作に関係ありませんでした。

**Comment by komagata** [comment]
> 前述した表の実装でOKの場合、3点質問があります。

> ドットのみ
> 先頭と最後がドット、ドットが2つ以上

ありがとうございます。こちらの二つは表に書いてある通りの対応でお願いします。

> メディアファイルの拡張子で終わる
> .js で終わる

こちらの二つは対応しなくて大丈夫です。

> . のタグを生成しないようにタグ名をバリデートするのですが、一緒にASCII文字1文字(e.g. a, %)だけのタグも生成できないようにしたほうがいいですか?

不要です〜

> タグ名のバリデートですが、VueのFormかRailsのmodelどちらで実装したほうがいいですか?

必要：modelでのvalidation、できたら嬉しい：VueのFormでのvalidation

って感じでお願いします〜

> post "tags/:tag", to: "tags#update", tag: /.+/ ですがtags#update は redirect するので format optionを追加する必要がないと考えていますが、 format: 'html' 追加したほうがいいですか?

不要です〜

**Comment by hituzi-no-sippo** [comment]
了解です 👍 

* メディアファイルの拡張子で終わる
* `.js` で終わる

は今回調べた内容と一緒にbugのissueとして作成しておきます。
