### ISSUE TITLE
お知らせのAPI（CRUD）が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2378]
「GitHubと連携して次週のリリースノートを作成する」などがやりたい。

**Comment by tam-03** [comment]
@komagata 
こちらのissueについてお聞きしたいです！🙇🏻‍♂️

## APIの仕様について

- APIを使うのは管理者のみと想定した方がが良いでしょうか？
- 「公開」「wipとして保存」が選べた方が良いでしょうか？

補足

`announcements`テーブルの`wip`カラムはデフォルトで`false`なので、リクエストに含めなければ「公開」となります。

## 現状のbootcamp内の「お知らせ」の仕様

※一般ユーザーの場合
|一覧|個別|作成|公開|更新(編集)|削除|
|-|-|-|-|-|-|
|○|○|○|✕|▲|▲|


- 公開は出来ない(メンションを送り確認してもらう)
- 更新と削除は「自分で作成したもの」のみ(現状はURL末尾に`/edit`で出来てしまいますが本来はこちらだと思います。)

**Comment by komagata** [comment]
@tam-03 基本的にはWeb上からできるのと権限は同じにしたいです。

Web上からできることも今とはちょっと変えたいですが、「公開」と「削除」以外は一般ユーザーでもできるようにしたいです。

**Comment by tam-03** [comment]
@komagata 
ありがとうございます！かしこまりました！🙇🏻‍♂️
