### ISSUE TITLE
右サイドバーのユーザータグをランダム表示に変更する

### ISSUE THREAD

**Issue by universato** [fjordllc/bootcamp#2380]
## 概要

ユーザー一覧の右サイドバーのタグが、
紐付けが多い順(人気順)になっているが、
この順番は変動することが少なく面白みがないと思われるので、
右サイドバーのタグをランダム表示させる。

## 参考： 現在の右サイドバーのタグ一覧

[![Image from Gyazo](https://i.gyazo.com/0f2f05ae82c147c025468370dc7e8106.png)](https://gyazo.com/0f2f05ae82c147c025468370dc7e8106)

## 備考

いまの人気のタグ一覧は、別ページを用意するのがよさそう。

**Comment by machida** [comment]
ランダム表示にして、その部分の見出しの文言などは変えたいと思いますー

**Comment by machida** [comment]
15人以上のタグは目立つようにする、など入れたいですねー

**Comment by misosoup160** [comment]
一度町田さんと相談して現在考えている実装
- 右のサイドバーのタグはランダムに表示する
- 全てのタグを表示する新しいページをつくる
    - ここは人気順にする
    - 期生別ユーザーページのようなデザイン
- 登録者が多い１〜３位には特別にクラスをふって表示を変えたい
- 人数を３段回くらいに分けてそれぞれクラスをふって表示を変えたい

**Comment by misosoup160** [comment]
今気になっているところは、
- １〜３位は上から３個のタグにするか、同数を考慮しないで３個以上になってもよいか
- 人数を３段階に分けるのをどうするか
    - 一番多い人数を３で割ってふる？
    - 今なら10人以上と3人以下とそれ以外くらいとかもいいかな？と思うけど数字を固定するのはどうか？
    - あと、上位３位とかぶってくるけど、デザイン的にどういう違いになるのか私があまり想像できていない…

- タグ一覧ページをどこにつくるのか？（別issueになりました）
    - users/tagsになると思いますが、サイドバーの一番下のリンクから飛べるだけでいい？
    - 期生別一覧のとなりにタブを並べるのは変ですよね？

こんな感じです。他にもご意見ありましたらお願いします🙏

**Comment by misosoup160** [comment]
@machida 
こちらのPRで後で変えようと思っていたところなんですが、もしデザインの方を別のPRで編集するなら、そこで同時に`app/views/users/_popular_tags.html.slim`のファイル名を`app/views/users/_random_tags.html.slim`に変更できたらいいんじゃないかと思っています。どうでしょうか。

**Comment by machida** [comment]
@misosoup160 そうですね、名前も変えた方が良さそうですねー。こちら対応しておきますー

**Comment by misosoup160** [comment]
@machida ありがとうございます。よろしくお願いします🙏😭

**Comment by misosoup160** [comment]
本番環境動作確認しました。
