### ISSUE TITLE
ログインしているとランディングページが見られない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2384]
ログイン中は https://bootcamp.fjord.jp/ にアクセスするとダッシュボードが表示されるため、非メンバー向けのトップページ（ランディングページ）が見られない。

たまに非メンバー向けの情報を確認したくなるときがあるが、毎回シークレットウインドウで開き直さなければいけないので面倒。

URL設計を見直して、それぞれのURLを独立させた方がいいのではないか？

例

- https://bootcamp.fjord.jp/ = 非会員向けのトップページ
- https://bootcamp.fjord.jp/dashboard = 会員向けのダッシュボード

**Comment by ima1zumi** [comment]
https://bootcamp.fjord.jp/welcome でアクセスできます！

**Comment by JunichiIto** [comment]
@ima1zumi なるほど〜。なんかそういうURLがありそうだな〜と思ってたんですが、やっぱりありましたかw
とはいえ、今のままだと気づきにくいですね〜。
