### ISSUE TITLE
[メンター向け機能]メンターがコメントすると自動で担当になるようにしたい

### ISSUE THREAD

**Issue by u1tnk** [fjordllc/bootcamp#2385]
**何故この機能が必要なのか**

現在のメンターの提出物の担当機能は一覧からメンターがボタンを押す必要があるが、押さずにコメントできてしまうので実質担当しているのに未担当になってしまう事があり、実質と乖離ができて分かりづらくなっている。

**機能の説明**

メンターが未担当の提出物にコメントすると自動で担当になる。

**Comment by komagata** [comment]
確かに、僕も思いました🤭
