### ISSUE TITLE
WIPのお知らせが通知される

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2389]
https://bootcamp.fjord.jp/announcements/411 はWIPだが通知が上がってきている。（仕様？バグ？）
<img width="372" alt="Screen Shot 2021-02-26 at 19 15 22" src="https://user-images.githubusercontent.com/1148320/109287658-37ea5200-7867-11eb-95f3-47bdf55eca70.png">

<img width="710" alt="Screen Shot 2021-02-26 at 19 15 40" src="https://user-images.githubusercontent.com/1148320/109287615-2b65f980-7867-11eb-85d7-1cb662477f5e.png">

**Comment by machida** [comment]
@JunichiIto Issueありがとうございます🙏

@komagata 今日の雑談タイムでも話題になってたのですが、公開してみんなに通知が飛んだ後に WIP にしたからなのか、WIP でも通知が飛んでしまっているのか確認をお願いしたいです🙏

**Comment by komagata** [comment]
@JunichiIto @machida 公開した後にWIPにしたので、通知が飛んでること自体は問題ないと思います〜。
