### ISSUE TITLE
[メンター向け]提出物の方の「確認OKにする」ボタンに警告を出して欲しい

### ISSUE THREAD

**Issue by u1tnk** [fjordllc/bootcamp#2397]
**何故この機能が必要なのか**

この「確認OKにする」ボタンが、日報だとほぼこちらしか使わない為問題無いが、提出物だと基本的にコメントのみなので、日報確認した後に提出物を見ると間違って押してしまう事があります。
![image](https://user-images.githubusercontent.com/279240/109465946-4d03f280-7aac-11eb-9bbb-d4292261a3d4.png)

**機能の説明**

この機能自体は便利なので、間違って押す事を防げれば良く、頻度の低さから多少面倒になっても良いので、個人的にはJavaScriptのポップアップで「確認OKにして良いですか？」と出すだけで良いと思います。

**Comment by komagata** [comment]
僕結構頻度高いのでポップアップ出るとちょっと使いづらいかも？

**Comment by u1tnk** [comment]
なるほど…  そうなると、一回確認しても戻せるし、担当されている生徒さんは確実に分かるので、そのままでも良いかもしれません。

**Comment by komagata** [comment]
@u1tnk  やっぱり生徒の方の体験の方が大事なので僕らがちょっと面倒でもポップアップ出る方がいいのかな〜と考え直しております。
