### ISSUE TITLE
身分証明書画像をアップする機能

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#240]
自分の身分証明書画像をプロフィールからアップできる。

管理者しか見えないようにする。
（基本、何かあったときのために保存しておくだけなので）

**Comment by machida** [comment]
@komagata 

これ、運用的には

身分証明書画像を渡してもらう（これでNDAを結んだことになる）
↓
bootcampにサインアップ

と、サインアップ前に提出してもらうことになるので、

- サインアップ時に身分証明書画像を要求される？
- 企業の場合（研修、アドバイザーなど）はなしにする必要がありそう
- 画像の確認が必要そう

など、ちょっと仕様を詰める必要がありそうですね。

**Comment by komagata** [comment]
@machida 現状の手動運用でも身分証明書はサインアップ後（プラクティスになっている）ので、とりあえずそこを置き換えるだけじゃだめですかね。

- アカウント修正画面で画像をアップできる。（必須ではない）
- 今までどおりプラクティスとして、生徒には画像を登録してもらう。

のような感じで。

**Comment by machida** [comment]
@komagata 

なるほど、大きい会社も利用するので、まずはそこの運用を変更したいですね。
NDAを結んだあとにサインアップができるようにしたいです。

それをシステムに落とし込むと、

1. サインアップ申請
1. adminが申請を受諾
1. サインアップ

のフローになってしまうのと、企業に所属しているユーザーの場合はそれが不要になるので複雑になってしまいますね。。。

ただ、欲を言えばサインアップ申請時に

- アンチハラスメントポリシーに同意
- 就職紹介を必ず利用することへの同意
- 辞めるときは退会処理を行うことへの同意

などもはさみたいなー、とは思います。
サインアップについてはもう少し詰めたいと思います。
