### ISSUE TITLE
提出物一覧の未返信タブを担当なしタブに変更する + サイドバーには「担当なし」件数を表示する

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2407]
**何故この機能が必要なのか**

もともと、メンターはメンターからのコメントの有無で担当者のありなしを判断していた。
その場合はコメント未返信≒担当者無しという関係が成り立っていた。

しかし、提出物一覧に「担当する」ボタンができてからは担当者のあり・なしを明確に識別できるようになった。
よって、コメントの有無を管理する必要はなくなり、かわりに担当者のあり・なしを管理する必要が出てきた。

この改善が実現すれば、「7日以内に提出物をレビューする」というSLAをメンターがより効率的にチェックしやすくなる。

**機能の説明**

- 未返信タブを廃止し、担当者なしタブを新設する
- 担当者なしタブの内容は以下のとおり。
  - 担当者が決まっていない、かつ確認OKになっていない提出物を一覧表示する
  - 表示順は提出日の昇順（古いものほど上、新しいものほど下）で表示
  - ページング不要（多くても70〜80件程度と思われるため）
- サイドバーに表示されている提出物のアラート件数も未返信の件数ではなく、担当者なしの件数を表示する

<img width="80" alt="Screen Shot 2021-03-03 at 8 56 32" src="https://user-images.githubusercontent.com/1148320/109731322-5ef5aa80-7bfe-11eb-95bb-ffe6dc730662.png">

- 担当者なしタブには提出日からの経過日数ごとに区切りを入れる

表示例＝今日が3/3の場合

```
（7日以上経過）=========
- lsコマンドの提出物（提出日 2/23）
- wcコマンドの提出物（提出日 2/24）
（6日経過）=========
- rbenvの提出物（提出日 2/25）
- ボウリングプログラムの提出物（提出日 2/25）
- FizzBuzzの提出物（提出日 2/25）
（5日経過）=========
- カレンダープログラムの提出物（提出日 2/26）
- lsコマンド提出物（提出日 2/26）
- wcコマンドの提出物（提出日 2/26）
- ユーザーフォローの提出物（提出日 2/26）
（4日以下）=========
- wcコマンドの提出物（提出日 2/27）
- ボウリングプログラムの提出物（提出日 2/27）
・
・
・
- CSS上級の提出物（提出日 3/3）
- FizzBuzzの提出物（提出日 3/3）
```

- 該当するグループがなければ区切りも表示しない

表示例＝6日経過の提出物がない場合

```
（7日以上経過）=========
- lsコマンドの提出物（提出日 2/23）
- wcコマンドの提出物（提出日 2/24）
（5日経過）=========
- カレンダープログラムの提出物（提出日 2/26）
- lsコマンド提出物（提出日 2/26）
- wcコマンドの提出物（提出日 2/26）
- ユーザーフォローの提出物（提出日 2/26）
```

**関連issue**

- [未返信の提出物一覧に日付ごとの区切り線を入れた by gallardo16 · Pull Request \#2367 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/2367)
- [【要調査】提出物一覧の提出日が実際の提出日になっていない（かも） · Issue \#2398 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/2398)
- [提出物一覧をVue\.jsで非同期にした by hogucc · Pull Request \#2280 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/2280)

**Comment by JunichiIto** [comment]
@u1tnk 完全にかぶってた💦
https://github.com/fjordllc/bootcamp/issues/2283

**Comment by JunichiIto** [comment]
https://github.com/fjordllc/bootcamp/issues/2005 ともかぶってた 💦 
全メンターが熱望してる機能ということみたいですね〜。

**Comment by u1tnk** [comment]
@JunichiIto @betachelsea 
なるほど、僕が立てたのも closeして、 #2005に統一しましょうか 😅

**Comment by JunichiIto** [comment]
@u1tnk  OK。 #2005 に統一だ！
