### ISSUE TITLE
管理メニューの「ブログ記事作成」へリンクを消したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2411]
<img width="491" alt="スクリーンショット 2021-03-03 14 36 24" src="https://user-images.githubusercontent.com/16577/109757865-f7575380-7c2d-11eb-878e-caf3236ea2bc.png">

これ。

ブログ昨日は未リリースなので。

**Comment by komagata** [comment]
@SeijiNumata こちらリリース後、本番環境で動作確認して完了していたらIssueのクローズもお願いします〜（僕がCloseしておきます〜）

**Comment by SeijiNumata** [comment]
@komagata 
承知しました。完了したら次からクローズさせます。
ありがとうございます。
