### ISSUE TITLE
提出物ページの終了条件と提出物の境目がわかりづらい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2418]
提出物ページを開いたときに、終了条件と提出物の境目が識別しづらいため、提出物を確認する際に神経を使ってしまう。
もう少し視覚的に明確な違いを出してほしい。

https://bootcamp.fjord.jp/products/6803
<img width="300" alt="Screen Shot 2021-03-05 at 7 28 15" src="https://user-images.githubusercontent.com/1148320/110039824-259b7700-7d85-11eb-9aa5-f382799e008b.png">

**Comment by JunichiIto** [comment]
@komagata @machida これ、結構不便なので早めに対応してもらえると嬉しいです〜 🙏

**Comment by JunichiIto** [comment]
@komagata @machida 再度pushしますが、このissue、早めに対応してもらえると嬉しいです！！
提出物をレビューするとき、結構目を凝らさないといけないので。

**Comment by machida** [comment]
@JunichiIto すいません！こちら優先度上げます🙋‍♂️

**Comment by machida** [comment]
提出物のデザインを更新しました💪

**Comment by JunichiIto** [comment]
見やすくなりました！！どうもありがとうございます〜 🙏
