### ISSUE TITLE
ユーザー全員の顔絵文字が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2427]
`:@komagata:` などのようにユーザーのニックネームをコロンで挟んだ記法でユーザーのプロフィール画像が小さく表示されるようにしたい。

**Comment by machida** [comment]
@komagata メンター以外も含めて、リタイアユーザー以外全員の絵文字が補完されるようにするのはどうですかねー？

**Comment by komagata** [comment]
@machida 確かに、まだ実装方法考えてないですが、できたらそっちがいいですね！

**Comment by gozasoro** [comment]
本番環境で確認できたのでcloseします！

**Comment by komagata** [comment]
神機能きた～～～！
