### ISSUE TITLE
.js で終わるタグをクリックした際のページ表示がおかしい

### ISSUE THREAD

**Issue by hituzi-no-sippo** [fjordllc/bootcamp#2446]
## 概要

`.js` の拡張子で終わるタグ(e.g. `vue.js`)をクリックするとCSSが効いていないページが表示される。

## 再現手順

1. `vue.js` のように `.js` で終わるタグを生成
2. 生成したタグをクリック

## 期待される振る舞い

拡張子が `.js` ではない、他のタグと同じようにCSSが効いているページを表示する。

## 解決案

[routeに `format` option](https://railsdoc.com/routes#resource)でHTMLを返すように設定する。

#2447 と解決案は同じです。

### エラー原因

HTMLではなく `js` ファイルを返すため `app/views/layouts/application.html.slim` を読みこんでいない `app/users/index.html.slim` がレスポンスと返される

## スクリーンショット

![js_file](https://user-images.githubusercontent.com/43565959/111051935-2ecdc780-849a-11eb-8254-af715261607b.gif)

## 環境

- OS: Ubuntu 20.04 LTS(WSL2)
- commit: 2c8339919249b1bce1067be145f1c76911beb5af
- Ruby: v2.6.6
- Node: v12.2.0

## 関連Issue

#2350

**Comment by IkumaTadokoro** [comment]
本番環境で動作していることを確認したため、クローズします
