### ISSUE TITLE
メディアファイルの拡張子で終わるタグをクリックするとエラーが発生する

### ISSUE THREAD

**Issue by hituzi-no-sippo** [fjordllc/bootcamp#2447]
## 概要

メディアファイルの拡張子で終わるタグ(e.g. `test.mp4`, `test.jpeg`, `test.md`)をクリックするとエラーが発生する

## 再現手順

1. `test.mp4` のように メディアファイルの拡張子で終わるタグを生成
2. 生成したタグをクリック

## 期待される振る舞い

メディアファイルの拡張子で終わらない、他のタグと同じページを表示する。

## 解決案

[routeに `format` option](https://railsdoc.com/routes#resource)でHTMLを返すように設定する。

#2446  と解決案は同じです。

### エラー原因

HTMLではなく拡張子のメディアファイルを返そうとし、そのメディアのテンプレートがないため `missing a template` が発生

## スクリーンショット

![media_file](https://user-images.githubusercontent.com/43565959/111052136-d8618880-849b-11eb-8f7f-1c463027d37d.gif)

## 環境

- OS: Ubuntu 20.04 LTS(WSL2)
- commit: 2c8339919249b1bce1067be145f1c76911beb5af
- Ruby: v2.6.6
- Node: v12.2.0

## 関連Issue

#2350

**Comment by IkumaTadokoro** [comment]
本番環境で動作していることを確認したため、クローズします
