### ISSUE TITLE
プロフィール画像のファイルアップロードにおけるセキュリティ上の懸念

### ISSUE THREAD

**Issue by mh-mobile** [fjordllc/bootcamp#2456]
## 概要

アップロードしたプロフィール画像には、以下のようなプライバシーに関するセキュリティ上の懸念が存在する。

* 画像のファイル名がアップロードした画像のファイル名のまま表示される。
* 画像のExifやGPSなどのメタ情報がアップロードした画像に残ったままになっている。

※ ただし、メタ情報付きの画像でも、ファイルアップロード後にメタ情報が削除されているケースも確認した。（原因は不明）

## 再現手順

1. 登録情報変更画面を表示する。
2. ExifやGPSなどのメタ情報付きの画像をアップロードする
3. 自分のプロフィール画面を表示し、プロフィール画像をダウンロードする。
4. ダウンロードしたプロフィール画像をMacのプレビューなどを使ってメタ情報を確認する。

## 期待される振る舞い

* 画像のファイル名はランダムな文字列が望ましい。
→ 個人情報を含むファイル名をアップロードした場合、プライバシーが漏れる可能性がある。
→ ディレクトリトラバーサル攻撃や任意のスクリプトが実行される可能性がある。

* ExifやGPS情報は削除されることが望ましい。
→ 撮影した端末や撮影日、位置情報などのプライバシーが漏れる可能性がある。

参考：
* [アップロード時に画像ファイルの名前を変更するセキュリティ的な理由が知りたい](https://teratail.com/questions/83216)
* [  Rails セキュリティガイド - Railsガイド 4.2 ファイルアップロード](https://railsguides.jp/security.html#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%A2%E3%83%83%E3%83%97%E3%83%AD%E3%83%BC%E3%83%89)

#### プロフィール登録の部分
![image](https://user-images.githubusercontent.com/13811034/111151399-c0405500-85d2-11eb-8423-5677438ce266.png)

#### プロフィール画像のダウンロードURLに含まれるファイル名

test_image.jpgのプロフィール画像をアップロードした場合
※マルチバイト文字列が含まれる場合はエンコードされて表示される

![貼り付けた画像_2021_03_15_21_41](https://user-images.githubusercontent.com/13811034/111155218-858ceb80-85d7-11eb-83b0-cb01e28aca15.png)

#### 登録したプロフィールのメタ情報

メタ情報付きの画像をプロフィール画像としてアップロードし、アップロードされた画像をダウンロードしてメタ情報を表示したスクショになります。
画像のメタ情報は、[ExifTool by Phil Harvey](https://exiftool.org/)を使って加工しています。
![image](https://user-images.githubusercontent.com/13811034/111151460-d51ce880-85d2-11eb-9474-58f3ea0e62a6.png)

## 検証に使用したメタ情報付きの画像

![test_image](https://user-images.githubusercontent.com/13811034/111154823-fbdd1e00-85d6-11eb-850f-81e9375fa625.jpg)

※ GitHubにアップロードした画像はメタ情報が消えないことは確認済み

## 環境

 - OS: Mac
 - ブラウザ: Chrome
 - バージョン: 89.0.4389.82

## 関連Issue

なし

**Comment by komagata** [comment]
:memo: ミーティングでアップする時に画像のExif情報を削除することで対応するという話になりました。

**Comment by siroemk** [comment]
📝 ミーティングにて、画像のファイル名も変更するという話になりました。

**Comment by siroemk** [comment]
@komagata 
こちら本番環境に適用されたので動作確認したいです！

サインアップ時に登録したプロフィール画像のExif情報が削除されるか、確認したいのですが、本番環境でユーザーを作成してもよろしいでしょうか？

ちなみに既存のユーザーでのプロフィール画像変更は問題ありませんでした🙆‍♀️

**Comment by komagata** [comment]
@siroemk 本番だと課金されちゃうので、新しいユーザーが入ってきたらそのユーザーのデータで確認できればと思います〜

**Comment by siroemk** [comment]
@komagata 
かしこまりました！
リリース後に新しいユーザーが入っていましたので、そちらのプロフィール画像にて、Exif情報が削除されていることを確認しました🙆‍♀️

closeします〜！
