### ISSUE TITLE
提出物のコメントを読み込むときに時間がかかるので、現在ローディング中であるとわかるものを表示を出したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2465]

**Comment by Yu-kichi** [comment]
@machida
こちら念のために確認ですが、個人の提出物のページに表示させるということでよろしいでしょうか？

### 完成イメージのスクショ
<img width="1262" alt="Terminalの基礎を覚えるの提出物___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）_と_show_html_slim_—_bootcamp" src="https://user-images.githubusercontent.com/64201542/112720278-ac84df00-8f40-11eb-9d38-36f0d8c17a9b.png">

**Comment by komagata** [comment]
@Yu-kichi 提出物の個別ページであっていますが、ローディングを出すところが、本来コメントが出る場所にコメントがロードされるまで表示させてほしいという感じです。

（ローディング表示なのか、プレースフォルダを表示するのかといった部分はまだ悩みますが）CC: @machida

**Comment by Yu-kichi** [comment]
>本来コメントが出る場所にコメントがロードされるまで表示させてほしいという感じです。

回答ありがとうございます！😊
了解しました。とりあえずコメント欄が表示される場所にローディングが表示されるように作成したいと思います！

**Comment by Yu-kichi** [comment]
本番環境で確認できましたので、こちらクローズしますー！
