### ISSUE TITLE
質問とDocsのタグ追加時、Enterキーを押さずに保存するボタンを押した際、タグが追加されない

### ISSUE THREAD

**Issue by hituzi-no-sippo** [fjordllc/bootcamp#2474]
## 概要

タグを入力して、Enterキーを押さずに、保存するボタンをクリックするとタグが追加されません。
表示上では追加されたようにみえますが、ページを再読み込みすると入力したタグが表示されず、追加されてないことがわかります。

質問とDocsの詳細ページのタグ編集で発生し、ユーザーのタグ入力や質問とDocsの新規作成ページでは発生しません。

## 再現手順

1. 質問 or Docsの詳細ページに移動
2. タグ編集をクリック
3. 追加するタグを入力
   __入力し終わった後、Enterキーは押してはいけません__
4. "保存する" ボタンを押す
    入力したタグがタグ一覧に追加され、表示上はタグが追加されたように見えます。
5. ページを再読み込みするが、入力したタグが表示されない

## 期待される振る舞い

次の2通りあると考えています。

* タグが表示通り追加される。
* Enterキーを押さずに "保存する" ボタンを押した際、入力したタグがタグ一覧に追加されないようにする。

### 再現手順通り

![not_add](https://user-images.githubusercontent.com/43565959/111756903-1583ab80-88de-11eb-9207-ab441ff577fb.gif)

### 保存ボタンを2回押せば追加されます

![add](https://user-images.githubusercontent.com/43565959/111754692-a2793580-88db-11eb-93d2-c2ea988dcbc3.gif)

### Enterキーを入力したタグは追加されます

![aa_zz](https://user-images.githubusercontent.com/43565959/111756049-1e27b200-88dd-11eb-9c2a-f450eeafc2e9.gif)

### 削除はちゃんとできます

![delete](https://user-images.githubusercontent.com/43565959/111753525-4d88ef80-88da-11eb-9abd-63080e4a51ef.gif)

## 原因だと推測されるコード

推測で検証はしていません。

tag入力のコンポーネント

https://github.com/fjordllc/bootcamp/blob/0da9ebc3ec8b984bdd7c84c4ee5d8ea8c4b06118/app/javascript/question_tags.vue#L13-L20

Enterキーを入力すると

https://github.com/fjordllc/bootcamp/blob/0da9ebc3ec8b984bdd7c84c4ee5d8ea8c4b06118/app/javascript/question_tags.vue#L58-L61

が実行されて、 `this.tagsValue` が更新されます。

Enterキーを押さずに保存ボタンを押すと、 `update` が実行されず `this.tagsValue`  が更新されない状態で

https://github.com/fjordllc/bootcamp/blob/0da9ebc3ec8b984bdd7c84c4ee5d8ea8c4b06118/app/javascript/question_tags.vue#L85-L108

が実行されます。

更新される前のタグの値がREST APIの値になるため、DBに追加されません。

上のコードは質問用のタグのコードですが、Docsでも同じようなことをやっているので、同じ問題だと考えています。

## 環境

 - OS: Windows10
 - ブラウザ: Chrome
 - バージョン: 89.0.4389.90
 - commit: 31918a214a9eb36644b9a639f2377a0e40fc3f6a

## 関連Issue

関連しそうなキーワードを入力しても発見できませんでした。

**Comment by unstoppa61e** [comment]
@komagata
こちらの Issue を「いつかやる」もしくは「やる」に加えて頂けますでしょうか？
結構重要な気がします。
