### ISSUE TITLE
担当になるボタンを表示するページでサイズを選択できるようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2483]
メンターでログインしたとき、

提出物一覧、

<img width="851" alt="貼り付けた画像_2021_03_24_12_29" src="https://user-images.githubusercontent.com/168265/112250355-90f9aa00-8c9c-11eb-9459-7961b60057c6.png">

提出物個別、

<img width="896" alt="貼り付けた画像_2021_03_24_12_30" src="https://user-images.githubusercontent.com/168265/112250461-c1d9df00-8c9c-11eb-831a-b5a2538e9d23.png">

両方に担当になるボタンがありますが、機能は同じですが、サイズが違います。

現在、提出物個別のときに、サイズをCSSで無理やり大きくしています。
でも、その対応はやめたいです。

-----

提出物一覧のときのボタンは、`is-sm` というclassが付いています。

<img width="677" alt="貼り付けた画像_2021_03_24_12_33" src="https://user-images.githubusercontent.com/168265/112250680-2b59ed80-8c9d-11eb-8929-1f72e9b132de.png">

提出物個別のときも、`is-sm` というclassが付いていますが、この `is-sm` を `is-md` に変更すると、サイズをCSSで無理やり大きくする必要がなくなります。

<img width="609" alt="貼り付けた画像_2021_03_24_12_34" src="https://user-images.githubusercontent.com/168265/112250786-5e03e600-8c9d-11eb-99af-f44da654d0fb.png">

----

なので、

- 提出物一覧のときのボタンは、`is-sm` というclassが付く
- 提出物個別のときのボタンは、`is-md` というclassが付く

ようにしていただきたいです。

**Comment by komagata** [comment]
「リファクタリング」は**振る舞いを変えず**にコードの内部構造を変えることなので、この場合はリファクタリングと言わない方がいいかも？（会社で先輩によく指摘される点なので）

**Comment by SeijiNumata** [comment]
なるほど〜、確かにそうですね。
issueの名前を修正しました。

**Comment by machida** [comment]
@komagata @SeijiNumata すいません、僕がリファクタリングと付けてました。今回いじったファイルだけをみると振る舞いが変わるのですが、今回いじったファイル + css で考えると同じ振る舞いをするところから、リファクタリングと付けましたー。
