### ISSUE TITLE
Watch中一覧からページ遷移なくそれぞれをWatch解除したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2489]
<img width="1348" alt="貼り付けた画像_2021_06_04_11_08" src="https://user-images.githubusercontent.com/168265/120735465-a05f6400-c525-11eb-8f54-bdfff0a47a50.png">

**Comment by SeijiNumata** [comment]
@komagata 
開発方針について確認です。

大きく分けて、
①watch中一覧をvue.jsで非同期にする
②上のmachidaさんが貼っている画像のようなチェックマークを入れるとwatch中を外せる機能を作る

という流れであっていますでしょうか？

現在一覧ページがvueで作られていないため、②の機能(特に、watchを外すとページ遷移なく一覧から消える機能)をいきなり作るのは難しいと考えたのですが、確信が持てないので質問しました。

よろしくお願いします。

**Comment by machida** [comment]
@SeijiNumata @komagata 

すいません、伝え漏れがありました。この機能を追加するにあたって、watch一覧ページ自体のvue.js化も同時に行なっていただきたいと考えていましたー

**Comment by SeijiNumata** [comment]
@machida @komagata 
承知いたしました！

機能追加と、watch一覧ページ自体のvue.js化も同時に行ないます！
プルリク分けた方が良ければ教えてください〜！

よろしくお願いします！

**Comment by machida** [comment]
> プルリクは一緒で行おうと思っていますが大丈夫ですか？

はい！それで大丈夫です。もし、途中でレビューをしてもらいたいときは、作業中でも @komagata さんに声をかけていただければと思いますー

**Comment by SeijiNumata** [comment]
作業途中でも見ていただけるんですね！助かります！🙏
プルリクの件承知いたしました、ありがとうございます！

**Comment by machida** [comment]
確認しました。closeしますー
