### ISSUE TITLE
日報個別ページに担当になるボタンが出てしまっている（display: none で見えないが、在る）

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2493]
<img width="892" alt="貼り付けた画像_2021_03_26_11_39" src="https://user-images.githubusercontent.com/168265/112569802-31c8a080-8e28-11eb-84d5-365054330d5a.png">

<img width="835" alt="貼り付けた画像_2021_03_26_11_41" src="https://user-images.githubusercontent.com/168265/112569860-4d33ab80-8e28-11eb-9bf2-e33db4f8acae.png">

DOMから上記のliがなくなるのが理想です。

**Comment by hituzi-no-sippo** [comment]
自分が担当したissue(#2455 )が原因で、すぐ修正できそうなので自分がやっておきます～ 😄
