### ISSUE TITLE
`@mentor` の記載があるときに確認ダイアログを表示する

### ISSUE THREAD

**Issue by hituzi-no-sippo** [fjordllc/bootcamp#2505]
## 何故この機能が必要なのか

意図せず(コードに記載 見落とし) `@mentor` と記載し、メンター全員に通知を送信されるのを防ぐためです。

## 機能の説明

日報やコメントなどで、 `@mentor` と記入がある投稿をしようとした際に `@mentor があるため、メンター全員に通知がいきますが、大丈夫ですか?` という確認ダイアログを表示します。

`@mentor` だけで、ユーザー名のメンション(e.g. `@hituzi-no-sippo`)のときは確認ダイアログは表示しなくてもいいと考えています。

日報のメンション通知ですが、その日報を初めて提出した時だけメンション通知がいくようになっています。そのため、WIPの場合は確認ダイアログは表示しなくていいと考えています。
[初めて日報を提出した時だけ、メンション通知とフォロワー、アドバイザーへ通知するように修正 by hituzi\-no\-sippo · Pull Request \#2480 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/2480)

## 優先度

低

意図せず(コードに記載 見落とし) `@mentor` と記載する場面はごく稀な印象があるので、優先度は低めでいいと感じています。

**Comment by JunichiIto** [comment]
たまにありますね〜、 `@mentor`の誤爆。
たしかにダイアログが出るようになっていると親切かも！
