### ISSUE TITLE
管理者が管理者権限でユーザーを退会にした場合は、ユーザーにメールと通知が飛ばないようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2512]
退会をすると、退会者に「フィヨルドブートキャンプをご利用いただきありがとうございました。退会処理が完了しました。」という旨のメッセージが飛びます。

管理者が管理者権限でユーザーを退会にした場合は、退会者には何もメールが飛ばないようにしていただきたいです。

**Comment by machida** [comment]
📝
飛んでなかったら、こちらのIssueはクローズにする

**Comment by shizimi50** [comment]
この辺りでユーザーにメール通知を飛ばしているが、ここはユーザー自身で退会を行なった場合
https://github.com/fjordllc/bootcamp/blob/f49b64afd1b41fc09725c46cb9f18eb7f889a1c9/app/controllers/retirement_controller.rb#L16

この辺りで管理者が管理者権限でユーザーの情報更新を行なっている
ただし、メール通知をユーザーに飛ばしている記述はなさそう
https://github.com/fjordllc/bootcamp/blob/f49b64afd1b41fc09725c46cb9f18eb7f889a1c9/app/controllers/admin/users_controller.rb#L22-L28

letter_openerでメールの確認を行った際、
ユーザー自身が退会した場合はメールが飛んでいたが、管理者が退会処理を行なった場合にメールは飛んでいなかった。

以上のことからメールは既に飛んでいないため、本件closeにします。
