### ISSUE TITLE
「担当する」ボタンと「提出物を確認」ボタンが枠からはみ出す

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2532]
提出物ページの幅を狭めるとボタンが枠からはみ出ます。

https://bootcamp.fjord.jp/products/7110

<img width="578" alt="Screen Shot 2021-04-01 at 9 06 09" src="https://user-images.githubusercontent.com/1148320/113225892-c3715b80-92c9-11eb-8ffb-e0ba1dc7029e.png">

**Comment by machida** [comment]
ご報告ありがとうございますー🙏
