### ISSUE TITLE
企業と会社の表記ゆれがあるので、企業に統一したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2539]

**Comment by yamadaab** [comment]
@machida @komagata 
昨日はありがとうございました。
マイクの方も無事に使用することができました。

この課題について質問があるのですが、「企業と会社の表記ゆれ」とはどこまでが対象でしょうか。

- アプリ内を検索すると「会社作成」、「会社編集」のような表記もありました。
- 上記などは関係なく、「法人利用」のページ内の「企業」と「法人」を、全て「企業」に統一するということでしょうか。

すみませんが、念の為確認させて頂ければと思いました。よろしくお願い致します。🙇‍♂️

**Comment by machida** [comment]
@yamadaab 会員登録しなくても入れるページは範囲外としてくださいー。welcome以下にあるページは範囲外でお願いします。

あと、法人は今回は範囲外でお願いします。

会社を企業に統一でお願いします。

参考
https://business-textbooks.com/difference-in-company-type/#toc-2
