### ISSUE TITLE
提出物の担当が外れてしまう

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2541]
## 概要

提出物の担当が外れてしまうバグがある。

- 自分（メンター）が担当の提出物に自分がコメントしたら外れてしまう
- コメントしたら自分が担当になる、の機能を入れたときのデグレの可能性がある
    - https://github.com/fjordllc/bootcamp/blob/main/app/models/product.rb#L99 

## 再現手順

1. 提出物一覧に行って、提出物の担当になる
2. その提出個別ページでコメントを投稿
3. 担当が外れている

## 期待される振る舞い

コメントを投稿しても、担当が外れないようにする。

**Comment by hituzi-no-sippo** [comment]
コメントしたら自分が担当になる機能は私が実装した部分なので、自分修正します。

**Comment by machida** [comment]
@hituzi-no-sippo おおー助かります🙏 ありがとうございます！！！！

**Comment by machida** [comment]
@hituzi-no-sippo @komagata こちら解決しましたら、hot fix としてすぐにリリースしたいと思います！！

**Comment by hituzi-no-sippo** [comment]
@komagata 
本番環境で動作確認の依頼を忘れていました。管理者ではないと無理なので、動作確認よろしくお願いします。

**Comment by komagata** [comment]
@hituzi-no-sippo 本番環境で動作することを確認しました〜
