### ISSUE TITLE
「日報を確認」ボタンが中央からずれていて気持ち悪い

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2552]
きっちりセンタリングしてもらえると嬉しいです。

https://bootcamp.fjord.jp/reports/28106

<img width="837" alt="Screen Shot 2021-04-04 at 6 46 30" src="https://user-images.githubusercontent.com/1148320/113492344-a75ffb00-9511-11eb-9c65-89a895a8f0fa.png">

**Comment by hituzi-no-sippo** [comment]
#2493  と同じ問題なのでCloseします。
この問題は #2494 のPRで修正されます。
PRの状況は実装が終わり、レビュー待ちです。

**Comment by JunichiIto** [comment]
なるほど了解です！！
