### ISSUE TITLE
プロフィール画像をユーザーアイコンに変えたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2560]
会員登録、登録情報変更のこの部分、

<img width="525" alt="貼り付けた画像_2021_04_05_14_38" src="https://user-images.githubusercontent.com/168265/113541153-a071df00-961c-11eb-8240-4e95621da295.png">

ユーザーアイコン に変更したい。
誰もこれのことを プロフィール画像 と呼んでいないので。

**Comment by yamadaab** [comment]
こちらのissue、本番環境で確認が完了したのでクローズさせて頂きます。
