### ISSUE TITLE
提出物のメッセージにスタイルが効いていない

### ISSUE THREAD

**Issue by ksmxxxxxx** [fjordllc/bootcamp#2562]
## 概要

提出物一覧の「プラクティスを完了するまで他の人の提出物は見れません。」部分にスタイルが当たっていないように見えます

## 再現手順

1. プラクティスページから提出物タブをクリック

## 期待される振る舞い

以前は赤背景色に白文字のスタイルだったように記憶しています

## スクリーンショット

<img width="980" alt="スクリーンショット 2021-04-05 23 13 26" src="https://user-images.githubusercontent.com/5976902/113583764-07b38180-9665-11eb-9a5b-dfee58dbda5a.png">

## 環境

 - OS: macOS Catelina
 - ブラウザ: Chrome最新版

**Comment by machida** [comment]
こちら修正しました🙇‍♂️
