### ISSUE TITLE
自分が担当する提出物(`products/self_assigned`)の2ページ目以降の提出物にコメントすると担当から外れる

### ISSUE THREAD

**Issue by hituzi-no-sippo** [fjordllc/bootcamp#2567]
## 概要

メンターが担当する提出物が50個以上で、51番目以降(2ページ目)以降の提出物にコメントすると、担当から外れてしまう。

メンターが担当する提出物に確認済のものは含まれていないため、メンターが担当する提出物が50個以上になるのは非常に稀で、この問題が発生する可能性は低いです。

## 再現手順

1. 自分の担当の提出物を50個以上にする
2. 2ページ目以降の提出物にコメントする
3. ページ再読み込み
4. 担当から外れている

## 期待される振る舞い

担当から外れないようにする

## 原因

自分が担当する提出物一覧を取得して、その一覧にコメントした提出物が存在するかどうかで、担当の切り替え(担当になる・外れる)を行なうREST APIを実行している。
自分が担当する提出物一覧は1ページ目しか取得しておらず、2ページ目以降の提出物を取得していないのが原因。2ページ目以降の提出物は取得しておらず、必ず担当の切り替え(担当になる・外れる)を行なうREST APIを実行するため、問題が発生している。

## 修正方法

2ページ目以降の提出物も取得するように修正する

## スクリーンショット

![before](https://user-images.githubusercontent.com/43565959/113820396-9d5e2680-97b5-11eb-84d4-4a2eab34ae54.gif)

## 環境

 - OS: Windows10
 - ブラウザ: Chrome
 - バージョン: 89.0.4389.114
 - commit: e1ec872298d005c1f5df0d307be7b7d58aa9afd2

## 関連Issue

原因のコードを書いた私のPR #2543

**Comment by hituzi-no-sippo** [comment]
自分が書いたコードが原因なので、自分が修正します。

**Comment by komagata** [comment]
@hituzi-no-sippo 申し訳ありません、ありがとうざいます 🙇

**Comment by hituzi-no-sippo** [comment]
@komagata 
本番環境で動作確認の依頼を忘れていました。管理者ではないと無理なので、動作確認よろしくお願いします。

**Comment by komagata** [comment]
@hituzi-no-sippo 連絡ありがとうございます。
僕の方で引き取ります〜。（2ページ目にいくようになったら確認します〜）
