### ISSUE TITLE
ベストアンサーを取り消すボタンと回答を削除するリンクの位置を入れ替える

### ISSUE THREAD

**Issue by hituzi-no-sippo** [fjordllc/bootcamp#2569]
次のようにテキストがボタンに挟まれて、格好悪い感じがします。

![answer](https://user-images.githubusercontent.com/43565959/113822754-cd5af900-97b8-11eb-80ed-15d989aedff6.png)

次のように、左から内容修正ボタン、ベストアンサーを取り消すボタン、削除の順に並んで欲しいです。

Windowsのペイントを利用して、作成した修正案

![fix](https://user-images.githubusercontent.com/43565959/113823778-00ea5300-97ba-11eb-84b1-404dce4fafea.png)

## 優先度

低

ログインユーザーが管理者、もしくは質問者本人の回答がベストアンサーになったときに、ボタンに挟まれる表示になります。ログインユーザーが生徒の場合、問題の画像のような表示になるのは稀です。

**Comment by machida** [comment]
@hituzi-no-sippo これ、修正のPRをなげてるのですが、ドラフトの状態で待機してます。色々コンフリクトが発生しそうなので、今あるPRが片付いたらマージします。

**Comment by hituzi-no-sippo** [comment]
> 修正のPRをなげてるのですが

#2561 ですかね ❔ 
[該当のdiff](https://github.com/fjordllc/bootcamp/pull/2561/files#diff-a3e459c7afaba5e18c0a494fbdc36f6a781cadd6254c00277362c0ef2f9e2056)
closeするの忘れそうなので、Linked pull requestsとして #2561 を紐づけました。
