### ISSUE TITLE
検索結果一覧をVue.jsで非同期にしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2571]

**Comment by alto-I** [comment]
@komagata 
こちらのissueを本番環境で動作確認しましたら、検索する対象物が多くなると検索結果の表示やページング処理にかなりの時間が掛かってしまう状況になっています。

試しに検索対象を`すべて`で検索ワードをなにも入れずに検索したところ
- 結果を表示するのに13秒
- 別ページへの遷移して表示するのに10秒以上

掛かってしまっています。動作自体は問題なく検索対象が少なければ遅くはならないのですが、こちらなにかしら対処した方がよろしいでしょうか😥
（ただ対象方法がどうすればいいか分かっていないのですが…）

**Comment by komagata** [comment]
@alto-I 今までの検索とVue.js版の検索の速度に違いがなければそのままで良いです。
Vue.jsにしたことで極端に遅くなったのだとしたら何かおかしいかもですね。

**Comment by alto-I** [comment]
@komagata 
開発環境で本番環境とほぼ同じ件数のデータを用意して検証したところ、どちらもほぼ同じ速度のレスポンスでした。なので特段vue化自体には問題ないと思います。

**Comment by alto-I** [comment]
こちら本番環境で確認しましたのでcloseします。
