### ISSUE TITLE
タグ編集の左右の余白が均等ではなく、右がずれている

### ISSUE THREAD

**Issue by hituzi-no-sippo** [fjordllc/bootcamp#2583]
## 概要

後述のスクリーンショットのように、タグ編集の左右の余白が均等ではなく、右がずれている。

特定のタグ編集ではなく、質問とDocs,プロフィール全てで発生している。

ステージング(https://bootcamp-staging.fjord.jp/ )や本番環境(https://bootcamp.fjord.jp/ )でしか発生しません。
私のローカルの開発環境(Ubuntu2004(WSL2))では現象は発生せず、再現できませんでした。

## 再現手順

1. タグ編集をする
2. タグ編集の欄の左右の余白の右がずれて表示される。

## 期待される振る舞い

余白を左右均等にする

### 本番環境

本番環境の最終リリースは[Release 2021\-04\-08](https://github.com/fjordllc/bootcamp/pull/2551)

質問

![tag_edit_on_question](https://user-images.githubusercontent.com/43565959/114230003-8c7b0400-99b3-11eb-8f6c-c9a75fc30f7f.png)

Docs

![tag_edit_on_doc](https://user-images.githubusercontent.com/43565959/114230002-8c7b0400-99b3-11eb-8e40-fc8394d91652.png)

ユーザー

![tag_profile](https://user-images.githubusercontent.com/43565959/114229996-8b49d700-99b3-11eb-8188-72476f316121.png)

### ステージング

gifをとったときのmainの最新のcommitが 993a1ed なので、環境は 993a1ed だと推測

![staging](https://user-images.githubusercontent.com/43565959/114230585-4a05f700-99b4-11eb-8f53-026bfabc3dd3.png)

### ローカルの開発環境

コミットのバージョンは本番環境とあわせるために 2722cd1926fb391bb9b5c823427a4c49d157f746 にした

![local](https://user-images.githubusercontent.com/43565959/114230598-4f634180-99b4-11eb-9a6c-d90195420410.png)

## 環境

 - OS: Windows10
 - ブラウザ: Chrome
 - バージョン: 89.0.4389.114

## 関連Issue

発見できませんでした。

**Comment by machida** [comment]
修正を確認したのでcloseしますー
