### ISSUE TITLE
長いコードが枠から横にはみ出すことがある

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2589]
下記ページ参照。

https://bootcamp.fjord.jp/questions/871

<img width="832" alt="Screen Shot 2021-04-11 at 8 43 02" src="https://user-images.githubusercontent.com/1148320/114287466-f4a81380-9aa1-11eb-85cf-f8f3d511b33b.png">

**Comment by machida** [comment]
修正を確認したのでcloseしますー
