### ISSUE TITLE
提出物のseedデータを50件より多くして、提出物のページャーの動作確認をしやすくする

### ISSUE THREAD

**Issue by hituzi-no-sippo** [fjordllc/bootcamp#2590]
## 概要

提出物のseedデータを50件より多くして、DBデータをリセット後(e.g. `rails db:seed:replant`)、すぐに提出物のページャーの動作確認をできるようにする。

50はページャーが利用される境界値

## この作業理由

DBデータをリセット後(e.g. `rails db:seed:replant`)、すぐに提出物のページャーの動作確認をできるようにしたいため。

## スクリーンショット

現状(993a1ed)の `rails db:seed:replant` してDBデータをリセット直後の提出物一覧(`products`)

![now](https://user-images.githubusercontent.com/43565959/114338934-116e4500-9b8f-11eb-9540-e82e08277d31.png)

提出物を50件より多くしたときの提出物一覧(`products`)

![add](https://user-images.githubusercontent.com/43565959/114339182-8f325080-9b8f-11eb-8663-f746c787f1d5.png)

## 関連Issue

#2567 
このバグの動作確認をするためには、2ページ目以降の提出物を操作する必要がある。そのため、提出物を50件以上にする必要がある。

#755

**Comment by hituzi-no-sippo** [comment]
@komagata 
私が作業している #2567 で必要な作業なので、私のほうでseedデータを追加してもよろしいですか ❓ OKな場合、こういうseedデータは作成して欲しくないとかありましたら、教えてください。

**Comment by komagata** [comment]
@hituzi-no-sippo はい、大丈夫です〜
