### ISSUE TITLE
通知メールによって本文の見え方が異なる

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2594]
https://bootcamp.fjord.jp/questions/873 にメンション付きの返信が届いたときの通知メールです。

### コメントの通知
MarkdownがHTMLに変換されている。
<img width="750" alt="Screen Shot 2021-04-14 at 9 50 18" src="https://user-images.githubusercontent.com/1148320/114638613-063e2500-9d07-11eb-9f9d-e51ba724079a.png">

### メンションの通知
Markdownがただのテキストになっている。
<img width="625" alt="Screen Shot 2021-04-14 at 9 50 27" src="https://user-images.githubusercontent.com/1148320/114638629-0ccc9c80-9d07-11eb-9ad8-60f57a519e69.png">

どちらか一方に形式を合わせたいです。（できれば前者）

**Comment by komagata** [comment]
:memo: メンションの通知メールの本文をHTMLに変換したい。（現状はMarkdownが生で出ている）
