### ISSUE TITLE
検索種別に提出物がない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2612]
検索結果に「提出物」は表示されますが、「提出物」のみで絞り込むことができません😣

<img width="833" alt="Screen Shot 2021-04-16 at 20 21 38" src="https://user-images.githubusercontent.com/1148320/115017462-8c1dc400-9ef1-11eb-9e30-2043d592b248.png">

**Comment by machida** [comment]
ありがとうございます！！
これ早めにやりたいと思います

**Comment by yamadaab** [comment]
@komagata 
仕様について確認をさせて下さい。
今回の提出物の検索結果は全ての人が確認できて問題ないでしょうか。

初期のプルリクから今回の提出物は検索対象に含まれない前提となっているようでした。
https://github.com/fjordllc/bootcamp/commit/c907e3497#diff-813e806b17ae840c301d910842cad3b9249825eed9ca742523ac22763218d16fR4-R11

こちらのプルリクでも提出物の扱いについて気にされていたようでした。
https://github.com/fjordllc/bootcamp/pull/1521#discussion_r409086692

以上、お忙しいところすみませんがご確認よろしくお願い致します。

**Comment by machida** [comment]
@komagata @yamadaab 

これって検索結果には表示されても、終わってないプラクティスの提出物はアクセスは出来ないのですよね？（もし違ったら対応を考えます）
少し文字が見えてしまいますが、それは問題ないかな、と思ってます。

**Comment by yamadaab** [comment]
@machida @komagata 
自分の意見もmachidaさんと同じです。
またkananashiという生徒アカウントで調べたところ、未完了のプラクティスは検索結果からアクセスできませんでした。
しかし、初期から「提出物」が無いこと。その後のプルリクエストでネタバレを心配されているような記述もあったので念の為確認させて頂きました🙇‍♂️

**Comment by machida** [comment]
@yamadaab アクセスが出来ない提出物はクリックする前にアクセスできない旨を表示しておきたいと思います。なので、もし、可能でしたらアクセスができない提出物には「アクセスできません」と文字を出すようにしていただけますでしょうか。文言の調整やデザインは僕の方で行いますー

**Comment by yamadaab** [comment]
@machida 
畏まりました！
「アクセスができない提出物には「アクセスできません」と文字を出す」も追加して取り組みます！
ご連絡ありがとうございます。🙇‍♂️

**Comment by komagata** [comment]
@yamadaab machidaさんと同意見です〜！

**Comment by yamadaab** [comment]
@machida 
お忙しいところすみません。
komagataさんのコメントについていかがでしょうか🙇‍♂️

**Comment by machida** [comment]
@yamadaab もし、可能だったらクリックできないものに、何かしら見た目の違いをだしたいとは思いますが、手間がかかりそうだったり、何かに何かの負荷がかかるなどがあったら今回は含めないで大丈夫です。

**Comment by machida** [comment]
@komagata 基本的にユーザーの予測を裏切らないようにしたいので、クリックしないと見れないことがわからないより、クリックする前に見れないことを伝えたいですが、その対応をすることにより何かデメリットが発生するなら今回の対応には含めなくていいと思います。

**Comment by komagata** [comment]
@machida できればやりたいですが、ちょっと大変なのでそこまでしてやらなくてもいいかな〜という温度感です。絶対やった方がいいというのであれば実装は可能です。

**Comment by machida** [comment]
@komagata なるほど、ではこのIssueではそこは含めない、でリリースをしたいと思いますー

**Comment by yamadaab** [comment]
@komagata @machida 
連絡せずにすみません。ご確認ありがとうございました。
上記、畏まりました。

また、質問があります。
今回の課題で提出物を検索結果に表示されることで表示がズレてしまい、既存のテストが一部通らなくなりました。
こちらについて既存のテストを変更すべきでしょうか。それともproductのseedデータを減らすなど対応すべきでしょうか。
お忙しいところ、すみませんがご確認よろしくお願い致します。

### これまで(main)の検索結果
![mainの検索結果](https://user-images.githubusercontent.com/47971067/117410235-1edbdc80-af4d-11eb-8f84-f7c565c0d8d3.png)

#### 山田変更後の検索結果
![山田のbranch](https://user-images.githubusercontent.com/47971067/117410244-21d6cd00-af4d-11eb-9ea2-fefbfd0f6f9b.png)

**Comment by harukus** [comment]
間違えて一旦クローズしてしましました🙇‍♂️

**Comment by komagata** [comment]
@yamadaab 

> 今回の課題で提出物を検索結果に表示されることで表示がズレてしまい、既存のテストが一部通らなくなりました。
> こちらについて既存のテストを変更すべきでしょうか。それともproductのseedデータを減らすなど対応すべきでしょうか。

テストの内容によるんですが、どういうテストでしょうか？

**Comment by komagata** [comment]
@yamadaab 

> ・エラーとなったassert_textを別の物に変更する。

でいいと思います。
本来、ここまでちょっとデータが増えただけで失敗するようなテストは望ましくないっすね〜

**Comment by yamadaab** [comment]
@komagata 
畏まりました！ひとまず、テストを通る形に修正してみます。(^^
ありがとうございます🙇‍♂️

**Comment by yamadaab** [comment]
@komagata 

エラーについて更に詳しく調べたところ以下が分かりました。
この対策を、更に下に記載しました。
すみませんがご確認よろしくお願い致します🙇‍♂️

### CIでエラーが起きた時の検索結果のスクショ
![スクリーンショット 2021-05-14 19 33 57](https://user-images.githubusercontent.com/47971067/118258883-5e756c00-b4eb-11eb-959d-f7e3ede9ca1d.png)


### ローカルで無事に動いた時の検索結果のスクショ
![スクリーンショット 2021-05-14 14 37 50](https://user-images.githubusercontent.com/47971067/118258559-fb83d500-b4ea-11eb-8451-47ab88a791c6.png)


どうやらソートがおかしいように見えます。
そして、どうやってソートしているのかコードを確認すると以下のように`updated_at`を用いて行っていました。

```
/fjordbootcamp/bootcamp/app/models/searcher.rb

def result_for_all(word)
      AVAILABLE_TYPES.flat_map { |type| result_for(type, word) }.sort_by(&:updated_at).reverse
    end
```

しかし、テストデータのファイルをそれぞれ見ると`updated_at`の記載はありません。
```
/fjordbootcamp/bootcamp/test/fixtures/products.yml

product1:
  practice: practice1
  user: yamada
  body: テストの提出物1です。
```

そのため、全て同じ日付となっていました。厳密にはミリ秒単位で違う日付がいくつかある状態でした。
上記のスクショでも全て同じ日付が表示されていました。

### 対応策
以下の対応だとどれが良いでしょうか。
- ①/fjordbootcamp/bootcamp/test/fixtures内のannouncements、practices、reports、products、questions、pages、eventsのテストデータ、一つ一つに`updated_at`を追加する
- ②/fjordbootcamp/bootcamp/test/system/searchables_test.rb内で使用されているデータのみ、未来の日時の`updated_at`を追加する
- ③、①をやった後に、最新の日付のテストデータを追加し、更にテストで使用されるデータを最新の日付のデータに変更する。

**Comment by komagata** [comment]
@yamadaab 

> 以下の対応だとどれが良いでしょうか。

どれでもなく、そもそものテストの内容がセンシティブ過ぎるのが問題だと思うので、もっと１〜２件しか引っかからないような検索ワードやテストデータにするのが良いと思います！

**Comment by JunichiIto** [comment]
@yamadaab ちゃんと実装されてました！素晴らしい😆
<img width="862" alt="Screen Shot 2021-06-05 at 7 03 09" src="https://user-images.githubusercontent.com/1148320/120871214-fbe92a80-c5d5-11eb-8cf9-17c5b2f3230a.png">
