### ISSUE TITLE
日報一覧取得のREST API内のログインユーザーのidのキー名が統一されていない

### ISSUE THREAD

**Issue by hituzi-no-sippo** [fjordllc/bootcamp#2625]
日報一覧取得REST APIは、全ての日報を取得と未チェックの日報を取得の2種類がある。
両方ともログインユーザーのidの値を格納しているのだが、キー名が統一されていない。

https://github.com/fjordllc/bootcamp/blob/fed6f3e53101e741c0fef4b7e6c4ad970ca51dfa/app/views/api/reports/index.json.jbuilder#L10

https://github.com/fjordllc/bootcamp/blob/fed6f3e53101e741c0fef4b7e6c4ad970ca51dfa/app/views/api/reports/unchecked/index.json.jbuilder#L9

未チェックの日報取得では、 `current_user_id` となっているので、次のコードで想定通りの動きにならない。

https://github.com/fjordllc/bootcamp/blob/fed6f3e53101e741c0fef4b7e6c4ad970ca51dfa/app/javascript/reports.vue#L79

**Comment by SatoshiHaramura** [comment]
@machida @komagata 
お疲れ様です。
本番環境での動作確認をお願いさせて頂きたいです🙏(管理者orメンターorアドバイザーのみが確認できるため)

以下の手順で、トグルが表示されることをご確認頂きたいです。
1. 日報作成ページ(/reports/new)にアクセスし、自分の日報を新規作成する。
2. 未チェックの日報一覧ページ(/reports/unchecked)にアクセスし、作成した自分の日報の右端に「内容変更/コピー」トグルが表示されることを確認する。

お手数ですが、宜しくお願い致します🙇‍♂️

**Comment by SatoshiHaramura** [comment]
@komagata 
ご確認頂きありがとうございました！

**Comment by SatoshiHaramura** [comment]
komagataさんにて本番環境での動作確認が完了したため、close致します。
