### ISSUE TITLE
IDとニックネームを併記したい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2632]
IDの表示だけだと読み方がぱっとわからない。プロフィールページを見ればニックネーム等がわかるが、少し手間。
以下の画像のようにニックネーム（または氏名）も併記してもらえると嬉しい。

<img width="607" alt="Screen Shot 2021-04-22 at 7 07 13" src="https://user-images.githubusercontent.com/1148320/115627340-d069f380-a339-11eb-94db-4c5aef742ddd.png">
<img width="309" alt="Screen Shot 2021-04-22 at 7 07 45" src="https://user-images.githubusercontent.com/1148320/115627347-d2cc4d80-a339-11eb-8351-9032276b5f6c.png">

Twitterのような表示形式にするのも一手。

<img width="397" alt="Screen Shot 2021-04-22 at 7 09 28" src="https://user-images.githubusercontent.com/1148320/115627349-d364e400-a339-11eb-9296-a1fc650384ac.png">

レビュー動画を作るときに受講生の名前を何と呼んだらいいかぱっとわからないときがある、というのが個人的な大きな動機のひとつです。

**Comment by kenboo0426** [comment]
https://github.com/fjordllc/bootcamp/pull/2757
こちらのプルリクで対応されていると思うのですが、されていたらcloseしていただいてもよろしいでしょうか？まだ未対応でしたら申し訳ございません🙇‍♂️
