### ISSUE TITLE
DocsやQ&A・プラクティスのページに未ログインでアクセスしたときに「ブートキャンプに登録するかログインしてください」と表示したい。

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2639]
ブログ記事からログインしないと見れないドキュメントにもリンクがあります。

外部の人が見る記事なのでそこから会員登録につなげるためにそれようの文言とリンクが欲しい。

**Comment by mono-nobe** [comment]
urlやdeveloper tool内のheadの中身は前のページと同様にする。

**Comment by mono-nobe** [comment]
@komagata @machida 
要件として
`会員登録 or ログイン推奨ページにおける <head> タグの中身を遷移先ページと同様にする`
がありますが、実現が難しそうです...

ログイン判定は以下のように行われています。

1. 遷移先ページへのリクエストが発生
1. Controller の `before_action` のタイミングでログイン判定処理が実行される
    - [sorceryライブラリの該当コード](https://github.com/NoamB/sorcery/blob/master/lib/sorcery/controller.rb#:~:text=To%20be%20used%20as%20before_action.)
1. 未ログインの場合、`not_authenticated`メソッドが実行され、`会員登録 or ログイン推奨ページ` へ遷移する
    - `not_authenticated`メソッド内で遷移先ページの`<head>`タグの情報が必要となる
        - `会員登録 or ログイン推奨ページ` へ `<head>` タグの情報を渡すため
    - [fjordアプリの該当コード](https://github.com/fjordllc/bootcamp/blob/main/app/controllers/concerns/authentication.rb#:~:text=def-,not_authenticated,-redirect_to%20root_path%2C)
        - 修正前であるため、現状 `アラート表示 & root_path への遷移` となっている

遷移先ページの `<head>` タグの情報は遷移先ページの `view` が持っています。
そのため、`not_authenticated` メソッド内で遷移先ページの `<head>` タグの情報が取得できない
=> `会員登録 or ログイン推奨ページにおける <head> タグの中身を遷移先ページと同様にする` のは難しいのでは考えています。

**Comment by mono-nobe** [comment]
以下のように、

- URLは遷移先ページと同様にする
- `<head>` タグ内の `title` タグに遷移先ページのURLを設定する

は可能です！

<img width="1164" alt="スクリーンショット 2023-02-17 19 44 35" src="https://user-images.githubusercontent.com/94843475/219623359-87edbfc2-b790-4f61-a50f-25d465266d5e.png">

**Comment by komagata** [comment]
@mono-nobe skip_before_actionとかで認証をしないようにするのはいかがでしょうか。

**Comment by mono-nobe** [comment]
@komagata 
ありがとうございます！
いただいた内容で検討してみます。

**Comment by mono-nobe** [comment]
> urlやdeveloper tool内のheadの中身は前のページと同様にする。

の背景を確認する。(以下の認識で合っているか)

1. Discordにログインが必要なページのURLを貼った際、ページタイトルが表示されない
1. 未ログインユーザーが対象ページへリクエスト際、タブなどからタイトルが見えるようにしたい
    - 露出して良い情報は露出させたい
    - ログイン・会員登録は何のページを見るために必要なのかをユーザーに知らせる


> DocsやQ&A・プラクティスのページ

対応範囲は上記の詳細ページのみで良いかを確認する

**Comment by mono-nobe** [comment]
>対応範囲は上記の詳細ページのみで良いかを確認する

これ以外はこれまで通りの挙動とする。

**Comment by mono-nobe** [comment]
本番環境で動作検証し問題ないことを確認したためcloseします
