### ISSUE TITLE
ユーザー個別ページの日報が空のときに日報はまだありません、と表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2642]
今は何もない状態
![image](https://user-images.githubusercontent.com/168265/116191897-0b1fc180-a768-11eb-9ab5-ae15a26dac1c.png)

**Comment by komagata** [comment]
@machida まさにgood first issueですね。登録ありがとうございます！

**Comment by obregonia1** [comment]
@machida 
ミーティングの時に通信状態が悪く聞き取れていなかったので確認したいんですが、こちらの顔マークも必要でしょうか？

![image](https://user-images.githubusercontent.com/66161651/118382520-6dfecd00-b631-11eb-8e9a-05b82c606647.png)

**Comment by machida** [comment]
@obregonia1 顔を出すようにしていただきたいですー🙏

**Comment by obregonia1** [comment]
@machida 
ありがとうございます！
対応しますー😄

**Comment by obregonia1** [comment]
本番環境で確認できたのでcloseします。
