### ISSUE TITLE
「このタグを自分に追加」を押すとうまくリダイレクトされない時がある

### ISSUE THREAD

**Issue by misosoup160** [fjordllc/bootcamp#2646]
## 概要

本番環境もしくはステージング環境でタグ別のユーザー一覧ページに表示される「このタグを自分に追加」ボタンを押すと、
アルファベットだけのタグはうまくリダイレクトされるが、日本語のタグではリダイレクトに失敗し、「You are being redirected.」というメッセージが表示される。develop環境だとどちらもうまくリダイレクトされる。

また、ユーザー登録情報のバリデーションで問題があるユーザーは、タグを追加できない（詳しくは以下のコメント参照）

~~今のところ私がタグが追加できない状態の再現ができていないので、再現できた方いたら書き足していただけるとありがたいです🙏~~

### リダイレクト
1. 　本番環境もしくはステージング環境でusers/tags/"何か日本語のタグ"にアクセス。
2. 「このタグを自分に追加」をクリック。
3. 「You are being redirected.」が表示される。

### タグを追加できない
1.　（developもしくはステージング環境の場合は）kananashiさんでログインする。
2.　users/tags/"何かタグ"にアクセス。
3. 「このタグを自分に追加」をクリック。
4.  タグが追加されない。

## 期待される振る舞い

全てのタグ、ユーザーでタグが追加でき、そのタグを登録しているユーザー一覧画面にリダイレクトされる。

## スクリーンショット

[![Image from Gyazo](https://i.gyazo.com/41bec87801b00c969a87b8b907b17d87.gif)](https://gyazo.com/41bec87801b00c969a87b8b907b17d87)

## 環境

 - OS: mac
 - ブラウザ: chrome
 - バージョン: 90.0.4430.85

## 関連Issue
なし？

**Comment by universato** [comment]
リダイレクトがちゃんと機能してない件と、タグが追加できない件は別件のはずですが、
関連事項としてタグが追加ができないケースについて記載します。

下記のコントローラ内のタグ追加するところの、
`current_user.save`のところで、ユーザーに関するバリデーションに失敗すると、タグが追加されません。

[bootcamp/tags\_controller\.rb at main · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/blob/88481dac097ef4e3a18bca12243bb26db5365b9a/app/controllers/users/tags_controller.rb#L5-L6)
```ruby
class Users::TagsController < ApplicationController
  def update
    current_user.tag_list.add(params[:tag])
    current_user.save
    redirect_to "/users/tags/#{params[:tag]}"
  end
end
```

バリデーションが起こる例として、ユーザー登録時などには問題なかったが、その後、ユーザー必須項目などが増えて、必須項目が埋まってなく、バリデーションに失敗する可能性があります。直近だとSlackからDiscordに移行して4桁の数値が求められるようになったため、それが埋まってないと失敗します。
「このタグを自分に追加」の機能を追加したときに、ユーザー全体にバリデーションが働かないようにすべきだったのでしょうね……。

**Comment by misosoup160** [comment]
@universato タグが追加できないのはこのように押しても何も起きないという状態ですか？

[![Image from Gyazo](https://i.gyazo.com/ff156575053cd9588bb248a821e70277.gif)](https://gyazo.com/ff156575053cd9588bb248a821e70277)

**Comment by universato** [comment]
リダイレクトが起きてるように見えないですが、たぶんそうかなという感じです。

英語だけにせよそうでないにせよ、ユーザー情報が足りてないとバリデーションに失敗され`current_user.save`で更新されませんが(`save!`ではないのでエラーは起きない)、英語オンリーだけのケースではリダイレクト(リロード)には成功して、日本語のあるケースだと真っ白で1文だけある画面になりました。

**Comment by misosoup160** [comment]
@universato 
これはdevelop環境で必須項目がない人なんですが、日本語と英語どちらも追加できずリロードするだけ？になるので、
追加できないという挙動は同じだけど、リダイレクトはやっぱり環境で挙動が変わるって感じなんですね。
了解です〜。ありがとうございました🙏

**Comment by universato** [comment]
もしdevelopmetとproductionで挙動が異なるという話だったら、
自分が機能を追加したときに本番環境でもちゃんと日本語のリダイレクトが機能してたか、ちょっと自信ないですね。
たぶん大丈夫だったと思うのですが、本番環境で日本語を試した画像記録などがないので、自信が100%にならずです。

**Comment by komagata** [comment]
@misosoup160 Issue登録ありがとうございます🙇‍♂️

**Comment by universato** [comment]
ユーザー情報が不完全だと「このタグを自分に追加」ボタンが使えない件については、
わかりやすいように別Issueに切り分けました。
本番環境で本題の日本語リダイレクトの修正を確かめられたので、閉じます。
