### ISSUE TITLE
プラクティスが終わってなくても見れる提出物には、その旨を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2652]

**Comment by obregonia1** [comment]
@machida 
これはすでに実装されているみたいですが、他の場所にも表示するという事ですかね？

![image](https://user-images.githubusercontent.com/75117116/118484233-f7a5bc00-b751-11eb-969f-3c92d4319f24.png)

**Comment by machida** [comment]
@obregonia1 

質問ありがとうございます!
貼っていただいたキャプチャは、プラクティスをやる人に向けたものなのですが、今回のIssueはちょっと違います。

プラクティスAというOKをもらっていなくても提出物を見ることができるプラクティスがあります。
Bさんが、Cさんの分報で気になるURLを見かけ、そのURLを踏みました。
そのURLはCさんのプラクティスAの提出物のページでした。
そこで、BさんはまだプラクティスAが完了していないことに気づきます。
Bさんは「なんでプラクティスAが完了していないのに、CさんのプラクティスAの提出物のページが見れるんだろう？」と疑問に思いました。
なぜなら、プラクティスAはOKをもらっていなくても提出物を見ることができるプラクティスである、ということが、CさんのプラクティスAの提出物のページにはどこにも書いていないからです。

...ということで、OKをもらっていなくても提出物を見ることができるプラクティスということが、

- プラクティス個別ページ

にしか、現在は表示されていません。

なので、直接提出物の一覧ページ、個別ページに URL から直接アクセスすると、「なんでプラクティスが完了していないのに提出物のページが見れるんだろう？」と、ユーザーを混乱させてしまいます。

そうならないように、OKをもらっていなくても提出物を見ることができるプラクティスの

- 提出物一覧ページ
- 提出物個別ページ

に、

「このプラクティスは、OKをもらっていなくても他の人の提出物を閲覧できます。」

と表示をするようお願いします🙏

**Comment by obregonia1** [comment]
@machida 
なるほどー！
丁寧な補足ありがとうございます🙇‍♂️

**Comment by kasai441** [comment]
@machida 
少し細かい仕様の確認をお願いしてもよろしいでしょうか。
### 全ページ共通 
  - 上記に言明されていませんが、「他の人の提出物も参考にしてください。」（リンク付き）を付加すべきでしょうか。
  - 赤い囲いや赤字などのスタイルについて、どの程度こちらで手を加えるべきでしょうか。下記の事例でコードも併記しますのでご確認お願いします。
  - 表示する場所や見た目など、下記に提案をしたので、何か注文等があれば教えてください。

### 提出物一覧ページ
- user、companyページから遷移した提出物一覧
提出物ごとに公開、限定公開が分かれているので、次のような各項目ごとにメッセージが分かれる表示のされ方をすればよいと考えます。


<img width="837" alt="image" src="https://user-images.githubusercontent.com/50036730/120255012-051c8380-c2c6-11eb-8466-13052313d0e4.png">

- practiceページから提出物一覧に遷移した提出物一覧
 全て同じプラクティスなので表示がうるさくなります（下記A案）。そこでpracticeからの遷移であることを条件として、一括のメッセージとして表示させるべきでしょうか（B案）

#### （A案）
<img width="847" alt="image" src="https://user-images.githubusercontent.com/50036730/120254963-eddd9600-c2c5-11eb-8351-eca9e4d9a6be.png">

#### （B案）
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/50036730/120255657-7446a780-c2c7-11eb-8674-c088fb83a4e1.png">
また、この図ではそうなっていませんが、プラクティスから提出物一覧を見る場合は、「他の人の提出物」のリンクはいらないと思います。そのページが現在表示されているページなので。

### 提出物個別ページ
<img width="766" alt="image" src="https://user-images.githubusercontent.com/50036730/120254880-c5559c00-c2c5-11eb-8d48-d488b244ac6c.png">

配置ですが、提出物の要件文と提出文の間くらいに配置するイメージでしょうか。この場合、``thread__description``クラスのdivを一つ増やした形ですがアンダーラインが一本余計に入っている感じがします。
sassに関する記述が難易度が高く、どこまで書くべきかわかりませんでした。

```
.thread__description.js-target-blank.is-long-text.js-markdown-view
  =  @product.practice.goal
.thread__description
  - if !current_user.adviser? && @product.practice.open_product?
    .practice-content__body-alert
      p
        | このプラクティスは、OKをもらっていなくても他の人の提出物を閲覧できます。
        = link_to practice_products_path(@practice) do
          | 他の人の提出物
        | も参考にしてください。
.thread__description.js-target-blank.is-long-text.js-markdown-view
  =  @product.body
```
ちなみに``js-target-blank``についてプロジェクト内を検索したところ、sassに定義されていないように見えましたが、これはどのような意味があるのか教えていただけますか。

**Comment by machida** [comment]
@kasai441 見た目はこちらでやるので、何か文字が表示されるようになっていれば続きは僕がやります。文言の中身も同様です。なので、文字を表示できたらpushをお願いします。続きは僕がやります。

**Comment by machida** [comment]
.js-target-blank これは前に使ってたもので、今は使ってないので見つけ次第消しています。

**Comment by kasai441** [comment]
本番で確認したのでクローズします
