### ISSUE TITLE
日報のブックマーク機能が欲しい

### ISSUE THREAD

**Issue by harukus** [fjordllc/bootcamp#2658]
**何故この機能が必要なのか**
参考になった日報やプラクティスを進める上で何度も見返す日報があるためです！

**機能の説明**
日報にお気に入りボタンを保存して、お気に入り一覧ページで見ることができる。

**Comment by komagata** [comment]
@harukus 良さそう！

**Comment by alto-I** [comment]
@komagata 
こちらのDB設計に関して質問があります。ブックマーク機能を今後、提出物やQ&Aに付けたい場合を想定するとポリモーフィックとして実装したほうがいいのでしょうか？

もしくはとりあえずBookmarkテーブルをreport_idを保存する形で作り、今後必要になったら後付けでポリモーフィックにするほうがいいのでしょうか？🤔

後付けでポリモーフィックが出来るのかどうかが分からなかったので質問させていただきました🙇

**Comment by komagata** [comment]
@alto-I 初めからポリモーフィックにした方がいいと思います〜

**Comment by alto-I** [comment]
@komagata 
ご回答ありがとうございます！
ポリモーフィックで実装していきたいと思います😄

**Comment by alto-I** [comment]
本番環境で動作確認できたのでcloseしますー
