### ISSUE TITLE
日報の画面上部にコメント数が載っているとうれしい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2659]
Q&Aページでは回答数が画面上部に表示されるようになりました。

<img width="224" alt="Screen Shot 2021-05-02 at 11 03 55" src="https://user-images.githubusercontent.com/1148320/116799762-3aeb1280-ab36-11eb-9fad-b082e49b1866.png">

Q&Aだけでなく日報や提出物など、コメントが付けられるページには同じようにコメント数が載っているとうれしいです。
なぜなら「この日報はコメント欄が盛り上がってるな」とか「この提出物は結構たくさんメンターとやりとりしてるんだな」という情報が、画面を下までスクロールしなくても把握できるようになるからです。

**Comment by udaikue** [comment]
@machida 1点質問させてください。

ミーティングのときにコメント数表示はJSではなくRubyで実装してOKというお話しをされていた記憶がありますが、Rubyの場合、コメントを投稿したタイミングではなく、ページをリロードしないとコメント数が反映されないのではないかと思います。
コメントした瞬間に反映されなくても良いですか？それとも即反映させる方法があるのでしょうか？

**Comment by machida** [comment]
@komagata 

こちら、どうしましょう？
今回はコメント後にコメント数が増えるのは範囲外にしますか？

> @machida 1点質問させてください。
>
> ミーティングのときにコメント数表示はJSではなくRubyで実装してOKというお話しをされていた記憶がありますが、Rubyの場合、コメントを投稿したタイミングではなく、ページをリロードしないとコメント数が反映されないのではないかと思います。
コメントした瞬間に反映されなくても良いですか？それとも即反映させる方法があるのでしょうか？

**Comment by machida** [comment]
@udaikue これ、Issueを作ったときは ページをリロードしないとコメント数が反映されないのは 別Issueでの対応を考えていましたが、もし、可能でしたらそこまで対応してくれると嬉しいですー

**Comment by udaikue** [comment]
@machida ご確認ありがとうございます〜。はい、ちょっと考えてみます！

**Comment by udaikue** [comment]
本番で確認できたのでcloseします。
