### ISSUE TITLE
公開済みの日報を更新するときに確認ダイアログを出す

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2661]
**何故この機能が必要なのか**
前日の日報をコピーするつもりが間違って編集ボタンを押してしまい、前日の日報を上書き更新（事実上の削除）してしまった、という事故がたまに発生するため。

<img width="320" alt="Screen Shot 2021-05-03 at 10 55 12" src="https://user-images.githubusercontent.com/1148320/116836945-7869a180-ac03-11eb-8de2-1e7c9b50619d.png">

参考 https://discord.com/channels/715806612824260640/824911197039099934/838576111280586802

**機能の説明**
公開済みの日報（WIPでない日報）を更新するときに「公開済みの日記を更新します。よろしいですか？」のような確認ダイアログを出す。

**考慮点**
公開済みの日報を頻繁に更新する人がいたら毎回ダイアログが出るのは鬱陶しいかも。

**Comment by ksmxxxxxx** [comment]
問題になっているポイントとしては、「日報をコピーを押したつもりが、編集を押してしまっている」というところがそもそもだと思います。

なので、
> 公開済みの日報（WIPでない日報）を更新するときに「公開済みの日記を更新します。よろしいですか？」のような確認ダイアログを出す。
これも対応策としてはいいと思うのですが、根本解決にはないっていないのではないかと考えます。

以下は自分が考えたアイディアです。

![image](https://user-images.githubusercontent.com/5976902/116837927-583be180-ac07-11eb-945f-aa82bf9ebcaa.png)

- 一覧の編集、コピーボタンのアイコンUIを中止して、文字UIに変更する
- 日報が確認されると確認スタンプでUIが隠れてしまい、UIの役割が果たせなくなってしまうので、ボタンと確認スタンプが重ならないように変更する
- 「前日の日報の内容をコピーして本日分の日報を作成する」という流れに一定の需要がありそうなので、日報作成に「前日の日報をコピーして作成」するボタンUIを新たに設けてもよさそうです

<img width="372" alt="スクリーンショット 2021-05-03 12 09 39" src="https://user-images.githubusercontent.com/5976902/116838269-bae1ad00-ac08-11eb-92eb-d203fdd2889b.png">

以上、参考になればと思います。

**Comment by becolomochi** [comment]
公開済みの日報の「編集する」ボタンを押下後のページ遷移後、ヘッダー直下に
「これは公開済みの日報です」
と出てるだけでも誤って上書きせずに済むかもと思いました〜！
（すいません今スマホなのでPC開けたらあとで追記します🙏）

**Comment by siroemk** [comment]
- ボタンを押し間違える件について

私も@ksmxxxxxx さんとほぼ同じ意見で「日報をコピーを押したつもりが編集を押してしまっている」ところが問題だと思うので、似たようなアイコン2つが並んでいる状態を解消するとミスも減るのかなと思いました。

> 日報作成に「前日の日報をコピーして作成」するボタン

日報作成のところにコピーボタンがあれば間違えないですね！

---

- 誤って公開済みの日報を更新しようとした時の対策

> 公開済みの日報を頻繁に更新する人がいたら毎回ダイアログが出るのは鬱陶しいかも。

頻繁に更新する人だと鬱陶しくなりそうですね...

それか、@becolomochi さんの意見にプラスで、現在「内容変更」ボタンの下に出ている「日報完成」という文言を「公開済みの日報が更新されます」のような文言に変えてwarning 系の色味で表示させると間違えて更新することもなくなりそうです。

![image](https://user-images.githubusercontent.com/31835314/116843578-5419bf00-ac1b-11eb-8838-6c40a75285e8.png)

**Comment by JunichiIto** [comment]
みなさん、ご意見ありがとうございます〜！
編集とコピーのボタンが近かったり、アクションが同じなのが根本原因なのかもしれませんね〜。
@ksmxxxxxx さんの意見のように、コピーの開始は編集とまったく別のアクションにするのがいいような気もしてきました。

このあたり、メンターは日報を書かないので受講生の生の声が非常に参考になります 🙏

**Comment by universato** [comment]
「日報の新規作成」ボタンを押すためにクリックする回数が増えるような変更は、よくないと思っています。
「前日の日報をコピー」と使わない自分にとって、「日報を作成」ボタンをクリックしたあとに「新規作成」か「コピー」を選ばすためにまたクリックする流れは避けて欲しい気持ちです。

**Comment by JunichiIto** [comment]
> 「前日の日報をコピー」と使わない自分にとって、「日報を作成」ボタンをクリックしたあとに「新規作成」か「コピー」を選ばすためにまたクリックする流れは避けて欲しい気持ちが強いです。

なるほど、それもたしかにそうですね〜。
ksmさんの意見は一案であって、まだこれにしましょう、と決定したわけではないので、みなさんからいろいろ意見をいただけるとありがたい次第です。（どこに着地するのかは僕もまだよくわかりませんが・・・）

-----

編集とコピーを押し間違える問題は、「アクセルとブレーキを踏み間違える問題」に似ているのかな〜ともふと思いました。
場所も近いし、ボタンをクリックするというアクションも同じなので、ぼーっとしてるとうっかりミスが起きやすい。

「[アクセルとブレーキの踏み間違いが起きないようにする発明](https://www.webcartop.jp/2016/02/32760/)」のように、編集とコピーを押し間違えないような発明が待たれる・・・!!!

![439cbd2b624dd5a4f87fdf6813ccf372](https://user-images.githubusercontent.com/1148320/116945021-a2799d00-acb1-11eb-859b-16ad8022304c.png)

**Comment by ksmxxxxxx** [comment]
![image](https://user-images.githubusercontent.com/5976902/117474534-f75d3200-af95-11eb-9288-32a16b4641f5.png)

思いついたとか、読んでて「こういうUI、他のサービスでも使われてるしアイディアとしてはこんなのもあるよね」っていうのを思い出したので貼っておきます。

**Comment by JunichiIto** [comment]
各位
本件、 https://bootcamp.fjord.jp/announcements/453 で紹介されている @machida さんの修正により改善されたと思うのですが、その後いかがですか？
誤操作しにくくなりましたか？

問題なさそうならクローズしようと思います〜。
