### ISSUE TITLE
自分が記載した全ての日報を一気にダウンロードできるようにする

### ISSUE THREAD

**Issue by hituzi-no-sippo** [fjordllc/bootcamp#2665]
## 何故この機能が必要なのか

この機能がないと手間がかかるからです。全ての日報を取得しようとすると、日報のmarkdownファイルを1つずつダウンロードするしかありません。

### 全ての日報を一気にダウンロードしたい場面

* 面接先の企業(fjordにアカウントがいない)の方からどんな日報を書いているか見てみたいといわれたとき
  面接先の企業がfjordにアカウントを登録するのも1つの手ですが、手続きとか大変そう&ダウンロードしたほうが楽で簡単そう
* 自分のブログに利用したいとき
* リタイアする時
   リタイアしたら、fjordのサービスを利用できない = 日報が見れなくなるから

## 機能の説明

ボタン1つ押せば、自分が記載した全ての日報のmarkdownファイルをダウンロードできるようにして欲しいです。markdownファイルを格納しているフォルダをzipで圧縮して、それをダウンロードする感じです。

### markdownファイルのフォーマット

* ファイル名: 日報の日付(e.g. 20110505.md)
* タイトル: 1番大きい見出し(i.e. `# 日報のタイトル`)として、markdown内に追加
* プラクティス、学習時間、日報についたコメント: 必要ないと考えています。

## 機能を追加するページ

次あたりにあると便利かなという印象です。

* 退会手続き(https://bootcamp.fjord.jp/retirement/new)
* ダッシュボード(https://bootcamp.fjord.jp)

## 優先度

低

欲しい人が少ないと考えているからです。

## 既存のREST APIを利用して自分が記載した全ての日報を一気に取得する方法

日報をユーザーで絞り込むREST APIがないので、日報一覧を取得するREST APIを利用して、次のようにするしかありません。

1. 全ての日報の情報を取得
1. 自分の日報だけになるように絞り込む
1. 日報のurlからmarkdownファイルのurlを取得
1. markdownファイルのurlに対して、wgetを実行して、ダウンロードする

"全ての日報の情報を取得" が大変です。

日報一覧を取得するREST APIの該当コード

https://github.com/fjordllc/bootcamp/blob/4b0cbcba988cf0c151904c71cbc5c096670d707f/app/controllers/api/reports/recents_controller.rb#L5-L9

**Comment by ima1zumi** [comment]
私もこの機能は欲しいと思っていました！
ref:https://github.com/fjordllc/bootcamp/issues/1808

**Comment by hituzi-no-sippo** [comment]
#3633 がマージされたので、closeします。
