### ISSUE TITLE
ステータスが卒業生のユーザーが卒業後に書いた日報が一覧に表示されない

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2669]

**Comment by universato** [comment]
Slackでやりとりしてるのを見て、確かめましたが、少し後ろの方にちゃんとありました。
日報の一覧は、日報の報告対象日(≠作成日時)の順に並ぶので、その報告対象日が古いと後ろの方になります。
また、報告対象日が同じ場合には、(WIPも含んだ)日報を作成した日時の順に並びます。

**Comment by machida** [comment]
@universato ご確認ありがとうございます！！バグじゃなくて良かったです😄 こちら、closeしますー
