### ISSUE TITLE
Vue.jsで表示されるページのページネーションをクリックしたら次のページの先頭に飛ぶようにしたい

### ISSUE THREAD

**Issue by misosoup160** [fjordllc/bootcamp#2677]
**何故この機能が必要なのか**

Vue.js化していないページではページャーをクリックすると次ページの上部に飛ぶが、Vue.js化したページではページ下部のページャーをクリックするとそのまま遷移したページの下部にとどまってしまう。
ページ遷移したことがわかりにくく、次ページは上からみたいため。

**機能の説明**
ページ下部のページャーでページ移動しても次ページの上部に飛ぶようにする。

**Comment by JunichiIto** [comment]
issueを書こうと思ったら同じissueがあった。僕も全く同意見です。

これ、対応してもらえると嬉しいな〜 👀 > @komagata @machida

**Comment by machida** [comment]
@JunichiIto @misosoup160
これ必要ですね！！Issue登録ありがとうございます！こちら優先度を上げてリリースしたいと思います。
