### ISSUE TITLE
Issueが登録されたらGitHub Action で自動でかんばん化されて欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2685]

**Comment by alto-I** [comment]
@komagata 
すいませんいくつか質問がありますでよろしくお願いします。

以下のようなワークフローを作成して自分のリポジトリで試したところ、issueのかんばん登録の自動化ができました。
~~~yaml
name: register issues in Kanban

on:
  issues:
    types: [opened]

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: 開発
          column: やる
          repo-token: ${{ secrets.GITHUB_TOKEN }}
~~~
使用したgithub actionは以下です。
[GitHub Project Automation\+ · Actions · GitHub Marketplace](https://github.com/marketplace/actions/github-project-automation)

`repo-token: ${{ secrets.GITHUB_TOKEN }}`の部分は管理者の方でないと設定できないのでご確認をお願いしたいです。

- Q1. この後このファイルを作成したPRをあげたほうがいいでしょうか？
- Q2. PRに上げた場合、キャンプ生へのレビュー依頼は必要でしょうか？

**Comment by sinsoku** [comment]
@alto-I @komagata 
`secrets.GITHUB_TOKEN` は特に設定不要で使えるので、管理者の作業は不要かなと思います。

> GitHubは、ワークフローで利用する`GITHUB_TOKEN`シークレットを自動的に生成します。 この`GITHUB_TOKEN`は、ワークフローの実行内での認証に利用できます。
> 引用: https://docs.github.com/ja/actions/reference/authentication-in-a-workflow

今回はissuesの更新だけなので、デフォルトの`GITHUB_TOKEN`の権限でも問題なさそう。

> Most of the time GITHUB_TOKEN will work as your repo-token. This requires no set up. If you have a public project board and public repository this is the option for you.
> 引用: https://github.com/alex-page/github-project-automation-plus/tree/8b1f15391cdb58c0c6a4ee4a83f5819cf3e747df#personal-access-token

**Comment by alto-I** [comment]
@sinsoku 
> secrets.GITHUB_TOKEN は特に設定不要で使えるので、管理者の作業は不要かなと思います。

リンクまでつけていただいて、丁寧なご回答ありがたいです🙇

**Comment by komagata** [comment]
@sinsoku 回答ありがとうございます。

@alto-I sinsokuさんのおっしゃる通りです〜

**Comment by alto-I** [comment]
@komagata 
こちらはPRを出して、他の方にレビュー依頼をすればいいでしょうか？🤔

**Comment by machida** [comment]
@alto-I @komagata

これは、もし動かないなどあってもユーザーには迷惑はかからないので、駒形さんのレビューだけでいいと思います。

自動で追加されたIssueは、[やる]ではない、レーンに入れたいですね。こちら、今日のMTGで話しましょう。

**Comment by alto-I** [comment]
@machida 
ご回答ありがとうございます！😄

あと今の状態だと登録したissueが全て「開発」のプロジェクトに登録されてしまうため、「カリキュラム改善」プロジェクトに登録する場合のパターンを実装できていません。そこも確認したいです。🙇

**Comment by alto-I** [comment]
メモ：入れるレーンは「いつかやる」、PRを入れてkomagataさんにレビューをお願いする

**Comment by alto-I** [comment]
実装確認できたのでclose
