### ISSUE TITLE
解決済みQAの表示件数にばらつきがある

### ISSUE THREAD

**Issue by harukus** [fjordllc/bootcamp#2689]
## 概要

PR : #2645 におけるバグ。
解決済みQAの一覧の表示件数がページごとに異なる。

## 再現手順

1. [解決済みの質問一覧 \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/questions?page=2&solved=true)にアクセス。
2. 2021年5月14日現在、２ページ目には３件しか表示されていない。
<img width="746" alt="スクリーンショット 2021-05-14 5 05 23" src="https://user-images.githubusercontent.com/52342576/118180896-0bab9e00-b472-11eb-8154-b79edd8b40db.png">

## 期待される振る舞い

全てのページで表示件数が25件になる。

**Comment by komagata** [comment]
@harukus Issue登録ありがとうございます〜！
