### ISSUE TITLE
WIPの日報がニコニコカレンダーに表示される

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2694]
WIPの日報がニコニコカレンダーに表示されるようです。
WIPなのでカレンダーには出さない方がいいと思います。

例 https://bootcamp.fjord.jp/users/1145 の5/14の日報はWIP

<img width="538" alt="Screen Shot 2021-05-14 at 11 41 54" src="https://user-images.githubusercontent.com/1148320/118213930-db7ff180-b4a9-11eb-9ef7-6a0031ef0538.png">

![nippo](https://user-images.githubusercontent.com/1148320/118213996-f8b4c000-b4a9-11eb-8de6-87f03fadc4ee.png)

**Comment by obregonia1** [comment]
本番環境で確認できたのでcloseします。
