### ISSUE TITLE
Q&Aで質問者にメンション付き回答を送ると、「メンション」と「Watch」両方の通知（＋メール）が来てしまう

### ISSUE THREAD

**Issue by alto-I** [fjordllc/bootcamp#2696]
下記のように質問者にメンション付き回答を送ると

![image](https://user-images.githubusercontent.com/68221700/118272720-fbd99b80-b4fd-11eb-82c1-7db78645a770.png)

「メンション」と「Watch」両方の通知（＋メール）が来てしまう。

![image](https://user-images.githubusercontent.com/68221700/118272331-6b02c000-b4fd-11eb-978c-22994a800587.png)

メンションだけが来るようにしたい。

 ## 類似issue
[コメントとメンションで2つの通知メールが同時に届く · Issue \#2595 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/2595)
[メンションの通知がある場合はWatchの通知を送らないようにした by komagata · Pull Request \#1728 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/1728)

**Comment by machida** [comment]
Watchをしていてもメンションと二重で通知がされてしまうかも。

**Comment by Ichiyo14** [comment]
本番環境で動作を確認しましたので、closeします。
