### ISSUE TITLE
終わっていないプラクティスの提出物一覧ページの文言を見やすくする

### ISSUE THREAD

**Issue by obregonia1** [fjordllc/bootcamp#2698]
![image](https://user-images.githubusercontent.com/75117116/118346753-8eb71c00-b578-11eb-8533-168ae589b063.png)

現状だと一目見て気付かないことがあるので、見やすいデザインに変更する。

**Comment by komagata** [comment]
@obregonia1 これバグですね。Issue登録ありがとうございます！
