### ISSUE TITLE
退会メールの一部が変数が表示されている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2705]
<img width="638" alt="screenshot 2021-05-16 20 48 30" src="https://user-images.githubusercontent.com/16577/118583710-73dee480-b7d0-11eb-9e16-2c237b48404d.png">

最終行に `#{@user.name}` と表示されてしまっている。

**Comment by obregonia1** [comment]
@komagata
こちらでは本番環境での確認ができないので、確認とIssueのCloseよろしくお願いします🙇‍♂️

**Comment by komagata** [comment]
@obregonia1 本番環境で動作することを確認しました。
