### ISSUE TITLE
ユーザータグのランキング一覧の読み込みに時間がかかる

### ISSUE THREAD

**Issue by universato** [fjordllc/bootcamp#2706]
## 概要

ユーザータグのランキング一覧の読み込みに時間がかかる。

## 再現手順

1.  https://bootcamp.fjord.jp/users/tags にアクセス。
2. 8秒ぐらい時間がかかる。

## 期待される振る舞い

他のページと同じぐらいの速さで読み込まれるのが嬉しいと思います。
今のままだと、ユーザーやタグが増えるほど、時間がかかってよくなさそうです。  
ページャをつけるか、もし改善できるならDBの読み込みを改善するか、あたりでしょうか。

## スクリーンショット

[![Image from Gyazo](https://i.gyazo.com/cb04c545691749bf7bc8e2a7890e79cc.png)](https://gyazo.com/cb04c545691749bf7bc8e2a7890e79cc)

## 環境

 - OS: Mac
 - ブラウザ: Chrome

**Comment by cafedomancer** [comment]
Lighthouse の結果を見ると "Reduce initial server response time" が一番大きな割合を占めているので普通にサーバーのレスポンスが遅そうですね。開発環境で rack-mini-profiler を確認してみます！

<img width="1920" alt="Screen Shot 2021-08-12 at 20 04 38" src="https://user-images.githubusercontent.com/7645585/129186498-796dc910-0f64-43c2-bd72-91062e48c406.png">

**Comment by cafedomancer** [comment]
タグの数だけ SQL クエリが発行されているので表示が遅くなっているようです。

![localhost_3000_users_tags](https://user-images.githubusercontent.com/7645585/129282072-c4df1994-495c-4236-9d58-5d645fa00e4b.png)

**Comment by cafedomancer** [comment]
1. クエリを減らす
2. ページネートする

**Comment by cafedomancer** [comment]
ちゃんと動いていそうなので close します。
