### ISSUE TITLE
メンションなしでコメントした場合、通知がある場合とない場合がある

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2719]
https://discord.com/channels/715806612824260640/828456619028381726/845130759882932285

![image](https://user-images.githubusercontent.com/75117116/120569913-de8b5380-c451-11eb-89e5-7e293e47d364.png)

**Comment by obregonia1** [comment]
@komagata @kasai441 
こちらのIssue なんですが、特定の日報でメンターが確認とコメントをした場合、通知されるのが後の方のアクションになるという仕様になっているのでバグというわけではなさそうです。
ちなみにメールの方の通知はどちらも送信されています。
このissueはクローズするか、確認もしくはコメントを優先する仕様に変更するかになると思いますがどうしましょう？

**Comment by kasai441** [comment]
そういう仕様なんですね。そういえば、逆パターンで、確認済みの通知がないのに確認済みになっていることもある気がします。

あくまで個人的使用感の話ですが、以下の順番で親切設計かと思います。
1. メールでの通知と同じように両方通知が一番分かりやすい。
2. 相手とのやり取りが発生するコメント優先
3. 仕様変更なしで、メンターがその仕様を把握して運用

もともとこのIssueのきっかけになった経緯は、コメント通知がないと（私の場合）その記事を見にいかないので、メンターのコメントを放置してしまったからです。メール通知を切っているユーザーの場合は、起こり得る現象と思います。

**Comment by obregonia1** [comment]
@kasai441 
なるほど！

> メールでの通知と同じように両方通知が一番分かりやすい。

これだと余計な通知が増えてしますなーとう

**Comment by komagata** [comment]
@obregonia1 @kasai441 まずはこのIssueについて、バグだったのか、仕様通りでバグではなかったのかをはっきりたせたいと思います〜。

改善要望などは別Issueとして起票していただければ〜

**Comment by obregonia1** [comment]
@komagata 
> こちらのIssue なんですが、特定の日報でメンターが確認とコメントをした場合、通知されるのが後の方のアクションになるという仕様になっているのでバグというわけではなさそうです。

こちらの通りバグではなかったようです！
なのでこのissueは一旦closeとしますが、僕も少し気になってた仕様だったのでDiscordの方で聞いてみて反応があれば起票しようと思います〜。

**Comment by kasai441** [comment]
@obregonia1 自分が投げた問題だったので引き取っていただいて申し訳ないですー。起票するにしても、仕様の決め方がむずかしいなーとか思って返事をしかねていました。もしお忙しいようでしたら起票とか、お手伝いしますのでお仕事投げてくださいー

**Comment by obregonia1** [comment]
@kasai441 
いえいえ、僕にアサインされたissueなので問題ないですよ👍
一応使っている皆さんの意見を反映した方がいいかなと思ったのでDiscordで質問して見ました！
反応がなかったら特に何もしませんが、もし @kasai441 さんがやっぱり変えたいんだよなーと思ったら新たに起票してみてください！

**Comment by kasai441** [comment]
@obregonia1 
ありがとうございます🙏
