### ISSUE TITLE
企業ユーザーのSlack通知・Slack用カラムを削除したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2732]
もうSlackを使ってないので。

**Comment by gozasoro** [comment]
@komagata 自分では確認できないので、こちら本番環境での確認をお願いいたします！

**Comment by machida** [comment]
@gozasoro @komagata 本番環境で削除されてることを確認しました🙆‍♂️

**Comment by gozasoro** [comment]
@komagata @machida 確認ありがとうございますー！
