### ISSUE TITLE
提出物のページでコメントが表示されるまでの間プレースフォルダを表示させる。

### ISSUE THREAD

**Issue by Yu-kichi** [fjordllc/bootcamp#2733]
**何故この機能が必要なのか**

コメントが表示されるまでの間ローディング中の画像を表示させていたが、プレースフォルダの表示に変更させるため。

**機能の説明**
ローディング中に次のような画面を表示させる。
<img width="635" alt="スクリーンショット 2021-05-24 18 13 21" src="https://user-images.githubusercontent.com/64201542/119325391-c8e09600-bcbb-11eb-8b3e-34b683fe8c32.png">

**Comment by JunichiIto** [comment]
これ早く実装してほしいです！
提出物のページだけじゃなく、日報のページとか、コメントが投稿できるページは同じように対応してもらえると助かります〜。

**Comment by machida** [comment]
📝コメント機能

- 日報のコメント
- Q&Aの回答
- docのコメント
- イベントのコメント
- お知らせのコメント

こちらIssue追加しました！
Yu-kichiさんのPRでやり方が固まったら、他のコメントにも適用させていきますー💪

**Comment by Yu-kichi** [comment]
[ロード中のプレースフォルダが表示されるように修正 \#2750](https://github.com/fjordllc/bootcamp/pull/2750)
こちらで対応が完了したのでクローズします。
