### ISSUE TITLE
WikiにDevelop環境でのメールの確認方法というページを作成し、そのページへのリンクをREADMEに追記

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2746]
これを

```md
- [Develop環境でのメールの確認方法](https://github.com/fjordllc/bootcamp/wiki/Develop%E7%92%B0%E5%A2%83%E3%81%A7%E3%81%AE%E3%83%A1%E3%83%BC%E3%83%AB%E3%81%AE%E7%A2%BA%E8%AA%8D%E6%96%B9%E6%B3%95)
```

READMEのここに追加。

<img width="392" alt="貼り付けた画像_2021_05_27_10_24" src="https://user-images.githubusercontent.com/168265/119751239-bf327a80-bed5-11eb-9dce-fb1479e4a637.png">

----

https://github.com/fjordllc/bootcamp/wiki/Develop%E7%92%B0%E5%A2%83%E3%81%A7%E3%81%AE%E3%83%A1%E3%83%BC%E3%83%AB%E3%81%AE%E7%A2%BA%E8%AA%8D%E6%96%B9%E6%B3%95

このページにいき、方法を記入。

**Comment by komagata** [comment]
:memo: letter_opner_web gemを使ってるのでそれの説明

**Comment by kasai441** [comment]
本番環境で動作確認できたのでcloseします
