### ISSUE TITLE
Docsに英語の名前をつけてアクセスできるようにしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2751]
slug: how-to-create-pr

のようにDocsのページにURLになる名前をつけてアクセスできるようにしたい。

例：

- `/pages/help`
- `/pages/how-to-create-pr`

「ヘルプページ」や「PRのや方」など、固定URLのページが欲しいためです。現状のIDだとdevelopment, productionなどでURLに違いが出てView内に埋め込んだりができないのと覚えられないURLになるため。

:memo:

- URLに使えない文字はだめ
- 数字だけはだめ

**Comment by gozasoro** [comment]
本番環境で確認できたのでcloseします〜
