### ISSUE TITLE
参考書籍に必読かどうかのチェックボックスが欲しい。（Descriptionも欲しい）

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2755]
プラクティス編集画面にこれがあります。
↓

<img width="527" alt="貼り付けた画像_2021_05_31_14_23" src="https://user-images.githubusercontent.com/168265/120143894-f5486500-c21b-11eb-8aa5-a16f50bef5df.png">

ここに、

- 必読か否かのチェックボックス（チェックが入っていたら必読書籍）
- 説明（textarea）

の追加をお願いします。

**Comment by gozasoro** [comment]
本番環境で確認できたのでcloseします〜
