### ISSUE TITLE
ユーザータグの詳細で「このタグを自分から外す」ボタンの導入

### ISSUE THREAD

**Issue by universato** [fjordllc/bootcamp#2778]
**何故この機能が必要なのか**

自分にあるタグを外すには、プロフィールに行く必要があって 、不便。
ブームが変わることもあるし、気軽に外せるようにした方が、気軽に追加しやすくてよい。
その他、タグの追加ボタンを試すときに不便。

**機能の説明**

現在は、ユーザータグ毎の詳細ページに行くと、追加済みのタグの場合は右上あたりで「追加済み」と表示されます。
この表示を外して、「このタグを(自分から)外す」のようなボタンにして、このボタンを押すとタグが外れるようにします。

**Comment by kasai441** [comment]
こちら、本番確認できましたので、クローズします
