### ISSUE TITLE
Q&Aでのユーザー権限のバグ

### ISSUE THREAD

**Issue by universato** [fjordllc/bootcamp#2781]
## 概要

Q&Aでのユーザー権限がバグっていそうと思います。

- 自分以外の質問や回答に「内容編集」ボタンがあり押せる。
  - 質問者のもののみかと思ったのですが、ステージング環境では質問者以外に対してもできそうでした。
  - ステージング環境で実際に編集できるか確かめたところ、実際にDBまで変更することはできませんでした。
- 自分が質問者でなくても、ベストアンサーを決めたり、取り消したりできる。
- 回答を送信する際のアイコンが、自分のアイコンでない。
  - 質問者のアイコンになっていそうでした。
  - 実際に送信したあとの回答では自分のアイコンでした。
  - 日報では、自分のアイコンになります。 

## 再現手順

- https://bootcamp.fjord.jp/questions から、任意のQ&Aをクリック。

## 期待される振る舞い

- 「内容編集」ボタンを押せるのは、本人(と管理者)のみ。
- ベストアンサーを決めることができるのは、本人(と管理者)のみ。
- 回答を送信するときのアイコンは、自分のアイコンか表示なし。

## 環境

 - OS: macOS
 - ブラウザ: Chrome

**Comment by Yu-kichi** [comment]
本番環境でテスト投稿した時のスクショをあげておきます。

自分の投稿が削除編集できない。
コメント投稿前のプレビュー画像がログイン者と違う。
他の人の投稿を削除編集できてしまう。
質問者ではないのにベストアンサーが決めれる。

<img width="992" alt="スクリーンショット 2021-06-04 22 12 25" src="https://user-images.githubusercontent.com/64201542/120810139-be5cb100-c585-11eb-9903-3254a396134e.png">
<img width="829" alt="スクリーンショット 2021-06-04 22 31 20" src="https://user-images.githubusercontent.com/64201542/120810170-c3b9fb80-c585-11eb-8474-f430a797afa4.png">

**Comment by komagata** [comment]
本番環境で修正されたことを確認しました。

**Comment by JunichiIto** [comment]
@komagata 修正ありがとうございますー。ただ、権限周りはバグると結構致命的なので、何ができる・できないのテストを書いて再発を防ぎたいですね。
