### ISSUE TITLE
ユーザーの紹介文がnilのユーザーの紹介文に「自己紹介文がない文言」を入れるrakeタスクを流す

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2798]
https://github.com/ilyakatz/data-migrate

**Comment by Daichi831** [comment]
質問タイムで以下のことを話しました。
## 自己紹介欄がnilのユーザーに対して空文字を入れることについて

現在は自己紹介欄がnilを許可してませんが以前はnilも許可されていたため自己紹介欄がnilのユーザーがいます。
### やろうとしたこと
nilに空文字を挿入する
### 話し合いで決まったこと
nilに空文字ではなく「自己紹介文はありません」という文言を挿入するようにする
### 変更の理由
空文字だとuserモデルのバリデーションに引っかかってします。
あまり自己紹介欄に空文字は入れて欲しくないため

---
以上から「nilのユーザーの自己紹介欄に空文字を入れる」→ 「nilのユーザーの自己紹介欄に別の文言を入れる」に変更します〜

**Comment by machida** [comment]
> 空文字だとuserモデルのバリデーションに引っかかってしまうため

ありがとうございます！！
「自己紹介文はありません。」でお願いしますー

**Comment by Daichi831** [comment]
承知しました！

**Comment by Daichi831** [comment]
@komagata 
すみません、１点質問があります💦
データを挿入するためマイグレーションファイルを作成したのですが、デプロイ時に自動でrake taskが実行されるためマイグレーションの状態はdownのままで良いのでしょうか？

**Comment by Daichi831** [comment]
@komagata 
先程の質問ですがそもそも開発ブランチでupかdown状態かは関係なくてmainブランチにマージされてから実行されるので問題ないですね💦

**Comment by komagata** [comment]
@Daichi831 ちょっと仰ってる意味がわかってないかもです。途中の状態をPRしてコードで見せてもらえればわかるかもです〜

**Comment by Daichi831** [comment]
@komagata 
すみません💦
こちらがPRになります！
https://github.com/fjordllc/bootcamp/pull/2859

**Comment by machida** [comment]
📝 
このIssueが完了したら、 #2788 これも解決しているか確認し、解決していたら close する

**Comment by Daichi831** [comment]
こちら本番環境でのみ確認ができる場合はステージングのチェック欄にチェックを入れても大丈夫でしょうか？

**Comment by komagata** [comment]
@Daichi831 ハイ、大丈夫です〜

**Comment by Daichi831** [comment]
承知しました！

**Comment by Daichi831** [comment]
こちら本番環境で確認したところ「自己紹介文はありません。」と文言が挿入されたユーザーとされていないユーザーがいました。
原因はよく分かっていませんが文言が挿入されていないユーザーは自己紹介欄がnilではなく空文字になっているからかな〜とも考えました。
この後、どうすれば良いか分からなかったためご連絡しました🙇‍♂️

- 「自己紹介文はありません。」と挿入されたユーザー

![image](https://user-images.githubusercontent.com/62867257/124432018-13b9f700-ddac-11eb-86e9-86458c8f0e2a.png)

- 何も挿入されていないユーザー（一部抜粋）

![image](https://user-images.githubusercontent.com/62867257/124432171-47951c80-ddac-11eb-954c-63a0ecee2717.png)

**Comment by komagata** [comment]
@Daichi831 そのURLなどを教えていただければありがたいです〜

**Comment by Daichi831** [comment]
失礼しました！
- 「自己紹介文はありません。」と挿入されているユーザー
https://bootcamp.fjord.jp/users?target=graduate
- 何も挿入されていないユーザー
https://bootcamp.fjord.jp/users?target=adviser&page=5

よろしくお願いします！

**Comment by komagata** [comment]
@Daichi831 おそらく空白文字になっているんだと思います。そちらに関しては僕が手動で「自己紹介文はありません。」と入力しておきました〜

このIssueは完了で大丈夫です〜。

**Comment by Daichi831** [comment]
承知しました！
ご対応ありがとうございます😊

**Comment by Daichi831** [comment]
@machida 
すみません！
#2788
このissueですが本番環境での確認だと思うのですがユーザー情報が不完全な状態を本番環境でどうやって再現すれば良いか分からなかったためご相談しました！

**Comment by machida** [comment]
@Daichi831 たしかにそうですねー。今回は不完全なユーザー情報のユーザーを撲滅させたので、もし、またこのエラーが出た場合は不完全な情報であることが原因ではない別の原因から起きるバグということになるので、不完全なユーザーを撲滅した旨を書いてIssueは閉じてしまって大丈夫ですー

**Comment by Daichi831** [comment]
@machida 
承知しました！
ありがとうございます😊

**Comment by Daichi831** [comment]
こちらdescriptionがnilのユーザーに対して自己紹介が無い文言を挿入し、空のユーザーに対しては駒形さんに直接入力していただきdescriptionがnilや空白のユーザーはなくなりました。
よってcloseします〜
