### ISSUE TITLE
Gemfileで特殊な使い方をしていたり古いバージョンを使っていたりするgemの説明を記載する

### ISSUE THREAD

**Issue by okuramasafumi** [fjordllc/bootcamp#2803]
Fukuoka.rbから来ました通りすがりのものです。

**何故この機能が必要なのか**

Gemの理解を深めるのはRails開発者として重要ですが、現状では`Gemfile`を眺めてもいくつかのgemについての情報を得られません。
名前から機能がわからないものも多いため、機能や役割についての説明があると助かるでしょう。

例：

```ruby
# Gemfile

gem 'kaminari' # ページネーションのため
```

**Comment by machida** [comment]
@okuramasafumi
ありがとうございます！！こちらやりたいと思いますー

**Comment by machida** [comment]
ちょっとこちら、もう少し考えてみたいと思います🙇‍♂️

**Comment by komagata** [comment]
@okuramasafumi Issue登録ありがとうございます！

コードはなるべくシンプルに保ちたいので `https://rubygems.org/gems/#{gemの名前}` でどういうgemかわかるということをカリキュラムに追記するのはどうかな〜と思いました。

**Comment by okuramasafumi** [comment]
一般的なgemについてはそれでよいと思います！特殊な使い方をしているものがあればコメントを追加するとわかりやすいかもしれません（が、具体例はパッと出ません）。
一般公開されている良い記事があれば、カリキュラムにはそれへのポインタだけあれば十分かもしれませんね。

**Comment by machida** [comment]
確かに、特殊なやつについてはREADMEからwikiにリンクを貼って説明するの良さそう、と思いました

**Comment by udzura** [comment]
私もkomagataさんの https://github.com/fjordllc/bootcamp/issues/2803#issuecomment-858382693 のご意見に賛成です！

特殊、というか現場では歴史的ないろいろから、古いバージョンに固定していたり、もはやあまり保守されていないgemを使わざるを得なかったり、などはあると思います。そういうパターンは（Gemfileに限りませんが）コメントするのがいいかと思います。

**Comment by sinsoku** [comment]
職場のGemfileでコメントを書くのは「バージョンを固定している理由」「歴史的な経緯で外せないgem」などが多く、gemの説明が書かれているケースは少ないかなと思いました。
なので、私もkomagataさんの意見に賛成で「gemを探したり、gemについて調べる方法」を伝えるのが良いかなと思いました。

**Comment by udzura** [comment]
もうすこし補足すると、Gemfileにgemの説明（What）を載せるべきではないと思う背景は、t-wadaさんの以下のツイートの原則を参考にしています。
https://twitter.com/t_wada/status/904916106153828352

バージョンを固定している理由（＝最新が原則なのに、最新になっていない理由）、歴史的な経緯で外せない理由、はWhy notであることを満たしていると思います。
