### ISSUE TITLE
お知らせ一覧ページでユーザー名も出したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2805]

**Comment by machida** [comment]
@mami-inuzuka 質問ありがとうございます！！

一覧系全てを「ユーザーIDだけを表示」 だったものから 「ユーザーID と氏名」 を出すに切り替えています。

それとは別に、コンテンツによって「更新者も出してほしい」という要望があったものは更新者も出すようにしています。

なので、今回は「ユーザーIDだけを表示」 だったものから 「ユーザーID と氏名」 を出すに切り替えをお願いしますー🙏

もし、今後「更新者も出してほしい」という声が上がったら別Issueで対応にしたいと思います。

---

ちょうど一覧に名前を出すというのがVue絡みのIssueの初めとしてちょうどいい難易度なので、一気にはやらず、少しずつみんなにこのIssueを割り振ってやってもらっているんですよね。全ての一覧に名前が出せたら、分類を整理したいと思います💪

**Comment by mami-inuzuka** [comment]
なるほど！！大変わかりやすくありがとうございます✨

それでは今回は「ユーザーID と氏名を出す」で対応しますね😊🙏

**Comment by mami-inuzuka** [comment]
こちら本番で確認を行い問題なかったのでクローズいたします。
