### ISSUE TITLE
ユーザーアイコンをhoverしたときに出すユーザーIDに、それだけではなく名前も表示されて欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2806]

**Comment by machida** [comment]
ユーザーアイコンをhoverすると、ユーザー名が表示されるのですが、それはtitle属性にユーザー名が入ってるからです。

https://www.tagindex.com/html5/attribute/title.html

ユーザーアイコンの部分は画像やtitle属性にユーザー名が入ってるなどがhelperで設定されてます。それを変更すれば、全てのユーザーアイコンに変更が反映されます。

**Comment by udaikue** [comment]
確認できたのでcloseします。
