### ISSUE TITLE
Admin画面のユーザー一覧にページャーを付ける

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2807]

**Comment by yana-gi** [comment]
@komagata 
こちらadmin管理機能のためご確認お願いします🙏

以下の点を確認していただきたいです！

- [ ]  `/admin/users`にページャーが表示されている（ユーザーは100件ごと）
- [ ]  どのターゲット区分でもページャーが表示されている
- [ ] ページ下部の「全員のメアド」にはターゲット区分に含まれるユーザーの全員分のメアドが表示されている（ページで表示されてるユーザーのみではない）

**Comment by yana-gi** [comment]
@komagata 
こちらadmin管理機能のためご確認お願いします🙏

以下の点を確認していただきたいです！

- [ ]  `/admin/users`にページャーが表示されている（ユーザーは100件ごと）
- [ ]  どのターゲット区分でもページャーが表示されている
- [ ] ページ下部の「全員のメアド」にはターゲット区分に含まれるユーザーの全員分のメアドが表示されている（ページで表示されてるユーザーのみではない）

**Comment by komagata** [comment]
@yana-gi それぞれ本番環境で動作していることを確認しました〜

**Comment by yana-gi** [comment]
@komagata
確認とcloseありがとうございますー！
