### ISSUE TITLE
Admin画面の企業一覧に一覧にページャーをつける

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2808]
Admin画面、企業一覧
https://bootcamp.fjord.jp/admin/companies

**Comment by Daichi831** [comment]
@komagata 
すみません、こちらのissueで質問があります💦
issueの内容は「adminのカテゴリー一覧にページャーをつける」ですが貼ってあるURLは企業一覧ページです。
こちらは表題どおりカテゴリーにページャーを付ければよろしいでしょうか？

**Comment by komagata** [comment]
@Daichi831 すみません、間違えていましたのを修正しました。企業一覧でお願いします。

**Comment by Daichi831** [comment]
@komagata 
承知しました！
管理者画面のカテゴリーにページャーをつけてしまったのですが、こちらはそのままでも大丈夫でしょうか？

**Comment by komagata** [comment]
@Daichi831 そちらのPRにコメントしましたのでそちらの確認をお願いします〜。

**Comment by Daichi831** [comment]
こちら管理者のみ確認できるため確認をよろしくお願いします🙇

**Comment by komagata** [comment]
@Daichi831 本番環境で動作することを確認しました。

**Comment by Daichi831** [comment]
ありがとうございます😊
こちらcloseします〜
