### ISSUE TITLE
[相談部屋]受講生は管理者に相談がしたい（相談機能）

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2810]
## 相談機能とは

受講者が管理者とプライベートな相談を行うためのクローズドな掲示板ページです。

## 必要な機能

- <s>メンター、アドバイザー、管理者以外のユーザー</s>全てのユーザーは、会員登録をすると、相談部屋が作られる。
- 相談部屋が作られたと同時に、「お気軽にこちらでご相談ください（ここの文章はもっと練ります）」という最初のコメントが相談部屋に投稿される。
    - ユーザーに対して通知が飛ぶ。
- 相談部屋ではコメントを書くことができ、コメントの送り合いで会話をする（要するに掲示板）。
- 相談部屋にアクセスでき、コメントを書くことができるのは以下のユーザー。
    - その相談部屋の持ち主のユーザー
    - 管理者全員
- 相談部屋に自分以外の新規コメントがあった際、以下のユーザーに通知が飛ぶ。
      - その相談部屋の持ち主のユーザー
      - 管理者全員
- グローバルナビに相談というリンクが増え、そこをクリックすると、
    - 受講生、卒業生の場合は自分の相談部屋（show）に飛ぶ
    - 管理者の場合は、すべての相談部屋の一覧（index）に飛ぶ
- グローバルナビにある相談リンクには、未読数が表示される。
- 管理者が見る相談部屋一覧（index）は、未読のあるものにだけ絞られいている状態がデフォルトで、すべてを表示に切り替えられる。

## リリースまでの流れ

タスクを分割、フィーチャーブランチを作り、そこに小分けにしたタスクごとにPRを送りマージしていく。完成したらmainブランチにマージしてリリース。

### この機能の前に

- 未返信が何日経っているかを知る、という機能が必要なので、その参考にするために提出物の経過日数の機能は先にリリースしたい。
- 提出物一覧の改善したUIと相談部屋一覧のUIは同じようなものになるので、提出物一覧の改善したUIのリリースを先にしたい。

### 相談部屋個別

![image](https://user-images.githubusercontent.com/168265/139791668-fb264de4-d9eb-4d5d-a1ac-5047a2098d6f.png)

### 管理者の相談部屋一覧

![image](https://user-images.githubusercontent.com/168265/121381779-f9dded80-c980-11eb-9da0-122b78d1c21a.png)

**Comment by mami-inuzuka** [comment]
いくつか確認と相談したいことがあります！お手隙でご確認お願いします✨


## [確認] 関連機能について
@machida 
下記2点なのですがすでにリリースってされていますか？
イメージを把握するために見ておきたいのでもしリリースされていたらそのissueかプルリクのURLを共有してもらえると嬉しいです😊🙏（ざっとissueみたのですがどれかわからなかったのでお手数ですがお願いいたします🙇🏻‍♂️）

>この機能の前に
>未返信が何日経っているかを知る、という機能が必要なので、その参考にするために提出物の経過日数の機能は先にリリースしたい。
>提出物一覧の改善したUIと相談部屋一覧のUIは同じようなものになるので、提出物一覧の改善したUIのリリースを先にしたい。

  
<br>

## [確認] 相談部屋の仕様について
@machida 
> * 相談部屋が作られたと同時に、「お気軽にこちらでご相談ください（ここの文章はもっと練ります）」という最初のコメントが相談部屋に投稿される。
     * ユーザーに対して通知が飛ぶ。

こちらの件ですが、イメージとしては添付画像のような感じであっていますか？💡「最初のコメントが投稿される」の認識が合ってるかどうかを念のため確認したく...！

（もしこの認識であっているのであれば、最初にすでに運営側から会話が始まっていると相談する側も最初の投稿がしやすくていいと思いました✨😊 ）

![139791668-fb264de4-d9eb-4d5d-a1ac-5047a2098d6f](https://user-images.githubusercontent.com/52844263/140002527-39e7baee-ac0d-44de-bd88-0a187d4c3208.png)

<br>

## [相談] URL（リソース）の命名について
@komagata @machida 

相談部屋を表すリソースの名前のご相談です。

今後同じような◯◯部屋ができてもいいように「XXX_room」みたいな感じにするのがいいのかなと思うのですが長すぎないかな...?ときになっています。

もしくは、長すぎるので「room」を省いてもいいかもしれないと思うのですがどうでしょうか？

そもそも「consultation」「counselling」という言葉があまり直感的ではないような気がしているのですがいい単語が思い浮かばず何かアイディアがあればお聞きしたいです🙏😊

▼リソース名候補
* consultation_room(s)
* counselling_room(s) （カウンセリングはちょっと違和感かも）
* consultation(s)
* counselling(s)

**Comment by komagata** [comment]
@mami-inuzuka talkとかでいいかもと思います〜

**Comment by machida** [comment]
@mami-inuzuka 

> [確認] 相談部屋の仕様について

まさにそのイメージです！！
 認識の確認ありがとうございます🙏

> [確認] 関連機能について

こちら確認します。見つけたら連絡しますー
このIssueを作ったのがかなり昔だったのですが、前は最後にコメントをしたのがいつ誰かを判断するのが大変でした。今はlast_commented みたいなカラムがあって、そこから取れた気がしてますー
確認します。

> [相談] URL（リソース）の命名について

komagataさんが言うように talk くらい抽象的な名前にしてもかぶらないかもしれないですー

**Comment by mami-inuzuka** [comment]
お二人ともご確認ありがとうございます！！

抽象度高めでも大丈夫とのことでしたら `talk` が直感的でわかりやすいなと思ったのでそちらで進めさせていただきたいと思います✨

関連機能については一旦はなくても作業進められるので、お手隙で大丈夫です！
お手数おかけします🙇🏻‍♂️

**Comment by mami-inuzuka** [comment]
本番での動作確認ができたためクローズします。
