### ISSUE TITLE
メンターが見れる提出物一覧の「未チェック」を「未完了」に名前を変えたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2811]
<img width="431" alt="貼り付けた画像_2021_06_10_1_44" src="https://user-images.githubusercontent.com/168265/121395471-6d85f780-c98d-11eb-8807-900e6257ac0b.png">

「未チェック」を「未完了」に

**Comment by Daichi831** [comment]
こちら管理者のみ確認可能ですので確認をよろしくお願いします！🙇‍♂️

**Comment by komagata** [comment]
@Daichi831 本番環境で動作することを確認しました。
