### ISSUE TITLE
コースに表示・非表示のフラグを設定できるようにする

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2812]
## 目的

ユーザー登録時に自分でコースを選択できるようにしたい。しかし現状では全コースを表示すると企業研修専用のコースなど見せたくないものもあるため、表示するコースと表示しないコースを分けられるようにしたい。

## やること

- コースのテーブルに表示・非表示のフラグを追加する。
- 管理画面のコース追加画面、コース編集画面でそれを編集できるようにする。
- 管理画面のコース一覧で表示・非表示フラグがどうなってるか表示する。
- ユーザー登録画面でコースを選択できるようにする。

**Comment by udaikue** [comment]
@komagata 確認させてください。

> 管理画面のコース追加画面、コース編集画面でそれを編集できるようにする。
> 管理画面のコース一覧で表示・非表示フラグがどうなってるか表示する。

コース追加画面、コース編集画面、コース一覧画面は新たに作成するということで合っていますか？

**Comment by komagata** [comment]
@udaikue 現状で`/courses`にアクセスするとコース一覧画面があり、そこから編集・追加画面にいけるようになっています。

すでにあるそれらの画面に表示・非表示フラグを追加する感じです～

**Comment by udaikue** [comment]
@komagata ありがとうございます〜。確認できました✨

**Comment by udaikue** [comment]
@komagata @machida 相談させてください〜。

登録画面(`/users/new`)のコース選択の項目は、どこに入れれば良いでしょうか??

**Comment by komagata** [comment]
@udaikue 確か既存コードに以前入れていた痕跡があったような気がします。
なかったらとりあえず良いと思うところにいれてみてください～

**Comment by udaikue** [comment]
本番で確認できたのでcloseします
