### ISSUE TITLE
プラクティス一覧のローディングをプレースフォルダにする

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2813]
プレースフォルダのデザインは @machida さんに聞いてみてください。

**Comment by maeda-seina** [comment]
### issueの方針
#3234 で作成されたvueファイルでは、今回のissueの「プラクティス一覧のプレースホルダ」には合わないため、新しいvueファイルを作成する。

### やること
プラクティス一覧のプレースホルダ用のvueファイルを用意して、デザインをmachidaさんに依頼する。
(@machida さんに確認済)

**Comment by maeda-seina** [comment]
本番環境で確認できたため、closeします。
