### ISSUE TITLE
通知一覧のローディングをプレースフォルダにする

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2814]
現在の通知一覧の読み込み時は、

![image](https://user-images.githubusercontent.com/168265/149260260-3c5fc0ef-ee6c-4e21-89e9-c359d01045cb.png)

このように表示される。

それを、日報一覧の読み込みと同じように

![image](https://user-images.githubusercontent.com/168265/149260332-ea51a006-5f28-47f5-be34-7fb27d8cb455.png)

このように表示したい。

**Comment by machida** [comment]
@Paru871 こちらアサインさせていただきましたー

**Comment by Paru871** [comment]
@machida
アサインいただきありがとうございます🙏かしこまりましたー！

**Comment by Paru871** [comment]
本番環境で確認できましたのでクローズさせていただきます。ありがとうございましたー🙏🏻
