### ISSUE TITLE
ユーザー一覧のローディングをプレースフォルダにする

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2816]
ユーザー一覧の読み込み中のデザインを入れます。

/users

ユーザー一覧を読み込み中は、読み込み中用のユーザーブロックを12個くらい表示する予定です。なので、12個くらいのブロックが読み込み中にだけ表示されるようにしてください。その時はブロックには仮のものを入れておいてください。

それができたら、machidaがブロックに仮ではなく正式なデザインをいれます。

**Comment by uchihiro04** [comment]
本番環境で動作確認ができましたので、issueをcloseいたします。
