### ISSUE TITLE
入会時のアンケートに『フィヨルドブートキャンプを卒業したらやりたいこと』の項目を追加する

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#2821]
**何故この機能が必要なのか**

現在、フィヨルドブートキャンプのカリキュラム卒業までに1年以上かかることが多い
学習モチベーションが下がってしまったときに、入会時の思いを見返せるようにしてモチベーションを上げるきっかけにしたい

**機能の説明**

入会時のアンケートに『フィヨルドブートキャンプを卒業したらやりたいこと』を追加する
プロフィールに自分だけ見れる項目として『フィヨルドブートキャンプを卒業したらやりたいこと』を表示する

**Comment by machida** [comment]
- 入会時のアンケートに『フィヨルドブートキャンプを卒業したらやりたいこと』を追加
- ダッシュボードに『フィヨルドブートキャンプを卒業したらやりたいこと』を表示

 入会時、『フィヨルドブートキャンプを卒業したらやりたいこと』は任意入力にするが、未入力の場合もダッシュボードに『フィヨルドブートキャンプを卒業したらやりたいこと』を表示し、未入力の場合は、入力しよう、という誘導も表示させる。

**Comment by R-Tsukada** [comment]
@machida 

> 自分のダッシュボードに『フィヨルドブートキャンプを卒業したらやりたいこと』を表示

このことを確認させてください。

<img width="2017" alt="ダッシュボード___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/62058863/145353951-22ef846e-99f6-4527-9fb9-b20f204e1cdb.png">

↑の画面に、「フィヨルドブートキャンプを卒業したらやりたいこと」を表示させればよかったでしょうか？

**Comment by machida** [comment]
@R-Tsukada はい！その理解で合ってますー

**Comment by R-Tsukada** [comment]
@machida 
返信遅くなってしまい申し訳ありません🙇‍♂️
確認ありがとうございます！

**Comment by R-Tsukada** [comment]
開発環境で確認できたためcloseする
