### ISSUE TITLE
通知一覧から記事に遷移した後に戻るボタンを押すと検索のモーダルが表示される

### ISSUE THREAD

**Issue by yana-gi** [fjordllc/bootcamp#2828]
## 概要

通知一覧から通知を選択し記事ページに遷移した後、戻るボタンを押すと検索のモーダルが表示される。

## 再現手順

1. https://bootcamp.fjord.jp/ にアクセスする
2. 「通知」をクリックして通知一覧を表示する
3. いずれかの通知をクリック
4. クリックした通知の該当ページに遷移する
5. ブラウザバックする
6. ブラウザバックした画面上に検索機能のモーダルが表示される

## 期待される振る舞い

検索機能のモーダルが表示されない

## スクリーンショット

![image](https://user-images.githubusercontent.com/67262644/121770732-13ac4a00-cba6-11eb-923f-1593cc7de3a9.png)

## 環境

 - OS: [iOS 11.0.1]
 - ブラウザ: [Chrome]
 - バージョン: [91.0.4472.77]

**Comment by universato** [comment]
参考までにmacOSだと再現しないですね。
- macOS Big Sur 11.4（20F71）
- Chrome 91.0.4472.101（Official Build） （x86_64）

**Comment by obregonia1** [comment]
これってたまになるなと思ってたんですが
- ベルマークをクリックしてドロップダウンから通知先に飛ぶ=>ブラウザバックでバグ発生
- 未読通知一覧(`notifications/unread`)から通知先に飛ぶ=>ブラウザバックではバグは発生しない

自分の環境だとこうなりますねー。
- masOS Big Sur 11.3.1（20E241
- Chrome 91.0.4472.77（Official Build） （x86_64）

**Comment by universato** [comment]
Chromeのバージョンを上げて再起動してもバグがでますかね。
自分はこのバグ生じないので、Chromeのバージョン違いかと思ったのですが。

**Comment by obregonia1** [comment]
91.0.4472.101（Official Build） （x86_64）
バージョン上げて再起動してみましたが状況変わらずですね。

**Comment by ima1zumi** [comment]
macOS Catalina 10.15.7
Chrome Version 91.0.4472.114 (Official Build) (x86_64) でも再現しました。

**Comment by mh-mobile** [comment]
最新バージョンのChrome（Chroniumベースのブラウザ）で再現したので、再現手順を載せておきます。
再現率は100%です。

## 再現手順

① 通知のアイコンをタップ ※通知がひとつ以上ある状態
② ポップアップが開いた状態で、画面遷移する。
→ 日報などの内部リンクやアドレスバー直打ちの画面遷移でもよい。
③ ブラウザバックする。
→ 戻るボタンや戻るジェスチャーのどちらでもよい。

## 環境:
Chrome バージョン: 91.0.4472.114
→ 再現する

Brave: バージョン: 1.26.74 Chromium: 91.0.4472.124（Official Build）
→ 再現する

Safari: バージョン14.0.3 (16610.4.3.1.4)
→ 再現しない

Firefox: 89.0.2 
→ 再現しない

Opera Neon: Version 1.0.2531.0 
→ 再現しない

## 備考

開発環境でも、本番環境でも再現した。

**Comment by universato** [comment]
再現できたし、理解できました。お騒がせしました。
ドロップダウンだしたまま、どこでもいいからクリックして画面遷移する(直URLでも)なんですね。
[![Image from Gyazo](https://i.gyazo.com/4d1446cbebbf1980a5f780b7103ba3c8.gif)](https://gyazo.com/4d1446cbebbf1980a5f780b7103ba3c8)

通知先にいかなきゃいけないと思いこんでて、かつ、なぜか通知一覧の方をいつもクリックしてて、ベルから一覧に行き一覧から通知先に行って「戻る」ボタンを押して、再現できなかったようです。

**Comment by mh-mobile** [comment]
参考までに再現動画をアップします。
※ QuickTimeで画面収録した動画のmovファイルをアップロードしてみました。


https://user-images.githubusercontent.com/13811034/125017269-bd033480-e0ad-11eb-957e-cced215be533.mov
