### ISSUE TITLE
お知らせ個別ページの作成ボタンが黄色いので白くしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2842]
<img width="941" alt="貼り付けた画像_2021_06_15_15_10" src="https://user-images.githubusercontent.com/168265/122001766-c4eff180-cdeb-11eb-9e3e-76613ea7564d.png">

is-warning を is-secondary にしたい。

**Comment by komagata** [comment]
@machida ナイスなgood first issueたくさんありがとうございます〜！

**Comment by machida** [comment]
@komagata いえいえ～。実は僕の作業漏れ...🤫

**Comment by makiichikawa** [comment]
本番環境での動作が問題ありませんでしたので、クローズいたします。
