### ISSUE TITLE
ダッシュボード配下に自分の提出物一覧をページを作りたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2843]
<img width="1750" alt="貼り付けた画像_2021_06_15_15_15" src="https://user-images.githubusercontent.com/168265/122002551-d7b6f600-cdec-11eb-8c2c-420ccd6a5492.png">

**Comment by udaikue** [comment]
【ペアプロメモ】
やること

- /current_user/products のページを作る
    - ダッシュボード配下に提出物タブを表示させる
- 提出物が0件のとき
    - 管理者、メンター、アドバイザーは提出物タブを非表示にする
    - それ以外(現役生、卒業生)は提出物タブを表示する

**Comment by yana-gi** [comment]
https://qiita.com/KONTA2019/items/0444ae3b8c8936a56ee0

**Comment by udaikue** [comment]
本番環境で確認できたのでcloseします。
