### ISSUE TITLE
ダッシュボード配下に自分の日報一覧ページを作りたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2844]
<img width="1750" alt="貼り付けた画像_2021_06_15_15_15" src="https://user-images.githubusercontent.com/168265/122002499-ca9a0700-cdec-11eb-8283-e966a6b41345.png">

**Comment by machida** [comment]
自分が昨日の日報を書いたかどうかすぐ確認できるように。

アドバイザー、メンター、管理者の場合は、

- 日報のタブ
- 提出物のタブ

は、投稿が0件だった場合は非表示にする。

現役生、卒業生は投稿が0件でもタブは表示させる。

**Comment by yana-gi** [comment]
@machida 

2点仕様の確認をさせてください。

>アドバイザー、メンター、管理者の場合は、
>* 日報のタブ
>* 提出物のタブ
>は、投稿が0件だった場合は非表示にする。

こちら非表示にするものは「自分の日報・提出物」のタブのみでしょうか？
それともタブ一覧ごと非表示にしますか？

また日報の一覧で表示させるものは、

`/users/<user_id>/reports`

で表示される内容と同じものという認識であっていますか？

**Comment by machida** [comment]
@yana-gi 

確認ありがとうございます！！

> こちら非表示にするものは「自分の日報・提出物」のタブのみでしょうか？
> それともタブ一覧ごと非表示にしますか？

こちらは、
「自分の日報・提出物」のタブのみ
でお願いします🙏

-----

`/users/<user_id>/reports` で表示される内容と同じものという認識であっていますか？

はい！その認識で合ってますー
最終的にはそのようにしたいのですが、Q&Aやポートフォリオも必要なので、それらの実装前はリンク先は消して、あるものだけタブを表示でいいかなーと考えています。随時、ダッシュボード配下にページを作ったらタブも追加していく流れで行こうと思ってます。

**Comment by yana-gi** [comment]
@machida 

>こちらは、
「自分の日報・提出物」のタブのみ
でお願いします🙏

アドバイザー・メンター・管理者の場合は「ダッシュボード」のタブのみ表示する、ということですね。承知しました！

>はい！その認識で合ってますー
最終的にはそのようにしたいのですが、Q&Aやポートフォリオも必要なので、それらの実装前はリンク先は消して、あるものだけタブを表示でいいかなーと考えています。随時、ダッシュボード配下にページを作ったらタブも追加していく流れで行こうと思ってます。

承知しました！
着手してみてまた疑問点があれば確認させてくださいー🙋‍♂️

**Comment by yana-gi** [comment]
@komagata 

「自分の日報」タブのリンク先のURLに関する確認です。

「自分の日報」タブボタンを押した遷移先のページのURLを新規に作成する必要がありますが、
ページのURLの`/xxx/reports`のxxxの部分は何にしましょうか。

案
- `/my/reports`
- `/me/reports`
- `/current_user/reports`


`my`だとmy reportsやmy productsと英語の文章らしくなるので個人的には`my`がいいと思っています。

**Comment by komagata** [comment]
@komagata ちょっと迷いますが、現状`current_user`を使ってるのでそれに合わせちゃいましょう〜

**Comment by yana-gi** [comment]
@komagata
承知しました〜！

**Comment by yana-gi** [comment]
@komagata @machida

追加で2点確認させてください〜。

## アドバイザー・メンター・管理者の場合について
> アドバイザー、メンター、管理者の場合は、
> 
> * 日報のタブ
> * 提出物のタブ
> 
> は、投稿が0件だった場合は非表示にする。
> 
> 現役生、卒業生は投稿が0件でもタブは表示させる。

とのことですが、アドバイザー・メンター・管理者かつ日報が0件のユーザーでも`/current_user/reports`の画面に遷移できるようにしますか？

また、遷移できる場合は以下のような表示にしたほうがいいと考えているのですがいかがでしょうか。
- ダッシュボードタブ画面(root画面）からは「ダッシュボード」タブのみ表示
- 「自分の日報」画面（`/current_user/reports`）からは「ダッシュボード」「自分の画面」タブを表示

というのも、「自分の日報」画面でも「ダッシュボード」タブのみの場合以下のような表示になってしまうためです。
![image](https://user-images.githubusercontent.com/67262644/123590245-5bc5a080-d825-11eb-90c6-b408bc816e8c.png)



## ヘッダーのボタンについて

ダッシュボードタブ画面(root画面）と「自分の日報」画面のヘッダーのボタンには何を表示させますか？
どちらの画面も「+日報作成」ボタンのみでよろしいでしょうか。
![貼り付けた画像_2021_06_28_15_19](https://user-images.githubusercontent.com/67262644/123589511-4bf98c80-d824-11eb-8325-fd0d8a1eddbc.png)

**Comment by komagata** [comment]
:memo: そのままで大丈夫です〜

**Comment by yana-gi** [comment]
質問タイムで確認したことメモ📝

### アドバイザー・メンター・管理者の場合について
アドバイザー・メンター・管理者かつ日報が0件のユーザーは
- `/current_user/reports`の画面に遷移できるようにする
- 「自分の日報」画面でも「ダッシュボード」タブのみ表示する

### ヘッダーのボタンについて
ダッシュボードタブ画面(root画面）と「自分の日報」画面ともに「+日報作成」ボタンのみ表示させる。
（「自分の提出物」タブはこのボタンは表示させない）

**Comment by komagata** [comment]
@yana-gi 質問タイムなど、ここ以外で話したことの経緯をここに書いておくのすごくナイスです〜！

**Comment by yana-gi** [comment]
@komagata
ありがとうございます！
自分だけでなくチームメンバーへの情報共有になると思うのでこれからも続けます👍

**Comment by yana-gi** [comment]
こちら本番環境で確認したためcloseします。
