### ISSUE TITLE
DocsをWatchできるようにしたい

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#2846]
**何故この機能が必要なのか**

就職関連のページやヘルプページなど、更新されたことを知りたいdocsがあります。
docs も Watch できると更新通知が届いてうれしいです。

:memo:

- Docsの作成者とそこにコメントした人はWatch状態になる。

**Comment by komagata** [comment]
@ima1zumi 確かにですね！

**Comment by yana-gi** [comment]
こちら本番環境で動作確認したため、closeします。
