### ISSUE TITLE
ユーザー > コメント一覧 にコメントがない場合の表示を変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2850]
![image](https://user-images.githubusercontent.com/168265/122146208-93c9fc80-ce91-11eb-961f-6b7d56c63b86.png)

このようにしたい。

ユーザー > 日報一覧 に日報が0件の場合の表示を参考にする。

**Comment by FUGA0618** [comment]
本番環境で確認できたのでcloseします🙆🏻‍♂️
