### ISSUE TITLE
ユーザー > 質問一覧 に質問がない場合の表示を変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2851]
![image](https://user-images.githubusercontent.com/168265/122146208-93c9fc80-ce91-11eb-961f-6b7d56c63b86.png)

このようにしたい。

ユーザー > 日報一覧 に日報が0件の場合の表示を参考にする。

**Comment by sutehuna** [comment]
確認したところ、既にこのようになっていました。実装されているのではないでしょうか？
![スクリーンショット 2021-09-23 171804](https://user-images.githubusercontent.com/57139988/134475342-80838880-de39-4475-a6f9-7b7c32390d92.png)

**Comment by komagata** [comment]
@sutehuna すみません、こちらもすでに実装されているIssueのClose忘れのようです。こちらは完了で別のIssueをお願い致します。
