### ISSUE TITLE
日報作成から日報一覧に戻るボタンの文言変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2854]
現在

![image](https://user-images.githubusercontent.com/168265/122149210-ad217780-ce96-11eb-8632-230e48bc1105.png)

こうしたい（日報一覧にして、< を付ける）

![image](https://user-images.githubusercontent.com/168265/122149379-efe34f80-ce96-11eb-8b70-7c8a7e05dc04.png)

誰かの日報のページに行くと、そのボタンがあるので、それを参考にする。

**Comment by udaikue** [comment]
本番環境で確認できたのでcloseします。
