### ISSUE TITLE
Doc個別ページにある、新規作成ボタンのデザインを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2858]
<img width="398" alt="貼り付けた画像_2021_06_17_11_01" src="https://user-images.githubusercontent.com/168265/122319340-7497a180-cf5b-11eb-9ce9-c3f6cf12624d.png">

このように変更する。

<img width="421" alt="貼り付けた画像_2021_06_17_11_07" src="https://user-images.githubusercontent.com/168265/122319833-2767ff80-cf5c-11eb-962c-ce618ad12443.png">

**Comment by machida** [comment]
<img width="398" alt="貼り付けた画像_2021_06_17_11_01" src="https://user-images.githubusercontent.com/168265/122319340-7497a180-cf5b-11eb-9ce9-c3f6cf12624d.png">

このように変更する。

<img width="421" alt="貼り付けた画像_2021_06_17_11_07" src="https://user-images.githubusercontent.com/168265/122319833-2767ff80-cf5c-11eb-962c-ce618ad12443.png">

**Comment by makiichikawa** [comment]
Docs一覧ページの新規作成ボタンとデザインを統一するため、ボタンの文言は"新規Doc作成"とします。

![Docs___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/57123982/125931611-0a0a1e8d-324c-43b8-b77c-d1b3e75a7472.png)

**Comment by makiichikawa** [comment]
本番環境での動作問題ありませんでしたので、クローズいたします。
