### ISSUE TITLE
ユーザ登録時に入力したタグが保存されない

### ISSUE THREAD

**Issue by satococoa** [fjordllc/bootcamp#2865]
## 概要

ユーザ登録画面の "タグ" にタグを入力してユーザ登録を行ってもタグが保存されません。

## 再現手順

1. /users/new にアクセス
2. 必須の情報を適当に埋める (クレカは stripe の [テストカード](https://stripe.com/docs/testing) を使いました)
3. /letter_opener から登録を完了する
4. 先ほど登録したアカウントでログインし、 "自分のプロフィール" を見てもタグが保存されていない

## 期待される振る舞い

登録時に入力したタグが保存されること

## スクリーンショット

/users/new
<img width="560" alt="スクリーンショット 2021-06-21 1 53 49" src="https://user-images.githubusercontent.com/31448/122682302-959a1400-d233-11eb-990c-100762d6f283.png">

ログイン後
/current_user/edit
<img width="587" alt="スクリーンショット 2021-06-21 1 50 45" src="https://user-images.githubusercontent.com/31448/122682223-28867e80-d233-11eb-825e-68f188500ddf.png">

## 環境

 - OS: macOS Big Sur バージョン 11.4
 - ブラウザ: Chrome
 - バージョン: 91.0.4472.106（Official Build） （x86_64）

📝 
本番環境にて自分がアドバイザーとして登録したときに発生し、先ほどローカル環境にて通常の生徒さんとしてのサインアップでも発生することを確認しました。

## 関連Issue

なし？

**Comment by machida** [comment]
Issue登録ありがとうございます！！
こちら優先度を上げて対応したいと思います🙇‍♂️

**Comment by machida** [comment]
@kasai441 こちらよろしくお願いします🙏

**Comment by kasai441** [comment]
> @kasai441 こちらよろしくお願いします🙏

わかりましたー

**Comment by kasai441** [comment]
本番で確認できたのでcloseしますー
