### ISSUE TITLE
プラクティスページから「質問する」を押したときは、対象のプラクティスが選択された状態で質問するページが開いていてほしい

### ISSUE THREAD

**Issue by cafedomancer** [fjordllc/bootcamp#2867]
**何故この機能が必要なのか**

* 誤ったプラクティスに対して質問するのを防ぐため
* プラクティスを選択する手間を減らすため

**機能の説明**

タイトルどおりです！

**Comment by Daichi831** [comment]
本番環境で確認できたためcloseします〜
