### ISSUE TITLE
通知メールの本文が simple_format になっているので、markdownで書き出すようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2871]
`/app/helpers/application_helper.rb` に `md2html()` を用意してあります。

```slim
= simple_format(本文)
```

をこのようにすると、markdownで書き出されます。

```slim
= md2html(本文)
```

`/app/views/notification_mailer` この中のファイルを修正お願いします。

開発環境でメールを確認する方法。
https://github.com/fjordllc/bootcamp/wiki/Develop%E7%92%B0%E5%A2%83%E3%81%A7%E3%81%AE%E3%83%A1%E3%83%BC%E3%83%AB%E3%81%AE%E7%A2%BA%E8%AA%8D%E6%96%B9%E6%B3%95

**Comment by Daichi831** [comment]
@machida 
# 概要
`simple_format`と`md2html`の2つの場合で日報にコメントをし、その時のメール通知を確認する
- sumiというユーザーが日報を作成
- jobseekerというユーザーが日報に対してコメントする

といった順序です。
## コメント入力画面
- コメント入力
![image](https://user-images.githubusercontent.com/62867257/122915920-44a33080-d397-11eb-99e3-393fc1c94801.png)
- 実際のコメント
![image](https://user-images.githubusercontent.com/62867257/122916056-6dc3c100-d397-11eb-888e-8cd0882f81aa.png)

## メールでの通知結果
![image](https://user-images.githubusercontent.com/62867257/122916291-afed0280-d397-11eb-9cf9-7a9378d2f4c3.png)


メールでの通知結果は上のようになりました。

---
ここで質問なのですが`/app/views/notification_mailer`のファイルの`simple_format`の箇所を`md2html`に書き換えて同じコメントをしてみると`simple_format`の時と同じ結果になりました、、、
期待するメールでの結果は入力したときのように`test test`の部分が改行されて表示されることでしょうか？

<img width="618" alt="貼り付けた画像_2021_06_22_20_34" src="https://user-images.githubusercontent.com/62867257/122918002-9947ab00-d399-11eb-9c90-78c6cd7ec02e.png">

**Comment by Daichi831** [comment]
@machida 
すみません！`simple_format`だと以下のようになりました。
前回同じ結果になったものは既に`md2html`が適用されていました🙇‍♂️
![image](https://user-images.githubusercontent.com/62867257/123056670-1890b980-d442-11eb-8d9d-0bad31ca643c.png)

確かに`simple_format`だとmarkdownで書けないようですね...
僕の検証の結果
- `simple_format`だとmarkdownで書き出されないが改行は適用される
- `md2html`だとmarkdownで書き出されるが改行を入れるには空行を入れる必要がある

といった感じになりました！
このまま`md2html`を適用して実装すればよろしいでしょうか？

**Comment by machida** [comment]
@Daichi831 検証ありがとうございます！！
md2html で Markdown 表示にしていただきたいです。
改行2回はpタグになるけど、改行1回はbrにならない、という現象が起きてますね。Markdownの仕様通りの動きになり、brは方言なので、そのオプションをオンにする必要があります。

確かredcarpetを使ってたと思うのですが、hardwrapというオプションをtrueにすればbrにしてくれると思いますー

参考
https://qiita.com/yuuuking/items/3f88454e164a5f7d4733

試してみてくださいー

**Comment by Daichi831** [comment]
ありがとうございます！
redcarpetですが現在のフィヨルドアプリではcommonmarkerが使われているようです〜
なのでgemをインストールして`md2html`メソッド内を書き換えて対応しようと考えてます！

**Comment by Daichi831** [comment]
本番環境で確認したためcloseします。
