### ISSUE TITLE
ヘルプ表示中はグローバルナビゲーションのヘルプのリンクがアクティブになっていて欲しい

### ISSUE THREAD

**Issue by satococoa** [fjordllc/bootcamp#2887]
## 概要

ヘルプ閲覧時に Docs のリンクがアクティブ（背景色黄色）になっています。
（実際にはヘルプは Docs の1ページに過ぎないので厳密にはバグとは言いづらいですが）

## 再現手順

1. グローバルナビゲーションの「ヘルプ」をクリック
2. 「Docs」の方がアクティブになっている

## 期待される振る舞い

「ヘルプ」がアクティブになる。
（ヘルプのトップページ閲覧中のみで良いと思います。リンク先に飛んだ後は「Docs」がアクティブで良いと思います。）

## スクリーンショット

<img width="750" alt="スクリーンショット 2021-06-26 23 54 15" src="https://user-images.githubusercontent.com/31448/123517022-f5803700-d6d9-11eb-8faf-edda917c2d30.png">

## 環境

 - OS: macOS Big Sur (バージョン 11.4)
 - ブラウザ: Chrome
 - バージョン: バージョン: 91.0.4472.114（Official Build） （x86_64）

## 関連Issue

Ref: #2566

**Comment by makiichikawa** [comment]
@machida @komagata 

ミーティングの会話がうろ覚えで自信がないので、念の為確認させてください😓

ヘルプのリンク先を参照した場合に、ヘルプのアイコンをアクティブにするのですが、
Docsのアイコンもアクティブにするで認識あっていますでしょうか？？

![ヘルプのページ___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/57123982/127125527-ce445db3-a6b5-4457-8336-f92069c11e64.png)


お手数おかけしますが、よろしくお願い致します🙇🏼‍♂️

**Comment by komagata** [comment]
@makiichikawa Docsの方はインアクティブでお願いします。

**Comment by makiichikawa** [comment]
本番で問題なく動作していましたので、クローズいたします。
