### ISSUE TITLE
ユーザーの質問一覧画面にのみユーザー一覧ボタンに<がない

### ISSUE THREAD

**Issue by yana-gi** [fjordllc/bootcamp#2895]
## 概要

ユーザーの質問一覧画面(`/user/:user_id/questions`)画面にのみユーザー一覧ボタンに`<`がない

## 再現手順

` /user/:user_id/questions`にアクセスする

## 期待される振る舞い

`/user/:user_id/questions`画面にもユーザー一覧ボタンに`<`が表示される

## スクリーンショット
`/user/:user_id/reports`

![貼り付けた画像_2021_06_28_17_36](https://user-images.githubusercontent.com/67262644/123721777-fc699e00-d8c1-11eb-8da8-911922d24173.png)

`/user/:user_id/questions`

![貼り付けた画像_2021_06_28_17_35](https://user-images.githubusercontent.com/67262644/123721791-04294280-d8c2-11eb-84de-797dffe36b04.png)

## 環境
* OS: [iOS 11.0.1]
* ブラウザ: [Chrome]
* バージョン: [91.0.4472.114]

**Comment by FUGA0618** [comment]
本番環境で確認できたのでcloseします🙆🏻‍♂️
