### ISSUE TITLE
管理画面にコース一覧が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2901]
現状は管理画面（`/admin/courses`）にはなく、`/courses`にコース一覧があるので、管理画面としてのコース一覧が欲しい。

**Comment by komagata** [comment]
@rjtt17 本番環境で動作することを確認しました。

**Comment by rjtt17** [comment]
@komagata
お忙しい中、ご確認ありがとうございました🙇‍♂️
こちらのIssueをClose致します！
