### ISSUE TITLE
管理画面にコース作成・編集・削除が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2902]

**Comment by rjtt17** [comment]
@komagata
今週リリースされた[「管理画面にコース作成・編集・削除機能の追加」](https://github.com/fjordllc/bootcamp/pull/3239)の機能ですが、管理者向けの機能なので本番環境での動作確認をして、頂けないでしょうか？🙏

**Comment by komagata** [comment]
@rjtt17 本番環境で動作することを確認しました。

**Comment by rjtt17** [comment]
@komagata
お忙しい中、ご確認ありがとうございました🙇‍♂️
こちらのIssueをClose致します！
