### ISSUE TITLE
お知らせページの上部にコメント数表示が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2906]

**Comment by makiichikawa** [comment]
@komagata @machida 

お知らせ個別ページについて、Doc個別ページと同様にVueではなくHTMLで実装されているかと思います。
#3034 と同様にRails側で実装し、再読み込み後、正しいコメント数の表示されるということで問題ないでしょうか？？

確認のほどよろしくお願いいたします🙇🏼‍♂️

**Comment by machida** [comment]
@makiichikawa 今、他の部分は一旦、Railsで実装しているのですが、もし vue.js で挑戦したいなどありましたら、お願いしたいですー

**Comment by komagata** [comment]
@makiichikawa はい、問題ありません。

**Comment by makiichikawa** [comment]
@machida @komagata 

返信ありがとうございます。
一旦、このissueとしてはRails側で実装するということでお願いします🙇🏼‍♂️

**Comment by makiichikawa** [comment]
本番にて問題なく動作しましたので、クローズいたします。
