### ISSUE TITLE
フィヨルドミートアップの出欠管理をBootCamp上で行いたい

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/bootcamp#291]

**Comment by machida** [comment]
## 機能

- 必要なページ
  - 新規 meetup 作成
    - 開催日時
      - 基本、第一木曜日 19:30からなので、予め第一木曜日 19:30が選択されている状態だと楽かも。
    - タイトル
      - 2017年11月 meetup的な決め打ちだけど、忘年会だけイレギュラー
      - 予め定型タイトルが入ってると楽かも。
    - 説明文
      - 忘年会の場合は店なども書きたい。
      - 普段は大体定型文なので、予め定型文が入ってると楽かも。 
  - meetup 編集
  - meetup 個別ページ
  - meetup 一覧ページ 
- meetup user
  - user が meetupに参加すると意思表明できる
  - リモート or ローカル で参加する
  - コメント（XXXの発表をしたい、久々に参加します、遅れます などのコメント）
- meetupが終了したら、自動で終了した、とmeetup一覧のそのmeetupと、そのmeetupの個別ページに表示される
- meetup個別ページ
  - リモート、ローカル参加者を混ぜずに一覧をリモートとローカルを2カラムで分けて表示したい
  - リモート、ローカル参加者それぞれの合計数が表示されてほしい（ピザの注文で人数が必要なので）
- 通知
  - meetupを公開したら、internに通知がいく
  - meetupを公開したら、slack に @chanel で流れる

**Comment by machida** [comment]
@sanfrecce-osaka ざっくり機能を考えてみました

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/33976879-420958fc-e0db-11e7-9740-8b7866bea972.png)

**Comment by sanfrecce-osaka** [comment]
@machida meetupの説明文に入る定型文、どのようにしましょうか？

**Comment by machida** [comment]
@sanfrecce-osaka 

対応ありがとうございます！

---

リアルタイムでコミュニケーションを取る場としてミートアップを毎月開催しています。次回はXX月XX日19:30〜開催します。

お酒を飲みながらのゆるーい会です。この場を利用して、メンターや他の研修者の方々に相談、質問をしてください。参加される方はお酒や食べ物を用意して時間になったらパソコンの前に来てください。オフィスに来れる方はローカル参加もOKです。途中参加、途中退席、全然OKです。

ローカル参加の方は、当日の15:00までに参加表明（以下に登録）をお願いします。人数分のピザや寿司を注文します。

リモート参加（オンラインでの参加）の方は、時間になりましたら [https://appear.in/fjord-party](https://appear.in/fjord-party) こちらにブラウザでアクセスしてください。設定なしでビデオチャットが始まります。

---

上記でお願いします！

**Comment by sanfrecce-osaka** [comment]
@machida 承知いたしました。
2度手間で申し訳ないのですが、忘年会の場合も定型文を用意しておきますか？
それとも他の月と同じ定型文にしておきますか？
用意する場合は文章の提示をよろしくお願いいたします。

**Comment by machida** [comment]
@sanfrecce-osaka 
忘年会の定型文もあるといいかもですが、年に一回だけの手間なので、とりあえず無しで、対応するときは別issue、別PRでお願いしますー

**Comment by sanfrecce-osaka** [comment]
@machida 承知致しました。

**Comment by komagata** [comment]
@sanfrecce-osaka これってどうなりましたっけ？
