### ISSUE TITLE
退会フォームの退会理由に企業研修終了の項目を追加

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2911]
/retirement/new このページの退会理由の項目、

<img width="515" alt="貼り付けた画像_2021_07_01_0_16" src="https://user-images.githubusercontent.com/168265/123986790-95eb9980-da01-11eb-81df-ab76a2f1ea98.png">

`企業研修で利用をしていて研修期間が終了したため`

を追加お願いします。

**Comment by FUGA0618** [comment]
本番環境で確認できたのでcloseします。
