### ISSUE TITLE
退会者のアンケート結果を退会者個別ページに全て表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2912]
メンター、管理者だけが見える設定でここに項目を追加。

<img width="617" alt="貼り付けた画像_2021_07_01_0_38" src="https://user-images.githubusercontent.com/168265/123990401-afdaab80-da04-11eb-9d11-1ab0e3a7b44f.png">

**Comment by FUGA0618** [comment]
@komata @machida 
2点ほど仕様の確認をさせてください。

1点目は、表示する項目名についてです。
現状で表示されているのは、退会時にテキストで入力してもらう方の退会理由で、今回追加するのは退会時にチェックボックスで選択してもらう方の退会理由です。
それぞれの項目名を何にするか決めかねています。

例えば、テキストの方を「**退会理由の詳細**」、チェックボックスの方を「**退会理由**」とするのが良いかなと考えましたが、他に良い案や想定のものがありましたらご教示ください🙏

2点目は、チェックボックスで選択した退会理由を出力するにあたり、出力する形式についてです。
現在カンマ区切りで出力するように実装していますが、区切り文字の指定や改行を入れた方が良いなどありましたらご教示ください🙏

参考：上記の提案の場合の出力
![スクリーンショット 2021-07-17 10 09 33](https://user-images.githubusercontent.com/58870882/126020956-688f7052-9412-42db-ab08-14b59e3b4d6a.png)

**Comment by machida** [comment]
@FUGA0618 

まず、項目名ですが、一旦、

- 選択入力の退会理由
- 自由記入の退会理由

でお願いします🙏
あとでデザインを入れるときに変えてしまうかもしれないのですが、とりあえずこれでお願いしますー

表示の仕方ですが、選択入力の項目は、ul li でマークアップされてると助かりますー

**Comment by FUGA0618** [comment]
@machida 
ありがとうございます！
その方針で実装します😊

**Comment by FUGA0618** [comment]
本番環境で確認できたのでcloseします。
