### ISSUE TITLE
メンターモードで見えてしまっている項目がある

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2915]
退会日、退会理由の項目が見えてしまっている。

:memo: メンターモードを安全に実装する方法があまり思いつかない。

メンターモードがあることによって余計にセンシティブな情報が映ってしまう可能性が上がってしまうかも？

**Comment by machida** [comment]
@komagata 
メンターモードのありなしに関わらず、隠すべき情報はメンターにしか表示されていはないので、もしメンターモードがオフの状態で隠すべき情報がでてしまっていても、そこまで深刻な問題ではないとは思っています。都度、対応するでいいと思います。
メンターモードはメンターが画面共有をしたときや、キャプチャを撮ったときに、その情報を映さないことを目的としています。

**Comment by komagata** [comment]
@machida メンターモードがあることによって、メンターが積極的に画面を見せてかえって見えてしまうことがあるかなと思いました。

**Comment by machida** [comment]
@komagata 

なるほど、積極的に見せるためのものではなく、

「うっかり表示してしまった場合のダメージを減らすものということ」を

- 周知する
- 説明に追記する

を行いたいと思います。
