### ISSUE TITLE
ブックマークをボタンを押したら toastr のような通知でブクマしたことを知らせて欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2920]
クリックしたら、

![image](https://user-images.githubusercontent.com/168265/124208771-3b4a5e80-db23-11eb-8702-003bb2697635.png)

こんな感じの通知で、

![image](https://user-images.githubusercontent.com/168265/124208664-ffaf9480-db22-11eb-8924-af2bd06a2a22.png)

ブックマークしました、と知らせて欲しい。

toastrの参考（デザインはmachidaがやります）
https://codeseven.github.io/toastr/demo.html

**Comment by cafedomancer** [comment]
使用するライブラリの検討中 💭

* toastr: 1番使われていそうだけど jQuery 依存なので避けたほうがよさそう？
* sweetalert2: 依存がなくてよさそう
* (etc)

**Comment by komagata** [comment]
@cafedomancer いまjQuery外しのためのIssueも別で走っているのでできればjQuery使ってないのにしたいっすね🤭

**Comment by cafedomancer** [comment]
ラジャーです！

**Comment by cafedomancer** [comment]
sweetalert2 が一番 star 付いていたのでそれにしてみました。Vue 版の [vue-sweetalert2](https://github.com/avil13/vue-sweetalert2) というのもあるみたいですが、たぶん wrap しているだけであんまり使うメリットがなさそうなのでやめておきました。

**Comment by cafedomancer** [comment]
本場環境で動作することを確認したので close します！
