### ISSUE TITLE
提出物個別ページの担当者部分のデザインがずれている？

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2928]
[![Image from Gyazo](https://i.gyazo.com/8348761bf1ef543a994cb7068645aee5.png)](https://gyazo.com/8348761bf1ef543a994cb7068645aee5)

**Comment by machida** [comment]
本番で修正されていることを確認しましたー

**Comment by komagata** [comment]
@machida ありがとうございます！
