### ISSUE TITLE
メンションを送るときにユーザーIDを補完してほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#293]
長いIDのときに大変。
@を打ったら候補が出るようにしてほしい。

**Comment by bluerabbit** [comment]
triplefirstだとjquery-textcomplete使ってました。

https://qiita.com/yuku_t/items/7ddcc842d3d8f6a9fcd5
https://github.com/yuku-t/jquery-textcomplete/blob/master/doc/how_to_use.md
