### ISSUE TITLE
公開した日報をWIPに戻しても、この日報は公開済ですと編集画面に表示されてしまう

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2934]
現在、この表示は published_at があるかないかで判断し、ある場合は表示している。

<img width="1414" alt="貼り付けた画像_2021_07_15_1_39" src="https://user-images.githubusercontent.com/168265/125659844-07bf8a15-280b-488a-aabd-2ddae97ddd45.png">

ところが、一度公開した日報を wip に戻しても、 published_at は持っているので、wip 状態であるにも関わらずこの表示が消えない。

なので、日報が wip の場合はこの表示はしないようにして欲しい。

**Comment by udaikue** [comment]
@machida 質問させてください。

[![Image from Gyazo](https://i.gyazo.com/4c9646eb6cf3c4c66899796558ec1492.gif)](https://gyazo.com/4c9646eb6cf3c4c66899796558ec1492)

「内容修正」ボタンを押して出てくる「この日報はすでに〜」メッセージを表示させないようにする、つまり「内容修正」ボタンを押したらwip状態になるようにするということで合っていますか??

**Comment by machida** [comment]
@udaikue

いえ、公開中の日報を編集する場合は今の挙動のままです。

解決したい問題は、一度提出した日報をWIPに戻したとき、つまり未提出状態に戻したのに、この日報はすでに提出済みです、と表示されてしまっていることです。

---


一度提出した日報をWIPに戻す。

その日報を編集する。

現在はこの日報は提出済みです、と表示されてしまう。

WIPの日報を編集した場合は、一度提出したものであっても、この日報は提出済みです、とは表示しないようにしたいです。

一度提出した日報をWIPに戻さずに編集した場合は今の挙動のまま、つまり、この日報は提出済みです、と表示されるようにしてください。

**Comment by udaikue** [comment]
@machida ありがとうございますー！理解できました〜

**Comment by udaikue** [comment]
本番で確認できたのでcloseします。
