### ISSUE TITLE
通知に「全てタブで開く」ボタンが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2936]
![貼り付けた画像_2021_07_06_16_06](https://user-images.githubusercontent.com/168265/124557209-3283c080-de74-11eb-8b40-08ae8f2e763d.png)

**Comment by Daichi831** [comment]
こちら質問があります！
「未読の通知を一括で開く」ボタンの挙動についてです〜

### 現在メンターでログインし通知の「全ての未読通知」ボタンを押すと未読一覧が表示されます。
![image](https://user-images.githubusercontent.com/62867257/124886141-ef118980-e00e-11eb-843c-51064a756053.png)
![image](https://user-images.githubusercontent.com/62867257/124886373-22541880-e00f-11eb-98a1-627a8845f8ea.png)

### 未読一覧の一番下の「未読の通知を一括で開く」ボタンを押すと一番古い未読のページが表示されます。

![https://i.gyazo.com/257465ad20ed949696aed51c770e2f98.gif](https://i.gyazo.com/257465ad20ed949696aed51c770e2f98.gif)

こちらの挙動は正しい挙動でしょうか？
よろしくお願いします！🙇‍♂️

**Comment by komagata** [comment]
@Daichi831 正しい挙動ではないです。
全てのリンク先が新しいタブとして開くはずです～。
ブラウザの機能でポップアップブロッカーが働いてるとかかも？

**Comment by Daichi831** [comment]
ポップアップブロックを許可に変更したら無事全てのリンクが新しいタブで開かれました！
ありがとうございます🙇

**Comment by Daichi831** [comment]
- 全てタブで開く（未読のもの）の実装
現在、「未読の通知を一括で開く」ボタンはメンターだけに実装されているが今回の「全てタブで開く」ボタンは全員に実装する

**Comment by Daichi831** [comment]
本番環境で確認したためcloseします。
