### ISSUE TITLE
コメント、日報本文内のメンション（@XXXX）は、それがメンションであることがひと目でわかるようにしてほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#294]
↓ `@machida` のところ

![image](https://user-images.githubusercontent.com/168265/34344407-002f0902-ea29-11e7-8736-5d9d91f2656b.png)

**Comment by bluerabbit** [comment]
https://github.com/bluerabbit/shogi/blob/develop/app/javascript/models/markdown.js#L20-L36

将棋アイオーだとmarkdown-itのlinkify使ってますね。

**Comment by tosite0345** [comment]
将来的にはTwitterやSlackライクに `@名前` をクリックするとユーザーのモーダル画面を表示して、ユーザー画面に飛べるようになると嬉しいかもですね😍
あとは `@名前` があると本人に通知されたりとか…？
