### ISSUE TITLE
GitHubアカウントでのログインで、write 権限は渡したくない

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2941]
## 概要

GitHubのアカウントを連携しようと思ってプロフィール変更から GitHub と連携する を行おうとしたのですが、下記のスクリーンショットのように Personal user data にフルアクセスを要求されました。

read に関しては必要だと思うのですが write 権限まで渡すのはちょっと。。。という気持ちになりました。

公式サイトのドキュメントを見た感じscopeの指定が user になっているように感じました。read:user もしくは user:email に変更して write 権限の要求まではしないようにすることは可能でしょうか？

https://docs.github.com/ja/developers/apps/building-oauth-apps/scopes-for-oauth-apps

（フィヨルドブートキャンプのQ&Aより: https://bootcamp.fjord.jp/questions/963）

## 再現手順

GitHubアカウントでログインする。

----

![image](https://user-images.githubusercontent.com/168265/124869713-91744180-dffc-11eb-9e1a-db66e0431abb.png)

**Comment by gozasoro** [comment]
本番環境で確認できたのでcloseしますー！
