### ISSUE TITLE
解決済みQ&Aの一覧表示で、同じ質問が複数ページに表示されるケースがある

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2945]
本番環境のスクショしかないので、ここには貼りませんでした。
以下の確認をお願いします🙏
https://discord.com/channels/715806612824260640/828456619028381726/862849051748859915

**Comment by machida** [comment]
@komagata @harukus こちら原因わかりますかねー？

**Comment by harukus** [comment]
@machida ごめんなさい、#2697 が修正できたら解決できると思います🙇‍♀️

**Comment by machida** [comment]
@harukus 了解です🙆‍♂️ありがとうございますー

**Comment by komagata** [comment]
#2697 と重複しているのでCloseします。
