### ISSUE TITLE
ダッシュボードのお知らせ一覧の表示を公開日順にしてほしい

### ISSUE THREAD

**Issue by yana-gi** [fjordllc/bootcamp#2956]
**何故この機能が必要なのか**

現在お知らせ一覧は公開日順に表示されているが、ダッシュボードのお知らせ一覧では作成日順になっている。
ダッシュボードのお知らせ一覧でも公開日順に表示して欲しい。
というのもリリースノートなどの作成日と公開日があいているお知らせは、その間に公開されたお知らせが多いとダッシュボード上に表示されないケースが想定されるため。

**機能の説明**

同上

**Comment by komagata** [comment]
:memo: お知らせには公開日がないものもあるので実装方法は要検討。

**Comment by rikuba** [comment]
@komagata

実装方針について確認したいことがあります。

> お知らせには公開日がないものもあるので実装方法は要検討。

ダッシュボードでは公開日のない WIP のお知らせを表示しないようになっている (*1) ため、コントローラ側でお知らせの取得処理を変更して対応することを考えています。

- (*1) [/app/views/home/_announcements.html.slim#L1](https://github.com/fjordllc/bootcamp/blob/45da325d804e7e7b40137cf98bec2b0a0396bbce/app/views/home/_announcements.html.slim#L1)

[/app/controllers/home_controller.rb#L10-L12](https://github.com/fjordllc/bootcamp/blob/45da325d804e7e7b40137cf98bec2b0a0396bbce/app/controllers/home_controller.rb#L10-L12)

```diff
        @announcements = Announcement.with_avatar
-                                     .limit(5)
-                                     .order(created_at: :desc)
+                                     .where(wip: false)
+                                     .order(published_at: :desc)
+                                     .limit(5)
```

現状では WIP のお知らせの有無によってダッシュボードに表示されるお知らせの件数が変わる (このコメントを書いた時点では最新の投稿が WIP のため、4件のみ表示されている (*2)) のですが、この変更により公開日時が新しい5件が常に表示されるように変わります。問題ないでしょうか。

(*2) ![bootcamp_fjord_jp_dashboard_announcements](https://user-images.githubusercontent.com/350435/125737298-fb9d144d-e4b5-482e-9c02-a3cb90ffe7da.png)

**Comment by komagata** [comment]
@rikuba 

> 問題ないでしょうか。

はい。問題ありません。

ただ下記でwipじゃないものだけというunless文があること自体が変な感じがするので変えたいですね。

https://github.com/fjordllc/bootcamp/blob/45da325d804e7e7b40137cf98bec2b0a0396bbce/app/views/home/_announcements.html.slim#L1

もしほこのpartialが他から使われてないのであればこのunless文自体とってしまいたいです。（常にcontrollerでどういうものを表示するか決めるようにしたい）

**Comment by rikuba** [comment]
@komagata

ありがとうございます。

> このpartialが他から使われてないのであればこのunless文自体とってしまいたい

以下の確認を行い、`unless`文は不要と判断し、削除しました。

- app/views/home/index.html.slimの一箇所でのみ呼び出されていること

  https://github.com/fjordllc/bootcamp/blob/d4e17050943b8545ba4fe4f4b0ffff06aa8059d7/app/views/home/index.html.slim#L24

- home以外のviewからも`render 'home/announcements'`といった呼び出しがないこと

- `rails test:all`が通ること

- `rails server`してダッシュボード・お知らせ一覧の表示に問題ないことを確認

---

もう一点質問があります。現状、[home_test.rb](https://github.com/fjordllc/bootcamp/blob/main/test/system/home_test.rb)にはダッシュボードのお知らせに関するテストがない状態なのですが、このIssueではテストも用意した方がよいでしょうか。

**Comment by komagata** [comment]
@rikuba テストたしかにあったほうがいいですね！
細かく確認していただいてありがとうございます～！

**Comment by rikuba** [comment]
@komagata 
承知しました!

**Comment by rikuba** [comment]
本番環境で動作を確認したのでcloseします。
