### ISSUE TITLE
提出物編集ページでメンターは担当者を変更できるようにしたい。

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#2964]

**Comment by rjtt17** [comment]
@komagata @machida 
前回の計画ミーティングで詳細について確認できておらず申し訳ありません。
実装前に、このissueについて以下のイメージで問題ないか教えて頂けないでしょうか🙏

---

### 概要
メンターの場合に、```/products/:id/edit```のページで担当者を変更できるようにする。

#### ・ 提出物の担当者がすでにいる場合
現在の担当者が表示され、担当者名をクリックするとプルダウンと検索窓でメンターが表示され、変更できる。

![image](https://user-images.githubusercontent.com/52092916/126889385-9571e82b-c061-40e8-955c-c2c4360ec2d8.png)



#### ・  提出物の担当者がいない場合
担当者が決まっていないので空欄となり、空欄ををクリックするとプルダウンと検索窓でメンターが表示され、
担当者をアサインできる。

![image](https://user-images.githubusercontent.com/52092916/126889373-82d03a24-92a7-4d1a-8af5-d50f29d93c1f.png)

**Comment by komagata** [comment]
@rjtt17 はい、そのイメージで大丈夫です～

**Comment by rjtt17** [comment]
@komagata 
今週リリースされた[「提出物編集ページでメンターは担当者を変更できるようにする #3138」](https://github.com/fjordllc/bootcamp/pull/3138)の機能ですが、メンターさん向けの機能なので本番環境での動作確認をして、頂けないでしょうか？🙏

**Comment by komagata** [comment]
@rjtt17 本番環境で動作することを確認しました！

**Comment by rjtt17** [comment]
@komagata 
お忙しい中、ご確認ありがとうございました🙇‍♂️  
こちらのIssueをClose致します！
