### ISSUE TITLE
自分のプロフィールからタグを編集しても変更が反映されていない

### ISSUE THREAD

**Issue by obregonia1** [fjordllc/bootcamp#2971]
## 概要
自分のプロフィールページからタグを編集し保存するとタグ一覧には一時的に表示されるが、ページをリロードすると編集する前の状態に戻っている。

## 再現手順

1. 自分のプロフィールページにアクセス
2. タグ編集をクリックし、タグを編集し、保存するボタンをクリック
3. 一時的にタグ一覧に編集内容されているがリロードすると編集前の状態に戻っている(consoleにエラーが表示されている)

## スクリーンショット
- タグを編集して保存ボタンをクリック
[![Image from Gyazo](https://i.gyazo.com/4acfe717cd5d73440b7a993f37a9325f.gif)](https://gyazo.com/4acfe717cd5d73440b7a993f37a9325f)
- リロード後
![image](https://user-images.githubusercontent.com/75117116/125568361-24b288d4-35ab-4c62-b833-3700ac9fae7c.png)

## 関連Issue
#2226

**Comment by universato** [comment]
これ、｢このタグを自分に追加｣ボタンで追加はできるし、｢登録情報変更｣をクリックした先であれば追加も削除もできて、ここだけがバグってるんですね

**Comment by obregonia1** [comment]
@universato 
補足ありがとうございます！
そうなんですよね〜。おそらくAPI周辺の問題だと思うのですが。

**Comment by rjtt17** [comment]
本番にて問題なく動作しましたので、クローズいたします。
