### ISSUE TITLE
開発環境で「help」というslugを持った doc をseed に入れたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#2977]

**Comment by makiichikawa** [comment]
@komagata @machida 

issueの内容について確認させてください🙏

当issue#2997はref #2887 の前準備として行うissueだと考えています。
（現時点の開発環境では、スラッグがヘルプのデータがなく、ヘルプのドキュメント表示ができず、バグが確認できないかと思います）

先ほどスラグがヘルプとなるデータを１件追加し、ヘルプページに飛ぶボタンを押したのですが、データなしでエラーとなります。原因はヘルプページに飛ぶボタンはpage_id:334のドキュメントにリンクを張っているのですが、開発環境のデータには存在しないためです。

今回のissueとしてはドキュメントの登録件数が334件になるまでseedへの追加を行い、page_id:334になるドキュメントのスラッグをhelpとするということででしょうか？？
(当初、334件も登録すると思っていなかったため、少し不安になり、連絡いたしました。)

**Comment by komagata** [comment]
@makiichikawa #2751 こちらのIssueによって `/pages/help` というURLでヘルプページを表示できるようになっております。
ですのでdocsのseedに追加するのはそういうslugをもった1件だけで大丈夫です。

**Comment by makiichikawa** [comment]
本番に上がったため、クローズします。
