### ISSUE TITLE
ニコニコカレンダーをめくって日報のリンクに遷移しブラウザバックしても元のカレンダーを表示したい

### ISSUE THREAD

**Issue by obregonia1** [fjordllc/bootcamp#2982]
**何故この機能が必要なのか**
引用元 https://github.com/fjordllc/bootcamp/pull/2886#pullrequestreview-693650505
> カレンダーをめくってリンクから日報に遷移した後、ブラウザバックすると最新の月に戻ってしまうのは、ユーザビリティが低そうです。

引用の通りですが、過去のカレンダーに遡っていくつか日報を見たい場合に
`カレンダーをめくる -> 日報のリンクをクリック -> ブラウザバック -> 再びカレンダーをめくる`
を行う必要があるため
`カレンダーをめくる -> 日報のリンクをクリック -> ブラウザバック -> 日報に遷移する前に表示していたカレンダーを表示する`
に変更する。

**Comment by rikuba** [comment]
@komagata @machida

こちらのIssueの実装方針についてご相談があります。

ミーティングで、History APIを使ってURLに`year`や`month`といったパラメータを持たせることになっていましたが、将来的にイベントカレンダーも表示されるという話がありましたので、`#niconico_calendar=2021-07`といった形で持たせた方がいいように思いました。

また、History APIを調べていると、[History.state](https://developer.mozilla.org/en-US/docs/Web/API/History/state)を使ってURLに表出させずにデータを保存することができることが分かりました。

<dl>
<dt>`Hisotry.state`で実装した動作例
<dd>

[![Image from Gyazo](https://i.gyazo.com/fd020622d50548b39d23e44f8f5ee74e.gif)](https://gyazo.com/fd020622d50548b39d23e44f8f5ee74e)
（戻るのあとリロードしても2021年7月のままになります）

</dd>
</dl>

そこで、以下の疑問が出てきました。

1. 年月のデータをURLに含めるべきでしょうか
2. (URLに含める場合) パラメータ名は`year`と`month`で問題ないでしょうか

私としては、フロントのVue化を進めるうちにパラメータが増えていくことが懸念されるので、`history.state`に内部的にデータを持たせた方がよいかと思いました。ご意見を伺いたいです。

**Comment by komagata** [comment]
@rikuba 

> また、History APIを調べていると、History.stateを使ってURLに表出させずにデータを保存することができることが分かりました。

URLに影響を与えることが大事で、目的です。

なぜかというと、URLが現在の画面の状態を表現できていることが（HTTP、REST的に）重要で、例えばLINEなどでURLを他人に送ったとき、URLが画面の状態を表現できていれば同じ画面を見れますが、そのように実装していないとURLを受け取った人は別の画面を見ることになるからです。

> 1

はい。

> 2

はい。（ただおっしゃるようにniconicoカレンダー以外のカレンダーが出てきたときのためにそれと分かる名前がいいかもしれません。）

**Comment by rikuba** [comment]
@komagata 

ご返信ありがとうございます🙇‍♂️

URLに反映させることの重要性、理解致しました。`state`ではなくURLに状態を持たせるように実装します。

後からパラメータ名を変更するとそれまでのURLが機能しなくなるため、パラメータ名についてもあらかじめ「niconicoカレンダー用」の名前にしておきます。

**Comment by rikuba** [comment]
本番環境で動作を確認できたためcloseします。
