### ISSUE TITLE
今日の気分が選択されていない日報がカレンダーに表示される

### ISSUE THREAD

**Issue by obregonia1** [fjordllc/bootcamp#2987]
## 概要
今日の気分のカラムがnullの日報がカレンダーに表示されるとき代替画像が表示されている。

## 対応案
今日の気分が選択されていない日報の画像を別で用意するか、日報の今日の気分は必ず選択されているようにバリデーションをつける。

## スクリーンショット

![53yyi1119tyon6lhucdmtrdtixil](https://user-images.githubusercontent.com/75117116/125773643-9d4963c0-439d-4421-9ab9-0983710e0a4f.png)

**Comment by machida** [comment]
- バリデーションをつける
- 今、二コカレが null のものは「soso」を入れる rake タスクを流す

**Comment by unstoppa61e** [comment]
@machida 
> バリデーションをつける

こちらは、 #2352 で既に対応されているように思ったのですが、その認識で合っていますでしょうか？
追加で実装すべき点がありましたらお知らせくださいませ🙏
> 今、二コカレが null のものは「soso」を入れる rake タスクを流す

rake タスクの使用につきまして、こちらの [wiki](https://github.com/fjordllc/bootcamp/wiki/DB%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92migrate%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95) にて「データの変更には rake task を使わずに data-migrate という gem を使用するように」とあるのですが、その方針で実装してよろしいでしょうか？

**Comment by unstoppa61e** [comment]
本番環境で動作を確認できたため、close させて頂きました。
