### ISSUE TITLE
ニコニコカレンダー上で「今日」が強調されていると嬉しい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#2991]
「今日はもう日報書いた？てか今日は何月何日だっけ？」「この生徒さん、どれくらい日報書いてないんだろう？」というのをぱっと把握できるように、なんらかの形で「今日」がわかるようになってると嬉しいです。（下図は一例）

<img width="477" alt="Screen Shot 2021-07-16 at 18 56 28" src="https://user-images.githubusercontent.com/1148320/125930296-fc87b3e1-27ba-4014-a9ab-61915f353d46.png">

**Comment by FUGA0618** [comment]
本番環境で確認できたのでcloseします
