### ISSUE TITLE
アドバイザーとして、アドバイスを受ける側のユーザーをフォローしているときは、そのユーザーが新しい提出物を作成したらアドバイザーに通知が来てほしい＆提出物を自動で watch してほしい

### ISSUE THREAD

**Issue by cafedomancer** [fjordllc/bootcamp#2992]
**何故この機能が必要なのか**

企業研修でブートキャンプを使っているアドバイザーとして、アドバイスを受ける側のユーザーの提出物とそれにまつわるやり取りを都度確認したいと思っています。現状は、そのユーザーが新しい提出物を作成しても通知などは特に来ないので (フォローしていても) 、確認するのは難しい状況です。代わりの手段として、そのユーザーの提出物一覧ページを定期的に確認して、新しい提出物があれば都度 watch しています。

**機能の説明**

アドバイザーがアドバイスを受ける側のユーザーをフォローしているときは、そのユーザーが新しい提出物を作成したらアドバイザーに通知が来てほしい & 提出物を自動で watch してほしいです。ただ、いまのフォロー機能にこれを組み込むとフォロー機能の挙動が変わってしまい、ブートキャンプのユーザー全体が影響を受けることになるので、そこが懸念点になります。

**Comment by machida** [comment]
企業のアドバイザーとしてフィヨルドブートキャンプに参加した場合、自分が担当している研修生の活動を全てWatchする必要があります。そのための機能追加です。

## アドバイザーでログインをした場合だけ、一つ選択肢を増やします。

<img width="323" alt="貼り付けた画像_2021_12_07_13_24" src="https://user-images.githubusercontent.com/168265/144966083-6af62fe7-fcd2-4a9a-9b28-ff860ddabcfb.png">

## 追加項目

```
全てWatch

フォローしたユーザーの日報、提出物、Q&A を自動でWatch状態にします。日報、提出物、Q&A 投稿時の通知とそれらにコメントが来た際に通知を受け取ります。自分が担当している研修生の活動をWatchする際はこちらを選択してください。
```

## 「全てWatch」を選択すると

フォローしたユーザーの日報、提出物、Q&A を自動でWatch状態にします。

**Comment by yoshitaku-jp** [comment]
@machida 
```
全てWatch

フォローしたユーザーの日報、提出物、Q&A を自動でWatch状態にします。日報、提出物、Q&A 投稿時の通知とそれらにコメントが来た際に通知を受け取ります。自分が担当している研修生の活動をWatchする際はこちらを選択してください。
```

この部分の確認ですが、Watchされる対象は「全てWatch」ボタンを押したときに存在している日報、提出物、Q&A でしょうか？それとも「全てWatch」ボタンを押した後、研修生が日報、提出物、Q&Aを作成するたびに自動的にWatchとなる状態が正しいでしょうか？

**Comment by machida** [comment]
@yoshitaku-jp 

> Watchされる対象は「全てWatch」ボタンを押したときに存在している日報、提出物、Q&A でしょうか？それとも「全てWatch」ボタンを押した後、研修生が日報、提出物、Q&Aを作成するたびに自動的にWatchとなる状態が正しいでしょうか？

Watchされる対象は

- 「全てWatch」ボタンを押したときに存在している日報、提出物、Q&A 
- 「全てWatch」ボタンを押した後、研修生が日報、提出物、Q&Aを作成するたびに自動的にWatchとなる

両方でお願いしたいです。

アドバイザーはフィヨルドブートキャンプのアプリ上で行われている全ての行動を見れるようにし、わからないこと、頑張ったこと、わからなかったけど解決したことなどを見逃さないようにしたいからです。

**Comment by machida** [comment]
@yoshitaku-jp 

Watchの対象を

- 日報
- 提出物
- Q&A

としてましたが、

- 日報
- 提出物
- Q&A
- Docs
- イベント

も対象に含めるようお願いします🙏

**Comment by yoshitaku-jp** [comment]
@machida 

>Watchされる対象は
>「全てWatch」ボタンを押したときに存在している日報、提出物、Q&A

今回のissueの範囲から上記部分を取り除きたいです:pray:
理由としては下記です。

- ユースケース
  1. アドバイザーが後から入ってきて、過去のものをWatch状態にしたい用途が少ない
- 技術的
  1. すべての対象をWatchにするまでレスポンスを待たなければいけない
  2. Active Jobなどを使って非同期処理にすることも可能だが、「全てWatch」→「コメントなし」→「全てWatch」を即時クリックしたときの状態の変わり方など考慮する部分が多い

以前からmachidaさんも対応しなくても良いことをおっしゃっていたと思いますが、ペアプロ設計中に考慮しなければいけない点を確認したところ、上記点が見つかり結果的に今回は除いても良いのではないかと考えました。再考いただけると助かります。

**Comment by yoshitaku-jp** [comment]
📝 :ミーティングで話し合った結果、対象から外すことになりました:pray:

**Comment by yoshitaku-jp** [comment]
@machida 

## 機能が実装されていることの確認

先日梅本さんに確認したところ、元々欲しかった下記機能（アドバイザーとして、研修生の提出物の通知とWatch）については実装されているようです:pray:
すでにアプリ上で通知が来ていることも確認されておりました。

以下issueより引用
> 何故この機能が必要なのか  

>企業研修でブートキャンプを使っているアドバイザーとして、アドバイスを受ける側のユーザーの提出物とそれにまつわるやり取りを都度確認したいと思っています。現状は、そのユーザーが新しい提出物を作成しても通知などは特に来ないので (フォローしていても) 、確認するのは難しい状況です。代わりの手段として、そのユーザーの提出物一覧ページを定期的に確認して、新しい提出物があれば都度 watch しています。  

> 機能の説明  

>アドバイザーがアドバイスを受ける側のユーザーをフォローしているときは、そのユーザーが新しい提出物を作成したらアドバイザーに通知が来てほしい & 提出物を自動で watch してほしいです。ただ、いまのフォロー機能にこれを組み込むとフォロー機能の挙動が変わってしまい、ブートキャンプのユーザー全体が影響を受けることになるので、そこが懸念点になります。

## 欲しいかも？

- <s>日報</s> （実装済み）
- <s>提出物</s>（実装済み）
- Q&A
- Docs
- イベント

また、QAに関しては「研修生が起票したときに通知が来ると嬉しいかもなぁ」というご意見もいただけました。こちらは別issueとして起票したり、別で必要になったタイミングで実装するのはありかもしれません。重要性と緊急性は低いです。

Docsとイベントは作成する機会が少ないし、アドバイザーとして必要性があまりないとおっしゃっていました。

**Comment by machida** [comment]
@yoshitaku-jp 

> すでにアプリ上で通知が来ていることも確認されておりました。

確認、ありがとうございます！
もう少し確認をお願いしたいです。この確認はコードを見ての確認で大丈夫です。

- アドバイザーの場合ユーザーをフォローをすると、日報 、提出物の2つが自動でWatchになるが、アドバイザーではない role の人がユーザーをフォローをすると、日報だけが自動でWatchになる、ということで合ってますでしょうか？
- 現在、フォローは2種類（コメントあり、コメントなし）ありますが、上記の動作をするのは、「コメントあり」の方を選択した場合に限る、で合っていますでしょうか？

**Comment by yoshitaku-jp** [comment]
@machida 

>アドバイザーの場合ユーザーをフォローをすると、日報 、提出物の2つが自動でWatchになるが、アドバイザーではない role の人がユーザーをフォローをすると、日報だけが自動でWatchになる、ということで合ってますでしょうか？

いえ、すべてのユーザは、ユーザーをフォローをすると、日報だけが自動でWatchになります。
アドバイザーと研修生の関係性の場合だけ、フォローしてなくても日報 、提出物の2つが自動でWatchになります。

>現在、フォローは2種類（コメントあり、コメントなし）ありますが、上記の動作をするのは、「コメントあり」の方を選択した場合に限る、で合っていますでしょうか？

はい、日報が自動でWatchになるのは「コメントあり」だけです。

**Comment by machida** [comment]
@yoshitaku-jp 返信遅れてすいません🙇‍♂️

なるほど、

> アドバイザーと研修生の関係性の場合だけ、フォローしてなくても日報 、提出物の2つが自動でWatchになります。

念のための確認です。特に何もアクションをしなくても、研修生がアドバイザーと同じ企業に所属をしていたら、研修生の提出物、日報がWatch状態になるということですね。

この確認の通りであるなら、現状これで要望は解決できていて問題は起きていないので、Issueはcloseにしたいと思います！！

**Comment by yoshitaku-jp** [comment]
@machida 

> 特に何もアクションをしなくても、研修生がアドバイザーと同じ企業に所属をしていたら、研修生の提出物、日報がWatch状態になるということですね。

はい、こちらイエスです！

**Comment by machida** [comment]
@yoshitaku-jp 

確認ありがとうございます！！
では、今回のIssueの対応なのですが、

アドバイザーは研修生を何のアクションもなしでフォローになるので、さらにその研修生をフォローするなどが起きないようにしたいと思います。

アドバイザーでログインしているときに、自社の研修生には、以下のような表示にして、フォローボタンは表示しないようにお願いします🙏

<img width="485" alt="貼り付けた画像_2022_02_02_23_20" src="https://user-images.githubusercontent.com/168265/152172007-bc10c355-1a19-4e0e-acca-c11f6c173708.png">

デザインは僕が入れます。「自社研修生」はボタンっぽい見た目ですが、クリックはできなくするので、button ではなく div でお願いしますー
