### ISSUE TITLE
通知一覧をカテゴリ別に表示したい

### ISSUE THREAD

**Issue by yana-gi** [fjordllc/bootcamp#2997]
**何故この機能が必要なのか**

現在通知一覧（`/notifications`）ではどんな通知でもすべて同じ一覧で表示される。
この場合メンションやお知らせなどの重要な通知が他の通知に紛れてしまい気づきにくい。

現在の画面
![image](https://user-images.githubusercontent.com/67262644/126094493-a9ab5253-4383-4b84-9402-7b9500c94f5a.png)

**機能の説明**

通知一覧をカテゴリ別に表示する。
カテゴリの種類・全体/未読の切り替えは要検討。

画面案
![image](https://user-images.githubusercontent.com/67262644/126094445-f39ff957-ec07-4eac-988b-f986c8cc3ece.png)
![image](https://user-images.githubusercontent.com/67262644/126094456-fb1574f5-7094-4077-9bc2-c0d5994f0b1b.png)

**Comment by yana-gi** [comment]
@komagata @machida 

通知のカテゴリ別のタブに何を表示させるか、についての相談です

表示させる手段について大きく分けて2パターンあると思っています。
1. 全ての通知が何かしらのカテゴリに含まれている
2. 重要度の高い通知のみカテゴリ別に表示し、それ以外は「全て」にのみ表示させる

自分としては、2がいいと思っています。
というのも、1を採用しようとすると以下のことが懸念されるためです。
- カテゴリ数が多く表示するタブが多くなる
- 1つの通知でも2つ以上のカテゴリに含まれることが考えられる
例：Watch中の日報のコメントにメンションがあった場合など

そもそもカテゴリ分けをする目的は「重要度の高い通知を見逃したくない」ためなので、私は2がいいと考えています。
1と2、どちらのパターンがいいかkomagataさんとmachidaさんの意見をお聞きしたいです！

---

仮に2にする場合のカテゴリの素案も考えてみました。

カテゴリ名 | 表示する通知の種類
-- | --
全て |  
お知らせ | announced
メンション | mentioned
コメント(回答) | came_comment, answered
提出物の確認 | checked
Watch中 | watching
フォロー中の日報 | following_report


参考：`notification.rb` のkindの定義
```ruby
  enum kind: {
    came_comment: 0,
    checked: 1,
    mentioned: 2,
    submitted: 3,
    answered: 4,
    announced: 5,
    came_question: 6,
    first_report: 7,
    watching: 8,
    retired: 9,
    trainee_report: 10,
    moved_up_event_waiting_user: 11,
    create_pages: 12,
    following_report: 13
  }
```

**Comment by komagata** [comment]
@yana-gi 僕も2でいいとおもいます～

カテゴリ案もそちらで大丈夫かなとおもいます～

**Comment by yana-gi** [comment]
@komagata 
承知しました！
ひとまずこれで作業を進めてみます〜

**Comment by yana-gi** [comment]
@komagata
ルーティングに関して相談させてください。


現在の /notificationsのルーティングは以下のようになっています。

通知の絞り込み | URL
-- | --
全て | /notifications
未読 | /notifications/unread

今回通知にカテゴリを追加するにあたってどのようにルーティングをどうすればいいか、パターン考えてみました。

### 案１
unreadのルーティングはそのまま
`?target=<カテゴリ名>`でカテゴリ名を絞る

通知の絞り込み | URL
-- | --
全て | /notifications
未読 | /notifications/unread
「お知らせ」カテゴリ全て | /notifications?target=announce
「お知らせ」カテゴリ未読 | /notifications/unread?target=announce

### 案２
`?query=unread `で未読を絞る
`?target=<カテゴリ名>`でカテゴリ名を絞る

通知の絞り込み | URL
-- | --
全て | /notifications
未読 | /notifications?query=unread
「お知らせ」カテゴリ全て | /notifications?target=announce
「お知らせ」カテゴリ未読 | /notifications?query=unread&target=announce

自分は案２の方ががいいと考えています。
というのも、画面案の階層は
`通知` > `カテゴリ` > `未読 or 全て`
という構成になっていますが、案１だと
`通知` >  `未読 or 全て` > `カテゴリ`
のような構成に見えてしまうと思ったためです。

この件に関して komagataさんの意見をお聞きしたいです。
実装側のことはあまり考慮していないので、別の案や考慮点があればお教えください🙏

**Comment by yana-gi** [comment]
メモ📝
- 今回のスコープでは「全て既読にする」ボタンはすべて既読のまま。カテゴリ別の一斉既読機能を実装する場合は別途issueを立てる
- 現在はデフォルトで「全て」を表示しているが、デフォルトで「未読」を表示させるよう変更する。

**Comment by komagata** [comment]
@yana-gi 案２でいいようにおもいます～！

**Comment by yana-gi** [comment]
@komagata 
承知しました〜！

**Comment by yana-gi** [comment]
@komagata  (CC: @cafedomancer )

クエリパラメータで指定するの未読/既読ステータスの件での相談です。

前回[提案した内容](https://github.com/fjordllc/bootcamp/issues/2997#issuecomment-890900249)では、
未読/既読ステータスを`/notifications?query=unread`のように`query`で指定していましたが、
`/notifications?status=unread`と`status`で指定する方がいいと思っています。
というのも、
- パラメータの内容が分かりやすい
- 将来的に他のクエリが追加されることｆ

**Comment by yana-gi** [comment]
@komagata 
クエリパラメータに関して、追加で確認させてください。

カテゴリステータスの`target`も`category`に変更してもよろしいでしょうか。
というのも実装していく中で`target`ではなく`category`を使った方が処理が分かりやすいことに気づいたためです。

上のコメントに合わせて２点ご検討お願いします🙏

**Comment by komagata** [comment]
@yana-gi はい、そちらでも構いません。
ただ、bootcampにはすでにCategoryモデルがあるので、そちらと混同しないようになっていないか確認してみてください〜

**Comment by cafedomancer** [comment]
> ただ、bootcampにはすでにCategoryモデルがあるので、そちらと混同しないようになっていないか確認してみてください〜

あーなるほどー。category をもし避けるとしたら group とか set (kind set) とか type とかですかねー。

**Comment by cafedomancer** [comment]
それか path のほうを工夫して

* all
  * /notifications
  * /notifications/announcement
  * /notifications/mention
  * ...
* unread
  * /notifications?status=unread
  * /notifications/announcement?status=unread
  * /notifications/mention?status=unread
  * ...
 
とか。all と unread しかないのであれば boolean で unread=true とかでもよいかも。

**Comment by yana-gi** [comment]
@cafedomancer 色々と案を挙げていただいてありがとうございますー！参考になります！

---

開発ミーティングで話したこと・決めたことのメモ📝

- 通知のカテゴリの指定は静的セグメントではなくクエリ文字列で行う
    - 通知のパラメーターが今後増える可能性がある
    - 今後のissueで「全て既読にする」ボタン(`/notifications/allmarks`)をカテゴリ別に実装するならすべてクエリ文字列のほうがよさそう
    - 静的セグメントとクエリ文字列どちらにするかは実装者の好みの問題でもある by komagataさん
- 通知のカテゴリの指定は`target`のままにする
    - `category`はすでにモデル名が存在するため
    - `admin/users`でもクエリ文字列に`target`を使用しているため

後ほど最終的に決まった仕様をPRの方にまとめておきます。

**Comment by yana-gi** [comment]
こちら本番環境で動作確認したためcloseします
