### ISSUE TITLE
プラクティスと参考書籍を多対多の関係に修正したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3000]
現在はプラクティスと参考書籍が一対多の関係になっているが、複数のプラクティスに同じ書籍が出てくる場合があるので多対多に修正したい。

## 実装

- 参考書籍のCRUD（管理画面）を作る。
- プラクティスの追加・修正画面で登録されている参考書籍を選んで登録できるようにする。
- 既存のデータを移行できるようにする。（data migrationのスクリプトを書く）
- reference_bookというモデル名になっているが、bookに変えて欲しい。今までは別の仕組みがbookという名前を使っていたがなくなったので申う使えるため。

**Comment by rjtt17** [comment]
@komagata 
昨日は、マイグレーションが失敗した為、本について登録頂きありがとうございました🙇‍♂️

今週リリースされた https://github.com/fjordllc/bootcamp/pull/3426 の機能ですが、以下の部分について管理者・メンター向けの機能なので本番環境での動作確認をして、頂けないでしょうか？🙏

- 参考書籍のCRUD（管理画面）を作る。
- プラクティスの追加・修正画面で登録されている参考書籍を選んで登録できるようにする。

**Comment by rjtt17** [comment]
お忙しい中、ご確認ありがとうございました🙇‍♂️
