### ISSUE TITLE
コメント通知が来ないタイプの日報フォロー機能が欲しい

### ISSUE THREAD

**Issue by yana-gi** [fjordllc/bootcamp#3007]
**何故この機能が必要なのか**

現在の日報フォロー機能では、フォローしているユーザーが日報を投稿すると自動でWatch状態になる。
自動Watchになるということはフォローしているユーザーが日報を投稿した時、また日報にコメントがついた時に通知がくる。

自分は日報の投稿だけを知りたいため、現行の日報フォロー機能（自動Watch）に加えてコメント通知が来ない「日報購読機能」が欲しい。
~~さらにユーザー個別に日報を自動Watchにするか・購読にするかを選択できるようにしたい。~~
さらに**フォローするユーザーごとに**日報を自動Watchにするか・購読にするかを選択できるようにしたい。

**機能の説明**

日報購読機能では、購読しているユーザーが日報を投稿した時のみ通知が来るようにする。
~~ユーザー個別に日報を自動Watchするか・購読するかを選択できるようにする。~~
フォローするユーザーごとに日報を自動Watchするか・購読するかを選択できるようにする。

**Comment by machida** [comment]
@yana-gi 

Issue登録ありがとうございます！！

yana-giさんも考慮していると思うのですが、このIssueを見た人に知っていただきたいので、共有させていただきますー

---

フォロー機能というものがある。
フォロー機能には、

- 自動Watch
- 日報購読

の二択があり、自分のフォロー設定はそのどちらにするかを選ぶ。

---

...という仕様だったとき、
「自動Watch」に設定していたのを「日報購読」に設定を変更したら、ユーザーは今までフォローして自動でWatchされていたもののWatchが全て解除されて、日報購読に切り替わることを期待するかと思います。

Watchには、フォローしたことによって自動でWatchになった日報の他に、自分でWatchしたもの、自分が日報にコメントをしたのでWatchになったものがありますが、なぜその日報がWatchになったのかの情報は持っていないので、フォローしたことによって自動でWatchになった日報だけWatchを外すということが出来ません。

となると、フォロー機能には

- 自動Watch
- 日報購読

の二択があって、どちらにするかを設定する、という仕様だと、途中で切り替えるときに厄介なことになりそうなので、

- 自動Watch
- 日報購読

は別々のものとした方が良さそうです。

---

## これだと問題がある

自分の登録情報へ移動

<img width="255" alt="貼り付けた画像_2021_07_21_23_48" src="https://user-images.githubusercontent.com/168265/126509122-bc500e6f-0d84-4f54-b47e-f49302f60446.png">

フォローをどちらにするか選ぶ

![image](https://user-images.githubusercontent.com/168265/126509808-36288469-db01-442a-b115-d6f73d0445f8.png)

選んだフォローに従って通知が来る

<img width="400" alt="貼り付けた画像_2021_07_21_23_47" src="https://user-images.githubusercontent.com/168265/126509040-56c18be8-c8c4-4771-bef1-2eae0e9a85d9.png">


## これなら良さそう

<img width="407" alt="貼り付けた画像_2021_07_21_23_55" src="https://user-images.githubusercontent.com/168265/126510461-9df4113b-b622-4a40-88c6-a26c4236fe08.png">

フォローしているユーザー一覧ページで、

- すべて
- 自動Watch
- 日報購読

で、絞り込むことができる。

<img width="1174" alt="貼り付けた画像_2021_07_21_23_58" src="https://user-images.githubusercontent.com/168265/126511076-178d7dcb-7a5a-429c-82ed-1f78af36cf5c.png">

**Comment by yana-gi** [comment]
@machida 
補足の共有ありがとうございます！
画面イメージがあるととても分かりやすいです🙏

> さらにユーザー個別に日報を自動Watchにするか・購読にするかを選択できるようにしたい。

自分が書いた上記の文言だと前者（問題がある方）と捉えてしまいそうですね。

「さらに**フォローするユーザーごとに**日報を自動Watchにするか・購読にするかを選択できるようにしたい。」に修正しておきました。

**Comment by ima1zumi** [comment]
もし複数種類の通知を選択できるようにする場合、 GitHub の リポジトリの Watch 機能のようにプルダウンで選べるといいのかなと思いました。
![image](https://user-images.githubusercontent.com/52617472/126589427-a1d6b8e1-d478-4780-8a43-cad31b088210.png)

**Comment by yana-gi** [comment]
@machida さん達と質問タイムにて決まったこと・話したことのメモ📝

## 名前の変更
自動Watch　→　コメント通知あり 
日報購読　→　コメント通知なし

### 変更の理由
- 「自動Watch」「日報購読」の2つに非対称性を感じる
- 「Watchあり」「Watchなし」でも非対称性を解消できるが、`Watch` という言葉は新規ユーザーには分かりにくい
- プルダウンの表記であれば説明欄にWatchの仕様の説明を入れることができる（下イメージ）
![Pasted Graphic 33](https://user-images.githubusercontent.com/67262644/132009179-ddb131e1-dea9-4e4e-be58-15c52c444819.png)

### issueのスコープ外で検討する必要がありそうなこと
- 今後フォロー機能を日報に限らずWatchできるもの全てフォローできるようにしたい場合は、名称を再検討する必要がありそう
- Watch機能についてもっと周知させる必要がありそう

**Comment by yana-gi** [comment]
こちら本番環境で動作確認しましたのでcloseします。

**Comment by yana-gi** [comment]
📝
フォロー機能の改修にあたって、フォロー機能を説明するDocsを修正した
https://bootcamp.fjord.jp/pages/303

差分
https://gist.github.com/yana-gi/24fb40a9e95d293d6db67b4636eb800a/revisions?short_path=35c6a30#diff-35c6a300694e690a49a1c5397ef34613231febefb1cd5880694daa1706394095
