### ISSUE TITLE
Q&A一覧ページの並び順を質問作成日順にしたい

### ISSUE THREAD

**Issue by obregonia1** [fjordllc/bootcamp#3015]
## 概要
~~Q&Aの一覧ページでの質問の表示順序は一般的には`質問の作成日`の降順で表示されますが、そのようにはなっていないようです。少しだけですが原因調査をしてみました。~~

~~- 質問の概要欄に投稿者、タイトル、日付が表示されているがこの日付が更新日時になっている~~
~~- 解答が投稿される度に日付が更新されるので質問の概要欄に表示される日付は最新の解答投稿日時になる~~
~~- 質問を更新日時でソートしてから降順で表示している~~

(追記)
このIssueの意図としては質問の作成順で表示すると、「古い質問に回答が来るたびに一番上に表示され、新しい質問が目に付きにくくなる」ことが回避されると思ったからです。

**Comment by universato** [comment]
Q&Aの回答日時で｢最新の質問･回答の作成日｣で並ぶことは、いいことだと思います。
何か新しい回答がきたときに、他の人の目にもそれがわかっていいからです。
特に解決済みのものに関しては、回答も含めて作成日で並ぶべきと考えます。

ただし、｢質問･回答の**更新日時**｣でソートすべきとは思えません。
更新の際の情報は誤字やタグづけ等の些細なもので、情報を知らせる価値が低いと考えられるためです。

**Comment by komagata** [comment]
@obregonia1 

> Q&Aの一覧ページでの質問の表示順序は一般的には質問の作成日の降順で表示されますが

そうとは限らないような？

**Comment by obregonia1** [comment]
@komagata 
そうですね。個人的な見解を書いてしまいました💦

**Comment by machida** [comment]
> ただし、｢質問･回答の更新日時｣でソートすべきとは思えません。
> 更新の際の情報は誤字やタグづけ等の些細なもので、情報を知らせる価値が低いと考えられるためです。

僕もupdated_at ではなく、最新のコメント順がいいと思ってますー

**Comment by komagata** [comment]
@obregonia1 これにはいろんな人の意見があると思うので、「バグ」ではなく改善案として話会えればと思います～（バグのタグは外しておきますね～）

また、タイトルもバグで「期待通りではない」という日本語表現だと「自分だけがそう思ってる個人的な意見」なのになぜかバグになっている（自分の好みじゃなかったらバグ？）という意味合いになっちゃうかもなので、たとえば、

Issue title：「Q&Aの並び順を質問作成日順にしたい」
description：なぜなら、～～～だとおもうからです。

みたいな感じにするのがいいかもです～

**Comment by obregonia1** [comment]
@komagata 
ありがとうございます！
Closeしようかと思ったのですが修正して残しておきます〜

**Comment by universato** [comment]
#2135｢解決済みのQ&Aのソート順(並び)を解決日時順か新規コメントの作成日時順にする｣
↑
ちなみに、｢**解決済み**のQ&Aのソート順｣については自分がIssue立ててたようで、
どういう理由でどういう順番になって欲しいか等を簡単に書いてるので、
何か並び順が変わるようであれば読んでいただきたいです。

なお、フィヨルドブートキャンプのQ&Aの｢**未解決**｣だとせいぜい4個とかそんなに溜まらないので、未解決のものに関しては並び順がそれほど気にならないかもしれないです。新規作成の質問が埋もれないように最初に来るべきというのも一理あると思う一方で、回答が新規にあったらそれもわかりたいし回答も埋もれないようになって欲しい気がします。

あと、自分自身｢全ての質問｣タブの方は見に行ってなく、どういう用途で使われているのかわからないので、特別意見がないです。
