### ISSUE TITLE
提出物に未アサインタブを追加する。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3021]
将来的にこのようにしたいのですが、その第一弾として、このIssueを分離しました。
https://github.com/fjordllc/bootcamp/issues/2005

----

今、メンターでログインをすると、提出物のタブがこの様になっています。

<img width="867" alt="貼り付けた画像_2021_07_24_23_45" src="https://user-images.githubusercontent.com/168265/126872081-ce68f3d2-1208-4cb7-8e09-c7fe941ca977.png">

未返信の右側に「未アサイン」というタブを増やしてください。

<img width="867" alt="貼り付けた画像_2021_07_24_23_45" src="https://user-images.githubusercontent.com/168265/126872099-4e7b9123-85be-4a83-b5d4-bfc8c61d5419.png">

現在、未返信のタブには、以下のように提出日から 5日目、6日目、7日目を表す帯が表示されています。このリストはVue.jsで実装されています。

![image](https://user-images.githubusercontent.com/168265/126872111-9eeb9b22-ff6b-40c4-9036-a531334c4fc8.png)

「未アサイン」を選択すると、

- まだ担当メンターが決まっていない、かつ未完了の提出物一覧が表示される
- 一覧には現在の未返信と同じように、提出日から 5日目、6日目、7日目を表す帯が表示される
- 「未アサイン」のタブには、まだ担当メンターが決まっていない、かつ未完了の提出物の数が表示されている
- Vue.js で実装する

このようにしていただきたいです。

**Comment by FUGA0618** [comment]
@komagata 
こちら、メンターさん向けの機能のため本番環境での動作確認をお願いしたいです🙏
確認項目は以下のとおりです。

- 提出物一覧ページ（`/products`）にアクセスして、「未アサイン」タブが表示されているか
- 「未アサイン」タブをクリックして、担当者が決まっていない提出物の一覧が表示されているか
- 担当者が決まった際や外れた際に、表示される件数が連動して変化しているか
- 「未アサイン」タブに表示されている件数と、左側の「提出物」メニューい表示されている件数が一致するか

お手数ですがよろしくお願いいたします🙏

**Comment by komagata** [comment]
@FUGA0618 上記全て確認しました。問題ありませんでした。実装ありがとうございます！

**Comment by FUGA0618** [comment]
@komagata ご確認ありがとうございました🙏動作確認していただいたのでcloseします。
