### ISSUE TITLE
メンターモードのクリック領域が狭い

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#3025]
メンターモードのクリック領域が狭く、間違ってクリック領域以外をクリックしてしまうと、ダッシュボードに移動してしまいます。
上下左右のマージンもメンターモードのON/OFFとして機能する or マージンクリック時はダッシュボードに移動しないようにする、というふうにしてもらえると嬉しいです。

<img width="398" alt="Screen Shot 2021-07-25 at 10 28 26" src="https://user-images.githubusercontent.com/1148320/126884829-77ce9f48-4ae1-4d4c-b6ff-8dec19110592.png">

**Comment by machida** [comment]
こちら修正しましたー！！
