### ISSUE TITLE
ユーザーアイコンのmarkdownを使った時に通知が届かないようにしたい

### ISSUE THREAD

**Issue by gozasoro** [fjordllc/bootcamp#3033]
現在ユーザーアイコンを`:@username:`のように書いてmarkdownで表示すると、メンション扱いになっており通知が届く状態です。絵文字のように使うなら、通知がない方がいいかも。

### 実装手順
メンションの通知は[mentionable gem](https://github.com/komagata/mentionable)で実装されている。
`:@`から始まる文字列はメンションとして判定されないようにする。

https://github.com/fjordllc/bootcamp/search?q=mentionable_as

**Comment by yana-gi** [comment]
私は自分のことが言及されていたら知りたいので、現在のまま（メンション扱いのまま）の方が嬉しいです！

**Comment by komagata** [comment]
@gozasoro ネタ元のesa.ioだとメンション扱いなんですよね。

僕もesaでそう使ってるから個人的にはそのままの方が嬉しい派かな～

**Comment by gozasoro** [comment]
なるほど、元々のほうもメンション扱いなんですねー！
確かに言及されてたら通知がきた方がいい気がします！参考になりました、ありがとうございます（ということでclose）！
