### ISSUE TITLE
通知メールの本文が表示されない（絵文字しか見えない）

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#3035]
通知メールの絵文字しか表示されてないようです。

<img width="1005" alt="Screen Shot 2021-07-27 at 10 29 49" src="https://user-images.githubusercontent.com/1148320/127080548-52999e9b-541b-483d-9204-be423bb17fa5.png">

https://bootcamp.fjord.jp/reports/34182#comment_67968

**Comment by JunichiIto** [comment]
この影響？
https://github.com/fjordllc/bootcamp/pull/2990/files#diff-96ff6af734f7a03cbf8e6c9d87194ed644dd4d0fc2d5655cea238f7d70b6c11d

**Comment by gozasoro** [comment]
自分が実装した`new UserIconRenderer().render(selector)`をコメントアウトしたらローカルではちゃんと通知されました💦
原因を調べてみます、すみません

**Comment by gozasoro** [comment]
と思ったら違いました...メールのHTML自体に本文が入っていますが、表示されていない状態みたいです。
https://github.com/fjordllc/bootcamp/blob/b82c2949623321a6ed3b6b1e5def9348cd93b2c3/app/views/notification_mailer/_notification_mailer_template.html.erb#L13-L15
ここの`div`タグを1つ前のコミットに置き換えたら表示されてます〜

**Comment by gozasoro** [comment]
https://github.com/fjordllc/bootcamp/blob/04cd2a7ac49f6591268bff7eb08b00f06cb592a4/app/views/notification_mailer/_mailer_style.html.erb#L55-L57
https://github.com/fjordllc/bootcamp/blob/b82c2949623321a6ed3b6b1e5def9348cd93b2c3/app/views/notification_mailer/_notification_mailer_template.html.erb#L12-L16
前回のコミットのコード
```
<td style="word-wrap:break-word;font-size:0px;padding:16px 24px 16px 24px;" align="left">
  <div style="cursor:auto; font-family:sans-serif; font-size:14px; text-align:left;" class='a-long-text'>
    <%= yield %>
  </div>
</td>
```
`div`タグのstyleが削除されており、`td`タグの`font-size: 0px`を参照しているため本文が表示されていないみたいです！

**Comment by gozasoro** [comment]
というか、 @JunichiIto さんが貼ってくれてたコードがピンポイントでそこでしたね...お騒がせしました...💧

**Comment by JunichiIto** [comment]
@gozasoro いえいえ、僕は単に「メールの問題だからmailerのコードが変わったんじゃない？」と雑に推測してリンクを貼っただけです。詳細な調査ありがとうございました！

@machida ということなので、該当コードをいったんロールバックするか、他の適切な方法で修正してもらえると助かります〜。

**Comment by JunichiIto** [comment]
修正されていたのでクローズしますー。
https://github.com/fjordllc/bootcamp/pull/3046
