### ISSUE TITLE
Docsの該当プラクティスのスタイルをQ&Aと同じものにして欲しい

### ISSUE THREAD

**Issue by yana-gi** [fjordllc/bootcamp#3036]
**何故この機能が必要なのか**
[\#3008](https://github.com/fjordllc/bootcamp/pull/3008)でDocsにWatchボタンをつけたことで、該当プラクティスの表示が分かりにくくなったため。

**機能の説明**
現在のDocs画面
![image](https://user-images.githubusercontent.com/67262644/127093551-dd1045af-70ba-4bf7-ac30-74c11fd3e9ca.png)

変更後のイメージ（Q&A画面）
![image](https://user-images.githubusercontent.com/67262644/127093560-d10c229c-0afb-4718-b778-ac24251d3a48.png)

**Comment by machida** [comment]
修正を確認したのでcloseしますー
