### ISSUE TITLE
提出物に最終コメント日時（commented_at）が欲しい。

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3038]
日報や提出物など全てに最終コメント日（commented_at）カラムをつけたい。

最終コメント日で並び替えたりしたいため。

**Comment by machida** [comment]
- こちらUIは変更せず、カラムの追加のみ
- 実装後にカラムに値を流し込む rake タスクも作成する

**Comment by komagata** [comment]
@gentamura すみません、こちら、まずはProductに対してだけでお願いしたいです〜
