### ISSUE TITLE
markdownでユーザーアイコン取得のリクエストが文字入力の都度発生する

### ISSUE THREAD

**Issue by mh-mobile** [fjordllc/bootcamp#3041]
## 概要

markdownでユーザーアイコンを表示した後に、文字入力する度にユーザーアイコン取得のリクエストが発生する。
※ 複数のユーザーアイコンを表示した場合は、複数のユーザーアイコン取得のリクエストが発生します。

## 再現手順

1. /reports/new
2. アイコン表示記法を使用する
3. 何か文字を入力する
4. DevToolsで通信を確認する

## 期待される振る舞い

アイコン表示記法を使った後に、文字入力するごとにアイコン取得の通信リクエストを行わない。

## スクリーンショット

![image](https://user-images.githubusercontent.com/13811034/127178915-f6d2d0e3-e961-4de8-b2c7-8f1bd336e74d.png)

## 環境

 - OS: macOS 11.4
 - ブラウザ:  Chrome 92.0.4515.107

## 関連Issue

Ref: #2958

**Comment by mh-mobile** [comment]
再現動画


https://user-images.githubusercontent.com/13811034/127181474-6159ced6-28f2-4071-b445-581b151c29cf.mov

**Comment by mh-mobile** [comment]
markdownにドラッグした普通の画像でも発生するので、ユーザアイコン取得機能の固有の問題ではなさそう。

**Comment by gozasoro** [comment]
markdownのプレビューがテキストエリアに書き込むたびに再描画されるんですよね

**Comment by mh-mobile** [comment]
他の2ペイン構成のmarkdownのサービスでも同様に都度画像取得されるので、これが一般的な挙動みたいですね。

-   https://stackedit.io/
-   https://dillinger.io/
-   http://marxi.co/  
-   https://hackmd.io/

**Comment by mh-mobile** [comment]
markdownのサービスの正常な挙動と思われるので、一般issueをクローズします。
