### ISSUE TITLE
メンター用の提出物ページでプラクティスメモを編集・保存してリロードした時の挙動に差異がある

### ISSUE THREAD

**Issue by FUGA0618** [fjordllc/bootcamp#3044]
## 概要

提出物個別ページでメンターモードをONにすると、画面右側にメンターのみが確認できるブロックが表示されます。
そのブロックの「プラクティスメモ」を編集・保存(またはキャンセル)した後にブラウザをリロードすると、「このサイトを再読み込みしますか？」というモーダルが表示されます。

<img width="685" alt="スクリーンショット 2021-07-28 16 29 02" src="https://user-images.githubusercontent.com/58870882/127281989-5d05feca-4363-40bc-91cd-b400d1cf8144.png">

一方、同一ブロック内の「ユーザーメモ」で同様の操作をした場合には、モーダルは表示されません。

## 再現手順

1. /products/{practice_id}にアクセス
1. メンターモードをONにする
1. 画面右側のブロックにある「プラクティスメモ」をクリック
1. 「編集」をクリック
1. 内容を編集して「保存」または「キャンセル」をクリック
1. cmd + Rなどでブラウザをリロードする

## 検討事項

- どちらの挙動を正とするべきか
    - 保存完了後なので、モーダルが表示される必要はなさそう？

## 環境

- ブラウザ: chrome

**Comment by cafedomancer** [comment]
SFC の template で指定している `.js-warning-form` クラスで `warning.js` スクリプトが動作しているのが原因ではないか。プラクティスメモでもメンターメモでも `.js-warning-form` クラスは指定されているので同じ挙動になるはずだけどそうはならない。これは `warning.js` スクリプトでは `DOMContentLoaded` イベントを起点に対象の DOM 要素にハンドラを設定しており、そのイベントが発火したタイミングでは Vue のレンダリングが完了していたりしていなかったりするせいかもしれない。`warning.js` の挙動をもう少し詳しく調査してみる。

**Comment by cafedomancer** [comment]
上記が原因のようなので  #3095 に詳細を書いてみました。

**Comment by cafedomancer** [comment]
@komagata こちらメンターさん向けの機能に関する部分なので動作確認をお願いしたいです！ 確認内容を以下に書いておきます。

- [ ] 提出物ページのプラクティスメモで「編集」を押したあとにリロードしようとすると確認ダイアログが表示される
- [ ] 提出物ページのユーザーメモで (同上)
- [ ] 提出物ページのプラクティスメモで「編集」を押したあとに「保存する」or「キャンセル」を押してリロードしようとしても確認ダイアログが表示されない
- [ ] 提出物ページのユーザーメモで (同上) 

以下は自分でも確認できそうなのでやります！

- [ ] Q&Aページの submit 済みの質問の「内容修正」を押したあとにリロードしようとすると確認ダイアログが表示される
- [ ] Q&Aページの submit 済みの回答の (同上)
- [ ] 日報ページの submit 済みのコメントの「編集」を押したあとにリロードしようとすると確認ダイアログが表示される

**Comment by komagata** [comment]
@cafedomancer 上記動作確認しました。正常に動作することを確認しました。ありがとうございます〜！

**Comment by cafedomancer** [comment]
動作確認ぜんぶ終わったので close です！
