### ISSUE TITLE
【メンター向け機能】画面の横幅を開くと「直近の日報」欄の表示が崩れる

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#3081]
表題の通りです。
27インチモニタでブラウザを全面表示したりするとタブのヘッダとボディがズレます。

<img width="2114" alt="Screen Shot 2021-08-03 at 7 23 08" src="https://user-images.githubusercontent.com/1148320/127931372-427faccb-603d-46f8-be7b-ad57905e8796.png">

該当ページ https://bootcamp.fjord.jp/products/8820

**Comment by machida** [comment]
修正を確認したのでcloseしますー
