### ISSUE TITLE
新規Doc作成の文言変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3084]
![image](https://user-images.githubusercontent.com/168265/128191709-816bf2d7-b2ba-4a7c-9180-bf1677a37f50.png)

↓

![image](https://user-images.githubusercontent.com/168265/128191811-d3e45e4b-f134-44de-850b-d8e840806d8c.png)

2箇所くらいあると思うので、検索してみてくださいー

**Comment by masamune17** [comment]
本番環境で確認できたのでcloseします
