### ISSUE TITLE
ページ遷移のない textarea で autosize の発火のタイミングがおかしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3085]
## 再現手順

長文のコメントを書いて保存。

![image](https://user-images.githubusercontent.com/168265/128204514-17676d3b-468e-411a-b3ce-7e1cb3538ef5.png)

内容修正をクリックする。

![image](https://user-images.githubusercontent.com/168265/128204639-c579f6a0-a0cf-4e92-9952-68c5283c8814.png)

文字の分量だけ大きくなってくれない。

<img width="891" alt="貼り付けた画像_2021_08_05_0_01" src="https://user-images.githubusercontent.com/168265/128204735-5ae04539-b34c-4977-af0f-98f01b5afd1b.png">

textarea 内で何かしらのキーを打つと textarea が大きくなる。

## こうしたい

内容修正をクリックした時点で、文字の分量だけ textarea が大きくなってほしい。

## これが起きている textarea

- 各コンテンツのコメント
- メンターでログインしたときに見れる提出物個別ページの右カラムにあるユーザーメモ
- メンターでログインしたときに見れる提出物個別ページの右カラムにあるプラクティスメモ

**Comment by cafedomancer** [comment]
あーこれは直したいですね…！

**Comment by cafedomancer** [comment]
以下のときに resize されるみたい。
```javascript
	window.addEventListener('resize', pageResize, false);
	ta.addEventListener('input', update, false);
	ta.addEventListener('autosize:update', update, false);
```
https://github.com/jackmoore/autosize/blob/d32047a7c06d81fedb12e0e9bfdd108e3a0a68f1/src/autosize.js#L200-L202

**Comment by cafedomancer** [comment]
「上記のイベントで height が update される」イコール「内容修正ボタンを押して textarea が表示されたタイミングでは height は update されない」ということなので、内容修正ボタンを押したときは明示的に `autosize.update` を呼び出す or `autosize:update` イベントを dispatch  すれば修正できそうです。

**Comment by cafedomancer** [comment]
本番環境で直っていることを確認できたので close します！
