### ISSUE TITLE
通知一覧ページにある「全てを別タブで開く」機能をメンター以外のユーザーも使えるようにする

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3097]
<img width="825" alt="貼り付けた画像_2021_08_05_20_38" src="https://user-images.githubusercontent.com/168265/128343937-022893b4-d167-4dfa-bed8-f5ea076766e2.png">

- この部分はメンターにしか表示されないようになっているので、メンター以外のユーザーに対しても表示する。
- メンターしか見えない部分には `.is-only-mentor` という class が付いているが、メンター以外のユーザーも表示するようになるので、このclassを削除する。

<img width="458" alt="貼り付けた画像_2021_08_05_20_40" src="https://user-images.githubusercontent.com/168265/128344102-daa685d3-b0fd-44b4-998d-dab5c935391f.png">

**Comment by machida** [comment]
受講生は一気に開いて片っ端からチェックをしていくという使い方はしないとのことなのでcloseします。
