### ISSUE TITLE
分報リンクからDisocrdアプリを開いても分報チャンネルが開かない

### ISSUE THREAD

**Issue by rikuba** [fjordllc/bootcamp#3101]
## 概要

ユーザーのプロフィールやユーザー一覧ページの「分報」リンクをクリックしても、Discordアプリで当該チャンネルを開けない。

## 再現手順

1. ユーザー一覧（`/users`）にアクセス
2. 「分報」リンクをクリック
3. Discordアプリで読み込みが行われるが、空白のチャンネルが表示される
   （Webでそのまま「Discordで開く」ボタンを押すとWeb版で分報チャンネルが表示される）

## 期待される振る舞い

Discordアプリで対象の分報チャンネルが表示される

## 関連Issue

Ref: #3020

**Comment by rikuba** [comment]
@mh-mobile さんからDiscordのURLについての情報をいただきました（ありがとうございます🙇‍♂️）。

https://discord.com/channels/715806612824260640/825925849327992882/861445012919156736

このURLの通り、DiscordのメッセージのURLは `https://discord.com/channels/:server_id/:channel_id/:message_id` になっています。末尾の `/:message_id` を取り除くとチャンネルのURLになります（招待URLで「Discordで開く」ボタンを押したときに遷移する先のURLに一致します）。

また、スキーム（プロトコル）部を`https`から`discord`に変えると、Discordアプリで開かれるURLになります。

## #3020 の問題点

### 分報URLとして登録するURLとして招待URLが相応しくない

- 招待URL：`https://discord.gg/:invite_id`
- チャンネルURL：`https://discord.com/channels/:server_id/:channel_id`

現在はvalidationによって前者しか登録できないため、前者ではなく後者を登録できるようにします。

### リリース済みのため既に分報URLを登録された方がいる

登録済みの招待URLをどのように処理すればよいか検討中です。

**Comment by mh-mobile** [comment]
気になった点があったので書いてみます。

分報リンクにdiscordのURLスキームを指定した場合は、分報のリンクをクリックした際に、DiscordアプリがマシンにインストールされていればDiscordアプリを開くことができます。ただし、インストールされていない場合は何も起きない問題がありますね。（実際にMacのDiscordアプリを削除して試しました。）

理想的には、DiscordアプリがインストールされていればDiscordアプリが開き、インストールされていない場合はWebのDiscordが開く感じかと思いました。

これを実現する一つの方法としては、タイムアウトでリダイレクトする方法があるかと思います。

[How can I check if an app is installed from a web-page on an iPhone](https://stackoverflow.com/questions/13044805/how-can-i-check-if-an-app-is-installed-from-a-web-page-on-an-iphone)
※ これはiPhoneの例ですが。。

テスト観点では、Mac、Winodows、Linux、iPhone、Android環境などの動作環境も考慮が必要になるかと思います。

**Comment by mh-mobile** [comment]
あっ、上記のタイムアウトでリダイレクトする方法も、Discordアプリの起動した際にダイアログが表示されるので、実現不可かもしれません。

![image](https://user-images.githubusercontent.com/13811034/128453021-870811aa-b402-4ed4-9d2d-2b160cfde1f8.png)

**Comment by mh-mobile** [comment]
代替案として、Webの分報リンクとDiscordアプリの分報リンクの２つを用意して、ユーザーに選択させるやり方もあるかもしれません。

**Comment by mh-mobile** [comment]
Slackのリダイレクト方式も良さそうです。

外部のワークスペース起動の例ですが、起動用のリダイレクトのページに遷移させて、アプリがインストールされていれば起動用のダイアログが表示され、アプリがインストールされてなかれば直接Webのワークスペースに遷移します。
どう実現しているかは、詳しく分からないですが。。

起動用のダイアログでキャンセルを押下すれば、Webページに遷移することもできるので、個人的に上手い方法だなと思いました。

## 起動前の画面
![slack_1](https://user-images.githubusercontent.com/13811034/128456120-09156885-ba4a-4935-b2ae-8993b7cd1472.png)

## 起動用のリダイレクト画面
![slack_2](https://user-images.githubusercontent.com/13811034/128456147-cb2d4f35-5a14-4b45-b8f6-03bac2806eef.png)

**Comment by rikuba** [comment]
@mh-mobile 

追跡調査ありがとうございます🙇‍♂️

> 理想的には、DiscordアプリがインストールされていればDiscordアプリが開き、インストールされていない場合はWebのDiscordが開く感じかと思いました。

Discordアプリをインストールしていない環境からのアクセスを考えていませんでした💦 Web版を使用しているユーザーや、普段と違う環境からのアクセスする場合などあり得ますね。

---

開けないプロトコルを指定したリンクに遷移したとき、ブラウザのコンソールに`Failed to launch 'fake://test' because the scheme does not have a registered handler.`というエラーメッセージが表示されるのですが、これはJavaScriptではcatchできないようです。

```javascript
window.addEventListener('error', (e) => {
  console.log('window.onerror', e);
});

try {
  location.href = 'fake://test'
} catch (e) {
  console.log('catch', e);
}

// どちらの`console.log`にも到達せず、エラーメッセージが表示される
```

また、`fetch`/`XMLHttpRequest`ならエラーハンドリングできるのではないかと思ったのですが、プロトコルが異なるとアクセスできませんでした😓

`<a>`要素+JavaScriptで実現できないかなと思いましたが、難しそうです（この点、インストールされているアプリを確認できるのはセキュリティ上の問題になるのかもしれないと思いました）。

Slackのリダイレクトを試してみると、アプリがインストールされているとWeb版の方ではそれを検知して「デスクトップアプリにリダイレクトしました。」というメッセージが表示されますね😮 Webもアプリも同じSlackのサーバに接続するからこそ実現できているのかなと思いました。

---

mh-mobile さんがご提案された

- Webの分報リンクとDiscordアプリの分報リンクの2つを用意する
- リダイレクトページを用意して、`location.href = 'discord://...'`しつつ、ページにはWeb版のリンクボタンを表示しておく

のいずれかがで対応するのがよさそうです。

**Comment by mh-mobile** [comment]
スマホにおける懸念事項を見つけたので書きます。

スマホのDiscordアプリのURLスキームは、MacアプリのURLスキームと異なる可能性があります。
少なくとも、iPhoneのDiscordアプリのURlスキームは、`com.hammerandchisel.discord://` であるため、`discord://` ではiPhoneのDiscordアプリを開くことができません。
※ Androidについては、少し調べてみましたが、わかりませんでした。

### iPhoneのURLスキーム例
```
com.hammerandchisel.discord://discordapp.com/channels/715806612824260640
```

つまり、独自にリダイレクトで制御する場合、スマホからのアクセスを判定して、URLスキームを変更する必要がありそうです。

ちなみに、iPhoneのSafariブラウザから招待リンクのURLをクリックすると、Discordアプリを起動することはできました。

参考: [iPhoneアプリのURLスキームまとめページ](https://urlschemesiphone.information.jp/def/)

**Comment by mh-mobile** [comment]
Discordの招待リンクに含まれるFirebase Dynamic Linksのクエリに以下の値が含まれていたので、Androidのスキーム名は、`com.discord:// `かもしれません。
※ 実際に試してない

apn=com.discord、ibi=com.hammerandchisel.discord

参考: [ダイナミック リンク URL を手動で構築する](https://firebase.google.com/docs/dynamic-links/create-manually?hl=ja)

**Comment by rikuba** [comment]
Android 10のChromeで`com.discord://`のURLのリンクを並べてタップしてみたのですが、何も起きませんでした。
Androidはプロトコルを変えるだけではダメなのかもしれません。

<dl>
<dt>USBデバッグでChrome for AndroidのコンソールをPCで表示
<dd>

![image-20210807142202790](https://user-images.githubusercontent.com/350435/128589170-25bbeade-ab3e-4fd6-9c1c-2d22174ef1f0.png)

</dl>

一方、通常の`https://`のリンクをタップするとどのアプリで開くかのダイアログが出てきました。Androidユーザー向けには通常のリンクを表示するだけで十分かもしれません。

<dl>
<dt>通常のチャンネルURLをタップしたとき
<dd>

<img src="https://user-images.githubusercontent.com/350435/128589154-24be6191-64b5-4e77-ae79-75978b6e466b.png" width="360">

</dl>

---

このような形になるでしょうか。

- Androidなら`<a href="https://チャンネルURL">分報</a>`表示
- 他のOSなら`<a href="リダイレクトページ">分報</a>`を表示
  - リダイレクトページでは`<a href="https://チャンネルURL">ブラウザでDiscordを開く</a>`を表示しながら、
    - iOSなら`com.hammerandchisel.discord://チャンネルURL`にリダイレクト
    - 他のOSなら`discord://チャンネルURL`にリダイレクト

**Comment by mh-mobile** [comment]
@rikuba 

> 一方、通常のhttps://のリンクをタップするとどのアプリで開くかのダイアログが出てきました。
Androidユーザー向けには通常のリンクを表示するだけで十分かもしれません。

あっ、なるほど。
Androidはインテントの仕組みがあるので、それで良さそうですね。

> アプリで開くことを考慮すると、このような形になるでしょうか。

これも、よさそうですね！

**Comment by komagata** [comment]
@rikuba @mh-mobile 不要にコードが複雑になるとよくないので、ブラウザで開くことができればOKです～！
