### ISSUE TITLE
【メンター向け機能】提出物・未返信タブの「n日経過」ラインを日時レベルではなく、日付レベルで切り替えたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#3109]
提出物・未返信タブの「n日経過」ラインは日時レベルで変動しているように見える。

たとえば以下の画像のような状況であれば、8月9日の11:35をすぎると、上から2つ目の提出物が「5日経過」のラインに移動する。

<img width="831" alt="Screen Shot 2021-08-09 at 9 03 36" src="https://user-images.githubusercontent.com/1148320/128649724-838d98f5-af09-4364-9737-82dedfa52f58.png">

そのため、1日の間に「n日経過」の件数がコロコロ変動してしまう。

「今日の残りは何件」という情報は1日中変動しない方が嬉しいので、「n日経過」のラインがAM0時を境に変動しないような動きになるとありがたい。（提出物の提出日時の時刻部分を無視して、「提出日」として経過日数を算出するのが良さそう）

## 検討ポイント
りほやんがアメリカにいるので、「日本時間の0時」で切り替えると、りほやん的には都合が悪い？
何かご意見があればよろしくお願いします > @rlho

**Comment by komagata** [comment]
@JunichiIto 

> 今日の残りは何件」という情報は1日中変動しない方が嬉しいので

これって何故でしょう～？

**Comment by JunichiIto** [comment]
メンターとして、

「げっ、5日経過が10件もあるやん！頑張って減らさないと！！」
↓
「ふう。なんとか3件まで減らしたぞ〜 💪 」
↓
（数時間経過）
↓
「えっ、なんで7件に増えてるの！？」

という気持ちになるのは、UX的に気持ちよくないからですー。
（件数が減るぶんにはリアルタイムで減ってほしいが、件数が増えるタイミングは1日1回で良い）

**Comment by komagata** [comment]
@JunichiIto なるほどです。
僕は最後の時間からきっちり7x24時間の方がありがたいかな～と感じておりました。
