### ISSUE TITLE
今のフォロー機能の名前を変える

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3113]

**Comment by yana-gi** [comment]
📝
- 変更する内容は画面上の項目のみ。モデル名等は変更しない
- 日報フォロー機能 → 自動Watch機能（もっといい名前があったらそちらにする）

**Comment by yana-gi** [comment]
こちらhttps://github.com/fjordllc/bootcamp/pull/3225 でRevertしたためcloseします。

**Comment by yana-gi** [comment]
こちら本番環境で確認したためcloseします
