### ISSUE TITLE
特定のテストがタイミングによって落ちたりパスしたりするのを修正したい

### ISSUE THREAD

**Issue by FUGA0618** [fjordllc/bootcamp#3126]
## 概要
タイミングによって落ちたりパスしたりと安定しないテストがあるので、常にパスするようにしたいです。
具体的には以下のテストです。

https://github.com/fjordllc/bootcamp/blob/66f78e0e2c5289e678074ea55bbf6f93fdca6799/test/system/users_test.rb#L211-L218

### 予測
GitHub Actionsのタイムゾーン設定がUTC（世界標準時）となっていて、アプリケーション側のタイムゾーン設定がJST（日本時）になっているからではないかと思われます。

### 根拠
日本時間で午前9時前のPRでは当該テストが落ちていたが、午前9時以降のテストはパスしていたため。

## 解決方法
GitHub Actions側のタイムゾーン設定をJSTにすれば解決するのではないかと考えます。
公式にはタイムゾーン設定について言及されていませんでしたが、参考URLを貼っておきます。

参考：
[GitHub ActionsでTimezoneを設定 \- Minerva](https://minerva.mamansoft.net/Notes/GitHub+Actions%E3%81%A7Timezone%E3%82%92%E8%A8%AD%E5%AE%9A)

**Comment by FUGA0618** [comment]
@komagata 本番反映後しばらく様子を見ていましたが、いまだにこの問題が解決していないようなので引き続き対応します🙇🏻‍♂️

**Comment by JunichiIto** [comment]
全然実装は見てないですが、`target_day = find('.niconico-calendar__day.is-today').text`で取ってくる日付が、ブラウザのJS内で`new Date`とかで生成されていると、問題が複雑になりそうな気がします。（すべてサーバサイドで完結しているなら、すべて`Time.current`や`Date.current`を使うようにしろ、で解決するんですが）

**Comment by FUGA0618** [comment]
@JunichiIto 
なるほど…！その視点は全然持てていませんでした。ありがとうございます🙇🏻‍♂️
実装を見るとニコニコカレンダーのvueファイルの中で`new Date`を使っていますね。

https://github.com/fjordllc/bootcamp/blob/2194e5ad0de4447b5b739ad0b0972e7893f9a937/app/javascript/niconico_calendar.vue#L221-L223

こちらの方向でも調査してみようと思います

**Comment by FUGA0618** [comment]
JSTに合わせる方法として↓の記事などを見ると、

- `new Date`で取得する日時は実行するマシンのタイムゾーンに依存する
- `Date#getTimezoneOffset`で取得できる値を足してJSTに調整する

という方法があるようです。
[JavaScript で実行環境に左右されず常に JST 日本時間を取得する \- Neo's World](https://neos21.net/blog/2020/12/09-01.html)

ただ、現状ローカルでは時間帯関係なくテストがパスしているということは、上記の方法を取ると今度はローカルでのテストがパスしなくなる気がしています。。。

**Comment by JunichiIto** [comment]
@FUGA0618 やっぱりJSでしたか。

> ただ、現状ローカルでは時間帯関係なくテストがパスしているということは、上記の方法を取ると今度はローカルでのテストがパスしなくなる気がしています。。。

この方法は初耳でした。僕が知ってるのは以下のブログ記事で説明しているように、JSのDateをモック（スタブ？）に置き換えて日時を固定する、という方法です。

[Rspec、Capybaraを使ったfeature specでJavaScript側でも指定した時間で固定できるHelperを作った \- Madogiwa Blog](https://madogiwa0124.hatenablog.com/entry/2019/11/24/140617)

↓こんなふうにすればワンチャンあるかも？

```ruby
class UsersTest < ApplicationSystemTestCase
  include TravelToJavascript

  test 'show mark to today on niconico_calendar' do 
    today = Time.current 
    trabel_to today
    visit_with_auth root_path, 'hatsuno' 
    travel_to_javascript(page, today) do
      visit user_path(users(:hajime).id) 
      assert_selector '.niconico-calendar__day.is-today' 
      target_day = find('.niconico-calendar__day.is-today').text 
      assert_equal today.day.to_s, target_day 
    end
  end 
end
```

ただ、この方法は知ってるだけで実際にやったことはないです。。

**Comment by komagata** [comment]
@FUGA0618 マシンというか、このJSを実行してるブラウザのTimezoneに合わせたものになるんじゃないかと思うので、固定するんじゃなくてそのブラウザのTimezoneを設定できるといいかな〜と思います。

**Comment by FUGA0618** [comment]
@JunichiIto 具体例までありがとうございます🙇🏻‍♂️
JSの日時をRailsに合わせられれば問題解決しそうですね。
@komagata が仰るようなTimezoneを設定する方法もあるかと思うので、調査しつつ方針をまたこちらに書きたいと思います。

**Comment by FUGA0618** [comment]
@komagata 
時間がかかってしまいすみません。
調べてみたところ、seleniumのChromeドライバーにはTimezonを設定するオプションがないみたいです。
[Class: Selenium::WebDriver::Chrome::Options — Documentation by YARD 0\.9\.26](https://www.selenium.dev/selenium/docs/api/rb/Selenium/WebDriver/Chrome/Options.html)

「ブラウザのTimezoneを設定する」だとseleniumになるかなと思いましたが、他の方法は考えられますでしょうか？
また、もしなければこのissueの対応方針を相談させていただきたいです🙇🏻‍♂️

ブラウザのTimezoneを設定できないとすれば、方針として考えられるのは

- テスト内でJSの日時を固定する形にする
- テスト自体を日時に依存しない形に変更する

あたりかなと考えています。

**Comment by komagata** [comment]
@FUGA0618 マシン自体のTimezoneは適切に設定できてる感じですかね？

**Comment by FUGA0618** [comment]
@komagata テスト失敗時のログを見る限り、できているように思います🙇🏻‍♂️

**Comment by komagata** [comment]
@FUGA0618 タイムゾーンを合わせずみんなテストできないと思うので一般的な対応方法がありそうな気がします。

> - テスト内でJSの日時を固定する形にする
> - テスト自体を日時に依存しない形に変更する

これらはトリッキーな対応なのでできれば他の方法でできればな〜と思います。

例えば、Timezoneだけを調べるテストを用意して、調査するなどはできないでしょうか？

もし無理であれば僕がやります〜

**Comment by FUGA0618** [comment]
@komagata 
> 例えば、Timezoneだけを調べるテストを用意して、調査するなどはできないでしょうか？
これはぜひやってみたいと思っていたので、試させてもらいたいです。
ではいったん、Timezoneを確認するためのテストを用意してPR送りたいと思います！

ちなみにこちらは、アサーションを使ってTimezoneを確認する形で良いのでしょうか？
予測が外れた場合、次のPRで修正するまで落ち続けるテストになってしまうのは問題ありませんか？

**Comment by komagata** [comment]
@FUGA0618  timezoneが何に設定されるのかに絞って、最小限のサンプルを作って確かめたりできないかな〜という意味です〜。

**Comment by komagata** [comment]
@FUGA0618 僕の書き方がわかりづらかったですね、すみません。

自分のリポジトリに最小限のサンプル（timezoneをテストするだけのサンプルやjsのdateがrubyのdateと一致していることを調べるテストだけがあるサンプル）を作ってそこで調査すると良いかもです〜。

**Comment by FUGA0618** [comment]
@komagata 
いえ、詳しくご説明いただきありがとうございます！
なるほど、自分のリポジトリにサンプルを作ればいいのですね〜
その方法で調査してみます！
