### ISSUE TITLE
【メンター向け機能？】日報ページに「直近の提出物（または直近の日報、またはその両方）」が載っていると嬉しい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#3130]
提出物ページには最近、直近の日報が表示されるようになりました。
<img width="1050" alt="Screen Shot 2021-08-14 at 7 09 34" src="https://user-images.githubusercontent.com/1148320/129422989-1aa94ebf-9a80-44c7-a68b-3c8748cfe6a6.png">

これがメンターとしては生徒さんがどういう気持ちで提出物に向き合っているのか、ぱっと確認できてなかなか便利です。

この逆バージョンで日報ページに直近の提出物が表示されれば、この生徒さんが今どのあたりのプラクティスを進めているのか、ぱっと確認できて便利なんじゃないかな〜と思いました。
（まだあまり活用できていないが、ユーザーメモのタブがあっても良さそう）

<img width="1131" alt="Screen Shot 2021-08-14 at 7 16 00" src="https://user-images.githubusercontent.com/1148320/129423321-51e7263f-b8dd-42e6-924d-c5ca85fb3f0a.png">

**Comment by JunichiIto** [comment]
この件、直近の提出物だけでなく、直近の日報も見たいかも。むしろそっちの方が重要？

過去に投稿された日報のタイトルを見て「この人はここ最近、こういうことでハマってるのか」とか、今見てる日報よりも新しい日報があることに着目して「この日報では○○がわからない、って書いてあるけど、最新の日報では解決してるかもしれないな」ということが一画面上で把握できそうなので。

**Comment by machida** [comment]
@JunichiIto 直近の日報を表示する機能がリリースされました。一旦こちらをクローズして、別Issueとして、提出物の一覧を表示する機能を進めていきたいと思います〜
https://github.com/fjordllc/bootcamp/issues/3740

**Comment by JunichiIto** [comment]
@machida ありがとうございます！
