### ISSUE TITLE
各プラクティスの『所要時間の目安』を非表示にする

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#3145]
**何故この機能が必要なのか**
現在プラクティス一覧には各プラクティスの『所要時間の目安』が表示されています
質問雑談タイムで実際にかかる時間とかなり違う、目安時間をすぎると焦るという話を聞き、自分でも確認してみたのですが確かにボーリングの所要時間目安が9時間になっていて、プラクティス自体の難易度と所用時間的には9時間で終わる人は少数派で、あまり信頼できる数値ではないと思います。
信頼できない数値で、不用意に受講生を焦らせてしまう可能性があるので改修したいです

**機能の説明**
対応方法はいろいろあると思うのでまちださんに相談させていただきたいです。
今回問題に思っているポイントは『不用意に受講生を焦らせたくない』こと、でこれを解決できる方法であってほしいです。

個人的に難易度別に3案あるかなと思っているので書いておきます。この解決方法でなくても大丈夫です。

松: 日報ベースではなく、実際に課題を始めた時間と(提出する or 提出物合格)時間をDBに保存し精度の高い時間を表示する
竹: 所要時間の表示の仕方を『 9時間30分 』のような書き方ではなく『平均時間〜1σ or 2σ 』にする
梅: 所要時間の目安自体を削除

**Comment by machida** [comment]
@rlho

ありがとうございます。
なぜこの数字が現実の数字から離れてしまったのか検証が必要だと思います。

> 松: 日報ベースではなく、実際に課題を始めた時間と(提出する or 提出物合格)時間をDBに保存し精度の高い時間を表示する

これに関しては、一日30分学習をしているや、8時間学習する人などがいるので、難しそうです。

> 竹: 所要時間の表示の仕方を『 9時間30分 』のような書き方ではなく『平均時間〜1σ or 2σ 』にする

これが現実的ではあると思うのですが、そもそも今のデータに現実の数字から離れてしまっている原因が含まれている事自体が問題だと思うので、それを特定し、それを取り除くロジックを計算に入れたいと思います。

原因の特定と、計算方法の改善が終わるまでは、今表示している時間は表示しないようにしたいと思います。

なので、まずは

> 梅: 所要時間の目安自体を削除

これで対応し、

今のデータに現実の数字から離れてしまっている原因の特定と、それを含めないように計算を改善する、

を別Issueとして対応していこうと思います。
