### ISSUE TITLE
プラクティスにかかる所要時間の算出に使っているデータに中央値を狂わすデータが含まれていないか調査をしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3149]
プラクティスにかかる所要時間には、受講生それぞれの日報に記録されたプラクティスと時間から、中央値と平均値を算出している。

中央値と平均値が大きく離れている、実際にかかる時間は中央値を大幅に超える（受講生の声より）、という問題が起きている。

中央値の算出の際に、学習時間が極端に短いものが含まれている可能性が考えられる。

そのような、中央値を狂わすデータが中央値算出の際に含まれていないかを調査をお願いします。

もしそのようなデータがあったら、そのデータを省いてから中央値、平均値を算出するように計算方法の改善をお願いしたいです。

**Comment by komagata** [comment]
@machida こちら調べてみたところ、データが多くなり過ぎて過去の時点からタイムアウトで動いてなかったようです。確認しておらずもうしわけありません。

今のまま普通にCloud Runで動かすのは無理があるので何か考えたいと思います。
