### ISSUE TITLE
コース毎のカテゴリーの並び替えが動いていない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3182]
categories_coursesにpositionカラムがないので実装されていない？っぽい。

`/courses/1/categories`こういうURLにあるページのコース別のカテゴリー並び替えが実装されてないので実装したい。
（現状はコースに関係なく、カテゴリーの並び順は一つになっている）

**Comment by cafedomancer** [comment]
あーいまは category の positon だけが変わっているので course ごとの category が並び替っていないってことですね。複数の courseにまたがるような category だと course に関わらず position が変わってしまう的な。

**Comment by cafedomancer** [comment]
Oh... ここ has_and_belongs_to_many になっているのか。いくつか作業が必要そうですね。

* 中間テーブルを普通の model にする
* 並び替えたときに categories_courses を update するように変更する
* practices の一覧に categories (categories_courses) の並び替えが反映されるようにする？

**Comment by cafedomancer** [comment]
@komagata こちら動作確認をお願いしたいです！複数のコースにまたがるカテゴリを各コースの中で並べ替えてもお互いに影響がないことを確認してもらえると OK だと思います。

**Comment by komagata** [comment]
@cafedomancer こちら本番環境で動作することを確認しました。修正ありがとうございます！

**Comment by cafedomancer** [comment]
確認ありがとうございます！では close します。
