### ISSUE TITLE
企業別のユーザー一覧で、「研修生」「全て」の区分けが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3183]
<img width="1506" alt="貼り付けた画像_2021_11_04_22_36" src="https://user-images.githubusercontent.com/168265/140323130-1019a28a-15c4-4d24-8849-07b4b61d2fc5.png">

左メニューからの「ユーザー」と同じように「現役生」「全て」の区分けが欲しい。デフォルトは「現役生」になっていて欲しい。

## 理由

企業ユーザーが増えてきて、研修がすでに終わった人と現在研修中の人の区分けがないと現在研修中の人をしっかり見るのが大変なため。

**Comment by Ichiyo14** [comment]
本番環境で動作を確認しましたのでクローズします。
