### ISSUE TITLE
提出物にコメントすると自動で担当になる機能が、本番で動いていない。

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3192]
<s>担当が登録されていない提出物に対して、メンターがコメントをすると、自動的にそのコメントをメンターが担当にアサインされる機能が実装されているはずなんだけど、動いていないので、原因を調査し、修正する。</s>

現状はJSで2回リクエストを飛ばして修正しているが、Ruby側のコールバックで処理するようにする。

**Comment by konaga-k** [comment]
@komagata 
最新のmainブランチで状況再現できません

- komagata(mentorかつadmin)で未アサイン提出物にコメントしたところ、アサインされました
- kimura(mentorかつ非admin)で未アサイン提出物にコメントしたところ、アサインされました

本当に自動アサインが機能していないかご確認お願いします🙇

**Comment by komagata** [comment]
@konaga-k 本番環境では再現できるんですが、どうやって直すか考えます・・・
