### ISSUE TITLE
【メンター向け・バグ】未アサインタブの並び順がid順になっている

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#3197]
提出物の未アサインタブを開くと提出日順ではなくid順になっている。
以下の画像でいうと8/22の提出物が一番下に来ないといけない。

![2](https://user-images.githubusercontent.com/1148320/131047481-88c4f7f8-21da-42c3-91c4-a9f0396a7fe5.png)

https://bootcamp.fjord.jp/products/unassigned

**Comment by konaga-k** [comment]
@JunichiIto 
提出日が最近のものを上に表示したいという意図ですよね
まだ提出されていないWIPの提出物は、ページ下部に表示されるようにしておいていいでしょうか？

**Comment by konaga-k** [comment]
すみません、WIPの提出物は未アサインタブには表示されないので影響しないんですね🙇
確認不足でした

**Comment by konaga-k** [comment]
@JunichiIto 
提出物の並び順は [Product.list](https://github.com/fjordllc/bootcamp/blob/main/app/models/product.rb#L39-L43)というスコープによって定義されているため、これを修正しようと思っています
ただ、未アサインタブ以外でも使われているスコープなので、単に修正すると他に影響します
未アサインタブだけの並び順を修正してもいいのですが、後々別タブについて同じようなissueが立ちそうです
そこで、他の画面も含めて提出物の並び順を以下のように変更したいのですがいかがでしょうか？
メンターから見て使い勝手がどうか、意見をもらえると助かります🙏

現在の提出物の並び順
|画面|提出済みの提出物の並び順|WIPの提出物を含むか|WIPの提出物の並び順|
|---|---|---|---|
|全ての提出物|提出日時順|含む|提出物の先頭|
|未完了の提出物|作成日時順|含まない|-|
|未返信の提出物|提出日時順|含まない|-|
|未アサインの提出物|作成日時順|含まない|-|
|自分の担当の提出物|作成日時順|含む|作成日時順（提出済み/WIP関係なく並べられる）|
|ログインユーザーの提出物 （/current_user/products）|作成日時順|含む|作成日時順（提出済み/WIP関係なく並べられる）|
|ユーザーごとの提出物 （/users/:user_id/products）|作成日時順|含む|作成日時順（提出済み/WIP関係なく並べられる）|
|企業所属ユーザーの提出物 （companies/:company_id/products）|作成日時順|含む|作成日時順（提出済み/WIP関係なく並べられる）|

PR後の提出物の並び順（予定）
|画面|提出済みの提出物の並び順|WIPの提出物を含むか|WIPの提出物の並び順|
|---|---|---|---|
|全ての提出物|**作成日時順**|含む|**作成日順（提出済み/WIP関係なく並べられる）**|
|未完了の提出物|**提出日時順**|含まない|-|
|未返信の提出物|提出日時順|含まない|-|
|未アサインの提出物|**提出日時順**|含まない|-|
|自分の担当の提出物|作成日時順|含む|作成日時順（提出済み/WIP関係なく並べられる）|
|ログインユーザーの提出物 （/current_user/products）|作成日時順|含む|作成日時順（提出済み/WIP関係なく並べられる）|
|ユーザーごとの提出物 （/users/:user_id/products）|作成日時順|含む|作成日時順（提出済み/WIP関係なく並べられる）|
|企業所属ユーザーの提出物 （companies/:company_id/products）|作成日時順|含む|作成日時順（提出済み/WIP関係なく並べられる）|

変更意図としては以下のような感じです
- WIPの提出物を含まない画面の場合、提出日時順で並べる
- WIPの提出物を含む画面の場合、直近のWIPの提出物も確認したいだろうから（特にログインユーザーの提出物画面）、作成日時順で並べる。提出日時順で並べるのは、WIPのものだけが先頭に来てしまうので止める

**Comment by JunichiIto** [comment]
@konaga-k 改善案ありがとうございます！基本的にこれでOKです 🙆‍♂️ 
あえて注文を付けるなら、

- 作成日順に並べても現時点では画面上に作成日時が表示されないため、ぱっと見「これ、何順？もしかしてぐちゃぐちゃ？？」と混乱してしまいそう。（てか、現状でもたまに混乱している）
- 自分の担当の提出物は直近にコメントしたものほど上に並ぶと嬉しい。が、コメントが0件だったらどうするの？とか、いろいろ考慮点が増えるので、もしやるとしても別チケットだな〜。

・・・みたいな思いはあるのですが、どちらも今回のissueのスコープ外だと思いますし、まずは「未アサインの提出物」が提出日順に並ぶことが最優先なので、これで良いです。対応よろしくお願いします！！

**Comment by JunichiIto** [comment]
@konaga-k 対応ありがとうございました！非常に助かります😆
対応が完了したのでこちらのissueはcloseしておきます〜。
