### ISSUE TITLE
タグの(先頭の)シャープないしハッシュ記号を無視するようにする

### ISSUE THREAD

**Issue by universato** [fjordllc/bootcamp#3202]
**何故この機能が必要なのか**

タグの冒頭にハッシュをつける方が少なくありません。
そのため、「PostgreSQL」と「#PostgreSQL」の2つのタグが出来るなどの状況が発生しています。

**機能の説明**

冒頭にシャープやハッシュがある場合は、削除した上でDBに保存するといいと思います。

なお、冒頭以外で、#が使われる代表例としてC#があります。

**Comment by machida** [comment]
@unstoppa61e 
こちら、始めの文字に記号を使った場合は無視されます、的な文言も表示しておきたいと思います。
デザインはmachidaがやりますー

可能でしたら、現在記号から始まっているタグもタグなしに置換するrakeタスクもあると嬉しいですー

**Comment by unstoppa61e** [comment]
@machida 
かしこまりました、rake タスクも込みで実装させて頂きます！

**Comment by machida** [comment]
@unstoppa61e 
ありがとうございます！！

**Comment by machida** [comment]
@unstoppa61e 
https://github.com/fjordllc/bootcamp/issues/3871
こちらとIssueを分割しましたー

**Comment by unstoppa61e** [comment]
@machida 
年の瀬にすみません🙇‍♂️

こちらのタグ登録機能に関して調べたところ、既に実装されている機能として、スペースを含んだタグを登録しようとすると「入力されたタグに空白が含まれています」と表示されます。
![スクリーンショット 2021-12-29 6 39 31](https://user-images.githubusercontent.com/46347198/147609102-42da7167-fca9-4974-b096-bc2abd150732.png)

今回の Issue でも、この実装済みの機能と仕様を統一し、シャープないしハッシュ記号はじまりのタグを登録しようとすると「先頭のハッシュ（`#`）は不要です」と表示して弾いてやった方が良いかもしれないと思ったのですが、いかがでしょうか？（こだわりがある訳ではございませんので、どちらでも大丈夫です）。

お返事は急ぎませんので、年明けでも結構です！

**Comment by unstoppa61e** [comment]
@machida 
> こちら、始めの文字に記号を使った場合は無視されます、的な文言も表示しておきたいと思います。 デザインはmachidaがやりますー

こちらの「始めの文字に記号を使った場合は無視されます」的な文言を表示するタイミングについてです。
実装しながら、「もしかすると、あらかじめ文言を表示しておくよりも、記号から始まるタグ名を入力した場合にだけ文言を表示した方が、ユーザーが読み取る必要がある情報量が減って良いかもしれない」と思ったのですが、いかがでしょうか？

例えば、次のような流れを想定しています（実装してみました）。
1. 記号から始まるタグを登録しようとする
![スクリーンショット 2022-01-03 16 32 40](https://user-images.githubusercontent.com/46347198/147907773-8c1410eb-3c7d-43d6-a5e3-b7262b7a2095.png)

2. アラートにて、文言が表示される
![スクリーンショット 2022-01-03 16 39 18](https://user-images.githubusercontent.com/46347198/147908183-e0daaedc-c315-4654-84ba-ca7e355cb748.png)

3. 記号の部分を除いたタグが登録される
![スクリーンショット 2022-01-03 16 33 09](https://user-images.githubusercontent.com/46347198/147907822-66f80b3f-ca13-4e4b-8ef7-25bd3e21548d.png)

また、やはりあらかじめ表示しておいた方が良さそうでしたら、どの辺りに表示させると良いかをご指示頂けますと助かります🙇‍♂️

**Comment by unstoppa61e** [comment]
@machida 
それと、別件なのですが、同ページにてスペースを含むタグを作成しようとした場合、「入力されたタグにスペースが含まれています」と表示されます。
![スクリーンショット 2022-01-03 16 54 42](https://user-images.githubusercontent.com/46347198/147909339-78a907d1-062e-42d3-bc30-52ef5af462aa.png)

こちらの文言は、「スペースを含むタグは作成できません」とした方が、分かりやすいように思いました。
![スクリーンショット 2022-01-03 16 55 20](https://user-images.githubusercontent.com/46347198/147909348-de5b5058-a3fc-486e-9095-283740cae5e4.png)





もしよろしければ、ついでに変更させて頂ければと思ったのですが、いかがでしょうか？

**Comment by machida** [comment]
@unstoppa61e 

> こちらの「始めの文字に記号を使った場合は無視されます」的な文言を表示するタイミングについてです。

可能であれば、#などを打った際に表示したいですー
表示場所は入力ボックスの真下がいいですー

**Comment by machida** [comment]
> 「スペースを含むタグは作成できません」

いいですね！！
ぜひ、ここも変更お願いします🙏

**Comment by unstoppa61e** [comment]
@machida 
> 可能であれば、#などを打った際に表示したいですー
表示場所は入力ボックスの真下がいいですー

なるほど！
かしこまりました、ありがとうございます🙏
