### ISSUE TITLE
提出物にブックマーク機能がほしい。提出物個別ページにブックマークボタンを設置。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3232]
toastもつけて欲しい。

toast はこちらのPRで実装しています。
https://github.com/fjordllc/bootcamp/pull/3180
このPRがマージ前に作業に入る際は、このPRのコミットを含めて作業をお願いしますー
（ https://github.com/fjordllc/bootcamp/pull/3180 から新しいブランチを作るなど ）

**Comment by masamune17** [comment]
本番環境で確認できたのでcloseします
