### ISSUE TITLE
すでに確認済の日報をチェックしようとした場合、エラーを出すようにしたい

### ISSUE THREAD

**Issue by kfukai23** [fjordllc/bootcamp#3242]
## 概要
日報詳細画面と、ユーザーごとの日報一覧画面とで日報確認者が異なる場合がある。

## 再現手順
以下の2画面の日報確認者を比較する
- 日報詳細画面 https://bootcamp.fjord.jp/reports/37756
 
![貼り付けた画像_2021_09_14_16_02](https://user-images.githubusercontent.com/168265/133210885-1cb5419c-cb11-49e4-b0ee-af4a845bafb3.png)

- ユーザーごとの日報一覧画面 https://bootcamp.fjord.jp/users/901/reports
 
![貼り付けた画像_2021_09_14_16_03](https://user-images.githubusercontent.com/168265/133211028-2910cb95-dc07-49ed-a3e7-18a1218cb64f.png)

## 期待される振る舞い
日報確認者が一致すること。

## 環境

 - OS: macOS Catalina 10.15.7
 - ブラウザ: Chrome
 - バージョン:  93.0.4577.63 (Official Build) (x86_64)

## 関連Issue

なし

## 補足
- 状況的に異なる2人がそれぞれ「日報を確認」を押している可能性がある。片方の確認者(@kfukai23)は、日報を確認するとき「いくつかまとめて開く -> 順に確認する」という手順を踏むことがある。この時、開いてから確認ボタンを押すまでの間に別の人が押している、ということが起こっているかもしれない。
- [やりとり](https://bootcamp.fjord.jp/reports/37756#comment_72669)

**Comment by machida** [comment]
## 現在

1. メンターAとメンターBが同時に日報Xを開いている。
1. メンターAが日報Xを確認済にした。日報XはメンターAの確認済スタンプが表示される。
1. メンターBは画面をリロードしていないので、メンターAが日報Xを確認済にしたことに気が付かず、メンターBも日報Xを確認済にした。
1. その結果、日報Xに付いたメンターAの確認済スタンプが更新され、メンターBの確認済スタンプに置き換わる。

## こうしたい

1. メンターAとメンターBが同時に日報Xを開いている。
1. メンターAが日報Xを確認済にした。日報XはメンターAの確認済スタンプが表示される。
1. メンターBは画面をリロードしていないので、メンターAが日報Xを確認済にしたことに気が付かず、メンターBも日報Xを確認済にしようとした。
1. その結果、日報XはメンターAが確認済にしているので、メンターBには「この日報は確認済です」と赤い toast で表示され、確認済スタンプはメンターAのまま。

**Comment by niikz** [comment]
@machida 
赤い toast の仕様に関して質問があります！お手すきの際にご確認お願いいたします🙏

1. 下記のライブラリ公式ページで紹介されているサンプルを参考にすると、`icon: 'error'` を指定することで赤いtoastが実装できそうです。（CSSの設定を追加する必要はあります）
懸念点として、現状の実装ではアイコンを指定していないため緑色のsuccessの場合にアイコン表示がないのですが、赤いerrorの場合はアイコンが表示されるという違いが出てしまう点があるため、どのようなデザインになるかご教示いただきたいです。
https://sweetalert2.github.io/recipe-gallery/colored-toasts.html

2. 上記1の `icon: 'error'` を使用せずに赤いerrorの場合はメソッドを分けてしまって、`toast.js` 側で `background: '#f27474'` のように設定すると色を変更できるのですが、色指定はCSS側で行なったほうがよいでしょうか？
https://sweetalert2.github.io/#background

**Comment by machida** [comment]
@niikz 

そうですねー、`icon: 'error'` を使わない形でやりたいですね。
`/app/assets/stylesheets/modules/_toasts.sass`
ここでcssを設定しているのですが、現在は `.swal2-toast` というブロックが toast になっています。
メソッドを分けなくても、何か独自のオプションを渡す実装でも大丈夫です。このへんは @komagata さんと相談をお願いします。

デザイン的なところでは、 `.swal2-toast` は緑で表示されるのですが、 `.swal2-toast` に `.is-error` という class を付けると赤になる、という css を書くなどの対応を考えています。なので、何かオプションを渡すと、 `.swal2-toast` に `.is-error` という class が付くようになるといいかな、と考えています。css の方は僕の方で対応します。

あと、せっかく `is-error` を作るなら、今のオプション無しの `.swal2-toast` には `is-success` が付くようにしたいなーと少し思いました（これは別Issueでもいいかも）。

**Comment by niikz** [comment]
@machida 
詳細なご説明ありがとうございます〜！承知しました🙆‍♀️
`customClass` を使うとクラス名を付与できそうなので、`.is-error` という class を追加する方向でやってみます！
参考：https://sweetalert2.github.io/#customClass

**Comment by niikz** [comment]
@machida @komagata 
お疲れさまです。お手数ですが、本番環境での動作確認をお願いいたします🙏

確認いただきたい箇所は以下の2点です。
（あわせて #4566 の確認もお願いいたします）

- 確認済みの日報をチェックした場合
  - "この日報は確認済です。"というエラーのtoastが表示される
  - 日報一覧の確認済みスタンプの名前が置き換わらない

**Comment by niikz** [comment]
machida さん、komagata さんに本番環境で確認いただいたのでcloseします。
