### ISSUE TITLE
通知をカテゴリごとに全て既読にする機能が欲しい

### ISSUE THREAD

**Issue by yana-gi** [fjordllc/bootcamp#3247]
**何故この機能が必要なのか**

https://github.com/fjordllc/bootcamp/issues/2997 で通知タブがカテゴリ別に表示されるようになったが、現在「全て既読にする」ボタンは通知全件分にしか対応していないため。

**Comment by IkumaTadokoro** [comment]
本番環境で動作していることを確認したため、クローズします
