### ISSUE TITLE
Docsは投稿者が重要ではないデザインにしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3282]
<img width="518" alt="スクリーンショット 2021-09-14 20 19 18" src="https://user-images.githubusercontent.com/16577/133248449-ed2ee2a7-9f08-4bf9-9484-edc6b198b66b.png">

Docsは文章（タイトル）が大事で、誰が書いたかという情報は重要視してほしくないので、投稿者は目立たないデザインにしたい。

**Comment by machida** [comment]
現在着手中
