### ISSUE TITLE
提出物の自分の担当タブに表示される、未返信の提出物個数が常にZEROで表示される

### ISSUE THREAD

**Issue by makiichikawa** [fjordllc/bootcamp#3291]
## 概要
メンターでログインして、提出物のページへ移動。そこに、自分の担当というタブがある。
自分の担当タブには未返信の提出物個数が表示されるが、常にZEROの値を表示してしまっている。

## 再現手順

1. メンターでログイン
2. 提出物をクリック
3. 自分の担当タブに「０」という数字が表示

## 期待される振る舞い
未返信の提出物の個数を正しく表示する

## スクリーンショット
![レビューを担当する未返信の提出物___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/57123982/133737052-82f7ec88-9cb1-4490-9e57-40e194b45edf.png)

## 環境
ステージング

## 関連Issue

Ref: #3022

**Comment by komagata** [comment]
@makiichikawa これはステージングで`0`が表示される状態になっているからバグっているという意味ですかね？

スクショには`3`が表示されていますがこれはどう言った意味でしょうか？（この状態に直すという意味？）

僕がステージングでユーザー komagata で提出物ページを見るとスクショのように3の表示になっているようです。

**Comment by makiichikawa** [comment]
@komagata 
ご確認頂き、ありがとうございます。

> これはステージングで0が表示される状態になっているからバグっているという意味ですかね？

ご認識の通りです。

> スクショには3が表示されていますがこれはどう言った意味でしょうか？（この状態に直すという意味？）

ご認識の通り、この状態に直すという意味で書きました。

> 僕がステージングでユーザー komagata で提出物ページを見るとスクショのように3の表示になっているようです。

金曜日時点ではDiscordでスクショを張っている通り、0で表示されていたのですが
![レビューを担当する未返信の提出物___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/57123982/133911820-ad24770b-f4ac-4818-9dfe-082fe356b944.png)

現時点で私の方もステージングを見てみたら、正しく3に表示されていました。
戸惑わせているだけみたいになってしまいすみません🙇🏼‍♂️

**Comment by makiichikawa** [comment]
正しく未返信の提出物個数が表示されているため、クローズいたします。
