### ISSUE TITLE
ニコニコカレンダーの日報未投稿の日付をクリックしたら、その日の日報作成画面を表示してほしい

### ISSUE THREAD

**Issue by asya81** [fjordllc/bootcamp#3295]
**何故この機能が必要なのか**

- 学習日当日以降に日報を書く場合、学習日を変更し忘れることがあるため、あらかじめ日付を選んで投稿できるようにしたい。

（ニコニコカレンダーから投稿したい理由）
- ダッシュボードのニコニコカレンダーを見て、どこまで日報作成したかを確認することが多いため、そこから投稿できると動線としてスムーズになる。（これは人によって異なる可能性あり）
- ニコニコカレンダーで日報投稿済の日付をクリックすると当日の日報が表示されるため、未投稿時には作成画面が表示されると違和感がない。

**機能の説明**

![ニコニコカレンダー](https://i.gyazo.com/33d486f4c38e6474494ea354d22ba6ae.png)

- ニコニコカレンダーで、日報が未投稿である日付（「ー」と表示されている日付）をクリックしたら、選択した日付を「学習日」にセットした日報作成画面を表示する。
- ただし、未来日付をクリックした場合は、これまで通り何も表示しない。

**Comment by sutehuna** [comment]
@komagata ホバーしたときにポップアップが出るようにしたいと会議で話がありましたが、そのような認識で正しいのでしょうか？

**Comment by machida** [comment]
@sutehuna ポップアップではなく、hover時に文字を表示する見た目を考えてます。こちらはデザインで僕が対応しますー

**Comment by sutehuna** [comment]
@machida では、指定した日の日報のページに飛ぶ機能だけを作ればよいということでしょうか？

**Comment by NorifumiOgawa** [comment]
本番環境で確認しました！
