### ISSUE TITLE
footerのメニューにTwitterの#fjordbootcampへのリンクを追加したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3303]
<img width="1227" alt="貼り付けた画像_2021_09_22_22_44" src="https://user-images.githubusercontent.com/168265/134355273-4459063f-134e-402c-b015-4c5cc1527e2e.png">

リンク先はこれでお願いします。

`https://twitter.com/hashtag/fjordbootcamp?src=hashtag_click&f=live`

aタグには、`target='_blank'` と `rel=''noopener` も追加しておいてください。

**Comment by kaiyu-tech** [comment]
本場環境で動作することを確認したので`Close`します！
