### ISSUE TITLE
日報の個別ページにメンターしか見れないユーザーメモを表示させたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3323]

**Comment by haruguchi-yuma** [comment]
@machida 
確認させてください。🙏
上記のIssueはユーザーが書いた日報の個別ページに対してメモできる領域を作ればいいということでしょうか？

プロフフィール欄にある「メンター向けユーザーメモ」を参考にしようと思っていますが、認識あっていますでしょうか？
![image](https://user-images.githubusercontent.com/57053236/136503126-e2d321bc-cc3d-4343-8c6e-33b8d7a0a3b6.png)

**Comment by haruguchi-yuma** [comment]
@machida
追加で質問させてください。🙇‍♂️

現在ユーザー詳細ページでメンター向けユーザーメモに`test`と入力すると提出物のメンター向けユーザーメモでも同じように`test`というメモが存在すると思います。

メンター向けユーザーメモというのはユーザーに紐づいたメモと理解したのですが、今回のIssueで実装するユーザーメモというのも、同じくユーザーに紐づいたメモということで良いでしょうか？

それとも、日報ごとに違った内容のメモが入力できる（日報に紐づいたメモ）メモを実装すれば良いのでしょうか？

よろしくお願いします！

**Comment by haruguchi-yuma** [comment]
@komagata  
メンター向け機能のため、本番環境で確認していただきたいです！

**Comment by komagata** [comment]
@haruguchi-yuma 本番環境で動作することを確認しました。

**Comment by haruguchi-yuma** [comment]
@komagata 
ありがとうございます！本番環境での動作が確認できたので、Issueをcloseします。
