### ISSUE TITLE
フォロー状態を変更したらdetailタグが閉じて欲しい

### ISSUE THREAD

**Issue by yana-gi** [fjordllc/bootcamp#3341]
**何故この機能が必要なのか**

フォローボタンからフォロー状態を切り替えもdetailタグが閉じない。
detailタグを閉じたい場合は自分でsummaryボタンをクリックする必要がある。

関連issue : https://github.com/fjordllc/bootcamp/issues/3007
関連コメント: https://github.com/fjordllc/bootcamp/pull/3227#issuecomment-927524698

**機能の説明**

フォロー状態を切り替えるときに、赤い枠で囲った部分をクリックしたらdetail タグの open 属性が削除されて detail が close になって欲しい。
![image](https://user-images.githubusercontent.com/67262644/135824810-cc940435-4566-42a4-9b4d-359f72d3ce38.png)

**Comment by yana-gi** [comment]
こちらのissue、自分はしばらく取り掛かれそうにないため他の方にissueを割り振って頂いて構いません🙏

**Comment by chidimi** [comment]
@machida 
@yana-gi 
修正してみました。ちなみに、finallyでフォロー処理の成功失敗関係なく必ず閉じるようにしてみたのですが、
成功の場合だけにしたほうが良いですか？
