### ISSUE TITLE
[メンター向け]進捗が遅れている方を確認できるようにする

### ISSUE THREAD

**Issue by u1tnk** [fjordllc/bootcamp#3344]
**何故この機能が必要なのか**

進捗が遅れている方を可視化する事によって、メンターからフォローできるようにしたい。
のんびりやっていて問題無い方も居るが困っている方も居ると思われるので。

**機能の説明**

具体的な検索条件は実装しやすいもので良いと思います。
案としてはそのプラクティスの平均値の倍経過しているユーザとか。

継続して確認していくことなので通知系の機能では無く、
確認できるリストをメンターが確認できるようにすると良い。メンターミーティング等で定期的に確認できるので。

**Comment by komagata** [comment]
:memo: 町田さんと仕様を話し合った結果メモ

<img width="1436" alt="スクリーンショット 2021-10-05 15 47 48" src="https://user-images.githubusercontent.com/16577/135974615-7980e998-379f-4050-812c-6df4651076e4.png">

- メンターだけが見れるページを `/mentor`に作る。（`/admin`と似た作りにする）
- プラクティスを最後に完了してから二週間以上経っている人を表示する。
- プラクティスを最後に完了したからの経過時間が大きい順に表示する。

他にもアイコンを追加していく予定だが、まずはこのIssueではこれだけで実装する。

**Comment by u1tnk** [comment]
早速仕様詰めして頂いてありがとうございます 🙏 
良いと思います 👍

**Comment by kaiyu-tech** [comment]
@komagata @machida
 本件、メンター向け機能のため、本場環境で動作することを確認していただけないでしょうか？🙏

**Comment by komagata** [comment]
@kaiyu-tech メンターダッシュボードのリンクをクリックすると管理者ページのトップにリダイレクトされちゃうみたいでした。

**Comment by kaiyu-tech** [comment]
@komagata
 私が追加したのは`メンターページ`で、ミーティングで`メンターページ`をメニューに追加してリンクを貼るようにご指示を受けていました。PRのDescriptionにもその理解で記載しています。

`メンターダッシュボード`はもともと項目がありましたが、もしかして`メンターダッシュボード`にリンクを貼るべきだったのでしょうか？

**Comment by komagata** [comment]
@kaiyu-tech すみません、メンターページとメンターダッシュボードを勘違いしていました。
本番環境で動作することを確認しました。

**Comment by kaiyu-tech** [comment]
@komagata 動作確認ありがとうございます！🙏 `Close`させていただきます。
