### ISSUE TITLE
Q&Aの通知メールに質問タイトルを含めてほしい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#3356]
Q&Aの通知メールに質問タイトルを含まれていないため、本文で「タイトルのエラーが発生」と書かれてもメールだけでは内容がわからない。
なのでメールのどこかに質問タイトルを書いてほしい。

例
https://bootcamp.fjord.jp/questions/1059

メール
<img width="907" alt="Screen Shot 2021-10-07 at 8 11 42" src="https://user-images.githubusercontent.com/1148320/136296264-e088f0e2-f516-4d27-8e33-68d4b6d6f311.png">

Q&Aページの投稿内容
<img width="800" alt="Screen Shot 2021-10-07 at 8 12 01" src="https://user-images.githubusercontent.com/1148320/136296298-a01a50d4-b2b9-4358-8a5f-414badd9ad0a.png">

**Comment by kawase-k** [comment]
@komagata さん
こちら本番環境での確認はすぐにできないと思うのでこのままCloseしてもよいでしょうか？🤔

**Comment by komagata** [comment]
@kawase-k 確認できる人（僕とか）に確認依頼をしてください〜

そしてこのIssue、僕が確認します〜

**Comment by komagata** [comment]
@kawase-k 本番環境で動作することを確認しました。

**Comment by kawase-k** [comment]
@komagata さん
本番環境での動作確認ありがとうございます🙏
こちらCloseします！
