### ISSUE TITLE
PR#3163のイベント表示がされない

### ISSUE THREAD

**Issue by yamadaab** [fjordllc/bootcamp#3358]
## 概要

私が担当した「イベントの日にダッシュボードに出したい(再作成) #3163」のPRにて
当日、翌日のイベントがダッシュボードに表示されるはずでした。

ところが、seedデータのイベント以外が表示されておりませんでした。

## 再現手順

ステージング、ローカル共に反映されません。
サービス内でイベントを作成しても反映されません。
seedデータのイベントのみ反映されます。

## 原因
原因は当日、翌日のイベントをDBより検索する以下のメソッドにありました。
```
home_controller

(省略)
@events_coming_soon = Event.where(start_at: Date.current).or(Event.where(start_at: Date.tomorrow)).where.not(id: cookies_ids)
(省略)
```

`start_at:`カラムがDate.currentとDate.tomorrowのデータを検索しておりますが、これが誤りでした。
`start_at:`カラム内のデータは`"2021-10-08 19:17:00.000000000 +0900"`のように時間まで指定されています。
Date.currentは当日が10/7の場合`"2021-10-07 9:00:00.000000000 +0900"`のように表示されていました。

そのため、Date.currentで設定していたseedデータのみ、表示される結果となっていました。

## 修正案
`Date.current`での検索から「当日0時〜翌日０時」のようなレンジとして検索すれば解決します。

## 関連Issue

Ref: #3163

**Comment by komagata** [comment]
@yamadaab 複数のwhereやorが出てくるようなARクエリはどのように評価されるのかむずかしいので、必ずどんなSQLが生成されるのか`to_sql`メソッドやログで確認しておくと良いかもですね。

**Comment by yamadaab** [comment]
> @yamadaab 複数のwhereやorが出てくるようなARクエリはどのように評価されるのかむずかしいので、必ずどんなSQLが生成されるのか`to_sql`メソッドやログで確認しておくと良いかもですね。

かしこまりました！
なぜかseedデータやtest以外は反映するのに時間がかかると思い込み、動作確認をseedデータやsystemtestだけで確認したのが良くありませんでした。実際にバグチェックをするように徹底します🙇‍♂️
