### ISSUE TITLE
ユーザーのステータスが卒業になったら運営のチャットに通知したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3368]
卒業になった受講生は、卒業ステータスを変更されます。その作業は管理者が行います。

管理者アカウントで `/admin/users` ここにアクセスすると、ユーザー一覧が表示されます。
卒業ボタンを押すと、その受講生は卒業生になります。

<img width="2228" alt="貼り付けた画像_2021_10_19_15_56" src="https://user-images.githubusercontent.com/168265/137859015-09b92082-da45-4b69-b24b-3d9f95ffd137.png">

受講生が卒業になりましたら、Discordのフィヨルドブートキャンプ運営チャンネルに、「XXXさんが卒業になりました。」という通知が飛ぶようにしていただきたいです。

Discordへの通知は、新規Docsが作られたときに飛ぶなど、どこかで実装されているので、それを参考にできると思います。

Discordのフィヨルドブートキャンプ運営チャンネルの情報は @komagata さんから連絡させていただきます。

**Comment by kawase-k** [comment]
@komagata @machida 

上記の件、承知しました！
また分からないところが出てきたら質問させていただきます🙏

**Comment by kawase-k** [comment]
@komagata さん
こちら本番環境での確認はできないと思うのでこのままCloseしてもよいでしょうか？🤔

**Comment by komagata** [comment]
@kawase-k 確認できる人に確認依頼を出してください〜（僕とか）

そしてこのIssueは僕が確認します。

**Comment by kawase-k** [comment]
@komagata さん
上記の件、承知しました。
お手数おかけしますが、本番での動作確認をお願いしてもよろしいでしょうか？🙇‍♂️

**Comment by machida** [comment]
@kotakawase こちら卒業生が出たので動作確認ができました！！ クローズしますー🎉
