### ISSUE TITLE
就職相談のプラクティスを開始したら運営のチャットに通知したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3369]

**Comment by komagata** [comment]
@haruguchi-yuma それは別の用途で別のチャンネルなので今回は今回のための環境変数を作っていただければ〜

**Comment by haruguchi-yuma** [comment]
@komagata 
ステージング環境での動作確認はどのようにやれば良いでしょうか？

**Comment by komagata** [comment]
@haruguchi-yuma こちらを参照いただければ〜

https://github.com/fjordllc/bootcamp/pull/3521#issuecomment-961680335

**Comment by haruguchi-yuma** [comment]
@komagata 
こちら、本番環境での動作確認はどのようにすればよいでしょうか？🙇

**Comment by komagata** [comment]
@haruguchi-yuma こちら僕が確認します〜

**Comment by haruguchi-yuma** [comment]
@komagata 
ありがとうございます！！
