### ISSUE TITLE
Featuredエントリー機能が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3375]
- 日報の個別ページで「注目エントリーボタン」を押すと「注目エントリー」になる。
  - トグルボタンになっていて外すこともできる。
  - 注目エントリーボタンが表示されてボタンを押せるのはメンターのみ。
- 「注目エントリーになっている日報」の一覧がダッシュボードページに表示される。
  - 表示するのは最近の注目エントリーになったもの５件。
- 日報以外にもDocsやコメントなど注目エントリーの対象が将来的に増える可能性があるのでそれを見据えて設計する。

<img width="1469" alt="スクリーンショット_2021-11-04_17_45_36" src="https://user-images.githubusercontent.com/16577/140287481-faec4477-d55d-4c57-bdb1-7a1219c7fe97.png">

<img width="1510" alt="スクリーンショット_2021-11-04_18_05_50" src="https://user-images.githubusercontent.com/16577/140287496-4696e214-cdab-4f7a-8d3c-c970f09b9c27.png">

**Comment by machida** [comment]
## 仕様の追加

<img width="588" alt="貼り付けた画像_2021_11_04_23_21" src="https://user-images.githubusercontent.com/168265/140330893-92eb342c-c759-4895-b8db-34efc88b5ea9.png">

- 上図の・・・・ の部分にその日報のコメントの最初の100文字（trancateする）と、そのコメントを書いたユーザーのアイコンを表示する
- コメントは古いもの最大3件を表示する

**Comment by komagata** [comment]
@machida 

> 日報以外にもDocsや**コメント**など注目エントリーの対象が将来的に増える可能性があるのでそれを見据えて設計する。

と書いてたんですが、ここにコメントそのものが来ることになるのかな〜と考えておりました。
だとするとエントリーに付随するコメントを表示する必要はないかなあと思いました。

**Comment by haruguchi-yuma** [comment]
@komagata @machida 
現在以下のようにダッシュボードに注目エントリーを一覧で出しました。
![image](https://user-images.githubusercontent.com/57053236/142144979-dd50c555-7471-4392-b1ec-b5663fba95ce.png)

このダッシュボードの注目エントリーに関して2点確認したいです。

> 表示するのは最近の注目エントリーになったもの５件。

とありますが、注目エントリーボタンを押した順（FeaturedEntryオブジェクトが作成された順)で最新のエントリーを並べる。ということでよろしいでしょうか？
それとも対象記事の公開順などで並べた方がいいでしょうか？

あと、5件以上あった場合上の画像のお知らせ欄のように「すべてのお知らせを表示」みたいにリンクをつけて注目エントリー一覧ページに飛べるようになっていた方がいいでしょうか？

**Comment by haruguchi-yuma** [comment]
上のコメントに関しては質問タイムで確認済みです！
注目エントリーのボタンを押した順。
注目エントリー一覧画面を作る

**Comment by machida** [comment]
@komagata @haruguchi-yuma
現状だと、なぜそれを注目させようとしたのかという意図がユーザーに伝わらず、受講生が混乱、もしくはノイズと感じてしまいます。なので、コメントを表示しないのであれば、注目ボタンを押したときにコメントを必須にして、なぜこれを受講生みんなに見てもらいたのかを伝えることが実現できた上でこの機能のリリースをしたいと思います。
