### ISSUE TITLE
プラクティスメモを更新したら toast で通知を出して欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3394]
メンター機能のプラクティスメモが提出物個別ページにあります。
それを保存したら、

<img width="1618" alt="貼り付けた画像_2021_10_13_23_48" src="https://user-images.githubusercontent.com/168265/137157314-a2210d54-b81d-49cc-adb9-51f180e29e67.png">

保存したことを toast で表示して欲しい。

<img width="491" alt="貼り付けた画像_2021_10_13_23_49" src="https://user-images.githubusercontent.com/168265/137157617-19c14ce2-511f-4690-b7d8-d1420aebbb15.png">

toast は、bookmark 、watch ボタンを押すと出てくるやつです。

**Comment by komagata** [comment]
@Ichiyo14 本番環境で動作することを確認しました。
