### ISSUE TITLE
複数のプラクティスに着手できるようにしてほしい

### ISSUE THREAD

**Issue by konaga-k** [fjordllc/bootcamp#3433]
着手しているプラクティスがある状態で別のプラクティスを進めようとすると、alertが出てステータスを着手にすることができない
![image](https://user-images.githubusercontent.com/54785890/138261775-165b1337-8415-4c69-80fa-3ede77a6016a.png)

具体的には、チーム開発と自作サービス作りは並行して進めることが推奨されているのに、
自作サービスのプラクティスについてbootcamp上のステータスを進めることができない
https://bootcamp.fjord.jp/practices/140
> Webサービスを作って公開する の始めの方のプラクティスはコードを書かないプラクティスが続きます。なので、「Webサービスを作って公開する」に入ると、コードを書かない期間ができてしまいます。それを防ぐために、フィヨルドブートキャンプの学習アプリのシステム的にプラクティスの同時進行ができないですが、ここだけは特別に同時に「Webサービスを作って公開する」も進めてください。

チーム開発と自作サービス作りのプラクティスのステータスを並行して進めたいというのが希望
特定のプラクティスに限って制限を取り除くと難易度・複雑度が高い気がするので、システム上は全てのプラクティスについて複数着手できるようにしていいと思う
（システムで制限しなくても、受講生が複数のプラクティスにかまけて進捗が滞ることは起こりにくい気がする）

**Comment by machida** [comment]
これ、昔は複数同時にできてたのですが、複数同時から一つしかできない制限を付けたんですよね。というのも、複数同時にやることを許すと複数を同時にやる人が何人か出てしまい、複数を同時にやってしまう人は100%リタイヤしてるんですよね。なので、今の仕様にしています。

**Comment by komagata** [comment]
僕も同意見なので一旦クローズしちゃいますね〜
