### ISSUE TITLE
日報の絞り込みの修正（泣き顔を出す）

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3443]
<img width="1557" alt="貼り付けた画像_2021_10_25_11_48" src="https://user-images.githubusercontent.com/168265/138627489-16c79cab-9c05-42cd-a81a-7c55a68730d0.png">

日報が無い場合はこのように表示する。

![image](https://user-images.githubusercontent.com/168265/138627533-83401172-dcd0-436f-a6d1-4803faf2f0d1.png)

**Comment by taka61** [comment]
@machida さん
本番環境では「日報が0のプラクティス」が存在しないため動作確認が出来ておりません。
この場合Issueはクローズしない方が良いでしょうか？
ご確認の程、よろしくお願いします🙏
