### ISSUE TITLE
古いコメントを表示の部分に、非表示になっている古いコメントの数を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3464]
<img width="852" alt="貼り付けた画像_2021_10_28_12_05" src="https://user-images.githubusercontent.com/168265/139179209-15939fa1-7b64-4719-8958-afd64395b05e.png">

こうしたい

<img width="852" alt="貼り付けた画像_2021_10_28_12_05" src="https://user-images.githubusercontent.com/168265/139179279-55e7e624-7909-42ce-b152-7710b39a19f0.png">

**Comment by kawase-k** [comment]
こちら本番で確認を行い問題なかったのでCloseします〜！
