### ISSUE TITLE
モバイル表示の場合に、プラクティスの更新者のアバターアイコンが表示されない

### ISSUE THREAD

**Issue by IkumaTadokoro** [fjordllc/bootcamp#3473]
## 概要

モバイル表示の場合に、プラクティスの更新者にアバターアイコンが表示されない。

## 再現手順

1. 任意のプラクティスのページにアクセス。
2. モバイル表示で、更新者名を確認する。
3. アバターアイコンが表示されていない。

## 期待される振る舞い

モバイル版でもデスクトップ版同様に、更新者にアバターアイコンが表示されてほしい。

### デスクトップ表示

![image](https://user-images.githubusercontent.com/61409641/139450428-ed8fa53b-f80d-4bbc-9dc1-8131358b50e4.png)

### モバイル表示

![image](https://user-images.githubusercontent.com/61409641/139450163-5644607f-bad9-46af-af1b-5aad793e8dfb.png)

## 関連Issue

- Ref: #3399 
    - > issueのスクリーンショットではこのユーザアイコンがなく、その点が問題だったが、本番環境を調査しアイコンが表示されていることを確認したため、issue自体はクローズとする。
    - 上記記載はデスクトップ版での確認結果であり、モバイル版では本番環境でもユーザアイコンが表示されていなかった。

## 備考

- 該当箇所はモバイルの場合、`display:none`となっている。
- https://github.com/fjordllc/bootcamp/blob/5763a5678eb0912c453150b8b2af1b69d6d623f8/app/assets/stylesheets/atoms/_a-meta.sass#L26

**Comment by IkumaTadokoro** [comment]
@machida 

本バグの原因ですが、issue記載の通り、アバターアイコンに対して`display:none`が適用されていることが原因でした。
使用箇所及びこのCSSをなくした場合の影響を下記の通り確認したのですが、なくしても特に問題なさそうです。

削除してしまおうと思うのですが、念の為ご確認お願いできますでしょうか🙇‍♂️
（ 53392bc46cceaa31de63dfd69c5803a3a82e4cfa にて追加されており、slug関連のデザインに影響があるかも？と少し懸念しています）

## アバターアイコンを非表示にしているCSS

```scss
  +media-breakpoint-down(sm)
    .thread-header__user-icon-link,
    .thread-list-item-meta__icon-link
      display: none
```

https://github.com/fjordllc/bootcamp/blob/5763a5678eb0912c453150b8b2af1b69d6d623f8/app/assets/stylesheets/atoms/_a-meta.sass#L26

## 該当CSSの使用箇所

モバイル表示の場合に、アバターアイコンを非表示にしているCSSの使用箇所は以下4箇所
（Docsとプラクティスの作成者、更新者のアバターアイコン表示）

https://github.com/fjordllc/bootcamp/blob/e34b9c71c597e8ba183bc40016ab403a3911cce8/app/views/pages/show.html.slim#L36

https://github.com/fjordllc/bootcamp/blob/e34b9c71c597e8ba183bc40016ab403a3911cce8/app/views/pages/show.html.slim#L57

https://github.com/fjordllc/bootcamp/blob/76a2d6b9c66e03aa8a7f64a95c130d2d466763f6/app/views/pages/_page.slim#L52

https://github.com/fjordllc/bootcamp/blob/8e446e949da35f1b511fe7ca0389fa27fae1217b/app/views/practices/show.html.slim#L72


## display:noneを解除した場合の見た目

**Docs**

![image](https://user-images.githubusercontent.com/61409641/140868437-af79702e-1675-42f7-aed9-38ca6b610fe2.png)

![image](https://user-images.githubusercontent.com/61409641/140868606-91791edd-89aa-4008-bf0e-5305d884bcfb.png)

**プラクティス**

![image](https://user-images.githubusercontent.com/61409641/140868507-0612a054-b51a-4770-bfb8-4f3e1efb6d24.png)

**Comment by tksmasaki** [comment]
> @machida
> 
> 本バグの原因ですが、issue記載の通り、アバターアイコンに対して`display:none`が適用されていることが原因でした。 使用箇所及びこのCSSをなくした場合の影響を下記の通り確認したのですが、なくしても特に問題なさそうです。
> 
> 削除してしまおうと思うのですが、念の為ご確認お願いできますでしょうか🙇‍♂️ （ [53392bc](https://github.com/fjordllc/bootcamp/commit/53392bc46cceaa31de63dfd69c5803a3a82e4cfa) にて追加されており、slug関連のデザインに影響があるかも？と少し懸念しています）
> 
> ## アバターアイコンを非表示にしているCSS
> ```css-scss
>   +media-breakpoint-down(sm)
>     .thread-header__user-icon-link,
>     .thread-list-item-meta__icon-link
>       display: none
> ```
> 
> https://github.com/fjordllc/bootcamp/blob/5763a5678eb0912c453150b8b2af1b69d6d623f8/app/assets/stylesheets/atoms/_a-meta.sass#L26
> 
> ## 該当CSSの使用箇所
> モバイル表示の場合に、アバターアイコンを非表示にしているCSSの使用箇所は以下4箇所 （Docsとプラクティスの作成者、更新者のアバターアイコン表示）
> 
> https://github.com/fjordllc/bootcamp/blob/e34b9c71c597e8ba183bc40016ab403a3911cce8/app/views/pages/show.html.slim#L36
> 
> https://github.com/fjordllc/bootcamp/blob/e34b9c71c597e8ba183bc40016ab403a3911cce8/app/views/pages/show.html.slim#L57
> 
> https://github.com/fjordllc/bootcamp/blob/76a2d6b9c66e03aa8a7f64a95c130d2d466763f6/app/views/pages/_page.slim#L52
> 
> https://github.com/fjordllc/bootcamp/blob/8e446e949da35f1b511fe7ca0389fa27fae1217b/app/views/practices/show.html.slim#L72
> 
> ## display:noneを解除した場合の見た目
> **Docs**
> 
> ![image](https://user-images.githubusercontent.com/61409641/140868437-af79702e-1675-42f7-aed9-38ca6b610fe2.png)
> 
> ![image](https://user-images.githubusercontent.com/61409641/140868606-91791edd-89aa-4008-bf0e-5305d884bcfb.png)
> 
> **プラクティス**
> 
> ![image](https://user-images.githubusercontent.com/61409641/140868507-0612a054-b51a-4770-bfb8-4f3e1efb6d24.png)

**Comment by tksmasaki** [comment]
@komagata @machida 
間違えて一度 close 操作してしまいました。
申し訳ありません🙇‍♂️

**Comment by tksmasaki** [comment]
本番環境での動作確認が完了しました。Close します！
