### ISSUE TITLE
末尾が`.js` のユーザー一覧ページのスタイルが当たっていない

### ISSUE THREAD

**Issue by obregonia1** [fjordllc/bootcamp#3479]
## 概要
https://discord.com/channels/715806612824260640/828456619028381726/904266585835991072

> これ不具合なのかはよくわかりませんが、Next.js のタグを持つユーザ一覧画面がおかしいと感じました

調べてみるとVue.jsも同様の表示だったため末尾が`.js`のタグの場合同様のバグが発生すると思われます。dev toolで確認するとassetsファイルが全てありませんでした。

## 再現手順

[https://bootcamp\.fjord\.jp/users/tags/Next\.js](https://bootcamp.fjord.jp/users/tags/Next.js) にアクセス

## スクリーンショット
![image](https://user-images.githubusercontent.com/75117116/139573525-1cf701a4-d949-4684-b36f-9c11a24900a2.png)
![image](https://user-images.githubusercontent.com/75117116/139573711-2671f459-d582-4c23-855d-b1e21b5373fb.png)

## 環境
 - OS: macOS Big Sur 11.6
 - ブラウザ: バージョン: 95.0.4638.54（Official Build） （x86_64）

**Comment by IkumaTadokoro** [comment]
本issueの対応をする場合、以下も確認お願いいたします。

- 重複しているissue： #2446
- 原因が同じissue：#2447

**Comment by mami-inuzuka** [comment]
@IkumaTadokoro こちら私のPCでも確認し正しく表示されることを確認しました！バッチリだと思います😊👌

**Comment by IkumaTadokoro** [comment]
本番環境で動作していることを確認したため、クローズします
