### ISSUE TITLE
Q&Aで`.js`で終わるタグを選択すると誤認識されていると思われる

### ISSUE THREAD

**Issue by kaiyu-tech** [fjordllc/bootcamp#3480]
## 概要

「ref #3479」と同様の問題ですが、[Q&Aで`.js`で終わるタグ](https://bootcamp.fjord.jp/questions/tags/Vue.js?all=true)を選択した場合にも発生します。

URLパスが`.js`で終わっているため、誤認識しているのではないでしょうか？

## 再現手順

1. [https://bootcamp.fjord.jp/questions/tags/Vue.js?all=true](https://bootcamp.fjord.jp/questions/tags/Vue.js?all=true)にアクセス。

## 期待される振る舞い

タグをURLエンコードする等で誤認識されないようにすれば解決するように思われます。

## スクリーンショット

![image](https://user-images.githubusercontent.com/73627898/139576298-7991350b-726e-4071-a795-4838bbc09822.png)

## 環境

 - OS: WIndows 10
 - ブラウザ: Microsoft Edge
 - バージョン: 95.0.1020.38

## 関連Issue

ref #3479

**Comment by IkumaTadokoro** [comment]
本番環境で動作していることを確認したため、クローズします
