### ISSUE TITLE
イベントの申込み期限が過ぎてもキャンセルはできるようにしたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#3483]
現状のイベントページは申込み期限が過ぎると申込みだけでなく、参加キャンセルもできなくなる。
「直前だけど急用ができたのでキャンセルしたい」というケースはあると思うので（というか、僕が経験した）、キャンセルはいつでもできた方が良さそう。

**Comment by kawase-k** [comment]
こちら本番で確認を行い問題なかったのでCloseします〜！

**Comment by JunichiIto** [comment]
@kawase-k 対応ありがとうございました！！
