### ISSUE TITLE
[相談部屋]相談部屋にコメントを投稿出来るようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3504]
https://github.com/fjordllc/bootcamp/issues/2810
このIssueを分割したもの。

https://github.com/fjordllc/bootcamp/issues/3503
このIssueで作られた相談部屋にコメント機能を付ける。

![貼り付けた画像_2021_11_02_14_38](https://user-images.githubusercontent.com/168265/139792317-126d8dde-c7bd-4b82-8373-37686f7a6e88.png)

### ユーザー

自分以外の人が自分の相談部屋でコメントをしたら通知が飛ぶ。

### 管理者

自分以外の人がどこかの相談部屋でコメントをしたら通知が飛ぶ。

**Comment by mami-inuzuka** [comment]
@komagata 

以前、相談部屋にTalkモデルは不要で、Commentable_typeをUserとしてコメント機能を作れば良いというアドバイスをいただいたかと思うのですが、既存の「UserモデルとCommentモデルの関連付け」が衝突してしまう気がするので質問です🙇🏻‍♂️

　
## Commentable_typeをUserとしてコメント機能を作る際に起きてしまうこと
Commentable_typeをUserとしてコメント機能を作ると、相談部屋で相談部屋の持ち主のコメントしか表示がされずadminユーザーがコメントを投稿してもリロードすると消えてしまう現象が起こってしまいます。
（Rails consoleで確認したのですが、adminのコメントの保存自体はされています。）

![Frame 7](https://user-images.githubusercontent.com/52844263/144366621-b4f2eff6-c8ef-4d50-be1e-21b5b2518287.png)


## 原因
Commentable_typeをUserとしてコメント機能を作る場合、
```ruby
class User < ApplicationRecord
    ...
  include Commentable
    ...
end
```
とポリモーフィック関連付けを行い、
`commentable.comments`とすれば相談部屋での会話が全て取り出せることが期待される動きかと思います。
（この時のcommentableはその相談部屋のユーザーのオブジェクトが入ります）
　

ただ、現状Userモデルに下記の関連付けが既に存在しているため、
```
has_many :comments,      dependent: :destroy
```
特定のユーザーオブジェクトに対して`comments`メソッドを呼び出すと、取り出せされるのは**そのユーザーがしたコメント全て** になると思います。
```
user.comments
```
（この時userは特定ユーザーのオブジェクトが入ります）

つまり、
`commentable.comments`が行っていることは`user.comments`と同じになってしまうため、相談部屋で相談部屋の持ち主のコメントしか表示がされずadminユーザーがコメントを投稿してもリロードすると消えてしまう現象が起こっていたのではないかなと思います。
　

## 質問
Talkモデルを使わずに実装する上で、上記のような問題をを回避する方法はあるのでしょうか....?

**Comment by komagata** [comment]
@mami-inuzuka なるほど、厄介ですね〜。

関連に別名をつければできそうですが、ややこしくなるのでtalkモデルを作るというのがいいように思います〜！

**Comment by mami-inuzuka** [comment]
ありがとうございます！！それではtalkモデルを作る方向で考えてみようと思います！😊

**Comment by mami-inuzuka** [comment]
@machida 
お疲れ様です！コメント機能周りでご相談があります😊


## ▼相談したいこと
相談部屋にコメント機能を実装すると、
下記のように相談部屋の会話内容もユーザープロフィールページのコメントタブに表示されることになります。

ですが、相談部屋の会話は本人と管理者以外見れないという前提があるので
**ここのコメントタブにおいても相談部屋のコメントについては表示しないようにするのが
いいのかなと思ったのですがどうでしょうか？💡**

（相談部屋個別ページと同様に本人と管理者のみコメントタブに相談部屋の会話も表示するようにしてもいいのかもしれないですが、ここに相談部屋の会話内容が表示されると自分の発言がパブリックな場に表示されてる感がしてしまって少し不安になってしまう可能性もあるので表示しない、とするのが良いのかなと思っています。）

<img width="1435" alt="スクリーンショット 2021-12-07 18 14 49" src="https://user-images.githubusercontent.com/52844263/145000917-94278475-b66a-4097-bae4-a3ef2babc361.png">

**Comment by machida** [comment]
@mami-inuzuka 
なるほど、ありがとうございます！！
ユーザー個別ページ配下のコメントに表示されるとまずいですね。ここには表示されないようにしたいです。inuzukaさんの考えに同意で、本人がアクセスしてもここには表示されないようにしたいです。
確かに、相談部屋もコメントを使ってるけど、本人しか見れないようにする、という対応が必要になりますね。
この対応はポイントに含まれていないかもしれないので、もし、想定よりも手間が発生しましたらポイントをふり直したいと思います。（cc @komagata ）

**Comment by mami-inuzuka** [comment]
ご確認ありがとうございます！！承知しました🙆‍♀️✨
それではその要件で進めさせていただきます😊

ポイントの件も承知しました！

**Comment by komagata** [comment]
@mami-inuzuka @machida 確かに表示されちゃまずいですね。ご指摘ありがとうございます〜！

**Comment by mami-inuzuka** [comment]
@komagata @machida 通知の設定に関するご相談です。

## 相談内容
相談部屋で誰かがコメントがした場合に、既存のコメント通知の実装をそのまま使用すると
「◯◯さんからコメントが来ました」というような通知メッセージとなるのですが、
相談部屋でコメントされた際は「◯◯さんが相談部屋でコメントをしました。」などと、**相談部屋でコメントされたことがわかるようなメッセージ**にした方が良さそうでしょうか？

既存のコメント通知の実装をそのまま使用場合、下記のスクリーンショットのような通知が届くようになります。

<img width="906" alt="スクリーンショット 2021-12-26 13 30 40" src="https://user-images.githubusercontent.com/52844263/147398945-a65237ea-da64-47de-9ded-24b83eb5be9a.png">

<img width="907" alt="スクリーンショット 2021-12-26 13 30 50" src="https://user-images.githubusercontent.com/52844263/147398948-9d3bc0fb-5342-4633-a1a4-4c28dfdc6e96.png">

## 背景（気になった理由）
おそらく管理者の方は大量の通知が届いてしまうと思うのですが、相談部屋でされたコメントは他のコメントに比べて対応の優先度が高くなるのかなと思うので、他のコメント通知と同じメッセージだと迅速に対応がしづらいのかなと思いました。

ただ、基本的に全てのコメントを平等に確認するということでしたら分けなくてもいいのかもと思い、ご相談させていただきました。

## 懸念
通知メッセージを変更するとなると[CommentCallbacksモデル](https://github.com/fjordllc/bootcamp/blob/main/app/models/comment_callbacks.rb)の中に`came_talk_comment` などとメソッドを追加することになるのかなと考えているのですが、微妙な通知メッセージの差でメソッドを増やすのはどうなんだろうと気になっています。

## 補足
[まちださんからご指示いただいた要件](https://github.com/fjordllc/bootcamp/issues/3504#issue-1041902561)は下記の通りです

### コメントがあった場合の通知の設定
* ユーザー
    * 自分以外の人が自分の相談部屋でコメントをしたら通知が飛ぶ。
* 管理者
    * 自分以外の人がどこかの相談部屋でコメントをしたら通知が飛ぶ。

**Comment by machida** [comment]
@mami-inuzuka 
確認の連絡ありがとうございますー！
もし、可能でしたら相談部屋でのコメントとわかる通知だと助かります🙏

**Comment by mami-inuzuka** [comment]
@machida ありがとうございます！そうですよね！🙆‍♀️
ではその方向性で実装させていただきます！

**Comment by komagata** [comment]
@mami-inuzuka (CC: @machida)

確か同じURLに対する通知は最新の一件だけになるので問題ないように思います〜。

また、コメントはあらゆるものにつくので、Talkのコメントだけ対応するのは実装的に不自然なので、やるのだとすれば別Issueにして、全てのコメント（お知らせや日報につくコメントなど）に同じ対応をするのが良いと思います〜。

その場合、このIssueではその部分を対応しなくて大丈夫です。

**Comment by mami-inuzuka** [comment]
@komagata 
ご確認ありがとうございます！

> 確か同じURLに対する通知は最新の一件だけになるので問題ないように思います〜。

特定の相談部屋の中での通知ではなく、日報からのコメント、お知らせからのコメント、提出物からのコメント…など様々なところからメンションが飛んできてしまうので優先度の高そうな相談部屋の通知が埋もれてしまうのではという意図でした🙇🏻‍♂️
わかりづらくすみません！🙇🏻‍♂️

ですが、その上で、駒形さんのご指摘は相談部屋でコメントされたことがわかるようにするのであれば全てのコメントにおいてコメントの種類がわかるようにした方がよく、それは別issueで対応ということであっていますでしょうか？💡

**Comment by komagata** [comment]
> 特定の相談部屋の中での通知ではなく、日報からのコメント、お知らせからのコメント、提出物からのコメント…など様々なところからメンションが飛んできてしまうので優先度の高そうな相談部屋の通知が埋もれてしまうのではという意図でした🙇🏻‍♂️

なるほどですね、僕が勘違いしていました。

ただ、メンター陣は全部の通知をちゃんとみて、既読にしてると思うので（無駄なコメント通知はないと思う）、こちらは問題ではないかな〜と思っております。

> ですが、その上で、駒形さんのご指摘は相談部屋でコメントされたことがわかるようにするのであれば全てのコメントにおいてコメントの種類がわかるようにした方がよく、それは別issueで対応ということであっていますでしょうか？

はい。

その上ででも、実装は相談部屋だけ特別扱いするのはアンバランスな感じなので、やるなら全てに対応した方が良いと思います。（手間も大して変わらなさそうなので）

**Comment by mami-inuzuka** [comment]
なるほどです！承知しました😊！

それでは既存のコメント通知の実装をそのまま使用させていただきます！😊🙏
