### ISSUE TITLE
企業別のユーザー一覧で「アドバイザー」「メンター」「卒業生」のタブが欲しい。

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3520]
全体のユーザー一覧みたいな感じ。

<img width="1506" alt="貼り付けた画像_2021_11_04_22_36" src="https://user-images.githubusercontent.com/168265/140323588-2379df21-78a9-4d81-bd60-a4392a98fa38.png">

**Comment by yoshitaku-jp** [comment]
@komagata 
要件の確認をさせてください。

issueのキャプチャでは中央に配置して欲しいように見受けられますが、

>全体のユーザー一覧みたいな感じ。

とコメントにあったユーザ一覧ではボタンが左に寄っておりました。

![image](https://user-images.githubusercontent.com/15277293/144396057-5c38c7eb-398a-41e6-abb3-06dd7b378562.png)

これは左寄せと中央のどちらに近づけたほうが良いでしょうか？

**Comment by machida** [comment]
@yoshitaku-jp 左寄せでお願いしますー
