### ISSUE TITLE
お知らせの通知にお知らせのタイトルを含めてほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3532]
今、お知らせが新規投稿されると、XXXさんからのお知らせです、としか通知されないので、通知にタイトルを含むようにしてほしいです。サイト内通知、メール同様にお願いします。

お知らせ「XXX」

という通知にして、XXXさんから は通知に無くしちゃっていいです。

**Comment by taka61** [comment]
本番環境で動作確認できたのでクローズします🙆‍♀️
