### ISSUE TITLE
通知ページの「全て」のタブに全件数と未読の件数のバッチが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3538]
<img width="541" alt="スクリーンショット 2021-11-09 15 54 05" src="https://user-images.githubusercontent.com/16577/140876807-7f4a539f-ec60-4476-8ae7-8f74ed8bccf1.png">

こういう感じ。

**Comment by taka61** [comment]
本番環境で確認できました。Issueはcloseします🙆‍♀️
