### ISSUE TITLE
通知ページの「フォロー中」のタブに全件数と未読の件数のバッチが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3540]
<img width="541" alt="スクリーンショット 2021-11-09 15 54 05" src="https://user-images.githubusercontent.com/16577/140876807-7f4a539f-ec60-4476-8ae7-8f74ed8bccf1.png">

こういう感じ。

重い処理になりそうなので、提出物の件数でやっているようにキャッシュもしたい。

**Comment by machida** [comment]
#3907 に含めることになったのでこちらはclose
