### ISSUE TITLE
通知ページの「メンション」のタブに全件数と未読の件数のバッチが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3543]
<img width="541" alt="スクリーンショット 2021-11-09 15 54 05" src="https://user-images.githubusercontent.com/16577/140876807-7f4a539f-ec60-4476-8ae7-8f74ed8bccf1.png">

こういう感じ。

重い処理になりそうなので、提出物の件数でやっているようにキャッシュもしたい。

**Comment by AudioStakes** [comment]
@komagata @machida 
こちらの Issue について、想定よりも作業量がだいぶ多くなってしまったため、ポイントの調整をお願いできますでしょうか？
「件数の表示」と「件数のキャッシュの保持」はそれほど時間をかけずに実装できたものの、「キャッシュの削除」については削除する条件を整理して一つ一つ対処していく必要があり、その分作業量が多くなってしまいました。

急ぎではありませんので、ご都合の良いときに見てもらえましたらありがたいです！
お手数おかけしますが、よろしくお願いいたします🙏

**Comment by komagata** [comment]
@AudioStakes 了解です。ポイントを増やしておきました〜

**Comment by AudioStakes** [comment]
@komagata ありがとうございます！

**Comment by AudioStakes** [comment]
本番環境で動作確認できましたので、close しますー
