### ISSUE TITLE
通知ページの「お知らせ」のタブに全件数と未読の件数のバッチが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3544]
<img width="541" alt="スクリーンショット 2021-11-09 15 54 05" src="https://user-images.githubusercontent.com/16577/140876807-7f4a539f-ec60-4476-8ae7-8f74ed8bccf1.png">

こういう感じ。

重い処理になりそうなので、提出物の件数でやっているようにキャッシュもしたい。

**Comment by machida** [comment]
#3907 にIssueをまとめたので、このIssueはcloseします。
変更点として、今までの総数は確認する機会がないので無しにして、未読数だけ表示するようにしました。
