### ISSUE TITLE
app/views/users/_user.html.slim は使われてないファイルか調査し、不要だったら消す

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3548]

**Comment by naomichi-h** [comment]
@machida 調査結果を以下に記述します。確認のほど、よろしくお願いいたします。

# 結論
app/views/users/_user.html.slimは現状必要なファイルであり、削除はできない。

# 調査内容
- app/views/users/_user.html.slim が他のviewファイルから呼び出されているかの調査
- app/views/users/_user.html.slim を削除した際、使われている箇所がどうなるかの確認

## app/views/users/_user.html.slim が他のviewファイルから呼び出されているかの調査
- `render 'users/user'`もしくは`render partial: 'users/user'`で全ファイル内検索をしたところ、`app/views/companies/users/index.html.slim`と`app/views/generations/show.html.slim`で呼び出されていることがわかった

## app/views/users/_user.html.slim を削除した際、使われている箇所がどうなるかの確認
### app/views/companies/users/index.html.slim
- 企業に所属しているユーザー一覧の表示に使われている
- app/views/users/_user.html.slim を削除した場合、
![スクリーンショット 2021-12-16 1 31 31](https://user-images.githubusercontent.com/73326842/146226040-1059ae49-85cc-4d64-a3f0-981a0fe385a4.png)
のユーザータブを押下すると`ActionView::MissingTemplate in Companies::Users#index`エラーとなる。
### app/views/generations/show.html.slim
- 期生別のユーザー一覧の表示に使われている
- app/views/users/_user.html.slim を削除した場合、
![スクリーンショット 2021-12-16 1 38 26](https://user-images.githubusercontent.com/73326842/146227191-82a9d4de-4241-45cb-80bf-d77c4c727ce9.png)
の何期生かを選択すると`ActionView::MissingTemplate in Generations#show`エラーとなる。
