### ISSUE TITLE
アイコンが楕円で表示されるユーザーがいる

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#3566]
https://bootcamp.fjord.jp/products/9846 を見てると、コメント欄のユーザーアイコンが楕円になってるユーザーがいました。

<img width="77" alt="Screen Shot 2021-11-15 at 8 21 06" src="https://user-images.githubusercontent.com/1148320/141702755-eed07d15-2049-4d44-b0cf-b66d3cad65d5.png">

ブラウザ

- Chrome Version 95.0.4638.69 (Official Build) (arm64)
- macOS 11.6

**Comment by machida** [comment]
Issueありがとうございます！
https://github.com/fjordllc/bootcamp/pull/3569
こちら対応しましたー

**Comment by JunichiIto** [comment]
対応ありがとうございます！！
