### ISSUE TITLE
コメントはコメントした本人と管理者（メンターは外す）だけが編集・削除できるようにしたい

### ISSUE THREAD

**Issue by yuuu** [fjordllc/bootcamp#3573]
スマホ版の提出物画面で他人のコメントに編集ボタンが表示される

## 概要

スマホ版の提出物画面のコメント欄で、自分以外のコメントにも編集ボタンが表示されています。

ボタンを押すと、テキストエリアが表示され、編集できそうです。編集を保存できるかどうかは未確認です。

メンターとして、アクセスしています。メンター以外の画面でも再現するかどうかは未確認です。

## 再現手順

1. 提出物の詳細画面にアクセス ( 例: https://bootcamp.fjord.jp/products/10002#comment_79547 )
2. 他人のコメントにも「編集」が表示されている

## 期待される振る舞い

自分のコメントにのみ編集ボタンが表示される

## スクリーンショット

![貼り付けた画像_2021_11_16_9_03](https://user-images.githubusercontent.com/8074640/141871770-8e0bba96-23b8-4ad4-ac31-431d1be7886e.png)

## 環境

 - OS: iOS 14.8.1
 - ブラウザ: Chrome
 - バージョン: 95.0.4638.50

## 関連Issue

おそらく、なし

**Comment by taka61** [comment]
@machida さん
このIssueの問題はスマホ版（PCでは問題なしでした）でのみ発生するバグだと思うのですが、
スマホ版のバグは私の方では確認できない状態にあります。
そのため実装が失敗か成功か確かめる方法が現在ないのですが、スマホ版の挙動をこちら側で確かめる方法は何かありますでしょうか？
以下の方法は既に試してみたのですが、これらの方法だとIssueに書かれているバグが確認できませんでした。

・[簡単localhost:3000をスマホ（iPhone）でも確認する方法](https://cloud5.jp/ruby_on_rails_localhost_access/)
・[PC版Chromeブラウザでスマホサイトをチェックする](https://atmarkit.itmedia.co.jp/ait/articles/1403/20/news050.html)

ご確認の程、よろしくお願いします🙏

**Comment by machida** [comment]
@taka61 
ごめんなさい！！
これ、Issueでやってほしいことはすでに実装されていました🙇‍♂️
申し訳ないです。
原因は、メンターに管理者権限も付与しているため、編集ボタンが表示されているというものでした。
なので、こちらはcloseにしたいと思います🙇‍♂️

---

ちなみに、フィヨルドブートキャンプではデバイスによる表示の出し分けは使っていないので、全てデバイスの横幅だけで表示内容を制御しています。

デベロッパーツールの

<img width="575" alt="貼り付けた画像_2021_12_07_12_24" src="https://user-images.githubusercontent.com/168265/144960630-ed14be28-fe06-4766-860d-6e60c39645b6.png">

ここをクリックして、スマホ表示を選択することで、スマホのときの表示の確認ができますー

**Comment by machida** [comment]
:memo:
#3682
これをやってこのバグは修正されます。

**Comment by taka61** [comment]
@machida さん
こちらのIssueをcloseとのこと承知いたしました〜！
>ちなみに、フィヨルドブートキャンプではデバイスによる表示の出し分けは使っていないので、全てデバイスの横幅だけで表示内容を制御しています。

デバイスによる表示の出し分けは行なっていないのですね👀
教えて頂きありがとうございます🙏
