### ISSUE TITLE
Docsタグ名を一括で変更できるようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3577]

**Comment by taka61** [comment]
@komagata @machida
管理者向けの機能のため、お手数ですが本番環境での確認をお願いいたします!🙇‍♀️

**Comment by komagata** [comment]
@taka61 本番環境で動作することを確認しました。

**Comment by taka61** [comment]
@komagata ご確認いただきありがとうございます!🙏

##
本番環境で動作確認できたため、クローズいたします!

**Comment by komagata** [comment]
@taka61 すみません、もう終わったと勘違いしてTeamメンバーを整理しているときにはずしてしまっていました。
僕の方でCloseしておきます〜！

**Comment by taka61** [comment]
@komagata 
closeまでして頂きありがとうございました😀🙏
