### ISSUE TITLE
レビューを担当する提出物のタイトルを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3588]
メンターでログインし、提出物へ、自分の担当タブを開いたときのページ。
以下の部分を「提出物」にする。

<img width="782" alt="貼り付けた画像_2021_11_18_10_40" src="https://user-images.githubusercontent.com/168265/142335653-8ce4bfee-1619-4060-914d-d70ad8de88c1.png">

**Comment by unstoppa61e** [comment]
@machida 
こちらのissueですが、着手しようとしたところ、既にissueがこなされているように見えるのですが、いかがでしょうか？
![スクリーンショット 2021-12-06 15 44 29](https://user-images.githubusercontent.com/46347198/144800093-9c7c70d3-2e26-4288-875c-d266aab7ce2f.png)

**Comment by unstoppa61e** [comment]
@machida 
おはようございます。
こちら、いかがでしょうか？

**Comment by unstoppa61e** [comment]
@machida 
何度もすみません。
こちら、クローズして頂くのがよろしいかと思うのですが、いかがでしょうか？
