### ISSUE TITLE
Q&A詳細ページにあるタグを押した際に、特定の文字が含まれているとタグ別のQ&Aページに遷移できない

### ISSUE THREAD

**Issue by IkumaTadokoro** [fjordllc/bootcamp#3592]
## 概要

Q&A詳細ページにあるタグのうち、URLとして意味を持つ文字（`#`、`?`、`%`）を含むタグをクリックすると、特殊文字がURLとして解釈され、意図しないページに遷移してしまう。

## 再現手順

本番環境「`#CSS上級`」をタグに持つ質問（=404が発生する例）

1. https://bootcamp.fjord.jp/questions/860 にアクセス
2. タグの「#CSS上級」のリンクを押す
3. 404 Not Foundが発生する

## 期待される振る舞い

指定したタグの、タグ別のQ&Aページに正しく遷移できるようにしたい。
文字列が直接URLとして埋め込まれているので、特殊文字はエスケープした上でリンクを生成するのが正しいと思われます。

## 補足

- Q&A一覧ページのタグはURLがエスケープされているため問題ないことを確認済

## 環境

 - OS: macOS BigSur
 - ブラウザ: Google Chrome
 - バージョン: 96

**Comment by machida** [comment]
Docsの方は対応済 #3593

**Comment by naomichi-h** [comment]
本番環境で正しく動作することを確認できたため、closeします。
