### ISSUE TITLE
Docs詳細ページにあるタグを押した際に、特定の文字が含まれているとタグ別のDocsページに遷移できない

### ISSUE THREAD

**Issue by IkumaTadokoro** [fjordllc/bootcamp#3593]
## 概要

#3592 **のDocs版です**

Docs詳細ページにあるタグのうち、URLとして意味を持つ文字（`#`、`?`、`%`）を含むタグをクリックすると、特殊文字がURLとして解釈され、意図しないページに遷移してしまう。

## 再現手順

本番環境には該当データなし。以下404が発生するケース

1. https://bootcamp.fjord.jp/pages/XXX にアクセス
2. 「#Test」というタグを登録する。
3. 登録した「#Test」をクリックする
4. 404 Not Foundが発生する

## 期待される振る舞い

指定したタグの、タグ別のDocsページに正しく遷移できるようにしたい。
文字列が直接URLとして埋め込まれているので、特殊文字はエスケープした上でリンクを生成するのが正しいと思われます。

## 補足

- Docs一覧ページのタグはURLがエスケープされているため問題ないことを確認済

## 環境

 - OS: macOS BigSur
 - ブラウザ: Google Chrome
 - バージョン: 96

**Comment by IkumaTadokoro** [comment]
@komagata 
別機能を実装していて気がついたのですが、Docsとユーザープロフィールのタグ入力部分は共通のコンポーネントを使っていました（Q&Aのタグは同じ構造ですが別のコンポーネント）。

マージ済みの #3606 でユーザープロフィールのタグの同様のバグを修正すると同時に、本issueも修正が完了していたので、差し支えなければこのissueは私の方で引き取らせていただければと思います🙏

**Comment by komagata** [comment]
@IkumaTadokoro なるほどですね！
そうしていただければ大変助かります。ありがとうございます〜！

**Comment by IkumaTadokoro** [comment]
本番環境で確認したため、クローズいたします！
