### ISSUE TITLE
「コース一覧」ページの表示が空になっている

### ISSUE THREAD

**Issue by unstoppa61e** [fjordllc/bootcamp#3595]
## 概要

フッターから飛べる「コース一覧」ページの表示が空になっています。

## 再現手順

https://bootcamp.fjord.jp/courses にアクセス

## スクリーンショット

<img width="1318" alt="2021-11-19_8 23 32" src="https://user-images.githubusercontent.com/46347198/142578321-4cfdea13-e7ff-4d48-a5d9-c0a0f31ff3af.png">

## 環境
 - OS: macOS Mojave バージョン 10.14.6
 - ブラウザ: Chrome

**Comment by machida** [comment]
管理者は非公開コースも見えるのですが、それ以外のroleでは非公開のコースが見えないのでこの様になっています。なので、公開コースがないときは、「公開コースはありません」という文言と泣き顔を表示していただきたいですー

**Comment by unstoppa61e** [comment]
本番環境で動作を確認できたため、close させて頂きました。
