### ISSUE TITLE
日報の入力欄の最下部が、途中保存の tip 表示と重なり隠れて見えにくくなってしまっている

### ISSUE THREAD

**Issue by unstoppa61e** [fjordllc/bootcamp#3599]
## 概要

日報の作成時、入力欄の最下部が、途中保存の tip 表示と重なり隠れて見えにくくなってしまって困る。

## 再現手順

1. 日報にある程度の情報を記入
2. ブラウザの幅を、２カラム表示になる幅よりも更に広げる

## スクリーンショット

<img width="493" alt="スクリーンショット 2021-11-20 9 50 16" src="https://user-images.githubusercontent.com/46347198/142708205-c1907928-9f1f-451b-8402-042f6b03cf9d.png">

## 環境

ブラウザ: Chrome
## 関連Issue

Ref: #2838

**Comment by machida** [comment]
報告ありがとうございます！！こちら対応したので次回リリースで修正されますー

**Comment by machida** [comment]
こちら対応しましたー
