### ISSUE TITLE
テスト用ユーザデータのFacebookURLが、Fjordに関係がなさそうな実在する人のURLになっている

### ISSUE THREAD

**Issue by yoshitaku-jp** [fjordllc/bootcamp#3601]
テスト用ユーザデータのFacebookURLにおいて、Fjordに関係がなさそうな実在する人のURLが設定されているように見受けられます。

ex)
- https://github.com/fjordllc/bootcamp/blob/main/db/fixtures/users.yml#L58
- https://github.com/fjordllc/bootcamp/blob/main/db/fixtures/users.yml#L97
- https://github.com/fjordllc/bootcamp/blob/main/db/fixtures/users.yml#L347
- https://github.com/fjordllc/bootcamp/blob/main/db/fixtures/users.yml#L538

おそらく`http://www.facebook.com/`の固定文字と`login_name`で生成し、偶然できたものかと思います。
issueとしてあげておきます。

**Comment by machida** [comment]
facebook の URL は以下に修正する。
https://www.facebook.com/fjordllc

**Comment by komagata** [comment]
:memo: `db/fixtures` と `test/fixutures` の両方を確認する。

**Comment by machida** [comment]
これはテストデータが変わるだけなので、マージされたらIssueはクローズしてしまってください

**Comment by siroemk** [comment]
マージされたのでcloseします！
