### ISSUE TITLE
書籍一覧ページが欲しい

### ISSUE THREAD

**Issue by obregonia1** [fjordllc/bootcamp#3604]
**何故この機能が必要なのか**

- 先のプラクティスページを一つ一つ確認して書籍が必要か確認して購入する必要がある
- 書籍が必要なプラクティスに到達したが、書籍が用意できていないため着手することができない

などの問題があったが、書籍一覧ページを見ることでどのプラクティスでどの書籍が必要になるか把握できるようになるため。

**機能の説明**

ヘルプページに参考書籍とその書籍を使うプラクティスが一覧できるページをつくる

参考: [プラクティスを進める上で必要な書籍に関して \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/questions/1093)

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/pull/3426
こちらで対応中ですー

**Comment by machida** [comment]
こちらリリースしたのでクローズしますー
