### ISSUE TITLE
ダッシュボードの表示が遅い

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#3614]
最近、ダッシュボード（ https://bootcamp.fjord.jp/ ）の表示で3〜5秒ぐらい待たされる印象があります。
ちょっともたつく感があるので1〜2秒以内にレスポンスが返ると嬉しいです。

**Comment by shibaaaa** [comment]
関連していると思われるものをコメントしておきますー
- #3276

**Comment by JunichiIto** [comment]
@shibaaaa 情報ありがとうございます！
