### ISSUE TITLE
提出物の自分の担当の数に確認済のものも含んでしまっている

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3626]
管理者でログインし、左ナビの提出物をクリック。

<img width="750" alt="貼り付けた画像_2021_11_26_17_42" src="https://user-images.githubusercontent.com/168265/143552388-73fecc35-11a7-47dc-97e8-b2b020bbaf9e.png">

ここのカッコの中の数字に、確認済の提出物は含めないようにしたい。

**Comment by taka61** [comment]
@komagata さん
お手数ですが、本番環境でこちらのIssueの実装に問題がないか確認頂けますよう、
よろしくお願いします。

**Comment by komagata** [comment]
@taka61 はい、本番環境で動作することを確認しました。

**Comment by taka61** [comment]
@komagata さん
ありがとうございます!🙏
こちらのissueクローズします！
