### ISSUE TITLE
提出物の状態を更新しても「未完了」と「自分の担当」のタブのバッジに表示される件数が変わらない

### ISSUE THREAD

**Issue by AudioStakes** [fjordllc/bootcamp#3638]
## 概要

提出物の状態を更新しても、提出物一覧ページの「未完了」と「自分の担当」のタブのバッジに表示される件数が変わりません。

![image](https://user-images.githubusercontent.com/15713392/143984160-7c6cc176-d3ae-4558-9bca-0d5dd10dc464.png)

### 「未完了」のタブのバッジ

1. 未完了の提出物一覧 （`/products/unchecked`） にアクセス
2. 未完了タブのバッジに表示されている件数を目視で確認
3. 未完了の提出物を開いて「提出物を確認」ボタンをクリック（完了の状態にする）
4. 未完了の提出物一覧 （`/products/unchecked`） にアクセス
5. 未完了タブのバッジに表示されている件数が手順 2 で確認した数と同じ

### 「自分の担当」タブのバッジ

1. 自分の担当の提出物一覧 （ `/products/self_assigned`） にアクセス
2. 自分の担当タブのバッジに表示されている件数を目視で確認
    - バッジには「自分の担当」かつ「未返信」の件数が表示されている
3. 「自分の担当」かつ「未返信」の提出物にコメントする（返信する）
4. 自分の担当の提出物一覧 （ `/products/self_assigned`） にアクセス
5. 自分の担当タブのバッジに表示されている件数が手順 2 で確認した数と同じ

### 「未完了」のタブのバッジ

未完了の提出物1件を完了（確認済み）にすると、「未完了」のタブのバッジに完了前よりも 1 少ない値が表示されてほしい

### 「自分の担当」タブのバッジ

「自分の担当」かつ「未返信」の提出物1件に返信すると、「自分の担当」タブのバッジに返信前より 1 少ない値が表示されてほしい

## 補足事項

- このバグの動作確認を development 環境で行う場合は、Rails のキャッシュを有効にすること
    - Rails のキャッシュを有効にする方法
        - [https://railsguides.jp/caching_with_rails.html#development環境のキャッシュ](https://railsguides.jp/caching_with_rails.html#development%E7%92%B0%E5%A2%83%E3%81%AE%E3%82%AD%E3%83%A3%E3%83%83%E3%82%B7%E3%83%A5)
- 「未返信」と「未アサイン」のタブのバッジに表示される件数ついては、返信もしくはアサインした後に 1 減る（期待通りの挙動）
    - ただし、1 減らない手順もあるかもしれない

## 環境

 - OS: macOS Monterey 12.0.1 
 - ブラウザ: Google Chrome Version 96.0.4664.55

## 関連Issue

Refs: #3022, #3594

**Comment by komagata** [comment]
@AudioStakes こちらポイント5にしておきました〜

**Comment by AudioStakes** [comment]
**[@komagata](https://github.com/komagata)**

こちらメンター向けの機能のため、お手数おかけしますが、リリース後に本番環境での動作確認をお願いいたします🙏

## 確認対象のキャプチャ

![image](https://user-images.githubusercontent.com/15713392/149457676-8feedd5d-3db9-4eca-9ff4-8af14c4db32d.png)

## 確認手順

各項目の起点となるページは、提出物一覧ページ [https://bootcamp.fjord.jp/products](https://bootcamp.fjord.jp/products) です。

### **未完了の件数（未完了タブの表示件数）**

- [ ]  未完了の提出物が確認済み（完了）に更新されたあと、未完了の件数が1件減っていること
- [ ]  確認済み（完了）の提出物が未完了に更新されたあと、未完了の件数が1件増えていること

### **「自分の担当」かつ「未返信」の件数（自分の担当タブのバッジの表示件数）**

- [ ]  「未アサイン」の提出物の担当になったあと、「自分の担当」かつ「未返信」の件数が1件増えていること
- [ ]  「自分の担当」かつ「未返信」の提出物の担当を外れたあと、「自分の担当」かつ「未返信」の件数が1件減っていること
- [ ]  「自分の担当」かつ「未返信」の提出物に担当がコメントしたあと、「自分の担当」かつ「未返信」の件数が1件減っていること
- [ ]  「自分の担当」かつ「未返信」の提出物の最新コメントが削除されて担当者のコメントが最新となったあと、「自分の担当」かつ「未返信」の件数が1件減っていること
- [ ]  「自分の担当」かつ「返信済み」の提出物に担当者以外がコメントしたあと、「自分の担当」かつ「未返信」の件数が1件増えていること
- [ ]  「自分の担当」かつ「返信済み」の提出物の最新コメントが削除されて担当以外のコメントが最新になったあと、「自分の担当」かつ「未返信」の件数が1件増えていること

**Comment by komagata** [comment]
@AudioStakes 本番環境で確認しています。

> 「未アサイン」の提出物の担当になったあと、「自分の担当」かつ「未返信」の件数が1件増えていること

これが増えていないかもです〜（赤丸の数字）

<img width="1285" alt="スクリーンショット 2022-01-14 15 14 39" src="https://user-images.githubusercontent.com/16577/149460615-bea9cdd9-be48-468c-a0e0-1c4f82d369d1.png">

**Comment by AudioStakes** [comment]
@komagata 
ご確認ありがとうございます！
すみません、こちらの Issue は来週2022/01/20(木)にリリース予定でして、今はまだリリースされていませんでした💦
いつ（どのリリースの後に）確認してほしいか、明記するようにします🙇‍♂️

もしくは、お願いするタイミングとして、基本的にリリースが終わったあとにお願いした方が良いでしょうか？

**Comment by komagata** [comment]
@AudioStakes なるほどです、早合点しちゃってすみません。

**Comment by JunichiIto** [comment]
未アサインのバッジの数と画面上に表示されている件数が一致しないのですが、この件はこのissueに関連していますか？

<img width="806" alt="Screen Shot 2022-01-15 at 9 44 35" src="https://user-images.githubusercontent.com/1148320/149602070-7a2afbcc-86b5-4646-98ec-804ba0923d4e.png">

いくつか提出物を確認済みにしたのに、バッジの件数が変わらないので 🤔 と思っていました。

**Comment by AudioStakes** [comment]
@JunichiIto 
ご報告ありがとうございます！

> 未アサインのバッジの数と画面上に表示されている件数が一致しない

未アサインの件数が変わってもバッジの表示件数が変わらないことがありまして、おそらくそれが原因で一致していないのだと思われます。未アサインのバッジの件数が変わらないという挙動については、現在 #3646 で対応中です🙏

**Comment by JunichiIto** [comment]
@AudioStakes なるほど、既知の不具合だったんですね。修正よろしくお願いします！

**Comment by AudioStakes** [comment]
@komagata こちらのメンター向けの機能のため、お時間のあるときに本番環境での動作確認をお願いいたしますー🙏
※ 動作確認方法は https://github.com/fjordllc/bootcamp/issues/3638#issuecomment-1012793978 に記載しました

**Comment by komagata** [comment]
@AudioStakes 本番環境で動作することを確認しました。

**Comment by AudioStakes** [comment]
@komgata ご確認、ありがとうございます！close しますー。
