### ISSUE TITLE
提出物一覧ページの「未アサイン」タブのバッジに表示される件数が変わらないことがある

### ISSUE THREAD

**Issue by AudioStakes** [fjordllc/bootcamp#3646]
## 概要

Rails の test モードでキャッシュを有効にしてテストした結果テストが1つ失敗します。失敗する原因は「未アサイン」の提出物に担当がついても（つまり未アサイン件数が減っても）「未アサイン」タブに表示される件数が変わらないことのようです。

失敗するテストは以下です。

[https://github.com/fjordllc/bootcamp/blob/31c3efd827b61734d25cdf90eed66dd7865d3108/test/system/products_test.rb#L434-L446](https://github.com/fjordllc/bootcamp/blob/31c3efd827b61734d25cdf90eed66dd7865d3108/test/system/products_test.rb#L434-L446)

なお、テストを実行するときは test モードのキャッシュストアを production モードと同じ **[`ActiveSupport::Cache::MemoryStore`](https://railsguides.jp/caching_with_rails.html#activesupport-cache-memorystore)** （キャッシュをメモリに保持）に設定しました。現状はキャッシュストアとして **[`ActiveSupport::Cache::NullStore`](https://railsguides.jp/caching_with_rails.html#activesupport-cache-nullstore)** （キャッシュを保持しない）を使用しており、その場合は上記のテストが成功します。

## 再現手順

1. Rails を test モードで実行する時にキャッシュストアとして **[`ActiveSupport::Cache::MemoryStore`](https://railsguides.jp/caching_with_rails.html#activesupport-cache-memorystore)** を使うように設定
    
    ```diff
    diff --git a/config/environments/test.rb b/config/environments/test.rb
    index e080eba6d..c20b14524 100644
    --- a/config/environments/test.rb
    +++ b/config/environments/test.rb
    @@ -25,7 +25,7 @@ Rails.application.configure do
       # Show full error reports and disable caching.
       config.consider_all_requests_local       = true
       config.action_controller.perform_caching = false
    -  config.cache_store = :null_store
    +  config.cache_store = :memory_store
     
       # Raise exceptions instead of rendering exception templates.
       config.action_dispatch.show_exceptions = false
    ```
    
2. テストを実行
    - `$ rails test:all`
3. 上記のテストが失敗する。
    ※ 以下のログは落ちるテストのみを対象にテストを実行
    
    ```bash
    $ rails test test/system/products_test.rb:434
    Running via Spring preloader in process 23787
    Run options: --seed 31601
    
    # Running:
    
    Capybara starting Puma...
    * Version 5.5.1 , codename: Zawgyi
    * Min threads: 0, max threads: 4
    * Listening on http://127.0.0.1:52742
    [Screenshot Image]: /Users/satoudaisuke/src/github.com/fjordllc/bootcamp/tmp/screenshots/failures_test_show_unassigned_products_counter_and_can_change_counter_after_click_assignee-button_on_unassigned-tab.png
    F
    
    Failure:
    ProductsTest#test_show_unassigned_products_counter_and_can_change_counter_after_click_assignee-button_on_unassigned-tab [/Users/satoudaisuke/src/github.com/fjordllc/bootcamp/test/system/products_test.rb:445]:
    Expected "55" to not be equal to "55".
    
    rails test test/system/products_test.rb:434
    
    Finished in 9.373226s, 0.1067 runs/s, 0.1067 assertions/s.
    1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
    ```

## 期待される振る舞い

キャッシュを保持するようにした状態でも上記のテストが成功すること（すなわち「未アサイン」の件数が減ったときに「未アサイン」タブに表示される件数も減ること）

## 補足

現状の設定、すなわち `config.cache_store = :null_store` （キャッシュを保持しない）、の場合は同じテストが成功している

```bash
$ rails test test/system/products_test.rb:434
Running via Spring preloader in process 20633
Run options: --seed 40012

# Running:

Capybara starting Puma...
* Version 5.5.1 , codename: Zawgyi
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:52417
.

Finished in 8.358322s, 0.1196 runs/s, 0.1196 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

## 環境

- OS: macOS Monterey 12.0.1
- ブラウザ: Google Chrome Version 96.0.4664.55

## 関連 PR

Ref: #3027

**Comment by AudioStakes** [comment]
@komagata
こちらメンター向けの機能のため、お手数おかけしますが、次のリリース後に本番環境での動作確認をお願いいたします🙏
なお、次のリリース予定日は明日2022/01/20(木)であり、本日1/19(木)はまだリリースされていません。

## 確認対象のキャプチャ

![image](https://user-images.githubusercontent.com/15713392/150061488-65827dd7-c610-4091-ab06-02def10afcaa.png)

## 確認手順

### すべての手順に共通すること

- 確認対象は「未アサイン」タブのバッジに表示される件数（以下、未アサイン件数）
- メンター ( `komagata` など）としてログインする
- 手順の始めに提出物一覧ページの未アサイン件数を確認する
    - [https://bootcamp.fjord.jp/products/unassigned](https://bootcamp.fjord.jp/products/unassigned)

### 確認すること

- [ ]  「未アサイン」の提出物の担当になったあとに画面を更新すると、未アサイン件数が1件減っていること
- [ ]  「自分の担当」の提出物の担当から外れたあとに画面を更新すると、未アサイン件数が1件増えていること
- [ ]  新しい提出物が作成されたあと、未アサイン件数が1件増えていること
- [ ]  「未アサイン」の提出物が削除されたあと、未アサイン件数が1件減っていること

**Comment by AudioStakes** [comment]
@komagata こちらのメンター向けの機能のため、お時間のあるときに本番環境での動作確認をお願いいたしますー🙏
※ 動作確認方法はコメント済みです

**Comment by komagata** [comment]
@AudioStakes 本番環境で動作することを確認しました。

**Comment by AudioStakes** [comment]
@komagata ご確認、ありがとうございます！close しますー。
