### ISSUE TITLE
「プラクティス」のページを開いた際、着手中のプラクティスのカテゴリーまでスクロールしてほしい

### ISSUE THREAD

**Issue by unstoppa61e** [fjordllc/bootcamp#3647]
**何故この機能が必要なのか**

「プラクティス」のページを開いた後で、現在取り組み中のプラクティスの内容を確認するために画面をスクロールするという作業を、何十回も繰り返してきました。
この機能を実装すれば、スクロールする労力と時間を省けます。

**機能の説明**

1. ユーザーがプラクティスページを開く
2. 現在着手中のプラクティスのカテゴリまで画面がスクロールしてくれる
※スクロールにこだわりがある訳ではなく、自分でスクロールする手間が省けるのならば、どのような形でも構いません。

**Comment by nga20167304** [comment]
@unstoppa61e 
お疲れ様です。
ユーザーのプラクティスページが以下の画像の状態ですか。
<img width="1440" alt="スクリーンショット 2021-12-06 12 10 00" src="https://user-images.githubusercontent.com/38340962/144790822-f71e6072-4b6f-4b33-9432-b004b6b3dd73.png">
そして、私の方がこのページにスクロールがあります。
間違ったら教えてくれませんか。
その他、機能の説明の画像も追加させていただけませんか。
よろしくお願い致します。

**Comment by unstoppa61e** [comment]
@nga20167304 
こんにちは！
例えば僕の場合、「開発に参加して PR を送りマージする」プラクティスに「着手」している状態ですので、「プラクティス」のページにジャンプした時に、「開発に参加して PR を送りマージする」プラクティスが所属する「システム開発」のカテゴリがトップに表示されてほしいです。
つまり、僕が「プラクティス」のリンクを開いた時、ブラウザの画面が、添付した画像の状態になっていてほしいです。

nga さんが聞いてくださっている内容を僕が理解できているか、僕はあまり自信がありません。
これで nga さんの質問の答えになっていますでしょうか？
これでまだ不十分でしたら、遠慮なさらずに、またメッセージを送ってください。
You can use English if you are more comfortable with using it than using Japanese.
![スクリーンショット 2021-12-06 16 09 12](https://user-images.githubusercontent.com/46347198/144803776-7b340536-8267-4aab-a7cb-39b75c50834c.png)

**Comment by machida** [comment]
@nga20167304 @unstoppa61e

なるほど、着手中のプラクティスへスクロールするのではなく、着手中のプラクティスがあるカテゴリーにスクロールしてほしいということですね！！

**Comment by unstoppa61e** [comment]
@nga20167304 @machida 
なんとなく、そちらの方が見栄えがきれいかと思い、そのようにリクエストさせて頂きました。
ですが、特にこだわりがある訳ではありませんので、着手中のプラクティスそのものへのスクロールでも全く問題ございません。

**Comment by machida** [comment]
@nga20167304 

今は、リンクのURLを `/courses/829913840/practices#practice_473419339` として、着手中のプラクティスの位置にスクロールしています。

これを変更します。

カテゴリー id を使って、

<img width="459" alt="貼り付けた画像_2021_12_06_16_22" src="https://user-images.githubusercontent.com/168265/144804358-029b159e-bfb6-4160-9857-4068319fba61.png">

`/courses/829913840/practices#category-7` のようにお願いします。

---

@unstoppa61e 確かに、前後のプラクティスが見れた方がいいので、カテゴリーに飛ばした方が良さそうです。カテゴリーに移動するように変更したいと思います。

**Comment by nga20167304** [comment]
@unstoppa61e 
答えてくださってありがとうございます。
つまり、着手中のプラクティスがある場合、左の「プラクティス」をクリックすると、以下の画像になっていますね。

<img width="1436" alt="スクリーンショット 2021-12-06 15 14 46" src="https://user-images.githubusercontent.com/38340962/144811489-771e1ea2-51e8-4aca-af74-ec757c39e635.png">

unstoppa61e さんのほしいものとしては、https://github.com/fjordllc/bootcamp/issues/3647#issuecomment-986503334 の画像の通りですね。
かしこまりました！
よろしくお願い致します。

**Comment by nga20167304** [comment]
@machida
ヒントと理解くださってありがとうございます〜
頑張ります〜
