### ISSUE TITLE
管理画面・企業一覧でDescriptionを削除したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3650]
![貼り付けた画像_2021_12_01_22_06](https://user-images.githubusercontent.com/168265/144239901-13e2dbac-058b-4c19-8e86-af3231d330ec.png)

Descriptionが長いが、不要なので。

**Comment by machida** [comment]
@R-Tsukada 本番環境で確認しました

**Comment by R-Tsukada** [comment]
@machida 
ありがとうございます！
それではこちらのissueはcloseしておきます。
