### ISSUE TITLE
welcomeのフッタのcopyrightの年の表示を変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3653]
/welcome このページのフッタ

<img width="741" alt="貼り付けた画像_2021_12_02_0_41" src="https://user-images.githubusercontent.com/168265/144265578-79242c67-a3de-4ea8-a3ab-b8faf505803e.png">

こうしたい。

<img width="741" alt="貼り付けた画像_2021_12_02_0_41" src="https://user-images.githubusercontent.com/168265/144265643-73b08434-e057-4aaf-b264-a8092a83d6ca.png">

2021 は動的に今の年を表示する。

**Comment by Paru871** [comment]
@machida 
お疲れさまです。
Issueの内容から外れるのですが、気づいたことがありましたので相談させてください！
こちらのwelcomeページのフッターの「Fjord Inc.」にはリンクは何もないのですが、ログイン後のフッターの「Fjord Inc.」には「https://fjord.jp/」のリンクがあります。
・welcomeページの方だけリンクがないのには理由があるのでしょうか？
・リンクの有無を揃えた方がいいでしょうか？
・リンクありにする場合、このIssue内で作業してしまっていいでしょうか？それとも別Issueにて対応していただくのがいいのでしょうか？
初めての作業でわからないことだらけですが、ご判断をお願いいたしますー🙏

**Comment by machida** [comment]
@Paru871 おおー、リンクの貼り忘れですね。これは別Issueにして、今回のには含めないようにしたいと思いますー(good first issue を増やしたいのが理由です)。

**Comment by Paru871** [comment]
@machida 
返信ありがとうございます。
かしこまりました！それでは今回のIssueでは年の表示の変更のみで進めていきます。

**Comment by Paru871** [comment]
本番環境で確認できましたのでCloseとさせていただきます🙋🏻‍♀️
