### ISSUE TITLE
Q&Aが投稿されたらメンターに通知がいくようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#366]
新規Question作成時、回答が投稿されたときも。

**Comment by komagata** [comment]
後者は別Issueにしました。 #425

**Comment by JunichiIto** [comment]
@komagata これも対応済みっぽいです。closeをお願いします。

**Comment by komagata** [comment]
@JunichiIto ご指摘ありがとうございます。確かに解決済みなのでCloseします。
