### ISSUE TITLE
フィヨルドを卒業したらどういう姿になりたいかを記入する欄を作り、ダッシュボードに表示する

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#3664]
**何故この機能が必要なのか**

フィヨルドブートキャンプは平均で卒業するのに1000時間以上かかる。
1on1をしたり日報を確認している上で、入会時に持っていたエンジニアになりたい、プログラミングを学びたい気持ちや覚悟が、
時間がたち学ぶ難しさやエラーでつまったときの辛い気持ちを繰り返していくうちに忘れがちになっている人を見かける。
そのため、いつでも入会した時の気持ちや覚悟を思い出せるように入力する欄をつくり常にダッシュボードなどに表示させたい

**機能の説明**

入会時、またはプロフィール編集画面で、『フィヨルドを卒業した自分はどうなっていたいか』を書く
本人のみ見える形でダッシュボードに表示させる

**Comment by rlho** [comment]
曖昧すぎたので捕捉させてください！

```
ラベル名: フィヨルドを卒業した自分はどうなっていたいか
説明: フィヨルドを卒業した自分をできるだけ詳細まで想像してなりたい姿ややりたいことを『具体的に』かいてください。例: 『ITジェンダーギャップ問題を解決するアプリケーションを作る事業にエンジニアとして携わる』『家族の時間を一番に優先しながら、好きなゲームに関連する会社でゲームを作る側のエンジニアとして働く』『地元の石川に貢献するようなWebアプリケーションを自分で開発し起業する』`
```

という感じで書いて欲しいです〜！

**Comment by machida** [comment]
@rlho 補足ありがとうございます！！

@R-Tsukada このようにお願いしますー🙏 デザインは僕がやりますー

**Comment by R-Tsukada** [comment]
@rlho 補足ありがとうございます！

@machida  承知しました！

**Comment by R-Tsukada** [comment]
開発環境で確認できたためcloseする
