### ISSUE TITLE
ウォッチ機能

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#367]
自分の日報へのコメントは通知が必ず来る。

しかし、他人の日報へコメントした後、それへの返信がメンション無しで来たときには通知が来ないので気づくことができない。

メンターとして困るのと、一般ユーザーとしても議論の続きがわからなくなるのでなんとかしたい。

## 機能

基本的にこのIssueは最小限の機能に絞る。他の機能は他のIssueにする。関連するすべての機能ができた時に一気にデプロイする。

- [ ] 日報の全ページにウォッチボタン
- [ ] ウォッチボタンはトグルになっていてON/OFFできる
- [ ] ウォッチがONになっているとその日報へ新しいコメントが付いたら通知がくる

## 実装

日報以外にも提出物やQ&Aなどにもつけたいのでcommentやcheckのようにpolymorphic関連を使いたい。（watchable）

**Comment by machida** [comment]
日報にwatchボタンを配置（最終的には QA、提出物、お知らせにも付ける）。

<img width="909" alt="_2019_01_24_19_17" src="https://user-images.githubusercontent.com/168265/51671826-43764980-200d-11e9-9125-b00b57ee00d7.png">

watchボタンは toggle になっていて（checkbox で実装）、オンの状態だと、その日報にコメントが付いたら通知が飛ぶようになる。

**Comment by komagata** [comment]
@machida さんのおっしゃってるとおり最初は日報へのものだけでいいですー
