### ISSUE TITLE
ウォッチ機能

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#368]
## 仕様

- 日報、Q&A、提出物に目玉マークがあって、ON/OFF（ウォッチ）できる。
- ONにしたものにコメントがつくとウォッチした人に通知が行く。

対象に対してコメントできる機能はCommentable、対象に対して確認できる機能はCheckableとして実装しているので、こちらもWatchableとして実装すれば対象が増えてもDRYにかける。

**Comment by machida** [comment]
## ウォッチ機能

日報、Q&A にウォッチボタンを付ける。
ウォッチボタンには ON OFF の状態があります。

<img width="882" alt="_2018_08_07_10_48" src="https://user-images.githubusercontent.com/168265/43749531-8422e8d0-9a2f-11e8-84d7-8d8b8771325e.png">

ウォッチがONになっている場合、その 日報、Q&A にコメントが付いた場合、ウォッチを ON にしているユーザーに通知がきます。

ウォッチボタンをクリックすることで、ON、OFFが切り替えられるが、そのボタンをクリックしなくても自動的に ON になる場合があります。

その場合とは、

1. 日報、Q&A の作成者（作成した時点で、ウォッチがONになる。OFFにすることもできる。）
1. 日報、Q&A にコメントをしたユーザー（コメントをした時点で、ウォッチがONになる。OFFにすることもできる。）
1. admin（日報、Q&A全てのウォッチがONになる。ウォッチがONになる。OFFにすることもできる。）

です。
