### ISSUE TITLE
見出しへのページ内リンクが生成されてほしい

### ISSUE THREAD

**Issue by yoshitsugu** [fjordllc/bootcamp#3687]
**何故この機能が必要なのか**

見出しのページ内リンクつきのURLを共有して、情報へ誘導しやすくしたい。

**機能の説明**

GitHubのREADMEのようにプラクティスやDocなどにおいて、MarkDownの `#` `##` `###` で生成される `h1` ~ `h3` に関するページ内リンクが作られるようにしてほしい

bootcampアプリのREADMEの `Lint` にマウスオーバーしたときの例
![Screenshot from 2021-12-06 20-14-45](https://user-images.githubusercontent.com/748445/144836699-66044705-e930-4e5d-9acd-549ffd32ce86.png)

**Comment by komagata** [comment]
@yoshitsugu これってどう実装するのがいいですかね〜

**Comment by yoshitsugu** [comment]
@komagata 僕もやったことがないのでわからないですが、パっと見た感じ、 `commonmarker` を使ってるんですかね？
https://github.com/gjtorikian/commonmarker#creating-a-custom-renderer あたりのカスタムレンダラでページ内リンクつきの :chains: アイコンを表示する、とかですかね〜。

**Comment by komagata** [comment]
@yoshitsugu なるほど、ご回答ありがとうございます。

**Comment by yoshitsugu** [comment]
修正していただいたのでCloseします！ありがとうございました！
