### ISSUE TITLE
Q&Aの日付がおかしい。投稿日を表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3689]

**Comment by komagata** [comment]
@machida こちら一覧・個別ページなどどこの部分でしょうか

**Comment by machida** [comment]
@komagata 一覧、個別に関わらず両方の日付がおかしいです。最新のコメントの日が表示されてるのかもしれません。

**Comment by komagata** [comment]
@machida なるほどです、情報ありがとうございます〜

**Comment by machida** [comment]
@nga20167304 

ここに表示されている日付ががおかしいので、何かバグがないかチェックをお願いします。
質問が投稿された日付を表示してもらいたいです。
<img width="761" alt="貼り付けた画像_2021_12_22_15_39" src="https://user-images.githubusercontent.com/168265/147047295-bb733136-892d-4ef9-8150-b424cefa517b.png">

今、Q&AをVue.jsにしようとしています。
https://github.com/fjordllc/bootcamp/pull/3822
こちらのブランチからブランチを作って作業をお願いします。

**Comment by nga20167304** [comment]
@machida さん
情報ありがとうございます。
そうすると、feature/convert-questions-list-to-vuejsをcheckoutして、新しいブランチを作って作業を始めますね。
作業を完成したら、どのブランチにPRを作成しますか。こちらの確認お願い致します。

**Comment by machida** [comment]
@nga20167304

新しいブランチを作成していただき、

feature/convert-questions-list-to-vuejs がまだマージ前でしたら、
feature/convert-questions-list-to-vuejs に向けて PR を送っていただきたいです。

feature/convert-questions-list-to-vuejs が main ブランチにマージされていたら、main から rebase をして main に向けて PR をお願いします 🙏

**Comment by nga20167304** [comment]
@machida 
回答ありがとうございます。
了解です！
よろしくお願い致します。
