### ISSUE TITLE
wiki で .（ドット）が付くタイトルにするとエラー

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#370]
![image](https://user-images.githubusercontent.com/168265/40164812-831ecba4-59f5-11e8-97b5-a1b1db08d3ea.png)

ページは作れるが、編集に行くとエラーになる。

**Comment by sanfrecce-osaka** [comment]
@komagata @machida 
原因は[コレ](https://qiita.com/ysk_1031/items/3d7dee2e3b2a2c1628be)ですね
解決策も上記リンク先のようにスラッシュ以外を許容してやるのがいいのではと思いますがどうでしょうか？

**Comment by komagata** [comment]
`ページ名.json`や`ページ名.txt`みたいに他フォーマットを提供したいのでドットはページ名として入力時に弾くか変換するようにしたいですね。
