### ISSUE TITLE
ユーザー個別ページのプロフィールページのタイトルを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3703]
http://localhost:3000/users/XXXXXXXXXXX

<img width="868" alt="貼り付けた画像_2021_12_08_16_08" src="https://user-images.githubusercontent.com/168265/145164132-623a433f-4a85-4d59-818f-e43b4180df9f.png">

「のプロフィール」を削除する。

**Comment by aim2bpg** [comment]
本番での動作確認完了しましたので、クローズしました👍
