### ISSUE TITLE
ユーザー > ポートフォリオ のページのタイトルを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3704]
http://localhost:3000/users/XXXXX/portfolio

<img width="606" alt="貼り付けた画像_2021_12_08_16_11" src="https://user-images.githubusercontent.com/168265/145164548-868dbb10-3c0d-4bfe-b50d-cf53646f4fd5.png">

「のポートフォリオ」を削除

**Comment by tksmasaki** [comment]
本番での動作確認ができたため、Close します！
