### ISSUE TITLE
ユーザー > コメント のページのタイトルを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3707]
http://localhost:3000/users/XXXXX/comments

<img width="687" alt="貼り付けた画像_2021_12_08_16_14" src="https://user-images.githubusercontent.com/168265/145164890-c17c41e2-fb27-4d74-8188-4454ea0878af.png">

「のコメント」を削除。

**Comment by eatplaynap** [comment]
@komagata
すみません、ステージング環境でのチェック後、本番環境でのチェック前にかんばんを完了に移動させてしまっていたので、issueを一旦reopenしました:pray:

**Comment by eatplaynap** [comment]
本番環境でのチェックが完了したのでcloseします。
