### ISSUE TITLE
ユーザー > 質問 のページタイトルを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3709]
http://localhost:3000/users/XXXXX/questions

<img width="914" alt="貼り付けた画像_2021_12_08_16_18" src="https://user-images.githubusercontent.com/168265/145165307-78477f5b-cbd0-465d-9ccf-109d1603dd52.png">

「の質問」を削除。

**Comment by Saki-htr** [comment]
@komagata
すみません💦
こちらのissue、本番環境の動作確認をしてからかんばんの「完了」に移動してcloseすべきところを、 ステージング環境の動作確認後に移動させると勘違いしてしまっていたため、「完了」に移動させていました。
closeしてくださったのに申し訳ないのですが、issueをreopenさせていただきます〜🙏

**Comment by Saki-htr** [comment]
本番環境で確認できましたので、closeいたします。
