### ISSUE TITLE
日報でURLが枠をはみ出してしまう時がある

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#3717]
## 概要
日報でURLが枠からはみ出してしまうケースがある
https://bootcamp.fjord.jp/reports/43609

## 再現手順
1. https://bootcamp.fjord.jp/reports/43609 にアクセス

## 期待される振る舞い

URLがはみ出さない

## スクリーンショット
<img width="809" alt="Screen Shot 2021-12-08 at 12 13 22" src="https://user-images.githubusercontent.com/5990045/145253071-ffd58fb9-5065-48b8-bf2a-2b99c3a7ffe5.png">

## 環境

 - OS: MacOS Big Sur
 - ブラウザ:Chrome
 - バージョン: 96.0.4664.55 

## 関連Issue

Ref: #関連Issue番号

**Comment by machida** [comment]
こちら本番で確認したのでクローズしますー
