### ISSUE TITLE
イベント作成時の日時選択を簡単にしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3723]
イベント作成時の便利機能の実装をお願いします。

![image](https://user-images.githubusercontent.com/168265/145344368-4b0732bb-0792-4833-8d98-32734364617e.png)

- イベント終了日時 が空の場合、
    - イベント開始日時 を入力したら、イベント修了日時に イベント開始日時 が入力されて欲しい。
    - そうすることで、大体のイベントは日にちをまたがないので、あとは時間を変更するだけになり手数が減る。
- 募集終了日時 が空の場合、
    - イベント開始日時 を入力したら、募集終了日時に イベント開始日時 が入力されて欲しい。
    - そうすることで、大体のイベントは募集終了日時はイベント開始日時の近くなので、募集終了日時設定の際の手数が減る。

**Comment by unstoppa61e** [comment]
本番環境で動作を確認できたため、close させて頂きました。
