### ISSUE TITLE
ブログにWIP機能が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3730]
- 記事の持つデータの追加
    - WIP  のフラグを持つ。
    - 記事公開日 published_at を持つ。
- 個別ページ
    - WIPのときは メンター、管理者だけがその記事の個別ページが見れる。
    - 記事にはWIPのマークが付いている。
    - 公開 になったら全員が見れる。WIPのマークが外れる。
    - 投稿日には published_at が表示される（WIPのときは投稿日に執筆中と表示）。
    - WIPのときは検索エンジンのボットが来ないようにmetaタグが設定されている。公開になったら外す。
- 一覧ページ
    - WIPのときは メンター、管理者だけ、記事の一覧にWIP状態の記事が表示されている。
    - 一覧の中のWIP状態の記事にはWIPのマークが付いている。
    - 投稿日には published_at が表示される（WIPのときは投稿日に執筆中と表示）。
    - 公開 になったら一覧のWIPだった記事が公開される。WIPのマークが外れる。

**Comment by kaisumi** [comment]
@komagata 確認です。
「ブログ」「記事」とは、「Docs」「Doc」機能のことで間違いないですか？

**Comment by kaisumi** [comment]
@komagata 
投稿日の表示について相談があります。
今回新たにpublished_atカラムを追加するのですが、既存の記事ではpublished_atカラムが空になります。
- published_atにcreated_atを入れる（リリース時に一度DBを触る必要があります）
- published_atが空だったらcreated_atを表示する（一覧の並び順はcreated_atになります）
本番環境への影響を考えると後者が良いと思いますが、いかがでしょうか。

**Comment by komagata** [comment]
@kaisumi 前者でお願いします。
今までの他のWIP機能を追加するIssueでも同じように対応していたので、そういうdata migrationを書くようにお願いします〜。

**Comment by machida** [comment]
@kaisumi こちら確認しました！！クローズしますー
