### ISSUE TITLE
ドキュメント内のアンカーリンクをコピーできるようにしたい

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#3734]
**何故この機能が必要なのか**

フィヨルドのドキュメント内で h1タグの場所を指定してURLにしたいときがある(例: [ヘルプ](https://bootcamp.fjord.jp/pages/help)のつらくなったらのh1に対してリンクを飛ばしたい)

**機能の説明**

Qiitaのようにh1タグをhoverした際に、ページ内のアンカーリンクをコピーできるようにする
<img width="247" alt="Screen Shot 2021-12-10 at 13 53 25" src="https://user-images.githubusercontent.com/5990045/145626917-358cf443-bbc8-4940-99be-b75118ebb433.png">

**Comment by komagata** [comment]
@rlho #3687 こちらと同じだと思うのでこのIssueの方はCloseしちゃいますね〜
