### ISSUE TITLE
提出物・日報のユーザーメモタブにユーザー情報を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3741]
メンターでログインした時だけ見れるこの部分（提出物・日報）に、

<img width="1608" alt="貼り付けた画像_2021_12_13_11_43" src="https://user-images.githubusercontent.com/168265/145744303-9d638072-bd80-4c0a-8d0d-98dced400fe3.png">

この部分に、ユーザー個別ページにあるこの2つのブロックを表示したい。

<img width="611" alt="貼り付けた画像_2021_12_13_11_44" src="https://user-images.githubusercontent.com/168265/145744331-e6bca70f-6d3d-4ce5-8a14-a807856bf6d9.png">

**Comment by Paru871** [comment]
@komagata @machida 
メンター向け機能のため、本番環境で確認していただきたいです！
よろしくお願いします🙏

**Comment by komagata** [comment]
@Paru871 本番環境で動作することを確認しました。

**Comment by Paru871** [comment]
@komagata 
お忙しいなかご確認ありがとうございました！
