### ISSUE TITLE
イベントに就活関係イベントというフラグを追加したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3748]
<img width="762" alt="貼り付けた画像_2021_12_13_14_49" src="https://user-images.githubusercontent.com/168265/145759346-f42b2971-cbf7-4a07-a5f3-b1e84c0a7098.png">

イベント一日前にイベントのお知らせがダッシュボードに表示されますが、それが現在は関係ない人にも表示されてしまっているので、その出し分けのための準備としてまずはフラグを持つというところをお願いします。

**Comment by naomichi-h** [comment]
@machida 
こちら仕様を確認させてください。

「イベント作成ページの「就活関係のイベントの場合はチェック」チェックボックスをチェックしてwipすると、そのイベントが就活関係がどうか、という属性(job_hunting)がtrueになったイベントデータが作成され、DBに保存される」

と認識しているのですが、正しいでしょうか？

また、この場合、内部ではフラグを持てても、「フラグを持てたかどうか」をデモでは表せないと思うのですが、問題ないでしょうか？

**Comment by naomichi-h** [comment]
本番環境で動作を確認できたため、close 致しました。
