### ISSUE TITLE
ブックマークのタブに合計数を表示

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3749]
<img width="713" alt="貼り付けた画像_2021_12_13_14_58" src="https://user-images.githubusercontent.com/168265/145760225-fabd30dc-084b-47f1-879f-a83dfe745d4f.png">

ブックマークはページ遷移なしで消せるので、数字は非同期で取得する必要がある？

**Comment by Saki-htr** [comment]
@komagata 
すみません💦
こちらのissue、本番環境の動作確認をしてからかんばんの「完了」に移動してcloseすべきところを、 ステージング環境の動作確認後に移動させると勘違いしてしまっていたため、「完了」に移動させていました。
closeしてくださったのに申し訳ないのですが、issueを`reopen`させていただきます〜🙏

**Comment by Saki-htr** [comment]
本番環境で確認できましたので、closeいたします。
