### ISSUE TITLE
通知一覧ページに表示する通知を通知元リンクごとに最新1件に絞れないことがある

### ISSUE THREAD

**Issue by AudioStakes** [fjordllc/bootcamp#3755]
### 現状の仕様

通知一覧ページにおいて、表示する通知は通知元のリンク（通知を発生させたオブジェクトのリンク）ごとに1件のみとされている

### ↑の実現方法(実現するために実装されていること)

「通知元リンクが同じである通知の集合」ごとにそれぞれ最新の作成日時を取得し、取得した作成日時のどれかに当てはまる通知を表示対象としている

※ 具体的には `where(created_at: Notification.into_one.values)` というクエリ条件を使っている
※ 日本語でうまく説明できないため、↓の補足にあるコードを読んでもらった方が理解しやすいかもしれない

### 何が問題か

「本来表示したい通知（通知元が同じリンクごとに1件に絞った通知）」ではないけれど「表示対象の通知と作成日時が同じ通知」が存在した場合、その通知も表示されてしまうこと

## 再現手順

例として、 `where(created_at: Notification.into_one.values)` を条件にしても、全ての通知の作成日時が同じ場合は全ての通知が該当してしまうことを以下に示す

```bash
$ rails c --sandbox
>> Notification.count
=> 16
>> Notification.where(created_at: Notification.into_one.values).count
=> 13
>> Notification.update_all(created_at: Time.now)
=> 16
>> Notification.where(created_at: Notification.into_one.values).count
=> 16
```

## 期待される振る舞い

「表示対象の通知と作成日時が同じ通知」が存在する場合でも、通知元リンクごとに表示する通知を1件に絞れること

### 通知元リンクごとに1件に限定するための現状のクエリ条件

`where(created_at: Notification.into_one.values)` という条件で限定している（すなわち `created_at` の値のみで判別している）

※ この条件はスコープの `reads` や `unreads` に含まれている

### `Notification.into_one` とは

`Notification`オブジェクトの `path` （通知元リンク、通知を発生させたオブジェクトのリンク）単位での通知の最新作成日時のハッシュを返す

```ruby
def self.into_one
  select(:link).group(:link).maximum(:created_at)
end
```

### どのようなときに困るか

以下のようなケースでは作成日時が同じ `Notification` レコードが存在するため、本来は表示対象ではない通知も対象に含まれてしまう。

- `db/seeds.rb` で投入されたデータを使って動作確認するとき
- テストを実行するとき
- （あまりないかもしれないけれど）本番環境に作成日時が同じ `Notification` レコードが存在するとき

### この Issue に対応する場合の影響範囲

#3752 と#3753 にも対応することになりそう

## 関連Issue

Ref: #974

**Comment by AudioStakes** [comment]
@komagata @machida
こちらの Issue について、僕自身をアサインしてもよろしいでしょうか？
https://github.com/fjordllc/bootcamp/pull/3642#issuecomment-994403424 のやり取りからしてアサインしてよさそうに思ったものの、念のため確認させてもらいたいです！

また、もしアサインして良い場合、併せて対応することになりそうな #3752 と #3753 にも僕自身をアサインして大丈夫そうか教えてもらいたいです🙏

**Comment by machida** [comment]
@AudioStakes アサインさせていただきました！こちらお願いしたいです🙏

**Comment by AudioStakes** [comment]
@machida アサインありがとうございます！関連 Issue （ #3752 と #3753 ）にもアサインさせてもらいますー

この Issue と関連 Issue について、今はまだポイントが振られていないようですので、ご都合の良いときにポイントをつけてもらえるとありがたいです🙏

**Comment by AudioStakes** [comment]
@komagata @machida 
ステージング環境と本番環境での動作確認方法について質問があります。
お時間のあるときに返答お願いいたします🙏

### ステージング環境

動作確認に必要な「作成日時が最新かつ同値である2つの通知」を見つけられず、動作確認を完了できていません。
それらの通知を作成するために、ステージング環境で次のスクリプトを実行してもらうことは可能でしょうか？

```ruby
receiver = User.find_by(login_name: 'komagata')
sender = User.find_by(login_name: 'machida')
comment = Product.first.comments.create!(description: '動作確認用のコメント', user: sender)
now = Time.current

2.times do |i|
  Notification.create!(
    kind: :came_comment,
    user: receiver,
    sender: comment.sender,
    link: comment.commentable.path,
    message: "#{comment.sender.login_name}さんがコメントしました。 #{i}",
    read: false,
    created_at: now
  )
end
```

### 本番環境

ステージング環境と同じスクリプトを実行すれば動作確認できるものの、本番環境なのでデータを作成しない方がよいと考えています。
リリースされたことを見た目（画面の表示）で判断できれば（少なくともリリースされていることは）確認できそうですが、この Issue にはそのような変更が含まれていないためそれも確認できません。
この場合、どのように動作確認をすると良いでしょうか？

**Comment by komagata** [comment]
@AudioStakes ステージング環境で自由に書いたスクリプトを実行する環境を作るのに時間がかかるので少々お待ちいただければと思います。

**Comment by AudioStakes** [comment]
@komagata スクリプトの実行環境を準備していただき、ありがとうございます！
実行したい処理を追加した PR #4005 を作成し、そちらでレビューをお願いしました。
ご対応のほど、よろしくお願いいたしします🙏

**Comment by komagata** [comment]
@AudioStakes 該当のPRをマージし、ステージング環境でタスクを実行しました〜

https://github.com/fjordllc/bootcamp/pull/4005#issuecomment-1018311356

**Comment by AudioStakes** [comment]
@komagata 
ありがとうございます！
ステージング環境で動作確認した結果、期待どおりに通知の表示を1つに絞れていることが確認できました。

**Comment by AudioStakes** [comment]
@komagata お時間のあるときに、本番環境での Rake タスクの実行をお願いいたしますー🙏

**Comment by komagata** [comment]
@AudioStakes 本番環境でRakeタスクを実行しました〜

**Comment by AudioStakes** [comment]
@komagata
ありがとうございますー！
本番環境で動作することを確認できましたので、close します。
