### ISSUE TITLE
卒業生の日付の表示を変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3756]
<img width="632" alt="貼り付けた画像_2021_12_13_17_43" src="https://user-images.githubusercontent.com/168265/145779728-5886dd03-6c78-4f7c-bb3e-e6ae7a16985a.png">

卒業したユーザーの場合、

2014年01月01日 365日目 5期生

を以下の表示に変更

2014年01月01日 （20XX年XX月XX日卒業 XXX日） 5期生

XXX日 は 開始日から卒業までの日数。

**Comment by machida** [comment]
@naomichi-h アサインさせていただきましたー 🙏

**Comment by naomichi-h** [comment]
本番環境で動作を確認できたため、close 致しました。
