### ISSUE TITLE
ダッシュボード > Watch中 の読み込み時にプレースホルダを表示

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3761]
日報一覧で表示されているこれを、Watch中 の読み込み時にも表示させる。
![image](https://user-images.githubusercontent.com/168265/145917957-641bc97f-8180-4bc5-bf3b-f0ebfae68d23.png)

**Comment by unstoppa61e** [comment]
本番環境で動作を確認できたため、close させて頂きました。
