### ISSUE TITLE
メンターログイン時の提出物一覧のタブの数字の表示の変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3765]
<img width="712" alt="貼り付けた画像_2021_12_14_13_39" src="https://user-images.githubusercontent.com/168265/145934236-5affe816-d064-4c6a-a5d1-7fd5088399ea.png">

**Comment by ot0m1** [comment]
`未返信`タブはなくなった模様。
https://discord.com/channels/715806612824260640/809595476847493192/929174526049259570

**Comment by ot0m1** [comment]
マージされたのでクローズ。

**Comment by komagata** [comment]
@ot0m1 本番にリリースされて、本番環境で動作することを確認した時点でCloseをお願いします〜

**Comment by ot0m1** [comment]
@komagata 
ハッ！認識不足で失礼しました🙏

**Comment by ot0m1** [comment]
@komagata 
こちら本番環境で僕のロールだと動作確認できないため、ご確認をお願いいたします。

**Comment by komagata** [comment]
@ot0m1 本番環境で動作することを確認しました。

**Comment by ot0m1** [comment]
ご確認ありがとうございました！クローズいたします。
