### ISSUE TITLE
会社概要の住所を更新

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3766]
<img width="715" alt="貼り付けた画像_2021_12_14_16_28" src="https://user-images.githubusercontent.com/168265/145952404-1daee61e-7b63-44de-b14d-fac985c0d5fc.png">

- 最寄り駅を削除
- 住所を `〒150-0031 東京都渋谷区桜丘町15-14 フジビル40 7F` に更新

**Comment by napple29** [comment]
本番環境で確認できたためクローズします！
