### ISSUE TITLE
日付をまたいだ際の学習時間がおかしい

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/bootcamp#377]
[![https://gyazo.com/0cb0c0a1901529b9baf43ae293b89126](https://i.gyazo.com/0cb0c0a1901529b9baf43ae293b89126.png)](https://gyazo.com/0cb0c0a1901529b9baf43ae293b89126)

**Comment by machida** [comment]
@chamao @nishide-h こちら出来そうでしたら自分をアサインして着手お願いしますー 🙏

**Comment by nishide-h** [comment]
@machida @chamao 確かに日付超えた感じに登録できちゃいますね。
開始時間より前の終了時間を選択できなくして、日付超えた分は追加で翌日日付で
登録してもらう対応で宜しいでしょうか？

**Comment by machida** [comment]
@nishide-h cc: @komagata 

結構夜中に学習をする方って多いんですよね。なので、できたらそういう方でもストレスなく入力できるようになるのが理想ではあります。

例えば、終了時間が開始時間を超えた場合は、演算の方法を変えて、日付をまたいだときも辻褄が合うように時間が表示されるように実装するのって何か問題ありますかねー？
「開始時間から24:00までの時間 + 00:00から終了時間」までを表示するとか。（すいません、現状のコードを見ずに言ってます）

**Comment by sanfrecce-osaka** [comment]
@machida @nishide-h @komagata 
すみません、自分にアサインするの忘れてました。
現在作業中です。

下記のようなロジックで学習時間の保存前に変換をかける実装で考えています。

- 完了日付が翌日の場合、完了日付に1日加える
  - 条件：完了hourが開始hourよりも小さいかつ完了日付が開始日付と同じかそれ以前
- 完了日付が同日の場合、完了日付から1日引く
  - 条件：完了hourが開始hour以上かつ完了日付が開始日付より後
  - 現状、datetime_selectには単純にfinished_atを渡しているため、23:00〜1:00から23:00〜23:30のような修正があった際に保存前に1日引いてやる処理が必要となる
