### ISSUE TITLE
横幅が一定以下の時は「直近の日報」欄が非表示になってほしい

### ISSUE THREAD

**Issue by pofkuma** [fjordllc/bootcamp#3774]
https://github.com/fjordllc/bootcamp/pull/3118 で直近の日報が表示されるようになりました。
複数ウィンドウを横に並べたい時などに、ウィンドウの幅を狭めると、
日報の幅が以前より狭くなりすぎて少し見づらいと感じました。(下の画像を参照）

<img src="https://user-images.githubusercontent.com/87865333/146078157-72d26208-425d-4124-a3cd-31721d5b408f.png" width="600">

アイディアですが、プラクティスページで表示されるプラクティスの一覧のように
一定幅より狭くなったら、直近の日報が非表示になると嬉しいです。

<img src="https://user-images.githubusercontent.com/87865333/146078555-e19da56b-7756-4122-8287-ef3c7752ed3f.png" height="200">

<img src="https://user-images.githubusercontent.com/87865333/146078627-1d67828d-1656-4770-8995-ef2b0e88a03f.png" height="195">

**Comment by machida** [comment]
@pofkuma
Issue登録ありがとうございますー

> 一定幅より狭くなったら

大体でいいので問題が起きる幅についての px 数が Issue に書かれていると、作業者が着手しやすくなったり、仕様を決める人が決めやすくなるのでよりよいですー（今回は大丈夫です😄）

**Comment by pofkuma** [comment]
@machida 
承知しました、以後心がけます！

今回は大丈夫ですと言っていただきましたが・・・
個人的希望になりますが、1000~1200px 以下の時に隠れると助かります。

**Comment by machida** [comment]
@pofkuma 

> 1000~1200px 以下の時に

ありがとうございます！！
助かりますー
そのようにします💪

**Comment by pofkuma** [comment]
ありがとうございます！
よろしくお願い致します🙇‍♀️
