### ISSUE TITLE
ユーザー退会時、管理者への退会メール通知が届かない。

### ISSUE THREAD

**Issue by taka61** [fjordllc/bootcamp#3782]
## 概要
メール通知の受け取りをONにしている管理者の場合、ユーザーが退会すると`XXさんが退会しました。`の文面のメールが届くはずだが、現状ではメールが届かない。（サイト内通知は来る）

## 再現手順

1. `fujiyasu`でログイン
2. 退会手続きから退会処理を行う
<img width="308" alt="スクリーンショット 2021-12-16 13 56 06" src="https://user-images.githubusercontent.com/80372144/146310726-1f7ae039-abd9-45a0-82f9-f4cbdf37f4a3.png">

<img width="525" alt="スクリーンショット 2021-12-16 13 54 55" src="https://user-images.githubusercontent.com/80372144/146310652-783bc55c-c672-4dbe-81c0-8548b41b6710.png">

3. 退会処理後、管理者（`komagata`）としてログイン
4. サイト内通知にて「退会しました」の通知が来ていることを確認

<img width="283" alt="スクリーンショット 2021-12-16 14 00 50" src="https://user-images.githubusercontent.com/80372144/146311135-bb32ec0e-a720-485c-ae27-e63653df8af9.png">

5. `http://localhost:3000/letter_opener`にアクセスし、メール通知は来ていないことを確認

※`komagata`さんはメール通知の受け取りをONにしています

## 期待される振る舞い
ユーザーが退会すると`XXさんが退会しました。`の文面のメールが届く。

## 環境
* OS: macOS Monterey 12.0.1
* ブラウザ: Google Chrome Version 96.0.4664.93

## 関連Issue

Ref: ##3654

**Comment by taka61** [comment]
@komagata @machida
管理者向けの機能のため本番での動作確認をお願いして宜しいでしょうか🙇🏻‍♀️

**Comment by komagata** [comment]
@taka61 退会者が出た時に確認させていただきます〜
