### ISSUE TITLE
画面右端に表示される直近の日報一覧の on / off 機能が欲しい

### ISSUE THREAD

**Issue by unstoppa61e** [fjordllc/bootcamp#3804]
**何故この機能が必要なのか**

「他の受講者の進捗が目に入ると焦ってしまう、精神的に追い詰められる」という状況が起こりうるため。

**機能の説明**

トグルスイッチによる表示の on / off を可能にする。

**関連 issue**
#2047 他人のプラクティスの進捗を見えなくする機能

**Comment by machida** [comment]
#3914
こちらのIssueで右側の最新の日報自体を削除することになりました。
こちらのIssueをcloseさせていただきますー
