### ISSUE TITLE
_user.html.slim を削除したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3814]
https://github.com/fjordllc/bootcamp/issues/3548

こちらのIssueの続きです。

- app/views/companies/users/index.html.slim 
- app/views/generations/show.html.slim

を vue.js 化し、

app/views/users/_user.html.slim を削除 をお願いしますー

**Comment by naomichi-h** [comment]
本番環境での動作を確認したためcloseします。
