### ISSUE TITLE
Docs 一覧を vue.js 化したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3817]
Docs 一覧: `/pages`
タグはそのまま、Docのリストだけを Vue.js にお願いします。
タグをクリックしたリンク先もお願いします。

**Comment by mami-inuzuka** [comment]
@machida cc : @komagata 
ページャー周りでご相談があります。

# 相談
お知らせなど他のVue.js化されているページを確認すると、ページャーもVue.jsで描画されているのですが今回のissueでもページャーのVue.js化は対応した方が良いでしょうか？

懸念点を考慮すると、一旦今回のissueではページャーは既存の実装のままとし（Vue.js化しない）、
タグ一覧をVue.js化するタイミング、もしくはタグ一覧がVue.js化された後にページャーのVue.js化を行うのが良いのかな？と思ったのですがいかがでしょうか。

# 懸念点（悩んでいる背景）
今回、タグ一覧はそのままにDocのリストだけをVue.js化するとのことですが、
ページャーも一緒にVue.js化する場合、下記のようにマークアップの構造上タグ一覧もVue.js化しないといけないかなと思っています。
<img width="754" alt="スクリーンショット 2021-12-23 18 51 05" src="https://user-images.githubusercontent.com/52844263/147224620-b3ee5eed-7e3e-4761-8eee-02883bcc3db7.png">


[似たようなissueのPR](https://github.com/fjordllc/bootcamp/pull/3822)でもページャーがVue.js化されていたので、同じく対応した方が良いのかなと思ったのですが、タグ一覧はVue.js化せずにDocs一覧のVue.jsファイルの中でページャーを設置無理やり設置すると、下記のようにページャーが画面左右中央ではなくDocs一覧の幅に対して中央に配置されてしまいレイアウトが崩れます。[こちらのPR](https://github.com/fjordllc/bootcamp/pull/3822)でもスクショを見る限り同じように崩れが発生しています
<img width="1161" alt="スクリーンショット 2021-12-23 18 51 57" src="https://user-images.githubusercontent.com/52844263/147223295-da61bf29-65fd-49ec-a449-fdc92e0f7e5f.png">

**Comment by machida** [comment]
@mami-inuzuka 
連絡ありがとうございます！
そうなんですよねー、ヴィンさんにやってもらったIssueで気がつきました。コンポーネントの問題でページャーの位置が変わってしまうのですが、一旦、そういうデザインにしてしまおうと思いますー。
なので、ページャーは左に寄せる形で実装をお願いします🙏

**Comment by mami-inuzuka** [comment]
@machida ご確認ありがとうございます！！
承知しました！！ではページャーもVue.js化し左に寄せる形で実装いたします😊🙏

**Comment by mami-inuzuka** [comment]
こちら本番で確認し問題なかったためissueをcloseします😊
