### ISSUE TITLE
wikiでeditから更新するとnewに飛んで更新できない

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/bootcamp#382]

**Comment by sanfrecce-osaka** [comment]
@komagata @machida 
[コレ](https://qiita.com/YamKenta/items/c5666908a6022b8a30ce)が原因ですね。
記事にある通りgsubで置き換えてやれば動くことはローカルで確認できました。
考慮するのはスペースだけでいいんでしょうかね？

**Comment by machida** [comment]
@sanfrecce-osaka 今のところの既知のものはスペースだけですね。
一旦それでリリースして、他の問題が見つかったら別issueで対応でいいかなー。

**Comment by komagata** [comment]
@sanfrecce-osaka 

> 記事にある通りgsubで置き換えてやれば動くことはローカルで確認できました。

`URI.decode_www_form_component`の方が良さそう

> 考慮するのはスペースだけでいいんでしょうかね？

まさにそのへん調査いただけるとありがたいです。

`application/x-www-form-urlencoded`で何がどうエンコードされるのか。

**Comment by sanfrecce-osaka** [comment]
@komagata 
- `URI.decode_www_form_component`は+をスペースにデコードする
- 今回は問題となっているのはURLでの半角スペース、そしてURLには半角スペースは含むことができない

上記の理由から`URI.decode_www_form_component`は不適だと思うのですが理解が間違っているでしょうか？

**Comment by komagata** [comment]
@sanfrecce-osaka ちょっと詳しく見る時間が取れないのですが、そもそも`CGI.escape`しないとかでそれ使えたりしないですかね？

なんか`gsub`を使わない場当たり的じゃない方法が無いのかなーという気持ちです。

**Comment by sanfrecce-osaka** [comment]
@komagata 
調べているうちにもっとbetterな解決策が見つかりました。
`form_with`と`to_param`と利用すれば半角スペース含め裏でいい感じにエンコードしてくれるようです。
ローカルで動くことも確認できました。

**Comment by machida** [comment]
@komagata これってデプロイされてないんでしたっけ？

**Comment by komagata** [comment]
@machida されてるはずですー

**Comment by machida** [comment]
@komagata ありがとうございます！解決できてないパターンを見つけたかも。調査します！

**Comment by sanfrecce-osaka** [comment]
@machida ドットのやつですか？
