### ISSUE TITLE
イベント前日、イベント当日に表示されるイベント通知で、就職関係のイベントの場合、就職希望社にのみ表示するようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3833]
<img width="1389" alt="貼り付けた画像_2021_12_23_19_26" src="https://user-images.githubusercontent.com/168265/147227031-68fde152-0938-4416-8435-8a679802611f.png">

イベントの開催日とその前日にはダッシュボードにこのようなお知らせが出ます。

これがマージされたので、
https://github.com/fjordllc/bootcamp/pull/3789
就活関係のイベントかどうかの情報をイベントが持っています。

**Comment by taka61** [comment]
こちらdiscordにて
>本番でやるとユーザーに影響しちゃうので確認せずにいて大丈夫です〜

との確認を頂きましたので、このままcloseいたします。
