### ISSUE TITLE
プラクティスメモが空のときの表示を変更。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3837]
現在の提出物個別ページにある、プラクティスメモが空の場合の表示。

<img width="1461" alt="貼り付けた画像_2021_12_22_17_22" src="https://user-images.githubusercontent.com/168265/147060033-3a4b23e0-4ff8-4f10-9f17-c6504f14c61c.png">

空だった場合、空であるということがわかりやすくしたい。

直近に日報がない場合と同じように泣き顔を出して、

![image](https://user-images.githubusercontent.com/168265/147060315-05256e4f-e2a7-4278-8d77-bb83c2a5a2a4.png)

「プラクティスメモはまだ空です。」

と表示をお願いします 🙏

**Comment by mami-inuzuka** [comment]
@machida お疲れ様です！
念の為前提と仕様の認識が合っているか確認させてください🙇🏻‍♂️🙏

## 前提の確認
プラクティスメモは**メンターさんが**自由に書き込める場所であっていますか？

## 今回のissueの仕様の確認
何もメモがない時には「プラクティスメモはまだ空です。」の表記と**その下に編集ボタン**があり、
![スクリーンショット 2021-12-22 22 33 47](https://user-images.githubusercontent.com/52844263/147100827-2bff654c-dfd0-4cf9-8b68-99654ea0c3e6.png)

編集ボタンをクリックし、内容を書き込むとその内容が表示される
![スクリーンショット 2021-12-22 22 33 59](https://user-images.githubusercontent.com/52844263/147100978-1db141bc-6280-4967-8440-54b9204b7efa.png)
![スクリーンショット 2021-12-22 22 34 06](https://user-images.githubusercontent.com/52844263/147100982-d4a4f484-3cf0-44b5-aa07-27351b635d96.png)

という動きで認識は合っていますでしょうか？💡

**Comment by mami-inuzuka** [comment]
⬆︎Discordeで確認し、解決済み

**Comment by mami-inuzuka** [comment]
まちださんに本番でご確認いただき問題なかったためcloseさせていただきます😊
