### ISSUE TITLE
提出物編集ページ（作成ではなく）に、再提出をした際はコメントから連絡を、のメッセージを表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3844]
提出物編集ページ（作成ではなく）に、

「再提出をした際はコメントからメンターに連絡をお願いします」

と、メッセージを表示したい。

見た目はmachidaがやりますー

**Comment by machida** [comment]
@napple29 こちらもアサインさせていただきましたー

**Comment by napple29** [comment]
@machida ありがとうございます！かしこまりました！

**Comment by napple29** [comment]
本番環境で確認できたのでcloseします！
