### ISSUE TITLE
WIPではない提出物を更新したら担当メンターに通知を飛ばしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3845]
WIPではない（提出済の）提出物の内容が更新されたら、その提出物の担当メンターに通知を飛ばしたい。

- 担当メンターがまだいない場合は通知は飛ばさない。
- 提出物が更新され、さらにその提出物に新規コメントがあった場合など、一つのURLに対して複数の通知があった場合は最新の一つだけを通知するようにしたい。

**Comment by machida** [comment]
@R-Tsukada こちらアサインさせていただきましたー

**Comment by R-Tsukada** [comment]
@machida 
承知しました！

**Comment by R-Tsukada** [comment]
本番環境で動作確認ができたため、closeする
