### ISSUE TITLE
メンターが別のメンターを提出物の担当者に指定したときに、担当者になったメンターに通知を飛ばしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3859]
メンターでログインし、受講生の提出物ページに行く。

内容修正に行くと、

<img width="834" alt="貼り付けた画像_2021_12_24_15_13" src="https://user-images.githubusercontent.com/168265/147323677-2b8b9254-93f0-4fef-86db-575a1e70d0cd.png">

担当者を指定出来る。

<img width="726" alt="貼り付けた画像_2021_12_24_15_13" src="https://user-images.githubusercontent.com/168265/147323707-51e03bd2-4ce6-44bc-9e95-9205b48b2d07.png">

このときに、メンターが自分以外のメンターを担当者として指定した場合、
指定されたメンターに、

XXXさんの提出物「XXXXXXX」の担当になりました。

という通知を飛ばしたいです。

通知は、「サイト内通知」 + 「もしメール通知設定をしていたらメール通知も」

**Comment by napple29** [comment]
本番環境で動作確認できたのでクローズします。
