### ISSUE TITLE
管理ページの企業一覧をVue.js化

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3861]
管理者でログインして `/admin/companies` にアクセスすると表示される企業一覧ページをVue.js化をページャー含めてお願いします🙏

**Comment by machida** [comment]
@napple29 こちらアサインしましたー

**Comment by napple29** [comment]
@machida 
お忙しいところありがとうございます！承知いたしました🙆‍♀️！！

**Comment by napple29** [comment]
@komagata @machida 
お疲れ様です。
こちらのIssue、管理ページの企業一覧(`admin/companies`)がVue.js化されているか確認していただけますでしょうか🙇🏻‍♀️
closeしていただいていたのですが、一旦reopenしました。

よろしくお願いします🙏🏻

**Comment by napple29** [comment]
本番での動作確認ができたのでクローズします！
