### ISSUE TITLE
特定の日報ページでエラー

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3866]
<img width="1293" alt="スクリーンショット 2021-12-25 10 44 58" src="https://user-images.githubusercontent.com/16577/147375617-73c89f7e-1f24-4494-a6b0-9d8fcd3e9808.png">

<img width="1317" alt="スクリーンショット 2021-12-26 11 17 08" src="https://user-images.githubusercontent.com/16577/147397232-94c8a5dd-2576-4234-9b2c-740c72c6e8b2.png">

https://bootcamp.fjord.jp/reports/44685

にアクセスすると500エラーが出る。

**Comment by maedana** [comment]
これも500になるので同じ原因かもしれません。
https://bootcamp.fjord.jp/reports/44713

**Comment by betachelsea** [comment]
ほかにも500になるページがあったので共有です。
https://bootcamp.fjord.jp/reports/44694
https://bootcamp.fjord.jp/reports/44685
https://bootcamp.fjord.jp/reports/44705
https://bootcamp.fjord.jp/reports/44723
https://bootcamp.fjord.jp/reports/44756

また、どうも該当ユーザ(下記)の過去の日報ページも500になっている様子かな？と思いました。
https://bootcamp.fjord.jp/users/1270
https://bootcamp.fjord.jp/users/986
https://bootcamp.fjord.jp/users/1319
https://bootcamp.fjord.jp/users/602
https://bootcamp.fjord.jp/users/1108

**Comment by komagata** [comment]
@maedana @betachelsea こちら修正しました〜
