### ISSUE TITLE
sorcery-jwt の影響で Ruby 3.0 にアップデートできない

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#3893]
## 課題

Ruby 3.0 にアップデートすると、現在使っている sorcery (0.15.0) で `NoMethodError` が発生する。
sorcery 0.16 にアップデートすると解決するが、 sorcery に依存している sorcery-jwt が sorcery < 0.16 を使うようになっているため、 sorcery 0.16 にアップデートできない。

sorcery-jwt は JWT ログインのために使われている模様。

## 解決したいこと
sorcery を 0.16 以上にアップデートしたい

## 案

1. JWT login を廃止し、sorcery-jwt を使わないようにする
1. sorcery-jwt に PR を送り、gemspec のバージョン指定を緩めてもらう
1. sorcery-jwt を fork して gemspec のバージョン指定を緩めた版を使う

## ref
`https://github.com/Sorcery/sorcery/issues/270`
https://github.com/hayfever/sorcery-jwt/blob/master/sorcery-jwt.gemspec#L45
https://github.com/fjordllc/bootcamp/pull/3458

**Comment by ima1zumi** [comment]
@komagata 

sorcery-jwt が Ruby 3.0 アップデートのブロッカーになっているため、まとめて issue として起票しました。
質問が2点あります。

1. JWTログインは今も使っていますか？
1. 使っている場合、JWTログインを廃止するのはどれくらい現実的でしょうか？ 🤔

**Comment by komagata** [comment]
@ima1zumi Issue作成ありがとうございます。なるほどです。

> JWTログインは今も使っていますか？

外部からAPIを叩くときは常に使ってると思います〜

> 使っている場合、JWTログインを廃止するのはどれくらい現実的でしょうか？ 

JWTの実装を別のものに差し替えるとかなら現実的だと思いますが、JWTでの認証自体を他のものに変えるのは、特に良い代替案も思いついてないので避けれると嬉しいな〜という感じです。

**Comment by komagata** [comment]
sorcery-jwtに上記修正が取り込まれたためCloseします。
