### ISSUE TITLE
担当者が決まってない提出物（未アサイン）の数をDiscordに通知する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3897]
#2568 こっちのPRで作業していたが、「未返信の提出物」ではなく「未アサインの提出物」を通知したい

<img width="817" alt="スクリーンショット 2022-01-04 13 01 36" src="https://user-images.githubusercontent.com/16577/148007980-386f41fd-d337-4e19-84d1-04379e771808.png">

`/path-to/xxx.txt`の形のページを作るところまでのPRを作ってください。
そのページの内容をDiscordに通知する部分は @komagata がCloud Functionsを使って実装します。

**Comment by kaisumi** [comment]
本番環境で確認していただいたのでクローズします。
