### ISSUE TITLE
通知ページの全てのタブに未読数を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3907]
<img width="1099" alt="貼り付けた画像_2022_01_05_14_31" src="https://user-images.githubusercontent.com/168265/148165491-551467fe-60dd-4b53-abc6-a6c22c4d8eb2.png">

**Comment by Aseiide** [comment]
とりあえず似た実装をピックアップ
[通知ページの「お知らせ」のタブに全件数と未読の件数のバッチを表示する by yoshitaku-jp · Pull Request #3589 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/3589)

[通知ページの「全て」のタブに全件数の表示・未読の件数のバッチを表示しました by taka61 · Pull Request #3590 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/3590/files)

**Comment by machida** [comment]
@Aseiide 「全てのタブ」にIssueのタイトルを変更しました🙇‍♂️
