### ISSUE TITLE
通知ページの全てのタブの通知合計数を削除したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3909]
<img width="1099" alt="貼り付けた画像_2022_01_05_14_31" src="https://user-images.githubusercontent.com/168265/148166903-e2a63e1f-9a47-4f65-9685-7776701d7429.png">

この数を確認する機会はなく不要だったので削除。

**Comment by machida** [comment]
<img width="186" alt="貼り付けた画像_2022_01_08_20_30" src="https://user-images.githubusercontent.com/168265/148642496-4da9f4f6-e4de-4e4f-bcd1-6060ef56707f.png">

**Comment by ot0m1** [comment]
右上の赤丸は残す。削除するのはカッコだけ。
https://discord.com/channels/715806612824260640/809595476847493192/929337996392681493

**Comment by ot0m1** [comment]
マージされたのでクローズ。

**Comment by komagata** [comment]
@ot0m1 本番にリリースされて、本番環境で動作することを確認した時点でCloseをお願いします〜

**Comment by ot0m1** [comment]
@komagata こちらも失礼しました🙏

**Comment by komagata** [comment]
Reopenしておきます〜

**Comment by ot0m1** [comment]
本番環境で動作確認できたためクローズ。

![スクリーンショット 2022-01-26 22 53 43](https://user-images.githubusercontent.com/6190966/151175624-41232d5c-214c-4333-b674-c5ce01f7bc93.png)
