### ISSUE TITLE
他の人と日報名のかぶりがると登録できない

### ISSUE THREAD

**Issue by chamao** [fjordllc/bootcamp#391]

**Comment by chamao** [comment]
日報についてなのですが、今日の日報を書いていたところ、自分の日報で使用したことのない日報タイトルでも、他の方が既に書いていたと思われるタイトルを入力していた際に「タイトルはすでに存在しています」とエラーが出ました。
もし意図していない動作でしたら確認よろしくお願いします（個人的にはタイトルを変えればいいだけなので今のところ困っていません）。

**Comment by komagata** [comment]
@chamao なるほど、直したいですね。
直していただけるとありがたいですー！

**Comment by chamao** [comment]
@komagata 

これは、branchでプッシュしたのはいいものの、その後
machidaさんが既に対応済みだときづきました、、、

作成したbranchは一応こちらです。
https://github.com/fjordllc/bootcamp/tree/report_title_uniqueness

**Comment by komagata** [comment]
> これは、branchでプッシュしたのはいいものの

???

@chamao さんの作ったPRはありますか？

またPRでIssueリンクをはらないと（番号をDescriptionに入れる）他の人が同時に作業したりすることが発生してしまうので、今後お願いします。

**Comment by chamao** [comment]
@komagata 

push後にPR作ろうとした時にmachidaさんのブランチがマージされていることに
気づいてこのissueと、branchが宙ぶらりん状態でした。

>  PRでIssueリンクをはらないと（番号をDescriptionに入れる）他の人が同時に作業したりすることが発生してしまうので、今後お願いします。

了解です。

machidaさんが解決してくれたのでこのissueはcloseします。
