### ISSUE TITLE
お試し延長 開始・修了機能

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3910]
## 目的

お試し期間延長キャンペーンを行っているときに入会をした方が、ちゃんと自分はそれが適用されているかがわかること。
サイトのキャンペーンの表示・非表示を自動化すること（自動化することによって、トップページ以外にも表示したいところを対応したい）。
課金スタートなど支払いに絡む部分はこのIssueでは適用外とします。

## お試し延長ページ

管理画面（/admin）にお試し延長一覧を作成

<img width="1571" alt="貼り付けた画像_2022_01_05_14_51" src="https://user-images.githubusercontent.com/168265/148167951-4b98fa78-e52e-4485-a92b-3c7b7ee9e573.png">

管理画面（/admin）にお試し延長新規作成を作成

<img width="1571" alt="貼り付けた画像_2022_01_05_14_51" src="https://user-images.githubusercontent.com/168265/148169137-336e783c-a686-403c-bb50-8361fbbdd16a.png">

その期間に会員登録したユーザーには、お試し延長 フラグが追加される。

## 管理画面ユーザーページ

お試し延長タブを追加

<img width="1274" alt="貼り付けた画像_2022_01_05_16_52" src="https://user-images.githubusercontent.com/168265/148180640-fd892182-242c-4fb6-ab6f-b10cfcfde6c6.png">

## 会員登録

お試し延長が適用されていることを明示する。

<img width="654" alt="貼り付けた画像_2022_01_05_16_55" src="https://user-images.githubusercontent.com/168265/148180966-42930276-985d-4e0c-96ac-ded8c00e80e7.png">

## welcomeメッセージ

お試し延長適用ユーザーの場合、一週間の表示に変更。

<img width="766" alt="貼り付けた画像_2022_01_05_16_54" src="https://user-images.githubusercontent.com/168265/148180797-da0da1d7-7170-4f1d-9cc5-08c150cc3929.png">

**Comment by machida** [comment]
@napple29 こちらをお願いします。大きいIssueなので、仕様についてわからないことなどありましたら、質問お願いいます。また、後から仕様の変更や追加が出てくるかもしれないですが、柔軟にやりとりをしながら進めていきたいと思います。

@komagata こちら、何か仕様で足りないものなどないかご確認お願いしたいです🙏

**Comment by komagata** [comment]
@machida 今手動でやっててStripeと絡むのでちょっと簡単に実装するのは難しいかもです・・・。

**Comment by napple29** [comment]
@machida @komagata 
Issueのアサインありがとうございます。

要件や設計について質問をさせてください🙇🏻‍♀️
お忙しいと思うので、お時間のある時にご返信いただけたら幸いです。

## ①管理画面（/admin）にお試し延長一覧を作成について
以下の画像は、
- 1/4 00:00~1/5 23:59 の間に入会すれば◯日間お試し期間が延長　（こちらは終了している）
- 1/7 00:00 ~2/7 23:59 の間に入会すれば◯日間お試し期間が延長　（こちらはお試し延長実施中なので編集可能）

という解釈で合っていますか？

![image](https://user-images.githubusercontent.com/82350582/149458307-37a450ba-244a-443b-8f36-abaff13b4523.png)

## ②管理画面のユーザー一覧について
お試し延長の分類でユーザーが表示される仕様になっていますが、こちらに表示するのはお試し期間（無料で受講できる期間　ex.7日間など）のみと解釈していますが合っていますか？

![image](https://user-images.githubusercontent.com/82350582/149458735-70eadff1-f9fe-401f-999d-fca2befe6dc0.png)


## ③管理画面（/admin）にお試し延長新規作成
上記の解釈が合っていれば、「お試し期間が通常3日間から何日間に延長されるのか」という情報が欲しいので、こちらの新規登録画面に **【お試し期間：◯日間】** と入力する仕様にしても良いでしょうか？（デザインなど詳細は後ほど相談させていただきます！）

![image](https://user-images.githubusercontent.com/82350582/149461600-f96765c4-a8d2-4918-8fbf-bf3c13ffaccc.png)

## ④Stripeについて
駒形さんからStripeについて触れられていますが、Stripeと紐づくような設計というのがよくわかっていません…。
また、課金部分に絡まず、上記の要件をクリアするのであれば、DBにテーブルとカラムを追加することで実装できそうに思いましたが、自信がないので追って相談させていただきたいです…！

お忙しいと思いますが、よろしくお願いします🙏🏻

**Comment by machida** [comment]
@napple29 質問ありがとうございます！！ @komagata 

## ①管理画面（/admin）にお試し延長一覧を作成について

はい！その解釈で合っています🙆‍♂️

## ②管理画面のユーザー一覧について

すいません、これはお試し期間延長が適用されているユーザーの一覧の表示をお願いします🙏
このユーザー一覧は、お試し終了の日時も表示されていると助かります。

## ③管理画面（/admin）にお試し延長新規作成

確かに！その方がシンプルでいいですね👍
スタート日時と日数でお願いします。

## ④Stripeについて

Stripe に絡む部分は、今回は範囲外、引き続き手動での作業を想定しています。
なので、その部分は気にしないで大丈夫です。

> お試し期間延長キャンペーンを行っているときに入会をした方が、ちゃんと自分はそれが適用されているかがわかること。
課金スタートなど支払いに絡む部分はこのIssueでは適用外とします。

を目的としているので、

- サイトが「現在お試し期間延長中である」という情報を持つ。それを使って、
    - トップページにお試し期間延長中であることを表示する。
    - 申込みフォームにお試し期間延長中であることを表示する。
    - クレジットカード入力フォームにお試し期間延長中であることを表示する。
    - 料金のページに試し期間延長中であることを表示する。
    - その他、お試し期間延長中と通常時でデザインの分岐をします。
- 「お試し期間延長が適用されていること」をユーザーの情報に持たせる。それを使って、
    - ウェルカムメッセージにあるお試し期間の日数を延長された日数を表示する。
    - 誰がお試し期間適用ユーザーなのかを管理者が把握する（Stripeの延長の手続きは手動で行う）。

ができればOKですー

**Comment by napple29** [comment]
@machida 
返信ありがとうございます！Issueの概要がより理解できました🙇🏻‍♀️✨
作業をしていて不明な点があったらまた質問させていただきます🙏🏻

**Comment by komagata** [comment]
:memo: 町田さんとビデオチャットで検討したところ、基本的にこの仕様でOKということになりました〜。

**Comment by machida** [comment]
@napple29
一点だけ変更があります。仕様ではユーザーにキャンペーン適用のデータを持たす、と書いてありましたが、ここを変更したいです。

ユーザーがキャンペーン適用かどうかはデータには持たさず、そのユーザーの created された日時がキャンペーン期間内であったかどうかで判別をしたいと思います。

helperで「キャンペーン適用ユーザー？」みたいな判別できるものを用意してもらえると助かりますー

**Comment by napple29** [comment]
@machida
承知いたしました！そのようなhelperを持たせるよう実装します✨
不明点があったら都度質問しながら進めていきたいと思っていますので、よろしくお願いします🙇🏻‍♀️！

**Comment by napple29** [comment]
仕様について、質問タイムにて再度確認しました

## 管理画面（/admin）にお試し延長新規作成を作成

<img width="1571" alt="貼り付けた画像_2022_01_05_14_51" src="https://user-images.githubusercontent.com/168265/148169137-336e783c-a686-403c-bb50-8361fbbdd16a.png">

### 相談と確認：お試しできる期間自体は7日間から変動しないかどうか
このIssueをアサインされた時の私の考えとして

例)　お試し延長キャンペーン
1月20日〜1月26日まで
通常3日間から7日間にお試し期間が延長

のとき、7日間の部分も変更できると思ってしまい、

![image](https://user-images.githubusercontent.com/82350582/149461600-f96765c4-a8d2-4918-8fbf-bf3c13ffaccc.png)

のような提案をしましたが、お試しできる期間が常に 3日間 → 7日間 で、変動しないのであれば、町田さんに最初に提案していただいた案の方で実装したいと思っていますが、いかがでしょうか？

### 回答
・今後、お試しできる期間の設定もできるような実装をする可能性もあるが、今回のIssueでは適用外とするため、当初の開始日時と終了日時のみ入力できる実装とする。

・今回のIssueへ追加の要件で、キャンペーン自体のtitleを入れられるようにカラムを増やしたい。

## 管理画面ユーザーページ

お試し延長タブを追加

<img width="1274" alt="貼り付けた画像_2022_01_05_16_52" src="https://user-images.githubusercontent.com/168265/148180640-fd892182-242c-4fb6-ab6f-b10cfcfde6c6.png">

・お試し期間延長が適用されているユーザーの一覧の表示
・このユーザー一覧は、お試し終了の日時も表示

![image](https://user-images.githubusercontent.com/82350582/150728512-66ad40c4-e490-4f43-b868-39540e6843dc.png)

### 相談
上記のように、お試し延長タブに表示されるユーザーのみ、お試し延長終了日時の項目を追加したが大丈夫か？

### 回答
・現段階ではお試しできる期間の設定はしないため、ユーザーのお試し延長終了日時はなくて良い。
・お試し終了日時はStripeのAPIから情報が取れるのでここでは実装しない

## 会員登録

お試し延長が適用されていることを明示する。

<img width="654" alt="貼り付けた画像_2022_01_05_16_55" src="https://user-images.githubusercontent.com/168265/148180966-42930276-985d-4e0c-96ac-ded8c00e80e7.png">

クレジットカード情報の入力欄下の説明文
![image](https://user-images.githubusercontent.com/82350582/150734014-2ddcb6f4-cdd0-4246-b634-ee9e813ebf30.png)


## welcomeメッセージ

お試し延長適用ユーザーの場合、一週間の表示に変更。

<img width="766" alt="貼り付けた画像_2022_01_05_16_54" src="https://user-images.githubusercontent.com/168265/148180797-da0da1d7-7170-4f1d-9cc5-08c150cc3929.png">

<img width="741" alt="スクリーンショット 2022-01-24 15 40 39" src="https://user-images.githubusercontent.com/82350582/150734289-805cfa51-9594-454d-8454-098b292fb5d3.png">

## トップページ
![image](https://user-images.githubusercontent.com/82350582/150730940-de615791-311d-4029-9bfc-cfcc524c5615.png)

### 相談：キャンペーンページのデザインについて

「お正月のお正月のプログラミング学習応援キャンペーン」などのタイトルもDBにデータとして持たせて自動で切り変わるようにしたほうが良いか

### 回答

・このIssueではお試し延長キャンペーン適用の期間中かどうかで、該当のslimが切り替わることが目的
・そのためslimのデザインは触らなくて良い

・また、3日間から◯日間と変更する部分については、パーシャルを使用する予定。町田さんにデザインを入れていただく段階で修正する

**Comment by machida** [comment]
ref #4160

**Comment by napple29** [comment]
@komagata @machida 
お疲れ様です！管理者向けの機能があるので本番環境で以下の確認をお願いします！
- 管理画面にお試し延長タブがあり、そこに一覧と新規登録の画面があること
- 管理画面のユーザー一覧のターゲットにお試し延長の項目が増えていること

また、フィヨルドブートキャンプのトップページからずっと表示されていたキャンペーン広告が消されたことを確認しました！
それ以外のキャンペーン中の動作確認ができないのですが、この場合Issueはクローズしてしまって大丈夫でしょうか？

**Comment by komagata** [comment]
@napple29 本番環境で以下の動作することを確認しました。

- [x] 管理画面にお試し延長タブがあり、そこに一覧と新規登録の画面があること
- [x] 管理画面のユーザー一覧のターゲットにお試し延長の項目が増えていること

> それ以外のキャンペーン中の動作確認ができないのですが、この場合Issueはクローズしてしまって大丈夫でしょうか？

実際にキャンペーンをやったときに僕らが確認するのでCloseせずに残しておいてもらえるとありがたいです。 @napple29 さんの仕事としてはもう完了という意識で大丈夫です〜。

**Comment by napple29** [comment]
@komagata 
ありがとうございます！
承知いたしました😊このままopenにしておきます！実際に運用されるのが楽しみです〜！

チーム開発では大変お世話になり、本当にありがとうございました🙇🏻‍♀️
