### ISSUE TITLE
右側にある新着日報一覧を削除したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3914]
<img width="894" alt="貼り付けた画像_2022_01_05_22_42" src="https://user-images.githubusercontent.com/168265/148227097-696673f8-50a4-4c27-bb38-3bf0ce3aea34.png">

これに関する諸々を全て削除。
Sassファイルはmachidaが削除します。

**Comment by komagata** [comment]
👍 賛成に一票

**Comment by ot0m1** [comment]
本番環境で確認できたのでクローズ。
