### ISSUE TITLE
`Failed to Parsing`という文法のミスを含んだエラーメッセージを一掃したい

### ISSUE THREAD

**Issue by unstoppa61e** [fjordllc/bootcamp#3920]
**何故この機能が必要なのか**

多くのコード内に、表題のエラーメッセージが含まれています。
`Failed to Parse`なら分かるのですが、`ing`形になってしまっております。
また、この文法的に誤ったエラーメッセージは先例のコピペによって量産されており、そもそも、メッセージ内容と実際のエラー内容が合致しているのかも怪しいかもしれません。
全体的に書き換え（場合によっては削除）をした方が良いかと思いました。

**Comment by unstoppa61e** [comment]
@komagata 
こちら、assignを頂いたのですが、僕は既に21ポイント分割り振って頂いております！

**Comment by komagata** [comment]
@unstoppa61e かしこまりました。他に人にお願いしておきます〜

**Comment by komagata** [comment]
```
console.warn(error)
```

こういう感じに書き換えちゃってOK

**Comment by Aseiide** [comment]
本番環境で動作確認できたためcloseします。
