### ISSUE TITLE
メンターでログインした際に提出物個別ページに表示するリンクの追加

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3935]
メンターでログインしたときだけ表示

<img width="885" alt="貼り付けた画像_2022_01_11_10_35" src="https://user-images.githubusercontent.com/168265/148866040-5462a349-614d-44c0-b5a7-4ea323accb7b.png">

リンク先は以下。

- 自分の担当
    - /products/self_assigned
- 未アサイン
    - /products/unassigned

**Comment by machida** [comment]
@maeda-seina こちらアサインさせていただきましたー

**Comment by maeda-seina** [comment]
@komagata さん

こちらメンター向け機能のため、本番環境でのご確認お願いします🙇‍♂️
- 提出物個別ページに「自分の提出物担当一覧ページ」と「未アサイン提出物一覧ページ」に遷移するリンクが表示されていること。
- 「提出物・自分の担当」リンクを押すと「自分の提出物担当一覧ページ(/products/self_assigned)」に遷移すること。
- 「提出物・未アサイン」リンクを押すと「未アサイン提出物一覧ページ(/products/unassigned)」に遷移すること。

上記のご確認お願いいたします🙏

**Comment by komagata** [comment]
@maeda-seina 本番環境で動作することを確認しました。

- [x] 提出物個別ページに「自分の提出物担当一覧ページ」と「未アサイン提出物一覧ページ」に遷移するリンクが表示されていること。
- [x] 「提出物・自分の担当」リンクを押すと「自分の提出物担当一覧ページ(/products/self_assigned)」に遷移すること。
- [x] 「提出物・未アサイン」リンクを押すと「未アサイン提出物一覧ページ(/products/unassigned)」に遷移すること。

**Comment by maeda-seina** [comment]
@komagata さん
ご確認ありがとうございます！

本番環境で確認できたため、closeします。
