### ISSUE TITLE
sadがついた日報にコメントを書いて『確認OKにする』ボタンを押した際に『今日の気分は「sad」ですが、コメント無しで確認しますか？』が表示される

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#3941]
## 概要
sadがついた日報にコメントを書いて『確認OKにする』ボタンを押した際に
コメントを書いているのに『今日の気分は「sad」ですが、コメント無しで確認しますか？』が表示される

## 再現手順

1. sadをつけた日報を投稿
2. メンター権限で日報を開きコメントを書き『確認OKにする』を押す
3. 『今日の気分は「sad」ですが、コメント無しで確認しますか？』が表示される。

## 期待される振る舞い

コメントを書いている場合は『今日の気分は「sad」ですが、コメント無しで確認しますか？』が表示されない

## スクリーンショット

<img width="496" alt="Screen Shot 2022-01-11 at 10 58 20" src="https://user-images.githubusercontent.com/5990045/148977023-92edad8d-932a-453e-b2eb-776e394ffd36.png">

**Comment by machida** [comment]
@rlho 
Issue登録ありがとうございます！！
こちら優先度高めで進めたいと思いますー

**Comment by Aseiide** [comment]
@machida 
確認しました。ありがとうございます！

**Comment by machida** [comment]
本番で確認出来ました！クローズしますー
