### ISSUE TITLE
日報に次と前が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#395]
日報ページに次の日報と前の日報へのリンクがほしい。

（見ているユーザーのもの）

**Comment by neko314** [comment]
@komagata 

現状と方針のご報告です。
以下で過不足や誤りはありませんでしょうか？

* 現状

”見ているユーザーの”という条件をひとまずおいておいて、前後の日報に移動できるようにしました。
be5b4e9b0f387ebd13fd3cbf3537aec2271af9c0

* 今後の方針

  - ”見ているユーザーの”日報で前後するように変更
  - 最初の日報、最後の日報の場合、リンクが表示されないようにする

**Comment by sanfrecce-osaka** [comment]
@neko314 
- コミットへのリンクを貼るのではなくWIPのPullRequestを作成した方が作業履歴が残っていいですよ
  - https://qiita.com/zwirky/items/5733bb20c7dd4c98b769
- Waffleの作業状況を`Ready`から`In Progress`に変えましょう

**Comment by komagata** [comment]
@neko314 

> 以下で過不足や誤りはありませんでしょうか？

そういう時はWIPのPRを作って見てもらうのが定番ですー。

[Work in ProgressパターンによるPull Requestを利用した開発フロー \- Qiita](https://qiita.com/numa08/items/b676e38e3dbabfd39d18)
