### ISSUE TITLE
Docsを更新した際の更新者ユーザーアイコンの表示がおかしい

### ISSUE THREAD

**Issue by kotakawase** [fjordllc/bootcamp#3965]
## 概要
メンターの方が作成したDocsを受講生である自分の立場で更新をする機会があったのですが、[Docs一覧ページ](https://bootcamp.fjord.jp/pages)で表示される更新者のユーザーアイコンの表示が受講生の枠なし表示ではなくメンターの赤枠で表示されてしまっています。キャプチャはWIP状態のものですが、提出した際の表示も確認してみたところ同じように表示されます。

## 再現手順

1. 該当する[Docs](https://bootcamp.fjord.jp/pages/409)にアクセス。
2. 「内容変更」をクリック。
3. 内容を編集後、「WIP」または「内容を保存」をクリック。
4. 保存されるのを確認する。
5. [Docs一覧ページ](https://bootcamp.fjord.jp/pages)にアクセス。
6. 該当するDocsの更新ユーザーのアイコン表示が自分の立場上枠なしになるはずがメンターの赤枠になって表示されている。

## 期待される振る舞い
メンターの赤枠でアイコン表示されるのではなく受講生の枠なしで表示されるようにする。

参考：[メンター、アドバイザー、卒業生の見分け方](https://bootcamp.fjord.jp/pages/360())

## スクリーンショット

![image](https://user-images.githubusercontent.com/74460623/149355668-d57582b2-3285-4357-b46e-0b99a9811949.png)

**Comment by komagata** [comment]
@kotakawase 作成者の変更は行われない仕様なので問題ないかも？

**Comment by kotakawase** [comment]
@komagata 
問題ないことを確認できてよかったです🙇‍♂️ 一時的に表示されてしまっているのですかね…。
ちなみに今回のようにIssueが採用されない場合は自分の方でクローズすればよろしいでしょうか？

**Comment by komagata** [comment]
@kotakawase すみません、こちらの文章を読み間違えていました。
垢枠になってたらおかしいですね。

**Comment by kotakawase** [comment]
@komagata 
こちらこそ勘違いさせてしまう説明文で書いてしまい申し訳ございませんでした🙏
タイトルと説明文を修正しましたのでご確認お願いいたします。

**Comment by komagata** [comment]
@kotakawase いや、かわせさんの文章は全く問題ないです。
僕が全くの勘違いをしていただけですのでお気になさらず〜

**Comment by machida** [comment]
こちら解決したのでクローズしますー

**Comment by kotakawase** [comment]
@machida 
ご対応いただきありがとうございます✨
よろしければ該当するPRを教えていただいてもよろしいでしょうか？👀

**Comment by machida** [comment]
@kotakawase 
https://github.com/fjordllc/bootcamp/pull/4299
こちらになりますー

**Comment by kotakawase** [comment]
@machida 
別issueで対応されていたのですね！
教えていただきありがとうございました🙇‍♂️
