### ISSUE TITLE
日報の不具合が再発しないようにテストを追加したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#3969]
関連：
- #3964
- #3825
- [🙇‍♂️ 日報編集画面で不具合が発生しています | FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/announcements/603)
- https://discord.com/channels/715806612824260640/809595476847493192/931159201223421993

**Comment by machida** [comment]
日報にMarkdownを入力したら、プレビューにHTMLで表示されている。
というテストを追加していただきたいですー
