### ISSUE TITLE
日報プレビュー画面が表示されないようです

### ISSUE THREAD

**Issue by satorutanahashi** [fjordllc/bootcamp#3978]
バリバリ初心者故に不安なのですが、コメント欄で書くように指南いただきました故に
はじめて書かせていただきます。

## 概要

日報のプレビュー画面が表示されないエラー

## 再現手順

1. 過去日報の画面で、「コピー」（右上ボタン）を押す
2. 内容枠内には、過去日報の内容がしっかり表示されていますがプレビュー枠内には何も表示されません
3. 内容枠内に新たに文字を入力してもプレビュー枠には何も表示されません

一方、下記は正常に動いています。

1．「＋日報作成」ボタンを押す
2．内容枠内にはテンプレートが反映されており、内容枠内に新たに文字を入力するとプレビュー枠内には即座に反映されます

## 期待される振る舞い

過去日報の画面で、「コピー」（右上ボタン）を押すと、内容枠の内容とプレビュー枠の内容が同期されている状態

## 環境

 - OS: [Windows]
 - ブラウザ: [chrome]
 - バージョン: [1909]

**Comment by machida** [comment]
@satorutanahashi  Issue登録ありがとうございます！！今日のリリースで修正されました🙏
