### ISSUE TITLE
日報に下書き機能が欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#398]
- 作業をしながら日報を書きたい
- 書き途中の消えないように保存をしたい
    - つまり、公開と保存、2つの概念が欲しい 
- 保存をしても公開されないか、公開されてもこれは下書きであるとわかるようにしたい（厳しく非公開にする必要はない、下書きが見えてもいいが、下書きとわかるようにしたい esa のwip と同じでもOK）

**Comment by komagata** [comment]
WIP機能と重複
