### ISSUE TITLE
「はじめての日報を書きました！」通知は現役生とメンターのみにする

### ISSUE THREAD

**Issue by ima1zumi** [fjordllc/bootcamp#3981]
## 機能の説明

タイトルの通り

## 何故この機能が必要なのか

卒業生などbootcampへのログイン頻度が少ない人の場合、「はじめての日報を書きました！」の通知で通知欄が数十件たまってしまうことがあります。メンションを見落とす可能性があるため、通知のオンオフを設定したいです。

**Comment by machida** [comment]
Issueありがとうございます！！
確かに、頻度も上がったりなどしてるので、一旦、「はじめての日報を書きました！」通知は現役生とメンターのみにしたいと思います。一旦はここまでにして、今後、メンターだけに絞ることも検討したいと思います。

**Comment by maeda-seina** [comment]
@komagata さん、 @machida さん

お疲れ様です。
こちら、「初めての日報書いたときに、”サイト内通知”も”メール通知”もどちらも卒業生には飛ばさないようにする」という実装で進めていけばよろしいでしょうか？

**Comment by komagata** [comment]
@maeda-seina 

> お疲れ様です。 こちら、「初めての日報書いたときに、”サイト内通知”も”メール通知”もどちらも卒業生には飛ばさないようにする」という実装で進めていけばよろしいでしょうか？

はい、そうです。

**Comment by ima1zumi** [comment]
横からすみません。アドバイザーなど、卒業生以外のroleには従来通り通知を飛ばすという認識であっていますか？

**Comment by maeda-seina** [comment]
@komagata さん
了解いたしました、ありがとうございます！

@ima1zumi さん
こちら認識がずれていました、ありがとうございます…‼︎🙇‍♂️（卒業生だけに通知を飛ばさないと勝手に解釈してしまっていました。）

@komagata さん、 @machida さん
> 一旦、「はじめての日報を書きました！」通知は現役生とメンターのみにしたいと思います。

こちらの町田さんのコメントのように、
現役生とメンターのみに通知がいくように実装していく方針でよろしいでしょうか？

**Comment by komagata** [comment]
@maeda-seina 

> こちらの町田さんのコメントのように、 現役生とメンターのみに通知がいくように実装していく方針でよろしいでしょうか？

はい。

**Comment by maeda-seina** [comment]
@komagata さん、 @machida さん
お疲れ様です。
こちら本番環境で確認したところ、卒業生に通知がいってしまうということがわかりました。
PR作成して、修正させて頂きます🙇‍♂️

**Comment by maeda-seina** [comment]
@komagata さん @machida さん
お疲れ様です。
こちら本番環境でリリースされて10日ほど経ちました。
以前と変わらずに、「〇〇さんがはじめての日報を書きました。」通知がサイト内通知・メール通知ともに届いてますでしょうか？

**Comment by komagata** [comment]
@maeda-seina 本番環境で確認できました〜！

**Comment by maeda-seina** [comment]
@komagata さん
ご確認ありがとうございます!!😄🙇‍♂️

**Comment by maeda-seina** [comment]
本番環境で確認できたためcloseします。

---
本番環境確認に協力してくださった方々ありがとうございました🙏
@komagata さん
@kaiyu-tech さん
@sinsoku さん
