### ISSUE TITLE
タグの編集後に「保存する」ボタンを見つけられなくてテストが失敗することがある

### ISSUE THREAD

**Issue by AudioStakes** [fjordllc/bootcamp#3982]
## 概要

ユーザーのタグを編集するテスト（下記2つ）が失敗することが多いようです。これにより CI があまり通らなくなっています。

https://github.com/fjordllc/bootcamp/blob/6c7c3220e93d311bc2b28294a9e97ef7af5dea8e/test/system/user/tags_test.rb#L50-L62

https://github.com/fjordllc/bootcamp/blob/bbd200f697cc393dfcd000145db3648c98ab0f31/test/system/user/tags_test.rb#L75-L86

## 再現手順

`$ rails test test/system/user/tags_test.rb:{50,75}` で対象のテストを実行すると、次のように失敗することが多いです。

```
$ rails test test/system/user/tags_test.rb:{50,75}
Running via Spring preloader in process 40722
Run options: --seed 2775

# Running:

Capybara starting Puma...
* Version 5.5.1 , codename: Zawgyi
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:63843
Capybara starting Puma...
* Version 5.5.1 , codename: Zawgyi
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:63851
[Screenshot Image]: /Users/satoudaisuke/src/github.com/fjordllc/bootcamp/tmp/screenshots/failures_test_edit_user_tag_current_user_page.png
E

Error:
User::TagsTest#test_edit_user_tag_current_user_page:
Capybara::ElementNotFound: Unable to find button "保存する" that is not disabled
    test/system/user/tags_test.rb:56:in `block in <class:TagsTest>'


rails test test/system/user/tags_test.rb:50

[Screenshot Image]: /Users/satoudaisuke/src/github.com/fjordllc/bootcamp/tmp/screenshots/failures_test_the_first_letter_is_ignored_when_adding_a_tag_whose_name_begins_with_octothorpe.png
E

Error:
User::TagsTest#test_the_first_letter_is_ignored_when_adding_a_tag_whose_name_begins_with_octothorpe:
Capybara::ElementNotFound: Unable to find button "保存する" that is not disabled
    test/system/user/tags_test.rb:81:in `block in <class:TagsTest>'


rails test test/system/user/tags_test.rb:75



Finished in 12.437939s, 0.1608 runs/s, 0.0000 assertions/s.
2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
```

## 期待される振る舞い

これら2つのテストが常に成功するようにしたい

### テストが失敗する原因

`find('body').click` した後の `click_button '保存する'` でボタンを見つけられなくなっていること（なぜ見つけられないのかはわかっていない）

該当箇所
https://github.com/fjordllc/bootcamp/blob/6c7c3220e93d311bc2b28294a9e97ef7af5dea8e/test/system/user/tags_test.rb#L55-L56

### テストの修正案

画面のクリック（ `find('body').click` ） を エンターキーの押下（ `tag_input.native.send_keys :return` ）に変更すると、テストが成功するようになる。
画面をクリックする意図は「入力中のタグの編集を完了すること」であると考え、それはエンターキーの押下でも実現可能なので、テストでエンターキーの押下を試した結果、テストが成功するようになった。

## 該当のテストコードが加えられたコミット

6ae16a7, c126464

**Comment by AudioStakes** [comment]
@komagata @machida 
この Issue に記載したテスト2つが失敗しやすく、現在 CI があまり通らなくなっています。
今後も CI が通らないことが頻発しそうなので、早めに対応した方がよいかもしれません。もし差し支えなければ、僕の方でこの Issue の対応を進めてもよいでしょうか？

なお、テストが失敗する原因を確認しているうちに修正案がわかり、軽微な修正だったため、修正の PR #3983 は作成してみました。

**Comment by komagata** [comment]
@AudioStakes 

> もし差し支えなければ、僕の方でこの Issue の対応を進めてもよいでしょうか？

ありがとうございます。そうしていただけると大変ありがたいです〜。

**Comment by AudioStakes** [comment]
本番環境へリリースされたため、クローズしますー
変更内容はテストの修正なので、本番環境で確認することは特にありません
