### ISSUE TITLE
プラクティス詳細画面に表示されるDocsタブをクリックすると500エラーが発生する

### ISSUE THREAD

**Issue by kotakawase** [fjordllc/bootcamp#3987]
## 概要
プラクティスの詳細画面にて、Docsタブをクリックすると500エラーが発生します。

エラー確認できたページ
https://bootcamp.fjord.jp/practices/147
https://bootcamp.fjord.jp/practices/158
https://bootcamp.fjord.jp/practices/211

## 再現手順

1. 上記に記載あるページへアクセス。
2. 「Docs」タブをクリック。
3. 500エラーが表示される。

## 期待される振る舞い
Docsの画面に遷移されてほしい。
例えば「どんなサービスを作るかを考える」のプラクティスのDocsは4つあるみたいなので、
https://bootcamp.fjord.jp/pages/235 とか
https://bootcamp.fjord.jp/pages/409 が見れるはずだと思います。

## スクリーンショット
![image](https://user-images.githubusercontent.com/74460623/149718274-642ce2f2-970a-453f-8b85-947c1e8342fb.png)

<img width="1552" alt="スクリーンショット 2022-01-17 15 00 34" src="https://user-images.githubusercontent.com/74460623/149716947-4f0177b0-3138-4d8c-99c2-cdb50d50e37f.png">

## 環境
 - OS: macOS Big Sur
 - ブラウザ: chrome
 - バージョン: 97.0

**Comment by machida** [comment]
@kotakawase 
Issue登録ありがとうございます！！

**Comment by maeda-seina** [comment]
本番環境で確認できたため、closeします。
