### ISSUE TITLE
プラクティスの詳細画面に、プラクティス共通で表示させるブロックを追加したい

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#3995]
## 機能の説明

現在プラクティスの詳細画面はプラクティスごとに内容を書かないといけない。
困った場合の対応についてなどは全プラクティスに共通して表示したい。
そのため全プラクティスで横断的に表示できるブロックを作ってほしいです。
https://bootcamp.fjord.jp/practices/223

## 何故この機能が必要なのか

以下のような困った場合の対応について、などは全プラクティスに共通して表示したい。
全プラクティスにコピーアンドペーストしたり内容が変わったときに全部のプラクティスを変更するのに時間がかかるのでプラクティスで共通で編集できるブロックがほしいです。

```
## 困った時は
### エラーがでて原因がわからない…
[プログラミング初心者歓迎！「エラーが出ました。どうすればいいですか？」から卒業するための基本と極意（解説動画付き）](https://qiita.com/jnchito/items/056325421b7e36f02335)を参考にデバッグをしてみよう

### Q&A・質問・雑談ルームを利用しましょう！
[🤔 わからないことをメンターや他の受講生に質問をする方法](https://bootcamp.fjord.jp/pages/245) を参考に質問をしてみましょう！

### ペアプロを依頼してみよう
コードを書いている時に詰まったりエラーが出た時は、テキストで伝えるのが大変な事が多いので、指摘の意図が分からなかったり質問のテキスト化に苦労したらペアプロを依頼してみましょう。メンター側もテキストで伝えるのが大変なので、ご遠慮なく！
```

**Comment by machida** [comment]
@tksmasaki 

1. docs(pages) に `practice_common_description` という slag を持ったページを作成する
1. 全てのプラクティス個別ページに `practice_common_description` という slag を持ったページの body が表示されるようにしたい。

**Comment by machida** [comment]
特定の slag を持った docs の内容を、どこかのページの一部に表示させる、ということは今後も発生する可能性があります。なので、書きやすい形で特定の slag を持った docs の内容が取ってこれるようになると嬉しいです。

**Comment by tksmasaki** [comment]
本番環境での動作確認が完了したため、Close します！
動作確認のために作成した Doc は削除しました。

@komagata @machida 
実際に活用する Doc に関しては内容の検討等もあると思うので、作成をおまかせしたいです。よろしくお願いします🙏

また、現状では WIP の場合にも対象の Doc の内容が表示されてしまいます。ご承知おきください。
こちらに関しては、WIP対応の Pull Request を作成しました。事前に気づけずに申し訳ありません🙇‍♂️
