### ISSUE TITLE
sadがついた日報を公開した後にヘルプへ誘導するポップアップを表示したい

### ISSUE THREAD

**Issue by rlho** [fjordllc/bootcamp#3996]
## 機能の説明

sadがついた日報を公開した後にヘルプへ誘導するポップアップを表示したい
文言は↓みたいな感じかなと思ってます。今考えただけの文言なので他の文言に変えてもらうの大歓迎です。

```
今日も学習お疲れ様でした！
[ヘルプページ](https://bootcamp.fjord.jp/pages/help)には学習のヒントになる情報が載っているので困った時はぜひのぞいてみてください
```

## 何故この機能が必要なのか

ヘルプページやQ&Aにたたくさんのモチベーションに関する情報や詰まっているときにヒントになる情報がたくさんあります。
しかし1人で詰まって悩んでいるときにはなかなかそれらの存在に気づくことは難しいと思います。
そこで日報に sadをつけた人に対してヘルプページを気づかせるための誘導導線を作りたいです。

**Comment by kaisumi** [comment]
@machida お疲れ様です。
本件のできあがりイメージについて質問です。
「ポップアップ」とありますが、内容を考えると以下のようなJSポップアップよりも
![image](https://user-images.githubusercontent.com/39044468/150235144-181a70af-b961-4c74-a8fc-bde75ebdb3df.png)
以下のようにHTML内に表示する方がいいかと思いました。
![image](https://user-images.githubusercontent.com/39044468/150234347-bfc20b7d-db0a-4a9d-8303-58f001adb644.png)

また、表示回数は日報提出時の1回のみがいいかと思っております。

この方針でいかがでしょうか。

**Comment by machida** [comment]
@kaisumi

表示は ポップアップするモーダルウィンドウ での表示を想定していますー。

![image](https://user-images.githubusercontent.com/168265/150294760-97833e65-98e6-41de-b655-f9bdbbc1512e.png)

> 表示回数は日報提出時の1回のみ

はい、そのようにお願いしたいです🙏

**Comment by kaisumi** [comment]
本番環境で動作を確認したのでクローズします。
