### ISSUE TITLE
vueファイル、jsファイル内の不要なパスの記述を削除したい

### ISSUE THREAD

**Issue by naomichi-h** [fjordllc/bootcamp#3997]
## 概要
現在、アプリ内のvueファイルおよびjsファイル内に、不要なパスの記述(`./`)を含むものがある。
これを削除し、パスに不要な記述をしないように統一したい。

例）
`app/javascript/announcement.js:2`
```js
import Announcements from './announcements.vue' 
```
　　　　　　　　　　　　↓
```js
import Announcements from 'announcements.vue'
```

**Comment by komagata** [comment]
@naomichi-h 自分で聞いておいてなんですが、これってこの変更しても動くんでしたっけ？

**Comment by naomichi-h** [comment]
@komagata はい。動きます。
https://github.com/fjordllc/bootcamp/pull/3917 ではすでにこの変更(`./`を消す変更)をしていますが、CIも通っています。

**Comment by komagata** [comment]
@naomichi-h なるほどです〜！

**Comment by siso25** [comment]
本番環境で一通りページの動作を確認しましたので、クローズします。
