### ISSUE TITLE
【メンター向け】コメントと同時に確認済みにできなくなった？

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4018]
以前はコメントするボタンの横に「確認済みにする」ボタンがあった気がするんですか、なくなりました？

https://bootcamp.fjord.jp/products/10967

<img width="702" alt="Screen Shot 2022-01-24 at 8 42 54" src="https://user-images.githubusercontent.com/1148320/150703053-fe19864d-2d59-4fdf-8d3c-9dff5a16ba7a.png">

上記のスクショはメンターモードONかつまだ確認済みにしていない状態でのスクショです。

<img width="544" alt="Screen Shot 2022-01-24 at 8 44 07" src="https://user-images.githubusercontent.com/1148320/150703079-bc4e09d0-0f46-4c70-9073-b0d9cba62744.png">

**Comment by machida** [comment]
@JunichiIto すいません、メンターと管理者の機能を整理してたのですが、そのときに非表示してしまったようです。こちらすぐに修正するようにします🙇‍♂️

**Comment by JunichiIto** [comment]
@machida 了解です。自動テストで検知できるとなお良しですね〜。

**Comment by machida** [comment]
@JunichiIto ありがとうございます！こちらテストも追加しますー💪
