### ISSUE TITLE
vue.js を使っているところでも複数の role を認識出来るようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4025]
例えばこのファイル `/app/javascript/comments.vue` の以下の部分。

``` js
.card-main-actions__item.is-only-mentor(
  v-if='(currentUser.role == "mentor" || currentUser.role == "admin") && commentType && !checkId'
)
  button.a-button.is-md.is-danger.is-block(
    @click='commentAndCheck',
    :disabled='!validation || buttonDisabled'
  )
    i.fas.fa-check
    | 確認OKにする
```

現在はユーザーに一つの role しか認識されていないので、
`(currentUser.role == "mentor" || currentUser.role == "admin")`
このように書いている。

本来であれば、komagata、machida は mentor と admin の 2つの role を持っているので、
`currentUser.role == "admin"` は不要。

ところが、mentor と admin の 2つの role を持っているのに、admin の方しか認識されていないので、
`currentUser.role == "mentor"` が true にならない。
そのため、 `(currentUser.role == "mentor" || currentUser.role == "admin")` と書いている。

複数の role が認識されるようになれば、
mentor と admin の 2つの role を持っている komagata、machida でも、
`currentUser.role == "mentor"` が true になり、
`(currentUser.role == "mentor" || currentUser.role == "admin")` と書かずに、
`currentUser.role == "mentor"` だけで済むようになる。

**Comment by ot0m1** [comment]
ref: https://discord.com/channels/715806612824260640/809595476847493192/942035335154659328

- https://github.com/fjordllc/bootcamp/issues/4025#issue-1112357516 にあるような `v-if='(currentUser.role == "mentor" || currentUser.role == "admin") && commentType && !checkId' ` に該当するコードは現在 `app/javascript/comments.vue` に存在していない
- 実装を追うと代わりに `v-if='(isRole("mentor") || isRole("admin")) && commentType && !checkId'` というロール判定のメソッドになっているようである
- 履歴を追ったところ https://github.com/fjordllc/bootcamp/pull/3979 このプルリクの実装で変更になった模様
- 上記のプルリクによって、このissueの問題は解消されているように思える（そのためおそらく if 文の修正だけで対応できる）

上記のような背景からポイントを3から2に変更して、if 文の修正のみの対応を行う。

**Comment by ot0m1** [comment]
@komagata こちら管理者でのみ確認可能なためご確認お願いいたします。

**Comment by komagata** [comment]
@ot0m1 これって何を確認すれば良いですか？

**Comment by ot0m1** [comment]
@komagata 言葉足らずで失礼いたしました〜🙇‍♂️
`app/javascript/question-edit.vue`、`app/javascript/comments.vue`、`app/javascript/answer.vue`のファイルで表示しているページにおいて、管理者のロールでログインした際に if 文が true となり対象の id や class の要素がレンダリングされていることを確認いただくようになっています。

具体的には以下です。

- app/javascript/answer.vue
  - ログイン者以外のQ&Aの回答で`ベストアンサーにする`、`ベストアンサーを取り消す`、`削除する`が表示されて機能する
- app/javascript/comments.vue
    - 任意のページのコメントのブロック（例えば日報のコメント）に、`<div class="card-main-actions__item is-only-mentor">`というエレメントが存在している
- app/javascript/question-edit.vue
    - ログイン者以外のQ&Aの質問で、`内容修正`、`削除する`が表示されて機能する

**Comment by ot0m1** [comment]
@komagata 
ログインしたアカウントと、Q&A の質問や回答を投稿したアカウントが同じ場合だと生徒のロールのアカウントでも`ベストアンサーにする、ベストアンサーを取り消す`などの作業ができてしまうので、例えば `komagata` さんのアカウントでログインした場合は `komagata` さん以外のアカウントが投稿している Q&A のページやコメントを閲覧する、という意味で書いていました。

重ね重ね分かりづらくてすいません！

なので上記の質問については「ログインしてない人」ということになります。

**Comment by komagata** [comment]
@ot0m1 すみません、ちょっとまだ理解できてないです。

「ログイン者」ってのがあまり使わない表現だったので混乱しています。

サイトの動作確認だと「ログインしてる人」「ログインしてない人」ってのはどのユーザーかって意味ではなく「サイトにログイン処理をしてる人」「サイトにログイン処理をしていない（会員ではない）ユーザー」って意味で使うので、

「ログイン者以外」だと「ログイン処理をせずにアクセスしている人」って意味になっちゃうかもです。

**Comment by ot0m1** [comment]
@komagata 
> サイトの動作確認だと「ログインしてる人」「ログインしてない人」ってのはどのユーザーかって意味ではなく「サイトにログイン処理をしてる人」「サイトにログイン処理をしていない（会員ではない）ユーザー」って意味で使う

確かにその通りでした。ログインしていることが当たり前と思い込んでしまっておりました。
また、変に汎用的に書こうとして分かりづらくなっていました。確認いただたきたいのは以下です。

- `app/javascript/answer.vue`
  - 管理者のロールのアカウント（`komagata` or `machida`）でログインし、 生徒のロールのアカウントが作成したQ&Aの回答で`ベストアンサーにする`、`ベストアンサーを取り消す`、`削除する`が表示されて機能する
- `app/javascript/comments.vue`
    -  管理者のロールのアカウント（`komagata` or `machida`）でログインし、任意のページのコメントのブロック（例えば日報のコメント）に、`<div class="card-main-actions__item is-only-mentor">`というエレメントが存在している
- `app/javascript/question-edit.vue`
    -  管理者のロールのアカウント（`komagata` or `machida`）でログインし、 生徒のロールのアカウントが作成したQ&Aの質問で、`内容修正`、`削除する`が表示されて機能する

**Comment by komagata** [comment]
@ot0m1 本番環境で確認してみました。２番目が確認できませんでした〜

- [x] 管理者のロールのアカウント（komagata or machida）でログインし、 生徒のロールのアカウントが作成したQ&Aの回答でベストアンサーにする、ベストアンサーを取り消す、削除するが表示されて機能する
- [ ] 管理者のロールのアカウント（komagata or machida）でログインし、任意のページのコメントのブロック（例えば日報のコメント）に、`<div class="card-main-actions__item is-only-mentor">`というエレメントが存在している
  - komagataのユーザーで日報のページのdomを検索したが上記のクラスを持つものは見つからなかったです。
- [x] 管理者のロールのアカウント（komagata or machida）でログインし、 生徒のロールのアカウントが作成したQ&Aの質問で、内容修正、削除するが表示されて機能する

**Comment by ot0m1** [comment]
@komagata
ご確認ありがとうございました。
添付のスクリーンショットのように、日報のコメントとして`確認OKにする`ボタンが表示されませんでしょうか。

このボタンの箇所が `<div class="card-main-actions__item is-only-mentor">` となっています。（ここだけボタンの名称じゃなくて DOM で指定しちゃってすいません）

僕の環境ですとステージングで管理者のロールのアカウントにてログインし、確認ができております。

![スクリーンショット 2022-03-01 20 11 15](https://user-images.githubusercontent.com/6190966/156158918-55ab4319-88f9-477a-bc32-80b7648c63fa.png)


```
<div class="card-main-actions__item is-only-mentor">
    <button disabled="disabled" class="a-button is-md is-danger is-block">
        <i class="fas fa-check"></i>確認OKにする
    </button>
</div>
```

**Comment by komagata** [comment]
@ot0m1 上記確認できました〜

**Comment by ot0m1** [comment]
ご確認ありがとうございました。issue クローズいたします。
