### ISSUE TITLE
開発環境でエラーが出る（管理者でないユーザーの場合、talkのidが取得できずエラー）

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4029]
![image](https://user-images.githubusercontent.com/168265/150907912-dda1659d-3a26-4f7e-b1ac-7fa03ee7f50f.png)

現在最新のmainブランチで、管理者以外のuserでログインしようとするとエラーになります。
エラー画面で示している通り、恐らくtalkを一つも持っていない、管理者でないユーザーの場合、talkのidが取得できずエラーになるようです。

**Comment by komagata** [comment]
@machida これ`rails db:reset`した状態でも出ちゃいますかね？
