### ISSUE TITLE
Q&Aの一覧画面にコメント数（回答数）を表示したい

### ISSUE THREAD

**Issue by haruguchi-yuma** [fjordllc/bootcamp#4036]
## 機能の説明
ちょっと前まではQ＆A一覧ページにコメント数が表示されていたと思うんですが、便利だったので復活してほしいです。
![image](https://user-images.githubusercontent.com/57053236/151086923-c2da17c7-7aaa-42d2-98b6-18b8e99a6950.png)

## 何故この機能が必要なのか
コメント数が0の場合自分が解決できる答えを持ってなくても（Discordで宣伝するなど）何かしらアクションを起こせる。
自分がその質問を参考にしたい場合、Q＆Aの詳細ページにいくまで回答の有無が分からないのは不便。

**Comment by JunichiIto** [comment]
> ちょっと前まではQ＆A一覧ページにコメント数が表示されていたと思うんですが

これ僕も思ってました。僕の勘違いじゃなかったかw
たしかに復活してほしいですね〜。

**Comment by Paru871** [comment]
@JunichiIto @haruguchi-yuma 
こちらのIssueにつきまして町田さんの許可をいただき、対応をさせていただきますー。
(現在、他IssuesのQ&AページのWIP機能追加に取り組んでいるため、ちょうど修正ポイントを見つけました。)
ご一緒にコードもチェックしていただけましたらとても幸いです。
よろしくお願いします🙏

**Comment by JunichiIto** [comment]
@Paru871 対応ありがとうございます！PRにコメントしました。（以降のやりとりはPR上で進めましょう）

**Comment by Paru871** [comment]
こちらのIssueは本日のリリースで本番環境での確認ができましたのでクローズとさせていただきます。
大変勉強になる挑戦をさせていただき、ありがとうございました🙏
