### ISSUE TITLE
コメントと同時に提出物を確認のテストを追加

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4038]
#4042、##4040 が終わったあとに対応。

<img width="937" alt="貼り付けた画像_2022_01_26_14_53" src="https://user-images.githubusercontent.com/168265/151111152-f69901ee-c835-423f-aeec-35f62f0cc546.png">

コメントと同時に日報を確認するボタンのテスト（上記のボタン）を、メンターのパターン、管理者のパターンで書く。
#4042、##4040 で作成されたユーザーを使い、komagata、machida は使わないようにする（管理者兼メンターなので）。

**Comment by garammasala29** [comment]
[\#4212](https://github.com/fjordllc/bootcamp/pull/4212)で実装されていますので、本issueはクローズします
