### ISSUE TITLE
コースを選択できるようにする

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4044]
コースを選んでサインアップできるようにしたい。

- コースの選択肢とコースの説明が必要。

**Comment by komagata** [comment]
@machida こちら、下記のパターンがあるかな〜と思うんですが、UIやデザインの都合で決めちゃった方がいいかな〜と思いました。どういう形がいいですかね〜？

- サインアップフォームの上の方にコース一覧と説明があるパターン
- トップページにコース一覧と説明があるパターン
- 個別のページとしてコース一覧と説明があるパターン

**Comment by machida** [comment]
@komagata 

以下のようにしたいと思いますー

- サインアップフォームの上の方にコース一覧と説明の概要があり、その中から選択をする。
- サインアップフォームの上の方にコース一覧と説明の概要はリンクがあり、それをクリックすると、モーダルでコースの説明が表示される
- 上記とは別にコースの説明ページを1ページ持つ。各コースごとに1ページではなく、1ページですべてのコースを説明するで良さそう。モーダルで表示されるコースの説明は、このページで表示される説明と共通化したいのでpartialにしたい。
- コースの説明ページからサインアップフォームに遷移場合は、遷移元のコースが選択されている状態にする。

<img width="718" alt="貼り付けた画像_2022_02_03_10_54" src="https://user-images.githubusercontent.com/168265/152268765-e9bf136f-04f7-49ba-af85-c15fb88a6156.png">

<img width="911" alt="貼り付けた画像_2022_02_03_11_00" src="https://user-images.githubusercontent.com/168265/152269191-49333c6b-0432-4fcf-aa11-3b85c0fa1fcf.png">

**Comment by komagata** [comment]
@machida 下記の両方って感じですかね〜？

> - サインアップフォームの上の方にコース一覧と説明があるパターン
> - 個別のページとしてコース一覧と説明があるパターン

できればシンプルにするためにどれか一つに統一できるといいかな〜と思いました。
また、ここだけでは無いのですが、自作のモーダルウィンドウは極力使いたく無いな〜と考えています。

なぜかというと、ブラウザが本来持つ部品ではないUI部品なので、自作せずに他で代替できる場合であればそちらを使った方がいいかなという点があるからです。（実装も不安定になりがちで、実際に今もページを戻ると時々モーダルの背景の黒い画面が出てしまうというバグが原因・再現不明）

アプリの中心部分となる様な部分にモーダルだけによって実現できるある種のUIはあるとは思いますが、代替手段があり、必須でない場合はできれば避けたいな〜と思っております。

いかがでしょうか。

**Comment by komagata** [comment]
@machida こちらいかがでしょうか？

**Comment by nakamu-kazu222** [comment]
@komagata @machida

お疲れ様です

本Issueの実装について、2点相談がございます
お手隙の際に、ご確認いただけると幸いです


1. 以下の画像のような実装でよろしいでしょうか？

  - コース名の枠をクリックすると、チェックマークなどの目印が付与され選択された状態になる
  - `詳しく`を押すと、コースの説明が記載されているモーダルが表示される
  - `コース一覧`を押すと、すべてのコースを説明するページに遷移される
    - サインアップフォーム
      <img width="688" alt="スクリーンショット 2024-05-16 16 32 55" src="https://github.com/fjordllc/bootcamp/assets/126838748/b4fc36a3-60f9-4305-92bd-8471f755a105">
    - モーダル
    <img width="265" alt="スクリーンショット 2024-05-16 20 02 07" src="https://github.com/fjordllc/bootcamp/assets/126838748/32e66490-c079-439c-829a-685d0d8ceaf5">

2. コース一覧とコースの説明は`/courses`に記載されている内容でよろしいでしょうか？

<img width="1429" alt="スクリーンショット 2024-05-16 20 11 52" src="https://github.com/fjordllc/bootcamp/assets/126838748/4bea634f-8df8-42d8-ab6b-1f639d4c3bf2">

**Comment by komagata** [comment]
@machida こちらいかがいたしましょう。
コースは複数選択できないのでUI的にはプルダウンやラジオボタン的な感じになるのかなと思っておりました。

@nakamu-kazu222 

> コース一覧とコースの説明は/coursesに記載されている内容でよろしいでしょうか？

はい。

すみません他のところは、上記UI以外の部分を先に進めておいていただければと思います。

**Comment by nakamu-kazu222** [comment]
@komagata 

承知いたしました
コース名とコースの説明の文言は/coursesに記載されている内容で進めます

**Comment by machida** [comment]
@nakamu-kazu222 @komagata 
コースの選択はラジオボタンでお願いします。
コースの説明はフォーム内のラジオボタン周辺に表示されるようにお願いします。

他の細かいところ僕の方でやりますー

**Comment by nakamu-kazu222** [comment]
@machida 

> コースの選択はラジオボタンでお願いします。
> コースの説明はフォーム内のラジオボタン周辺に表示されるようにお願いします。

承知いたしました
念の為確認ですが、モーダル機能は実装してもよろしいでしょうか？

**Comment by komagata** [comment]
@nakamu-kazu222 @machida 

> 念の為確認ですが、モーダル機能は実装してもよろしいでしょうか？

うーん、どうしますかね、スマホでもモーダルをいい感じにするのがちょっと難しいかも？

**Comment by machida** [comment]
@komagata @nakamu-kazu222 
モーダルで大丈夫ですー
こちらでいい感じにしておきますので、デザインの細部はこだわらなくて大丈夫です。

**Comment by nakamu-kazu222** [comment]
@machida @komagata 
承知いたしました

以下の内容を実装しましたら、デザインの依頼をさせていただきます

- ラジオボタンでコースを選択して、サインアップできる
- モーダルでコースの説明を表示する
- コース一覧を押すと、すべてのコースを説明するページに遷移される
- すべてのコースを説明するページでもコースを選択できるようにする

**Comment by machida** [comment]
@nakamu-kazu222 はい！それでお願いしますー

**Comment by nakamu-kazu222** [comment]
@komagata @machida 

本番環境での動作確認を @machida さんに行なっていただいたためcloseしてもよろしいでしょうか？
- [Discordでの動作確認完了のメッセージ](https://discord.com/channels/715806612824260640/809595476847493192/1256983582740713604)

**Comment by machida** [comment]
@nakamu-kazu222 はい！こちらクローズでお願いしますー クローズしておきます！！

**Comment by nakamu-kazu222** [comment]
@machida

ありがとうございます！
ご協力いただきありがとうございました！
