### ISSUE TITLE
プラクティス > Docs一覧をVue.js化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4048]
<img width="1537" alt="貼り付けた画像_2022_02_14_17_07" src="https://user-images.githubusercontent.com/168265/153824481-94cedc3c-d4f9-4727-913b-f8439797a51d.png">

**Comment by aim2bpg** [comment]
画像はプラクティス>日報となっているが、2/21(月)にタイトル通りプラクティス>Docsで良いことを町田さんに確認済み。
https://discord.com/channels/715806612824260640/809595476847493192/945085340518084618

**Comment by aim2bpg** [comment]
本番環境での確認が取れましたのでクローズします〜
