### ISSUE TITLE
[動画] 動画ページが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4054]
## 目的

現状、FBCの動画はVimeoにアップしたものをDocsページに貼り付けて使っている。
igaigaさんの講座動画など、いい動画が埋もれがちなので、みんながしっかり動画があると分かるように個別の動画ページが欲しい。

![image](https://user-images.githubusercontent.com/16577/151177850-32f67c46-a5fb-4f88-b75e-fd2d6da9120a.png)

### 動画が持つ情報

- Vimeoの動画ID（みたいなもの）
- 説明 （Docと同じMarkdown）
- タグ
- 関連するプラクティス

#### 注

- 動画アップロード機能は付けずに、特定アカウントのVimeoの動画を表示するだけにする。
- VimeoのAPIを使って表示するので、「動画登録」はVimeoの動画ID（みたいなもの）をDBに登録するだけになると思う。

### 追加するページ

- 動画一覧ページ（/movies）
- 動画個別ページ（/movies/1234）
- 動画追加ページ（/movies/new）追加できるのは管理者のみ
- 動画追加ページ（/movies/edit）編集できるのは管理者のみ

### 動画一覧ページ

![スクリーンショット 2022-01-27 15 40 10](https://user-images.githubusercontent.com/16577/151306452-4f2e58e7-d28e-4f9a-bf5e-2b4f4164027f.png)

### 動画作成、編集ページ

![image](https://user-images.githubusercontent.com/168265/152178832-514af4ab-2a61-437b-9d80-6e14ea22c9b6.png)

**Comment by machida** [comment]
@komagata 

動画を検索しやすいように、

- 説明
- タグ
- 関連するプラクティス

の情報を持ちたいと思います。
これを踏まえてワイヤを修正してみますー

**Comment by komagata** [comment]
@machida 追記ありがとうございます。
動画タイトルや説明文はVimeoから取れそうです〜

**Comment by machida** [comment]
@komagata 

> 動画タイトルや説明文はVimeoから取れそうです〜

なるほど、

- ブートキャンプ内の検索に引っ掛けるため
- みんなが説明文やタイトルを編集しより良くできるようにするため
- Vimeo上のデータが整理されていない、typoがあるなどが受講生の使い勝手に影響されてしまうため
- ある程度立地な説明文を提供するため（Markdownでの説明文、チャプタ表など）

の理由から、動画にタイトルと説明文を持ちたいと思いますー

**Comment by komagata** [comment]
@machida 動画をアップする時の作業の手間を省くという目的もあるので、できれば二重に管理するのは避けたいな〜と思っております。
