### ISSUE TITLE
日報の不具合が再発しないようにテストを追加する

### ISSUE THREAD

**Issue by maeda-seina** [fjordllc/bootcamp#4057]
## 概要

日報作成ページでtextareaに文字を打つと、textareaの高さが自動で大きくなることが確認できるテストを追加する

こちらのissueは、

- #3969 
- #4051 

の関連issueとなります。

## 関連
- #3964
- #3825
- [🙇‍♂️ 日報編集画面で不具合が発生しています | FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/announcements/603)
- https://discord.com/channels/715806612824260640/809595476847493192/931159201223421993

**Comment by R-Tsukada** [comment]
テストが実装できたのでcloseする
