### ISSUE TITLE
[相談部屋] 管理者で入った相談部屋の一覧にページャーがほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4066]
管理者でログインし、左のナビの相談に入ると、相談部屋一覧が表示される。相談部屋は数が多いのでページャーを付ける。一覧に表示させる数は日報や提出物と同じでOK。

**Comment by machida** [comment]
@ot0m1 こちらアサインさせていただきましたー

**Comment by ot0m1** [comment]
@komagata こちら管理者でのみ確認可能なためご確認お願いいたします。

**Comment by komagata** [comment]
@ot0m1 本番環境で動作することを確認しました。

**Comment by ot0m1** [comment]
ご確認ありがとうございました。
