### ISSUE TITLE
[相談部屋] 管理者で入った相談部屋一覧にユーザーのステータスで絞り込みが出来るようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4067]
<img width="1102" alt="貼り付けた画像_2022_01_30_23_30" src="https://user-images.githubusercontent.com/168265/151703990-9190061c-6a45-441e-b589-873acba662c3.png">
↑
相談部屋一覧にこれを付けたい

細かい仕様はここのコメントでやりとりしましょう

**Comment by maeda-seina** [comment]
@komagata さん @machida さん

こちら管理者向け機能のため、本番環境での確認をお願いします。（下記三点の確認をお願いします。）

- [ ] 相談部屋一覧をユーザーのロールで絞り込めるようになっている、またVueで表示されている。
- [ ] 相談部屋の数が20以上の場合、ページャーが表示される。またページャーが機能している。
- [ ] 相談部屋一覧で「〇〇さんの相談部屋」リンクをクリックすると、その人の相談部屋詳細に遷移する。

**Comment by machida** [comment]
@maeda-seina 確認しました！クローズしますー🎉
