### ISSUE TITLE
ユーザーの検索結果に、管理者でログインしたときだけそのユーザーの相談部屋へのリンクを表示してほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4068]
Adminにだけ、これを表示して欲しい

<img width="1334" alt="貼り付けた画像_2022_01_30_23_35" src="https://user-images.githubusercontent.com/168265/151704142-7677b194-f6c1-4e6e-833e-580874f2b9f1.png">

**Comment by ot0m1** [comment]
@komagata @machida 
本件について管理者のロールのアカウントでログインいただいて、以下のご確認をお願いいたします :pray:

- 適当に検索したユーザーの検索結果（ 一例：http://localhost:3000/searchables?document_type=users&word=a ）画面で相談部屋を持っている全てのユーザーで相談部屋へのリンクが表示される

以下のように表示されることを期待しています。

<img width="706" alt="スクリーンショット 2022-03-18 13 05 51" src="https://user-images.githubusercontent.com/6190966/158935547-7f6b873d-fb23-42ea-9d04-e9ec43983b2b.png">

生徒のロールのアカウントでは期待通りに相談部屋へのリンクが表示されないことを確認しました。

<img width="706" alt="スクリーンショット 2022-03-18 13 05 51" src="https://user-images.githubusercontent.com/6190966/158935622-f32e409d-dec9-4fb3-bb88-1d2bfa3a8b2d.png">

**Comment by komagata** [comment]
@ot0m1 本番環境で動作することを確認しました。

**Comment by ot0m1** [comment]
@komagata ご確認ありがとうございました。
