### ISSUE TITLE
管理者でログインしたときだけ、ユーザー一覧のそれぞれのユーザーに相談部屋へのリンクを表示して欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4069]
<img width="915" alt="貼り付けた画像_2022_01_29_11_06" src="https://user-images.githubusercontent.com/168265/151643227-c055e846-d8c6-43c9-8cb2-aa91a10a973a.png">

こんな感じですー。

**Comment by machida** [comment]
@Paru871 こちらアサインさせていただきました！！よろしくお願いします🙏

**Comment by Paru871** [comment]
@machida 
アサインありがとうございます！かしこまりましたー✨

**Comment by Paru871** [comment]
@komagata @machida
お疲れさまです。
こちらは管理者向けの機能のため、本番環境で変更のご確認をお願いできますでしょうか。

【確認手順とチェックしていただきたいこと】
- 左側のナビゲーションバーから「ユーザー」をクリックしてユーザー一覧ページを開きます。
- それぞれのユーザーの枠内に「相談部屋」の文字と、それぞれの相談部屋へのリンクが付加されていることをご確認ください。

よろしくお願いします🙏

**Comment by machida** [comment]
@Paru871 
こちら確認しました！！
クローズしますー
ご対応ありがとうございます🎉
