### ISSUE TITLE
[相談部屋] 管理者でログインしたときだけ、相談部屋の個別ページにユーザーメモと、ユーザー公開情報、非公開情報を表示して欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4070]

**Comment by ot0m1** [comment]
日報の詳細ページなどに表示される以下の情報のこと。

![スクリーンショット 2022-02-12 19 32 53](https://user-images.githubusercontent.com/6190966/153707815-553830ea-5923-4afb-a91a-1f8d8d1cc708.png)

**Comment by ot0m1** [comment]
@machida 
お疲れさまです。こちら本番環境での動作確認をお願いいたします🙏

**Comment by ot0m1** [comment]
ご確認いただいたのでクローズ。
https://discord.com/channels/715806612824260640/809595476847493192/952877754804764702

<img width="920" alt="スクリーンショット 2022-03-14 20 26 51" src="https://user-images.githubusercontent.com/6190966/158162954-48e5f53e-4206-41d9-99c1-109c6df089f3.png">
