### ISSUE TITLE
管理者でログインしたとき、相談部屋で未返信のコメントがあったらグローバルナビに数字を表示

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4085]
<img width="112" alt="貼り付けた画像_2022_01_29_23_16" src="https://user-images.githubusercontent.com/168265/151664359-70ebfcb1-eb3f-4772-bdcd-0e60155465f3.png">

ここに未返信質問部屋数の数を表示する。

**Comment by maeda-seina** [comment]
@komagata さん @machida さん
お疲れ様です。
こちら管理者向け機能のため、本番環境でのご確認お願いします🙇‍♂️

- 相談部屋一覧（`/talks`）において、未返信のコメントがある時、グローバルナビ（相談部屋）に未返信の相談部屋数が表示されている。
-  相談部屋一覧（`/talks`）において、未返信のコメントがある時、未返信タブに未返信の相談部屋数が表示されている。

上記のご確認お願い致します🙏

**Comment by machida** [comment]
確認できました！！
クローズしますー
