### ISSUE TITLE
Slackに表示される提出物へのリンクURLがおかしくなる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#409]
[![Image from Gyazo](https://i.gyazo.com/ce1434a29e4ac3254b8cbee4df154c31.png)](https://gyazo.com/ce1434a29e4ac3254b8cbee4df154c31)

**Comment by ikaruga777** [comment]
slack APIがリンクのフォーマットをサポートしている。
https://api.slack.com/docs/message-formatting
リンクにしたい文字列に改行が入ってるので、フォーマットが崩れている。
