### ISSUE TITLE
管理者でログインしたときに、ユーザー個別ページに相談部屋へのリンクを表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4094]
管理者でログインしたとき、ユーザー個別ページにそのユーザーの相談部屋へのリンクを表示するようにしたい。

<img width="1428" alt="貼り付けた画像_2022_01_30_23_42" src="https://user-images.githubusercontent.com/168265/151704440-10b01c04-b494-473d-b418-2fd8491c09e8.png">

追加仕様

- ユーザー個別ページのユーザーが管理者だった場合は、相談部屋へのリンクは表示しない。
- ユーザー個別ページのユーザーが自分自身でかつ、メンターでない場合は、自分の相談部屋、というボタンにして表示したい。

**Comment by Saki-htr** [comment]
@machida さん

お疲れさまです☺️
仕様について、２点確認したいことがございます。お忙しいと思いますので、お手すきの際にご返信いただけますと幸いです🙇‍♀️

## 1. studentでログイン時、ユーザー個別ページに「自分の相談部屋」ボタンを表示するのか

issueのdescriptionに、
> - ユーザー個別ページのユーザーが自分自身でかつ、メンターでない場合は、自分の相談部屋、というボタンにして表示したい

とありますが、
[bootcamp/\_global\_nav\.slim](https://github.com/fjordllc/bootcamp/blob/main/app/views/application/_global_nav.slim) を確認したところ、現在、「`student`でログインすると、左の紫色のメニューに[相談]ボタンが表示され、`student`はここから自分の相談部屋に飛べる」ようになっていることが分かりました。

![スクリーンショット 2022-02-22 7 26 53](https://user-images.githubusercontent.com/58052292/155033280-9c4ed4ca-ddd9-44c8-b930-a964cf12a6d6.png)
この紫色のメニューは全ページで常に表示されるため、「`student`が自分の個別ページを見る時、 [自分の相談部屋]ボタンは不要なのではないか？」と思ったのですが、machidaさんのご見解を伺いたいです🙏

## 2. メンターには「自分の相談部屋」リンクを表示しないのか

issueのdescriptionに、
> ユーザー個別ページのユーザーが自分自身でかつ、**メンターでない場合は**、自分の相談部屋、というボタンにして表示したい。

とありますが、メンターは表示しないのでしょうか??

- メンターにも相談部屋がある
- メンターには左の紫色のメニューに[相談]ボタンが無いので、今回のissueでユーザー個別ページに[自分の相談部屋]リンクを表示しない場合、メンターが自分の相談部屋に行くには、自分の`talk_id`を調べてアドレスバーに直打ちして行くしか方法がない
- 以前、machidaさんが[私の分報](https://discord.com/channels/715806612824260640/824909262911438888/942733237439062026)で、
  > メンターだったら請求についてとか、稼働についての相談などが発生する可能性がありますね〜。

と仰っていたので、メンターも相談部屋を使うことが想定される。

上記の点から、「メンターでログインして、自分のユーザー個別ページを見た時に、[自分の相談部屋]リンクがあった方がよいのではないか」と考えました。machidaさんのご見解を伺いたいです🙏

**Comment by machida** [comment]
@Saki-htr 
質問ありがとうございます🙏ごめんなさい！表示するのは管理者に対してのみ(管理者でログインしたときのみ)でお願いしますー。確かに、それ以外のユーザーは左メニューから行くので自分のプロフィールにはリンクはいりませんでした🙇‍♂️

**Comment by Saki-htr** [comment]
@machida さん
早速ご確認くださりありがとうございます！かしこまりました。
[自分の相談部屋]リンクの実装はせず、

- 管理者でログインしたとき、ユーザー個別ページにそのユーザーの相談部屋へのリンクを表示するようにしたい。
- ユーザー個別ページのユーザーが管理者だった場合は、相談部屋へのリンクは表示しない。

を実装いたします〜

**Comment by machida** [comment]
@Saki-htr 本番で確認しました！クローズしますー🎉
