### ISSUE TITLE
GitHubの草も1年より前の分も参照できると嬉しい

### ISSUE THREAD

**Issue by kotakawase** [fjordllc/bootcamp#4100]
## 何故この機能が必要なのか
現在ダッシュボードやプロフィールに表示されるGitHubは1年分しか参照できないので、学習時間と同じようにどのくらい草を生やしたのか知れると嬉しいです。可能でしょうか？🤔

## 参考Issue
記載不要でしたらコメントお願いいたします。
Ref: #3194

**Comment by komagata** [comment]
📝 リンクを用意してGitHubサイトに飛ばしてそちらで昔の草を見てもらうようにするといいかも？

**Comment by komagata** [comment]
@kotakawase なるほど、既にリンクあるんですね〜。

僕はGetting Realを参考にしてWebサービスの開発しているのですが、Getting Realに従ってアプリのメインの機能以外の機能は極力少ない方がいいと考えています。なので僕は個人的に外部のサービスで代替できる部分については極力そちらに任せた方がいいと思います。

[Getting Real的なものとそうでないもの - komagataのブログ](https://docs.komagata.org/5741)

**Comment by kotakawase** [comment]
@komagata 
確かにおっしゃる通りだと思いました…！
GitHubのところは既にリンクが用意されているのでそちらを参照するで問題なさそうです。
改めてGetting Realを学ぶいい機会になりました。ありがとうございます🙇‍♂️

こちらのIssueはクローズするで問題ないでしょうか？
