### ISSUE TITLE
卒業後のゴールに「ファイト」と入ってしまっている。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4109]
卒業後のゴールが未入力のユーザーに「ファイト」という値が入力されてしまっている。
「ファイト」を削除し、空にしたい。

---

調査したところ、値が入ってる訳ではありませんでした！詳しくはコメントを見てくださいー

**Comment by machida** [comment]
`/app/views/users/_user_secret_attributes.html.slim` このファイルの修正をお願いします。

<img width="375" alt="貼り付けた画像_2022_02_02_15_44" src="https://user-images.githubusercontent.com/168265/152106561-995d1208-d796-4a00-8e72-db471e46d2c3.png">

`ファイト！` を `未入力` に変更お願いします。

**Comment by machida** [comment]
@garammasala29 確認しましたー

**Comment by garammasala29** [comment]
@machida さん
早速のご確認、ありがとうございます！
