### ISSUE TITLE
js-target-blank という class を削除する

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4125]
以前、`js-target-blank` というclassがついたブロックの中身のリンクは自動で target: blank になる、という機能があったのですが、その機能がなくなってしまったのに、HTMLについて `js-target-blank` という class は残ったままになっています。

`js-target-blank` で検索して、すべて削除をお願いします。

**Comment by NorifumiOgawa** [comment]
`js-target-blank` の削除が本番環境にも反映されていることを確認しました。
