### ISSUE TITLE
一度公開したお知らせはメンター・管理者以外が修正しても、WIPではなく公開したままにできるようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4127]
現在、お知らせはメンター・管理者しか公開ができません。
この仕様はこのままでいいのですが、
一度公開したお知らせをメンター・管理者以外が編集した場合、WIPの状態で保存しなくてはならず、公開をすることができません。
一度公開したお知らせは、メンター・管理者以外が編集しても、公開の状態で保存できるように変更をお願いします。

**Comment by aim2bpg** [comment]
@machida さん
> 一度公開したお知らせをメンター・管理者以外が編集

こちら、現役生の自分には編集できないようです。
「以外」のスコープをご教示いただけますでしょうかー。

![image](https://user-images.githubusercontent.com/58363353/153315307-a65c782d-1e8b-4459-b486-1e05c5ead286.png)

**Comment by aim2bpg** [comment]
@machida さんのDiscordコメントを追記しておきます。
> すいません、編集へのリンクが表示されてないことに気付きました。みんな編集していたので気づいてなかったのですが、URLを直打ちしてたっぽいです。URLを直打ちする運用はよくないので、公開されたお知らせにも編集ボタンを表示していただきたいです。この仕様も追加でお願いします🙏
> 
> 公開されたお知らせに表示する編集ボタンはほとんどの人にとっては不要なリンクなので、目立たないデザインを入れる予定です。

**Comment by aim2bpg** [comment]
シモカワのDiscordコメントを追記しておきます。
> @machida さん
編集ボタン表示の件、承知しましたー。
本Issueはプラクティスのページにある「デザインが必要な issue の進め方の流れ」に沿って進めさせていただきます。プログラムを書いたら、またご連絡いたします〜。
[デザインが必要な issue の進め方の流れ \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/pages/139)

**Comment by aim2bpg** [comment]
@machida さんのDiscordコメントを追記しておきます。
> デザイン了解です🙋‍♂️

**Comment by aim2bpg** [comment]
@machida さん
お知らせページの編集ボタンの仕様確認です。

本IssueのPRで、(一般ユーザー & 提出)の条件が追加となり、WIPかそうでないかの2条件に分かれます。
編集ボタンの方は、下記のように2種類に分けるの認識で合っていますでしょうか。

- WIP：従来ボタン
- 提出：目立たないデザイン（今回デザイン予定）

いっそうのこと、同じボタンにして、WIP/提出の分岐を入れない方がシンプルかとも思いましたがいかがでしょうか。

https://github.com/fjordllc/bootcamp/pull/2479#issuecomment-806880585 より抜粋
![image](https://user-images.githubusercontent.com/58363353/153360947-de84e297-1e40-4231-946d-b9898d6aa389.png)

**Comment by aim2bpg** [comment]
@machida さんのDiscordコメントを転記しておきます。

> 編集のリンクなのですが、大きいリンクが表示されると操作ミスが発生する可能性があるのと(お知らせには変更履歴の情報がないので戻せない)、逆になんでお知らせが自分も編集できるようになっていますがバグですか？という質問が殺到しそうなので、公開済みのお知らせのみ目立たない編集でお願いしたいです🙏

**Comment by aim2bpg** [comment]
@komagata @machida 
本番環境での動作確認をお願いいたします〜
内容は、PR: #4215 のメンター・管理者がログインするパターン1,3,5のケースです。
町田さんにデザインいただいた「内容修正」「削除する」ボタンが目立たないデザインとなっていることのご確認もお願いいたします🙇🏻‍♂️
