### ISSUE TITLE
[お試し延長 開始・終了機能] キャンペーン名を動的に表示するようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4130]
![貼り付けた画像_2022_02_03_17_40](https://user-images.githubusercontent.com/168265/152308923-3904ffba-735a-4e33-973e-d261fae9a955.png)

この部分を管理者画面のお試し延長で設定した現在開催されているキャンペーンのタイトルを表示したい。

![貼り付けた画像_2022_02_03_17_41](https://user-images.githubusercontent.com/168265/152309037-8c4998de-1619-40d3-b0af-7874d49af3f8.png)

**Comment by ot0m1** [comment]
@komagata @machida 
キャンペーン名が動的に反映されるかのご確認をお願いいたします。
もしくは実際にキャンペーンが実施されるまで確認できないため、このissueをクローズしてよいかのご判断をお願いします 🙏 :

**Comment by komagata** [comment]
@ot0m1 (CC: @machida )今後実際にキャンペーンを近々やるのでその時に確認したいと思います。
IssueとしてはOPENさせたままでお願いします。@ot0m1さんの作業としては完了で大丈夫です〜！

**Comment by ot0m1** [comment]
@komagata かしこまりました〜！ では引き続きご確認お願いいたします🙏

**Comment by komagata** [comment]
@ot0m1 本番環境で動作することを確認しました。
