### ISSUE TITLE
一般ユーザーで、未入力がない場合にも、未入力の項目のブロックが表示されてしまっている。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4135]
![image](https://user-images.githubusercontent.com/168265/152470719-56b8869c-f528-4c29-bc17-5ea5f8d2ef3c.png)

特定の項目が未入力のときに項目を埋めてくださいのメッセージが表示されるようになっているのだけど、全部埋まってても出ているっぽいです。こちら、動作を確認し、不具合を見つけ、修正をお願いします。不明点や仕様の確認が必要になりましたらコメントやチャットでどんどん質問お願いしますー

**Comment by tksmasaki** [comment]
## バグの原因

- 未入力項目のバリデーション対象となっているもの
⇒ [自己紹介文、GitHubアカウント、Discordアカウント、アバターアイコン、タグ登録]
- [Pull request #3778](https://github.com/fjordllc/bootcamp/pull/3778) での、[卒業後のゴールのデザイン、出し分けの設定](https://github.com/fjordllc/bootcamp/pull/3778/commits/7a95e4c6d86c29af08d45ded5c8ff3b188c40935#diff-fe59f7d4db37f4fc1fde0caf7e8e3693305160fc42e6249aa121d97bbd11d861) のコミットで「タグ登録してください」 のエラーメッセージが削除されていた
- そのため、タグが登録されているかのバリデーションは残っているが、バリデーションのメッセージは表示されない状態になっているため、未入力項目ブロックがメッセージなしで表示されてしまっている
=> タグ登録以外が完了している場合に、メッセージなしで未入力項目

### 質問、確認したいこと

- タグの登録がない場合のメッセージを表示するように戻すか？（タグの登録はバリデーションの対象として残すか？）
- 「フィヨルドブートキャンプを卒業した自分はどうなっていたいか」をバリデーション対象として加えるか？
    - 現状ではこの項目が未入力でも、他の項目が入力されていれば未入力項目ブロックはでない

### Issueのスコープ外かもしれないが、修正したい点

- `_required_fields.html.slim`（未入力項目ブロック）の表示までの処理のリファクタリング
    - 表示の際の条件式を、`@required_fields.valid? && current_user.avatar.attached? && !current_user.tag_list.empty?` としているが、`@required_fields.valid?` だけで済むように `RequiredField` クラスの属性を追加する
    - 自己紹介文も表示のための条件となっているが、そもそもサインアップや登録情報変更時の必須項目であり、ここで検査する必要がないため対象から除外する
    （`RequiredField`クラスはここ以外で使用されていないため、他に影響はでない）

**Comment by tksmasaki** [comment]
## 修正方針の決定
- 未入力項目のバリデーション対象とするもの
⇒ [GitHubアカウント、Discordアカウント、アバターアイコン、タグ登録、卒業した自分はどうなっていたいか]
- 表示されなくなっていた「タグを登録してください」 のエラーメッセージも表示するように戻す

**Comment by tksmasaki** [comment]
## 仕様変更
https://github.com/fjordllc/bootcamp/pull/4300#issuecomment-1060218725
> ## 催促したいもの。
> * アバターアイコン
> * タグ登録
> * 卒業した自分はどうなっていたいか
> * Discordアカウント
> * GitHubアカウント
> * ブログURL

**Comment by tksmasaki** [comment]
本番環境での動作確認が完了したため、Close します。
