### ISSUE TITLE
通知ベルにローディング用プレースフォルダが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4137]
<img width="229" alt="貼り付けた画像_2022_02_16_19_32" src="https://user-images.githubusercontent.com/168265/154246790-047590ce-5bcb-4080-a8e6-b7904ff16e93.png">

**Comment by machida** [comment]
@Aseiide 
ぐるぐるを出すのはmachidaがやるので、仮の何かを表示しておいてくださいー

**Comment by Aseiide** [comment]
本番環境での動作確認ができたのでcloseします！
