### ISSUE TITLE
ユーザー情報変更ページで、管理者の場合はコース変更ができるようにしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4138]
現状はDBを直接変更する必要があるので管理者が画面からプルダウンを選んで変更できるようにしたい。

**Comment by Saki-htr** [comment]
@machida さん
お疲れ様です! 仕様について一点質問させていただきたいです🙏 お手すきの際にご回答いただけますと幸いです〜。

## プロフィール画面に非公開のコースが表示されても良いのか
管理者でログイン時、ユーザー情報変更ページでコース変更ができるように、実装いたました。
今のコードですと、ユーザー個別ページのプロフィールにコース名が表示されるのですが、こちら、**非公開のコースがプロフィールに表示されていてもよろしいのでしょうか**。現在本番環境で作成されているコースは全て非公開のため、ユーザー個別ページのプロフィールに表示されていても良いものなのか、気になりました。

以下の画像は、私が手動で作成した非公開の企業研修用コースを選択した場合の画面です。

- 管理者でログインした時の画面
![スクリーンショット 2022-04-09 18 14 38](https://user-images.githubusercontent.com/58052292/162565231-378af0bb-4201-46b3-a66f-c97b865f2b14.png)

- 受講生 kimura でログインした時の画面
![スクリーンショット 2022-04-09 18 17 23](https://user-images.githubusercontent.com/58052292/162565249-07edd7b7-4905-4966-86a0-0df5fa6de4bc.png)

machidaさんのご見解を伺いたいです。宜しくお願いいたします🙏

**Comment by machida** [comment]
@Saki-htr すいません、確認が遅くなりました🙇‍♂️
こちら表示されてOKですー！
非表示のコースがなぜ非表示かというと、企業のために作られたコースなので、隠したいのではなく、将来的に受講者が自分でコースを選択できるようになったときに、選択ができないようにという目的になりますー。一覧でも非表示のコースがあるのは、見えても選択できないから詳細は非表示している、という理由です。

**Comment by Saki-htr** [comment]
@machida 
ご回答くださり、ありがとうございます🙇‍♀️✨
> こちら表示されてOKですー！

かしこまりました!

> 非表示のコースがなぜ非表示かというと、企業のために作られたコースなので、隠したいのではなく、将来的に受講者が自分でコースを選択できるようになったときに、選択ができないようにという目的になりますー。

非表示になっていた理由が分かりました! ありがとうございます🙏

**Comment by Saki-htr** [comment]
こちら、komagataさんに本番環境の動作確認が問題ないことを確認していただきましたので、closeいたします。
