### ISSUE TITLE
FAQのQマークがずれている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4142]
<img width="695" alt="スクリーンショット 2022-02-05 16 53 26" src="https://user-images.githubusercontent.com/16577/152633598-546ecb3f-40d9-4808-8a60-d9f29be684e8.png">

**Comment by machida** [comment]
ここの値をこのように変更すると直ります。
<img width="173" alt="貼り付けた画像_2022_02_07_2_46" src="https://user-images.githubusercontent.com/168265/152693930-8d81aa05-2ac2-432a-a32c-85189d84987a.png">

**Comment by aim2bpg** [comment]
@machida 

> ここの値をこのように変更すると直ります。

アドバイスありがとうございます😊
やってみます💪

**Comment by aim2bpg** [comment]
本番での動作確認完了しましたので、クローズしました👍
