### ISSUE TITLE
使われていないgemや更新すべきgemがあるので、Gemfileを更新したい

### ISSUE THREAD

**Issue by Aseiide** [fjordllc/bootcamp#4149]
## 概要

- Gemfileが古い可能性があります
- 少なくともRails6.1.4.4において、`gem 'spring-watcher-listen'`ではなく`gem 'listen'` を使うようになっているようです([RailsDiff参考](https://railsdiff.org/6.0.4/6.1.4.4))
  - ブートキャンプアプリでは、`gem 'spring-watcher-listen'` がバージョンストッパーになっていて`gem 'spring'`のバージョンが古い
- RailsDiffやRails6.1.4.4でrails newなどをして、Gemfileのデフォルトの状態にgemの種類やバージョンを合わせることが必要かと思われます。

## 関連・参照

- [こちらのQ&A](https://bootcamp.fjord.jp/questions/1168)の中で伊藤さんがコメントしておられます。
- Q&A内にある動画の13:00以降がこの話に該当します

**Comment by komagata** [comment]
@Aseiide 具体的なgemを書いていただけるとありがたいです〜

**Comment by Aseiide** [comment]
@komagata 
了解です。まだ調べ切れてないので調査したら追記して連絡します

**Comment by JunichiIto** [comment]
https://github.com/fjordllc/bootcamp/pull/4182 ではすでに綺麗になってるかも？（詳細未調査）
CC @ima1zumi

**Comment by ima1zumi** [comment]
listen, spring は　https://github.com/fjordllc/bootcamp/pull/4180 で対応済みと思います〜

**Comment by Aseiide** [comment]
@ima1zumi @JunichiIto @komagata 
なるほど、見逃していました。対応ありがとうございます！
本issueは閉じて良いですかね?

**Comment by JunichiIto** [comment]
@Aseiide 念のため、他のgem（listen以外のgem）はどうなってるのか確認してもらってからcloseした方がいいかな〜と思います。

**Comment by Aseiide** [comment]
@JunichiIto 
承知しました。できるだけ早く調査して確認します！

**Comment by Aseiide** [comment]
@JunichiIto @ima1zumi 
自分でRailsDiff見たり、`rails new`したりしたところ、#4180 で対応できていそうなのでcloseします！
わからないことや聞きたいことがあったらそちらの方でコメントしたいと思います。
