### ISSUE TITLE
ユーザー個別ページにある管理者しか見えない相談部屋へのリンクの位置の変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4155]
<img width="2010" alt="貼り付けた画像_2022_03_30_23_42" src="https://user-images.githubusercontent.com/168265/160862135-5c9fbad1-31aa-4a57-90b0-9a8f1193b524.png">

右上は見逃しやすいので、タブに移動。

**Comment by tksmasaki** [comment]
@machida 
お疲れさまです。
以下の Issue でユーザー個別ページに相談部屋へのリンクが作成されると、タブは不要になるのではないかと思いました。

- #4094

相談部屋のタブの作成をした方がよいか、確認よろしくお願いします🙏

**Comment by machida** [comment]
@tksmasaki すいません、Issueを重複させてしまってました。
一旦、前のものがマージされたら、使い勝手を見て、目立つページタイトル横ではなくタブに移動しても良さそうだったら、こちらのIssueをやる、という進め方にしたいと思います。
なので、こちらはアサインを外させていただきます🙇‍♂️
