### ISSUE TITLE
「お正月のプログラミング学習応援キャンペーン」の表示が表示されっぱなしになっている

### ISSUE THREAD

**Issue by unstoppa61e** [fjordllc/bootcamp#4159]
## 修正すべきこと
当該キャンペーンの表示をとりやめる

## 概要
当該キャンペーンの期間は１月４日までであったが、２月７日現在、なおキャンペーンのお知らせが表示されっぱなしになってしまっている。

## 修正すべき理由
キャンペーン期間終了後の未入会者がこの表示を見ることで、タイミングを逃して損をしたという気持ちを起こしてしまうかもしれません。
また、期間が大幅に過ぎても表示を放置してあることで、「このスクールは大丈夫なのだろうか」とスクールに対する信用を損ねかねないとも思います。

**Comment by machida** [comment]
@unstoppa61e 
おおーマジだ！！
ありがとうございます🙏
