### ISSUE TITLE
期間限定キャンペーンの終了後、キャンペーン告知を表示させないような仕組みを作る

### ISSUE THREAD

**Issue by unstoppa61e** [fjordllc/bootcamp#4160]
## 機能の説明
ゴールデンウィークや年末年始などに実施されている、お試し期間延長キャンペーンの対象期間が終了後、その告知を表示させないような仕組みを作る。
具体的には、以下のような方法が考えられる。
- キャンペーン終了後には表示されないようなプログラムにしておく
- キャンペーン終了後、告知が表示されっぱなしになっている場合には、その旨をメンターに対して常に通知するような機能を作る

## 何故この機能が必要なのか
今年のお正月キャンペーンの期間は１月４日までだったが、２月７日現在もなおその告知が表示され続けているという事態が発生してしまっている。
未入会者にとって、キャンペーン期間終了後にこの告知を目にすることは、ネガティブキャンペーンに他ならない。
また、この画面は未ログイン状態でしか表示されず、普段目にする機会が少ない画面なので、修正をする必要があるという意識も抜けがちである。
今後同様の事態が発生するのを防ぐため、また、放置していた人が責められたりしないためにも、仕組み化によって対処しておくことが重要だと考える。

**Comment by machida** [comment]
こちら
https://github.com/fjordllc/bootcamp/issues/3910
もうすぐリリースされる予定です
なので、こちらのIssueはクローズにさせていただきますー

**Comment by unstoppa61e** [comment]
@machida 
既に issue があったのですね…！
失礼致しました。
お知らせ、ありがとうございました🙏
