### ISSUE TITLE
日報が公開されたらDiscordの専用チャンネルに通知する

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4161]
https://discord.com/channels/715806612824260640/823739924615790622/938959818729848844 で話していた、サイドバーから日報が表示されなくなった件の代替案です。

Bootcampアプリ内に専用ページを作る、という方法もあるかもしれませんが、「自分から読みに行かないと気づけない情報」よりも、「勝手に目に飛び込んでくる情報」である方が個人的には嬉しいです。（プル型 vs プッシュ型）

なので、Discordに日報通知チャンネルみたいなものを作って、日報が公開されたらそこに通知が飛ぶ（＝かつてのサイドバーの役割をDiscordが受け持つ）ようにしたらいいんじゃないかな〜と思いました。
これであればDiscordの未読チェック機能を使うときに気づけそうです。

<img width="578" alt="Screen Shot 2022-02-07 at 8 32 28" src="https://user-images.githubusercontent.com/1148320/152706306-a6765aaa-cb5b-4425-9be8-e986bd918f45.png">

また、他の人の日報を見たくない人はチャンネルをミュートにすれば無視することができます。

<img width="479" alt="Screen Shot 2022-02-07 at 8 34 34" src="https://user-images.githubusercontent.com/1148320/152706371-6b9526c6-72a2-4b38-b747-e819981a9836.png">

**Comment by aim2bpg** [comment]
@komagata @machida @JunichiIto 
本件、フォーマットでご希望がありましたら、お聞かせください🙏

文字入れ
\--------------------------------------------------
◯◯さんが◯日目の日報を公開しました。
タイトル：今日は頑張った
URL：https://bootcamp.fjord.jp/reports/xxxxxxxx
\--------------------------------------------------

イメージ画像
![image](https://user-images.githubusercontent.com/58363353/156189114-cffd0972-a1d4-4a68-8326-4c15c8ba357c.png)

**Comment by komagata** [comment]
@aim2bpg こちらでいいと思います〜

**Comment by aim2bpg** [comment]
@komagata @machida ご確認ありがとうございます🙇🏻‍♂️
では、日報の日付を入れた、こちらで進めさせていただきます〜
![image](https://user-images.githubusercontent.com/58363353/156273963-64501176-6f1f-44e2-8d9c-325806d02bf0.png)

**Comment by aim2bpg** [comment]
@haruguchi-yuma さんの日報が通知されたことをもって確認できましたのでクローズいたします〜
