### ISSUE TITLE
卒業をしていても就職希望者には就職希望者のみのお知らせ通知が飛ぶようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4169]
## 機能の説明

卒業をしていても就職希望者には就職希望者のみのお知らせ通知が飛ぶようにしたい。
現在は現役生でかつ就職希望者にしか飛ばない。

## 何故この機能が必要なのか

卒業と就職のタイミングはバラバラなので、卒業後に就職情報が必要な人もいる。

**Comment by machida** [comment]
@kaisumi 
こちら、直近のお知らせが卒業生から飛んでないという報告があって立てたIssueなのですが、お知らせを今確認したところ、就職希望者に通知ではなく、現役生だけに通知に✓が入ってました。
なので、このIssueの問題は起こっていない可能性があります。その可能性を含めて調査をお願いします🙏
あと、テストがなかったらテストも追加いただきたいです🙏

**Comment by kaisumi** [comment]
スコープを見てみました。就職希望者は現役生から絞られているようなので、最初におっしゃっていたように、現状では現役生かつ就職希望者にしか通知が飛んでいないようです。
https://github.com/fjordllc/bootcamp/blob/83d7d8073153f1c0d873b6f80510bd0683eba2fd/app/models/user.rb#L218-L227
https://github.com/fjordllc/bootcamp/blob/83d7d8073153f1c0d873b6f80510bd0683eba2fd/app/models/user.rb#L259-L263

テストも、「卒業生かつ就職希望者」はテストされていないようでした。
https://github.com/fjordllc/bootcamp/blob/83d7d8073153f1c0d873b6f80510bd0683eba2fd/app/models/user.rb#L259-L263

就職希望者のスコープに、卒業生の就職希望者を含めるように修正し、卒業生かつ就職希望者のユーザーがいなければ追加してテストを追加しようと思います。

**Comment by machida** [comment]
動作確認ができたのでクローズしますー🎉
