### ISSUE TITLE
経過日数計算の起点になる投稿日の更新に提出→WIP→提出の場合が考慮されていない

### ISSUE THREAD

**Issue by kaisumi** [fjordllc/bootcamp#4172]
## 概要
メンター機能として、提出後5日、6日、7日以上過ぎた提出物をまとめて見るページがある。
受講生がある提出物について、提出→WIPに戻す→提出の操作を行うと、タイミングによっては急に7日以上過ぎた提出物が現れることになる。
- https://github.com/fjordllc/bootcamp/pull/4136#issuecomment-1032113856

## 再現手順
提出した後に6日超えた提出物を WIP に戻し、その後に再提出しても6日超えたままになっている。

1. （受講生が）操作を誤って提出してしまった
1. （受講生が）WIP に戻した
1. （受講生が）その7日後、完成した提出物を提出した（WIP ではない状態にした）
1. （メンターが）メンター向けの提出物一覧画面を見ると、期限の7日を超えた提出物がいきなり現れた

## 検討事項

提出後にWIPに戻した後にもpublished_atが更新されるようにする必要があるかどうか、検討する必要がある。
https://github.com/fjordllc/bootcamp/blob/425a72c928e8d921957e3e11f733544723a0cc75/app/models/product_callbacks.rb#L20-L40

## スクリーンショット

https://user-images.githubusercontent.com/15713392/152898900-b38f2f19-4fff-4e2a-bd08-12bfb1e515a1.mov

**Comment by komagata** [comment]
@kaisumi なるほどですね〜。
気付きずらいバグをIssueにしてくださってありがとうございます〜！

**Comment by machida** [comment]
こちら、WIP に戻してから公開した場合は、published_at が更新されるようにし、n日経過の表示も、更新された published_at  に従うようにしたいと思います。

**Comment by kaisumi** [comment]
@machida 
アサインありがとうございます！
この件、published_atを更新するcallbackでは、他に、メンターに通知したり、アドバイザーに通知したりしているようです。これらも全て実行するようにしますか？
https://github.com/fjordllc/bootcamp/blob/425a72c928e8d921957e3e11f733544723a0cc75/app/models/product_callbacks.rb#L20-L40

**Comment by machida** [comment]
@kaisumi なるほど、こちらもご対応お願いします🙏

**Comment by kaisumi** [comment]
@komagata @machida お疲れ様です！こちらメンター機能のため、ご都合の良い時に本番環境での確認をお願いします 🙏

**Comment by kaisumi** [comment]
本番環境で確認していただいたのでクローズします 😄 
https://discord.com/channels/715806612824260640/809595476847493192/957964931360231494
