### ISSUE TITLE
[お試し延長 開始・終了機能]お試し期間日数をデータとして持ち、現在のキャンペーンのデータから動的に表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4183]
# 管理画面

## 作成、編集

<img width="745" alt="貼り付けた画像_2022_02_10_13_38" src="https://user-images.githubusercontent.com/168265/153338259-445ebae9-edca-4848-a89c-d73cdd922785.png">

## 一覧

<img width="955" alt="貼り付けた画像_2022_02_10_13_40" src="https://user-images.githubusercontent.com/168265/153338334-7e59ae04-7461-4130-b553-dc9a9a4262fc.png">

## 表側

<img width="766" alt="貼り付けた画像_2022_02_10_13_41" src="https://user-images.githubusercontent.com/168265/153338518-83ebef7e-7525-46fc-8a9e-efbee7819a05.png">

**Comment by aim2bpg** [comment]
@machida さん、2点ご質問です🙏
1. 作成、編集画面に表示するお試し期間のフォーム右横に「日」を表示させるとのことですが、実現方法を調べてみましたが、分かりませんでした😅　ご教示いただけますでしょうか。
2. お試し延長期間の入力値は4日以上14日未満で入力値制限かけようかと思いますが、ご希望の範囲はありますでしょうか。

**Comment by machida** [comment]
> 作成、編集画面に表示するお試し期間のフォーム右横に「日」を表示させるとのことですが、実現方法を調べてみましたが、分かりませんでした😅　ご教示いただけますでしょうか。

「日」を表示だけしておいていただけたら、レイアウトが僕の方でやりますー

> お試し延長期間の入力値は4日以上14日以下で入力値制限かけようかと思いますが、ご希望の範囲はありますでしょうか。

4日以上 はあるといいですが、n日以下の入力値制限はなくて大丈夫ですー

**Comment by aim2bpg** [comment]
@komagata @machida 
こちらのIssueはステージング環境まで動作確認を完了しております。
本番環境では管理者しか確認できないため、リリース後、実際にキャンペーンを開始される際に動作確認をお願いいたします🙏

**Comment by komagata** [comment]
@aim2bpg 作業ありがとうございます。
こちらは実際にキャンペーンをやったときに確認しますので @aim2bpg さんの作業としては完了で大丈夫です〜

**Comment by aim2bpg** [comment]
@komagata さん、ご連絡ありがとうございます。

> こちらは実際にキャンペーンをやったときに確認しますので @aim2bpg さんの作業としては完了で大丈夫です〜

承知しました🙇🏻‍♂️

**Comment by komagata** [comment]
@aim2bpg 本番環境で動作することを確認しました。

**Comment by aim2bpg** [comment]
@komagata さん、ご確認ありがとうございました🙇🏻‍♂️
こちらでも、本番環境に反映されていることを確認いたしましたー🎉🎉🎉
仕様検討・レビュー時にご協力いただきました@machida さん、@napple29 さんにも御礼申し上げます🙏
