### ISSUE TITLE
[相談部屋] 相談部屋個別ページに一覧に戻るリンクを管理者にだけ表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4187]
管理者にだけ表示する。

<img width="1224" alt="貼り付けた画像_2022_02_09_15_14" src="https://user-images.githubusercontent.com/168265/153133540-b8d294b7-5cb9-404e-93be-bf4e03594938.png">

**Comment by tomonariha** [comment]
@komagata さん @machida さん
相談部屋個別ページの「相談部屋一覧」リンクですが、管理者限定ですので本番環境での動作確認をお願いします🙏

**Comment by tomonariha** [comment]
@machida さんに動作確認して頂いたので、closeします。
