### ISSUE TITLE
[お試し延長]管理ページのお試し延長タブのコンテンツ全てのタイトルを管理ページに変更する

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4197]
<img width="1059" alt="貼り付けた画像_2022_02_10_14_53" src="https://user-images.githubusercontent.com/168265/153346520-5263d849-c045-4025-b966-7cac87f30ded.png">

index, new, edit 全てタイトルを上記のように変更。

**Comment by clio209** [comment]
確認いただいたのでcloseします。
