### ISSUE TITLE
日報のコメントの投稿日時をクリックするとコメントURLがコピーされる機能のテストが落ちる

### ISSUE THREAD

**Issue by kaisumi** [fjordllc/bootcamp#4201]
## 概要
テストで不合格が出るが、実際の開発環境ではクリップボードにコピーされた内容の末尾に空白は追加されていない。

![image](https://user-images.githubusercontent.com/39044468/153394132-c085976d-b496-46c3-80ee-58dc5f9fcbbf.png)

````
Failure:
CommentsTest#test_comment_url_is_copied_when_click_its_updated_time [/home/runner/work/bootcamp/bootcamp/test/system/comments_test.rb:245]:
--- expected
+++ actual
@@ -1 +1 @@
-"http://127.0.0.1:44295/reports/701335546?_login_name=komagata#comment_122467993"
+"http://127.0.0.1:44295/reports/701335546?_login_name=komagata#comment_122467993"
````

https://user-images.githubusercontent.com/39044468/153395623-1fda6e32-0c9b-4cf6-88e6-cbea3640e7b6.mov
## 該当のテストコード
https://github.com/fjordllc/bootcamp/blob/83d7d8073153f1c0d873b6f80510bd0683eba2fd/test/system/comments_test.rb#L236-L246

**Comment by komagata** [comment]
@kaisumi 空白ではなくて、改行コードなどの何かのコードが入っている気がします。

**Comment by kaisumi** [comment]
対策したPRが埋もれてしまったので以下に記載します：
- https://github.com/fjordllc/bootcamp/pull/4203

**Comment by kaisumi** [comment]
develop環境のみが関与するテストの修正です。マージ後テストOKによりクローズします。
