### ISSUE TITLE
【メンター向け】メンターモードがOFFでもメンター向けメモが表示される

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4218]
プラクティスのページでメンターモードをOFFにしてもメンター向けメモ（と、管理者・メンター用メニュー）が表示されています。
これは非表示にした方が良さそうです。

例 https://bootcamp.fjord.jp/practices/194

<img width="848" alt="Screen Shot 2022-02-14 at 9 47 24" src="https://user-images.githubusercontent.com/1148320/153783382-b5877a01-ee1d-420c-acfa-126f4a0d4df2.png">

**Comment by machida** [comment]
@clio209 

メンターでログイン、プラクティスの個別ページ。

![image](https://user-images.githubusercontent.com/168265/153826482-b8c20bce-d035-4b5b-8e8f-d696ef075b07.png)

これと、

![image](https://user-images.githubusercontent.com/168265/153826737-d3b3e8b4-c691-4a30-b760-dfe251d0af22.png)

これに `.is-only-mentor` を付けてください🙏

付けたあと、

![image](https://user-images.githubusercontent.com/168265/153826822-bf592a4b-18b1-46f4-ab36-f2ad141544ac.png)

これを切り替えて非表示になるか確認をお願いします🙏
