### ISSUE TITLE
Markdownの中で独自記法でメッセージブロックを書けるようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4225]
## メッセージブロック

Markdownのエディタの中で、

```
:::message
メッセージ
:::
```

このように書くと、

```
<div class="msg">
<p>メッセージ</p>
</div>
```

このような HTML が出力されるようにしたい。

---

## メッセージブロックのバリエーション

このバリエーションで、

```
:::message alert
警告メッセージ
:::
```

このように書くと、

```
<div class="msg alert">
<p>警告メッセージ</p>
</div>
```

と出力されるようにしたい。

---

## メッセージブロックのバリエーション2

```
:::message info
メッセージ
:::
```

このように書くと、

```
<div class="msg info">
    <p>メッセージ</p>
</div>
```

と出力されるようにしたい。

---

## ポイント

メッセージブロックの中はMarkdown記法が使えるようにする。

```
:::message
### 見出し

ああああああああああああああ

- あああああ
- あああああ
:::
```

```
<div class="msg">
<h3>見出し</h3>
<p>ああああああああああああああ</p>
<ul>
<li>あああああ</li>
<li>あああああ</li>
</ul>
</div>
```

---

## 仕様のまとめ

-  `:::文字列` と `:::`  があると、`<div class="文字列">` 、`</div>` で囲われる。
- `:::文字列` と `:::` の間には Markdown 記法が使える。
- `:::文字列 文字列` とあった場合は、div に複数 class が付く。`<div class="文字列 文字列">`

**Comment by eatplaynap** [comment]
@machida 
お疲れさまです。こちらの仕様について確認したい件が1点あるので、下記ご回答お願いいたします:pray:

> `:::文字列` と `:::` があると、`<div class="文字列">` 、`</div>` で囲われる。

と仕様のまとめにはありますが、具体例の方では`message`→`msg`への変換も含まれているようです。

![Markdownの中で独自記法でメッセージブロックを書けるようにしたい_·_Issue__4225_·_fjordllc_bootcamp](https://user-images.githubusercontent.com/63531341/157379133-b4192e00-92e6-4da1-8176-4f27aefd98cb.png)

`:::文字列`の文字列をそのままclass属性に渡すのではなく、この変換にも対応する必要があるのかご教示ください:pray:

**Comment by machida** [comment]
@eatplaynap
こちら、フィヨルドブートキャンプでは、

`:::文字列` の文字列がそのまま class名になる、
という仕様で願いします🙏

（message → msg の変換は無し）

**Comment by eatplaynap** [comment]
@machida
本日の開発ミーティングでこちらのIssueの仕様変更を承諾いただいた件について、下記で認識があっているかどうかご確認お願いします🙏

変更前: `:::文字列` と `:::` があると、`<div class="文字列">` 、`</div>` で囲われる
変更後: `:::message` と `:::` があると、`<div class="message">` 、`</div>` で囲われる

**Comment by eatplaynap** [comment]
町田さんからDiscordで下記返答をいただいたので↑については確認済みです。
> はい！それで合ってますー🙆‍♂️
divのclass名は決め打ちでお願いします。今後、warningやinfoなどを追加していく予定です。

https://discord.com/channels/715806612824260640/809595476847493192/953572167046529095

**Comment by eatplaynap** [comment]
@machida
クラス名を`message`のみの決め打ちで実装したところ、レビュワーの@garammasala29さんが`message`のあとに自由に文字列を入力できる方法をご教示くださったため、そのように修正しました！
参考: https://github.com/fjordllc/bootcamp/pull/4424#discussion_r829931214

この変更により、下記のようにクラス名を指定することが可能になりました。
- `:::message`と`:::` → `<div class="message">` と`</div>` 
- `:::message warning`と`:::` → `<div class="message warning">` と`</div>` 
- `:::message hoge`と`:::` → `<div class="message hoge">` と`</div>` 
- `:::message hoge fuga piyo`と`:::` → `<div class="message hoge fuga piyo">` と`</div>` 

※`message`以外で始まるクラス名は指定できません。別の名前で始まるクラスを作りたい場合は、また別途markdown-it-containerを使用した別のコンテナを作る必要があります😄

**Comment by eatplaynap** [comment]
本番環境で動作確認できたのでcloseします〜！
