### ISSUE TITLE
Storybookを導入したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4236]
今あるReactのコンポーネントが見れる状態にする。

使えるようにして、サンプルで一つコンポーネントが見れるようになってればいい。

**Comment by dowdiness** [comment]
@komagata 
このIssueをやる中でいくつか問題が出てきたので質問させてください。

## FontAwesomeが使用できない

現在の設定ではFontAwesomeを使っているコンポーネントではアイコンが表示されません。Railsとは違うポート番号でStoryBookを動かしているからですが、設定を工夫することでStoryBook上でもアイコンを表示させれるのかどうか、もし不可能なのならこのままでもいいのか知りたいです。

## Mock Service Workerの必要性について

現在FjordのReactコンポーネントにはApiとの通信のあるコンポーネントが多くありStoryBookで扱うためにはそのApi通信部分をどのように扱うか考える必要があります。解決方法としてはMock Service Workerというアドオンを入れればApi通信をモックすることが出来るのですが本当に入れる必要があるのかどうか悩んでいます。
というのも現在の作り方ではApiからデータを取得する部分と見た目を構築する部分が同じコンポーネント内にありますが、Api部分と見た目部分を分離して違うコンポーネントに分けるように実装して、その見た目を担当するコンポーネントだけにStoryBookのStoryを作るようにしたほうが良いコンポーネントの作り方、StoryBookの使い方になると思うからです。
この問題についてどのように考えるか知りたいです。
https://storybook.js.org/addons/msw-storybook-addon

**Comment by komagata** [comment]
:memo: FontAwesomeについては @machida さんが調べるとのこと

**Comment by machida** [comment]
@dowdiness 

> FontAwesomeが使用できない

一旦これはそのままで進めてくださいー🙏
同時にどうにかできないか調査進めます
