### ISSUE TITLE
[fixture] docsのseedデータに関連プラクティス、タグを持っているものがない

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4240]
docsのseedデータに関連プラクティス、タグを持っているものがないので、今 fixtures に入っているデータに、関連プラクティスとタグを持たせる。

**Comment by machida** [comment]
このIssueはステージングでの確認ができないので、マージしたらクローズ。

**Comment by aim2bpg** [comment]
@machida さん、2点ご教示ください。

> docsのseedデータに関連プラクティス、タグを持っているものがない

1. これがないと何が困るのかが読み取れませんでした。
おそらく、動作確認時のデモデータとしてあったら良いものかと想像しましたが、合っていますでしょうか？

2. seedデータとは、`db/fixtures/pages.yml`のことで、`test/fixtures/pages.yml`の方はテスト用で本Issueの対象外だという認識であっていますでしょうか？

**Comment by aim2bpg** [comment]
町田さんのDiscordでの回答を転記しておきます。

> データがないのでタグ周りのデザインの確認ができないという問題が起きてます。
> 
> 一つの例としてデザインが確認できないという問題がありますが、機能があるのにデータがないことでその機能の存在がコードを見るか本番環境を見ないと知ることができないことによる弊害は色々あります。フィヨルドブートキャンプは利用者が開発しているという特殊なアプリなのですが、例えば特定の会社でしか使わない業務アプリの開発を請け負った場合は本番環境が見れないという場合もあります。

**Comment by aim2bpg** [comment]
こちらのIssue、ステージング環境まで確認できましたのでクローズしますー
