### ISSUE TITLE
日報のafter_save内でsaveされていて循環の危険あり

### ISSUE THREAD

**Issue by kaisumi** [fjordllc/bootcamp#4241]
## 概要
日報のコールバック`after_save`内で`save!`が使用されており、循環の危険があります。
https://github.com/fjordllc/bootcamp/blob/a00f769ac4d7fd064b854319c13b1cda49dab973/app/models/report_callbacks.rb#L4-L15

## 再現手順
5行目または9行目が無くなると循環して戻ってこなくなってしまうと思われます。

## 関連PR
以下のPRで似たような記述を修正したので参考になるかもしれません。
- https://github.com/fjordllc/bootcamp/pull/4238

**Comment by aim2bpg** [comment]
ステージング以降の確認ができない案件のため、クローズします。
