### ISSUE TITLE
【メンター向け機能】sadの日報の時に出てくるポップアップに対してキャンセルを押してるのにコメントが投稿されてしまう

### ISSUE THREAD

**Issue by Aseiide** [fjordllc/bootcamp#4244]
## 概要

https://user-images.githubusercontent.com/45246171/154417148-416814e5-8596-4c56-a348-ef4f43574645.mov

sadの日報のときに、コメントを付けて「確認OKにする」ボタンを押す。
すると、ポップアップが出てきますが、そのポップアップに対してキャンセルをしてもコメントが投稿されてしまう

## 再現手順

1. sadの日報にアクセス
2. メンターでログインし、コメント欄にコメントをつける
3. 「確認OKにする」ボタンをクリック
4. ポップアップが出てくるので、キャンセルをクリック
5. 日報の確認はしないが、コメントがついた状態になっている

## 期待される振る舞い

5の段階で、確認もしないし **コメントも無し** のほうが直感的かなと思いました。
今はキャンセルを押してるのにコメントは投稿されてしまっています。

#4239 の作業をしている時に気づいた挙動です。
現況で正しく動作しているのか、メンターにしかわからないので @komagata  @machida にご意見を伺いたいです。
現況で正常、ということであればcloseしていただいて大丈夫です。

## 関連Issue・PR

issue: #3941
PR: #4239

**Comment by komagata** [comment]
@Aseiide こちらステージング環境ではどうなりますか？そちらを確認していただければありがたいです〜。

**Comment by Aseiide** [comment]
@komagata 
ステージング環境で確認しました。ステージング環境でも同様に、ポップアップに対してキャンセルを押してもコメントが投稿されるようになっています。

**Comment by machida** [comment]
sad の日報の際、

----

ここをクリックすると、ポップアップが出る。

<img width="486" alt="貼り付けた画像_2022_02_21_15_32" src="https://user-images.githubusercontent.com/168265/154901221-acd980e8-1834-4c71-82d4-abf79add85aa.png">

----

こちらはクリックしてもポップアップが出ない。

<img width="444" alt="貼り付けた画像_2022_02_21_15_31" src="https://user-images.githubusercontent.com/168265/154901173-47fa1be1-2eef-4531-b592-2166500e9d97.png">

----

この様にお願いしますー

**Comment by Aseiide** [comment]
@machida 
すみません！このissue closeで良い気がしてきました。
町田さんが書いてくれた仕様については、既に #4239 で満たしています。コメント欄のボタンを押したときにはポップアップが出ないように自分で変更していました。

キャプチャをとったブランチがメインで、変更が反映されてないままキャプチャしてissueを立ててしまった感じです。

**Comment by machida** [comment]
@Aseiide 調査ありがとうございます！
https://github.com/fjordllc/bootcamp/pull/4239 がリリースされればこれもクローズ了解です！！
では、このIssueはクローズにしたいと思いますー
