### ISSUE TITLE
categories.positionを削除したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4245]
並び順問題についてドキュメントにまとめました。

[カテゴリー・プラクティスの並び順 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/%E3%82%AB%E3%83%86%E3%82%B4%E3%83%AA%E3%83%BC%E3%83%BB%E3%83%97%E3%83%A9%E3%82%AF%E3%83%86%E3%82%A3%E3%82%B9%E3%81%AE%E4%B8%A6%E3%81%B3%E9%A0%86)

デプロイするときに本番に影響が出ないように気をつけたい。

#3924 こちらのバグを直すためにこのIssueを先に直す必要がある。

**Comment by Saki-htr** [comment]
本番環境での動作確認を行い、問題なかったため、issueをcloseいたします。
