### ISSUE TITLE
practices.positionを削除したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4246]
並び順問題についてドキュメントを書きました。

[カテゴリー・プラクティスの並び順 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/%E3%82%AB%E3%83%86%E3%82%B4%E3%83%AA%E3%83%BC%E3%83%BB%E3%83%97%E3%83%A9%E3%82%AF%E3%83%86%E3%82%A3%E3%82%B9%E3%81%AE%E4%B8%A6%E3%81%B3%E9%A0%86)

本番にデプロイした時に並び順が無茶苦茶にならないように気をつけたい。

#3924 こちらのバグを直すためにこのIssueを先に直す必要がある。

**Comment by yuma-matsui** [comment]
@komagata @machida 
お疲れ様です。
こちらのissueについて本番環境でのご確認をお願い致します。

自身のアカウントではプラクティス一覧の順番が変わってないことを確認できました。

プラクティス一覧ページとプラクティスの順番変更ページの並び順が変わっていないことをご確認いただけたらと思います。

お手数をおかけしますがお願い致します。

**Comment by komagata** [comment]
@yuma-matsui 本番環境で動作することを確認しました。

**Comment by yuma-matsui** [comment]
@komagata 
ご確認いただきありがとうございます！

issueをクローズします。
