### ISSUE TITLE
[fixture] 開発用データの日報にニコニコカレンダーの情報が含まれていない

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4248]
ニコニコカレンダーの情報 は必須項目なので、fixtureの日報のデータにニコニコカレンダーの値を含むようにする。

これは開発用データのIssueなので、マージされたらcloseでOK。

**Comment by komagata** [comment]
:memo: `db/fiuxtures/reports.yml`に日報のseedデータがあるはず。

**Comment by niikz** [comment]
マージされたのでcloseします。
