### ISSUE TITLE
アドバイザー用のWelcomeメッセージがほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4253]
現在、ダッシュボードに受講生用のWelcomeメッセージが表示されるのだけど、アドバイザーにも別の文章でWelcomeメッセージを表示したい。

受講生は、プラクティスをスタートするとWelcomeメッセージは消えるんだけど、アドバイザーの場合は、閉じたら消えるようにしたい。消した、という情報はCookieに保存する。

**Comment by komagata** [comment]
初回の表示をしたかどうかはCookieでやるのがいいと思います。（このサイトの他の場所でも使っているので）

**Comment by komagata** [comment]
:memo: Development環境でも一般の生徒でプラクティスをやってない人（確かhatsuno）とかでログインすると、一般の生徒向けのWelcomeメッセージが出るのでそれをみるとイメージしやすいかもです〜

**Comment by taka110-IT** [comment]
@machida @komagata 
仕様について確認です。Cookieで保存する場合は、異なる環境（モバイルとデスクトップ、ChromeとFirefox）でダッシュボードを見た時に再表示されるかと思いますが、今回はそれでも良いということでよろしいでしょうか。

**Comment by machida** [comment]
@taka110-IT はい！大丈夫ですー🙆‍♂️

**Comment by komagata** [comment]
@taka110-IT はい。クッキーはクライアント（多くの場合はブラウザ）に保存されるものなので、クッキーを使うときは基本的にそういう認識をみんな持っているので大丈夫です。

そういう理由もあって「Windowを閉じたかどうか」とか「以前に入力したIDを記憶しておく」などといった重要でない部分に利用することが多いです。今回もそんな感じです〜。

**Comment by taka110-IT** [comment]
@machida @komagata 
ありがとうございます。昨日のミーティングでもお伺いしましたが、このままCookieでの実装を進めていきます。

**Comment by taka110-IT** [comment]
アドバイザーの方に本番環境で動作を確認していただきましたので、Issueをクローズします。
