### ISSUE TITLE
[相談部屋] 相談部屋の最新コメントを読んだら未読ではない状態にしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4260]
管理者でログインしたときは相談部屋個別にこれを表示したい。

![貼り付けた画像_2022_02_19_0_07](https://user-images.githubusercontent.com/168265/154708624-1d117aae-412a-4e7a-a52e-9675a51c9ed3.png)

「読んだ」を押すと、

- 未読ではなくなる
- 左メニューの相談リンクにある未読数のカウントが減る
- 管理者でログインしたときの相談部屋一覧の未読のタブからもなくなる

このようにしたい。

**Comment by komagata** [comment]
@machida ちょっとこれ、実装方法や他との整合性のために詳しく考えたいです。

**Comment by machida** [comment]
@komagata 了解ですー

今、返信をしないの未読に残り続けるので、それを解決しないことには相談部屋への移行が難しそうです。
この問題が解決されたら相談部屋に相談の移行をしたいと思います。

**Comment by machida** [comment]
こちら、一旦コメントをするで対応することになったのでクローズ
