### ISSUE TITLE
[ブログ] WIPで保存されている記事の場合は、edit でも WIP であることがわかるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4261]
<img width="1997" alt="貼り付けた画像_2022_02_18_22_17" src="https://user-images.githubusercontent.com/168265/154689929-55b54c86-a6c5-410a-83b8-242e22cd140b.png">

**Comment by eatplaynap** [comment]
町田さんに本番環境でのチェックしていただき、確認OKだったのでcloseします
