### ISSUE TITLE
次回から自動的にログインが動いていない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#427]
動いてない気がする。

[![Image from Gyazo](https://i.gyazo.com/5a4979163e25d1efd22d4c816221db61.png)](https://gyazo.com/5a4979163e25d1efd22d4c816221db61)

**Comment by neko314** [comment]
@komagata 

とりあえず自分のPCでは自動ログインできています。

何をどうやって調査するとよいか、自分でパッと思いつくのはこんな感じです。

* 自動ログインできない人が他にいるかみんなにきく
* どのPC,ブラウザ使っているのかもきく

どうでしょうか？

**Comment by komagata** [comment]
@neko314

@bluerabbit さんが言ってたので聞いてみてください。

**Comment by neko314** [comment]
@bluerabbit 

こちらの問題についてどのような様子か教えていただけないでしょうか。

* ログインできない頻度はどれくらいですか？（毎回？できるときもありますか？）
* どのブラウザをお使いですか？バージョンも教えてください。
* PCは何をお使いですか？

以上、よろしくお願いします。

**Comment by neko314** [comment]
@komagata 

セッションの保存期間を見てみました。

sorcery/wiki/Remember-Me)[https://github.com/NoamB/sorcery/wiki/Remember-Me]によるとsouceryのデフォルトではセッションは1週間とありました。

bootcampの設定ですが、「[複数ブラウザでログインを永続化](https://github.com/fjordllc/bootcamp/commit/d171c20753617ddf789b7e8b376dd871c1f5ceaa)」のcommitで変更になっていました。

現在も[bootcamp/config/initializers/sorcery.rb:255](https://github.com/fjordllc/bootcamp/blob/master/config/initializers/sorcery.rb#L255)に` user.remember_me_for = 256.weeks` とあります。

**Comment by machida** [comment]
動いてるのでclose
