### ISSUE TITLE
提出個別ページのページタイトルを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4274]
提出物個別ページのタイトルが、
[プラクティス名]の提出物
になっているか、
[プラクティス名]
だけにする。

<img width="713" alt="貼り付けた画像_2022_03_02_22_36" src="https://user-images.githubusercontent.com/168265/156371958-611fa1e4-1020-41a2-bbbe-f05d498076af.png">

**Comment by saeyama** [comment]
本番環境で確認が出来たのでクローズします！
