### ISSUE TITLE
サイト内通知に質問の内容を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4285]
現在の通知

<img width="240" alt="貼り付けた画像_2022_02_22_16_13" src="https://user-images.githubusercontent.com/168265/155081173-82e5b037-403f-4eb2-9673-eeb872a9c795.png">

```
XXXさんから質問「質問のタイトル」が投稿されました。
```

という通知に変更する。

メール通知の方も同様にお願いします。

**Comment by tksmasaki** [comment]
@komagata @machida 
こちらはメンター向けの機能のため、質問が投稿された際に本番環境での動作確認をしていただきたいです。
よろしくお願いいたします🙏

**Comment by komagata** [comment]
@tksmasaki 本番環境で動作することを確認しました。

**Comment by tksmasaki** [comment]
@komagata 
動作確認ありがとうございました！ Close します。
