### ISSUE TITLE
Docs一覧ページにWIP中のDocが表示されていない

### ISSUE THREAD

**Issue by Paru871** [fjordllc/bootcamp#4286]
## 概要
Docを作成してWIPで保存したあと、Docs一覧ページを表示させるとWIP保存中のDocが表示されていない
WIP保存したDocは自分のダッシュボードに「WIPのページ」として表示されているのでそこからアクセスするしかない

## 再現手順
1. 画面左側のナビゲーションバーから「Docs」をクリック、Docs一覧ページが表示される
1. 右上の[+Doc作成]をクリックすると入力フォームが開くので、必要事項を入力して[WIP]をクリックしてWIP保存する
1. 「WIPとして保存しました」というメッセージとともにDoc個別ページが表示される(WIPとして表示されている)
1. 画面左側のナビゲーションバーから「Docs」をクリック、Docs一覧ページが表示される
1. WIP保存したDocが一覧に表示されていない

## 期待される振る舞い
お知らせ一覧やイベント一覧ページと同様に、WIP保存したDocもWIPとわかる形式でDocs一覧ページに表示してほしい

## スクリーンショット
![image](https://user-images.githubusercontent.com/82434093/155130772-300040d7-f127-431f-901e-44c974d7d339.png)
![image](https://user-images.githubusercontent.com/82434093/155131024-96babdab-a7d0-46b4-a1ac-503f6884ffa8.png)

**Comment by Paru871** [comment]
@komagata @machida 
お疲れさまです。現在Q&AページのWIPの機能に取り組んでいるため、DocsのVueと見比べていたらバグを発見しました。
修正は簡単だったので、私の方でプルリクも作らせていただきました。
現在チームメンバーさんのレビューの依頼中です。
よろしくお願いします🙏

**Comment by komagata** [comment]
@Paru871 PRの作成ありがとうございます〜！

**Comment by Paru871** [comment]
こちら本番環境で動作確認ができましたのでcloseとさせていただきます。ありがとうございました！
