### ISSUE TITLE
ブラウザバックすると謎の検索ウィンドウが出現するときがある

### ISSUE THREAD

**Issue by cafedomancer** [fjordllc/bootcamp#4288]
## 概要

タイトルどおり

## 再現手順

不明

## 期待される振る舞い

ブラウザバックしても検索ウィンドウが出現しない

## スクリーンショット

(こんなのが画面の真ん中に表示される)

<img width="2897" alt="Screen Shot 2022-02-23 at 22 04 07" src="https://user-images.githubusercontent.com/7645585/155324765-f16eff6e-760c-43ed-a7f7-6d2a8ab01e9f.png">

## 環境

 - OS: macOS Monterey
 - ブラウザ: Google Chrome
 - バージョン: 98.0.4758.102 (Official Build) (x86_64)

**Comment by ima1zumi** [comment]
📝  https://github.com/fjordllc/bootcamp/issues/2828 に再現手順があります

**Comment by cafedomancer** [comment]
お、一本化したほうが良いと思うので閉じます！
