### ISSUE TITLE
[相談部屋] 管理者の相談部屋一覧に相談部屋検索（インクリメンタルサーチ）を付けたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4290]
全員を一番左に移動。

<img width="887" alt="貼り付けた画像_2022_03_18_12_12" src="https://user-images.githubusercontent.com/168265/158930627-79ac1fd1-8a7a-46da-a95c-7efb469a7426.png">

---

text input を追加。

<img width="1399" alt="貼り付けた画像_2022_03_18_12_14" src="https://user-images.githubusercontent.com/168265/158930829-b7fa6e7f-639d-416e-ae7e-a2f7ed20ed88.png">

ここに `ma` と入力したら、

<img width="1399" alt="貼り付けた画像_2022_03_18_12_14" src="https://user-images.githubusercontent.com/168265/158930977-fea99820-35c4-412f-955f-fb622fa2aec7.png">

- ユーザーID
- ユーザー名
- ユーザー名読み方
- DiscordID

のいずれかに `ma` が含まれているユーザーの相談部屋だけが残り、それ以外は消える。

---

何文字入力したらリストが更新されるか？など細かい設定についてはここでやり取りをしながら進めましょう。

**Comment by tksmasaki** [comment]
## 現在の仮実装内容

- 現在は全角カタカナを含む場合は2文字以上、それ以外は3文字以上で検索する
- ロールごとのページで絞り込み可能
- 必要な文字数が入力された場合は、現在の一覧を非表示（display: none）にし、検索結果一覧を表示をする
  - 文字が削除された場合はその逆
- 検索（問い合わせ）は 500ms に一度
- 検索結果一覧にはページャーを使用しない
- 一致するものがない場合はその旨を表示

<img width="625" alt="image" src="https://user-images.githubusercontent.com/83743223/160344287-58842a85-3a37-4673-9a0a-895c73d68733.png">
<img width="623" alt="image" src="https://user-images.githubusercontent.com/83743223/160344254-2dc0af25-221d-4ac4-9cf9-5ffc85c99bbe.png">
<img width="627" alt="image" src="https://user-images.githubusercontent.com/83743223/160344537-6e4ace1a-f10e-486c-ad6e-81a08b70320b.png">
<img width="628" alt="image" src="https://user-images.githubusercontent.com/83743223/160344927-73696dab-d5e3-49a6-9c33-1d5b32ef2b86.png">
<img width="627" alt="image" src="https://user-images.githubusercontent.com/83743223/160344583-abf0cffc-080d-4083-a08a-1d9b9369aa74.png">

## 確認すること

1. 検索を開始する文字数はどうするか？
→現在は全角カタカナを含む場合は2文字以上、それ以外は4文字以上
2. target=all（全員） 以外の場合も検索機能は必要か？
3. かな → カナ、ｂｃｄ→ bcd ように検索できるようにするか？
4. debounce 実行する感覚は 500ms でよいか？

**Comment by tksmasaki** [comment]
## 2022/03/28 質問タイムにて
komagata さんに確認
> 1. 検索を開始する文字数はどうするか？
> →現在は全角カタカナを含む場合は2文字以上、それ以外は3文字以上
> 2. target=all（全員） 以外の場合も検索機能は必要か？
> 3. かな → カナ、ｂｃｄ→ bcd ように検索できるようにするか？
> 4. debounce 実行する感覚は 500ms でよいか？

- 1，2，4 は仮実装している内容のままでよいと思う
- 3 は今回実装しなくてよいと思う

**Comment by tksmasaki** [comment]
@machida 
仮実装の内容と、質問タイムで komagata さんと話した内容について確認していただきたいです🙏

検索文字数については、半角英数2文字だとローマ字読みで1文字相当なのでマッチしすぎるかなと思い、3文字にしてあります。その他の点も、何か変更したい点があればお伝えください。

**Comment by tksmasaki** [comment]
ユーザー名にも全角文字などが入力できることを失念していました🙇‍♂️

> 1. 検索を開始する文字数はどうするか？
> →現在は全角カタカナを含む場合は2文字以上、それ以外は3文字以上

こう書いていましたが、半角英数字 + ハイフン + アンダーバー のみの場合（`/^[\w-]+$/`）は3文字以上、それ以外は2文字以上で検索するようにしようと考えています。

**Comment by machida** [comment]
@tksmasaki 

> 3文字にしてあります。

了解です！これでお願いします🙏 もし使い勝手で問題が発生したら別Issueで対応したいと思います。でも、3文字がちょうど良さそうな予感がします。

**Comment by tksmasaki** [comment]
@machida 
確認ありがとうございます！ これでPRを作成します。
デザインが必要になるので、後ほど依頼させていただきます🙏

**Comment by tksmasaki** [comment]
> - ユーザーID
> - ユーザー名
> - ユーザー名読み方
> - DiscordID
> のいずれかに ma が含まれているユーザーの相談部屋だけが残り、それ以外は消える。

##検索対象を追加（2022/04/04 質問タイムで確認済み）

**Comment by tksmasaki** [comment]
@komagata @machida 
管理者向けの機能のため、本番環境での確認をしていただきたいです。よろしくお願いします🙏

**Comment by machida** [comment]
@tksmasaki 本番で確認しました🙆‍♂️
実装ありがとうございます！！

**Comment by tksmasaki** [comment]
@machida 
確認ありがとうございます🙏 色々と学べた Issue だったので、担当できてよかったです！
Close します！
