### ISSUE TITLE
ユーザー個別ページ > 質問一覧 の vue.js化

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4294]
<img width="1021" alt="貼り付けた画像_2022_02_24_18_43" src="https://user-images.githubusercontent.com/168265/155499379-6f72deb3-b251-4e72-9372-3f7d8cc332c2.png">

ページャーも出すようにお願いします🙏

**Comment by garammasala29** [comment]
本番環境で確認、問題点も修正いたしましたのでCloseします
