### ISSUE TITLE
ユーザー個別ページ > 回答一覧 を vue.js化したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4295]
<img width="982" alt="貼り付けた画像_2022_02_25_0_22" src="https://user-images.githubusercontent.com/168265/155553911-dcf72080-2f34-4791-b7b8-16f67afb34e4.png">

- 回答一覧 を vue.js化
- ページのタイトルを変更
- ページャーを付ける

こちらお願いします🙏

**Comment by eatplaynap** [comment]
本番環境で確認できたのでcloseします
