### ISSUE TITLE
未アサインの提出物のDiscordの通知にリンクを付ける

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4313]
[#4310](https://github.com/fjordllc/bootcamp/issues/4310)
こちらのIssueを分割

**Comment by machida** [comment]
このURLを追加してください。
https://bootcamp.fjord.jp/products/unassigned

**Comment by siroemk** [comment]
@machida 
お疲れ様です！
1点確認したいのですが、Discordのメンターチャンネルに投稿されているのは
bootcamp/app/views/api/products/passed/show.text.erb
ではなく、以下ではないでしょうか。
bootcamp/app/views/api/products/unassigned/counts.text.erb

[#4136](https://github.com/fjordllc/bootcamp/pull/4136)
こちらのやりとりを見ていると、``bootcamp/app/views/api/products/unassigned/counts.text.erb``が対象であるように見えました👀

**Comment by machida** [comment]
@siroemk すいません、僕が間違えてました🙇‍♂️
正しいファイルはそっちになりますー

**Comment by siroemk** [comment]
@machida 
ご確認ありがとございます！作業を進めます🙆‍♀️

**Comment by siroemk** [comment]
本番で動作確認ができたのでcloseします！
