### ISSUE TITLE
「メンターログイン時、『日報個別ページにXX日ぶりの日報です』と表示するテスト」が頻繁に落ちる

### ISSUE THREAD

**Issue by kaiyu-tech** [fjordllc/bootcamp#4315]
## 概要

テスト対象の日報データの`created_at`がすべて同値で生成されている。

[`report34`](https://github.com/fjordllc/bootcamp/blob/main/test/fixtures/reports.yml#L275-L280)  が「初日報」と判断されることを想定してテストが記述されている。

[`first?`](https://github.com/fjordllc/bootcamp/blob/main/app/models/report.rb#L95-L104)  で「初日報」か判断しているが、`created_at` がすべて同値の為に誤判断が起きたり起きなかったりする。

## 再現手順

1. Mainブランチで`rails test test/system/reports_test.rb:624`を実行する
2. [`report32`](https://github.com/fjordllc/bootcamp/blob/main/test/fixtures/reports.yml#L250-L280)  が「初日報」と誤判断されて、テストが通らないことが頻繁にある。

```ruby
  # bootcamp/test/system/reports_test.rb:624
  
  test 'display report interval for mentor while undoing wip' do
    visit_with_auth report_path(reports(:report32)), 'komagata'
    assert_selector '.a-page-notice.is-only-mentor.is-danger', text: '10日ぶりの日報です'

    visit_with_auth report_path(reports(:report33)), 'kananashi'
    click_link '内容修正'
    click_button '提出'

    visit_with_auth report_path(reports(:report32)), 'komagata'
    assert_no_selector '.a-page-notice.is-only-mentor.is-danger', text: '9日ぶりの日報です'
  end
```

## 期待される振る舞い

[`report32`](https://github.com/fjordllc/bootcamp/blob/main/test/fixtures/reports.yml#L250-L280)  が「初日報」と判断されずに、10日ぶりの日報と判断されて、テストが通る。

## スクリーンショット

- テストが通ったとき

![image](https://user-images.githubusercontent.com/73627898/155903397-11acb845-85fc-4359-9e0d-b48eec603bee.png)

- テストが通らなかったとき

![image](https://user-images.githubusercontent.com/73627898/155880637-32a89c44-5276-4a4b-b3d8-6c37e1e44414.png)

## 環境

 - OS: macOS 11.6.3
 - ブラウザ: Chrome
 - バージョン: 98.0.4758.109

## 関連

[メンターでログインしたときだけ日報個別ページに「XX日ぶりの日報です」と表示する by garammasala29 · Pull Request #4170 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4170)

[wip解除をしながら、メンター側で日報間隔を表示するテストを追加 · fjordllc/bootcamp@e212cd1](https://github.com/fjordllc/bootcamp/commit/e212cd13ba60541b210b08c76b4ba210bdb5e4eb)

**Comment by komagata** [comment]
@kaiyu-tech Issue登録ありがとうございます。

@garammasala29 さんの追加したテストが頻繁に落ちるようなので確認してみてください〜

https://github.com/fjordllc/bootcamp/blame/main/test/system/reports_test.rb#L624

**Comment by garammasala29** [comment]
開発環境のテストの修正でしたので本issueはcloseします
