### ISSUE TITLE
所属企業にインクリメンタルサーチが使えるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4322]
管理者でログインし、ユーザー個別ページに行く。

<img width="718" alt="貼り付けた画像_2022_03_01_14_55" src="https://user-images.githubusercontent.com/168265/156113172-209a6ca5-70b4-448b-a2b1-6d182488079a.png">

ここにインクリメンタルサーチ。

<img width="647" alt="貼り付けた画像_2022_03_01_14_55" src="https://user-images.githubusercontent.com/168265/156113238-23f86d53-7491-435b-b66f-3882cac1936e.png">

https://choices-js.github.io/Choices/
このライブラリを実験的に使ってみる。

このライブラリの Option groups のこれを入れる。

<img width="574" alt="image" src="https://user-images.githubusercontent.com/168265/156113432-74b59e26-98bb-49b1-a4c8-b544fcac8df0.png">

<img width="569" alt="image" src="https://user-images.githubusercontent.com/168265/156113465-91082118-3179-4f58-a6e8-ef22c07fdae0.png">

**Comment by garammasala29** [comment]
@komagata @machida 
本番環境でのご確認よろしくお願いいたします🙏

**Comment by komagata** [comment]
@garammasala29 本番環境で動作することを確認しました。

**Comment by garammasala29** [comment]
@komagata さん
ありがとうございました！本issueはcloseとさせていただきます🙏
