### ISSUE TITLE
お知らせ作成ページに不要な公開ボタンが表示される

### ISSUE THREAD

**Issue by aim2bpg** [fjordllc/bootcamp#4327]
## 概要
お知らせ作成ページに不要な公開ボタンが表示される。
原因：#4215 で、`app/views/announcements/_form.html.slim`の公開ボタンを出す条件分岐の作り込みにミスがあった。

## スクリーンショット
![image](https://user-images.githubusercontent.com/58363353/156293556-ad5f8a71-bff6-4f12-a68a-4e5f763b85d7.png)

**Comment by machida** [comment]
@aim2bpg こちら、どのような場合にボタンが二重で表示されてましたでしょうか？

**Comment by aim2bpg** [comment]
@machida さん、管理者かメンターがお知らせ作成する場合です。

**Comment by aim2bpg** [comment]
@machida さん、Discordで中途半端な依頼となって申し訳ありませんでした🙏
こちら、管理者・メンターがログインした状態での確認となりますので、よろしくお願いいたします🙇🏻‍♂️

修正前後の振る舞いとしては、
- 修正前：「作成」「公開」が表示される。
- 修正後：「作成」が表示され、「公開」は表示されない。
- となります。

**Comment by machida** [comment]
@aim2bpg ありがとうございます！不具合は出てませんでした。不具合は解消されてますのでクローズしますー✨
