### ISSUE TITLE
管理者ページのユーザー一覧のお試し延長適用ユーザー一覧にアドバイザーが含まれてしまう。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4331]
このページにキャンペーン期間中に登録したユーザー一覧が表示される。

<img width="1305" alt="貼り付けた画像_2022_03_02_16_37" src="https://user-images.githubusercontent.com/168265/156316274-369ccb24-dbe7-4477-a0ae-cf4a595219a3.png">

この一覧にアドバイザーは含めないようにする。

**Comment by saeyama** [comment]
管理者ページのユーザー一覧のお試し延長適用ユーザー一覧からアドバイザーは削除しましたが、メンターや卒業生、退会者等は表示されている状態となっております。
ページ下部の全員のメアドの欄にアドバイザーのメールアドレスが表示された状態となっております。
上記、修正不要との回答を駒形さん、町田さんに3/9(水)開発MTGの時に確認済。

**Comment by saeyama** [comment]
@komagata さん @machida さん
https://discord.com/channels/715806612824260640/809595476847493192/956541585967972383
上記でもお願いしたのですが、管理者向け機能となっているので、お手数ですが本番環境で確認をお願いします🙏

**Comment by machida** [comment]
🗒
GWにキャンペーンをやるので、そのときに確認

**Comment by saeyama** [comment]
町田さんに本番環境で確認いただいたのでクローズします！
https://discord.com/channels/715806612824260640/809595476847493192/972499163709337600
