### ISSUE TITLE
イベント一覧を開催日順に並べたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4336]
<img width="211" alt="貼り付けた画像_2022_03_06_23_52" src="https://user-images.githubusercontent.com/168265/156928489-bf8c9dd0-76e1-4a11-a64e-e49a1723879f.png">

このリンクの先のページ。

**Comment by komagata** [comment]
💭 もっともだと思った🤭

**Comment by niikz** [comment]
本番環境で確認できたのでcloseします。
