### ISSUE TITLE
【メンター向け】「n日経過」の部分に件数を入れたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4345]
[提出物の未アサインタブ](https://bootcamp.fjord.jp/products/unassigned)で「5日経過」のような区切り線が表示されるが、件数が多いと具体的な件数がが把握しづらいので、「5日経過 (10)」のように件数が表示されると嬉しい。

![hoge](https://user-images.githubusercontent.com/1148320/156667887-771c9e50-0323-464d-8b16-c53c74c9595c.png)

**Comment by Aseiide** [comment]
開発MTG 📝 
未アサインと未完了、どちらにも表示する

**Comment by Aseiide** [comment]
@machida 
こちらなんですけど、件数は「未完了」と「未アサイン」のどちらにもあったほうが良いですか? それとも、「未アサイン」タブだけに表示しますか??

**Comment by machida** [comment]
両方にお願いしますー

**Comment by Aseiide** [comment]
@machida わかりました！ありがとうございます！

**Comment by Aseiide** [comment]
## 1ページ
![screencapture-localhost-3000-products-unchecked-2022-04-16-14_30_27](https://user-images.githubusercontent.com/45246171/163663095-3a83d569-05dc-4e5d-a04c-8cc40356eafb.png)

## 2ページ
![screencapture-localhost-3000-products-unchecked-2022-04-16-14_30_45](https://user-images.githubusercontent.com/45246171/163663100-6d4c96a9-b7d4-486a-9810-9eb9abe5895d.png)


@machida 
「未完了」のタブにはページネーションがあって、今の実装だとページが変わると表示される件数が変わってしまうんですが、`()`の中には全件数が表示されたほうが良いですよね??
この場合だったら、ページ1にもページ2にも1日経過の全件数である48を表示すると思っているんですが。

**Comment by Aseiide** [comment]
📝 
- jbuilderで全件数を取って、それをvueで表示する
- integrationテストでレスポンスを確認する
- システムテストで書く

**Comment by machida** [comment]
あー、なるほど、ではページネーションのない未アサインタブだけで大丈夫ですー🙆‍♂️

**Comment by Aseiide** [comment]
@machida 
承知しました！

**Comment by Aseiide** [comment]
動作確認ができたのでcloseします！ @machida 確認ありがとうございました！
