### ISSUE TITLE
卒業生はダッシュボードの「学習時間」を非表示にできるようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4347]
ダッシュボードの「学習時間」

<img width="649" alt="貼り付けた画像_2022_03_04_12_40" src="https://user-images.githubusercontent.com/168265/156695050-9a4a5247-6624-4867-ab81-92fa9c80b9bf.png">

~~管理者、メンター、~~ 卒業生 ~~、アドバイザー~~には非表示リンクを表示。
非表示にした情報はcookieで保存。

消したあと戻したくなったらどうするの？... 要望が出たら別Issueで対応。

**Comment by garammasala29** [comment]
管理者、メンター、アドバイザーは元々ダッシュボードに「学習時間」が表示されない設定となっていたので、町田さんに相談し卒業生のみを対象とすることになりました
https://discord.com/channels/715806612824260640/809595476847493192/954692078867218522

**Comment by garammasala29** [comment]
@kaiyu-tech さんに本番環境で確認していただいたのでcloseとします。
「卒業生と研修生」など複数ロールには対応できていないようだったので、他PRで対応します。
