### ISSUE TITLE
通知一覧のメンションの合計数を削除する

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4355]
<img width="982" alt="貼り付けた画像_2022_03_06_23_27" src="https://user-images.githubusercontent.com/168265/156927478-c3816e5c-1496-49ca-ae7e-4222b80b7646.png">

この数字を確認するシチュエーションはないので、削除する

**Comment by saeyama** [comment]
本番環境で確認が出来たのでクローズします！
