### ISSUE TITLE
コメントの検索にHTMLが表示されている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4358]
<img width="1197" alt="スクリーンショット 2022-03-07 17 25 23" src="https://user-images.githubusercontent.com/16577/156997581-0bae391b-86b2-4ff8-8d1b-687795dbf70f.png">

https://bootcamp.fjord.jp/searchables?document_type=all&word=相談部屋

**Comment by machida** [comment]
相談部屋のコメントが検索にひっかかったせいでこのバグが出ていました。
相談部屋のコメントは検索結果に表示されないようになったので、このバグが出ることはなくなったのでクローズしますー
