### ISSUE TITLE
【メンター向け】受講生が卒業したら通知してほしい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4361]
現状、受講生が退会した場合はメンターに通知が飛ぶが、卒業した場合は通知が飛ばない。
メンターから見ると「退会者がいないのに、受講生の人数がなぜか減ってる！？」となるので、卒業生も通知してほしい。

あと、単純に「卒業めでたい！」と心の中でお祝いしたい気持ちもある😄

**Comment by tksmasaki** [comment]
@machida
通知の内容について質問があります。
現在、`XXXさんが卒業しました。` で仮実装しているのですが、文言は何がいいでしょうか？
お手すきの際に、ご確認よろしくお願いいたします🙏

他の通知例を記載しておきます。
- Discord への通知は `「XXXさんが卒業になりました」`
- 退会時のサイト内通知は `XXXさんが退会しました。`

**Comment by JunichiIto** [comment]
> 「XXXさんが卒業になりました」

日本語の話ですが、「XXXさんが卒業しました」で良さそうですね。

**Comment by tksmasaki** [comment]
@JunichiIto 
> 日本語の話ですが、「XXXさんが卒業しました」で良さそうですね。

コメントありがとうございます！ 僕も「卒業になりました」だとちょっと違和感があるなと思っていました。

@machida 
`XXXさんが卒業しました。` にする場合は、 Discord 通知の方も修正してしまいましょうか？（ 1p の Issue として作っておくものありですかね？🤔 ）
また追加の確認内容になってしまうのですが、卒業時の Discord 通知のには `「」` がついていますが、これはつけなくていいでしょうか？ 他の通知にはついていないので、たまたまついてしまったのかなと思っています。

**Comment by tksmasaki** [comment]
## 仕様（2022/03/16 開発ミーティングにて）
- 通知内容は ``

**Comment by komagata** [comment]
@tksmasaki GitHub外で話したことをこちらに書いておくの、後から参加する方も問題を追跡しやすいのでとっても素晴らしいです〜！

**Comment by tksmasaki** [comment]
@komagata @machida 
メンター向けの機能のため、卒業生が出た際に確認していただきたいです。
よろしくお願いいたします🙏

**Comment by komagata** [comment]
@tksmasaki 実際に卒業したときに確認しますので、 @tksmasaki さんの作業としては完了で大丈夫です〜

**Comment by JunichiIto** [comment]
こちら、先日通知が届くことを確認しました。ご対応どうもありがとうございました！
