### ISSUE TITLE
ユーザー個別ページの日報と提出物を別タブにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#437]
![image](https://user-images.githubusercontent.com/168265/43431151-73edf37a-94a7-11e8-82a5-877ff9fedab3.png)

↓

プラクティス個別ページの様に別タブにしたい

![image](https://user-images.githubusercontent.com/168265/43431175-8781bac0-94a7-11e8-835e-43c6bf49d834.png)

**Comment by shibaaaa** [comment]
こちら対応済みなのでクローズします〜
