### ISSUE TITLE
[Fixture]開発用データに長いIDのユーザー（roleはメンター）のデータがほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4370]

**Comment by machida** [comment]
long-idなんとかみたいなidで、名前も長いidメンターみたいな、そのユーザーがなぜテストデータにあるのかがわかるid、名前で作って欲しいです。idの長さは12文字くらい欲しいです。

**Comment by machida** [comment]
これはfixtureにデータを追加するだけで、本番には関係ないので、マージされたらクローズでお願いします。

**Comment by machida** [comment]
このユーザーで確認した提出物(OKにした提出物)、担当アサインしている提出物、日報と提出物にコメント投稿したデータ、作ったDocも欲しいです。

**Comment by rosh-1228** [comment]
mainブランチに反映されていましたので、closeします。
