### ISSUE TITLE
テストデータの企業ロゴ画像を更新する

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4371]
実在の企業ロゴは使わずにダミーにする。以下の画像に差し替える。

<img width="150" alt="001" src="https://user-images.githubusercontent.com/168265/157275260-e6d7f130-1df3-4fce-b254-dc30728aebe0.png">

<img width="150" alt="002" src="https://user-images.githubusercontent.com/168265/157275265-1275ea0d-33c7-4ac7-8c94-16e4598ed4c2.png">

<img width="150" alt="003" src="https://user-images.githubusercontent.com/168265/157275309-d74e53b3-bb51-4c6f-8dcd-3ce23b46b93c.png">

<img width="150" alt="004" src="https://user-images.githubusercontent.com/168265/157275314-9f782fc8-c21a-4ce7-ba92-ca6f3d46fdcb.png">

**Comment by saeyama** [comment]
画像は以下のフォルダ内にある1.jpg~4.jpgの画像を差し替えする。

- `db/fixtures/files/companies/logos`
- `test/fixtures/files/companies/logos`

develop環境で差し替えした画像が確認出来なくても問題ない。
あくまでも、画像の差し替えがされていれば良い。
（3/16 質問タイムで駒形さんに確認済）
