### ISSUE TITLE
DocsやQ&Aの一覧ページでプラクティスにリンクを付ける

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4397]
DocsやQ&Aの一覧ページでは以下のようにアイテムが一覧表示されるが、この中の関連プラクティスはただのテキストになっている（赤線部分）。

<img width="595" alt="Screen Shot 2022-03-14 at 7 42 27" src="https://user-images.githubusercontent.com/1148320/158082427-91574241-e814-47dd-9689-9ef7012e9fe0.png">

<img width="597" alt="Screen Shot 2022-03-14 at 7 43 34" src="https://user-images.githubusercontent.com/1148320/158082429-c2a8f7a2-d987-435b-95c8-5e0f0d17dbca.png">

これをプラクティス詳細ページへのリンクに変えてあげるとちょっと便利になるかも。

**Comment by JunichiIto** [comment]
これは付いててもいいんじゃないかなー。

**Comment by masanarih0ri** [comment]
動作確認しましたのでクローズさせていただきます！
