### ISSUE TITLE
次の経過日数までの時間を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4400]

**Comment by Aseiide** [comment]
<img width="848" alt="Screen_Shot_2022-03-14_at_21 50 05" src="https://user-images.githubusercontent.com/45246171/158196997-36138519-cf8e-4937-86e8-4e1ffcc74087.png">

更新を起点に、
```
* 3日経過のポイント
* now
* 4日経過のポイント
(updated_at + 24 * 4) - now 
(updated_at + 次のポイントの日数) - now
```
を計算して表示する
