### ISSUE TITLE
旧住所に関する情報がサイトに残っている

### ISSUE THREAD

**Issue by napple29** [fjordllc/bootcamp#4406]
## 概要
オフィスをお引越しされていると思うのですが、旧住所や明大前といった情報がサイトに残っていました。

トップページの運営会社の部分
https://bootcamp.fjord.jp/  （メンター紹介の上に明大前の文字）

特定商取引に関する法律
https://bootcamp.fjord.jp/law （住所が旧住所）

個人情報の取り扱いについて（下記で使われている。元ファイルは同一ファイルと考えられる）
https://fjord.jp/commissioned-development/  （住所が旧住所、以下同様）
https://fjord.jp/privacy.html
https://bootcamp.fjord.jp/inquiry/new

## 再現手順

上記URLにアクセスする
or
VScodeなどのエディタで`明大前`や`世田谷`で検索

## 期待される振る舞い

旧住所に関する情報が更新される

### トップページの運営会社の部分
<img width="729" alt="スクリーンショット 2022-03-15 13 08 47" src="https://user-images.githubusercontent.com/82350582/158304679-6b8de7e3-7c62-4a3e-93e3-476043650e55.png">

### 特定商取引に関する法律のページ
<img width="908" alt="スクリーンショット 2022-03-15 13 08 07" src="https://user-images.githubusercontent.com/82350582/158304652-9785b82b-a648-46d3-8874-b22832ec57fb.png">

### 個人情報の取り扱いについて
<img width="644" alt="スクリーンショット 2022-03-15 13 06 33" src="https://user-images.githubusercontent.com/82350582/158304430-28eee4a7-9b13-43fd-aba6-a4b5de82e5d1.png">

## 関連するIssue
[会社概要の住所を更新](https://github.com/fjordllc/bootcamp/issues/3766)

**Comment by komagata** [comment]
:memo: fjord.jp の方は僕の方で修正致しました。

**Comment by Nabegon** [comment]
@komagata さん

承知しました！ありがとうございます！
