### ISSUE TITLE
[相談部屋]（受講者）相談部屋でメンションがあったときのメッセージを変更したい

### ISSUE THREAD

**Issue by IkumaTadokoro** [fjordllc/bootcamp#4409]
## 機能の説明

相談部屋で管理者から受講者にメンションがあったときは、相談部屋でメンションがあった旨がわかるような通知内容にしたい。

### 現状

![CleanShot 2022-03-15 at 15 36 18](https://user-images.githubusercontent.com/61409641/158320891-b94ecfaf-aebe-4316-a5ef-a9b5bdab8035.png)

相談部屋で管理者からメンションがあった場合の通知は「へのコメントで〇〇さんからメンションがありました」となっています。

### メッセージ案

相談部屋でメンションがあったことが分かればなんでもいいですが、参考までに以下のような文言であれば伝わると私は思います。

1. 「相談部屋へのコメントで〇〇さんからメンションがありました」（現状のテンプレート踏襲、実装がすぐ終わると思う）
2. 「相談部屋で〇〇さんからメンションがありました」（相談部屋にはコメントしかないので、そこを削減した形。）

#4086 での対応と合わせると、2がよいかな〜と思っています（受講者にとって相談部屋は1つなので、「〇〇さんの」は不要）

### 関連Issue

#4086

## 何故この機能が必要なのか

「何に対してのコメントかわからない」、また「文言として変なので、バグが発生しているのかと錯覚する」ため。

**Comment by rosh-1228** [comment]
2つ確認させてください。
## 1. 現状の仕様では、相談部屋で管理者から受講者にメンションがあった場合は、「へのコメントで〇〇さんからメンションがありました」という文言で通知が来るのでしょうか？

> 相談部屋で管理者からメンションがあった場合の通知は「へのコメントで〇〇さんからメンションがありました」となっています

上記のようにありますが、ローカル環境(devlopment)で管理者が受講者に相談部屋でメンションを送った時に、「へのコメントで〇〇さんからメンションがありました」という文言ではなく、「○○さんからコメントが届きました」という文言で通知されます。
![_development__通知___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64620506/167043845-f445f9f1-42a5-41c0-a9a0-f764311d0c6a.png)

受講者から管理者へメンションを送った場合は、- #4086 で実装されている通りの文言で通知がきます。

メンションあるなしに関わらず、相談部屋にてコメントを行うと以下の2通りだけを確認しているのですが、間違っておりましたらご教示いただきたいです🙇‍♂️
| コメントの送り先 | 送り先の人に通知される文言 |
| --- | --- |
| 管理者⇨受講者 | ○○さんからコメントが届きました |
| 受講者⇨管理者 | ○○さんの相談部屋で○○さんからコメントが届きました。 |

## 2. 相談部屋で管理者から受講者へメンションを送った時に「へのコメントで〇〇さんからメンションがありました」という文言で通知が来ない場合

本issueでは、相談部屋でメンションがあった場合、以下のように変更するということ良いでしょうか？

| メンションの送り先 | 現状 | 変更後 |
| --- | --- | --- |
| 管理者⇨受講者 | ○○さんからコメントが届きました | 相談部屋で〇〇さんからメンションがありました |
| 受講者⇨管理者 | ○○さんの相談部屋で○○さんからコメントが届きました。 | ○○さんの相談部屋で〇〇さんからメンションがありました(追加の仕様) |

**Comment by IkumaTadokoro** [comment]
手元からbootcampの開発環境をリセットしてしまった&現状の開発状況を追い切れていないので、一旦ユーザとして確認した情報を先に共有させていただきます！（つまり確認事項1に対する返答です）

他の情報も確認次第、別途共有させていただきます。

---

Issueをたてた2022/03/15時点では、次のような通知が来ていました。
- 管理者からのメンション付きコメントは「へのコメントで〇〇さんからメンションがありました」と通知（スクリーンショットは本番環境で実際に発生しているものです）
- メールも同様の文言
- 分類は「メンション」タブ

![CleanShot 2022-05-06 at 19 47 23](https://user-images.githubusercontent.com/61409641/167117693-43018e6a-241a-4703-9dcc-8dec13f21cf4.png)

そこからしばらくメンションがなかったのですが、2022/04/27時点ではメンション付きコメントでは次のような状況でした。
- そもそも通知欄に通知が残っていない
- メールは「○○さんからコメントが届きました」で届いている

---

上記仕様の変遷から、3/15~4/27までの間に「相談部屋ではメンションがあっても、メンションとして扱わないようにする」変更が入ったのではないかと推測します。

そうだとすると、

- 確認事項1についてはその仕様変更によって文言が変わった
- 確認事項2については、（仕様変更の経緯に依存するものの）メンションとして扱わないように変更したのであれば、メッセージもメンション用にする必要はない（変更不要）

と言えそうです。

...とユーザ側から見える部分から推測でコメント書いてしまっているので、一応裏取りします🙏

**Comment by rosh-1228** [comment]
@IkumaTadokoro 
調査までいただきありがとうございます！
#4425 にてメンションできないようになっていたところまで、追いきれていませんでした💦

メンションできないようになっているということは、そもそも相談部屋ではメンションが必要がないということですね。
受講者側からすると、誰がコメントしてくれたかが重要だと思いますので、ikumaさんのとおり、`相談部屋で〇〇さんからコメントがありました`へ通知の文言を変更すれば良いだけかなと思います。

私がそこまで提案しなければいけなかったです🙇‍♂️
ありがとうございます。

@machida 
ikumaさんの調査・ご意見、私の意見踏まえまして、以下のように変更を行うべきかなと思いますがいかがでしょうか？

| 相談部屋でコメントする人 | 通知を受け取る人 | 現状の通知の文言 | 変更後の文言 |
| --- | --- | --- | --- |
| 管理者 | 受講者 | ○○さんからコメントが届きました | 相談部屋で〇〇さんからコメントがありました |
| 受講者 | 管理者 | 相談部屋で○○さんからコメントが届きました。 | 現状のまま #4086 |

**Comment by machida** [comment]
@IkumaTadokoro

ありがとうございます！
なるほど、こんなコミットがマージされてたとは。全く気づいてませんでした。調査めちゃくちゃ助かります🙏
修正案も納得です！これで行こうと思いますー

@rosh-1228

修正案ありがとうございます！
これでお願いします🙏
やりとりありがとうございます！

**Comment by komagata** [comment]
@machida @IkumaTadokoro @rosh-1228 

https://github.com/fjordllc/bootcamp/pull/4425

こちら、相談部屋でメンション通知のメールが飛ぶと、他の人が見れないはずの内容がメール本文経由で見えてしまうという障害があったので急いで修正したものになります。
