### ISSUE TITLE
検索結果一覧でWIPの日報やDocsを識別できるようにしたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4420]
キーワード検索で日報などを検索すると、WIPの日報も提出済みの日報も同じスタイルで出力されるため、区別がつきづらい。
日報一覧のようにWIPはWIPであることがわかるようなスタイルになっていると、「これはWIPだからまたあとでチェックしよう」と思えるので、クリックする手間が省けそう。

参考：上は検索結果一覧、下は日報一覧

<img width="713" alt="Screen Shot 2022-03-16 at 7 44 57" src="https://user-images.githubusercontent.com/1148320/158485020-22d06dbb-f11b-4ac9-8f62-57ea5eeec1ad.png">

**Comment by eatplaynap** [comment]
@JunichiIto 
お疲れさまです。こちらのIssueの仕様について確認させてください！
#4501 の「変更後」のように実装したのですが、日報一覧のWIPだとアイコン画像もグレーアウトしているように見受けられます。
検索一覧のアイコンも日報と同じようにグレーアウトするよう対応したほうがよいでしょうか？

**Comment by JunichiIto** [comment]
@eatplaynap 対応ありがとうございます！

> 検索一覧のアイコンも日報と同じようにグレーアウトするよう対応したほうがよいでしょうか？

いえ、これでも十分識別できるので全然問題ありません〜 🙆‍♂️

**Comment by eatplaynap** [comment]
@JunichiIto 
ご確認ありがとうございました！
それでは今のコードでメンバーにコードレビューの依頼をしようと思います:pray:

**Comment by eatplaynap** [comment]
本番環境で動作確認できたのでcloseします〜

**Comment by JunichiIto** [comment]
ご対応どうもありがとうございました！！ 😄
