### ISSUE TITLE
検索結果がユーザーの場合にユーザーアイコンが出てほしい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4421]
似た名前の人が多く、アイコンがあると判別しやすいため。
（管理者はユーザーを検索することがたくさんあるため）

**Comment by JunichiIto** [comment]
これ、欲しいかも！staleラベル外しておきます。

**Comment by machida** [comment]
@tomonariha 

<img width="707" alt="貼り付けた画像_2022_06_10_12_19" src="https://user-images.githubusercontent.com/168265/172983765-47e7c9f3-5d91-4b46-96d2-1ce021029e01.png">

ユーザーの場合は、この部分にアイコンが表示されるようにお願いします。
デザインはmachidaがやるので、アイコンが表示されるようになったらメンションをお願いします。

**Comment by tomonariha** [comment]
本番環境で動作確認できましたので、closeします。
