### ISSUE TITLE
企業研修のユーザーのための研修の終了日をユーザー情報として登録したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4426]
管理者でログインをして、ユーザーの編集画面にいくと、

<img width="568" alt="image" src="https://user-images.githubusercontent.com/168265/158613200-b8a39426-f7a9-4de1-ba61-835d5549d50d.png">

こういう入力があります。

研修生はここにチェックが入っていて、研修生として登録されています。
このブロックが管理者しか表示されないので、このチェックは管理者しか入れることができません。

---

`https://bootcamp-staging.fjord.jp/users/new?company_id=24043549&role=trainee&token=test`

こんな感じで会員登録のページにパラメータを渡すと、最初から所属企業やroleが入力された状態で会員登録ページが開きます。研修生登録の場合は、企業にこのURLを渡し、そのURLから登録をしてもらっています。

なので、管理者しか研修生のチェックボックスに入力ができないのですが、代わりにパラメータを渡してチェックが入った状態のフォームに誘導しています。

---

研修生のチェックが入っていた場合、今回新たに追加するこのブロックが表示されるようにしてください。

<img width="661" alt="貼り付けた画像_2022_03_16_23_34" src="https://user-images.githubusercontent.com/168265/158614283-47a3bf40-5e6d-48d0-9848-e78e830d75a8.png">

このブロックは管理者でなくて、登録者本人にも表示されるようにしたいです。

その際、前途したパラメータを持ったURLから研修生は登録するので、チェックが入っていたらこのブロックが表示される、という動きは、JavaScriptでチェックが入ったら表示されるように実装をお願いします。

**Comment by niikz** [comment]
@machida 
仕様に関して質問があります！お手すきの際にご確認お願いいたします🙏

1. 研修終了日のカラムはDate型の認識であたっていますでしょうか？

2. 研修終了日を登録できるユーザーは管理者・研修生の両方またはどちらかでしょうか？
※研修情報のブロックは、管理者・研修生の両方に表示しています。

**Comment by machida** [comment]
@niikz 

> 1.

Date型でお願いしますー
年月日を入力、表示します。

> 2.

管理者と研修生(本人の情報のみ)でお願いします🙏

**Comment by niikz** [comment]
@machida 
早速のご確認ありがとうございます！！下記の通り対応いたします〜！

1. 研修終了日のカラム
→ Date型。年月日を入力、表示できるようにする。

2. 研修終了日を登録できるユーザー
→ 管理者と研修生(本人の情報のみ)

**Comment by niikz** [comment]
研修生・管理者ともに本番環境で確認いただいたのでcloseします。
