### ISSUE TITLE
プラクティスのステータスが提出しても【提出】にならない

### ISSUE THREAD

**Issue by napple29** [fjordllc/bootcamp#4428]
## 概要
プラクティスの提出物を出しても、ステータスが提出にならない現象が起こっています。

## 再現手順

本番環境で発見したバグですが、開発環境でも確認できたのでそちらの手順を記載します。

1. bootcampアプリの最新mainブランチをローカルで立ち上げる
2. ユーザー`kimura`でログイン
3. プラクティスページ`/courses/829913840/practices#category-917504053`にて 【Terminalの基礎を覚える】のステータスが未着手であることを確認
4. 【Terminalの基礎を覚える】の提出物一覧`/practices/198065840/products`に、すでにkimuraの提出物がある。

また、私の場合はあるプラクティスが着手中の時に別のプラクティスを提出し、後者のステータスが提出に変わらなかったので、開発環境でも、
- 他のプラクティスが着手中の場合
- 他のプラクティスに着手中がない場合

の２通りを試しましたが、どちらの場合でも提出中のプラクティスのステータスは【提出】になりませんでした。

## 期待される振る舞い

提出物を出したらステータスが提出になる

## スクリーンショット

![image](https://user-images.githubusercontent.com/82350582/158718914-de3052f9-7634-4f21-b7aa-bbd81158fdd7.png)
![image](https://user-images.githubusercontent.com/82350582/158719163-f54f9522-0772-4475-b371-0104568033d9.png)

## 環境

 - OS: macOS BigSur
 - ブラウザ: chrome
 - バージョン: 11.5.2

**Comment by machida** [comment]
以前、あらゆるIssueを着手にしつつ、つまみ食いで進める人が時々いたのですが、そのように進めた人で卒業できた人がいなかったので、プラクティスは一つしか進められないように仕様変更をした、ということがありました。

なので、着手は一つのプラクティスしかできないのだけど、複数のプラクティスの提出はできるように仕様自体を変更する必要があります。その変更によって、どこか不具合が起きないかなどの確認が必要そう（ユーザーごとの現在のプラクティスの表示や、プラクティスごとの今着手中のユーザー一覧など）。

**Comment by yocajii** [comment]
本番環境で動作確認できましたので、クローズいたします。
