### ISSUE TITLE
[相談部屋]相談部屋個別ページを開いたら、最新のコメントの位置までスクロールされてほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4437]
js で実装するか、個別ページへのリンクにアンカーを追加するか（href の url に #xxx を付ける）はMTGで話し合いましょう。

**Comment by komagata** [comment]
:memo: `#latest-comment`みたいな固定のアンカーを入れておいて、相談部屋へのリンクはそこへのリンクに変えると良いかも。

**Comment by machida** [comment]
固定のアンカーをつけて、相談部屋個別へのリンクはそこへのリンクに変える、という対応でお願いします🙏

**Comment by clio209** [comment]
本番環境で確認できたのでcloseします〜
