### ISSUE TITLE
サイドバーの日報のもっと見るボタンのページ遷移に関するDiscussion

### ISSUE THREAD

**Issue by yoshino** [fjordllc/bootcamp#444]
## 現状

もっと見るボタンをクリックすると、/reportsが表示される。

![screenshot from 2018-08-04 10-41-14](https://user-images.githubusercontent.com/17586662/43671338-f92acb5c-97d2-11e8-8c96-5a86af3add2b.png)

## 代案
もっと見るボタンを押すと、”サイドバーの見える日報が多くなる”あるいは以下のように
ページ遷移する方がわかりやすいのではないかと思いISSUEにしました。

もっと見るボタンを押すと、

https://bootcamp.fjord.jp/reports?page=2

さらにクリック！

https://bootcamp.fjord.jp/reports?page=3

みたいに遷移する。

**Comment by yoshino** [comment]
うーむ。

個人的には動作が気になったので、この挙動が実際に望んでいるものならCLOSEすれば良いし、そうでないならISSUEとして残せばいいかなと思って書きました。

こういうスタンスは間違っているのかもしれませんね。
なんかすいません。

時間おいてCLOSEします。

**Comment by sanfrecce-osaka** [comment]
@yoshino 
あーすみません、ちょっと伝わってなかったですかね。
言いたかったのはissueを書く前にコードを確認してから書きましょう、ということとtitleがちょっと不適切ではないかな？ということです。
issueをcloseする必要はないですよ。
ただtitleは修正したほうがいいかも。
ちょっと急用ができたのでまた後ほどコメントしますねー。

**Comment by komagata** [comment]
@yoshino @sanfrecce-osaka ソースを見てからIssue作成できればBetterですが、必須ではないです。（ソース読めないと誰もIssue作れなくなってしまう）

僕もタイトルは不適切だと思います。「おかしい？？」という言葉はよくわからないときは使わないほうが良いと思います。他の表現もあるので。

それこそ、作った人にとっては「は？想定通りなんだけど？」などと要らぬトラブルを生みそう。

**Comment by yoshino** [comment]
タイトルの方変更しました！

**Comment by komagata** [comment]
@sanfrecce-osaka 言ってることはわかります。そうじゃなくて、言い方です。

あくまで @yoshino さんと @sanfrecce-osaka さんは同じく学んでる仲間なので、上から「ソース読め」的なこと言われたらムカついても仕方ないように思います。

例えば、

```
リンク先が`reports_path`になってるので想定通りなのかもです。
```

とかでも良いわけで。

仕事の開発プロジェクトだったらこれだけで雰囲気最悪ではじまっちゃいそうです。

Team Geekにあるように、自分が絶対に正しいという考えに固執せず、相手へのリスペクトを持って接するべきだと思います。

[Team Geek ―Googleのギークたちはいかにしてチームを作るのか \| Brian W\. Fitzpatrick, Ben Collins\-Sussman, 及川 卓也, 角 征典 \|本 \| 通販 \| Amazon](https://www.amazon.co.jp/dp/4873116309)

**Comment by sanfrecce-osaka** [comment]
@komagata 
上から言ってるつもりはないんですがそう伝わってしまってしまいましたか・・・。
急いで書くとどうしても伝え下手がでてしまう・・・。
自分の1番はじめのコメントも上から目線に聞こえてしまうでしょうか？

@yoshino 
気を悪くされましたでしょうか？
本当に申し訳ないです・・・。

**Comment by yoshino** [comment]
ISSUE１つにしても様々な意見があるので、そうした問題を回避するためには雛形とかを使ったらいいかもしれませんね。

この議論をみた他のインターン生がISSUEを出すハードルをすごく高く感じてしまうのではと危惧します。それはISSUEのあるべき形では無いと思います。

正直、気分を害しましたｗ。

でも、僕は@sanfrecce-osakaさんと直接話したこともありますし、自分なりに心の中で落とし所を見つけることができます。

僕もプログラミングが好きで、日々切磋琢磨していきたいと思っています。
お互いがんばっていきましょう！

**Comment by machida** [comment]
@yoshino @sanfrecce-osaka @komagata 

すいません、議論に入るのが遅れました。「もっと見る」をクリックした後の動きは吉野さんの考える通り、 https://bootcamp.fjord.jp/reports?page=2 へリンクを貼る方が圧倒的に使い勝手がいいです。

ただ、https://bootcamp.fjord.jp/reports?page=2 へリンクを貼る場合、

- seedに日報が26件以上入ってないので、ローカルで立ち上げたときに存在しないページへリンクが貼られてしまう（テストでもそう？）
- 26件以上日報がある場合のみ、「もっと見る」のリンクを出したいが、26件の26は変数にしたい
- ここに関するテストも欲しい

...と考えた結果、面倒なので今の段階では report_path にリンクを貼っておきました。
でも、やっぱり理想は  https://bootcamp.fjord.jp/reports?page=2 へリンクを貼ることです。

サイドバーの中身に変化が起きるパターン、もっと見るをクリックするともっと日報が表示されるのはやらなくていいかなー。そこまで日報を見たい場合は日報を見る気満々になってるので、メインカラムで日報を探したいかも。

ということで、この議論はcloseして、もっと見るのリンク先を https://bootcamp.fjord.jp/reports?page=2 にする issue を作っておきます。

issue作りました！
https://github.com/fjordllc/bootcamp/issues/450
