### ISSUE TITLE
コメント欄のスタンプ一覧が見切れている

### ISSUE THREAD

**Issue by napple29** [fjordllc/bootcamp#4440]
## 概要
コメント欄のスタンプ一覧が見切れている状態です。
![image](https://user-images.githubusercontent.com/82350582/158941518-e9cbaac6-bc56-4fbb-99fb-79bcc0be2273.png)

日報、Q&A、Docs、イベントページの確認をしましたが、全てコメント欄のみスタンプ一覧が見切れていました。
## 再現手順

1. 上記の該当ページにアクセス
2. コメント欄のスタンプを押す
3. スタンプ一覧が見切れているのが確認できる

## 期待される振る舞い
スタンプ一覧が見切れずに全て見られる。

**Comment by machida** [comment]
こちら修正しましたー🙇‍♂️
