### ISSUE TITLE
エラーで表示されないメールのプレビュー画面がある

### ISSUE THREAD

**Issue by tksmasaki** [fjordllc/bootcamp#4441]
## 概要
現在、以下の4つのプレビューが機能していません。

http://localhost:3000/rails/mailers/notification_mailer/came_answer
http://localhost:3000/rails/mailers/notification_mailer/consecutive_sad_report
http://localhost:3000/rails/mailers/notification_mailer/mentioned
http://localhost:3000/rails/mailers/notification_mailer/moved_up_event_waiting_user

おそらく fixtures に必要なデータが入っていないことが原因の1つだと思います。

## 再現手順

上記のURLにアクセスする。

## 期待される振る舞い

プレビューが表示される。

**Comment by siroemk** [comment]
マージされたのでcloseします！
