### ISSUE TITLE
全てのリアクションボタンを押せるか、のテストを追加する

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4445]

**Comment by taka110-IT** [comment]
@machida 
仕様についての確認です。
`/test/system/reactions_test.rb` にすでにリアクションのテストがありますが、同様に全てのリアクションに対してpostとドロップダウンからのdestroy、日報のfooterからのdestroyのテストを追加するのか、postだけの追加で良いのか、どちらでしょうか。

**Comment by machida** [comment]
@taka110-IT 
postだけで大丈夫です。今あるテストに他のボタンも全部追加をお願いします。以前、CSSの関係で一部のリアクションボタンが隠れてしまってユーザーが押せないボタンが出てしまったということがありました。それを発生させないためのテストをお願いしたいです。

**Comment by taka110-IT** [comment]
@machida 
承知しました。postだけ追加する方向で作成します。ありがとうございます。

**Comment by taka110-IT** [comment]
@machida 
[滅多に使わないネガティブなリアクションを消す\#2310](https://github.com/fjordllc/bootcamp/pull/2310)で、ネガティブな絵文字が除外されてますが、ネガティブな絵文字が表示されないテストは必要でしょうか。

**Comment by machida** [comment]
@taka110-IT ネガティブな絵文字を表に出すことはないので、テストはなくて大丈夫ですー

**Comment by taka110-IT** [comment]
@machida 
承知しました。ありがとうございます。

**Comment by taka110-IT** [comment]
PRがマージされましたのでIssueをクローズします。
