### ISSUE TITLE
「フィヨルドブートキャンプを卒業した自分はどうなっていたいかを教えてください」の欄をアドバイザー登録・編集時に非表示にしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4449]
アドバイザー登録される方で戸惑った方がいたので。

---

## 本番での確認方法

role アドバイザーでログイン。

https://bootcamp.fjord.jp/current_user/edit にアクセス。

<img width="652" alt="貼り付けた画像_2022_04_01_22_41" src="https://user-images.githubusercontent.com/168265/161275237-91b2b667-5d4f-4be1-83c7-376b4af0274b.png">

「フィヨルドブートキャンプを卒業した自分はどうなっていたいかを教えてください」という質問が表示されていなければOK。

**Comment by NorifumiOgawa** [comment]
本番での確認が取れたのでクローズとします。
https://discord.com/channels/715806612824260640/809595476847493192/959474973733449790
