### ISSUE TITLE
Q&AのAが投稿された際の通知タイトル、通知文の変更

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4450]
Q&AのA投稿の通知。

Answerの通知も現在は日報などのコメントと同じで「〜さんがコメントしました。」になっている。

Answerの通知を「〜さんが回答しました。」に変更する。

わかりやすくするため。
Q＆AのAはCommentではなくAnswer。別物であることに注意。

**Comment by machida** [comment]
ページ内通知、メール通知を修正する。

**Comment by machida** [comment]
@yocajii こちらお願いします。

**Comment by yocajii** [comment]
@machida 承知いたしました、アサインありがとうございます🙏✨

**Comment by yocajii** [comment]
@machida 
要件について確認させてください。

Q&Aに回答が付いた時の通知は、下記のようにユーザーによって文言が異なるようでした。
このIssueで対応するべきは 2 の通知という認識で合っていますでしょうか。

1. 質問の投稿ユーザーへの通知  
![image](https://user-images.githubusercontent.com/33394676/177028262-428dd7c5-04ab-4bb6-86f4-ea2901006816.png)
2. （回答者など）質問をWatch中のユーザーへの通知  
![image](https://user-images.githubusercontent.com/33394676/177028290-efe49c19-3681-4129-9de6-8303c623ef28.png)

**Comment by machida** [comment]
@yocajii 質問ありがとうございます！2の通知でお願いします🙏

**Comment by yocajii** [comment]
@machida 早速ご回答いただきましてありがとうございます！2の通知とのこと、承知いたしました🙆‍♂️
