### ISSUE TITLE
[Markdown]Markdownのエディタでdetailsを簡単に書けるようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4462]
現在、フィヨルドブートキャンプのMarkdown で details タグ（アコーディオンで開閉するやつ、ネタバレ注意などで使う）を使う場合、以下の様に書きます。

```md
<details><summary>ネタバレ注意！</summary>

## 私の書いたコード

今回はこんなコードを書きました。

</details>
```

すると、以下のHTMLが出力されます。

```html
<details>
    <summary>ネタバレ注意！</summary>
    <h2>私の書いたコード</h2>
    <p>今回はこんなコードを書きました。</p>
</details>
```

これをもっと簡単に書きたい。
以下のように書けるようにしたいです。

```md
:::details ネタバレ注意！
## 私の書いたコード

今回はこんなコードを書きました。
:::
```

- `:::details` と `:::` で囲うと、`<details>`タグで囲われる。
- `:::details`の右に半角スペースを空けて、文字列を入れると、その文字列が、`<details>`タグ内の `<summary>` タグで囲われる。
- `:::details` と `:::`  の間の中身には Markdown 記法が使える。

**Comment by machida** [comment]
- https://github.com/fjordllc/bootcamp/pull/4424
- https://github.com/fjordllc/bootcamp/pull/4496

こちらのPRを参考にしてください🙏

**Comment by clio209** [comment]
本番環境で動作することを確認しました。
