### ISSUE TITLE
[相談部屋]左メニューの相談ボタンが表示されない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4467]
![aaaunknown](https://user-images.githubusercontent.com/16577/159598128-e7b28c41-664f-4e43-a8de-e0fb5ca2964b.png)

管理者と一般の生徒以外表示されない。

特に研修生で表示されないのは直したい。

**Comment by komagata** [comment]
@machida こちらアドバイザー、メンター、研修生で表示されないようになっているのですが、全員表示させちゃっても問題ないかなと思うんですがいかがでしょう？

**Comment by komagata** [comment]
:memo: 全員表示してしまって良いという話になりました。

**Comment by Nabegon** [comment]
@komagata さん
お疲れ様です。質問があります。相談ボタンの表示を全員に出来るようになったのですが、メンターさんやアドバイザーさんなど相談が不要な人でも相談のページに遷移出来てしまいます。例えば、相談が必要な人（現役生と研修生？）は相談ページ、そうでない人は管理者画面に飛ぶようにした方が良いでしょうか。

相談ボタンの表示を制御しているファイル：`app/views/application/_global_nav.slim`
該当箇所：
```
- if admin_login? || student_login? //ここでボタンの表示の制御が行われています
          li.global-nav-links__item
            = link_to unreplied_index_path(current_user.talk), class: "global-nav-links__link #{current_link(/talk/)}" do
              .global-nav-links__link-icon
                i.fas.fa-comment-alt-smile
              - if admin_or_mentor_login? && Talk.unreplied.count.positive?
                .global-nav__item-count.a-notification-count.is-only-mentor
                  = Talk.unreplied.count
              .global-nav-links__link-label 相談
```

以上になります。ご検討のほどよろしくお願いします🙏

**Comment by Nabegon** [comment]
駒形さんから返信が来ていませんが、類似のissueで管理者以外はメンターでも相談部屋に遷移して良いとのことだったので、このまま（メンターやアドバイザーも相談ボタンを押すと相談部屋に遷移する）でチームレビュー出します。

参考にした類似のissue: 管理者でログインしたときに、ユーザー個別ページに相談部屋へのリンクを表示したい #4094
[](https://github.com/fjordllc/bootcamp/issues/4094)

**Comment by komagata** [comment]
@Nabegon 全員遷移できて大丈夫です〜
