### ISSUE TITLE
【メンター向け】メンターが未アサインの提出物にコメントしたら、担当者になったことを画面上に反映する

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4469]
## 現状の問題

メンターが未アサインの提出物にコメントしたら自動的に担当者になるが、画面上に変化がないので、担当者になったことがわかりづらい。

## 改善案

メンターがコメントを投稿したら「担当する」ボタンが黄色の「担当から外れる」ボタンに切り替わる。

<img width="790" alt="Screen Shot 2022-03-23 at 10 41 43" src="https://user-images.githubusercontent.com/1148320/159605191-569d0434-5c8a-4194-b344-f330dddf2caa.png">
<img width="709" alt="Screen Shot 2022-03-23 at 10 42 58" src="https://user-images.githubusercontent.com/1148320/159605198-40181fd4-8502-462f-88a6-a7e909d242f5.png">

あと、Toastでも「コメントを投稿しました。担当者になりました。」みたいなメッセージを表示してもいいかもしれない。

**Comment by eatplaynap** [comment]
本番環境での動作確認いただいたのでcloseします〜
