### ISSUE TITLE
質問作成中にWIPしてもDiscordに通知が行かないようにしたい

### ISSUE THREAD

**Issue by aim2bpg** [fjordllc/bootcamp#4470]
## 概要

質問作成中にWIPするとDiscordに通知が行き、それを見たユーザーが質問ページに飛んで、まだ作成中の質問であることに気付いて無駄足となってしまう。

## 再現手順

1. https://bootcamp.fjord.jp/questions/new にアクセス。
2. 「タイトル」と「質問文」を入力し、「WIP」をクリック。
3. 質問作成中にも関わらず、Discordに「質問...が作成されました。」が通知されてしまう。

## 期待される振る舞い

**質問を公開した時に、Discordに「質問...が作成されました。」が通知されること。**
現状のWIPの通知だと、下記の通知のユースケース(イメージ)の2番で多くのユーザーが無駄足となってしまうため。
1. ユーザーが通知を見て質問を知る。
2. ユーザーが質問ページに移動する。（ここで、もし質問がWIP状態だとユーザーは無駄足となってしまう）
3. ユーザーが質問に対して回答する。

## スクリーンショット

![image](https://user-images.githubusercontent.com/58363353/159603219-888ab4a7-eaae-4578-8e01-9a3e5c41666a.png)

**Comment by Paru871** [comment]
@machida @komagata 
お疲れさまです。こちらのIssueはQ&Aのwip機能追加の際の取りこぼしですので、私の方で修正させていただきます。

この修正を行なっている際に、「質問を投稿すると、メンターさん側のWatchマークをon」の機能もwip状態で働いてしまうことに気づいたのですが、こちらも同じく、wipではなく「本公開後にWatchマークをon」という挙動に修正してよろしいでしょうか？
修正してよろしければ、別Issueを立ててそのまま修正対応させていただこうと思っています。
ご指示いただきたく、よろしくお願いします🙏
![スクリーンショット 2022-03-24 8 55 41](https://user-images.githubusercontent.com/82434093/159823041-23ab9979-6a02-4b38-8126-f238093b98e5.png)

**Comment by komagata** [comment]
@machida こちらいかがでしょう？
ちょっと僕は迷ってしまって決断しあぐねております。

**Comment by machida** [comment]
@Paru871 @komagata 一旦はWIPが外れたらwatchになる、でお願いしますー🙏
WIPの状態で質問のレビューをお願いしたい場合は明示的に連絡をしてもらうようにしたいと思います。使い方についてはドキュメントに追記と、別Issueで質問作成ページにも書きますー

**Comment by Paru871** [comment]
@machida @komagata 
ご指示ありがとうございます！かしこまりました。
それでは、「WIPの場合はwatchにせず、WIPから本公開になるタイミングでwatchになる」で別Issueで修正いたします。
よろしくお願いします🙏

**Comment by aim2bpg** [comment]
@Paru871 さん、本件もDiscord通知と類似案件ですのでレビュー振っていただいても大丈夫ですよ〜🙆‍♀️

**Comment by Paru871** [comment]
本番環境にて、WIP保存時にはDiscordに通知が行かず、初の本公開時のみDiscordに通知が行くことを確認できましたので、こちらのIssueはクローズとさせていただきます。
ありがとうございました🙏
