### ISSUE TITLE
WIPの質問は未解決一覧には含めず、全ての質問一覧にだけ含めるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4474]
現在、WIP状態の質問を作ると、

未解決、全て のリストに表示される。

<img width="1358" alt="貼り付けた画像_2022_04_06_21_44" src="https://user-images.githubusercontent.com/168265/161977239-0710a09a-5ab7-4e2f-8790-30d0e9c1c5e5.png">

<img width="1341" alt="貼り付けた画像_2022_04_06_21_44" src="https://user-images.githubusercontent.com/168265/161977325-9e2bb22c-3f91-4d27-9718-85f68ac8d414.png">

これを修正して、未解決には表示せず、全て にだけ表示されるようにしたい。

**Comment by machida** [comment]
@NorifumiOgawa こちらお願いしますー🙏

**Comment by NorifumiOgawa** [comment]
本番環境で確認しました！
