### ISSUE TITLE
[Markdown]メッセージブロック機能でXSSの危険性

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4491]
https://github.com/fjordllc/bootcamp/pull/4424 の変更はXSSの危険性があります。

## 再現手順

日報に以下の文言を入力して保存する。

```
:::message "></div><a href="javascript:alert('XSS');">クリックしてね</a><div class="
メッセージ
:::
```

<img width="666" alt="Screen Shot 2022-03-24 at 19 36 57" src="https://user-images.githubusercontent.com/1148320/159898476-3902d26e-08a5-4f4e-84cb-ef4924882058.png">

保存後のリンクをクリックするとJavaScriptが実行される。

<img width="771" alt="Screen Shot 2022-03-24 at 19 39 18" src="https://user-images.githubusercontent.com/1148320/159898739-99f1da39-867d-4283-aae7-04412b913058.png">

## 対処方法（案）

`.*`の代わりに有効なclass名をリストアップする。

```diff
diff --git a/app/javascript/markdown-it-container-message.js b/app/javascript/markdown-it-container-message.js
index c22406b6b..c6607e04f 100644
--- a/app/javascript/markdown-it-container-message.js
+++ b/app/javascript/markdown-it-container-message.js
@@ -3,7 +3,7 @@ import MarkdownItContainer from 'markdown-it-container'
 export default (md) => {
   md.use(MarkdownItContainer, 'message', {
     render: (tokens, idx) => {
-      const messageInfo = tokens[idx].info.trim().match(/^message\s+(.*)$/)
+      const messageInfo = tokens[idx].info.trim().match(/^message\s+(alert|danger|warning|info|primary|success)$/)
       const messageName = messageInfo ? ` ${messageInfo[1]}` : ''
       if (tokens[idx].nesting === 1) {
         return `<div class="message${messageName}">\n`
```

## 備考
XSSとは直接関係ありませんが、正規表現の`.*`や`.+`を便利なワイルドカードとして使うと、ReDoS攻撃の脆弱性につながったりすることもあるので、`.`（任意の文字）ではなく、`\w`や`[^>]`など、なんらかの形で有効な文字種を制限した方が良いです。

**Comment by eatplaynap** [comment]
@komagata
こちらのご指摘で、修正PRを伊藤さんがIssueに書いてくださった案(`message` のあとに有効なクラス名`alert|danger|warning|info|primary|success` を限定させる)で対応するPRを作ろうかと思っているのですが、この場合のテストはどう書くべきか迷っています。
1. `alert|danger|warning|info|primary|success` 以外のクラス名を指定した際、無視されて`message` というクラス名になる
2. `message` 以下で伊藤さんの行った再現通りにXSSを行おうとすると、無視されて`message` というクラス名になるのでXSSが行えない

PRでの対処自体は1なのですが、1を何のために行うのかを明示した方がよいのか、もしくは2では冗長なのかが自分で判断できないのでアドバイスをいただけるとありがたいです:pray:

**Comment by komagata** [comment]
@eatplaynap ご連絡ありがとうございます。

バグ修正にはそれを防ぐ（修正前は失敗して、修正後は成功する）テストが必要で、それの主題はそのバグについてなので2がいいと思います〜。

**Comment by eatplaynap** [comment]
@komagata アドバイスありがとうございます〜！
それでは2の方向でテストを書いてみようと思います！

**Comment by machida** [comment]
Issue: https://github.com/fjordllc/bootcamp/pull/4496

**Comment by eatplaynap** [comment]
本番環境で動作確認できたのでcloseします！！
