### ISSUE TITLE
卒業生のダッシュボードに「卒業後の目標」の入力を促すブロックは表示しない

### ISSUE THREAD

**Issue by fugakkbn** [fjordllc/bootcamp#4505]
## 概要
現在、卒業後の目標が未入力の場合「フィヨルドブートキャンプを卒業した自分はどうなっていたいかを登録してください。」というアナウンスがダッシュボードに表示されます。

<img width="1650" alt="スクリーンショット 2022-03-26 0 22 31" src="https://user-images.githubusercontent.com/58870882/160151338-cfb12c17-d631-400a-8109-9426ca8d187e.png">

こちらは性質上受講生向けのものであり、卒業生のダッシュボードには表示しなくて良いと思うので、表示をなくしたいです。

## 確認事項
#4449 にもあるように、卒業生以外のロールでも表示すべきでないロールがあります。
それらのロールでの表示状況がどのようになっているかを確認する必要があります。

**Comment by siroemk** [comment]
@fugakkbn 
お久しぶりです〜😄
こちら本日リリースしましたので、お手隙の際に、本番にて「卒業後の目標」が出なくなったかご確認いただけますでしょうか。
よろしくお願いします〜！

**Comment by fugakkbn** [comment]
@siroemk 
お久しぶりです！
本番環境で表示されていないことを確認しました。
実装ありがとうございました！

**Comment by obregonia1** [comment]
自分も表示されないこと確認できました〜
ありがとうございます！

**Comment by siroemk** [comment]
@fugakkbn @obregonia1 
おふたりともご協力ありがとうございました〜😊
本番環境で確認していただいたので、closeします！
