### ISSUE TITLE
ブログ投稿・修正時に投稿者を選べるようにしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4513]
choice.jsを使うようにしたい。

管理者でログインしたときのアカウント情報で、所属企業選択部分で既に使われているので、そちらを参考にしてください。

**Comment by niikz** [comment]
@machida 
仕様に関して質問があります！お手すきの際にご確認お願いいたします🙏 

ブログの投稿者として選択できるユーザーは下記のどちらがよろしいでしょうか？
1. 管理者・メンターのみ（ブログを投稿・修正できるのは管理者・メンターのみのため）
2. 退会者を除く全員

参考にしたDocs作成のページでは、（管理者・メンターでログインした場合）退会者を除く全員から投稿ユーザーを選べるようになっていたため改めて確認させてください〜🙇

**Comment by machida** [comment]
@niikz

管理者とメンターでお願いしますー🙏
Docsはフィヨルドブートキャンプ内向けのドキュメントなので、フィヨルドブートキャンプコミュニティの全員が書いたり編集できるようにしてるのですが、ブログは対外的なものなので、管理者とメンターだけが関わるように今のところしてるからですー

**Comment by niikz** [comment]
@machida 
早速のご確認ありがとうございます🙇 
ブログの投稿者として選択できるユーザーは **管理者・メンターのみ** で対応いたします〜！

**Comment by niikz** [comment]
@komagata @machida 
お疲れさまです。お手数ですが、本番環境での動作確認をお願いいたします🙏

**Comment by komagata** [comment]
@niikz 本番環境で動作することを確認しました。

**Comment by niikz** [comment]
@komagata 
ご確認ありがとうございました！

本番環境で確認いただいたのでcloseします。
