### ISSUE TITLE
スマホで日報を見たときの「見たよ」のアイコンが潰れて表示されている

### ISSUE THREAD

**Issue by neko314** [fjordllc/bootcamp#452]
アイコンの数が少ないときれいな円ですが、多いと左右が圧縮されたような円になるみたいです。

![image](https://user-images.githubusercontent.com/29836309/43816553-4bea5f8e-9b10-11e8-84c0-7e27d48406ce.png)

**Comment by machida** [comment]
開発環境でこの現象を再現させるために

- seedのユーザーを21人以上増やす
- 見たよ、が20人付いてる日報を作る

も含めてやりたいです。

**Comment by shibaaaa** [comment]
こちら対応済のようなのでクローズしておきます〜
