### ISSUE TITLE
アドバイザー招待リンクのthの文言を変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4533]
adminでログインして、ここにアクセス
http://localhost:3000/admin/companies

<img width="966" alt="貼り付けた画像_2022_03_30_22_32" src="https://user-images.githubusercontent.com/168265/160846696-6d122f62-c41d-4eac-8cc8-a2a66b726ddd.png">

「リンク」を「アドバイザー招待」に変更。

**Comment by rosh-1228** [comment]
本番環境で動作確認いただいたのでcloseします。
