### ISSUE TITLE
[定期イベント]定期イベント一覧、個別、作成、削除がほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4537]
events は使われているので、regular_events に。

輪読会、質問タイム、開発MTG、自作サービス進捗報告会などをこれで管理する予定です。

regular_event が持つ情報は、

- イベントタイトル（XXX輪読会）
- 開催日時（毎週火曜16:00から17:00まで）
- 祝日は開催するか？（boolean）
- オーガナイザー（複数人登録）
- イベントの説明
- イベントは終了したか？（boolean）

events にタブを用意して、定期イベント一覧に行けるようにします。

<img width="1663" alt="貼り付けた画像_2022_04_06_14_47" src="https://user-images.githubusercontent.com/168265/161905804-782898fc-91da-47f3-8401-83bf94d4f3d8.png">

**Comment by siroemk** [comment]
開発mtgや質問タイムにお話したことをメモしておきます
- 開催日時（毎週火曜16:00から17:00まで）のカラムはどうする
   - 時間(16:00から17:00など)はTime型を使う
   - 曜日についてはファーストリリースの段階では自由記入（text型）
   - 曜日は今後変える可能性あり
- 現在存在しているイベントでは作成時にはwipにし、管理者やメンターが公開するようになっているが、定期イベントも同じ運用にするか
  - 定期イベントはwipではなく、ユーザーが作成できるようにして良い

**Comment by siroemk** [comment]
本番環境で確認したのでcloseします！
