### ISSUE TITLE
ダッシュボードにあるWatch中の一覧に何も表示がされない

### ISSUE THREAD

**Issue by saeyama** [fjordllc/bootcamp#4538]
## 概要

- メンターもしくは管理者でログインした際、提出物があるプラクティスをWatchしてから、ダッシュボードにあるWatch中のタブをクリックしても何も表示がされない。
- ローカル環境とステージング環境のみ。本番環境では問題なく表示されているとのこと（駒形さん・町田さん確認済）

## 再現手順

1. メンターか管理者でログイン。
1. 右上のMeからダッシュボードをクリック（Watch中タブがないことを確認）。
1. 提出物があるプラクティスをWatchする。
1. ダッシュボードのWatch中のタブをクリック。

## 期待される振る舞い

ダッシュボードのWatch中タブをクリックするとWatchしている一覧が表示される。

## スクリーンショット

- 何もWatchしていない状態だと、Watch中タブは表示されない。
![image](https://user-images.githubusercontent.com/64824195/160858110-50e7b3d4-63e9-4822-8d5b-871bc7d433dc.jpg)

- 提出物があるプラクティスを`Watch`
![image](https://user-images.githubusercontent.com/64824195/160858470-e2977fd5-0ef0-43cb-b969-c76e5c35908c.jpg)

- ダッシュボードにWatch中のタブが出ているが、クリックしても何も表示されない。
(ローカル環境/メンター↓)
![image](https://user-images.githubusercontent.com/64824195/160869429-31d936a6-9cc1-4582-8eb7-8701799f66ed.jpg)
(ローカル環境/管理者↓)
![image](https://user-images.githubusercontent.com/64824195/160868944-e203cae0-7da0-4f51-90b2-34d572372ac2.jpg)
(ステージング環境/メンター↓)
![image](https://user-images.githubusercontent.com/64824195/160869968-b4a00e41-5017-489e-a543-bd3c4432dda5.jpg)
(ステージング環境/管理者↓)
![image](https://user-images.githubusercontent.com/64824195/160868235-ef3364d0-06f6-492e-ae07-f911fdd077ed.jpg)

**Comment by SatoshiHaramura** [comment]
【アップデート情報】
6/15(水)に町田さんにて本番環境を確認して頂いたところ、本番環境でも同様の事象が発生していることが判明した。

**Comment by SatoshiHaramura** [comment]
@komagata @machida 
お疲れ様です。
本番環境で動作確認を行なって頂きたく連絡致しました🙏(メンター機能のため)
確認手順と確認内容は以下の通りとなります。

確認手順と確認内容
1. プラクティス詳細ページ(/practices/:id)にアクセスし、Watchボタンをクリックする。
2. プラクティス以外(何でもよい)の詳細ページにアクセスし、Watchボタンをクリックする。
3. Watch一覧ページ(/current_user/watches)にアクセスし、watchした対象(プラクティスとその他)が一覧で表示されることを確認する。
4. watch対象がプラクティスの場合、プラクティスの作成者のログイン名は(存在しないため)表示されないことを確認する。

**Comment by SatoshiHaramura** [comment]
本番環境での動作確認が完了したため、close致します。
