### ISSUE TITLE
ダッシュボードのGitHubの草にローディングの表示が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4541]
読み込みに少し時間がかかるのでローディング中の表示と処理が欲しい

<img width="655" alt="スクリーンショット 2022-03-31 15 08 55" src="https://user-images.githubusercontent.com/16577/160987916-4c1a2bbf-b140-47c3-a681-7141e05e48fe.png">

**Comment by machida** [comment]
:memo:
`images/loading/github-grass-loading.svg` 画像を用意済

**Comment by komagata** [comment]
@machida ありがとうございます！

**Comment by machida** [comment]
@tomonariha ローディング中に表示する仮のdivを作成してください。そのdivのデザインはmachidaが行うので、仮のdivができたらメンションをお願いします。

**Comment by tomonariha** [comment]
本番環境で動作確認できましたので、closeさせていただきます。
