### ISSUE TITLE
ダッシュボードに「完了してないプラクティス」一覧も欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4542]
現状、"完了しているプラクティス 76 / 89" のような表示があるが、残っているプラクティスがどれなのかがわからないので、完了していないプラクティスの一覧も欲しい。

<img width="645" alt="スクリーンショット 2022-03-31 15 10 52" src="https://user-images.githubusercontent.com/16577/160988118-17be577e-4d97-413a-81f4-154c8bb1f562.png">

現状の"完了しているプラクティス"に"完了してないプラクティス"のようなタブを追加するイメージ。

完了してないプラクティスは、選択しているコースのすべてのプラクティスではなく、その中でも「進捗に含める」フラグがONになっているものだけを表示する。

**Comment by machida** [comment]
終わっていないプラクティスの一覧はプラクティスページで見れるので、この画面で残りのプラクティスを確認したいケースは現在では発生していないのでクローズにします。
