### ISSUE TITLE
Docs作成時のDiscord通知をタイトルだけにする

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4547]
現状、Docsを作成すると本文がすべてDiscordに通知されます。

<img width="664" alt="Screen Shot 2022-04-02 at 14 15 39" src="https://user-images.githubusercontent.com/1148320/161367643-c8a278e4-b416-434c-8108-c8c07faa1c1f.png">

ちょっと長すぎるので、Q&Aのようにタイトルとリンクだけ載せれば十分かなーと思います。

例

```
Docs: 「!が付く破壊的メソッドの使用は原則として避ける」が作成されました
https://bootcamp.fjord.jp/pages/do-not-use-destructive-method
```

**Comment by siso25** [comment]
本番での動作確認ができましたので、こちらのissueをCloseします。
