### ISSUE TITLE
カテゴリー並び替えで空のスラッグの行を削除したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4563]
管理画面のコース > カテゴリーの並び替えで下記のようにスラッグの行が空で無意味なので削除したい。

<img width="1579" alt="スクリーンショット 2022-04-05 20 08 45" src="https://user-images.githubusercontent.com/16577/161741587-2981f7ba-b191-4dbe-85de-e0d2f5d8c569.png">

**Comment by siroemk** [comment]
本番環境で確認していただいたのでcloseします🙆‍♀️
