### ISSUE TITLE
日報の一覧と詳細で確認スタンプが異なる

### ISSUE THREAD

**Issue by udaikue** [fjordllc/bootcamp#4566]
## 概要

日報の一覧と日報詳細で確認スタンプが異なっています。

## 再現手順
https://bootcamp.fjord.jp/reports/50943 の日報について、日報を開いたときの確認スタンプと一覧での確認スタンプでメンターが異なっています。

![スクリーンショット 2022-04-05 21 53 27](https://user-images.githubusercontent.com/58643754/161764448-5bd3e3c0-bccd-425c-ac37-256bff356af4.png)

![スクリーンショット 2022-04-05 21 55 42](https://user-images.githubusercontent.com/58643754/161764467-afebd256-0260-426b-b8a9-ed502a8d9cfc.png)

## 環境

 - OS: MacOS
 - ブラウザ: chrome

**Comment by niikz** [comment]
machida さん、komagata さんに本番環境で確認いただいたのでcloseします。
