### ISSUE TITLE
[定期イベント] 明日開催される定期イベントの一覧をDiscrodで通知してほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4572]
Discordの「お知らせ」チャンネルに、明日開催される定期イベントの一覧を以下のような形でDiscrodで通知したい。

```
⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️

【イベントのお知らせ】

明日 12月12日（月）に開催されるイベント。

--------------------------------------------

XXXXX会
時間: 12:00 〜

--------------------------------------------

XXXXX会
時間: 13:00 〜

⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️
```

通知の設定については駒形さんとのやりとりをお願いします。

**Comment by masanarih0ri** [comment]
@komagata 
こちらのissueの対応にそろそろ入れそうな状態になりました。

仕様としては
* 毎日X時に、「定期イベントの中に明日開催のものがあるか？」を確認する
* あればその定期イベント分だけ通知を送る
* 通知はAbstractNotifierを使用する

というようなイメージなのですが、何か他に考えておかなくてはいけないことはありますでしょうか？

また、毎日X時に「定期イベントの中に明日開催のものがあるか？」を確認するというのは、どうやって実装すれば良いでしょうか？会社だとECSTaskを毎日X時Y分に実行という設定をしてあるんですが、フィヨルドではどういった実装がされているのかと思いまして。

**Comment by komagata** [comment]
@masanarih0ri 

> - 毎日X時に、「定期イベントの中に明日開催のものがあるか？」を確認する
> - あればその定期イベント分だけ通知を送る
> - 通知はAbstractNotifierを使用する

こちらでOKです〜。

下記のコントローラーに毎日5時に（Cloud Schedulerで）アクセスするようになっているのでそちらから処理を実行するようにお願いします。（既にある処理を参考にしていただければと思います)

https://github.com/fjordllc/bootcamp/blob/main/app/controllers/scheduler/daily_controller.rb

**Comment by masanarih0ri** [comment]
@komagata 

追加で質問です。

## ①通知先の詳細について
タイトルにDiscordで通知してほしいとあるのでそうだという認識なのですが、通知はDiscordへの通知のみの実装でOKでしょうか？他の実装を見るとメールやアプリケーションへの通知も行っているようなので確認したく。

他の実装というのは、例えば以下のコードです。

```ruby
def self.hibernated(sender, receiver)
  ActivityNotifier.with(sender: sender, receiver: receiver).hibernated.notify_now # アプリでの通知
  DiscordNotifier.with(sender: sender, receiver: receiver).hibernated.notify_now # Discordでの通知
  return unless receiver.mail_notification?

  # メールでの通知
  NotificationMailer.with(
    sender: sender,
    receiver: receiver
  ).hibernated.deliver_later(wait: 5)
end
```

## ②通知用のクラスについて
通知関連のコードを読んでみると、Discordへの通知は、ActivityNotifier と DiscordNotifier、どちらでも実装されているケースがあるのですが、DiscordNotifierの方は退会、休会という管理者だけ見れれば良さそうな通知に使っていそうでした。
[ActivityNotifierを使ってDiscordへの通知を行っているPR](https://github.com/fjordllc/bootcamp/pull/5041)

こうした状況から気になったのですが、DiscordNotifierは管理者向けの通知、それ以外はActivityNotifierを使う、というような自前のルールはあったりするのでしょうか？（あるとすれば今回はActivityNotifierを使うという認識なのですが間違っていないでしょうか？）

**Comment by komagata** [comment]
@masanarih0ri 

> ①通知先の詳細について

まずはDiscordだけでお願いします〜。

> こうした状況から気になったのですが、管理者向けの通知をする場合はDiscordNotifierを使う、それ以外はActivityNotifierを使う、というような自前のルールはあったりするのでしょうか？

そういうルールはないです。

DiscordNotifierを使ってください。

**Comment by masanarih0ri** [comment]
本番環境で定期イベントが作成され、実際に通知が飛ぶかどうか待つ必要があるので、issue自体はcloseします。
