### ISSUE TITLE
Vue化したユーザー個別ページ > 回答一覧のdescriptionが全文表示されている

### ISSUE THREAD

**Issue by eatplaynap** [fjordllc/bootcamp#4575]
## 概要

Vue化前は、「質問内容先頭90文字+...」で省略表記されていた回答一覧のdescriptionが、Vue化後全文表示されている

## 期待される振る舞い

「質問内容先頭90文字+...」で省略表記

### Vue化前
![image](https://user-images.githubusercontent.com/63531341/162142784-b1906634-e205-4529-920c-21dca5a76d6b.png)

### Vue化後

![image](https://user-images.githubusercontent.com/63531341/162142444-dba0361a-f114-4772-83ab-5a48d36f46af.png)

## 関連Issue

Ref: #4295

**Comment by machida** [comment]
確認したのでクローズにしますー
