### ISSUE TITLE
パスワード変更を別のページに移動させる

### ISSUE THREAD

**Issue by ghost** [fjordllc/bootcamp#458]
プロフィールの「アカウント編集」ページにて、
パスワード及び確認用のパスワードを入力しなくとも
プロフィールが更新出来てしまいます。
これはエラーなのでしょうか？

**Comment by sanfrecce-osaka** [comment]
@yousuke1991o 
必須マークついてるので混乱しやすいかもしれませんね。
動きとしてはエラーではないです。
ここでのパスワード入力欄は**変更する際に必ず入力する必要のある欄**ではなく**パスワードを変更する際に入力する欄**だからです。

@machida 
上記から`edit`の際は必須マーク外しておくべきかなと思うんですがどうでしょう？

**Comment by komagata** [comment]
必須マークを外して、「パスワードを変更する場合にのみ入力してください」とか書くべきかもですね。

もしくはパスワード変更は別ページにするとか。

そもそもURLがわかりづらいとおもうので以前から直したいんですよね・・・

**Comment by june29** [comment]
> これはエラーなのでしょうか？

における「エラー」が指すものについて認識合わせしておくといいかもしれませんね :bulb:

ウェブアプリケーションについては、エラーページが出ることもなく処理が完了していればエラーではない場合がほとんどだと思います。今回 @yousuke1991o さんが話したかったことは「これは意図したものでしょうか？」なのではないかな〜と感じました。

ソフトウェア開発の現場において、同じ語彙を用いていながら各位が別の概念を指していると認識にズレが生じて混乱が生じることも多々あるかと思いますので、各位が適切に語彙を選択できる状態にあるのが理想でしょう。

以上、補足でした！

**Comment by yousuke1991o** [comment]
june29さん、ご補足ありがとうございます！
助かります！

ウェブアプリケーション制作の場合ではエラーページが表示されなければ「エラー」としては扱われないという認識があるということなのですね！

**Comment by machida** [comment]
この問題はパスワードの変更はプロフィールとは別のページに移動させる、でいきます！

**Comment by komagata** [comment]
@tetishi こちらやるIssueが減ってきているので @mikihito-h さんにお願いしちゃいたいと思います。

**Comment by kaitoyoshioka** [comment]
@komagata 
すみません、こちらのissueと私が今現在担当している #1609 はもしかして同じだったりしますでしょうか?

**Comment by komagata** [comment]
@kaitoyoshioka すいません、間違ってすでにあるIssueを作ってしまったのと、すでに @kaitoyoshioka さんに依頼しているのを @mikihito-h さんにも依頼してしまいました。

@mikihito-h さんはなしで、@kaitoyoshioka さんでお願いします。すみません。

**Comment by kaitoyoshioka** [comment]
@komagata 
承知いたしました🙇‍♂️
