### ISSUE TITLE
[Choice.js] 新規質問作成フォームのプラクティス選択をChoice.jsに置き換える。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4582]

**Comment by machida** [comment]
@saeyama 
この Issue は、https://github.com/fjordllc/bootcamp/issues/4584 とほぼやることが同じで、同じファイルを使ったりなどがあるので同時にやったほうがやりやすいことがわかりました。なので、https://github.com/fjordllc/bootcamp/issues/4584 も同時に一つの Pull Request で作業をお願いしたいです。

**Comment by machida** [comment]
今回お願いしている「新規質問作成フォームのプラクティス選択」と「日報一覧のプラクティスで絞り込む」は、「ユーザー編集の企業選択」と同じ UI になります。

「ユーザー編集の企業選択」は、管理者でログインした状態でユーザー個別（誰でもOK）に行くと、「管理者として情報変更」というボタンが表示されます。そこからユーザー編集画面に行き、下の方にスクロールすると、「企業」という項目があります。その企業の選択のところで choices.js が使われています。

具体的には、`company-select.js` にあるのですが、`js-company-select` という ID が付いた select タグには choices.js が適用されるようになっています。

choices.js を見たところ、select タグに choices.js を適用すればリッチな UI にしてくれる、というシンプルなもので、select タグの中身（select タグが持つ選択肢など）と choices.js の関係はありませんでした。

今は select2 というライブラリが「新規質問作成フォームのプラクティス選択」と「日報一覧のプラクティスで絞り込む」に適用されています。select2 は、`js-select2` という class を付けると select2 が適用されるようになっているので、select タグから class `js-select2` を削除すれば select2 を「新規質問作成フォームのプラクティス選択」と「日報一覧のプラクティスで絞り込む」から剥がすことができます。

なので、「新規質問作成フォームのプラクティス選択」と「日報一覧のプラクティスで絞り込む」の select タグから `js-select2` という class を削除し、 `js-company-select` という ID を付ければ今回の Issue でやりたいことはできてしまいます。

ただ、企業選択ではない別のページにある select タグに、`js-company-select` という id が使われているのは気持ち悪いし、ファイル名が `company-select.js` なのも引っかかります。ファイル名 `company-select.js` を `choices-ui.js` という名前に変更をし、その中にある id の `js-company-select` の名前も変更したいと思います。

https://choices-js.github.io/Choices/ このページに choices.js が提供する UI の一覧がありますが、 `js-company-select` で採用している UI はこのページにある Single select input の Default です。今回お願いしている「新規質問作成フォームのプラクティス選択」と「日報一覧のプラクティスで絞り込む」にも Single select input の Default を適用します。

id 名 `js-company-select` を変更したいと言いましたが、具体的には、`js-company-select` から choices.js の Single select input の Default を示す id 名にしたいです。なので、`js-choices-single-select` という名前に変えていただきたいです。id名の頭に `js-` というプリフィクスを付けているのは、この ID は JavaScript のためのもの、というのを表しています。

id 名を変更したら、「ユーザー編集の企業選択」に付いている id 名の変更もお願いします。

これで Single select input の Default が適用されるのですが、少しマージの前にデザインの調整をしたいと思います。なので、実装が完了したら machida にメンションをお願いします。デザインを更新します。デザインの更新とレビューは同時進行で大丈夫です。

**Comment by NorifumiOgawa** [comment]
↑Issue番号を間違えてこちらにmentionしてしまいました！失礼しました🙇

**Comment by saeyama** [comment]
@machida さん、詳しいご説明ありがとうございます🙇‍♀️
了解しました！

**Comment by saeyama** [comment]
本番環境で確認が出来たのでクローズします！
