### ISSUE TITLE
[Choice.js] 日報作成、編集フォームのプラクティス選択をChoice.jsに置き換える。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4583]

**Comment by NorifumiOgawa** [comment]
管理者でログイン→「ユーザー登録情報変更」画面の「企業」欄を参考に。

**Comment by machida** [comment]
チャットに貼ったメッセージをこちらにも貼っておきます。

---

今回お願いしている「日報作成、編集フォームのプラクティス選択」と、「Q&Aページのプラクティスで絞り込む」は共通化されてませんでした。

「Q&Aページのプラクティスで絞り込む」だけ特別で、vue-multiselect というライブラリを使っているのでコードがすごく複雑なのですが、今回使おうとしている choices.js とは使い方も全然違うので、そのコードは無視して大丈夫です。

管理者でログインした状態でユーザー個別（誰でもOK）に行くと、「管理者として情報変更」というボタンが表示されます。そこからユーザー編集画面に行き、下の方にスクロールすると、「企業」という項目があります。その企業の選択のところで choices.js が使われています。そのコードを参考にしてください。

具体的には、`company-select.js` にあるのですが、`js-company-select` という ID が付いた select タグには choices.js が適用去れるようになっています。これを真似して、日報のプラクティス選択用の js ファイルを作り、特定の id を付けた select タグには choices.js が適用されるようにしていただきたいです。

今回、choices.js を見たところ、select タグに choices.js が適用すればリッチな UI にしてくれる、というシンプルなもので、select タグの中身（select タグが持つ選択肢など）と choices.js の関係がありませんでした。

なので、企業選択ではない別のページにある select タグに、`js-company-select` という ID を付けても企業選択と同じリッチな UI が適用されます。ということは、js のファイル名は select で何を選択するかについての名前を付けるのは（company-select.js のような）今後同じUIを別のselect タグでも使う場合に良くないことがわかりました。

という訳で、`company-select.js` を `choices-ui.js` という名前に変更をし、一旦その中にある `js-company-select` はそのままにしておいて、このファイルに今回実装したい UI を定義する方針でいきたいと思います。

https://choices-js.github.io/Choices/ このページに choices.js が提供する UI の一覧がありますが、 `js-company-select` で採用している UI はこのページにある Single select input の Default でした。今回お願いしている「日報作成、編集フォームのプラクティス選択」は、このページにある Multiple select input の With remove button が良さそうです。

`js-company-select` は、choices.js の Single select input の Default を示す id の方が良さそうなので、`js-choices-single-select` という名前に変えようかなと思っています。id名の頭に `js-` というプリフィクスを付けているのは、この ID は JavaScript のためのもの、というのを表しています。

同じ感じで、「日報作成、編集フォームのプラクティス選択」で使う id は、choices.js の Multiple select input の With remove button を示しているものにしたいと思います。ただ、フィヨルドブートキャンプのアプリ内で、Multiple select input には、With remove button 以外のものは使うことは無さそうなので、With remove button は含めなくて大丈夫です。`js-choices-multiple-select` で良さそうです。

https://choices-js.github.io/Choices/ のページのコードは https://github.com/Choices-js/Choices/blob/master/public/index.html にあるのですが、このコードの 658 行目が Multiple select input の With remove button を適用させるためのjsのコードになります。これを参考に、`company-select.js` のファイル名を変更した `choices-ui.js` に書いていただきたいです。

HTML の方は https://github.com/Choices-js/Choices/blob/master/public/index.html の 203 行目にあるのですが、select タグに multiple が設定されていればいいだけのようです。今回適用させる select タグは `/app/views/reports/_form.html.slim` の 8 行目らへんにあります。確認すると、multiple が設定されているので、id `js-choices-multiple-select` を付ければリッチな UI が適用されるはずです。

ここで注意なのが、今は select2 というライブラリが適用されています。select2 は、`js-select2` という class を付けると select2 が適用されるようになっているので、select タグから class `js-select2` は削除するようにしてください。

これで Multiple select input の With remove button が適用されるのですが、このままのデザインだとフィヨルドブートキャンプには合わないので、マージの前にデザインの調整をしたいと思います。なので、実装が完了したら machida にメンションをお願いします。デザインを更新します。デザインの更新とレビューは同時進行で大丈夫です。

**Comment by NorifumiOgawa** [comment]
本番環境で確認しました！
