### ISSUE TITLE
[Choice.js] 日報一覧のプラクティスで絞り込むをchoice.jsに置き換える。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4584]

**Comment by machida** [comment]
@niikz 
このIssueなのですが、調べてみたら https://github.com/fjordllc/bootcamp/issues/4582 こちらの Issue と同時にやった方が作業がやりやすいので、今回は @saeyama さんにこのIssueも同時にお願いしすることにしました🙇‍♂️
別の Issue をアサインさせていただきます。

**Comment by saeyama** [comment]
本番環境で確認が出来たのでクローズします！
