### ISSUE TITLE
[アンケート機能]アンケートを作成できるようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4586]
#4472 でアンケートで使う質問を登録する機能が作られています。
このIssueでは、質問をまとめたものを作る、というのをお願いしたいです。

アンケートは `surveys` でお願いします。

## アンケートが持つデータ

- タイトル
    - 例: 2023年04月のアンケート
- 質問
    - [#4472](https://github.com/fjordllc/bootcamp/issues/4472) で作った質問を複数個持つことができる
- 作成者
- 作成日時
- ~~更新者~~ **話し合いの末、不要になりました。**
- 更新日時
- ~~回答期限日時~~ **「回答受付終了日」に変更**
- ~~WIP or 公開~~ **wipカラムにbooleanを入れる形ではなく、start_atとend_atを設け、その期間に入っているかで判断する**
- 回答受付開始日
- アンケートの説明

## アクセス権限

~~index、new、edit は 管理者、メンターだけがアクセスできる。~~
~~アンケートフォームは全てのユーザーがアクセスできる。~~
index、new、edit、show全てのページにおいて管理者、メンターだけがアクセスできる。

**Comment by machida** [comment]
## アンケート一覧

`surveys` の index

<img width="1189" alt="image.png (1.9 MB)" src="https://img.esa.io/uploads/production/attachments/79/2022/06/17/10/a35bdfd3-1ef5-4f06-b6ab-78d1a9caff16.png">

## アンケート作成・編集

`surveys` の new, edit

<img width="1220" alt="image.png (2.8 MB)" src="https://img.esa.io/uploads/production/attachments/79/2022/06/17/10/2019a2a4-6a9f-48d0-bb90-c3057140cab8.png">

## アンケート個別（アンケートフォーム）

<img width="922" alt="image.png (1.1 MB)" src="https://img.esa.io/uploads/production/attachments/79/2022/06/17/10/9a9cc74b-c8ba-4cec-8865-d4e92a4da4eb.png">

**Comment by AyakaTakashima** [comment]
@machida 
こちらのissueなのですが、前回の計画ミーティングの時に「これも既存のPRにプッシュするissueですね」と聞いた気がするのですが、こちらの #5370 のPRという認識で問題ありませんでしょうか？

また、「アンケート個別（アンケートフォーム）」にURLについては相談しながら決めましょうとありますが、いかがいたしましょうか？
前回のMTGでは「showはなくてよい」とおっしゃっており、全く別のURLになると認識しています。

ご回答よろしくお願いいたします🙇‍♀️

**Comment by machida** [comment]
@AyakaTakashima 

伝え忘れてました🙇‍♂️

https://github.com/fjordllc/bootcamp/pull/5370

こちらのブランチから新しいブランチを作って作業をお願いしますー

**Comment by AyakaTakashima** [comment]
@machida 

承知いたしました！ありがとうございます！

**Comment by AyakaTakashima** [comment]
@machida 
度々申し訳ございません！
下記についてはいかがでしょうか？

> また、「アンケート個別（アンケートフォーム）」にURLについては相談しながら決めましょうとありますが、いかがいたしましょうか？
前回のMTGでは「showはなくてよい」とおっしゃっており、全く別のURLになると認識しています。

**Comment by machida** [comment]
@AyakaTakashima アンケートフォームは今回のIssueには含めないことにしました。ただ、showの作成はお願いします。showはアンケートフォームのプレビューにしようと思ってます。文章だと分かりづらいのでここはワイヤフレームを作成します。

**Comment by AyakaTakashima** [comment]
@machida 
承知いたしました！それでは、showの方はそのワイヤーフレームの作成待ちということで問題ありませんでしょうか？？

**Comment by machida** [comment]
@AyakaTakashima はい、作成待ちでお願いします🙏

**Comment by machida** [comment]
@AyakaTakashima 
お待たせしましたー。
show こんな感じでアンケートのプレビュー画面にしたいと思います。
自分で作ったアンケートの内容が確認できるページをお願いします。

<img width="596" alt="image" src="https://user-images.githubusercontent.com/168265/192169385-c9465cef-8244-45dd-b94b-5c055e2193ad.png">

このあと、何人が回答したかなども見れるようにしたいですが、それは別Issueにしたいと思います。

**Comment by AyakaTakashima** [comment]
@machida 
承知いたしました！ありがとうございます！

**Comment by AyakaTakashima** [comment]
@machida 
お疲れ様です！
本件について、ER図を書いてみました。
実は、ER図を書くプラクティスをやった際に、6回も再提出になりました。
自信がないので一度みていただきたいです😭

もし、「ここはnullでもOKというのがあれば、それもあわせて教えていただけますと助かります！

![image](https://user-images.githubusercontent.com/76944527/192302081-ed360f0b-ba29-44a8-aaac-e952175900f3.png)

- タイトル
    - 型：`text`
    - カラム名：`title`
    - 制約： `limit: 255, null: false`（日報のタイトルと同じ制約）
- 質問
    - 型：`references`
    - カラム名：`questionsurvey_question_id`にし、#5370 で作成いただいた`questionsurvey_question`テーブルの`id`を外部キーとする
    - 制約： `foreign_key: true,null: false`
- 作成者
    - 型：`references`
    - カラム名：`creator_id`
    - 制約：`foreign_key: { to_table: :users }`
- 作成日時
    - 型：`datetime`
    - カラム名：`created_at`
    - 制約：`null: false`
- 更新者
    - 型：`references`
    - カラム名：`updator_id`
    - 制約：`foreign_key: { to_table: :users }`
- 更新日時
    - 型：`datetime`
    - カラム名：`updated_at`
    - 制約：`null: false `
- 回答期限日時
    - カラム名：`reply_deadline`
    - 型： `datetime`
    - 制約：`null: false`
- WIP or 公開
    - カラム名：`wip` 
    - 型：`boolean` 
    - 制約：`default: false, null: false`


よろしくお願いいたします🙇‍♀️

**Comment by machida** [comment]
> タイトルは日報と同じく必須でいいのか、回答期限も必須にしようと思いますがこれで良いのか、が気になっています。

どちらも必須でOKですー👍
DB設計は komagata さんに見てもらおうと思いますー

@komagata こちら確認お願いします🙏

**Comment by AyakaTakashima** [comment]
@machida 
machidaさん、お返事ありがとうございます！！

@komagata 
komagataさん、ご確認よろしくお願いいたします🙇‍♀️

**Comment by komagata** [comment]
@machida かしこまりました。

@AyakaTakashima 

> creator_id

複数ある場合以外はそのままの名前の`user_id`でいいと思います。

> 更新者
(CC: @machida)

作成者とは別に更新者が必要な感じでしょうか？更新者は複数いると言うことになるので、ちゃんとやるには複雑になりそうです。（個人的には作成者があれば更新者はいらないのではないかと思います）

> reply_deadline

railsでは日付は`xxxx_on`、日時は`xxxx_at`という命名規約があるので、できればそれに従う形の名前にできるといいなと思います。

**Comment by AyakaTakashima** [comment]
@komagata 
ご確認ありがとうございます！
本issueのdescriptionにアンケートが持つデータとして更新者と作成者の項目がありましたので追加しておりました！
しかし念の為machidaさんにお伺いしようと思います。

また、理解が及ばず申し訳ないのですが、

> 複数ある場合以外はそのままの名前のuser_idでいいと思います。

というのは何が複数ある場合でしょうか？🧐

@machida 
machidaさん、上記の更新者に関してご回答いただけますと幸いです🙇‍♀️

**Comment by komagata** [comment]
@AyakaTakashima すみません、このDB設計自体は @AyakaTakashima さんが作ったものではなく、既にあるものをER図に起こしただけなんですね。

DB設計に対するコメントは同じものを @daiki0381 さんの方にさせていただき、別のPRで議論を続けていきたいと思います。

> というのは何が複数ある場合でしょうか？🧐

すみません、わかりずらい書き方でしたね。

userテーブルと関連するものが一つしかないのであれば`user_id`という名前が一般的なので`creator_id`ではなく、`user_id`がいいのではないかという意味です。

**Comment by komagata** [comment]
@AyakaTakashima 

> ただ、daiki0381さんが作成したものを私が作成したというのは間違えで、このPRで私が作成しようと思っているものをER図に起こしたと認識していただけますと幸いです。

なるほどです。認識しました。

**Comment by AyakaTakashima** [comment]
@komagata 
#5370 の回答を拝見いたしました。
更新者のデータは不要ということで理解しました。

ER図を書き直しいたしましたので、再度ご確認をお願いしたいです。
![image](https://user-images.githubusercontent.com/76944527/196159985-7c6c9f30-c49e-428c-b43c-ae0d3057429e.png)

よろしくお願いいたします🙇‍♀️

**Comment by komagata** [comment]
@AyakaTakashima surveryが複数のsurvey_questionをもつのだとしたら、surveryのsurvey_question_idだと複数のものを表現できないかもです〜。

**Comment by AyakaTakashima** [comment]
@komagata 
修正してみました！ご確認よろしくお願いいたします🙇‍♀️
![image](https://user-images.githubusercontent.com/76944527/197376418-8559fb0f-5675-49c0-ac9f-7f2fe7158ece.png)

**Comment by komagata** [comment]
@AyakaTakashima これだとsurvey_questionは一つのsurveyにしか所属できないように思います〜

**Comment by komagata** [comment]
@AyakaTakashima 中間テーブルになった部分はOKです〜。

ただ、`reply_deadline_at`は`created_at`や`published_at`のように動詞じゃないと`_at`が英語的に成り立たないので、名前を検討してみていただきたいです〜

**Comment by AyakaTakashima** [comment]
@komagata 
ありがとうございます！
`deadline_survey_is_replied_at`と考えて、`deadline_replied_at`でいかがでしょうか？

**Comment by komagata** [comment]
@AyakaTakashima 冗長な表現は避けたいので直訳を避けて`expires_at`などはいかがでしょうか。

**Comment by AyakaTakashima** [comment]
@komagata 
なるほど！`expires_at `にします。ありがとうございます！

**Comment by AyakaTakashima** [comment]
テーブル構造は下記で決定
![image](https://user-images.githubusercontent.com/76944527/197757823-7ad92ae8-c85f-45dc-9f4d-01d202713ed0.png)

**Comment by AyakaTakashima** [comment]
@machida 
お疲れ様です！`surveys` の indexについて確認したいことがあります！
![image](https://user-images.githubusercontent.com/76944527/198292568-1d2a5c32-15b8-42d2-93b5-06caf100a9e0.png)

上記ページの、下記の部分で不明点があります。
![image](https://user-images.githubusercontent.com/76944527/198292914-1081b541-6bf1-4df8-80fa-878fd81fab1f.png)

下記についてご回答お願いいたします🙇‍♀️
![image](https://user-images.githubusercontent.com/76944527/198295541-7986c758-7bc3-4274-8e63-24f8a7413977.png)

**Comment by AyakaTakashima** [comment]
@machida 
すみません。上記に追加で質問です！
`surveys` の new, editのワイヤーフレームでは、「説明」欄があります。
しかし、本issueの一番上で「アンケートが持つデータ」と指定されているものの中に「説明」というデータはありません。
どちらが正しいものでしょうか？
ご確認よろしくお願いいたします！

**Comment by machida** [comment]
@AyakaTakashima 

確認ありがとうございます！！
回答させていただきますー

日付の部分は、published_at 〜 expires_at でお願いします。WIPのときは日付の代わりにWIPと表示します。

タイトルの部分はカッコ内も含めて二つともタイトルになります。わかりにくい例にしてしまってすいません🙇‍♂️

回答の件数は別Issueでやりたいと思います。

---

説明が抜けててすいません、説明の追加をお願いします🙏

**Comment by AyakaTakashima** [comment]
@machida 
早速のご回答ありがとうございます！！

承知しました！一覧表示のカード内は下記のようにします！
![image](https://user-images.githubusercontent.com/76944527/198307690-2f572665-feca-4ce2-9c04-d2e5adc01820.png)

ということは、descriptionだけでなく、published_atも加える必要がありますね🧐

@komagata 
お疲れ様です！
上記のような形になりましたので、新規テーブルのsurveyにdescriptionとpublished_atカラムを追加することにしました！
ご報告まで🙇‍♀️
![image](https://user-images.githubusercontent.com/76944527/198308258-f1550764-0535-411d-90d7-46b154fab4d9.png)

**Comment by AyakaTakashima** [comment]
> WIPのときは日付の代わりにWIPと表示

![image](https://user-images.githubusercontent.com/76944527/198564749-533825e1-9b99-4e59-8af3-6516b4b71721.png)

**Comment by komagata** [comment]
@machida (CC: @AyakaTakashima )

アンケートの開始と終了日であれば、他のとは別の仕組みにして、`start_at`, `end_at`にした方がわかりやすいかな〜と思いました。

公開 <-> WIP という仕組みではなく、開始日・終了日　に当てはまってる時だけ、ユーザーから見えるという感じ。

アンケートというとそっちの方があっているように思いました。

**Comment by machida** [comment]
@komagata なるほど！それいいですねー。

@AyakaTakashima @komagata 
WIPを無しにして、スタートとエンドの設定でお願いしたいです🙏

**Comment by AyakaTakashima** [comment]
@machida 
承知しました！
下記のようにしたいと思います。
![image](https://user-images.githubusercontent.com/76944527/198971747-0a95a479-6cf5-4309-9b3f-791f9db5126a.png)
![image](https://user-images.githubusercontent.com/76944527/198971768-4580646c-27e6-4036-8fa5-14d6c81a394b.png)

published_atで作成している時に、ワイヤフレームではpublished_atを入力する欄がありませんでした。
published_atも入力させた方がいいのでは？と思い、下記のように入力欄を設けていました。
![image](https://user-images.githubusercontent.com/76944527/198972239-7e15fac9-73f7-4703-9039-2349ed13118e.png)

ただ、publish_atが「アンケート公開日」で、expires_atが「回答期限」なのが、対になっていなくてなんか気持ち悪いなと思っていたのでちょうどよかったかもです。

ただ、一つ確認したいのが、new、edit画面のワイヤフレームの日付の入力欄が
「回答期限」しかないのでstart_atも入力される想定であっているのか確認したいです。
どちらも入力させる場合ですが、end_atを「回答期限日」ではなく、「回答受付終了日」というラベルにし、
start_atと対になるような日本語にしてみてはどうでしょうか。（下記のように）
![image](https://user-images.githubusercontent.com/76944527/198973273-4f40399e-03a4-414d-bc61-b26b53f05716.png)

ご確認お願いいたします🙏

**Comment by machida** [comment]
@AyakaTakashima 確かに！スタートの日付も入力できるようにお願いしますー🙏

**Comment by AyakaTakashima** [comment]
@machida 
承知しました！下記についての回答はいかがでしょうか？？

> どちらも入力させる場合ですが、end_atを「回答期限日」ではなく、「回答受付終了日」というラベルにし、
start_atと対になるような日本語にしてみてはどうでしょうか。（下記のように）
![image](https://user-images.githubusercontent.com/76944527/198990541-83b3b67a-830f-42d0-b531-a8b31a26fcc7.png)

**Comment by machida** [comment]
@AyakaTakashima すいません🙇‍♂️ラベルもそのようにお願いしますー🙏

**Comment by AyakaTakashima** [comment]
@machida 
承知しました！ご回答ありがとうございました！！

**Comment by AyakaTakashima** [comment]
@machida 
お疲れ様です！
アンケートを削除するボタンが見つからないのですが、削除ボタンは未設置という認識でよろしいでしょうか？
見落としでしたらすみません😭

**Comment by AyakaTakashima** [comment]
すみません！上記の質問に加えて、もう一つ確認させてください！
アンケートは、「XX月XX日のXX時XX分までに回答してください」というのが一般的かなと思っています。
そこで、下記2点を確認させていただきたいです。
1. 回答開始日と回答期限日を入力するときは、時間も入力させる気でいたのですがこの認識でよろしいでしょうか？
1. 時間も入力させる場合、カードに表示させるのは日付のみでしょうか？それとも時間も表示いたしますか？
1. ワイヤーフレームでは、省略されて日付のみが表示されているようです。（下記参照）年月が異なる場合は全て表示した方がいいと思っていますが、よろしいでしょうか？また、同じ年月の場合は、省略して表示した方が良いのでしょうか？

ワイヤーフレームでは、下記のように年月が省略されて表示されている（同じ年月の場合？）
![image](https://user-images.githubusercontent.com/76944527/200839694-6405fbf0-31cf-4406-b546-00f92f3ccb51.png)

下記のように全て表示した方がいいのではないか？と思っています。
![image](https://user-images.githubusercontent.com/76944527/200839022-b19265cf-db55-42b0-90c5-85ee4042814d.png)

**Comment by machida** [comment]
@AyakaTakashima すいません！削除が抜けてました。編集ページに削除の設置をお願いします🙏

**Comment by AyakaTakashima** [comment]
@machida 
承知いたしました！期間の表示は下記のままでいきますね！
![image](https://user-images.githubusercontent.com/76944527/201065117-c67740a5-4cbc-442e-8f79-e293ec9f8a91.png)

> 00:00 から 23:59までという設定が多くなると思うので、新規作成をした際、デフォルトでその日時が入っているようにしていただきたいです🙏

新規作成を押した当日の、00:00 から 23:59がデフォルトで入るようにする、という形ですね！（下記のような認識です）
承知しました！
![image](https://user-images.githubusercontent.com/76944527/201066218-0f65f2ff-db6e-475e-b32c-7b3eaeec14d9.png)


「削除する」はどこに置きましょうか？日報は下記画像の一番右端のように、リンクになっているようでした。
![image](https://user-images.githubusercontent.com/76944527/201065304-2d6dc0a2-cc4b-41b5-bc1f-6be0ed56f65c.png)

これに倣って下記のようにボタンの横に「削除する」を置く形で大丈夫でしょうか？（＊目立ちやすいよう文字を赤で記載しています）
![image](https://user-images.githubusercontent.com/76944527/201065789-dfb0519b-530e-42ae-9c2f-573f1d2d63cb.png)

**Comment by machida** [comment]
@AyakaTakashima 削除は日報と同じように右下でお願いしますー
細かいデザインら僕の方でやりますが、滅多に使わないので、目立たない色で良さそうですね。

**Comment by AyakaTakashima** [comment]
@machida 
ありがとうございます！
はい、見ていただきやすいように画像では一時的に赤くしただけですので色に関しては気にせず大丈夫です。

**Comment by AyakaTakashima** [comment]
📝11/16の開発MTGにて
- indexページの「WIP」の表示は、「WIP」ではなく「受付前」にする
- それに伴い、survey.start_at~survey.end_at期間中のものは「受付中」マークをつける

**Comment by AyakaTakashima** [comment]
@machida 
お疲れ様です！
アクセス権限について、質問があります。

以前に、下記のようにshowのページの仕様変更が発生したと思います。
変更前：showはアンケートフォームにする。一番下のボタンは「送信」だった。
→ 変更後：showは作成したアンケートのプレビューの画面にする。一番下のボタンは「編集」に変更になった。

現在、このissueの一番上のdescriptionに、アクセス権限について下記のように記載があります。

> index、new、edit は 管理者、メンターだけがアクセスできる。
アンケートフォームは全てのユーザーがアクセスできる

このように「アンケートフォームは全てのユーザーがアクセスできる」とあります。
しかし上記に記載したとおり、showは「アンケートフォーム」では無くなったので今一度アクセス権限について確認したいです。
私の考えでは、アンケートのプレビュー画面なので、showもメンターや管理者しか見れないのかなーというイメージがいかがでしょうか？
ご回答よろしくお願いいたします！

**Comment by machida** [comment]
@AyakaTakashima 削除、その位置でお願いします〜。細かいところは僕の方で対応しますが、今の感じで良さそうですー。

**Comment by machida** [comment]
@AyakaTakashima showのアクセス権限はそれでお願いしますー。プレビューになるので、editができる人はshowもアクセスできる、という形でお願いします🙏

**Comment by AyakaTakashima** [comment]
@machida 
承知しました！ご回答ありがとうございます！

**Comment by AyakaTakashima** [comment]
komagataさんに本番にて確認していただき、問題ないことを確認しました。
クローズいたします！
