### ISSUE TITLE
研修生招待リンクを管理者の企業一覧に追加したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4611]
adminでログインして、ここにアクセス
http://localhost:3000/admin/companies

![貼り付けた画像_2022_04_13_16_27](https://user-images.githubusercontent.com/168265/163122883-46604368-c956-4b9f-8658-d7a89425b060.png)

table に研修生招待リンク というカラムを追加し、アドバイザー招待リンクのようにリンクを置く。
研修生招待リンクのURLについては @komagata さんに確認をお願いします。

**Comment by komagata** [comment]
:memo: `http://localhost:3000/users/new?role=trainee&company_id=1234&token=xxxx`みたいな感じのリンクになるようにお願いします。

company_idのところはその企業のIDになるようにすれば、その企業が選ばれた状態でサインアップできるようになっている（はず）です〜。

**Comment by siso25** [comment]
@komagata @machida 
お手隙の際に本番環境の動作確認をお願いいたします。

**Comment by machida** [comment]
本番で確認しましたー🙆

**Comment by siso25** [comment]
@machida 
ご確認ありがとうございます。

**Comment by siso25** [comment]
本番環境で確認いただきましたので、クローズとさせていただきます。
