### ISSUE TITLE
【メンター向け】「○日経過」のラインの見方が直感的によくわからない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4620]
提出物一覧が提出日昇順となったが、「○日経過」のラインの見方が直感的によくわからない。

たとえば下の画像のような状況だと、以下のどちらの解釈になるのかわからない。
（おそらく後者だろうが、前者に見えてしまう。なお、スクショを撮ったタイミングは2022/4/14 18:16）

- 6日経過が1件、5日経過が大量にある（または不具合で切れ目が表示されていない）
- 6日経過は0件、5日経過が1件

![mosaic](https://user-images.githubusercontent.com/1148320/163355535-3e1282a8-77bc-4076-8361-1e0aab5d84b3.png)

個人的には何かしらのデザイン修正が必要かな〜と思います。

関連 https://github.com/fjordllc/bootcamp/pull/4399

**Comment by Aseiide** [comment]
@JunichiIto 
実装したものです！
こちらの問題に対しては、#4393 で対応していて、「本日提出、1日経過, 2,3,..., 7日以上経過」のそれぞれラベルが出るようになります。(スクショ参照)
こちらはhotfixとして近々リリースされると思います。
参照: https://discord.com/channels/715806612824260640/809595476847493192/964059408663470090
![screencapture-localhost-3000-products-unassigned-2022-04-14-18_40_44](https://user-images.githubusercontent.com/45246171/163358915-b5aedc6c-46ef-48d1-bd3c-6713239c3064.png)

また、それぞれの件数についても #4345 で対応予定で、現在実装中です。

ご不便おかけしていてすみません 🙏

**Comment by JunichiIto** [comment]
@Aseiide 共有ありがとうございます。了解です！
すいません、この件はすでにDiscordでやりとりされてたんですね。先にFBCの方を見に行ったので、issueを先に書いちゃいました😓
こちらのissueはcloseしておきます〜。
