### ISSUE TITLE
日報個別ページの右にある直近の日報一覧のユーザーアイコンは非表示にしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4628]
日報個別ページの右にある直近の日報一覧のユーザーアイコンは非表示にしたい。

<img width="1505" alt="貼り付けた画像_2022_04_15_14_02" src="https://user-images.githubusercontent.com/168265/163522364-0d24c4d1-7dd0-446e-a445-49557066baac.png">

現在、日報一覧はすべて同じテンプレートを使っている。
同じテンプレートを使っているのはそのままで、何か引数を渡すとユーザーアイコンが非表示のリストで表示できるようにしたい。

`.thread-list-item__user`  を非表示にする。

<img width="1022" alt="貼り付けた画像_2022_04_15_14_06" src="https://user-images.githubusercontent.com/168265/163523296-ae2eed97-7c8b-4867-ac7f-a864dbc1ea9e.png">

**Comment by taka110-IT** [comment]
本番環境で確認ができましたのでIssueをCloseします。
