### ISSUE TITLE
検索ワードに文字を入力するとページがスクロールされてしまう

### ISSUE THREAD

**Issue by kotakawase** [fjordllc/bootcamp#4630]
## 概要
検索ワードに文字を入力するとページが一緒にスクロールされることがあります。

## 再現手順
スクロールできるページであれば再現可能かと思われます。

1. 例として[Railsプログラマーコース](https://bootcamp.fjord.jp/courses/1/practices#category-25)にアクセス。
2. 「検索ワード」をクリックして文字を入力する。

検索ワードはこちらです。

![スクリーンショット 2022-04-16 12 33 14](https://user-images.githubusercontent.com/74460623/163659959-62111c9b-0c59-47dc-944b-1cdfe23f9668.png)

文字を入力。

![https://gyazo.com/c0b2b76a3ecc572dd0687337c89cf6df](https://gyazo.com/c0b2b76a3ecc572dd0687337c89cf6df.gif)

3. ページがスクロールされてしまう。

補足
- スクロールバーが1番上部にあるときはスクロールされないです
- 入力した文字を削除すると上にスクロールされます

## 期待される振る舞い
ページがスクロールされることなく検索ワードに文字を入力・削除できる。

## 環境

 - OS: macOS Monterey
 - ブラウザ: Google Chrome
 - バージョン: 100.0.4896.88（Official Build） （x86_64）

**Comment by ima1zumi** [comment]
私の環境でも再現しました。
