### ISSUE TITLE
アドバイザーでログインしたときに提出物にアクセスをしたら、全ての提出物一覧が表示されてほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4651]
今はアドバイザーでログインして左メニューの提出物にアクセスをすると何も表示されない。

全ての提出物が一覧で表示されるようにして欲しい。

**Comment by shirotamaki** [comment]
@komagata @machida
 お疲れさまです！今週のリリースありがとうございます✨
 こちら、アドバイザー向けのページのため本番環境での動作確認をお願いできますでしょうか？
 
 確認方法
 - アドバイザーアカウントでログインする
 - 右記へ接続する http://localhost:3000/products
「全て」の提出物が表示されていることが確認する

**Comment by shirotamaki** [comment]
本番環境での動作確認が完了しましたのでcloseいたします！

**Comment by shirotamaki** [comment]
本番環境での動作確認が完了しましたのでcloseいたします！
