### ISSUE TITLE
お知らせの編集に排他制御(楽観ロック)を導入する

### ISSUE THREAD

**Issue by NorifumiOgawa** [fjordllc/bootcamp#4661]
## 機能の説明

お知らせの文書更新に排他制御を追加し、衝突が起きたときにはエラーもしくはメッセージを表示する。

## 何故この機能が必要なのか

「今週のリリース」など、複数人で同じ文書を更新する場合、更新タイミングによって一旦保存された内容が（何のエラーも起きずに）消えてしまうことがあるようです。このような現象を防ぐために排他制御の導入が適当かと思われます。

再現手順）
`A` と書かれた文書をaliceとbobが編集画面で開いて、aliceは`AB`と書き換えて保存、次に、bobは`AC` と書き換えて保存した場合、現状のお知らせ編集の仕組みだとaliceの更新内容`AB` が残らない。

**Comment by machida** [comment]
:memo:

- お知らせの編集をする際に、編集画面を開いた時点でのお知らせページの `updated_at` を hidden に入れておく
- 開いた編集画面の保存ボタンを押した時点での、更新をしようとしているページの最新の `updated_at`
と hidden に入れていた `updated_at` の値を比較し、それが一致していなかったらエラーを出す

エラー文は、「別の人がお知らせを更新していたので更新できませんでした。」でお願いします。

**Comment by kei-kmj** [comment]
@machida
updateアクションの時に、編集開始時のupdated_atと更新時のupdated_atが違っていたらエラーを出し、後の人が更新できないようにするところまでは出来ました。

しかし、更新できないようにしても、ブラウザの戻るボタンから編集画面に戻ってしまうと、そこでSQL問い合わせが発生するために、`updated_at`が最新の`updated_at`に書き変ってしまうので、後の人の更新が成功してしまいます。これは`lock_version`カラムを使ったとしても、戻るボタンを押すとSQL問い合わせしてしまう以上避けられないと思うのですが、このままの仕様で良いのでしょうか？質問タイムなどで画面を見ていただきながらアドバイスを受けた方が良いかもしれませんが、次の質問タイムまで5日もあるので、先に疑問点をお伝えします。

**Comment by machida** [comment]
@komagata 

ブラウザの戻るボタンから編集画面に戻った場合についての対応は別Issueでいこうと思いますがいかがでしょうか？

**Comment by komagata** [comment]
@machida (CC: @kei-kmj ) 別Issueでいいと思います〜

**Comment by kei-kmj** [comment]
本番環境で動作確認したのでcloseします。
