### ISSUE TITLE
現役生で退会をしようとして必須項目未入力でエラーが出た場合にヘッダに不要なboderが出る

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4662]
<img width="429" alt="貼り付けた画像_2022_04_21_18_39" src="https://user-images.githubusercontent.com/168265/164427069-710908b3-adf0-4023-981a-2cacde47f238.png">

現役生ログインした状態で退会をしようとして必須項目未入力でエラーが出た場合にだけ出る。

**Comment by yamatatsu10969** [comment]
本番環境ですでにラジオボタンが選択されているので、バリデーションエラーが確認できませんでした。
修正は完了しているのでクローズします。
