### ISSUE TITLE
管理画面の企業一覧の企業名にリンクを貼りたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4665]
adminでログインして、
https://bootcamp-staging.fjord.jp/admin/companies
にアクセス。

<img width="984" alt="貼り付けた画像_2022_04_22_11_46" src="https://user-images.githubusercontent.com/168265/164586255-7c07863c-4424-48e3-a8e4-c20ce1b0cc2f.png">

これをリンクにしてほしい。
リンクに指定する URL は admin でなくても見れる会社個別ページ `/companies/XXXXX` 。

**Comment by komagata** [comment]
@isshi-hasegawa 本番環境で動作することを確認しました。

**Comment by isshi-hasegawa** [comment]
本番環境で動作確認頂いたのでcloseします。
