### ISSUE TITLE
卒業生も全提出物を見れるようにしたい

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/bootcamp#467]
- 現状
  - 新規で追加されたプラクティスの提出物は、追加前にその後のプラクティスに進んだ場合、卒業後も提出物は見られない
- 提案
  - 卒業をトリガーとして全提出物を見られるようにする
    - 卒業をトリガーとするのは、卒業以前に何かトリガーを設けると、それを悪用して他者の答えを見ることもできるため
- メリット
  - 現役生がより多くのアドバイスを受けやすくなる

**Comment by komagata** [comment]
卒業生も実際やってみるのはどうでしょうか？

僕もやってみましたが、アドバイザーはともかくやってない人にアドバイスもらいたくないかも？

**Comment by machida** [comment]
僕も駒形さんの意見に賛成です。

あとは、今、アドバイザー自体の在り方を変えようと思ってて、今後の卒業生はアドバイザーになってもらおうと考えているので（もっと就職した卒業生や卒業生の就職先の同僚や上司の方がアドバイザーとしてコメントができるようにしたい）、そこをまとめたら共有します。

**Comment by sanfrecce-osaka** [comment]
@komagata 
たしかにそうですね

@machida 
わかりました。
こちらのissueは一旦closeしましょうか？

**Comment by machida** [comment]
@sanfrecce-osaka 一旦closeでお願いします
