### ISSUE TITLE
提出物一覧の「全て」のタブだけ新しいもの順に並べてほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4671]
メンターでログインして左ナビの提出物をクリックして表示されるページの「全て」のタブを開いたときは、提出物が新しいもの順で並んでほしい（他のタブは古い順だが、それはそのままで）。

**Comment by kazumi3858** [comment]
@komagata さん @machida さん

お疲れ様です！
こちら本番環境での動作確認をお願いいたします🙇‍♂️✨

**Comment by machida** [comment]
@kazumi3858 確認しました！OKですー🙆‍♂️
