### ISSUE TITLE
メンターでログインしたときに相談部屋の未読数が表示されてしまっている

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4672]
## 概要

メンターでログインしたときに、管理者にしか必要のない未読数が左ナビの相談部屋に表示されてしまっている。

## 期待される振る舞い

メンターには未読数は表示しない。

---

<img width="157" alt="貼り付けた画像_2022_05_09_13_48" src="https://user-images.githubusercontent.com/168265/167342514-16fd68d3-01f4-4468-8953-59c4420eaf5b.png">

ここにでる数字はadminでログインしたときだけ表示されるようにする。
メンター、受講生、アドバイザーのときは数字が表示されない、というテストもほしいです。

**Comment by masanarih0ri** [comment]
@machida 
お疲れ様です！
こちらの仕様について確認したいのですが
* 管理者のみ未読数が表示される
* 実装の対象は相談の部分のみ（サイドのグローバルナビにある他のQ&Aやヘルプなどは特に考えなくて良い）
ということで間違っていないでしょうか？
それと、既存のテストが特になさそうなのですが、`bootcamp/test` 配下に自分で作るようイメージであっていますでしょうか？

**Comment by machida** [comment]
@masanarih0ri はい！その理解で合ってますー🙆それでお願いしたいです🙏

**Comment by masanarih0ri** [comment]
@machida 
承知しました！ではやってみます！👍
