### ISSUE TITLE
[abstract_notifier] 提出物の更新の通知を置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4680]
## 経緯

通知部分を整理するのに[active_delivery](https://github.com/palkan/active_delivery)を使ったものに変えたいと思っているが、前準備として[abstract_notifier](https://github.com/palkan/abstract_notifier)に対応させる必要がある。

## やること

**提出物の更新の通知の実装**をabstract_notifierに置き換えたい。

既に[導入したPR](https://github.com/fjordllc/bootcamp/pull/4673)があるのでそちらを参考にする。

- [abstract_notifierで通知を実装する - komagataのブログ](https://docs.komagata.org/5857)
- [現状の提出物の更新の通知の実装](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification.rb#L257)
- [abstract_notifierを導入 by komagata · Pull Request #4673 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4673)
- [palkan/active_delivery: Ruby framework for keeping all types of notifications (mailers, push notifications, whatever) in one place](https://github.com/palkan/active_delivery)
- [palkan/abstract_notifier: ActionMailer-like interface for any type of notifications](https://github.com/palkan/abstract_notifier)

**Comment by fuwa-syugyo** [comment]
@komagata @machida 
お疲れ様です！
こちらのissueにつきまして、本番環境での動作確認をお願いできますでしょうか？

**確認方法**
1. 受講生のアカウントでログインし、任意のプラクティスの提出物を作成する
1. メンターのアカウントでログインし、1. の提出物の担当者になる
1. `1.` の提出物の内容を更新する
1. メンターのアカウントに通知が来ていることを確認する
1. メンター宛にメールが届いていることを確認する

**Comment by fuwa-syugyo** [comment]
@komagata 
承知いたしました！
ご確認いただきありがとうございます。
closeさせていただきます〜
