### ISSUE TITLE
[abstract_notifier] フォローしてる人の日報の更新の通知を置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4684]
## 経緯

通知部分を整理するのに[active_delivery](https://github.com/palkan/active_delivery)を使ったものに変えたいと思っているが、前準備として[abstract_notifier](https://github.com/palkan/abstract_notifier)に対応させる必要がある。

## やること

**フォローしてる人の日報の更新の通知の実装**をabstract_notifierに置き換えたい。

既に[導入したPR](https://github.com/fjordllc/bootcamp/pull/4673)があるのでそちらを参考にする。

- [abstract_notifierで通知を実装する - komagataのブログ](https://docs.komagata.org/5857)
- [現状のフォローしてる人の日報の更新の通知の実装](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification.rb#L213)
- [abstract_notifierを導入 by komagata · Pull Request #4673 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4673)
- [palkan/active_delivery: Ruby framework for keeping all types of notifications (mailers, push notifications, whatever) in one place](https://github.com/palkan/active_delivery)
- [palkan/abstract_notifier: ActionMailer-like interface for any type of notifications](https://github.com/palkan/abstract_notifier)

**Comment by keiz1213** [comment]
本番環境で動作確認できましたのでcloseします
