### ISSUE TITLE
[abstract_notifier] イベントの補欠への繰り上がりの通知の実装を置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4686]
## 経緯

通知部分を整理するのに[active_delivery](https://github.com/palkan/active_delivery)を使ったものに変えたいと思っているが、前準備として[abstract_notifier](https://github.com/palkan/abstract_notifier)に対応させる必要がある。

## やること

**イベントの補欠への繰り上がりの通知の実装**をabstract_notifierに置き換えたい。

既に[導入したPR](https://github.com/fjordllc/bootcamp/pull/4673)があるのでそちらを参考にする。

- [abstract_notifierで通知を実装する - komagataのブログ](https://docs.komagata.org/5857)
- [現状のイベントの補欠への繰り上がりの通知の実装](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification.rb#L191)
- [abstract_notifierを導入 by komagata · Pull Request #4673 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4673)
- [palkan/active_delivery: Ruby framework for keeping all types of notifications (mailers, push notifications, whatever) in one place](https://github.com/palkan/active_delivery)
- [palkan/abstract_notifier: ActionMailer-like interface for any type of notifications](https://github.com/palkan/abstract_notifier)

**Comment by shirotamaki** [comment]
@komagata @machida 
お疲れ様です！Issueの内容について質問になります🙏
「イベントの補欠への繰り上がりの通知」についてですが、イベント参加者枠でキャンセルが発生した場合、補欠者枠からの繰り上がりで参加された方への通知でよいでしょうか？
誰宛に通知を行うのかしっかり理解しておきたく質問させていただきました。よろしくお願いします🙏

**Comment by machida** [comment]
@shirotamaki 🙆‍♂️その通知になりますー

https://github.com/fjordllc/bootcamp/pull/1430

このPRで実装された機能を置き換えお願いしますー

**Comment by shirotamaki** [comment]
@machida 
承知しました。ありがとうございます！
