### ISSUE TITLE
[abstract_notifier] 研修生の日報作成の通知の実装を置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4687]
## 経緯

通知部分を整理するのに[active_delivery](https://github.com/palkan/active_delivery)を使ったものに変えたいと思っているが、前準備として[abstract_notifier](https://github.com/palkan/abstract_notifier)に対応させる必要がある。

## やること

**研修生の日報の更新の通知の実装**をabstract_notifierに置き換えたい。

既に[導入したPR](https://github.com/fjordllc/bootcamp/pull/4673)があるのでそちらを参考にする。

- [abstract_notifierで通知を実装する - komagataのブログ](https://docs.komagata.org/5857)
- [現状の研修生の日報の更新の通知の実装](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification.rb#L180)
- [abstract_notifierを導入 by komagata · Pull Request #4673 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4673)
- [palkan/active_delivery: Ruby framework for keeping all types of notifications (mailers, push notifications, whatever) in one place](https://github.com/palkan/active_delivery)
- [palkan/abstract_notifier: ActionMailer-like interface for any type of notifications](https://github.com/palkan/abstract_notifier)

**Comment by shirotamaki** [comment]
@machida 
issueの内容について質問になります🙏
「研修生の日報の更新の通知」とありますが、この「通知」とは右上の通知マークへの通知のことでしょうか？現在の状況を確認してみたところ、右上の「通知」へは何も通知が来ません。通知の定義をしっかり理解しておきたいと思い質問させていただきました。よろしくお願いします。

1. `kensyu@fjord.jp`でログインし日報を更新する。

![image](https://user-images.githubusercontent.com/65638955/190101648-ca406511-e9fd-47a9-9b2d-c923409c2311.png)

2. `komagata@fjord.jp`でログインし確認する。

![image](https://user-images.githubusercontent.com/65638955/190102158-7fed8ab0-06e0-4d99-b351-1a10702d8a20.png)

**Comment by machida** [comment]
@shirotamaki 
お答えしますー
研修生が日報を書くと、研修生の所属している企業のアドバイザーに通知が飛ぶ仕組みが用意されています。
今回の通知は、企業のアドバイザーが受け取る通知になります。

**Comment by shirotamaki** [comment]
@machida 
度々すいません💦
研修生が所属している企業のアドバイザーへの通知ですが、新規で日報を作成した際の通知は確認できました。
「日報の更新」の定義について確認なのですが、既存の日報の内容を修正して更新した場合は「日報の更新」に該当せず、通知は飛ばないという理解で合っていますでしょうか？

**Comment by machida** [comment]
@shirotamaki おっ、これはIssueのタイトルのみすですね。更新では飛ばず、作成のみ飛びます🙇‍♂️

**Comment by shirotamaki** [comment]
@machida 
いえいえとんでもないです！理解できました💡
ありがとうございます🙏

**Comment by shirotamaki** [comment]
@komagata @machida 
お疲れさまです！こちらのissueの動作確認を本番環境でお願いできますでしょうか？

**Comment by komagata** [comment]
@shirotamaki 本番環境で動作することを確認しました。

**Comment by shirotamaki** [comment]
@komagata ご確認ありがとうございます！closeいたします！
