### ISSUE TITLE
[abstract_notifier] 退会後３ヶ月通知の実装を置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4688]
## 経緯

通知部分を整理するのに[active_delivery](https://github.com/palkan/active_delivery)を使ったものに変えたいと思っているが、前準備として[abstract_notifier](https://github.com/palkan/abstract_notifier)に対応させる必要がある。

## やること

**退会後３ヶ月通知の実装**をabstract_notifierに置き換えたい。

既に[導入したPR](https://github.com/fjordllc/bootcamp/pull/4673)があるのでそちらを参考にする。

- [abstract_notifierで通知を実装する - komagataのブログ](https://docs.komagata.org/5857)
- [現状の退会後３ヶ月通知の実装](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification.rb#L169)
- [abstract_notifierを導入 by komagata · Pull Request #4673 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4673)
- [palkan/active_delivery: Ruby framework for keeping all types of notifications (mailers, push notifications, whatever) in one place](https://github.com/palkan/active_delivery)
- [palkan/abstract_notifier: ActionMailer-like interface for any type of notifications](https://github.com/palkan/abstract_notifier)

**Comment by fuwa-syugyo** [comment]
@komagata 
お疲れ様です。

ただログインしただけでは退会後3ヶ月通知が送られておらず、チェック方法についてご相談させていただきたいです。
システムテストのように` /scheduler/daily ` にアクセスすると通知が送られたのですが、
` /scheduler/daily ` にアクセス→退会後3ヶ月通知をクリック→退会したユーザーページに遷移する　ことを確認すると言う方法でよろしいでしょうか？
以前質問タイムでテスト用DBとdev環境DBは異なっていると伺いましたが、チェック自体は通知がちゃんと表示されているかを確認する程度で良いという認識なので今回の内容では大丈夫かな…と考えています。

◯該当箇所のテストコード
```
  test 'three months have passed since user retired' do
    visit_with_auth '/scheduler/daily', 'komagata'
    visit '/notifications'

    within first('.card-list-item.is-unread') do
      assert_text 'taikai3さんが退会してから3カ月が経過しました。Discord ID: taikai#3333, ユーザーページ: https://bootcamp.fjord.jp/users/1008501353'
    end
  end
```


お手数ですがご確認よろしくお願いいたします。

**Comment by komagata** [comment]
@fuwa-syugyo 

まず、通知を送るタイミングはおっしゃるように`/scheduler/daily`にアクセスがあった時です。
（外部のスケジューラーで毎日ここにアクセスするようになっています）

> /scheduler/daily にアクセス→退会後3ヶ月通知をクリック→退会したユーザーページに遷移する　ことを確認すると言う方法でよろしいでしょうか？

テストのタイトル（主題）が通知を送ることであれば、通知が来ていることを確認できればそれでOKです。（クリックは不要です）

**Comment by fuwa-syugyo** [comment]
@komagata 
ご回答ありがとうございます！
外部スケジューラで`/scheduler/daily`にアクセスするようにしているのですね。

> テストのタイトル（主題）が通知を送ることであれば、通知が来ていることを確認できればそれでOKです。（クリックは不要です）

テストのタイトルは`three months have passed since user retired` で、`/scheduler/daily`にアクセス→通知一覧画面( `/notifications`)に遷移→最新の通知のタイトルが想定通りか をテストしているようです。
テストのタイトルは通知を送ること、ということではないと思います。
`/scheduler/daily`にアクセスすること以外に実際に通知が来ていることを確認する方法はありますでしょうか？

**Comment by komagata** [comment]
@fuwa-syugyo 

> /scheduler/dailyにアクセスすること以外に実際に通知が来ていることを確認する方法はありますでしょうか？

似たコードで呼び出す以外には、無いと思います。
ちょっと求めていることがわからないかもなのですが、別の方法を取る必要はないように思います。

**Comment by fuwa-syugyo** [comment]
@komagata 
開発ミーティングでお話しさせていただきましたが、以下のチェック方法ということで承知いたしました。
* `/scheduler/daily` にアクセスして通知を確認する
* テストが通ることを確認する
ご確認いただきありがとうございます！

**Comment by fuwa-syugyo** [comment]
本番環境で確認していただいたので、closeします。
