### ISSUE TITLE
[abstract_notifier] 退会通知を置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4689]
## 経緯

通知部分を整理するのに[active_delivery](https://github.com/palkan/active_delivery)を使ったものに変えたいと思っているが、前準備として[abstract_notifier](https://github.com/palkan/abstract_notifier)に対応させる必要がある。

## やること

**退会通知の実装**をabstract_notifierに置き換えたい。

既に[導入したPR](https://github.com/fjordllc/bootcamp/pull/4673)があるのでそちらを参考にする。

- [abstract_notifierで通知を実装する - komagataのブログ](https://docs.komagata.org/5857)
- [現状の退会通知の実装](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification.rb#L158)
- [abstract_notifierを導入 by komagata · Pull Request #4673 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4673)
- [palkan/active_delivery: Ruby framework for keeping all types of notifications (mailers, push notifications, whatever) in one place](https://github.com/palkan/active_delivery)
- [palkan/abstract_notifier: ActionMailer-like interface for any type of notifications](https://github.com/palkan/abstract_notifier)

**Comment by SatoshiHaramura** [comment]
@komagata @machida 
お疲れ様です。
ユーザーが退会時のサイト内通知の動作確認を本番環境で行なって頂きたく連絡致しました🙏(管理者orメンターの機能のため)
確認手順と確認内容は以下の通りとなります。

確認手順と確認内容
1. 新たに退会者が出た時に、通知ページ(/notifications)にアクセスし、ユーザーが退会した旨(`😥 xxさんが退会しました。`)の通知があることを確認する。

**Comment by komagata** [comment]
@SatoshiHaramura 本番環境で動作することを確認しました。

**Comment by SatoshiHaramura** [comment]
@komagata 
動作確認して頂き、ありがとうございました！

**Comment by SatoshiHaramura** [comment]
本番環境での動作確認が完了致しましたので、close致します。
