### ISSUE TITLE
アドバイザーは顔を出さない

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#469]
アドバイザーは職場から繋いでるので、その会社のルールを優先。

アイコンが多すぎるので、メンターと受講生だけに絞る。

アドミンとアクティブな現役生だけにしたい。

**Comment by komagata** [comment]
最初から予定としてはある、カメラをオフにするなどの設定画面を作るのがいいかも？

**Comment by machida** [comment]
@komagata 受講生が多くて、ほとんど顔を出すことのない人のアイコンが並んでるのに違和感あるんですよね。あとは、アドバイザーは今ログインをしていることを意識する必要はないので出す必要もないのでは、と、アドバイザーの方にはどんどんアドバイスをしてもらいたいので、その障壁をなくしたい（カメラを止めるなどの手間も極力なくしたい）、というのがあります。

**Comment by masuyama13** [comment]
#511 で対応済みのためcloseします〜
