### ISSUE TITLE
[abstract_notifier] お知らせ通知を置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4693]
## 経緯

通知部分を整理するのに[active_delivery](https://github.com/palkan/active_delivery)を使ったものに変えたいと思っているが、前準備として[abstract_notifier](https://github.com/palkan/abstract_notifier)に対応させる必要がある。

## やること

**お知らせ通知の実装**をabstract_notifierに置き換えたい。

既に[導入したPR](https://github.com/fjordllc/bootcamp/pull/4673)があるのでそちらを参考にする。

- [abstract_notifierで通知を実装する - komagataのブログ](https://docs.komagata.org/5857)
- [現状のお知らせ通知の実装](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification.rb#L112)
- [abstract_notifierを導入 by komagata · Pull Request #4673 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4673)
- [palkan/active_delivery: Ruby framework for keeping all types of notifications (mailers, push notifications, whatever) in one place](https://github.com/palkan/active_delivery)
- [palkan/abstract_notifier: ActionMailer-like interface for any type of notifications](https://github.com/palkan/abstract_notifier)

**Comment by tomonariha** [comment]
@komagata @machida 
本番環境でのアプリのお知らせ通知と、お知らせ通知メールの動作確認をお願いします🙏
ディスコードに通知がきていることは確認ができました。
「今週のリリース2022年07月07日」がアプリの通知とメールに来ているかで確認していただけると思います。
このお知らせを作った本人なためか、私の方には通知とメールが来ませんでした😭
よろしくお願いします！

**Comment by tomonariha** [comment]
machidaさんに本番環境でご確認いただいたので、issueをclose致します。
