### ISSUE TITLE
[abstract_notifier] 回答通知を置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4694]
## 経緯

通知部分を整理するのに[active_delivery](https://github.com/palkan/active_delivery)を使ったものに変えたいと思っているが、前準備として[abstract_notifier](https://github.com/palkan/abstract_notifier)に対応させる必要がある。

## やること

**回答通知の実装**をabstract_notifierに置き換えたい。

既に[導入したPR](https://github.com/fjordllc/bootcamp/pull/4673)があるのでそちらを参考にする。

- [abstract_notifierで通知を実装する - komagataのブログ](https://docs.komagata.org/5857)
- [現状の回答通知の実装](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification.rb#L101)
- [abstract_notifierを導入 by komagata · Pull Request #4673 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4673)
- [palkan/active_delivery: Ruby framework for keeping all types of notifications (mailers, push notifications, whatever) in one place](https://github.com/palkan/active_delivery)
- [palkan/abstract_notifier: ActionMailer-like interface for any type of notifications](https://github.com/palkan/abstract_notifier)

**Comment by yuki-snow1823** [comment]
他issueがレビューまたは質問のご回答待ちになったので着手します。
よろしくお願いします。

**Comment by yuki-snow1823** [comment]
@komagata 
個人的に気になったところなのですが
>通知部分を整理するのにactive_deliveryを使ったものに[変え](https://github.com/palkan/active_delivery)たいと思っているが、事前準備として[abstract_notifier](https://github.com/palkan/abstract_notifier)に対応させる必要がある。

こちらに関して、active_deliveryのどこら辺の実装を見て、先にactive_notiferに対応させないとダメだとお気づきになったのでしょうか。まだまだその辺の理解が及ばず、質問させていただきました。

**Comment by komagata** [comment]
@yuki-snow1823 abstruct_notifierを知ったのはREADMEのRelated projectsに書いてあったからです。

active_deliveryはaction_mailer的な処理をまとめてやってくれるライブラリなので自前の処理をaction_mailerと同じインターフェースに書き換える必要があるなと考えていたらまさにabstruct_notifierがそのために用意されたライブラリだとわかり、見た瞬間に飛びついた感じです。

**Comment by yuki-snow1823** [comment]
@komagata 
ご説明ありがとうございます。

自分もGemを開発するようなことがあればRelated Projectを示したいなと思いました。
そしてそういう応用のさせ方があると知れてよかったです！

**Comment by yuki-snow1823** [comment]
@komagata 
こちらの本番環境での動作チェックは、実際にテスト用のQ&Aを作ってどなたかに回答をしてもらい
通知を確認するような流れで大丈夫でしょうか...？

**Comment by komagata** [comment]
@yuki-snow1823 はい、そちらでお願いします〜

**Comment by yuki-snow1823** [comment]
![スクリーンショット 2022-09-21 8 32 17](https://user-images.githubusercontent.com/59280290/191382891-7838da98-29a9-4fdc-8add-f7dfab768bb1.png)

動作確認完了しました！

**Comment by komagata** [comment]
@yuki-snow1823 下記の通りIssueのCloseをお願いします〜

[チーム開発の作業手順 \| FBC](https://bootcamp.fjord.jp/pages/305#-11)

**Comment by yuki-snow1823** [comment]
遅れてすみません！完了しました。
