### ISSUE TITLE
[abstract_notifier] お知らせのDiscord通知を置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4699]
## 経緯

通知部分を整理するのに[active_delivery](https://github.com/palkan/active_delivery)を使ったものに変えたいと思っているが、前準備として[abstract_notifier](https://github.com/palkan/abstract_notifier)に対応させる必要がある。

## やること

**お知らせのDiscord通知の実装**をabstract_notifierに置き換えたい。

既に[導入したPR](https://github.com/fjordllc/bootcamp/pull/4676)があるのでそちらを参考にする。

- [abstract_notifierで通知を実装する - komagataのブログ](https://docs.komagata.org/5857)
- [現状のお知らせDiscord通知の実装](https://github.com/fjordllc/bootcamp/blob/b584dd14f9cd82ab99f77ed487deeb4be76d7f3a/app/models/announcement_callbacks.rb#L36)
- [Discord通知にabstract_notifierを導入 by komagata · Pull Request #4676 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4676)
- [palkan/active_delivery: Ruby framework for keeping all types of notifications (mailers, push notifications, whatever) in one place](https://github.com/palkan/active_delivery)
- [palkan/abstract_notifier: ActionMailer-like interface for any type of notifications](https://github.com/palkan/abstract_notifier)

**Comment by yuma-matsui** [comment]
@komagata @machida 
お疲れ様です！
こちらの本番環境での動作確認をお願いいたします。

**Comment by machida** [comment]
@yuma-matsui 今日の18:56のお知らせの通知が飛んでいて、この通知はデプロイ後なので、無事動いていると確認できました🙆‍♂️

**Comment by yuma-matsui** [comment]
@machida 
早速ご確認いただきありがとうございます！！
Discordの方でも確認させていただきました。

動作検証が完了したのでクローズします。
