### ISSUE TITLE
お知らせ機能

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#471]
## お知らせ機能

これは、slack で channel で通知しているお知らせを bootcmap に移すのが目的。
slack では情報が流れてしまうので、 bootcmap にお知らせ機能を付け、そこからお知らせにアクセスする。

## お知らせ機能の詳細

- /announcements/new から admin が お知らせを投稿
- /announcement/ に今までのお知らせが見れる
- 新規 announcement が投稿されると、すべてのユーザーに通知が行く

- [ ] お知らせ一覧
- [ ] お知らせ詳細
- [ ] お知らせ投稿
- [ ] お知らせ編集
- [ ] お知らせ削除

## お知らせ機能が使われるとき

- 2018年10月のmeetupの開催日時についてのお知らせ
- 2018年忘年会のお知らせ
- XXXさんが株式会社XXXに就職が決まりました
- 2018年の夏休みのお知らせ
- RubyKaigi2019のお知らせ

などなど

**Comment by gouf** [comment]
@machida @komagata 
Assign してもらったのでやっていきます 💪 
bootcamp での Pull Request 5回チャレンジの第1回目ですね

ムリせず 訊くべきは訊くという姿勢で臨みたいと思います

**Comment by machida** [comment]
@gouf はい、頑張ってくださいー！始めは色々レビューをされてなかなかマージがされなくて大変みたいですが、みんなそうなので、くじけず頑張ってください！！

このissueの進め方なんですが、

https://github.com/fjordllc/bootcamp/pull/485

このフィーチャーブランチを作りました。
このブランチからブランチを作って、作業が完了したらこのブランチへPRをお願いします。

**Comment by sanfrecce-osaka** [comment]
@machida 少し疑問に思ったんですがこの機能ってbootcampに新機能が追加されたりバグフィックスされたりした場合には使わないんですか？
〇〇が☓☓の機能を追加してくれました！みたいなお知らせが他の生徒に届くとユーザーからの感想を受け取れて今後の開発に繋げられたり開発者のモチベーションアップに繋がったりしていいのではないかと感じました。
また、そうするとadmin以外にもお知らせの作成権限があった方がいいのかも？と思いました。

**Comment by machida** [comment]
@sanfrecce-osaka 使います。ただ、まずはadminだけで運用します。というのも、森塚さんは「〇〇が☓☓の機能を追加してくれました！みたいなお知らせ」をしたいタイプの人かと思いますが、そうではない人もいたりするので、告知は実装した人任せではなく、告知のフローを作るところから始めたいからです。

**Comment by shibaaaa** [comment]
こちら対応済みのようなのでクローズしておきます〜

**Comment by machida** [comment]
ありがとうございますー
