### ISSUE TITLE
ユーザー個別ページから就活中フラグをオン・オフができるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4710]
管理者でログインしたときだけこの部分に就活中フラグをオン・オフを表示するようお願いします🙏

<img width="1425" alt="貼り付けた画像_2022_06_10_12_51" src="https://user-images.githubusercontent.com/168265/172986814-6f4ff35c-b61e-444e-8902-cbd9a1a7e3f8.png">

こちらを参考にお願いします。
https://github.com/fjordllc/bootcamp/pull/4833

**Comment by kazumi3858** [comment]
@machida さん

お疲れ様です😄

こちらのissueがカンバンの上にあったので取り掛かる予定だったのですが、
#4833 のプルリクがマージされるまでは作業がしづらいなと感じたので他のissueから進めることにします。
フィヨルドのルールではカンバンの上から着手ように書かれていたので、念のためご報告です。
何か問題がございましたらご連絡くださいませ。

**Comment by machida** [comment]
おおー、すいません！こちらクローズしておきます🙇‍♂️調査をしていただいたのでポイントには追加お願いしますー
別のIssueをアサインします！

**Comment by kazumi3858** [comment]
@komagata さん @machida さん

お疲れ様です。
お手数ですが、こちらのイシューの本番環境での動作確認をお願いいたします✨🙏

**Comment by machida** [comment]
@kazumi3858 動作確認しました！！OKですー🙆‍♂️

**Comment by kazumi3858** [comment]
machidaさん
ご確認ありがとうございました✨😄
