### ISSUE TITLE
ユーザー個別ページから卒業フラグをオンにできるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4711]
https://github.com/fjordllc/bootcamp/pull/4875
こちらを参考にお願いします🙏

この辺にボタンを置いておいてください。
デザインは machida がやるので、実装が終わったらレビューと同時進行でメンションお願いしますー

<img width="1334" alt="貼り付けた画像_2022_06_09_14_53" src="https://user-images.githubusercontent.com/168265/172774287-738b8049-adf3-479a-8a5c-facf96f621d1.png">

**Comment by tomonariha** [comment]
@komagata @machida
こちら管理者のみの機能ですので、本番環境での確認をよろしくお願いします🙏
<img width="1431" alt="スクリーンショット 2022-06-16 17 44 33" src="https://user-images.githubusercontent.com/96340764/175234472-ee49218c-b78e-49a4-b155-9622710aa701.png">

**Comment by komagata** [comment]
@tomonariha 本番環境で確認しました〜

**Comment by tomonariha** [comment]
@komagata さん、確認ありがとうございます🙏
動作確認して頂いたので、issueをclose致します。
