### ISSUE TITLE
コメント完了後、プレビューの表示がクリアされない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4715]
## 再現手順

1. 日報にコメントを投稿する
2. 投稿完了後、投稿フォームのプレビュータブを開く
3. プレビュータブに1で投稿した内容が表示される

![vBDBMl0dRD](https://user-images.githubusercontent.com/1148320/165401064-2f401f3b-29e0-4f39-99e7-6fd1ff6b3511.gif)

## 期待する振る舞い

上記3でプレビュータブの内容も真っ白になっている

致命的な問題では無いので優先度は低めでもいいかもしれません。

**Comment by siso25** [comment]
不具合について調査したところ日報のコメントに加え、Q&Aのコメントも同様の事象が起きていることがわかりました。
対象のソースは以下の通りなのですが、このissue内でQ&Aのコメントについても修正した方が良いでしょうか。

## 修正対象
### 日報のコメント
app/javascript/comments.vue
### Q&Aのコメント
app/javascript/answers.vue

**Comment by komagata** [comment]
@siso25 そちらはやらなくて大丈夫です〜
別Issueとして作成しておいていただければありがたいです〜！

**Comment by siso25** [comment]
@komagata 
承知しました！
類似についての別Issueを作成します。

**Comment by komagata** [comment]
@siso25 Issue作成ありがとうございます〜！

**Comment by siso25** [comment]
本番環境でコメントのプレビューがクリアされることを確認しましたので、クローズさせていただきます。
