### ISSUE TITLE
メンターログイン時の提出物一覧（未アサイン）にページ内リンクを設置

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4717]
<img width="1683" alt="貼り付けた画像_2022_05_18_22_28" src="https://user-images.githubusercontent.com/168265/169051164-7fe49c67-3e04-43ec-a874-5a9f41f50577.png">

**Comment by ai-24** [comment]
@komagata さん
お手数お掛け致しますが、こちらのIssueの動作確認を本番環境でお願いできますでしょうか。

確認していただきたいポイントは以下になります。
## ページ内リンク
1. 提出物一覧にある未アサインタブのページ内に、提出物が作成されてからの経過日数とその経過日数に該当する提出物の個数が表示されたページ内リンクが動作することを確認してください。リンク先は、ページ内に表示されているページ内リンクと同じ表示のある見出しになります。提出物数が０の場合はリンクがクリックできない仕様になっております。
2. リンクが動作し画面遷移した後に、画面を別の要素までスクロールし、ブラウザの再リロードを行なってください。リロード完了後、1でリンクしたリンク先に画面遷移することを確認してください。

## ページャー
**またページ内リンクを設置してことにより発生した、無限ループを解消するためにページャーの実装も一部修正しております。**
よって、ページャーに関する部分も確認いただきたいです。

無限ループ解消に取り組んだ流れは以下となります。
無限ループの起因となっていたコードを削除した。（その際、他に影響がないか自身で提出物一覧配下を確認。またチームメンバーにも確認を行なった。）しかし削除すると、ブラウザの戻る矢印ボタンをクリックした際にページャーが動作しないことが発覚。(下記動画のURL、ページャー、ブラウザ戻るボタンに注目してください。)そのため、無限ループの起因となるコードを削除するのではなく、実装方法を変更いたしました。

[![Image from Gyazo](https://i.gyazo.com/b560599542bc108fe775c92268ffacc0.gif)](https://gyazo.com/b560599542bc108fe775c92268ffacc0)

#### 確認していただきたいこと
提出物一覧でページャーが存在するタブのページに移動し、ページャーが正しく動作することを確認してください。その際ブラウザの戻る（矢印ボタン）もクリックして動作確認を行なってください。

<img width="879" alt="スクリーンショット 2022-08-15 19 10 10" src="https://user-images.githubusercontent.com/76685187/184617721-b5bd5e97-1e38-496e-980b-6b5bb61788ea.png">

よろしくお願いいたします。

**Comment by komagata** [comment]
@ai-24 こちら動作確認しました。問題ありませんでした〜。

**Comment by ai-24** [comment]
@komagata さん
ありがとうございました！

動作確認出来ましたのでcloseします。
