### ISSUE TITLE
日報個別ページに名前を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4718]
日報個別ページにはIDしか表示されてないので、名前も表示したい。

<img width="488" alt="貼り付けた画像_2022_04_27_11_47" src="https://user-images.githubusercontent.com/168265/165429652-1ae27f87-a58e-413a-b26c-e8c5f7223915.png">

**Comment by isshi-hasegawa** [comment]
@machida 

もとのコードでは、日報作成者の名前にマウスオーバー時に名前が**ポップアップする**実装になっていました。
提出物やQ&A、Docsなどの個別ページを確認すると、**ポップアップなし**の実装になっていましたので、 #4790 では**ポップアップなし**の方に合わせました。
この認識であってますでしょうか？

## 変更前

<img width="1051" alt="スクリーンショット 2022-05-10 21 42 37" src="https://user-images.githubusercontent.com/53898556/167630936-2471df9d-12a1-4bf6-8190-dec1cb2bc2eb.png">

## 変更後

<img width="1060" alt="Cursor_と__development__今日は頑張りました___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/53898556/167628681-4d623ccd-bd6c-4bca-a9f1-4ed31152fc12.png">

**Comment by machida** [comment]
@isshi-hasegawa あーそうか、ポップアップで表示されるようになってたんですね。それを見逃してました🙏他の部分と同じように表示でお願いしますー。

**Comment by isshi-hasegawa** [comment]
本番環境で動作確認できたのでCloseいたします！
