### ISSUE TITLE
Markdown 内のメンションの a タグに class が付くようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4720]
日報などの Markdown のエディタで、

```
@machida 
```

と、書くと、

```
<a href="XXXX">machida</a>
```

このような HTML になる。この HTML の a タグに以下のように class が付くようにしたい。

```
<a href="XXXX" class="mention-link">machida</a>
```

---

なぜclassが必要か？

ログイン無しでも見れるブログでも、Markdown のエディタを使っているので、ブログの際にはクリックが出来ないように css で設定したいため。

**Comment by isshi-hasegawa** [comment]
本番環境での動作を確認できましたのでCloseします〜
