### ISSUE TITLE
ダッシュボードに、自分が作成したWIPのお知らせ、WIPのイベントの一覧を表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4727]
現在、ダッシュボードに、

<img width="778" alt="貼り付けた画像_2022_04_28_13_44" src="https://user-images.githubusercontent.com/168265/165678218-1134ac0f-5e32-44ba-adb2-cd08e815920d.png">

WIPの日報、提出物、Q&Aは表示されるが、
WIPのお知らせ、イベント は表示されないので表示されるようにしたい。

**Comment by ai-24** [comment]
本番環境での動作確認が出来ましたのでcloseいたします🎉
