### ISSUE TITLE
ユーザーページでの提出物閲覧権限の設定がうまくいっていない

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/bootcamp#474]
### 現状
ユーザーページでは`current_user`ではなく`表示されているユーザー`が確認済の提出物を持っているかどうかでタブの表示非表示を判定している

### 問題点
- `current_user`が、あるプラクティスの提出物を持っていない状態でも`表示されているユーザー`がそのプラクティスの確認済の提出物を持っていれば閲覧できてしまう
- `表示されているユーザー`の確認済でない提出物へのリンクも表示されてしまう
  - リンク先は閲覧はできない

### 参考画像
- `current_user`の提出物
[![Image from Gyazo](https://i.gyazo.com/2d1eb93d58bb5e269e807ff8ccce6a00.png)](https://gyazo.com/2d1eb93d58bb5e269e807ff8ccce6a00)
- `別ユーザー`の提出物
[![Image from Gyazo](https://i.gyazo.com/96f92324b498031c74cc47f5ccb0bf9b.png)](https://gyazo.com/96f92324b498031c74cc47f5ccb0bf9b)

**Comment by machida** [comment]
こちら作業中になっているので、作業してる方、アサインをお願いします

**Comment by sanfrecce-osaka** [comment]
@machida 
すみません、設定し忘れてました。
