### ISSUE TITLE
[newspaper] 完了プラクティスのキャッシュ削除をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4758]
learning作成・削除時のキャッシュ削除処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/learning_callbacks.rb#L14)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by machida** [comment]
@yuma-matsui やることがなくなったら、次はこちらをお願いしますー
