### ISSUE TITLE
[newspaper] 購読解除トークン作成をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4759]
UserCallbacksにある購読解除トークン作成処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/user_callbacks.rb#L5)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by lanactindi** [comment]
@komagata 駒形さん、お疲れ様です。
こちらのissueに関して、今日の午後リリースしましたが、本番でユーザーを登録するのはちょっと難しいです。
理由は以下の画像みたいに、本物のクレジットカードが必要なので駒形さんがご確認していただいてもよろしいでしょうか。
よろしくお願い致します。
<img width="693" alt="Screen Shot 0004-10-06 at 18 31 08" src="https://user-images.githubusercontent.com/94335407/194278436-e14c5c76-0b5e-4e7f-902e-26c0114d542e.png">

**Comment by lanactindi** [comment]
> @lanactindi 購読解除はすぐ戻せるので、自分のアカウントで試すのはどうでしょうか？

それはちょっと難しいと思います。すみませんでした。

**Comment by lanactindi** [comment]
@komagata 相談してくれてありがとうございました。
確認できたのでcloseします！
