### ISSUE TITLE
ユーザー一覧 > 企業別ページにローディングの表示が欲しい

### ISSUE THREAD

**Issue by taka61** [fjordllc/bootcamp#4760]
## 現状
「ユーザー一覧」のページから「企業別」のタブをクリックすると、「企業別ユーザー」を表示するまでに下記の状態で固まるため、読み込み中かどうか認識しづらい

<img width="1404" alt="スクリーンショット 2022-05-04 12 38 57" src="https://user-images.githubusercontent.com/80372144/166620752-a95d5312-3f22-4c95-94f2-ddf7e1b5dcbb.png">

## 要望
読み込み中のときは[日報一覧](https://bootcamp.fjord.jp/reports)などと同様にローディングを表示するようにしてほしい。

![image](https://user-images.githubusercontent.com/80372144/166621199-84c8218e-ec66-42b0-801f-7b402da99f52.png)

## 環境
OS: macOS Monterey 12.3.1
ブラウザ: Google Chrome Version 96.0.4664.93

## 関連issue
Ref: #3552

**Comment by machida** [comment]
📝 
https://github.com/fjordllc/bootcamp/pull/5315
こちらのブランチを手元に持ってきて作業をお願いします。

**Comment by daiki0381** [comment]
こちら問題無かったので、Closeします。
