### ISSUE TITLE
未チェックの日報はありませんは、笑顔の表示にしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4763]
現在、未チェックの日報が0の場合、このような表示になる。

<img width="1085" alt="貼り付けた画像_2022_06_10_13_11" src="https://user-images.githubusercontent.com/168265/172988797-63a7aaa9-aaac-4c8b-90cc-f571e8ffdba3.png">

このように変更したい。

<img width="814" alt="image" src="https://user-images.githubusercontent.com/168265/172989121-e9c7ab76-f879-4877-8ca9-b734c1866530.png">

<img width="557" alt="image" src="https://user-images.githubusercontent.com/168265/172989177-8566b625-16ab-4643-84bb-108d78022d2b.png">

**Comment by kazumi3858** [comment]
@machida さん

お疲れ様です😄
こちらのissueの内容を確認したところ、すでに「未チェックの日報はありません」の絵文字は笑顔になっておりました。

![image](https://user-images.githubusercontent.com/97820517/173215052-5f4e4bab-5490-4cd4-9504-005884013245.png)

該当のコード（`app/javascript/reports.vue` 37行目~）

```javascript
  .o-empty-message(v-else)
    .o-empty-message__icon
      i.fa-regular.fa-smile
    p.o-empty-message__text
      | 未チェックの日報はありません
```

ご確認よろしくお願いいたします🙇‍♂️

**Comment by kazumi3858** [comment]
@machida さん

お疲れ様です😸
[こちらのコメント](https://github.com/fjordllc/bootcamp/issues/4710#issuecomment-1153078968)はこちらのイシューに対してでしょうか？
またクローズになっていないようなので念のためご報告いたします🙇‍♂️

**Comment by machida** [comment]
@kazumi3858 すいません、このIssueに対してでしたー。外出中でモバイルから操作してたら、操作ミスをしてしまいました🙇‍♂️クローズもモバイルからだとできないので、今夜クローズしておきますー。

**Comment by kazumi3858** [comment]
承知しました😊
お忙しい中ご対応ありがとうございました🙇‍♂️🙇‍♂️

**Comment by machida** [comment]
クローズしましたー！調査ありがとうございます！
