### ISSUE TITLE
企業個別ページに企業一覧へのリンクを貼りたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4768]
http://localhost:3000/companies の企業一覧から、企業個別ページに入る。
このページに企業一覧に戻るリンクを設置したい。

<img width="1397" alt="貼り付けた画像_2022_05_06_14_05" src="https://user-images.githubusercontent.com/168265/167070432-14b3039b-e356-4e96-8471-5db2e5565f09.png">

**Comment by masanarih0ri** [comment]
こちら本番環境で動作確認しました！
closeのタイミング間違えていて、マージされたらだと思ってました。次回以降気をつけます！
