### ISSUE TITLE
大名エンジニアカレッジ特有の機能・フラグを削除する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4769]
daimyo ユーザーのための分岐のコードを全て削除。
`daimyo` で grep して見つかったものを削除お願いします。

**Comment by Saki-htr** [comment]
@komagata @machida 
お疲れ様です。
削除する対象について質問がございますので、お手すきの際にご回答いただけますと幸いです🙏

## Q. 初期データ ・テストデータのdaimyo関連のユーザーも削除しますか?
現在、daimyoユーザーのための分岐のコードを全て削除したところです。(PullRequest #5012) 

`db/fixtures/users.yml`,`test/fixtures/users.yml`等の初期データをにはdaimyo関連のユーザー(`daimyo`,`daimyo-adviser`,`daimyo-kensyu`,`daimyo-mentor`,`daimyo-sotugyou`)がありますが、そちらも削除した方がよろしいでしょうか??

**Comment by komagata** [comment]
@Saki-htr はい、削除お願いします〜

**Comment by Saki-htr** [comment]
@komagata 
かしこまりました! ご回答ありがとうございます🙏

**Comment by Saki-htr** [comment]
本番環境で検証ツールを開きながらbootcampアプリを一通り触り、エラーが起こらないことを確認しましたので、issueをcloseいたします。
