### ISSUE TITLE
卒業した日付を記録したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#477]
- [ ] 管理者のユーザー情報編集ページに卒業ボタンを作る
- [ ] ユーザー情報に卒業日時を持つ
- [ ] ユーザーの個別ページに卒業日時を出す（卒業してた場合のみ）

**Comment by ycoda** [comment]
viewについて質問です。今のところ卒業日というフィールドを作ってviewをこのようにしていました。

![screenshot from 2018-09-10 18-53-35](https://user-images.githubusercontent.com/3740249/45290623-0b251180-b52b-11e8-813b-0500ebeeb6f7.png)

卒業というチェックボックスが既にあったので、これにチエックが入ったら卒業ボタンがアクティブになり、クリックしたら今日の日付をテキストフィールドに表示するというようにしていましたが、
日報のコメントを受けて、
> viewにはフィールドを用意せず、rubyの中だけで時間をいじるのはどうでしょうか？

そのように変更しようと思うのですが、どのようなviewにしたら良いでしょうか。

**Comment by komagata** [comment]
@ycoda なるほど、すでにあるものを利用するならば、ボタンも追加せず、更新時に卒業のステータスがOFFからONに変更があったら卒業日を保存するというようにするのがいいかもですね。（callbackに書く）
