### ISSUE TITLE
会員登録、ユーザー編集の「学習に使うマシン・OS」はラジオボタンにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4771]

**Comment by komagata** [comment]
確かにですね！

**Comment by isshi-hasegawa** [comment]
@machida 
ラジオボタンの実装方法として、以下の2通りを考えています。
デザインを考慮するとどちらを選択するべきか、ご意見を頂きたいです〜

1. collection_radio_buttons
    - 	例：日報作成画面の「今日の気分
    - https://github.com/fjordllc/bootcamp/blob/main/app/views/reports/_form.html.slim
    - こちらはデザイン上のカスタマイズがしにくい場合があると、 komagata さんより共有頂きました
2. radio_button
    - 	例：お知らせ作成画面の「通知ターゲット」 
    - https://github.com/fjordllc/bootcamp/blob/main/app/views/announcements/_form.html.slim

**Comment by machida** [comment]
@isshi-hasegawa 
どっちでも大丈夫ですが、2方が素直な感じがしましたー

**Comment by isshi-hasegawa** [comment]
本番環境での動作確認ができましたので、このIssueはCloseいたします〜
