### ISSUE TITLE
企業 > ユーザー一覧 に 企業一覧へのリンクを貼りたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4773]
http://localhost:3000/companies の企業一覧から、企業個別ページに入る。
その企業のユーザー一覧へ移動。
このページに企業一覧に戻るリンクを設置したい。

<img width="1580" alt="貼り付けた画像_2022_05_06_14_07" src="https://user-images.githubusercontent.com/168265/167070703-cdda2f2e-8958-497c-9f1e-97e44b6c6101.png">

**Comment by tomonariha** [comment]
本番環境で確認できましたので、closeします。
