### ISSUE TITLE
企業 > 日報一覧 に 企業一覧へのリンクを貼りたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4774]
http://localhost:3000/companies の企業一覧から、企業個別ページに入る。
そこから日報へ移動。
このページに企業一覧に戻るリンクを設置したい。

<img width="1581" alt="貼り付けた画像_2022_05_06_14_11" src="https://user-images.githubusercontent.com/168265/167070897-a1862e58-8203-416f-bcec-262ca83455da.png">

**Comment by ai-24** [comment]
@machida 
お疲れ様です。
細かいことなのですが、リリースノートを書いていて気になったことがあったので確認させてください🙏
こちらのURL http://localhost:3000/companies へ直接入るとページが見れたのですが、フィヨルドのページからこちらのページまでの移動の仕方が見つけられなかったので、教えていただけると助かります。
リリースノートにもその内容を追加しようと思っています！

**Comment by machida** [comment]
@ai-24 
フッターにリンクがありますー
<img width="1274" alt="貼り付けた画像_2022_05_26_10_27" src="https://user-images.githubusercontent.com/168265/170396206-b0d59de5-bf7c-403b-b73b-95662384c51a.png">

**Comment by ai-24** [comment]
@machida 
お手数おかけいたしました🙇‍♀️
ありがとうございます！！

**Comment by ai-24** [comment]
本番環境で動作確認ができましたのでcloseします！
