### ISSUE TITLE
企業 > 提出物一覧 に 企業一覧へのリンクを貼りたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4775]
http://localhost:3000/companies の企業一覧から、企業個別ページに入る。
そこから提出物へ移動。
このページに企業一覧に戻るリンクを設置したい。

<img width="1578" alt="貼り付けた画像_2022_05_06_14_14" src="https://user-images.githubusercontent.com/168265/167071190-0aa3cae7-55f0-4d04-98ba-3d19d011b2ec.png">

**Comment by kazumi3858** [comment]
本番環境での動作確認が済みましたのでCloseいたします😊
