### ISSUE TITLE
トップページの資本金修正

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4788]
500万円 に修正。

**Comment by machida** [comment]
ここにアクセス
<img width="1335" alt="貼り付けた画像_2022_05_18_15_55" src="https://user-images.githubusercontent.com/168265/168976602-d0fd773b-7aec-4206-ba1d-7fa87aacc04e.png">

この部分を修正
<img width="788" alt="貼り付けた画像_2022_05_18_15_55" src="https://user-images.githubusercontent.com/168265/168976521-525cc65b-6b81-4e12-90bf-3ae46ab053ae.png">

**Comment by ai-24** [comment]
本番環境での動作確認が終わりましたのでクローズします！
