### ISSUE TITLE
ユーザー情報変更から退会できない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4789]
管理者でユーザー情報変更から下記のように退会日を入力して更新しても保存されない

<img width="600" alt="スクリーンショット 2022-05-10 14 42 44" src="https://user-images.githubusercontent.com/16577/167556598-56e2b253-a1f9-4c11-84aa-9ca138b1c630.png">

**Comment by rosh-1228** [comment]
@komagata @machida 
仕様について質問があります。

## 質問
- 管理者は自身の以下の情報を変更させる必要があるのでしょうか？

![_development__ユーザー登録情報変更___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64620506/168518279-3ab7556d-4d55-46e3-a6ae-de8e493f789f.png)

上記画像の機能は、管理者が受講者等の他者の登録情報変更を行う機能だと推察しました。
本issueでは、管理者が自身の情報変更時に退会日を設定し更新を行えるようにしたいというものだと思いますが、そもそも自身の情報変更時に、上記画像にある情報まで変更する必要があるのかなと疑問に思いました🤔

## 提案
以上の質問のご回答次第で3つの実装方法があるのかなと思い、以下に記述しました。

1. 上記画像の情報変更は必要
=> 管理者は自身の情報変更時に上記画像の情報変更を行えるようにする。
2. 一部の情報変更のみ必要
=> 必要な情報のみ変更を行えるようにする。
3. 上記画像の情報変更は必要ない
=> 管理者が自身の情報変更時は上記画像の操作画面を表示させないようにする。(管理者Aから管理者Bは情報変更可能)

お手数ですがご回答いただけますと幸いです🙇‍♂️

## 原因
これより以下は、管理者自身が退会日を入力して更新しても保存されない原因について記述しております。

管理者自身の情報変更ページにて、退会日を入力し更新を行なったところ、`Unpermitted parameters`がログとして流れてきました。
```
Unpermitted parameters: :retired_on, :graduated_on, :free, :github_collaborator
```
つまり、`退会`以外に、`卒業` `特殊ユーザー属性の無料` `外部サービス`の情報更新ができない状態にあると思います。

更新できない理由としましては、`app/views/users/show.html.slim`の64行目にて`edit_current_user_path`が渡されております。
```ruby
- if current_user == @user
  li.card-main-actions__item
    = link_to '登録情報変更', edit_current_user_path, class: 'card-main-actions__action a-button is-sm is-secondary is-block'
- elsif admin_login?
  li.card-main-actions__item
    = link_to '管理者として情報変更', edit_admin_user_path, class: 'card-main-actions__action a-button is-sm is-secondary is-block'
```
この状態で登録情報変更を行なった場合、`app/controllers/current_user_controller.rb`を使うことになり、こちらのコントローラーのuser_paramsでは、`:retired_on, :graduated_on, :free, :github_collaborator`が許可されていないため、管理者は自身の退会や卒業を更新することができません。
```ruby
def user_params
    params.require(:user).permit(
      :adviser, :login_name, :name,
      :name_kana, :email, :course_id,
      :description, :job_seeking, :discord_account,
      :github_account, :twitter_account, :facebook_url,
      :blog_url, :times_url, :password, :password_confirmation,
      :job, :organization, :os,
      :experience, :prefecture_code, :company_id,
      :nda, :avatar, :trainee,
      :mail_notification, :job_seeker, :tag_list,
      :after_graduation_hope, :training_ends_on
    )
end
```

**Comment by komagata** [comment]
@rosh-1228 

> 1. 上記画像の情報変更は必要

でお願いします〜！

**Comment by rosh-1228** [comment]
@komagata 
ご返信ありがとうございます！
それではこちらで実装します！

1. 上記画像の情報変更は必要
=> 管理者は自身の情報変更時に上記画像の情報変更を行えるようにする。

**Comment by komagata** [comment]
@rosh-1228 本番環境で動作することを確認しました。

**Comment by rosh-1228** [comment]
@komagata 
ご確認ありがとうございます！
