### ISSUE TITLE
日報作成ページでのプラクティス選択時の検索ボックスで検索ワードを含むプラクティスが表示されない

### ISSUE THREAD

**Issue by kasai441** [fjordllc/bootcamp#4793]
## 概要

おそらく１、2ヶ月まえから、日報のプラクティスの検索ボックスで検索ワードを含むプラクティスが表示されなくなりました。
検索せずにプルダウンで全部の中から選択していますが、数が多く、すこし不便です。
観測範囲は自分の取り組んでいる「Webサービスを作って公開する」だけです。

## 再現手順

1. 日報の新規作成
2. プラクティス検索ボックスに「サービス」と入力
3. 「サービス」を含むプラクティスがすべて表示されない

## 期待される振る舞い

「サービス」を含むすべてのプラクティスが表示される

## スクリーンショット

- 現状：以下のものだけ表示される
<img width="698" alt="image" src="https://user-images.githubusercontent.com/50036730/167756929-1775eac1-3e56-426a-afa8-64d9c833d922.png">

- 期待される動き：サービスを含むプラクティスが網羅される
<img width="668" alt="image" src="https://user-images.githubusercontent.com/50036730/167757092-44e49ea4-d47e-45d4-b915-964ab6722a90.png">
<img width="682" alt="image" src="https://user-images.githubusercontent.com/50036730/167757220-c527ef5e-d55e-4263-a4a9-ae8be5391009.png">

## 環境

 - OS: iOS 12.3
 - ブラウザ: chrome  100.0.4896.127

**Comment by komagata** [comment]
@kasai441 なるほどですね。
もしよろしければ修正にチャレンジしてみると勉強になるかもしれません〜！

**Comment by machida** [comment]
@SatoshiHaramura 
選択部分には
https://github.com/Choices-js/Choices
このライブラリを使っています。

公式をざっと読んでみたのですが、searchResultLimit あたりの設定を変えると修正できそうです。
検索結果は 20 くらいに設定しておけばいいかと思いますー

**Comment by SatoshiHaramura** [comment]
本番環境で動作確認が完了致しましたので、close致します。
