### ISSUE TITLE
日報の編集画面で最近の日報一覧が表示されていない

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/bootcamp#480]
発生しているのは編集画面のみで作成画面では正常に表示されている
[![Image from Gyazo](https://i.gyazo.com/376a8f407255cd6ef4d0bcbd0d95524e.png)](https://gyazo.com/376a8f407255cd6ef4d0bcbd0d95524e)

**Comment by komagata** [comment]
#482 でやるのでClose。
