### ISSUE TITLE
Q&A一覧でコメントがまだ付いていない場合はあえてそれを目立たせる

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4805]
Q&A一覧を開いたとき、コメントが全く付いていない質問というのは誰かのヘルプが絶対必要な状況なので、ぱっと見て「あ、この質問はまだコメントが付いてないな」というのがわかるようになってた方がいいと思います。

たとえば以下はその一案です。
![save](https://user-images.githubusercontent.com/1148320/167962603-4f1f3f32-1a1d-47d4-a0cc-98e0f1462ee9.png)

（参考)現状はコメントが付いてないと、コメント数の表示が何もされません。
![save](https://user-images.githubusercontent.com/1148320/167963784-710d9b4a-75af-443e-a412-36f1793ad456.png)

**Comment by machida** [comment]
📝
回答が0のときは、該当箇所に class=“is-danger” というクラスが付くようにする。赤くする、太字にする、はmachidaがやります。

**Comment by yuma-matsui** [comment]
本番環境での動作が確認できましたのでcloseします！

@machida 
デザインのご対応ありがとうございました😌
