### ISSUE TITLE
長いタイトルの提出物ページのタイトル部分のデザインが崩れている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4807]
![スクリーンショット 2022-05-12 8 30 42](https://user-images.githubusercontent.com/16577/167964218-7d67aa6b-07f8-42f9-be80-20d886e58aa0.png)

こちらのURLです：
https://bootcamp.fjord.jp/products/12377

**Comment by machida** [comment]
対応したのでクローズします
