### ISSUE TITLE
ブログ記事でアイキャッチ画像がある場合は、OGP画像をそっちの画像に指定したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4838]

**Comment by masanarih0ri** [comment]
@machida 
お疲れ様です！
こちら、細かい仕様の確認です。 サムネイルがない場合

https://bootcamp.fjord.jp/ogp/ogp.png の画像が出る

という形で問題ないですか？（何の画像であれ工数は変わらないと思うので、ご指定いただければと思います🙇‍♂️）

**Comment by machida** [comment]
@masanarih0ri ありがとうございます！今回はその画像でお願いします。確かに、ブログの場合はブログ用のデフォルト画像があるといいですね。それは別Issueでやろうと思いますー。

**Comment by masanarih0ri** [comment]
@machida 
ありがとうございます！そうですね、ちゃんとした画像はすでにあるので急がなくてもいいとは思いますが、ブログ用の画像もあるとより良くなりそうだと思いました👍

今回は上記のURLで進めさせていただきます！！

**Comment by masanarih0ri** [comment]
確認済みですのでcloseします！
