### ISSUE TITLE
ブログ記事にサマリーを登録できるようにし、サマリーがある場合は meta discriptionをそっちに設定したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4839]
<img width="436" alt="貼り付けた画像_2022_05_25_22_52" src="https://user-images.githubusercontent.com/168265/170278924-f7cfe975-998e-450c-b47b-c5a53b9b8a7f.png">

こういう文章が入力できるようにしたいです。

メンターでログインし、ブログ作成ページ http://localhost:3000/articles/new に行ったとき、それの入力欄を設置する。

**Comment by NorifumiOgawa** [comment]
@machida さん、こちらのIssueについて、いくつか仕様の確認をさせてください。

1. サマリーの入力欄の配置は、タイトルと本文の間で良いでしょうか？
2. サマリーの入力欄にプレビュー表示は必要でしょうか？
3. サマリーの入力欄のデザイン（大きさなど）はマチダさんにお願いする感じでしょうか？
4. ブログ表示（`/articles/{id}`）の際も、サマリーを表示しますか？

よろしくお願いします！

**Comment by machida** [comment]
@NorifumiOgawa 
質問ありがとうございます！

1. 一旦、本文の下に置いてみたいと思います。
1. プレビューは無しでお願いします。
1. デザインは僕の方でやるので、レビューと同時進行でメンションをいただけたらデザインしますー
1. ブログの個別ページではmetaだけでbodyの中では表示無しでお願いします。

**Comment by NorifumiOgawa** [comment]
本番環境での確認が終わったのでクローズします！
