### ISSUE TITLE
お知らせ通知機能（全員に）

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#484]

**Comment by nishide-h** [comment]
@komagata 
@machida 
お知らせ通知機能に関して仕様を確認させてください。

## 1. 通知先について
全員に通知とのことですが、リタイアの方は省くと思いますが卒業生が微妙なところ。
卒業後もログインできるとの話がありましたが、卒業後の通知が大量に溜まってるのは嫌ですよね。
お知らせに公開期間は無いですよね？あれば通知あっても無視できそうですが。

ユーザーテーブルを見て関係ありそうなものを抜き出しました。
- graduation: 卒業生もログインするならあっても良いかな
- adviser: 通知あり？
- retire: 通知不要
- nda: これはない状態でもログインできるなら通知不要にすべき？
- mentor: 通知あり？

## 2.権限といいますか、役割について
Bootcampのアドバイザーやメンターについてよく理解しておりません。
ご教授お願いします。

**Comment by nishide-h** [comment]
@komagata 
回答ありがとうございます。
ログイン可能な方全員に通知行くように対応致します。

**Comment by nishide-h** [comment]
@komagata 
ごめんなさい。Push先を間違えて#485 のプルリクにPushしてしまいました。
git revertで元に戻して宜しいでしょうか？

**Comment by machida** [comment]
@nishide

大丈夫です！

1. これから消すコミット達のコミットIDをどこかにメモ
1. git rese — hard して戻して 
1. このリモートブランチに git push --force-with-lease 
1. 本来コミットするべきだったブランチに消したコミットを cherry-pick

ですかねー

**Comment by komagata** [comment]
@nishide-h 大丈夫ですー。

revertより単に戻す方がいいかも？

**Comment by nishide-h** [comment]
@machida 
@komagata 
ありがとうございます。ご迷惑おかけしました。
ローカルで間違って上げたコミットをgit resetで削除して--force-with-lease付きでPush。
GitHubから間違いコミットが消えてることを確認後、ローカルで再度git resetで消したコミットを戻して
プルリクブランチにPush致しました。

**Comment by shibaaaa** [comment]
こちら対応済みのようなのでクローズしておきます〜
