### ISSUE TITLE
【メンター向け】卒業と退会の通知の区別を付きやすくしたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4840]
卒業したり退会したりすると通知が届くが、文言がほぼ同じ、かつ、卒業よりも退会の方が頻度が多いので、卒業通知を「えっ、○○さん退会しちゃったの！？」と一瞬勘違いしてしまうときがある。

![save](https://user-images.githubusercontent.com/1148320/168706964-454e2254-bf42-4348-9353-fb35dfd92db4.png)

一見して卒業と退会を区別できるような文言になると嬉しいです。

例 「㊗️ jnchitoさんが卒業しました！」

**Comment by isshi-hasegawa** [comment]
@machida 

お疲れさまです。
通知の文言に手を加えましたが、ローカル環境では㊗️の絵文字が以下のように「マルに祝の字」で表示されます。
こちらはmachidaさんの意図どおりでしょうか？
もし文言に変更があればお知らせください🙏

なお、自分の動作環境はmacOS 12.3.1です。

<img width="1224" alt="_development__通知___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/53898556/172177921-900492e1-5540-42cd-9b57-7c072b736f77.png">

**Comment by machida** [comment]
@isshi-hasegawa あー、そうか！別の絵文字にしましょう。代わりに 🎉 これでお願いします！

絵文字は、その近辺の文字色と違う色のものが現れる、文字より色が塗られた面積が大きいものが現れる、の二点から目に付きやすいので、絵文字を使いたいと思ってますー。

**Comment by isshi-hasegawa** [comment]
@machida 
卒業通知にも 🎉 を使用する旨承知しました😄

> その近辺の文字色と違う色のものが現れる、文字より色が塗られた面積が大きいものが現れる、の二点から目に付きやすい

絵文字をこういうふうに捉えたことがなかったので勉強になります😳

**Comment by isshi-hasegawa** [comment]
✅動作確認
絵文字が文頭に追加されているか確認

- [ ] 卒業通知
- [ ] 退会通知
- [ ] 初日報通知

**Comment by komagata** [comment]
@isshi-hasegawa 本番環境で確認しました。

**Comment by isshi-hasegawa** [comment]
@komagata 
ご確認ありがとうございます！
本番環境で確認頂きましたのでCloseします。
