### ISSUE TITLE
【メンター向け】「snsでの反応」チャンネルの投稿が止まっている

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4849]
Discordの「snsでの反応」チャンネルの投稿が止まっているようです。
簡単に再開できそうなら再開を希望します。

**Comment by komagata** [comment]
スタート時からほとんど拾えてないのでいらないかな〜と思っておりました。

**Comment by JunichiIto** [comment]
ないとめちゃくちゃ困る、ってことはないけど、たまに「おっ」って思う投稿があったりしたので、あった方がいいかな〜と。

**Comment by komagata** [comment]
強力な理由がなければ手間なのでできれば無くせればな〜と思っておりました。

**Comment by machida** [comment]
📝 
既存のbotが動いてなかったので、自作する必要がありそう。

**Comment by JunichiIto** [comment]
自作が高コストならcloseでもいいかも。
