### ISSUE TITLE
提出物を更新すると、提出日も更新されてしまう。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4852]
現在は提出物の内容を更新すると、提出物日も更新されてしまう。

そうではなく、提出物をWIPにし、その後公開したら提出日が更新されるように変更したい。

**Comment by rosh-1228** [comment]
@machida 
仕様について確認させてください。

- 質問
提出物が持つ日付のパラメーターは、`createded_at` `updated_at` `published_at`の3つあります。
提出日に`published_at`を使用すると`updated_at < published_at`ということが発生します。
提出物の提出日に使用するパラメーターは、`提出日=created_at`という認識でよいでしょうか？

- 現状
現在は、提出日は`published_at`もしくは`created_at`を使うという記述になっております。
```slim
- if @product.wip?
  .a-meta__value
    | 提出物作成中
- elsif @product.published_at.present?
  span.a-meta__label
    | 提出日
  time.a-meta__value(datetime="#{@product.published_at.to_datetime}")
    = l @product.published_at
- else
  span.a-meta__label
   | 提出日
  time.a-meta__value(datetime="#{@product.created_at.to_datetime}")
    = l @product.created_at
```

しかし、更新日は`updated_at`を使っており、提出日に`published_at`を使うと、`updated_at < published_at`という現象が発生してしまいます。
```slim
- if @product.updated_at.present?
  .page-content-header-metas__meta
    .a-meta
      span.a-meta__label
        | 更新
     time.a-meta__value(datetime="#{@product.updated_at.to_datetime}")
       = l @product.updated_at
```
- 提出物を公開(提出)後の`@product`の内容(パラメーター)
```
$ @product
=> #<Product:0x000000011805e1c8
 id: 1071056619,
 practice_id: 198065840,
 user_id: 138009375,
 body: "test",
 created_at: Fri, 10 Jun 2022 15:08:34.423373000 JST +09:00,

 updated_at: Fri, 10 Jun 2022 15:12:23.371461000 JST +09:00,

 wip: false,

 published_at: Fri, 10 Jun 2022 15:12:17.555130000 JST +09:00,

 checker_id: nil,
 self_last_commented_at: nil,
 mentor_last_commented_at: nil,
 commented_at: nil>
```

そのため、提出日は`提出日=created_at`のみを使用するように変更したほうが良いのか？と疑問に思いましたので、使用確認の質問をさせていただきました。

**Comment by machida** [comment]
提出日は常に published_at を使うようにお願いします。updated_at はその名の通り更新日時を表し、それ以外では使用しないように変更をお願いします。

updated_at が published_at より新しい日時になっても問題はないです。

published_at を持つ提出物、要するに提出済みの提出物を WIP 状態に変更した場合、持っていた published_at を削除するようにしてください。

WIP のものを再度提出にした際に、新しい published_at を持つようにお願いします。

**Comment by rosh-1228** [comment]
ありがとうございます！
上記について承知しました！

**Comment by rosh-1228** [comment]
こちら本番環境にて確認できましたので、Closeします。
