### ISSUE TITLE
未完了の提出物一覧を担当メンターで絞り込みたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4853]
<img width="1711" alt="貼り付けた画像_2022_05_18_22_36" src="https://user-images.githubusercontent.com/168265/169052237-9071e4f4-e60d-42d5-b5f4-7a9b4d318950.png">

**Comment by Saki-htr** [comment]
### 6/6(月) 質問タイム:仕様について再度確認
未完了タブの「未返信」の欄にも作成することになった。

**Comment by Saki-htr** [comment]
@machida さん
お疲れ様です。仕様について1点お聞きしたいことがございます。お手隙の際にご回答いただけましたら幸いです🙏
よろしくお願いいたします。

### Q.プルダウンリストのメンターの並び順は、何を基準にソートするか
プルダウンリストに表示するメンターは、何を基準にソートすればよろしいでしょうか。
以下の画像のように、アルファベット順(昇順)でソートするのが一番自然かなと思いましたが、いかがでしょうか？?

![スクリーンショット 2022-06-09 0 44 55](https://user-images.githubusercontent.com/58052292/172661576-c2f52cdf-e1a7-4887-94a2-2126c014ec66.png)

**Comment by Saki-htr** [comment]
@machida さん
> アルファベット順でお願いしたいです。

かしこまりました!早速ご回答くださり、ありがとうございます🙏✨

**Comment by Saki-htr** [comment]
@machida さん

お疲れさまです。仕様について1点質問したいことがございますので、お手すきの際にご回答いただけますと幸いです🙏

## Q. 未返信タブで担当メンターを絞り込んだ時、「誰が」返信していない提出物を表示するか

元々、未返信タブには**ログインユーザーが**未返信の提出物が表示されていました。
未返信タブで担当メンターを絞り込んだ時、担当メンターとログインユーザーのどちらが未返信の提出物を表示したらよいでしょうか。

絞り込んでない時はログインユーザーが未返信の提出物が表示されるのに、メンターを選択した時に担当メンターが未返信のものが表示されると、「誰が」未返信のものが表示されているのか分かりづらくなるため、ログインユーザーが未返信のものを表示した方が良いかと思いましたが、いかがでしょうか??

### 1. 担当メンターが未返信の場合

![スクリーンショット 2022-06-14 11 32 13](https://user-images.githubusercontent.com/58052292/173482404-559f87c6-0478-4523-a468-22ac75c42fcc.png)



### 2. ログインユーザーが未返信の場合
![スクリーンショット 2022-06-14 11 39 21](https://user-images.githubusercontent.com/58052292/173482415-a76694b5-5ce0-4e6e-a9c4-4c02b115ebf1.png)

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/issues/5028
こちらの Issue を作成しましたー。

- まだ誰も提出物にコメントをしていないもの
- 最後のコメントが提出者であるもの

でかつ、

- 絞り込んだメンターが担当になっているもの

を表示するようにお願いします🙏

**Comment by Saki-htr** [comment]
@machida さん

早速issueを作成してくださり、ありがとうございます!
かしこまりました🙏

**Comment by Saki-htr** [comment]
本番環境での動作確認を完了しましたので、issueをcloseいたします〜
