### ISSUE TITLE
メンターのプロフィール欄が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4855]
トップページにあるメンターのプロフィールを入力する欄をメンターの登録上方修正画面から入力したい。

最終的にやりたいこととしては、ブログのエントリーのページにそのエントリーを書いた人のプロフィールを載せたい。（これは別Issueで大丈夫です。）

このIssueでは、トップページに出しているプロフィールの部分をDBから出すようにしたい。

**Comment by daiki0381** [comment]
@machida 
お疲れ様です。仕様に関してご相談させてください🙏

> トップページにあるメンターのプロフィールを入力する欄をメンターの登録上方修正画面から入力したい。

こちらは下記の仕様で問題ないでしょうか。

ユーザー登録情報変更画面にメンターのみプロフィール欄を追加 (自己紹介の入力欄とは別) → 入力された情報をDBに格納する → トップページの「メンター・顧問」のプロフィール文をDBから取り出して表示する。

▼トップページの「メンター・顧問」

<img width="1450" alt="スクリーンショット 2022-07-27 18 27 51" src="https://user-images.githubusercontent.com/98577773/181214278-64b3bbca-cb82-4e35-9a6a-9e447526fbe5.png">

▼ユーザー登録情報変更

<img width="1914" alt="スクリーンショット 2022-07-27 18 27 32" src="https://user-images.githubusercontent.com/98577773/181214234-01afc2df-67ab-419c-acf3-9c1a01507290.png">

**Comment by machida** [comment]
@daiki0381

はい！その通りですー
文章については、Markdownでお願いします。
関連書籍の登録については別Issueで考えたいと思います。

**Comment by daiki0381** [comment]
@machida 
お疲れ様です。もう4点仕様に関してご相談させてください🙏

> 関連書籍の登録については別Issueで考えたいと思います。

①こちらの**関連書籍**というのは下記の画像の赤枠の認識で相違ないか。

<img width="429" alt="スクリーンショット 2022-07-28 20 34 48" src="https://user-images.githubusercontent.com/98577773/181495810-684397af-e791-4430-9e95-2a477f337b05.png">

②DBに登録する情報はどれか。(自分の認識としては、上記の関連書籍以外でした。)

③今回の仕様は下記の認識で相違ないか。

登録情報変更画面にメンターのみプロフィール用の入力スペースを表示する (入力できる項目は、プロフィール画像、仕事、プロフィール名、プロフィール文、githubのid、blogのurl、twitterのid、facebookのid。プロフィール画像、仕事、プロフィール名、プロフィール文は入力必須。) → 入力したデータをusersテーブルに格納する → usersテーブルのmentor: trueのアカウントをeachで回してトップページの「メンター・顧問」の箇所にカード表示する。

④関連書籍に関しては、今回のissueでは表示しないという認識で問題ないか。

**Comment by machida** [comment]
@daiki0381

> ①こちらの関連書籍というのは下記の画像の赤枠の認識で相違ないか。

相違ないです。


> ②DBに登録する情報はどれか。(自分の認識としては、上記の関連書籍以外でした。)

上記の関連書籍以外です。

<img width="237" alt="image" src="https://user-images.githubusercontent.com/168265/181800187-056bc77b-6b3c-4cdd-ba0a-9824b3f0f35b.png">

この部分を Markdown で public_profile みたいな名前でお願いします。
メンターだけ、ユーザー情報変更のフォームに表示させるようにしてください。

> ③今回の仕様は下記の認識で相違ないか。

- 登録情報変更画面にメンターのみプロフィール用の入力スペースを表示する
- それ以外の入力できる項目は他のユーザーと同じ
- 入力したデータをusersテーブルに格納する → usersテーブルのmentor: trueのアカウントをeachで回してトップページの「メンター・顧問」の箇所にカード表示する。

④関連書籍に関しては、今回のissueでは表示しないという認識で問題ないか。

- 問題ないです。
- [#5287](https://github.com/fjordllc/bootcamp/issues/5287) 別Issueを作りました。

---

この Issue には machida もレビュワーとして登録をお願いします。
