### ISSUE TITLE
コース作成・編集ページでチェックボックスがチェックできない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4880]
チェックボックス（やラベル）をクリックしてもチェックされないのでコース作成ができない状態。

https://bootcamp.fjord.jp/admin/courses/25/edit

<img width="1474" alt="スクリーンショット 2022-05-24 23 50 22" src="https://user-images.githubusercontent.com/16577/170065822-c4f600eb-09e3-4fc8-bc5e-a183cb471f0e.png">

**Comment by machida** [comment]
こちら修正を確認したのでクローズしますー
