### ISSUE TITLE
メンター向けDiscord通知が二重で届いてしまう

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4893]
<img width="599" alt="貼り付けた画像_2022_05_25_15_21" src="https://user-images.githubusercontent.com/168265/170194106-eea85cfa-459e-4cd1-ab95-912b819c5fe1.png">

原因調査と修正をお願いします。

**Comment by machida** [comment]
📝 
> 未確認日報数を投稿するつもりで、間違って未確認提出物数を投稿

の可能性があるので、一旦 @komagata さんをアサインしました。

**Comment by komagata** [comment]
Done.
