### ISSUE TITLE
[Markdown] ユーザーアイコンメンションがログインしていなくても表示できるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4895]
管理者でログインして、ブログ記事を新規作成する。

```
:@machida:
```

これをブログ記事に入れる。
ブログ記事を公開する。
その記事にアクセスするとアイコン画像が表示されている。

ログアウトしたあと、そのブログ記事にアクセスすると、ユーザーアイコンが表示されない。

これを、ログアウトした状態でもユーザーアイコンが表示されるようにする。

**Comment by rosh-1228** [comment]
こちら本番環境にて確認いただいて問題ありませんでしたので、closeします
