### ISSUE TITLE
Q&A作成時、プラクティスの指定を空にして保存すると表示や編集ができなくなる

### ISSUE THREAD

**Issue by NorifumiOgawa** [fjordllc/bootcamp#4896]
## 概要

「質問する」画面でプラクティスの項目を空にして保存（WIPもしくは登録する）すると、その質問の表示や編集ができなくなる。

## 再現手順

1. 「質問する」画面`/questions/new` にアクセス。
2. プラクティス項目の右にある「x」をクリックして、選択されているプラクティスを空にする。
3. 「タイトル」と「質問文」を入力して「登録する」ボタンを押す。

## 期待される振る舞い

質問が登録された後、質問のページに遷移し、タイトルや質問文が表示される。

## スクリーンショット

「質問する」画面でプラクティスを空にして、質問を登録する。
![image](https://user-images.githubusercontent.com/770527/170288337-06805d88-ba93-429e-9d9f-d34a9e05a23e.png)

保存された質問のタイトルや内容が表示されない。
![image](https://user-images.githubusercontent.com/770527/170288619-1b85fd45-3894-498f-9e36-66a9358f8471.png)

## 環境

 - OS: macOS 11.5.2
 - ブラウザ: Google Chrome
 - バージョン: 101.0.4951.64

**Comment by taka110-IT** [comment]
本番環境での動作確認ができましたので、IssueをCloseします。
