### ISSUE TITLE
[定期イベント] 定期イベントにWatchの機能が欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4912]
Watch機能を付け、コメントがあったらWatchしている人に通知が飛ぶことで、コメントから参加者に連絡ができるようにしたい。

関連: https://github.com/fjordllc/bootcamp/issues/4913

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/pull/4862
こちらのブランチから新たにブランチを作って作業をお願いします。
上記ブランチがmainにマージされたら、mainブランチからrebaseをお願いします。

https://github.com/fjordllc/bootcamp/issues/4913
こちらと関連しているIssueなので、同じブランチで作業してしまって大丈夫です。

**Comment by siso25** [comment]
本番環境で動作確認ができましたので、こちらのissueはクローズさせていただきます。
