### ISSUE TITLE
[定期イベント] 定期イベントに参加の機能が欲しい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4913]
参加をしたら、自動でWatchになるようにしたい。参加人数制限は無し。

関連: https://github.com/fjordllc/bootcamp/issues/4912
同時に一人が実装したほうがいいかも。

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/pull/4862
こちらのブランチから新たにブランチを作って作業をお願いします。
上記ブランチがmainにマージされたら、mainブランチからrebaseをお願いします。

https://github.com/fjordllc/bootcamp/issues/4912
こちらと関連しているIssueなので、同じブランチで作業してしまって大丈夫です。

**Comment by siso25** [comment]
本番環境で動作確認ができましたので、クローズさせていただきます。
