### ISSUE TITLE
[定期イベント]定期イベント一覧にタブを付けたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4914]
<img width="1816" alt="貼り付けた画像_2022_05_30_15_41" src="https://user-images.githubusercontent.com/168265/170932288-68e123e9-5ade-4ce9-bdcc-14b9cf53432b.png">

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/pull/4862
こちらのブランチから新たにブランチを作って作業をお願いします。
上記ブランチがmainにマージされたら、mainブランチからrebaseをお願いします。

**Comment by siso25** [comment]
本番環境で動作確認ができましたので、こちらのissueをクローズさせていただきます。
