### ISSUE TITLE
[定期イベント]開催日を毎月第XのX曜日と指定できるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4915]
現在、開催日は自由テキスト、それを変更。

こんなUIにして、

<img width="740" alt="貼り付けた画像_2022_05_30_16_03" src="https://user-images.githubusercontent.com/168265/170936247-2492505b-7675-4e02-bc1a-fc1ddc8d3082.png">

- 毎週月曜
- 第1月曜
- 第1月曜と第3月曜

などと指定ができるようにしたい。

---

なぜそうしたいか？

- イベントが開催される前日に Discord に通知したい
- イベント参加者のダッシュボードに今日は開催日であることを表示したい

これらを実装するため。

---

上記を実装するには、今日（明日）は第1月曜であるか？true or false を返す仕組みが必要になる。
この仕組は Gem として切り出すのもありかも。

**Comment by masanarih0ri** [comment]
gemを作ったことはないけど、gemとして切り出す方向性も調査、検討が必要そう。

**Comment by masanarih0ri** [comment]
@machida 
お疲れ様です！
こちらは `第1月曜と第3月曜` のように複数の情報を表示するには、regular_eventが「第1月曜」「第3月曜」のような情報を複数持つ必要があると感じました。

現状のDBの構成では難しいのではないかと思いますが、設計はメンターの方と一緒にやって変更していくような感じで進めていいでしょうか？
↑はDB設計などはあまり得意ではなく、1人で進めようとして詰まってしまうのを避けたいという意図もあります。

それと、このissueは 
* 「第1月曜」「第3月曜」のようなデータを登録&表示できるようにする
* 今日（明日）は第1月曜であるか？をtrue or false を返す仕組みが何かしらある

上記の2つを実装して完了となるという認識でしょうか？

**Comment by machida** [comment]
@masanarih0ri 

質問ありがとうございます！

> 現状のDBの構成では難しいのではないかと思いますが、設計はメンターの方と一緒にやって変更していくような感じで進めていいでしょうか？

はい！ここは仕様に合わせて変更をお願いしますー🙏

> 上記の2つを実装して完了となるという認識でしょうか？

その2つに追加して、次回のイベント開催日は XX月XX日である、という表示もできるようにしておいていただきたいです🙏

**Comment by masanarih0ri** [comment]
@machida 

お疲れ様です！添付のような形で定期イベントの実装が少しずつ進んできました。（`feature/add-regular-event-repeat-rule` のブランチで動作確認もできます）

これから実装の細かいところを進めていくにあたり、いくつか質問をさせていただきたいです。

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/20497053/174434296-04e5ea1e-6ca1-4dd8-978c-85ca3cd51ade.png">

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/20497053/174434283-bd0e1347-41ec-4773-8694-b260566a7753.png">

### ①セレクトボックスの見た目

- 「毎週」や「月曜日」などを選択するセレクトボックスは、現時点で日報のコードを流用して実装していますが、最終的にCSSの調整が必要かと思います。その部分はロジックやテストの実装が全て終わった後に対応していただくという認識なのですが、それで問題ないでしょうか？

### ②セレクトボックスの初期状態

- セレクトボックスは現時点で添付のように、新しいイベントを作成するページに遷移した際には「毎週」「日曜日」という文字列が表示されるようになっています。こちらは空欄にしておいた方がいいでしょうか？
<img width="315" alt="image" src="https://user-images.githubusercontent.com/20497053/174434384-970751e8-8dd8-4873-93a3-f4e5d67db6fa.png">


### ③セレクトボックスにおけるバリデーション

- 現時点での仕様は、複数のイベント周期を登録した時に、同じものを登録することができる状態になっています。（例：「毎週日曜日」を登録した後に「毎週日曜日」を登録できる）こちらはそのままでも大きな問題はなさそうですが、バリデーションはXXのようにして欲しいなどありますでしょうか？

### ④コピーした際の挙動

- コピーする機能を仕様した際に、登録した定期イベントの周期までコピーする必要がありますでしょうか？ちなみに、今回の実装と似た仕様である日報の学習時間の情報は、コピーを行なった際には元の日報のデータをコピーしないようになっています。これに合わせて、定期イベントの周期はコピーされないという仕様にしておきたいのですが良いでしょうか？もしやるとしても、テスト含めて工数が膨らみそうなので、別issueで他の方に対応していただきたいと思っています。

**Comment by machida** [comment]
@masanarih0ri 
返信遅れてすいません🙇‍♂️

> ①セレクトボックスの見た目

はい、その認識で大丈夫ですー

> ②セレクトボックスの初期状態

「毎週」「日曜日」で問題ないですー

> ③セレクトボックスにおけるバリデーション

特に現時点でのバリデーションのリクエストは無いです。運用して気づいたら別Issueであげたいと思います。

> ④コピーした際の挙動

こちら了解です。ファーストリリースでは周期は含まずのコピーで問題ないです。
もし、その後、周期を含んでほしいというリクエストが来たら、別Issueで対応したいと思います。

**Comment by masanarih0ri** [comment]
@machida 
ご確認ありがとうございます！

①については、また別途お伝えしますが、テストの関係で消して欲しくないクラスがあるので、PRのレビューが通ったあたりでお伝えしますね！

今週水曜にはある程度デモができると思いますので、引き続き、よろしくお願いいたします！

**Comment by machida** [comment]
@masanarih0ri 了解ですー！よろしくおねがいしますー

**Comment by masanarih0ri** [comment]
@machida 
またまた細かい点なのですが、定期イベントの次回の開催日は、毎週日曜日の周期のイベントだとしたら
* 7/2（土）の時点では 07月03日と表示される
* 7/3（日）の時点では 07月10日と表示される
という仕様で問題ないでしょうか？

7/3（日）の時点では、（まだイベントの時間になっていなくても）確かに次回開催日は7/10（日）であるはずなので、正しいと思っているのですが、念のため確認したいです。

**Comment by machida** [comment]
@masanarih0ri もし可能でしたら、イベントの時間になるまでは、「本日開催」という表示にしたいです（デザイン的にも本日開催のときは赤い字で目立たせたいです）ー。

**Comment by masanarih0ri** [comment]
@machida 
なるほど！ちょっとまだ試してないのでなんとも言えないのですが、おそらくそこまで複雑にはならないかと思います。

イベントが今日の21時からの場合
* 昨日の23:59までは 次回開催日 07月05日と表示
* 7/5の 0:00〜20:59までは 本日開催 と表示
* 7/5の 21:00 以降は次回開催日を表示

という仕様にしたいということで間違いないでしょうか？

**Comment by machida** [comment]
@masanarih0ri 仕様をまとめていただきありだと思います！想像通りです。それでお願いしたいですー🙏

**Comment by machida** [comment]
@masanarih0ri ありがとうございます！よろしくお願いします🙏

**Comment by masanarih0ri** [comment]
@machida 
またまた細かい質問すみません！
終了している定期イベントの場合は、「次回の開催は~~~です」と出す必要がないので、「開催終了」という文字列を表示しようと思っています。それで問題ないですか？

**Comment by machida** [comment]
@masanarih0ri そうか、終了したイベントには次回がないですね。そのようにお願いします🙏

**Comment by masanarih0ri** [comment]
承知しました！ではそのように実装します！

**Comment by masanarih0ri** [comment]
@machida 
次回の開催日などの実装を色々していて思ったんですが、第5 N曜日の定期イベントって作る人いるんでしょうか？もし第5を条件から外して良いなら外したいと思っています。
理由としては、第5 N曜日は基本的に2ヶ月〜3ヶ月に1回になることが多く、周期もバラバラなので、設定できなくしても良いのではないかと思っているためです。少なくとも私がイベントの開催者だったら、毎週 or 第1~4の曜日で設定します。（理由は、毎週 or 毎月定期開催の方が参加者も主催者も把握しやすいし記憶しやすいから）

※例えばイベントを第5火曜日とすると、2022年の場合は、3/29,5/31,8/30,11/29となり、毎月開催でもなく、特に規則性がないので、定期イベントとして成立していないように思います。

また、第5を避けたいもう1つの理由としては、実装が非常に複雑になりそうで、現時点で解決策が出せていません。これ以上時間をかけても、ただ時間が過ぎていくだけな気がしているので、仕様の変更をお願いしたいと思っています。

**Comment by machida** [comment]
@masanarih0ri はい！無くして大丈夫ですー🙆

**Comment by masanarih0ri** [comment]
確認しました！
