### ISSUE TITLE
画像以外のファイルを添付された場合の表示がおかしい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#4919]
txtファイルなど、非画像ファイルを添付したときに表示が崩れます。

https://bootcamp.fjord.jp/questions/1305
<img width="872" alt="Screen Shot 2022-05-31 at 7 51 04" src="https://user-images.githubusercontent.com/1148320/171065840-16ef91c4-da3e-4139-b822-66710d3c9464.png">

マークダウンテキストはこんな感じ。

```
## 起きている問題（起きている現象の詳細/エラーコード/スクリーンショット）
![error.txt](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcm...2fb3c/error.txt)
```

画像でなければこんな感じでただのリンクにするといいかもしれません。

```
<a href="https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcm...2fb3c/error.txt">error.txt</a>
```

他のサービスだと非画像ファイルをドラッグアンドドロップされるとどういう挙動になるんですかね〜？ 🤔

**Comment by machida** [comment]
こちらテキストリンクで表示されるようにしたいと思います！
クリックするとダウンロードが始まるので、kb数も表示したいです。

```
<a href="https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcm...2fb3c/error.txt">error.txt(4kb)</a>
```

**Comment by keiz1213** [comment]
本番環境で動作確認できたのでcloseします。
