### ISSUE TITLE
[定期イベント] 定期イベントにカテゴリーを設定できるようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4924]
定期イベントに、

- 輪読会
- 雑談
- 質問
- MTG
- その他

のカテゴリーをラジオボタンで選択できるようにしたい。

<img width="709" alt="貼り付けた画像_2022_06_01_15_37" src="https://user-images.githubusercontent.com/168265/171342804-1934dc21-3a9f-466e-aec1-b762e62d2e05.png">

ここにカテゴリーアイコンが表示さるようにしたい。
machidaがデザインやります！

**Comment by machida** [comment]
定期イベントに、

- 輪読会
- 雑談
- 質問
- MTG
- その他

のカテゴリーをラジオボタンで選択できるようにしたい。

**Comment by ai-24** [comment]
本番環境で動作確認できましたのでクローズします！
