### ISSUE TITLE
管理者でログインしたときの相談部屋個別ページにタブを表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4931]
管理者でログインしている場合のみ、

このタブを

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/168265/171421357-0feedc76-6469-45fd-b9cc-a0c28a01c3b9.png">

ここに表示したい。

<img width="1936" alt="貼り付けた画像_2022_06_01_22_54" src="https://user-images.githubusercontent.com/168265/171421599-b3cd0776-7fc1-44a6-8d4e-7c3ff168f705.png">

**Comment by isshi-hasegawa** [comment]
@machida 
管理者向け機能の動作確認のお願いです。
`https://bootcamp.fjord.jp/talks/`から任意の相談部屋の個別ページアクセスし、

- タブの表示
- タブの動作

をご確認いただけますでしょうか🙏

**Comment by machida** [comment]
@isshi-hasegawa 確認遅れてすいません🙇‍♂️本番で確認しました🙆‍♂️

**Comment by isshi-hasegawa** [comment]
@machida 
いえいえ、とんでもないです🙏
本番環境での動作確認ありがとうございます！

このIssueはClose致します〜
