### ISSUE TITLE
通知の一覧画面が欲しい

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/bootcamp#494]
現状だと一度確認すると二度と確認できないので。

欲しい機能
- ヘッダーの新着通知一覧のボタンから通知一覧画面へのリンク
- 通知を一覧する機能
  - 既読と未読は分けて表示（URLはわけなくてもいい）
- チェックボックスで選択した通知を一気に既読にする機能

あるといいかもしれない機能
- 通知を紐づく日報や提出物ごとにグループ化して表示する機能

**Comment by gogutan** [comment]
#881 に同じIssue（Close済）があるため、こちらもCloseします。
