### ISSUE TITLE
参考書籍一覧ページの Vue.js化

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4949]
`/books` を Vue.js 化お願いしますー

**Comment by isshi-hasegawa** [comment]
Vue.js化と表紙画像が表示できないバグの修正について、本番環境での動作を確認しました。

**Comment by isshi-hasegawa** [comment]
@komagata 

`https://bootcamp.fjord.jp/books`にアクセスし、編集ボタンが表示されていることと、編集画面に遷移できることをご確認いただけませんでしょうか？

<img width="1336" alt="参考書籍___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/53898556/181878799-3e742ad5-d8b9-4206-a40b-f70c6c57d96a.png">

**Comment by komagata** [comment]
@isshi-hasegawa 編集ボタンが表示されていることを確認致しました。

**Comment by isshi-hasegawa** [comment]
@komagata 
ご確認ありがとうございます〜
本番環境での動作確認が完了したので、このIssueはCloseします！
