### ISSUE TITLE
footer に参考書籍へのリンクを置きたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4956]
<img width="1356" alt="貼り付けた画像_2022_06_08_15_35" src="https://user-images.githubusercontent.com/168265/172548357-95cb6a65-0829-4017-ad97-8173eba6afc9.png">

参考書籍 `/books` へのリンクを置く。

**Comment by SatoshiHaramura** [comment]
@machida 
今回のissueの要件について確認させて頂きたいです🙏

現状、下記のスクショのように、「参考書籍一覧」をクリックすると、`/books`へリンクするようになっているかと思います。

■スクショ
<img width="1419" alt="172548357-95cb6a65-0829-4017-ad97-8173eba6afc9_png__2712×224_" src="https://user-images.githubusercontent.com/11376040/172657214-55a6a8c0-ec9e-49a5-bbf3-7837963ec553.png">


■HTML
![_development__参考書籍一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/11376040/172656266-e74e81bf-2569-4092-80d3-4b54f3232479.png)

この場合の変更内容としては、「参考書籍一覧」の文言を「参考書籍」に変更して、リンクの位置を「ホームページ」と「GitHub Projects」の間に移動させればよいのでしょうか？

ご教授頂きたいです🙏

**Comment by machida** [comment]
おー、すでにありましたね！すいません🙇‍♂️

> この場合の変更内容としては、「参考書籍一覧」の文言を「参考書籍」に変更して、リンクの位置を「ホームページ」と「GitHub Projects」の間に移動させればよいのでしょうか？

この対応でお願いしますー

**Comment by SatoshiHaramura** [comment]
@machida 
承知致しました。

**Comment by SatoshiHaramura** [comment]
本番環境で動作確認が完了したため、close致します。
