### ISSUE TITLE
[参考書籍] 参考書籍一覧をプラクティスで絞り込みたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4958]
`/books` にアクセス。

<img width="1103" alt="貼り付けた画像_2022_09_26_6_48" src="https://user-images.githubusercontent.com/168265/192167060-aa16ddea-9da1-4a7b-bc34-cb58e58bbe9d.png">

`/questions` にあるプラクティスで絞り込みと同じ絞り込みを参考書籍一覧に置く。

**Comment by shirotamaki** [comment]
本番環境で動作確認できましたのでクローズいたします！
