### ISSUE TITLE
参考書籍一覧のそれぞれの書籍に紐付いているプラクティスを表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4959]

**Comment by SatoshiHaramura** [comment]
@machida 
お疲れ様です。
本件の仕様についてご教授頂きたいです🙏

issueのタイトルから、完成のイメージ図が分からなかったため、認識合わせさせて頂きたいです。
以下のように、参考書籍ページにおいて、書籍に紐づくプラクティス名を表示させるイメージをしたのですが、認識合っておりますでしょうか？

<img width="531" alt="Cursor_and_参考書籍一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/11376040/173231127-719d149f-e92f-4f05-b709-71bf8a0cfa4a.png">

**Comment by machida** [comment]
@SatoshiHaramura それで合ってますー👍 デザインは僕の方でやりますー

**Comment by SatoshiHaramura** [comment]
@machida 
承知しました！
追加の確認になりますが、プラクティス名はテキストで良いのでしょうか？
それとも、リンクにしたほうが良いでしょうか？(別のissueで対応する方針でしょうか？)

**Comment by machida** [comment]
@SatoshiHaramura プラクティス個別ページへのリンクでお願いしますー

**Comment by SatoshiHaramura** [comment]
@machida 
承知致しました！

**Comment by SatoshiHaramura** [comment]
@komagata 
お疲れ様です。
リリース後の動作確認において、[参考書籍](https://bootcamp.fjord.jp/books) ページで以下2点気になる点がありましたので、ご報告および確認させて頂きたいです。

1. 「リーダブルコード」には、プラクティス名が表示されていない状況となっております。この状況が期待通りの挙動なのか判断できず、それを調べるためには、本番DBを確認する必要があるかと思うのですが、komagataさんにてご対応いただけるのでしょうか？

2. 「イラスト図解式 ...」は、2つ表示されている状況となっております。これも、本番DBを確認する必要があるかと思うのですが、komagataさんにてご対応いただけるのでしょうか？

<img width="1562" alt="参考書籍___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/11376040/176626881-5db036c9-d11a-4ed6-b419-31a3289b9bae.png">

**Comment by SatoshiHaramura** [comment]
@machida 
お疲れ様です。
念の為の確認となりますが、1. と 2.の両方ともissue登録が必要ということでしょうか？

**Comment by machida** [comment]
@SatoshiHaramura
2 はバグとして登録しておいてくださいー（原因は未調査）。
1 は僕の方でプラクティスを登録しておいておきます。

**Comment by SatoshiHaramura** [comment]
@machida 
承知致しました。

**Comment by SatoshiHaramura** [comment]
本番環境での動作確認が完了しましたので、本Issueをclose致します。
