### ISSUE TITLE
検索結果のリストそれぞれに表示している本文のtrancateを削除し、cssで対応したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4962]
<img width="786" alt="貼り付けた画像_2022_06_08_13_46" src="https://user-images.githubusercontent.com/168265/172533765-e658fd65-9b6e-4da4-8122-0e65fee3976e.png">

この trancate（文字数制限）は CSS で行うので、ruby の処理を削除お願いします。
CSS側の処理はもう入っているので、ruby の処理の削除後、CSS で trancate がされているのを確認したらレビューを依頼し、マージでお願いします。

**Comment by tomonariha** [comment]
本番環境で字数制限できていることが確認できましたので、closeします。
