### ISSUE TITLE
質問一覧、プラクティスで絞り込むパーツの移動

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4964]
<img width="1637" alt="貼り付けた画像_2022_06_08_13_56" src="https://user-images.githubusercontent.com/168265/172534927-7134aa1d-4ef6-4cdf-b841-cded7870a02c.png">

こっちに移動し、プラクティスで絞り込んだときの遷移先に違和感がないようにしたい。

**Comment by yuki-snow1823** [comment]
状況確認できました。着手します。
