### ISSUE TITLE
`app/views/questions/_question.html.slim` 使われてないか調査

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4966]
`app/views/questions/_question.html.slim`
この partial が使われていないか調査し、使われていなかった削除する。
使われていたら、その部分を報告。

**Comment by SatoshiHaramura** [comment]
@machida 
以下質問させて頂きたいです。

> 使われていたら、その部分を報告

とありますが、報告方法はどのようにすればよいのでしょうか？

新規PRを作成して、そのPRに内容を記載して、レビュー(メンバー/リーダー)して頂くフローとなりますでしょうか？

**Comment by machida** [comment]
@SatoshiHaramura 

machida にメンションでお願いしますー
メンションを受けたら僕の方でIssueはクローズしますー

**Comment by SatoshiHaramura** [comment]
@machida 
承知致しました。

以下、調査結果を報告致します。

#### 結論
`app/views/questions/_question.html.slim`は、以下の1箇所で利用されておりました。

https://github.com/fjordllc/bootcamp/blob/90b0ca004223ce588d9f177a0a13527e6650eb52/app/views/practices/questions/index.html.slim#L21

#### 調査の方法
以下の2つ条件で検索を行いました。

検索条件その1
- 検索範囲：app/views配下すべて
- 検索文字列：`'questions/question'`
→　検索結果は、`app/views/questions/_question.html.slim`がヒットしました。

検索条件その2
- 検索範囲：app/views配下すべて
- 検索文字列：`'question'`
→　検索結果は、（renderメソッドを呼んでいる箇所に限り）何もヒットしなかった。

以上、ご確認宜しくお願い致します🙏

**Comment by machida** [comment]
@SatoshiHaramura 調査ありがとうございます！では、こちらはクローズしますー
