### ISSUE TITLE
ユーザー個別ページの回答一覧の回答それぞれのプラクティスをリンクにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4967]
<img width="743" alt="貼り付けた画像_2022_06_08_14_34" src="https://user-images.githubusercontent.com/168265/172539563-c4b5adc4-fd96-4696-ae45-4efc2ff7af02.png">

プラクティスへのリンクにする

**Comment by machida** [comment]
手持ちのIssueがなくなったらこちらをお願いしますー

**Comment by kazumi3858** [comment]
本番環境での動作確認が済みましたのでCloseいたします😄
