### ISSUE TITLE
ユーザー個別の日報一覧のtitle の修正

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4969]
{ユーザー名} 日報 | FJORD BOOT CAMP（フィヨルドブートキャンプ）

に変更。

<img width="600" alt="貼り付けた画像_2022_06_08_15_30" src="https://user-images.githubusercontent.com/168265/172547572-9280bc44-77e1-4ad2-9dcc-12f3ca680d59.png">

**Comment by SatoshiHaramura** [comment]
@machida 
本件の仕様(titleの文言)について確認させて頂きたいです🙏

上記のコメント(https://github.com/fjordllc/bootcamp/issues/4969#issue-1264260486) には、以下のように`日報`という文字が新たに追加されているかと思います。
`{ユーザー名} 日報 | FJORD BOOT CAMP（フィヨルドブートキャンプ）`

ただ、ユーザー個別の他の4つリソース(コメント、提出物、質問、回答)を確認してみたところ、以下のスクショのように`の〇〇一覧`という表記になっておりました。(コメント一覧のスクショは撮れていないですが..)

<img width="602" alt="_development__kimuraの提出物一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/11376040/172800452-91eee97b-70be-4fa9-b3e7-cfef128e79ae.png">

<img width="587" alt="_development__kimuraの質問一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/11376040/172800515-cb1e18f6-e9ff-401b-99d1-67ff809f0740.png">

<img width="589" alt="_development__kimuraの回答一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/11376040/172800582-e9e484b5-e36a-4220-a96e-fe2a019b99d2.png">


そのため、この`日報一覧`と`それ以外の一覧`において、titleの表記が異なることになりますが、よいということでしょうか？

もしくは、以下のように`の日報一覧`としたほうがよいのでしょうか？
`{ユーザー名}の日報一覧 | FJORD BOOT CAMP（フィヨルドブートキャンプ）`

ご教授お願い致します🙏

**Comment by machida** [comment]
> そのため、この日報一覧とそれ以外の一覧において、titleの表記が異なることになりますが、よいということでしょうか？

はい！大丈夫です。
他の部分の修正は good first issue として別 Issue で登録するので、今回は

`{ユーザー名} 日報 | FJORD BOOT CAMP（フィヨルドブートキャンプ）`

だけの対応でお願いしますー

**Comment by SatoshiHaramura** [comment]
@machida 
承知致しました。

**Comment by komagata** [comment]
@machida (CC: @SatoshiHaramura )

これって

`komagata の日報`　ではなく、 `komagata 日報`

で大丈夫ですかね？（いただいたPRをレビュー中なのですが気になったので）

**Comment by komagata** [comment]
:memo: そのままでOKとのこと

**Comment by SatoshiHaramura** [comment]
本番環境で動作確認が完了しましたので、close致します。
