### ISSUE TITLE
参考書籍一覧を参考書籍に title を変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#4971]
`/books` のタイトルを変更。

<img width="503" alt="貼り付けた画像_2022_06_08_15_37" src="https://user-images.githubusercontent.com/168265/172548593-5761e52a-5904-4525-b9cb-c678f524a879.png">

meta title は、`参考書籍 | FJORD BOOT CAMP（フィヨルドブートキャンプ）` にする。

<img width="493" alt="貼り付けた画像_2022_06_08_15_57" src="https://user-images.githubusercontent.com/168265/172552057-5c572001-09ff-4563-8857-31a5126ef5ec.png">

**Comment by kazumi3858** [comment]
本番環境での動作確認が済みましたのでCloseいたします😊
