### ISSUE TITLE
期一覧ページが遅い

### ISSUE THREAD

**Issue by shibaaaa** [fjordllc/bootcamp#5010]
## 概要

下記ページの描画が体感で他のページより遅いです。
https://bootcamp.fjord.jp/generations

## 原因？

コードを見たところ、下記で期数分usersテーブルへのクエリが発行されており、ボトルネックになってそうでした。
(issue起票時で38期あるので38回発行される)

https://github.com/fjordllc/bootcamp/blob/417db4906aba8d932057699629e6962e77cde9f6/app/views/generations/_generation.html.slim#L1

### Generation#usersの定義元

https://github.com/fjordllc/bootcamp/blob/417db4906aba8d932057699629e6962e77cde9f6/app/models/generation.rb#L36-L38

今後時間の経過とともに期が増え、少しずつこのページが遅くなっていきそうです💦

**Comment by Seakimhour** [comment]
本番環境で動作確認をできましたので、closeさせていただきます！
