### ISSUE TITLE
質問一覧をvue.js化し、`app/views/questions/_question.html.slim` を削除

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5020]
質問一覧をvue.js化し、`app/views/questions/_question.html.slim` を削除する。
`app/views/questions/_question.html.slim` が使われている箇所は、 https://github.com/fjordllc/bootcamp/issues/4966 こちらを参照。

**Comment by ai-24** [comment]
@machida さん
お疲れ様です。
こちらのIssueに関して調査したところ下記のVue化は完了しているようでした。
- Q&A > Q&A一覧

質問一覧をQ&A > Q&A一覧と認識しているのですが間違いないでしょうか。

また`app/views/questions/_question.html.slim`につきましては、下記PRで削除してくださっています🙏
[プラクティス個別 > Q&Aの一覧 を Vue\.js化した by tomonariha · Pull Request \#5255 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5255)

**Comment by machida** [comment]
@ai-24 おお、すいません🙇‍♂️確認して別のIssueをアサインします。報告ありがとうございます🙏

**Comment by ai-24** [comment]
@machida さん
よろしくお願いします🙇‍♀️

**Comment by machida** [comment]
@ai-24 別のIssueをアサインさせていただきました🙇‍♂️こちらはcloseします
