### ISSUE TITLE
「今日の気分」のアイコンを日報の一覧に表示する

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5063]
## 機能の説明

「今日の気分」のアイコンを日報の一覧に表示したい。イメージ的にはこんな感じ（あくまでイメージです。実際の「今日の気分」ではありません）。

<img width="756" alt="s" src="https://user-images.githubusercontent.com/1148320/175155514-8d81ca4d-dd24-4267-8fd5-30458e468127.png">

日報の詳細ページや提出物ページ（メンターモードの場合）の右側に出てくる「直近の日報」でも同じように「今日の気分」のアイコンを出したい。

<img width="486" alt="t" src="https://user-images.githubusercontent.com/1148320/175160262-a2a743d1-8473-4daf-b1ef-f2b5c9241517.png">

## 何故この機能が必要なのか

どちらかというと、後者の「直近の日報」にアイコンを出す方が重要。

日をまたがってその受講生の「今日の気分」を確認することで、最近どう？楽しくやれてる？という雰囲気がなんとなくわかりそうだから。
場合によってはメンターから何かフォローを入れられるかもしれません。

**Comment by yocajii** [comment]
本番環境で動作確認できましたので、クローズいたします。

**Comment by JunichiIto** [comment]
@yocajii  メンター向け機能なので確認できないかもしれませんが、提出物ページの直近の日報にはアイコンが表示されてないようです。
https://bootcamp.fjord.jp/products/13025

<img width="1434" alt="1" src="https://user-images.githubusercontent.com/1148320/185511417-9f0a7ed2-3b01-40b3-9917-cbcc419459b6.png">

**Comment by yocajii** [comment]
@JunichiIto 
ご連絡ありがとうございます🙏
確認して対応いたします。

**Comment by yocajii** [comment]
@JunichiIto 
先日、修正のPR #5391 が本番環境にリリースされました。
こちらのバグに気付いてくださったのが伊藤さんなので、もしよろしければ提出物ページの動作確認をお願いできますでしょうか🙏

**Comment by JunichiIto** [comment]
@yocajii 表示されてました。大丈夫そうです〜  🙆‍♂️ 

<img width="267" alt="Screen Shot 2022-09-09 at 15 30 36" src="https://user-images.githubusercontent.com/1148320/189286064-10d1fb30-4d69-4ddf-81d2-de6a79b10ccc.png">

closeしておきますね。対応ありがとうございました！

**Comment by yocajii** [comment]
@JunichiIto 
早速ご確認くださいましてありがとうございます🙏✨
