### ISSUE TITLE
セレクトボックス横のアイコンが正常に表示されていない

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/bootcamp#510]
[![Image from Gyazo](https://i.gyazo.com/d60c5e37d042ca8ed073a3b7a083c46c.png)](https://gyazo.com/d60c5e37d042ca8ed073a3b7a083c46c)

**Comment by sanfrecce-osaka** [comment]
@machida 
こちらGemの`oulu`が原因でしょうか？

**Comment by machida** [comment]
@sanfrecce-osaka oulu と CDNの両方に原因がありました。
