### ISSUE TITLE
未アサインの提出物のtitleを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5103]
メンターでログインし、
http://localhost:3000/products/unassigned
にアクセス。
このページの title タグが、現在は「提出物 | FJORD BOOT CAMP（フィヨルドブートキャンプ）」になっている。
これを「未アサインの提出物 | FJORD BOOT CAMP（フィヨルドブートキャンプ）」に変更。

**Comment by kei-kmj** [comment]
@machida
おつかれさまです。
仕様の確認をさせてください。

ページ上に表示されているタイトルは変えずにtitleタグだけ変更するのでしょうか？それとも、ページ上の表示も変更するのでしょうか？スクショのオレンジの囲いの部分です
![2022-07-01 (3)](https://user-images.githubusercontent.com/82737807/177161999-ff8e0c09-ef06-49a5-a18c-ff34a484fa47.png)

**Comment by machida** [comment]
@kei-kmj オレンジの部分はそのままでタイトルタグだけ変更お願いしますー

オレンジの部分はなぜそのままかというと、タブは

https://www.monotaro.com/p/7021/1076/?utm_id=g_pla&utm_medium=cpc&utm_source=google&utm_campaign=246-833-4061_6466659573_shopping&utm_content=96539050923&utm_term=_419857551521_x_pla-879055534935&gbraid=0AAAAADNqOHCavK-ObM6e9aKqvARMEuR_k&gclid=EAIaIQobChMIseK8kbTf-AIVI9dMAh2W8AQxEA0YAiABEgLgovD_BwE

これのメタファーなので、どれかタブを開いたとき、変化が起きるのはそのタブより下の部分だけでないと物理的におかしいからです。

**Comment by machida** [comment]
@kei-kmj 確認しました！！OKでしたー🙆‍♂️

**Comment by kei-kmj** [comment]
本番環境での動作確認が完了したため、close致します。
