### ISSUE TITLE
自分の担当の提出物のtitleを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5104]
メンターでログインし、
http://localhost:3000/products/self_assigned
にアクセス。
このページの title タグが、現在は「提出物 | FJORD BOOT CAMP（フィヨルドブートキャンプ）」になっている。
これを「自分の担当の提出物 | FJORD BOOT CAMP（フィヨルドブートキャンプ）」に変更。

**Comment by daiki0381** [comment]
@komagata @machida 
お疲れ様です。こちらメンターアカウントの修正なので本番環境のご確認をお願いしたいです🙏

【確認事項】
- 「提出物」の「自分の担当」のtitleが「自分の担当の提出物 | FJORD BOOT CAMP（フィヨルドブートキャンプ）」に変更されているか。

![image](https://user-images.githubusercontent.com/98577773/181781893-07c5e353-da14-4225-b659-df41b6281653.png)

**Comment by daiki0381** [comment]
こちら問題無かったので、Closeします。
