### ISSUE TITLE
全ての質問一覧のページ見出しと、titleタグの変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5108]
http://localhost:3000/questions
このページにアクセス

## ページ見出しとタブ

<img width="501" alt="貼り付けた画像_2022_06_29_14_54" src="https://user-images.githubusercontent.com/168265/176361977-63b0b716-901b-48ee-a50b-617e90051990.png">

## titleタグ

現在は「全ての質問 | FJORD BOOT CAMP（フィヨルドブートキャンプ）」になっている。
これを、「全てのQ&A | FJORD BOOT CAMP（フィヨルドブートキャンプ）」に変更。

**Comment by daiki0381** [comment]
本番確認しました。問題無かったので、Closeします。
