### ISSUE TITLE
ユーザー一覧 > 企業別 にフィルターがほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5109]
<img width="1159" alt="貼り付けた画像_2022_06_29_14_59" src="https://user-images.githubusercontent.com/168265/176362716-9322862b-1ae3-41f2-9574-77685aea964c.png">

この箇所に、

<img width="617" alt="image" src="https://user-images.githubusercontent.com/168265/176451391-0bc8b7ef-2aa3-41b6-919f-40508feba03e.png">

これを挿入して絞り込みができるようにしたい。

**Comment by machida** [comment]
@SatoshiHaramura こちらお願いします

**Comment by SatoshiHaramura** [comment]
@machida 
承知致しました！

念の為に確認させていただきたいのですが、「企業別」タブをクリックしたときに適用されるフィルターは、一番左端の「全員」フィルターでよいでしょうか??

↓は仮実装中です
<img width="714" alt="Cursor_and__development__企業別___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/11376040/177029485-7cd937c4-1956-4214-b560-8b80ea6686e4.png">

**Comment by machida** [comment]
@SatoshiHaramura はい！デフォルトは全員でお願いしますー

**Comment by SatoshiHaramura** [comment]
本番環境での動作確認が完了しましたので、close致します。
