### ISSUE TITLE
check-stamp.vueをreactに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5118]
下記を参考にしてreactに変える。

- [react導入 \+ 管理画面のコース一覧をreact化 by komagata · Pull Request \#5515 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5515)

**Comment by kyokucho1989** [comment]
@komagata 
おはようございます！
こちらのIssue進め方について２点確認したいことがあります。

 **categories.vue について**

　#5660  ですでにReact化されていました。そのため、今回は`check-stamp.vue`のみReact化しようと思います。  

**React化の方針**

　すでに`app/javascript/components/Reports.jsx` と `app/javascript/components/Report.jsx` の中にスタンプを実装している箇所がありました。 `useSWR` を用いてスタンプに関するデータ取得を行い、その内容を出力しています。

　そのコードを参考に実装を進めようと思います。重複する箇所が発生してしまいますが、共通化は必要であれば別Issueを立てて後日実施したいです。


以上です。確認のほどよろしくお願いします。

**Comment by komagata** [comment]
@kyokucho1989 

> https://github.com/fjordllc/bootcamp/pull/5660 ですでにReact化されていました。そのため、今回はcheck-stamp.vueのみReact化しようと思います。

おお、すみません、その通りで大丈夫です。Issueのタイトルからも抜いておきました〜。

> React化の方針

すみません、こちら( check-stamp.vue )、もしかしたら @dowdiness さんが今作業中かもしれないので、そちらを確認してみてください〜

**Comment by kyokucho1989** [comment]
@komagata 
了解です！　確認してみます。

**Comment by kyokucho1989** [comment]
@komagata 
さきほど確認しました。
`check-stamp.vue` についても、
#7216  このプルリクですでに実装しているとのことです。
こちらのIssueはクローズした方がよいでしょうか？

**Comment by dowdiness** [comment]
@komagata @kyokucho1989 

先程このIssueについて確認を受けました。

- https://github.com/fjordllc/bootcamp/issues/5122

今こちらの自分の担当しているCommentコンポーネントに関係するIssueがあるか確認しました。

- https://github.com/fjordllc/bootcamp/issues/5118
- https://github.com/fjordllc/bootcamp/issues/5119
- https://github.com/fjordllc/bootcamp/issues/5134

この上記の３つのIssueは、Commentコンポーネントの中で使われているか依存関係があるため、先にReactコンポーネントに変換しないとCommentコンポーネントのreact化が出来ません。

なので既にこちらの[PR](https://github.com/fjordllc/bootcamp/pull/7216
)や、手元にあるブランチの作業ではReactに書き換えてしまっています。

Issueにコメントしたり自分にアサインしたりして、他の人が作業しないように分かりやすくするべきでした。
二度手間になってしまいすいません!🙇

**Comment by kyokucho1989** [comment]
@komagata 
ありがとうございます！
