### ISSUE TITLE
comment.vue, comments.vueをreactを対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5122]
下記を参考にしてreactに変える。

- [react導入 \+ 管理画面のコース一覧をreact化 by komagata · Pull Request \#5515 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5515)

**Comment by dowdiness** [comment]
Commentコンポーネントが内部で使っているか、vuexを通して依存している部分があるため、既にこちらのIssueらは自分が作業を始めています。

- https://github.com/fjordllc/bootcamp/issues/5118
- https://github.com/fjordllc/bootcamp/issues/5119
- https://github.com/fjordllc/bootcamp/issues/5134

もしかしたら他の人も着手していて二度手間になっている可能性があります。
