### ISSUE TITLE
company-products.vue, company-users.vueを非vue化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5123]
vueを使わないようにするためにタイトルになっているファイルを使っている箇所を普通のHTMLでの実装に変える。

元々Reactに変更する予定でしたが、最終的にはHotwireにする予定なので、VueもReactも使わない実装にしたいです。（普通にviewに表示する方式）

**Comment by komagata** [comment]
@ham-cap こちらもうしわけありませんが、react化も不要になってきているので内容を変更させていただきました。

**Comment by ham-cap** [comment]
@komagata 
内容変更について承知いたしました👍
RailsのViewで実装するようにいたします。
