### ISSUE TITLE
courses-practice.vue, courses-practices.vueを削除したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5124]
vueを使わないようにするためにタイトルになっているファイルを使っている箇所を普通のHTMLでの実装に変える。

元々Reactに変更する予定でしたが、最終的にはHotwireにする予定なので、VueもReactも使わない実装にしたいです。（普通にviewに表示する方式）

**Comment by omochiumaiumai** [comment]
リリース及び本番環境の確認が完了しました。Issueをcloseします。
