### ISSUE TITLE
event.vue, events.vueをreactに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5125]
下記を参考にしてreactに変える。

- [react導入 \+ 管理画面のコース一覧をreact化 by komagata · Pull Request \#5515 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5515)

**Comment by dowdiness** [comment]
reactへ書き換えようとして気づいたのですが、event.vue, events.vueは他のvueのコンポーネントやライブラリを使って依存しているのでそのままの書き換えが出来ません。

今回のevent関連のコンポーネントが依存しているのはPagerとLoadingListPlaceholder、UserIconです。LoadingListPlaceholderとUserIconは簡単にreactで書き直せると思いますが、Pagerは外部の[ライブラリ](https://www.npmjs.com/package/vuejs-paginate)を使っているため置き換えが難しいです。

個人的には[vuera](https://github.com/akxcv/vuera)のようなreact内でvueを使えるようにするライブラリを使ってreactへの置き換えが進むまで共存しやすいようにするのが良いと思うのですがどうでしょうか？

**Comment by komagata** [comment]
@dowdiness Vueは使わなくなるので全部Reactに書き換えるようにお願いします。
コンポーネントの分け方はVueの時の設計を考慮しなくて良いです。

Pagerなどは管理画面の企業一覧でもReactで行なっているので参考にしてみてください。（Pagerのコンポーネントはこちらを使えると思います。）

管理画面の企業一覧
/admin/companies

**Comment by dowdiness** [comment]
@komagata
なるほどーvueで全部書き換える予定だったんですね。
Pagerのreactコンポーネントがあるのには気付かなかったですが、途中で気付いてcompaniesのコンポーネントを参考にこのコンポーネントを使って書くようにしました。

**Comment by dowdiness** [comment]
マージされたのでクローズします
