### ISSUE TITLE
generation-users.vueをreactに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5126]
下記を参考にしてreactに変える。

- [react導入 \+ 管理画面のコース一覧をreact化 by komagata · Pull Request \#5515 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5515)

**Comment by natsuto6** [comment]
@komagata @machida 
こちらのIssueについて質問させてください。
12/27（水）の開発MTGにて確認させていただきましたが、`generation-users.vue`をReact化するにあたり、関連するファイル全てをReact化しております。
その中に`pager.vue`が含まれており、このページネーションをReactで実現するために、[react-paginate](https://github.com/AdeleD/react-paginate)の使用はどうかと考えています。`pager.vue`のロジックを維持し、見た目も同じにするためには、`react-paginate`を使用するのが良いのではと考えました。スター獲得数、メンテナンスの頻度を見ても信頼できるかと判断しました。
このライブラリを使用する前に、ご意見を伺いたいと思いましたので何か他の推奨する方法や注意点がありましたら、教えていただけますと幸いです。

**Comment by komagata** [comment]
@natsuto6 実装してみて問題なければ使って大丈夫です〜

**Comment by natsuto6** [comment]
3/27（水）チーム開発MTG
結論、pagerのcomponentを使う
https://github.com/fjordllc/bootcamp/pull/7170#discussion_r1536711474

**Comment by natsuto6** [comment]
本番環境で動作確認完了しましたのでcloseします
