### ISSUE TITLE
learning-status.vue, learning.vueを削除できるようにする

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5127]
最終的にはhotwireにしたいので、VueもReactも使わない実装にする。

**Comment by Sasaco-JM** [comment]
@komagata
お疲れ様です。
こちらDiscordで対応依頼をいただいたのですが、assigneeを私に変更してもよろしいでしょうか。

**Comment by komagata** [comment]
@Sasaco-JM すみません、assigneeを変更するのを忘れておりました。今変更しました〜。
