### ISSUE TITLE
practice-user-icon.vueを削除したい。

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5132]
vueを使わないようにするためにタイトルになっているファイルを使っている箇所を普通のHTMLでの実装に変える。

元々Reactに変更する予定でしたが、最終的にはHotwireにする予定なので、VueもReactも使わない実装にしたいです。（普通にviewに表示する方式）

**Comment by nishitatsu-dev** [comment]
@komagata 
すみませんが、下記についてアドバイス下さい🙏
【状況】
- `practice-user-icon.vue`は、`courses-practice.vue`の子コンポーネント
- 親コンポーネントの`courses-practice.vue`に対するissueが動いている
  同名のissue2件が、2人に割り振られていますが、大丈夫でしょうか？
  #5124 
  #7391 

【アドバイスいただきたい事】
どう動けば良いか、全くイメージ出来ず、すみませんが、アドバイスお願いします🙇🏻
（親コンポーネントのissue完了を待てば良いのでしょうか？）

**Comment by komagata** [comment]
@nishitatsu-dev 大変申し訳ありません、こちら親コンポーネントのIssueの中で解決してしまうものだと思うので申し訳ありmせんがCloseとさせてください。

**Comment by nishitatsu-dev** [comment]
@komagata 
ご対応ありがとうございます🙏　承知しました〜
