### ISSUE TITLE
product.vue, products.vueをreactに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5133]
下記を参考にしてreactに変える。

- [react導入 \+ 管理画面のコース一覧をreact化 by komagata · Pull Request \#5515 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5515)

**Comment by lef237** [comment]
#6164 がリリースされました。Vuexの状態管理の影響でリプレース（置き換え）はおこなっておりません。
コンポーネントファイルを追加して対応したため、Close致します。
