### ISSUE TITLE
product_checker.vue, reaction.vueをreactに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5134]
下記を参考にしてreactに変える。

- [react導入 \+ 管理画面のコース一覧をreact化 by komagata · Pull Request \#5515 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5515)

**Comment by a-kuroki-gs** [comment]
@komagata
お疲れ様です。
https://github.com/fjordllc/bootcamp/issues/5118 と https://github.com/fjordllc/bootcamp/issues/5122 のコメントでの議論を拝見しました。
すでに本issueの内容も取り組まれているということであれば、こちらはCloseした方がよろしいでしょうか？
(まだほぼ実装できていないかったので、影響は特にないです。)

**Comment by komagata** [comment]
@a-kuroki-gs 大変申し訳ありません。こちらも同じくすでに別Issueで取り掛かっているものでした。
申し訳ないですがCloseしていただければありがたいです。
