### ISSUE TITLE
report.vue, reports.vueをVueMounterに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5138]
下記を参考にしてVueMounterを使ったマウント方法に変える。

- [Vue Componentのマウント方法 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/Vue-Component%E3%81%AE%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E6%96%B9%E6%B3%95)
- [announcementsをVueMounterに対応 by komagata · Pull Request #5113 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5113)

**Comment by kei-kmj** [comment]
@komagata @machida 

おつかれさまです。
質問が3つあります。お忙しいところ申し訳ありませんがご教示いただけますでしょうか。

1. 実装が正しく出来ていることの確認方法について
- 正しく実装されたかどうかは、マウント方法を変えた後も、reportsのカードコンポーネントが従来通り表示出来ているかどうかで判断すればいいのでしょうか？
- 他に確認すべきことはありますでしょうか？

2. `id`の型について
[すでにマージ済みのプルリク](https://github.com/fjordllc/bootcamp/pull/5113/files) で
![image](https://user-images.githubusercontent.com/82737807/181450349-2780caa5-bb1e-43cf-8d8d-d7539f33a478.png)
の修正が入っていますが、これはVueMounterだから修正する、というより、データの型をDBの型に合わせるため、という理解で合っていますでしょうか？

3.practice>日報一覧について
見方が間違っていたら申し訳ありませんんが、`app/views/practices/reports/index.html.slim`を見ると、ここはまだVue.js化されていないように見えます。これは別issueになりますでしょうか？

**Comment by komagata** [comment]
@kei-kmj 

> 正しく実装されたかどうかは、マウント方法を変えた後も、reportsのカードコンポーネントが従来通り表示出来ているかどうかで判断すればいいのでしょうか？

はい。

> 他に確認すべきことはありますでしょうか？

ないです。

> の修正が入っていますが、これはVueMounterだから修正する、というより、データの型をDBの型に合わせるため、という理解で合っていますでしょうか？

DBの型に合わせるためという感じではないです。

Vueのコンポーネント単体でのあるべき設計を考えた時に、idはNumberであるべきだからです。

> 3.practice>日報一覧について

別Issueになります。

**Comment by kei-kmj** [comment]
@komagata 
ご回答ありがとうございます🙏

**Comment by kei-kmj** [comment]
@komagata @machida
お忙しいところ申し訳ありませんが、以下の2つのurlで日報が表示されるか確認いただけますでしょうか。

3.7 reports/unchecked（メンター）
3.8 talks/:user_id のユーザーの日報タブ（管理者）


自分で動作確認済
3.1 reports
3.2 users/:user_id/reports
3.3 companies/:companies_id/reports
3.4 current_user/reports
3.5 reports/:id の直近の日報

**Comment by komagata** [comment]
@kei-kmj 

> 3.7 reports/unchecked（メンター）
> 3.8 talks/:user_id のユーザーの日報タブ（管理者）

こちらが表示されていることを確認しました〜！

**Comment by kei-kmj** [comment]
本番での動作確認ができたのでcloaseします
