### ISSUE TITLE
tag-edit-button.vue, tag-edit-modal.vueをreactに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5141]
下記を参考にしてreactに変える。

- [react導入 \+ 管理画面のコース一覧をreact化 by komagata · Pull Request \#5515 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5515)

**Comment by syo-tokeshi** [comment]
@komagata 
お疲れ様です。
こちらのissueなのですが、本番での動作確認がメンターじゃないと出来ないので、お願いをしてもよろしいでしょうか？
https://github.com/fjordllc/bootcamp/pull/6549

**Comment by komagata** [comment]
@syo-tokeshi 本番環境で動作することを確認しました。

**Comment by syo-tokeshi** [comment]
@komagata 
ご確認ありがとうございました🙇‍♂️
