### ISSUE TITLE
tags-input.vue, tags.vueをreactに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5142]
下記を参考にしてreactに変える。

- [react導入 \+ 管理画面のコース一覧をreact化 by komagata · Pull Request \#5515 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5515)

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/pull/5942
この作業の続きを行う。

**Comment by syo-tokeshi** [comment]
本番環境での動作確認をし、okだったのでクローズします。
