### ISSUE TITLE
talk.vue, talks.vueをVueMounterに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5143]
下記を参考にしてVueMounterを使ったマウント方法に変える。

- [Vue Componentのマウント方法 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/Vue-Component%E3%81%AE%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E6%96%B9%E6%B3%95)
- [announcementsをVueMounterに対応 by komagata · Pull Request #5113 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5113)

**Comment by machida** [comment]
@fuwa-syugyo やることがなくなったら、次はこちらをお願いしますー

**Comment by fuwa-syugyo** [comment]
@machida 
承知いたしました！
ありがとうございます〜

**Comment by fuwa-syugyo** [comment]
@komagata  @machida 
お疲れ様です！今週のリリース、ありがとうございます。
相談部屋のメンター向けページについて、本番環境での動作確認をお願いできますでしょうか？

確認方法
* サイドバーで`相談` をクリックする
*  `全て` タブと`未返信` タブの両方で相談部屋のリストが表示されていることを確認する(相談部屋がない場合は`未返信の相談部屋はありません` と表示されることを確認する)

よろしくお願いいたします！

**Comment by machida** [comment]
@fuwa-syugyo 本番で確認しました🙆‍♂️

**Comment by fuwa-syugyo** [comment]
本番環境でご確認いただきありがとうございます！
受講生向けページは確認済みですのでcloseします。
