### ISSUE TITLE
unconfirmed_link.vue, user-icon.vueをreactに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5144]
下記を参考にしてreactに変える。

- [react導入 \+ 管理画面のコース一覧をreact化 by komagata · Pull Request \#5515 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5515)

**Comment by maeda-m** [comment]
:memo: [ふりかえり・計画ミーティング2023年01月11日](https://github.com/fjordllc/bootcamp/wiki/%E3%81%B5%E3%82%8A%E3%81%8B%E3%81%88%E3%82%8A%E3%83%BB%E8%A8%88%E7%94%BB%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B02023%E5%B9%B401%E6%9C%8811%E6%97%A5) よりメモ

react に変える vue コンポーネントを使用している vue コンポーネントがあるため、この議題では react コンポーネントの新規作成までとする。
現状の vue コンポーネントには何もしない。

**Comment by maeda-m** [comment]
#6039 が本日リリースされました。
コンポーネントファイルの追加のみのため Close します🎉
