### ISSUE TITLE
user-practice-progress.vueをVueMounterに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5145]
下記を参考にしてVueMounterを使ったマウント方法に変える。

- [Vue Componentのマウント方法 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/Vue-Component%E3%81%AE%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E6%96%B9%E6%B3%95)
- [announcementsをVueMounterに対応 by komagata · Pull Request #5113 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5113)

**Comment by machida** [comment]
@choco0809 こちらもアサインさせていただきましたー

**Comment by choco0809** [comment]
@machida 
アサインありがとうございます🙇‍♂️

**Comment by choco0809** [comment]
@komagata 
`user-practice-progress.vue`は`user.vue`から`components`として利用されているように思えます。
今回のissueは`user.vue`をVueMounterに対応させるではなくて、`user-practice-progress.vue`をVueMounterに対応させるという認識で合っていますでしょうか？

**Comment by choco0809** [comment]
@komagata 
上記の質問ちゃんとVueしかりissueを理解できていなかったため、質問しましたが自己解決しました🙇‍♂️

**Comment by komagata** [comment]
@choco0809 

> 上記の2つをVue Mounterに対応させると、componentで使用されているuser-practice-progress.vueも一緒にマウントされるんじゃないかと思うのですが、認識はあやまっていますでしょうか？

「一緒にマウントされる」というのはちょっと違うんですが、今回修正する必要があるのはusers.vue, user.vueだけになるかと思います〜

**Comment by choco0809** [comment]
@komagata 
お忙しいところありがとうございます🙇‍♂️

> 今回修正する必要があるのはusers.vue, user.vueだけになるかと思います〜

#5147 のissueがusers.vue、user.vueをVueMounterに対応させるだったので、今回のissueと範囲が被るのではないかと思い、勝手にuser-practice-progress.vueを修正するんだと勘違いしていました！

> 「一緒にマウントされる」というのはちょっと違うんですが、

この点に関してはもうすこし理解しよう思います！

**Comment by choco0809** [comment]
本番環境で確認できましたのでcloseします。
