### ISSUE TITLE
user-sns.vue, user-tags.vueをVueMounterに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5146]
下記を参考にしてVueMounterを使ったマウント方法に変える。

- [Vue Componentのマウント方法 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/Vue-Component%E3%81%AE%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E6%96%B9%E6%B3%95)
- [announcementsをVueMounterに対応 by komagata · Pull Request #5113 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5113)

**Comment by AyakaTakashima** [comment]
@komagata @machida 
お疲れ様です！
こちらのissueなのですが、user-sns.vueとuser-tags.vueをcomponents配下に移動し、app/javascript/components/user.vueの中のimportパスを書き換えただけで完了してしまったのですが、変更内容はこの認識で合ってますでしょうか？
下記がPRの下書きです！（本件を確認したいため、まだPRは下書き状態です。）
https://github.com/fjordllc/bootcamp/pull/5524

cafedomancerさんとペアプロをさせていただいた際に、「簡単だったのでこの認識であっているか確認したほうが良い」とおっしゃっていたため確認させていただきたいです🙇‍♀️
よろしくお願いいたします🙇‍♀️

**Comment by komagata** [comment]
@AyakaTakashima user-sns.vueとuser-tags.vueが使われているのが上記だけであれば、こちらで問題ありません〜。

**Comment by AyakaTakashima** [comment]
@komagata 承知いたしました！お返事ありがとうございます！

**Comment by AyakaTakashima** [comment]
本番を確認し、問題なさそうでした。
クローズいたします。
