### ISSUE TITLE
user.vue, users.vueをVueMounterに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5147]
下記を参考にしてVueMounterを使ったマウント方法に変える。

- [Vue Componentのマウント方法 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/Vue-Component%E3%81%AE%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E6%96%B9%E6%B3%95)
- [announcementsをVueMounterに対応 by komagata · Pull Request #5113 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5113)

**Comment by shirotamaki** [comment]
本番環境での動作確認ができたのでcloseします！
