### ISSUE TITLE
watch.vue, watches.vueをVueMounterに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5150]
下記を参考にしてVueMounterを使ったマウント方法に変える。

- [Vue Componentのマウント方法 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/Vue-Component%E3%81%AE%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E6%96%B9%E6%B3%95)
- [announcementsをVueMounterに対応 by komagata · Pull Request #5113 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5113)

**Comment by keiz1213** [comment]
@komagata @machida 

お疲れさまです。1点質問があります。

## app/views/watches/index.html.slimについて
現状ではapp/views/watches/index.html.slimは使われていないと思いますが、削除してもよろしいでしょうか？それとも残していたほうがよろしいでしょうか？よろしくお願いいたします。

**Comment by machida** [comment]
@keiz1213 削除お願いしますー🙏

**Comment by keiz1213** [comment]
本番環境で確認できたのでcloseします。
