### ISSUE TITLE
worried-user.vue, worried-users.vueをVueMounterに対応させる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5151]
下記を参考にしてVueMounterを使ったマウント方法に変える。

- [Vue Componentのマウント方法 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/Vue-Component%E3%81%AE%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E6%96%B9%E6%B3%95)
- [announcementsをVueMounterに対応 by komagata · Pull Request #5113 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5113)

**Comment by daiki0381** [comment]
@komagata @machida 
お疲れ様です。こちらメンターアカウントの修正なので本番環境のご確認をお願いしたいです🙏

【確認事項】

- https://bootcamp.fjord.jp/mentor にアクセスし、問題なく表示されるか確認する。

**Comment by komagata** [comment]
@daiki0381 本番環境で動作することを確認しました。

**Comment by daiki0381** [comment]
@komagata  ありがとうございます🙇‍♂️ こちらcloseさせて頂きます。
