### ISSUE TITLE
参考書籍ページの「イラスト図解式 この一冊で全部わかるWeb技術の基本」が2つ表示されている

### ISSUE THREAD

**Issue by SatoshiHaramura** [fjordllc/bootcamp#5153]
## 概要

参考書籍ページの「イラスト図解式 この一冊で全部わかるWeb技術の基本」が2つ表示されている。

## 再現手順

1. /booksにアクセス。

## 期待される振る舞い

「イラスト図解式 この一冊で全部わかるWeb技術の基本」が1つのみ表示されること。

## スクリーンショット
![Cursor_and_参考書籍___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/11376040/176807229-f3ca29ce-d0bc-4551-ab65-7b23551a3293.png)

**Comment by komagata** [comment]
@SatoshiHaramura 2個登録されているだけなので片方削除しておきます〜
