### ISSUE TITLE
企業一覧、企業個別の現役生の数字に卒業生を含めない

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5163]
http://localhost:3000/companies

ここにアクセスすると、

<img width="561" alt="貼り付けた画像_2022_07_05_19_52" src="https://user-images.githubusercontent.com/168265/177312151-36f42406-0004-495c-8b58-caa7aba8df8e.png">

このように研修生の数字が表示されている。
現在、研修生に卒業生も含まれているが、卒業生は別で表示したい。
卒業生を別で表示するのは別Issueでの対応にするので、今回は、ここの数字を卒業生は含めない数に変更をお願いします。

卒業生を含めない数は、企業個別ページのユーザータブ > 現役生 で表示しています。

<img width="512" alt="貼り付けた画像_2022_07_05_19_56" src="https://user-images.githubusercontent.com/168265/177312739-eff7b4a3-3a76-4a5e-ba35-4bf7c62550ea.png">

同時に、企業個別ページの企業情報タブ の以下の部分も卒業生は含めない数に変更をお願いします。

<img width="782" alt="貼り付けた画像_2022_07_05_19_58" src="https://user-images.githubusercontent.com/168265/177313033-59a81685-2a88-43b2-81fb-c03c02d4a6a9.png">

**Comment by kei-kmj** [comment]
@machida
>卒業生を含めない数は、企業個別ページのユーザータブ > 現役生 で表示しています。

ということは、会社別の現役の研修生の数と、企業個別ページのユーザータブの現役生の数は常に一致するという理解でいいのでしょうか？

下記のMaruMaru.incは会社所属の現役生が研修生となっていないために、数字が合わないようです。
- 研修生の定義
- MaruMaru.incの研修生の数は何人になるべきか
について教えていただけますでしょうか？
![2022-07-07](https://user-images.githubusercontent.com/82737807/177742033-d33c4afe-8909-4ed1-b099-7ac5301bed52.png)
![2022-07-07 (1)](https://user-images.githubusercontent.com/82737807/177742069-a94963ab-570b-42ca-856f-e04c8dbe1145.png)

**Comment by machida** [comment]
@kei-kmj 

seedデータがおかしいですね。

本番のデータでは、企業に紐付いた現役生は研修生であるので、研修生のフラグを持っていない企業に紐付いた現役生は存在しないです。

ただ、現時点では研修生のフラグを持っていない企業に紐付いた現役生を作成することは可能です。本番のデータで研修生のフラグを持っていない企業に紐付いた現役生がもしいた場合、研修生のフラグを付け忘れていることになります。

なので、このIssueで変更する数字は、「企業に紐付いた現役生であるユーザー（研修生のフラグのある無しは問わない）」の数を表示してもらえば、その企業に現在何人の研修生が稼働中なのかが確認できます。

「企業に紐付いた現役生であるユーザー」の数とは、

<img width="202" alt="貼り付けた画像_2022_07_08_3_49" src="https://user-images.githubusercontent.com/168265/177849260-2b11a7dd-6400-4991-adf4-1f8fcb7885a3.png">

この数字になります。

なので、この数字を以下の部分に表示する様にお願いします。

<img width="338" alt="貼り付けた画像_2022_07_08_3_48" src="https://user-images.githubusercontent.com/168265/177848980-58cd1d7c-da9b-419d-ae3d-2cf5311de727.png">

ちなみに、研修生のフラグを持つと、ユーザーのアイコンの周りに紫色のボーダーが付くようになります。
企業に紐付いた現役生であるユーザーは現役研修生なので研修生のフラグは不要？かもしれないのですが、そのへんの整理は別Issueで行います。

---

> 研修生のretiredはありえないのでしょうか？

研修期間が終了するとretiredになります。（研修終了が completedではなく retired になってしまうのはシステム的には退会になっているせいです）

以下の数字は研期間修が終了した企業に紐づくユーザーも含んだ数になります。

<img width="350" alt="貼り付けた画像_2022_07_08_3_55" src="https://user-images.githubusercontent.com/168265/177850797-07558817-1d2a-49c1-8730-7e614670015e.png">

**Comment by machida** [comment]
ついでなのですが、以下の部分で「現役生」という名前を使っているので、

<img width="281" alt="貼り付けた画像_2022_07_08_4_05" src="https://user-images.githubusercontent.com/168265/177852353-56534354-aaba-46f3-a43d-494bbb2902eb.png">

ここも現役生に変更をお願いします🙏


<img width="136" alt="貼り付けた画像_2022_07_08_4_04" src="https://user-images.githubusercontent.com/168265/177852268-33a819c5-a49d-4031-ab23-85e7ea517a11.png">

**Comment by kei-kmj** [comment]
本番環境で動作確認できましたのでcloseします
