### ISSUE TITLE
通知のWatchにプラクティスの提出物についての通知がない

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5177]
メンターでログインをし、プラクティス個別ページに行き、プラクティスを Watch する。

<img width="1099" alt="貼り付けた画像_2022_07_05_19_43" src="https://user-images.githubusercontent.com/168265/177310755-8610184e-4a9c-4889-a349-ca0ce1c40f3e.png">

別のユーザーでログインし、上記のプラクティスを提出する。

また先程のメンターでログインする。

すると、メンターに通知が届いている。

<img width="269" alt="image" src="https://user-images.githubusercontent.com/168265/177310907-9936f318-4521-40ca-baa5-aa0c70af9768.png">

ところが、

通知 > Watch（ http://localhost:3000/notifications?status=unread&target=watching ）にも、

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/168265/177310596-d28a9430-22a9-4537-91e9-c714b255583f.png">

通知 > 全て（ http://localhost:3000/notifications?status=unread ）にも

この通知が表示されていない。

---

Watch しているプラクティスに提出物が新規に登録されたら、

- 通知 > 全て にその通知が登録される
- 通知 > Watch にその通知が登録される

ようにお願いします。

**Comment by akingo55** [comment]
@machida 
こちらのバグ、ローカルで再現しました。
watch中のプラクティスは、Notificationの種類(kind)がsubmittedで登録されているため、通知>watchには表示されないようです。
Notificationの種類をwatchingに変更すれば、想定通りの挙動になりますが、こちらはsubmittedからwatchingに変更して問題ないでしょうか？
該当コード：https://github.com/fjordllc/bootcamp/blob/main/app/notifiers/activity_notifier.rb#L92

>通知 > 全て（ http://localhost:3000/notifications?status=unread ）にもこの通知が表示されていない。

こちらの件に関しては、通知が表示されているので問題ないかと思います。
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/43959158/209907884-c95aea0d-3ed7-421a-a1ba-3201eb7df35d.png">

**Comment by machida** [comment]
@akingo55 確認ありがとうございます！！
一旦、watch に変更して問題がないか確認をお願いします。
問題がなかったら、これについてのテストの追加もお願いします。

**Comment by akingo55** [comment]
確認ずみ
https://github.com/fjordllc/bootcamp/pull/5994#issuecomment-1415224535
