### ISSUE TITLE
検索結果にコンテンツ作成者のアイコンを表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5184]
<img width="523" alt="貼り付けた画像_2022_07_06_23_29" src="https://user-images.githubusercontent.com/168265/177574643-9e9434d1-81a1-42ae-9679-267d4c545737.png">

**Comment by kei-kmj** [comment]
@machida @komagata
お手数をお掛けして申し訳ありませんが、
仕様に関して、下記の1～6の認識で合っているかどうか、お教えいただけますでしょうか。

![2022-08-05 (1)](https://user-images.githubusercontent.com/82737807/183068763-3b87cbdd-d31c-413f-8c86-210893eaed0d.png)
1. スクショ中の検索結果2つ目のように、3行目にコンテンツ作成者の名前が表示されるときに、左わきにアイコンが表示される
2. スクショ中の検索結果3つ目のように、検索結果がコメントだった場合、日報作成者であるhatunoのアイコンではなく、コメントした人のアイコンを表示する
3. 3行目にコンテンツ作成者の名前が表示されない、プラクティスやユーザー等の検索結果はアイコン不要
4. アイコンはホバーすると作成者の名前とroleがポップアップ表示される
5. アイコンは作成者のプロフィールページにリンクする
6. 町田さんにデザインをお願いする必要がある

**Comment by komagata** [comment]
@kei-kmj 

> 1. スクショ中の検索結果2つ目のように、3行目にコンテンツ作成者の名前が表示されるときに、左わきにアイコンが表示される

はい。

> 2. スクショ中の検索結果3つ目のように、検索結果がコメントだった場合、日報作成者であるhatunoのアイコンではなく、コメントした人のアイコンを表示する

表示されているlogin_nameと同じユーザーのアイコンを表示してください。

> 3. 3行目にコンテンツ作成者の名前が表示されない、プラクティスやユーザー等の検索結果はアイコン不要

はい。

> 4. アイコンはホバーすると作成者の名前とroleがポップアップ表示される

他のアイコンが表示されている場所と同じ仕様でお願いします。

> 5. アイコンは作成者のプロフィールページにリンクする

他のアイコンが表示されている場所と同じ仕様でお願いします。

> 6. 町田さんにデザインをお願いする必要がある

はい。

**Comment by machida** [comment]
@kei-kmj 確認しました！それでお願いしますー🙆‍♂️

**Comment by kei-kmj** [comment]
本番環境で動作確認できたのでcloseします
