### ISSUE TITLE
[みんなのブログ] RSS から最新のブログ記事を取得したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5193]
一日 n 回、RSSからブログ記事の

- 記事タイトル
- 記事URL
- 記事サマリー
- OGP イメージ
- ブログタイトル

を取得し、DBに入れたい。

**Comment by siso25** [comment]
2022/11/16 振り返りMTG
退会したユーザーのみ取得・更新対象から除外する

**Comment by komagata** [comment]
@siso25 後から見た人（後からこのプロジェクトに入ってきて、このIssueに関連する不具合の修正の担当になり、その経緯を調査している人をイメージするとわかりやすいです。）にとってわかりやすい書き方をしていただければありがたいです。
ちょっと言葉・情報が足りないかもです。

**Comment by siso25** [comment]
@komagata 
申し訳ありません。上記の記載内容を修正しました。

**Comment by siso25** [comment]
@komagata 
最新のブログ記事を取得するrakeタスクを定期実行をするために、[whenever](https://github.com/javan/whenever)を追加しようと考えていますが、よろしいでしょうか。

**Comment by komagata** [comment]
@siso25 定期実行はCloud Runだと使えないので（cronがないため）、`/scheduler/daily`に毎日アクセスさせるなどで対応しています。

定期実行させたい処理はどのくらいの頻度でしょうか？

**Comment by siso25** [comment]
@komagata 
あくまで「フィヨルドに登録している人のブログのみ」を取得する機能ですので、1日1〜2回程度で考えていました。

> /scheduler/dailyに毎日アクセスさせるなどで対応しています。

1日1回こちらの方法で定期実行させたいと思います。
`Scheduler::DailyController`の`show`アクションに、当該rakeタスクを実行する処理を追加するイメージで問題ないでしょうか。

**Comment by komagata** [comment]
@siso25 

> 1日1〜2回程度で考えていました。

なるほどですね。`Scheduler::HourlyController`とかを作ることも考えていたので必要であればおっしゃっていただければ僕の方で作ります。

> 当該rakeタスクを実行する処理を追加するイメージで問題ないでしょうか。

Rakeタスクを実行するのではなくて、rakeタスクの中でやっている処理をこちら（Controller）に書くようにお願いします。（Rakeタスクは不要になるので）

**Comment by siso25** [comment]
> Rakeタスクを実行するのではなくて、rakeタスクの中でやっている処理をこちら（Controller）に書くようにお願いします。

承知しました。`Scheduler::DailyController`に処理を書くようにします。

**Comment by siso25** [comment]
@komagata 
「ユーザー情報に登録されているURLから記事を取得して、DBに登録する」テストを書く際、実在するブログのURLを使用するのでしょうか。

**Comment by komagata** [comment]
@siso25 実在しないものを使ってvcr(webmock)のgemを使ってmockすると良いと思います〜
（bootcampでも既に使っているのでその部分のコードが参考になるかもです）

**Comment by komagata** [comment]
@siso25 難しいかもなので、もし行き詰まっていたらペアプロしましょ〜

**Comment by siso25** [comment]
@komagata 
該当箇所は見つけましたが、ちょっと詰まっているのでペアプロをお願いしたいです。
直近ですと「金曜日の20時以降」か「土、日」でお願いできればと思いますが、ご都合いかがでしょうか。

**Comment by siso25** [comment]
@komagata 
はい、12/9 20:00〜でよろしくお願いします！

**Comment by komagata** [comment]
:memo: ペアプロ済み
