### ISSUE TITLE
新規ユーザー登録があったときに、mentorに通知したい。

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5198]
サイト内通知・メール通知が飛ぶようにしたい。

**Comment by SatoshiHaramura** [comment]
@machida 
お疲れ様です。
新規ユーザー登録時の、メンター宛てのメール通知とサイト内通知につきまして、以下の草案を考えましたので、問題がなさそうかご確認頂きたいです🙏
1. メールの件名と本文
2. サイト内通知のタイトル

### 1. メールの件名と本文

| 件名 | 本文 |
| --- | --- | 
| [bootcamp] xxxxさんが新しく入会しました！ | xxxxさんが新しく入会しました！</br> xxxxさんのページへ |

↓は仮実装でのイメージとなります。
![_development__LetterOpenerWeb](https://user-images.githubusercontent.com/11376040/179094136-c9b7cb6c-c9df-42d1-bfc0-15a4586a0777.png)


### 2. サイト内通知のタイトル
`🎉 xxxxさんが新しく入会しました！`

↓は仮実装でのイメージとなります。
![Cursor_and__development__通知___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/11376040/179092958-0b591cd8-be05-4c43-a0b3-3f4cf9797a6b.png)

**Comment by SatoshiHaramura** [comment]
@komagata @machida 
お疲れさまです。
本番環境にリリースされましたので、本番環境で動作確認を行って頂きたいです🙏

新規ユーザーが登録された際に、メンター宛てに、メール通知およびサイト内通知が行われていることを確認して頂きたいです。

- メール通知の場合
以下の内容のメールが届きます。

![Cursor_and__development__LetterOpenerWeb](https://user-images.githubusercontent.com/11376040/179086352-1d9182d2-fea9-4d33-9488-dae721981697.png)

- サイト内通知の場合
以下の内容が通知されます。

![Cursor_and__development__ダッシュボード___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/11376040/179088701-88a7039c-30c9-4934-aa49-26e9de8df33a.png)

![Cursor_and__development__通知___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/11376040/179089420-473d3ec6-cb3d-404d-a406-d4d3bfaed904.png)

**Comment by komagata** [comment]
@SatoshiHaramura 本番で本当にユーザー登録があった時に確認いたしますのでしばらくお待ちいただければ幸いです〜。

**Comment by komagata** [comment]
@SatoshiHaramura 本番環境で通知されていることを確認致しました。

**Comment by SatoshiHaramura** [comment]
@komagata 
ご確認頂きありがとうございます！

**Comment by SatoshiHaramura** [comment]
本番環境での動作確認が完了しましたので、close致します。
