### ISSUE TITLE
アイコン付きメンションで使われている画像が無駄に大きい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5200]
`:@jnchito:` のように記述するアイコン付きメンション（ユーザー絵文字）で表示される画像は、どうもオリジナルサイズの画像が使われている様子。

人によっては数MBある大きな画像をアップロードしているので、小さなアイコンなのに表示されるまで数秒かかることがある。
表示サイズは27x27px程度なので、そのサイズに見合った小さな画像を用意する方が望ましい。

例 https://bootcamp.fjord.jp/announcements/697
<img width="825" alt="2" src="https://user-images.githubusercontent.com/1148320/177886906-7e082781-9197-4738-a919-b6dbdbfc46b6.png">

**Comment by kei-kmj** [comment]
@machida
おつかれさまです。アイコン付きメンションのリサイズについて、
下記の表のように数パターンでリサイズしてみたので、どの程度のサイズにするか相談させてください。
追加で必要なデータがあればご教示ください。

- 検証方法
お知らせを作成し、文章中に写真と絵のアイコン付きメンション2つを挿入し、devツールのネットワークタブで画像の容量と全体の処理時間を比べました
- 表の見方
  - 元は1.86MBあった画像が、500*500にリサイズすると93.4kBになる
  - 500*500にリサイズした時のお知らせ全体のリクエスト処理時間が4.02秒である
 - 比較対象
 一番右にアイコン画像の容量を比較として載せました。この処理時間は、お知らせからアイコン付きメンションを2つ削除した時のリクエスト全体の処理時間です。
- 処理時間について
あまり差が出ていませんが、ローカル環境だと検証しにくいのかも、と思いました

<img width="820" alt="画像3" src="https://user-images.githubusercontent.com/82737807/179874625-9f776ff9-1f65-4b04-a9c6-1442ebe53b6c.png">

**Comment by machida** [comment]
@kei-kmj アイコンのサイズの提案ありがとうございます！！

今表示しているサイズが、27px * 27px なのですが、近々 28px * 28px に修正する予定です。
高解像度のディスプレイを考慮して、その倍の解像度 56px * 56px で表示したいと思います。
なので、500px よりかなり小さいですが、56px * 56px でのリサイズでお願いします🙏

**Comment by kei-kmj** [comment]
動作確認できたのでcloseします
