### ISSUE TITLE
プラクティスのステータスが提出しても【提出】にならない

### ISSUE THREAD

**Issue by mayumonj** [fjordllc/bootcamp#5202]
## 概要

プラクティスの提出物を出しても、ステータスが提出にならない

## 再現手順

「着手」ステータスになっているプラクティスの提出物を出すと、ステータスが「着手」のままになります。
（「未着手」のステータスから提出物を出したときにどうなるのかは、現状確認できていません。）

## 期待される振る舞い

提出物を出したらステータスが提出になる

## 環境

 - Mac OS 12.4
 - chrome
 - バージョン: 103.0.5060.114（Official Build） （x86_64）

## 関連Issue

https://github.com/fjordllc/bootcamp/issues/4428
こちらのissueと同じ内容です。
権限の問題なのかReopenができなかったため、新規issueとして起票しました。

**Comment by yocajii** [comment]
本番環境で動作確認できましたので、クローズいたします。
