### ISSUE TITLE
M2 チップ搭載マシンが発売されたので "学習に使うマシン・OS" の項目を見直す必要がある

### ISSUE THREAD

**Issue by cafedomancer** [fjordllc/bootcamp#5205]
## 機能の説明

そのままです。この情報はトラブルシューティングするときの参考として必要になります。欲しい情報は Intel チップと Apple チップのどちらであるかということなので、以下のように項目を統合するのがいいのかなーと思います (もちろん保存済みのデータ合わせて見直す必要アリ) 。

as is

- Mac (Intel)
- Mac (M1 chip)

to be

- Mac (Intel チップ)
- Mac (Apple チップ)

## 何故この機能が必要なのか

M2 チップ搭載マシンを使用している人が "学習に使うマシン・OS" を適切に選択できないため。

## 関連 issue

https://github.com/fjordllc/bootcamp/issues/2559

**Comment by machida** [comment]
📝 

- 見た目の変更は完了してます。
- 残りの作業
    - `enum os:` で `mac_m1` と名前が付けられていて、それに合わせていくつかの箇所で `mac_m1` を使っているところをがあるので、それらを `mac_apple` に変更する。

**Comment by komagata** [comment]
@machida ありがとうございます〜！

**Comment by yocajii** [comment]
- 見た目の変更
- コード上の変更

いずれも本番環境で動作確認できましたので、closeいたします。
