### ISSUE TITLE
新規ユーザーが登録され、そのユーザーが初回ログインするまでの間、一部のページが正しく表示されない

### ISSUE THREAD

**Issue by SatoshiHaramura** [fjordllc/bootcamp#5207]
## 概要

新規ユーザーが登録され、そのユーザーが初回ログインするまでの間、以下のページにアクセスしても正しく表示されない。

正しく表示されないページ
1. ユーザー一覧ページ(/users)　※全ユーザー
2. 新規登録されたユーザーのユーザー詳細ページ(/users/:id)　※管理者orメンターでログイン時
3. 管理ページのユーザー一覧(/admin/users)　※管理者でログイン時

## 再現手順

共通の手順
1. フィヨルドブートキャンプ参加登録(/users/new)にアクセスし、必要な情報を入力し「参加する」をクリックする。

#### 1. ユーザー一覧ページの場合
1. ログインページ(/login)にアクセスし、任意のユーザーでログインする。
2. ユーザー一覧ページ(/users)にアクセス。
3. 「ロード中」と表示されたままになる。

#### 2. 新規登録されたユーザーのユーザー詳細ページの場合
1. ログインページ(/login)にアクセスし、管理者orメンターでログインする。
2. 新規登録されたユーザーのユーザー詳細ページ(/users/:id)にアクセス。
3. エラーが表示される。

#### 3. 管理ページのユーザー一覧の場合
1. ログインページ(/login)にアクセスし、管理者でログインする。
2. 管理ページのユーザー一覧(/admin/users)にアクセス。
3. エラーが表示される。

## 期待される振る舞い

1. ユーザー一覧ページが正しく表示されること。
2. 新規登録されたユーザーのユーザー詳細ページが正しく表示されること。
3. 管理ページのユーザー一覧が正しく表示されること。

## 関連Issue

Ref: #2231

**Comment by SatoshiHaramura** [comment]
@komagata @machida 
お疲れ様です。
新規ユーザーが登録されそのユーザーが初回ログインするまでの間でも、一部のページが正しく表示されることを、本番環境で動作確認して頂きたいです🙏

確認手順と確認内容は以下の通りとなります。

### 前提条件
1. フィヨルドブートキャンプ参加登録(/users/new)にアクセスし、必要な情報を入力し「参加する」をクリックし、新規ユーザーを登録する。(アカウントを作成するのみで、そのアカウントでログインは1度も行わない状態)

### 確認手順と確認内容
#### 1. ユーザー一覧ページの場合
1. ユーザー一覧ページ(/users)にアクセス。
2. 「ロード中」と表示されず、正しく表示されることを確認する。

#### 2. 新規登録されたユーザーのユーザー詳細ページの場合
1. 新規登録されたユーザーのユーザー詳細ページ(/users/:id)にアクセス。
2. 正しく表示されることを確認する。
3. 1度もログインしていないユーザーの場合、`最終活動日時`が何も表示されていないことを確認する。

#### 3. 管理ページのユーザー一覧の場合
1. 管理ページのユーザー一覧(/admin/users)にアクセス。
2. 正しく表示されることを確認する。
3. 1度もログインしていないユーザーの場合、`最終活動日時`が何も表示されていないことを確認する。

**Comment by komagata** [comment]
@SatoshiHaramura 本番環境で動作することを確認しました。

**Comment by SatoshiHaramura** [comment]
@komagata 
動作確認していただきありがとうございました！

**Comment by SatoshiHaramura** [comment]
本番環境での動作確認が完了致しましたので、close致します。
