### ISSUE TITLE
プレビューと投稿後の表示が異なる

### ISSUE THREAD

**Issue by OdenTakashi** [fjordllc/bootcamp#5212]
## 概要
テーブル作成の際一部の行で列数が揃っていない場合にプレビューと投稿後の表示が異なる。
同じくプレビューと投稿後の表示が異なるページ
## 再現手順
https://bootcamp.fjord.jp/products/:id/edit にて。
1. テーブル作成の際にヘッダの行の列数を７、その下の行の列数のみを８にする
2. プレビューを確認するとテーブルが作成されている
3. 投稿をする
4. 投稿後は表示がプレビューと異なり、テーブルが作成されていない

### 再現用の入力テキストです。

|      | パターン | 1 | 2 | 3 | 4 | 5 |
|------|------------------|---|---|---|---|---|---|
| 条件 | 500円以上買い物 | - | - | - | Y | N |
|      | 3000円以上買い物 | - | - | Y | N | N |
|      | 日曜祝日 | - | Y | N | N | N | 
|      | 商品券利用 | Y | - | N | N | N |
| 結果 | 1時間無料 | - | - | - | X | - |
|      | 2時間無料 | - | - | X | - | - |
|      | 割引無し | X |  X | - | - | X |

### プレビュー時の表示です。
<img width="634" alt="スクリーンショット 2022-07-12 12 48 32" src="https://user-images.githubusercontent.com/81839214/178404683-cfb12def-8b21-44dc-a319-4a671fe71d54.png">

### 投稿後の表示です。
<img width="321" alt="スクリーンショット 2022-07-11 23 18 58" src="https://user-images.githubusercontent.com/81839214/178285893-d35657ac-68ee-4e93-bdb9-b2d78742fde7.png">

## 期待される振る舞い
テーブルの記述がおかしい場合にプレビューでテーブルが作成されないこと

**Comment by machida** [comment]
📝  追記解説

以下の Markdown の table のコードには間違いがある。
thead と tbody の境目の `---` のボーダーの列のカラム数が1つ足りない。

```md
| | パターン | 1 | 2 | 3 | 4 | 5 |
|------|------------------|---|---|---|---|---|---|
| 条件 | 500円以上買い物 | - | - | - | Y | N |
| | 3000円以上買い物 | - | - | Y | N | N |
| | 日曜祝日 | - | Y | N | N | N |
| | 商品券利用 | Y | - | N | N | N |
| 結果 | 1時間無料 | - | - | - | X | - |
| | 2時間無料 | - | - | X | - | - |
| | 割引無し | X | X | - | - | X |
```

ところが、間違いのある table を書いても、プレビューでは間違いを無視して、table タグとして認識をし、プレビューには table で表示される。

しかし、プレビューではなく提出をすると、間違いは無視されず、table では表示されず、文字列で表示されてしまう。
