### ISSUE TITLE
[ブログ] ブログ個別ページに最新の記事の一覧を10個表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5213]
<img width="1058" alt="貼り付けた画像_2022_07_12_11_33" src="https://user-images.githubusercontent.com/168265/178395989-39641f30-15ef-4386-bf20-4a50cbb750d9.png">

ここに最新の記事の一覧を10個表示。

各記事に表示するもの

- 記事タイトル
- サムネイル（記事に設定してあれば）
- 作者のアイコン
- 作者ID

**Comment by yocajii** [comment]
@machida @komagata 
ブログの最新記事の要件について質問させてください。

当初は「`publidhed_at`に日時が入っている、かつWIPではない」記事を公開中の記事と判定して、`publidhed_at`が新しい順に並べる、という処理をイメージしていましたが、過去のプルリクを調べてみると`publidhed_at`が空でもあえて公開済みの扱いにしているようでした。
また、ブログ記事一覧ページでソートに使われているのも`published_at`ではなく`created_at`でした。
https://github.com/fjordllc/bootcamp/blob/7c19c621d46cfc0fc548cf815d33b77544f4c612/app/controllers/articles_controller.rb#L59

そこで、下記2点について確認させていただきたいです。

1. 公開中の記事の判定は次のどちらを採用するべきでしょうか
   - `publidhed_at`に日時が入っている、かつWIPではない
   - WIPではない
2. 最新記事のソートにはどちらの列を採用するべきでしょうか
   - `published_at`
   - `created_at`

## 参考にしたIssue, PR

#4200
#3730

**Comment by yocajii** [comment]
2022-07-20 チーム開発ミーティングにて
- 公開中の記事の判定：WIPかどうか
- ソート：`published_at`
  - 一覧画面のソートも`published_at`に変更する

**Comment by yocajii** [comment]
本番環境で動作確認できましたので、クローズいたします。
