### ISSUE TITLE
提出物を提出したら、ステータスを自動で提出にしてほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5214]
## バグの修正

現在、プラクティスAを着手にし、提出をすると、プラクティスAのステータスは提出になる。
この時点で、別のプラクティスBを着手することができる。
ここまではOK。

別のプラクティスBを提出すると、
始めに提出したプラクティスAのステータスが提出から着手に戻ってしまう。
これがバグ。
プラクティスAのステータスは提出のままでいてほしい。

## バグ修正後の仕様変更

バグが修正され、
プラクティスAのステータスは提出、別のプラクティスBのステータスも提出になったら、
さらに別のプラクティスCに着手ができるようにしたい。

- ダッシュボードにある「進行中のプラクティス」
- ユーザー個別ページにある「進行中のプラクティス」

には、まだ完了はしていない着手、提出のステータスになっているプラクティスを全て表示したい。

## バグ修正後の仕様変更2

プラクティス一覧ページに移動する際、着手中のプラクティスにスクロールされるようになっている。
今回の仕様変更で、ユーザーは複数の着手中のプラクティスを持つことになるが、それらの中の順番が一番若いもののところへスクロールされるようにしたい。

**Comment by machida** [comment]
関連Issue

- https://github.com/fjordllc/bootcamp/issues/5202
- https://github.com/fjordllc/bootcamp/issues/4428

このIssueをクローズしたら、上記のIssueもクローズをお願いします。

**Comment by komagata** [comment]
@machida 上記のスクショには「提出物を提出するか完了すると新しいプラクティスを開始できます」と書いてありますが、
変更後と同じ内容だったりしないですかね？

**Comment by machida** [comment]
@komagata 勘違いしてました🙇‍♂️

バグがあったので、Issueの内容を修正しますー

**Comment by yocajii** [comment]
@machida さん
このIssueで対応するべきことについて相談させてください。

まず、元のIssue #4428 を確認すると、下記の動作が現状では機能していない事を報告する内容のように見受けられました。
> 現在、プラクティスAを着手にし、提出をすると、プラクティスAのステータスは提出になる。
ここまではOK。

また、下記の動作は開発環境では再現できず、元のIssueでも触れられていないように見受けられました。
> 別のプラクティスBを提出すると、始めに提出したプラクティスAのステータスが提出から着手に戻ってしまう。
これがバグ。

そのため、OKのはずの動作が機能しておらず、バグとされる動作が確認できないといった状況で、どのように対応すれば良いか困っています。

一方で、元のIssueで報告されているバグについても調査してみました。
本番環境および開発環境でも再現済みで、原因と修正箇所も特定済みです。

- 現状
  - 提出物を出してもプラクティスのステータスが変わらない
- あるべき姿
  - 提出物を出したらプラクティスのステータスが提出になる

このIssueは #4428, #5202 に対応するために作られたようですので、そちらで報告されているバグを解消するのが本来の目的にかなうかと考えましたが、このまま元のIssueで報告されているバグに対応する方向で進めて問題ないでしょうか。

**Comment by machida** [comment]
@yocajii すいません、現状の認識が間違ってましたー🙇‍♂️関連Issueにあるバグを修正し、最終的にこのIssueの目的の通りの動きになるように対応していただきたいです🙏

**Comment by yocajii** [comment]
@machida 
ご回答くださいましてありがとうございます🙏✨
> 関連Issueにあるバグを修正し、

承知しました！

> 最終的にこのIssueの目的の通りの動きになるように対応

仕様変更の件で合っていますでしょうか。
仕様変更についても、いくつか確認させていただきたいことがあります。

### バグ修正後の仕様変更について

> プラクティスAのステータスは提出、別のプラクティスBのステータスも提出になったら、  
さらに別のプラクティスCに着手ができるようにしたい。

こちらは現状の動作と変わらないように思いました。
現状は、着手できるかどうかの条件は「着手中のプラクティスが1つもない」だけで、ステータス「提出」のプラクティスがいくつあったとしても新しいプラクティスに着手できない要因にはなっていないように見受けられます。

> - ダッシュボードにある「進行中のプラクティス」
> - ユーザー個別ページにある「進行中のプラクティス」
>
> には、まだ完了はしていない着手、提出のステータスになっているプラクティスを全て表示したい。

現状では「着手」のプラクティスのみ表示されますが、新しい要件として「提出」のプラクティスも表示したいということで合っていますでしょうか。

こちらはバグ対応とはまた別途調査が必要そうなので、ポイントについて相談させていただければと思います🙇‍♂️

### バグ修正後の仕様変更2

> 今回の仕様変更で、ユーザーは複数の着手中のプラクティスを持つことになる

ここまでで、現状は1つまでに制限されている「着手」ステータスのプラクティスの制限をなくすといった話は出ていない認識です。
「着手」ステータスに加えて「提出」ステータスも含めて「着手中」のようなものと考えるという意味でしょうか？

> それらの中の順番が一番若いもののところへスクロールされるようにしたい。

現状は「着手」にスクロールしますが、変更後は「着手」「提出」の中で最も若いプラクティスにスクロール先を変更するということで合っていますでしょうか。

こちらもバグ対応とはまた別途調査が必要そうなので、ポイントについて相談させていただければと思います🙇‍♂️

**Comment by machida** [comment]
@yocajii 

すいません、なんか色々現状について僕の誤解がありました。
まとめますー

1. 一旦ローカルで、DBを初期化します（`db:reset db:migrate db:seed`）。
1. hatsuno でログインします。
1. プラクティス「OS X Mountain Lionをクリーンインストールする」のステータスを「着手」にします。
1. プラクティス「PC性能の見方を知る」のステータスを「着手」にするとエラーが出る（これでOK）。
1. プラクティス「OS X Mountain Lionをクリーンインストールする」で提出物を提出します。すると、提出をしたのにステータスは「着手」のままで自動で「提出」に切り替わらない（これはバグ？自動で切り替わるようにしたい）。
1. プラクティス「PC性能の見方を知る」のステータスを「着手」にするとエラーが出る（着手が2つになるのでエラーが出るのはOK）。
1. プラクティス「OS X Mountain Lionをクリーンインストールする」を手動で「提出」に変更する。
1. 再度、プラクティス「PC性能の見方を知る」のステータスを「着手」にする。今度はエラーは出ずに「着手」にステータスを変えることができる（着手は1つだけなので、これでOK）。
1. プラクティス「PC性能の見方を知る」のステータスを「完了」にするとエラーは出ずに「完了」にステータスを変えることができる（これでOK）。
1. 別ブラウザで machida でログインをし、hatsuno のプラクティス「OS X Mountain Lionをクリーンインストールする」の提出物を「確認」する。
1. hatsuno のプラクティス「OS X Mountain Lionをクリーンインストールする」のステータスは自動で「完了」になる（これでOK）。

提出物を提出すると、自動でステータスが「提出」に切り替わるようにしていたと思ったのですが、そうはなっていませんでした。こちらをそうなるように仕様変更をお願いしたいです🙏

メンターが提出物をOKにすると、自動でプラクティスのステータスが完了になりますが、それと同様に、提出物を提出したら自動でステータスが「提出」に切り替わるようにしてほしいです。

---

## 今回、変更をしないもの

### 複数の着手は不可

着手から提出にステータスを切り替えたら他のプラクティスに着手ができるようになる、はすでに実装されていて、その部分にバグがなかったので変更はなしでお願いします。引き続き複数のプラクティスを着手にはできないようにお願いします。

## ダッシュボードにある「進行中のプラクティス」とユーザー個別ページにある「進行中のプラクティス」

現在は着手中のプラクティスだけが表示されている。つまり「進行中 = 着手」となっているが、「進行中 = 着手 or 提出」にしたい。でも、これは別Issueにしたいと思います。

### プラクティス一覧のスクロール

> 現状は「着手」にスクロールしますが、変更後は「着手」「提出」の中で最も若いプラクティスにスクロール先を変更するということで合っていますでしょうか。

別 Issue で「進行中 = 着手 or 提出」に変更した上で、スクロールのルールもそのようにしたいと考えています。これも別 Issue で対応したいと思います。

---

## 今回、変更をしてほしいもの

### 機能: 提出をすると自動で提出にステータスが変わる

- 提出物を提出したら、そのプラクティスは自動で「提出」になる。
- もし、そのプラクティスが提出物を提出する前に「着手」にはなっていなかったとしても、提出物を提出したら、そのプラクティスは自動で「提出」になる。
- 提出物が「WIP」状態だった場合は「提出」にならない。
- 今回の時点では、ユーザーが手動で「提出」に切り替える機能も残しておく。手動で変えられないようにするのは別Issueで。
- 提出物が「WIP」ではない状態から「WIP」に変更された場合、もし他のプラクティスで「着手」のものがあった場合は「未着手」に変更、「着手」のものがなかったら「着手」に変更するようにしたい。これを実装するにあたって何か問題があったら、ステータスは「提出」のままにする、にしたいと思います。

**Comment by yocajii** [comment]
@machida 
整理していただきありがとうございます！
このIssueでの対応範囲について、以下の通り承知いたしました🙆‍♂️

- バグの修正
- 仕様変更
  - 提出済みの状態からWIPに戻したとき、ステータスを「着手」または「未着手」に更新する

**Comment by machida** [comment]
@yocajii よろしくお願いしますー🙏

**Comment by yocajii** [comment]
本番環境で動作確認できましたので、クローズいたします。
