### ISSUE TITLE
[アドバイザーダッシュボード] アドバイザーのダッシュボードに同僚の現役生の一覧を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5215]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/168265/186811613-fcdab25c-ca41-46b3-b23a-8e88a4419978.png">

senpai でログインをする。

senpai は BatsBatsinc. という会社所属なので、

<img width="601" alt="image" src="https://user-images.githubusercontent.com/168265/186811870-1f6d0ed8-0c38-4980-a595-bb54e6e99417.png">

この部分に、

<img width="1137" alt="貼り付けた画像_2022_08_26_12_32" src="https://user-images.githubusercontent.com/168265/186811837-0158b041-ca09-4354-ae68-ce3cf39115fd.png">

senpai が所属している BatsBats inc. 所属の現役の研修生を全て表示したい。

ユーザーそれぞれに、以下の情報を表示したい。

<img width="637" alt="image" src="https://user-images.githubusercontent.com/168265/186812212-30bc8218-7ab6-4d4f-adb5-ecec6d5611a8.png">

デザインは machida がやるので、表示だけされていればOKです。

**Comment by yuma-matsui** [comment]
@machida 

> 現役の研修生を全て表示したい。

こちらは研修が終了したユーザーは**含めない**という認識で間違い無いでしょうか🤔?

***

- 含める場合
![image](https://user-images.githubusercontent.com/70259961/186895903-266edb8d-86a2-48b8-b25d-48bb13997a19.png)

- 含めない場合
![image](https://user-images.githubusercontent.com/70259961/186896043-f2d1b6b6-057c-42a9-98a0-174a158e4f10.png)

**Comment by machida** [comment]
@yuma-matsui はいー、研修が終了したユーザーは含めない、でお願いします

**Comment by yuma-matsui** [comment]
@machida 
かしこまりました！！
ありがとうございます😁

**Comment by yuma-matsui** [comment]
@machida 
お疲れ様です！
本番環境での動作検証をお願いいたします。
アドバイザー権限でのログインが必要なためです！

お手数をおかけしますがよろしくお願いいたします🙏

**Comment by yuma-matsui** [comment]
@machida 
ご確認いただきありがとうございました！
issueをクローズいたします。
