### ISSUE TITLE
提出物個別ページ、相談部屋個別ページのサイドカラムにある日報一覧にあるユーザーアイコンを非表示にしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5224]
関連Issue: https://github.com/fjordllc/bootcamp/issues/4628

提出物個別ページ
相談部屋個別ページ

それぞれにメンター・管理者しか見れないサイドカラムに、そのユーザーの日報一覧があります。
その日報一覧のユーザーアイコンを非表示にお願いします。

関連Issue のものも含めて、このIssueでコードを共通化していただきたいです。

**Comment by machida** [comment]
@taka110-IT はい！それでお願いします。やりたいことは、それが表示される URL で見た目を変えるのではなく、呼び出すときの呼び出す方法で見た目を指定するようにする、に変えていただきたいです。細かいところはお任せしますー。

**Comment by taka110-IT** [comment]
@machida 
承知しました。ありがとうございます😊

**Comment by taka110-IT** [comment]
本番環境で確認ができましたのでIssueをCloseします。
