### ISSUE TITLE
提出物一覧（メンターログイン時）のページャーがページャー１の場合機能しない問題を解決したい

### ISSUE THREAD

**Issue by ai-24** [fjordllc/bootcamp#5229]
## 概要

提出物一覧（メンターログイン時）のページャーがページャー１から２など他に遷移した後に、１に戻るとURLが変わらない問題を解決したい。

[![Image from Gyazo](https://i.gyazo.com/81ed770fd7155678f986c2a61e23a7d0.gif)](https://gyazo.com/81ed770fd7155678f986c2a61e23a7d0)

**Comment by ai-24** [comment]
@komagata さん
実装方法のご相談をさせていただきます。

ブートキャンプで使用されているページャーのURLの表示方法は様々のようですが、こちらのIssueで実装する際「pager=1の場合はpagerパラメーター自体が消える」実装方法が良いかと思うのですが、こちらでよろしいでしょうか。

**Comment by komagata** [comment]
@ai-24 そうですね〜、特に大変とかでなければ「pageパラメーター自体が消える」でお願いしたいです〜。

**Comment by ai-24** [comment]
@komagata 
かしこまりました！

**Comment by ai-24** [comment]
@komagata 
２点質問させてください。

- こちらはバグ修正のIssueとなりますが、テストは書いた方がよろしいでしょうか。
- 実装が完成したのですが、気になっていた`onpopstate`は触らなくてもやりたいことが出来ている状況なのですが、この部分についてもこちらのIssueで対応した方がよろしいでしょうか。

**Comment by komagata** [comment]
@ai-24 

> こちらはバグ修正のIssueとなりますが、テストは書いた方がよろしいでしょうか。

テストも欲しいですね！

> 実装が完成したのですが、気になっていたonpopstateは触らなくてもやりたいことが出来ている状況です。この部分についてもこちらのIssueで対応した方がよろしいでしょうか。

この部分と関係なければこのIssueで対応しなくて大丈夫です〜

**Comment by ai-24** [comment]
@komagata 
ご返信ありがとうございます🙏
２点かしこまりました！

**Comment by ai-24** [comment]
@komagata さん @machida さん
こちらのIssueの動作確認を本番環境でお願いできますでしょうか🙏

**Comment by komagata** [comment]
@ai-24 本番環境で動作することを確認しました。

**Comment by ai-24** [comment]
@komagata さん
ありがとうございます！

では確認できましたのでクローズします。
