### ISSUE TITLE
アイコン付きメンションで、アイコンが付かないユーザーがいる

### ISSUE THREAD

**Issue by kei-kmj** [fjordllc/bootcamp#5241]
## 概要

アイコン付きメンションをしようとしても、アイコンが付かないユーザーがいます

## 再現手順

1. mentormentaroまたは管理者でログインし、mentormentaroのプロフィール画面でユーザーアイコンを設定する
2. mentormentaro以外でログインし、お知らせ、日報、コメント等を開き、アイコン付きメンションする
3. mentormentaroへのアイコン付きメンションにアイコンが付かない

## 期待される振る舞い
アイコンが表示されて欲しい

## スクリーンショット
- ユーザーアイコンは設定されている
<img width="518" alt="2022-07-20 (19)" src="https://user-images.githubusercontent.com/82737807/179930941-491959f7-9de1-4b29-83e2-2c6260aec431.png">

- アイコン付きメンションにアイコンがつかない
<img width="654" alt="2022-07-20 (17)" src="https://user-images.githubusercontent.com/82737807/179926513-6625aa3f-f1f8-4693-94dc-3949bc1fc9cf.png">

## 関連Issue
機能導入時のissue 
- #2427

**Comment by lanactindi** [comment]
確認できましたのでcloseします。
