### ISSUE TITLE
[FBC] メール通知のサブジェクトの変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5244]
現在、フィヨルドブートキャンプから届くメールのサブジェクトの頭に、[bootcamp] もしくは [Bootcamp] という文字が入っている。

これを [FBC] に変更する。
 [FBC] の後には半角スペースを入れる（すでに入っているが、念のため確認）。

例:

`[FBC] komagataさんから回答がありました。`

**Comment by daiki0381** [comment]
こちら問題無かったので、Closeします。
