### ISSUE TITLE
[FBC] ログインしないと見れないページのタイトルを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5245]
`<title>提出物 | FJORD BOOT CAMP（フィヨルドブートキャンプ）</title>`

現在のタイトルタグは例えば上記のように ` | FJORD BOOT CAMP（フィヨルドブートキャンプ）` が入っている。

ログインしなくても見れるページ（トップページ、FAQ、newとeditを除くブログのページなど）はこのまま変更無しで、それ以外のログインしないと見れないページのタイトルを変更したい。

## 変更内容

ログインしないと見れないページは、

` | FJORD BOOT CAMP（フィヨルドブートキャンプ）`

の部分を

` | FBC`

に変更したい。

**Comment by machida** [comment]
meta-tags という gem を使って title タグを表示しています。
https://github.com/kpumuk/meta-tags
こちらを見ながらこのIssueに挑んでくださいー

**Comment by daiki0381** [comment]
こちら問題無かったので、Closeします。
