### ISSUE TITLE
ページのタイトルを省略せずに全部載せてほしい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5258]
どういうルールかわからないが、現状のブートキャンプアプリではhead/titleのタイトルが不思議な場所で省略されている。

https://bootcamp.fjord.jp/products/13197
※画面上部の「プロトタイプチェーン」と、メインコンテナの「プロトタイプチェーンの提出物」があるが、どちらもh1タグでかつ後者の方が文字が大きいので、head/titleも後者になるのが自然な気がする
<img width="689" alt="2" src="https://user-images.githubusercontent.com/1148320/180629370-9539f2a3-adad-40d4-868e-3e4dc14f6f4d.png">

https://bootcamp.fjord.jp/practices/17
<img width="764" alt="Screen Shot 2022-07-24 at 11 13 17" src="https://user-images.githubusercontent.com/1148320/180629393-74438d90-f395-43b4-885d-6bdc0b3af702.png">

https://bootcamp.fjord.jp/questions/1356
<img width="1159" alt="1" src="https://user-images.githubusercontent.com/1148320/180629403-d40ca5b5-b3b1-447c-8953-50b3c2795fc6.png">

何か特別な理由がなければ、省略せずに全部載せてほしい。

## Why?
Chrome extensionなどを使ってMarkdownリンクを作るときに、おかしなリンクテキストになるため。

例 [バックグラウンドでジョブを実行したにも関わらずフォアグラウンド実行時の挙動を \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/questions/1356)

**Comment by machida** [comment]
📝 
- https://github.com/fjordllc/bootcamp/issues/5245 このIssueの後に着手。
- meta-tags が文字数の制限を付けているっぽいので、https://github.com/kpumuk/meta-tags を確認。
- FBCの表記より、titleの文字を優先して表示させるようにする（meta-tags の仕様上問題があったら相談）

**Comment by komagata** [comment]
@JunichiIto (CC: @machida ) gemのmeta-tagsのデフォルト設定のようです。僕はmeta-tagsのデフォルトでいいんじゃないかな〜と思いました。

**Comment by JunichiIto** [comment]
@komagata うーん、でもそれだと僕の問題は解決しないので、「デフォルトだと困る」という返事になってしまいますね。

**Comment by JunichiIto** [comment]
https://github.com/fjordllc/bootcamp/pull/5581 がマージされたのでこちらはクローズします。
Thank you @cafedomancer !
