### ISSUE TITLE
GitHubの草表示が途中で切れている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5269]
下記のページで発生。もしかしたら最近入ったローディング表示が関係しているのかもです。

https://bootcamp.fjord.jp/users/1544

<img width="646" alt="スクリーンショット 2022-07-26 3 01 02" src="https://user-images.githubusercontent.com/16577/180843866-101b2651-c972-452e-b5ac-af2ad4f2dbd4.png">

**Comment by tomonariha** [comment]
参考として、ローディング処理はこちらのPRで実装しました。
[ダッシュボードのGithubの草にローディング中の表示がされるようにした#5218](https://github.com/fjordllc/bootcamp/pull/5218)
本番環境へのリリースは2022年7月21日です。https://github.com/fjordllc/bootcamp/pull/5232
もし不具合の原因になっていたら申し訳ないです🙇‍♂️

**Comment by machida** [comment]
@tomonariha @komagata すいません、こちら僕の変更のせいでした🙇‍♂️ 修正しましたー

**Comment by komagata** [comment]
@machida すみません、ありがとうございます！
