### ISSUE TITLE
ダッシュボード 自分の日報ページの title タグ変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5273]
現在
<img width="412" alt="image" src="https://user-images.githubusercontent.com/168265/181173531-e7e927db-761f-4584-92f6-5435846196e5.png">

こうしたい
<img width="475" alt="image" src="https://user-images.githubusercontent.com/168265/181173768-f0591a57-f1ff-4915-bd9e-f2e9b9b3c051.png">

こちらの Issue の PR がマージされるかもです。
https://github.com/fjordllc/bootcamp/issues/5245
マージされると、FJORD BOOT CAMP（フィヨルドブートキャンプ） が FBC  になります。

**Comment by keiz1213** [comment]
本番環境で動作確認ができたのでcloseします。
