### ISSUE TITLE
ユーザー一覧の titleタグとページタイトルを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5274]
http://localhost:3000/users

このページでやることが2つあります。

## 1

ユーザー一覧 を ユーザー に変更。

<img width="347" alt="貼り付けた画像_2022_07_27_15_13" src="https://user-images.githubusercontent.com/168265/181174496-2c42974e-97ff-42e2-805c-d3ac5301da13.png">

## 2

titleタグを変更。

現在

<img width="428" alt="image" src="https://user-images.githubusercontent.com/168265/181174624-9a21f169-67c2-4b09-b7de-305434416bc6.png">

こうしたい

<img width="425" alt="image" src="https://user-images.githubusercontent.com/168265/181174757-73cc9ef4-3323-4cd4-b8bb-16c103b2353d.png">

**Comment by keiz1213** [comment]
本番環境で確認できたのでcloseします。
