### ISSUE TITLE
コメントが多い場合の読み込み方法の仕様変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5276]
現在、

コメントが9個以上あった場合、最新の8個だけが表示され、

<img width="738" alt="image" src="https://user-images.githubusercontent.com/168265/182527950-1b0822a7-c9ee-4128-b8a6-f694125bcf32.png">

「もっと見る」をクリックすると、全てのコメントが表示される。
これは、スマホのときに一度にたくさんのコメントを表示しようとするとブラウザがエラーを出してしまうための対策。

ここで仕様変更。

> 「もっと見る」をクリックすると、全てのコメントが表示される。

だと、コメントが30個くらいあった場合、「もっと見る」をクリックすると、次に22個のコメントを表示しようとするのでエラーが出てしまう。

そうならないように、もっと見るをクリックしたら、その次の8件だけを表示し、さらに「もっと見る」をクリックすると、さらに次の8件を表示...と8件ずつ表示するようにしたい。

**Comment by komagata** [comment]
:memo: GitHubのコメント表示を参考にしてほしいです〜。

**Comment by kei-kmj** [comment]
<<Draft>>

コメント数の表示部分の仕様について確認させてください🙏

<img width="413" alt="コメント" src="https://user-images.githubusercontent.com/82737807/183552552-43f386a0-1967-4090-89c1-6789ad1a68d6.png">

- 前提
コメントは全部で22あり、今、最初の8個が表示されている

- 質問
この時、`コメント(?)をもっと見る`の部分はどう表示すべきか
- 選択肢と考えたこと
  - A. `コメント(14)をもっと見る`
  このボタンを押しても、コメントが14中8しか表示されないことが分かり難いか
  - B. `コメント(8)をもっと見る`
  コメントが8個しか無さそう
  - C. `コメントをもっと見る`
  - D. `次のコメント(8) を見る`
  Githubに一番近いのはこれかも
- 参考情報
前回のMTGで、Githubに寄せた実装をするというお話だったので、Githubを確認してみました。
Githubは、データを間引いて隠しているようなので、

**Comment by machida** [comment]
@kei-kmj 確認ありがとうございます！

`次のコメント(8 / 14)`

このようにお願いしたいです。
分母は残りの合計数、8は次に表示される数。

残りが8以下の場合は、
`次のコメント(8)` や `次のコメント(4)` のように、分母は無しで表示したいです。

**Comment by kei-kmj** [comment]
@machida 
回答ありがとうございます。

すみませんが、更に確認させてください🙏
`をもっと見る`無しで、`次のコメント()`にするということで良いでしょうか？

そうすると、
- 括弧が全角の時：リンクの下線が右にはみ出しているように見える
![image](https://user-images.githubusercontent.com/82737807/183654371-52faa903-4a8b-4e1b-931c-5fa04a47269f.png)

- 括弧が半角の時：リンクの下線が途切れ途切れに見える
![image](https://user-images.githubusercontent.com/82737807/183654406-1828f984-0727-47ae-b523-45857ebefbc1.png)

となるのですが、どちらにすべきでしょうか？それともCSSで解決できるのでしょうか？

**Comment by machida** [comment]
@kei-kmj 

もっと見るは今回の変更から無しでお願いします。

カッコは全角でお願いします。
全角カッコに特殊なフォントを使ってるのですが、keiさんの開発環境でうまく動いてないっぽいです。こちらは別Issueで調べるようにしますー。

**Comment by kei-kmj** [comment]
本番環境で動作確認できたのでcloseします

@machida 
本番環境でもリンクの下線が右にはみ出しているようように見えるので、一応報告します。
![image](https://user-images.githubusercontent.com/82737807/185526603-28082a00-5cb2-46c7-a162-eca3f8257364.png)
