### ISSUE TITLE
学習のステータス「完了」を「修了」に変更したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5281]
<img width="419" alt="貼り付けた画像_2022_07_28_11_36" src="https://user-images.githubusercontent.com/168265/181408035-efcb942c-e7c4-4449-8b03-a2c7408a5a32.png">

修了 Tweet と表記ゆれをなくすために、完了を修了に変更する。

ここ以外にもダッシュボードのこれなど、

<img width="706" alt="貼り付けた画像_2022_07_28_11_37" src="https://user-images.githubusercontent.com/168265/181408186-7d26c372-413c-41ba-b810-fb9c058a65cd.png">

一通り検索して変更をする。

**Comment by keiz1213** [comment]
@komagata  @machida 


### 本番環境での動作確認のお願い
お疲れさまです！
今回のリリースでプラクティス作成フォームのラベルが変更になりました。本番環境での確認をお願いいたします。
![名称未設定_key](https://user-images.githubusercontent.com/72614612/183292527-ecd07d53-632e-47f4-a1ac-bfebc7f2da79.png)

### 一点質問があります
今回のリリースでwelcomeページに変更を加えました。こちらの本番環境での確認はどうすればよろしいでしょうか？
![名称未設定_key](https://user-images.githubusercontent.com/72614612/183291797-37a1febb-ebd9-449a-9d4c-da52ba3cd2c3.png)

**Comment by komagata** [comment]
@keiz1213 前者については本番環境で確認致しました。
後者については確認できないので確認しなくて大丈夫です〜。

**Comment by keiz1213** [comment]
@komagata 
わかりました。ありがとうございました！

**Comment by keiz1213** [comment]
本番環境で確認できましたのでcloseします。
