### ISSUE TITLE
ユーザー情報に関連書籍を登録できるようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5287]
https://github.com/fjordllc/bootcamp/pull/5300
このブランチに向けてPRを送る。

---

管理者・メンターでログインをして、プラクティス個別ページの下にあるリンクから編集画面に行く。

<img width="984" alt="貼り付けた画像_2022_08_28_5_25" src="https://user-images.githubusercontent.com/168265/187046848-dcfa5055-78fc-42e1-828a-95a71f7c6a18.png">

参考書籍という項目がある。

<img width="391" alt="image" src="https://user-images.githubusercontent.com/168265/187046863-7a510642-0d10-4302-8fd4-7c02096de86b.png">

この UI を真似て、関わった書籍という項目をユーザー情報に追加する。ポイントは、書籍を追加をクリックすると、入力ボックスが増えていくところ。細かいデザインはmachidaがやります。

こういう UI になっている。

<img width="1542" alt="image" src="https://user-images.githubusercontent.com/168265/187046891-c481a494-983d-4985-bb13-ad00748d2de1.png">

ユーザー情報の関わった書籍の入力項目は上記とは違って、以下のようにしたい。

<img width="502" alt="貼り付けた画像_2022_08_28_5_29" src="https://user-images.githubusercontent.com/168265/187046995-a5739ae9-8119-4536-b25a-040bdbbe0e03.png">

表紙画像のアップロードのパーツは以下のページを参考にする。
http://localhost:3000/books/new

今回はメンターの場合だけユーザー情報編集ページに関わった書籍の項目を表示するようにする（将来はアドバイザーや一般ユーザーにも表示するかも？）。

登録した書籍は、welcomeページのメンター一覧に表示されるようにする。

**Comment by machida** [comment]
@daiki0381 明日中にこのIssueの詳細を書きます🙇‍♂️

**Comment by machida** [comment]
@daiki0381 お待たせしました🙇‍♂️ この Issue の説明に仕様を書きました。

**Comment by daiki0381** [comment]
@machida ありがとうございます🙏
