### ISSUE TITLE
提出物を確認済みにすると「日報を確認済みにしました」と表示される

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5293]
トーストのメッセージがおかしいです。

https://bootcamp.fjord.jp/products/13359 を確認済みにしたときのスクショ

<img width="1053" alt="Screen Shot 2022-07-30 at 13 37 38" src="https://user-images.githubusercontent.com/1148320/181872644-bf45529d-df1a-4709-979b-81db6b89ad58.png">

**Comment by lanactindi** [comment]
確認できたのでcloseします！
