### ISSUE TITLE
[コース]【メンター向け】企業向けコースの内容を確認したい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5302]
現状、メンター権限でコース一覧ページを開くと、何もデータが表示されない（Railsプログラマーコースすら表示されないのはもしかしてバグ？？）。

https://bootcamp.fjord.jp/courses
<img width="699" alt="Screen Shot 2022-08-01 at 10 05 35" src="https://user-images.githubusercontent.com/1148320/182054079-fbf05f01-a326-4f84-a350-97537949aa17.png">

企業研修で「Railsプログラマーコース」以外のコースを受講している場合は、メンターとしてその生徒さんがどんな順番でプラクティスを進めてきたのか確認したくても確認することができない。

よってメンター権限があれば、企業向けコースであっても一覧や詳細を確認できるようにしたい。

さらにいえば、ユーザー詳細ページの「コース」にもリンクが付いていると嬉しい。（これは受講生とメンターでリンクのあり・なしを切り替える必要が出てくるので面倒か？）
https://bootcamp.fjord.jp/users/1548
<img width="616" alt="Screen Shot 2022-08-01 at 10 08 03" src="https://user-images.githubusercontent.com/1148320/182054217-6747a01e-3224-43f7-924b-b353ac16805e.png">

**Comment by machida** [comment]
📝 
現在、非公開のプラクティスは管理者しか見れなくなっているので、メンターも見れるようにする。

**Comment by daiki0381** [comment]
@komagata @machida 
お疲れ様です。こちらメンターアカウントの修正なので本番環境のご確認をお願いしたいです🙏

【確認事項】

- 管理者権限のないメンターでログインする。http://localhost:3000/courses にアクセスし、非公開のコースが見れることを確認する。

**Comment by komagata** [comment]
@daiki0381 本番環境で動作することを確認しました。

**Comment by daiki0381** [comment]
@komagata ありがとうございます🙇‍♂️ こちらcloseさせて頂きます。

**Comment by JunichiIto** [comment]
@daiki0381 対応ありがとうございました！😄
