### ISSUE TITLE
提出物個別ページのメンター用サイドカラムに提出物一覧を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5309]
メンターでログインして提出物個別ページにアクセスしたときに表示されるサイドカラムに提出物一覧も表示したい。

<img width="1476" alt="貼り付けた画像_2022_08_03_13_28" src="https://user-images.githubusercontent.com/168265/182524313-3529beef-e329-4dd5-b30e-1dee4925be76.png">

サイドカラムの提出物一覧は、日報個別ページのサイドカラムには表示されているので、それを参考にしてみてください。

**Comment by keiz1213** [comment]
@machida 
お疲れさまです！
現在こちらのissueに取り組んでいて、ほぼ実装は終わったのですが2点質問があります。

## ブラウザの幅を狭めると一部デザインが崩れてしまう
現状、ブラウザの幅が一定以上あるとデザインは崩れないのですが、ある程度狭めると一部デザインが崩れてしまいます。
こちらは自分で触らず町田さんにお願いしたほうがよろしいでしょうか？
### 一定以上ブラウザの幅がある
![_development__OS_X_Mountain_Lionをクリーンインストールする___FBC](https://user-images.githubusercontent.com/72614612/184294669-666f2a3f-7ee6-4057-b472-d42d7fc46010.png)
### ブラウザの幅を狭めるとデザインが崩れる
![_development__OS_X_Mountain_Lionをクリーンインストールする___FBC](https://user-images.githubusercontent.com/72614612/184294819-43ee645e-2397-4efb-bad9-a8cf027ebd56.png)



## 「提出物はまだありません」の文言について
日報個別ページの`提出物`タブを参考に今回の実装を行いました。日報個別ページではそのユーザーの提出物がゼロの場合は条件分岐で「提出物はまだありません」が表示されます。
```slim
// app/views/reports/show.html.slim


.card-list.a-card
  - if @products.present?
    - @products.each do |product|
      = render partial: 'product', locals: { product: product }
  - else
    .card-list__message
      .container
        .o-empty-message
          .o-empty-message__icon
            i.fa-regular.fa-sad-tear
          .o-empty-message__text
              | 提出物はまだありません。
```

今回のissueでは提出物個別ページにすでにアクセスしているので提出物がゼロの場合はありえないと思うので提出物がゼロの場合を考慮しないように実装しようと思いますがよろしいでしょうか？

```slim
// app/views/products/show.html.slim

.card-list.a-card
  - @products.each do |product|
    = render partial: 'product', locals: { product: product }
```

以上の2点よろしくおねがいします。

**Comment by machida** [comment]
> ブラウザの幅を狭めると一部デザインが崩れてしまう

おお、これは厄介ですね。僕の方で対応しておきますー

> 「提出物はまだありません」の文言について

確かに、このページでは0はありえないですね。考慮しなくて大丈夫ですー🙆‍♂️

**Comment by machida** [comment]
@keiz1213 
本番で確認しましたー🙆‍♂️
