### ISSUE TITLE
[コース]ユーザー個別ページのコースにコース詳細へのリンクを貼ってほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5310]
ユーザー個別ページの、

<img width="644" alt="貼り付けた画像_2022_08_03_13_33" src="https://user-images.githubusercontent.com/168265/182524715-4f4fbe3b-8c67-487d-83e4-eb09b5bf9f47.png">

これをリンクにする。

リンク先は、
http://localhost:3000/courses/XXXXXX/practices
というそのコースのプラクティス一覧。
target blank を付けて別タブで開くようにする。

**Comment by daiki0381** [comment]
こちら問題無かったので、Closeします。
