### ISSUE TITLE
[コース]カテゴリー個別ページを作成し、カテゴリーの管理ページからリンクを貼りたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5311]
管理者でログインし、
http://localhost:3000/admin/categories
ここにアクセスすると、プラクティスのカテゴリー一覧ページが表示される。

現在、それぞれのカテゴリーはどのプラクティスを持っているかが確認できない。
なので、カテゴリー個別ページを作成し、そのページで確認できるようにしたい。

---

ここをリンクにする。

<img width="1115" alt="貼り付けた画像_2022_08_03_13_48" src="https://user-images.githubusercontent.com/168265/182526384-5cdee201-af4b-43a9-b880-412d9ff1f817.png">

リンク先（show）には、

- カテゴリー名
- カテゴリースラッグ
- カテゴリー説明（詳細）
- そのカテゴリーに紐付いているプラクティスの一覧

を表示したい。

**Comment by yocajii** [comment]
@machida @komagata 
3点質問させてください。

### viewについて

管理ページはVueコンポーネントが使われているページと、slimのみでできているページがあるようでした。
今回のカテゴリー個別ページは、どちらで作成するべきでしょうか？
また、その理由というか方針があれば伺いたいです。

### 編集ページへのリンクについて

管理者の方がこのページを見る時、カテゴリーに属するプラクティスの情報を確認するだけで終わると考えて良いでしょうか？
もし次のアクションとして編集が来るのであれば、カテゴリー編集ページへのリンクと各プラクティスの編集ページへのリンクがあると、使いやすそうだと思いました。

### 見た目について

ひとまず必要なデータは表示できましたが、町田さんにデザインをお願いする時点でスクショのような状態で良いのでしょうか？
もしカテゴリーの情報を表示するにあたって見た目の参考にできそうな既存ページがありましたら教えていただけますか🙏
![image](https://user-images.githubusercontent.com/33394676/183289972-9078d94b-3f2f-4a9c-8ea0-efd098f34431.png)

**Comment by komagata** [comment]
@yocajii 

> viewについて

slimで大丈夫です〜

> 編集ページへのリンクについて
> 見た目について

@machida こちらいかがでしょう〜？

**Comment by machida** [comment]
@yocajii @komagata デザインは僕の方でやるので、また同時進行でレビューをお願いしますー

**Comment by yocajii** [comment]
@komagata 
ご回答ありがとうございます！
slimでOKとのこと、承知いたしました🙆‍♂️

@machida 
デザインと同時進行でレビューとのこと、承知いたしました🙆‍♂️
編集ページのリンクについては不要ということでよかったでしょうか？

> ### 編集ページへのリンクについて
> 管理者の方がこのページを見る時、カテゴリーに属するプラクティスの情報を確認するだけで終わると考えて良いでしょうか？  
もし次のアクションとして編集が来るのであれば、カテゴリー編集ページへのリンクと各プラクティスの編集ページへのリンクがあると、使いやすそうだと思いました。

**Comment by machida** [comment]
@yocajii あー、確かに、showには編集へのリンクも置いておきたいですー

**Comment by yocajii** [comment]
@machida 
ご回答ありがとうございます！承知いたしました👍

**Comment by yocajii** [comment]
本番環境での動作確認ができたため、クローズいたします。
