### ISSUE TITLE
コース編集の「詳細」を「説明」に変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5312]
管理者でログインし、
http://localhost:3000/admin/courses
ここにアクセス。

コースの編集ページへ。

<img width="931" alt="貼り付けた画像_2022_08_03_13_53" src="https://user-images.githubusercontent.com/168265/182526905-69be0824-0f9f-412f-9599-e4313e96db14.png">

詳細を説明に変更。

<img width="518" alt="貼り付けた画像_2022_08_03_13_53" src="https://user-images.githubusercontent.com/168265/182526983-b937e67d-fd21-4a2c-b893-135791bacd74.png">

**Comment by lanactindi** [comment]
@machida 　こちらもアドミンアカウントがないので本番で確認していただけないでしょうか？

**Comment by komagata** [comment]
@lanactindi 本番環境で確認しました。OKでした〜！
