### ISSUE TITLE
カテゴリー編集の「詳細」を「説明」に変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5313]
管理者でログインして、
http://localhost:3000/admin/categories
カテゴリー一覧にアクセス。

カテゴリー編集ページへ。
<img width="954" alt="貼り付けた画像_2022_08_03_13_57" src="https://user-images.githubusercontent.com/168265/182527377-7bbde5e4-59b5-41ed-a956-1dd63b2dc963.png">

<img width="376" alt="貼り付けた画像_2022_08_03_13_58" src="https://user-images.githubusercontent.com/168265/182527466-14f4cc6b-e75f-4b5e-99e3-c71c10776c59.png">

**Comment by lanactindi** [comment]
@machida 　遅くなってすみませんが、こちらはアドミンアカウントがないので本番で確認していただけないでしょうか？

**Comment by lanactindi** [comment]
確認できたのでcloseします！
