### ISSUE TITLE
レイアウト application にブログへのリンクを追加

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5317]
<img width="1356" alt="貼り付けた画像_2022_08_03_15_00" src="https://user-images.githubusercontent.com/168265/182535308-f20f7694-05ae-4186-82f6-0f57ecabe1f6.png">

ブログを追加。
URL は articles_path でお願いします。

**Comment by fuwa-syugyo** [comment]
本番環境で確認しましたのでcloseします。
