### ISSUE TITLE
みんなのブログが使えないのでどうにかしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#532]
みんなのブログをメニューから外して、まとめフィードのリンク・アイコンだけユーザー一覧に追加する。

**Comment by sanfrecce-osaka** [comment]
@komagata 
ウォッチ機能が追加されたらの話なのですが、ユーザーがウォッチ対象にしているユーザーのfeedだけ取得するようにしてはどうでしょうか？

**Comment by machida** [comment]
@sanfrecce-osaka @komagata 

feed は feedリーダーで見てもらうだけでいいかなー。
メンターやアドバイザーがブログを見るのは大事だけど、BootCampの人には、本当に仲がいい人とか、進んでる学習が自分と近くて気になってる、って場合以外では、BootCampの人のブログではなく、プロのエンジニアのブログを購読してほしいです。普段の購読までBootCampの中にばっかりいてアドバイスする隙を探したりするより、自分よりも遥かにできる人のものを購読して、もっと上を見て欲しいと個人的には思います。

**Comment by sanfrecce-osaka** [comment]
@machida 
おっしゃる通りだと思います。
ただ1点、誤解されているような気がするので補足すると、アドバイスする隙を探して先述の実装を提言したのではなく、単純にみんなのブログ機能をこうしたら使いやすいのではないかという思いからです。
ただ、実際にどう使われるのがBootcampの人の利益になるのかという観点までは考慮できていませんでした。
