### ISSUE TITLE
FirefoxでD&Dによる画像添付ができない

### ISSUE THREAD

**Issue by ksmxxxxxx** [fjordllc/bootcamp#5332]
## 概要

日報投稿画面において、D&Dによる画像添付ができないようです。

## 再現手順

1. `https://bootcamp.fjord.jp/reports/:id/edit
2. 「日報」の「内容」テキストエリアに画像（あるいはGIFアニメーション画像）を添付しようとD&D
3. 添付されず、ドラッグしたアイコンは元の位置に戻っていく……。

## 期待される振る舞い

Firefoxでも画像添付できてほしいです

## スクリーンショット

![Aug-06-2022 11-03-09](https://user-images.githubusercontent.com/5976902/183229384-2b3fee5b-28d6-4b9d-976f-07bd0c1199af.gif)

### OS
<img width="698" alt="macOS Monterey 12.4" src="https://user-images.githubusercontent.com/5976902/183229404-4177b1e5-22cd-45c5-9e90-4fd0d6f850dd.png">

### ブラウザ
<img width="799" alt="Firefox 103.0.1 (64 ビット)" src="https://user-images.githubusercontent.com/5976902/183229406-0ee5b7f2-e26c-43a9-809c-474946de4f75.png">

**Comment by siroemk** [comment]
@komagata 
こちらはnpm（[komagata/textarea\-markdown](https://github.com/komagata/textarea-markdown)）側の問題のようでしたので、npmにPRを出しています。
ご確認をお願いします🙆‍♀️　

https://github.com/komagata/textarea-markdown/pull/25

**Comment by komagata** [comment]
@siroemk あちらのリポジトリで取り込みました〜

**Comment by siroemk** [comment]
本番環境で確認できたのでcloseします！
