### ISSUE TITLE
Twitterに投稿しても画像が出ない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5354]
https://bootcamp.fjord.jp/ をツイートに含めても画像が出ないです。

https://twitter.com/jnchito/status/1557137447041253376 
<img width="601" alt="Screen Shot 2022-08-10 at 7 52 39" src="https://user-images.githubusercontent.com/1148320/183775517-b79a4715-c2f4-4e1d-b3c0-f884c07a6ac9.png">

https://cards-dev.twitter.com/validator で検証するとエラーが出てるのでこれが原因？

<img width="1010" alt="Screen Shot 2022-08-10 at 7 52 32" src="https://user-images.githubusercontent.com/1148320/183775540-2908da3f-ca1c-4359-9fa7-823d06656fa4.png">

**Comment by lanactindi** [comment]
@machida すみませんが、おそらくtwitter card validatorが動かないと思います。
<img width="1137" alt="Screen Shot 0004-08-26 at 21 03 33" src="https://user-images.githubusercontent.com/94335407/186899404-5f1f7470-cc76-4eec-9228-41cff34c37fc.png">
エラーがなくてもプレビューが表示されないです。
参考: https://twittercommunity.com/t/card-validator-preview-removal/175006
しかし、twitter本番で試してもいいですのでこのプレビューはいかがでしょうか？
<img width="614" alt="Screen Shot 0004-08-26 at 21 06 09" src="https://user-images.githubusercontent.com/94335407/186899811-f031f839-1dc7-4daa-bb53-c182edb77d95.png">
og:title、twitter:title、twitter:text:titleの価値は何がいいのでしょうか？
私は全て「FJORD BOOT CAMP（フィヨルドブートキャンプ）」を設定しましたが、不安なので確認していただきたいです。

**Comment by machida** [comment]
@lanactindi 
コードを見ながらやり取りができるように、
https://github.com/fjordllc/bootcamp/pull/5434
PRのコメントでやり取りをさせていただきますー

**Comment by lanactindi** [comment]
@machida すみませんが、水曜日に相談したog:titleの値は何の件ですが、なかなか元のog:titleの値を見つけないので @JunichiIto さんに聞いても大丈夫でしょうか？
それとも、このままでリリースするのでしょうか？
https://twitter.com/LHongLn1/status/1563860067354820608?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1563860067354820608%7Ctwgr%5E36f94a793a181ba30000f3b57a81dcfd83d6ab32%7Ctwcon%5Es1_c10&ref_url=https%3A%2F%2Fpublish.twitter.com%2F%3Fquery%3Dhttps3A2F2Ftwitter.com2FLHongLn12Fstatus2F1563860067354820608widget%3DTweet
ご確認よろしくお願いいたします。

**Comment by machida** [comment]
@lanactindi 
viewファイルにそれぞれ titleの値が設定されていて、それがない場合はデフォルトの値が表示されるようになっています。このデフォルトを表示する機能が動いていないため、Twitterカードが表示されない場合があるのだと思います。機能については @komagata さんに質問をお願いします。

**Comment by komagata** [comment]
@lanactindi meta-tagsのコードも参考にして調べてみてください〜

**Comment by lanactindi** [comment]
@machida 町田さん、おそらく元々:titleの値はページのタイトルだと思います。
なぜなら、https://og.nullnull.dev/　このChrome拡張を使って、URLをコピーしてTwitter本番で試したらこういうなhttps://twitter.com/LHongLn1/status/1573426647243829248 tweetが表示されました。
例えば、ブートキャンプの日報ページだとしたら、:titleの値は「日報」です。
ダッシュボードページの場合、もちろん:titleの値は「ダッシュボード」ですね。
なぜこのChrome拡張を使ったらそんな値が表示されるのかちょっとよくわからないが、元々はそういうな値が設定されたですか？ご確認お願いします。

**Comment by komagata** [comment]
@lanactindi 

> おそらく元々:titleの値はページのタイトルだと思います。

この動作をmeta-tagsの実装（ソースコード）を調べて確かめてください。勘ではなく、実装をしっかり調べて動作がどうなっているか調査をお願いします。

**Comment by lanactindi** [comment]
<img width="615" alt="Screen Shot 0004-10-24 at 15 58 43" src="https://user-images.githubusercontent.com/94335407/197466044-c2b63a14-350e-4139-aa8b-7fc85450c4ac.png">
確認させて頂いたのでcloseします！
