### ISSUE TITLE
【メンター向け】メンターが未アサインの提出物にコメントした際、担当者になったことをToastでわかりやすく通知する

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5355]
関連issue

- [【メンター向け】メンターが未アサインの提出物にコメントしたら、担当者になったことを画面上に反映する · Issue \#4469 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/4469)
- [メンターが未アサインの提出物にコメントしたら、担当者になったことを画面上に反映するようにした by eatplaynap · Pull Request \#4518 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4518)

未アサインの提出物にコメントすると、「コメントを投稿しました！」のToastしか表示されないので、担当者になったことがわかりづらいです。
（もしかすると「担当になりました」が一瞬出ているのかもしれないが、ほとんど気づけないレベル）

Toast上でもわかりやすく表示してもらえると嬉しいです。

**Comment by lanactindi** [comment]
@machida すみません、ちょっと聞きたいことがあります。
わかりやすいため、同時に両方二つのToastを表示したほうが良いかなと思いますが、いかがでしょうか？
同時に表示するということは上に「コメントを投稿しました！」
下は「担当になりました」ということですが、いかがでしょうか？
ご確認よろしくお願いします。

**Comment by machida** [comment]
@lanactindi 二つのtoastを表示することが可能でしたら、そのようにしていただきたいです🙏

**Comment by lanactindi** [comment]
すみません、おそらく両方表示することができないので「コメントを投稿ました！」が表示された後「担当になりました。」が表示されるように対応しましたが、大丈夫でしょうか。
参考: https://github.com/sweetalert2/sweetalert2/issues/606

**Comment by machida** [comment]
@lanactindi なるほど、両方を表示させることができない場合は、[担当になりました]だけが表示されるようにしていただきたいですー🙏

**Comment by lanactindi** [comment]
@machida 町田さん、私はアドミン権限がないので本番で確認していただいてもよろしいでしょうか。

**Comment by machida** [comment]
@lanactindi こちら本番で確認できましたー🙆‍♂️

**Comment by lanactindi** [comment]
@machida 町田さん、ありがとうございました。closeします！
