### ISSUE TITLE
お試し期間の開始・終了日付とお試し期間が連動してしまっている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5359]
"お試し期間"が"キャンペーン期間"の意味になってしまっている。

"お試し期間"は「料金が無料になる期間が何日間なのか」の意味であって、「キャンペーン実施期間」の意味ではない。
しかし、現在は前者の意味になっていてそれを強制するValidationがかかってしまっている。

基本的には"お試し期間"は7日でほぼ固定。
例えば、"お試し期間"が7日で、"キャンペーン実施期間"は1年ということもあり得るにもかかわらず、終了日時にお試し期間と連動したValidationがかかっている。

## どういう状態が正しいか

終了日時は現在、"開始日時 + お試し期間"より前の日時は設定できないようになっているが、そのValidationは削除する。
（終了日を開始日より前に設定できないというValidationはあってもいい）

<img width="743" alt="スクリーンショット 2022-08-11 10 34 09" src="https://user-images.githubusercontent.com/16577/184050313-4f586dbf-81ae-4cf6-a215-a7e32053b4a2.png">

**Comment by lanactindi** [comment]
@komagata すみません、本番でこちらを確認していただいてもよろしいでしょうか。アドミン権限がないので申しわけありません。

**Comment by komagata** [comment]
@lanactindi 本番環境で動作することを確認しました。

**Comment by lanactindi** [comment]
> @lanactindi 本番環境で動作することを確認しました。

@komagata 遅くなって申し訳ありません。コメントありがとうございました。
closeします。
