### ISSUE TITLE
【メンター向け】日報や提出物をコメント欄から確認OKにした際、Toastが「コメントを投稿しました！」になるのが違和感

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5364]
日報や提出物はコメント欄から確認OKにできるが、このときのToastの通知が「コメントを投稿しました！」になっています。
たしかに、アクションとしては「コメントを投稿し、確認OKにした」なので、嘘ではないのですが、情報としては「確認OKにした」の方が重要なので、こっちがToastに出てる方がしっくりくる気がします。

<img width="840" alt="Screen Shot 2022-08-12 at 8 19 33" src="https://user-images.githubusercontent.com/1148320/184258620-33f71f1e-f363-4fc6-a957-bf172c063a2e.png">

<img width="1274" alt="screen" src="https://user-images.githubusercontent.com/1148320/184259242-d9b77175-c8af-49c0-95d5-815abc32c517.png">

とはいえ、主観の問題なので、どっちのメッセージにすべきかは要検討かもしれません。

関連issue

- [【メンター向け】メンターが未アサインの提出物にコメントした際、担当者になったことをToastでわかりやすく通知する · Issue \#5355 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/5355)

**Comment by machida** [comment]
📝コメントを投稿と確認OKを同時にした場合は、確認OKの方のメッセージを表示する

**Comment by yuma-matsui** [comment]
@machida 
一点確認をさせていただきたいです！


> 📝コメントを投稿と確認OKを同時にした場合は、確認OKの方のメッセージを表示する

こちらについてローカルで動かしてみたところ、
コメントの投稿と確認OKを同時にする方法が分からなかったです😥

下記変更が期待されていると認識しているのですが、間違い無いでしょうか。

## 現状の挙動
![image](https://user-images.githubusercontent.com/70259961/187059102-2c0a011a-3d96-4d87-8508-12c09ed3d71c.png)


## 変更後に期待される挙動
![image](https://user-images.githubusercontent.com/70259961/187059227-3c9d490a-dd9e-4cd7-9a34-7359609bd67f.png)

**Comment by machida** [comment]
@yuma-matsui 

コメントの投稿と確認OKを同時にする方法
とは、コメントの投稿ボタンにある確認OKボタンを押すことです。認識合ってます🙆‍♂️それでお願いしますー

**Comment by yuma-matsui** [comment]
@machida 
早速ありがとうございます。
やっぱりテクストのコミュニケーションは確認が大切だと実感しました〜😅
こちら対応します！！

**Comment by yuma-matsui** [comment]
@machida 
お疲れ様です！！
こちらの本番環境での動作確認をお願いいたします。

**Comment by komagata** [comment]
@yuma-matsui 本番環境で動作することを確認しました。

**Comment by yuma-matsui** [comment]
@komagata 
ご確認いただきありがとうございました。
クローズいたします。
