### ISSUE TITLE
【メンター向け】退会の通知メールに選択入力の退会理由も載せる

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5365]
退会の通知メールは自由記入の退会理由だけ掲載されるが、この理由が未入力だと「退会しました」だけの通知になってしまう。　

<img width="626" alt="screen" src="https://user-images.githubusercontent.com/1148320/184274622-31b9376c-2641-416a-bf6e-5de0c2116ca1.png">

メンターとしてはなんで退会しちゃったのかな？という理由が気になるので、選択入力の退会理由が選択されていれば、それも掲載してもらうと嬉しい。

**Comment by lanactindi** [comment]
@JunichiIto @machida すみません、デザインの方はこちらの画像みたいでいかがでしょうか。
先に町田さんにデザインお願いしなかったすみませんでした。勝手に設計しました。
ご確認よろしくお願いします。
![image](https://user-images.githubusercontent.com/94335407/185741743-207ce29b-7c5b-4c63-9128-b9c616e87171.png)

**Comment by machida** [comment]
@lanactindi デザインありがとうございます。デザイン確認しますね。

**Comment by lanactindi** [comment]
@machida ありがとうございます。よろしくお願いします。

**Comment by lanactindi** [comment]
@machida 町田さん、ご確認お願いします。:bowing_man:

**Comment by lanactindi** [comment]
@machida 町田さん、お疲れ様です。
本番でアドミン権限がないのでこちらもご確認していただいてもよろしいでしょうか。

**Comment by lanactindi** [comment]
確認させて頂いたのでcloseします！
