### ISSUE TITLE
[休会] 休会フォームに 注意を読んだのチェックボックスを追加

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5378]
`/hibernation/new` にアクセスすると、休会フォームが表示される。

---

以下の実装をお願いします。

`/app/views/hibernation/new.html.slim` の以下の部分のコメントを外す。

<img width="522" alt="image" src="https://user-images.githubusercontent.com/168265/186810634-7bd29e8f-426f-4ef6-99ea-c0880c0a8130.png">

チェックボックスが表示される。

<img width="353" alt="image" src="https://user-images.githubusercontent.com/168265/186810911-0f472897-b42b-4a0a-ad30-182ee7d86d7d.png">

---

以下を js で実装お願いします。

## チェックが入っていないとき

<img width="613" alt="貼り付けた画像_2022_08_26_12_24" src="https://user-images.githubusercontent.com/168265/186811014-9d25e42d-9c5a-461b-89a5-c4940e5cc11f.png">

休会するのボタンには、`a-button is-md is-block is-disabled` という class が付く。

## チェックが入っているとき

<img width="575" alt="image" src="https://user-images.githubusercontent.com/168265/186811079-788fc0d8-d1c7-4f4d-965c-bb7b62bee525.png">

休会するのボタンには、`a-button is-md is-block is-danger` という class が付く。
`is-disabled` が ` is-danger` に差し替えられる。

**Comment by machida** [comment]
@AyakaTakashima すいません、大事な情報を伝え忘れてました🙇‍♂️

https://github.com/fjordllc/bootcamp/pull/5461

こちらを手元に持ってきて、作業し、このPRにpushをお願いします。

**Comment by AyakaTakashima** [comment]
@machida 
承知いたしました！！
ご連絡ありがとうございます！！

**Comment by AyakaTakashima** [comment]
@machida 
お疲れ様です！！
本件、もう少しでレビュー依頼に出せそうなのですが、description(?)は、こちら（[#5461](https://github.com/fjordllc/bootcamp/pull/5461)）のmachidaさんが作成いただいたPRに後からコメントする形で私が書いて大丈夫なのでしょうか🧐？？
（descriptionはいつもPRの一番最初に書いている、変更内容や変更内容の確認方法を書いているもののことを指しております！）
既存のPRにプッシュするのが初めてでして、教えていただけますと幸いです！！

**Comment by AyakaTakashima** [comment]
#5461
上記issueがマージされたためクローズいたします。
（＊休会フォームは本番では未実装）
