### ISSUE TITLE
Watch中の表示（特定の日報）が枠外にはみ出て表示される

### ISSUE THREAD

**Issue by choco0809** [fjordllc/bootcamp#5384]
## 概要
[特定の日報](https://bootcamp.fjord.jp/reports/59001)だけ、Watch中の表示が枠外にはみ出て表示されている。

## 再現手順
再現手順まで調査できていません。
※ iphoneのchromeで確認したところ、枠内に収まって表示されていました。

## 期待される振る舞い
他の日報と同様、枠内に収まって表示されてほしい。

## スクリーンショット
![スクリーンショット (54)](https://user-images.githubusercontent.com/99729409/185282992-416e9063-bb8c-4d7a-a023-76ac48fb6870.png)

## 環境
 - OS: [Windows 10 Enterprise]
 - ブラウザ: [chrome]
 - バージョン: [104.0.5112.81（Official Build） （64 ビット）]

## 関連Issue

Ref: #関連Issue番号

**Comment by machida** [comment]
:memo:

code がサマリーに含まれると伸びてしまう。
対策を考え中。

**Comment by machida** [comment]
解決させていたので close しますー
