### ISSUE TITLE
日報のプラクティス選択と、Q&Aのプラクティス選択を複数選択可のselectにして、 select2を導入したい

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/bootcamp#539]
日報や質問の絞り込みで使用するセレクトボックスの項目数が多いかつ並びが不規則で目的のものを探しづらい

**Comment by tosite0345** [comment]
セレクトボックスを2つにして `カテゴリ` → `詳細` と絞り込む、といった実装はいかがでしょうか？
もっと簡単な実装だとセレクトボックスにヘッダ行を入れてカテゴリ分けするのがよさそうです😃
（が、量はそのままなので確かに探すのは大変かもしれませんね）

**Comment by machida** [comment]
select2 を使って実装します
https://select2.org/
