### ISSUE TITLE
定期イベントのページタイトルをイベントにする

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5402]
http://localhost:3000/regular_events にアクセス。
このページのこの部分を

<img width="486" alt="貼り付けた画像_2022_08_24_15_34" src="https://user-images.githubusercontent.com/168265/186347579-571f74b7-2ea4-4cb4-a1e0-f5efa5ad0af5.png">

に修正。

**Comment by fuwa-syugyo** [comment]
本番環境で確認しましたのでcloseします。
