### ISSUE TITLE
管理者でログインしている場合のユーザー相談部屋のページタイトルの変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5403]
管理者でログインしているときは、相談部屋のこの部分のタイトルを

<img width="1062" alt="貼り付けた画像_2022_08_24_15_40" src="https://user-images.githubusercontent.com/168265/186348630-6e9ce4d8-6074-4c0f-90e0-1ba6b5dd8a69.png">

ユーザーIDだけに変更してほしい。

---

管理者ではない場合、自分の相談部屋にアクセスしたときは、

<img width="651" alt="貼り付けた画像_2022_08_24_15_42" src="https://user-images.githubusercontent.com/168265/186348896-7c172031-4a77-49cf-a0a3-846bf465b5d2.png">

相談部屋 に変更してほしい。

---

管理者と管理者以外で相談部屋のこの部分の表示が異なるので分岐させる。

**Comment by pachikuriii** [comment]
本番環境での動作が確認できたため、本issueをクローズさせていただきます〜🙏
