### ISSUE TITLE
管理者・メンターでログインしたときだけ、ユーザー一覧に退会、休会のタブを表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5404]
<img width="1224" alt="貼り付けた画像_2022_08_24_15_50" src="https://user-images.githubusercontent.com/168265/186350439-472a933d-0080-4f39-9468-443462b42fcb.png">

退会、休会 はタブを出さないだけではなく、そのページも管理者・メンターでないとアクセスできないようにしてほしい。

- 現状
  - 全員タブ（管理者だけが見える）
- 理想の状態
  - 全員タブ（管理者とメンターだけが見える）
  - 退会タブ（管理者とメンターだけが見える）
  - 休会タブ（管理者とメンターだけが見える）

**Comment by Nabegon** [comment]
@machida さん、お疲れ様です。仕様に関しまして以下1点質問があります🙏

休会と退会の方々も全員表示に表示させるか
現状、退会の方は全員表示に表示されませんが、こちらの機能を追加することで、休会と退会の方々も全員表示に表示させるようにして大丈夫でしょうか。

ご検討のほどよろしくお願いします！

**Comment by machida** [comment]
@Nabegon 質問ありがとうございますー
今回は休会も退会と同じように非表示でお願いします🙏

**Comment by mono-nobe** [comment]
@komagata @machida 
こちら本番リリースされたため、正常に動作するかご確認をお願いします 🙇

**Comment by mono-nobe** [comment]
現役生の権限ではタブが表示されないことは確認しました。

<img width="806" alt="スクリーンショット 2023-03-25 21 54 22" src="https://user-images.githubusercontent.com/94843475/227718463-21d7ff9d-e87b-4747-bfb2-cc3a3c54d2db.png">

**Comment by machida** [comment]
@mono-nobe 本番で確認しましたー🙆‍♂️

**Comment by mono-nobe** [comment]
@machida 
ご確認ありがとうございます！
issueをcloseします。
