### ISSUE TITLE
ユーザー一覧 > 期生別 の title タグの修正

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5405]
http://localhost:3000/generations

<img width="425" alt="貼り付けた画像_2022_08_24_15_58" src="https://user-images.githubusercontent.com/168265/186351732-e1d240f3-8a52-4b3c-b0eb-174aa2299bb5.png">

このページの title は、

<img width="529" alt="貼り付けた画像_2022_08_24_15_59" src="https://user-images.githubusercontent.com/168265/186351889-5e6472b3-32a5-4ebf-a2f1-067cafe393e8.png">

このようになっているが、この部分を、`期生別ユーザー一覧` に変更したい。

**Comment by machida** [comment]
@yuma-matsui 質問ありがとうございます！
今回は title タグだけの変更でお願いしますー

**Comment by yuma-matsui** [comment]
@machida 
かしこまりました！
対応致します😁

**Comment by yuma-matsui** [comment]
本番環境で動作の確認ができましたのでcloseします！
