### ISSUE TITLE
フォロー中ユーザー一覧の title タグを変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5407]
- http://localhost:3000/users?target=followings
- http://localhost:3000/users?target=followings&watch=true
- http://localhost:3000/users?target=followings&watch=false

これらのページのときは（フォロー中のユーザー一覧のページ）

<img width="537" alt="貼り付けた画像_2022_08_24_16_05" src="https://user-images.githubusercontent.com/168265/186353093-0893cb5c-c310-4353-b2eb-fb9b8218da20.png">

全てのユーザーになっているので、`フォロー中のユーザー一覧` に変更したい。

**Comment by OdenTakashi** [comment]
本番環境で確認が取れましたのでcloseします！
