### ISSUE TITLE
プラクティス個別 > 日報 の title タグ変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5409]
プラクティス個別 > 日報 にアクセス。

<img width="848" alt="image" src="https://user-images.githubusercontent.com/168265/186354691-804fa916-0655-473a-8da8-340d3a3ecd7f.png">

title タグが、`プラクティス名` になっているのを

<img width="511" alt="貼り付けた画像_2022_08_24_16_12" src="https://user-images.githubusercontent.com/168265/186354426-7ae9a4a8-8190-44cb-9950-ca7665ddc0f2.png">

`プラクティス名に関する日報` に変更したい。

この場合は `OS X Mountain Lionをクリーンインストールするに関する日報`

**Comment by choco0809** [comment]
本番環境で確認できましたのでcloseします。
