### ISSUE TITLE
adminからユーザーの削除を行いたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#541]

**Comment by komagata** [comment]
> 削除処理を行う時にバックエンド側でフェイルセーフかけたほうがいいでしょうか？
> 例えば何らかのフラグが立っていたら削除禁止、などです。

いらないです。

> また、削除についてですが、こちらはハードデリートですか？

ハードデリートです。

> 一旦退会させたけどまた戻ってくることは考慮しなくて大丈夫ですか？

考慮しなくて良いです。

**Comment by tosite0345** [comment]
@komagata さん
ご回答ありがとうございます。
実装を進めます。

**Comment by tosite0345** [comment]
[app/controllers/users_controller#destroy](https://github.com/fjordllc/bootcamp/blob/master/app/controllers/users_controller.rb#L65)

```ruby
UserDeleter.new(current_user).delete
```

[app/models/user_deleter](https://github.com/fjordllc/bootcamp/blob/master/app/models/user_deleter.rb#L8)

```ruby
  def delete
    @user.notifications.destroy_all
    @user.send_notifications.destroy_all
    @user.destroy
  end
 ```

んー…？
[app/models/user](https://github.com/fjordllc/bootcamp/blob/master/app/models/user.rb#L9) によると

```ruby
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :footprints, dependent: :destroy
  has_many :notifications, dependent: :destroy
```

となっていて、これ全部 `User.destroy` で済みそうな気がする…？
なぜ `UserDeleter` モデルを別に切り分けたのだろう。
理由如何では実装が変わるので…調査してみます。

**Comment by komagata** [comment]
この場合`user.destroy`でいい気がします。

`UserDeleter`的なのが必要になる場合は、

- 削除件数が多い時クッソ重くなるのを避けるため
- callbackを多様

**Comment by tosite0345** [comment]
@komagata さん
なるほど、そういう背景があったのですね。
確かに実プロダクトだと件数が多すぎて重くなりそうな…。
例えばその場合って `job` 化するとかでは対応しきれないものなんでしょうか。
バックグラウンドで走らせるとしても件数が多すぎてタイムアウトする感じですかね。

承知しました、 `user,destroy` で対応します。

**Comment by tosite0345** [comment]
https://github.com/fjordllc/bootcamp/pull/558 で対応。
