### ISSUE TITLE
プラクティス個別ページ > Q&A の title タグ変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5410]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/168265/186355200-ad914427-75f2-4490-8375-784a882d7ada.png">

title タグが、`プラクティス名` になっているのを

<img width="511" alt="貼り付けた画像_2022_08_24_16_12" src="https://user-images.githubusercontent.com/168265/186354426-7ae9a4a8-8190-44cb-9950-ca7665ddc0f2.png">

`プラクティス名に関するQ&A` に変更したい。

この場合は `OS X Mountain Lionをクリーンインストールするに関するQ&A`

**Comment by AyakaTakashima** [comment]
PR：[プラクティス個別ページのQ&Aページの、titleタグを変更した by AyakaTakashima · Pull Request \#5425 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5425)

本番環境で動作確認が完了しましたのでclose致します！
