### ISSUE TITLE
プラクティス個別ページ > Docs の title タグ変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5411]
プラクティス個別ページ > Docs

<img width="748" alt="貼り付けた画像_2022_08_24_16_17" src="https://user-images.githubusercontent.com/168265/186355558-0ae97d36-3383-43fb-afc7-5d27f556e9ba.png">

title タグが、`プラクティス名` になっているのを

<img width="511" alt="貼り付けた画像_2022_08_24_16_12" src="https://user-images.githubusercontent.com/168265/186354426-7ae9a4a8-8190-44cb-9950-ca7665ddc0f2.png">

`プラクティス名に関するDocs` に変更したい。

この場合は `OS X Mountain Lionをクリーンインストールするに関するDocs`

**Comment by yuma-matsui** [comment]
本番環境で問題なく動作が確認できたためcloseします！
