### ISSUE TITLE
プラクティス個別ページ > 提出物の title タグ変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5412]
プラクティス個別ページ > 提出物

<img width="815" alt="image" src="https://user-images.githubusercontent.com/168265/186356226-59a76189-c9ad-4ca5-95cf-a478e60d6027.png">

title タグが、`プラクティス名` になっているのを

<img width="511" alt="貼り付けた画像_2022_08_24_16_12" src="https://user-images.githubusercontent.com/168265/186354426-7ae9a4a8-8190-44cb-9950-ca7665ddc0f2.png">

`プラクティス名の提出物` に変更したい。

この場合は `OS X Mountain Lionをクリーンインストールするの提出物`

**Comment by choco0809** [comment]
bodyタグ内のh1タグコンテキストは「プラクティクス名」のままで、headタグ内のtitleコンテキストのみ「プラクティス名の提出物」に変更する。（町田さんに確認済み）

詳細は下記issueを参照
https://github.com/fjordllc/bootcamp/issues/5405

**Comment by choco0809** [comment]
本番環境で確認できましたのでcloseします。
