### ISSUE TITLE
プラクティスページの日報一覧タブをVue化する

### ISSUE THREAD

**Issue by yocajii** [fjordllc/bootcamp#5414]
## 概要

プラクティスページの日報一覧タブにおける、日報一覧をVue化する。
![image](https://user-images.githubusercontent.com/33394676/186376120-f9831f94-93eb-437d-8a84-8318aae773d8.png)

## 参考情報

既に他の画面で使われている日報のVueパーツとして、`app/javascript/components/reports.vue` が存在する。
このIssueと #5415 が両方対応済みになると、`app/views/reports/_report.html.slim` が不要になる。

**Comment by yuma-matsui** [comment]
本番環境での動作確認が済んだのでクローズします！
