### ISSUE TITLE
「2回連続sadのユーザー」のカードをVue化する

### ISSUE THREAD

**Issue by yocajii** [fjordllc/bootcamp#5415]
## 概要

ダッシュボードにメンター/管理者ユーザーでアクセスした時に表示される「2回連続sadのユーザー」のカードをVue化する。
![image](https://user-images.githubusercontent.com/33394676/186377226-ed06ef2a-ff1f-4f04-a6c9-7748a485f0cf.png)

## 参考情報

既に他の画面で使われている日報のVueパーツとして、`app/javascript/components/report.vue` が存在するため、共通化できると良い。
このIssueと #5414 が両方対応済みになると、`app/views/reports/_report.html.slim` が不要になる。

**Comment by AyakaTakashima** [comment]
machidaさんに本番確認いただきました！クローズします！
https://discord.com/channels/715806612824260640/809595476847493192/1040637114926235659
