### ISSUE TITLE
提出物ページの「直近の日報」をVue化する

### ISSUE THREAD

**Issue by yocajii** [fjordllc/bootcamp#5416]
## 概要

メンター/管理者ユーザーで受講生の提出物ページにアクセスした時に表示される「直近の日報」をVue化する。
![image](https://user-images.githubusercontent.com/33394676/186379743-e05c43cb-ec25-4f9f-90e2-bad18e0b22b8.png)

## 参考情報

既に他の画面で使われている日報のVueパーツとして、`app/javascript/components/reports.vue` が存在する。

**Comment by komagata** [comment]
@pachikuriii 本番環境で動作することを確認しました。

**Comment by pachikuriii** [comment]
@komagata 
ご確認をありがとうございます！

本件はcloseとさせていただきます☺️
