### ISSUE TITLE
日報個別ページに研修生の場合は企業アイコンを表示してほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5442]
日報の個別ページ。

もし、その日報の作者が

- 卒業していない
- 研修生

の条件を満たしていた場合、日報のタイトルの近くにそのユーザーが所属している企業のアイコンを表示したい。配置などはmachidaがやるので、適当に表示だけさせておいてください。

なぜ必要か？

メンターがチェックする場合に、何か企業にも共有しておいた方がいいことが日報に含まれていた場合に、どの企業所属の人なのかがすぐわかるようにしたいから。

**Comment by choco0809** [comment]
@machida 
日報個別ページというのは下記の認識であっていますでしょうか？
<img width="1437" alt="_development__今日は頑張りました___FBC" src="https://user-images.githubusercontent.com/99729409/187055772-609deaf7-2e78-4948-a433-731b302c3f60.png">

> メンターがチェックする場合に、何か企業にも共有しておいた方がいいことが日報に含まれていた場合に、どの企業所属の人なのかがすぐわかるようにしたいから。

とあったので、adminユーザーからみれる下記のページなのかなと個人的に思ったので、
どちらの認識なのか教えて頂きたいです。
<img width="1439" alt="_development__日報___FBC" src="https://user-images.githubusercontent.com/99729409/187055803-e1709369-9c9a-484d-be65-272899d085d6.png">

**Comment by machida** [comment]
@choco0809 

https://user-images.githubusercontent.com/99729409/187055772-609deaf7-2e78-4948-a433-731b302c3f60.png

こちらのページ(reports/show)でお願いしますー

**Comment by choco0809** [comment]
@machida 
承知しました〜！

**Comment by choco0809** [comment]
@machida 
現状、研修生のみ個別日報のタイトル付近に企業ロゴを表示できるようになったんですが、テストをどうするべきか悩んでいます。過去のPRなどをみてみたところ、画像を表示させるテストが見当たらなかったのですが（自分が探した限り😓）、今回の機能追加もテストは必要なのでしょうか？
個人的にはテストは必要だと思うのですが、テストケースを作る、作らないの境目がわからず...

**Comment by machida** [comment]
@choco0809 そうですね、こちら駒形さんとやりとりをしていただけたらと思いますー
@komagata

**Comment by choco0809** [comment]
@machida @komagata 
自分の調査不足で、ユーザーアイコンに関するテストを見つけたので、そこを参考にテストを作成してみようと思います。

**Comment by choco0809** [comment]
本番環境で確認できましたのでcloseします。
