### ISSUE TITLE
一定期間クローズされないQ&Aがあったら投稿者に通知する

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5451]
## 機能の説明

一定期間クローズされないQ&Aがあったら投稿者にwebの通知欄とメールで通知する。

例
Q&A「受講生のみなさんはどこで「丁寧でわかりやすいPRの作り方」を学んでるんでしょうか？」のベストアンサーがまだ選ばれていません。

## 何故この機能が必要なのか

Q&Aを投稿したことを忘れて放置してしまうことがあるから（経験談）。

## 備考

- 投稿者だけではなく、Watch中のユーザー（メンターが含まれる）に通知してもいいかもしれない。
- 質問が投稿されてからn日、ではなく、コメントが最後に投稿されてからn日、というような条件の方がベターかも（回答が1件も投稿されていないのにベストアンサーを選べ、と言われても困るので）。
- 同じようなissueで「一定期間回答コメントが付かないQ&AがあったらWatch中のユーザーに通知する」というissueを作ろうと思ったが、回答が全く質問はまれなので、これは作らなくて良さそう。

**Comment by machida** [comment]
📝 
一旦、今回は、最後の回答から7日間が経過したら質問を作成した人に通知を飛ばすようお願いします。

- 8/1に質問を投稿、翌日8/2に回答があったら、8/9 に通知が飛ぶ。
- 8/1に質問を投稿、翌日8/2に回答があった、さらにその翌日の8/3にも回答があった場合は、8/10 に通知が飛ぶ。
    - 回答がある度に7日間のカウントがリセットされるようにしたいです。

通知の文章は、

```
Q&A「受講生のみなさんはどこで「丁寧でわかりやすいPRの作り方」を学んでるんでしょうか？」のベストアンサーがまだ選ばれていません。
```

でお願いします🙏

**Comment by keiz1213** [comment]
@komagata 

お疲れさまです。相談があります。

前回のリリースでリリースしていただいたのですが、本番環境で期待する動作が確認できず悩んでいます。
[11月30日のリリース](https://github.com/fjordllc/bootcamp/pull/5809)でマージしていただき、12月2日に本番環境で動作確認を行いました。本番環境での動作確認の手順は以下の通りです。

1. [Q&A](https://bootcamp.fjord.jp/questions/1485)を作成する(12/2 21:52)
2. そのQ&Aにコメントする(12/2 21:52)
3. 一週間待つ

期待する動作では12/9に自分に通知が来るはずですが通知が来ませんでした。本日12/11まで様子を見ていたのですがまだ通知が届いていません。開発環境、ステージング環境では動作が確認できており、システムテストも通っています。なぜ本番環境で期待する動作をしないのかが分かりません。開発環境、ステージング環境では手動で`/scheduler/daily`にアクセスしており、その違いが関係あるのかと思っているのですがどうでしょうか？

パスしている該当のシステムテストは以下になります。
```ruby
test 'notify to questioner when a week has passed since last answer' do
    questioner = users(:kimura)
    answerer = users(:komagata)
    question = Question.create!(
      title: 'テストの質問',
      description: 'テスト',
      user: questioner,
      created_at: '2022-10-31',
      updated_at: '2022-10-31',
      published_at: '2022-10-31'
    )
    Answer.create!(
      description: '最後の回答',
      user: answerer,
      question: question,
      created_at: '2022-10-31',
      updated_at: '2022-10-31'
    )

    travel_to Time.zone.local(2022, 11, 6, 0, 0, 0) do
      visit_with_auth '/scheduler/daily', 'kimura'
      visit '/notifications'

      assert_no_text 'Q&A「テストの質問」のベストアンサーがまだ選ばれていません。'
    end

    travel_to Time.zone.local(2022, 11, 7, 0, 0, 0) do
      visit_with_auth '/scheduler/daily', 'kimura'
      visit '/notifications'

      assert_text 'Q&A「テストの質問」のベストアンサーがまだ選ばれていません。'
    end
  end
```

**Comment by komagata** [comment]
@keiz1213 

> 開発環境、ステージング環境では手動で/scheduler/dailyにアクセスしており、その違いが関係あるのかと思っているのですがどうでしょうか？

本番ではgoogle schedulerがアクセスするようになっていますがエラーは出ていないようです。本番でも手動でアクセスして見ました。

ちょっと何故動かないのかは僕の方でもわかっていません。

**Comment by keiz1213** [comment]
@komagata 

>本番ではgoogle schedulerがアクセスするようになっていますがエラーは出ていないようです。本番でも手動でアクセスして見ました。

調べていただきありがとうございます。もう一度Q&Aを作成して試してみます。

**Comment by komagata** [comment]
@keiz1213 こちら調べた結果、本番環境で`scheduler/daily`の処理に時間がかかり過ぎて実行できていないようでした。

それを解決するためにこちらのIssueを作成しました。

#5934

@keiz1213 さんはもう20ポイント終わっているので別の方にこのIssueをお願いして、終わったらこちらも動作確認完了ということにできればと思います。

**Comment by keiz1213** [comment]
@komagata 

>本番環境でscheduler/dailyの処理に時間がかかり過ぎて実行できていないようでした。

なるほどです。調査ありがとうございます！了解致しました！

**Comment by komagata** [comment]
下記のIssueが完了したのCloseします〜
#6111
