### ISSUE TITLE
Q&A一覧でタグのある投稿がないと、タグ一覧が非表示になってしまう。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5456]
http://localhost:3000/questions?target=not_solved
ここにアクセス。

このページで表示されている質問一覧それぞれの質問からタグを全て外す。
すると、投稿一覧の右側にあるタグ一覧が表示されなくなってしまう。

表示されている質問一覧それぞれの質問全てがタグを持っていなくても、タグ一覧は表示されているようにしてほしい。

**Comment by yuki-snow1823** [comment]
開発環境で状況確認できました。着手します。

**Comment by yuki-snow1823** [comment]
@machida 
質問です🙇‍♂️

以下のページにアクセスし、タグのついている質問からタグを削除したところ、質問一覧からタグが消えてしまうことを確認しました。
http://localhost:3000/questions?target=not_solved

一方で、2ページ目の質問のみにタグがついていて、1ページ目を閲覧した場合はきちんとタグが出ていました。

>タグ一覧は表示されているようにしてほしい。
そこで質問なのですが、表示されている質問のタグを全て削除したときに表示しておきたい「タグ一覧」とは、何が出力されていると望ましいでしょうか？

**Comment by machida** [comment]
@yuki-snow1823 

質問ありがとうございます！！
今回は、タグの表示の仕方までは考えていませんでした。
タグ一覧が表示されていればOKと考えてました。

改めて、現状ではどういうルールでタグの一覧が表示されているのか調べたところ、

- Qについたタグ全てが表示されている
- Qについたタグが古い順で表示されている
- タグのリンク先は、全てタブ（解決したもの、未解決がミックスされた一覧）

となっていました。
今回表示するのは上記のままでOKです。

別 Issue で、

- Qについたタグ全てが表示されている
    - これは制限があってもいいかも、要相談
- Qについたタグが古い順で表示されている
    - これを多い順に変更
- タグのリンク先は、全てタブ（解決したもの、未解決がミックスされた一覧）
    - これはこのまま

としたいと思います。
ただ別 Issue なので、今回の PR には含めなくて大丈夫ですー

**Comment by yuki-snow1823** [comment]
@machida 
ありがとうございます🙏

ということは、

本issueでは、「全て」タブを開いたときに表示されているタグと同様のタグが表示されているという状態を目指す形でよろしいでしょうか。

「全て」タブを開いたときに表示されているタグが

>Qについたタグ全てが表示されている
Qについたタグが古い順で表示されている
タグのリンク先は、全てタブ（解決したもの、未解決がミックスされた一覧）

こちらを満たすと考えました👀

**Comment by yuki-snow1823** [comment]
ちなみにその場合は、以下のコードで全てのQuestionに関連するtagを出せていそうなので、このままでも問題なさそうかな...？と読んでみて思いました🙏

`bootcamp/app/views/questions/index.html.slim`
```slim
                - Question.all.all_tags.each do |tag|
                  - if tag.present?
                    li.page-tags-nav__item
                      = link_to tag.name, questions_tag_path(tag.name), class: 'page-tags-nav__item-link'
```

**Comment by yuki-snow1823** [comment]
ページに関係なくタグ一覧には全てタグを出力する
