### ISSUE TITLE
提出物に最終更新日を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#546]

**Comment by shikibum** [comment]
@machida @komagata 
確認なのですが、提出物一覧の日付はcreated_atのまま、提出物のページはcreated_atとupdated_atを併記するという認識であっていますか？
（例　2018年11月23日(金) 23:14　最終更新：2018年12月05日(水) 14:16）
<img width="706" alt="2018-12-14 23 07 41" src="https://user-images.githubusercontent.com/37039268/50007866-ada2d400-fff5-11e8-9238-dae9050cd0a4.png">
<img width="994" alt="2018-12-14 23 07 56" src="https://user-images.githubusercontent.com/37039268/50007873-b09dc480-fff5-11e8-89d8-a1b422f410ae.png">

**Comment by machida** [comment]
@shikibum はい！その認識で合ってますー！！

**Comment by shikibum** [comment]
@machida 了解です、ありがとうございます！
