### ISSUE TITLE
アバター画像が未設定の人へアイコンでのメンションをしようとすると画像がリンク切れになる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5469]
画像が未設定の人の場合はデフォルトのアバター画像を出したい。

https://user-images.githubusercontent.com/16577/187876092-42ed2026-d202-43e6-90cd-005792314bc7.mov

**Comment by yuki-snow1823** [comment]
memo: 画像がある人のみを参照する形になっているらしい

**Comment by yuki-snow1823** [comment]
着手します。

**Comment by komagata** [comment]
@yuki-snow1823 メモは :memo: この絵文字おすすめです〜🤭

**Comment by komagata** [comment]
リリース済みなのでCloseします。
