### ISSUE TITLE
プラクティス新規作成の表示をadminだけにするほうがよいかもしれない

### ISSUE THREAD

**Issue by neko314** [fjordllc/bootcamp#547]
## 現状
![image](https://user-images.githubusercontent.com/29836309/47479976-c4d10b00-d869-11e8-93aa-d79a80482492.png)

## issueの理由

* ユーザー（受講生）が0からプラクティスを作るケースが考えにくい
* パッと見で日報の新規作成っぽくて間違えやすい（私がよく間違えるだけという可能性は高い・・・）

**Comment by machida** [comment]
あー、これはおっしゃる通りです。やってしまいますー。

**Comment by neko314** [comment]
ありがとうございます〜よろしくお願いします✨

**Comment by shikibum** [comment]
@komagata @machida 
`before_action :require_admin_login, except: %i(show)`で行くつもりなのですが、admin以外のユーザがeditなどshow以外をすることって想定していますか？？

**Comment by machida** [comment]
@shikibum @komagata 今のところ想定してないですー adminだけで大丈夫です 👌🏿

**Comment by shikibum** [comment]
@machida @komagata 了解です、ありがとうございます！
