### ISSUE TITLE
[newspaper] お知らせの通知をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5491]
AnnouncementCallbacksにある通知処理をnewspaperに置き換えたい
同じ場所にあるDiscordへの通知も置き換えたい。

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/announcement_callbacks.rb#L29)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by hikarook94** [comment]
本番環境で確認いただいたのでCloseします
