### ISSUE TITLE
[newspaper] お知らせのWatch処理をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5492]
AnnoucementCallbacksにあるWatch処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/announcement_callbacks.rb#L8)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by akingo55** [comment]
@komagata 
もともとのWatch処理はお知らせが`create`された場合のみwatch中になる仕様となっていますが、この場合だとお知らせが`wip`の状態から公開になった場合は、watch中にならないのは理由がありますでしょうか。
自分が公開したお知らせを自動的に`watch`する仕様でしたら、`wip`の状態から公開になった場合も同様の処理が必要かと思うので、こちらのIssueで対応しようかと思いますが、いかがでしょうか。
https://github.com/fjordllc/bootcamp/blob/main/app/models/announcement_callbacks.rb#L8

**Comment by komagata** [comment]
@akingo55 なるほど〜それはバグだと思います。
大変申し訳ありませんが、こちらのIssueで一緒に対応していただけると大変ありがたいです〜！

**Comment by akingo55** [comment]
@komagata 
承知いたしました！
あわせて対応します！
