### ISSUE TITLE
[newspaper] お知らせの通知削除処理をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5493]
AnnouncementCallbacksにある通知削除処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/announcement_callbacks.rb#L47)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by shirotamaki** [comment]
@komagata @machida 
お疲れさまです！こちらのissueの動作確認を本番環境でお願いできますでしょうか？

**Comment by komagata** [comment]
@shirotamaki こちら、大勢に影響を与えずに確認が難しいので、確認はなしでOKにしたいと思います〜。

**Comment by shirotamaki** [comment]
@komagata 承知しました！closeいたします！
