### ISSUE TITLE
[newspaper] Q＆Aの回答がきた通知処理をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5495]
AnswerCallbacksにある回答がきた通知処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/answer_callbacks.rb#L5)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by pachikuriii** [comment]
回答が来た際に質問者へ通知が飛ぶことを本番環境で確認できたため、本issueはクローズします。

![image](https://user-images.githubusercontent.com/58751858/191694915-fb3d37e4-6d37-43b1-8668-f5577e624ced.png)

![image](https://user-images.githubusercontent.com/58751858/191695195-74a6eb56-c6c4-4e58-962d-4064eb980d85.png)
