### ISSUE TITLE
[newspaper] Q＆Aの解答を投稿したらWatchする処理をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5496]
AnswerCallbacksにある解答を投稿したらWatchする処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/answer_callbacks.rb#L6)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by machida** [comment]
@pachikuriii こちらアサインさせていただきましたー

**Comment by pachikuriii** [comment]
本番環境で動作が確認できましたので、こちらはcloseします🙌

![image](https://user-images.githubusercontent.com/76944527/194324379-905d33f6-f52a-4761-a6fb-1eb2949d84cf.png)
![image](https://user-images.githubusercontent.com/76944527/194324406-95946421-cc05-4d04-8b07-eb4f941954ca.png)
