### ISSUE TITLE
[newspaper] Q＆AのWatchしてる人への通知処理をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5497]
AnswerCallbacksにあるWatchしてる人への通知処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/answer_callbacks.rb#L7)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by AyakaTakashima** [comment]
shirotamakiさんに協力していただき、本番環境にて問題ないことが確認できました。
[こちらのQ&A](https://bootcamp.fjord.jp/questions/1445)を作成し、確認しました。
通知が来たとのことで下記お返事がきました。
https://discord.com/channels/715806612824260640/809595476847493192/1024984271091421185

クローズします！
