### ISSUE TITLE
[newspaper] Q＆Aの解決質問数のキャッシュ削除処理をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5499]
AnswerCallbacksにある解決質問数のキャッシュ削除処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/answer_callbacks.rb#L13-L17)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by choco0809** [comment]
本番環境で確認できましたのでcloseします。
