### ISSUE TITLE
【メンター向け】提出物を「担当する」ボタンを押す前にコメント欄から確認OKにした際、Toastが「担当になりました」になってしまう

### ISSUE THREAD

**Issue by yuma-matsui** [fjordllc/bootcamp#5502]
## 概要
メンターが担当になっていない提出物に対して、「担当する」を押す前にコメントまたはコメント欄からOKにした場合に表示されるトーストが「担当になりました！」になっている。情報としては「コメントした」、「確認OKにした」ことが正しいので、こっちが表示されるようにしたい。

### 再現GIF
- https://i.gyazo.com/b5115a65db8d47733dfa0aa65c7482c0.mp4
- https://i.gyazo.com/0bc5735013e0ba34813e3d93351a4721.mp4

## 再現手順

1. `machida`でログイン
2. `/products/:id`にアクセスする
3. 「担当する」を押す前にコメントまたはコメント欄から確認OKにする

## 修正案
-  担当するを押す前にコメント、コメント欄から確認OKにした場合のToastをそれぞれ「コメントしました！」、「提出物を確認済みにしました！」にする

**Comment by yuma-matsui** [comment]
@keiz1213 

お疲れ様です！
こちら自分から回答させてもらいますね。

結論から申し上げると「意図せずに最初にコメントしたメンターが担当者になってしまっている」というのが現状です。
なので担当がついていない提出物へメンターがコメントをした場合には担当にならずコメントだけ残るようにしてほしいです。

@machida 
認識に間違いありましたらご指摘いただければと思います！

**Comment by machida** [comment]
@keiz1213 @yuma-matsui 
おっと、認識に違いがありました。

担当がいないときにコメントをした場合は担当になる、というのは仕様で、意図せず担当になってしまうという問題は、別のIssueで担当になりました、とtoastで表示されるようになったのでこの問題は解決されました。どちらかというと、担当になるのを忘れてる方が多かったという背景もあり、コメントをしたら担当になるというのはこのままにしておきたいです。

今回お願いしたいのは、自分が担当ではない場合に、コメントから確認OKをすると、提出物を確認しました、ではなく、担当になりました、とtoastで表示される点です。

自分が担当ではない場合に、コメントから確認OKをした際は、提出物を確認しました、的なメッセージを toast で表示するようにしていただきたいです🙏

**Comment by keiz1213** [comment]
@yuma-matsui  @machida 
なるほどです💡現状を把握できました😄
とても迅速な回答ありがとうございました🙏

**Comment by keiz1213** [comment]
本番環境で動作確認をしていただきましたのでcloseします。
