### ISSUE TITLE
ダッシュボードのブックマークの作成者名の表示変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5509]
ダッシュボードに表示されるブックマークの作成者名が名前で表示されているが、IDも表示したい

<img width="652" alt="貼り付けた画像_2022_09_13_16_07" src="https://user-images.githubusercontent.com/168265/189833689-f6d8a278-cace-467b-bdf2-009d3cbb5301.png">

このように表示したい。

<img width="648" alt="貼り付けた画像_2022_09_13_16_09" src="https://user-images.githubusercontent.com/168265/189834048-c54c573c-d022-425f-b776-207f1db119e2.png">

**Comment by pachikuriii** [comment]
本番環境で確認できましたため、こちらはcloseとさせていただきます☺️
