### ISSUE TITLE
ダッシュボードにある最新のブックマークに削除の機能が欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5511]
日報や提出物などをブックマークすると、ダッシュボード に最新のブックマークが表示される。

<img width="671" alt="image" src="https://user-images.githubusercontent.com/168265/191072640-390b1761-c243-4251-b39b-41f79db0ae33.png">

ここに編集スイッチ（チェックボックス）を置く。

<img width="671" alt="貼り付けた画像_2022_09_20_2_01" src="https://user-images.githubusercontent.com/168265/191073006-832d3225-875e-43f7-aad4-02280359980a.png">

オンにすると、削除ボタンが表示される。

<img width="671" alt="貼り付けた画像_2022_09_20_2_01" src="https://user-images.githubusercontent.com/168265/191073182-167af319-4a63-4359-8abf-62b32d3ce2ee.png">

削除ボタンをクリックすると、ブックマークが消せる。

動きとしては、

<img width="671" alt="貼り付けた画像_2022_09_20_2_01" src="https://user-images.githubusercontent.com/168265/191073311-684b3947-2cf7-45bd-8de4-56a5bc05c64d.png">

全てのブックマークのページに同じ機能があるが、それと同じものを実装する。

**Comment by choco0809** [comment]
@machida 
1点、ご質問があります。
> 全てのブックマークのページに同じ機能があるが、それと同じものを実装する。

全てのブックマークはVueにてブックマーク削除機能を実装しています。
最新のブックマークではVueは使用されていないのですが、Vueにて機能実装して問題ないのでしょうか🤔
もしくは、Vueを使わずに全てのブックマークと同等の機能を実装するということでしょうか🤔
お手数ですが、よろしくお願いします🙇‍♂️

**Comment by machida** [comment]
@choco0809 vueは使わずに同じ動きをするものを実装お願いします。ページ遷移や読み込みが発生して大丈夫ですー

**Comment by choco0809** [comment]
@machida
vue使わない旨承知しました🙇‍♂️
このissueもデザイン依頼あると認識していて問題ないでしょうか？

**Comment by machida** [comment]
@choco0809 はい、デザインは僕がやりますー

**Comment by choco0809** [comment]
@machida 
編集ボタン/削除ボタンの追加は完了したのですが、1点ご相談があります。

現在、削除ボタンをJavaScript内で`display = 'none'/'block'`で表示/非表示を制御しています。
`display`プロパティを使用すると要素自体を非表示の場合削除してしまうので、位置ズレが生じます。
この位置ズレはデザインで対応していただける範囲でしょうか？

**Comment by machida** [comment]
@choco0809 僕の方で対応するので大丈夫ですー
