### ISSUE TITLE
カテゴリー編集画面の文言変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5517]
管理者でログインし、

/admin/categories/

にアクセス。

カテゴリーの編集画面にいく（どのカテゴリーでもOK）。

<img width="963" alt="貼り付けた画像_2022_09_14_16_32" src="https://user-images.githubusercontent.com/168265/190090235-ab6275bb-685e-47bf-b244-7ab0f7a2c571.png">

ここの部分の文言変更。

<img width="753" alt="貼り付けた画像_2022_09_14_16_31" src="https://user-images.githubusercontent.com/168265/190090054-a5636834-7d11-46de-ae6d-2055f83073a7.png">

以下の文言に変更お願いします🙏

```
このカテゴリーを学ぶことでできるようになること、なぜこれを学ぶのかの理由、学ぶにあたっての必要な前提条件（修了していないといけないプラクティスなど）を記入してください。
```

**Comment by akingo55** [comment]
@komagata @machida 
お疲れ様です。
こちら本番環境にて上記の文言の表示が変更されているかご確認いただけますでしょうか？
お手隙によろしくお願いします:pray:

**Comment by komagata** [comment]
@akingo55 本番環境で変更されていることを確認しました。
