### ISSUE TITLE
日報タイトルの入力欄のヘルプの文章を変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5518]
`/reports/new` 日報作成画面にアクセス。

<img width="759" alt="貼り付けた画像_2022_09_14_16_58" src="https://user-images.githubusercontent.com/168265/190095927-4a5d0dc9-6587-48f4-893b-ef0f107e44eb.png">

この文章を以下のものに変更。

```
日報のタイトルはあとで振り返りやすいタイトルを付けてください。

「今日はここまでやった」「今日はこんなことを感じた」という概要をタイトルに含めておけば、あとで読みかえしたいときにぱっと目的の日報にたどり着けます。

それだけでなく、他の受講生があなたの日報を参考にしたいときにも「あ、この日報を読めば何か手がかりが得られるかも」ということがタイトルから把握できます。

自分自身のため、そして他の受講生のために、わかりやすい日報タイトルを付けましょう。

gitのようなソースコード管理ツールを使ったことがある人は、未来の自分自身へ向けたコミットメッセージだと考えると良いと思います。
```

文言変更後、machida がデザインで調整をするので、文言変更をしたら machida にメンションを PR のコメントから送り、PRのアサインに machida を追加してください。（PR = Pull Request）

<img width="381" alt="貼り付けた画像_2022_09_14_17_00" src="https://user-images.githubusercontent.com/168265/190096362-2fdaaa79-ec12-4c6f-ab5a-57243f737caa.png">

**Comment by akingo55** [comment]
本番環境で文言変更されていることを確認したので、Closeします。
![image](https://user-images.githubusercontent.com/43959158/194833921-d46a9d41-06d0-44ec-a2a9-ecc222d4209d.png)
