### ISSUE TITLE
溜まった通知を一括で既読にする機能について

### ISSUE THREAD

**Issue by tosite0345** [fjordllc/bootcamp#552]
# はじめに
<img width="368" alt="2018-10-26 17 56 50" src="https://user-images.githubusercontent.com/24952964/47556131-8f4f1f00-d948-11e8-873e-ef9eeda0501f.png">
ここの通知を一括で既読にする機能があればいいかな、と思ってIssue書きました。

# どういうことか
今は「通知」の中からページを遷移しないとお知らせが消えない仕様？になっているようで…。
明示的に確認したことが明らかであれば、一括で既読にしてしまってもいいかな？と思いました。
あるいは通知が起こっているページを閲覧したらNewフラグが消える、とか…？

皆さんのご意見お待ちしております。

**Comment by neko314** [comment]
意見なわけじゃないんですけど・・・

一度、いつかのミートアップで話題になりました！そのときの記憶上では

* 一括既読ほしい
* 既読にしても通知欄から通知が消えないようにしたい
* このままでいい

という意見が出ていて、（通知たくさんある人そうでない人、通知を開かずにおいておくことで後で見るぞというふうに使っている人など）人によって使い方も要望もいろいろっぽくて現状のままってなったようなきがします〜

ミートアップでの私の記憶がどこまで確かだったか怪しいので、この情報100％ 正確ではないかも・・・

**Comment by tosite0345** [comment]
@neko314 さん
ご回答ありがとうございます〜！
なるほど…個人的に過去の通知が残っているのが気持ち悪いので一括で既読にしたい派なのでそういった提案をさせていただきましたが…。
過去にそういったディスカッションがあったのですね。

そのような経緯があるのであれば、仮に実装するなら例えば通知リストの中に「一括で既読にする」リンクを作っておいて消したい人はそこから消す、みたいな機能が良さそうですね。
消す・消さないはユーザーに任せてしまう、的な。

とは言えおっしゃるようにこの辺はユーザーのユースケース次第なので、なんとも難しい感じにはなりそうですね…。

**Comment by komagata** [comment]
#443 と重複ですね。「やる」に入っているのでそのうちやる予定ですー

**Comment by tosite0345** [comment]
重複していたようなのでCloseしておきます。
確認不足ですみませんでした。
