### ISSUE TITLE
ナビゲーションバーのデザインについて

### ISSUE THREAD

**Issue by tosite0345** [fjordllc/bootcamp#555]
# 概要
ナビゲーションバーのデザインで一部戸惑った部分があったのでIssue立てました。

**現在**
<img width="232" alt="2018-10-30 11 48 35" src="https://user-images.githubusercontent.com/24952964/47692737-27475400-dc3a-11e8-8c3f-051aed0b772b.png">

**提案**
<img width="232" alt="2018-10-30 11 48 47" src="https://user-images.githubusercontent.com/24952964/47692736-27475400-dc3a-11e8-8e26-a6972a80883c.png">

各ボタンの下に機能名を表示してはいかがでしょう？
使い慣れた方だと不要かなとは思いますが、 `admin` 機能に入ろうとした際に、旗アイコンがそれだと気づかず迷ったもので…。

**ちなみにスマホ表示**
<img width="406" alt="2018-10-30 11 56 12" src="https://user-images.githubusercontent.com/24952964/47692916-e13ec000-dc3a-11e8-8367-e531a1c1d669.png">
スマホだと全てサイドバーに行くようなので、こちらには手を加えなくて良さそうです。

## 導入効果
- UIがより分かりやすくなる

ご意見お待ちしております。

**Comment by tosite0345** [comment]
文字数でデザイン崩れしそうなことを考えたら [Tooltips](https://getbootstrap.com/docs/4.1/components/tooltips/#examples) でもいいかと思ったけどよく考えたらiPadでhoverの挙動できなかったですね。

**Comment by machida** [comment]
@tosite0345 これ、急ぎで入れたのでまだ文字を出してませんでした。中途半端に進めてるブランチが手元にあるので早く片付けてpush してしまいます。

**Comment by tosite0345** [comment]
@machida さん
お返事ありがとうございます。
そうだったんですね！
ありがとうございます、よろしくお願いいたします。

**Comment by tosite0345** [comment]
確認しました。
ご対応いただきありがとうございます😃
クローズしておきます〜🙏
