### ISSUE TITLE
アドバイザーがQ&Aに回答をしたら、所属企業のアイコンがコメントに表示されたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5553]
https://github.com/fjordllc/bootcamp/pull/5534
こちらはコメントに機能を実装している。これ参考に、Q&Aの回答に機能を実装。

---

回答したユーザーが、アドバイザーでかつ、企業に所属をしていた場合、企業ロゴを表示する。

**Comment by hikarook94** [comment]
本番環境で確認いただいたのでCloseします。
