### ISSUE TITLE
アドバイザーでログインしたときのダッシュボードに研修生がいなくても研修生を表示するブロックが表示されてしまう。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5560]
アドバイザーでログインすると、ログインしたアドバイザーアカウントと同じ企業に所属する現役の研修生の一覧がダッシュボードに表示される。

<img width="761" alt="貼り付けた画像_2022_09_21_14_58" src="https://user-images.githubusercontent.com/168265/191425723-c38c7b5f-4b4d-4b34-8f46-6f0ec9f19db8.png">

ログインしたアドバイザーアカウントと同じ企業に所属する現役の研修生が0の場合も、これが表示されてるので、ログインしたアドバイザーアカウントと同じ企業に所属する現役の研修生が0の場合は非表示にしたい。

**Comment by yamatatsu10969** [comment]
## 調査ログ

senpai でログインすると研修生が表示される。

`_collegue_trainee.html` が実際に研修生を表示している箇所


### 再現方法

- kensyu を削除する
- kensyu の所属企業を削除する

**Comment by yamatatsu10969** [comment]
seed に同僚がいないユーザ作った方が良さそうな気がした。あと、テストも書いた方がいいかも。

**Comment by yamatatsu10969** [comment]
`@completed_learnings.present?` の条件式、不要そうなんだがどうなんだろうか。
アドバイザーは企業の先輩的な立ち位置なので、終了したラーニングはなさそうだ。
実際にアドバイザーの方のデータ見たところ、終了したラーニングがない人の方が多い。

```ruby
          - if current_user.belongs_company_and_adviser? && @completed_learnings.present?
            = render 'collegue_trainees', collegue_trainees: @collegue_trainees
```

**Comment by yamatatsu10969** [comment]
issueの問題を再現するのに苦労した。
特に user に紐づく talks にもデータがないとログイン後にエラーになることを知った。
talks が nil になるので、talks_unreplied_index_url がないというエラーになる。

1. `db/fixtures/user.yml` に必要なデータを入れる
2. `db/fixtures/company.yml` に必要なデータを入れる 
3. `db/fixures/talk.yml` に必要なデータを入れる
4. `rails db:drop`
5. `rails db:setup`
6. `bin/rails s` で起動
7.  `rails c` を使って、作成された user の id を探す
  9. `User.find_by(login_name: 'advisernocolleguetrainee')`
10. id をつかってログインする

**Comment by yamatatsu10969** [comment]
rails db:seed でも行けるんだろうか。

**Comment by yamatatsu10969** [comment]
|before|after|
|---|---|
|<img width="1505" alt="CleanShot 2022-10-12 at 09 55 13@2x" src="https://user-images.githubusercontent.com/43805056/195224604-a564bdbe-758d-452e-8046-10e2c348630d.png">|<img width="1512" alt="CleanShot 2022-10-12 at 09 56 02@2x" src="https://user-images.githubusercontent.com/43805056/195224675-e1554991-5f2c-46dd-ae33-3b189124b8ac.png">|
|||

**Comment by yamatatsu10969** [comment]
## 聞きたいこと
- 簡単な再現方法
  - 今回は seed に作成して再現してみた
- collegue(正しくはcolleague) をタイポしているので修正したいのだが別チケットにするべきか
- テストはどこまで書くか問題

**Comment by komagata** [comment]
@yamatatsu10969 

https://github.com/fjordllc/bootcamp/issues/5560#issuecomment-1275479350

こちらはメンターへの質問という意味でしょうか？
もしそうだとしたら、メンションがないと気づくことができないので今後はメンションをお願いできれば助かります〜。
（他の方のPRやIssueも見ていただけるとどのようなコミュニケーションをとっているのか参考になるかもです〜）

> fixtures に追加した user などは、 rails seed コマンドでDBに追加されるのか

`rails db:seed`で追加されます。しかし、fixturesは二箇所あります。
`db/fixtures`はdevelopment環境のデータで、`test/fixtures`はtest環境のデータです。

> collegue(正しくはcolleague) をタイポしているので修正したいのだが別チケットにするべきか

見つけてくださってありがとうございます。このぐらいであれば、コミットが別であれば同一Issue内で治してしまって大丈夫です〜。

**Comment by yamatatsu10969** [comment]
@komagata 
こちら自分用のメモなので次回から📝をつけますね！

他にも返信ありがとうございます。
疑問が解消されました。

**Comment by yamatatsu10969** [comment]
📝
アドバイザーで見る必要があるので、machida さんと komagata さんに依頼中
https://discord.com/channels/715806612824260640/809595476847493192/1038393145316085780

**Comment by yamatatsu10969** [comment]
確認したいただいたのでクローズ
