### ISSUE TITLE
ブログ edit の published_at の変更フォームが欲しい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5561]
メンターでログインし、ブログ記事作成に行く。

<img width="295" alt="image" src="https://user-images.githubusercontent.com/168265/191435286-ed48c564-e2ea-4244-b7d3-74cf67f84a19.png">

記事公開日時（published_at ）の入力を用意する。日時入力パーツは、イベント作成のフォームを参考にするといいかも。

<img width="1183" alt="貼り付けた画像_2022_09_21_15_54" src="https://user-images.githubusercontent.com/168265/191435476-fedce648-ed98-4f79-9922-910bbba6ebb0.png">

記事公開日時を入力したにも関わらず、WIP で保存した場合は、ここに入力した値は保存しない（published_at の値のある、なしで WIP 判定をしているため）。

<img width="1183" alt="貼り付けた画像_2022_09_21_15_54" src="https://user-images.githubusercontent.com/168265/191436281-c8bd1418-c883-401e-901e-8a5f244d51c5.png">

WIPで保存した場合は、記事公開日は保存されません。 という注意文と、
これをクリックしたら今この瞬間の日時が記事公開日時の input に入力されるボタンがあると良さそうです。

記事公開日時を入力は、edit のときだけ表示。
未来の日時を入れると、投稿予約ができるみたいな機能があってもいいけど、それは別Issueで。
newのときに、記事をWIPでなく公開をした場合は、published_at には公開ボタンを押したときの日時が保存される（今までと同じ仕様）。

**Comment by pachikuriii** [comment]
@machida 

町田さん、おつかれさまです〜！🍵
こちらのイシューについて2点ご相談です。

1.  >記事公開日時を入力したにも関わらず、WIP で保存した場合は、ここに入力した値は保存しない（published_at の値のある、なしで WIP 判定をしているため）。

こちらの仕様についてです。
現状のコードと動作の確認をしてみたところ、WIPかどうかについては記事のWIP属性が`true`か`false`かで判定がなされているようで、published_atの値があるかどうかはWIPの判定に関係がないようでした。

なのでeditページで記事公開日時を入力しWIP で保存した時の仕様としては、
- 編集の際に記事公開日時のフォームで入力した値はWIPでも保存する
- 記事公開日時の入力値はWIPでも保存されるので`WIPで保存した場合は、記事公開日は保存されません。` という注意文はなし

とした方がユーザーにとって親切かな〜と思ったため、上記の仕様について町田さんのご意見を伺えたらうれしいです…！

2.　画像の`現在の日時`のボタンのデザイン
![image](https://user-images.githubusercontent.com/58751858/191884905-714899b4-a30b-4d83-9141-efc599819592.png)

https://bootcamp.fjord.jp/pages/139 の手順でプログラムが出来上がった時点で町田さんにご連絡するかたちでよろしいでしょうか🌸？

上記について、お手隙の際にご確認いただけますと幸いです😌

**Comment by machida** [comment]
@pachikuriii

> published_atの値があるかどうかはWIPの判定に関係がないようでした。

なるほど、勘違いしてました🙇‍♂️ 調査ありがとうございます！！

記事を公開していないのに公開日時を持っているのはちょっと気持ち悪い感じがしますね〜。あと、設計やソースコード的に他の開発者が混乱をしてしまいそうな気がします（なんで publishしてないのに published_at の値が入ってるの？みたいな）。なので、WIPのときは published_at は空にしておきたいです。

ここで、ちょっと考えたのですが、published_at は基本的には投稿の時点の日時が入るのが普通で、その値をいじるのはイレギュラーなケースになります。なので、ちょっと UI に手を加えて、記事公開日時は普段は隠しておいて、変更したいときだけ表示させる、という UI にしたいと思いました。この UI 僕の方で手を加えるのでコミットさせていただきますー。

> 画像の現在の日時のボタンのデザインについて

こちら、僕の方でデザインを入れます。class名がテストに影響するなどありましたら、完成前でも声をかけていただけたら対応しますー

**Comment by pachikuriii** [comment]
@machida 
おはようございます☺️ご確認をありがとうございます〜！
> 設計やソースコード的に他の開発者が混乱をしてしまいそうな気がします

なるほどです…！publishしてないのに値が入ってるのは変ですね…🤔
記事新規作成ページ→公開せずにWIPとした場合はpublished_atの値は空、
公開後の記事を編集→WIPとした場合は、公開時のpublished_atの値がWIPの状態でも保存される…という形でいいでしょうか…？

> 記事公開日時は普段は隠しておいて、変更したいときだけ表示させる、という UI にしたいと思いました。

ありがとうございます😊
ボタンのデザインの件と合わせて、プログラムが完成次第PRよりご連絡させていただきますね💪🏻

**Comment by machida** [comment]
@pachikuriii 公開していたものをWIPに変更した時どうなっているか気になってましたー
こちら、提出物や日報を見ていただき、同じ仕様にしていただきたいです🙏

**Comment by pachikuriii** [comment]
@machida 
手元で確認したところ、日報においては
1.  日報新規作成ページ→公開せずにWIPとした場合はpublished_atの値は空
2. 公開後の日報を編集→WIPとした場合は、初回公開時のpublished_atの値がWIPの状態でも保存される
3. 2のWIPの状態から日報を公開した場合、初回公開時のpublished_atが保存される
（今回のイシューはこの3で初回公開日時のpublished_atを変更するためのもの）

という形になっていたので、この仕様に合わせたいと思います😊

**Comment by machida** [comment]
@pachikuriii 調査ありがとうございます🙏仕様を確認しました！！それと同じでお願いしますー🙏

**Comment by pachikuriii** [comment]
@machida 
こんにちは！たびたびすみません…。1点仕様の確認をさせてください。

-  日報新規作成ページ→公開せずにWIPとした場合はpublished_atの値は空
このパターンでの記事編集画面におけるフォームを以下のように作りました💪🏻
![image](https://user-images.githubusercontent.com/58751858/192935183-dcd1348b-3b79-41f4-9292-739eb63df2cc.png)
published_atの値は空なので記事公開日時のフォームには何の年月日も表示されません。


現状は`更新する`ボタンを押すとpublished_atの値が空のまま記事が投稿される…という状態でして、`published_at`を記事に持たせるためにどういった仕様にしたらいいか、悩んでいます🤔

> 記事公開日時は普段は隠しておいて、変更したいときだけ表示させる、という UI にしたいと思いました。

とのことでしたので、
(1) 記事公開日時を特に変更する必要がなければ、常に`更新する`ボタンを押したその時点の日時を自動で記事投稿日時にする

**Comment by pachikuriii** [comment]
本番環境でご確認いただきました。closeとさせていただきます〜🙆‍♀️
