### ISSUE TITLE
RegularEvent関係のScheduler::DailyControllerのテストがないので書く

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5566]
下記の部分がテストされてなくて、上部の実行に影響してしまっているのでテストを書きたい。

<s>https://github.com/fjordllc/bootcamp/blob/main/app/controllers/scheduler/daily_controller.rb#L16-L20</s>

https://github.com/fjordllc/bootcamp/blob/main/app/controllers/scheduler/daily_controller.rb#L26-L32

**Comment by shucream-p** [comment]
@komagata
お疲れ様です。issueについて一点質問です。

現在descriptionの指定がこの部分に当たっているのですが
```ruby
User.retired.find_each do |retired_user|
  if retired_user.retired_three_months_ago_and_notification_not_sent?
    User.admins.each do |admin_user|
    NotificationFacade.three_months_after_retirement(retired_user, admin_user)
    retired_user.update!(notified_retirement: true)
```
issueのタイトルは「RegularEvent関係のScheduler::DailyControllerのテストがないので書く」となっているので、`notify_tomorrow_regular_event`の中身のことをおっしゃってるのでしょうか？

ご確認お願いいたします🙇‍♂️

**Comment by komagata** [comment]
@shucream-p すみません、revisionを指定してなかったので昔のURLになってしまっていました。正しくは下記です。
https://github.com/fjordllc/bootcamp/blob/main/app/controllers/scheduler/daily_controller.rb#L26-L32

**Comment by shucream-p** [comment]
@komagata
ご確認ありがとうございます。
ちなみにこちらとは別にテストが必要ということでしょうか？
https://github.com/fjordllc/bootcamp/blob/main/test/notifiers/discord_notifier_test.rb#L65-L90

**Comment by komagata** [comment]
@shucream-p はい。以前にこの部分でエラーが起きたのでSystem Testの観点からテストが欲しい感じです。

**Comment by shucream-p** [comment]
@komagata
ご確認ありがとうございます！
かしこりました！

**Comment by shucream-p** [comment]
📝 質問タイムでkomagataさんに教えていただいた内容
- disocordの通知テストはAbstractNotifierの`delivery_mode`を`:test`にして行う。
```ruby
AbstractNotifier.delivery_mode = :test
```
https://github.com/palkan/abstract_notifier#delivery-modes
- 値は`AbstractNotifier::Testing::Driver.deliveries`（同期処理）、`AbstractNotifier::Testing::Driver.enqueued_deliveries`（非同期処理）に格納される。

**Comment by shucream-p** [comment]
@komagata 
お疲れ様です。ミーティングでもお話しさせていただいたdiscordの通知テストについて質問です。

`AbstractNotifier::Testing::Driver.deliveries`の中身をシステムテストではなく、`/scheduler/daily`にアクセスした際に実行されるメソッド内で確認したところデータが入っていることが確認できました。
システムテスト内では中身が空だったので疑問に思い、gemを確認したところ`AbstractNotifier::Testing::Driver.deliveries`は`Thread.current[:notifier_deliveries]`を参照しているようでした。
https://github.com/palkan/abstract_notifier/blob/master/lib/abstract_notifier/testing.rb#L8

デバッグしてみると実行されるメソッド内とシステムテスト内では参照している`Thread`が違ったのですが、テスト内でも`AbstractNotifier::Testing::Driver.deliveries`で通知内容を確認することは可能なのでしょうか？

**Comment by komagata** [comment]
@shucream-p なるほど〜、Thread.currentを見ているならsystem testで確認するのは無理そうですね。
ではmodeを`:normal`にしてwebmockとかを使うのがいいかもです。（FBCではvcrも使っているのでそちらもでOKです）

**Comment by shucream-p** [comment]
@komagata 
ご確認ありがとうございます！
かしこまりました。その方向で進めてみます。

**Comment by shucream-p** [comment]
テストを作成したPRがmainにマージされましたので、issueをcloseいたします。
