### ISSUE TITLE
[アンケート]アンケート編集で質問を並び替えられるようにする

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5568]
管理者でログインをして http://localhost:3000/surveys/ にアクセス。

アンケート一覧があるので、どれか選んで編集をクリック。

編集画面にある、

<img width="977" alt="貼り付けた画像_2023_01_18_22_51" src="https://user-images.githubusercontent.com/168265/213188775-f725a7c9-1505-4aa4-a2a8-df1ebb2f7de9.png">

この質問のリストをドラッグアンドドロップで並び替えられるようにしてほしい。

**Comment by AyakaTakashima** [comment]
@komagata 
お疲れ様です。
こちらのissueは、#4586 で作成したeditで質問を並び替えできるようにするという内容の認識で間違えありませんでしょうか？

**Comment by komagata** [comment]
@AyakaTakashima はい、そうなります〜

**Comment by machida** [comment]
:memo:
https://github.com/fjordllc/bootcamp/pull/5690
こちらの Issue がマージされたら着手、もしくは、このPRからブランチを作る。

**Comment by machida** [comment]
## 並び替えの参考になるページ

管理者でログインして、

<img width="257" alt="貼り付けた画像_2023_01_24_15_41" src="https://user-images.githubusercontent.com/168265/214227660-ef256c82-c813-463a-a5a7-c6caa23afef4.png">

管理ページへ。

<img width="951" alt="貼り付けた画像_2023_01_24_15_41" src="https://user-images.githubusercontent.com/168265/214227726-f1fdf129-6e3f-4329-b574-675a9243c377.png">

コースタブを開き、これをクリック。

<img width="932" alt="貼り付けた画像_2023_01_24_15_42" src="https://user-images.githubusercontent.com/168265/214227803-e8561561-5522-42a8-8a94-34855fe49eba.png">

このアイコンをドラッグアンドドロップすると並び順が変えられます。

**Comment by sadanora** [comment]
@komagata @machida 
おつかれさまです。

ドラッグアンドドロップ機能を実装するにあたり、以下どの方針が適当でしょうか？
1. Vueで実装する
1. Reactで実装する
1. Vanilla JSで実装する

machidaさんから並び替えの参考ページとして紹介いただいた、コースのプラクティス並び替え機能部分はVueで実装されていると思います。素直に同じように実装するなら、このissue内でアンケートページをVue化することになるのかな？と思いました。
ただ現状bootcampアプリはVueからReactへ移行の最中だと思いますので確認させてください。
そもそも的外れな質問してるようであればご指摘お願いいたします:bow:

**Comment by komagata** [comment]
@sadanora 

2, 1, 3の順番で望ましいですが、Reactを一から勉強するのは大変なのでその場合は1でも大丈夫です〜

**Comment by sadanora** [comment]
@komagata 
ご回答ありがとうございます！

ちょうどいま自作サービスの技術検証の一環でReactを学習中でした。
Reactでの実装が手に負えなそうならVueに切り替えることも頭に入れつつ、一旦Reactでチャレンジしてみたいと思います〜

**Comment by sadanora** [comment]
@komagata  
こちらReactの実装にチャレンジしていましたが、結果的にVanilla JS(SortableJS)で実装しました。

cocoonやchoicesjsなどのライブラリやRailsの機能をしっかり使っているフォームをReact化するのが今の自分には難しすぎたというのが理由ですが、いくつかReactでのdnd実装方法を調べたところ[^anchor]、dndのロジックは結構自前で書く必要があって複雑になりそうだなというのもありReactでの実装は諦めました。

また、コースのカテゴリ並び替えはVue(vuedraggable)で実装されていると思っていましたが#4890 でvuedraggableからSortableJSに移行した経緯を知ったので、このissueでもSortableJSを使った実装としました。

[^anchor]:[同時編集可能なドラッグアンドドロップによる並び替えを実装する \| Wantedly Engineer Blog](https://www.wantedly.com/companies/wantedly/post_articles/386188)など

**Comment by sadanora** [comment]
@komagata @machida 
当issueの機能が本日リリースされましたが、動作確認にメンター以上の権限が必要になるためお手数ですが本番での動作確認をお願いいたします:pray:

## 確認手順
1. メンターまたは管理者権限をもつアカウントでログイン
2. アンケートの質問並び替え画面(`/surveys/:id/survey_questions`)でドラッグ&ドロップで質問が並び替えられることを確認する
3. アンケート画面(`/surveys/:id/`)に並び替えた質問の順番が反映されていることを確認する

**Comment by machida** [comment]
@sadanora 本番で確認できましたー🙆‍♂️ 対応ありがとうございます！！
