### ISSUE TITLE
参考書籍一覧で、書籍が何かしらのプラクティスで必読だったら、必読マークを表示する。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5571]
参考書籍一覧 `/books`
各書籍が何かしらのプラクティスで必読だったら、必読マークを表示する。

<img width="355" alt="貼り付けた画像_2022_09_22_11_03" src="https://user-images.githubusercontent.com/168265/191642142-30fc4995-9b68-4c8e-bb30-41e486b64a4f.png">

**Comment by hikarook94** [comment]
本番環境で確認したのでCloseします。
