### ISSUE TITLE
管理者がアドバイザーの所属企業を変更できない

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5589]
管理者でログインし、アドバイザーユーザーの個別ページに行き、登録情報を管理者権限で変更。

<img width="908" alt="貼り付けた画像_2022_09_26_7_01" src="https://user-images.githubusercontent.com/168265/192167537-fa64d65b-14fe-4979-960f-35a0ab4a3d96.png">

この所属企業を変更して保存をしても、内容が更新されない。

<img width="631" alt="貼り付けた画像_2022_09_26_7_03" src="https://user-images.githubusercontent.com/168265/192167581-7d0f5b95-fac5-4d34-a7ae-26021d9c9a33.png">

このバグの修正をお願いします。

**Comment by lanactindi** [comment]
@komagata こちらを動作確認していただいてもよろしいでしょうか。

**Comment by lanactindi** [comment]
確認できたのでcloseします！
