### ISSUE TITLE
管理者が見る相談部屋一覧で、退会したユーザーだった場合はリンクの色を変えたい（リンクに `is-inactive` の class を付ける）

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5590]
管理者でログインし、`/talks` にアクセス。

相談部屋一覧が表示される。

<img width="875" alt="貼り付けた画像_2022_09_26_7_45" src="https://user-images.githubusercontent.com/168265/192168963-ef648092-a9b9-43f5-9885-8d2fc992e158.png">

全て、未返信のタブがあるが、どちらの一覧でも、ユーザーが退会している場合は、

<img width="691" alt="貼り付けた画像_2022_09_27_17_45" src="https://user-images.githubusercontent.com/168265/192478848-016560e7-636c-4505-8d36-5ccd8317feda.png">

このリンクに、`is-inactive` という class が付くようにしてほしい。

<img width="1212" alt="貼り付けた画像_2022_09_27_17_47" src="https://user-images.githubusercontent.com/168265/192479385-7c136b69-a8ed-4303-bd85-a597e2a37c96.png">

デザインが machida がやります。

**Comment by komagata** [comment]
@machida 退会した人はアイコン画像の装飾でわかるようにするとかはどうですかね？（他の場所でも同じく）

**Comment by komagata** [comment]
@machida なるほどです、いいと思います〜！
