### ISSUE TITLE
newspaperの設定ファイル名のtypo

### ISSUE THREAD

**Issue by eatplaynap** [fjordllc/bootcamp#5592]
## 概要

[bootcamp/newspaer\.rb at main · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/blob/main/config/initializers/newspaer.rb)

↑のファイル名は`newspaer.rb`ではなく`newspaper.rb`が正しいのでは？と思いました。
参考: [komagata/newspaper](https://github.com/komagata/newspaper#usage)

**Comment by komagata** [comment]
@eatplaynap バグIssue登録ありがとうございます！
PRも歓迎です！

**Comment by eatplaynap** [comment]
mainに反映されたことを確認したのでcloseします。
