### ISSUE TITLE
退会したユーザーアイコンに `is-retired` の class を付け、退会ユーザーだとわかるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5596]
## やってほしいこと 1

<img width="82" alt="image" src="https://user-images.githubusercontent.com/168265/192480378-dabb1668-6441-4218-8b5e-c2cd3c71d873.png">

ユーザーアイコンのimgタグには、user class が設定されている。

<img width="1322" alt="貼り付けた画像_2022_09_27_17_52" src="https://user-images.githubusercontent.com/168265/192480592-53903894-9853-495e-8ec3-e20499630599.png">

この例だと、現役受講生なので、`is-student` という class がついている。

### user class 一覧

- 現役受講生... is-student
- 管理者... is-admin
- メンター... is-mentor
- アドバイザー... is-adviser
- 研修生... is-trainee
- 卒業生... is-graduate

ユーザーの状態や role に応じてこのような class が付く。
退会ユーザーの class がまだないので、退会ユーザーには、`is-retaired` という class を付くようにしてほしい。

- 退会ユーザー... is-retaired

## やってほしいこと 2

ここで、ちょっと厄介なやつもお願いしたいです。
現在はユーザーアイコンのimgタグに class がついていますが、 HTML の構造を変更していただきたいです。

```html
<img title="ユーザー名" alt="ユーザー名" src="アイコン画像パス" class="a-user-icon is-graduate">
 ```

という構造になっています。これを以下のように変更していただきたいです。

```html
<span  class="a-user-role is-graduate">
  <img title="ユーザー名" alt="ユーザー名" src="アイコン画像パス" class="a-user-icon">
</span>
 ```

このように、img を span タグで囲い、その span タグに `a-user-role ` という class と user class を付けて欲しいです。

**Comment by OdenTakashi** [comment]
@machida 
付与するクラスについて一点質問させていただきたいです🙏

ダッシュボード上トップページのユーザーアイコンのimgタグに３つのクラスが付与されていました。(スクリーンショットではkomagataでログインしています)
- `card-list-item__user-icon`クラス
- `a-user-icon`クラス
- `is-admin`クラス
<img width="1060" alt="スクリーンショット 2022-11-17 15 58 20" src="https://user-images.githubusercontent.com/81839214/202377915-e6f8dab7-93e5-45b8-887b-382ab8d5cf88.png">

やってほしいこと２で以下のような例が記述されているのですが、
imgタグには`card-list-item__user-icon`クラスが付与されておらず`a-user-icon`クラスのみが付与されています。

```html
<span  class="a-user-role is-graduate">
  <img title="ユーザー名" alt="ユーザー名" src="アイコン画像パス" class="a-user-icon">
</span>
```

そこで質問なのですが、実際にimgタグに付与するクラスは例でやってほしいこと２で記述されているクラスのみという解釈で問題ないでしょうか。？

**Comment by machida** [comment]
@OdenTakashi 

すいません、オプションで追加する class について抜けてました。

```slim
= render 'users/icon',
  user: user,
  image_class: 'a-user-icon',
  link_class: 'card-list-item__user-icons-icon'
```

現在はこんな感じで、link_class に指定があると、img にその class も付くようになっています。
その指定がなくても、a-user-icon は img に必ず付くようになっています。
この仕様はそのままでお願いします。

is-admin などの role の class は span タグに付くようにお願いします🙏

---

この変更に関する部分は、slim だけでなく、vue に関わるところもあります。
今回の Issue は slim の部分だけの対応でお願いします🙏

**Comment by OdenTakashi** [comment]
@machida 
ご返信ありがとうございます🙏

そのような仕様になっているのですね🤔
なるほどです！承知しました！👍

**Comment by OdenTakashi** [comment]
@machida 
度々質問失礼します🙏

付与するクラスについて質問させていただきたいです🤲

## 状況
マイプロフィールページのコメントページにてユーザーアイコンのimgタグにis-admin などの role の class が付与されていませんでした。(この時のURLは`http://localhost:3000/users/459775584/comments`です)

<img width="1440" alt="スクリーンショット 2022-11-25 14 05 11" src="https://user-images.githubusercontent.com/81839214/203905240-99e55603-a722-4036-a766-c09991ef173e.png">


<img width="1069" alt="スクリーンショット 2022-11-25 14 00 40" src="https://user-images.githubusercontent.com/81839214/203904668-a8c65bb9-97c2-490f-ad5f-bfbb24009c00.png">

## 質問
imgタグをspanタグで囲む際にspanタグにis-admin などの role の class を付与した方がよろしいでしょうか、それともこのアイコンはspanタグで囲まない方がよろしいでしょうか？

**Comment by machida** [comment]
@OdenTakashi 提案ありがとうございます！
その部分、付け忘れなので、今回の作業でそこにもクラスを付ける作業をお願いします🙏

**Comment by OdenTakashi** [comment]
@machida 
ご返信ありがとうございます！
承知しました！

**Comment by OdenTakashi** [comment]
本番環境で動作確認が取れたためcloseします
