### ISSUE TITLE
休会しようとすると、エラーになり手続きをすることができない

### ISSUE THREAD

**Issue by AyakaTakashima** [fjordllc/bootcamp#5598]
## 概要

#5461　こちらのPRで見つけました。
`http://localhost:3000/hibernation/new`から、「休会する」ボタンを押した後にエラーになる。

エラー画面は下記。

## 再現手順

1. `feature/comeback_check`ブランチを取り込む
2. `rails s`でローカルを立ち上げる
3. `http://localhost:3000/hibernation/new`にアクセス
3. 必須項目を入力し、「読みました」のチェックボックスをクリック
4. 「休会する」ボタンをクリック
3. エラーが表示される

## 期待される振る舞い

休会手続きが実行される。

## スクリーンショット

![image](https://user-images.githubusercontent.com/76944527/192504611-f77b9411-fefa-450f-830d-4bdfe3635bde.png)

## 環境

 - OS: macOS Monterey
 - ブラウザ: chrome
 - バージョン: 105.0.5195.125（Official Build） （arm64）
![image](https://user-images.githubusercontent.com/76944527/192504860-0ac1a1d3-8302-4a98-9db9-275465be4dc7.png)

## 関連Issue

Ref: #5461

**Comment by AyakaTakashima** [comment]
@komagata @machida 
お疲れ様です！
こちらのissueなのですが、色々な方の日報やPRを参考に、修正しようと試みましたがバグではないかもしれないと感じてきました。

discordの通知のissueをやったことがなかったので、知らなかったのですがステージング環境ではエラーになるのが仕様とのことで理解しました。
手元で、皆さんがやっているのと同じように自分のサーバーを用意し、webhook urlを直で書いたら正常に通知されました。
```rb
class DiscordDriver
  def call(params)
    Discord::Notifier.message(
      params[:body],
      username: params[:name],
      url: '自分のサーバーのwebhook_url'
    )
  end
end
```

discord通知に関するPR（下記参考に記載）をレビューする際の手順にも含まれており、これはバグではないのだと思いましたがいかがでしょうか？
自分で作ったissueだったのでバグであることに自信がないのですが、
issueとして普通に割り振られたのでやっぱりこれはバグなのだろうか...？という風になっており、判断がついておりません。
技術的にも2時間半ほど調べましたが結論がつかず、お聞きしたいです。

ご確認よろしくお願いいたします🙇‍♀️

## 参考
#5480
#5041
#5377
[【589日目】 discord通知について \| FBC](https://bootcamp.fjord.jp/reports/59836)

**Comment by komagata** [comment]
@AyakaTakashima 自分のサーバーで動いたのであれば解決でOKです〜。（調査すること自体がIssueになるのでこれでOKです）

**Comment by AyakaTakashima** [comment]
@komagata 
そうだったんですね！
それではこちらのissueはこれにてクローズしたいと思います🙇‍♀️
ありがとうございました🙇‍♀️
