### ISSUE TITLE
アドバイザーのダッシュボードには GitHub の草は非表示にしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5601]

**Comment by machida** [comment]
@shucream-p 
ごめんなさい、これ、ダッシュボードのリニューアルの際に僕がやっちゃってました🙇‍♂️
代わりに
https://github.com/fjordllc/bootcamp/issues/5724
こちらをお願いします🙏

このIssueは closeしますー

**Comment by shucream-p** [comment]
@machida 
かしこまりました！ありがとうございます🙇‍♂️
