### ISSUE TITLE
アドバイザーは日報作成を非表示にしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5604]
これらをアドバイザーでログインしているときは非表示でお願いします🙏

http://localhost:3000/

<img width="1924" alt="貼り付けた画像_2022_10_26_22_53" src="https://user-images.githubusercontent.com/168265/198044755-f1c27372-a182-49df-a3db-c1edf4c82cbc.png">

---

http://localhost:3000/current_user/reports

<img width="2108" alt="貼り付けた画像_2022_10_28_12_31" src="https://user-images.githubusercontent.com/168265/198496103-c061f328-a82d-44a8-9c38-202607648ded.png">

**Comment by shucream-p** [comment]
本番環境で確認いただいたのでCloseします。
