### ISSUE TITLE
[ダッシュボード]自分の日報にリンクを追加

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5605]
ダッシュボードトップ

<img width="2337" alt="貼り付けた画像_2022_09_29_16_17" src="https://user-images.githubusercontent.com/168265/192965346-1dd7ae39-7d4a-45bf-93df-a4c447f48e06.png">

自分の日報

<img width="2344" alt="貼り付けた画像_2022_09_29_16_17" src="https://user-images.githubusercontent.com/168265/192965497-f5be2fe2-bfce-4fff-9331-7bb75851e211.png">

自分の日報にも、マイプロフィールのボタンを出したい

**Comment by OdenTakashi** [comment]
本番環境で確認が取れましたのでcloseします！
