### ISSUE TITLE
[ダッシュボード]ブックマークにリンクを追加

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5608]
ダッシュボードトップ

<img width="2337" alt="貼り付けた画像_2022_09_29_16_17" src="https://user-images.githubusercontent.com/168265/192965346-1dd7ae39-7d4a-45bf-93df-a4c447f48e06.png">

ブックマーク

<img width="2348" alt="貼り付けた画像_2022_09_29_16_24" src="https://user-images.githubusercontent.com/168265/192967078-0c0e95f7-ddf9-47f0-ae42-d02cb85080c2.png">

ブックマークにも、マイプロフィールのボタンと日報作成のボタンを出したい

**Comment by shucream-p** [comment]
本番環境で動作確認できましたので、こちらのissueをcloseさせていただきます。
