### ISSUE TITLE
ユーザー一覧の期生別のタブにroleごとのフィルターが欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5609]
`/generations` にアクセス。

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/168265/193101864-5b8f7c2f-270f-45c7-b8c6-8022cf1ff28a.png">

ここに、

<img width="859" alt="image" src="https://user-images.githubusercontent.com/168265/193102053-ccc02989-1d3a-47ad-921e-bc4c2703ced0.png">

これを付けたい。

さらに、管理者でログインした場合のみ、

<img width="859" alt="貼り付けた画像_2022_09_30_2_31" src="https://user-images.githubusercontent.com/168265/193102196-3d8f4fee-0296-4c3c-9b1e-b01f8a474e70.png">

退会者で絞り込むリンクを表示し、そのリンク先は、管理者でしか見れないようにしてほしい。

**Comment by fuwa-syugyo** [comment]
@machida 
お疲れ様です！
仕様について、2点確認させていただきたいです。
1. roleごとのフィルターでユーザーを絞り込んだ後の画面(generationsのshow画面)で、「◯期生」をクリックした後の画面でも、ユーザーについてroleごとの絞り込みは有効のままということで合っていますでしょうか？
2. generationsのshow画面にも同じroleごとのフィルターは不要で大丈夫でしょうか？

お手数ですがご確認よろしくお願いいたします。

◯generationsのshow画面に遷移するリンク
![image](https://user-images.githubusercontent.com/62344131/201476405-0af107f7-a0f7-4273-be13-6c4912d76760.png)

◯現在のgenerationsのshow画面
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/62344131/201476585-cc9ed01b-24ca-41a9-9289-f252080e4736.png">

**Comment by machida** [comment]
@fuwa-syugyo 質問ありがとうございますー
showに行ったときの挙動は別Issueで対応しようと思います。今回はshowに行ったときは従来のままでお願いします。
なので、ちょっと現状では少し変な仕様になりますが、退会ユーザーで絞り込んだ後も、showの行き先は従来のshowのまま(退会ユーザーは非表示の一覧へ行く)でお願いしますー

**Comment by fuwa-syugyo** [comment]
@machida 
showの挙動は従来通りということで承知いたしました！
ご確認ありがとうございます〜

**Comment by fuwa-syugyo** [comment]
@komagata @machida 
お疲れ様です！
管理者権限で本番環境の確認をお願いしてもよろしいでしょうか…？

## 確認手順
1. ユーザー一覧ページ( https://bootcamp.fjord.jp/generations )にアクセスする
1. 「退会」フィルターをクリックして退会ユーザーが表示されていることを確認する

お手数ですがよろしくお願い致します。

**Comment by machida** [comment]
@fuwa-syugyo 確認しましたー🙆‍♂️

**Comment by fuwa-syugyo** [comment]
本番環境で確認しましたのでcloseします。
