### ISSUE TITLE
通知メッセージが集約されていることを分かりやすくする

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5615]
状況の調査を含めて修正をお願いします。

- https://discord.com/channels/715806612824260640/828456619028381726/1025552876162011288
- https://discord.com/channels/715806612824260640/828456619028381726/1025553358385320036

**Comment by cafedomancer** [comment]
調査してみたところ、#974 の issue によるものでした。通知が aggregate されること自体はよい気がします。ただ、各 URL に対する最新の一件の通知を見ただけでは aggregate されていることが分からないという、ユーザーに対するコミュニケーション上の問題がある気がしました。

**Comment by cafedomancer** [comment]
> 調査ありがとうございます🙏通知メッセージの内容をケース毎に変更するようにしたいと思いますー

https://discord.com/channels/715806612824260640/828456619028381726/1025924655128793118
