### ISSUE TITLE
新規入会者の通知にroleも表示してほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5620]
<img width="684" alt="貼り付けた画像_2022_10_03_17_24" src="https://user-images.githubusercontent.com/168265/193532673-22ebe8b8-11fa-4ffd-88bb-b4fa38521968.png">

-  一般受講生の場合
    - 今のまま
- アドバイザーの場合
    - 🎉 XXXさん（アドバイザー）が新しく入会しました！
- メンターの場合
    - 🎉 XXXさん（メンター）が新しく入会しました！
- 管理者の場合
    - 🎉 XXXさん（管理者）が新しく入会しました！
- 研修生の場合
    - 🎉 XXXさん（研修生）が新しく入会しました！

**Comment by yamatatsu10969** [comment]
📝
- [ ] 通知の仕組みを理解する
  - [ ] Notification.create! を行うとユーザが画面を開いた時に新規通知が追加されている。prefix: 🎉 
  - [ ] `notification_mailer` で `mail to` を行うとメールでの通知がいく。prefix: [FBC]
- [ ] どうやって通知が送られているか
  - [ ] メール→ `action_mailer` の `mail to` メソッド
    - [ ] user が退会、もしくはメールの設定をオフにしていたらメール送信しない。
  - [ ] 画面での通知 → `Notification.create` or `Notification.new` また、
- [ ] 通知の文言はどこで決まるか
  - [ ] 「さんが新しく入会しました！」で検索する
  - [ ] `notification_mailer.signed_up` ← こちらはメール
  - [ ] `activity_notifier.signed_up` ← 今回はこっち。通知のみ。 
- [ ] 新規入会者の通知をローカルで出すにはどうするか

**Comment by yamatatsu10969** [comment]
@machida 
こちら調査したところ、通知はメールでの件名の通知とフィヨルドの画面での通知の2種類があることがわかりました。
両方の通知にroleを追加した方がよろしいでしょうか？
ご確認よろしくお願いいたします！

**Comment by yamatatsu10969** [comment]
📝
新規入会者がいた場合、メールと fjord の画面に通知が飛んでくる

### メール
![CleanShot 2022-10-23 at 15 34 58](https://user-images.githubusercontent.com/43805056/197377785-d31ebd30-4fc3-40ba-9c68-4ee8756070cc.png)

### 通知
![CleanShot 2022-10-23 at 15 24 38](https://user-images.githubusercontent.com/43805056/197377826-9bcd8510-dd95-4cac-a4ac-bfeb7d2fa71c.png)
