### ISSUE TITLE
OKになった提出物の内容を更新すると、そのプラクティスの自分以外の提出物が見れなくなってしまう。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5637]
## 再現方法

1. 提出物を提出。
1. メンターでログインし、提出物をOKにする。
1. 提出物を提出したユーザーでログインし、OKになった提出物のプラクティスに紐づく自分以外の提出物が見れるようになっているのを確認。
1. 提出物を提出したユーザーでログインしたまま、OKになった自分の提出物の内容を更新する。
1. 更新後、先程まで見れていたOKになった提出物のプラクティスに紐づく自分以外の提出物が見れなくなっているのを確認。この見れなくなってしまっているのがバグです。

**Comment by fuwa-syugyo** [comment]
@machida 
お疲れ様です。
仕様について1点質問させていただきたいです！

OK後の提出物を更新orWIPで保存した場合、プラクティスのステータスを「修了」→「着手」に変更しますか？
ちなみに今の本番環境だと、OK後にWIPで保存した場合は「着手」に切り替わりました。

ステータスは↓のことです。
<img width="784" alt="image" src="https://user-images.githubusercontent.com/62344131/198837785-276c0ffc-631a-406e-ab9b-52c5a50dad09.png">

**Comment by machida** [comment]
@fuwa-syugyo なるほど、ステータスが変わってしまうことに気づいてませんでした！！一度修了になったら、提出物の編集を行ってもステータスは修了のままでお願いしたいです🙏

**Comment by fuwa-syugyo** [comment]
@machida 
ご確認いただきありがとうございます！
一度修了になったら提出物を編集しても修了のままということで承知いたしました。

もう一点確認ですが、OKをもらっていない状態で提出物をWIPで保存した場合は「着手」と「提出」のどちらでしょうか？

**Comment by machida** [comment]
@fuwa-syugyo OKをもらってない場合はWIPにしたときは着手でお願いしますー🙏

**Comment by fuwa-syugyo** [comment]
@machida 
承知いたしました〜！
ご確認ありがとうございます！

**Comment by fuwa-syugyo** [comment]
本番環境で確認しましたのでcloseします〜
