### ISSUE TITLE
卒業生の通知に不要な空白がある

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5661]

**Comment by yamatatsu10969** [comment]
@machida 
こちら詳細を記述していただいてもよろしいでしょうか？🙇‍♂️
事象が確認できずでして。

**Comment by machida** [comment]
@yamatatsu10969 ごめんなさい、こちら僕も確認中で一旦保留でお願いします🙏別のIssue をアサインしておきますー

**Comment by yamatatsu10969** [comment]
@machida 承知しました！アサイン確認できました🙏
アサインいただいたチケットの見積もりがなぜか remove されていたので見積もりもお願いいたします！みんなで見積もるという意図でしたらそのままで大丈夫です！ 
https://github.com/fjordllc/bootcamp/issues/5644

**Comment by machida** [comment]
@yamatatsu10969 見積もりは次回MTGで付けようと思いますー

**Comment by yamatatsu10969** [comment]
machida さんが事象を確認でき次第、着手。

**Comment by machida** [comment]
@yamatatsu10969 すいません、こちら safari だけで起きる変なバグだったので僕の方で対応しました🙇‍♂️
https://github.com/fjordllc/bootcamp/pull/5678/commits/f3eda2963316c0cfd51f1c52645ce8e2bdd30258
diffを見てもわからないのですが、変なスペースが使われてたっぽい。

**Comment by yamatatsu10969** [comment]
@machida 
ご対応ありがとうございます！環境依存だったんですね。
machida さんが対応されたということで承知いたしました！
