### ISSUE TITLE
コードブロックの表示崩れ

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5677]
@machida  確認お願いします〜。
https://bootcamp.fjord.jp/pages/311

<img width="389" alt="Screen Shot 2022-10-26 at 9 59 24" src="https://user-images.githubusercontent.com/1148320/197910077-2d382e04-4f30-4477-a532-0a1452f00b1b.png">

**Comment by machida** [comment]
@JunichiIto ありがとうございます！！こちらすぐ対応します💪
