### ISSUE TITLE
ダッシュボード > ブックマークが 0 のときの表示を変えたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5679]
現在の表示

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/168265/197923732-1083278f-53d9-41ab-9935-e80965d0bfbd.png">

---

こうしたい（Watch中のタブの中を参考に）（編集のスイッチも非表示にする）

<img width="751" alt="image" src="https://user-images.githubusercontent.com/168265/197923838-9372fbf5-476d-48dc-8d5b-f0e56b796f61.png">

**Comment by peno022** [comment]
@machida @komagata 

おつかれさまです！一点質問させてください。
ダッシュボード内で、ブックマーク一覧画面だけReactにしている背景って何があるのでしょうか？
[ブックマーク一覧をReact化 by komagata · Pull Request #5658 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5658)

**Comment by peno022** [comment]
@machida @komagata 
追加で質問です🙏
`test/system/current_user`配下に、`bookmarks`のテストだけが無いので、作成しようと思いますが問題ないでしょうか？

（`test/system/bookmark/products_test.rb` `test/system/bookmark/page_test.rb`はあるのですが、ブックマーク画面の挙動（編集ボタン・削除ボタンなど）のテスト等は書かれていなかったため、提出物・Docs画面側のbookmarkボタンの動作のテストという位置付けに見えました。）

**Comment by komagata** [comment]
@peno022 

> ダッシュボード内で、ブックマーク一覧画面だけReactにしている背景って何があるのでしょうか？

最終的には全部Reactにする予定で、まだできていない状態というのが経緯です。

> test/system/current_user配下に、bookmarksのテストだけが無いので、作成しようと思いますが問題ないでしょうか？

問題ありません。書いていただければ非常にありがたいです〜！

**Comment by peno022** [comment]
@komagata 
ご確認ありがとうございます〜承知しました！
ちなみに、React化自体の目的はどんなものなのでしょうか？

**Comment by komagata** [comment]
@peno022 Vue.jsからReactにフレームワークを変えようとしています。

理由は、スクールとしてカリキュラムでは普及率の高いReactに変えようとしているので終盤課題ので利用するこのプロジェクトもReactにしたいからです。

**Comment by peno022** [comment]
本番で確認できたのでクローズします。
![スクリーンショット 2022-12-25 8 42 12](https://user-images.githubusercontent.com/40317050/209453390-3f8b17a2-9034-4ac8-a82d-1ad15f0828ef.png)
