### ISSUE TITLE
Wikiからも検索できるようにしたい

### ISSUE THREAD

**Issue by tosite0345** [fjordllc/bootcamp#569]
## 概要
現在、画面上部に「日報検索」ボックスがありますが、そちらで日報以外にもWikiやコメントなどから検索できるようにできればと思います。
（いわゆる「検索機能の共通化」を実装したいと思います）
<img width="1129" alt="2018-11-01 15 51 19" src="https://user-images.githubusercontent.com/24952964/47837168-57cfef00-ddee-11e8-929b-e591d10a781b.png">

## 展望
- 全てのテキストレコードから検索できるようになる
- 適切な文字長で切って、長すぎる記事を削る
    - 全文を読むには記事をクリックする
- レイアウト崩れの対応
    - 現状、文字列が枠をはみ出している
    - <img width="973" alt="2018-11-01 15 58 53" src="https://user-images.githubusercontent.com/24952964/47837419-50f5ac00-ddef-11e8-8351-44577753707f.png">
- Markdownのフォーマット
    - 画像やリンクがMDのまま表示されている
- カテゴリ別（Wiki・日報・コメント）で更に絞り込めるようにする
- #210 辺りと連携してやるといいかも

**Comment by komagata** [comment]
カンバン上であくまでプロダクトオーナーに対するストーリーとして考えると「機能の共通化」はプロダクトオーナー（主にお客さん）に対してはメリットが伝わらない（内部的な話がメインになる）ので、「Wikiやコメントも検索できるようにしたい」などの方が良さそうです。

**Comment by tosite0345** [comment]
検索対象となるモデルは、現時点で以下のとおりです。
- Report
- Question
- Announcement
- Answer
- Page
- Report
- Practice
- Comment

ここに `Product` も含めるべきか迷いますが、こちらは閲覧可否の問題があるため今回は考えないこととしたいです。
現時点で構想している設計は次のとおりです。
`searchable` として `polymorphic` を定義し、そこに対して `title` `body` をセット、そこから検索をするというのが妥当かな、と考えています。
