### ISSUE TITLE
イベント一覧に定期イベント作成リンクが欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5693]
<img width="2114" alt="貼り付けた画像_2022_10_28_13_38" src="https://user-images.githubusercontent.com/168265/198503896-a2331971-7a64-418d-b5cc-f8b250ba6843.png">

ここに、

<img width="182" alt="image" src="https://user-images.githubusercontent.com/168265/198503955-eadc6e66-7cba-4672-bad1-974ee0f824a5.png">

これを置く。

**Comment by sadanora** [comment]
本番で動作確認ができたのでcloseします。
