### ISSUE TITLE
定期イベント一覧にイベント作成リンクが欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5695]
<img width="2129" alt="貼り付けた画像_2022_10_28_13_40" src="https://user-images.githubusercontent.com/168265/198504043-1d5e5d9e-c870-42b2-afb9-d561ab67e4bd.png">

ここに、

<img width="166" alt="image" src="https://user-images.githubusercontent.com/168265/198504090-099b532a-2287-49c8-a785-4c730d305847.png">

これを置く。

**Comment by sadanora** [comment]
本番環境で動作確認ができたのでcloseします。
