### ISSUE TITLE
[定期イベント] 定期イベントの内容が更新されたら参加者に通知したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5696]
`/regular_events` 定期イベントページ。

<img width="447" alt="image" src="https://user-images.githubusercontent.com/168265/199172093-215f63e9-5333-4f00-96a7-6fa1e249882f.png">

イベントに参加をすると、Watch中になる。

<img width="861" alt="貼り付けた画像_2022_11_01_15_26" src="https://user-images.githubusercontent.com/168265/199172360-35237119-04b1-4984-9cf4-433b79bb9a5b.png">

もし、イベントの内容に更新があったら（開催日変更や、イベントが終了になったり、説明文が変更になったりなど）、Watch中の人に、定期イベントの内容が更新があったことを通知（メール and サイト内通知）したい。
newspaperを使ってほしい。

**Comment by hikarook94** [comment]
本番環境で確認しましたのでCloseします
