### ISSUE TITLE
日報の保存忘れを極力なくすための対応について

### ISSUE THREAD

**Issue by tosite** [fjordllc/bootcamp#570]
## 概要
#549 を実装可能な形にしたIssueです。

## やること
- 日報画面に `Command + S` で保存できる旨を表示する
- 画面を閉じようとしたら「保存されていませんが移動してもよろしいですか」メッセージを表示させる

**Comment by machida** [comment]
日報のフォームでPCのときだけこれを表示するようにしました。

<img width="773" alt="貼り付けた画像_2021_06_15_11_57" src="https://user-images.githubusercontent.com/168265/121986067-e0013800-cdd0-11eb-8674-03fd54550088.png">
