### ISSUE TITLE
日報一覧画面に「見たよ」の件数を表示したい

### ISSUE THREAD

**Issue by tosite** [fjordllc/bootcamp#571]
## 概要
日報一覧画面など（ `/users/:id/reports` ）から、何人からの「見たよ」があるかを確認できると嬉しいかな、と思いました！
イメージ的にはこのコメント画面の横に `👀10` みたいな表示があれば…という感じです。
今だと日報詳細画面まで飛ばないと確認できないので…。

ご検討よろしくお願いいたします。

<img width="807" alt="2018-11-01 18 53 42" src="https://user-images.githubusercontent.com/24952964/47845217-c9686700-de07-11e8-8b66-973c3a51743c.png">

**Comment by komagata** [comment]
@tosite0345 件数系は多くなった時どう重くならないように実装するか悩みますねー
