### ISSUE TITLE
卒業後のゴールの表示部分を simple_format にしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5713]
管理者でログインしていると、ユーザープロフィールページと自分のダッシュボードに卒業後のゴールが表示されている。

そこが改行など反映されていないので、simple_formatを使って反映されるようにしたい。

simple_format の参考 https://qiita.com/mmaumtjgj/items/1b672f3accd37387b2f3

**Comment by komagata** [comment]
確かに〜🤭

**Comment by OdenTakashi** [comment]
@machida 
修正箇所ついて一点質問させていただきたいです。🙏

`simple_format`にする箇所について確認なのですが

- 管理者でログインを行い、受講生のユーザープロフィール上に卒業後のゴールが表示されている
- 現役生でログインを行うと、自分のダッシューボード上に卒業後のゴールが表示されている

以上の2箇所という認識でよろしいでしょうか。？

管理者でログインを行い、受講生のユーザープロフィール上に卒業後のゴールを確認したところこちらは`simple_format`になっていなかったのですが、
現役生でログインを行いダッシュボード上で卒業後のゴールを確認したところすでに`simple_format`になっているように見えました。

`現役生のダッシュボード`
<img width="645" alt="スクリーンショット 2022-11-05 11 55 34" src="https://user-images.githubusercontent.com/81839214/200097991-b330b5c2-9c85-4d2f-bf7e-258425ea6f8a.png">

`app/views/home/_after_graduation_hope.html.slim`
<img width="1122" alt="スクリーンショット 2022-11-05 11 57 41" src="https://user-images.githubusercontent.com/81839214/200098054-7a6cfeb0-0b4d-4d2c-a7ca-b6e8a1974d90.png">

なので新たに`simple_format`にする箇所は

- 管理者でログインを行い、受講生のユーザープロフィール上に卒業後のゴールが表示されている

箇所だけでよろしいのでしょうか。？

もし私の方で認識の誤りがありましたらご指摘お願いします🙇‍♂️

**Comment by machida** [comment]
@OdenTakashi 対象個所はそれであってますー。すでに対応されてる部分はそのままで、未対応の部分だけ対応お願いします🙏

**Comment by OdenTakashi** [comment]
@machida 
ありがとうございます！🙏
承知しました！
