### ISSUE TITLE
メンター向けユーザーメモが保存できない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5714]
「プロフィールページ」にある「メンター向けユーザーメモ」と「相談部屋」にある「ユーザーメモ」が保存できない。

保存してもリロードすると消えている。

**Comment by machida** [comment]
僕はプロフィールページ、相談部屋からユーザーメモの更新を本番で確認できたので、

- 管理者では保存できず、メンター権限がないと保存できない
- Safari などユーザーの環境によって保存できない

などの原因がありそうです。

**Comment by machida** [comment]
URLが違っていたことが原因っぽいです。

`https://bootcamp.fjord.jp/admin/users/{ID番号}` がユーザー個別ページの正しい URL ですが、
`https://bootcamp.fjord.jp/admin/users/{ID名}` からメンター向けユーザーメモを変更しようとしていたせいで保存ができなかったようです。

原因が特定でき、バグによるものではなかったので、こちらの Issue は Close します。
