### ISSUE TITLE
/users/:user_id/reports/:report_id の「次の日報・前の日報」の挙動がおかしい

### ISSUE THREAD

**Issue by tosite** [fjordllc/bootcamp#572]
## 概要
**詳細画面**
![2018-11-01 19 28 03](https://user-images.githubusercontent.com/24952964/47846759-5d3c3200-de0c-11e8-87cf-a3b610dafdfc.png)
**一覧画面**
![2018-11-01 19 29 42](https://user-images.githubusercontent.com/24952964/47846842-a55b5480-de0c-11e8-9b2a-d784b1dffcbb.png)

上記、詳細画面の「前の日報」「次の日報」の順が一覧画面の順になっておらず、挙動がおかしいようです。
順序が入れ替わっているだけでなく、スキップされるもの・順序が変わるものなどがあります。

`app/models/report.rb` 内のメソッド、 `previous` と `next` のSQL部分に問題があると思っています。

別Issueとして立てました。
急ぎ対応したいと思います。

**Comment by ima1zumi** [comment]
Merge 済のため Close します。
