### ISSUE TITLE
定期イベントが登録できない

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5727]
定期イベントを登録しようとしたらエラーが出たので、原因を探りつつ、修正をお願いします🙏

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/168265/200489420-98af7083-8c13-4b86-b36a-0ba16afb1519.png">

**Comment by hikarook94** [comment]
@machida 
お疲れ様です！
エラーがローカル環境で再現しなかったので、擬似的にステージング環境をローカルで再現して検証してみました。
修正案も考えてみたのですが、確認はどのように行えばいいでしょうか？

## 原因について
このエラーはおそらく以下の部分が原因だと思われます。
- #5286 のIssueの通り、development環境以外では画像のアタッチメントがされないようになっている
https://github.com/fjordllc/bootcamp/blob/36ee3a0dcefe84e475f884887d0e344c02bc4d9e/db/seeds.rb#L51
- メンターアカウントの場合はプロフィール画像がアタッチメントされているかのバリデーションが存在する
https://github.com/fjordllc/bootcamp/blob/36ee3a0dcefe84e475f884887d0e344c02bc4d9e/app/models/user.rb#L165-L169
- 定期イベント登録時にUserに対してバリデーションが走る
（参考）https://github.com/fjordllc/bootcamp/pull/4862#discussion_r889808022

## 修正案
`regular_event.rb`の`has_many :users, through: :organizers`に`validate: false`を追加して定期イベント登録時にuserのバリデーションを行わないようにする
```ruby
# regular_event.rb
  has_many :users, through: :organizers, validate: false
```

## 試したこと
### ローカル環境ではエラーが再現しなかった
- 画像の通りの定期イベントの設定情報で試したところエラーは出なかった（主催者にメンターを指定してもエラーが出なかった）

### ステージング環境でエラーを確認
- 主催者にメンターを指定した場合エラーが出た
- 主催者をkimuraにしたら登録できた

### 本番環境ではエラーが再現しなかった
- 画像の通りの定期イベントの設定情報で試したところエラーは出なかった（主催者にメンターを指定してもエラーが出なかった）

### ローカル環境でエラーを再現
ステージング環境と同様、画像がアタッチメントされないように`seeds.rb`を以下をコメントアウトしてセットアップ
```ruby
# Bootcamp::Setup.attachment if Rails.env.development?
```
この状況で、
- 主催者にメンターを指定して定期イベントを登録しようとしたらエラーが出た
- プロフィール画像がアタッチメントされているかのバリデーションを削除したところ、エラーが出なくなった
- regular_event.rbを`has_many :users, through: :organizers, validate: false`に変更したところ、エラーが出なくなった

**Comment by machida** [comment]
@hikarook94

原因の調査、修正案ありがとうございます！！こちら、komagataさんに修正案の確認お願いしたいですー

> 確認はどのように行えばいいでしょうか？

確認とは修正案について？修正後の修正されたことの確認？何についての確認になりますでしょうか？
確認について、komagataさんに連絡をお願いします🙏

@komagata 修正案の確認をお願いします🙏

**Comment by hikarook94** [comment]
@machida @komagata 
> 確認とは修正案について？修正後の修正されたことの確認？何についての確認になりますでしょうか？
確認について、komagataさんに連絡をお願いします🙏

説明不足ですみません🙏 以下をお願いします！
- 修正方法や原因調査の妥当性について、何か見落としや問題があればご指摘をお願いします！
- 修正中や修正後の動作確認の方法を教えてください！
厳密にはステージング環境でしかエラーが再現できない状況だと思っています。修正のPRはとりあえずmainにマージして、ステージング環境で動作を確認していくということでしょうか？

**Comment by komagata** [comment]
> 厳密にはステージング環境でしかエラーが再現できない状況だと思っています。

@machida さんがIssueを作った原因となった件は本番環境で起きたことなのかなと思うのですが、いかがでしょうか？

(CC: @hikarook94 )

**Comment by hikarook94** [comment]
@machida 
お疲れ様です！
このバグが起きた時の手順・環境を詳しく教えていただけますでしょうか？（具体的に項目立てできずすみません...）

**Comment by machida** [comment]
@hikarook94 

はい！説明しますー

1. Chrome の最新でブートキャンプにアクセス
1. machida（管理者 / メンター）でログイン
1. 定期イベント作成ページへ
1. 質問・雑談タイムの内容を入力
    1. タイトルを「質問・雑談タイム」に設定
    1. 主催者を komagata に設定（machida は入れてない）
    1. 開催日を毎週 月・水・金 に設定
    1. 時間を 16:00 〜 17:00 に設定
    1. 祝日の開催 はチェックなし
    1. 詳細を記入
    1. イベントが終了した場合 はチェックなし
1. 「作成」ボタンをクリック

...でエラーが出ましたー

**Comment by hikarook94** [comment]
@machida 
ありがとうございます！ちょっと確認してみます！

**Comment by hikarook94** [comment]
@machida 
操作手順の提供ありがとうございました！僕のアカウントで同様にやってみたところ正常に登録できました...🤔

もう少し原因を探りたいので、以下のパターンで定期イベントを登録してみてどうなるか確認していただいてもいいでしょうか？
- 主催者をHikaru（一般のユーザー）にして登録する
- 主催者をメンターにして登録する

**Comment by machida** [comment]
@hikarook94
やってみました！

主催者 Hikaruのみ...作成できた

主催者 Hikaru、komagata...作成できた

主催者 komagataのみ...作成できた

作成できました！

**Comment by machida** [comment]
@hikarook94 前はエラーが起こったのに、今は大丈夫でした。最初にkomagataを主催者にして作成しても、最初はHikaruを主催者にして、後からkomagataを追加したり、komagataだけにしてもOKでした。

**Comment by hikarook94** [comment]
@machida 
早速ありがとうございます！

> 最初にkomagataを主催者にして作成しても

このパターンは、このIssueを作ったきっかけの不具合と同じパターンってことですかね？

**Comment by hikarook94** [comment]
@machida 
そうですよねえ...謎だ🤔 
登録のタイミングが関係しているのでしょうか...
関係がありそうなものが正直思いつかないです...何かヒントをいただけると嬉しいのですが😵

**Comment by machida** [comment]
@hikarook94 前回のデプロイで何か関連するところが更新されて、定期イベントも直ったのかもしれないですね。一応前回のデプロイのdiffを見てみてください🙏もし、関連してるところがなくても、まぁ、解決してしまったのでIssueはクローズにしたいと思います。

**Comment by hikarook94** [comment]
@machida 
わかりました！確認してみます！
Issueクローズも承知しました🙆‍♂️

**Comment by komagata** [comment]
@hikarook94 (CC: @machida ) 上記の流れ確認致しました。問題ございません〜。

**Comment by hikarook94** [comment]
不具合が再現しなくなったのでIssueをCloseします。
（前回デプロイ時の差分を調査してみましたが、原因箇所について特定することはできませんでした。）
