### ISSUE TITLE
進行中のプラクティスがあるメンターのダッシュボードのGitHubの草のデザインが崩れている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5730]
https://discord.com/channels/715806612824260640/828456619028381726/1037999138052247613

<img width="1076" alt="Screen_Shot_2022-11-04_at_16 57 21" src="https://user-images.githubusercontent.com/16577/200089341-3c57b584-a799-4b73-9a1c-f0906288e336.png">

**Comment by komagata** [comment]
@machida すみません、こちらお願いできればありがたいです〜

**Comment by machida** [comment]
こちら修正済みだったのでcloseしますー
