### ISSUE TITLE
管理者権限でユーザー情報変更ページから一般受講生を「研修生」に変更できない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5731]
「研修生」は「所属企業」が必須となっているが、研修生になる前のページなので所属企業が選択できない。
「研修生」のチェックボックスがONになったらJavascriptで所属企業が表示されるようにすると良さそう。

**Comment by yamatatsu10969** [comment]
📝 以下を表示するようにする
![CleanShot 2022-11-08 at 22 42 57](https://user-images.githubusercontent.com/43805056/200580356-5ddd677c-6116-486b-87de-644329877234.png)

**Comment by yamatatsu10969** [comment]
📝
- 「所属企業」の項目を複数出さないようにする
- チェックボックスにチェックがついてるかどうかで、表示を切り替える方法がわからない
- :trainee で研修生かどうかを判断してる
- `users/form/company` の form を使って表示している
-

**Comment by akingo55** [comment]
@machida 
こちらのIssueは、管理者で一般ユーザーを研修生に変更するとき、所属企業が選択できるようにするってことでしょうか？
開発環境でみたところ、研修生のチェックいれると企業を選べるようになってました🤔
![image](https://user-images.githubusercontent.com/43959158/212472062-78390978-fee2-465f-96a5-698d21381312.png)

**Comment by machida** [comment]
@akingo55 

<img width="654" alt="貼り付けた画像_2023_01_16_0_53" src="https://user-images.githubusercontent.com/168265/212551423-efa545e0-63d2-4eec-9488-a326a12e73ec.png">

研修生にチェックを入れても出てこないんですよね。
チェックを入れた状態で更新をすると、

<img width="609" alt="image" src="https://user-images.githubusercontent.com/168265/212551506-78f47289-b63c-404d-9062-66ba9d494f19.png">

エラーが出ます。

<img width="606" alt="image" src="https://user-images.githubusercontent.com/168265/212551576-faa52c45-e059-4cf5-8638-6fca58d9400c.png">

エラーを出した画面では、所属企業の選択ができるようになります。

---

これをエラーを出さなくても所属企業の選択ができるようにしていただきたいです🙏

<img width="593" alt="貼り付けた画像_2023_01_16_0_57" src="https://user-images.githubusercontent.com/168265/212551668-d8464cb3-27ca-476d-a5f4-8f5757529ff2.png">

ここにチェックを入れると、

<img width="592" alt="image" src="https://user-images.githubusercontent.com/168265/212551695-1587d999-4570-4d27-bbad-b3b3b6d2c4d8.png">

このブロックが表示されるように js で実装をお願いしたいです。

このブロックの位置なのですが、

<img width="601" alt="貼り付けた画像_2023_01_16_0_58" src="https://user-images.githubusercontent.com/168265/212551811-a887c9aa-b7f6-49f6-80f9-110143abff77.png">

現在は管理者のみ操作できます の上にあります。
上にあるものが表示されたり、非表示になったりしても気づかないので、

<img width="614" alt="貼り付けた画像_2023_01_16_0_59" src="https://user-images.githubusercontent.com/168265/212551852-1a39851e-0fa1-4c95-aad6-d8208121786a.png">

この位置に移動していただきたいです🙏

**Comment by komagata** [comment]
@akingo55 完成していたらIssueのCloseをお願いします〜
