### ISSUE TITLE
ユーザー登録から数日後に相談部屋にメッセージを送りたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5746]
一般の生徒の方が登録から30日後のタイミングでそれぞれ相談部屋に

「楽しくできていますか？困っていることはありませんか？」

というメッセージを自動で送りたい。

`/scheduler/daily`
に毎日一回アクセスが来るようになっているのでその辺りで実装するとよさそう。

**Comment by ksmxxxxxx** [comment]
@komagata @machida お疲れさまです。
こちら着手しようと思うのですが、メッセージ文面などはこちらで考えたものを送るで問題ないでしょうか？
もし送りたい文面などありましたら、コメントで明示していただけるとありがたいです〜。

よろしくおねがいします。

**Comment by komagata** [comment]
@ksmxxxxxx 下記でお願いします〜

```
こんにちは、komagataです。
ご登録から30日ほど経ちますが、学習について困っていることや詰まっている部分などありますでしょうか？
もしあればお気軽におっしゃっていただければと思います。
```

**Comment by ksmxxxxxx** [comment]
@komagata ありがとうございます！こちらの文言で進めさせていただきますねー 💪

**Comment by ksmxxxxxx** [comment]
@komagata お疲れさまです。
こちらのIssueについて要件を確認させてほしいです。

https://github.com/fjordllc/bootcamp/pull/5959#discussion_r1057052261

penoさんのコメントで気づいたことなんですが、コメントを送信したいユーザー条件について「入会から30日経過している受講生」とだけ認識していたんですが、なんらかの理由で定期実行がなされずコメントが送信されなかった場合も考慮する必要があるのかなと思いました。
その場合、コメントを送信したいユーザーの条件が以下のようになるのかなと考えます。

- 入会から30日が経過している
- かつ、過去に自動送信のコメントが送信されていない

上記の要件で実装したほうが良いのかな？と考えたんですが……、自分が今考えている **過去に自動送信のコメントが送信されていない**チェックに関してのチェック方法が、`notified_retirement`のように、コメント送信済みかをbooleanでフラグを立てるくらいしか思いつかないです。
ただ、コメント送信済みかどうかでカラムを追加して良いものか？というところが自分としては引っかかっています。
`notified_retirement`でも使われている手法なので、良いかと一瞬思ったんですが、今後似たような要件のたびにカラムを追加するのが果たして一般的なのか……判断ができなかったので、質問させていただきました。

ご教示いただけると助かります。
よろしくお願いいたします 🙇‍♀️

**Comment by komagata** [comment]
@ksmxxxxxx 質問としては下記になりますでしょうか？

> 今後似たような要件のたびにカラムを追加するのが果たして一般的なのか

その通りだと思います〜。

**Comment by ksmxxxxxx** [comment]
@komagata ありがとうございます。
以下の方針で進めようと思います〜

-  「入会から30日が経過しているかつ、過去に自動送信のコメントが送信されていない」受講者にコメントを自動送信
-  #5932 のコメントより、controllerの位置も`/scheduler/daily`に移動

**Comment by ksmxxxxxx** [comment]
@komagata cc: @peno022 

2点相談させてください。

【1つめ】
入会30日経過した受講生の相談部屋にメッセージを送信する by ksmxxxxxx · Pull Request #5959 · fjordllc/bootcamp
https://github.com/fjordllc/bootcamp/pull/5959
こちらのPRで対応中の機能で、送信対象者から休会中の受講生は除外しようと先日の質問タイム（雑談タイム）でお話してた件です。

送信対象者から休会中の受講生はメッセージ送信しないようにすると、もしかしたら**休会処理、休会からの復帰処理にメッセージ送信フラグを変更する処理を追加する必要がある**んじゃないかなぁと気が付きました。
この処理の追加が必要かどうかをお伺いしたいです。

【2つめ】
1つめの処理自体はこのPRで新しく追加したカラムの値をbooleanをひっくり返すだけなので難しくはないと思うんですが、現時点で当該のPRが結構な超大作担ってると思っていて、レビューする側の負担が増えるのが忍びないかなぁなんて思っています。
つまり

- 休会処理と休会からの復帰処理にメッセージ送信フラグを変更する処理を追加する作業を当該のPRで作業する
- 別ISSUEを作成、別PRで実装する
- 当該PRのブランチから派生ブランチを作成し作業→別PRでレビューをしてもらう→作業完了後は当該PRにマージする

上記、いずれの対応をとるかで迷子になっています。
どの対応が良さそうでしょうか？

**Comment by komagata** [comment]
@ksmxxxxxx 

> 【1つめ】

不要です。

送信するときの条件に「休会してない」を追加すればいいと思います。

> 【2つめ】

そこまで複雑な内容ではないのでこのPRで実装して良いです。

**Comment by ksmxxxxxx** [comment]
@komagata なるほど、たしかに「休会してない」条件追加だけでいいですね！
同じPRで作業進めたいと思います〜 👍

**Comment by ksmxxxxxx** [comment]
@machida @komagata 
仕様について確認させてほしいです。

https://github.com/fjordllc/bootcamp/pull/5959#discussion_r1088896038

こちらのPRのコメントで、休会明けの受講生に考慮したほうがいいのではないかというレビューを頂きました。

自分は、入会から29日目で休会→90日後に復帰、91日目に「入会から30日経過しました…」というメッセージがくるのは適切に思えないので、考慮されたほうがいいのかなと考えました。

考慮する場合、仕様を再検討する必要がありそうだと考えています。
自分が考えたのは以下のようなことです。

- メッセージの「入会からn日が経過しました」というメッセージにする
- 入会日から学習日数をカウントして、学習日数が30日目にメッセージを送信するのか？
- 休会日からn日経過してからメッセージを送信するのか？

考慮したほうがいいと思いつつ、仕様面についてはPOの意図なども含めて確認したほうがいいのかなと思いコメントさせていただきました。

お手数かけて恐縮ですが、よろしくお願いします。

**Comment by machida** [comment]
@ksmxxxxxx 返信遅れてすいません🙏
確かに、休会を利用した場合を考慮する必要がありますね。提案ありがとうございます！！

運営としては、
入会してどう？を聞きたいのと同様に、
復帰してどう？を聞きたいと思ってます。

今回実装する入会してn日で質問が飛ぶという機能は、一度でも休会した人には飛ばないようにしたいです。

別Issueで休会から復帰してn日でメッセージを飛ばしたい、に対応したいと思います。

つまり、一度でも休会したら、日数のカウントをやり直す形にしたいです。休会から復帰した時点でカウントを新しくスタートします。

今回の範囲外ですが、メモとして…入会してn日、復帰してn日、nの値は共通でいいかな、と考えています。

**Comment by ksmxxxxxx** [comment]
@machida 
ありがとうございます〜。

- 今回のIssueでは一旦入会日から30日経過した受講生を対象にメッセージを送る仕様ですすめる
  - 休会したひとにはメッセージを送らない
- 別Issueで、休会から復帰した日数をカウントしてメッセージを送る対応をする
  - つまり、今回のIssueでは休会してメッセージが送信されなかったひとについては実装しない

この認識で進めてしまって、大丈夫でしょうか？
（例によって文章の読解に時間がかかる && 理解できてるか心配があるので、指差し確認させてください 🙏 ）

**Comment by machida** [comment]
@ksmxxxxxx 確認ありがとうございます！！その理解で合ってますー🙆‍♂️
