### ISSUE TITLE
相談部屋に管理者にだけブックマーク機能を追加したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5748]

**Comment by shucream-p** [comment]
@machida 
お疲れ様です！
仕様について一点質問です。


<img width="680" alt="スクリーンショット 2022-12-26 21 36 42" src="https://user-images.githubusercontent.com/88083085/209549810-60b2c324-1227-4736-af24-b3f6b1fef8ec.png">




ブックマーク一覧での相談部屋の表示ですが、日報などのようにdescription が無いため、相談のアイコン、〇〇さんの相談部屋（相談部屋へのリンク）、ユーザーリンク、更新日時だけでよろしいでしょうか？

それか相談部屋の一覧のような形で表示するのが良いでしょうか？

<img width="718" alt="スクリーンショット 2022-12-26 21 48 21" src="https://user-images.githubusercontent.com/88083085/209550803-a9a40deb-b4d6-450e-88c7-cdbdfdc318b3.png">

ご回答よろしくお願いいたします🙇‍♂️

**Comment by machida** [comment]
@shucream-p 質問ありがとうございます！！
そうですねー。今回は、

> それか相談部屋の一覧のような形

![image](https://user-images.githubusercontent.com/168265/209635917-5e6783f2-04a1-4ead-a82b-3d29c17e943e.png)

これでお願いします🙏

**Comment by shucream-p** [comment]
@machida 
返信ありがとうございます！
かしこまりました！そちらで実装してみます。

**Comment by shucream-p** [comment]
@komagata @machida 
お疲れ様です！
こちらのPR[#6007](https://github.com/fjordllc/bootcamp/pull/6007)がリリースされましたので、以下の手順で本番環境での動作確認をお願いしたいです。

1. 管理者権限を持つアカウントでログインする
2. 任意のユーザーの相談部屋ページを開く
3. `Bookmark`ボタンがあることを確認する
4. `Bookmark`をクリックし`Bookmark中`に変わることを確認する
5. `/current_user/bookmarks`にアクセスして、ブックマーク一覧に先ほどブックマークした相談部屋が追加されていることを確認する
6. 〇〇さんの相談部屋をクリックして相談部屋に遷移することを確認する
7. トップページに戻り、ダッシュボードの最新のブックマーク一覧に先ほどブックマークした相談部屋が追加されていることを確認する
8. 〇〇さんの相談部屋をクリックして相談部屋に遷移することを確認する
9. 最後に`Bookmark中`をクリックしてブックマークを解除し、/current_user/bookmarksとダッシュボード最新のブックマーク一覧からブックマークを解除した相談部屋が消えていることを確認する

以上です。よろしくお願いいたします🙇‍♂️

**Comment by shucream-p** [comment]
本番環境で動作確認していただいたのでissueをcloseいたします。
