### ISSUE TITLE
イベント作成のタイトル入力のinputにプレースホルダーがほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5749]
<img width="963" alt="貼り付けた画像_2022_11_08_22_13" src="https://user-images.githubusercontent.com/168265/200573939-79091540-9047-40de-a323-d56b86da6856.png">

ここにプレースホルダーで、

```
ミートアップ2022年12月
```

と入れたい。

**Comment by Seakimhour** [comment]
本番環境で動作確認をできましたので、closeさせていただきます！
