### ISSUE TITLE
管理者、メンター、アドバイザー、卒業生でログインしているときは、休会へのリンクを非表示にしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5769]

**Comment by sadanora** [comment]
@komagata @machida
本番での管理者向け機能の動作確認のお願いです:pray:

 - 管理者、メンター、アドバイザー、卒業生いずれかでログイン
 - 右上の「Me」をクリック
 - ドロップダウンメニュー内に「休会手続き」が**ない**ことを確認

お手数ですが上記ご確認のほどよろしくお願いいたします！

**Comment by komagata** [comment]
@sadanora 本番環境で確認しました。OKでした〜！

**Comment by sadanora** [comment]
@komagata 
ご確認ありがとうございました！
このissueはcloseさせていただきます〜
