### ISSUE TITLE
[定期イベント] 定期イベントにコメントができない

### ISSUE THREAD

**Issue by yamatatsu10969** [fjordllc/bootcamp#5777]
## 概要

定期イベントにコメントができない。

## 再現手順

1. /regular_events にアクセス。→ [ステージング環境の定期イベント](https://bootcamp-staging.fjord.jp/regular_events?target=not_finished)
2. 適当な定期イベントをクリック
3. コメントを入力し、「コメントする」をクリック
4. 投稿が完了せずに、「コメントする」ボタンが非活性になった状態のままになる

## 期待される振る舞い

コメントが投稿できる。

## 動画

https://user-images.githubusercontent.com/43805056/201463891-6781bb55-d752-4129-ad68-632455f71489.mp4

## 環境

 - OS: [Mac OS]
 - ブラウザ: [Sidekick(chrome)]
 - バージョン: [Chrome 104.30.579.685]

## 関連Issue

なし

**Comment by komagata** [comment]
直ってるみたいなのでCloseします。

**Comment by machida** [comment]
@komagata 本番で試したらエラーを再現できましたので reopen しますー

https://bootcamp.fjord.jp/regular_events/13
このテストイベントに machida（管理者兼メンター）でコメントをしたところエラーが発生。

<img width="427" alt="image" src="https://user-images.githubusercontent.com/168265/205820403-ac0b213a-4725-4e2f-a118-16ced3ef5ee9.png">

**Comment by komagata** [comment]
:memo:

`app/models/regular_event.rb`と`app/models/concerns/watchable.rb`で`watched?`メソッドがかぶっていることからエラーが起きているようです。

- https://github.com/fjordllc/bootcamp/blob/main/app/models/regular_event.rb#L135
- https://github.com/fjordllc/bootcamp/blob/main/app/models/concerns/watchable.rb#L12

下記でエラーが起きてる。（メソッドが想定していないものに上書きされてしまっているため）

https://github.com/fjordllc/bootcamp/blob/main/app/models/comment/after_create_callback.rb#L43

**Comment by Seakimhour** [comment]
本番で確認できたのでクローズします。
