### ISSUE TITLE
イベントの system test が頻繁に retry されている

### ISSUE THREAD

**Issue by cafedomancer** [fjordllc/bootcamp#5779]
## 概要

https://github.com/fjordllc/bootcamp/blob/5fbbcfc85ecd734b91dd750fd38bb7924484c902/test/system/events_test.rb#L294-L333
https://app.circleci.com/pipelines/github/fjordllc/bootcamp/4239/workflows/42512ce0-69a1-4141-9cad-82619ce73e95/jobs/10851

## 再現手順

不明

## 期待される振る舞い

リトライされずにテストが通る

**Comment by fuwa-syugyo** [comment]
@cafedomancer 
お疲れ様です！
こちらのissueについて何点か質問をさせていただきたいです。
ローカルではテストが問題なく通り、再現ができていません。。

1. いつ頃から発生していますか？(分かる範囲で大丈夫です)
1. 今でも発生していますか？
私が別件でCircleCIを回した際に最終的に通ったものの一度リトライされていたようなので、まだ発生していると思いますが。。
https://app.circleci.com/pipelines/github/fjordllc/bootcamp/4327/workflows/3a79b983-79bb-4509-821b-4ffb7b5029bb/jobs/11179
1. 再度テストを行った際は通りましたか？
1. ローカルではテストが通りましたか？
1. その他、何か心当たりがあれば教えていただきたいです

お手数ですがご確認よろしくお願いいたします。

**Comment by cafedomancer** [comment]
> 1. いつ頃から発生していますか？(分かる範囲で大丈夫です)

うーん分からないです。CircleCI のリトライに関するログを遡って確認してみてください。

> 2. 今でも発生していますか？

こちらも分からないので CircleCI のリトライに関するログを確認してみてください。 

> 3. 再度テストを行った際は通りましたか？

通った気がします (が flaky なテストだと思うので通るか通らないかは確率の問題で、再度テストを行うことと通るかどうかは関係なさそうな気がします) 。

> 4. ローカルではテストが通りましたか？

通るときと通らないときがあったような気がします。

> 5. その他、何か心当たりがあれば教えていただきたいです

特にないです。

**Comment by fuwa-syugyo** [comment]
@cafedomancer 
ありがとうございます！
CircleCIのログを見てみます。。

**Comment by fuwa-syugyo** [comment]
@komagata 
こちら、申し訳ございませんがご対応をお願いいたします。
