### ISSUE TITLE
[メンター紹介]トップページのメンター ・ 顧問の並び順をcreated_at順にしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5781]
トップページに「メンター ・ 顧問」が表示されているが、今は動的に表示・ベタ書きで表示の2つがある。動的な方は管理者でログインしないと見れない。動的な方は created_at順ではない何かの順で並んでいる。

管理者でログインしないと見れない動的に表示しているものの表示順をcreated_at順に変更したい。

**Comment by sadanora** [comment]
:memo:
`app/views/welcome/_administrator.slim`12行目あたり
```
    - if Rails.env.production?
      = render 'welcome/temp_mentors'
    - else
      = render 'welcome/mentors', mentors: mentors
    - if admin_login?
      | ↑古い表示 / ↓新しい表示
      = render 'welcome/mentors', mentors: mentors
```
本番環境のみ`welcome/temp_mentors`を呼んでいる。

>今は動的に表示・ベタ書きで表示の2つがある

は本番環境でしか確認できないはずなので、開発環境では「動的に表示」するものが2つ並ぶ。

**Comment by sadanora** [comment]
@komagata @machida
本番での管理者向け機能の動作確認のお願いです🙏

- 管理者でログイン
- https://bootcamp.fjord.jp/welcome にアクセス
- 管理者向けのメンター・顧問の並び順がcreated_at順になっていることを確認

お手数ですが上記ご確認のほどよろしくお願いいたします！

**Comment by komagata** [comment]
@sadanora 確認しました。OKでした〜！

**Comment by sadanora** [comment]
@komagata 
ご確認ありがとうございます！
closeさせていただきます〜！
