### ISSUE TITLE
メンターでログインしている場合、自分自身のユーザー編集画面の「お住まいの都道府県」と「プログラミング経験」は非表示にしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5782]

**Comment by komagata** [comment]
@machida 「プログラミング経験」も非表示にしたいのは何故ですか？

**Comment by machida** [comment]
@komagata 確認する機会が今までなかったのが理由になります。アドバイザーはプログラミング経験をなくして、人事とかプログラマーとか社内での役割を入れる欄の方がいいかなと思いましたー。

**Comment by komagata** [comment]
@machida 僕はレビュー時やスクラムの時に経験があるのかどうかをとっても大事な情報源としてるのでメンターにとってはみれた方がいいのかな〜と思いました。

> アドバイザーはプログラミング経験をなくして、

タイトルには「メンター」とありますが「アドバイザー」の場合は非表示にするという意図のIssueですかね？

**Comment by komagata** [comment]
@machida こちらいかがでしょうか

**Comment by machida** [comment]
@komagata 

受講生や研修生など教育を受ける側は必須のままです。

アドバイザーとメンターにはプログラミング経験を聞くことはないと思うので、アドバイザーとメンターの場合は不要だと思います。

このIssueはアドバイザーではなくメンターの場合はプログラミング経験の欄を非表示という目的で作ってたのですが、途中アドバイザーと勘違いしてました。アドバイザーは別Issueにしたいと思います。

**Comment by komagata** [comment]
@machida 

> アドバイザーとメンターにはプログラミング経験を聞くことはないと思うので、アドバイザーとメンターの場合は不要だと思います。

アドバイザーはわからないですが、メンターにはレビューの時などとても大事な項目だと思うのですがいかがでしょうか？

**Comment by komagata** [comment]
@machida こちらいかがでしょうか？

**Comment by machida** [comment]
@komagata 一旦こちらクローズして整理をし直したいと思いますー
