### ISSUE TITLE
`app/views/home/index.html.slim` の `.page-header-actions` のリンクに`ul`,`li`タグを付与したい

### ISSUE THREAD

**Issue by OdenTakashi** [fjordllc/bootcamp#5783]
## 概要
`app/views/current_user/reports/index.html.slim`内のリンクに`ul`, `li`タグが付与されているが、`app/views/home/index.html.slim`内のリンクには`ul`, `li`タグが付与されていないので、`ul`, `li`タグを付与したい。

## `app/views/current_user/reports/index.html.slim`

`app/views/current_user/reports/index.html.slim`
<img width="1051" alt="スクリーンショット 2022-11-14 12 36 50" src="https://user-images.githubusercontent.com/81839214/201569998-603eb7e1-60fd-488d-976c-9434b448d1bc.png">

## `app/views/home/index.html.slim`

`app/views/home/index.html.slim`
<img width="1046" alt="スクリーンショット 2022-11-14 12 36 21" src="https://user-images.githubusercontent.com/81839214/201569917-2f30cc8e-d80d-4c4b-bae5-dd8efc9ea9e0.png">

`app/views/home/index.html.slim` も `app/views/current_user/reports/index.html.slim` と同様に、`ul`, `li` タグを付ける。

**Comment by peno022** [comment]
@machida 
おつかれさまです〜本issueの背景と対応範囲について質問させてください！

**＜背景について＞**
issueに記載があるのはダッシュボード画面の「マイプロフィール」と「日報作成」のボタンのところにul, liタグを付与したい、だと思うのですが、

![スクリーンショット 2022-11-21 9 04 14](https://user-images.githubusercontent.com/40317050/202933931-930150ac-1776-4c43-85c6-c6f437760b26.png)

ダッシュボードのページには
- ダッシュボード（`app/views/home/index.html.slim`）
- 自分の日報（`app/views/current_user/reports/index.html.slim`）
- 自分の提出物（`app/views/current_user/products/index.html.slim`）
- Watch中（`app/views/current_user/watches/index.html.slim`）
- ブックマーク（`app/views/current_user/bookmarks/index.html.slim`）
の5つのタブがあり、そのうち
- 自分の提出物（`app/views/current_user/products/index.html.slim`）
- Watch中（`app/views/current_user/watches/index.html.slim`）
の2つには「マイプロフィール」と「日報作成」のボタンがありません。

この2つにだけボタンがないことには理由があるのでしょうか？
5つ全部の画面でマイプロフィールと日報作成ボタンがあってもいいんじゃないかな？と思ったので気になりました。

**＜対応範囲について＞**
ここの部分を各タブのviewに毎回記載する形になってしまうので、

![スクリーンショット 2022-11-21 9 08 53](https://user-images.githubusercontent.com/40317050/202934140-d194dbb1-2ae2-4156-844b-f764de9b1b25.png)


`app/views/home/index.html.slim` の `.page-header-actions` のリンクにul,liタグを付与するというよりも、
今`app/views/current_user/reports/index.html.slim`にある下記の部分を`app/views/home/_page_header.html.slim`といったファイルに切り出してrenderするといった形にしてもいいのかな？と思ったのですが、問題ありそうでしょうか？

``` html
header.page-header
  .container
    .page-header__inner
      h2.page-header__title
        | ダッシュボード
      .page-header-actions
        ul.page-header-actions__items
          li.page-header-actions__item
            = link_to user_path(id: current_user.id), class: 'a-button is-md is-secondary is-block' do
              i.fa-solid.fa-user
              | マイプロフィール
          - unless current_user.adviser?
            li.page-header-actions__item
              = link_to new_report_path, class: 'a-button is-md is-secondary is-block' do
                i.fa-regular.fa-plus
                | 日報作成
```

まだテストなど確認してないですが、
各タブのviewで
= render 'home/page_header'
に置き換えるのを試した限りだと表示は問題なさそうかと思い。

**Comment by machida** [comment]
@peno022
確認ありがとうございますー！

実は、good first issue を作るために共通化してなくて、少しずつ修正の Issue を切り出してました。なので、本当はダッシュボードのページタイトルの部分は partial にして共通化するのが正しいですー。

partial化の提案をいただいたので、ダッシュボードのグループのページタイトルの部分は partial にして共通化をお願いします🙏

Issues を確認して、この作業で解決できる Issue がありましたら、マージされたときにそれも同時に close をお願いしますー

**Comment by peno022** [comment]
@machida 
なるほどです！承知しました！
関連issue探して同じPRに紐付け＆クローズするようにします。
