### ISSUE TITLE
管理者は各ユーザーの情報変更ページでメンター権限を付与できるようにしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5784]
<img width="327" alt="スクリーンショット 2022-11-14 13 21 48" src="https://user-images.githubusercontent.com/16577/201574617-aec79cfd-fe32-42d7-b281-980e3ab956d1.png">

ここで「メンター」も設定できるようにしたい。

**Comment by ksmxxxxxx** [comment]
@komagata @machida 
こちらのIssueの実装について確認させてください。

特殊ユーザー属性でメンターを設定できるようにしたいとのことなんですがメンターで登録する場合、メンター紹介用のプロフィールや職業、プロフ画像などの入力できることが必須になるようです。

現状だとチェックできるよう実装だけすると、たとえばアドバイザーのユーザーをメンターとして登録しようとすると、チェック→更新ボタン押下すると、必須項目が未入力としてバリデーションに引っかかり、この時点ではじめてメンター紹介用の入力項目が表示されるようになります。

本来であれば、メンターにチェックが入った段階で紹介用の入力フォームが出てほしいんじゃないのかなぁとエスパーしたんですが、その場合このIssueの作業範囲に入るのか、自分としては判断が難しいと思ったので、確認させてもらおうと考えました。（ポイントも変わる作業量になりそうだったので 😅 ）
実装の想定としてこのIssueの範囲に入りますか？

**Comment by komagata** [comment]
@ksmxxxxxx 

> 本来であれば、メンターにチェックが入った段階で紹介用の入力フォームが出てほしいんじゃないのかなぁとエスパーしたんですが

こちらの実装も含めてお願いします〜。

**Comment by machida** [comment]
@ksmxxxxxx @komagata 

紹介用の入力フォームなのですが、現状、表側（FBCトップページ）には紹介用の入力フォームに入力されていたら表示されるようになっています。なので、紹介用の入力フォームが必須にである必要はないです。

ユーザーがメンターになるのと、そのユーザーがトップページにそのメンターとして表示されるタイミングには時間差があります。

まずはメンターとしてメンター業務ができることを優先します。新規メンターは、メンター業務を開始しつつ、任意のタイミングで紹介用の入力フォームに入力をお願いすることになります。場合によっては本業の方に副業申請などを行うなど、すぐにトップページに表示ができない場合があったり、お試しメンター期間中でその期間が終わってからトップページに表示する、ということもあるので、トップページに表示していい状況になったら紹介用の入力フォームに入力をお願いする、という流れになります。

ということで、仕様をまとめると、

1. 管理者がユーザーにメンターフラグを付与することができる。
1. メンターフラグを追加した時点でメンター紹介用のプロフィールや職業、プロフ画像などの入力がされていなくてもバリデーションエラーは起きないようにする。
1. メンターフラグを追加しようとした時点で（メンターのチェックボックスにチェックを入れた時点で）、メンター紹介用のプロフィールや職業、プロフ画像などの入力は表示される（js で表示されるようにしたい）。

をお願いしたいです

仕様が増えたので、ポイントは次回MTGで振り直したいと思いますー

**Comment by komagata** [comment]
@machida (CC: @ksmxxxxxx )

こちら、プロフィールや職業などのバリデーションを外しても他の様々なパターンで同じことが起きます。（アドバイザーとかも）

なのでこの対応策だと一時的な対策になってしまって、すぐに元に戻すことになりそうです。
ですので、根本的な対策をした方がいいように思います。

## komagataの考える根本的な対策

必須項目のフォームはruby的に非表示ではなくhidden（）として表示する。

**Comment by ksmxxxxxx** [comment]
2022年12月7日開発MTGメモ

- 管理者はメンターフラグをつけることができる
- メンター紹介用入力フォームのバリデーションは外す
- メンターフラグのon, offによるフォームの表示切り替えについては、このIssueではやらない
