### ISSUE TITLE
[メンター紹介]メンターの関連書籍に画像をアップロードしてもプレビューできない

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5785]
メンターでログインし、登録情報変更で関連書籍を登録。

<img width="588" alt="貼り付けた画像_2022_11_14_17_13" src="https://user-images.githubusercontent.com/168265/201608651-a34ed5a2-9dcf-463e-9e81-be513f686f10.png">

**Comment by shirotamaki** [comment]
@komagata @machida
 お疲れさまです！今週のリリースありがとうございます✨
 こちら、メンター向けのページのため本番環境での動作確認をお願いできますでしょうか？

 確認方法
- メンターアカウントでログインする `/current_user/edit`へアクセスする
- 「+書籍を追加」をクリックし「画像を選択」から任意の画像を選択肢アップロードする
- プレビュー画像が表示されることを確認する

**Comment by komagata** [comment]
@shirotamaki 本番環境で動作することを確認しました。

**Comment by shirotamaki** [comment]
@komagata ご確認ありがとうございます！Closeいたします！
