### ISSUE TITLE
[メンター紹介]トップページのメンター・顧問紹介の部分で、関連書籍の並び順は後から登録したものを先に表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5786]
現在、管理者（komagata）でログインして、` http://localhost:3000/welcome ` にアクセスすると、

<img width="462" alt="貼り付けた画像_2022_11_17_16_19" src="https://user-images.githubusercontent.com/168265/202381412-273a10f3-069f-4bc0-b11e-1b083f48581c.png">

メンター・顧問のブロックが2つ表示されるが、2つのうち、上の方は、本番環境でだけ `welcome/_temp_mentors.html.slim` の内容を表示しています。

`welcome/_temp_mentors.html.slim` は slim に メンター・顧問 の情報がベタ書きされたファイルです。近い将来、ベタ書きしたものは削除して、本番環境以外で表示されている動的に表示しているものを表示する予定です。`welcome/_mentors.html.slim` が動的に表示しているものになります。動的の表示にバグや仕様漏れがあったので、それらの対応が終わったら切り替えます。で、このIssueは動的に表示しているものの仕様漏れの一つです。

---

なぜ管理者でログインすると、同じものが2つ表示されるのか？

2つのうち、1つは本番環境ではベタ書きの方が表示されます。
もう一つは動的表示の方になりますが、これは管理者しか見れません。ベタ書きの表示を見て、本番環境にデータを登録し（手動で）、動的表示の方にうまく反映さえれているかを確認する、という作業を行うために2つ表示されています。

---

## やってほしいこと 1

動的表示の方は、メンターの一覧を表示しています。

メンターでログインをして、メンター権限のあるユーザーの個別ページに行き、管理者権限でそのユーザーの編集ページに行きます。

<img width="1273" alt="貼り付けた画像_2022_11_17_16_28" src="https://user-images.githubusercontent.com/168265/202383116-8448a6f3-62dc-46fa-8c51-cc378c9ba6e1.png">

すると、`メンター紹介用公開プロフィール` というブロックがあります。

<img width="599" alt="貼り付けた画像_2022_11_17_16_29" src="https://user-images.githubusercontent.com/168265/202383329-ed121768-156c-415e-be05-46c24443593e.png">

この情報を動的表示に表示しています。

ここに `関わった書籍` を登録するブロックがあります。

<img width="270" alt="image" src="https://user-images.githubusercontent.com/168265/202383521-c918e656-0da8-453e-9270-4316688ced1b.png">

複数登録ができるのですが、登録した順番に動的表示に表示されてしまいます。順番を逆にして、後から登録したものが先に表示されるように変更をお願いします。

---

## やってほしいこと 2

seed データに関連書籍を持ったメンターがいません。
`メンタ 麺太郎` に関連書籍を 2つ以上持たせてほしいです。

**Comment by ksmxxxxxx** [comment]
@machida Issueの割り振り、ありがとうございます。

気になったところがあったので確認させてほしいです。

- 現状、書籍には書影画像を登録するようになっていますが、書籍名とURLだけ入力、書影画像なしで登録するとwelcomeページには表示されないようになっています。こちらは想定している挙動でしょうか？
- 逆順に表示する対象はwelcomeページのみという認識で合っていますか？　メンター別の登録情報変更画面の書籍追加の部分は対象ではないと理解しています

指差し確認みたいな質問で恐縮ですが、ご確認のほど、よろしくおねがいします 🙇🏻‍♀️

**Comment by machida** [comment]
@ksmxxxxxx 
確認ありがとうございますー

今のところ、書籍画像がない場合は非表示でお願いしますー。別IssueでNo Image的なやつを作ったらその部分を変更しようと思います。

順番の変更はトップページだけでお願いします🙏
編集画面では登録した順で表示をお願いしますー

**Comment by ksmxxxxxx** [comment]
@machida 承知しました、ありがとうございますー
