### ISSUE TITLE
参考書籍一覧を画面遷移無しで絞り込みたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5787]
参考書籍一覧：
https://bootcamp.fjord.jp/books

プルダウンリストを選択したら画面遷移無しで書籍一覧が変わるようにしたい。

**Comment by ksmxxxxxx** [comment]
@machida デザイン？的なところだと思うので、町田さんにメンションさせてもらいます。

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/5976902/215038712-22dd4485-328b-4acb-bae7-d5ceba1faeb6.png">

作業中に画像の箇所の文言が、ページのコンテンツに合ってないような気がしました。
このIssueで一緒に直しちゃっていいかな？と考えていますが、いかがでしょう？

また、文言を変えるとして代替の文言ってなにかアイディアありますでしょうか？

自分は「すべての参考書籍を表示」だと、読み上げられえも伝わると思うので妥当かなと考えています。

**Comment by machida** [comment]
@ksmxxxxxx 提案ありがとうございます！！一緒に修正お願いしたいです🙏文言もそれでお願いしたいですー🙏
