### ISSUE TITLE
トップページのお二人の横断幕を外す

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5796]
<img width="1125" alt="貼り付けた画像_2022_11_16_22_51" src="https://user-images.githubusercontent.com/168265/202198480-15bc9230-6cf2-4ae5-992b-71c9880e8de7.png">

**Comment by peno022** [comment]
本番確認OKです。クローズします。

![スクリーンショット 2022-12-02 7 15 22](https://user-images.githubusercontent.com/40317050/205170678-b8e7393e-828e-4670-a1ae-925ce390a2c2.png)
