### ISSUE TITLE
スマホ時の検索の表示・非表示をJSで行いたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5805]
ここをクリックすると、

<img width="417" alt="貼り付けた画像_2022_11_17_15_51" src="https://user-images.githubusercontent.com/168265/202376747-bad9be00-8b17-4284-b061-77d23b599cff.png">

検索フォームが表示される。

<img width="408" alt="image" src="https://user-images.githubusercontent.com/168265/202376826-f85f274f-99ba-457a-b79e-90e018603293.png">

現在は、`#header-search` がついた checkbox にチェックが入ったら表示される、という方法を取っている（JSは使っていない）。

以下を JS で実装お願いします🙏

---

`#header-search` がついた checkbox を削除してください。

<img width="540" alt="貼り付けた画像_2022_11_17_15_55" src="https://user-images.githubusercontent.com/168265/202377456-bec8f9c9-1025-48c2-9579-a51865a116a0.png">

`#header-search` がついた checkbox を削除。

---

<img width="290" alt="貼り付けた画像_2022_11_17_15_58" src="https://user-images.githubusercontent.com/168265/202378017-e354e168-40a1-4a20-a026-06b1ee7c1f17.png">

この部分は、`.header-links__link.test-show-menu` という class がついた label タグ。

<img width="656" alt="貼り付けた画像_2022_11_17_15_59" src="https://user-images.githubusercontent.com/168265/202378113-f83ff7ef-6301-4d30-95ba-0eb570101e3d.png">

- label から button タグに変更。
- `for="header-search"` を削除。
- ここをクリックしたら、先程削除した `#header-search` がついた checkbox の隣にある `.modal` が表示されるようにする。

---

<img width="294" alt="貼り付けた画像_2022_11_17_16_07" src="https://user-images.githubusercontent.com/168265/202379391-d3d1a34f-12e1-424c-aa7d-2a261c8a917a.png">

.modal の背景と「X」 をクリックしたら .modal が非表示になる。

---

この変更で不要になった sass の削除が必要になるので、作業が終わったら machida にメンションお願いします。

**Comment by komagata** [comment]
@machida これってどういった理由からでしょうか

**Comment by komagata** [comment]
:memo: MTGで話した結果、CSSで実装すると原因不明のバグが出るため。

**Comment by sadanora** [comment]
@machida
こちら実装しました〜
なお、CIでテストが落ちていますが、[fixtureの変更により通らなくなったテストを通るようにした](https://github.com/fjordllc/bootcamp/pull/5935)がmainにマージされ次第解消されるはずなので無視しています。

>この変更で不要になった sass の削除が必要になるので、作業が終わったら machida にメンションお願いします。

上記sassの削除依頼は、メンバーレビュー後でよいでしょうか？

**Comment by machida** [comment]
@sadanora はい、同時進行で進めますので、レビューに進めてくださいー

**Comment by sadanora** [comment]
本番での動作確認ができたのでcloseします。
