### ISSUE TITLE
Node.js を 18 LTS にバージョンアップする

### ISSUE THREAD

**Issue by cafedomancer** [fjordllc/bootcamp#5818]
(やりたい人がいなければ @cafedomancer がやります)

**Comment by komagata** [comment]
:memo: 各自が環境変数に設定を追加しないといけないやり方でアップデートしてしまったため戻します。

**Comment by komagata** [comment]
:memo: 上記の指定はwebpack4を使ってるため。webpackerの最新だとwebpack4のため。
webpack5からはshakapackerを使う必要がある。そのためまず先にrails7にアップデートするのが良さそう。

**Comment by komagata** [comment]
20.9.0にアップグレードしたのでClose。
理由がわからなかったのですがOpenSSLの互換エラーは無くなっていた。
