### ISSUE TITLE
ユーザー個別 > コメント一覧 にコメントフォームが出てるので削除したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#582]
（例 https://bootcamp.fjord.jp/users/175/comments ）

![image](https://user-images.githubusercontent.com/168265/47897034-57e5f280-deb3-11e8-840d-f859399c6d6d.png)

**Comment by tosite0345** [comment]
https://github.com/fjordllc/bootcamp/pull/590 にて対応中です。

**Comment by komagata** [comment]
@machida 修正されましたー。
