### ISSUE TITLE
CircleCIのスクリーンショットを見れる用意する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5844]

**Comment by komagata** [comment]
スクショが見れるようにしました。

https://app.circleci.com/pipelines/github/fjordllc/bootcamp/4388/workflows/a53f26d2-3854-4d88-a1aa-a4199fbc4f0f/jobs/11413/artifacts

![スクリーンショット 2022-11-30 22 39 18](https://user-images.githubusercontent.com/16577/204811218-8ab73c69-3827-4a93-9198-dd60345874cf.png)

**Comment by fuwa-syugyo** [comment]
@komagata 
ありがとうございます！非常に助かります。
使い方について2点質問したいです。
1. 上記リンクのARTIFACTSのみでしかスクショは見れないでしょうか？
自分でpushしてプルリクを作ってみたのですが、ARTICATSが今までと同じ画面になってしまいました。
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/62344131/204825227-4342dbe0-22ca-46fc-9d5e-38ded08e3a15.png">
2. スクショでは文字が❎で表示されていますが、実際のテストでは正しい文字で判定しているということであっていますか？


お手数ですがご確認いただけますと幸いです。
よろしくお願いします。

**Comment by komagata** [comment]
@fuwa-syugyo 新しいCircleCIの設定を最新のmainで行なっているので、自分のブランチにもmainの最新のコードを取り込んでください。そうすればそのブランチでもARTIFACTSが見れると思います。

**Comment by fuwa-syugyo** [comment]
@komagata 
私のブランチでもARTIFACTSを見ることができました！ありがとうございます。
フォントについて、お手数ですがご確認よろしくお願いいたします🙏

**Comment by komagata** [comment]
@fuwa-syugyo 遅くなりまして申し訳ないです。下記のIssueで修正しましたのでmainの最新を取り込んでいただければスクリーンショットに日本語が表示されるようになっているはずです〜。

#5866

**Comment by fuwa-syugyo** [comment]
@komagata 
ありがとうございます！
スクショで日本語が表示されるようになりました〜
