### ISSUE TITLE
vue に書かれているユーザーアイコンのマークアップを変更したい。退会ユーザーに対して is-retired クラスの付与も。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5848]
https://github.com/fjordllc/bootcamp/issues/5596
こちらで行った作業は view の slim  に書かれたものの対応でした。 
同じ対応を vue の方もお願いします。

現在はユーザーアイコンのimgタグに class がついていますが、 HTML の構造を変更していただきたいです。

```html
<img title="ユーザー名" alt="ユーザー名" src="アイコン画像パス" class="a-user-icon is-graduate">
 ```

という構造になっています。これを以下のように変更していただきたいです。

```html
<span  class="a-user-role is-graduate">
  <img title="ユーザー名" alt="ユーザー名" src="アイコン画像パス" class="a-user-icon">
</span>
 ```

このように、img を span タグで囲い、その span タグに `a-user-role ` という class と user class を付けて欲しいです。

**Comment by OdenTakashi** [comment]
@machida 
付与するクラスについて一点質問させていただきたいです！🙏

## 状況
Q&Aページ内の回答,コメントフォームの左に置かれているユーザーアイコンのimgタグに`is-admin`の様なクラスが付与されていませんでした。

<img width="1440" alt="スクリーンショット 2022-12-09 11 41 07" src="https://user-images.githubusercontent.com/81839214/206611976-5ffd9733-dc11-4b6a-bed9-f092f9eee605.png">

<img width="1180" alt="スクリーンショット 2022-12-09 11 41 56" src="https://user-images.githubusercontent.com/81839214/206612057-62cdd830-fb84-42c7-9385-b2ac9f6ff79b.png">

## 質問
この箇所には`is-admin`の様なrollのクラスを付与しても問題はないでしょうか？

**Comment by machida** [comment]
@OdenTakashi 質問ありがとうございます！ここは、やり忘れですね。この機会にこの部分も他と合わせるようお願いします🙏

**Comment by OdenTakashi** [comment]
@machida 
ご返信ありがとうございます！🙏
承知しました！

**Comment by machida** [comment]
@OdenTakashi

こちらのIssueのPRは、main ブランチではなく、
https://github.com/fjordllc/bootcamp/pull/5755
このPRに向けて、PRを送るようお願いします。

このIssueと
https://github.com/fjordllc/bootcamp/issues/5596 この Issue はまとめてリリースします。

**Comment by machida** [comment]
@OdenTakashi 
この Issue に書き漏れがありました🙇‍♂️
is-retiredクラスを付与 もお願いします🙏

**Comment by OdenTakashi** [comment]
@machida 
ご連絡遅れしまい大変申し訳ありません💦🙇‍♂️

> こちらのIssueのPRは、main ブランチではなく、
https://github.com/fjordllc/bootcamp/pull/5755
このPRに向けて、PRを送るようお願いします。
このIssueと
https://github.com/fjordllc/bootcamp/issues/5596 この Issue はまとめてリリースします。

承知しました！

> この Issue に書き漏れがありました🙇‍♂️
is-retiredクラスを付与 もお願いします🙏

こちらも承知しました！

**Comment by OdenTakashi** [comment]
本番環境で動作確認が取れたためcloseします
