### ISSUE TITLE
プラクティス『HTMLの基本を理解する』における誤字

### ISSUE THREAD

**Issue by ericgpks** [fjordllc/bootcamp#5862]
## 概要
プラクティス『HTMLの基本を理解する』の中に誤字がありましたので報告します

## 期待される振る舞い
2箇所ありました
該当箇所とおそらくこうであるべき文言をスクリーンショットにてお伝えします

## スクリーンショット
1.
<img width="880" alt="HTMLの基本を理解する___FBC" src="https://user-images.githubusercontent.com/40660382/205448875-7db0dcf5-df42-4871-8cd1-7906c694e17e.png">

2.
<img width="877" alt="HTMLの基本を理解する___FBC2" src="https://user-images.githubusercontent.com/40660382/205448967-4c2b621c-8d81-4bf9-9fe8-9e64c9d40c7f.png">

**Comment by machida** [comment]
対応しましたー
