### ISSUE TITLE
Q&AのAをスマホで表示したときにアイコンを表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5863]
<img width="436" alt="貼り付けた画像_2022_12_05_16_56" src="https://user-images.githubusercontent.com/168265/205583637-3f89d289-f0d9-4f70-b9f1-e52362c6ae0d.png">

A ではなく、コメントにはアイコンが出るので、同じにしたい。

<img width="400" alt="image" src="https://user-images.githubusercontent.com/168265/205583782-83d4aa39-cbcd-499f-9a4c-44668da107f9.png">

**Comment by shucream-p** [comment]
本番環境で動作確認できましたのでissueをcloseいたします。
