### ISSUE TITLE
Discrodの管理者向け卒業通知が何個も飛んでいる

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5868]
<img width="323" alt="貼り付けた画像_2022_12_06_17_06" src="https://user-images.githubusercontent.com/168265/205855293-f9cb8e57-3d79-42a2-a60b-cb1958f12afe.png">

こんな風に通知されてしまっているので1つだけになるように修正したい。

**Comment by sadanora** [comment]
@komagata 
おつかれさまです。
このissueに取り組んでいたのですが、https://github.com/fjordllc/bootcamp/pull/5961 で同様の不具合を解消されたようなのでこのissueはcloseということになりますでしょうか？

**Comment by komagata** [comment]
@sadanora すみません、僕の方で思いがけずこのIssueが直ってしまったのでこちらはcloseでOKです〜。
調査していただいたのでポイントはそのままでGETでOKです〜

**Comment by sadanora** [comment]
@sadanora 
承知しました、ご確認ありがとうございます〜！
closeさせていただきます〜

**Comment by sadanora** [comment]
@komagata 
承知しました、ご確認ありがとうございます〜！
closeさせていただきます〜
