### ISSUE TITLE
[定期イベント] 今日開催のイベントが管理者用の通知チャンネルに飛んでしまっている。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5869]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/168265/205855566-d80924a9-a351-4818-928d-39a9b8738c1a.png">

この通知が、運営通知チャンネルに飛んでいるので、お知らせチャンネルで通知するようにしたい。

**Comment by machida** [comment]
@komagata

**Comment by komagata** [comment]
@machida 了解です。

**Comment by machida** [comment]
本番で確認したのでクローズします。
