### ISSUE TITLE
CORSの設定が適切かどうかを見直す

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5872]
@mono-nobe さんが書かれたこちらの日報を参照。
https://bootcamp.fjord.jp/reports/64320

@komagata さんも理由がわからないとのことだが、

- 当時は必要だったが、今は不要になっている
- 開発環境やステージング環境では必要だが、本番環境では設定不要（なので、設定を環境によって切り分ける？）

等々の原因が考えられるかも。いずれにせよまずは調査から始める必要がありそうです。

**Comment by komagata** [comment]
:memo: 多分Cloud Storageにアップしてる画像を読み込めなくなるからだと思う。
