### ISSUE TITLE
[続き]コメント通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5873]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L4)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/pull/5919
このPRの続きを行う。

**Comment by machida** [comment]
@rira100000000 こちら、作業を途中から行うIssueになりますー アサインさせていただきました。

**Comment by rira100000000** [comment]
本番環境での確認が完了しましたのでcloseします。
