### ISSUE TITLE
確認通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5874]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L15)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by peno022** [comment]
@machida @komagata 
おつかれさまです！
こちらのissueの本番確認をしたく、テスト用の提出物を作成しました。
下記リンクの提出物（rubygemを作る）を「確認」をお願いできますでしょうか？
https://bootcamp.fjord.jp/products/15139

「確認」を実行いただいたら、私のほうで、サイト内通知とメール通知が来ていることを確認します。

**Comment by peno022** [comment]
本番での動作確認ができたのでクローズします！

こちらの提出物の確認をし、サイト内通知・メール通知が来ることを確認しました。
https://bootcamp.fjord.jp/products/15139

![スクリーンショット 2023-02-20 20 42 51](https://user-images.githubusercontent.com/40317050/220097642-e567450b-2cad-489c-86d6-b31db943ede2.png)

![IMG_2362](https://user-images.githubusercontent.com/40317050/220097517-bcc735fe-76e5-4be1-a1a3-ff3bf3ed7dfb.PNG)

**Comment by komagata** [comment]
@peno022 ありがとうございました〜！
