### ISSUE TITLE
提出物更新通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5875]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L23)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by monyatto** [comment]
@komagata @machida 

お疲れさまです！このissueについて2点確認させてください。

- 現状、提出物更新の通知はフィヨルド内のお知らせのみでメールは来ないみたいですが、これはそのままで大丈夫でしょうか？

- newspaper化もした方がコードがすっきりしそうだなと思ったのですが、active_deliveryの導入と同じPRではやらない方がいいでしょうか？

ご確認お願いします🙏

**Comment by machida** [comment]
@monyatto 

> 現状、提出物更新の通知はフィヨルド内のお知らせのみでメールは来ないみたいですが、これはそのままで大丈夫でしょうか？

お、これも他の通知と同じにしたいです。メールを許可していたらメールも飛ぶ様にお願いします。

> newspaper化もした方がコードがすっきりしそうだなと思ったのですが、active_deliveryの導入と同じPRではやらない方がいいでしょうか？

なるほどー

- newspaper化 の Issue を作り、まずはそれの対応をお願いします。
- そのPRから新しくブランチを作り、このIssueの対応をお願いします。
- このIssueの対応中にnewspaper化 のPRがmainにマージされたら、このIssueのPRを最新のmainからリベースしてください。

**Comment by monyatto** [comment]
@machida 
ご確認ありがとうございます！
- 提出物更新した際にメールも飛ぶようにするとのこと承知いたしました。
- newspaper化のissueとして #6515 を作成しました。

**Comment by monyatto** [comment]
@machida 
あっnewspaper化も自分でやるものだと思い込んでいましたが、#6515に関してはとりあえず「いつかやる」で担当者空欄にしておけばいいでしょうか？

**Comment by machida** [comment]
@monyatto newspaper化のIssueの対応もお願いしますー🙏アサインしておきます

**Comment by monyatto** [comment]
@komagata @machida
お疲れ様です！
こちら提出物が更新された際に、その提出物を担当しているメンターへサイト内通知とメールがくるか動作確認をお願いしたいです。
（チーム開発MTG内で動作確認した方がよさそうでしたら、次回参加しますのでお知らせください🙏）

**Comment by komagata** [comment]
@monyatto 自分で提出物を作って自分を担当にしましたが、更新時の通知は来ていないようです。
https://bootcamp.fjord.jp/products/17135

**Comment by monyatto** [comment]
@komagata 
説明不足で申し訳ありません🙇🏻
こちら更新したのがメンターの場合は通知が飛ばないようになっています。

**Comment by komagata** [comment]
@monyatto なるほどです。
僕だけだと環境が出来ないのでテスト用の提出物の作成など確認できる段取りをお願いできればありがたいです〜。

**Comment by monyatto** [comment]
@komagata 
提出物作成しましたので、担当になっていただけますでしょうか🙏（その後こちらで更新します！）
https://bootcamp.fjord.jp/products/17162

**Comment by komagata** [comment]
@monyatto 提出物作成ありがとうございます。担当者になりました。

**Comment by monyatto** [comment]
@komagata 
ありがとうございます！　更新したので通知が来ているかご確認お願いします🙏

**Comment by komagata** [comment]
@monyatto 通知が来ていないようです〜。

**Comment by monyatto** [comment]
【メモ】
こちらステージング環境では正常に通知が来るのを確認。
質問タイムにて相談。再度駒形さん以外の方に動作確認お願いする。

**Comment by monyatto** [comment]
@machida 
こちらの動作確認をお願いできますでしょうか。
以下の提出物の担当になっていただき、その後こちらで提出物を更新するので、通知が来るかご確認いただきたいです🙏
https://bootcamp.fjord.jp/products/17570

（なお、一度駒形さんに動作確認いただいたのですが、通知が送られませんでした。ステージング環境では通知が正常に送られている状態です）

**Comment by machida** [comment]
@monyatto 担当になりました！更新お願いします

**Comment by monyatto** [comment]
@machida 
早速ありがとうございます！　更新しましたが通知は送られているでしょうか？

**Comment by machida** [comment]
@monyatto 通知届きましたー🙆‍♂️

**Comment by monyatto** [comment]
@machida 
ご確認ありがとうございます！

こちら動作確認できたので、closeいたします。
