### ISSUE TITLE
回答通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5878]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L49)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by maeda-m** [comment]
:memo: [ふりかえり・計画ミーティング2023年01月11日](https://github.com/fjordllc/bootcamp/wiki/%E3%81%B5%E3%82%8A%E3%81%8B%E3%81%88%E3%82%8A%E3%83%BB%E8%A8%88%E7%94%BB%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B02023%E5%B9%B401%E6%9C%8811%E6%97%A5) よりメモ

メール通知がサイト内通知より先に送られてしまうと、通知の既読未読管理用のレコードが作成されていないためメール内で使用するURL生成でエラーになる。通知レコードが作成されていなくてもOKなように修正する必要がある。

**Comment by maeda-m** [comment]
本番環境で動作を確認しましたので Close します🎉

https://bootcamp.fjord.jp/questions/1520 にてウォッチなし、メンションなしの状態でコメントをしてもらいました。
時間差はありましたがメールが届きました。

![5878](https://user-images.githubusercontent.com/943541/214788005-f32491c5-f97f-48a3-bed2-bed77f212fe7.png)
