### ISSUE TITLE
reportsのカラム名について

### ISSUE THREAD

**Issue by tosite0345** [fjordllc/bootcamp#588]
## 概要
カラム名の命名と実際のデータに相違があります。
[こちら](https://github.com/fjordllc/bootcamp/blob/master/db/schema.rb#L203) をご覧ください。

`reports.reported_at` は `at` であるので日付時刻型であるべきですが、実際は日付型になっているようです。
名前に寄せて日付時刻型にするか、名前を変えて日付型（ `reported_on` ）に修正したほうがいいのではと思います。

今のところ、特に挙動がおかしいなどの弊害は出ていないようです。
ご検討いただければ幸いです。

**Comment by komagata** [comment]
`reported_on`に変更でいいと思います。

**Comment by tosite0345** [comment]
https://github.com/fjordllc/bootcamp/pull/596 で対応中です。
