### ISSUE TITLE
最初の日報投稿通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5881]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L77)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by YukiWatanabe824** [comment]
@komagata @machida 
お疲れ様です。
こちらの本番環境での確認をお願いできますでしょうか。

ユーザーが初めての日報を投稿すると、管理者とメンターにapp内通知とメール通知が配信されますので届いていることを確認いただくものになります。
よろしくお願いいたします。

**Comment by machida** [comment]
@YukiWatanabe824 遅くなってすいません🙇‍♂️ こちら本番で確認できましたー🙆‍♂️

**Comment by YukiWatanabe824** [comment]
@machida
ありがとうございます！
確認が取れたのでCloseいたします
