### ISSUE TITLE
退会通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5882]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L98)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by futa4095** [comment]
@komagata @machida 
管理者とメンターへの通知のため、本番確認をお願いしたいです！

確認内容
- (2/18リリース以降)退会が発生した時に、サイト内通知・メール通知が行われること

**Comment by komagata** [comment]
@futa4095 本番環境で退会者が出た時に私の方で確認したいと思います〜

**Comment by futa4095** [comment]
> @futa4095 本番環境で退会者が出た時に私の方で確認したいと思います〜

@komagata こちらの経過はどうでしょうか？退会の通知が行われていますでしょうか。

**Comment by komagata** [comment]
@futa4095 退会通知きていました。確認が遅くなり申し訳ありません〜。
