### ISSUE TITLE
フォローしてる人の日報投稿通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5886]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/dcdf8a7ecc69199ba3a24bcd52c33f040f12eb15/app/models/notification_facade.rb#L90)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by uchihiro04** [comment]
@komagata
issue名について1点確認させていただければと思います🙇‍♂️

こちらの勘違いでしたら申し訳ないのですが、issue名といただいた[既存の実装](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L128)が食い違っていそうです。

現在のissue名は「フォローしてる人の日報投稿通知をactive_delivery化したい」になっていますが、概要にある[既存の実装](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L128)では、Q&Aでベストアンサーが決定した際の通知に関するメソッド（`self.chose_correct_answer`）内のコードが表示されています。

また、現在のissue名とほぼ同じissueが存在しています（既に他の方がプルリクエストを出しています）
[フォローしているユーザーの日報通知をactive\_delivery化したい · Issue \#5885 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/5885)

そのため、こちらのissue名につきましては、「Q&Aのベストアンサーが選ばれた時の通知をactive_delivery化したい」のような形になるのではと推測しています。

ご確認のほど、よろしくお願いいたします🙏

**Comment by komagata** [comment]
すみません、 #5885 と重複しているのでCloseします。
