### ISSUE TITLE
Docs作成通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5888]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/dcdf8a7ecc69199ba3a24bcd52c33f040f12eb15/app/models/notification_facade.rb#L113)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by uchihiro04** [comment]
@komagata @machida 
本番環境での確認について質問です。

現在、ドキュメントの作成時にサイト内通知・メール通知が飛ぶか、本番環境にて確認を行おうと考えています。
しかし、ドキュメント作成を行うと現役生・管理者・メンターといった多くの方にテスト用の通知が飛ぶため、多くの人を巻き込む形になります。

このまま、ドキュメント作成時の通知確認を本番環境で行ってもよろしいでしょうか。
（テスト用のドキュメントには、本番環境での確認テストである旨を書きます）。

もし別の確認方法がございましたら、ご教示いただけますと幸いです🙇‍♂️

**Comment by komagata** [comment]
@uchihiro04 本日、ちょうど下記のDocsを作成したのですが、そちらで確認できますでしょうか？

https://bootcamp.fjord.jp/pages/487

**Comment by uchihiro04** [comment]
@komagata 
ありがとうございます🙇‍♂️
サイト内通知・メール通知のどちらも届いていることが確認できました！

**Comment by uchihiro04** [comment]
本番環境で動作確認ができましたので、issueをcloseいたします。
