### ISSUE TITLE
ベストアンサー決定通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5889]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L161)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by syo-tokeshi** [comment]
本番環境で動作確認が出来ましたので、証跡を残します

[WEBの通知]
<img width="261" alt="スクリーンショット 2023-06-24 20 06 13" src="https://github.com/fjordllc/bootcamp/assets/54713809/c20bdde0-0b26-4fe6-9af0-77d1b45d0b70">

[メールの通知]
<img width="1044" alt="スクリーンショット 2023-06-24 20 06 52" src="https://github.com/fjordllc/bootcamp/assets/54713809/6fe17bbc-816e-42d9-9eb6-b8ea43cdf56a">

**Comment by ogawa-tomo** [comment]
上記の通り本番環境で確認がとれましたので、クローズします
