### ISSUE TITLE
涙マーク連続通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5890]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L171)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by mono-nobe** [comment]
@komagata 
`ActivityDelivery`による実行順を `ActivityNotifier` → `ActivityMailer` と固定したいのですが、調査が進まず手が止まっています...
そのため、参考資料などありましたらご共有いただけないでしょうか？

実行順を固定したい理由は、`ActivityMailer` で参照している通知レコードが `ActivityNotifier` で作成されるためです。
現状、実行順が固定されていないため、メールが送信されたりされなかったり(動作確認の度に送信されるユーザーが変動)しております。
また、以下のissueと似た挙動であったため、該当処理を `Callback` を使わない形にしたのですが、解決しませんでした。

https://github.com/fjordllc/bootcamp/pull/5924#issuecomment-1370632149

お手数ですが、よろしくお願いします 🙇

**Comment by mono-nobe** [comment]
>該当処理を Callback を使わない形にしたのですが、

具体的には、[Reportモデルの `after_save`](https://github.com/fjordllc/bootcamp/blob/40e87efdf8c864011cbcf005869bde8dc29bd6fd/app/models/report.rb#:~:text=after_save%20%20%20ReportCallbacks.new)内を `Newspaper` に置き換えました。
また、`active_delivery` 化の対象は[こちら](https://github.com/fjordllc/bootcamp/blob/main/app/models/report_callbacks.rb#:~:text=NotificationFacade.consecutive_sad_report)になります。

**Comment by komagata** [comment]
@mono-nobe 

他の通知では通知の順番を固定せずに、どちらが先に動いても大丈夫な形で実装されているのでそちらを参考にしてみてはいかがでしょうか。

下記のIssueのやりとりも参考にしてみてください。

[メンション通知をactive\_delivery化する by Seakimhour · Pull Request \#6085 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/6085)

**Comment by mono-nobe** [comment]
@komagata 
ありがとうございます！
いただいた内容を参考に進めてみます。

**Comment by mono-nobe** [comment]
@komagata 
調査した結果、想定通りに動作するようになりました！

>具体的には、[Reportモデルの after_save](https://github.com/fjordllc/bootcamp/blob/40e87efdf8c864011cbcf005869bde8dc29bd6fd/app/models/report.rb#:~:text=after_save%20%20%20ReportCallbacks.new) の処理を Newspaper に置き換えました。

また、こちらの対応が必要なので上記を別issueとして作成し、対応後に本isuueを進める形でもよろしいですか？

**Comment by mono-nobe** [comment]
>また、https://github.com/fjordllc/bootcamp/pull/5924#issuecomment-1378266245と同様にこちらの対応が必要なため、別issueとして作成し、対応後に本isuueを進める形でもよろしいですか？

=> 本issueで同時に対応する方針で決定

**Comment by mono-nobe** [comment]
本番環境での動作確認完了したためcloseします
