### ISSUE TITLE
担当者通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5891]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L181)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by djkazunoko** [comment]
@komagata @machida 
[#6342](https://github.com/fjordllc/bootcamp/pull/6342) がリリースされましたので本番環境で以下の手順で動作確認をお願いしたいです〜:raised_hands:

komagataさん
1. 未アサインの提出物一覧画面(`/products/unassigned`)にアクセス
2. 任意の提出物を選択し、提出物の詳細画面(`/products/{ID}`)にアクセス
3. 「内容修正」を選択し、提出物の編集画面(`/products/{ID}/edit`)にアクセス
4. 担当者にmachidaさんを指定し、「提出する」を選択

machidaさん
1. サイト内通知が届いていることを確認
2. メール通知が届いていることを確認

**Comment by machida** [comment]
@djkazunoko すいません、komagataさんが体調不良のため、確認までもう少しお時間いただきます🙇‍♂️

**Comment by komagata** [comment]
@djkazunoko (CC: @machida ) 上記の手順を行いました〜

**Comment by djkazunoko** [comment]
machidaさんが通知を確認できたので、closeいたします。
