### ISSUE TITLE
休会通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5892]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L202)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by YukiWatanabe824** [comment]
@komagata @machida
お疲れ様です。
こちらの本番環境での確認をお願いできますでしょうか？

## 確認方法
01. 任意のユーザーを休会状態にする
01. adminとmenterに01のユーザーが休会になったことを知らせるメール通知とapp内通知が届く

**Comment by komagata** [comment]
@YukiWatanabe824 

> 01のユーザー

すみません、ちょっと意味が理解できておらず、これはどう言った意味でしょうか？

**Comment by YukiWatanabe824** [comment]
@komagata 
> 01のユーザー

分かりづらくてすみません💦
「1.任意のユーザーを休会状態にする」で休会状態にしたユーザーを意図しています。

**Comment by komagata** [comment]
@YukiWatanabe824 なるほどです。
実際に本番で休会ユーザーが出た時に確認したいと思います〜！

**Comment by YukiWatanabe824** [comment]
@komagata 
よろしくお願いいたします。

**Comment by komagata** [comment]
@YukiWatanabe824 本番環境で確認いたしました〜！

**Comment by YukiWatanabe824** [comment]
@komagata 
ありがとうございます！

確認が取れたのでcloseいたします！
