### ISSUE TITLE
定期イベント通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5893]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L212)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by Kassy0220** [comment]
@komagata @machida 
お疲れ様です！
すみません、こちらのIssueに関して質問があります。

### 質問

このIssueで対象となる通知処理はDiscord通知だと思うのですが、Discord通知をactive_delivery化するとはどの様に行えば良いのでしょうか？

以下の理由から、Discord通知のactive_delivery化することは出来ないのではないかと考えました。

### 私の理解

こちらのIssueで実現すべきことを、次のように考えました。

1. 既存の処理を確認する

( app/models/notification_facade.rb )
```ruby
class NotificationFacade
  def self.coming_soon_regular_events(today_events, tomorrow_events)
    DiscordNotifier.with(today_events: today_events, tomorrow_events: tomorrow_events).coming_soon_regular_events.notify_now
  end
end
```

( app/notifiers/discord_notifier.rb )
```ruby
class DiscordNotifier < ApplicationNotifier # rubocop:disable Metrics/ClassLength
  self.driver = DiscordDriver.new
  self.async_adapter = DiscordAsyncAdapter.new

  def coming_soon_regular_events(params = {})
    params.merge!(@params)
    webhook_url = params[:webhook_url] || Rails.application.secrets[:webhook][:all]
    today_events = params[:today_events]
    tomorrow_events = params[:tomorrow_events]
    today = Time.current
    tomorrow = Time.current.next_day
    event_info = <<~TEXT.gsub(/^\n+/, "\n").chomp
      ⚡️⚡️⚡️イベントのお知らせ⚡️⚡️⚡️

      #{add_event_info(today_events, '今日', today)}

      #{'------------------------------' if today_events.present?}

      #{add_event_info(tomorrow_events, '明日', tomorrow)}

      ⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️
    TEXT

    notification(
      body: event_info,
      name: 'ピヨルド',
      webhook_url: webhook_url
    )
  end

end
```

2. 上記の処理が呼ばれている箇所を確認する

( app/controllers/scheduler/daily/notify_coming_soon_regular_events_controller.rb )
```ruby
class Scheduler::Daily::NotifyComingSoonRegularEventsController < SchedulerController
  def show
    notify_coming_soon_regular_events
    head :ok
  end

  private

  def notify_coming_soon_regular_events
    today_events = RegularEvent.today_events
    tomorrow_events = RegularEvent.tomorrow_events
    return if today_events.blank? && tomorrow_events.blank?

    NotificationFacade.coming_soon_regular_events(today_events, tomorrow_events)
  end
end
```

3. 1の処理を削除し、2の処理は次の様に実装を行う。

```diff
  def notify_coming_soon_regular_events
    today_events = RegularEvent.today_events
    tomorrow_events = RegularEvent.tomorrow_events
    return if today_events.blank? && tomorrow_events.blank?

-    NotificationFacade.coming_soon_regular_events(today_events, tomorrow_events)
+    ActivityDelivery.with(today_events:, tomorrow_events:).notify(:coming_soon_regular_events)
  end
```

active_delivery化とは`ActivityDelivery.with(…).notify(…)`を呼び出すことで、AbstractNotifierで実装された通知処理をまとめて実行すること、と理解しました。

しかし、Discord通知をActiveDeliveryでまとめて通知することはできない、とドキュメントに書いてあります。

> 上記の違いから、Discord通知はactive_deliveryで一気に送ることができない。個別にDiscordNotifierを使う必要がある。

[gemを使った通知機能 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/gem%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9F%E9%80%9A%E7%9F%A5%E6%A9%9F%E8%83%BD)

このドキュメントに沿うと、このIssueで対象となる通知処理はactive_delivery化できないのではないかと考えました。

私の理解にもし誤りがありましたら、ご指摘していただきたいです。
よろしくお願いいたします🙇🏻

**Comment by komagata** [comment]
@Kassy0220 すみません、こちらはIssue自体が必要無い物のようです。Closeさせていただければと思います。
