### ISSUE TITLE
サインアップ通知をactive_delivery化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5894]
[既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/notification_facade.rb#L216)をactive_delivery化したい。

## 参考コード

- [active\_deliveryを導入 · fjordllc/bootcamp@127e884](https://github.com/fjordllc/bootcamp/commit/127e884e3b208ddd5152c6476f463a00138bddff)

## 参考エントリー

- [active\_deliveryで通知をまとめる \- komagataのブログ](https://docs.komagata.org/5858)
- [abstract\_notifierで通知を実装する \- komagataのブログ](https://docs.komagata.org/5857)

**Comment by YukiWatanabe824** [comment]
@machida @komagata 
お疲れ様です。
こちらのIssueについて本番環境での確認をお願いできますでしょうか。

新規ユーザー入会時にそのことを知らせるメールとapp内通知が以下画像のようにメンターと管理者に届きますので、こちらが届いていることが確認できれば大丈夫です。
<img width="1024" alt="image" src="https://github.com/fjordllc/bootcamp/assets/69577164/de3dcf75-f442-40c7-8b60-993262cf76df">
<img width="1327" alt="image" src="https://github.com/fjordllc/bootcamp/assets/69577164/e091105f-50fd-4d2e-86d0-09930318a8d8">

**Comment by machida** [comment]
@YukiWatanabe824 本番で確認できました！！

**Comment by YukiWatanabe824** [comment]
@machida 
ありがとうございます！

**Comment by YukiWatanabe824** [comment]
本番環境で確認がとれたので本件Closeいたします
