### ISSUE TITLE
期生別ユーザー一覧でタブがアクティブにならない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5899]
<img width="298" alt="スクリーンショット 2022-12-07 15 21 38" src="https://user-images.githubusercontent.com/16577/206104122-5be98c56-e451-4237-a62a-380e45c0640d.png">

ここで期生別タブがアクティブになってないとおかしい。

**Comment by Seakimhour** [comment]
本番環境で動作確認をできましたので、closeさせていただきます！
