### ISSUE TITLE
Buzzcord へのリンクをフッタに追加したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5907]
Buzzcord URL は https://discord-bot-fjord.herokuapp.com/

フッタはログイン後のフッタのみでお願いします。

**Comment by futa4095** [comment]
@machida 念の為の確認ですが、末尾への追加で良いでしょうか？

DiscordBotF(#5906)の右隣への追加を想定しています。

![image](https://user-images.githubusercontent.com/69447745/208889831-4e29dac5-9216-42d6-b24b-42c008004e39.png)

**Comment by machida** [comment]
@futa4095 はい！今回は末尾でお願いしますー 並べ替えは別 Issue にしたいと思います

**Comment by futa4095** [comment]
@machida URLがDiscordBotFのものになっています。

以下のURLにして良いでしょうか？卒業生のサービス一覧から探しました
https://buzzcord-fjord-jp.herokuapp.com/

**Comment by machida** [comment]
すいません、URL間違えてました🙇‍♂️
https://buzzcord-fjord-jp.herokuapp.com/
こちらでお願いします🙏

**Comment by futa4095** [comment]
本番環境で動作を確認できたのでcloseします
