### ISSUE TITLE
【メンター向け】未アサインのDiscord通知の並び順を見直す

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#5910]
現状は以下のように通知されますが、

```
提出されてから日数が経っている提出物の数をお知らせします。
https://bootcamp.fjord.jp/products/unassigned

- 5日経過：4件
- 6日経過：1件
```

緊急度の高いものが先に目に入る方がいいと思うので、こんなふうにした方がいいかもしれません👇
（経過日数が大きいものほど先に表示する）

```
提出されてから日数が経っている提出物の数をお知らせします。
https://bootcamp.fjord.jp/products/unassigned

- 6日経過：1件
- 5日経過：4件
```

**Comment by maeda-m** [comment]
@komagata @machida こちらのプルリクエスト #6012 がリリースされましたので本番環境で動作確認をお願いしたいです～🙏

次のURLにアクセスいただき、提出物の経過日数が7日以上経過、6日経過、5日経過の順で表示されていればOKです～
https://bootcamp.fjord.jp/api/products/unassigned/counts.txt

もし経過日数が5日以上の提出物がなければ後日確認いただければと思います～

**Comment by komagata** [comment]
@maeda-m 本番環境で動作することを確認しました。

**Comment by maeda-m** [comment]
@komagata 確認ありがとうございます🙏 Close しますね💡
