### ISSUE TITLE
休会・退会しても中身が見れる場合がある

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5928]
お問合せからバグが判明したパターンは下記の通りです。

1. 退会する。
1. 退会前に開いていた別ブラウザーだとまだ中身が見れる。

退会をしたブラウザーでは強制的にログアウトされるが、別のブラウザーでは見れてしまう。

## 修正方針

ログインが必要などのページにアクセスしても、現在**休会・退会**しているかチェックして、**休会・退会**していたら強制ログアウトをしてトップページにリダイレクトする。

**Comment by sadanora** [comment]
@komagata @machida
おつかれさまです！
本番での管理者向け機能の動作確認のお願いです。
お手数ですが以下ご確認のほどよろしくお願いいたします🙏

## 確認手順
- この動作確認では複数ブラウザを使用します。
    - 便宜的にchrome側とFirefox側操作に分けて手順を記載しますが、chrome&safariなどで動作確認いただいても大丈夫です。
- この動作確認には、ユーザーの休会や退会操作が必要です。
    - 本番環境に検証用データが存在するか知らないのですが、一旦存在する前提で確認手順を記します。
### 休会ユーザーの動作確認
#### chromeで操作
1. 検証用の現役生アカウントでログイン
#### Firefoxで操作
2. 手順1と同じユーザーでログイン
3. 右上のMeから**休会**手続きを行う
#### chromeで操作
4. ログインが必要なページを開こうとするとトップにリダイレクトされ、「休会中です。休会復帰ページから手続きをお願いします。」というアラート文が表示されることを確認する

### 退会ユーザーの動作確認
#### chromeで操作
1. 検証用の現役生アカウントでログイン
#### Firefoxで操作
2. 手順1と同じユーザーでログイン
3. 右上のMeから**退会**手続きを行う
#### chromeで操作
4. ログインが必要なページを開こうとするとトップにリダイレクトされ、「退会したユーザーです。」というアラート文が表示されることを確認する

**Comment by komagata** [comment]
@sadanora 僕の方でアカウントを作って確認しておきます〜

**Comment by sadanora** [comment]
@komagata 
ご確認ありがとうございます！
closeさせていただきます〜！
