### ISSUE TITLE
notify_certain_period_passed_after_retirementを別コントローラーに分けたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5929]
[こちら](https://github.com/fjordllc/bootcamp/blob/main/app/controllers/scheduler/daily_controller.rb#L6)の処理を別コントローラーに分けたい。

```ruby
class Scheduler::Xxxxx < SchedulerController
  def show
    # 処理
  end
end
```

## 目的

Scheduler::DailyControllerで定期実行の全ての処理をやっていたが、本番環境で実行時間が長いために全ての処理が終わらなくなってしまった。
それを解決するためにそれぞれ別のURLにしたい。

**Comment by maeda-m** [comment]
📝  [ふりかえり・計画ミーティング2022年12月21日](https://github.com/fjordllc/bootcamp/wiki/%E3%81%B5%E3%82%8A%E3%81%8B%E3%81%88%E3%82%8A%E3%83%BB%E8%A8%88%E7%94%BB%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B02022%E5%B9%B412%E6%9C%8821%E6%97%A5) でのメモ

- 現状はGCPのURLアクセスをスケジューラーで実行しているが、処理時間が長くなってきたため処理を分割したい。
- 本番環境で動作させるための、GCPのURLアクセス設定はこの議題に含まない。
- 分割後の処理も現状と同じようにURLアクセスで処理を実行させる。

**Comment by maeda-m** [comment]
@komagata @machida こちらのプルリクエスト #5962 がリリースされましたので本番環境で動作確認をお願いしたいです～🙏

スケジューラーで実行する定期処理のURL「 `https://bootcamp.fjord.jp//scheduler/daily/after_retirement` 」を設定いただいた後、
管理者宛にメール件名「 `[FBC] xxx さんが退会してから3カ月が経過しました。`」が届けばOKです～

**Comment by komagata** [comment]
@maeda-m メールが届くことを確認しました〜。

![スクリーンショット 2023-01-16 15 50 49](https://user-images.githubusercontent.com/16577/212615438-14b24568-9caf-4c05-bdfb-7608a833271c.png)

**Comment by maeda-m** [comment]
@komagata 確認ありがとうございます🙏 Close しますね💡
