### ISSUE TITLE
notify_tomorrow_regular_eventを別コントローラーに分けたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5932]
[こちら](https://github.com/fjordllc/bootcamp/blame/main/app/controllers/scheduler/daily_controller.rb#L7)の処理を別コントローラーに分けたい。

```ruby
class Scheduler::Xxxxx < SchedulerController
  def show
    # 処理
  end
end
```

## 目的

Scheduler::DailyControllerで定期実行の全ての処理をやっていたが、本番環境で実行時間が長いために全ての処理が終わらなくなってしまった。
それを解決するためにそれぞれ別のURLにしたい。

**Comment by ksmxxxxxx** [comment]
@komagata お疲れさまです。
こちら着手前にいくつか確認させてほしいです。

現在私が着手→レビュー中の https://github.com/fjordllc/bootcamp/pull/5959 について、「`schedule/daily`とは別にcontrollerを生やして対応する」ってことで、`scheduler/send_message`を追加して対応しました。

で、先程たまたま @maeda-m さんが対応されてた https://github.com/fjordllc/bootcamp/pull/5962 を見ていたんですが、こちらは `scheduler/daily/after_retirement`を追加する形で対応されてました。ここで自分が確認したいと思ったのは以下の2点です。

- https://github.com/fjordllc/bootcamp/pull/5959 も `daily`配下にcontrollerを追加したほうが良かったか？
- こちらのIssueも`scheduler/daily`配下にcontrollerを追加する形で対応したほうが良いのか？

上記2点についておしえていただければと思います。
もし @maeda-m さんと「`scheduler/daily`配下にcontrollerを追加する方針で話し合われているのであればそちらに合わせたほうが良いかなと考えています。

よろしくおねがいします。

**Comment by maeda-m** [comment]
@ksmxxxxxx メリークリスマスです～🎅

似たようなイシューに取り組まれていたのですね。
私から補足できればと思いコメントします💡

> 「scheduler/daily配下にcontrollerを追加する方針で話し合われているのであればそちらに合わせたほうが良いかなと考えています。

こちらは特に方針を話し合っていないです～
`Scheduler::DailyController` の `daily` を参考に、名前空間で分割して漸進的に移行できたらと思い `scheduler/daily/after_retirement` を追加しました～

**Comment by ksmxxxxxx** [comment]
@maeda-m コメントありがとうございます〜（メリクリです）

> こちらは特に方針を話し合っていないです～

なるほど、そうなんですね〜。
`dailyに入ってるものは、基本的にdailyに入れちゃっても良いのかなぁと思いつつ、 #5959 って他のdailyに入ってるやつと同じように日次で動かす……んだよね？？っていうところを確認したいところですね（たぶん、日次でうごかすんだろうなぁと思いつつ指差し確認したいお気持ち）

というわけで @komagata さんの返答を待ちたいと思います〜

**Comment by komagata** [comment]
@ksmxxxxxx 

> https://github.com/fjordllc/bootcamp/pull/5959 も daily配下にcontrollerを追加したほうが良かったか？

YESです。

> こちらのIssueもscheduler/daily配下にcontrollerを追加する形で対応したほうが良いのか？

YESです。

**Comment by ksmxxxxxx** [comment]
@komagata ありがとうございます。
`/scheduler/daily`配下にcontrollerを追加する方針で対応させていただきます〜
