### ISSUE TITLE
notify_product_review_not_completedを別コントローラーに分けたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5933]
[こちら](https://github.com/fjordllc/bootcamp/blame/main/app/controllers/scheduler/daily_controller.rb#L8)の処理を別コントローラーに分けたい。

```ruby
class Scheduler::Xxxxx < SchedulerController
  def show
    # 処理
  end
end
```

## 目的

Scheduler::DailyControllerで定期実行の全ての処理をやっていたが、本番環境で実行時間が長いために全ての処理が終わらなくなってしまった。
それを解決するためにそれぞれ別のURLにしたい。

**Comment by futa4095** [comment]
@komagata
3つほど質問があります。確認よろしくお願いします！！

1. notify_product_review_not_completedを下記のパスに切り出すことを考えています。
`/scheduler/daily/notify_product_review_not_completed`

別のURLにした部分の定期実行の設定は駒形さんが実施されるのでしょうか？

2. 新設するコントローラーは`SchedulerController`を継承することで良いですか？
一部のコントローラーがトークン不要な`ApplicationController`を継承していたのでどちらにするべきか知りたいです。

- `ApplicationController`を継承
  - `Scheduler::Daily::NotifyCertainPeriodPassedAfterLastAnswerController`
  - `Scheduler::Daily::NotifyTomorrowRegularEventController`
- `SchedulerController`を継承
  - `Scheduler::DailyController`
  - その他の`Scheduler::*`

3. notify_product_review_not_completedなんですがN+1問題を抱えているようです。
このissueの範囲外で良いでしょうか？
(bullet.logから判断。`Scheduler::Daily::*`全てに問題あり)

**Comment by komagata** [comment]
@futa4095 全てYESです〜

**Comment by futa4095** [comment]
@komagata @machida 
こちらからメンターチャンネルを見れないため、本番環境での確認をお願いしたいです！

確認内容

- 未完了の提出物の最後のコメントが提出者の場合、5日経過したらDiscordのメンターチャンネルに通知されること

**Comment by machida** [comment]
@futa4095 
了解ですー！
確認のために、発展編にある何か適当なプラクティスから提出をお願いします🙏

提出物の内容には、

動作確認テストの提出物なので、コメント、担当アサインはしないでください。

と書いておいていただけると助かります。

**Comment by futa4095** [comment]
@machida 
提出しました！
https://bootcamp.fjord.jp/products/15222

1点だけ。担当アサインが条件に入っているため、アサインお願いします🙏

**Comment by machida** [comment]
@futa4095 アサインしましたー

**Comment by machida** [comment]
@komagata @futa4095
こちら、まだメンターチャンネルには飛んでないですね。

**Comment by machida** [comment]
@komagata @futa4095
https://github.com/fjordllc/bootcamp/pull/5667
こちらのIssueの段階でも本番でメッセージが飛んでるのを確認できてなかったので、何かDiscordとの連携部分で問題があるのかもしれないです。その調査をお願いします。

**Comment by futa4095** [comment]
本番環境を見れないので推測しかできないですが・・、以下が考えられます
- Discord webhookが環境変数に設定されていない
- 別コントローラーが定期実行されていない
- コントローラー分割後も依然処理に時間がかかりすぎる

**Comment by machida** [comment]
@futa4095 ありがとうございます。

@komagata こちら調査をお願いします🙏

**Comment by komagata** [comment]
@futa4095 

- Discord webhookが環境変数に設定されていない
  - 設定されているようでした。
- 別コントローラーが定期実行されていない
  - 定期実行は成功している状態でした。
- コントローラー分割後も依然処理に時間がかかりすぎる
  - 直接URLにアクセスしたところ時間内にレスポンスが返ってきました。

**Comment by komagata** [comment]
:memo: komagataの方で引き取って調べることになった。

**Comment by machida** [comment]
@futa4095 こちら、`2023/03/25 06:01` から通知が飛ぶようになりました。動作を確認できたのでクローズにしますー
