### ISSUE TITLE
Question.notify_certain_period_passed_after_last_answerを別コントローラーに分けたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5934]
[こちら](https://github.com/fjordllc/bootcamp/blame/main/app/controllers/scheduler/daily_controller.rb#L9)の処理を別コントローラーに分けたい。

```ruby
class Scheduler::Xxxxx < SchedulerController
  def show
    # 処理
  end
end
```

## 目的

Scheduler::DailyControllerで定期実行の全ての処理をやっていたが、本番環境で実行時間が長いために全ての処理が終わらなくなってしまった。
それを解決するためにそれぞれ別のURLにしたい。

**Comment by Seakimhour** [comment]
本番環境で`/scheduler/daily/notify_certain_period_passed_after_last_answer`確認できましたので、
closeさせていただきます！
