### ISSUE TITLE
休会中のユーザーには、`is-hibernationed` というclassを付けたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5937]

**Comment by OdenTakashi** [comment]
@machida 
お疲れ様です！🙌
こちらのIssueは作業が完了次第デザインをお願いした方がよろしいでしょうか？

**Comment by machida** [comment]
@OdenTakashi デザインも同時に進めますー来週のどこかで時間を取って作業しますー

**Comment by OdenTakashi** [comment]
@machida 
ご返信ありがとうございます🙏
承知しました！

**Comment by komagata** [comment]
@OdenTakashi 完了していたらIssueのCloseをお願いします〜

**Comment by OdenTakashi** [comment]
本番環境で動作確認ができましたので、closeします。
