### ISSUE TITLE
日報個別ページにユーザー用のタブナビを表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5938]
## ユーザー用のページタイトル部分を partial 化

<img width="2221" alt="貼り付けた画像_2022_12_13_15_51" src="https://user-images.githubusercontent.com/168265/207246648-e0602805-7c1d-4cce-a481-04f4ca9e402f.png">

この部分を patical にする。

---

ページタイトル部分は

<img width="2221" alt="貼り付けた画像_2022_12_13_15_51" src="https://user-images.githubusercontent.com/168265/207247159-73811bbe-9683-45dd-b814-e1ee69cd95e2.png">

- a ... ユーザー ID
- b ... 日報作成ページへのリンク
- c ... ユーザー一覧へのリンク

の構成にする。

---

A〜G のリンク先のページのページタイトル部分を上記した partical に置き換える。

<img width="2221" alt="貼り付けた画像_2022_12_13_15_51" src="https://user-images.githubusercontent.com/168265/207246946-19f7082e-2a6d-4e2c-b15c-e0230abc5e88.png">

## 日報個別ページにユーザー用のタブナビを表示

現在の日報個別ページはこのようなページタイトルがある。

<img width="2222" alt="image" src="https://user-images.githubusercontent.com/168265/207247596-a282264c-4930-45c5-b5f0-41b3e0a01b6b.png">

このページタイトルを削除し、partial 化したユーザー用のページタイトル部分とタブナビのpartialを配置し、以下のようにする。

<img width="2214" alt="image" src="https://user-images.githubusercontent.com/168265/207247869-fa5b152c-cfea-442a-ae03-851cceef9955.png">

**Comment by lef237** [comment]
本番環境で確認できたのでclose致します！
