### ISSUE TITLE
休会から復帰したときに、メンター、管理者に通知を飛ばしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5952]
通知はサイト内通知、メール通知でお願いします。

**Comment by sadanora** [comment]
@komagata @machida
おつかれさまです！
このissueの本番での動作確認をお願いできますでしょうか。

この動作確認には、ユーザーの休会&復帰操作が必要です。
本番環境に検証用データが存在するか知らないのですが、一旦存在する前提で確認内容を記します🙏

1. 休会
※検証用に休会ステータスのユーザーが存在する場合はこの手順は飛ばして手順2に進んでください。
    1. 検証用ユーザーでログイン
    1. 休会操作を行う
2. 休会から復帰
    1. https://bootcamp.fjord.jp/comeback/new にアクセス
    1. 手順 1で休会したユーザーの復帰操作を行う
    1. ログアウト
3. 管理者でログイン
    - 2で復帰操作したユーザーの復帰通知が飛んでいることを確認。
        - サイト内通知とメール通知が飛んでいるはずです。

**Comment by komagata** [comment]
@sadanora 後ほど休会から復帰するユーザーがいた時に確認したいと思います〜

**Comment by sadanora** [comment]
@komagata 
承知しました、よろしくお願いいたします〜！

**Comment by komagata** [comment]
@sadanora 本番環境で動作することを確認しました。
