### ISSUE TITLE
お知らせ作成画面のタイトル入力部分にプレースホルダーを追加。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5957]
`/announcements/new` このページ。

<img width="1509" alt="貼り付けた画像_2022_12_21_15_50" src="https://user-images.githubusercontent.com/168265/208839878-3c0df04d-5fae-455b-888f-21bcb8969a7d.png">

ここに placeholder で、`今週のリリース2023年12月22日` と設定してほしいです。

**Comment by futa4095** [comment]
本番環境で動作を確認できたのでcloseします
