### ISSUE TITLE
Q&Aなどで使われているタグの名称を正式なものにする

### ISSUE THREAD

**Issue by universato** [fjordllc/bootcamp#5963]
## 概要

バグというか新機能というか、改善要望です。
Q&Aなどで使われているタグの名称を正式なものにする。

- ruby -> Ruby
- rails -> Rails
- css -> CSS
- rubocop -> RuboCop

など。

現状の問題点として、タグ名を正式名称と勘違いするような人がいたり、不正確なタグ名を使いたくない人がいるため。

## 再現手順

https://bootcamp.fjord.jp/questions?target=not_solved
上記リンク先にアクセスして確かめられる。

## スクリーンショット

[![Image from Gyazo](https://i.gyazo.com/c762dfebaca9c6540895a48baa72c8da.png)](https://gyazo.com/c762dfebaca9c6540895a48baa72c8da)

**Comment by komagata** [comment]
@universato いいですね。OSSなのでPRいただければ嬉しいです〜！

**Comment by universato** [comment]
追記です。

- Q&Aのタグ一覧等は「Ruby」と「ruby」、「Rails」と「rails」と両方見られる。
  - ユーザータグのサジェストでも、「Rails」「rails」の両方がでてくる。
- ただ、ユーザータグで「Ruby」「Rails」で登録しようとすると、「ruby」「rails」 になってしまう。

ユーザータグで正式名称にならないのが問題に感じます。
