### ISSUE TITLE
ログイン必須の指定が多すぎる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#5984]
controllerに`before_action :required_login`と書いているが、ほとんどのページがログイン必須なので、デフォルトをログイン必須にして、ログインがいらないページにだけskip_before_actionした方が漏れが少ない。
影響ページが多いのでテストをたくさん書く必要がありそう。

**Comment by peno022** [comment]
本番で、[プラクティス一覧画面](https://bootcamp.fjord.jp/courses/1/practices)（ログインが必要なページ）でトップページにリダイレクトされて「ログインしてください」のメッセージが出ること、[お問い合わせ](https://bootcamp.fjord.jp/inquiry/new)（ログインが不要なページ）にはログインなしでアクセスできることを確認しました。クローズします。
