### ISSUE TITLE
Q&A個別ページの右カラムに、そのカテゴリーの一覧を表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#5999]
<img width="1516" alt="貼り付けた画像_2023_01_05_13_39" src="https://user-images.githubusercontent.com/168265/210703498-c7ad9af5-8bee-411a-b9c1-5500abea02c3.png">

こんな感じで、右カラムにそのページのQ&Aが紐づくプラクティスのQ&A一覧を表示したい。

**Comment by futa4095** [comment]
@machida
数が多いですが質問があります！回答お願いします！

### 右カラム質問一覧のイメージ

|OS X Mountain Lionをクリーンインストールする|
|-|
|更新日時が新しい質問|
|WIPの質問|
|未解決の質問|
| 解決済みの質問 |
| : |
|更新日時が古い質問|
|もっと見る|

### 質問1 一覧にタイトル以外にも表示したい項目はありますか？

候補
- ユーザーアイコン
- ユーザー名
- 作成日時
- 更新日時
- WIPであるか
- 解決済みであるか
- 回答コメント数
- プラクティス名

### 質問2 表示順について

Q&A一覧ページと同じ順番(更新日時の降順, idの降順)で良いでしょうか？

### 質問3 未解決やWIPの扱い

未解決やWIPを除外して、解決済みだけ表示しますか？

### 質問4 カテゴリーに紐づくQ&Aがない場合は？

↓のように一覧の中身を空にして良いでしょうか？

|質問がないプラクティス|
|-|
|もっと見る|

左カラムの質問は一覧に含めない認識です

### 質問5 カテゴリー未選択の場合は？

カテゴリー(プラクティス)を未選択のQ&Aの場合、右カラムの表示は不要ですか？

### 質問6 Rails(API) + Vue.jsで作るべきですか？

当初Railsのみで作る想定でしたが、左カラムがVue.js + Rails APIで作られており、
右カラムがRailsのみの場合に動作が不自然になります。(右カラムが左より先に表示される)

### 質問7 左カラムから内容修正をしてプラクティスを変更した場合に、右カラムの一覧にも反映するべきですか？

issueの範囲を確認したいです。
Vue.jsを使うかどうかで実現方法が変わりそうなので気にしています。

**Comment by machida** [comment]
@futa4095 おまたせしました🙇‍♂️
お答えしますー。

> 質問1 一覧にタイトル以外にも表示したい項目はありますか？

ユーザー名
作成日時
解決済みであるか
回答コメント数

を出していただきたいです。デザインは machida がやりますー

> 質問2 表示順について

Q&A一覧ページと同じ順番 でお願いします。

> 質問3 未解決やWIPの扱い

未解決は表示、WIPは非表示でお願いします。

> 質問4 カテゴリーに紐づくQ&Aがない場合は？

今後変更が発生するかもですが、今回は提案していただいた形でお願いします。

>  質問5 カテゴリー未選択の場合は？

もし可能でしたら、未選択のQ&Aの一覧を表示していただきたいです。
多分、何かしらのプラクティスに紐付けられるので、一覧を表示した上で紐付け作業を行うためです。
その際の右カラムの見出しは、`関連プラクティス無し` としていただきたいです。

> 質問6 Rails(API) + Vue.jsで作るべきですか？

今回は Rails のみでお願いします。

>  質問7 左カラムから内容修正をしてプラクティスを変更した場合に、右カラムの一覧にも反映するべきですか？

おお、これは見逃してました。今回は範囲外としたいと思います。
この Issue の PR がマージされたら、右カラムの一覧にも反映の Issue 追加をお願いします🙏

**Comment by futa4095** [comment]
本番環境で確認できたのでcloseします！
