### ISSUE TITLE
Doc個別ページの右カラムに、そのDocの紐づくプラクティスに紐づくDocs一覧を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6000]
<img width="1293" alt="貼り付けた画像_2023_01_05_13_46" src="https://user-images.githubusercontent.com/168265/210703933-2f39d5fe-a5bd-4399-b2f1-8c84263fe2ab.png">

**Comment by lef237** [comment]
本番環境で動作確認ができたのでclose致します。
