### ISSUE TITLE
お知らせの通知ターゲットの「全員」の内訳をUI上で確認したい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6003]
お知らせ編集画面の通知ターゲットに「全員」とありますが、何を持って「全員」なのかがわからず、選択するのが少し不安になりました。

<img width="720" alt="Screenshot 2023-01-05 at 17 05 32" src="https://user-images.githubusercontent.com/1148320/210731890-94eabec2-4b21-4716-a4f5-4f9e365b0c57.png">

[テストコード](https://github.com/fjordllc/bootcamp/blob/main/test/system/notification/announcements_test.rb#L12)を見ると「退会者を除く全員」っぽいことがわかったのですが、何かしらの方法で具体的な対象者がわかるようになっていると嬉しいです。

たとえばボタンのラベルを「全員（退会者を除く）」にする、など。

**Comment by machida** [comment]
@maimux2x 
全員（退会者を除く）に変更をお願いしますー
