### ISSUE TITLE
初日報の通知をメンターのみにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6006]
現在、新しく入会したユーザーが初めての日報を提出すると、現役受講生、メンターに通知（サイト内通知、メール通知）が飛んでいるが、これをメンターのみに変更したい。

**Comment by futa4095** [comment]
@komagata @machida 
本番確認の協力お願いします！🙏

依頼したいこと
- 初日報の通知が届いたら連絡をいただきたいです

連絡を受けて、私に通知が来ていないことを確認できたらcloseします。

**Comment by futa4095** [comment]
Discordで初日報の通知が届いていると連絡をいただきました
想定通りこちらには届いていないのでcloseします
