### ISSUE TITLE
[newspaper] 提出物のステータス変更処理をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6018]
CheckCallbacks.rbにある提出物のステータス変更処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/check_callbacks.rb#L7)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by peno022** [comment]
本番で確認できたのでクローズします。
