### ISSUE TITLE
イベント作成ページの会場にプレースホルダが欲しい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6020]
<img width="1033" alt="貼り付けた画像_2023_01_11_16_14" src="https://user-images.githubusercontent.com/168265/211741332-509bde6a-d066-4e87-86af-2ba65f87d730.png">

プレースホルダの内容は、

```
オンライン（Remo: https://live.remo.co/e/XXXXX）
```

でお願いします。

**Comment by lef237** [comment]
本番環境で確認できたのでclose致します！
