### ISSUE TITLE
イベント個別ページの上部を変更したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6022]
<img width="1359" alt="貼り付けた画像_2023_01_11_16_39" src="https://user-images.githubusercontent.com/168265/211745980-8a975dd1-9262-445c-a7d6-4a3df5f5f4fd.png">

この部分を変更したい。

<img width="1582" alt="貼り付けた画像_2023_01_11_16_44" src="https://user-images.githubusercontent.com/168265/211747070-ef73e208-c3c6-4fbf-b5cf-a864867f31f3.png">

↑こうしたい

**Comment by lef237** [comment]
本番環境で確認できたのでClose致します！
