### ISSUE TITLE
ユーザー一覧targetアドバイザーにエラーが発生する

### ISSUE THREAD

**Issue by Seakimhour** [fjordllc/bootcamp#6024]
## 概要

ユーザー一覧targetアドバイザーにエラーが発生される。
エラーが発生する環境はStagingとDevelopmentのみ、Production環境は発生しない。

## 再現手順

1. `https://bootcamp-staging.fjord.jp/users?target=adviser`にアクセス。
2. ブラウザConsoleでエラーが表示される。

## 期待される振る舞い

エラーが発生しない。

## スクリーンショット

![Screenshot 2023-01-11 174014](https://user-images.githubusercontent.com/52590443/211758413-0f29a788-5471-4317-9c36-07f921094b3e.png)

## 環境

 - OS: Windows 11
 - ブラウザ: chrome
 - バージョン: 108.0.5359.125 (Official Build) (64-bit)

**Comment by akingo55** [comment]
発生するのはSTG環境のみ
DEVでは発生しない

**Comment by akingo55** [comment]
@machida 
お疲れ様です！
こちら調査しまして、DEVでは再現せずSTGのみ再現する状態でした。
ターゲットユーザー一覧を`userDescParagraphs`プロパティを使って、ループして表示させていると思いますが、
Chromeのデベロッパーツールに確認したところループ回数が4回あり、4回目は変数`description`にnullが入ってきているようでした。
このことからアドバイザーロールで表示できないユーザーが存在しているのでは？と考えているので、お手隙にrails console等で`User.users_role('adviser').unretired`にヒットするユーザーを確認していただけないでしょうか？:pray:

![image](https://user-images.githubusercontent.com/43959158/212550616-cb18e911-29e8-4bab-b386-3b804e57e2a3.png)

**Comment by machida** [comment]
@akingo55 

<img width="2017" alt="貼り付けた画像_2023_01_16_0_42" src="https://user-images.githubusercontent.com/168265/212550911-59ada061-2e6f-46b0-a392-5b4969d64be0.png">

このユーザーでしたー。
このユーザーの seed データの修正をお願いします🙏
