### ISSUE TITLE
プラクティス作成のタイトルにプレースホルダが欲しい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6026]
メンターでログインし、プラクティスへ。

<img width="1952" alt="貼り付けた画像_2023_01_11_22_26" src="https://user-images.githubusercontent.com/168265/211817811-308c8ad8-4040-4116-8706-08ee6fbcb7ea.png">

そこからプラクティス作成ページへ行く。

<img width="1025" alt="貼り付けた画像_2023_01_11_22_09" src="https://user-images.githubusercontent.com/168265/211814495-c871de4c-3225-4143-8707-79d57b7a453f.png">

ここにプレースホルダをお願いします。

```
JavaScript 入門
```

↑ プレースホルダの文言はこれでお願いします。

**Comment by e6i24vi** [comment]
大変レベルの低い質問で申し訳ないのですが、メンターでログインというのは具体的にどのようにするということでしょうか？
- メンターのIDとかパスワードとかどこかでわかるのでしょうか？
- ログインというのはFjordのアプリにログインするということでしょうか？

**Comment by komagata** [comment]
@e6i24vi 

> メンターのIDとかパスワードとかどこかでわかるのでしょうか？

下記をご覧になっていただければわかると思います〜。

[Develop環境でログインする方法 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/Develop%E7%92%B0%E5%A2%83%E3%81%A7%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95)

> ログインというのはFjordのアプリにログインするということでしょうか？

はい。

別件ですが、気づくことができないため、連絡を取りたい場合はメンションを使っていただければありがたいです〜。

[基本的な書き方とフォーマットの構文 \- GitHub Docs](https://docs.github.com/ja/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#%E4%BA%BA%E3%82%84-team-%E3%81%AE%E3%83%A1%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%B3)

**Comment by machida** [comment]
@e6i24vi こちらはクローズにさせていただきます。
