### ISSUE TITLE
個人の日報一覧もプラクティスで絞り込みたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6037]
<img width="1216" alt="貼り付けた画像_2023_01_12_14_11" src="https://user-images.githubusercontent.com/168265/211982579-d13a73f1-fe8a-4bc1-bee7-135382babca9.png">

<img width="725" alt="image" src="https://user-images.githubusercontent.com/168265/211982650-efb9d38e-ffab-4fe7-9f4d-396f74f1fde4.png">

これを追加して、プラクティスで絞り込みたい。

**Comment by komagata** [comment]
:memo: 画面遷移無しで絞り込みたい

**Comment by peno022** [comment]
本番で確認できましたので、クローズします。

初期表示
![スクリーンショット 2023-02-18 14 34 16](https://user-images.githubusercontent.com/40317050/219843106-cd404f48-56c3-46ec-ba16-f87f479cfb61.png)

絞り込み（該当あり）
![スクリーンショット 2023-02-18 14 34 24](https://user-images.githubusercontent.com/40317050/219843104-fcb4ca47-e6a3-4e5f-b7a8-7ac592b2ac88.png)

絞り込み（該当なし）
![スクリーンショット 2023-02-18 14 34 37](https://user-images.githubusercontent.com/40317050/219843103-ef348788-2194-47d3-b8b2-5cf8f8df1d37.png)
