### ISSUE TITLE
お問い合わせのスパム対策としてお問い合わせページに Google reCAPTCHA v3 を導入したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6038]
https://qiita.com/HavenSpring/items/98fa8960746c944b6e8c
こちらを参考にして導入。

**Comment by maeda-m** [comment]
@komagata #6072 をステージング環境で確認するため、次の設定をお願いしたいです。

### 1. Google reCAPTCHA v3 の利用を始めるためにサイトを登録する

https://www.google.com/recaptcha/admin/create にアクセスしてフリープランとしてサイトを登録します。

次の項目を入力・チェックしてフォームを送信すれば登録できます。
フォーム送信後に表示される2つのキーは環境変数で使用するため、コピーして控えてください。

|項目|入力値・チェック有無|備考|
|-----|-------------------------|-----|
|ラベル|bootcamp|任意の値で問題ありません。|
|reCAPTCHA タイプ|reCAPTCHA v3||
|ドメイン|bootcamp.fjord.jp<br>bootcamp-staging.fjord.jp|項目下の ＋ で入力欄を追加できます。|
|reCAPTCHA 利用条件に同意する|チェックを入れる|利用規約をご確認ください。|
|アラートをオーナーに送信する|任意です||

### 2. 2の環境変数を [cloudbuild-staging.yaml](https://github.com/fjordllc/bootcamp/blob/main/.cloudbuild/cloudbuild-staging.yaml) に設定する

前述の「Google reCAPTCHA v3 の利用を始めるためにサイトを登録する」で発行された各キーを環境変数を設定してください。

|環境変数|値の説明|
|----------|----------|
|`RECAPTCHA_SITE_KEY`|このサイトキーは、ユーザーに表示するサイトの HTML コードで使用します。と説明がある値です。|
|`RECAPTCHA_SECRET_KEY`|このシークレット キーは、サイトと reCAPTCHA 間の通信で使用します。と説明がある値です。|

> **Note**
> なお本番環境へのリリース時においても同様に環境変数への設定が必要になります。

以上、よろしくお願いします🙏

**Comment by komagata** [comment]
@maeda-m 大変遅くなりました。設定いたしました。

#6237

**Comment by maeda-m** [comment]
@komagata 設定ありがとうございました🙏 スパム対策の動作を確認できました～

**Comment by maeda-m** [comment]
本番環境で動作を確認しましたので Close します🎉

以下、確認手順です。

1. 次のJSでお問い合わせフォーム画面の上に「Bot対策のため送信を拒否しました。しばらくしてからもう一度送信してください。」と表示されることを確認した
```javascript
const bot = window.open('https://bootcamp.fjord.jp/inquiry/new', '_blank')
setTimeout(() => {
  bot.document.querySelector('form').submit()
}, 3000)
```
2. 1のお問い合わせフォーム画面の項目をすべて入力・チェックし、ボタン「送信」をクリックし、「お問い合わせを送信しました。」と表示されることを確認した
    - お問い合わせ内容には `実際のお問い合わせではありません。無視してください。` と記載しておきました
