### ISSUE TITLE
他の人のWIP提出物ページでの警告メッセージが適切でない

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#6045]
## 概要

以下の提出物個別ページを表示すると警告メッセージがWIPにしたユーザー以外にも表示される(スクリーンショット参照)
- 提出物がWIP
- 他人の提出物

メッセージの内容的にWIPにした本人向けと思われます

例えば「完成したら「提出する」をクリック！」←本人以外はクリックできない

## 再現手順

1. WIP状態 かつ 他人の提出物個別ページにアクセス。
（「開発に参加して PR を送りマージする」の提出物タブで見つかります）
1. 警告メッセージが表示される(スクリーンショット参照)

## 期待される振る舞い

WIPにしたユーザー本人のみに表示
またはメッセージの内容を変更（「完成したら「提出する」をクリック！」を削除するなど）

## スクリーンショット

![image](https://user-images.githubusercontent.com/69447745/212232657-0c330041-651b-46fc-8ae2-df06b72f09af.png)

**Comment by machida** [comment]
:memo:

提出物作成者にだけこのメッセージを表示するようにする。

**Comment by komagata** [comment]
:memo: e6i24vi さんが休会されたのでアサインを外させていただきました。

**Comment by junohm410** [comment]
本番環境での動作が確認できましたので、このIssueはCloseいたします。
