### ISSUE TITLE
参考書籍一覧のセレクトボックスの文言を修正したい

### ISSUE THREAD

**Issue by peno022** [fjordllc/bootcamp#6047]
## 概要

参考書籍一覧画面（ https://bootcamp.fjord.jp/books ）のセレクトボックスで、何も選択されていない時の文言が
「全ての質問を表示」になってしまっているので、「全ての書籍を表示」に修正したいです。

![image](https://user-images.githubusercontent.com/40317050/212280446-17a9665d-2f4e-4f8e-92a6-ac477acfdf93.png)

**Comment by uchihiro04** [comment]
本番環境で動作確認ができましたので、issueをcloseいたします。
