### ISSUE TITLE
ログイン失敗時に続けてログインできない

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#6055]
## 概要

`/login`でログインに失敗すると、その後正しい「ユーザー名」「パスワード」を入力してもログインできない。

再度`/login`にアクセスし直し、正しい「ユーザー名」等を入力した場合はログイン可能です。

## 再現手順

1. ログイン中の場合はログアウトする。
1. /loginにアクセス。
1. 「ユーザー名」「パスワード」を空にして、「ログイン」をクリック。
1. アドレスバーが「/user_sessions」になり、「ユーザー名かパスワードが違います。」のエラーが表示される。
(この時「パスワード」のラベルが「Password」になる)
1. 「ユーザー名」「パスワード」を正しい情報にして、「ログイン」をクリック。
1. 「ユーザー名かパスワードが違います。」のエラーが表示されログインできない。

## 期待される振る舞い

ログイン失敗後も、「ユーザー名」「パスワード」が正しい場合にはログインできる

## スクリーンショット

developmentで取得していますが、本番環境でも起きます

#### /login (未入力のままログイン)

<img width="584" alt="image" src="https://user-images.githubusercontent.com/69447745/212532350-0e8597ae-1c17-4edd-ba66-e921633e0864.png">

#### /user_session (/loginからのログイン失敗時と/user_sessionで正しい内容を入力して失敗した時で同じスクショになりました)

<img width="606" alt="image" src="https://user-images.githubusercontent.com/69447745/212532443-753188d9-119c-4e52-abb8-5bf955c4eaef.png">

## 環境

 - OS: macOS 13.1（22C65）
 - ブラウザ: chrome
 - バージョン: 108.0.5359.124

## 関連Issue

Ref: #5380

**Comment by komagata** [comment]
@futa4095 Issue登録ありがとうございます〜！
いい機会ですので、お時間あったら是非こちらのバグの修正にチャレンジしてみてください。ポイントも割り振っておきます。

**Comment by futa4095** [comment]
本番環境で確認できたのでcloseします
