### ISSUE TITLE
bootcamp内でeveryoneへとメンションできる機能が欲しい

### ISSUE THREAD

**Issue by lef237** [fjordllc/bootcamp#6056]
## 機能の説明

DiscordやSlackの`@everyone`のように、FBC内の全員に送れるメンション機能があると良さそうだと思いました。

## 何故この機能が必要なのか

例えば、大事なお知らせがあって、その内容に修正があることを全体に伝えたい場合、再度お知らせを作り直す必要がありました。

しかし、`@everyone`のような全体にメンションできる機能があれば、お知らせ等を新規作成する必要もなく、コメント欄に
```
@everyone
このお知らせに誤記があったので修正致しました！
〇〇イベントの開催日は1/16ではなく、1/17となっております。お間違えの無いようにお気をつけください🙏
```
と書くだけで、全体に知らせることができます。

具体的な仕様としては、
```
@everyone → 全体に送る
@students → 現役生
@graduate → 卒業生
@adviser → アドバイザー
@trainee → 研修生
```
などがあると良さそうだと思いました。

※メンターの方全員に送る`@mentor`は既にあります。

**Comment by komagata** [comment]
@lef237 メンションひとつで大量の通知が送られてしまうので、システムの負荷や容量的に少し抵抗があります。

メリットがものすごく大きいのであれば実現するために仕組みを考えたいですが、まだそこまでではないかな〜と思っています。

**Comment by lef237** [comment]
承知致しました！ issueもclose致します。🙏
