### ISSUE TITLE
TypeScript, JSX, TSXにもシンタックスハイライトが適用されるようにしたい

### ISSUE THREAD

**Issue by lef237** [fjordllc/bootcamp#6057]
## 機能の説明

bootcamp内でもTypeScript, JSX, TSXのコードにもシンタックスハイライトが適用されるようにする。

## 何故この機能が必要なのか

現状では、bootcamp内のアプリでは、TypeScriptやJSX, TSXのシンタックスハイライトに対応していないため、コードが読みづらいという問題が生じています。

例えば次のTypeScriptのコードをご覧ください。

```ts
class Person {

    name: string;
    age: number;

    constructor(name: string, age: number) {
        this.name = name;
        this.age = age;
    }
}
```

GitHubではこのようにハイライトが付くコードでも、bootcamp内ではこのようになってしまいます。

![image](https://user-images.githubusercontent.com/93074851/212611161-04154630-fbde-4e52-a86e-de465e1340f8.png)

そのため、bootcamp内でもGitHubのように、TypeScript, JSX, TSXにシンタックスハイライトが適用されるようにしたいです。

※JSXやTSXはReactやNextjsで使われる形式です。

**Comment by komagata** [comment]
@lef237 ちょうどいい機会なので是非チャレンジしてみてください〜。ポイントも割り振っておきました〜。

**Comment by lef237** [comment]
本番環境で動作確認ができたのでclose致します。
