### ISSUE TITLE
卒業通知メールの本文にあるリンクが相対的なURLになっている

### ISSUE THREAD

**Issue by maeda-m** [fjordllc/bootcamp#6065]
## 概要

表題の通り。

## 再現手順

1. http://localhost:3000/rails/mailers/activity_mailer/graduated にアクセスする
2. 卒業アカウントへのリンク要素を検証ツールから確認する

## 期待される振る舞い

ホスト名を含めたURLに変更する必要がある。

参考： [Action Mailer の基礎 - Railsガイド | 2.7 Action MailerのビューでURLを生成する](https://railsguides.jp/action_mailer_basics.html#action-mailer%E3%81%AE%E3%83%93%E3%83%A5%E3%83%BC%E3%81%A7url%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B)

## スクリーンショット

![path_to_url](https://user-images.githubusercontent.com/943541/213100220-de9f4f8a-f330-45f6-92f8-b818b2e767e1.png)

## 環境

 - OS: Windows 10
 - ブラウザ: Google Chrome
 - バージョン: `108.0.5359.126`

## 関連Issue

Ref: #6001

**Comment by maeda-m** [comment]
@komagata @machida こちらのプルリクエスト #6067 がリリースされましたので動作確認のために
本番環境でユーザー一覧から現役生を選んで卒業にする操作をお願いしたいのですがいかがでしょうか？
こちら、本番環境だと影響が大きいので確認なしでクローズでしょうか？

**Comment by komagata** [comment]
@maeda-m こちら確認せずにCloseで大丈夫です〜。
卒業生が出た時に僕が確認しておきます〜。

**Comment by maeda-m** [comment]
@komagata 承知しました～
Closeしますね😀
