### ISSUE TITLE
休会中または退会済みのユーザーで、ログインに失敗した後、ログインし直すとRouting Errorは発生する

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#6079]
## 概要

休会中または退会済みのユーザーでログインを試みてログイン不可となった後に
続けてログインをクリックするとRouting Errorが発生する
<img width="461" alt="スクリーンショット 2023-05-09 20 02 03" src="https://github.com/fjordllc/bootcamp/assets/54713809/af64abcd-d7bf-44f3-ab92-b9607607224f">
## 再現手順

1. http://localhost:3000/login にアクセス。
2. ユーザー名に`kyuukai`、パスワードに`testtest`を入力して、「ログイン」をクリック。
3. 休会中のメッセージが表示される。
4. 「ログイン」をクリック。
5. Routing Errorが発生する。
(staging環境では404 not foundとなります)

退会済みのユーザーで確認する場合は`yameo`などを使用してください

## 期待される振る舞い

Routing Errorが発生しない。
ログイン可能なユーザー・パスワードであればログインでき、それ以外はログイン画面を表示する。

## スクリーンショット

![routingerror](https://user-images.githubusercontent.com/69447745/213705305-b95247fc-0093-47f7-b17a-c1e14bccb44d.gif)

## 関連Issue

Ref: #6055

**Comment by syo-tokeshi** [comment]
@komagata 
お疲れ様です。
こちらの本番環境での動作確認なのですが、

- 休会中または退会済みのユーザーでログインを試みてログイン不可となった後に、
続けてログインをクリックするとRouting Errorが発生する

という動作は、私の方では確認することができません🙇‍♂️(そのユーザーの情報を知らないからです)

stエージング環境での動作確認は私の方で確認が取れたのですが、
本番環境での確認をお願いしてもよろしいでしょうか？
