### ISSUE TITLE
SeedデータがValidateの設定にあってない

### ISSUE THREAD

**Issue by ksmxxxxxx** [fjordllc/bootcamp#6082]
## 概要

 #5959 実装中に見つけました。
`db/fixtures/users.yml`に登録されている `marumarushain<%= i %>`のseedデータが、Userの`name_kana`のvalidateの設定にあってないため、`update!`などを使った際にvalidateエラーになることがあります。

## 再現手順

1. `marumarushain8`でログイン
2. `/current_user`（登録情報変更）で名前（カナ）に`マルマル シャイン8`が入った状態のまま「更新する」をクリック
3. エラーが表示される。
4. 名前（カナ）の`マルマル シャイン8`→`マルマル シャイン`に変更→更新するをクリック
5. 正常に更新される

## 期待される振る舞い

`update!`などDBの更新を実行した際にvalidateエラーが出ないようになる

### 対応案

- Userの`name_kana`のvalidateで数字を許容する変更を行う
- Seedデータから数字を抜く

上記のいずれかの対応をするのがいいと思います。

## スクリーンショット

![image](https://user-images.githubusercontent.com/5976902/213858733-79295759-4ef4-4da6-af8b-ee107d56adfb.png)

## 環境

 - OS: mac OS Montrey
 - ブラウザ: Firefox
 - バージョン: 最新版

## 関連Issue

Ref: #5959

**Comment by uchihiro04** [comment]
振り返り・計画ミーティングおよび質問タイムでバグ修正の方針が定まったため、こちらに残しておきます。

* 該当するSeedデータのUserについて`nama_kana`の数字を抜き、代わりに末尾にカタカナ1文字をつける。
* カタカナは重複しない形にする。順不同で問題ない。
* `test/fixtures/users.yml`内のSeedデータと同じ形で修正する。

**Comment by uchihiro04** [comment]
開発環境およびステージング環境にて動作確認を行い、エラーが出ないことを確認しましたためissueをクローズいたします。
