### ISSUE TITLE
ログイン画面の「サインアップ」を「参加登録」にする

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#6087]
## 概要

トップページの「参加登録」とログイン画面の「サインアップ」がどちらも同じリンク先のため揃えたい。

#### /login

<img width="300" alt="image" src="https://user-images.githubusercontent.com/69447745/214026587-9e5442de-789c-4843-ac01-1a581323cf7d.png">

#### /

<img width="400" alt="image" src="https://user-images.githubusercontent.com/69447745/214027102-ae6bac11-06ce-4ff8-ac78-c8585c705531.png">

#### /users/new

<img width="400" alt="image" src="https://user-images.githubusercontent.com/69447745/214027317-7ccf933f-4481-4249-bc30-a5f51648a0f3.png">

**Comment by mono-nobe** [comment]
本番環境に反映されていることを確認したためcloseする
