### ISSUE TITLE
メンターとして、Watchしているプラクティスの提出物があったときに届く通知が二重で飛んでいるかチェック・修正。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6088]
メンターにはプラクティスをWatchする機能があります。

<img width="836" alt="貼り付けた画像_2023_01_24_14_05" src="https://user-images.githubusercontent.com/168265/214216044-23f23bb1-edc6-4a61-8617-5afc6d1bee17.png">

プラクティスをWatchすると、そのプラクティスの提出物が作成された際に（ユーザーがそのプラクティスの提出物を提出した際に）、通知が届きます。

その通知が二回飛んでいるっぽいです。その調査をお願いします。二回飛んでいたら修正をお願いします。

**Comment by uchihiro04** [comment]
こちらのissueにつきまして、2点ほど質問させていただければと思います。
1. 調査結果の提出方法について
こちらのissue調査
1. 調査範囲について

**Comment by machida** [comment]
@uchihiro04 

> 調査結果の提出方法について

Issueのコメントに調査結果を書き、machida にメンションをお願いします🙏

> 調査範囲について

通知が二重で飛んでそうなのは、サイト内通知（画面右上のベル） になります。

起きている状況としては、

- machida がメール通知をオフにしている。
- machida はいくつかのプラクティスを watch している。
- watch しているプラクティスに提出物があった場合にmachidaにサイト内通知が来る。
- サイト内通知をクリックしても消えない。
- もう一回クリックすると消える。

ということが起きています。

**Comment by uchihiro04** [comment]
@machida 
メンターとして、Watchしているプラクティスの提出物があったときに通知が二重で飛んでいるかチェックを行いました。
結論から申し上げると、最新のmainブランチではissueのような現象は再現できませんでした。

以下、調査の詳細となります。
`machida`でログインし、2つのプラクティスを「watch中」にします。

![スクリーンショット 2023-02-06 11.40.48.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFRxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8088dda508d7ae0a1120359907f6f91b80206017/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202023-02-06%2011.40.48.png)

![スクリーンショット 2023-02-06 11.41.46.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFhxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c113493f821bda873fc5d8b5d6ba32d4d8711bb3/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202023-02-06%2011.41.46.png)

次にメール通知をOFFにします。
![スクリーンショット 2023-02-06 11.43.32.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--810f10547584de95a0a8f234b4215742fb400fe9/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202023-02-06%2011.43.32.png)

次に`rie`でログインし、「machida」でwatch中になっているプラクティスの課題を提出します。
![スクリーンショット 2023-02-06 14.22.19.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG5xQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c723ebd139cc079a57f5d58eed14d3f4beeb2bd/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202023-02-06%2014.22.19.png)

再度`machida`でログインし、サイト内通知をクリックします。
![23020601](https://user-images.githubusercontent.com/77523896/216905562-32bfaa93-8cc1-40a6-9ee1-3202bb85966f.gif)

クリックすると、該当する通知は消えました。
`mentormentaro`でも試してみましたがissueのような状況は発生しませんでした。また、ステージング環境でも確認してみましたが、issueのような状況は再現できませんでした。

コンソールでDBを確認してみましたが、作成された通知は1つでした。
<img width="818" alt="image" src="https://user-images.githubusercontent.com/77523896/216906024-9e84a65b-0d22-49d5-a8a6-c907187d6a8b.png">

実行した環境は以下の通りです。
* PC: MacBook Air
* チップ: Apple M1
* MacOS: Ventura 13.1
* ブラウザ: Google Chrome
* ブラウザのバージョン: 109.0.5414.87（Official Build）（arm64）

**Comment by machida** [comment]
@uchihiro04 調査ありがとうございました！！こちら、本番でも発生しないことが確認できましたのでクローズさせていただきますー 通知の仕組みを置き換えて修正されたのかもしれないです。
