### ISSUE TITLE
お知らせを全員が公開できるようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6089]
現在は、お知らせの作成は誰でもできるが、メンターしかお知らせの公開権限がない。
全員が公開できるように変更したい。
この変更に伴い、メンターに連絡をしてください、的なメッセージも削除する。

**Comment by Seakimhour** [comment]
@machida @komagata 1点確認をしたいです。
> 全員が公開できるように変更したい。

お知らせに見れる全が公開できるですか？
それともお知らせ作成者とメンターとアドミンユーザーですか？

**Comment by machida** [comment]
@Seakimhour
すいません、仕様の説明が足りてませんでした🙇‍♂️

公開できるのは、

- そのお知らせの作成者
- アドミン
- メンター

でお願いします。

**Comment by Seakimhour** [comment]
本番環境で動作確認をできましたので、closeさせていただきます！
