### ISSUE TITLE
ページ作成のスラッグの説明文の修正

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6090]
`/pages/new` にアクセス。

<img width="1029" alt="貼り付けた画像_2023_01_24_14_23" src="https://user-images.githubusercontent.com/168265/214218057-ada3798d-119f-49da-990a-5a7ed7f66a1f.png">

これを修正。

```
スラッグを設定すると`https://bootcamp.fjord.jp/pages/{スラッグ}`の様にスラッグで指定した文字列のURLでアクセスが出来るようになります。
スラッグにはアルファベットから始まる半角英数字と、ハイフン （ - ）、アンダーバー （ _ ） が使えます。
```

上記にしてください。

**Comment by shizimi50** [comment]
本番環境での動作確認完了したため、closeします。
