### ISSUE TITLE
ページ作成のスラッグのinput に placeholder を設定したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6091]
`/pages/new` にアクセス。

<img width="740" alt="貼り付けた画像_2023_01_24_14_28" src="https://user-images.githubusercontent.com/168265/214218620-212eab5c-eae2-4782-991d-37461f6bcf36.png">

placeholder で help と設定してほしい。

<img width="123" alt="image" src="https://user-images.githubusercontent.com/168265/214218693-ac03954c-fb6d-4e1b-8302-969d72b90f2d.png">

これを追加して、

<img width="760" alt="image" src="https://user-images.githubusercontent.com/168265/214218730-c1e1b587-cc5e-4cf9-a5a2-1d9f05603d94.png">

こうしたい。

**Comment by ymmtd0x0b** [comment]
本番環境にて動作確認しましたので Close します！
