### ISSUE TITLE
ページ作成のタイトルに placeholder を設定したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6092]
`/pages/new` にアクセス。

<img width="765" alt="貼り付けた画像_2023_01_24_14_46" src="https://user-images.githubusercontent.com/168265/214220899-57b5d6d2-5a6b-4346-a5e4-8de4765f1119.png">

placeholder で `つらくなったときに見るドキュメント` と設定してほしい。

<img width="252" alt="image" src="https://user-images.githubusercontent.com/168265/214220746-1214fc73-78bf-4617-8f63-dd1d9005d14a.png">

これを追加して、

<img width="737" alt="image" src="https://user-images.githubusercontent.com/168265/214220846-4a2cb513-282b-4df6-bf85-7be9eb55763c.png">

こうしたい。

**Comment by shizimi50** [comment]
本番環境で動作確認完了したため、closeします。
