### ISSUE TITLE
質問作成のタイトルに placeholder を設定したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6093]
`/questions/new` にアクセス。

<img width="797" alt="貼り付けた画像_2023_01_24_14_51" src="https://user-images.githubusercontent.com/168265/214221428-11baefa7-f07c-4fec-b229-e2b1c3f72398.png">

placeholder で `メソッドを定義するときの考え方がわからない` と設定してほしい。

<img width="303" alt="image" src="https://user-images.githubusercontent.com/168265/214221510-0ef271e3-8c7b-44f1-8c1e-e3412fedb72b.png">

これを追加して、

<img width="751" alt="image" src="https://user-images.githubusercontent.com/168265/214221557-9e739193-04ae-45ab-a4df-a073ec223aba.png">

こうしたい。

**Comment by mono-nobe** [comment]
本番環境で問題なく追加されていることを確認したためclose

<img width="838" alt="スクリーンショット 2023-02-21 21 02 40" src="https://user-images.githubusercontent.com/94843475/220339840-f517478d-d1aa-498b-aaf9-7cda676eb2d7.png">
