### ISSUE TITLE
プラクティス作成のタイトルに placeholder を設定したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6094]
メンターでログインし、

<img width="1718" alt="貼り付けた画像_2023_01_24_14_59" src="https://user-images.githubusercontent.com/168265/214222373-d3a39019-ade9-49eb-9798-2ddd69a5fc58.png">

これをクリック。

<img width="853" alt="貼り付けた画像_2023_01_24_15_00" src="https://user-images.githubusercontent.com/168265/214222485-b95286d4-7ec1-442b-a675-efc6173a34ce.png">

placeholder で `HTMLの基本を理解する` と設定してほしい。

<img width="206" alt="image" src="https://user-images.githubusercontent.com/168265/214222674-2d5e7ffe-6c46-447d-8e67-df097b5e241f.png">

これを追加して、

<img width="755" alt="image" src="https://user-images.githubusercontent.com/168265/214222703-abd4599c-0fa1-4f8c-bb6e-fba04e16cea3.png">

こうしたい。

**Comment by uchihiro04** [comment]
@komagata @machida 
本番環境にて、プラクティス作成画面のタイトルの部分にplaceholderが追加されているか確認をお願いいたします🙇‍♂️
確認方法は以下の通りです。

1. ログイン後、サイドバーの「プラクティス」をクリックする
![image](https://user-images.githubusercontent.com/77523896/218034925-f6036e07-0a52-4edd-a49d-d036b597dab1.png)

1. 画面右上の「プラクティス作成」をクリックする
![image](https://user-images.githubusercontent.com/77523896/218035029-d1006321-fb72-4ba4-90fa-c86586367358.png)

1. プラクティス作成画面のタイトルにplaceholder（HTMLの基本を理解する）が表示されているか確認する
![image](https://user-images.githubusercontent.com/77523896/218035080-d9d9176e-d2f5-494a-9fd3-72fdabe54a0e.png)

**Comment by komagata** [comment]
@uchihiro04 本番環境で動作することを確認しました。

**Comment by uchihiro04** [comment]
本番環境で動作確認ができましたので、issueをcloseいたします。
