### ISSUE TITLE
[都道府県別ユーザー一覧]ユーザー情報のお住まいの都道府県に海外の場合も対応したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6095]
<img width="235" alt="貼り付けた画像_2023_01_24_15_06" src="https://user-images.githubusercontent.com/168265/214223161-2840ce20-96ad-499c-8ebc-345d6536cec8.png">

ユーザー情報変更画面へ行く。

<img width="570" alt="貼り付けた画像_2023_01_24_15_07" src="https://user-images.githubusercontent.com/168265/214223268-7af9ccc4-14a4-4a7f-86ae-f8768d246fc4.png">

現在はこのように、都道府県しか登録できない。

<img width="570" alt="貼り付けた画像_2023_01_24_15_07" src="https://user-images.githubusercontent.com/168265/214223395-e1936186-b97e-4857-8fc4-dd27ee978a52.png">

日本以外の国に在住 というチェックボックスを作り、

<img width="570" alt="貼り付けた画像_2023_01_24_15_07" src="https://user-images.githubusercontent.com/168265/214223607-e6203946-411a-4fd4-8fc2-6d71e70fab1b.png">

- チェックを入れたら国を入力する text input が表示されるようにしてほしい。
- ユーザー個別ページなどではそれを表示してほしい。
- placeholder には `アメリカ合衆国` と表示してほしい。
- チェックを外したら、国を入力する text input は非表示に戻って欲しい。（ text input の値も空にしてほしい）

**Comment by komagata** [comment]
@machida 日本以外に対応するのであれば下記などを使って海外対応の設計にするといいかもと思いました。

https://country-regions.github.io/react-country-region-selector/

**Comment by machida** [comment]
@komagata なるほど、海外に対応する場合、国名の表記揺れをどうするか迷いつつ、そこまで数がないなら管理者が修正すればいいかと思っていたのですが、こういうのを導入すればいいですね。

**Comment by komagata** [comment]
@machida 想定しないといけない問題が非常にたくさんあるので、ライブラリを使うのがいいかな〜と思います〜。

**Comment by machida** [comment]
@komagata もしくは、国名を入れるから複雑になるので、その他（日本以外）とひとまとめにしちゃってもいいかもですね。

**Comment by machida** [comment]
@shucream-p @komagata 

今回は日本を特別扱いせず、country → prefecture を選ぶ形式にしたいと思います。

リリース時にはこの Issue の Description に貼った UI のように、UI に手を入れてたいとは思いますが、今回のスコープは UI はプレーンなまま、country → prefecture を選ぶことができるところまでにします。

country を選択したら、その country に紐づく prefecture が表示され、それを選ぶという形になりますが、その部分は自作せずに、ライブラリで対応したいと思います。

例えば、 https://github.com/country-regions/country-region-selector これには、[standalone script](https://github.com/country-regions/country-region-selector/tree/master/dist/crs.min.js) があります。これのように、jQueryなど、他のライブラリとの依存がないものを選ぶようにしてください。

日本語化もしてください。

**Comment by shucream-p** [comment]
@machida  
現在、都道府県の選択はjp_prefecture gemで行なってると思うんですが、こちらは使用せず、海外の地域も選択できるライブラリで統一するという認識でよろしいでしょうか？

**Comment by machida** [comment]
@shucream-p はい！今回の仕様に合ったライブラリに移行をお願いしますー🙏

**Comment by shucream-p** [comment]
@machida 
かしこまりました！
ありがとうございます🙏

**Comment by shucream-p** [comment]
@machida 
追加で質問させてください。
こちらの[Reactコンポーネント](https://github.com/country-regions/react-country-region-selector)は使用しても大丈夫でしょうか？

**Comment by machida** [comment]
@shucream-p その判断は駒形さんに任せたいと思いますー

@komagata こちら回答をお願いします

**Comment by komagata** [comment]
@shucream-p 大丈夫ですが、そのライブラリだと日本語化が難しいかも？と思いました〜。

**Comment by shucream-p** [comment]
@machida @komagata
ご回答ありがとうございます！

なるほど。日本語化も考慮しないといけませんでしたね💦

rubyのgemの方でも探してみたんですが、国であれば[countries](https://github.com/countries/countries) や[country_select](https://github.com/countries/country_select)など日本語化対応できそうなものがありました。
国の地域まで網羅してそうなものは[city-state](https://github.com/thecodecrate/city-state)がありましたが、日本語化対応するのが難しそうです。

僕の調べた限りでは、machidaさんが提示された
>country を選択したら、その country に紐づく prefecture が表示され、それを選ぶという形

という仕様で日本語化対応するのは厳しいように思うのですが、どうしたらよいでしょうか？

**Comment by komagata** [comment]
@shucream-p 全部の国対応して日本語にもしたいっすね。（絶対ではないけど）
深掘りすると面白そうなのでもう少し調べてみるとどうでしょうか。
Linuxとかでは日本語データもある気がするのであれってどっかにあったりしますかね〜

**Comment by shucream-p** [comment]
📝2月15日質問タイム

subregionsのデータはhttps://github.com/unicode-org/cldr/blob/main/common/subdivisions/ja.xml から取ってきいるみたい
[countries gem](https://github.com/countries/countries)とISO 3166について詳しく調べる。

**Comment by shucream-p** [comment]
@machida 
お疲れ様です！
仕様について質問です。

MTGで国のデフォルトの選択が日本になるようにしてほしいということだったのですが、こちらのカラムは必須項目にしますか？
それとも都道府県に合わせて、必須にはしませんか？
必須にしない場合は、selectedと一緒にinclude_blankも設定しておかないとなと思い、質問させていただきました🙏

**Comment by machida** [comment]
@shucream-p
カラムは日本、日本外関わらず同じ情報を持たせるようにしたいと思います。
UIだけの工夫をし（日本に住んでいる人にとって手間の少ないUIにする）、持つデータはみんな同じにしたいと思っています。ただし、そもそもお住まいの住所は入力必須項目ではないのでどのようにするか考える必要がありますね。

こちら、後ほどまたコメントをさせていただきますー

**Comment by machida** [comment]
@shucream-p

考えました！住所は、登録する、登録しないのラジオボタンを用意して（デフォルトは登録しない）、登録する、を選択したら国や都道府県の入力フォームが表示され登録できるようになる（デフォルトは日本が選択されてる）、というUIにしたいと思います。登録しない、を選択すると、住所データは空になるようにしたいです。

**Comment by shucream-p** [comment]
@machida 
ありがとうございます！
そちらで進めてみます！

**Comment by machida** [comment]
@shucream-p 

ほとんどの人が日本なので、国を見ることはほぼないので、国を目線に入れる優先度を下げたいと思います。なので、以下のようにお願いします🙏

| --- | --- |
| お住まい| 東京都（日本） |

**Comment by shucream-p** [comment]
@machida 
かしこまりました！
ありがとうございます！

**Comment by shucream-p** [comment]
本番環境で動作確認できましたのでissueをcloseいたします。
