### ISSUE TITLE
[都道府県別ユーザー一覧]都道府県別ユーザー一覧が欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6096]
<img width="1609" alt="貼り付けた画像_2023_01_24_15_19" src="https://user-images.githubusercontent.com/168265/214225113-c01b3bb2-d6c2-49d1-a0fc-1d13ba4695e3.png">

こんな感じの都道府県別ユーザー一覧が欲しい

地方区分の参考。
https://clip.zaigenkakuho.com/chiho_kubun/

- 北海道・東北
- 東北
- 関東
- 中部
- 近畿
- 中国
- 四国
- 九州・沖縄

に加え、

- 海外

も追加したい。
https://github.com/fjordllc/bootcamp/issues/6095
そのためにはこれを実装する必要がある。

- ユーザーの一覧はアイコンだけでなく、もっと情報を出すかも。
- 左カラムの都道府県のリンクの横に（10）など、人数を表示したい。

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/issues/6095

このIssueで海外も対応になる。海外はまとめて一つのグループにしたい。

**Comment by dowdiness** [comment]
@komagata 

こちらのIssueの本番リリースで現在、500: Internal Server Errorが起こってます。

https://bootcamp.fjord.jp/users/areas

本番のログを見ないと原因を正確に特定するのは難しいですが、おそらく原因であろう場所を推測したので下記に説明します。

Areaクラス内での`country_subdivision_pairs `、country_codeとsubdivision_codeカラムを取得して配列のペアにする関数では、`.where.not(subdivision_code: nil)`でsubdivision_codeがnullになっているユーザーの情報を取得しないようにしています。しかし、この記述だとsubdivision_codeがnullでなくcountry_codeがnullであるユーザーを考慮出来ておらず、country_codeがnullになる可能性があります。おそらく`where.not(country_code: nil, subdivision_code: nil)`と書けば両方にnullでないカラムを取得出来るようになるはずです。

おそらくnilへのアクセスをしてエラーが出てしまっている気がします。

修正前
```ruby
def country_subdivision_pairs
  User
    .select('country_code, subdivision_code')
    .where.not(subdivision_code: nil)
    .pluck(:country_code, :subdivision_code)
end
```

修正後
```ruby
def country_subdivision_pairs
  User
    .select('country_code, subdivision_code')
    .where.not(country_code: nil, subdivision_code: nil)
    .pluck(:country_code, :subdivision_code)
end
```

問題のコードの該当箇所
https://github.com/fjordllc/bootcamp/blob/62086613dac86a93b25db8dd6c1435c6fe8ae3bd/app/models/area.rb#L66-L71

**Comment by komagata** [comment]
@dowdiness ログに下記のようにでているのでおそらくおっしゃってる通りだと思います。
もし可能であればproductionに対する修正PRを作っていただければありがたいです～。

![image](https://github.com/fjordllc/bootcamp/assets/16577/984e46ea-423d-4bb7-bc43-280d042cd3d5)

**Comment by komagata** [comment]
@dowdiness とりあえず、上記コードを追加するといろいろとarea関係のテストが落ちるところまでは手元で確認しました。

**Comment by dowdiness** [comment]
@komagata 

確認ありがとうございます。
上記の変更とそれに合わせたテストの修正とテストデータの追加(country_codeとsubdivision_codeのどちらかだけしか持っていないユーザー)をした修正PRを作ります。

早めに直した方が良い修正だと思うので、もしPRが完成していなくても金曜日までには一旦途中報告します。

**Comment by komagata** [comment]
@dowdiness ありがとうございます。途中経過のご報告ありがたいです。

**Comment by dowdiness** [comment]
@komagata 

productionに向けて修正のPR作りました
https://github.com/fjordllc/bootcamp/pull/7589

途中報告すると言っておいて結局全然出来てなく申し訳ないです😓

**Comment by komagata** [comment]
@dowdiness hotfixとして本番にデプロイしました～！
本番で確認して治っていました。ありがとうございます～

**Comment by komagata** [comment]
@dowdiness すみません、上記を「４３期の一覧がエラー」の件と間違っておりました。

都道府県一覧　https://bootcamp.fjord.jp/users/areas　はまだエラーの状態でした。間違えていてすみません。

**Comment by dowdiness** [comment]
@komagata 

テストが落ちていたのを修正しました。（まだ落ちているのがあるのはFlakyなテストです）

調べてみたところ現在のユーザーの登録情報変更では、お住まいの地域を登録しないを選んだ場合に空文字列が保存されるようになっていました。

country_codeとsubdivision_codeの両方に空文字列の可能性があるため、両方の場合でnilか空文字列の場合はデータの取得をしないようにして、不正な値のデータを配列から除くようにしました。

country_codeのvalidationで`allow_nil: true`を使っていましたがこれでは空文字列を扱えないためテストが落ちていたようです。なので空文字列も許容出来る`allow_blank: true`へと変更しました。subdivision_codeの方にもvalidationを追加しています。

今回はしてませんが、もしかしたらデータベースの空文字列や不正な値を変換するスクリプトを実行して、入力がなかった場合に空文字列を保存するのではなくnilを保存するようにも変更した方がいいかもしれません。

**Comment by dowdiness** [comment]
こちらが修正のPRです
https://github.com/fjordllc/bootcamp/pull/7610
ただ何故か名前とコメントの文章が変えられてます。

**Comment by komagata** [comment]
@dowdiness 

> 今回はしてませんが、もしかしたらデータベースの空文字列や不正な値を変換するスクリプトを実行して、入力がなかった場合に空文字列を保存するのではなくnilを保存するようにも変更した方がいいかもしれません。

こちらやりたいのでIssueを作成していただければありがたいです～！

**Comment by dowdiness** [comment]
@komagata 
了解です
今からIsseuを作成します。
