### ISSUE TITLE
ポートフォリオ機能が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#610]
machidaと話し合いながら、仕様・デザインの段階から詰めていくIssue。

**Comment by kasumi8pon** [comment]
@machida 
プロトタイプを作成してみました。

項目は、タイトル・URL・説明の3項目のみとりあえず作成しました。
ポートフォリオということで、他のユーザーのものと混ぜて表示するのに違和感があったことと、
他のユーザーのポートフォリオも見ることができた方がいいかと思ったため、
ユーザーページのタブにポートフォリオタブを追加してみました。
![machidaのポートフォリオ   FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/38184457/57271503-ab3b3680-70ca-11e9-9e5b-c5eefa304129.png)
![ポートフォリオ   FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/38184457/57271510-b3937180-70ca-11e9-8d17-a9133362408a.png)
![ポートフォリオ追加   FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/38184457/57271523-c312ba80-70ca-11e9-89be-e1323b71099a.png)


気になってること
- 「ポートフォリオ」というメニューについて
左のメニューにポートフォリオというメニューを追加するならば、ポートフォリオ一覧に飛ぶのが自然かと思ったのですが、全員のポートフォリオの作品が混ざって表示されるのも違和感があるかな？と思ってます。ポートフォリオに項目をすでに作成している人の一覧が出てきて、その人のポートフォリオに飛べるとかいう形などがいいでしょうか？
- ポートフォリオという言葉について
ポートフォリオって、作品集みたいなイメージなのですが、ひとつひとつの項目をポートフォリオと呼ぶのはおかしいですかね。成果物とかの方がいいでしょうか。

こういう項目が欲しいとか、そもそも想定と全然違うなどあればおっしゃっていただければと思います！

**Comment by machida** [comment]
@kasumi8pon 今の考えてるものでOKですー！！

- ユーザー個別ページの別タブ（URL）にするのも賛成です。その際のURLなのですが、名前について今駒形さんと話し合いました。URLは、https://bootcamp.fjord.jp/users/XXX/portfolioにしたいと思います。ただ、ちょっとイレギュラーで、DBでは、work、works にしたいです（works == portfolio）。
- ユーザー個別>ポートフォリオ のページはいい感じの見た目を用意したいと思います。
- work には、タイトル、説明、リポジトリ、URL、イメージ画像がほしいです。
- 左メニューのポートフォリオ一覧のリンクは無しにしましょう。そのかわり、アドバイザーのページに出す就活中ユーザーの一覧にそれぞれのポートフォリオへのリンクを出したいと思います。

**Comment by machida** [comment]
ポートフォリオのスケッチ

![image](https://user-images.githubusercontent.com/168265/57272525-0a02af00-70cf-11e9-8050-7ae3c14fa8e5.png)

**Comment by kasumi8pon** [comment]
@machida 
works == portfolio、しっくりきました！
スケッチありがとうございます！これで進めてみます！

**Comment by kasumi8pon** [comment]
@machida 
いただいたスケッチを元に機能の大部分を作成しました。
![machidaのポートフォリオ   FJORD BOOT CAMP（フィヨルドブートキャンプ） (3)](https://user-images.githubusercontent.com/38184457/57310080-23821600-7124-11e9-94b1-98219e90941a.png)

![Workの編集   FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/38184457/57310634-14e82e80-7125-11e9-9c73-4557a3d3ba3b.png)

![シンガポール   FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/38184457/57310106-2da41480-7124-11e9-98b2-ce31b4a3d16f.png)

明日のMTGで動きはお見せしますが、先にご相談したい点を書いておきます。
- ポートフォリオにWorkを追加する際の動線は、プロフィール画面→ポートフォリオタブ→右上の追加ボタンとした。問題ないか
  （アドバイザーの方は、トップ画面に出るようにする）
- リポジトリは必須、URLは任意にした。問題ないか
- 画像の登録を必須にするか
- 必須にしない場合、NO IMAGEのような画像が必要か
- ポートフォリオの中のひとつひとつ(Work）は日本語でなんと呼ぶか
  （追加ボタン等、現在は「Workを追加」と表示している）

よろしくお願いします。

**Comment by machida** [comment]
@kasumi8pon ありがとうございます！今日のMTGで話しましょうー こういう連絡すごく助かります！！

**Comment by kasumi8pon** [comment]
@komagata @machida 
基本的な動作について、本番環境で確認しました。
<img width="1190" alt="スクリーンショット 2019-06-12 17 06 28" src="https://user-images.githubusercontent.com/38184457/59333986-773fda80-8d34-11e9-96df-297a3b1602e3.png">
<img width="1193" alt="スクリーンショット 2019-06-12 17 06 37" src="https://user-images.githubusercontent.com/38184457/59334033-9474a900-8d34-11e9-93e6-4423a2ef059d.png">

管理者は他のユーザーの作品が編集・削除できるという部分の確認をしていただけますでしょうか。
よろしくお願いします🙏
（もしよろしければ、[上記のWork](https://bootcamp.fjord.jp/works/1)のリンクを貼っておくのでお使いください）

**Comment by kasumi8pon** [comment]
本日ミーティングにて、管理者機能部分も確認いただきましたので、
このissueはクローズします！
