### ISSUE TITLE
[分報]退会したら自動で分報が削除されてほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6102]

**Comment by ogawa-tomo** [comment]
@komagata 本イシューのステージング環境での動作確認方法についてご相談させていただきたいです:pray:

このあたり↓のやりとりを見まして、ステージング環境には管理者だけがアクセスできるDiscord サーバーがあるのではと思ったのですが、正しいでしょうか？
https://github.com/fjordllc/bootcamp/issues/6103#issuecomment-1449613188

だとすれば、ステージング環境での動作確認は以下のような手順になると考えているのですが、誤解などあればご指摘いただきたいです。
1. デプロイ後、適当なユーザーで新規登録する
2. （管理者が）分報ができていることを確認する
3. 新規登録したユーザーでログインし、退会する
4. （管理者が）分報が削除されていることを確認する

**Comment by komagata** [comment]
@ogawa-tomo こちらがステージング用のDiscordサーバーになります〜。
https://discord.gg/n6UkwDR3

動作確認の手順についてはおっしゃる通りで問題ありません。

**Comment by ogawa-tomo** [comment]
ステージングで動作確認OK

退会前
![image](https://github.com/fjordllc/bootcamp/assets/46841037/e8469aa5-cc69-470a-bee2-a3475143d80c)

退会後
![image](https://github.com/fjordllc/bootcamp/assets/46841037/e28f3bab-0bfc-484c-95c0-653bc587a7b3)

**Comment by ogawa-tomo** [comment]
@komagata @machida こちら、本番にリリースされましたので、退会者が出た際に動作の確認をお願いします:bow:

**Comment by machida** [comment]
@ogawa-tomo こちら、本番で確認しました！！確認が遅れてすいません🙇‍♂️ クローズしておきますー
