### ISSUE TITLE
[newspaper] Docs作成通知の処理をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6105]
PageCallbacks.rbにあるDocs作成通知の処理をnewspaperに置き換えたい

- 既存の処理
  - https://github.com/fjordllc/bootcamp/blob/main/app/models/page_callbacks.rb#L28
  - https://github.com/fjordllc/bootcamp/blob/main/app/models/page_callbacks.rb#L35
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by lef237** [comment]
本番環境で通知を確認できたため、Close致します。
