### ISSUE TITLE
[newspaper] Docsの作成者へのWatch処理をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6106]
PageCallbacks.rbにあるDocs作成者へのWatch処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/page_callbacks.rb#L48)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by mono-nobe** [comment]
@komagata 
本issueは以下のissueで解決されている気がしますが、いかがでしょうか...？

#6105

**Comment by komagata** [comment]
@mono-nobe おっしゃる通りでした。クローズさせていただきます。
