### ISSUE TITLE
[newspaper] 提出物が作成時の同じ会社のアドバイザーへの通知処理をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6108]
Callbackを使っている処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/product_callbacks.rb#L48)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by futa4095** [comment]
@komagata 
newspaperに置き換える対象について確認させてください。

タイトルでは「同じ会社のアドバイザーへの通知処理」となっていますが、
リンクで提示されている既存の処理では「同じ会社のアドバイザーへのwatch処理」に見受けられます。

どちらを対象（または両方とも対象）にするべきでしょうか？

> * [既存の処理](https://github.com/fjordllc/bootcamp/blob/main/app/models/product_callbacks.rb#L48)

https://github.com/fjordllc/bootcamp/blob/e7b76cbfd9949bbd019201f3d84600046edae1ca/app/models/product_callbacks.rb#L48-L53

**Comment by komagata** [comment]
@futa4095 すみません、mainのURLにリンクを貼ったので最新でずれているようです。前者でお願いします〜

**Comment by futa4095** [comment]
@komagata @machida 
こちらのissue、本番環境での確認をお願いしたいです🙏
(アドバイザーの権限が必要です)

確認内容
1. 研修生が提出物を提出する
2. 研修生所属企業のアドバイザーに通知される

**Comment by komagata** [comment]
@futa4095 本番環境で動作することを確認しました。

**Comment by futa4095** [comment]
@komagata 確認ありがとうございました！！

当issueをcloseします。
