### ISSUE TITLE
新着のお知らせの通知メールが、メールをオフにしても届く

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6114]
## 概要

お知らせの新規投稿があった場合、サイト内通知とメール通知をメール通知がされるようになっていて、メール通知をオフにしている場合はメールは届かないようになっている。

しかし、メール通知をオフにしていてもお知らせの新規投稿があった場合にメールが届いてしまう。

**Comment by maimux2x** [comment]
@komagata @machida 
お疲れ様です。
こちらのissueの調査で質問です。

`mail_notification: false` の `hajime` というデータで調査を行ったのですが、

お知らせを

- 全員（退会者を除く）
- 現役生のみ
- 就活希望者のみ

で作成してテストをしても `hajime` にメールは送信されていませんでした。
`hajime` は就活希望のデータではなかったため、調査時のみ `job_seeker: true` に設定を変えて検証しました。

こちらのissueが起票された経緯をもう少し具体的に確認させていただくことは可能でしょうか？

- 本番環境で再現しているのか、stg環境のみ、ローカルでのみなど、どの実行環境で発生しているのか
- メールが配信されたデータは受講生なのか、メンターなのか

辺りを確認したいです。

**Comment by machida** [comment]
@maimux2x 

- ターゲット
    - 全員（退会者を除く） 宛のお知らせで、
- 環境
    - 本番
- 受取先
    - メンター・管理者（machida）

になりますー。
実際に届いているのは、
https://bootcamp.fjord.jp/announcements/794
こちらのお知らせになります。

次回のリリースのときも確認をするので、その間に行うIssueがなければまたアサインしますので、言ってくださいー

**Comment by maimux2x** [comment]
@komagata @machida
本件確認が遅くなり申し訳ありません。
改めて最新のメインで

- Komagataさんのテストアカウント
- 全員（退会者を除く） 宛のお知らせ
で検証いたしました。

その結果

- サイト内通知は届いた
- `mail_notification: false` のユーザーにはメールは配信されない

状態でした。
先週は「今週のリリース」のお知らせが通知されない問題があったと認識しておりますが、`mail_notification: false` のユーザーにメール配信が再発した報告があったかを確認させていただけると幸いです。

**Comment by maimux2x** [comment]
@machida 
ご確認ありがとうございます！
承知いたしました！
