### ISSUE TITLE
初日報が投稿されたら自己紹介チャンネルで知らせたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6120]
現在、入会きたばかりの人が初めて日報を書くと、メンターに初日報の通知が飛ぶ。

メンター以外の人にも知らせたいので、自己紹介チャンネルに、初日報が投稿されたことを通知したい。

**Comment by futa4095** [comment]
@machida 自己紹介チャンネルへの投稿内容は以下のイメージで良いでしょうか？

<img width="400" alt="image" src="https://user-images.githubusercontent.com/69447745/216591344-36f876d7-37f2-43dd-9626-c7fc0f3834ae.png">

もし日報のタイトルも含めたい場合は、以下の内容でどうでしょう？
(日報チャンネルを参考にしました)

```
🎉hatsunoさんがはじめての日報を書きました！
タイトル：「今日からはじめます！」
URL： https://bootcamp.fjord.jp/reports/xxxxx
```

**Comment by futa4095** [comment]
@komagata 
Discordチャンネルへの投稿にウェブフックの作成が必要なことがわかりました。
また本番環境等への環境変数の設定も必要そうでした。(ウェブフックURLを秘匿するため)
こちらお願いして良いでしょうか？

#### 依頼したいこと
- Discord サーバーでウェブフックを2つ作成
  - 本番環境で #自己紹介🥁 への投稿用
  - ステージング環境で #テスト通知（開発用） への投稿用
- ウェブフックURLを環境変数に設定
  - 本番環境・ステージング環境それぞれ  DISCORD_INTRODUCTION_WEBHOOK_URL に設定

**Comment by machida** [comment]
@futa4095 タイトルも含めた形でお願いしますー🙏

**Comment by komagata** [comment]
@komagata かしこまりました〜！
環境変数の名前も大丈夫です〜。

**Comment by futa4095** [comment]
@komagata 
mainにマージされたのでこちらおねがいします🙏

> #### 依頼したいこと
> * Discord サーバーでウェブフックを2つ作成
>   
>   * 本番環境で #自己紹介🥁 への投稿用
>   * ステージング環境で #テスト通知（開発用） への投稿用
> * ウェブフックURLを環境変数に設定
>   
>   * 本番環境・ステージング環境それぞれ  DISCORD_INTRODUCTION_WEBHOOK_URL に設定

**Comment by komagata** [comment]
@futa4095 環境変数の設定とcloud buildの設定を行いましたので、ステージングでの確認をお願いします〜。
https://github.com/fjordllc/bootcamp/pull/6189

**Comment by futa4095** [comment]
ありがとうございます！！
ステージングで確認できましたー

**Comment by futa4095** [comment]
本日本番環境で確認できましたのでcloseします！
