### ISSUE TITLE
日報作成ページにMac以外の環境でもMac用のショートカットキーが表示される

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#6121]
## 概要

日報作成ページで途中保存のショートカットキーが設定されているが、途中保存の案内がMac用固定になっている

Mac: command + s
Mac以外: Ctrl + s

## 期待される振る舞い

Mac以外の環境ではCtrl + sを表示する
または環境関係なく両方併記する

## スクリーンショット

<img width="500" alt="image" src="https://user-images.githubusercontent.com/69447745/215229797-d31f60ea-5054-48d2-a598-18f3994e5a41.png">

**Comment by komagata** [comment]
ちょうどいい機会なのでぜひお願いしたいです〜

**Comment by futa4095** [comment]
@komagata 
Macの判定にはUserAgentを使用することで問題ないでしょうか？
JS側のショートカット設定ではUserAgentを使っていました。

```js
// app/javascript/shortcut.js
function isMac() {
  return navigator.userAgent.toLowerCase().indexOf('mac') > 0
}
```

こんな感じで表示しようと思います。

|Mac|Mac以外(Windows, Linux)|
|-|-|
|途中保存は「command + s」 マメに保存しよう。|途中保存は「Ctrl + s」 マメに保存しよう。|

**Comment by komagata** [comment]
@futa4095 大丈夫です〜

**Comment by machida** [comment]
@futa4095 
https://github.com/k0kubun/rack-user_agent
この gem が入っているので、これを使ってUserAgent判定をお願いします。

```
if request.os == 'Mac OSX'
```

**Comment by komagata** [comment]
@futa4095 メンター二人の発言が一致していなくて混乱させてしまってすみません。

@machida 上記はgemで、JSの処理にどうやって使うかなどちょっと考えなきゃいけない点があるかもです。

**Comment by futa4095** [comment]
@komagata 
Railsのview(slim)の変更のみでできそうかと思っていたのですが、JS側で実装するべきでしょうか？

**Comment by machida** [comment]
@futa4095 @komagata この部分は view(slim) に書いてあるので JSでの対応は不要ですー

**Comment by futa4095** [comment]
本番環境で確認できたのでcloseします
