### ISSUE TITLE
ステージングのユーザー期成別ページにページャーを出したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6134]
<img width="1564" alt="貼り付けた画像_2023_01_30_16_37" src="https://user-images.githubusercontent.com/168265/215415724-86af67bd-340e-4771-838b-c9b15fd8147f.png">

ステージングのユーザー期成別ページ ににページャーが出ない。
seed データをいじり、ユーザーの入会日をずらして期を増やすなどしてページャーを出すようにする。

**Comment by uchihiro04** [comment]
ステージング環境にてページャーが出ることを確認しましたため、issueをクローズいたします。
