### ISSUE TITLE
日報一覧の投稿者名のカッコ内を名前ではなく「名前（カナ）」にしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6137]
<img width="1453" alt="貼り付けた画像_2023_01_31_14_48" src="https://user-images.githubusercontent.com/168265/215676588-33d245dc-ba40-4f0a-80a1-127549991465.png">

今はカッコ内に名前を表示しているが、名前ではなく「名前（カナ）」を表示したい。

もし、この部分が共通化されていて、他の部分も同様に変更されてしまう場合、それでOKです。
将来的に全てを同じように変更する予定です。

---

IDは投稿者を識別するために表示しています。
ペアプロなど、ビデオチャットでやりとりをする際のため、その人をどう呼ぶか知りたい、という要望に答えるためにカッコ表示を用意しています。
ところが、カッコの中には名前が表示されていて、登録している名前によって読み方がわからず、その人をどう呼ぶか知りたい、という要望に応えられていません。
なので、カッコの中は「名前（カナ）」を表示することに変更にします。

**Comment by komagata** [comment]
@machida 理由なども記載していただければありがたいです〜

**Comment by machida** [comment]
@komagata @maimux2x 
理由を追記しましたー

**Comment by komagata** [comment]
@machida ありがとうございます〜！
