### ISSUE TITLE
ユーザー情報変更画面でsubscription_idを編集したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6140]
管理者だけは全てのユーザーのユーザー情報変更画面でsubscription_idを編集できるようにしたい。

subscription_idはStripeで使う、サブスクを識別するIDです。
今までは退会者が復帰した時など、管理者がDBを直接編集してsubscription_idを書き換えていましたが、それをWebの画面からできるようにしたいため。

**Comment by mono-nobe** [comment]
@komagata 
`subscription_id`は必須バリデーションを設定する必要はありますか？

**Comment by mono-nobe** [comment]
@komagata 

`サブスクリプションID`を、ユーザー情報詳細画面で確認できるようにする必要はありますか？

<img width="850" alt="スクリーンショット 2023-02-06 9 53 44" src="https://user-images.githubusercontent.com/94843475/216860863-5c84167a-7953-46f7-b67f-e8dff99d59c2.png">

**Comment by mono-nobe** [comment]
> `subscription_id`は必須バリデーションを設定する必要はありますか？ また、必須バリデーションを設定する場合、初期・テストデータとして全ユーザーのパラメータに追加してもよろしいですか？

以下、回答

> 無料のユーザー（メンターやアドバイザー、研修生）もいるので必須バリデーションは不要です〜。

https://discord.com/channels/715806612824260640/1070716425473372200/1070947803318190110

**Comment by komagata** [comment]
@mono-nobe 本番環境で動作することを確認しました。

**Comment by mono-nobe** [comment]
@komagata 
早速のご対応ありがとうございます！
確認いただいたためCloseします。
