### ISSUE TITLE
左ナビのヘルプのリンク先をアドバイザーでログインしたときは変える

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6142]
<img width="83" alt="image" src="https://user-images.githubusercontent.com/168265/215969589-254f4d49-8b05-4527-a844-c0389ab2849e.png">

ここのリンク先は、 `/pages/help` になっているが、アドバイザーでログインしたときは `/pages/help-adviser` にする。

また、seed データに `help-adviser` というスラッグを持つ doc を作成してください。

実装が終わったらデザインをいじるので、PR のコメントから machida にメンションをお願いします。

**Comment by ymmtd0x0b** [comment]
@komagata @machida 
お疲れ様です！
今週のリリースに含まれるコチラの Issue の動作確認には『アドバイザー』と『メンター』のアカウントが必要になるのですが、確認作業をお願いしても宜しいでしょうか？🙇‍♂️

- https://github.com/fjordllc/bootcamp/pull/6178

**Comment by machida** [comment]
@ymmtd0x0b 本番で確認できましたー🙆‍♂️

**Comment by ymmtd0x0b** [comment]
@machida
良かったです！ご対応ありがとうございました！！

**Comment by ymmtd0x0b** [comment]
本番環境で動作確認して頂いたのでcloseします

**Comment by ymmtd0x0b** [comment]
本番環境で動作確認して頂いたのでcloseします
