### ISSUE TITLE
退会手続きページのタイトルから「休会」を外す

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#6147]
## 概要

退会手続きのページタイトルが「退会・休会手続き」となっています。
休会手続きのページが別にあるため「退会手続き」で良さそうです。

## スクリーンショット

退会手続きページ

<img width="521" alt="image" src="https://user-images.githubusercontent.com/69447745/216244880-0a815a37-9bf3-4e51-9dc2-b2467641fc50.png">

休会手続きページ

<img width="492" alt="image" src="https://user-images.githubusercontent.com/69447745/216245130-a5a9bcbb-d038-40db-9c94-6204d381d82b.png">

**Comment by djkazunoko** [comment]
本番環境で動作確認ができましたので、closeいたします。
