### ISSUE TITLE
入会n日目、休会復帰n日目にフォローアップコメントを相談部屋に送信したい

### ISSUE THREAD

**Issue by ksmxxxxxx** [fjordllc/bootcamp#6157]
## 機能の説明

#5959 に関連する機能です。

このIssueでは #5959 で考慮できなかった「休会復帰n日目の受講生にフォローアップコメントを送信する」機能を実装していただきたいです。

## 何故この機能が必要なのか

#5959 では「入会n日目の受講者にフォローアップコメントを相談部屋に投稿する機能を作成しました。
しかし、この機能だけだと休会から復帰した人へのフォローアップが考慮されていません。
@machida さんとしては、「入会n日目の受講生、休会復帰してn日目の受講生に「最近どうですか？楽しくやれてますか？」といったメッセージを送りたい」ということでした。

## 要件

- 休会復帰して30日経過した受講生の相談部屋にフォローアップコメントを送信できる
  - 30日は、#5959 で実装した機能と同じ経過日数です

要件の経緯については関連IssueやPullReqを参照してください。

## 関連Issue・PullReq

- #5959 
- #5746

**Comment by ksmxxxxxx** [comment]
[memo]
#5959 がマージされたら参考情報として、FIXMEコメント部分のリンクを追加する。

**Comment by ksmxxxxxx** [comment]
@machida こちら完了していると思うのでcloseしちゃってもいいのでは？って思いますがいかがでしょう？

**Comment by machida** [comment]
@ksmxxxxxx これ、まずは30日経過でのメッセージを実装してもらったのですが、さらに n日後 にもメッセージを投稿するか検討して決めたいと思いますー。今のところ、180日後と365日後くらいに一度メッセージを飛ばすといいかな、と考えています。

**Comment by ksmxxxxxx** [comment]
@machida naruhodo.であれば、このままにしておくのが良さそうですね。ありがとうございます 🙏

**Comment by komagata** [comment]
@ksmxxxxxx そもそも本番環境でのこちらの動作環境がまだ取れてないように思います。

**Comment by machida** [comment]
@komagata 

本番環境で確認が必要なIssueとPRはこのIssueではなく、以下になります。

- https://github.com/fjordllc/bootcamp/issues/5746
- https://github.com/fjordllc/bootcamp/pull/5959

上記のIssueは、手始めに入会してから30日経過した受講生に対してのメッセージを送信する機能についてでした。

こちらのIssueでは、すでに実装された30日経過した受講生に対してメッセージを送信する機能以外の、

「n日経過したら受講生に対してのメッセージを送信する機能」をまとめて実装するIssueになります。

例えば、n は 180日と 365日 とし、 180日のときのメッセージはXXX、365日のときのメッセージはXXX、にする、というような形で、30日経過以外のメッセージを送信する複数のタイミングと、それぞれのタイミングで送られるメッセージ内容もこのIssueで合わせて検討していく予定です。

**Comment by komagata** [comment]
@machida なるほどですね、ご説明ありがとうございます。

@ksmxxxxxx 申し訳ありません、コメントを書くIssueを間違えておりました。
