### ISSUE TITLE
diffにもシンタックスハイライトが適用されるようにしたい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6171]
diffが見にくいのでシンタックスハイライトが適用されるようにしたいです。

https://bootcamp.fjord.jp/pages/how-to-install-machida-special

<img width="770" alt="Screenshot 2023-02-06 at 10 48 25" src="https://user-images.githubusercontent.com/1148320/216863594-f0e801ef-e16b-4d6e-8d03-18f0ce6db877.png">

参考 [TypeScript, JSX, TSXにもシンタックスハイライトが適用されるようにしたい · Issue \#6057 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/6057)

**Comment by cafedomancer** [comment]
されてほしいので reopen します。
