### ISSUE TITLE
管理画面のお試し延長一覧にユーザー数を表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6188]
管理者でログインし、`/admin/campaigns` にアクセス。

<img width="940" alt="貼り付けた画像_2023_02_09_10_17" src="https://user-images.githubusercontent.com/168265/217690087-605acc1e-be6b-4496-abb2-f61f04941b83.png">

このように、table で今まで開催したお試し延長キャンペーンの一覧が表示されている。

この table にユーザー数を追加したい。

<img width="919" alt="貼り付けた画像_2023_02_09_10_24" src="https://user-images.githubusercontent.com/168265/217691391-bc0b7910-2f24-4bbf-908e-db938d1e904a.png">

**Comment by lef237** [comment]
@komagata 
管理者のみが確認できるページのため、本番環境での確認をよろしくお願い致します🙏
URLは`/admin/campaigns`となります。

**Comment by komagata** [comment]
@lef237 本番環境で確認しました。ただ、下記の現役生の数がマイナスになっているところが気になりました。

![スクリーンショット 2023-02-25 18 27 07](https://user-images.githubusercontent.com/16577/221349710-24f0bb6d-ac8d-4d91-a94c-350c9285e1ab.png)

**Comment by lef237** [comment]
@komagata 
ご確認頂きありがとうございます！
キャンペーン期間の入会者のスコープの範囲を間違ってしまっていました。すみません。🙇

コードミスを修正し、新たにPull Requestを作成し直しました。
よろしくお願いします🙏

- #6267

**Comment by komagata** [comment]
@lef237 PRありがとうございます！マージさせていただきました！

**Comment by lef237** [comment]
@komagata 
コードを修正致しましたので、再度本番環境での確認をよろしくお願いします🙏
URLは`/admin/campaigns`となります。

**Comment by komagata** [comment]
@lef237 本番環境で動作することを確認しました。

**Comment by lef237** [comment]
ご確認頂き、ありがとうございました🙏

本番環境の確認が終わりましたのでClose致します。
