### ISSUE TITLE
本番環境で特定のユーザーにお知らせ通知が飛ばない場合がある

### ISSUE THREAD

**Issue by lef237** [fjordllc/bootcamp#6202]
## 概要

2/10のマージ以降、本番環境でお知らせ通知が飛んでいない現象がありました。

## 再現手順

1. 本番環境でkomagataさんが、お知らせで今週のリリースを公開した。
2. 通知が特定のユーザーに届いていない。

全体に飛んでいないわけではなく、特定の少数のユーザーにだけ飛ばないことがあるようです。

※この現象が今回限りのものなのか、デプロイ先のサーバーの不具合なのかも含めて、現在不明です。

## 期待される振る舞い

お知らせを公開したら通知が飛ぶ。

## 関連Issue
今日の #6166 リリース後に発生したため、下のPull Requestがバグに関係している可能性あり。

Ref: #6148

**Comment by machida** [comment]
@lef237 machidaには届いていたので、管理者かメンターには届いているようです。

**Comment by lef237** [comment]
@machida 
ご確認ありがとうございます！🙏

**Comment by lef237** [comment]
📝 先程の質問・雑談タイムの参加者の中では、自分と @futa4095 さんには全ての通知欄にも通知が残っていなかったので、ここに記録を残しておきます。

**Comment by Seakimhour** [comment]
@lef237 
僕には今週のリリースの通知は届いてました。

こちらのPRは確認をしました。
- #6148

変えたところには問題なさそうと思います。

**Comment by lef237** [comment]
@Seakimhour 
ご確認いただき、ありがとうございます🙏

**Comment by lef237** [comment]
@akingo55 @djkazunoko @dowdiness @e6i24vi @hikarook94 @ksmxxxxxx @maeda-m @maimux2x @mono-nobe @OdenTakashi @peno022 @sadanora @shizimi50 @shucream-p @siso25 

お疲れ様です！

皆様にご確認したいことがございます。
「今週のリリース2023年02月09日」が、通知の「全て」のタブに表示されていない方（通知が飛んでいない方）はいらっしゃいますでしょうか？

このページです → https://bootcamp.fjord.jp/notifications

質問雑談タイムで確認した限りでは、自分と @futa4095 さんに、今週のリリースのお知らせ通知が飛んでいない状態でした。

お手数をおかけしますが、通知欄をご確認頂けると助かります。よろしくお願いします🙏

**Comment by lef237** [comment]
📝 メモ：Kimuhourさんが動作確認したお知らせの通知は届いていました。しかし、リリースのほうのお知らせ通知は何度確認しても見当たりませんでした。

![image](https://user-images.githubusercontent.com/93074851/218055537-db4ed371-f413-4335-a605-d5d7cf4fb174.png)

**Comment by Seakimhour** [comment]
@lef237 メール通知は届いていましたか？

**Comment by lef237** [comment]
@Seakimhour 自分はメール通知をOFFにしているのでメールはちょっと分からないです……💧
FBCのDiscordの通知は飛んでいたので、大丈夫だと思います！

Seakimuhourさんのコードを確認しましたが、特に問題は無さそうでした。やはり、別のところに問題があるようです。もしかしたら、Heroku側の問題かもしれません。

**Comment by hikarook94** [comment]
@lef237 
お疲れ様です！
出先からスマホで確認しましたが、リリースのお知らせは届いていないようです
ご確認ください
![EE65F5D1-A747-449B-8042-9A7E4641E892](https://user-images.githubusercontent.com/59002337/218062925-19380f9c-60e0-4034-9d39-977b36f5718a.png)

**Comment by lef237** [comment]
@hikarook94 
ありがとうございます！　助かります🙏🙏

**Comment by shizimi50** [comment]
@lef237
お疲れ様です！確認したところ、通知きていませんでした🙌
「今週のリリース」に関しては、2023年02月02日までしかきていないようです。
<img width="700" alt="スクリーンショット 2023-02-10 19 12 33" src="https://user-images.githubusercontent.com/75718420/218065320-c73ad175-a99e-4af2-ace6-706353ec72b1.png">

**Comment by lef237** [comment]
@shizimi50 
ありがとうございます！　助かりました🙏

**Comment by ksmxxxxxx** [comment]
@lef237 自分には通知は来ていないようでした。
<img width="813" alt="image" src="https://user-images.githubusercontent.com/5976902/218076812-6590dab9-35c9-432b-aa22-fd683c72c3e7.png">

**Comment by lef237** [comment]
@ksmxxxxxx 
ご確認いただき、ありがとうございます！🙏

**Comment by djkazunoko** [comment]
@lef237 
自分も通知は来ていませんでした！
<img width="739" alt="スクリーンショット 2023-02-10 20 09 16" src="https://user-images.githubusercontent.com/65595901/218078019-5801e749-d51c-4515-a46f-5c3852875e81.png">

**Comment by lef237** [comment]
@djkazunoko 
ありがとうございます！！🙏

**Comment by OdenTakashi** [comment]
@lef237 
僕の方にも届いていませんでした！
![9F70290F-09C3-4841-A69F-EF429ABB6ECD](https://user-images.githubusercontent.com/81839214/218082554-91f6f053-ed51-4abf-bf1e-980d306dafd9.png)

**Comment by lef237** [comment]
@OdenTakashi 
ありがとうございます！！🙇

**Comment by lef237** [comment]
メモ📝：
## 現在の状況
- リリースのお知らせに関しては通知が飛んでいなかったが、動作確認の際のお知らせに関しては通知が飛んでいた

## 考えられる可能性
1. 本番環境にデプロイしたばかりのタイミングで、うまく通知が動かなかった
2. たまたまそのタイミングでHeroku側に障害が起こっていた

## ネクストアクション
このissueで取り上げられているバグは、一回限りで発生した偶発的な事故（一時的な障害）かもしれず、インフラ側（Heroku）の問題である場合には、原因が突き止められない可能性が高い。

ローカル環境やステージング環境でも問題なく動いている。

そのため、今後のお知らせで問題なく通知が飛んでいれば、このissueはCloseして良いと考えられる。

**Comment by shucream-p** [comment]
@lef237 
お疲れ様です！
僕の方には通知来てました！

<img width="721" alt="スクリーンショット 2023-02-10 22 48 41" src="https://user-images.githubusercontent.com/88083085/218107940-e7d8130b-a7f0-4a61-a58f-38084e963f06.png">

**Comment by lef237** [comment]
@shucream-p 
ありがとうございます！🙏　正常系も動いているんですね👀

あれっ、でもKimuhourさんの通知がもしかしてシュークリームさんには届いていない感じですね。なんでだろう？🤔

**Comment by ymmtd0x0b** [comment]
@lef237 
お疲れ様です！
質問・雑談タイムの中で「私には通知が来ていた」とメッセージを書きましたが、勘違いでした！すみません🙏 (レフさんのDocsページの投稿の事だと勘違いしてました)

改めて https://bootcamp.fjord.jp/notifications にアクセスしましたが、私にも通知は来ていませんでした

![2023-02-11_01-12](https://user-images.githubusercontent.com/95903475/218141060-5869ef91-3831-4c19-a371-0c3f8b22a2c0.png)

**Comment by peno022** [comment]
@lef237 
昨日確認できておらずすみません！今さらかもですが、私はリリースお知らせの通知はなく、テストのお知らせは来ていました。

![スクリーンショット 2023-02-11 8 19 18](https://user-images.githubusercontent.com/40317050/218220492-cdf787fa-c384-40ea-9316-8d3b6631d869.png)

**Comment by lef237** [comment]
@peno022 @ymmtd0x0b 
ご確認いただき、ありがとうございます！🙏

**Comment by lef237** [comment]
@komagata 
> インフラはHerokuではなくGoogle Cloud Runです〜

Herokuと勘違いしていました。ありがとうございます！

## 現状報告

現在までの状況報告なのですが、簡単にまとめると以下のようになります。
- 通知機能自体は動いている
  - コメント通知やドキュメント作成の通知は問題なく動いている
- お知らせ通知だけ、動かない場合がある
  - ローカル環境やステージング環境では動いている

そのため、これ以上調査ができない状態です。

## 推測と考察
ここからは推測なのですが、お知らせ通知が届かなかった要因としては、以下の４点に絞られると思います。
- Google Cloud Runが昨日だけ一時的に何らかの障害を起こしていた
- 他のメンターさんが誤ってお知らせ通知を削除してしまった
- デプロイ前にWIPだった記事をデプロイ後に投稿すると、先程のバグが起こる？（要検証）
- お知らせ通知関連のコードのどこかに、なんらかのバグがある
  - 一番高い可能性としては、「お知らせ通知の削除機能」が勝手に動いてしまっている説です
    - ref: #5493 
    - ref: #5586  

この「お知らせ通知の削除機能が勝手に動いてしまった説」が、一番有り得そうな要因だと思います。
（`AnnouncementNotificationDestroyer`が何らかの要因で`call`されてしまった）

## 今後について
現在、複数の別のIssueに取り組んでいるため、自分の調査としてはいったんここまでにしたいと思います🙏

※来週（2/16）のリリースノートのお知らせ通知が届くかについては、この issueに記録を残そうと思います。

**Comment by sadanora** [comment]
@lef237 
昨日反応できずにすみません。今週のリリースのお知らせ通知は来ていませんでした。
いまさらかと思いますが参考までに:pray:
![スクリーンショット 2023-02-11 11 35 47](https://user-images.githubusercontent.com/66685066/218234648-6378a5bd-7898-4490-8196-55b6f6a5fd0f.png)

**Comment by lef237** [comment]
@sadanora 
ご確認ありがとうございます！🙏🙏

**Comment by akingo55** [comment]
遅くなりました、自分は届いてます！
<img width="702" alt="image" src="https://user-images.githubusercontent.com/43959158/218265671-025f8b81-adac-45a6-ab59-a9c68ed52073.png">

**Comment by lef237** [comment]
@akingo55 
お知らせいただき、ありがとうございます！🙏
やはり届いている方と届いていない方に別れている感じですね📨

**Comment by maeda-m** [comment]
@lef237 遅くなりました～
届いていないのは、今週のリリース2023年02月09日のみでした👍

|有無|通知件名|日時|
|:----:|-----|:----:|
|✅|お知らせ「お知らせを全が公開できるようにするの本番環境テスト」|2023年02月10日(金) 18:19|
|✅|lef237さんがDocsにテストですを投稿しました。|2023年02月10日(金) 16:43|
|❌|今週のリリース2023年02月09日|2023年02月10日(金) 15:37|

**Comment by lef237** [comment]
@maeda-m 
ご確認ありがとうございます！　日時も含めて表にして頂き、とてもありがたいです🙏

**Comment by lef237** [comment]
📝メモ：2023-02-12に公開された新しいお知らせの通知は届いていた。もしかすると、メンターさん以外の受講生がWIPをすると、バグのフラグが立つのかもしれない。
![image](https://user-images.githubusercontent.com/93074851/218295849-afa3d6fb-7495-4322-a2f1-f3e26f58fb58.png)

**Comment by siso25** [comment]
@lef237 
遅くなりまして申し訳ありません。
私はリリース情報、テストともに届いていました！
![image](https://user-images.githubusercontent.com/47073105/218296486-2f490110-fe9c-4e3a-88fa-de202dc4c23f.png)

**Comment by lef237** [comment]
@siso25 
ご確認いただき、ありがとうございます！🙏

**Comment by machida** [comment]
結果をまとめてみました。

|ユーザー|結果|
| --- | --- |
|@siso25 | ○ |
|@maeda-m | ✗ |
|@akingo55| ○ |
| @sadanora | ✗ |
| @peno022 | ✗ |
|@ymmtd0x0b  | ✗ |
| @shucream-p | ○ |
| @djkazunoko | ✗ |
| @OdenTakashi | ✗ |
| @ksmxxxxxx | ✗ |
| @shizimi50 | ✗ |
| @hikarook94 | ✗ |
|@Seakimhour   | ○ |
| @lef237 | ✗ |
| @machida | ○ |

## 調査したこと

- お知らせの編集に関わった人、関わってない人は関係あるか？
    - 関係なかった

**Comment by lef237** [comment]
@komagata @machida 
お疲れ様です。
本日（2023-02-18）、「今週のリリース2023年02月16日」が公開されましたが、お知らせ通知が届いていませんでした。

## スクリーンショット
お知らせ一覧はこのようになっていますが、
![image](https://user-images.githubusercontent.com/93074851/219827403-9b731522-79b0-4484-8dc9-92a4cb93d7d8.png)

通知一覧（全て）はこのようになっています。
![image](https://user-images.githubusercontent.com/93074851/219827457-d6ffd4d1-28a6-43b1-ae11-ca0e1254cef3.png)

お知らせ通知（全て）はこのような形です。
![image](https://user-images.githubusercontent.com/93074851/219827493-70f89f3c-7c59-4acf-87b3-ada41ac70af6.png)

今週のリリースのお知らせだけが、先週と同様に届いていない状態です。
（他のお知らせは問題なく通知が届いています）

## 結論
普通のお知らせの場合は問題なく通知されていますが、リリースノートのお知らせだけはなぜか通知が届いておりません。

推測ですが、お知らせを作成した人とお知らせを編集した人が異なる場合（あるいは、お知らせを編集した人とお知らせを公開した人が異なる場合）に、このようなバグが生じると思われました。

共同で編集した場合にのみ、このバグが生じるという推測です。

https://github.com/fjordllc/bootcamp/issues/6202#issuecomment-1426540348

こちらのコメントに書きましたが、現在、複数の別のIssueに取り組んでいるため、自分の調査としてはいったんここまでにしたいと思います🙏

**Comment by machida** [comment]
@lef237 調査ありがとうございます！！一旦この Issue はクローズにして、別 Issue をたてることにします（そこからこちらにリンクを貼ります）。

**Comment by lef237** [comment]
本日（2023-02-24）のリリースのお知らせに関しては、通知が問題なく届いていました。

理由は分からないですが、念のためログを残しておきます。

![image](https://user-images.githubusercontent.com/93074851/221139062-0084372e-092a-4fc3-be0f-1c59e04d9779.png)
