### ISSUE TITLE
[newspaper] リタイアした時の処理をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6203]
UserCallbacks.rbにあるリタイアした時の処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/dcdf8a7ecc69199ba3a24bcd52c33f040f12eb15/app/models/user_callbacks.rb#L9-L14)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by machida** [comment]
@uchihiro04 本番で確認しましたー🙆‍♂️

**Comment by uchihiro04** [comment]
@machida 
ご確認ありがとうございます！　こちらのIssueをクローズしたいと思います。
