### ISSUE TITLE
[プラクティス編集]プラクティスカテゴリーの削除ボタンの移動

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6208]
`admin/categories` にそれぞれのカテゴリーの削除ボタンがある。（つまり、index にある。）

<img width="948" alt="貼り付けた画像_2023_02_12_10_30" src="https://user-images.githubusercontent.com/168265/218288261-76a91662-006f-4b60-b628-8cb62acf153b.png">

`/admin/categories/{ID}/edit` に削除ボタンを移動したい。

<img width="1567" alt="貼り付けた画像_2023_02_12_10_32" src="https://user-images.githubusercontent.com/168265/218288300-18c700cb-2a3b-4232-a1ef-07bfe0142544.png">

デザインは machida がやります。

**Comment by djkazunoko** [comment]
@komagata @machida 
https://github.com/fjordllc/bootcamp/pull/6271 がリリースされましたので本番環境で以下の動作確認をお願いしたいです〜🙌
1. `admin/categories`から削除ボタンがなくなっていること
1. `/admin/categories/{ID}`の削除ボタンからプラクティスカテゴリーを削除できること
1. `/admin/categories/{ID}/edit`の削除ボタンからプラクティスカテゴリーを削除できること

**Comment by komagata** [comment]
@djkazunoko 本番環境で動作することを確認しました。

- [x] admin/categoriesから削除ボタンがなくなっていること
- [x] /admin/categories/{ID}の削除ボタンからプラクティスカテゴリーを削除できること
- [x] /admin/categories/{ID}/editの削除ボタンからプラクティスカテゴリーを削除できること
