### ISSUE TITLE
[プラクティス編集]カテゴリーに紐づくプラクティスの並び替え機能

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6209]
コースは複数のカテゴリーを持ち、カテゴリーは複数のプラクティスを持つ、という構造になっている。

- コース
    - カテゴリー
        - プラクティス

コースに紐づくカテゴリーの並び替え機能はあるが、カテゴリーに紐づくプラクティスの並び替え機能が現在はない。

これの実装をお願いします。

---

## コースに紐づくカテゴリーの並び替え機能の確認方法

管理者でログインし、`/admin/courses` にアクセス。

<img width="955" alt="貼り付けた画像_2023_02_12_10_35" src="https://user-images.githubusercontent.com/168265/218288376-10cb8f1c-8b90-4853-9e42-2a7b387a2336.png">

ここをクリックすると、並び替えページが見れる。

これと、同じものを `/admin/categories` にも付けたい。

**Comment by komagata** [comment]
@machida カテゴリーに紐づくプラクティスの並び替え機能はここにはありますが、別途って感じですかね？

<img width="1120" alt="スクリーンショット 2023-02-20 10 12 03" src="https://user-images.githubusercontent.com/16577/219987842-2f14091d-33f7-4189-b110-b31db32fb5d3.png">

**Comment by machida** [comment]
@komagata あー、そうか、そこにあったのを忘れてました。そこへのリンクをカテゴリの方にも追加するようにします。

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/issues/6254
新しいIssueを作ったので、こちらはクローズ。
