### ISSUE TITLE
[プラクティス編集]プラクティス、コース、カテゴリーの編集権限を管理者からメンターに移行。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6210]
現在、プラクティス、コース、カテゴリーの編集権限は管理者しか持っていない。
これを管理者とメンターに変更をしたい。
変更に伴い URL も変更したい。

現在は、

- /admin/categories
- /admin/courses
- /admin/practices

となっている。

これを

- /mentor/categories
- /mentor/courses
- /mentor/practices

にし、プラクティス、コース、カテゴリーのタブをメンターページのタブに移す。

<img width="1749" alt="貼り付けた画像_2023_02_12_10_41" src="https://user-images.githubusercontent.com/168265/218288500-f34b2c10-002b-4081-bda5-55f931ad38c0.png">

**Comment by mono-nobe** [comment]
@machida 
改修方針について2点確認させてください！

### 管理ページのタブは削除してもよろしいですか？

issueの概要に

>プラクティス、コース、カテゴリーのタブをメンターページのタブに移す。

とあるのですが、管理ページからタブ自体削除してもよろしいですか？

<img width="760" alt="スクリーンショット 2023-03-10 17 40 38" src="https://user-images.githubusercontent.com/94843475/224266828-1a9a8984-8c63-48f3-8a20-f7232c7f96fc.png">


### クラス(CSS)もメンターページ用に置き換える必要はありますか？

ページを置き換える際のクラスの扱いについて、以下のどちらが良さそうですか？
(他に良い方針などあればご教示お願いします🙇 )

- mentor用のページを作成する際、置き換え対象のページに使用されている各クラス名をmentor用に置き換える
    - 具体的には、mentor用の[スタイルシート](https://github.com/fjordllc/bootcamp/blob/main/app/assets/stylesheets/application/blocks/admin/_admin-table.sass)を新たに作成し、`admin-table__item-value` クラスを `mentor-table__item-value`とする
    - => 差分がかなり大きくなりそう
    - 仮にクラス名も置き換える場合、他ページに影響がないことを確認した後、admin用のスタイルシートを削除してもよろしいですか？
- 既存のクラスを参照する
    - 具体的には、コンポーネント名を `MentorCourse` とし、クラス名で `admin-table__item` を使用する
    - => 置き換え後のコンポーネント名とクラス名に差が生じるため誤解を招く可能性がある


#### 対象ページ

##### プラクティス

<img width="734" alt="スクリーンショット 2023-03-10 18 03 40" src="https://user-images.githubusercontent.com/94843475/224272437-043a034f-9034-4ea8-9f47-6f8620c27941.png">

##### カテゴリー

<img width="728" alt="スクリーンショット 2023-03-10 18 04 31" src="https://user-images.githubusercontent.com/94843475/224272637-41ae2016-671f-4719-a742-8a11d7866c1d.png">

##### コース

<img width="733" alt="スクリーンショット 2023-03-10 18 04 40" src="https://user-images.githubusercontent.com/94843475/224272669-62f8c901-8871-4969-90ee-35a15f388eeb.png">

**Comment by machida** [comment]
@mono-nobe 

質問ありがとうございます！！

> 管理ページのタブは削除してもよろしいですか？

はい！削除でお願いしますー。

> クラス(CSS)もメンターページ用に置き換える必要はありますか？

これは置き換えずにこのままでお願いします。
別Issueで、メンター用のクラス名を付けるのではなく、admin-table の admin をもっと抽象化して admin にも mentor にも使えるように management-table などにする予定ですー

**Comment by mono-nobe** [comment]
@machida 
ご回答ありがとうございます！
上記、承知しました。いただいた内容で進めます！

**Comment by mono-nobe** [comment]
@machida 
権限周りについて、各項目の作成はこれまで通り **管理者のみ行える** 認識であっていますか？
その場合、管理者の `routes` や `controllers` などには作成に必要な処理のみ残し、他は削除してもよろしいですか？

**Comment by mono-nobe** [comment]
@machida 
追加で1点確認させてください。

>別Issueで、メンター用のクラス名を付けるのではなく、admin-table の admin をもっと抽象化して admin にも mentor にも使えるように management-table などにする予定ですー

`routes` や `controllers` などを格納するために新しくディレクトリを作成するのですが、命名には `management` を使用した方がよろしいですか？

**Comment by mono-nobe** [comment]
@machida 

カテゴリー削除の権限はメンターに移行しますか？ 👀 
(編集画面にも削除ボタンがあることを確認しました)

![スクリーンショット 2023-03-21 23 10 30](https://user-images.githubusercontent.com/94843475/226633023-d2a0630a-dbb4-4dad-bdd6-a492778c1661.png)

**Comment by mono-nobe** [comment]
>権限周りについて、各項目の作成はこれまで通り 管理者のみ行える 認識であっていますか？

作成や削除など諸々含め移行する

**Comment by mono-nobe** [comment]
>ファイルやディレクトリ、変数を命名する際には、mentor の代わりに management を使用した方がよろしいですか？

`mentor` を使用する

**Comment by machida** [comment]
@mono-nobe 

まとめておきますー

:memo:

> 権限周りについて、各項目の作成はこれまで通り 管理者のみ行える 認識であっていますか？

メンターにも管理者同様の権限の追加をお願いします。
プラクティス周りの権限はメンターと管理者が持つようにお願いします。

> ファイルやディレクトリ、変数を命名する際には、mentor の代わりに management を使用した方がよろしいですか？

mentor でお願いします。
管理画面に使っている table の HTML の class 名だけ、変更する予定です。

> カテゴリー削除の権限はメンターに移行しますか？ 👀

こちらの権限も他のプラクティス周りと同様にメンターと管理者にお願いします。

**Comment by mono-nobe** [comment]
📝 2023/03/29 振り返りMTGメモ
PRの差分が多いが、単純な置き換えであるため1つのPRで対応する。

**Comment by mono-nobe** [comment]
@komagata @machida 
本番環境へリリースされましたので、動作確認をお願いします 🙇

**Comment by komagata** [comment]
@mono-nobe 何を確認すればいいのかの指示をお願いします〜

**Comment by mono-nobe** [comment]
@komagata 
失礼しました... 🙇 
管理者権限を持つ駒形さんにはプラクティス、コース、カテゴリーのタブが管理者ページに存在しないことを確認していただきたいです！(以下PRの8番以降になります)
https://github.com/fjordllc/bootcamp/pull/6344#issue-1633376779

また、別途メンター権限のみ持つ方へ動作確認依頼しようと思うのですが、コースやカテゴリーの作成なども実行いただいて良いのでしょうか。。？
(本番環境で使用しないコースなどが作成されるのは良くないかと思い)

**Comment by komagata** [comment]
@mono-nobe 

> 管理者権限を持つ駒形さんにはプラクティス、コース、カテゴリーのタブが管理者ページに存在しないことを確認していただきたいです！

こちら確認致しました。問題ありませんでした。

> また、別途メンター権限のみ持つ方へ動作確認依頼しようと思うのですが、コースやカテゴリーの作成なども実行いただいて良いのでしょうか。。？

はい、その後削除していただけるのであれば問題ありません。

**Comment by mono-nobe** [comment]
@komagata 
すみません、、こちら見逃しておりました 🙇 

>はい、その後削除していただけるのであれば問題ありません。

承知しました！
こちらの内容でメンターの方に依頼しようと思います。

**Comment by mono-nobe** [comment]
@cafedomancer 
>お手数ですが、移行した以下のタブの機能が使えるかご確認いただきたいです。 🙇

ご対応いただきありがとうございました！
とても助かりました。 😊

**Comment by mono-nobe** [comment]
本Issueでの確認は完了しましたのでcloseします。
https://discord.com/channels/715806612824260640/809595476847493192/1140632509802098768
