### ISSUE TITLE
開発環境の学習内容をもっとたくさん表示されるようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6218]
`/practices` にアクセス。

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/168265/218656094-c6b4a1a6-973a-461f-8883-181d18ea0a55.png">

ここにもっとたくさん表示されるように、seedデータをいじってください。

**Comment by komagata** [comment]
@shizimi50 ミーティングでお話しした内容ですが、本番・ステージング・開発環境でもこのページで「Railsプログラマーコース」のプラクティスが表示されるように変更することで対応をお願い致します〜。

コースのタイトルを基準にして取ってくるようにするといいかな〜と思います。

**Comment by komagata** [comment]
:memo: @shizimi50 さんが休会されたので、一旦担当を外して他の方に担当していただく感じです。

**Comment by monyatto** [comment]
@komagata @machida 

お疲れさまです！　issueの内容について確認させてください🙏

>ミーティングでお話しした内容ですが、本番・ステージング・開発環境でもこのページで「Railsプログラマーコース」のプラクティスが表示されるように変更することで対応をお願い致します〜。

こちら本番環境については[#6247](https://github.com/fjordllc/bootcamp/pull/6247)で実装されているようなので。これから対応する内容としては、「開発環境（とステージング環境）において`/practices`にアクセスすると「Railsプログラマーコース」の学習内容が表示されるようにする」ということであってますでしょうか？

以下は現在それぞれの環境で`/practices`にアクセスしたときに表示されている内容です。

開発環境とステージング環境
![image](https://user-images.githubusercontent.com/83024928/236976105-b7203dbe-60a5-4b92-9ea3-0d37b27218b9.png)

本番環境
![image](https://user-images.githubusercontent.com/83024928/236975919-60e020bd-1632-45f8-a70b-fb59808b100b.png)

**Comment by machida** [comment]
@monyatto あー、すいません、こちら完了してますね！このIssueはクローズして別のIssueをアサインします🙇‍♂️
