### ISSUE TITLE
ユーザー一覧の各ユーザーに日報数、提出物数、コメント数、質問数を表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6219]
一目でどれくらいフィヨルドブートキャンプを積極的に利用してる人なのかわかりやすくするための取り組みの第一弾として。

デザインは町田がやりますー

**Comment by ksmxxxxxx** [comment]
@machida アサインありがとうございます。
仕様について伺いたいんですが、
- コメント数
- 質問数
こちらってどのへんのものをカウントするイメージですかね？

たとえばコメントって日報についてるコメントとか質問やイベントのコメントとかいろいろあると思うのですが、全部ひっくるめてカウントするイメージですか？

**Comment by machida** [comment]
@ksmxxxxxx

この機能独自のアルゴリズムを作るなどは一旦はなしで、全部ひっくるめてでお願いしますー

<img width="1039" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/a82b77eb-ecf7-4874-bc96-e1eb576226e2">

ユーザー個別ページのタブにある数字の表示をお願いします🙏

**Comment by ksmxxxxxx** [comment]
@machida 度々の質問で恐縮です。
ユーザー一覧に日報数などを表示とあるんですが、よく考えたら生徒の日報数とかは必要だけどメンターやアドバイザーは日報書くことがないので、表示しなくてもいいのでは？と思ったんですがどうなんでしょうか。
ロールによって表示・非表示とか考慮する必要ありますかね？

**Comment by machida** [comment]
あー、確かに！
何を表示するかまとめまて連絡しますー

**Comment by machida** [comment]
@ksmxxxxxx すいません！返信が遅くなりました🙇‍♂️

一旦今回は、

- アドバイザー
- メンター
- 管理者

は非表示でお願いします🙏

- 現役生
- 研修生
- 卒業生

だけ表示をお願いします🙏

**Comment by ksmxxxxxx** [comment]
@machida 念のための確認になってしまうんですが、休会中の受講生についても表示扱いでいいですよね？

**Comment by machida** [comment]
@ksmxxxxxx はい！休会、退会のユーザーも表示してしまって大丈夫です

**Comment by ksmxxxxxx** [comment]
@machida 承知しました、ありがとうございます 👍
