### ISSUE TITLE
ログイン時にOAuth認証を実装したい

### ISSUE THREAD

**Issue by tosite0345** [fjordllc/bootcamp#622]
## 概要
ログイン画面でTwitterやGithubなど、複数認証ができるとステキだなぁと思いました！
実装コストは割と高そうですが…一度ご検討いただければ幸いです。

<img width="413" alt="2018-11-16 18 52 39" src="https://user-images.githubusercontent.com/24952964/48614206-0e2bfa80-e9d1-11e8-84e2-c09cedb508ff.png">

**Comment by shibaaaa** [comment]
こちら対応済みのようなのでクローズしておきます〜
