### ISSUE TITLE
【メンター向け】休会中のユーザーは「自分の担当」に含めない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6222]
提出物 > 自分の担当タブを見ると、休会中ユーザーの提出物も一覧に含まれています。
たとえば、以下の画像では3つ提出物がありますが、上の2つは休会中ユーザーの提出物です。

<img width="1109" alt="skitch" src="https://user-images.githubusercontent.com/1148320/218892897-669edee1-632b-4f59-81d5-4a741a333d83.png">

休会中の場合、コメントを返したりすることができない（しても意味がない）ので、復帰するまでは非表示にしてもらえると「今自分が担当すべき提出物」にフォーカスできて嬉しいです。

**Comment by JunichiIto** [comment]
この機能、今すぐにでもほしいかも。（「自分の担当」画面を見ながら）
ご検討よろしくお願いします〜 🙏

**Comment by junohm410** [comment]
@komagata @machida 
CC: @JunichiIto 
お疲れ様です。こちらのIssueにつきまして、本番環境での動作の確認をお願いします🙏

### 確認いただきたいこと
`/products/self_assigned`の中に、以前まで表示されていた休会者の提出物がリストされていないこと

生徒である私の方では「この休会者の提出物が前まで載っていたと思いますが、今は載っていないことを確認してください」というように指定できないので、上記のようなざっくりとした確認方法でしかお願いできないできず恐縮なのですが……🙇‍♂️

ご確認のほど、何卒よろしくお願い申し上げます。

**Comment by machida** [comment]
@junohm410 
返信遅れてすいません🙇
こちら本番で確認できました🙆‍♂️
休会中のユーザーの提出物は入らなくなってました。

**Comment by junohm410** [comment]
@machida 
ご確認ありがとうございました！よかったです〜。
本番での動作確認が取れましたので、本IssueはCloseさせていただきたきます。
