### ISSUE TITLE
新規ドキュメントの通知方法の変更

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6223]
現在は、新規ドキュメントを投稿すると、全員に通知が飛ぶ。
この仕様だと以下のデメリットがある。

- どのドキュメントについて、なぜそのドキュメントを書いたかなどを伝える場合には、その通知とは別にお知らせも投稿する必要があり、二重の通知になってしまう。
- 就職に関するドキュメントを投稿した場合、就職を希望していない人や研修生にもその通知が飛んでしまう。
- ただ通知が飛んだだけだと、なぜそのドキュメントを書いたのかわからない場合がある。

---

以下のように新規ドキュメント時の通知を変更したい。

- メンター・管理者には今まで通り、新規ドキュメントを投稿されると通知が飛ぶ。
- それ以外は自動で通知が飛ぶ機能はストップする。

`/pages/new` ドキュメント作成ページに、「お知らせ作成」という項目を追加。

<img width="1111" alt="貼り付けた画像_2023_02_15_11_36" src="https://user-images.githubusercontent.com/168265/218913198-c2dda3d3-7ee4-460a-8bc1-cc046a3d0c4f.png">

この項目にチェックが入った状態でドキュメントが公開されたとき（WIPで保存ではなく）、

投稿後に `/announcements/new` にリダイレクトされる。

リダイレクトされたときに、フォームの内容が以下の状態になっている。

<img width="896" alt="貼り付けた画像_2023_02_15_11_45" src="https://user-images.githubusercontent.com/168265/218914174-d3bc940a-9872-44f9-9ae8-9d109a498214.png">

お知らせ作成のチェックの有無の値はDBに保存する必要はない。

---

##### タイトル

```
ドキュメント「{ドキュメントタイトル}」を公開しました。
```

が入力されている。`{ドキュメントタイトル}` の部分は作成したドキュメントのタイトルを取ってくる。

##### 内容

```
<!--  このテキストを編集してください-->

ドキュメント「{ドキュメントタイトル}」を公開しました。
https://xxxxxxxxxxxxx

<!--  不要な場合以下は削除 -->
---

{ドキュメントの内容}
```

が入力されている。`{ドキュメントタイトル}` 、`{ドキュメントの内容}` は、作成したドキュメントから取ってくる。

##### 通知ターゲット

デフォルトのまま。

---

上記のように入力された状態のお知らせ作成ページが開く。

ドキュメント作成者は、この内容を編集してお知らせを書き、お知らせからドキュメントが作成されたことを通知する、というフローに変更したい。

**Comment by uchihiro04** [comment]
@machida 
確認のため、通知について1点質問させていただければと思います🙇‍♂️
新規ドキュメント投稿時の「通知」が指す範囲は、「サイト内通知」および「メール通知」の両方で間違い無いでしょうか。

ご教示のほどよろしくお願いいたします🙇‍♂️

**Comment by machida** [comment]
:memo:

> サイト内通知」および「メール通知」の両方

でお願いします。

---

デザインを入れるのでレビュー依頼と同時にmachidaにメンションをお願いします

**Comment by uchihiro04** [comment]
@machida 
Issueについて1点質問させていただければと思います🙇‍♂️

* ドキュメント公開後のチェックボックスについて
ドキュメントを一度公開した後のドキュメント編集画面について、「このドキュメント公開についてお知らせを書く」のチェックボックスは以下のどの形を想定されていらっしゃいますでしょうか。

    * チェックボックスが存在し、チェックを入れて更新した場合「お知らせ作成ページ」にリダイレクトする
    * チェックボックスが存在し、チェックを入れて更新した場合「ドキュメントの詳細ページ」にリダイレクトする
    * チェックボックスを表示させない

お手数をお掛けしますが、ご教示いただけますようお願いいたします🙏

**Comment by uchihiro04** [comment]
上記質問について、質問タイムにて@machidaさんに確認を行いましたのでメモとして以下に残します。

> ドキュメント公開後のチェックボックスについて

「チェックボックスを表示させない」形にする（published_atがついていた場合、チェックボックスを表示させない）。

**Comment by machida** [comment]
メモありがとうございます！！

**Comment by uchihiro04** [comment]
本番環境で動作確認ができましたので、issueをcloseいたします。
