### ISSUE TITLE
ページ作成をドキュメント作成に変更したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6224]
`/pages/new` にアクセス。

<img width="642" alt="貼り付けた画像_2023_02_15_11_34" src="https://user-images.githubusercontent.com/168265/218912653-3913eceb-5e5a-42c4-959d-5ce9927e6b66.png">

ページ作成をドキュメント作成に変更したい。

このページの title タグもページ作成からドキュメント作成に変更したい。

<img width="378" alt="image" src="https://user-images.githubusercontent.com/168265/218912728-3f6d35b8-80ce-4b22-9e1f-c36a8a7c3195.png">

**Comment by djkazunoko** [comment]
本番環境で動作確認ができましたので、closeいたします。
