### ISSUE TITLE
Doc の作者を変更したら、その作者は自動でWatchになるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6225]
現在、

- ドキュメントを投稿すると、その投稿者は自動でWatch中になる。
- そのドキュメントにコメントを投稿しても自動でWatch中になる。

<img width="388" alt="image" src="https://user-images.githubusercontent.com/168265/218917296-275eb1be-aed5-41c0-bf1c-be526c1070bd.png">

ドキュメントに関わった人にはドキュメントには、そのドキュメントで起こったことを把握出来るように、通知がされたいためです。

しかし、

- ドキュメントの作成者ではない人がドキュメント編集した場合、その編集者は自動でWatch中にならない。
- ドキュメントの作成者を変更した場合（メンターだけにある機能）、変更された作成者とされた人はWatch中にならない。

---

今回の Issue では、

> ドキュメントの作成者を変更した場合（メンターだけにある機能）、変更された作成者とされた人はWatch中にならない。

をWatch中になるように変更お願いします。

**Comment by machida** [comment]
関連Issue https://github.com/fjordllc/bootcamp/issues/6226

**Comment by komagata** [comment]
@wata00913 下記の通り作りました。

- [Docs: 本番環境の動作確認用Doc\(WIP\) \| FBC](https://bootcamp.fjord.jp/pages/544)
- [Docs: 本番環境の動作確認用Doc\(公開\) \| FBC](https://bootcamp.fjord.jp/pages/545)

上記を作る前に間違って、「WIPで作ったものを編集して公開する」という間違った作業をしてしまったのでその記事は削除しました。（動作確認に影響があるかもしれないので念の為お伝えします。）

**Comment by wata00913** [comment]
@komagata 
>「WIPで作ったものを編集して公開する」という間違った作業をしてしまったのでその記事は削除しました。

了解しました！

お手伝い頂きありがとうございました🙇‍♂️
動作確認で問題が無かったためcloseします。(作成して頂いたDocはこちらで削除済みです。)
