### ISSUE TITLE
Doc の内容を編集したら、自動でWatchになるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6226]
現在、

- ドキュメントを投稿すると、その投稿者は自動でWatch中になる。
- そのドキュメントにコメントを投稿しても自動でWatch中になる。

<img width="388" alt="image" src="https://user-images.githubusercontent.com/168265/218917296-275eb1be-aed5-41c0-bf1c-be526c1070bd.png">

ドキュメントに関わった人にはドキュメントには、そのドキュメントで起こったことを把握出来るように、通知がされたいためです。

しかし、

- ドキュメントの作成者ではない人がドキュメント編集した場合、その編集者は自動でWatch中にならない。
- ドキュメントの作成者を変更した場合（メンターだけにある機能）、変更された作成者とされた人はWatch中にならない。

---

今回の Issue では、

> ドキュメントの作成者ではない人がドキュメント編集した場合、その編集者は自動でWatch中にならない。

をWatch中になるように変更お願いします。

**Comment by machida** [comment]
関連 Issue https://github.com/fjordllc/bootcamp/issues/6225

**Comment by wata00913** [comment]
@machida @komagata 
Issueの内容について1点、質問させて頂きたいと思います。

> ・ドキュメントの作成者ではない人がドキュメント編集した場合、その編集者は自動でWatch中にならない。
・ドキュメントの作成者を変更した場合（メンターだけにある機能）、変更された作成者とされた人はWatch中にならない。

「ドキュメント編集した場合」と「作成者を変更した場合」とありますが、Watch中になる操作は、
「ページ更新」した場合( `内容の保存`ボタンを押下した場合)**のみ**でしょうか？
それとも、「ページ更新」、「WIPで保存する」に関わらずWatch中になるのでしょうか？

**Comment by machida** [comment]
@wata00913 wip、公開に関わらず、docの編集に関わったらwatchになるようお願いしますー🙏

**Comment by wata00913** [comment]
本番環境での動作確認が遅れてしまいすみません🙇‍♂️
本番環境で動作確認をしましたのでクローズします。
