### ISSUE TITLE
コメント・回答を投稿したら、画面をリロードしなくても、ボタンはWatch中に変更されてほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6227]
- 日報
- 提出物
- Q&A
- ドキュメント
- イベント

は、

コメント（Q&A の場合は回答）を投稿したら自動でWatch中になる。

<img width="307" alt="image" src="https://user-images.githubusercontent.com/168265/218924965-2c690d14-123c-4dd7-8a24-bcef16cfa8bd.png">

ただ、コメント投稿直後にはWatch中の表示にはならず、画面をリロードしないとWatch中の表示に変更されない。

画面をリロードしなくてもコメント投稿直後はWatch中の表示になるようにしていただきたいです。

**Comment by uchihiro04** [comment]
@machida
要件について1点質問させていただければと思います。

「お知らせ」へのコメントも、現在画面をリロードしないと「Watch中」とならない状態になっております。
上記の要件に加え、「お知らせ」も画面をリロードしなくても、コメント投稿直後に「Watch中」になるように実装を行う形でよろしいでしょうか。

ご教示いただけますようお願いいたします🙇‍♂️

**Comment by machida** [comment]
@uchihiro04 ありがとうございます！お知らせも同様にお願いしますー🙏

**Comment by uchihiro04** [comment]
@komagata @machida 
こちらのissueに取り組んでいる際、1点バグと見受けられる現象を発見しました。
バグの修正につきましては別issueとしたほうがよろしいでしょうか。ご教示いただけますと幸いです🙇‍♂️

### バグ内容
Watchしていない状態で日報※にコメントを投稿した後にWatchボタンを押すと、Watch中の一覧ページに2つ同じ日報が表示される
※日報以外にも、提出物、Q&A、ドキュメント、イベント、お知らせにコメントを投稿した場合でも上記バグが発生します

### バグの再現方法
1. `/reports`にアクセスした後、任意の日報の詳細ページにアクセスする
1. 日報がWatch中になっていないことを確認し、コメントを投稿する
日報がWatch中の場合は、Watchボタンを押してWatch状態を解除する
1. リロードを行わない状態で、Watchボタンを1回押す（その際、「Watchしました！」と表示される）
1. `/current_user/watches`にアクセスし、2~3でWatchした日報が2つ表示されることを確認する

### スクリーンショット
![23032505](https://user-images.githubusercontent.com/77523896/227716515-3a210501-a611-49bf-bcf2-1271c9d3366b.gif)

**Comment by machida** [comment]
@uchihiro04 

バグの報告ありがとうございます！！
こちら、別Issueにしたいと思います。
Issueの作成をお願いしますー🙏

**Comment by uchihiro04** [comment]
@machida 
Issueを作成しました！
[Watchしていない状態でコメントを投稿した後Watchボタンを押すと、Watchが重複した状態になる · Issue \#6369 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/6369)

今回のIssue（#6227）では、バグは残したままでプルリクエストを作成したいと思います。

**Comment by machida** [comment]
@uchihiro04 Issue確認しました！！作成ありがとうございます🙏

**Comment by uchihiro04** [comment]
本番環境で動作確認ができましたので、issueをcloseいたします。
