### ISSUE TITLE
メンターの提出物一覧の未返信タブにWIPの提出物は含めないようにしてほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6252]
メンターでログインし、

`/products/self_assigned?target=self_assigned_no_replied`

にアクセス。

このページには、

- コメントが0でかつ未完了の提出物
- 最後にコメントしたのがメンターではなく提出者でかつ未完了の提出物

が表示される。

WIP 状態の提出物であっても、上記の条件を満たすとここに表示されてしまう。
WIP 状態の提出物は、上記の条件を満たしていても、ここには表示されないようにしてほしい。

なぜなら、このページはメンターからのアクションが必要な提出物一覧を見るためのページで、WIP 状態の提出物は、今メンターからのアクションが必要ではないから。

**Comment by komagata** [comment]
@ymmtd0x0b 本番環境で動作することを確認しました。

**Comment by ymmtd0x0b** [comment]
@komagata 
ご対応ありがとうございます！

動作確認OKを頂いたのでcloseします！
