### ISSUE TITLE
[プラクティス編集]カテゴリーに紐づくプラクティスの並び替えリンクの追加

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6254]
コースは複数のカテゴリーを持ち、カテゴリーは複数のプラクティスを持つ、という構造になっている。

- コース
    - カテゴリー
        - プラクティス

コースに紐づくカテゴリーの並び替え機能はあるが、カテゴリーに紐づくプラクティスの並び替えのリンクの場所が管理画面にないので、それを置いてほしい。

管理者でログインし、 `/admin/categories` にアクセスすると、カテゴリー一覧がある。

<img width="1041" alt="貼り付けた画像_2023_02_22_15_55" src="https://user-images.githubusercontent.com/168265/220545655-4b2a64e1-8cf5-4766-af2c-73e91ffe2641.png">

ここに並び替えへのリンクの設置をお願いします。

並び替えページの URL は`/courses/1/practices/sort` この様になっています。

並び替えのアイコンやボタンは `/admin/courses` と同じにしてください。

<img width="941" alt="image" src="https://user-images.githubusercontent.com/168265/220545960-f7cd98e3-259b-4da1-b4f1-9e252039502f.png">

**Comment by machida** [comment]
@monyatto 
すいません、確かにそうでした！!
指摘ありがとうございます🙏

現状はコースのshowからカテゴリーに紐づくプラクティスの並べ替えをやってますね。
これは、コースが増えていくことを想定していなかった昔の名残ですね。

別 Issue でカテゴリーに紐づくプラクティスの並べ替えのUIとURLの変更の Issue を立てます。
そのIssueのときにこのPRは取り込もうと思います。
なので、アイコンを追加した PR を push しておいてくださいー🙏

**Comment by monyatto** [comment]
本番環境で動作確認いただいたのでcloseします。
