### ISSUE TITLE
ファイル選択ダイアログから画像を添付したい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6259]
FBCのテキストエリアではドラッグ＆ドロップしか画像を添付する方法がない（はず）。
ただ、場合によってはドラッグ＆ドロップよりも画像添付のボタンをクリックして、ファイル選択ダイアログからファイルを選択する、という昔ながら方法の方が速いことがあります。（ドラッグ＆ドロップが面倒な例：現在表示されているウインドウを全部どけて、その背後に隠れていたデスクトップ上の画像をドラッグしてくる場合など）

たとえばQiitaやGitHubなどでは画像添付用のボタン(?)があるので、こんな感じでファイル選択ダイアログを表示できるようにしてもらえると嬉しいです。
<img width="776" alt="Qiita" src="https://user-images.githubusercontent.com/1148320/221062779-41badff2-b88b-44a8-ba91-0fc4c4a44e31.png">
<img width="527" alt="github" src="https://user-images.githubusercontent.com/1148320/221062817-2916efa4-0b7d-4873-9b86-1c0aef837a0d.png">

**Comment by YukiWatanabe824** [comment]
23年5/31ミーティングにて
`<input>`を使用して「ファイル選択ダイアログでのファイル添付」実装の確認がとれました。
`<input>`にID等を付加することで`textarea-markdown`におけるプレビューと同様にオプション的に実行できる形で実装します。

これによって機能そのものの実装は`textarea-markdown`に、`<input>`のデザインはbootcampで行います。

**Comment by YukiWatanabe824** [comment]
@komagata @machida 
お疲れ様です。
`<input>`を使用してファイル選択ダイアログからファイル添付できる機能をひとまず形になりました。

<img width="1440" alt="スクリーンショット 2023-06-04 14 02 49" src="https://github.com/fjordllc/bootcamp/assets/69577164/15714065-085c-4f5e-b004-13c955dc20b8">

この`<input>`によるファイル添付は、テキストエリアと同じview(パーシャル)内で`class='js-input'`を持つ`<input>`がある場合に機能するようにしました。そのためview(パーシャル)ごとに実装(`<input>`を追加してデザインを付加)する必要があります。
今回Issueではどこにこの機能を実装するのが良いでしょうか？ ↑のスクショに関しては開発上たまたま日報ページで作りましたが、これまで特に指定はありませんでした。

**Comment by YukiWatanabe824** [comment]
6/6 MTGにて
必要箇所全てに実装して町田さんにデザイン依頼するフローで進めることの確認が取れました

**Comment by YukiWatanabe824** [comment]
本番環境で確認ができましたのでcloseいたします〜
