### ISSUE TITLE
日報の右側の最近の日報でページャーが表示されることで見た目が崩れている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6262]
下記で起こっていました。

https://bootcamp.fjord.jp/reports/68482

![スクリーンショット 2023-02-24 21 45 16](https://user-images.githubusercontent.com/16577/221182440-c579852e-7fef-40bc-a616-8e1d95d28b43.png)

**Comment by lef237** [comment]
@komagata 

お疲れ様です！

こちら自分のミスであり、３時間前にこちらのPull Requestで修正致しました。

#6261 

ご確認お願い致します🙏

**Comment by komagata** [comment]
@lef237 確認しました。ありがとうございます〜！

**Comment by lef237** [comment]
本番環境でバグの修正が確認できましたので、Close致します。
