### ISSUE TITLE
Q&A個別ページ、コメントへのページ内リンクが機能していない

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#6264]
## 概要

Q&A個別ページ右上に回答数を表示していて、ページ内リンクが設定されているが、クリックしてもコメント欄に移動しない

## 再現手順

**縦スクロールバーが表示されるウィンドウサイズで試してください!ページ内リンクが機能していても確認できません！**

1. /questionsにアクセス。
2. (どれでもいいので)質問をクリック。
3. 回答数(0でも良い)をクリック。
4. URLがフラグメント識別子付きに変わるがコメント欄に移動しない。

## 期待される振る舞い

回答・コメントにページ内リンクする

## スクリーンショット

<img width="889" alt="image" src="https://user-images.githubusercontent.com/69447745/221337039-7585cc7c-633f-4bf0-a460-2cd87ca07bf1.png">

**Comment by machida** [comment]
.thread-comments に `#comments` を付ける。

**Comment by naokinaokiboo** [comment]
本番環境で動作が確認しましたのでclose致します。
