### ISSUE TITLE
Q&A個別ページで質問に関連したプラクティスを変更すると、右カラムの質問一覧にも反映されるようにする

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#6265]
## 概要

Q&A個別ページで表示中の質問を内容修正しプラクティスを変更しても、右カラムの質問一覧に反映されないので反映させる

## 再現手順

1. /questionsにアクセス。
2. 任意の質問をクリック。
3. 「内容修正」をクリック。
4. プラクティスを変更して「更新する」をクリック。
5. 右カラムの質問一覧が変わらず。

## 期待される振る舞い

右カラムの質問一覧が変更後のプラクティスのものである

## スクリーンショット

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/69447745/221338841-1661a8a4-a995-4d65-acab-31208e323333.png">

## 関連Issue

Ref: #5999

**Comment by syo-tokeshi** [comment]
本番環境で確認が取れましたのでclose致します🙇‍♂️
