### ISSUE TITLE
ブックマーク一覧ページの削除ボタンに同じ ID が複数個使われている

### ISSUE THREAD

**Issue by uchihiro04** [fjordllc/bootcamp#6273]
## 概要
ブックマーク一覧ページの、編集をONにしたときに表示されるブックマーク削除ボタンについて、ボタンの数だけ`id="bookmark-button”`が存在している。

## 再現手順

1. 日報やDocsなどを複数個ブックマークする
2. `/current_user/bookmarks`にアクセスする
3. 「編集」をONにする
4. ブックマーク削除ボタンが表示されている状態でデベロッパーツールを開く
5. ブックマーク削除ボタンに関するコードを見て、削除ボタンの数だけ`id="bookmark-button"`が使用されていることを確認する

## 期待される振る舞い
ブックマーク削除ボタンのコードをデベロッパーツールで確認したとき、`class="bookmark-button”`となっている。

## スクリーンショット
ブックマーク一覧ページの削除ボタンについて、デベロッパーツールでコードを確認
<img width="766" alt="スクリーンショット 2023-02-28 13 07 08" src="https://user-images.githubusercontent.com/77523896/221751269-60386e34-dcee-4bd3-9e93-7dc9268a49ad.png">
<img width="614" alt="スクリーンショット 2023-02-28 13 08 53" src="https://user-images.githubusercontent.com/77523896/221753586-47ed9f87-a3b1-4041-b289-a334e8b6733c.png">

## 環境
 - OS: macOS Ventura 13.1
 - ブラウザ: chrome
 - ブラウザのバージョン: 109.0.5414.119（Official Build）（arm64）
 
 ## 備考
 `app/javascript/components/Bookmarks.jsx`の、削除ボタン（DeleteButton）に関するHTMLのコードが`id="bookmark-button”`となっているため、下記スクリーンショットのような形になっていると推測される。
 https://github.com/fjordllc/bootcamp/blob/907e81d32c14ff48c69e0d936b27cb4ca83dae30/app/javascript/components/Bookmarks.jsx#L141-L152

**Comment by djkazunoko** [comment]
本番環境で動作確認ができましたので、closeいたします。
