### ISSUE TITLE
ブックマーク一覧からブックマークを削除するテストが機能していない

### ISSUE THREAD

**Issue by uchihiro04** [fjordllc/bootcamp#6275]
## 概要
ブックマーク一覧からブックマークを削除するテストが機能していない。

機能していない箇所は以下の通り。
* 本来削除するべきブックマークが削除できていない
99行目で「Bookmark中」であることを確認した日報を削除する必要がある。
* チェックする必要の薄いブックマークがチェックされている（101・105行目）
99行目で「Bookmark中」であることを確認した日報についてチェックする必要がある。
* ブックマーク編集ページからブックマークを削除する際、テストに直接関係のないブックマークを削除している（104行目）
* 2回目に日報詳細ページへアクセスする際、`visit`を使用しているためログインするアカウントを指定できておらず、98行目でログインしたアカウントのBookmarkが本当に削除できているか確認が取れていない（106行目）

該当するテスト
https://github.com/fjordllc/bootcamp/blob/907e81d32c14ff48c69e0d936b27cb4ca83dae30/test/system/bookmarks_test.rb#L95-L108

## 再現手順

1. `test/system/bookmarks_test.rb`の95行目にあるテスト（`'delete bookmark from bookmarks'`）を確認する

## 期待される振る舞い
上記テストが機能するためには、テストを以下のような流れに変更する必要があると思われる。

1. 特定のユーザー（以下、ユーザー1）でログインし、特定の日報（以下、日報A）の詳細ページへアクセスする
アクセス時は`visit_with_auth`を使用する。
1. 日報Aのブックマークボタンが「Bookmark中」になっていることを確認する
1. ユーザー1のブックマーク一覧ページにアクセスする
1. 日報Aがブックマーク一覧にあることを確認する
1. ブックマーク一覧から、日報Aを削除する
1. 日報Aがブックマーク一覧にないことを確認する
1. ユーザー1でログインした状態で、日報Aの詳細ページへアクセスする
アクセス時は`visit_with_auth`を使用する。
1. 日報Aのブックマークボタンが「Bookmark」になっていることを確認する

## 環境
 - OS: macOS Ventura 13.1
 - ブラウザ: chrome
 - バージョン: 109.0.5414.119（Official Build）（arm64）

**Comment by djkazunoko** [comment]
本番環境で動作確認ができましたので、closeいたします。
