### ISSUE TITLE
Q&Aの新規投稿が通知されない？

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6277]
https://bootcamp.fjord.jp/questions/1553 について、回答の通知は来ましたが、新規投稿の通知は来ませんでした。

回答の通知はあるが、新規投稿の通知はない（通知メールについても同様）
<img width="756" alt="notice" src="https://user-images.githubusercontent.com/1148320/222019637-dfaf5299-dbb7-45ec-8ad1-f0e9feb5680d.png">

新規投稿の日時
<img width="857" alt="qa" src="https://user-images.githubusercontent.com/1148320/222019709-9a7e3009-487d-4c32-923a-07497bb09f34.png">

これ以外も数日前から新規Q&Aの通知が来てないような気がしてます。（詳細未確認）

**Comment by JunichiIto** [comment]
さっき投稿された https://bootcamp.fjord.jp/questions/1554 は通知されました。（通知メールは未受信）
通知する・しないについて、何かルールがあるんですかね？ 🤔

**Comment by machida** [comment]
@JunichiIto こちら通知がいく、いかないのルールはないので、何かしら不具合がありそうです。調査します。

**Comment by JunichiIto** [comment]
FYI
https://bootcamp.fjord.jp/questions/1555 は新規投稿の通知はなく、回答の通知しか来ませんでした。

@cafedomancer 新規投稿の通知って来ました？

<img width="988" alt="qa" src="https://user-images.githubusercontent.com/1148320/222276957-196db2d2-8edc-4cb1-b7f6-2bfdfa0ae64d.png">

**Comment by JunichiIto** [comment]
https://bootcamp.fjord.jp/questions/1556 も同様でした。
<img width="802" alt="qa" src="https://user-images.githubusercontent.com/1148320/222620666-540408da-ae6e-4a40-9e0e-eb90004fcd9c.png">

**Comment by cafedomancer** [comment]
> @cafedomancer 新規投稿の通知って来ました？

来てました！

**Comment by JunichiIto** [comment]
参考）3/7朝の通知状況を以下に載せてます。（受講生の名前が見えるのでここには載せない）
https://discord.com/channels/715806612824260640/798498633694838785/1082437947904761856

**Comment by machida** [comment]
バックグラウンド処理にgood_jobを導入することでキューが消えずに動くようになったので、この件も解決されました。
https://github.com/fjordllc/bootcamp/pull/6323

**Comment by JunichiIto** [comment]
たしかに最近は改善されたように思います。対応ありがとうございました！
