### ISSUE TITLE
カテゴリー作成ボタンの移動。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6278]
管理者でログイン `http://localhost:3000/mentor/categories` にアクセス。

<img width="1130" alt="貼り付けた画像_2023_03_01_14_43" src="https://user-images.githubusercontent.com/168265/222055084-256a86f7-456a-40e0-ae76-a901361bd314.png">

ボタンをタブの下に移動。
デザインは machida がやるので、作業をしたら machida にメンションをお願いします。

**Comment by rira100000000** [comment]
@komagata 

お疲れ様です。
https://github.com/fjordllc/bootcamp/pull/6729
こちらのPRがマージ、リリースされましたので、本番環境での確認をお願いいたします。

## 確認方法
1. メンターアカウントにてログインする
2. https://bootcamp.fjord.jp/mentor/categoriesにアクセスする
3. カテゴリー作成ボタンが以下画像の位置にあることを確認する
![image](https://github.com/fjordllc/bootcamp/assets/99132547/fc5ea165-0bb4-427f-ab9c-c6977e098a64)

**Comment by machida** [comment]
@rira100000000 確認しましたー🙆‍♂️本番でOKでした🎉

**Comment by rira100000000** [comment]
@machida 
確認ありがとうございます！closeします！
