### ISSUE TITLE
企業作成ボタンの移動。ボタンの文言変更。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6280]
管理者でログイン。
`http://localhost:3000/admin/companies` にアクセス。

<img width="2235" alt="貼り付けた画像_2023_03_15_16_07" src="https://user-images.githubusercontent.com/168265/225232806-3a1c38da-6566-4e04-abe3-7bb2b7f478cd.png">

ボタンをタブの下に移動。
企業作成を企業追加にボタンの文言変更。
企業一覧というタイトルを追加。
デザインは machida がやるので、作業をしたら machida にメンションをお願いします。

**Comment by wata00913** [comment]
@komagata @machida 
こちらのPR[#6300](https://github.com/fjordllc/bootcamp/pull/6300)がリリースされました。動作確認に管理者権限のログインが必要なので、本番環境での動作確認をお願いいたします🙇‍♂️

確認方法は下記の手順となります。

1. 管理者権限を持つアカウントでログインする
2. 企業一覧ページ `admin/companies` にアクセスする
3. 「企業追加」ボタンがタブの右下に移動していることを確認する
4. 「企業一覧」がタブの右下に表示されていることを確認する

以上、よろしくお願いいたします🙇‍♂️

**Comment by machida** [comment]
@wata00913 確認しました🙆‍♂️
