### ISSUE TITLE
企業作成ページのタイトル修正。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6281]
管理者でログインして、
http://localhost:3000/admin/companies/new
にアクセス。

<img width="1157" alt="貼り付けた画像_2023_03_01_14_51" src="https://user-images.githubusercontent.com/168265/222056415-dbae695d-1076-4eae-94e7-d159c3ad3171.png">

管理ページに修正し、企業追加をタブの下に置く。
デザインは machida がやるので、作業をしたら machida にメンションをお願いします。

**Comment by wata00913** [comment]
@komagata @machida 
こちらのPR[#6288](https://github.com/fjordllc/bootcamp/pull/6288)がリリースされました。動作確認に管理者権限のログインが必要なので、本番環境での動作確認をお願いいたします🙇‍♂️

確認方法は下記の手順となります。

1. 管理者権限を持つアカウントでログインする
2. 企業登録ページ `admin/companies/new` にアクセスする
3. タイトルが `管理ページ` であることを確認する
4. タブの左下に `企業追加` があることを確認する
5. タブの右下に `企業一覧` リンクがあることを確認する
6. 企業編集ページ `admin/companies/{company_id}/edit` にアクセスする
7.  タブの右上に`企業追加` リンクがあることを確認する

以上、よろしくお願いいたします🙇‍♂️

**Comment by komagata** [comment]
@wata00913 本番環境で動作することを確認しました。

**Comment by wata00913** [comment]
本番環境で動作確認をして頂いたのでクローズします。
