### ISSUE TITLE
お試し延長作成ボタンの移動。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6282]
管理者でログインして、
http://localhost:3000/admin/campaigns
にアクセス。

<img width="1142" alt="貼り付けた画像_2023_03_01_14_55" src="https://user-images.githubusercontent.com/168265/222056921-a5614382-c9fd-4931-b438-6db9624b9e83.png">

ボタンをタブの下に移動。
デザインは machida がやるので、作業をしたら machida にメンションをお願いします。

**Comment by komagata** [comment]
(CC: @monyatto ) すでに完了しているようなのでCloseします〜。
