### ISSUE TITLE
お試し延長一覧ボタンの移動。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6283]
管理者でログインして
http://localhost:3000/admin/campaigns/new
にアクセス。

<img width="1375" alt="貼り付けた画像_2023_03_01_14_57" src="https://user-images.githubusercontent.com/168265/222057219-2b3048c1-1d17-4a89-8324-31b09d2d6ed6.png">

お試し延長一覧ボタンをタブの下に置く。
デザインは machida がやるので、作業をしたら machida にメンションをお願いします。

**Comment by komagata** [comment]
:memo: 何を「管理ページに修正」なのか

**Comment by monyatto** [comment]
@machida 
お疲れさまです！
こちら「お試し延長一覧ボタンを」管理ページに置くということであってますでしょうか？

**Comment by machida** [comment]
@monyatto 管理ページの中にいくつかページがありますが、その中の お試し延長作成 ページの中に お試し延長一覧 のリンクの設置をお願いします。

**Comment by machida** [comment]
@monyatto @komagata 
すいません、このIssueの説明文でコピペのミスをしてました。修正しました。

**Comment by monyatto** [comment]
@komagata @machida 
お疲れさまです！　こちら本番環境での動作確認をお願いしたいです🙏

**Comment by komagata** [comment]
@monyatto 一覧にボタンが移動していないかもです〜

![スクリーンショット 2023-03-18 8 10 42](https://user-images.githubusercontent.com/16577/226067511-b3425177-2899-4579-adf3-d884d977bffb.png)

**Comment by monyatto** [comment]
@komagata 
ご指摘いただいた`admin/campaigns`での移動は`admin/campaigns/new`とは別のissueとして登録されているため、対応外の認識なのですがいかがでしょうか？
[お試し延長作成ボタンの移動。 · Issue \#6282 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/6282)

**Comment by komagata** [comment]
@monyatto すみません、下記は何を確認すればいいでしょうか？わかっておらず・・・

> お疲れさまです！　こちら本番環境での動作確認をお願いしたいです🙏

**Comment by monyatto** [comment]
@komagata 
説明不足で失礼しました！ `admin/campaigns/new`で本番環境でもタブ下に「お試し延長一覧」ボタンが移動しているかご確認いただきたいです🙏（下記issue内でメンションすべきでしたね…！まぎらわしくて申し訳ございません）
[お試し延長一覧のボタンをタブ下に移動 by monyatto · Pull Request \#6287 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/6287)

**Comment by komagata** [comment]
@monyatto 

> admin/campaigns/newで本番環境でもタブ下に「お試し延長一覧」ボタンが移動しているかご確認いただきたいです🙏

こちら確認できました〜

**Comment by monyatto** [comment]
ご確認ありがとうございます！

本番環境で動作確認いただいたのでcloseします。
