### ISSUE TITLE
企業編集ページのタイトル修正。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6284]
管理者でログインし、
http://localhost:3000/admin/companies
にアクセス。企業一覧から適当な一社を選び、その企業の編集ページに入る。

<img width="1605" alt="貼り付けた画像_2023_03_01_15_05" src="https://user-images.githubusercontent.com/168265/222058463-771f5c36-e3ee-4e4b-b90a-f3cf01676af2.png">

上記の様に修正する。
デザインは machida がやるので、作業をしたら machida にメンションをお願いします。

**Comment by machida** [comment]
:memo:
一部、https://github.com/fjordllc/bootcamp/pull/6288 こちらで対応しているので、Issueの内容を書き換える。

**Comment by rira100000000** [comment]
@komagata 

お疲れ様です。こちらのPRがマージ、リリースされましたので本番環境での確認をお願いします。
[企業編集ページのタイトル修正 by rira100000000 · Pull Request \#6731 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/6731)

# 確認方法
1. 管理者アカウントでログインする。
2. `http://localhost:3000/admin/companies`にアクセスする。
3. 任意の企業の編集ページにアクセスする。
4. 以下画像と同じように表示されていることを確認する。
![image](https://github.com/fjordllc/bootcamp/assets/99132547/756ebbd0-010a-4de8-932c-15e571ae166a)

**Comment by machida** [comment]
@rira100000000 本番で確認しましたー🙆‍♂️

**Comment by rira100000000** [comment]
@machida 
ありがとうございます！
closeします！
