### ISSUE TITLE
お試し延長編集ページのボタンの移動。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6285]
管理者でログイン。
http://localhost:3000/admin/campaigns
にアクセスし、お試し延長を作成、編集画面へ行く。

<img width="1110" alt="貼り付けた画像_2023_03_01_15_25" src="https://user-images.githubusercontent.com/168265/222061374-27ff0e01-84d8-4644-bcf6-8be95555ecc0.png">

ボタンをタブの下に移動。
デザインは machida がやるので、作業をしたら machida にメンションをお願いします。

**Comment by Kassy0220** [comment]
@komagata @machida 
このIssueに対応したPRがリリースされました。
動作確認には管理者権限が必要なので、ご確認をお願いしても良いでしょうか？🙏

確認していただきたいのは次の2点です。

### お試し延長編集ページにあるボタンの位置
以下の手順で確認をお願いいたします。

1. 管理者権限を持つアカウントでログイン
2. お試し延長作成ページ(`https://bootcamp.fjord.jp/admin/campaigns/new`)から、お試し延長を作成する。
3. お試し延長が作成されるので、作成されたお試し延長の操作ボタンをクリックして、お試し延長編集ページ(`https://bootcamp.fjord.jp/admin/campaigns/campaign_id/edit`)に移動する。
4. `お試し延長一覧`ボタンがタブの下に移動していることを確認する。

### titleタグの文言の変更

以下のページのタイトルタグの文言の確認をお願いいたします。

| 該当ページ           | タグの文言         | 
| -------------------- | -------------- | 
| お試し延長一覧ページ(`https://bootcamp.fjord.jp/admin/campaigns`) | お試し延長一覧 | 
| お試し延長作成ページ(`https://bootcamp.fjord.jp/admin/campaigns/new`) | お試し延長作成 | 
| お試し延長編集ページ(`https://bootcamp.fjord.jp/admin/campaigns/campaign_id/edit`) | お試し延長編集 |

**Comment by machida** [comment]
@Kassy0220 本番で確認しました！OKでしたー🙆‍♂️

**Comment by Kassy0220** [comment]
@machida 
ご確認ありがとうございます！🙏

本番環境で動作確認できましたので、Issueをcloseいたします。
