### ISSUE TITLE
休会ユーザーのプロフィールでtranslation missing

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#6296]
## 概要

休会ユーザーのプロフィールページで区分にHibernationedが表示され、日本語化に失敗している

## 再現手順

1. /users/kyuukaiにアクセス。
2. 区分に「Hibernationed」が表示される。カーソルを合わせるとtranslation missing。

## 期待される振る舞い

「休会」を表示

## スクリーンショット

<img width="540" alt="image" src="https://user-images.githubusercontent.com/69447745/223004570-0b22eba4-06b9-4e5e-b4ef-bc4b77d20b6e.png">

**Comment by YukiWatanabe824** [comment]
本番で確認が取れたのでクローズいたします
