### ISSUE TITLE
提出物一覧で研修生の提出物に研修修了までの日数を表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6297]
メンターでログインし、提出物一覧にアクセスしたとき、提出物が研修生の提出物だった場合、提出物に研修終了日と研修修了まであと何日かを表示したい。

<img width="772" alt="貼り付けた画像_2023_03_09_16_21" src="https://user-images.githubusercontent.com/168265/223949535-e57f4afe-9a19-44c6-9b10-22e285fba9cc.png">

- この部分に、`研修終了日: 20XX年XX月XX日（あとXX日）` と表示したい（曜日は不要）。
- この表示はメンターと管理者にだけ表示される。
- 研修の残りが24時間を切った場合は、`研修終了日: 20XX年XX月XX日（本日研修最終日）` と表示したい。
- 研修終了まで8日を切った場合は（8日未満、つまり7日以下の場合）は赤文字で表示したい。

こちらデザインは僕の方で対応しますー。

**Comment by a-kuroki-gs** [comment]
@komagata @machida 
お疲れ様です！２点質問がございます。

１点目、研修生のデータについてです。
現在、(研修中の)企業研修生として`db/fixtures/users.yml`に存在するのは、終了日が１年後のユーザー・定められていないユーザーの２名となっております。
以下の手順で、ローカルでの動作確認自体は可能ではあるのですが、動作確認用のデータ(24時間以内に終了、７日以内に終了などの研修生データ)は必要でしょうか？
- `db/fixtures/users.yml`を書き換える
- `rails db:seed`を実行→研修終了日を書き換わる

また必要であった場合、このPRに含めてよいかどうかも教えていただけますと幸いです。

２点目、１点目とも少し関連しますがテストについてです。
「提出物一覧画面に`研修終了日: 20XX年XX月XX日（あとXX日）`と表示されるかどうか」のテストを追加しようと考えているのですが、その他の内容(24時間以内に終了、７日以内に終了など)のテストも追加すべきでしょうか？
またそうであれば、`test/fixtures/users.yml`にも必要なデータを追加したほうがよいでしょうか？

お忙しいところ恐れ入りますが、ご確認よろしくお願いいたします🙏

**Comment by komagata** [comment]
@a-kuroki-gs 

> 以下の手順で、ローカルでの動作確認自体は可能ではあるのですが、動作確認用のデータ(24時間以内に終了、７日以内に終了などの研修生データ)は必要でしょうか？

ステージング環境での確認には必要かと思います。（ステージング環境ではDBを直接いじることができないのでseedで設定する必要があります）

> その他の内容(24時間以内に終了、７日以内に終了など)のテストも追加すべきでしょうか？

不要です。（迷うところですが）

**Comment by a-kuroki-gs** [comment]
@komagata @machida 
お疲れ様です！
こちらのIssueの動作確認を行っている際に、気になった点がありましたのでご相談です。

提出物に研修終了日を表示する対象として、現在の状況では以下のようになっております。
- 一覧画面：管理者とメンター
- 詳細画面：メンター

(参考：[詳細画面のIssue](https://github.com/fjordllc/bootcamp/issues/6298)・[詳細画面のPR](https://github.com/fjordllc/bootcamp/pull/6363))

これらの仕様は合わせるべきだと考えており、
両方のIssue内で `この表示はメンターと管理者にだけ表示される。` と@machidaさんもコメントされていますので
その方向性で合わせるのがよいと思うのですが、いかがでしょうか？

また、もしその方向性でよければ、私の方でIssueを作成してよろしいでしょうか？

ご確認よろしくお願いいたします🙏

**Comment by machida** [comment]
@a-kuroki-gs 
提案ありがとうございます！
仕様を合わせて、どちらも管理者とメンターにしたいです。Issueお願いします🙏

**Comment by a-kuroki-gs** [comment]
@machida 
ありがとうございます！
Issue作成しました(^^)/
https://github.com/fjordllc/bootcamp/issues/7603

**Comment by machida** [comment]
@a-kuroki-gs ありがとうございます🙏

**Comment by komagata** [comment]
@a-kuroki-gs 本番環境で正しく動作することを確認しました～🎉

**Comment by a-kuroki-gs** [comment]
確認いただきありがとうございました～！Closeさせていただきます🙌
