### ISSUE TITLE
【メンター向け】企業研修生は研修終了日がいつなのかわかりやすくする

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6298]
## 困っていること
企業研修生は研修終了日が事前に決められている場合がある。
終了日直前に提出物のレビューをすると、そのあとのやりとりがほとんどできずに（もしくはまったくできずに）研修終了になってしまう可能性がある。

## こうなると嬉しい
- メンターが企業研修生の研修終了日に早めに気づける
  - 終了日が近い生徒さんを見つけたら少し優先的にレビューコメントを付けたり、「終了日が近いですけど大丈夫ですか？」的なコメントを入れたりすることができるかもしれない

## 解決策（案）
提出物のページなどで名前の横に「研修終了日: 2023-3-31」のような文言を少し目立つ形で表示する。

<img width="874" alt="fbc" src="https://user-images.githubusercontent.com/1148320/223102692-1d64ea94-fc35-4b2e-9792-38077c0f0c7c.png">

上記はあくまで一案なので、問題が解決されるのであれば方法は何でも構いません！

**Comment by machida** [comment]
@monyatto 

![貼り付けた画像_2023_03_09_16_37](https://user-images.githubusercontent.com/168265/223952893-80a3573d-4b5e-42d4-b803-bca0e0871458.png)

- この部分に、`研修終了日: 20XX年XX月XX日（あとXX日）` と表示したい（曜日は不要）。
- この表示はメンターと管理者にだけ表示される。
- 研修の残りが24時間を切った場合は、`研修終了日: 20XX年XX月XX日（本日研修最終日）` と表示したい。
- 研修終了まで8日を切った場合は（8日未満、つまり7日以下の場合）は赤文字で表示したい。

こちらデザインは僕の方で対応しますー。

**Comment by monyatto** [comment]
@machida 
お疲れさまです！　実装を進めるにあたっていくつか質問がでてきたのでご確認お願いします🙏

1. 今回の機能を実装するのは提出物のページのみで大丈夫でしょうか？　日報やQ&Aは不要でしょうか。

2. 下記以外に追加した方が良さそうな条件についてに考えてみたので、ご確認お願いします。

>この部分に、研修終了日: 20XX年XX月XX日（あとXX日） と表示したい（曜日は不要）。
この表示はメンターと管理者にだけ表示される。
研修の残りが24時間を切った場合は、研修終了日: 20XX年XX月XX日（本日研修最終日） と表示したい。
研修終了まで8日を切った場合は（8日未満、つまり7日以下の場合）は赤文字で表示したい。

- 研修終了日を過ぎた場合、`研修終了日: 20XX年XX月XX日（研修終了済）`などの文言を表示する。
- 研修日終了日が入力されていない場合は以下のいずれかの表示にする。
  - `研修終了日: 未入力`などの文言を表示する
  - `研修終了日:`の表示自体を無くす（名前のみの表示にする）

**Comment by machida** [comment]
@monyatto ありがとうございます！！

なるほど、確かに提出物以外にも必要かもですね。こちらは別Issueにして、今回は提出物だけでお願いします。

未入力の場合と終了の場合の表示を考えていませんでした。提案助かります🙏提案いただいた内容で対応お願いしますー

**Comment by monyatto** [comment]
本番環境で動作確認いただいたためcloseします。

**Comment by JunichiIto** [comment]
@monyatto 対応ありがとうございました！😄
