### ISSUE TITLE
Docを公開したときの notification のメッセージを変更したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6302]
<img width="2221" alt="貼り付けた画像_2023_03_08_15_14" src="https://user-images.githubusercontent.com/168265/223633833-0e2f5946-252d-4ac4-999a-c76b71b15ab6.png">

これを `ドキュメントを作成しました。`  に変更したい。

**Comment by YukiWatanabe824** [comment]
本番環境で確認できたのでIssueをCloseします
