### ISSUE TITLE
Docを更新したときのnotification のメッセージを変更したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6304]
<img width="2244" alt="貼り付けた画像_2023_03_08_15_21" src="https://user-images.githubusercontent.com/168265/223635000-6113b338-3daa-43a5-8af4-2fe0acf4ffd1.png">

これを `ドキュメントを更新しました。`  に変更したい。

( 7/5 追記 )
DocをWIPで保存した際のメッセージも`ページをWIPとして保存しました。`となっているので、
`ドキュメントをWIPとして保存しました。`に変更する。

<img width="1134" alt="_development__サンプルドキュメント___FBC" src="https://github.com/fjordllc/bootcamp/assets/79003082/e6700a55-37c4-4931-805b-5ab20bb6df54">

**Comment by Kassy0220** [comment]
@komagata @machida 
すみません、このIssueに関して一点質問があります。

Docを更新した時と同じく、DocをWIPで保存した際のメッセージも「ページ」の文言になっていることに気づきました。
<img width="1208" alt="_development__サンプルドキュメント___FBC" src="https://github.com/fjordllc/bootcamp/assets/79003082/5ba3589a-b5b6-4cf1-9022-a52e5ed76912">

DocをWIPで保存した際のメッセージも同様に修正しても大丈夫でしょうか？
それとも別のIssueに切り出した方が良いでしょうか？

**Comment by machida** [comment]
@Kassy0220

Issueは追加せず、Issueを編集して追記をお願いします。

両方の対応を一つのプルリクで作業をお願いします。

**Comment by Kassy0220** [comment]
@machida 
ご確認ありがとうございます🙇🏻

Issueの概要を編集して、WIPの場合を追記しました。
両方の場合を今回のプルリクで対応いたします。

**Comment by machida** [comment]
@Kassy0220 追記ありがとうございますー🙏

**Comment by Kassy0220** [comment]
本番環境で動作確認できましたので、こちらのIssueをcloseします🙌
