### ISSUE TITLE
お知らせのメール通知に作者を表示してほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6305]
お知らせを作成したときに飛ぶ通知メール、

<img width="736" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/d4304d63-efaa-4f71-a5aa-a2f050c878f4">

お知らせの作者が載ってないので、お知らせ作成者のアカウントID（ログイン名）を表示したい。
デザインは町田がやります。

**Comment by 88-99** [comment]
本番環境で確認できましたのでcloseします。

**Comment by 88-99** [comment]
本番環境で確認できましたのでcloseします。

**Comment by 88-99** [comment]
本番環境で確認できましたのでcloseします。

**Comment by 88-99** [comment]
本番環境で確認できましたのでcloseします。
