### ISSUE TITLE
提出物個別ページにある、右側の自分の提出物一覧をvue.js化する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6308]

**Comment by maimux2x** [comment]
@komagata 
早速の質問で恐縮なのですが、対象のページは以下でよろしいでしょうか？
https://bootcamp.fjord.jp/current_user/products

![Monosnap 自分の提出物 | FBC 2023-03-08 23-03-22](https://user-images.githubusercontent.com/76797372/223733357-d5ee9c6c-cc5f-45b1-8314-6019f0b9121b.png)

「右側の自分の提出物一覧」が指す箇所が分からず、確認させていただけると幸いです。

**Comment by komagata** [comment]
@maimux2x いいえ、提出物の個別ページです。（`/products/1234`みたいなページ）

**Comment by maimux2x** [comment]
@komagata 
ありがとうございます！
自分の `https://bootcamp.fjord.jp/products/14743` などのページを見てみましたが右側に提出物一覧があるページが見当たりません。。。

<img width="2136" alt="提出物" src="https://user-images.githubusercontent.com/76797372/224493924-3387c057-16b4-4c11-a34d-c5c69b9b9aef.png">

メンターさんの権限でログインすると提出物個別ページの右側に受講生の日報や提出物を確認できる一覧があったのですが、こちらが開発対象でしょうか？
<img width="1256" alt="メンター" src="https://user-images.githubusercontent.com/76797372/224494111-50d0faba-e0f1-41c9-b159-2029f63c8d00.png">

**Comment by komagata** [comment]
@maimux2x はい、メンターでログインした時の場合の右側にある提出物一覧です。
