### ISSUE TITLE
Docs『提出物を出す時の注意点』における誤字

### ISSUE THREAD

**Issue by note103** [fjordllc/bootcamp#6311]
## 概要

下記ページの冒頭部分に、1文字、誤字がありました。
https://bootcamp.fjord.jp/pages/info-for-product

## 再現手順 / 期待される振る舞い

以下のスクリーンショット部分に「 `提提出物` 」という文言がありますが、本来は「 `提出物` 」かと思います。

## スクリーンショット

![03d36a231c526be2c33dc961fc44c9f4-2](https://user-images.githubusercontent.com/970686/224009092-a8831b48-c4ef-4ba1-8b56-827dc47618fb.png)

## 備考

上記の誤字部分はリンクになっていますが、リンク先の記事タイトルにはとくに誤字はありませんでした。

## 環境

 - OS: macOS 13.2.1
 - ブラウザ: Google Chrome
 - バージョン:  110.0.5481.177（Official Build） （arm64）

**Comment by komagata** [comment]
修正いたしました〜

**Comment by note103** [comment]
ありがとうございます！確認しました  🙌
