### ISSUE TITLE
今日、明日開催のイベントのお知らせ方法の通知方法の変更

### ISSUE THREAD

**Issue by lef237** [fjordllc/bootcamp#6320]
## 機能の説明

定期イベントの「ダッシュボードに表示されるお知らせ」のバーのON/OFFを切り替えられるようにする。

ON/OFFが切り替えられるようにすれば、ダッシュボードにバーが毎日大量表示されてしまう問題を防げる。

## 何故この機能が必要なのか

![image](https://user-images.githubusercontent.com/93074851/224911584-5082df18-a600-4fef-9796-ccd75448cc5e.png)

このように、定期イベントがダッシュボードに表示されるのですが、毎日開催の定期イベントの場合だと、画面表示されるバーの数がかなり増えてしまって（毎日表示されるので）、消すのが面倒だったりします。

そのため、「ダッシュボードに表示されるお知らせ」の画面表示バーを、定期イベントの個別ページでON/OFFできるように自分で設定することができたらとても助かります！

※定期イベントの参加登録を解除すれば、お知らせのバーは表示されなくなるのですが、せっかく定期イベントに参加しているのに、一度参加ボタンを押した登録を解除するのは、主催者の方にも申し訳なくて、心理的なハードルが大きいです。
（以前は参加者が多かったのに、今では参加者がこんなに減っている……！というショックを与えてしまいます😭）

**Comment by wata00913** [comment]
@machida 
お疲れ様です！

仕様について質問があります。
1. 今回のIssueで `今日、明日開催イベントのお知らせ` の通知方法を変更しますが、その通知方法は以下の「最新のお知らせ」のようなカード形式という認識でよろしいでしょうか？
    <img width="720" alt="image" src="https://user-images.githubusercontent.com/85052152/229010580-7c096341-b928-4ebe-9f12-10538504d638.png">
1. 通知方法を変更する対象は、イベント種別に関わらず「イベント(特別イベント)」、「定期イベント」の両方でしょうか？

以前チーム開発MTGの際に説明を受けたのですが、改めて確認させて下さい🙏

**Comment by machida** [comment]
@wata00913 すいません、こちらのデザインについて連絡をしようとしてたのですが、遅れてしまいました🙇‍♂️

はい！そのようにカード内のリストに変更しようと考えています。詳細は後ほど連絡します。

また、その変更によって、現在の表示で使っているXをクリックすると消える機能も削除することになります。その機能に関するjsのファイルの削除をお願いします。

もし、デザインがなくて手が止まった場合は追加のIssueをアサインするので連絡をお願いします。

**Comment by machida** [comment]
@wata00913 通知を変更するのは、定期イベント、特別イベント両方でお願いします。

**Comment by wata00913** [comment]
@machida 
回答ありがとうございます！

>はい！そのようにカード内のリストに変更しようと考えています。詳細は後ほど連絡します。
もし、デザインがなくて手が止まった場合は追加のIssueをアサインするので連絡をお願いします。

了解しました！手が止まったらアサインの連絡しようと思います。

また、機能面についての補足説明もありがとうございます🙇‍♂️

**Comment by machida** [comment]
@wata00913 
https://github.com/fjordllc/bootcamp/pull/6377
デザイン（見た目だけでリンクなどはベタ書き）を作り、PRを作りました。
こちらをそのまま使うか、この PR の commit を cherry-pick するなどしてくださいー

**Comment by wata00913** [comment]
@machida 

>デザイン（見た目だけでリンクなどはベタ書き）を作り、PRを作りました。

お知らせありがとうございます！

**Comment by wata00913** [comment]
本番環境で動作確認したのでcloseします。
