### ISSUE TITLE
提出物一覧の提出物投稿者名の表示を他の一覧と合わせたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6321]
<img width="769" alt="貼り付けた画像_2023_03_14_17_28" src="https://user-images.githubusercontent.com/168265/224941083-5bb2f864-0f98-4152-adc2-64635e608433.png">

今はアカウント名だけが表示されているが、

`アカウント名（カタカナの名前）` で表示したい。

日報一覧はその様になっている。それと同じにする。

<img width="691" alt="貼り付けた画像_2023_03_14_17_29" src="https://user-images.githubusercontent.com/168265/224941384-8993c8af-507a-4efb-a184-390947bfe5d5.png">

**Comment by OdenTakashi** [comment]
本番環境で動作確認が取れたため、closeします！
