### ISSUE TITLE
ダッシュボードの最新のお知らせ一覧に投稿者名を表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6322]
ダッシュボードの最新のお知らせ一覧

<img width="388" alt="image" src="https://user-images.githubusercontent.com/168265/224941779-9d9e89ff-8fdb-45f3-929d-4f948abd3226.png">

この一覧に、

<img width="694" alt="貼り付けた画像_2023_03_14_17_32" src="https://user-images.githubusercontent.com/168265/224941928-9046dfd8-c2e4-40e1-bbae-c39be090a909.png">

これを表示するようにする。上はお知らせ一覧をキャプチャしたもの。

**Comment by sochi419** [comment]
本番環境で動作確認OKでした！
closeします。
