### ISSUE TITLE
[お知らせ生成]イベントを作成したときに、お知らせが作成されるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6324]
イベント作成ページにこのようなチェックボックスを置きたい。
（このチェックは公開されているイベントの編集画面には表示しない。）

<img width="1334" alt="貼り付けた画像_2023_03_22_14_42" src="https://user-images.githubusercontent.com/168265/226814948-f04a735e-e274-42eb-952a-a53e678b6eb2.png">

これをチェックした状態で定期イベントを公開すると、お知らせ作成ページに遷移するようにしたい。

お知らせページには、

---

## タイトル

`{イベント名}を開催します🎉`

## 本文

```
<!-- このテキストを編集してください -->

{イベント名}を開催します🎉

- 開催日時
    - {イベント開始日時} 〜 {イベント終了日時}
- 会場
    - {会場}
- 定員
    - {定員}
- 募集期間
    - {募集開始日時} 〜 {募集終了日時}

---

{イベントの詳細}

## 参加登録はこちら
https:xxxxxxxxx（イベントページのURL）

---
```

上記が入力された状態で開く。

---

参考: https://github.com/fjordllc/bootcamp/pull/6269

**Comment by ymmtd0x0b** [comment]
本番環境にて正常動作しているのを確認できましたので Close します！
