### ISSUE TITLE
[お知らせ生成]定期イベントを作成したときに、お知らせが作成されるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6325]
定期イベント作成ページにこのようなチェックボックスを置きたい。
（このチェックは公開されているイベントの編集画面には表示しない。）

<img width="1334" alt="貼り付けた画像_2023_03_22_14_42" src="https://user-images.githubusercontent.com/168265/226813080-7790ed64-df7e-42c6-aee2-95bde835fa55.png">

これをチェックした状態で定期イベントを公開すると、お知らせ作成ページに遷移するようにしたい。

お知らせページには、

---

## タイトル

`{定期イベント名}を開催します🎉`

## 本文

```
<!-- このテキストを編集してください -->

{定期イベント名}を開催します🎉

- 開催日
    - {定期開催日 例: 毎週月曜日} （祝日も開催 or 祝日はお休み）
- 開催時間
    - {開始時間} 〜 {終了時間}
- 主催者
    - @{主催者 アカウント}
    - @{主催者 アカウント}

---

{定期イベントの詳細}

## 参加登録はこちら
https:xxxxxxxxx（定期イベントページのURL）

---

このチェックは公開されているイベントの編集画面には表示しない。


```

上記が入力された状態で開く。

---

参考: https://github.com/fjordllc/bootcamp/pull/6269

**Comment by ymmtd0x0b** [comment]
@djkazunoko 
お疲れ様です！現在、チーム開発に参加中のヤマモトです！

雑談・質問タイムで頂いたアドバイスが、こちらの Issue でも役立ちそうだと思ったので共有させて頂きます！不要かもしれませんが、ご参考になれば幸いです🙏

## Q. どうやって『イベントが公開済み』なのかを判定すれば良いのか🤔

### 背景

今回、私とdjkazunokoさんはそれぞれの担当するビューにお知らせ作成用のチェックボックスを配置しますが、加えてこのチェックボックスは『既に公開しているイベントの編集画面では表示しない』という条件があります！

このため、下記コードのように作成・編集するイベントが『公開済みであるか』を判定して、チェックボックスの表示・非表示を切り替える必要があると思います！

```rb
# views/pages/_form.html.rb
unless event.公開済み?
  f.checkbox '属性名', 'クラス名'
  f.label '属性名'
```

### 問題点

しかしながら、[参考PR](https://github.com/fjordllc/bootcamp/pull/6269)の pageテーブルと異なり、イベントと定期イベントのテーブルには `published_atカラム` が存在しないため、これを判定するメソッドの定義が非常に難しいです💦

## A. published_at カラムを追加してください

上記の背景と問題点をkomagataさんとmachidaさんに相談したところ、他のテーブルと同様に`published_atカラム`を追加して下さいと回答を頂きました🙌 ( 定期イベントもこの方法で良いそうです😄 )

**Comment by djkazunoko** [comment]
本番環境で動作確認ができましたので、closeいたします。
