### ISSUE TITLE
[newspaper] 提出物のメンターへの通知をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6327]
ProductCallbacks.rbにあるメンターへの通知をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/62f28dbc23c1f947790a324ed57f627e5a69d6c2/app/models/product_callbacks.rb#L56)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by monyatto** [comment]
@komagata 
チームメンバーからApproveいただいたのでご確認お願いします🙏

**Comment by monyatto** [comment]
@komagata 
こちらのissueについて確認させてください🙇🏻
- 既存の実装では、提出物が作成あるいは更新されたタイミングでそのプラクティスをwatchしているメンターに通知されるようになっています。
- 作成と更新のどちらでも`〇〇さんが「×××」の提出物を提出しました。`という文面になっています。
- プラクティスをwatchしているメンターへの通知は、提出物を作成したタイミングだけでなく、更新したタイミングも含まれるのは想定された動作でしょうか？
  - 上記が想定された動作の場合、提出物が更新された場合は`〇〇さんが「×××」の提出物を更新しました。`という文面になるように変更した方が良いのではないかと思ったのですがいかがでしょうか？ その場合、こちらのissueとは別に新規issueを立ててよろしいでしょうか？
  - 想定されていない動作の場合（提出物作成時のみに通知がいく）、今回のissueでそのように修正してもよろしいでしょうか？
- また研修生の提出物に関する所属企業のアドバイザーへの通知も上記と同じ実装になっているので、今回のissueで対応する内容、あるいは新規issueとして作成が必要でしたらお知らせいただけると幸いです。

**Comment by monyatto** [comment]
チーム開発MTGにて相談したところ、以下の二つの内容に対応する別のissueを立てることになった。
- 提出物が更新された場合は`〇〇さんが「×××」の提出物を更新しました。`という文言で通知されるように変更する。
- 研修生の提出物に関する所属企業のアドバイザーへの通知も同様にする。

**Comment by monyatto** [comment]
@komagata @machida 
#6444 次回のMTG中に動作確認お願いしたいです🙏

**Comment by monyatto** [comment]
開発MTGにて動作確認ができましたのでcloseします！
