### ISSUE TITLE
[newspaper] 提出物の学習ステータス変更処理をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6328]
ProductCallbacks.rbにある学習ステータス変更処理をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/62f28dbc23c1f947790a324ed57f627e5a69d6c2/app/models/product_callbacks.rb#L66)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by wata00913** [comment]
本番環境で動作確認しましたのでCloseします。
