### ISSUE TITLE
[newspaper] 質問のDiscord通知をnewspaperに置き換えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6329]
QuestionCallbacks.rbにある質問のDiscord通知をnewspaperに置き換えたい

- [既存の処理](https://github.com/fjordllc/bootcamp/blob/62f28dbc23c1f947790a324ed57f627e5a69d6c2/app/models/question_callbacks.rb#L19)
- [ActiveRecordのObserversやCallbacksの問題点 - komagataのブログ](https://docs.komagata.org/5859)
- [newspaperでActiveRecordのCallbacksを置き換える - komagataのブログ](https://docs.komagata.org/5860)

**Comment by djkazunoko** [comment]
本番環境で動作確認ができましたので、closeいたします。
