### ISSUE TITLE
[分報]分報チャンネルがアカウントIDの頭文字のグループ内で自動作成されるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6350]

**Comment by ymmtd0x0b** [comment]
@komagata 
アカウント登録時のDiscordチャンネル自動作成の対象カテゴリー変更に伴い次の２つの作業をお願いしたいです。

## 作業

1. ステージング環境での動作確認のために、以下の手順により"ステージング環境用のDiscord"に `数字・A・B・C (ひとりごと・分報)` のカテゴリーを作成
2. デプロイ後は"本番環境用のDiscord"の `新規🎉(ひとりごと・分報)` が、チャンネル作成時に適切なカテゴリーへ分類出来ない際のデフォルトグループとして扱うため、カテゴリー名を"その他"や"Other"等の適切な名称へ変更

## カテゴリー作成手順

1. Discord を立ち上げ、チャンネルエリア上で右クリック<br><img src="https://github.com/fjordllc/bootcamp/assets/95903475/1eb25326-ca1c-41c8-8bcb-5fae8264e2dd" width="300">

2. 『カテゴリーを作成』をクリック<br><img src="https://github.com/fjordllc/bootcamp/assets/95903475/abf29e60-e950-4c5f-a991-5a1946b9e621" width="300">

4. カテゴリー名に `数字・A・B・C (ひとりごと・分報)`  を入力して、カテゴリー作成ボタンをクリック<br><img src="https://github.com/fjordllc/bootcamp/assets/95903475/6c973a73-1757-40d3-a24f-2c0ca1b017a9" width="300">

5. カテゴリーが作成されている事を確認<br><img src="https://github.com/fjordllc/bootcamp/assets/95903475/7d286c36-31f4-411d-8fe1-b64957694368" width="300">

以上、よろしくお願い致します🙇‍♂️

**Comment by komagata** [comment]
@ymmtd0x0b こちら作業行いました〜

**Comment by ymmtd0x0b** [comment]
@komagata 
ありがとうございます🙏

もう1点確認をお願いしたいです。
先程作成して頂いたステージング環境用 Discord サーバーのカテゴリー`数字・A・B・C (ひとりごと・分報)`に、次の分報チャンネルがあることを確認いただきたいです。
- alice

**Comment by komagata** [comment]
@ymmtd0x0b ステージング用のDiscordサーバーにaliceチャンネルができていることを確認しました。

<img width="261" alt="スクリーンショット 2023-06-21 23 16 53" src="https://github.com/fjordllc/bootcamp/assets/16577/24875ceb-109d-4f66-acb8-a396d2b50789">

**Comment by ymmtd0x0b** [comment]
@machida 
お疲れ様です！
今週のリリースにより、入会時に自動作成される分報チャンネルの対象カテゴリーが変更されました。

この変更に伴い ドキュメント：[⏱分報を書こう！！ひとりごとチャンネルの作り方 #自分の分報チャンネル](https://bootcamp.fjord.jp/pages/times#-3)  の更新が必要と思われますが、作業をお願いしてもよろしでしょうか？🙇‍♂️ 
( 私の方で変更しようと思いましたが[こちらのやりとり](https://github.com/fjordllc/bootcamp/issues/6103#issuecomment-1473200672)で町田さんにご対応頂いていたので、今回もお願いした方が良いと判断しました )

<br>

問題なければ私が作成した文面をお使い頂ければと思います。

---

自分の分報チャンネルは、入会時に自動で生成されています。
Discord の画面左にあるチャンネル一覧に、「〇〇(ひとりごと・分報)」というカテゴリーがあります。

| 数字 + A 〜 N | O 〜 Z |
| :--: | :--: |
| <img src="https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlFXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--966f637b26714d76fc57b114a42bed3da86aebc3/discord_%E5%88%86%E5%A0%B1%E3%83%81%E3%83%A3%E3%83%B3%E3%83%8D%E3%83%AB_a-n.png"> | <img src="https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk1XQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e07a1b128a8e170288eebc8098ff8de6448e001f/discord_%E5%88%86%E5%A0%B1%E3%83%81%E3%83%A3%E3%83%B3%E3%83%8D%E3%83%AB_o-z.png" style="margin-bottom: 50px"> |


自分のアカウント名の頭文字と同じカテゴリー内にあるので、そこを探してみてください。

**Comment by machida** [comment]
@ymmtd0x0b

おお、リリースされたんですね！報告ありがとうございます🙏

文面もありがとうございます！こちら更新の際に使用させていただきますー

Discordでtogoさん宛にこの機能のリリースについて(今までとの変更点など)簡単に説明をしていただけると助かります🙏

**Comment by machida** [comment]
@ymmtd0x0b 
すいません、やっぱりドキュメントも更新していただけると助かります🙏

**Comment by ymmtd0x0b** [comment]
@machida 
了解しました！ドキュメント更新とtogoさんへ変更点の連絡をしておきます🙋‍♂️

**Comment by ymmtd0x0b** [comment]
📝メモ

[ドキュメントの更新](https://bootcamp.fjord.jp/pages/times#-3) と togoさんへの連絡 を行いました🙋‍♂️

**Comment by machida** [comment]
@ymmtd0x0b 対応ありがとうございます🙏

**Comment by ymmtd0x0b** [comment]
本番環境にて正常動作していることを確認しましたので Close します🙋‍♂️
