### ISSUE TITLE
イベントを「特別イベント」に名称を変更したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6352]
今までは events をイベントという名前にしていたが、regular-events （定期イベント）という新しいものを作ったので、

- イベント
    - イベント... events
    - 定期イベント... regular-events

という構造になっていて気持ち悪い。

今までイベントと呼ばれていた events を 特別イベント という名称にしたい。

- イベント
    - 特別イベント... events
    - 定期イベント... regular-events

このようにしたい。

**Comment by wata00913** [comment]
@komagata @machida

お疲れさまです。

本日リリース予定のこちらの[PR](https://github.com/fjordllc/bootcamp/pull/6403)について、本番環境での動作確認について質問があります。

このPRでは、FBCのページとメール通知での文言確認を行います。それに伴い、いくつかの文言を確認するために特別イベントを1つ作成する必要があります。

**質問内容**としては、「本番環境で動作確認用のイベントを作成しても問題はないか？」です。

懸念点としては以下があります。

1. ダッシュボード上の今日開催のイベント通知の文言を確認したいが、利用者全員に表示されてしまいます。
    - 上記の文言以外を確認する場合は、開催予定日が未来の日付でも対応可能です。
    - 未来の日付で作成する場合、ダッシュボード上のイベント通知の文言確認は、実運用で作成されたイベントの開催日当日に確認する予定です。

※本番環境の動作確認で特別イベントの作成が必要な理由は以下となります。

- イベント作成画面、イベント編集画面で「公開」、「WIP」時のメッセージを確認
- 補欠登録時のダイアログの確認
- イベント削除時のメッセージを確認
- イベントへのコメント、メンション付きコメントの操作が必要（サイト内通知とメール通知の確認）

**Comment by machida** [comment]
@wata00913 確認項目が多いので、本番で試してみてOKです。テストのためのデータであることがわかるようなタイトルと説明をお願いします🙏また、補欠繰り上がりなどの確認作業で他のユーザーの操作も必要な場合は指示をお願いしますー

**Comment by wata00913** [comment]
@machida 
了解しました〜
駒形さん or 町田さんとチーム開発メンバーの操作が必要になりそうなので、その際は指示を出したいと思います。

ご回答ありがとうございました🙏

**Comment by wata00913** [comment]
@komagata @machida

こちらのPR[#6403](https://github.com/fjordllc/bootcamp/pull/6403)がリリースされました。動作確認に管理者権限のログインが必要なので、本番環境での動作確認をお願いいたします🙇‍♂️

### イベント作成時の確認

1.  管理者権限を持つアカウントでログインする
1. 特別イベント作成ページ `/events/new` にアクセスする
1. 以下の項目を入力する
    - タイトル：本番環境の動作確認用イベント（終了済み）
    - 会場：test
    - 定員：1
    - イベント開始日時：2023/05/06 18:15
    - イベント終了日時：2023/05/06 20:15
    - 募集開始日時：2023/05/05 10:15
    - 募集終了日時：2023/05/05 18:15
    - 詳細：本番環境の動作確認用イベントになります。イベントの参加申込や、内容の修正はしないでください。
1. 「作成」ボタンをクリックし、特別イベントを作成する（注意：「WIP」ボタンをクリックしないで下さい。）
1. 作成後のメッセージが「特別イベントを作成しました。」であることを確認する。
1. 上記を確認後、イベントを削除すること。

### イベント更新時の確認

1. 特別イベント編集ページ 「本番環境の動作確認用イベント」( `/events/111/edit` )の「内容変更」ボタンをクリックする
1. 更新後のメッセージが「特別イベントを更新しました。」であることを確認する。
1. 上記を確認後、wata宛てに連絡をお願いします。（注意：こちらで作成した特別イベント「本番環境の動作確認用イベント」は削除しないで下さい。）

**Comment by machida** [comment]
@wata00913 動作確認しましたー🙆‍♂️

**Comment by wata00913** [comment]
@machida 
ありがとうございます！
残りの確認作業は、自分とチーム開発メンバーでしていきます〜

**Comment by wata00913** [comment]
@チーム開発メンバー
チーム開発メンバーのどなたかに、以下の本番環境の動作確認をお願いします。

### 補欠参加の確認
1. 特別イベントページ 「本番環境の動作確認用イベント」( `/events/111` )にアクセスする
1. 「補欠登録」ボタンをクリックする
1. 確認ダイアログのメッセージが「補欠として特別イベント参加申込をします。よろしいですか?」であることを確認する。
1. 確認ダイアログのOKボタンをクリックする。
1. wataがイベントの登録を解除する（手順4. までが完了したらwata宛てに連絡をお願いします。）
1. 補欠から参加に繰り上がりのメールを開く
1. リンクの文言が「特別イベント詳細へ」であることを確認する
### コメント、メンション付きコメントの確認
こちらは確認項目はありません。以下の操作をお願いします。
1. 特別イベントページ 「本番環境の動作確認用イベント」( `/events/111` )にアクセスする
1. イベントページのコメント欄に「本番環境動作確認用のコメントです。」と記載し、コメントする
1. イベントページのコメント欄に **wataをメンションにして**「本番環境動作確認用のメンション付きコメントです。」と記載し、コメントする

**Comment by wata00913** [comment]
odentakashiさんに[動作確認](https://github.com/fjordllc/bootcamp/issues/6352#issuecomment-1549005937)を依頼し、確認完了しました。

**Comment by wata00913** [comment]
本番環境で動作確認しましたのでCloseします。
