### ISSUE TITLE
管理ページ > ユーザー一覧 の「削除ボタン」を削除し、ユーザー個別ページに配置。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6357]
管理者でログインし、 http://localhost:3000/admin/users にアクセス。

<img width="1559" alt="貼り付けた画像_2023_03_23_14_20" src="https://user-images.githubusercontent.com/168265/227110696-b5f7439b-4000-48dd-8374-55673aea72c7.png">

これを削除する。

---

ユーザー個別ページに削除リンクを置く。

<img width="1361" alt="貼り付けた画像_2023_03_23_14_22" src="https://user-images.githubusercontent.com/168265/227111042-fc867b93-5d8e-48a6-bc66-62abe29b3b7c.png">

この削除リンクは、管理者でログインしたときだけ見れるようにする。
デザインはmachidaがやるのでメンションをお願いします。

**Comment by YukiWatanabe824** [comment]
本番環境で確認が取れたのでCloseいたします。
