### ISSUE TITLE
相談部屋に対応済みのフラグを持ちたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6372]
管理者でログインをし、相談部屋にアクセスすると、一般ユーザーと違って、全ての相談部屋の一覧が表示される。

現在、相談部屋は、未返信かどうかで区別ををしている。

<img width="352" alt="image" src="https://user-images.githubusercontent.com/168265/228436631-db9d15b3-145f-463c-9f2d-10899913f2c4.png">

未返信とは、最後に相談部屋でコメントをしたのが管理者ではなく、相談部屋の主である状態のことを指す。
返信したかどうかではなく、管理者は対応が必要なのかそうでないのかで区別をしたい。

なので、管理者でログインした場合は、相談部屋にこのようなチェックボックスを表示したい。

<img width="442" alt="貼り付けた画像_2023_03_29_14_42" src="https://user-images.githubusercontent.com/168265/228437536-a1c37785-4dcf-4575-882a-faf9cce77485.png">

対応済にチェックが入っていなかった場合は、未対応の状態である。

以下の画像の A の数字は、現在は「最後に相談部屋でコメントをしたのが管理者ではなく、相談部屋の主である状態の相談部屋の数」を表示しているが、それを変更し、未対応の状態の部屋の数を表示するようにする。

この変更に伴い、未返信ではなく未対応に文言を変更する。

![貼り付けた画像_2023_03_29_14_44](https://user-images.githubusercontent.com/168265/228437806-b35bdc0d-6319-4e2d-b7fc-495c620b0e46.png)

この数字も同様に未対応の状態の部屋の数を表示するようにする。

<img width="100" alt="貼り付けた画像_2023_03_29_14_47" src="https://user-images.githubusercontent.com/168265/228438182-98b6c9f1-adae-492b-aca4-0e54ceb4ca37.png">

---

一度、対応済にチェックを入れても、相談部屋の主が新たにメッセージを投稿したら、対応済のチェックは外れるようにする。

しかし、新たにメッセージを投稿したのが相談部屋の主ではなく管理者の場合は、対応済のチェックが入っている場合はその状態がキープされる。

**Comment by OdenTakashi** [comment]
@machida 

お疲れ様です！
相談部屋の利用に関して1点質問させて頂きたいです！

## 質問
- 管理者の方が実際に相談部屋を使われている中で「解決してないけど相談としては終了したい」というケースはありますか？

## 背景
現在、こちらのPR([相談部屋に対応済みのフラグを追加した。 \#6393](https://github.com/fjordllc/bootcamp/pull/6393))で作業を進めている状況です。
その中で「対応済み」かどうかを判定するために`resolved`というカラムを`talks`テーブルに追加しようと考えています。
しかし、管理者の方が相談部屋を実際に使われている中で「解決してないけど相談としては終了したい」というケースがあるとすると`resolved`というカラムでは整合性が取れなくなってしまうのではないかと考えたことがこの質問をさせていただいた背景になります。

**Comment by machida** [comment]
@OdenTakashi 

> 管理者の方が実際に相談部屋を使われている中で「解決してないけど相談としては終了したい」というケースはありますか？

はい、あります！相談が解決という意味ではなく、「管理者のターンが終了した」という意味で使いたいと考えています。

例えば、

ビデオチャットの候補日を管理者が投稿した場合、次のアクションは相談者がその中から日時を選択することになりますが、管理者としては候補日を管理者が投稿した時点で、それに対する返信が来るまでやることはなくなります。その場合、対応済にします。

相談者から返信が来たら、次は管理者のターンです。相談者の選んだ日付の確認、次にビデオチャットのURLを送るなどをします。その作業をこれからするので、相談者から返信があった場合は、自動で対応済のチェックは外れるようになります。

---

別の例で、

相談者から新規の相談が投稿された場合、その相談を machida が開いたが、その回答は komagata さんでないとできない内容だったとします。

まず、相談者から投稿された場合、自動で対応済みのチェックは外れます。そして machida が、その件については komagata さんから連絡します、と投稿します。しかし、まだこのやりとりのターンは管理者です。komagata さんが返信して管理者のターンが終了します。なので、machida は対応済みのチェックはしません。

komagata さんが返信した時点で komagataさんが対応済みのチェックを外します。

もし、machida が、その件については komagata さんから連絡します、と投稿した後、komagata さんの返信の前に相談者から、承知しました、komagata さんからの返信を待ちます、という返信があった場合、対応済みのチェックは外れたままです。そして、komagata さんが返信した時点で komagataさんが対応済みのチェックを外します。

**Comment by OdenTakashi** [comment]
@machida 
ご返信いただきありがとうございます！
丁寧に例をあげて頂きありがとうございます、とてもわかりやすくて助かります🙏

> 相談が解決という意味ではなく、「管理者のターンが終了した」という意味で使いたいと考えています。

なるほどです！
対応済みのチェックは管理者と相談者の会話のラリーの中でその都度されていくという想定なのですね！
最終的に解決したかどうかのみに焦点を当てて考えてしまっていました。💦

でしたら`resolved`というカラム名は適していないと思いますので、もう一度考え直したいと思います。！

**Comment by machida** [comment]
`action_completed` とかでもいいかもですねー。

**Comment by OdenTakashi** [comment]
@machida
> action_completed とかでもいいかもですねー。

なるほどです！
`action_completed`は思いつきませんでした💦
この文脈でとてもfitする名前だなと感じましたので、参考にさせて頂きます🙏

**Comment by wata00913** [comment]
@machida 
お疲れさまです！
仕様について1点質問させて頂きたいです！

現在の実装では、相談部屋の主が既存コメントを編集した場合も「対応済みのステータス」に変更されてしまいます。この機能は個人的には不要だと考えましたが、必要でしょうか？

不要だと判断した理由は、以下のPRコメントに記載しております。
https://github.com/fjordllc/bootcamp/pull/6393#discussion_r1209789875

よろしくお願いします🙇‍♂️

**Comment by machida** [comment]
📝 :

> こちらのhttps://github.com/fjordllc/bootcamp/pull/6393の実装では、相談部屋の主が既存コメントを編集した場合も「対応済みのステータス」に変更されてしまいます。この機能は個人的には不要だと考えましたが、必要でしょうか？

https://github.com/fjordllc/bootcamp/pull/6393#issuecomment-1584220000

**Comment by OdenTakashi** [comment]
@machida @komagata 
お疲れ様です。
こちらの修正について、自分に権限がないため本番環境での動作確認をお願いしたいです🙇‍♂️
確認手順が多くなっていますがよろしくお願いします🙌💦

## 動作の確認
確認手順は以下の通りになります。

1. 管理者で[odentakashiさんの相談部屋 \| FBC](https://bootcamp.fjord.jp/talks/123#latest-comment)にアクセスしてください。
2. `対応済みです`というボタンをクリックして、画面右上に`未対応にしました`というflashが出ること、`対応済みです`というボタンが`対応済みにする`ボタンに変わっていることを確認してください。

### クリック前
![スクリーンショット 2023-09-15 11 19 18](https://github.com/fjordllc/bootcamp/assets/81839214/0d1e2c82-7629-4293-849c-8493ba2bde7d)

### クリック後
![スクリーンショット 2023-09-15 11 27 03](https://github.com/fjordllc/bootcamp/assets/81839214/b41de1b2-7598-4027-9d0f-1fc4be814f46)

3. [未対応の相談部屋 \| FBC](https://bootcamp.fjord.jp/talks/action_uncompleted)にアクセスを行い、`odentakashiさんの相談部屋 `があることを確認してください。またタブの文言が`未対応`となっていることを確認してください。

![スクリーンショット 2023-09-15 12 57 24](https://github.com/fjordllc/bootcamp/assets/81839214/8188bf5c-2bce-432c-b833-b5dad7978c1c)

4. 再度[odentakashiさんの相談部屋 \| FBC](https://bootcamp.fjord.jp/talks/123#latest-comment)にアクセスしてください。

5. `対応済みにする`ボタンをクリックして、画面右上に`対応済みにしました`というflashが出ること、`対応済みにする`というボタンが`対応済みです`ボタンに変わっていることを確認してください。

`対応済み`の状態で相談部屋の主からコメントが来た際に、`未対応`に変わるということを確認したいため、`手順5`を行い対応済みにした後、連絡をいただきたいです。

連絡をいただいた後、自分が[odentakashiさんの相談部屋 \| FBC](https://bootcamp.fjord.jp/talks/123#latest-comment)にコメントを追加します。コメントを追加後、再度ご連絡差し上げます。

6. [odentakashiさんの相談部屋 \| FBC](https://bootcamp.fjord.jp/talks/123#latest-comment)にアクセスを行い、`対応済みにする`ボタンがあることを確認してください。

**Comment by OdenTakashi** [comment]
本番環境で動作確認をしていただいたのでcloseします。
