### ISSUE TITLE
それぞれのプラクティスに概要を登録できるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6376]
<img width="1840" alt="貼り付けた画像_2023_03_29_14_24" src="https://user-images.githubusercontent.com/168265/228434637-fe5b3271-ef2c-4709-ad18-2c69e0faaa8d.png">

この部分に、

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/168265/228434922-65c0b897-c599-4e7e-b71e-336fe52e469b.png">

概要を追加したい。

概要は必須項目ではない。

---

概要がもし入力されていたら、プラクティス個別ページのこの部分に表示する。

<img width="883" alt="貼り付けた画像_2023_03_29_14_28" src="https://user-images.githubusercontent.com/168265/228435201-c39f0f7e-251e-44bf-8096-2e715ad1ede9.png">

---

## なぜこの機能が必要か？

ログインをしなくてもプラクティスページにアクセスができる機能が近々リリースされる。

ログインをしていない場合は、プラクティスページにアクセスはできるが、プラクティスページの内容は見れない。

ただ、ログインをしていない場合は何も表示しないのではなく、何かしらの情報を表示し、フィヨルドブートキャンプに入会すると何が見れるようになるのか訪問者が予想できる状態にしたい。

この「何かしらの情報」として、概要を表示するようにしたいから。

**Comment by ymmtd0x0b** [comment]
@komagata @machida
お疲れ様です！
今週リリースされたコチラの Issue の動作確認にメンターの権限が必要になりますので、以下の内容のチェックをお願いしたいです🙇‍♂️

## 確認内容

- プラクティスに『概要』が登録できる
- 概要にテキストを登録したプラクティスのみ『概要欄』が表示される

**Comment by komagata** [comment]
@ymmtd0x0b 本番環境で動作することを確認しました。

**Comment by ymmtd0x0b** [comment]
@komagata 
確認ありがとうございました！

**Comment by ymmtd0x0b** [comment]
本番環境にて動作確認OKを頂いたので Close します！
