### ISSUE TITLE
プラクティス着手状態から提出物をWIPにすると未着手になる

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#6381]
## 概要

プラクティスのステータスを「着手」の状態から、そのプラクティスの提出物をWIPで保存するとステータスが「未着手」に変わる

## 再現手順

1. 提出物のあるプラクティス個別ページにアクセス。
2. ステータス「着手」をクリック。
3. 提出物編集ページにアクセス。
4. WIPで途中保存する
5. 1.のページに再度アクセス。
6. ステータス「未着手」が表示される

## 期待される振る舞い

ステータス「着手」のまま

## 余談

「未着手」から提出物をWIPにすると「着手」に変わるため、
WIPで保存するたびに「未着手」<->「着手」が切り替わります
(着手中の他のプラクティスがない場合限定)

## 関連Issue

Ref: #5214

**Comment by goruchanchan** [comment]
本番環境にて動作確認しましたのでクローズします🙇‍♂️
