### ISSUE TITLE
文字列を選択した状態でURLをコピペするとリンク形式に展開される機能

### ISSUE THREAD

**Issue by yoshitsugu** [fjordllc/bootcamp#6385]
## 機能の説明

- GitHubやNotionなどのサービスにはあるのですが、文字列を選択した上で、URLをコピペするとリンク形式になります

- GitHubの例

https://user-images.githubusercontent.com/748445/229649692-5712c2aa-f120-422e-a2ed-10048579fc3d.mp4

- Notionの例

https://user-images.githubusercontent.com/748445/229649827-6fe26cff-435e-4c3a-9623-af131fa3c937.mp4

## 何故この機能が必要なのか

- あるとちょっと便利です。

**Comment by machida** [comment]
@djkazunoko 

Markdownエディタはnpmモジュールを使ってるのですが、それにオプションを追加する方法があります。
https://github.com/fjordllc/bootcamp/pull/4424
このPRが参考になるかもです。

**Comment by komagata** [comment]
@yoshitsugu なるほどです、ありがとうございます〜。

**Comment by djkazunoko** [comment]
本番環境で動作確認ができましたので、closeいたします。
