### ISSUE TITLE
プラクティスにOGP画像を登録できるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6388]
プラクティスのフォームから OGP 画像を登録できるようにしたい。

<img width="1957" alt="貼り付けた画像_2023_04_04_17_36" src="https://user-images.githubusercontent.com/168265/229736163-cf6704bb-c386-469c-ac9b-8761d791cc42.png">

OGP 画像が登録されている場合、そのページの OGP image はその画像を設定する。
登録されていない場合はデフォルトのものを出す。

その画像は OGP として使うだけでなく、

<img width="906" alt="貼り付けた画像_2023_04_04_17_39" src="https://user-images.githubusercontent.com/168265/229737067-b9267023-c5f7-4daa-b338-2af72e7aa10c.png">

上記のように、概要ブロックの中で表示をしたい。
概要のブロックは以下の Issue で対応中。

https://github.com/fjordllc/bootcamp/issues/6376

---

## OGP画像は登録されているが、概要文が登録されていないとき

- OGP画像は登録されているものを表示する。
- プラクティスの概要ブロックは非表示。

## OGP画像は登録されていないが、概要文が登録されているとき

- OGP画像はデフォルトのものを表示する。
- プラクティスの概要ブロックは 画像無し で表示する。

## OGP画像は登録されていないが、概要文も登録されていないとき

- OGP画像はデフォルトのものを表示する。
- プラクティスの概要ブロックは非表示。

**Comment by machida** [comment]
@ymmtd0x0b
この Issue は、 
https://github.com/fjordllc/bootcamp/issues/6376
こちらの Issue の続きの Issue になるので、こちらもアサインさせていただきましたー

**Comment by ymmtd0x0b** [comment]
@machida 
ありがとうございます！こちらの Issue にも取り組ませて頂きます💪

**Comment by ymmtd0x0b** [comment]
@komagata @machida 
お疲れ様です！
今週リリースされたコチラの Issue の動作確認にメンターの権限が必要になりますので、以下の内容のチェックをお願いしたいです🙇‍♂️

## 確認内容

任意のプラクティスに対して...

1. 「 OGP画像のみ 」を登録します<br><div><ul><li>ログイン状態の詳細表示には、OGP画像は表示されません</li><li>未ログイン状態の詳細表示にも、OGP画像は表示されません</li><li>Twitter や Discord に貼り付けた場合は、登録したOGP画像がサムネイルとして表示されます</li></div><br>
2. 「 OGP画像 と 概要文 」を登録します<br><div><ul><li>ログイン状態の詳細表示には、概要欄と共にOGP画像は表示されます</li><li>未ログイン状態の詳細表示にも、概要欄と共にOGP画像は表示されます</li><li>Twitter や Discord に貼り付けた場合は、登録したOGP画像がサムネイルとして表示されます</li></div>

**Comment by komagata** [comment]
@ymmtd0x0b こちら本番環境で確認して問題ありませんでした〜。

**Comment by ymmtd0x0b** [comment]
@komagata 確認作業ありがとうございました🙇‍♂️

動作確認OKを頂いたのでcloseします！
