### ISSUE TITLE
ログインしていない状態でQ&Aページにアクセスしたときの meta description を設定。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6390]
現在、ログインをしなくでも、Q&A( questions/show ) にアクセスができる（ただし内容は見れない、以前はトップページにリダイレクトされてた）。ログインをしてない状態でQ&A( questions/show )  にアクセスしたときのmeta description を設定してください。

meta description の文章は、

```
オンラインプログラミングスクール「フィヨルドブートキャンプ」のQ&A「{タイトル}」のページです。
```

にしてください🙏

meta description の表示は meta-tags（ https://github.com/kpumuk/meta-tags ） を使ってます。

---

参考（似た作業の PR）
https://github.com/fjordllc/bootcamp/pull/6406

**Comment by ogawa-tomo** [comment]
本番環境で確認できたのでクローズします
