### ISSUE TITLE
ログインしていない状態でDocページにアクセスしたときの meta description を設定。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6391]
現在、ログインをしなくでも、Doc( pages/show ) にアクセスができる（ただし内容は見れない、以前はトップページにリダイレクトされてた）。ログインをしてない状態でDoc( pages/show ) にアクセスしたときのmeta description を設定してください。

meta description の文章は、

```
オンラインプログラミングスクール「フィヨルドブートキャンプ」のドキュメント「{タイトル}」のページです。
```

にしてください🙏

meta description の表示は meta-tags（ https://github.com/kpumuk/meta-tags ） を使ってます。

---

参考（似た作業の PR）
https://github.com/fjordllc/bootcamp/pull/6406

**Comment by machida** [comment]
参考
https://github.com/fjordllc/bootcamp/pull/6406

**Comment by syo-tokeshi** [comment]
@machida 
お疲れ様です。

> 現在、ログインをしなくでも、Doc( pages/show ) にアクセスができる（ただし内容は見れない

とありますが、
確かに本番環境では、ログインしてなくてもpages/showにアクセス出来ます
<img width="956" alt="スクリーンショット 2023-04-17 19 06 28" src="https://user-images.githubusercontent.com/54713809/232453979-82d9c376-9fa8-4064-8e48-fe9152e5ac8c.png">

ですが、開発環境では、アクセスが出来ないみたいです
<img width="804" alt="スクリーンショット 2023-04-17 19 07 37" src="https://user-images.githubusercontent.com/54713809/232454164-efd31b02-a8e5-41ea-90f6-d7651286bdb2.png">

なので、開発環境で確認出来るようにすることも含め

1. 開発環境でログイン無しで、本番環境と同じように、pages/showにアクセス出来るようにする
1. meta description を設定する

の二つが、このissueに含まれる、という認識でよろしいでしょうか？

**Comment by syo-tokeshi** [comment]
このように本番環境でmeta descriptionが表示されるのが確認できたのでcloseします
![スクリーンショット 2023-06-01 16 41 36](https://github.com/fjordllc/bootcamp/assets/54713809/b305bcb2-427f-4d1f-b0b0-ec18032f908f)
