### ISSUE TITLE
fjord chiceで完了しているユーザーを除外できるようにしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6394]
終わった人が残り続けている状態なので。

**Comment by machida** [comment]
:memo:
20ポイントを達成したら自動で外れるようにする。

**Comment by goruchanchan** [comment]
@komagata @machida こちらの Issue ですが、[fjord\-choice](https://github.com/Saki-htr/fjord-choice)に対して PR を出して、[fjord\-choice](https://github.com/Saki-htr/fjord-choice)を更新し、FBCアプリ内の[fjord\-choice](https://github.com/Saki-htr/fjord-choice)を更新するという流れで良いでしょうか？

**Comment by goruchanchan** [comment]
@komagata @machida 作業イメージですが fjord-choice アプリに下記のようなPRを出す認識で良いでしょうか？

[![Image from Gyazo](https://i.gyazo.com/e722193002037d65b578fd2c7414671a.png)](https://gyazo.com/e722193002037d65b578fd2c7414671a)

**Comment by komagata** [comment]
@goruchanchan 

> @komagata @machida こちらの Issue ですが、[fjord-choice](https://github.com/Saki-htr/fjord-choice)に対して PR を出して、[fjord-choice](https://github.com/Saki-htr/fjord-choice)を更新し、稼働している fjord-choice アプリを更新するという流れで良いでしょうか？

はい。

> @komagata @machida 作業イメージですが fjord-choice アプリに下記のようなPRを出す認識で良いでしょうか？

はい。

管理者アカウントはアカウント名が`komagata` or `machida` かどうかみたいな決め打ちで大丈夫です。設定ファイルでそのアカウント名を決められると良いと思います。

**Comment by goruchanchan** [comment]
下記PRにて本番環境にて動作確認できましたのでクローズします🙇‍♂️

https://github.com/Saki-htr/fjord-choice/pull/210#issuecomment-2050696336
