### ISSUE TITLE
カテゴリー作成でバリデーションのエラーメッセージが表示されない

### ISSUE THREAD

**Issue by wata00913** [fjordllc/bootcamp#6402]
## 概要

カテゴリー作成で必須項目に未入力がある場合、バリデーションメッセージが表示されません。

## 再現手順

1. 管理者権限を持つユーザーでログインする
1.  `admin/categories/new`にアクセスする
1. 「名前」または「URLスラッグ」を未入力にする
1. 「登録する」ボタンをクリックする

## 期待される振る舞い
以下のようなバリデーションのエラーメッセージが表示される。
`未入力項目`は「名前」または「URLスラッグ」
```
`未入力項目`を入力してください
```

## スクリーンショット
![Kapture 2023-04-06 at 13 57 21](https://user-images.githubusercontent.com/85052152/230275758-57a6188a-bfe2-4324-b097-5cd06af917e7.gif)

**Comment by ogawa-tomo** [comment]
こちら、本番環境で動作確認がとれましたのでクローズします。
https://github.com/fjordllc/bootcamp/pull/6470#issuecomment-1572511119
