### ISSUE TITLE
企業一覧に企業の合計数の表示が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6405]
どのくらいの企業が使ってるんですか？と数を聞かれることが多いため。

<img width="898" alt="スクリーンショット 2023-04-08 16 31 15" src="https://user-images.githubusercontent.com/16577/230709505-51a849be-ae48-4668-9705-f5289f400e90.png">

**Comment by syo-tokeshi** [comment]
このように本番環境で企業一覧に企業の合計数が表示されるのが確認できたのでcloseします
![スクリーンショット 2023-06-01 16 44 37](https://github.com/fjordllc/bootcamp/assets/54713809/e075bb81-068d-413e-b4ec-766368ab5881)
