### ISSUE TITLE
請求書払いの人用のフラグを持ちたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6410]
現在、企業研修で使っている一部のユーザーはカード登録はないが、請求書払いにししている。
請求書払いをしているユーザーの情報がDBに無いので集計ができない。
そのためのカラムとユーザー情報変更ページから管理者のみ変更できるフラグが欲しい。

意味的には「請求書払い」というBooleanカラムが欲しい。

**Comment by yocchan-git** [comment]
@komagata さん
@machida さん

こちら、本番環境で確認する術がなくて...
お手隙で、ご確認いただけますでしょうか？🙏

### 変更確認方法
1. https://bootcamp.fjord.jp/admin/users にアクセスする
2. 請求書払いのユーザーの編集画面に移動する
3. 下スクロールで、画像のチェックボックスにチェックをいれる
4. 更新して、DBから修正したユーザーのデータを検索する
5. `invoice_payment`カラムが`true`になっているか確認する

[![Image from Gyazo](https://i.gyazo.com/a4b50cdd54b968d741215783d6b65a2f.png)](https://gyazo.com/a4b50cdd54b968d741215783d6b65a2f)

変更確認方法は一例ですので、やりやすい方法でよろしくお願いいたします🙇‍♂️

**Comment by komagata** [comment]
@yocchan-git 本番環境で確認しました。OKでした〜！

**Comment by yocchan-git** [comment]
ありがとうございます！closeさせていただきます
