### ISSUE TITLE
ブートキャンプアプリのVue.jsのファイルでcurrentUserIdがNumberとStringで型定義が混在しているのをNumberに統一したい

### ISSUE THREAD

**Issue by maimux2x** [fjordllc/bootcamp#6414]
## 概要

ブートキャンプアプリのVue.jsのファイルでcurrentUserIdがNumberとStringで型定義が混在しているのをNumberに統一したい

## 再現手順
`/app/javascript/components/announcements.vue` では `cirrentUserId` は`Number` で定義されている

```js
props: {
    title: { type: String, required: true },
    currentUserId: { type: Number, required: true }
  },
```

`app/javascript/products.vue` など他の複数のコンポーネントではcurrentUserIdは `String` で定義されている

```js
props: {
    title: { type: String, required: true },
    selectedTab: { type: String, required: true },
    isMentor: { type: Boolean, required: true },
    currentUserId: { type: String, required: true },
    checkerId: { type: String, required: false, default: null },
    displayUserIcon: { type: Boolean, default: true }
  },
```

currentUserIdが `String` で定義されているコンポーネントは以下です。

 - app/javascript/comments.vue
 - app/javascript/company-products.vue
 - app/javascript/product_checker.vue
 - app/javascript/product.vue
 - app/javascript/products.vue
 - app/javascript/components/question-page.vue
 - app/javascript/components/user-recent-products.vue
 - app/javascript/check.vue
 - app/javascript/components/comments.vue

上記のようにcurrentUserIdは複数のコンポーネントで利用されていますが、例えば提出物の担当者を処理しているコンポーネントでは
IDの比較に == を使用しているため、checkerID(Number)とcurrentUserId(String)の比較ができていることが分かりました。

```js
// product_checker.vue
button(
  v-if='!checkerId || checkerId == currentUserId',
  :class='["a-button", "is-block", id ? "is-warning" : "is-secondary", checkableType ? "is-sm" : "is-sm"]',
  @click='checkInCharge')
  i(
    v-if='!checkerId || checkerId == currentUserId',
    :class='["fas", productCheckerId ? "fa-times" : "fa-hand-paper"]',
    @click='checkInCharge')
```

## 期待される振る舞い

ID同士の比較を異なるデータ型で判定するのではなく、`Number` 同士を比較した方が良いと思います。
currentUserIdがコンポーネントによって `Number` か `String` かが混在していると今後の実装でもどちらが適切か判断に迷ってしまうと思うため、`Number` に統一し、影響箇所を修正した方が良いと考えています。

## スクリーンショット

なし

## 環境

全環境
## 関連Issue

なし

**Comment by ymmtd0x0b** [comment]
@komagata @machida 
お疲れ様です！
今週リリースされたコチラの Issue の動作確認にメンター権限が必要ですので、以下の項目のチェックをお願いしたいのですがよろしいでしょうか？🙇‍♂️ 

---

## チェック項目

各項目の画像が多くそのまま表示すると見辛いため折りたたんでいます。

### 表示の確認

以下の各画面が正常に表示される＋ 検証機能のConsole にエラーが表示されない事をそれぞれ確認して下さい。

<details><summary>提出物一覧 / <a href="https://bootcamp.fjord.jp/products">リンク</a></summary><p>※アクセス権が無いので画像は開発環境のモノになります。作業時は実際の画面に読み替えて下さい。</p><img src="https://github.com/fjordllc/bootcamp/assets/95903475/414b49a3-c83e-46b8-aec5-6f63786006a2" width="500"></details>

<details><summary>提出物詳細 / <a href="https://bootcamp.fjord.jp/products/14952">リンク</a> ※右枠は"提出物タブ"をクリックして下さい</summary><p>※右枠の表示権が無いので画像は開発環境のモノになります。作業時は実際の画面に読み替えて下さい。</p><img src="https://github.com/fjordllc/bootcamp/assets/95903475/5cbbd0cf-db69-457a-ac39-7510d5c991e7" width="500"></details>

<details><summary>企業所属の研修生の提出物一覧 / <a href="https://bootcamp.fjord.jp/companies">リンク</a></summary><p>※個人情報に係る部分なので、念の為リンクは一覧表示・画像は開発環境のモノになります。作業時は任意の企業の提出物一覧へ手動でアクセスして確認をお願いします。</p><img src="https://github.com/fjordllc/bootcamp/assets/95903475/89a4ee09-d406-462c-8859-c97b0931558b" width="500"></details>


<details><summary>※１：ブラウザ検証機能の Consoleタグ をアクティブにした画像</summary><img src="https://github.com/fjordllc/bootcamp/assets/95903475/b01cb822-5fd3-4c63-bca5-c090ec71a89c" width="500"></details>


### 動作の確認
以下の各操作が正常に動作する＋ 検証機能のConsole にエラーが表示されない事をそれぞれ確認して下さい。<br><details><summary>担当ボタンのクリック動作 ( 提出物一覧 )</summary><p>※アクセス権が無いため画像は開発環境下のものになります。作業時は実際の画面に読み替えて下さい。</p><ol><li><a href="https://bootcamp.fjord.jp/products">提出物一覧</a> へアクセス </li><li> 『 システム開発おかわりの提出物 ymmtd0x0b (ヤマモト) 』の <code>担当するボタン</code> をクリックする      <table><tr><td>Before</td><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/77e0b65a-d06e-41ce-b558-f5699658a2ef" width="500"></td></tr><tr><td>After</td><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/64bf37d2-7058-40f4-86b5-384a13a3ffa0" width="500"></td></tr></table></li><li>自分の担当タブ をクリック <table><tr><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/a2f1b573-d2cd-4e52-b1c5-568aa6e4824f" width="400"></td></tr></table></li><li> 『 システム開発おかわりの提出物 ymmtd0x0b(ヤマモト)  』が存在することを確認      <table><tr><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/75ecabb0-0ec8-4c53-ac54-e8eb0ec0fece" width="500"></td></tr></table></li><li><code>担当から外れるボタン</code> をクリックする      <table><tr><td>Before</td><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/64bf37d2-7058-40f4-86b5-384a13a3ffa0" width="500"></td></tr><tr><td>After</td><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/77e0b65a-d06e-41ce-b558-f5699658a2ef" width="500"></td></tr></table></li><li> 画面をリロードすると『 システム開発おかわりの提出物 ymmtd0x0b(ヤマモト)  』が表示されない事を確認      <table><tr><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/7ff72cb8-5ee4-4165-bbc3-e3cfdf174deb" width="500"></td></tr></table></li></ol></details><details><summary>担当ボタンのクリック動作 ( 提出物詳細 )</summary><p>※アクセス権が無いため画像は開発環境下のものになります。作業時は実際の画面に読み替えて下さい。</p><ol><li> <a href="https://bootcamp.fjord.jp/products/16422">システム開発おかわりの提出物 ymmtd0x0b(ヤマモト)</a> へアクセス </li><li> 画面中段の <code>担当するボタン</code> をクリックする      <table><tr><td>Before</td><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/6a27a612-a755-4d0e-8b43-fa0295638ac5" width="350"></td></tr><tr><td>After</td><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/1a1d0fd6-54f7-4db1-a049-0c9b6fe6b0c9" width="350"></td></tr></table></li><li><a href="https://bootcamp.fjord.jp/products/self_assigned">自分の担当提出物一覧</a> へアクセス </li><li> 『 システム開発おかわりの提出物 ymmtd0x0b(ヤマモト) 』が存在することを確認      <table><tr><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/435aa11f-87f3-4cad-98ab-beda949c8cf9" width="500"></td></tr></table></li><li> 再度、<a href="https://bootcamp.fjord.jp/products/16422">システム開発おかわりの提出物 ymmtd0x0b(ヤマモト)</a> へアクセス </li><li> 画面中段の <code>担当から外れるボタン</code> をクリックする      <table><tr><td>Before</td><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/1a1d0fd6-54f7-4db1-a049-0c9b6fe6b0c9" width="350"></td></tr><tr><td>After</td><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/6a27a612-a755-4d0e-8b43-fa0295638ac5" width="350"></td></tr></table></li><li> 再度、<a href="https://bootcamp.fjord.jp/products/self_assigned">自分の担当提出物一覧</a>  へアクセスし、『 システム開発おかわりの提出物 ymmtd0x0b(ヤマモト) 』が表示されない事を確認      <table><tr><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/7ff72cb8-5ee4-4165-bbc3-e3cfdf174deb" width="500"></td></tr></table></li></ol></details><details><summary>メンターがコメントすると担当者になる</summary><p>※アクセス権が無いため画像は開発環境下のものになります。作業時は実際の画面に読み替えて下さい。</p><ol><li><a href="https://bootcamp.fjord.jp/products/16422">システム開発おかわりの提出物 ymmtd0x0b(ヤマモト)</a> へアクセス </li><li> 画面下段の <code>コメントフォーム</code> から任意のコメントを送信する      <table><tr><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/c4205ff3-825a-4109-84e2-db9e10c200c8" width="500"></td></tr></table></li><li><a href="https://bootcamp.fjord.jp/products/self_assigned">自分の担当提出物</a> へアクセス </li><li> 『 システム開発おかわりの提出物 ymmtd0x0b(ヤマモト) 』が存在することを確認      <table><tr><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/de619425-7f2f-4ea3-b5ff-258204442dd4" width="500"></td></tr></table></li></ol></details><details><summary>企業の日報一覧上にある日報オプション表示</summary><p>※個人情報に係る部分なので、画像は開発環境下のものになります。作業時は実際の画面に読み替えて下さい。</p><ol><li><a href="https://bootcamp.fjord.jp/companies/1/reports">企業所属の全ユーザーの日報一覧</a> へアクセス </li><li>  自身の日報の右上に `…` が表示されいる事を確認      <table><tr><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/b6626ba5-8af0-4245-8b78-22b6aa25ea7f" width="500"></td></tr></table></li><li> `…` をクリックして、内容変更とコピーが表示される事を確認      <table><tr><td><img src="https://github.com/fjordllc/bootcamp/assets/95903475/c162b0fd-1af1-4777-9636-43f105c8aee7" width="500"></td></tr></table></li></ol><p>※日報一覧が２重に表示されていますが、この件はバグ報告済みです [#6638](https://github.com/fjordllc/bootcamp/issues/6638)</p></details>

**Comment by komagata** [comment]
@ymmtd0x0b 上記の動作を本番環境で確認しました。OKでした〜。

**Comment by ymmtd0x0b** [comment]
@komagata 項目が多く大変だったと思いますが、確認作業ありがとうございました🙇‍♂️

**Comment by ymmtd0x0b** [comment]
本番環境での動作確認が取れましたので、Close します！
