### ISSUE TITLE
ブログ記事のサムネイル画像を 1200px ✕ 630px にシステム側で強制したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6415]
- 拡大、縮小のルールは以下。
    - 重要なポイントは、黒や白で埋めるなどはしないで、1200px * 630px いっぱいに画像が埋まるようにする点。
- ~リサイズした画像の拡張子をWebPにする。~
    - これは別Issueにすることにしました。

---

<img width="500" alt="image" src="https://user-images.githubusercontent.com/168265/232405294-547ab7dc-8a36-486f-bfa5-0665b46fe5e7.png">

この場合、以下のように拡大する。

<img width="920" alt="image" src="https://user-images.githubusercontent.com/168265/232405494-8d2bcb5b-40af-43b4-a1b9-d5ab3a331643.png">

このように、黒や白で埋めるなどはせず、1200px * 630px いっぱいに画像が埋まるようにする。

<img width="955" alt="image" src="https://user-images.githubusercontent.com/168265/232405902-4c8405c4-e289-4c59-aa5a-129627e4e9df.png">

---

1000px * 2000px の場合、以下のように拡大する。

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/168265/232406285-5075f189-0e0b-4bb1-a080-c795f7766fec.png">

拡大した画像の真ん中部分で切り抜く。

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/168265/232406482-6f4bb1b0-148d-44ee-a12e-ff23e7232d49.png">

**Comment by machida** [comment]
今回はブログのサムネイルの対応ですが、今後、他のページでもOGP画像用の画像のリサイズにこのルールを使います。

- 他のページでもこの画像リサイズのルールは使う。
- 他のページでも使うが、全ての目的は共通していて、OGP画像用の画像の生成のためである。

上記を考慮していただけたらと思います。

**Comment by wata00913** [comment]
@machida 
お疲れさまです！

仕様の確認をさせて頂きたいと思います。🙇‍♂️
下の見出し「画像の拡大・縮小のルール」にて、拡大・縮小のルールを記載しましたが、この内容で間違いないでしょうか？

### 画像の拡大・縮小のルール
※前提： 元画像の横、縦のピクセル数を(w, h)とします。拡大・縮小後の画像の横、縦のピクセル数を(w’, h’)とします。

1. 拡大・縮小したときに、横または縦がOGPの画像サイズを超えても問題はない。（サイズが超えても中心から「1200 * 630」で切り抜くため。）

1. 拡大の場合
    - w ≥ 1200、h < 630の場合
        - h’ = 630にし、w’は変形前のアスペクト比を維持して拡大。
    - w < 1200、h ≥ 630の場合
        - w’ = 1200にし、h’は変形前のアスペクト比を維持して拡大。
    - (w, h)のどちらとも(1200, 630)より小さい場合
        - w’ = 1200または、h’ = 630にする。片方は、変形前のアスペクト比を維持した状態で拡大する。ただし、片方のピクセル数がOGP画像のサイズを超える必要がある。
        - 例えば、(w, h) = (500, 500)の場合、(w’, h’) = (1200, 1200)。
            - まず、w’=1200にする。片方のh’はアスペクト比を維持したまま拡大するのでh’ = 1200。h’=630にする場合、w’=630でOGP画像のサイズを超えないためh' = 630で拡大操作は出来ない。
1.  縮小の場合
    - (w, h)のどちらとも(1200, 630)より大きい場合
        - w’ = 1200または、h’ = 630にする。片方は変形前のアスペクト比を維持した状態で縮小する。ただし、片方のピクセル数がOGP画像のサイズを下回らない必要がある。
        - 例えば、(w, h) = (1500, 700)の場合は、(w’, h’) = (1350, 630)。
            - まず、h’ = 630にする。片方のw’はアスペクト比を維持したまま縮小するのでw’ = 1350。w’ = 1200にする場合、h’ = 560でOGP画像のサイズを下回るためw'=1200で縮小操作は出来ない。

**Comment by wata00913** [comment]
@machida 
>そのルールでバッチリですー🙆‍♂️

確認して頂きありがとうございます！😀

**Comment by wata00913** [comment]
@machida 
お疲れさまです！

今回のIssueの対応で、サムネイル画像登録の説明文を`修正後の説明文`にて修正してみました。
こちらの説明文で問題ないでしょうか？

- 修正前の説明文
    
    ```
    ここにアップロードした画像が、TwitterでTweet、Facebookで投稿した際に表示される画像として使われます。
    画像サイズは必ず 1200px × 630px でお願いします。
    ```
    
- 修正後の説明文
    
    ```
    ここにアップロードした画像が、TwitterでTweet、Facebookで投稿した際に表示される画像として使われます。
    画像サイズが 1200px x 630px でない場合は、登録時に自動で 1200px x 630px に加工されます。
    ```

よろしくお願いします🙇‍♂️

**Comment by machida** [comment]
@wata00913 
ありがとうございます！それでお願いしますー

**Comment by machida** [comment]
📝 
https://github.com/fjordllc/bootcamp/pull/6483
この続きの作業をお願いします。

**Comment by reckyy** [comment]
@machida 
お疲れ様です！

一応念のために、作業の方針が合っている確認させてください🙏
以下の方針であっていますでしょうか。

wataさんがリサイズの処理をモジュール化していたが、 `resize_to_fill`オプションが見つかったため作成されたモジュールを全て削除し、`resize_to_fill`オプションを用いたリサイズ方法に切り替える。

**Comment by komagata** [comment]
@reckyy 

> 1. 念のために、作業の方針が合っているか確認させてください🙏
> 以下の方針であっていますでしょうか。

はい。

> 2. レビューはもう一度チームメンバーを挟む or komagataさんにそのままレビュー依頼するかどうか。

内容がだいぶ変わるのでチームメンバーレビューを入れてください〜。

**Comment by reckyy** [comment]
@komagata 
こちら、新しくブランチを切ってPR作成してもいいでしょうか？

**Comment by komagata** [comment]
@reckyy はい、大丈夫です。
ただ、元のPRの中の議論を後から見た人が追える状態にしていただければと思います。

**Comment by reckyy** [comment]
@komagata @machida 
お疲れ様です。
こちら、ブログの画像のリサイズを本番環境で確認いただけないでしょうか。
よろしくお願いいたします。

**Comment by machida** [comment]
@reckyy 本番で確認しました:+1: OKでした:ok_man:

**Comment by reckyy** [comment]
@machida 
迅速なご確認ありがとうございます！！
closeします〜。
