### ISSUE TITLE
研修生の提出物個別ページに企業ロゴを表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6419]
<img width="827" alt="貼り付けた画像_2023_04_12_12_41" src="https://user-images.githubusercontent.com/168265/231343421-af3d52ec-594d-4a99-9a1a-a021c10f4dbb.png">

研修生というユーザーロールのユーザーの提出物の場合、ここに企業ロゴを表示。

**Comment by machida** [comment]
日報にはロゴが表示されてるので、それが参考になるかもです。

**Comment by syo-tokeshi** [comment]
本番環境での確認が取れましたのでcloseします🙇‍♂️
