### ISSUE TITLE
[退会]休会中に三ヶ月後に退会にしないフラグが欲しい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6424]
https://github.com/fjordllc/bootcamp/issues/6423
こちらで休会中から3ヶ月後に自動で退会する機能の実装を進める。

この機能の追加機能で、3ヶ月後に退会にしないフラグを作り、それにチェックが入ってるユーザーは休会中から3ヶ月経っても自動で退会しないようにする。このフラグの編集は管理者だけが行えるようにする。

このフラグは研修先の企業の案件の都合などで3ヶ月以上休会する場合に使用する。

**Comment by ogawa-tomo** [comment]
@machida @komagata 
フラグを操作する画面の仕様について確認させてください:bow:

## 操作する場所について
管理ページのユーザー登録情報変更ページ（`/admin/users/:id/edit`）に以下のように仮実装してみました。ユーザーステータスを操作する欄の下に「自動退会設定」という欄を新たに設け、そこでチェックボックスを操作できるようにしています。
![image](https://user-images.githubusercontent.com/46841037/236650141-c230584f-7eb7-4a4f-b5e8-2cffaa42d71a.png)
以上が仮案ですが、操作する場所や文言について修正・追加などありましたらご教示ください。

## チェックボックスの文言について
上記に含まれていることですが、チェックボックスの文言に少し悩んでいます。

上記の仮案だとチェックボックスには「～自動退会しない」と表示しています。
これは、「自動退会する」という状態をデフォルトと考え、チェックを入れたときだけ「自動退会しない」という特殊な状態に遷移することとなり、これはこれで素直な実装だと思います。
その一方で、「～自動退会しない」というチェックが外れている状態では、「～自動退会しないことはない」→「自動退会する」という意味になり、二重否定のようになって若干分かりにくい気もします。

二重否定を避けるという意味では、下記画像のように、チェックボックスとしては「自動退会する」と表示し、チェックを外すと自動退会しなくなる、というのも一案ではあると思いました。

![image](https://user-images.githubusercontent.com/46841037/236650372-f8f3a7cd-0980-40de-8b71-374c1c6270b0.png)

どちらの案がよろしいでしょうか？

**Comment by machida** [comment]
@ogawa-tomo

確認ありがとうございます！！

> 「～自動退会しない」

で、いきたいと思います。
理由は、ほとんどのユーザーにはこのチェックを入れることはないので、チェックが入ってるときに目立つようにするためです。

**Comment by ogawa-tomo** [comment]
@machida 
管理者としてそちらのほうが分かりやすいということで、承知しました！

一応再度確認なのですが、チェックボックスを表示する場所についても上記の方針でよいでしょうか？（「自動退会設定」という欄を新たに設け、そこに表示）

**Comment by machida** [comment]
はい！その表示でお願いします🙏

**Comment by machida** [comment]
@ogawa-tomo こちら、確認が遅れてすいません。今月中に結果を出します🙏

---

📝 
https://bootcamp.fjord.jp/users/1685
このユーザーで2023/12/26日に退会にならずに休会のままでいるかを確認。
休会のままだったらOK。

**Comment by komagata** [comment]
@ogawa-tomo こちら完了でしたらCloseお願いします〜

**Comment by ogawa-tomo** [comment]
@komagata @machida 
反応遅くなりすみません、クローズします！ご確認ありがとうございます:bow:
