### ISSUE TITLE
チャットのお知らせグループの通知で流している新メンバー参加のお知らせの表示を変更したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6425]
<img width="560" alt="貼り付けた画像_2023_04_12_16_37" src="https://user-images.githubusercontent.com/168265/231386700-e7b2c6f3-e89d-4cbc-bde6-a11b73e014f7.png">

この部分に名前が表示されているので、アカウント名を表示するように変更したい。

**Comment by YukiWatanabe824** [comment]
@machida
お疲れさまです！
念のため確認になりますが「アカウント名」はFJORDBOOTCAMPでのアカウント名でよろしいでしょうか？

**Comment by machida** [comment]
@YukiWatanabe824 はい！FBCのアカウント名でお願いします。

**Comment by YukiWatanabe824** [comment]
了解しました！ありがとうございます！

**Comment by YukiWatanabe824** [comment]
こちら本番環境で確認が取れましたのでCloseいたします
