### ISSUE TITLE
チャットに投稿される明日開催のイベント一覧の表示を変えたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6457]
現在、このように表示されている。

<img width="583" alt="貼り付けた画像_2023_04_19_13_58" src="https://user-images.githubusercontent.com/168265/232970956-2684d900-23ec-42e0-8b96-ecdc0563b816.png">

イベントが2つある場合、このように2回繰り返されているのを、

```
⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️
【イベントのお知らせ】
明日 04月20日（木）に開催されるイベントです！
--------------------------------------------
{イベント1}
時間: {開始時間〜終了時間}
詳細: {URL}
--------------------------------------------
⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️

⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️
【イベントのお知らせ】
明日 04月20日（木）に開催されるイベントです！
--------------------------------------------
{イベント2}
時間: {開始時間〜終了時間}
詳細: {URL}
--------------------------------------------
⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️
```

以下のように表示をまとめ、仕様変更も追加する。

- `⚡️` の数を変更（スマホのときに折り返されるので）
- `------------------------------`の長さを変更（スマホのときに折り返されるので）
- 最後のイベントの下の `------------------------------` は表示しない
- 明日だけでなく、今日のイベント一覧も表示する

```
⚡️⚡️⚡️イベントのお知らせ⚡️⚡️⚡️

< 今日 (04/20 月) 開催 >

{イベント1}
時間: {開始時間〜終了時間}
詳細: {URL}

{イベント2}
時間: {開始時間〜終了時間}
詳細: {URL}

------------------------------

< 明日 (04/21 火) 開催 >

{イベント1}
時間: {開始時間〜終了時間}
詳細: {URL}

{イベント2}
時間: {開始時間〜終了時間}
詳細: {URL}

⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️
```

**Comment by machida** [comment]
関連 Issue
https://github.com/fjordllc/bootcamp/issues/6486

**Comment by syo-tokeshi** [comment]
@machida 
本日MTGでお伝えして頂いように実装を変更したいのですが、

**本日(または明日)は祝日のため、OO(イベント名が入る)をお休み致します。**
という文言を、どのように表示しましょうか？

現在のDiscordへの通知は、このような見た目になっております
<img width="537" alt="スクリーンショット 2023-05-31 18 34 59" src="https://github.com/fjordllc/bootcamp/assets/54713809/97e5263a-7cc6-4657-9ff4-919de0ad7722">

こういうフォーマットでお伝えして頂けたら嬉しいです🙇‍♂️

```
⚡️⚡️⚡️イベントのお知らせ⚡️⚡️⚡️

< 今日 (04/20 月) 開催 >

{イベント1}
時間: {開始時間〜終了時間}
詳細: {URL}

{イベント2}
時間: {開始時間〜終了時間}
詳細: {URL}

------------------------------

< 明日 (04/21 火) 開催 >

{イベント1}
時間: {開始時間〜終了時間}
詳細: {URL}

{イベント2}
時間: {開始時間〜終了時間}
詳細: {URL}

⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️
```

**Comment by machida** [comment]
以下のようにお願いします。
 `⚠️` は ⚠️ この絵文字でお願いします。

```
⚡️⚡️⚡️イベントのお知らせ⚡️⚡️⚡️

< 今日 (04/20 月) 開催 >

{イベント1}
時間: {開始時間〜終了時間}
詳細: {URL}

{イベント2}
時間: {開始時間〜終了時間}
詳細: {URL}

~~~

⚠️ {イベント3} 、
⚠️ {イベント4} 、
⚠️ {イベント5} 
はお休みです。

------------------------------

< 明日 (04/21 火) 開催 >

{イベント1}
時間: {開始時間〜終了時間}
詳細: {URL}

{イベント2}
時間: {開始時間〜終了時間}
詳細: {URL}

~~~

⚠️ {イベント3} 、
⚠️ {イベント4} 、
⚠️ {イベント5} 
はお休みです。

⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️
```

**Comment by syo-tokeshi** [comment]
@machida 
お疲れ様です。
現在このような見た目になっています。
![スクリーンショット 2023-06-01 11 43 19](https://github.com/fjordllc/bootcamp/assets/54713809/09f548fd-3417-48db-8647-b29d8d41430d)

この見た目でよろしいでしょうか？

**Comment by syo-tokeshi** [comment]
@machida 
こちらお聞きしたいのですが、
```
⚠️ {イベント3} 、
⚠️ {イベント4} 、
⚠️ {イベント5} 
はお休みです。
```

このような、最後の`、`は表示しない方が良いと思ってます。
- ⚠️ {イベント5} `、`

理由として、
- これを表示しなくても、別にユーザーは困らない
- このロジックを追加しなかったら複雑性が減るので、ない方が良い

なので、上記の写真のフォーマットでよろしいでしょうか？

**Comment by machida** [comment]
@syo-tokeshi あー、確かにいらないですね👍無しでお願いしますー
提案ありがとうございます！！

**Comment by syo-tokeshi** [comment]
@machida 
ありがとうございます。
またまた質問なのですが、
こうするとどうでしょうか？
[1]
![スクリーンショット 2023-06-01 12 15 30](https://github.com/fjordllc/bootcamp/assets/54713809/a99dc28b-1bdc-4ed6-bd85-08b13551d483)

この部分を無くしました🙇‍♂️
スッキリする気がするけど、1と2どっちが良いのか気になって連絡しました
[2]
![無くした](https://github.com/fjordllc/bootcamp/assets/54713809/6497b1e2-ba51-4f42-8201-7590ac759bbf)

**Comment by machida** [comment]
@syo-tokeshi ありがとうございます！区切り無しでお願いしますー👍

**Comment by syo-tokeshi** [comment]
~~あ、やっぱし最初の町田さんの提案の方が良い気がしてきました、、(区切り線の話です)~~

~~その方が「間(空間)が空いているので、別のものに見える」だからです。~~

~~デザインパターンで言う、近接(グループ化)ですかね？~~

ありがとうございます🙇‍♂️

上の文章考えていたのですが、

- ロジックは少なければ少ないほど良い(バグが減る)

とも思ったので、**区切り無し**で行きます！😊

**Comment by machida** [comment]
@syo-tokeshi 

> [質問]
> プログラムとデザインのバランスをとって
> 「プログラム&デザイン共に条件分岐をなるべく減らしてシンプルにする」
> って大事ですかね？😀
>
> 「条件分岐(OOの場合はOO)」が減れば減るほど、全部が上手く行く気がしてきました

プログラムとデザインにバランスは必要ないと僕は考えますー。
というのも、プログラムの問題は技術力でカバーできるからです。技術力が足りないため、デザインの部分でどこまで妥協するか、ということをバランスと呼ぶのであれば、理想はApple製品のように妥協はしたくないところではあります。

とはいえ、それは理想なので、リリースにボーダーを引く際は、問題が解決されているかどうかにあります。自作サービスでエレベーターピッチを作ってもらってますが、それと同様に、割り振られたIssue一つ一つにも、問題があり、解決策があり、今はその解決策が実装されていないから、ユーザーは仕方なく代替手段でその問題を無理やり解決したり、解決できなかったり、している現状があります。

https://bootcamp.fjord.jp/articles/60
こちらの記事にもそれに触れているので見てみてください。

**Comment by syo-tokeshi** [comment]
@machida 
かしこまりました🙇‍♂️
ご親切にありがとうございました🙇‍♂️

**Comment by syo-tokeshi** [comment]
Discordに通知が来ていることを確認できたのでcloseさせて頂きます🙇‍♂️
