### ISSUE TITLE
プラクティス一覧ページのユーザーアイコンに適切なクラスが付与されていない

### ISSUE THREAD

**Issue by ogawa-tomo** [fjordllc/bootcamp#6469]
## 概要

コードを見ると、プラクティス一覧ページでプラクティス進行中のユーザーを表示するアイコンには、ユーザーがアクティブかどうか（1ヵ月以内にログインがあるかどうか）に応じて`active`クラスか`inactive`クラスを付与しようとしています。
これがうまく機能しておらず、常に`inactive`クラスが付与されているようです。また、このクラスにはとくにスタイルが当たっていないようです。

このクラスが必要ならば適切にクラスとスタイルを付与したいですし、不要であれば関連コードを削除したいです。

## 再現手順

1. プラクティス一覧ページにアクセス
2. 開発者ツールでユーザーアイコンのクラスを表示する
3. `inactive`クラスが付与されている（明らかにアクティブなユーザーでも）
4. 開発者ツールでクラスを`active`に変更しても表示は変わらない

## 期待される振る舞い

アクティブなユーザのアイコンには`active`クラスが付与され、それに応じて表示が変化する
or
不要なコードは削除する

## スクリーンショット
![image](https://user-images.githubusercontent.com/46841037/233785737-ada5c258-5922-4a34-b7a8-19b6c74d17c8.png)

## 環境

 - OS: Windows10
 - ブラウザ: chrome
 - バージョン: 112.0.5615.138（Official Build）

## 関連Issue
下記のPRの作業中に発見しました。
https://github.com/fjordllc/bootcamp/pull/6468

## 調査したこと
クラスが適切に付与されていない原因は、以下の箇所でtypoしていることです。

https://github.com/fjordllc/bootcamp/blob/8d2c8e0f21a2b51ace429a9eb8624f831e0492d5/app/views/api/courses/practices/index.json.jbuilder#L14

クラスを実際に付与しているのは以下の箇所です。
https://github.com/fjordllc/bootcamp/blob/8d2c8e0f21a2b51ace429a9eb8624f831e0492d5/app/javascript/practice-user-icon.vue#L5-L8

**Comment by machida** [comment]
📝 
ここでの（プラクティス一覧ページでの） inactive active の class は使わないので、削除する。

**Comment by sochi419** [comment]
本番環境で確認ができたため、closeします。
