### ISSUE TITLE
日報ページの見出しの"日報"という文字と"日報作成"のボタンがずれている

### ISSUE THREAD

**Issue by yupa-eg** [fjordllc/bootcamp#647]
https://bootcamp.fjord.jp/reports の“日報“の文字と“日報作成“のボタンが他のページ(Q&A, プラクティス)と比べすこしズレています。
( Google Chrome 69.0.3497.100, MacBook Pro macOS Mojave 10.14 にて確認 )
![2018-11-23 8 58 21](https://user-images.githubusercontent.com/37173138/48924890-b75a7f80-ef00-11e8-81a8-634640272235.png)

**Comment by machida** [comment]
ありがとうございます！対応しました
