### ISSUE TITLE
WIPで保存中の提出物ページの「提出する」ボタンと「内容修正」ボタンの位置を逆にしたい

### ISSUE THREAD

**Issue by ogawa-tomo** [fjordllc/bootcamp#6471]
## 概要
バグというわけではないですが、いちユーザーの意見です。

WIPで保存中の提出物ページでは、「提出する」ボタンが左に、「内容修正」ボタンが右にあります。
![image](https://user-images.githubusercontent.com/46841037/233837763-da65909c-bda9-4fdf-b0b1-233f7b6d6b9f.png)

一方、提出物の編集ページでは、「提出する」ボタンは右にあり、「WIP」の保存ボタンが左にあります。つまり、「提出する」ボタンの位置が逆です。
![image](https://user-images.githubusercontent.com/46841037/233837780-3c345382-8524-42e2-a14d-b0e29072f7e2.png)

日報やQ&Aなど他の編集ページでも、「提出する」ボタンは右にあります。

提案としては、WIPで保存中の提出物ページでも「提出する」ボタンの位置は右側に揃えたいです。
現在は左側にあるので、私はうっかり未完成の提出物を提出しそうになったことが何度かあります。

いかがでしょうか？

**Comment by sochi419** [comment]
本番環境で動作がOKだったので、closeします。
