### ISSUE TITLE
研修生の相談部屋個別ページに企業ロゴを表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6475]
<img width="839" alt="貼り付けた画像_2023_04_25_16_41" src="https://user-images.githubusercontent.com/168265/234208208-2b401f02-4b47-4969-8e55-dd9f45663c88.png">

マークアップはすでに企業ロゴが表示されている日報個別ページ、提出物個別ページを参考にする。

**Comment by natsuto6** [comment]
本番環境で動作確認いただいたのでcloseします
