### ISSUE TITLE
Ruby on Railsのプラクティスのみ、日報が重複して表示される

### ISSUE THREAD

**Issue by kurosu66** [fjordllc/bootcamp#6477]
## 概要
Ruby on Railsのプラクティスのみ日報が重複して表示される

## 再現手順
1.ログイン後、サイドメニューの「プラクティス」にアクセス
2.Ruby on Railsのプラクティスの中から1つ選びアクセス
3.上部のタブの「日報」をクリック
4.重複して表示される日報がある

再現箇所のURL
https://bootcamp.fjord.jp/practices/146/reports

## 期待される振る舞い
日報が重複しない。1つの日報が1つ表示される

## スクリーンショット

![貼り付けた画像_2023_06_06_15_22](https://github.com/fjordllc/bootcamp/assets/168265/d7a3aaea-6fc2-4a17-a9fa-6c664b35ed5b)

## 環境

 - OS: macOS Ventura 13.2
 - ブラウザ: chrome バージョン: 112.0.5615.137（Official Build） （arm64）

## 関連Issue
なし

Ref: #関連Issue番号
なし

## その他
問題が再現するのはRuby on Railsのプラクティスのみで、Ruby on Railsのプラクティスには6.1版と7版があるため、その影響かもしれません。意図した挙動であればご放念ください。

**Comment by djkazunoko** [comment]
## バグの詳細

- 日報のプラクティス選択で、特定のプラクティスの別カテゴリー版(異なるカテゴリーに属する同一のプラクティス)を選択すると、プラクティスの日報一覧(`practices/{ID}/reports`)で日報が重複して表示される
  - Ruby on Rails(`category55`)の「Rails の基本を理解する」(`practice33`)
  - Ruby on Rails （Rails 6.1版）(`category6`)の「Rails の基本を理解する」(`practice33`)

![1](https://github.com/fjordllc/bootcamp/assets/65595901/962b4b06-c85d-4b04-93fa-fbbd39fa930a)

`/practices/33/reports`
![2](https://github.com/fjordllc/bootcamp/assets/65595901/1250b608-43ac-4d72-ade2-cdce1021e1a6)

**Comment by djkazunoko** [comment]
📝5/15質問タイム
- 「Ruby on Rails （Rails 6.1版）」(category6)を削除すればいいのでは？→❌
  - 「Railsでユーザーフォローを作る」(practice170)がこっちにしかないため却下
- 日報のプラクティス選択で別カテゴリー版を選択できないようにする→✅
  - 特定のプラクティスを選択したら、そのプラクティスの別カテゴリー版を選択できないようにする
  - 別のプラクティスは選択できる

**Comment by machida** [comment]
キャプチャの画像を差し替えました。

**Comment by djkazunoko** [comment]
📝6/7MTG
- 日報のプラクティス選択の表示形式を`[カテゴリー名][プラクティス名]`から`[プラクティス名]`に変更する

**Comment by djkazunoko** [comment]
本番環境で動作確認ができましたので、closeいたします。
