### ISSUE TITLE
コメントを削除・編集するとWatch中になってしまう

### ISSUE THREAD

**Issue by uchihiro04** [fjordllc/bootcamp#6480]
## 概要
Watchしていない状態でコメントを削除・編集するとWatch中になってしまいます。

お知らせ、提出物、日報、ドキュメント、イベント、定期イベントで上記不具合が発生します。質問（Q&A）への回答では上記不具合は発生しませんでした。

## 再現手順
1. 日報にアクセスする。
後の手順でコメントを投稿するため、自分が書いたかつ誰もコメントをしていない日報が良いと思います。
2. コメントを投稿し、リロードを行う。
3. Watchボタンを押し、日報のWatchを解除する。
4. コメントを編集または削除し、リロードを行う。
5. 日報がWatch中になっていることを確認する。
6. `/current_user/watches`にアクセスし、Watch中の一覧にコメントを削除した日報が存在することを確認する。

## 期待される振る舞い
Watchしていない状態でコメント※を編集・削除しても、Watch中にならないようにしたいです。

※お知らせ、提出物、日報、ドキュメント、イベント、定期イベントへのコメントを指します。

## スクリーンショット
![23042801](https://user-images.githubusercontent.com/77523896/235096715-8fe7207a-bdbf-4eff-93b1-b318338c160a.gif)

## 環境
 - OS: macOS Ventura 13.1
 - ブラウザ: chrome
 - バージョン: 112.0.5615.137（Official Build） （arm64）

**Comment by junohm410** [comment]
@komagata @machida 
お疲れ様です。
アサインいただいたこちらのIssueですが、調べてみた結果、現在はこちらのバグは解消されていると思われます。
以下、調査した内容をまとめます。

## 現在の状態
現在の`main`ブランチでIssueに記載の再現方法を実行しても、バグが再現しません。
※お知らせ、提出物、日報、ドキュメント、イベント、定期イベントへのコメントの全て（削除・更新の両パターン）で試しました。

> 日報にアクセスする。
後の手順でコメントを投稿するため、自分が書いたかつ誰もコメントをしていない日報が良いと思います。
コメントを投稿し、リロードを行う。
Watchボタンを押し、日報のWatchを解除する。
コメントを編集または削除し、リロードを行う。
日報がWatch中になっていることを確認する。
/current_user/watchesにアクセスし、Watch中の一覧にコメントを削除した日報が存在することを確認する。

### 再現を試みた際の挙動

#### 日報へのコメントの投稿→リロードまで
![BpJ6Zl4KHt](https://github.com/fjordllc/bootcamp/assets/128765400/cc3381c3-7231-4c88-a1b7-76590f06e6e1)

#### Watchの解除→コメントの削除→リロード
Watchは解除されたまま、バグは起きていない
`/current_user/watches`の中にも、削除した日報は入っていませんでした
![UEWngyPTuJ](https://github.com/fjordllc/bootcamp/assets/128765400/79608c2c-25fd-412d-9f20-66cb24c63cc0)




## 解消の原因
**→ このIssueが立ったあとにマージされた下のPRにおいて、問題点が修正されたから。**
- https://github.com/fjordllc/bootcamp/pull/6854

> 対象のコールバックは元々create時のみ呼ばれる処理だったが、コミット時に呼び出す変更を加えた際にafter_commitを指定していたため、createのみではなくupdateやdestroy時のコミットでも呼ばれるようになっていた。
( https://github.com/fjordllc/bootcamp/pull/6253/files#diff-3baef9453c5d8b6c8962ce9ff9ec6b570b2e9cbad934e9f95b6d217ff1029b07 で変更が加わった)
その結果、意図せずコールバックが呼ばれることにより、Commentモデルをdestroyする際に関連するProductモデルのcommented_atカラムをnullにしたいところを新たに値をセットしてupdateしてしまっていた。
意図しないカラムのupdateを防ぐため、本来の挙動であるCommentモデルのcreate_commit時にのみコールバックが呼ばれるようにした。

### なぜ上記の修正でなおるのか
このIssueの発起人であるuchihiroさんの日報を拝読したところ、このIssueの起票のタイミングでは、コメントを削除した際にコールバッククラスである`app/models/comment/after_create_callback.rb`内の`create_watch`メソッドが呼ばれていることがログから判明したようでした。

https://bootcamp.fjord.jp/reports/72175
https://bootcamp.fjord.jp/reports/72237

`create_watch`は、コメントに紐づく対象（日報、お知らせ等）に紐づいた新規`Watch`を作成・保存するメソッドです。

```rb
class Comment::AfterCreateCallback
  def after_commit(comment)
    if comment.commentable.class.include?(Watchable)
      create_watch(comment)
      notify_to_watching_user(comment)
    elsif comment.sender != comment.receiver
      Newspaper.publish(:came_comment, comment)
    end

# 中略

  def create_watch(comment)
    watchable = comment.commentable

    return if watchable.watches.pluck(:user_id).include?(comment.sender.id)

    @watch = Watch.new(
      user: comment.sender,
      watchable: watchable
    )
    @watch.save!
  end

```

このコールバックが、この時点では`after_commit`時に呼ばれるように設定されていたため、`create`時だけでなく`update`や`destroy`のコミットのタイミングでも呼ばれるようになっていたことが、このバグの原因と思われます。

https://github.com/fjordllc/bootcamp/pull/6854/commits/22abe606e04c07c1ee7aa839ae6ddd015d86ad66
↑こちらの修正により、`after_create_callback.rb`のコールバックの呼び出しが`create_commit`時に変更されたため、コメントの削除・更新のコミット時に`Watch`が作成・保存されなくなり、バグが解消した、ということになると思われます。

よって、本件はCloseして問題ないIssueかと思いますが、ご確認いただけますと幸いです。
よろしくお願いいたします🙏

**Comment by machida** [comment]
@junohm410 

調査ありがとうございます！！すでに解決されていること、なぜ解決されたかがよくわかりました。
念のため今後デグレを防ぐために日報だけでいいのでテストを書いていただきたいですー。
テストを追加したらクローズしたいと思います。

**Comment by junohm410** [comment]
@machida 
ご確認いただき、ありがとうございました！承知しました。
日報パターンでテストを追加するように取り組みます。
引き続き、よろしくお願いいたします🙏

**Comment by komagata** [comment]
@junohm410 詳細な説明ありがとうございます！

**Comment by junohm410** [comment]
> @junohm410
> 
> 調査ありがとうございます！！すでに解決されていること、なぜ解決されたかがよくわかりました。 念のため今後デグレを防ぐために日報だけでいいのでテストを書いていただきたいですー。 テストを追加したらクローズしたいと思います。

本件、テストのみ追加したPRがマージされましたので、上記のやりとりに則り、これでクローズとさせていただきます🙏
