### ISSUE TITLE
祝日非開催である定期イベント開催のお知らせがDiscordに通知されている

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#6486]
## 概要

祝日に開催しない定期イベントの開催通知がDiscordの#お知らせ チャンネルに通知されている
(スクリーンショット参照)

## 期待される振る舞い

`（祝日は休み）`になっている定期イベントを祝日前日に通知しない

## スクリーンショット

2023/5/3は憲法記念日のため開催しない

##### 通知されたイベント
<img width="423" alt="image" src="https://user-images.githubusercontent.com/69447745/235562871-93c6f886-0786-4978-96c9-f8f7c5331f9d.png">

##### 開催日時の設定
![image](https://user-images.githubusercontent.com/69447745/235562981-c429cf54-5f99-456b-93d3-548ddc520a1d.png)

**Comment by machida** [comment]
@syo-tokeshi 
https://github.com/fjordllc/bootcamp/issues/6457
こちらの Issue と一緒にこのバグも対応お願いしたいです。プルリクは一つにまとめてOKです。

**Comment by syo-tokeshi** [comment]
@machida 
かしこまりました🙇‍♂️

**Comment by syo-tokeshi** [comment]
Discordに通知が来ていることを確認できたのでcloseさせて頂きます🙇‍♂️
