### ISSUE TITLE
定期イベントの次回開催日が祝日を考慮していない

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#6487]
## 概要

定期イベント個別ページに表示している次回開催日が祝日休みの場合を考慮していない

スクリーンショットのケースでは5/2(火)に定期イベントページにアクセスしていますが、5/3(水 / 憲法記念日)が次回開催日となっています

## 期待される振る舞い

祝日休みの場合は、次回が非開催日であればスキップする
スクリーンショットのケースでは5/8を次回開催日にする

## スクリーンショット
スクリーンショット取得日は5/2です
![image](https://user-images.githubusercontent.com/69447745/235564152-7310d137-59e2-47ec-9454-6b7f05aa17a5.png)

**Comment by omochiumaiumai** [comment]
リリースと本番確認が完了したため、こちらのIssueはcloseします。
