### ISSUE TITLE
slim-lint の実行で出力されるようになったスタイル違反を修正して欲しい

### ISSUE THREAD

**Issue by ymmtd0x0b** [fjordllc/bootcamp#6496]
## 概要

rubocop-fjord のバージョンアップ( `0.2.0` ➜ `0.3.0` )に伴い、slim-lint の実行でスタイル違反が出力されるようになりました

現在は slim-lint の設定ファイルにて該当のスタイル違反をチェック項目から除外させる事で対応していますが、違反元のコード修正をお願いしたいです

## 期待される振る舞い

こちらの[コミット](https://github.com/fjordllc/bootcamp/pull/6370/commits/a194582f1d4a92be7a3d12782d0f57d48be15aa7)で`config/slim_lint.yml`に追加した除外ルールを削除した状態で `bundle exec slim-lint app/views -c config/slim_lint.yml` を実行してもスタイル違反が出力されなくなる

## 違反スタイルと該当ファイル

<details>
<summary>出力結果</summary>

app/views/admin/users/_nav.html.slim:6 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/admin/users/_sort_column.html.slim:3 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/admin/users/_sort_column.html.slim:3 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/admin/users/_sort_column.html.slim:3 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/application/_global_nav.slim:14 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/application/_page_tabs.html.slim:8 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/application/_page_tabs.html.slim:11 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/application/_page_tabs.html.slim:13 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/comments/_user_icons.html.slim:2 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/companies/users/_users_tabs.html.slim:6 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/events/_event.html.slim:47 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/events/_event.html.slim:58 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/generations/_users_tabs.html.slim:9 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/home/index.html.slim:14 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/home/index.html.slim:16 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/kaminari/_first_page.html.slim:3 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/kaminari/_last_page.html.slim:3 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/kaminari/_next_page.html.slim:3 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/kaminari/_page.html.slim:9 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/kaminari/_page.html.slim:9 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/kaminari/_page.html.slim:12 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/kaminari/_page.html.slim:12 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/kaminari/_prev_page.html.slim:3 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/notifications/_tabs.html.slim:12 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/products/self_assigned/_nav.html.slim:7 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/products/show.html.slim:7 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/products/show.html.slim:84 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/products/unchecked/_nav.html.slim:6 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/products/unchecked/_nav.html.slim:6 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/regular_events/_regular_event.html.slim:45 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/regular_events/_regular_event.html.slim:59 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/reports/show.html.slim:167 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/talks/_nav.html.slim:6 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/talks/show.html.slim:79 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:14 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:22 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:22 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:26 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:28 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:40 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:43 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:43 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:47 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:47 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:59 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:117 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_form.html.slim:117 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_metas.html.slim:49 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_nav.html.slim:9 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_nav.html.slim:18 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/_password_change.html.slim:17 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/companies/_users_tabs.html.slim:6 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/practices/_completed_practices.html.slim:7 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/practices/_completed_practices.html.slim:7 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/users/show.html.slim:86 [W] RuboCop: Style/HashSyntax: Omit the hash value.
app/views/welcome/_mentors.html.slim:9 [W] RuboCop: Style/HashSyntax: Omit the hash value.

</details>

## 注意
上記の折りたたみ要素に除外した内容を添付していますが、これは Issue 作成時の実行結果になります。Issue に取り組む際は事前に設定ファイルに追記されている除外ルールを削除し、`bundle exec slim-lint app/views -c config/slim_lint.yml`を実行して最新の状態を把握した方が良いと思われます

## 関連Issue

Ref: #6495

**Comment by machida** [comment]
1 〜 6 の Issue に分けました。少しずつ対応していきたいと思います。
