### ISSUE TITLE
卒業させることができてしまう問題

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6497]
## 概要

**管理者でなくても任意のユーザーを卒業させることができる**。

## 動作確認方法
ローカル環境とステージング環境で確認しました。

1. 任意の一般ユーザーでログイン。（kimuraで実験）
2. ユーザー一覧ページから、他の任意の卒業させたい現役生ユーザー（ここではtake8）のページに入って、現役生であることをを確認。また、URLを見てユーザーIDを確認してメモする。（ここでは、ID: 1038099145）

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOElFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce5e04d5c5c57af95973fb15b724053933f3093d/image.png)

3. 自分の日報ページから、適当な日報を開いて、「内容修正」を押す。
4. ブラウザの開発者ツールを開いて、「内容変更」ボタン周辺のソースを開く。

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d82c5f67858e263a4568ada913ef84ece5eaddb0/image.png)

5. formタグの`action="/reports/{レポートID}"`を、`action="/users/{卒業させたいユーザーのID}/graduation`に変更

（ここでは、`/users/1038099145/graduation`に変更）

before

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f71de6cced47114bda5635c282f12e2d38ffee66/image.png)

after

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGNFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11e45506e798cf8a2cdd6d9c1803e56f84ccc359/image.png)

6. 画面の「内容変更」ボタンを押す。

7. （トップ画面にリダイレクトされ、「管理者としてログインしてください」の警告が出る）

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGdFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c22387432896d5e428eeaa420dfd5a60087415a8/image.png)

8. 再びユーザーページにアクセスし、「卒業生」に先ほどのユーザーがいることを確認

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGtFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f989a9851ffbb079889ae5d0f79b7d684e62d98f/image.png)

9. ユーザーページにアクセスし、たしかに卒業生になっていることを確認

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG9FQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7320d4c50f284f9a252ffecefda02fcad78832d/image.png)

## 原因

ユーザーの退会処理は、`GraduationController`が担っています。このコントローラでは、とくに管理者権限のチェックや、卒業するユーザー自身がログインしていることのチェックなどを行っていません。単純に、URLのパスで渡されたIDのユーザーを卒業させる処理をしています。
https://github.com/fjordllc/bootcamp/blob/e892fda0c5da128a9e27e94e9a3b03bce7044355/app/controllers/graduation_controller.rb
そのため、Railsの`AuthenticityToken`のチェックさえパスしてしまえば、ユーザーを卒業させるリクエストを送ることができてしまうと思われます。

**Comment by YukiWatanabe824** [comment]
@komagata 
お疲れ様です。
こちら詳細記入お願いいたします🙇‍♀️

**Comment by machida** [comment]
@YukiWatanabe824 詳細を書きましたー

**Comment by komagata** [comment]
@machida 詳細の記入ありがとうございます。助かります〜！

**Comment by YukiWatanabe824** [comment]
@machida 
ありがとうございます！！

**Comment by YukiWatanabe824** [comment]
@komagata @machida
お疲れ様です。
こちらのIssueで質問です。
本件のような「ユーザーによる想定外の操作」に対してテストを書くものでしょうか？
bootcampだと想定外の操作に対するテストが無いように思いました(調べた限りですが)ので質問いたしました。

**Comment by YukiWatanabe824** [comment]
@komagata @machida 
お疲れさまです。
こちら、本番環境でもし卒業させてしまった際の復帰方法がないため、確認をお願いしても良いでしょうか？
確認手順は #6546 に記載のとおりです。
よろしくお願いいたします。

**Comment by machida** [comment]
@YukiWatanabe824 連絡ありがとうございます！
https://bootcamp.fjord.jp/users/997
こちらのユーザーを卒業できるか確認お願いします🙏
テストユーザーなので、万が一卒業させてしまえても問題ないですー

**Comment by YukiWatanabe824** [comment]
@machida 
了解しました！
確認してみます！

**Comment by YukiWatanabe824** [comment]
バグが発生しないことが確認できましたのでcloseいたします！

@machida 
対応ありがとうございました！
