### ISSUE TITLE
管理画面から退会処理を行ったときクレジットカードの定期支払いが停止されていない

### ISSUE THREAD

**Issue by ogawa-tomo** [fjordllc/bootcamp#6498]
## 概要
通常、ユーザーが退会する際には、クレジットカードの定期支払いが停止されます。
しかしながら、管理画面のユーザー編集ページからユーザーの退会処理を行ったとき、この処理を行っていないように見えます。

## 再現手順

1. ログインなしでユーザーの新規登録ページにアクセスし、適当にフォームを入れてユーザー登録をする
    - クレジットカードにはテスト用のカードを入れる
      - https://stripe.com/docs/testing?testing-method=card-numbers#cards 
2. Railsコンソール上で操作し、ユーザーのクレジットカード支払情報が存在しかつ定期支払いが停止されていないことを確認
```ruby
> user = User.find_by(login_name: 'shinkitouroku')
> Stripe::Subscription.retrieve(user.subscription_id).cancel_at_period_end
=> false
```
3. 管理者ユーザーでログインし、新規登録したユーザー情報の編集ページ`/admin/users/:id/edit`にアクセスし、ユーザーステータスの「退会済」にチェックを入れて更新
![image](https://user-images.githubusercontent.com/46841037/236355548-52acf493-9cd7-4da4-9d04-8ad19432e4ff.png)

4. 管理画面のユーザーページからユーザーが退会していることを確認
5. 再びRailsコンソール上で2と同じ操作をすると、定期支払いが継続されたままとなっている

```ruby
> Stripe::Subscription.retrieve(user.subscription_id).cancel_at_period_end
=> false
```

## 期待される振る舞い

管理ページから退会させたときも定期支払いが停止される。
```ruby
> Stripe::Subscription.retrieve(user.subscription_id).cancel_at_period_end
=> true
```
ユーザー自身が退会処理を行ったときはこの挙動になることを確認しています。

## スクリーンショット

なし

## 調査したこと
ユーザー自身が行う退会処理は`RetirementController`が担っており、その処理の中で下記のコードを呼んでいます。
https://github.com/fjordllc/bootcamp/blob/e892fda0c5da128a9e27e94e9a3b03bce7044355/app/models/subscription.rb#L26

これはStripeの下記APIを叩いており、これによって定期支払を停止しているようです。
https://stripe.com/docs/api/subscriptions/update#update_subscription-cancel_at_period_end

管理ページの退会処理（だけでなくユーザー更新処理全般）は`Admin::UsersController`が担っていますが、退会フラグを更新したときもとくに上記のAPIは叩いていないようです。

## その他：管理ページからの退会動線の位置づけと修正方針について
管理ページからの退会動線は下記PRで比較的最近修正されており、それなりに使われているように思われます。
https://github.com/fjordllc/bootcamp/pull/6239

と、ここまで書いて気付いたのですが、管理画面から退会させるのは主に休会中のユーザーなのですかね。だとしたら、休会した時点で支払は停止されているので、大きな問題にはなっていないのかもしれません。
ただ、退会したのに支払いが継続したままになりうる動線が存在するのは、問題といえば問題かと思いました。

下記Issueで休会3ヵ月後に自動退会するように修正する予定なので、あるいは管理ページから退会させる動線自体が不要になるかもしれません。ただ、何らかの事情で管理者から強制退会させたいケースなどがもしあるのであれば、必要ですね。
- https://github.com/fjordllc/bootcamp/issues/6423

## 関連Issue
精査できていませんが、卒業処理についても似たことが起こっていそうに見えます。
→起票しました
Ref: #6499

**Comment by machida** [comment]
@ogawa-tomo こちらもアサインさせていただきました。関連Issueでファイルの共通化が必要な場合、その作業もお願いしたいです。その際、PRもまとめてお願いします。

**Comment by ogawa-tomo** [comment]
@komagata @machida こちら、本番での動作確認をお願いいたします。PRはこちらhttps://github.com/fjordllc/bootcamp/pull/6537 です。

**Comment by komagata** [comment]
@ogawa-tomo 本番環境で管理画面からの退会ができるようなシチュエーションになったときに確認したいとおもいます。

**Comment by komagata** [comment]
@ogawa-tomo 本番環境で動作することを確認しました。
