### ISSUE TITLE
管理画面のユーザー編集ページから卒業処理を行ったときクレジットカードの定期支払いが停止されていない

### ISSUE THREAD

**Issue by ogawa-tomo** [fjordllc/bootcamp#6499]
## 概要

管理ページのユーザー一覧画面から「卒業」ボタンを押して卒業させた場合は、クレジットカードの支払いが停止されます。
しかし、管理ページのユーザー編集画面から卒業チェックを入れて卒業させた場合はそうなっていないように見えます。

## 再現手順

1. ログインなしでユーザーの新規登録ページにアクセスし、適当にフォームを入れてユーザー登録をする
    - クレジットカードにはテスト用のカードを入れる
      - https://stripe.com/docs/testing?testing-method=card-numbers#cards 
2. Railsコンソール上で操作し、ユーザーのクレジットカード支払情報が存在しかつ定期支払いが停止されていないことを確認
```ruby
> user = User.find_by(login_name: 'sotugyousitai')
> Stripe::Subscription.retrieve(user.subscription_id).cancel_at_period_end
=> false
```
3. 管理者ユーザーでログインし、新規登録したユーザー情報の編集ページ`/admin/users/:id/edit`にアクセスし、ユーザーステータスの「卒業済」にチェックを入れて更新
![image](https://user-images.githubusercontent.com/46841037/236363107-a8798869-bf5f-43a9-8bd8-52b91ec5fe41.png)
4. 管理画面のユーザーページからユーザーが退会していることを確認
5. 再びRailsコンソール上で2と同じ操作をすると、定期支払いが継続されたままとなっている
```ruby
> Stripe::Subscription.retrieve(user.subscription_id).cancel_at_period_end
=> false
```

## 期待される振る舞い
管理ページのユーザー編集ページから卒業させたときも定期支払いが停止される。
```ruby
> Stripe::Subscription.retrieve(user.subscription_id).cancel_at_period_end
=> true
```
管理ページのユーザー一覧ページの「卒業」ボタンを押して卒業処理を行ったときはこの挙動になることを確認しています。
![image](https://user-images.githubusercontent.com/46841037/236363747-9488e860-6d1e-41df-b37e-ee8a443c1d37.png)

あるいは、管理ページのユーザー編集ページ自体に卒業を操作するチェックボックス自体が不要かもしれません。
もし、卒業を取り消すケースなどがあるのであれば、「卒業を取り消す」ボタンを設置するなどのほうが適切かもしれません。

## 調査したこと
管理ページのユーザー一覧画面から「卒業」ボタンを押したときの処理は`GraduationController`が担っており、この処理の中で下記のコードを呼んでいます。

https://github.com/fjordllc/bootcamp/blob/e892fda0c5da128a9e27e94e9a3b03bce7044355/app/models/subscription.rb#L26

これはStripeの下記APIを叩いており、これによって定期支払を停止しているようです。
https://stripe.com/docs/api/subscriptions/update#update_subscription-cancel_at_period_end

ユーザー編集画面から卒業させた場合の処理（卒業に限らずユーザーの更新処理）は`Admin::UsersController`が担っており、卒業フラグを更新したときも上記のAPIは叩いていないようです。

## 関連Issue
退会処理についても似たような挙動を発見しています。
Ref: #6498

**Comment by machida** [comment]
こちらは、ユーザー一覧から卒業のステータスを変更することは滅多にないのですが、編集ページからは行うので、編集ページでも課金が止まるように修正をお願いします。

**Comment by ogawa-tomo** [comment]
@komagata @machida こちら、本番での動作確認をお願いいたします。PRはこちらhttps://github.com/fjordllc/bootcamp/pull/6537 です。

**Comment by komagata** [comment]
@machida かしこまりました〜。

**Comment by ogawa-tomo** [comment]
@komagata @machida こちら、本番動作確認待ちのステータスなのでstaleラベルを外しました:bow:

**Comment by machida** [comment]
@ogawa-tomo ありがとうございます！

**Comment by machida** [comment]
@komagata こちらの動作確認をお願いします。

**Comment by komagata** [comment]
@machida 了解です。

**Comment by komagata** [comment]
@ogawa-tomo @machida こちら先ほど卒業処理をやって動作することが確認できました〜。
