### ISSUE TITLE
担当者が決まった提出物にはレビュー中という表示をつけたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6508]
<img width="689" alt="貼り付けた画像_2023_05_09_11_29" src="https://user-images.githubusercontent.com/168265/236978825-194cd06f-d87a-4c9a-b161-8243dcc892b7.png">

<img width="844" alt="貼り付けた画像_2023_05_09_11_32" src="https://user-images.githubusercontent.com/168265/236979060-59fd269b-89c0-4702-83d0-eea4aa90f1ba.png">

レビュー中という表示をつけ、その横に担当メンターのアイコンを表示させる。
デザインは machida がやりますー。

**Comment by machida** [comment]
@monyatto こちらの Issue をアサインしました！よろしくお願いします🙏

**Comment by monyatto** [comment]
こちら本番環境で動作確認できましたのでcloseいたします！
