### ISSUE TITLE
User.users_roleの実装がナイーブすぎて危険なので、実装を見直す

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6511]
@mono-nobe さんとペアプロしてるときに気付いたのですが、`User.users_role`で引数をそのまま`send`に渡すコードがあります。

https://github.com/fjordllc/bootcamp/blob/d28b702b93f2ea8b1f8de90afc828aefc9a3da04/app/models/user.rb#L404-L419

実装を確認したところ、いずれも呼び出し側でパラメータのバリデーションをしてから`User.users_role`を呼んでいるので（[例](https://github.com/fjordllc/bootcamp/blob/e892fda0c5da128a9e27e94e9a3b03bce7044355/app/controllers/api/users_controller.rb#L13)）、現時点では`User.send('destroy_all')`のようなコードが実行される危険性がないことは確認しました。

しかし、これが万一、「今後追加された実装でパラメータのバリデーションを忘れ、それがコードレビューをすり抜けて、デプロイされた後に悪意あるユーザーに不正なパラメータを指定されて・・・」というような問題が起きると致命的です（実装者とレビュアーが気を付けて`User.user_role`を利用する、という運用はあまりにもリスキー）。

なので、`send`に頼らない安全なメソッド設計に切り替えるべきだと思います。

## 雑な改善案
せめて、こう？

```ruby
def users_role(target, allowed_scopes: [], default_scope: :none)
  case target
  when 'student_and_trainee'
    students_and_trainees
  when 'graduate'
    graduated
  when 'adviser'
    advisers
  when 'inactive'
    inactive.order(:last_activity_at)
  when 'trainee'
    trainees
  else
    target = default_scope unless allowed_scopes.include?(target)
    send(target)
  end
end
```

**Comment by JunichiIto** [comment]
@Kassy0220 student_and_trainee や graduate も allowed_scopes に含めてもらう実装にした方が一貫性があってかつ安全になりそうです。

```ruby 
def users_role(target, allowed_scopes: [], default_scope: :none)
  return default_scope unless allowed_scopes.include?(target)

  case target
  when 'student_and_trainee'
    students_and_trainees
  when 'graduate'
    graduated
  when 'adviser'
    advisers
  when 'inactive'
    inactive.order(:last_activity_at)
  when 'trainee'
    trainees
  else
    send(target)
  end
end
```

が、そうすると allowed_scopes には student_and_trainee か student_and_trainees か、どっちを指定するねん、っていう話が出てきてややこしそう。
今のAPI的には student_and_trainee を指定するんだろうけど、それってscope名ちゃうやん、じゃあ allowed_targets か？みたいになるので、やっぱりstudent_and_traineeよりもstudent_and_traineesでtargetを指定してもらう方がいいですね。。

**Comment by Kassy0220** [comment]
@JunichiIto さんコメントありがとうございます！
次のように理解したのですが、この理解で大丈夫でしょうか？

- `allwed_scopes`にも`student_and_trainee`や`graduate`を含めたい
- しかし、`student_and_trainee`や`graduate`はスコープ名ではないので、スコープ名である`students_and_trainees`や`graduated`で`target`を指定するように修正した方が良い

`student_and_trainee`, `graduate`, `adviser`, `trainee`をスコープ名に合わせて、最終的には次のような形にしょうと考えています。
case when の分岐が2通り(`inactive`かそれ以外か)になるので、三項演算子に書き換えました。

```ruby
def users_role(target, allowed_scopes: [], default_scope: :none)
  return default_scope unless allowed_scopes.include?(target)

  target == 'inactive' ? inactive.order(:last_activity_at) : send(target)
end
```

**Comment by JunichiIto** [comment]
> この理解で大丈夫でしょうか？

合ってます！

> case when の分岐が2通り(inactiveかそれ以外か)になるので、三項演算子に書き換えました。

以前からの問題なのですが、よく考えるとこのメソッド内でorderを指定するのはちょっとおかしいですね。
メソッドの利用者は検索条件(scope)だけが返ってくると期待するはずなのに、勝手にorderを指定されるのはサプライズです。

参考 [僕が考える「良いコード」 \- give IT a try](https://blog.jnito.com/entry/2023/07/12/115733)

なので、

```ruby
def users_role(target, allowed_scopes: [], default_scope: :none)
  allowed_scopes.include?(target) ? send(target) : send(default_scope)
end
```

として、orderの付与は呼び出し側でなんとかするのがメソッドの設計としては適切ではないかと思いました。

**Comment by Kassy0220** [comment]
@JunichiIto さん、ご返信ありがとうございます🙏
> 以前からの問題なのですが、よく考えるとこのメソッド内でorderを指定するのはちょっとおかしいですね。
メソッドの利用者は検索条件(scope)だけが返ってくると期待するはずなのに、勝手にorderを指定されるのはサプライズです。

あくまで`users_role`は検索条件に当てはまるユーザーのリストを返す責務だけを担い、並び順は呼び出し側で並び替える、という方が確かに良い設計ですね！

`users_role`の中身もスッキリするので、`.order(:last_activity_at)`の並び替えは呼び出し側で担うよう修正することにします。

もし何か問題が発生した場合はまたご連絡するかもしれません🙏
丁寧なアドバイスありがとうございました🙇‍♂️

**Comment by JunichiIto** [comment]
すいません、また追加でコメントするんですが、

```ruby
def users_role(target, allowed_scopes: [], default_scope: :none)
  allowed_scopes.include?(target) ? send(target) : send(default_scope)
end
```

だと、全然user_roleと関係ない実装になってしまってます。（user roleに限らず、何でも呼び出せるメソッドになっている）

user_role と名乗るなら、それ関係のscopeしか呼び出せないようにしておくといいかも？

```ruby
USER_ROLE_SCOPES = %i[
  hoge
  piyo
  fuga
]
def users_role(target, allowed_scopes: [], default_scope: :none)
  (USER_ROLE_SCOPES & allowed_scopes).include?(target) ? send(target) : send(default_scope)
end
```

**Comment by Kassy0220** [comment]
@JunichiIto さん、アドバイスありがとうございます🙏
確かに`allowed_scopes`に呼び出したいメソッドを追加してしまえば、メソッドを呼べてしまいますね。
```ruby
# このような形にすれば、User.tagsを呼び出すことができる
@target = 'tags'
users_role(@target, allowed_scopes: ['users_and_trainees', 'tags'], default_scope: 'users_and_trainees')
```

`allowed_scopes`に含まれる値がuser_roleであることを保証する処理(`(USER_ROLE_SCOPES & allowed_scopes)`)も追加します！
詰めが甘かったです、またまたアドバイスありがとうございました🙇‍♂️

**Comment by Kassy0220** [comment]
@JunichiIto さん、ご返信ありがとうございます🙏
> 修正ボリュームを考えると、費用対効果が悪い（リスクが大きい割に得られるメリットが小さい）ので、issueに切り出しても対応される可能性は低い気がします。
なので、個人的にはtarget名の修正自体を見送ってもいいんじゃないかと思いました。

一つのメソッドに対して見合わない修正の量になってしまいました、影響範囲の見積もりが甘かったです。
target名の修正は見送ることにします。

修正案も教えていただきありがとうございます🙇‍♂️
まずはtarget名の修正見送りに関して駒形さんに相談し、OKをいただいたらポイントを踏まえて修正を行いたいと思います。

**Comment by komagata** [comment]
@Kassy0220 (CC: @JunichiIto )

変更点がとっても多いのであれば @Kassy0220 さんのおっしゃる通りで大丈夫です〜

**Comment by Kassy0220** [comment]
@komagata (CC: @JunichiIto )
駒形さんご返信ありがとうございます🙏
target名の修正は行わずに`users_role`の修正を行います。

**Comment by Kassy0220** [comment]
@komagata @machida 
お疲れ様です。
こちらの修正を行ったPRが本番環境にマージされたため、管理者のみアクセスできる以下のページが正しく動作しているか確認をお願いしたいです🙏

確認をお願いしたいページは次の2つです。

1. ユーザー管理ページ(`/admin/users`)
- user_roleごとの絞り込みが正しく機能しているか
<img width="1187" alt="_development__管理ページ___FBC" src="https://github.com/fjordllc/bootcamp/assets/79003082/b0d2e797-29b0-4f29-a329-db31db3c6d3a">

- 不正な値で絞り込みを行う(例えば`/admin/users?target=invalid`)と、「現役生」のユーザ一覧が表示されるか


2. 相談部屋ページ(`/talks`)
- user_roleごとの絞り込みが正しく機能しているか
<img width="976" alt="_development__相談部屋___FBC" src="https://github.com/fjordllc/bootcamp/assets/79003082/84f6c3de-1686-4027-99a1-da5805a04405">

- 不正な値で絞り込みを行う(例えば`/talks?target=invalid`)と、「全員」の相談部屋一覧が表示されるか

よろしくお願いいたします🙇‍♂️

**Comment by machida** [comment]
@Kassy0220 管理画面ユーザー一覧も、相談部屋一覧も確認できました👍不正な値を入れた際の動作もOKでした🙆‍♀️

**Comment by Kassy0220** [comment]
@machida 
ご確認ありがとうございます！🙇‍♂️
こちら本番環境での確認が完了しましたので、Closeいたします〜🙌
