### ISSUE TITLE
Q&Aを削除できなくする（再）

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6513]
以前、以下のissueで、Q&Aは「アラートを出した上で削除可とする」という仕様に変更されました。

https://github.com/fjordllc/bootcamp/issues/1531

しかし、アラートを出しても（気軽に？）Q&Aを削除してしまう受講生さんがいます。
しかも、Q&Aの内容的に「それ、いい質問だし、消さなくてええやん」と思うものも多いです。
あと、回答を投稿しようとした直前に質問が削除されて、「僕が書いた回答はどうすれば・・・😭」となったこともありました。

やはりQ&Aは削除不可（もしできるとしても、メンター権限以上が必要）として、削除したい場合は何かしらコメントを書いてそれを自分でベストアンサーに選んでクローズしてもらう、という仕様にしたいです。

**Comment by machida** [comment]
📝 
- メンター
- 管理者

のみが削除できるようにする。

デザインと注意書きを入れるので、machidaにメンションお願いします。

**Comment by machida** [comment]
@sochi419 こちら、UIの方はリリースがされています（削除リンクは表示されていない）。機能的にはメンター、管理者以外は削除できないという制限は実装されていない状況です。
