### ISSUE TITLE
提出物更新の通知をnewspaper化する

### ISSUE THREAD

**Issue by monyatto** [fjordllc/bootcamp#6515]
提出物更新の通知をnewspaperを使用したものに変更する。
 #5875（提出物更新通知をactive_delivery化したい ）から派生したissueです。

**Comment by monyatto** [comment]
@komagata @machida 
お手隙の際に「受講生が提出物を更新すると担当メンターにサイト内通知がいく（メンターが更新した場合は通知は飛ばない）」という内容で本番環境で動作確認していただきたいです🙏

**Comment by machida** [comment]
@monyatto @komagata こちらは次回のMTGのときに動作確認したいと思いますー

**Comment by monyatto** [comment]
チーム開発MTGにて動作確認いただいたためcloseします〜
