### ISSUE TITLE
未ログイン時のmeta description表示のテストファイル名を統一したい

### ISSUE THREAD

**Issue by ogawa-tomo** [fjordllc/bootcamp#6524]
## 概要
現状、未ログイン時のmeta descriptionを設定したPRは3つあります。

1. https://github.com/fjordllc/bootcamp/pull/6448
2. https://github.com/fjordllc/bootcamp/pull/6458
3. https://github.com/fjordllc/bootcamp/pull/6406

この3つのPRで、3だけテストが書かれたファイル名が異なっています。
1と2は`test/system/{model名}/not_logged_in_test.rb`に書かれていますが、3は`test/system/{model名}/completion_test.rb`に書かれています。
3のテストも`not_logged_in_test.rb`を作成し、そこに書くよう統一したいです。

3はpracticeページに関するPRであり、`completion_test.rb`はpracticeの「修了」に関するテストを書くためのファイルだと考えられます。したがって、未ログイン時のmeta description表示のテストを書く場所として適切ではないと考えています。

テストの書き方を統一することで、リポジトリ全体としてのコードを分かりやすくし、後続の実装者が迷うことがないようにしたいと考えています。

## 参考
こちらのコメントを受け作成したIssueです。
- https://github.com/fjordllc/bootcamp/pull/6458#discussion_r1194784955

**Comment by syo-tokeshi** [comment]
@ogawa-tomo 
お疲れ様です🙇‍♂️
tomoさんに言われて気づきましたが、その通りだと思います🙇‍♂️
@YukiWatanabe824 
レビューの時、気付けなくてすみませんでした🙇‍♂️

**Comment by YukiWatanabe824** [comment]
@ogawa-tomo 
私もそのとおりだと思いました。
全体で統一したほうがわかりやすくなると思いました。
ただしそれでいくと、この3Issue以外の部分についても該当する部分は`not_logged_in_test.rb`を作成してテストを移管する必要がある気がします。

**Comment by ogawa-tomo** [comment]
ご確認ありがとうございます！

@YukiWatanabe824 
> ただしそれでいくと、この3Issue以外の部分についても該当する部分はnot_logged_in_test.rbを作成してテストを移管する必要がある気がします。

私の探した限りでは、未ログイン時のmeta descriptionに関するテストはこの3PRしか見つかりませんでした。（PR一覧で「meta description」と検索したり、コードを`meta[name='description']`で全文検索したりしました）
他にも類似のテストがありそうですかね？
あるいは、類似の箇所がもしあればそこも統一する、とIssueに書き足しておくとよいですかね。

**Comment by YukiWatanabe824** [comment]
> 他にも類似のテストがありそうですかね？
私もざっとですが検索かけた限りヒットしませんでした！すみません、現状この3PRのみとなりそうです！

> あるいは、類似の箇所がもしあればそこも統一する、とIssueに書き足しておくとよいですかね。
私は現状の3PRを対象にすればいいと思います。類似箇所がでてきたらそれはそれでIssueを起票して対応するとよい気がします。

**Comment by ogawa-tomo** [comment]
OKです！ではIssueとしてはこのままにしておきます。

**Comment by 2525nicole** [comment]
リリースされたためCloseします！
