### ISSUE TITLE
ユーザータグ別に表示される人数が、表示箇所によって異なっている

### ISSUE THREAD

**Issue by gogutan** [fjordllc/bootcamp#6525]
## 概要

表示箇所によって、「現役生」「退会」「休会」などのステータスのうち、
どのステータスのユーザーを対象とするかが異なっていると思われる。

## 期待される振る舞い

「退会と休会のユーザーは対象外とする」など、全ての箇所で仕様が統一されること。

## スクリーンショット

https://bootcamp.fjord.jp/users/tags?page=2
![タグ別ユーザー一覧___FBC](https://github.com/fjordllc/bootcamp/assets/50437473/b1462870-b027-43c5-bb0a-42655b520a6d)

https://bootcamp.fjord.jp/users/tags/%E9%87%A3%E3%82%8A
![全てのユーザー___FBC](https://github.com/fjordllc/bootcamp/assets/50437473/e1c3093c-172c-4f89-8b50-33a964d67b9c)

**Comment by machida** [comment]
「退会と休会のユーザーは対象外とする」これを全ての箇所で仕様が統一する、で行きます。

**Comment by machida** [comment]
@2525nicole こちらもアサインさせていただきましたー

**Comment by 2525nicole** [comment]
@machida 
ありがとうございます🙇‍♀️進めてまいります！

**Comment by 2525nicole** [comment]
本番環境で動作確認ができたためcloseいたします🙇‍♀️
