### ISSUE TITLE
iPhoneで通知メールからFBCにアクセスすると「問題が繰り返し起きました」という表示が出ることがある

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6529]
## 概要

iPhoneで通知メールからFBCにアクセスすると「問題が繰り返し起きました」という表示が出ることがある。

## 再現手順

この現象が発生するときとしないときがあります。

1. iPhoneの標準のメールアプリで通知メールを開く。
2. 「この○○へ」ボタンをクリック。
3. エラーが表示される。

## 期待される振る舞い

エラーなくリンク先を表示できる。

## スクリーンショット

https://bootcamp.fjord.jp/reports/72857#comment_131108 を開こうとしたときの例です。

![IMG_686D75C38E8F-1](https://github.com/fjordllc/bootcamp/assets/1148320/fc417d45-b499-4184-8f26-b0ffcb47ab79)

![IMG_8519](https://github.com/fjordllc/bootcamp/assets/1148320/b2611db3-6a71-4c22-9d1a-28a4e64cb1df)

## 環境

 - OS: iOS 16.4.1 (a)
 - メーラー: Gmail
 - ブラウザ: Safari

**Comment by JunichiIto** [comment]
これ、たまに起きるんですよね。再現手順はよくわからないけど。。

**Comment by machida** [comment]
gogutanさんがPRを出してくれましたー🎉
https://github.com/fjordllc/bootcamp/pull/6771

**Comment by JunichiIto** [comment]
なんと！！
@gogutan さん、どうもありがとうございます！🙏

**Comment by machida** [comment]
こちら本番で解決されたのが確認できたのでクローズしますー🎉
