### ISSUE TITLE
メンターの責務をメンター用Controllerに集約する

### ISSUE THREAD

**Issue by mono-nobe** [fjordllc/bootcamp#6536]
## 概要

メンターのみが使用できるメソッドの一部がメンター用Controllerに定義されていないため集約したい。
また、それに伴い不要な画面などあれば削除する。

## 詳細

以下のメンター用 Controller において、一般の Controller と処理が重複しているメソッドが存在する。
現状、一般の Controller に定義されているメンター用メソッドは、`before_action :require_admin_or_mentor_login` によりメンターのみが使用できるようになっている。

- メンター用
    - Mentor::CoursesController
    - Mentor::PracticesController
    - Mentor::CategoriesController
- 一般
    - CoursesController
    - PracticesController
    - Courses::CategoriesController

また、処理の重複に伴い、同じ機能を持った画面が存在している。
以下、どちらもメンターのみが閲覧できるコース一覧画面である。作成画面も同様に複数存在している。

#### http://localhost:3000/mentor/courses

<img width="1715" alt="image" src="https://github.com/fjordllc/bootcamp/assets/94843475/d0f7c302-edb6-4ef9-a78f-3ed7c97a3903">

#### http://localhost:3000/courses

<img width="1702" alt="image" src="https://github.com/fjordllc/bootcamp/assets/94843475/c5f070d2-843f-4290-9de8-ffbbd39bf88e">

機能が同じ & メンター用画面が存在するため、`http://localhost:3000/courses` の画面は削除したい。

## 期待される振る舞い

- メンター用のメソッドはメンター用Controllerのみに定義されている
- 機能が重複している画面が削除されている

## 関連Issue
https://github.com/fjordllc/bootcamp/issues/6210

**Comment by komagata** [comment]
おそらく完了しているのでCloseします。
