### ISSUE TITLE
分報チャンネルが作られないユーザーがいる

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6551]
<img width="500" alt="スクリーンショット 2023-05-23 2 18 02" src="https://github.com/fjordllc/bootcamp/assets/16577/06350215-8f87-4b19-92fc-c3a347dd3bd3">

---

- 原因を特定し修正する。
- 修正するのに加え、日報が作られなかったとき（例えばチャンネル数の上限のせいでなど）は、管理者の通知チャンネルで報告がされるようにしてほしい。

**Comment by machida** [comment]
- hotpepsi
- m0nch1

は登録時はアドバイザーとして登録したので分報は作成されないままでOK。

- Yusa

は研修生としての登録だが、研修生は分報が作成される仕様なのでバグ。

- sp8783
- Nissy

は一般受講生なので分報が作成されないのはバグ。
