### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'facebook.json')

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6556]
View details in Rollbar: [https://rollbar.com/komagata/Bootcamp/items/1406/](https://rollbar.com/komagata/Bootcamp/items/1406/)

```

TypeError: Cannot read properties of undefined (reading 'facebook.json')
  File "(unknown)", line 5925, in getConfig
  File "(unknown)", line 7984, in ClickToLoad.init
  File "(unknown)", line 1326, in ClickToLoad.callInit
  File "(unknown)", line 8181, in [anonymous]
  File "(unknown)", line 8179, in Object.init
```

**Comment by yagitoshiro** [comment]
@komagata これってduckduckgoのせいじゃない？エラー出てるのこれなんじゃないかな。

https://github.com/duckduckgo/content-scope-scripts/blob/main/src/features/click-to-load/ctl-config.js#L622

**Comment by komagata** [comment]
@yagitoshiro dackdackgoの拡張を使ってる人がアクセスするとこのエラーが出るってことですかね？

**Comment by yagitoshiro** [comment]
@komagata そうみたい。このページを見ている時にも（まさにこの瞬間に）同じエラーが出てました。

**Comment by komagata** [comment]
@yagitoshiro なるほどぉ〜！
