### ISSUE TITLE
コメントとメンションで、通知メールの件名の形式が異なる

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6558]
### コメントが付いたとき

hogeさんの【 「メンション機能レビュー #5インスタンスへのパラメータの値の格納。Help」の日報 】にhogeさんがコメントしました。

### メンションがあったとき

hogeさんの日報「メンション機能レビュー #5インスタンスへのパラメータの値の格納。Help」へのコメントでhogeさんからメンションがありました。

<img width="1511" alt="fbc" src="https://github.com/fjordllc/bootcamp/assets/1148320/f9c21720-934d-4266-b940-0e2383c7097e">

### 改善案

軽微な問題ですが、微妙に形式（フォーマット）が違って気持ち悪いので、どちらかの形式に合わせた方が良さそう。

例）hogeさんの日報「メンション機能レビュー #5インスタンスへのパラメータの値の格納。Help」にhogeさんがコメントしました。

これ以外にもあるかもしれないので、全体的に通知メールの件名を棚卸しして、形式を揃えた方がいいかもしれません。

**Comment by Sasaco-JM** [comment]
本番環境への反映を確認しましたのでクローズいたします。

- コメントの場合
<img width="1201" alt="image" src="https://github.com/fjordllc/bootcamp/assets/78665068/f97c8cac-24cb-4049-87e8-5d3b7fa85223">

- メンションの場合
<img width="1313" alt="image" src="https://github.com/fjordllc/bootcamp/assets/78665068/56ea1be0-17e3-4af0-8849-45b7d4d315af">
