### ISSUE TITLE
通知ページのユーザーアイコンからプロフィールページに飛べるようにしたい

### ISSUE THREAD

**Issue by gogutan** [fjordllc/bootcamp#6581]
## 機能の説明

![通知___FBC](https://github.com/fjordllc/bootcamp/assets/50437473/d0d2be8d-c6e3-4677-b449-df77ffd732d4)

## 何故この機能が必要なのか

お知らせ、日報・ブログ、Q&A…など他のページではユーザーアイコンからプロフィールページに飛ぶことができるが、
通知ページのユーザーアイコンからはプロフィールページに飛ぶことができず、少し不便なため。

**Comment by 2525nicole** [comment]
本番環境で動作確認ができたためCloseします！
