### ISSUE TITLE
ダッシュボードページで、メンターモードを OFF にしても提出物状況が表示されてしまう

### ISSUE THREAD

**Issue by cafedomancer** [fjordllc/bootcamp#6585]
## 概要

そのmama

## 再現手順

1. / にアクセス
2. メンターモードを OFF
3. 提出物状況が引き続き表示される

## 期待される振る舞い

メンタモードが OFF のときには提出物状況が表示されない

## スクリーンショット

| メンターモード ON | メンターモード OFF |
| - | - |
| ![localhost_3000_](https://github.com/fjordllc/bootcamp/assets/7645585/e2d59302-bd04-487c-ac92-10eb71b15297) | ![localhost_3000_ (1)](https://github.com/fjordllc/bootcamp/assets/7645585/3ab5085b-d1ac-4da1-9df0-c598072dd97b) |

## 環境

 - OS: macOS Ventura
 - ブラウザ: Google Chrome
 - バージョン: 114.0.5735.45 (Official Build) (arm64)

## 関連Issue

なし？

**Comment by machida** [comment]
対応しましたー
