### ISSUE TITLE
ブックマーク一覧, 企業一覧ページで1ページの場合もページネーションが表示されている

### ISSUE THREAD

**Issue by djkazunoko** [fjordllc/bootcamp#6597]
## 概要

1ページの場合もページネーションが表示されている。対象は以下の2箇所。
- ブックマーク一覧(`/current_user/bookmarks`)
- 企業一覧(`/admin/companies`)

## 再現手順

1. `/current_user/bookmarks`にアクセス
2. ブックマークを20件以下にする
3. ページネーションが表示される
4. `/admin/companies`にアクセス
5. 企業を20件以下にする
6. ページネーションが表示される

## 期待される振る舞い

1ページの場合はページネーションが表示されない

## スクリーンショット
`/current_user/bookmarks`
![スクリーンショット 2023-06-02 12 41 07](https://github.com/fjordllc/bootcamp/assets/65595901/a34294a9-7ceb-45a7-bd5c-1a92013eed3b)

`/admin/companies`
![スクリーンショット 2023-06-02 12 40 50](https://github.com/fjordllc/bootcamp/assets/65595901/11f453b8-976f-40aa-a596-d79f26842fd3)

## 参考

- https://github.com/fjordllc/bootcamp/pull/6459
- https://github.com/fjordllc/bootcamp/pull/5599
- https://github.com/fjordllc/bootcamp/pull/5912

## メモ
- 以下のコンポーネントではページネーションの非表示の処理が実装されている
  - `app/javascript/components/Events.jsx`
  - `app/javascript/components/Products.jsx`
  - `app/javascript/components/Reports.jsx`

**Comment by dowdiness** [comment]
リリースされたのでcloseします

https://github.com/fjordllc/bootcamp/pull/6904
