### ISSUE TITLE
提出物一覧を表示するVueコンポーネントを提出からの経過日数ラベル表示の有無で分割したい

### ISSUE THREAD

**Issue by ogawa-tomo** [fjordllc/bootcamp#6599]
## 概要
メンターの見る提出物一覧表示には、大きく分けて提出からの経過日数がラベルで表示されるものとそうでないものの2種類があります。
現状、これらの2種類の表示は同一のVueコンポーネント内で表示方法を分岐することで実現されています。
そのVueコンポーネントを分割し、それぞれの表示について個別のコンポーネントを用意するよう改修することで、コードの見通しが良くなるのではないか、という提案です。

## 現状の表示とコード
メンターの見る提出物一覧表示は以下の5つがあります。
1. トップページ `/`
2. 全ての提出物一覧ページ `/products`
3. 未完了の提出物一覧ページ `/products/unchecked`
4. 未アサインの提出物一覧ページ `/products/unassigned`
5. 自分の担当の提出物一覧ページ `/products/self_assigned`

このうち、1, 3, 4は提出からの経過日数がラベルで表示され、2, 5はその表示がありません。

| 提出からの経過日数をラベルで表示するケース | 提出からの経過日数をラベルで表示しないケース |
|--------|--------|
| ![image](https://github.com/fjordllc/bootcamp/assets/46841037/8d6f8af1-9ed7-428e-8565-6a65fefeb83d)| ![image](https://github.com/fjordllc/bootcamp/assets/46841037/cc0a0f3a-11ac-4cfb-b8ed-8639e50e4428) |

これらの表示は、すべて`app/javascript/products.vue`ファイルのProductsコンポーネントが担っています。
このVueコンポーネントは基本的にはProductコンポーネントを繰り返し表示するだけのものですが、上記のラベルの表示の有無を制御するために随所に条件分岐が仕込まれています。

たとえばここでは、提出からの経過日数をラベルで表示するページについてのみ、提出からの経過日数ごとにグルーピングした提出物のデータを読み込んでいます。
https://github.com/fjordllc/bootcamp/blob/a8fee391964505a564cd23f527c03fa3471890f3/app/javascript/products.vue#L198-L205

そしてここで、上記のグルーピングした提出物のデータの有無に応じて、ラベル表示の有無を制御しています。
https://github.com/fjordllc/bootcamp/blob/a8fee391964505a564cd23f527c03fa3471890f3/app/javascript/products.vue#L19-L29

前述の通り、Productsコンポーネントは基本的にはProductコンポーネントを繰り返し表示する単純なものですが、このような条件分岐および提出からの経過日数ラベル表示がコードの大部分を占めているように見えます。

## 改善案
提案としては、提出からの経過日数ラベルの表示の有無によってコンポーネントそのものを分割したいです。たとえば、ラベルを表示するコンポーネントはProductsWithElapsedDaysLabelコンポーネント、ラベルを表示しないコンポーネントはProductsコンポーネント、といった具合です。
そうすることによって、コンポーネントからラベル表示制御のための条件分岐ロジックが不要となり、またそれぞれのコンポーネントに必要な処理だけが記述されるようになり、コードの見通しがよくなるのではと考えています。

合わせてコントローラ側にも不要なコードがありそうなので削除したいです。たとえば、下記の箇所は全ての提出物一覧ページ（`/products`）に対応するAPIのコントローラですが、このページでは提出からの経過日数ラベルを表示しないので、不要であるように見えます。

https://github.com/fjordllc/bootcamp/blob/a8fee391964505a564cd23f527c03fa3471890f3/app/controllers/api/products_controller.rb#L12

まったく別の案としては、全ての表示について提出からの経過日数ラベルを表示するようにする、という仕様変更もあり得るかもしれません。
## 優先度について
現状この箇所で不具合が起きているというわけではなく、優先度としてはさほど高くないとは考えています。（この箇所を読み解くのに苦労したので問題の整理を兼ねて起票しました）
たとえば将来的にbootcampリポジトリのVueをReactに置き換えていくのであれば、その際に検討するということでもよいかもしれません。

**Comment by komagata** [comment]
すでにReactに置き換えて行っている状態なのでVueに工数を費やすのはできれば避けたいなと考えています。
