### ISSUE TITLE
イベント購読に自分が参加している定期イベントも反映させたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6607]
/events にアクセス。

![IMG_0137](https://github.com/fjordllc/bootcamp/assets/168265/3f35031c-27bf-4392-a6bc-8362e65a35ee)

イベント購読ボタンをクリックすると、参加・不参加関係無しに、全ての特別イベントがカレンダーに反映される。

参加・不参加関係無いので、カレンダーに反映される結果はどのユーザーも同じである。なので、どのユーザーもボタンのリンク先も同じ。

以下が、今回行って欲しい機能追加、変更。

自分が参加登録している特別イベントは、参
加登録済み、のような文言がカレンダーに表示されるようにしたい。参加登録していない特別イベントも今と変わらずカレンダーに表示されるようにする。

自分が参加登録している定期イベントもカレンダーに表示されるようにしてほしい。今までは特別イベントだけが表示されていたので、定期イベントがカレンダーに表示されるのは完全に新機能。

特別イベントは自分が参加・不参加関係なくカレンダーに表示されるが、定期イベントは自分が参加登録しているものだけが表示されるようにする。

また、定期イベントが祝日などの関係で休みになる場合は、カレンダーにも表示しないようにする。

今まではどのユーザーもイベント購読ボタンのURLは同じだったが、今回の変更によりユーザーによってカレンダーに表示される内容が異なるので、ユーザーごとにボタンのURLが異なるようになる。

**Comment by machida** [comment]
@komagata 詳細を書きましたー

**Comment by komagata** [comment]
@machida ありがとうございます～！

**Comment by a-terumoto-gs** [comment]
本番環境での動作が確認できたのでcloseします

**Comment by komagata** [comment]
@a-terumoto-gs #8119 でカレンダーにエラーが起きているようです。確認お願いできればありがたいです。`

**Comment by a-terumoto-gs** [comment]
@komagata 
申し訳ございません。エラーについて確認しました。
エラーがでているURLについて、イベント購読の旧仕様で使用されていたURLで、パラメータとしてuser_idを渡していないためでているのだと思います。
動作のほうも合わせて確認しようと思ったのですが、先週の3日のリリース後の動作確認を終えてフィヨルドを退会してしまっており、現在サイトに入れない状況です。
実装後のフォローまで完了できず大変申し訳ないのですが、私のほうでの修正が難しそうです。

**Comment by komagata** [comment]
@a-terumoto-gs すみません、もう @a-terumoto-gs さんは卒業されているので作業は不要です。
こちらの方で引き取らせていただきます。

> エラーがでているURLについて、イベント購読の旧仕様で使用されていたURLで、パラメータとしてuser_idを渡していないためユーザーの情報が取得できずでているエラーだと思います。

もしよろしければ、こちら（旧仕様で使われていた）についてもう少しヒントをいただければありがたいです〜。

**Comment by a-terumoto-gs** [comment]
@komagata 
返信が遅くなり申し訳ありませんm(__)m

イベント購読をする際にはcalendars_controllerにリクエストをおくってイベントのデータを取ってくるようにしています。
仕様変更前後でcalendars_controller内での処理は変わりましたが、calendars_controllerにリクエストをおくるのは今回の変更前から変わらずになっています。

以前はどのユーザーも共通でこれから開催の特別イベントのデータを取ってくる仕様だったため、
`https://bootcamp.fjord.jp/events/calendars.ics`に特に追加情報を渡すことなくリクエストを飛ばすようにになっていました。

今回の仕様変更でユーザーごとにカスタムされたイベントのデータが必要になったため、リクエスト時に必要な情報としてuser_idを追加で渡すようにしております。
その後calendars_controller内での処理でuser_idを使用しております。
その結果リクエストをおくるURLが`https://bootcamp.fjord.jp/events/calendars.ics?user_id=○○`という形になりました。

エラーがでているのは`https://bootcamp.fjord.jp/events/calendars.ics`であるため、旧仕様で使用されていたリクエスト先になっております。
今の仕様だとこのURLにリクエストは飛ばないはずです。
旧仕様のイベント購読をカレンダーに登録したままの方がいて何かのきっかけでリクエストが飛んだりしてるのかも？と推測しましたが、
カレンダーへの登録時以外にリクエストが飛ぶというようなことがあり得るのかまで調べられていません。申し訳ございません。

この説明で伝わりますでしょうか？
不明点ありましたらまたご連絡いただけますと幸いですm(__)m

**Comment by komagata** [comment]
@a-terumoto-gs なるほどです。
研修が終わっているにも関わらず情報ありがとうございました。非常に助かります。
