### ISSUE TITLE
管理者・メンター以外も特別イベントの公開ができるようにする

### ISSUE THREAD

**Issue by sadanora** [fjordllc/bootcamp#6608]

**Comment by machida** [comment]
@sadanora 
Issueと着手ありがとうございます！

確かに誰でも削除できるのはミスもあるかもしれないので危険ですね。

---

## 作成

- 誰でも

## 編集

- 作者
- メンター
- 管理者

## 削除

- 作者
- メンター
- 管理者

---

で、お願いします。
定期イベントと同様に主催者を登録する機能を付けて、主催者も編集、削除ができるようにする、などいつかしたいですが、それは別Issueで、今は上記でお願いしますー🙏

**Comment by sadanora** [comment]
@machida 
ありがとうございます〜！
ご回答いただいた権限で進めます。

(そもそも私が既存の仕様を勘違いしていてちょっと変な質問をしてしまった気がします。失礼いたしました:pray:)
