### ISSUE TITLE
ユーザー一覧 > 休会中の各ユーザーに休会してからの経過日数を表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6613]

**Comment by sochi419** [comment]
すみません、私のissueかと勘違いをしていて私が担当しているわけではないのに、一旦staleラベルを外してしまいました。
再度staleラベルを付け直しました。

**Comment by 2525nicole** [comment]
@machida 
お疲れ様です！仕様について2点確認させていただきます🙇‍♀️
お手数をおかけしますが、ご確認の程よろしくお願いいたします。

1. こちらのIssueで実装する内容ですが、
以下のIssueと同様に **「メンターと管理者」にのみ「休会期限と経過日数」が表示される機能の実装** という認識で相違ないでしょうか🙏？

- #6615 

>## 休会期限とは
>- 休会期限日は、休会に入ってから3ヶ月後。
>- 1月20日の14:00に休会をした場合
>    - 3月20日が休会期限日
>    - 3月20日の13:59が休会期限時間

>## 経過日数の表示方法法
>- `休会期限日: 20XX年XX月XX日（あとXX日）` と表示したい（曜日は不要）。
>- 休会期限日の残りが24時間を切った場合は、休会期限日: 20XX年XX月XX日（本日休会最終日） と表示したい。
>- 休会期限日まで8日を切った場合は（8日未満、つまり7日以下の場合）は赤文字で表示したい。
 
>## 表示のルール
>- この表示はメンターと管理者にだけ表示される。

2. 表示位置
表示位置ですが、以下の箇所でいかがでしょうか🙏
「1ヶ月以上ログインがありません」表示とユーザー名と干渉しない位置、ということでこの箇所を想定として置いてみました。

想定されていた位置や、その他好ましい表示位置がありましたらご教示いただけますと幸いです。

![スクリーンショット 2023-12-01 8 52 22](https://github.com/fjordllc/bootcamp/assets/104631303/c573e332-fac8-492c-9471-43e1a7901784)

**Comment by 2525nicole** [comment]
@machida 
とんでもないです！！ご回答ありがとうございます🙇‍♀️
表示内容と場所について承知いたしました🙏
頂戴した内容で進めてまいります💪

**Comment by 2525nicole** [comment]
@komagata @machida
お疲れ様です！以下のPRが本日マージ&リリースされました。
[ユーザー一覧ページにおいてメンターと管理者には休会中ユーザーの休会日と経過日数が表示されるようにした #7115](https://github.com/fjordllc/bootcamp/pull/7115)

メンターと管理者のみが確認できる画面のため、本番環境でのご確認をお願いできますでしょうか🙏
お手数をおかけいたしますがよろしくお願いいたします🙇‍♀️

## 確認方法
1. メンターのアカウントでログインする
2. [休会中ユーザー一覧画面](https://bootcamp.fjord.jp/users?target=hibernated) にアクセスする
3. 各ユーザーに休会中: yyyy年mm月dd日〜（dd日経過）という表示がされていることを確認する

<img width="889" alt="休会ユーザー一覧ページ" src="https://github.com/fjordllc/bootcamp/assets/104631303/5a7f0970-444b-43d9-badf-4bbe44fabd6b">

4.  [退会ユーザーの一覧ページ](https://bootcamp.fjord.jp/users?target=retired)にアクセスする
5. 各ユーザーに「退会しました」という表示がされていることを確認する

<img width="888" alt="退会ユーザー一覧ページ" src="https://github.com/fjordllc/bootcamp/assets/104631303/6e6d12cb-728f-4a9a-93fc-427d8a406a40">

**Comment by 2525nicole** [comment]
本番環境での動作確認OKをいただいたのでcloseいたします🙇‍♀️

@machida 
お忙しいところご協力ありがとうございました🙏

https://discord.com/channels/715806612824260640/809595476847493192/1195216517072171019
