### ISSUE TITLE
newspaperの引数をハッシュで受け渡しするように修正したい。

### ISSUE THREAD

**Issue by monyatto** [fjordllc/bootcamp#6617]
全てのnewspaper呼び出しの引数をハッシュでの受け渡しに変更したい。

- newspaper が受け取れる引数は1つ。
- そのためnewspaper での通知の際に、コントローラーから複数のデータを渡したい場合はハッシュで渡す必要がある。
- newspaper の通知では同じファイルが違う呼び出し元（と異なる引数）で呼ばれる場合がある。
- 現在、引数がハッシュで呼ばれる場合とそうでない場合が混在している。応急処置として、該当のファイルではハッシュかそれ以外かで分岐させる処理を入れている。

全てのnewspaper呼び出しをハッシュでの受け渡しに変更することで、引数を受け取る際にハッシュかそれ以外かで分岐させる処理の必要を無くしたい。

#6521 から派生したissueです。

**Comment by machida** [comment]
@2525nicole こちらお願いしますー
news paper に関するIssueやPRを見てnews paper gem ついて調べながらこのIssueをお願いします。不明点などが出たら、@monyatto さんに相談お願いしますー

**Comment by 2525nicole** [comment]
@komagata @machida 
おつかれさまです！
本IssueのPRについてご相談です🙇‍♀️

## 【ご相談したい内容】
以下の状況によりレビュワーの方に（特に動作確認の点で）負担をかけてしまう懸念や、
動作確認の項目数や変更ファイル数を鑑みて**2つのPRに分けたい**と考えておりますが問題ないでしょうか。

### 【状況】
newspaperの引数の受け渡し方法をすべてハッシュに置き換えたため、PRの確認内容が膨れてしまいました。

- 「変更確認方法」が15項目 
  - 一連の流れでできるアクションについては項目をまとめましたが、15個の項目に及んでいます（1つの項目で2-3つのケースを確認いただく項目もあります）
- 「 Files changed」が52
  - 以下のとおりファイルの変更点は一定の法則にしたがったものなので、1件1件の変更は複雑なものではないものの件数としては多めの印象です
  - newspaperを呼び出す側：変数をハッシュに変更
  - newspaperで呼び出される側：`payload`で引数を受け取り、ハッシュから変数を取り出す

### 実際に作成したPR
[newspaperの引数をハッシュで受け渡しするように統一した by 2525nicole · Pull Request \#7173 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/7173)

=>問題なければこのPRの内容を2つに分けたいと考えております

**Comment by machida** [comment]
@2525nicole 分けるの、とてもいいと思いますー👍

**Comment by 2525nicole** [comment]
@machida 
年始にも関わらず早速のご回答ありがとうございます🙇‍♀️！
問題ないようで安心いたしました☺️
それではPRは分けて出すようにいたします🙏

**Comment by 2525nicole** [comment]
## メモ：ステージング環境での確認について
komagataさんにご連絡の上、
以下動作についてはステージング環境での動作確認はスキップし、本番環境での確認とすることになった🙏

### 該当の動作確認項目
### [newspaperの引数をハッシュでの受け渡しに統一 1/2](https://github.com/fjordllc/bootcamp/pull/7175)

- Learningが保存・削除された場合のキャッシュ削除の確認（loggerを使用した確認方法調査中）

### [newspaperの引数をハッシュでの受け渡しに統一 2/2](https://github.com/fjordllc/bootcamp/pull/7174)

- Q＆Aの解決質問数のキャッシュ削除の確認（loggerを使用した確認方法調査中）
- 新規登録ユーザーの購読解除トークン作成の確認
- 6ヶ月経過した休会ユーザーが自動退会した際の退会処理の確認
- 自主退会、管理者による退会の処理は確認済み


[Didcordでの該当メッセージ](https://discord.com/channels/715806612824260640/809595476847493192/1199950910680469515)

**Comment by 2525nicole** [comment]
@komagata @machida 
## 【ご依頼】本番環境での動作確認について
分量が多く大変恐れ入りますが、こちらのIssueの動作確認について
1. ご協力依頼
2. 質問
3. ご共有事項
がございます。

それぞれ詳細を以下に記載しますので、お手数をおかけしますがご確認をいただけますと幸いです🙏

## 1. 動作確認ご協力のお願い

以下、管理者/メンター、またはアドバイザーのみが確認できる内容ですので
協力をお願いできますでしょうか🙇‍♀️

### 休会関連
- [ ]  休会復帰時の処理
  -  休会されていた方が復帰された際に管理者/メンターにメール/サイト内通知が届くことを確認する

### 提出物関連
- [ ] 「メンターがWatchしているプラクティス」に提出物があった時にWatch中のメンターに通知が届く
- 確認手順
1. メンターが任意の「提出物が必要なプラクティス」をWatchする
2. 1でWatchしたプラクティスに提出物が出された際にメール/サイト内通知が届くことを確認する

- [ ] 研修生が提出物が出された時にアドバイザーに通知が届く
- 確認手順
1.  研修生が提出物を出す
2. 研修生所属企業のアドバイザーにメール/サイト内通知が届くことを確認する

### 日報投稿関連
- [ ] 研修生が日報を投稿するとアドバイザーに通知が届く
- 確認手順
1.  研修生が日報を投稿する
2. 研修生所属企業のアドバイザーにメール/サイト内通知が届くことを確認する
- [ ] 初めての日報が投稿されると管理者/メンターにメール/サイト内通知が届く
  - メールは1通のみ届くこと（二度お手間をかけることのないよう、ここで #7193 の確認も兼ねられればと思います）
- [ ] 2回連続sadの日報が投稿されると管理者/メンターにメール/サイト内通知が届く
- [ ] ダッシュボードの「2回連続sadのユーザー」に反映されている

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2hhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbb2e9578a5f84f8aedd1221e25de9045616ac93/image.png)

### ユーザー新規登録時の処理
- [ ] ユーザーが新規登録すると購読解除トークンが生成されていることを確認する

### ユーザー卒業時の処理
- [ ] 管理者/メンターにユーザー卒業のメール/サイト内通知が届くことを確認する

### ユーザー退会
- [ ] 退会ユーザーについて、以下を確認する
  - WIP中の日報が存在しないこと
  - 未確認の提出物が存在しないこと
  - 就職活動中のステータスがOFFになっていること

------

以下は、別途Discordからご連絡をさせていただきます🙏

### 相談部屋の通知関連
- [ ]  相談部屋のコメント投稿時の処理
  - 相談部屋にコメント投稿があるとメール/サイト内通知が届くことを確認する
  
=>相談部屋にコメントを投稿しましたら別途Discordからご連絡いたします🙇‍♀️

### Q＆A関連
- [ ] 質問投稿があると、メール/サイト内通知が届くことを確認する
- [ ] 質問投稿があると、Watch中になっていること
- [ ] AI生成された回答が表示されること

 =>質問を投稿しましたら別途Discordからご連絡いたします🙇‍♀️

### Docs投稿関連
- [ ] Docsが投稿されると、メール/サイト内通知が届くことを確認する

 =>Docsを投稿しましたら別途Discordからご連絡いたします🙇‍♀️

## 2. 質問
### Learningのキャッシュ削除処理の動作確認について
先日の開発Mtgでご教示いただいた`logger`を利用した確認方法ですが、
以下の認識で相違ないでしょうか👀？

1. 以下、`app/models/learning_cache_destroyer.rb`に`Rails.logger.info 'LearningCacheDestroyer called'`を追記したPRを出す

https://github.com/fjordllc/bootcamp/blob/00faadedb1027f1c5c6b212f1d758695997b7306/app/models/learning_cache_destroyer.rb#L1-L8
 
2. 1がマージされた後、ユーザー削除が発生した際に`'LearningCacheDestroyer called'`がログに残っているかkomagataさんとmachidaさんに確認のご依頼をする

## 3.  ご共有
### お知らせの通知について
- [ ] お知らせを投稿した際にサイト内/メール/Discordで対象者に通知が届くこと
- [ ] お知らせが削除されると通知が[お知らせの通知ページ](https://bootcamp.fjord.jp/notifications?status=unread&target=announcement)から削除されること

上記の動作確認について、
以前に影響範囲が広いことから確認なしにされていた[やりとり](https://github.com/fjordllc/bootcamp/issues/5493)を拝見したため今回も確認は割愛しようかと考えております🙇‍♀️

**Comment by komagata** [comment]
@2525nicole 

### 確認項目について

すぐには起きない事象も入っているので、僕らでそれが起きた時に確認していきます。
@2525nicole さんの方は急がないで大丈夫なので気長に待っていていただければありがたいです〜。

> 先日の開発Mtgでご教示いただいたloggerを利用した確認方法ですが、
> 以下の認識で相違ないでしょうか👀？

はい、相違ないです。

> 以前に影響範囲が広いことから確認なしにされていたhttps://github.com/fjordllc/bootcamp/issues/5493を拝見したため今回も確認は割愛しようかと考えております🙇‍♀️

OKです〜！

**Comment by 2525nicole** [comment]
@komagata 
早速のご確認ありがとうございます🙇‍♀️
承知いたしました！
引き続きお手数をおかけしますが、よろしくお願いいたします🙇‍♀️

また`logger`とお知らせの動作確認の件もご回答ありがとうございました🙏
`logger`追加のPR作成進めてまいります💡

**Comment by 2525nicole** [comment]
@komagata @machida 
## 【ご依頼】ステージング環境での動作確認について
本Issueのうち、以下処理のステージング環境での動作確認をお願いできますでしょうか🙏

### 対象の動作：Learningのキャッシュ削除処理
#### 確認いただきたいこと
- ユーザー`muryou`がプラクティスのステータスを「着手」に変更した際（本日1/29　18:14）
- ユーザー`muryou`が削除された際（本日1/29　18:16）

上記それぞれ実行されたタイミングでログに`"[LearningCacheDestroyer] Cache destroyed for user #746986380"`と出力されているかご確認をお願いたします🙇‍♀️

すぐにご確認可能なタイミングで再度動作が必要などありましたらご教示いただけますと幸いです🙏
お手数をおかけしますが、どうぞよろしくお願いいたします！

**Comment by komagata** [comment]
@2525nicole ステージング環境のログに書かれていたことを確認しました〜。

![スクリーンショット 2024-01-30 14 08 07](https://github.com/fjordllc/bootcamp/assets/16577/d1351ad5-c9aa-4654-87be-753f4d169eaa)

**Comment by 2525nicole** [comment]
@komagata 
お忙しいところご確認ありがとうございました🙇‍♀️！
ステージング環境での動作確認完了とさせていただきます🫡

**Comment by komagata** [comment]
@2525nicole 相談部屋にコメントするとメール／サイト内通知がくることを確認しました〜

**Comment by 2525nicole** [comment]
@komagata 
無事届いていたようで安心いたしました🙏
お忙しいところご確認ありがとうございます🙇‍♀️！
