### ISSUE TITLE
管理画面からFAQを登録したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6627]
![スクリーンショット 2023-06-21 21 33 45](https://github.com/fjordllc/bootcamp/assets/16577/b3d8acc4-0e7a-4fc3-9461-7549aaf7fef9)

`/faq`ここのFAQを管理画面から登録できるようにしたい。

- [x] 管理画面 FAQ一覧ページ
- [x] 管理画面 FAQ個別ページ
- [x] 管理画面 FAQ登録ページ
- [x] 管理画面 FAQ編集ページ
- [x] 管理画面 FAQ削除機能
- [x] FAQ一覧（DBから表示する）

**Comment by yuma-matsui** [comment]
@komagata 

テーブル設計の方針について相談です。
下記に考え得る2つの案とそれぞれのメリット・デメリットをまとめましたのでご確認の上アドバイスを頂けますでしょうか。

## 案1

### FAQs
| カラム名 | データ型 | 制約                          | 説明     |
| -------- | -------- | ----------------------------- | -------- |
| question | text     | null: false, uniqueness: true | 質問内容 |
| answer   | text     | null: false, uniqueness: true | 回答内容 |

### メリデメ
#### メリット
- 1つのテーブルで済むので実装が容易
- CURDのロジックも容易に実装ができる

#### デメリット
- 将来的に「回答に対する質問」というデータを追加したくなった場合にテーブルの再設計が必要になりそう

## 案2

### Questions
| カラム名 | データ型 | 制約                          | 説明     |
| -------- | -------- | ----------------------------- | -------- |
| content  | text     | null: false, uniqueness: true | 質問内容 |

#### Association
- has_one: answer

### Answers
| カラム名    | データ型 | 制約                           | 説明     |
| ----------- | -------- | ------------------------------ | -------- |
| content     | text     | null: false, uniqueness: true  | 回答内容 |
| question_id | integer  | null: false, foreign_key: true |          |

#### Association
- belongs_to: questions

### メリデメ
#### メリット
- データの変更に強い

#### デメリット
- 2つのレコードを同時に保存するためにフォームオブジェクト等を用意する必要がありそう

**Comment by yuma-matsui** [comment]
もう2点確認です。

- FAQに関する機能は管理ページのタブに「FAQ」を追加する方針でよいか

![image](https://github.com/fjordllc/bootcamp/assets/70259961/7e4e958c-8754-4ceb-af3d-3611c5360fc4)

- メーンターぺージにも同様に追加する必要があるか

![image](https://github.com/fjordllc/bootcamp/assets/70259961/df7c7462-b1a5-4a13-9e33-bb475eef7a42)

**Comment by machida** [comment]
@yuma-matsui 

FAQは複雑な階層になることはなく、常に一問一答の形を取るので、案1  でお願いしますー🙏

---

FAQに関する機能は管理ページのタブに「FAQ」を追加でお願いします🙏
あと、ごめんなさい、管理者・メンターが投稿できるようにと言ったのですが、今回は管理者だけに変更でお願いします🙏
のちほど、メンターも投稿できるようになったほうがいい、となったらメンターも投稿できるようにしたいと思います。
なので、タブは管理ページのみでお願いします。

**Comment by yuma-matsui** [comment]
回答ありがとうございます！！

> 案1 でお願いしますー🙏

> 今回は管理者だけに変更でお願いします🙏

上記2点承知しました。
実装進めます💪

**Comment by yuma-matsui** [comment]
@machida 

追加で確認させていただきたいことが出てきました！
回答文言が別ページへのリンクを含んでいる場合について考慮することを漏れていました...。
このリンクをどう扱うかについての2つ案を考えてきたのでご確認をお願いします。

![image](https://github.com/fjordllc/bootcamp/assets/70259961/e087cba5-fd41-4747-8708-fec69391bab0)

## 案1
リンクを含む文言はその都度viewファイルにベタ書きする。
方針としてはFAQのanswerカラムから特定の文字列を検索して、リンクに置き換えるメソッドを用意する

### メリット
- 実装が楽
### デメリット
- リンクを含む回答が増えてきた場合に管理が大変（特定の文言、リンクのURLを定数として追加していく必要がある）

##  案2
FAQsテーブルに関連するLinksテーブルを作って、リンクを含むFAQの場合はFAQ作成時に同時にLinkレコードも作成する。

### メリット
- リンクが増えた場合にも管理が比較的楽

### デメリット
- 実装がやや複雑になりそう

*
ユーザー向けの機能ではないですし、リンクを含む文言がそこまで増えることもないような気がするので１でいいような気もしますが、念の為確認させていただきました。

よろしくお願いします。

**Comment by machida** [comment]
@yuma-matsui すいません、連絡漏れでした。FAQのanserの方はMarkdownが使えるようにしていただきたいですー。リンクはMarkdownで書くようにしたいと思います。

**Comment by yuma-matsui** [comment]
@machida 
了解しました！
ありがとうございます。

**Comment by yuma-matsui** [comment]
@machida 

[こちら(FAQ一覧ページ)](https://bootcamp.fjord.jp/faq)で表示させるFAQは管理者側で順番を変更できた方が良いですよね？
その場合、プラクティスの順番変更と同じ仕様（ドラッグ&ドロップで順番変更できる）で実装をする方針でよろしいでしょうか？

**Comment by machida** [comment]
@yuma-matsui おおー、順番変更ができると助かります！！

**Comment by yuma-matsui** [comment]
さてさて、大掛かりになってきましたね〜😁笑
頑張ります💪
