### ISSUE TITLE
特別・定期イベントの両方で権限のないユーザーが編集できてしまう

### ISSUE THREAD

**Issue by ymmtd0x0b** [fjordllc/bootcamp#6634]
## 概要

作成済みの特別・定期イベントを編集可能なのは 作成者/メンター/管理者(+ 定期イベントのみ主催者) のみだが、URLから直接編集画面へアクセスすると権限のないユーザーも編集可能になってしまう

### 特別イベントの再現手順

1. `kimura`でログイン ( 管理者・メンター以外ならだれでもOKです )
2. [募集期間中のイベント(補欠者あり)](http://localhost:3000/events/626726618) へアクセスし、`内容修正ボタン` が表示されていない事を確認 ( ログインユーザーが作成者以外のイベントならどれでもOKです )
3. URLの末尾に `/edit` を追記して Enter を押す
4. 編集画面が表示される事を確認 
5. 適当に内容を変更し、`内容変更ボタン` をクリックする
6. 変更が反映されている事を確認

### 定期イベントの再現手順

特別イベントの再現手順 2.を次の内容で読み替えて下さい

2. [開発MTG](http://localhost:3000/regular_events/459650222) へアクセスし、`内容修正ボタン` が表示されていない事を確認 ( ログインユーザーが作成者以外のイベントならどれでもOKです )

## 期待される振る舞い

権限の無いユーザーからは編集できないようすべきだと考えています。

## 解決方法

日報のようなフィルタを特別・定期イベントのコントローラーに追加すれば解決可能だと思っています。

https://github.com/fjordllc/bootcamp/blob/dda6dcab455e507f6dc7602b06dfc1301fbe6cd1/app/controllers/reports_controller.rb#L8

https://github.com/fjordllc/bootcamp/blob/dda6dcab455e507f6dc7602b06dfc1301fbe6cd1/app/controllers/reports_controller.rb#L102-L105

### 特別イベントの権限

| | 管理者・メンター以外 | 管理者・メンター |
| -- | -- | -- |
| 作成 | ○ | ○ |
| 編集 | ○[^1] | ○ |
| 公開 | × | ○ |
| 削除 | ○[^1] | ○ |

### 定期イベントの権限

| | 管理者・メンター以外 | 管理者・メンター |
| -- | -- | -- |
| 作成 | ○ | ○ |
| 編集 | ○[^2] | ○ |
| 公開 | ○ | ○ |
| 削除 | ○[^2] | ○ |

[^1]: 作成者のみ可能
[^2]: 作成者と主催者のみ可能

**Comment by fuwa-syugyo** [comment]
@komagata 
お疲れ様です。
仕様について確認させていただきたいところがあります。

定期イベントの権限について、編集or削除ができるのはメンター、主催者、作成者のいずれかと上記issueに記載があります。
現状を確認したところ、主催者でない作成者では「削除」と「内容修正」のボタンが表示されていないようです。
(画像は主催者がtomomiで作成者がhajimeで、hajimeでログインしたときの画面です)
![image](https://github.com/fjordllc/bootcamp/assets/62344131/86d64100-0e2f-4098-9b04-9a94cc6201c8)

issueの仕様に合わせて作成者でも「削除」と「内容修正」のボタンを表示するようにするか、表示は現状のままで作成者は編集の権限をなくすかのどちらかに統一した方が良いかと思うのですがいかがでしょうか？

お手数ですがご確認よろしくお願いいたします。

**Comment by ymmtd0x0b** [comment]
@komagata ( CC: @fuwa-syugyo )
すみません🙏
おそらく私が調査した当時は「主催者ではない作成者」のパターンを確認していなかったみたいです。

再度確認したところfuwaさんがコメントされている通り"主催者ではない作成者には「削除」と「内容修正」のボタンは表示されない"が正しいです。

つまり、現状の定期イベントの編集権限のあるロールは

- 誤：作成者 / 主催者 / メンター / 管理者
- 正：主催者 / メンター / 管理者 ( ※作成者であっても主催者に含まれない場合は編集できない )

が正しい認識になります。

Issueの概要文が正確性を欠いている状況ではありますが、上記のkomagataさんのコメント通り『作成者でも「削除」と「内容修正」のボタンを表示するようにする』方向で問題ないか、再度判断をお願いしたいです🙇‍♂️

#### 📝補足

以前は主催者の概念が無く作成者に編集権限があったようですが、主催者に編集権限を与える変更を行う際に作成者が含まれなくなったみたいです。

- https://github.com/fjordllc/bootcamp/issues/6014
- [変更箇所](https://github.com/fjordllc/bootcamp/pull/6049/files#diff-69d7e288d5b765a72ce26c174ce06f4c1c8407bc4c7f5903712f056ac78da028)

**Comment by fuwa-syugyo** [comment]
@ymmtd0x0b  cc @komagata 
お疲れ様です！
MTで駒形さんに相談したところ、「作成者は自動的に主催者にする」という処理を行うことになりました。
ご確認いただきありがとうございます！

**Comment by fuwa-syugyo** [comment]
以下を本番で確認したのでクローズします。
* 権限のないユーザーが編集ページにアクセスできないこと
*  定期イベントの作成者が自動的に主催者に追加されること
