### ISSUE TITLE
企業ページの日報一覧が２重に表示されている

### ISSUE THREAD

**Issue by ymmtd0x0b** [fjordllc/bootcamp#6638]
## 概要

企業ページにて、その企業所属のユーザーが作成した日報一覧が２重に表示されています。

## 再現手順

1. [企業一覧](https://bootcamp.fjord.jp/companies) にアクセス
2. 任意の企業へアクセス
3. "日報タグ"をクリック
4. 同じ内容の一覧が２つ表示されている事を確認

## 期待される振る舞い

一覧表示は１つであるのが正常だと思いますので、どちらか一方は表示されないようにしたいです。

## スクリーンショット

※開発環境の画像になります

<img src="https://github.com/fjordllc/bootcamp/assets/95903475/41212676-57a4-415d-8d2a-96cb970961ec" width="500">

## 原因

該当ビューファイルにて、Vue.js と React のコンポーネントが両方とも有効になっている事が原因と思われます。

どちらを無効にすべきかの判断に自信がないため、指示を頂けますと幸いです。

https://github.com/fjordllc/bootcamp/blob/23e3eb8538f99c3607a4b160830093bb1b0e6583/app/views/companies/reports/index.html.slim#L16-L18

**Comment by komagata** [comment]
:memo: Vue.jsからReactへの移行中なのでVue.jsの方を消すやり方でお願いします。

**Comment by Kassy0220** [comment]
こちら本番環境で確認できましたので、closeいたします〜🙌
