### ISSUE TITLE
メンターが提出物の確認を取り消しても、提出者のプラクティス一覧画面で修了と表示される

### ISSUE THREAD

**Issue by monyatto** [fjordllc/bootcamp#6642]
## 概要

提出物の確認を取り消してもプラクティス一覧画面で修了になっています。

## 再現手順

1. ID`hajime`で http://localhost:3000/products/1071056610 にアクセスして提出物を作成。
2. ID`machida`で上記の提出物の担当になる。
3. 「提出物を確認」ボタンをクリック後、同画面に表示される「提出物の確認を取り消す」をクリック。
4.  ID`hajime`で http://localhost:3000/courses/829913840/practices#category-533964039 にアクセスすると該当のプラクティスが「修了」になっている。

## 期待される振る舞い
「提出物の確認を取り消す」を押したら、ステータスが「着手」に戻る。

## 考えれる原因
提出物の進行状態を管理しているのはLearning のstatusかと思いますが、「提出物の確認を取り消す」を押しても、完了（complete）のままになっているようです。

## スクリーンショット
<img width="795" alt="image" src="https://github.com/fjordllc/bootcamp/assets/83024928/6dc4dcbd-bbdc-409b-be28-663757a8a2b8">

## 関連Issue

Ref: #6508 こちら対応中に発見しました。

**Comment by reckyy** [comment]
@komagata @machida 
お疲れ様です。こちら現在でも確認できる現象かご確認をお願いしたいです。
私の手元では再現できませんでした。（私の使っているブラウザArcが原因の可能性は排除済みです。Chromeでも再現できませんでした。）
よろしくお願いいたします。

## 方法
再現手順の1が、恐らく少し省略されているので変更し実行しました。

> ID `hajime` で http://localhost:3000/products/1071056610 にアクセスして提出物を作成。

はすでにWIPの提出物がある想定のリンクだと思います。実際アクセスしてもそのidのproductがないのでエラーになりました。
なので、以下の方法を実行しました。
1. `hajime`でログイン後、http://localhost:3000/practices/315059988 にアクセスし提出物を作成。
（アクセスし、一旦WIPしてから作成、という方法も念の為試しました。）

2以降は同じなので割愛します。

**Comment by reckyy** [comment]
@komagata @machida 
お疲れ様です。
下記手順では本Issueの現象を再現することができました。
こちらが
- 望まれた仕様でないかどうか
- 解決に取りかかっても良いか

ご確認をお願いいたします。

## 再現手順
1. ID `hajime` でログイン後、http://localhost:3000/practices/315059988 にアクセスし提出物を作成。
2. ID `machida` で上記の提出物の担当になる。
3. **コメントを打ち込み、「確認OKにする」をクリック後**、同画面に表示される「提出物の確認を取り消す」をクリック。
<img width="860" alt="スクリーンショット_2024-02-03_16_52_56" src="https://github.com/fjordllc/bootcamp/assets/106903482/1291d410-90cb-4d33-8621-3d248306ea80">


4. ID `hajime` で http://localhost:3000/courses/829913840/practices#category-533964039 にアクセスすると該当のプラクティスが「修了」になっている。
<img width="954" alt="スクリーンショット_2024-02-03_16_53_40" src="https://github.com/fjordllc/bootcamp/assets/106903482/5f8041c4-77ac-49c9-91f4-e845893d7d19">
開いても修了したままでした。
担当を外れても結果は同じでした。
<img width="954" alt="スクリーンショット_2024-02-03_16_54_21" src="https://github.com/fjordllc/bootcamp/assets/106903482/d89643a6-2a31-46ae-8b75-056feeae8168">

**Comment by komagata** [comment]
@reckyy 

> 望まれた仕様でないかどうか（メンターではないことから、正規の提出物確認方法がわからないため確認です。）

望まれた仕様でないです。

> 解決に取りかかっても良いか

はい、お願いします。

## 一般的な提出物の確認

> （メンターではないことから、正規の提出物確認方法がわからないため確認です。）

念の為お伝えしておきます。

- 一般ユーザーで提出物を作る。
- メンターのユーザーで「提出物ページ」に行き、「提出物を確認ボタン」を押す。

**Comment by reckyy** [comment]
メモ。
https://github.com/fjordllc/bootcamp/issues/6642#issuecomment-192519647時点では、再現できなかったが、今同様の手順で再現できた。
そのため、両方対応する。

**Comment by reckyy** [comment]
@komagata @machida 
お疲れ様です。こちらのIssueにつきまして、本番環境での動作確認についてお伺いしたいです。
本番確認のためのテストデータについて、存じ上げないので推測ではあるのですが、

- 生徒のテストデータを用いて提出物を作成し、お二方どちらかがその提出物を確認→取り消し。
生徒側でプラクティスのステータスが「提出」になっていることを確認。

上記の認識で間違いないでしょうか。
お手数をおかけしますが、ご確認の程宜しくお願いいたします。

**Comment by komagata** [comment]
@reckyy 遅くなって大変もうしわけありません。
本番環境で正しく動作することを確認しました～🎉
