### ISSUE TITLE
新しい形式のDiscordユーザー名を設定できるようにする

### ISSUE THREAD

**Issue by sadanora** [fjordllc/bootcamp#6646]
## 概要
Discord側でユーザー名の形式に仕様変更があったため対応が必要。
現在ブートキャンプアカウントの登録情報には、末尾に`#４桁の数字`を含まない形式のDiscordアカウントは登録できないため、登録できるようにする。

### Discord側の仕様変更
これまでDiscordのユーザー名の形式は必ず`ユーザー名#4桁の数字`でした。
(`#4桁の数字`はDiscord公式ブログでは「識別子」と呼ばれているようなので、このissue内でも「識別子」と呼ぶことにします。)

しかしDiscordからユーザー名の仕様変更についてアナウンスがあり、今後はユーザー名に識別子を含まないことになったようです。
詳しくは以下参照
[新しいユーザー名 & 表示される名前 – Discord](https://support.discord.com/hc/ja/articles/12620128861463)
[Discordにおけるユーザー名の進化](https://discord.com/blog/usernames)

ブートキャンプアプリ側の挙動として、「識別子を含まないDiscordユーザー名を登録できない」ことはこれまでは正しい挙動だったと思いますが、上記Discordの仕様変更にあわせて、識別子を含まないDiscordユーザー名を登録できるようにする必要があると思います。

## 再現手順
1. 任意のブートキャンプアカウントでログイン
1. 登録情報変更ページ`/current_user/edit`にアクセス
1. Discordアカウントの項目に、識別子を含まないDiscordユーザー名（`kimura`など）の項目を入力し、`更新`ボタンをクリック
1. エラーが表示される
<img width="983" alt="Screenshot 2023-06-16 at 12 27 21" src="https://github.com/fjordllc/bootcamp/assets/66685066/71ff3a3a-abd1-4100-b9c8-e0356a65036b">

## 期待される振る舞い
識別子を含まない形式のDiscordユーザー名が登録できる。

**Comment by machida** [comment]
📝 
識別子が入っていないといけない、というバリデーションを削除する。

**Comment by machida** [comment]
本番で確認が済んでいるのでクローズにします。
