### ISSUE TITLE
提出物を作成したときと更新したときで通知の文面を変えたい

### ISSUE THREAD

**Issue by monyatto** [fjordllc/bootcamp#6647]
現在、提出物の作成と更新のどちらでも`〇〇さんが「×××」の提出物を提出しました。`という文面になっている通知があります。
更新の場合は`〇〇さんが「×××」の提出物を更新しました。`という文面に変えたいです。

以下の二つの通知が対象になります。
- 提出物が作成or更新された際に、そのプラクティスをwatchしているメンターに飛ぶ通知
- 企業の研修生が提出物を作成or更新した際に、同じ企業に属しているアドバイザーに飛ぶ通知

関連issue: #6327（このissueを進めているときに発見しました）

**Comment by Kassy0220** [comment]
@monyatto 
お疲れ様です🍵
更新時の通知に関して一つ確認したいことがあります。

提出物を更新した際、通知の文面を`〇〇さんが「×××」の提出物を更新しました。`に変更することが求められています。

次の場合は`〇〇さんが「×××」の提出物を提出しました。`の文面のままで良いのではないかと考えたのですが、この場合も文面を変更した方が良いでしょうか？

+ 提出物をWIPで保存する → 提出物を提出する

はるまきさんのご意見を伺いたいです🙏

**Comment by monyatto** [comment]
@Kassy0220 
お疲れさまです！

>次の場合は〇〇さんが「×××」の提出物を提出しました。の文面のままで良いのではないかと考えたのですが、この場合も文面を変更した方が良いでしょうか？
>
>提出物をWIPで保存する → 提出物を提出する

提出物をWIPで保存した場合は通知が飛ばない仕様になっています。

以下が該当箇所です。
https://github.com/fjordllc/bootcamp/blob/31d7a1386e3c6c808ac68f4f90c9a828de4aaf32/app/models/product_notifier_for_colleague.rb#L12
https://github.com/fjordllc/bootcamp/blob/31d7a1386e3c6c808ac68f4f90c9a828de4aaf32/app/models/product_notifier_for_practice_watcher.rb#L5

なので、以下の動作が良いのではないかと思います。
`（提出物が未提出の状態で）提出物をWIPで保存する → 提出物を提出する`の場合は更新ではなく初回の提出に該当。
`（提出物が提出済みの状態で）提出物をWIPで保存する → 提出物を提出する`は更新に該当。

不明点などあればまたご連絡ください！
よろしくお願いいたします🙏

**Comment by Kassy0220** [comment]
@monyatto 
詳細なご回答ありがとうございます！
WIPで保存した時の通知について把握することができました🙏

次のように実装したいと思います。

+ 提出物をWIPで保存 → 提出した場合
  + 提出物をWIPで保存(通知が飛ばない)
  + 提出物を提出(`〇〇さんが「×××」の提出物を提出しました。`の通知が飛ぶ)
+ 提出物を提出 → 提出物をWIPで保存 → 提出物を提出した場合
  + 提出物を提出(`〇〇さんが「×××」の提出物を提出しました。`の通知が飛ぶ)
  + 提出物をWIPで保存(通知が飛ばない)
  + 提出物を提出する(`〇〇さんが「×××」の提出物を更新しました。`の通知が飛ぶ)

**Comment by komagata** [comment]
@Kassy0220 こちら本番環境で確認しました〜！

**Comment by Kassy0220** [comment]
@komagata 
返信遅れて申し訳ありません、ご確認ありがとうございました🙏
本番環境で確認が取れましたので、こちらCloseいたします〜！
