### ISSUE TITLE
プロフィール欄に「使用しているエディタ」を追加する

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6650]
## 機能の説明

プロフィール欄に「使用しているエディタ」を追加する

## 何故この機能が必要なのか

メンターとして「エディタの設定、ちゃんとやってますか？」みたいな話をするときに、受講生の使っているエディタが事前にわかっていた方が自信をもってコメントしやすくなるため。
（8割方VSCodeだろう、と思いつつ、100%そうとは言えないので微妙にコメントしづらい）

## その他
- 選択式ではなく、自由入力で良さそう
- 入会時点では「エディタって何？」ということも多いと思うので、最初は「わからなければ空欄のままでもOKです」としておいて、Rubyのプラクティスあたりで「プロフィール欄に使用しているエディタを更新して下さい」みたいに指示すると良いかもしれない

**Comment by machida** [comment]
/current_user/edit に 「使用しているエディタ」を追加する。

会員登録時（new）の時点では、非表示にする。
受講生、研修生のみ、edit のときは表示する（入力は任意）。

- VSCode
-RubyMine
- Vim
- Emacs
-その他

をラジオボタンで選択。
その他を選択したときだけ、 text input が表示され、自由入力をする。

**Comment by machida** [comment]
ユーザー個別ページ（show）にエディタを表示する。

<img width="915" alt="貼り付けた画像_2023_12_13_17_35" src="https://github.com/fjordllc/bootcamp/assets/168265/3b0d838d-84da-438e-9484-8ed5dd301212">

一旦この辺に表示する。

**Comment by 88-99** [comment]
@machida 

大きく2点、質問させていただけますでしょうか。

 1点目は、
https://github.com/fjordllc/bootcamp/issues/6650#issuecomment-1853479206
> 一旦この辺に表示する。

とあり、「修了プラクティス」と「合計学習時間」の間に実装するようご指示されています。
私の考え違いで「合計学習時間」と「区分」の間に実装してしまいました。（この辺とあるので）そのままでも問題ないでしょうか？
個人的な意見として恐縮ですが、「修了プラクティス」と「合計学習時間」はセットのように考えていました。

2点目は、
スタイルの適用に取り組んでいます。
既存の`class`（例えば`a-form-label`）を調べたところ、`app/javascript/stylesheets/atoms/_a-form-label.sass`のファイルに実装されているようだとわかりました。
質問としては、以下の点をよろしければご教示いただけないでしょうか。
- ディレクトリ名の`atoms`はどのような意味なのか。英語には原子という意味があるようでした。
- `_a-form-label.sass`はなぜ頭に`_a`を付けているのか。
- スタイルの適用はスペース（画像に矢印で示した部分）の調整をしたいと考えています。`app/javascript/stylesheets/atoms/`配下に同じようにファイルを作成して`class`を定義する形でよろしいでしょうか？

#### 【実装状況】
<img src="https://github.com/88-99/ProductX/assets/83388876/04cbc90d-bad6-4102-aa3a-cef65fb6ad11" alt="Image from Gyazo" width="70%">

お手数おかけしますが、お願いいたします🙇‍♂️

**Comment by 88-99** [comment]
本番環境で確認できましたのでcloseします。
