### ISSUE TITLE
日報一覧の user-role の class の表示が壊れている。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6654]
http://localhost:3000/reports
日報一覧の各日報にあるユーザーアイコンを囲っている span タグの class がおかしい。

<img width="643" alt="貼り付けた画像_2023_06_20_0_03" src="https://github.com/fjordllc/bootcamp/assets/168265/6fd6484e-8c0a-4991-b1d8-119d128a8893">

修正したら再発を防ぐためにテストも書くようにお願いします。

**Comment by sochi419** [comment]
本番環境で確認が取れたので、closeします。
