### ISSUE TITLE
休会から復帰したら、相談部屋へメッセージを投稿したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6656]
休会から復帰したら、komagataアカウントで相談部屋へメッセージを投稿する。

```
お帰りなさい！！複会ありがとうございます。
休会中に何か変わったことがあれば、再びスムーズに学び始めることができるように全力でサポートします。何か困ったことや質問があれば、遠慮なくご相談ください。

またフィヨルドブートキャンプの Discord のサーバーに入室できるように、再度、Doc にある Discord の招待 URL にアクセスをお願いします。
https://bootcamp.fjord.jp/practices/129#url
```

相談部屋へメッセージを投稿する機能の参考
https://github.com/fjordllc/bootcamp/pull/5959
https://github.com/fjordllc/bootcamp/pull/6494

**Comment by komagata** [comment]
@machida これいいっすね！

**Comment by monyatto** [comment]
@komagata @machida 
こちら「休会から復帰したら相談部屋にメッセージが送られているか」という内容で動作確認をお願いしたいです🙏
なにか私の方で必要な作業等ありましたらご教示ください！

**Comment by komagata** [comment]
@monyatto 実際に復帰した人がいて、相談部屋にメッセージが送られることを確認しました〜。

![スクリーンショット 2023-08-26 15 30 32](https://github.com/fjordllc/bootcamp/assets/16577/854a06e2-3135-4c0a-a8b0-7891b516e2ca)

**Comment by monyatto** [comment]
@komagata 
ご確認ありがとうございます！　closeします〜！
