### ISSUE TITLE
提出物、お知らせ、特別イベント、定期イベント、Doc を WIP で保存した場合、ページ遷移はしないでほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6658]
現在、提出物、お知らせ、特別イベント、定期イベント、Doc を WIP で保存した場合、showに遷移する。showに遷移せずに form ページのままでいてほしい。間違えて消さないように保存をしながら入力をしたいため。

( 2023/07/14 追記 )
質問・雑談タイムにて駒形さんに確認をし、質問をWIPで保存した場合に関しては、変更せずそのままで良いということになりました。
そのため、Issueのタイトルと概要から「質問」を削除しています。
※ 質問は`edit`ページが無く、`new`ページ上でVueを使って編集フォームが実装されているため

**Comment by Kassy0220** [comment]
@komagata @machida 
お疲れ様です！
すみません、こちらのIssueについて一つ確認したいことがあります。

Issueの概要に書かれていることに加えて、日報とDocをWIPで保存した時の挙動を確認したところ、次のようになりました。
+ 日報 : editページに遷移
+ Doc : showページに遷移

DocをWIPで保存した際もshowに遷移することが確認されたため、Doc保存時の挙動も一緒に変更しようと考えているのですが、大丈夫でしょうか。
ご確認をよろしくお願いいたします。

( DocをWIPで保存時のスクショ )
<img width="532" alt="メモ" src="https://github.com/fjordllc/bootcamp/assets/79003082/b2cfc83f-200f-451a-b36b-9ab026ea63c8">

**Comment by machida** [comment]
@Kassy0220 すいません、Docが抜けてました🙇‍♂️Docも同じようにお願いします🙏

**Comment by Kassy0220** [comment]
@machida 
ご確認ありがとうございます！Docの場合も変更いたします🙆‍♂️
Issueのタイトルと説明にもDocを追加しました。

**Comment by Kassy0220** [comment]
@komagata @machida 
お疲れ様です！

すみません、こちらのIssueに関してもう一つ質問があります。

実装方法として次の2つを考えたのですが、どちらの実装方法が良いでしょうか？
1. `reder`でページを表示する
2. `redirect_to`でformのあるページに移動する


2の方法を考えていたのですが、それだと「ページ遷移はしない」ことに背くことに気づき、確認することにしました。
ちなみに、日報をWIPで保存した際はeditページにリダイレクトするようになっています。

```ruby
  def create
    @report = Report.new(report_params)
    @report.user = current_user
    set_wip
    canonicalize_learning_times(@report)
    if @report.save
      Newspaper.publish(:report_save, @report)
      redirect_to redirect_url(@report), notice: notice_message(@report), flash: flash_contents(@report)
    else
      render :new
    end
  end

  # 日報がWIPか否かでリダイレクト先のURLを変更しています
  def redirect_url(report)
    report.wip? ? edit_report_url(report) : report_url(report)
  end
```

お手数ですが、ご確認をよろしくお願いいたします🙇🏻

**Comment by machida** [comment]
@Kassy0220 保存した後に表示されるページが編集ページであればOKなので、日報と同じでお願いしますー

**Comment by Kassy0220** [comment]
@machida 
ご確認ありがとうございます！

了解しました👍
日報と同じ処理で実装を進めます💨

**Comment by Kassy0220** [comment]
本番環境で動作確認ができましたので、こちらのIssueをcloseいたします〜！
