### ISSUE TITLE
ブログ記事のタグ入力をDocのタグ入力と同じUIにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6663]
メンター、管理者でログインし、
`/articles/new` にアクセス。

ブログ作成ページのタグ入力を、Docのタグ入力と同じにしたい。

<img width="673" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/66b3a0dd-5cc1-4363-aa38-67caaf477d93">

↑これを変更する。

参考 Docのタグ入力の実装のPR : https://github.com/fjordllc/bootcamp/pull/5942

**Comment by Kassy0220** [comment]
@komagata @machida 
当Issueに対応したPRが本番環境にマージされましたので、ご確認をお願いしたいです🙏
確認の手順は以下になります。

1. 記事作成ページ `articles/new` を開く
2. タグの入力フォームが、次の様になっていることを確認する
[![Image from Gyazo](https://i.gyazo.com/e43b72baf15b34f7a984d7eb0c43bbc1.gif)](https://gyazo.com/e43b72baf15b34f7a984d7eb0c43bbc1)

記事作成ページは管理者またはメンターしかアクセスできませんので、ご確認をよろしくお願いいたします🙇🏻

**Comment by machida** [comment]
@Kassy0220 本番で確認しましたー🙆‍♂️

**Comment by Kassy0220** [comment]
@machida 
ご確認ありがとうございます！🙏
こちら本番環境で確認できましたので、closeいたします〜
