### ISSUE TITLE
ユーザーアイコンを正方形で切り抜きたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6668]
画像サイズを強制的に 120px * 120px で切り抜くようにしてください。
長方形の画像の場合、短い方の辺を120pxにし、長い方の辺は中央で切り抜いてください。

### 1000px * 500px の画像の場合

500px の辺を基準に、500px の辺が120pxになるように縮小する。
そうすると、1000px の辺は 240px に縮小されるが、その際に 240px になった辺の中央で120pxに切り抜くようにしてください。
つまり、両端  60px ずつが切り捨てられます。

### 100px * 50px の画像の場合

50px の辺を基準に、50px の辺が120pxになるように拡大する。
そうすると、100px の辺は 240px に拡大されるが、その際に 240px になった辺の中央で120pxに切り抜くようにしてください。
つまり、両端  60px ずつが切り捨てられます。

**Comment by yocchan-git** [comment]
@umizaru さん、こちらのissueなのですがどうしましょうか？🤔

どちらが先にするか決める感じにしましょうか？
それとも、先に実装できた方が！という感じの方がよろしいでしょうか？

合わせますのでお手隙でご回答いただけますと嬉しいです🙏

**Comment by yocchan-git** [comment]
@machida さん、descriptionの記述ありがとうございます！
仕様について1点質問よろしくお願いいたします🙏

### 質問内容
正方形で切り抜く意図を教えていただけますと嬉しいです🙇‍♂️

### 現状
現状、ユーザー視点(ブラウザの表示)では120px * 120pxでくりぬけています。👍
ただ、Railsだけで切り抜くのは僕の技術力では解決できそうになくて、Sassのコードと連携して実装しています。

つまり、
- 最初の短い辺を基準にリサイズ→Rails
- そこから120*120で中央くり抜き→Sass(ブラウザ)

という感じの挙動になっています。😃

現状の変更したコードです
- [`user.rb`](https://github.com/fjordllc/bootcamp/pull/7431/files#diff-9802ca3c9c4cf89904fd44bc114e35ebdf2c5dd3d5b645491e2b253e1afef29b)ファイル
- [`_a-user-icon.sass`](https://github.com/fjordllc/bootcamp/pull/7431/files#diff-61fafaf9fb53749cf7c4f2126cb735bc43f09a17c7e9c4c0d12ae68a14fb49b6)ファイル

libvipsからブランチを切ったので、差分が分かりずらいですが変更は２つのファイルです。

ただ、目的がわからないのでこれでいいのか？🤔と思っています。

「いや、Railsで実装しろよ！」というお気持ちになっていることでしょう。おっしゃる通りです笑
僕の技術力では手詰まりでして...もしその場合は質問タイムなどで相談させていただきたいです。😢

### 試したこと
- 短い辺を基準にリサイズしてから、正方形にする💪
→そもそも、一つずつリサイズしていくのは不可能(つまり、流れるように一気にリサイズの必要がある)
   ただ、libvipsに変更したことで、一気にリサイズするメソッドがなくて...実装できませんでした

- `MiniMagick`を使用する
→オブジェクトがMiniMagickになって`ActiveStorage::`では無くなってしまうのと、URLのパスがnull byteになるみたくそもそも論で読み取れませんでした...🥲

他にもいろいろ試したのですが、どうにも画像の表示まで辿り着けずでして...😓
長文失礼致します。お手隙でご回答いただけますと嬉しいです🙏

**Comment by umizaru** [comment]
@yocchan-git 
ご連絡ありがとうございます🙏
ちょっと他のIssueに時間がかかりそうなので、もしよろしければ先に進めていただくことできますか？

**Comment by yocchan-git** [comment]
承知しました！連絡ありがとうございます🙏

**Comment by yocchan-git** [comment]
komagataさんのお陰様で解決しましたので、コメント削除しました

**Comment by yocchan-git** [comment]
本番環境確認OKでした！
