### ISSUE TITLE
管理者でログインしているとき、登録情報変更でアイコン画像を更新してもプレビューに変化が無い。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6669]
<img width="634" alt="貼り付けた画像_2023_06_22_17_12" src="https://github.com/fjordllc/bootcamp/assets/168265/6c4021e7-d9de-46be-b6d8-3a3af4928b12">

別の画像をアップロードしても、この画像が切り替わらない。

**Comment by yocchan-git** [comment]
@komagata さん
@machida さん

このバグなのですが、僕のローカルでは再現できずでして...
解消されていそうなのですが、お二人の環境ではいかがでしょうか？🙏

お手隙でご確認いただけますと嬉しいです🙇‍♂️

### 確認方法
1. mainブランチでサーバーを立ち上げる
2. 管理者としてログインする(例. username: `machida`, password: `testtest`)
3. http://localhost:3000/current_user/edit の画面にアクセスする
4. ユーザアイコンを変更してプレビューが変わるか確認する

### 動作確認
- [x] ユーザアイコンのプレビューが変更されるのを確認しました

[![Image from Gyazo](https://i.gyazo.com/321f9468b1ac37850a98281d1695fe93.gif)](https://gyazo.com/321f9468b1ac37850a98281d1695fe93)

**Comment by komagata** [comment]
@yocchan-git 僕も再現しませんでした〜。

**Comment by yocchan-git** [comment]
@komagata さん

なるほどです...ご確認いただきありがとうございます🙇‍♂️
ではこのissueはcloseって感じでよろしいでしょうか？

**Comment by komagata** [comment]
@yocchan-git machidaさんのたてたIssueですので、machidaさんに確認を取ってからでお願いします〜。

**Comment by yocchan-git** [comment]
@machida さん、

[再現できない](https://github.com/fjordllc/bootcamp/issues/6669#issuecomment-1951618017)件について、komagataさんの環境でも再現できなかったそうなので、issueはcloseしていただいてもよろしいでしょうか？

また、その分のissueを適当に入れていただけますと嬉しいです🙇‍♂️

**Comment by machida** [comment]
@yocchan-git すいません、いつの間にか修正されてました。
こちらクローズでお願いします🙏
Issueをすぐアサインしますー
少々お待ち下さいー
