### ISSUE TITLE
ヤフーメールに対してメール通知が届かない

### ISSUE THREAD

**Issue by ogawa-tomo** [fjordllc/bootcamp#6671]
## 概要

私はFBCにヤフーメール（@yahoo.co.jp）を登録しているのですが、以前は届いていたFBCからのメール通知（日報や提出物のコメント、お知らせなど）が最近は届いていません。
メールボックスを確認すると、最後にメール通知が来たのは2023年4月21日（金）でした。

ステージング環境でも再現しました。gmailにはメールが届くようです。

## 再現手順
ステージング環境にて、下記のPRの動作確認中に再現した。
https://github.com/fjordllc/bootcamp/pull/6479

1. kimuraでログイン（誰でもよい）
2. 登録情報変更ページから、メールアドレスを自分のyahooメールに変更したうえでメール通知をONにする
3. Q&Aページから適当な質問にアクセスして回答する
4. ログアウトし、3で回答した質問の質問者でログイン
5. 3で回答した質問にアクセスし、回答の「ベストアンサーにする」をクリック
6. 自分のyahooメールにメールが届いていないことを確認
7. 再びkimuraでログインし、メールアドレスを自分のgmailに変更する
8. 3~5の手順を繰り返し、自分のgmailにメールが届いていることを確認
## 期待される振る舞い
ドメインにかかわらずメールが届く

**Comment by JunichiIto** [comment]
参考）
下記ページの確認項目を全部確認して、それでもおかしければYahoo!に問い合わせが必要になりそう。

[届くはずのメールが届いてない](https://support.yahoo-net.jp/PccMail/s/article/H000007299)

あとは、メール送信サービスの管理画面のActivity等にメールの送信状態が表示されてるかもしれません。
（SendGridとかにはそういう機能がある）

**Comment by ogawa-tomo** [comment]
ありがとうございます！
たしかに、素直に考えればyahoo側の問題ですね。確認項目を見まして、該当しないようでしたので問い合わせをしました。

**Comment by machida** [comment]
@ogawa-tomo こちら、問い合わせをした結果この問題は解決されましたでしょうか？教えていただけると助かりますー🙏

**Comment by ogawa-tomo** [comment]
@machida @komagata 
すみません、こちら完全に放置してしまっておりました:bow::bow::bow:

まだ解決はしておりません。
問い合わせたところヤフーの担当者から返信がありまして、「担当部署にてお調べしましたが、お知らせいただいた送信元メールアドレスからメールを受信した形跡がありませんでした。」とのことでした。

また、さらなる調査に必要とのことで、以下のいずれかの情報を取得できないかと聞かれました。
・送信済みメールの詳細ヘッダー全文
・メール送信した際の送信ログ（詳細日時、送信元ドメイン等を含む）

直近で私だけに送信されたはずのメール通知としては、7/30（日）7:10の下記コメントがあります。
https://bootcamp.fjord.jp/products/16762#comment_138789
このときのサーバーログを取得するなどして、上記いずれかの情報を入手することは可能でしょうか？

お手数おかけしますがよろしくお願いします:bow:

**Comment by machida** [comment]
@ogawa-tomo 状況の共有ありがとうございます🙏 ログの方はkomagataさんにお願いしたいと思いますー
