### ISSUE TITLE
Talksテーブルの`unreplied`カラムを削除する

### ISSUE THREAD

**Issue by OdenTakashi** [fjordllc/bootcamp#6673]
[ \#6393](https://github.com/fjordllc/bootcamp/pull/6393)こちらのPRでTalksテーブルの`unreplied`カラムのデータをTalksテーブルに新しく作成した`action_completed`カラムへ移行する作業を行っています。
なので、このPRがマージされた後に`unreplied`カラムを削除します。

関連Issue: [ \#6372](https://github.com/fjordllc/bootcamp/issues/6372)

**Comment by omochiumaiumai** [comment]
こちらのIssueはリリースが完了したためcloseします。
