### ISSUE TITLE
FireFoxの場合、Markdownエディタにフォーカスしているときでも⌘Sを打つと保存ダイアログが出てしまう。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6675]
Markdownエディタにフォーカスしているときに⌘Sを打つと、WIPで保存される機能がある。

しかし、FireFoxで⌘Sを打つと、の保存アイアログが表示されてしまう。
FireFox以外のブラウザでは、保存アイアログが出る機能がエディタ内では無効になってる。
Firefoxではそうはなっていない。

**Comment by a-kuroki-gs** [comment]
@komagata @machida 
お疲れ様です！
先ほど振っていただいたばかりのissueですが、１点質問です。
このissueの状況が現在再現できておりませんので、実行環境・実行方法を確認していただきたいです。

PC：Windows(`⌘S` → `Ctrl＋S`で実行しました)
ブラウザ：FireFox

- Markdownエディタにフォーカスしているとき → WIPで保存される
[![Image from Gyazo](https://i.gyazo.com/508356d67250e63bc085f96d8afcbea0.gif)](https://gyazo.com/508356d67250e63bc085f96d8afcbea0)

- Markdownエディタにフォーカスしていないとき → 保存ダイアログが表示される
[![Image from Gyazo](https://i.gyazo.com/b6a4a5679c8de21c1827df400470e90e.gif)](https://gyazo.com/b6a4a5679c8de21c1827df400470e90e)

私の理解や調査方法が間違っていますでしょうか？
また、もしMacでのみ再現するような場合、私の環境ではこちらの内容を調査できないことになります。可能であれば、issueの変更をお願いできますでしょうか？
ご確認よろしくお願いいたします。

**Comment by machida** [comment]
@a-kuroki-gs 質問ありがとうございます！
Macだけで再現するか、FFのアップデートで何かが変わったかがあるかもです。僕も再現するか試してみます。

**Comment by machida** [comment]
Mac版のFireFoxでも動作しました。
以前はできなかったのができるようになったっぽいです。
この問題は解決したのでIssue自体をクローズします🙇‍♂️
