### ISSUE TITLE
「最初にコメントしたメンターが提出物の担当者になる」機能のテストが落ちやすい

### ISSUE THREAD

**Issue by wata00913** [fjordllc/bootcamp#6681]
## 概要
「最初にコメントしたメンターが提出物の担当者になる」機能のシステムテスト(`Product::CheckerTest`と`Product::UncheckedTest`)が落ちやすいです。

### 
以下のテストが頻繁に落ちました。
- `/test/system/product/checker_test.rb`の9行目：'be person on charge at comment on product of there are not person on charge'
- `/test/system/product/unchecked_test.rb`の104行目：'not display products last commented by mentor if click on no-replied-button'

104行目のエラーメッセージ
```sh
Error:
Product::UncheckedTest#test_not_display_products_last_commented_by_mentor_if_click_on_no-replied-button:
Selenium::WebDriver::Error::UnexpectedAlertOpenError: unexpected alert open: {Alert text : すでに他のメンターが担当者になっています。}
  (Session info: headless chrome=114.0.5735.133)
    test/system/product/unchecked_test.rb:114:in `block in <class:UncheckedTest>'


rails test test/system/product/unchecked_test.rb:104
```

**Comment by wata00913** [comment]
@komagata @machida 
こちらのPR #6682 がリリースされました。動作確認に管理者権限のログインが必要なので、本番環境での動作確認をお願いいたします🙇‍♂️

確認方法は下記の手順となります。

1. 管理者権限を持つアカウントでログインする
1. 提出物ページ`products/16723` にアクセスする
1. 提出物ページに「担当する」ボタンが表示されていることを確認する
1. コメントを投稿する
1. `products/16723`を再読み込みする
1. 提出物ページに「担当から外れる」ボタンが表示されていることを確認する

以上、よろしくお願いいたします🙇‍♂️

**Comment by komagata** [comment]
@wata00913 こちらで確認できました〜
https://bootcamp.fjord.jp/products/16723

**Comment by wata00913** [comment]
本番環境で動作確認頂いたのでcloseします。
