### ISSUE TITLE
usersテーブルから不要になったprefecture_codeを削除する

### ISSUE THREAD

**Issue by shucream-p** [fjordllc/bootcamp#6683]
https://github.com/fjordllc/bootcamp/pull/6533 でユーザーのお住まいの情報は`country_code`と`subdivision_code`で持つことになったので、不要になった`prefecture_code`を削除する。

**Comment by machida** [comment]
@monyatto こちらをアサインさせていただきましたー

**Comment by monyatto** [comment]
@komagata @machida 
こちら本番環境にてusersテーブルからprefecture_codeカラムが削除されているかご確認お願いできますでしょうか🙏

**Comment by komagata** [comment]
@monyatto 本番のusersテーブルからprefecture_codeが削除されているのを確認しました〜。
