### ISSUE TITLE
休会期限に関するロジックの共通化

### ISSUE THREAD

**Issue by ogawa-tomo** [fjordllc/bootcamp#6691]
こちらのPR https://github.com/fjordllc/bootcamp/pull/6490 で実装している休会後三ヶ月で退会する処理ですが、休会後三ヶ月が経ったことを判定するロジックがコントローラ側にべたっと書いてあります。
https://github.com/fjordllc/bootcamp/blob/571de43ae0d22bcb5ae5ad0ebb9c48be859b01d8/app/controllers/scheduler/daily/retirement_after_long_hibernation_controller.rb#L12

一方、こちらのPR https://github.com/fjordllc/bootcamp/pull/6659 でユーザーの自動退会日（「休会期限日時」）を計算するメソッドを実装しています。ロジックを共通化する意味で、休会後三ヶ月後に自動退会する処理でもこのメソッドを使いたいです。

**Comment by ogawa-tomo** [comment]
休会期間をいったん三ヶ月から六ヶ月に変更することになった
https://github.com/fjordllc/bootcamp/issues/6423#issuecomment-1659740402

**Comment by reckyy** [comment]
@komagata 
お疲れ様です。こちらのIssueに取り組むにあたりご相談があり、ご連絡いたしました。

## 考えた結果
この共通化はしないほうがいいのではないか、と感じました。（現時点での感想です。）
コードの理解がまだまだ足りていないので、もし間違いや、「いや実装できる方法がある」などあれば忌憚なくコメントいただければ幸いです。

## 前提
まず今回挙げられている「休会後三ヶ月が経ったことを判定するロジック」が含まれている行が以下です。
https://github.com/fjordllc/bootcamp/blob/af01eb03b410c5c736dd3e22e9566077bb6126e8/app/controllers/scheduler/daily/auto_retire_controller.rb#L12
用いられているスコープが以下です。
```ruby
scope :unretired, -> { where(retired_on: nil) } #退会していないか
scope :hibernated_for, ->(period) { where(hibernated_at: nil..period.ago) }　#休会してから6ヶ月経過しているレコードを取得
scope :auto_retire, -> { where(auto_retire: true) } #自動退会を許可しているか
```
そして、Issueで触れられている別PRで実装された「ユーザーの自動退会日（「休会期限日時」）を計算するメソッド」が以下になります。（Issueの説明で明言はされていませんがおそらくこれだと思います。PRを拝見しましたが、他の追加メソッドは全て `user_decorator.rb` に定義されていたので。）
https://github.com/fjordllc/bootcamp/blob/af01eb03b410c5c736dd3e22e9566077bb6126e8/app/models/user.rb#L773-L775

## 理由
今回スコープを用いて自動退会すべきuserを取得しています。
しかし今回共通化の候補として挙げられている `scheduled_retire_at` メソッドはインスタンスメソッドです。なのでこれをスコープなどに適用することはできません。
仮にこれを採用するとなると、自分には以下しか思いつきませんでした。
```ruby
#auto_retire_controller.rb
  def auto_retire
    User.unretired.auto_retire.each do |user|
      next if user.scheduled_retire_at < Time.now

      user.retire_reason = '（休会後六ヶ月経過したため自動退会）'
```
ですが、この方法だと余分なレコードを所得してループを回してしまっているので、パフォーマンスが低下します。

これら2つのメソッドは「判定」と「日時を返す」という形で用途が異なるので、このままの方がいいという所感です。

**Comment by komagata** [comment]
@ogawa-tomo 上記いかがでしょう？

**Comment by reckyy** [comment]
@ogawa-tomo 
返信ありがとうございます。
> しかしながら、現状の実装に問題があるとは思っています。「休会の期限が6ヵ月である」という知識が別々のところに分散して書かれてしまっているからです。これはアプリケーションで共通の設定ですから、1箇所にまとめたいところです。

こちらに関しては、おっしゃる通りです。

ご提案に関してですが、とてもいいアイデアだと思います。

@komagata 
[こちらの内容](https://github.com/fjordllc/bootcamp/issues/6691#issuecomment-1938479020) のアイデアの方針で実装してもいいでしょうか。
またその際、Issueのタイトルも変更する必要がありますでしょうか。

ご返信お待ちしております。

**Comment by komagata** [comment]
@reckyy 

> https://github.com/fjordllc/bootcamp/issues/6691#issuecomment-1938479020 のアイデアの方針で実装してもいいでしょうか。
> またその際、Issueのタイトルも変更する必要がありますでしょうか。

両方YESです〜！

**Comment by reckyy** [comment]
@komagata @machida 
お疲れ様です。こちらのIssueのcloseタイミングについてお伺いしたいです。
本番環境での休会処理がまだ正常に行われている、ということを確認していただいた方がいいでしょうか。
それとも、そちらは不要でこのままcloseしてしまってもよろしいでしょうか。

お手数をおかけしますが、ご確認の程宜しくお願いいたします。

### ご確認いただきたいこと
自動退会の処理が未だ正常に行われるか。

**Comment by komagata** [comment]
@reckyy 

> 本番環境での休会処理がまだ正常に行われている、ということを確認していただいてからclose。

こちらでお願いします。

**Comment by reckyy** [comment]
memo 📝 
本番環境での自動退会処理がまだ正常に行われている、ということを確認していただいてからclose。

**Comment by komagata** [comment]
@reckyy こちら本番環境で動作することを確認しました～。
