### ISSUE TITLE
「最初にコメントしたメンターが提出物の担当者になる」処理が重複しているので、不要な方を削除したい

### ISSUE THREAD

**Issue by ymmtd0x0b** [fjordllc/bootcamp#6696]
## 概要

「最初にコメントしたメンターが提出物の担当者になる」処理が `API::CommentsController` と `API::Products::CheckerController` で重複しているため、動作時に競合が発生し Flanky なテストを発生させる要因の１つになっていました。

この Flaky なテストの根本的なエラー原因は https://github.com/fjordllc/bootcamp/pull/6682 にて解消されており、アプリの動作・テスト共に現状は問題はありません。

しかし、競合自体は現在も発生しており今後の仕様変更や機能追加によって同様の問題が発生する可能性が考えられるため、片方の処理 ( `API::CommentsController`側 ) を削除して Flaky な動作を解消したいなと思いました。

## 関連Issue

Ref: https://github.com/fjordllc/bootcamp/issues/6681

**Comment by ymmtd0x0b** [comment]
@komagata @machida 
こちらの Issue の動作確認にメンター権限のログインが必要なので、本番環境での動作確認をお願いしたいです🙇‍♂️

確認方法は下記の手順となります。

1. メンター権限を持つアカウントでログインする
2. [提出物：products/15573](https://bootcamp.fjord.jp/products/15573) にアクセスする
3. 提出物ページに「担当する」ボタンが表示されていることを確認する
4. コメントを投稿する
5. 表示中の提出物のページを再読み込みする
6. 提出物ページに「担当から外れる」ボタンが表示されていることを確認する

##### [後処理]

7. 表示中の「担当から外れる」ボタンをクリックして、「担当する」に変更した事を確認する
8. 投稿したコメントを削除する

以上、よろしくお願いいたします🙇‍♂️

**Comment by machida** [comment]
@ymmtd0x0b 本番でいただいた手順を一通り行い動作確認しました！全てOKでしたー🙆‍♂️

**Comment by ymmtd0x0b** [comment]
@machida 確認作業ありがとうございます🙇‍♂️

動作確認OKを頂いたのでcloseします！
