### ISSUE TITLE
定期イベントに休日を登録できるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6715]
決まっている休みが表示されるようにする。
祝日は開催しない定期イベントの場合、開催日が祝日で開催しない日をここに表示する。直近一年くらい。
現在は祝日しか休みにできないが、例えばRubyKaigi中や夏休みなど定期イベントの休みをあらかじめ設定できるようにしたい。

<img width="797" alt="貼り付けた画像_2023_09_14_17_53" src="https://github.com/fjordllc/bootcamp/assets/168265/20495344-83c5-4401-ba3f-d10321ee48af">

---

さらに、管理者が定期イベント編集ページから休みを登録できるようにする。

休みの追加という項目を作る。

年月日を入力し登録ボタンを押すと、input タグから普通の文字に画面遷移なく変更され、新たなinputタグが出現する。
普通の文字になった際、右側に削除リンクが表示される。削除をクリックすると、画面遷移なく登録した年月日が消える。

<img width="1589" alt="貼り付けた画像_2023_09_14_17_58" src="https://github.com/fjordllc/bootcamp/assets/168265/12d5808f-a38b-44a8-90a8-af4ec99eabf3">

↓

<img width="1589" alt="貼り付けた画像_2023_09_14_17_58" src="https://github.com/fjordllc/bootcamp/assets/168265/1288252f-65c8-4572-985e-334c681953d9">

過去に入力した年月日が、現在の年月日より古い場合は表示をしない、もしくは削除する。

**Comment by hirano-vm4** [comment]
@machida

## 方向性の確認と提案

### 【提案】休みの理由の表示について
>管理者が定期イベント編集ページから休みを登録できるようにする

こちらの実装について、1つの定期イベントに対して複数休みの日付が登録されることになるため、以下のように定期イベント休日登録用にテーブルを別に切り出して実装しようと考えています。

`イメージ：regular_event_holidays（仮名）`


| カラム名           | データ型          |                                               |
|----------------|----------------|--------------------------------------------------|
| id             | Integer        | 主キー                                |
| regular_event_id | Integer        | `regular_events`テーブルのレコードを参照する外部キー              |
| date           | Date           | 休日に設定した日付                                           |
| description         | String         | 休日の理由（任意）          |
| created_at     | DateTime       | レコードの作成日時                                       |
| updated_at     | DateTime       | レコードの最終更新日時                                     |

※`regular_events`（一）と`regular_event_holidays`（多）を関連付け


その際、上記のように`description`カラムを任意設定で用意して、なぜ休みなのかを参加者に伝えることができる仕様のほうが個人的には便利かな？と考えています。


- 任意設定の休みの表示: `2024年4月4日(木)　RubyKaigi開催期間のため`

- 祝日の休みの表示:`2024年4月29日(月・祝)`
祝日は曜日と一緒に`祝`と表示


## 確認したいこと
上記の方向性で良いか、また別のイメージがあれば教えていただければ幸いです🙏

**Comment by komagata** [comment]
@hirano-vm4 システム的には下記以外OKです～。

descriptionはstringではなくtextがいいかも。

@machida 仕様的にはいかがでしょうか～？

**Comment by machida** [comment]
@komagata @hirano-vm4 仕様的にはOKですー🙆

**Comment by hirano-vm4** [comment]
@komagata 

>descriptionはstringではなくtextがいいかも。

こちら、たしかに長めに入力されることも想定して`test`型で進めていきます！

**Comment by hirano-vm4** [comment]
@machida 

## 「休みの追加」フォームの実装の方向性のご相談

>年月日を入力し登録ボタンを押すと、input タグから普通の文字に画面遷移なく変更され、新たなinputタグが出現する。
普通の文字になった際、右側に削除リンクが表示される。削除をクリックすると、画面遷移なく登録した年月日が消える。

![image](https://github.com/fjordllc/bootcamp/assets/105143414/87c0fb3e-c353-47b9-bad4-c4fb2930a940)

こちらの実装ですが、休みに設定する日付をユーザーが入力したあと **「登録」ボタンを押して、次のフォームが出現する** 、というオーダーかと思いますが、以下のような実装もありかな？と思ってのご相談になります🙏

以下のように同じページに「定期開催日」というフォームがあります。

これは開催日程を設定して、追加があれば「定期開催日追加」ボタンを押して複数の開催日を設定し、最後にページ下部のボタンを押して確定します（新規作成であれば「作成」ボタン、更新であれば「内容変更」）。

![f402ee9e48918de3f3839dfc38fe6e0d (1)](https://github.com/fjordllc/bootcamp/assets/105143414/f443902d-9bd7-4b56-b888-6ccdb987e4b5)


定期イベントに休日を登録する場合においても、同様の実装でも大丈夫そうでしょうか？

提案した理由としては2点あります。

- **日付のフォーム入力部分にも「登録」があると、ページ下部の確定ボタン（新規作成であれば「作成」ボタン、更新であれば「内容変更」）を押さないで別ページに移動してしまうなどの、勘違いが発生するかもと考えた（あくまでフォームは設定のみで、確定はページ下部の確定ボタンとしたい）**
- **同じフォーム内で統一したほうがユーザーは理解しやすいと考えた**

上記の点を個人的に感じたので、ご相談させていただきました🙏

下記のようなイメージです
![34fe9e3f373ba57b5b332db509fc4b79](https://github.com/fjordllc/bootcamp/assets/105143414/efd63c4e-dd7e-41ce-8245-1ada74f30b6d)


町田さんのイメージもあるかと思いますので、ご意見やアドバイスいただけたら嬉しいです🙆

**Comment by machida** [comment]
@hirano-vm4 提案ありがとうございます！そのUIでいいと思いましたー。そのように実装お願いしたいですー

**Comment by hirano-vm4** [comment]
@machida 

早速ありがとうございます！

では、どのように進めさせていただきます💪
