### ISSUE TITLE
日報の学習終了時間に23:45以降を入力したい

### ISSUE THREAD

**Issue by shibainurou** [fjordllc/bootcamp#6723]
## 機能の説明
日報の学習終了時間に日付をまたいだ時間を入力できるようにする。
現在は23:45が最大なので、24:00以降を24:00, 25:00ように入力したい。
<img width="363" alt="image" src="https://github.com/fjordllc/bootcamp/assets/2572625/8846a6a9-de78-4720-9abd-8a4b07e1f1d2">

## 何故この機能が必要なのか
日付をまたいで学習したときに時間の入力ができない。もし日報を分けたとしても23:45〜24:00までの15分が入力できない。
そのため日付をまたいだ場合は、開始時間を実際よりも早めて入力しないといけない。

**Comment by machida** [comment]
📝
30:00 まで選択できるようにする。

例えば 1/1 に 22:00 〜 28:45 と選択したときは、
1/1 22:00 〜 1/2 04:45 まで学習したことになる。

**Comment by komagata** [comment]
:memo:

日報の個別ページで、日付を跨いでる場合は　

22:00 〜 （翌日）6:00

のような表示にする。

**Comment by omochiumaiumai** [comment]
こちらのIssueはリリースと本番環境での変更を確認したため、Closeします。
