### ISSUE TITLE
GitHubのContributions GraphがSVGで取得できない

### ISSUE THREAD

**Issue by wata00913** [fjordllc/bootcamp#6732]
## 概要
- ダッシュボードページの「学習時間」と「GitHub」のContributions Graphがありますが、現在はGitHubの方が表示されません。

  ![image](https://github.com/fjordllc/bootcamp/assets/85052152/fa81dae8-7745-4249-89b4-793e83dcc4e7)

- GithubGrassTestのテストが落ちてしまいます。
  **再現手順**
`/test/models/github_grass_test.rb`
エラーメッセージ(パスは一部省略)
  ```sh
  Failure:
  GithubGrassTest#test_#fetch [test/models/github_grass_test.rb:8]:
  Expected /svg/ to match "".
  
  
  rails test test/models/github_grass_test.rb:6
  ```

### 原因
GitHubのContributions Graphの表示方法がSVGからtableタグの構成に変更されています。
<img width="834" alt="image" src="https://github.com/fjordllc/bootcamp/assets/85052152/f0a73933-5add-46e6-9705-01fdd0ed6a73">

現在のBootcampアプリでは、`model/github_grass.rb`にて`js-calendar-graph-svg`クラスのsvgタグを取得する方法のため表示できない状況です。

https://github.com/fjordllc/bootcamp/blob/7010e2dc44c1a644002e2d58e8ae0b69ac21a13f/app/models/github_grass.rb#L29-L31

**Comment by yuma-matsui** [comment]
@machida 

Githubの草の表示について確認させていただきたいです！

![image](https://github.com/fjordllc/bootcamp/assets/70259961/a0c20e64-601b-4710-ac1b-a70a821c963b)

上記画像のように草情報を取れるようにはなりました。
Wataさんから以下コメントをもらったんですが、以前（SVGで表示していた時）って曜日、月などの補足情報って表示していましたっけ？

https://github.com/fjordllc/bootcamp/pull/6745#issuecomment-1647349901

自分は以下の理由から表示する必要はないのではないかと思っています。

- 実装がGithubに依存する
- 詳細情報が知りたい人はGithubを直接確認すると思う（ここではなんとなくの草分布だけわかれば良い）

実装が面倒とかは全くないので¥machidaさんの意見をいただければと思います！
よろしくお願いします🙏

**Comment by machida** [comment]
@yuma-matsui 質問ありがとうございますー
表示をするならGitHubと同じがいいですね。ただ、表示に手間があったり、保守に手間があるなら、全然優先度は高くないので非表示で草だけで十分なのですが、今回は手間はないようなので、GitHubと同じものを表示したいと思います。CSSが必要でしたら、それは僕の方でやりますー

**Comment by komagata** [comment]
@yuma-matsui GitHubでは月・曜日表記がされていて、以前はそれを日本語化して表示していました。
ただ、必須ではないです。

**Comment by SuzukaHori** [comment]
### 確認したいことメモ
NokogiriでHTMLタグを取得したり、不要なタグを削除したりする処理を行っている。
レビューによって、HTMLの中身が変わる可能性があるので、デザインより前にレビューをお願いしても問題ないか。

→2/14のMTで確認。レビューが先、デザインを後で問題ない。

**Comment by SuzukaHori** [comment]
- https://github.com/fjordllc/bootcamp/pull/7361
→こちらのPRマージ後にGithubの仕様変更が発生したため、修正のPRを作りました。

- https://github.com/fjordllc/bootcamp/pull/7667
この変更により本番環境で正常に草が表示できるようになったため、IssueをCloseします。
<img width="505" alt="スクリーンショット 2024-04-16 20 43 13" src="https://github.com/fjordllc/bootcamp/assets/129706209/ed4b975a-462d-4016-b485-1d25df1d117c">
