### ISSUE TITLE
メンターページのプラクティスタグにある所属カテゴリーが機能しない

### ISSUE THREAD

**Issue by mono-nobe** [fjordllc/bootcamp#6737]
## 概要

メンターページのプラクティスタグにある所属カテゴリーについて、カテゴリー数をクリックしてもモーダルが表示されません。

## 再現手順

1. メンター権限を持つアカウントでログインする
2. `/mentor/practices` にアクセスする
3. 所属カテゴリーの数をクリックする

<img width="1374" alt="スクリーンショット 2023-07-18 22 34 30" src="https://github.com/fjordllc/bootcamp/assets/94843475/f824d6e5-312d-48e0-8c57-018878d23959">

4. モーダルが表示されないことを確認する

## 期待される振る舞い

所属しているカテゴリー一覧がモーダルで表示される。
(ローカルでの動作確認の都合上、管理者アカウントでログインし管理者ページで確認しています)

<img width="1152" alt="image" src="https://github.com/fjordllc/bootcamp/assets/94843475/d5bdfa19-add9-4ebb-a7c7-55ff4455ab0b">

## 環境

 - OS: iOS
 - ブラウザ: chrome

## その他

ローカルで動作確認すると、以下のPRのマージを境にモーダルが表示されなくなるようでした。

#6549

## 関連Issue

Ref: #5666, #6549

**Comment by Kassy0220** [comment]
@komagata @machida 
こちらのIssueが本番環境にマージされましたので、本番環境でのご確認をお願いしてもよろしいでしょうか？
確認手順は次になります。

1. `https://bootcamp.fjord.jp/mentor/practices`にアクセス
2. プラクティスの所属カテゴリーをクリック
<img width="1139" alt="_development__プラクティス___FBC" src="https://github.com/fjordllc/bootcamp/assets/79003082/44712b4a-7b14-4c4e-b735-093e02ac4251">
3. 所属カテゴリーのモーダルが表示されることを確認する

よろしくお願いいたします🙇🏻

**Comment by machida** [comment]
@Kassy0220 おまたせしました！！本番で確認できましたー🙆‍♂️
