### ISSUE TITLE
ダッシュボードのブックマーク一覧をreactにする。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6749]
ダッシュボードに最新のブックマーク一覧を表示する機能がある。

<img width="409" alt="貼り付けた画像_2023_11_13_12_50" src="https://github.com/fjordllc/bootcamp/assets/168265/c4320595-c032-4033-884d-0b49d9e12994">

これをオンにすると、

<img width="409" alt="貼り付けた画像_2023_11_13_12_50" src="https://github.com/fjordllc/bootcamp/assets/168265/441abc72-2672-4086-b84c-1445b6780ced">

削除ボタンが表示され、ブックマーク一覧や、それぞれのページに遷移しなくても、ここから削除ができる。

<img width="397" alt="貼り付けた画像_2023_11_13_12_51" src="https://github.com/fjordllc/bootcamp/assets/168265/3cc63bee-8c48-4d70-8045-f88e3243aaef">

この部分が現在は Rails の view で実装されているので、React 化をお願いします。

**Comment by ham-cap** [comment]
@machida @komagata 

お疲れ様です！

こちらのissueの範囲について確認させてください🙏

やることとしては、編集のオン/オフスイッチでブックマークの削除ボタンの表示/非表示を切り替える機能をReact化するという理解なのですが、そうすると少なくとも`app/views/home/_bookmarks.html.slim` 以下にある要素は全てReactコンポーネントで構造化させることになると思うのですが、その認識で合っていますでしょうか？👀

例えば、現状の構造に倣って以下のような親子関係にして削除ボタンの表示/非表示を切り替えるような実装を考えています。
`BookMarks.jsx`直下に削除ボタンの表示/ひひょうじを

- BookMarks.jsx (ブックマーク一覧全体)
    - BookMarkEditButton.jsx（編集オン/オフスイッチ）
    - BookMark.jsx（ブックマークのリスト）
        - BookMarkDeleteButton.jsx（削除ボタン） 

issueのボリューム感が当初考えていたより大きそうに思えてきたので念のため認識の確認をさせてください🙇‍♂️
よろしくお願いいたします🙏

**Comment by machida** [comment]
@ham-cap その認識であってます🙆‍♂️リストをReact化し、削除機能も実装する、を想定してます。ポイントがIssue内容と不釣り合いでしたら、次回MTGで話し合いましょう。

**Comment by ham-cap** [comment]
@machida 
ありがとうございます🙏
承知いたしました🙌
一旦この方向性で作業をしてみたボリューム感を次回のMTGでご報告させていただきます💪

**Comment by ham-cap** [comment]
本番環境で動作確認できたためクローズしました。
