### ISSUE TITLE
提出物がレビュー中になったら提出物作成者に通知が飛んで欲しい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6756]
<img width="864" alt="貼り付けた画像_2023_07_25_12_32" src="https://github.com/fjordllc/bootcamp/assets/168265/1e03b191-06b2-40a3-bb55-77bc166370c3">

提出物に担当メンターがアサインされると、レビュー中と表示される。
担当メンターがアサインされたら、提出物作成者に

```
プラクティス｛プラクティス名｝の提出物がレビュー中になりました（担当メンター {メンターアカウント}）。
```

という通知を飛ばして欲しい（サイト内、メール 両方）。

**Comment by rira100000000** [comment]
マージ後に不要と判断されたため、revertされました。
通知が飛ばないことを確認できたためcloseします。

**Comment by rira100000000** [comment]
マージ後に不要と判断されたため、revertされました。
通知が飛ばないことを確認できたためcloseします。
