### ISSUE TITLE
日報でユーザーにメンションできない

### ISSUE THREAD

**Issue by ryotori1024** [fjordllc/bootcamp#6758]
## 概要
日報のコメントでユーザーにメンションできない状態です。
(現在日報でしか試していませんが、Q&A等でも発生するかもしれません)

## スクリーンショット
![image](https://github.com/fjordllc/bootcamp/assets/68388062/4a89e4b7-2f70-42e9-9533-69ad9acd71c6)

**Comment by machida** [comment]
@ryotori1024 

こちらのバグが再現ができない状況です。

<img width="501" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/73a4bb78-6eec-459f-97ac-bc0edb8086e4">

メンションができない状況について、何かもう少し詳しいシチュエーションなどがありましたら教えていただけると助かります（特にないかもしれないですが、もしあれば）🙏

**Comment by JunichiIto** [comment]
これに関連するかもしれませんが、メンションがリンクになっているものとなってないものが混在している日報がありました。

https://bootcamp.fjord.jp/reports/77938

<img width="793" alt="fbc" src="https://github.com/fjordllc/bootcamp/assets/1148320/2ad59219-17f2-4605-9643-a115fc718a3d">

markdownで見てみても、特に違いがわからなくて謎です。。

https://bootcamp.fjord.jp/reports/77938.md

**Comment by ryotori1024** [comment]
@machida 
返信遅くなりすみません。
先ほど自分の日報で試したところ、メンションできるようになっていました。
ブラウザはchromeです。
![image](https://github.com/fjordllc/bootcamp/assets/68388062/017ccecd-9cda-4594-853a-998f7700e2a6)
![image](https://github.com/fjordllc/bootcamp/assets/68388062/f47ba2c2-33bf-4443-8434-a14221a9f7b7)

**Comment by JunichiIto** [comment]
issueの内容が違うかもしれないので新しくissueを立てておきました。

https://github.com/fjordllc/bootcamp/issues/6800

**Comment by machida** [comment]
@JunichiIto 
Issueありがとうございますー🙏
