### ISSUE TITLE
ダッシュボードの近日開催のイベントに、定期イベントが休みの場合も表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6778]
現在、ダッシュボードの近日開催のイベントには休みが反映されていない。定期イベントには、休日は休みに設定する機能があるので、ダッシュボードの近日開催のイベントにもそれを反映させたい。

しかし、休みだから表示しない、のではなく、休みであることを表示するようにしたい。

<img width="447" alt="貼り付けた画像_2023_08_01_17_34" src="https://github.com/fjordllc/bootcamp/assets/168265/736cb914-82dd-437b-85d6-2c303f33e084">

こんな形で、定期イベントが休みの場合は、休みとわかる表示でリストの中に入れたい。

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/pull/6565
Discord通知が参考になるかもです。

**Comment by Kassy0220** [comment]
こちら本番環境での動作確認ができましたので、Closeいたします！🙌
