### ISSUE TITLE
メンターが見れるカテゴリー画面の各カテゴリーに、所属するプラクティス数を表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6782]
メンターでログインして、
http://localhost:3000/mentor/categories
にアクセス。

<img width="1660" alt="貼り付けた画像_2023_08_02_14_57" src="https://github.com/fjordllc/bootcamp/assets/168265/1500c79c-986f-4fbc-b293-f58dcb56bc96">

**Comment by omochiumaiumai** [comment]
@komagata @machida
お疲れ様です！こちらのPRがマージ&リリースされました。
[メンターが見れるカテゴリー画面に、各カテゴリーに所属するプラクティス数を表示 #6969](https://github.com/fjordllc/bootcamp/pull/6969)
受講生には権限がないため、本番環境でのご確認をお願いしてもよろしいでしょうか？
## 確認方法
1. メンターのアカウントでログイン
2. メンターページのカテゴリー画面(https://bootcamp.fjord.jp/mentor/categories) にアクセス
3. 各カテゴリーの名前の横に、所属するプラクティスの数が表示されていることを確認
![image](https://github.com/fjordllc/bootcamp/assets/88243294/12529608-5328-4a9c-bd84-ad52b57748f6)

**Comment by komagata** [comment]
@omochiumaiumai 本番環境で確認できました〜！

**Comment by omochiumaiumai** [comment]
@komagata 
ご確認ありがとうございます！Issueを閉じさせていただきます🙌
