### ISSUE TITLE
コース一覧アイコンが表示されていない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6787]
カテゴリー並び替えページのアイコンが表示されていない。
https://bootcamp.fjord.jp/courses/36/categories

![スクリーンショット 2023-08-03 17 24 12](https://github.com/fjordllc/bootcamp/assets/16577/de4b9ccd-e7b1-4e12-a6ec-d23ecca9fb42)

**Comment by machida** [comment]
@komagata 
https://github.com/fjordllc/bootcamp/pull/6788
PR出しました。テストが通ったらマージしますー

**Comment by machida** [comment]
マージしました！！

**Comment by komagata** [comment]
@machida ありがとうございます〜！

**Comment by machida** [comment]
こちら本番で解決されたのが確認できたのでクローズしますー🎉
