### ISSUE TITLE
画像アップロードボタンがSafariでおかしい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6790]
MacのSafariで画像アップロードボタンの表示がおかしいようです。

![スクリーンショット 2023-08-03 19 45 00](https://github.com/fjordllc/bootcamp/assets/16577/33b78b6d-c968-4a65-a5a5-62cb6a91549f)

**Comment by machida** [comment]
こちら本番で確認したのでクローズしますー
