### ISSUE TITLE
「ファイルを挿入」ボタンの自己主張が強い

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6792]
「ファイルを挿入する」ボタン、便利なのですが、コメントを書くときに必要以上に視界に入ってくる感があります。

<img width="713" alt="Screenshot 2023-08-04 at 10 21 14" src="https://github.com/fjordllc/bootcamp/assets/1148320/56e613d1-d783-4031-8029-81869c780137">

個人的にはこれぐらいの控えめなデザインでもいいかなーと思っています。（具体的なデザインはお任せします）

<img width="714" alt="Screenshot 2023-08-04 at 10 20 57" src="https://github.com/fjordllc/bootcamp/assets/1148320/6850b732-4b00-43c7-8efa-1f6e55f9b2a3">

**Comment by machida** [comment]
<img width="919" alt="貼り付けた画像_2023_08_05_3_13" src="https://github.com/fjordllc/bootcamp/assets/168265/4d06f71c-6fb3-459d-bbd9-ce93e19511e1">

一旦このようにしましたー
これで様子を見て何かあれば改善したいと思います。

**Comment by JunichiIto** [comment]
@machida ありがとうございます！良いと思います〜 👍
