### ISSUE TITLE
近日開催のイベントに質問・雑談タイムが表示されない。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6793]
<img width="430" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/15fbd5d9-5036-48c2-926a-285c8e0a44eb">

質問・雑談タイムは全員が参加されている状態になっているはずが、近日開催のイベントに表示されない。

**Comment by machida** [comment]
@wata00913 こちら、原因わかりますでしょうか？質問・雑談タイムは全員が自動で参加登録をしている状態になっていると思っていたのですが、そうはなっていないのか、近日開催のイベントに表示されていませんでした。

近日開催のイベントの実装、もしくは、質問・雑談タイムの実装、どちらに原因があるかを知りたいですー

**Comment by wata00913** [comment]
@machida 
>近日開催のイベントの実装、もしくは、質問・雑談タイムの実装、どちらに原因があるかを知りたいですー

調査しました〜
質問・雑談タイムの実装（定期イベントの全員参加機能）が原因みたいです。※１

まず、全員参加機能は、自動登録の対象ユーザーが現役生と現役研修生のみとなっています。
（※自動登録する処理は下記です。）
https://github.com/fjordllc/bootcamp/blob/61c9191e1e44d7a43cfde6a2601b5efe96d0e752/app/controllers/regular_events_controller.rb#L101-L102

次に、定期イベントの登録機能は、主催者を参加者として登録してないです。つまり、主催者が参加扱いになるには「参加申込」ボタンで参加登録する必要があります。

以上の２点から、質問・雑談タイムが表示されないユーザーは、主催者の駒形さん、町田さんのみだと考えられます。
受講生の自分は、表示されていました。

<img width="802" alt="image" src="https://github.com/fjordllc/bootcamp/assets/85052152/c3870f48-b9c3-4f33-a1ed-5284056b4051">


※１関連PR
- #5728

**Comment by machida** [comment]
@wata00913 おおー、調査ありがとうございます！なるほど、原因がはっきりしました。とても助かります。ありがとうございます🙏 開催のお知らせは主催者も知りたい情報なので、別Issueを立てようと思いますー

**Comment by machida** [comment]
https://github.com/fjordllc/bootcamp/issues/6794
Issueを立てたのでこちらはクローズ。
