### ISSUE TITLE
全員参加のイベントに主催者も参加させたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6794]
自動で全員参加するイベント（現在は質問・雑談タイム）では、自動で受講生・研修生が参加になるようになっている。
詳しくは: https://github.com/fjordllc/bootcamp/issues/6793
現状、主催者が管理者やメンターなど受講生・研修生ではない場合は主催者であっても参加になっていない。
これを、催者が管理者やメンターなど受講生・研修生ではない場合でも、主催者であれば参加になるようにしたい。

そうすることで、

- そのイベントページにコメントがあった場合に、主催者もイベントの通知を受け取ることができるようになる。

**Comment by sochi419** [comment]
本番環境で確認ができたので、closeします。

**Comment by sochi419** [comment]
本番環境で確認ができたので、closeします。
