### ISSUE TITLE
質問を編集するたびに（？）Discordに通知が走っている

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6799]
「質問：「fly.ioの無料枠でデプロイした際のマシーンのスペックに関して」を----さんが作成しました。」がDiscordに何度も通知されているんですが、なんとなく質問の本文を編集するたびにDiscordに通知が走っている気がします。
通知は新規投稿時だけで良いのでは？
https://bootcamp.fjord.jp/questions/1721

<img width="1048" alt="fbc1" src="https://github.com/fjordllc/bootcamp/assets/1148320/02854709-29b6-4dd3-b2a4-9bb9361038e5">
<img width="1097" alt="fbc2" src="https://github.com/fjordllc/bootcamp/assets/1148320/ece7b45f-db23-43bf-9a1b-4fb12c29c257">

**Comment by omochiumaiumai** [comment]
リリースと本番確認が完了したため、こちらのIssueはcloseさせていただきます。
