### ISSUE TITLE
管理者はユーザー個別ページで、そのユーザーのStripeの情報にアクセスできるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6817]

**Comment by komagata** [comment]
@machida こちらStripeのどのような情報が必要ですかね？

何故かというとStripeのAPIは遅いのとアクセスの回数に制限があるためです。
１ユーザーについて１アクセスぐらいなら問題無いですが、何かのリストをページングしながら全部持ってくる必要のある情報などだと相当遅くなっちゃいそうだからです。（管理ページのユーザー一覧などはそのために重くなっている）

**Comment by machida** [comment]
@komagata

まずは、ユーザーは自分の領収書などのお支払い情報が見れますが、それを管理者も見れるようにしたいです。
https://bootcamp.fjord.jp/pages/440

あとは、以下も見れるようにしたいです。

- サブスクリプションのステータス（未払いなど）
- 次回請求日時
- 残りのお試し期間（あれば）

ユーザーの個別ページから見れればOKなので、一覧で表示する必要はないです。
問い合わせが来たときにステータスや次回の支払日などを調べられるようにするのが目的です（Stripeの管理画面から確認するのは属人的なので）。

**Comment by komagata** [comment]
@machida 

> 問い合わせが来たときにステータスや次回の支払日などを調べられるようにするのが目的です（Stripeの管理画面から確認するのは属人的なので）。

管理画面の該当のページへのリンクを作るのはいかがでしょうか？（管理者であれば誰でも見れるかなと思います）

領収ののページ自体はStripeの該当の機能を使っているのでユーザーが見ているままを管理者が見れるようにするのは難しいかもです。

**Comment by komagata** [comment]
@machida こちらいかがでしょうか～？

**Comment by komagata** [comment]
@machida 上記いかがでしょうか～？
