### ISSUE TITLE
usersテーブルから不要になったDiscord関連のカラムを削除する

### ISSUE THREAD

**Issue by mono-nobe** [fjordllc/bootcamp#6818]
https://github.com/fjordllc/bootcamp/issues/6215 にて、users テーブルにある Discord 関連のカラムを移行しました。
そのため、users から不要になった以下のカラムを削除したいです。

- discord_account
- times_url
- times_id

**Comment by komagata** [comment]
#6856 と一緒の作業なので二つで1ポイントとするために、こちらのIssueは0にしています。
