### ISSUE TITLE
提出物ページにメンター向けメモも表示したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6820]
メンターがアクセスした場合、提出物ページにメンターメモを表示したい。

何故ならレビュー中はプラクティスページではなく提出物ページを見ているので、レビューの参考にするメンターメモは提出物ページでも表示されて欲しいため。

**Comment by machida** [comment]
@komagata 

<img width="1659" alt="貼り付けた画像_2023_09_01_10_43" src="https://github.com/fjordllc/bootcamp/assets/168265/f5c22c7d-ad1a-4e97-9f19-843bdbb1ad5d">

提出物ページのここから見れるようになってますー

**Comment by komagata** [comment]
@machida 見逃していました。ありがとうございます。ではCloseしちゃいますね。
