### ISSUE TITLE
ダッシュボードの近日開催のイベントには、自分が参加していない定期イベント、特別イベントも表示するようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6823]
現在、ダッシュボードの近日開催のイベントには、自分が参加しているイベントしか表示されない。

以下のように変更したい。
↓
- 全てのイベント（特別イベント、定期イベント両方）が表示されるようにする。
- 自分が参加登録しているものには、「参加登録済」と表示するようにしたい。

---

現在、ダッシュボードの近日開催のイベントには、祝日で休みの定期イベントは非表示になっています。
それを変更し、休みの場合は、非表示ではなく休みとして表示する変更をこちらで進めています。
https://github.com/fjordllc/bootcamp/pull/6806
このPRがまだ main にマージされていなかったら、このブランチからブランチを作って作業を進めてください。
このPRがmainにマージされたら、作業中のブランチを main から rebase をしてください。

デザインはmachidaがやります。

**Comment by fuwa-syugyo** [comment]
@machida  cc @Kassy0220 
お疲れ様です。
issue自体とは直接関係がないことだとは思うのですが、動作チェックのためにイベントを作成しようとしたら画像のようなエラーとなってしまいました。
定期イベント、特別イベントの両方です。

<img width="864" alt="image" src="https://github.com/fjordllc/bootcamp/assets/62344131/3a4924da-531f-49f9-8504-51c167f3e248">

こちらのブランチ( https://github.com/fjordllc/bootcamp/pull/6806 )を取り込んでの作業中に発生しました。mainブランチでも確認してみましたが、発生していませんでした。

6806のブランチで上記のエラーは発生していますでしょうか…？
(チーム開発が久しぶりでいろいろと不慣れなところがあり、私の環境に問題がある可能性も十分にあると思います)
お手数ですがご確認をお願いできますでしょうか。

**Comment by machida** [comment]
@fuwa-syugyo @Kassy0220 こちら、僕の手元でも発生しました！
https://github.com/fjordllc/bootcamp/pull/6806
これで発生しているバグだと思います。

@fuwa-syugyo 

- 原因がわかりそうだったら #6806 から別のブランチを作って、#6808 に対して PR を送る。それがマージされるまで、その PR からブランチを作りこの作業を進める。
- このバグがあっても自分のIssue対応ができるのであれば、作業を進める。
- 原因もわからず、自分のIssueも進められなかったら他のIssueをもらう。

Kassyさんと連絡をしながら、上記のどれでいくか決めていただけたらと思いますー

**Comment by Kassy0220** [comment]
@fuwa-syugyo @machida 
お疲れ様です！

私の手元で[最新のコミット](https://github.com/fjordllc/bootcamp/commit/eb70b94aa97332a7073682f9984cb875bf78b4f8)を取り込み、mainブランチとfeature/change-dashboard-display-to-indicate-that-event-is-not-heldブランチで確認しましたが、エラーは確認できませんでした。

私がのPRで追加したコードは次のものであり、エラーの原因は今のところ分からない状態です。
+ スタイルの追加
+ RegularEventモデルにメソッドを追加
+ ダッシュボードのビューを一部変更
+ テストの追加 + テストデータの追加

エラーメッセージからするに、Watchが二重で作成されてしまい、バリデーションに引っかかってエラーが発生しているのではないかと思いました。
以前自分も同じエラーが発生したことがあり、次のことを実行すると解決しました。

`config/initializers/newspaper.rb`の3行目を次の様に変更して、アプリを再起動する。
```ruby
# frozen_string_literal: true

Rails.application.config.after_initialize do
  Newspaper.subscribe(:event_create, EventOrganizerWatcher.new)
```
[\#322 チーム開発 : 再びエラーと格闘した \| FBC](https://bootcamp.fjord.jp/reports/77011)

上記を実行してエラーが解決しない場合は、また教えていただけるとありがたいです！
お手数ですが、よろしくお願いします🙏

**Comment by fuwa-syugyo** [comment]
@Kassy0220 
お疲れ様です！
上記の手順を試したところ、エラーが解決しました！
アプリ全体で `Rails.application.config.to_prepare` を `Rails.application.config.after_initialize` に変更しようという話になっているのですね。初めて知りました。

教えていただきありがとうございました🙏

@machida 
エラーが解決しましたのでこのまま作業を進めます。
ご確認いただきありがとうございました🙏

**Comment by machida** [comment]
@fuwa-syugyo 了解ですー👍

@Kassy0220 ありがとうございます🙏
