### ISSUE TITLE
メンターページ/コース一覧の読み込み時にローディングを出したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6845]
メンターでログインし、 http://localhost:300/mentor/courses にアクセス。
このページが表示されるまでの間にローディング中であると分かるものを表示したい。

---

再利用しやすいように、読み込み中に表示するビューを別ファイルで作成、それを読み込み中に表示し、読み込みが完了したら消えるようにする。

読み込み中に表示するものは https://github.com/fjordllc/bootcamp/issues/6847 このIssueで使っているものと同じものを表示してください。

**Comment by taco-nantai** [comment]
@komagata @machida 
お疲れ様です。
本Issueの作業内容がリリースされたので、本番環境での確認を行いたいのですが、確認に管理者ユーザーでのログインが必要なため、本番環境での確認をお願いしてもよろしいでしょうか。
お手数をおかけしますが、よろしくお願いいたします🙇‍♂️

**Comment by komagata** [comment]
@taco-nantai 本番環境で確認しました。OKでした〜！

**Comment by taco-nantai** [comment]
確認ありがとうございます🙇‍♂️

**Comment by komagata** [comment]
@taco-nantai 完了していたらIssueのCloseお願いします〜
