### ISSUE TITLE
メンターページ/プラクティス一覧の読み込み時にローディングを出したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6847]
メンターでログインし、 http://localhost:300/mentor/categories にアクセス。
このページが表示されるまでの間にローディング中であると分かるものを表示したい。

---

再利用しやすいように、読み込み中に表示するビューを別ファイルで作成、それを読み込み中に表示し、読み込みが完了したら消えるようにする。

読み込み中に表示するものは machida がデザインするので、とりあえず「読み込み中」と文字が出るようにしてください。

読み込み中に表示するファイルを教えてくれたら、そこにデザインを入れます。

**Comment by omochiumaiumai** [comment]
こちらのIssueはリリースと本番確認が完了したため、Closeします。
