### ISSUE TITLE
就職活動中ボタンが動かない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6849]
管理者でユーザー個別ページにアクセスした時の「就職活動中」のトグルボタンが動作しない

![スクリーンショット 2023-08-30 22 55 12](https://github.com/fjordllc/bootcamp/assets/16577/cba54f36-b6c8-4ad8-8fb0-6760c7a82737)

**Comment by fuwa-syugyo** [comment]
@komagata 
お疲れ様です。
ローカル環境とステージング環境でバグが発生するのか試したのですが、いずれも発生しませんでした。
更新しましたと表示されます。

![image](https://github.com/fjordllc/bootcamp/assets/62344131/c853b193-5224-43d0-b46c-ee7085996d9b)

状況について、何点か確認させていただきたいです。

1. 対象のトグルスイッチは以下で合っていますでしょうか？
(念の為確認です)
<img width="1333" alt="image" src="https://github.com/fjordllc/bootcamp/assets/62344131/8f49e5b8-bdcf-4319-baf6-bc652ed70b9f">

2. 全てのユーザーに対して発生しますか？
ユーザーが就職を希望しているか/していないかの両方で確認してみましたが、いずれも更新されました。

よろしくお願いいたします。

**Comment by fuwa-syugyo** [comment]
@komagata 
こちらのPR(https://github.com/fjordllc/bootcamp/pull/6855) で修正されたので、クローズいたします。
