### ISSUE TITLE
メンターページ / プラクティス一覧 所属カテゴリーを数字ではなく、カテゴリー名を全て表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6850]
メンターでログインし、 http://localhost:3000/mentor/practices にアクセス。

<img width="1236" alt="貼り付けた画像_2023_08_31_0_13" src="https://github.com/fjordllc/bootcamp/assets/168265/ed842d14-4660-4621-9f32-b566beb83f05">

これを数字ではなく、カテゴリー名全て表示するように変更。
リンクもなくす。

**Comment by Sasaco-JM** [comment]
komagataさんに本番環境でご確認いただき、問題なしとのことなのでクローズします。
