### ISSUE TITLE
プラクティス関係のページのURLを全て mentor 以下に移動させる。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6852]
## コース > カテゴリー並べ変え

現在のURL
http://localhost:3000/courses/{ID}/categories
他のプラクティス関連ページと同じように mentor 以下に移動させたい。

この作業と一緒に、コースからカテゴリー並べ変えに行った時、

<img width="1368" alt="貼り付けた画像_2023_08_31_0_36" src="https://github.com/fjordllc/bootcamp/assets/168265/de397c0d-6a77-429d-ad97-02fb2e89ca5c">

コースのタブがアクティブになるように修正をお願いします。

## カテゴリー > プラクティス並べ替え

現在のURL
http://localhost:3000/categories/{ID}/practices
他のプラクティス関連ページと同じように mentor 以下に移動させたい。

この作業と一緒に、カテゴリーからプラクティス並べ替えページに行った時、

<img width="1420" alt="貼り付けた画像_2023_08_31_0_39" src="https://github.com/fjordllc/bootcamp/assets/168265/7106c456-d856-44cb-a11b-87b47f171fc9">

カテゴリーのタブがアクティブになるように修正をお願いします。

## プラクティス作成と編集

現在のURL
http://localhost:3000/practices/new
他のプラクティス関連ページと同じように mentor 以下に移動させたい。

この作業と一緒に、プラクティス作成と編集ページに行った時、

<img width="342" alt="貼り付けた画像_2023_08_31_1_28" src="https://github.com/fjordllc/bootcamp/assets/168265/c48dda2c-327b-41ed-ba61-99b76a74089e">

プラクティスのタブがアクティブになるように修正をお願いします。

---

もし、他にも mentor 以下に移動させたほうがいいページがあったら言ってださいー

## コース作成
現在のURL
http://localhost:3000/courses/new
他のプラクティス関連ページと同じように mentor 以下に移動させたい。

**Comment by machida** [comment]
@rira100000000 こちらアサインさせていただきましたー

**Comment by Kassy0220** [comment]
@rira100000000 
お疲れ様です！

RiraさんにアサインされているこのIssueに関して、[自分にアサインされているIssue](https://github.com/fjordllc/bootcamp/issues/6844)と次の作業箇所が被っています。

+ コースページからカテゴリー並び替えページに行った時、コースのタブがアクティブになるようにする
+ カテゴリーページからプラクティス並び替えページに行った時、カテゴリータブがアクティブになるようにする

もしすでにriraさんが実装されているなら、この箇所の実装はriraさんにお願いしようと思うのですが、いかがでしょうか？
または、自分が実装した方が良いのであれば、その時は仰っていただけるとありがたいです。
ご確認をよろしくお願いいたします🙏

**Comment by rira100000000** [comment]
本番環境での確認ができたのでcloseします。
