### ISSUE TITLE
User の discord_account 属性 と DiscordProfile の ccount_name 属性 が混在しているので、discord_account 属性 を削除したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6856]
User の discord_account 属性 と DiscordProfile の ccount_name 属性 が混在していたためバグが発生していた。

こちらでバグは修正したが、
https://github.com/fjordllc/bootcamp/pull/6855
User の discord_account 属性のコードはまだ残っている状態。

User の discord_account 属性 のコードと、DB のカラムの削除をお願いします。
https://github.com/fjordllc/bootcamp/issues/6818

**Comment by machida** [comment]
この Issue と
https://github.com/fjordllc/bootcamp/issues/6818
この Issue は同時に行う。

**Comment by machida** [comment]
#6447 でやってくれた @mono-nobe さんの作業の一部が main ブランチで消えてるっぽい。

**Comment by sochi419** [comment]
本番環境で確認できたのでcloseします。
