### ISSUE TITLE
定期イベントの主催者が退会、休会などして主催者がいなくなってしまった場合は、管理者が主催者になるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6876]
@komagata さんを主催者にする

**Comment by natsuto6** [comment]
@machida 
こちらのIssueについて、discordにてjnchitoさんからご助言があったので確認させていただきたいです。
そもそも「定期イベントの主催者が退会、休会する」を実行したタイミングで、「あなたが主催者の定期イベントがあります。`komagata`を主催者に変更してから退会 or 休会してください」みたいなエラーメッセージを表示する実装にするのはいかがでしょうか？

UI上から主催者を変更できるのは確認しました。
てっきり自動でkomagataさんを割り当てる実装を考えておりましたが、こちらの対応で問題ないでしょうか？

**Comment by natsuto6** [comment]
machidaさんより
> なるほど！確かにそれで要件は満たしています。退会、休会のときに自分が主催しているイベントがあったらエラーを出し、そのエラーには該当する定期イベントの編集画面へのリンクを表示してあげたいです。
また、定期イベントの主催をしてる人には退会、休会フォームにアクセスした時点で定期イベントの主催者をkomagataに変える必要がある旨のメッセージとそのリンク先を表示しておきたいです。
ただし、定期イベントが終了しているものは主催をしていても無視するようにしたいです。
複数主催してる場合は、その数だけエラーを表示したいです。

**Comment by natsuto6** [comment]
komagataさんより
> ただ、お客さんが退会するときに義務を課すというのは、お客さん視点からはちょっと嫌だなと思われてしまうかもと思いました。
もう関わりたくないからやめてしまう！という時に何か義務があって退会できないというのはお客さん視点からはちょっとフェアじゃないように思われてしまうかも。
退会する時というのはサービスに好意を抱いていない可能性も高いと思うので。

**Comment by natsuto6** [comment]
machidaさんより
> そうですね、請求の関係で一刻も早く退会、休会をする必要なケースもあり、システム側で自動でやってくれるのであればそれに越したことはないです。ただ、休会、退会フォームに自分が主催している定期イベントがある場合はメッセージを表示したいと思いました。余裕がある場合は、別の参加者に主催者を引き継ぐことをおすすめしたいです。その部分は僕の方でデザインやメッセージを入れるので、仮の物を退会フォーム、休会フォームに出しておいていただけると助かります。

**Comment by natsuto6** [comment]
「自動でkomagataさんを割り当てる処理」と「休会、退会フォームに自分が主催している定期イベントがある場合は、任意で別の参加者に主催者を引き継ぐことをおすすめするメッセージを表示する」の両方を実装する

**Comment by natsuto6** [comment]
イベント主催者の退会/休会の発生を待つのは困難なため、本番でテストユーザーを使って動作確認を実施いただきました。closeします

**Comment by komagata** [comment]
@natsuto6 誰が確認したというのも大事な情報なので記載しておいていただければありがたいです〜
（後から関連した問題が発生したときにとても大事で、この人に直接聞いたらすぐに解決したりするので）

**Comment by natsuto6** [comment]
@komagata 
承知しました！komagataさんのお名前を追記させていただきました🙇‍♂️
