### ISSUE TITLE
Chrome115以上を使用している場合にWebdrivers::VersionErrorが発生する

### ISSUE THREAD

**Issue by dowdiness** [fjordllc/bootcamp#6881]
## 概要

[こちらの記事](https://qiita.com/jnchito/items/f994dd3ac2cdc39bff8c)で説明されている通り、ローカルでインストールされているChromeが115以上の場合システムテストが実行出来なくなっています。

記事に紹介されているようにGemfileからwebdriversを削除した後、Webdriversの設定をしているコードを`vcr_helper.rb`と`test_helper.rb`から削除したら問題なく動くようになると思います。

### 参考

https://github.com/titusfortner/webdrivers#update-future-of-this-project

## 再現手順

Chrome115以上をインストールしている場合システムテストを実行したらエラーが起こる。

## 期待される振る舞い

Chrome115以上をインストールしていてもシステムテストが実行できる。

**Comment by komagata** [comment]
@dowdiness Issue作成ありがとうございます。
もしお時間あればPRいただければありがたいです〜！

**Comment by komagata** [comment]
:memo: 昼のミーティングで @sochi419 さんに担当していただくことになりました。

**Comment by sochi419** [comment]
本番環境で確認ができたので、closeします。
