### ISSUE TITLE
ログインしていない状態でユーザー個別ページにアクセスした場合は、トップページにリダイレクトさせるのではなく、ユーザーIDだけを表示したログインしていない人向けのユーザー個別ページを表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6886]
https://github.com/fjordllc/bootcamp/pull/6257
こちらを参考にお願いします。

デザインは machida がやります。

**Comment by machida** [comment]
@2525nicole 質問ありがとうございます！！この認識でほとんどOKですー
一点だけ、IDなのですが、DB上のユーザーIDではなく、FBC上のアカウント名（machida など）でお願いしたいですー🙏

**Comment by 2525nicole** [comment]
本番環境で動作確認ができたためcloseいたします🙇‍♀️
