### ISSUE TITLE
FAQにカテゴリを付けたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6889]
カテゴリーは、

- 学習内容について
- 学習環境について
- 利用料について
- 就職について
- 入会について
- 退会、休会、卒業について
- 法人利用について

をお願いします。

- 「質問 +  答え」は
    - 必ず一つのカテゴリーに所属する。
    - 複数のカテゴリーには所属しない。

**Comment by machida** [comment]
@sochi419 このIssueの説明文にカテゴリーを書きましたー

**Comment by sochi419** [comment]
@machida 
説明文の記載ありがとうございます〜🙏

**Comment by sochi419** [comment]
@machida 

お疲れ様です！
こちらのissueの「UI上の表示」について相談させてください🙏

# 相談内容1
管理ページ上(https://bootcamp.fjord.jp/admin/faqs) のUIは、現状は「質問」「回答」「編集」「並び順」というカラムがある表になっているが、ここに「カテゴリ」のカラムを1行追加する方針で良いか？

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0ZHQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26609c9ce2cf4ce2327d9dbd820d845098074f1c/image.png)

# 相談内容2
管理ページ上からFAQを新規作成するとき(https://bootcamp.fjord.jp/admin/faqs/new) に、カテゴリを選択する仕様で良いか？
（現状の仕様では、質問と回答を書くフォームのみが用意されている）

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXBHQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1aff695d69293a8ad87770d2dfb25eb9657970c0/image.png)

下記は別PRで見かけたものですが、イメージとしては以下の様な「カテゴリ選択」ができるものを、FAQ作成ページ上に表示させる方向で考えています。
![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RHQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b359791078bd219e1bc60cfdbf7b31a7c07c4be1/image.png)

# 相談内容3
[FAQページ](https://bootcamp.fjord.jp/faq ) (`https://bootcamp.fjord.jp/faq`)は、今回のissueのカテゴリ追加に伴って、変更を加える必要はあるか？

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWhHQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d87f742e8154536ce18fef8f61396e9dd250ba5/image.png)

**Comment by sochi419** [comment]
@machida 

もう1点、ブランチの切り方について相談させてください🙏

このissueはyumaさんが実装した[こちらのPR](https://github.com/fjordllc/bootcamp/pull/6727)の続きで、まだyumaさんのPRはマージされていません。yumaさんのブランチから、今回の作業のブランチを切っていいのでしょうか？また、その場合に以下の点が気になっています。

## yumaさんのブランチから作業ブランチを切る場合
また、作業ブランチをリモートにpush する前に、リモートの main ブランチが更新されていないか確認のために rebase をするよう、[チーム開発作業手順](https://bootcamp.fjord.jp/pages/305#push)に記載されています。
````
git pull --rebase origin main
````

`mainブランチ → 私の作業ブランチ`というブランチの切り方ではなく、`mainブランチ → yumaさんのブランチ（未マージ） → 私の作業ブランチ` というブランチの切り方の場合、上記のコマンドは合っていますでしょうか？

他の人のPRの続きから作業をした経験がないので確認させていただきたいです🙏
よろしくお願いします。

**Comment by machida** [comment]
ブランチの切り方はそれで合ってます。yumaさんのブランチから別ブランチを生やし、それのブランチで
最新の main をリベースしてください。

カテゴリは管理画面からカテゴリを選択できるようにしてください。今回はカテゴリは一つしか選択できないように、チェックボックスではなくラジオボタンにしてください。細かいデザインはmachidaがやります。
また、管理画面の一覧画面では今のものにカテゴリを持つ形にしてください。並べ替えは生かしたままでお願いします。カテゴリごとにリストが分かれてる方がより好ましいです。

管理画面ではなく訪問者が見るFAQページは、カテゴリ毎に絞り込みができるようにしてください。デフォルトは全てが選択されていて、全てを表示しておいてください。その際、カテゴリごとにリストが分かれているようしてください。

**Comment by sochi419** [comment]
@machida 

お疲れ様です！
もう一点確認したいことがあります。
PRを作成する際に私の作業ブランチと比較するブランチを選択するのですが、

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8bce276048fcb7fa72112ceffb315fc32f7bcc3d/image.png)

今回のPRでは、mainブランチをcompareするのか、yumaさんのブランチをcompareするべきなのか相談させていただきたいです。

試しにmainブランチと比較したPRを作成してみたのですが、`Files changed`がPRを作成した時点で36件ありました。
<img width="941" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/daffb15a-20a6-44a7-8ebe-44c8008f54f6">

mainブランチではなく、他人の作業ブランチから私の作業ブランチを切った場合はこうなるものなのでしょうか？（今回の私の作業が既にある36件の`Files changed`とごちゃ混ぜになって、確認者が私の追加した差分を探し出すのが大変だなと思ってしまいました。）

**Comment by machida** [comment]
メインとの差分なのでそうなります。
mainではなくブランチを作ったものブランチにPRを向けると、そのブランチとの差分だけが表示されます。

**Comment by machida** [comment]
PRを元ブランチに向けて出し、元ブランチにマージしてからmainにマージするでもOKです。

**Comment by sochi419** [comment]
回答ありがとうございます🙏

> PRを元ブランチに向けて出し、元ブランチにマージしてからmainにマージするでもOKです。

今回のPRでは元ブランチ（yumaさんのブランチ）をcompareしたPRを作成して、元ブランチにマージする流れにしたいと思います~
