### ISSUE TITLE
ブログ記事に内容に応じたサムネイル（OGPイメージ）を自動で設定できるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6895]
## サムネイル

- Ruby
- Ruby on Rails
- JavaScript
- WSL2
- Linux
- アドバイス
- スクール情報
- 自分で設定

を用意し、「自分で設定」以外は、予め用意したサムネイル画像が適用されるようにしたい。
今ある記事は、全て自分で設定しているので、「自分で設定」が選択されているようにする。

---

<img width="1063" alt="貼り付けた画像_2023_09_14_17_43" src="https://github.com/fjordllc/bootcamp/assets/168265/04e20f16-2836-45d5-ba30-f5b9f707b6b2">

---

画像はこちらです。

[サムネイル.zip](https://github.com/fjordllc/bootcamp/files/12606809/default.zip)

WSL2の画像は用意するので着手するときに言ってください。

**Comment by syo-tokeshi** [comment]
@machida 
お疲れ様です。
質問してよろしいでしょうか？

# 「ブログ記事に内容に応じたサムネイル（OGPイメージ）を自動で設定できるようにしたい」について

この「ブログ記事」とは [ブログ \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/articles)
こちらのページの、一つ一つの記事、という理解でよろしいでしょうか？

**Comment by machida** [comment]
@syo-tokeshi そうです！articles show です。

**Comment by syo-tokeshi** [comment]
> @syo-tokeshi そうです！articles show です。

かしこまりました🙇‍♂️
ご返答ありがとうございます！

**Comment by syo-tokeshi** [comment]
[個人めも]
やること

- [ ] articlesコントローラーのshowアクションを探す
- [ ] /articles下のviewファイルを確認する
- [ ]  articleモデルがあるなら確認する
- [ ] ブログ記事を構成しているhtmlファイルにセレクトボックスを作る
- [ ] 「自分で設定」以外の選択を選んだ場合は`assets`になる画像ファイルが自動で選ばれるようにする
- [ ] 「自分で設定」を選んだ際は、既存のActiveStorageのクラスを利用し、ファイルをアップできるようにする
- [ ] 
- [ ] 
- [ ]

**Comment by syo-tokeshi** [comment]
@machida 
@komagata 
お疲れ様です。
念の為実装方法をご確認させて頂いてもよろしいでしょうか?(手戻り作業を防ぐ意味があります)

# 実装方法

1. articlesテーブルにthumbnail_typeというカラムをinteger型で追加する
1. enum型でthumbnail_typeを管理する(「自分で設定する」を選んだ際は`set_by_me`という名前で管理する)

[例]
```ruby
enum thumbnail_type: {Ruby: 0, Ruby_on_Rails: 1,JavaScript: 2, WSL2: 3, Linux: 4, Advice: 5, school_information: 6, set_by_me: 7}
```

3. 「自分で設定する」以外は`app/assets/images/articles/thumbnails`配下に画像を保存する
4. 「自分で設定する」はActiveStorageの機能を使い`public.active_storage_blobs`テーブルを利用し、画像を保存する

という実装にしようと考えているのですが、いかがでしょうか？

**Comment by komagata** [comment]
@syo-tokeshi 上記の感じで大丈夫です〜。

コードをここまで書いて聞く場合はPRを作るのが双方にとって手っ取り早いかもです〜。
（Pull Requestが元々自分のコードをプルして確認してくださいリクエストなので）

動かなくてもよくて、bこんな方向性でどうですか？

**Comment by syo-tokeshi** [comment]
> @syo-tokeshi 上記の感じで大丈夫です〜。
> 
> コードをここまで書いて聞く場合はPRを作るのが双方にとって手っ取り早いかもです〜。 （Pull Requestが元々自分のコードをプルして確認してくださいリクエストなので）
> 
> 動かなくてもよくて、「こんな方向性でどうですか？」というのは仕事でもよくやります。

なるほどです！
確かにそのやり方でプルリクあげちゃった方が早かったですね、、🙇‍♂️

ご教授いただきありがとうございます🙇‍♂️

**Comment by syo-tokeshi** [comment]
> WSL2の画像は用意するので着手するときに言ってください。

@machida 
お疲れ様です。
WSL2の画像を頂いてもよろしいでしょうか？

**Comment by syo-tokeshi** [comment]
@machida 
お疲れ様です。

# ご依頼

上記で質問しました画像を頂けますでしょうか？🙇‍♂️
https://github.com/fjordllc/bootcamp/issues/6895#issuecomment-1726776833

# 確認

こちらのissueで
- og画像
- twitter(新X)画像

も、ラジオボタンの選択肢により、変更する形へ、修正する形でよろしいでしょうか？
現在は
https://github.com/fjordllc/bootcamp/blob/main/app/views/articles/show.html.slim#L10-L11

のように、もしサムネイル画像を設定していない場合は`https://bootcamp.fjord.jp/ogp/ogp.png`の画像が使用されるようになっています。
```erb
  if @article.thumbnail.attached?
    set_meta_tags(og: { image: @article.thumbnail_url, url: request.url })
    set_meta_tags(twitter: { image: @article.thumbnail_url, url: request.url })
  else
    set_meta_tags(og: { image: image_url('https://bootcamp.fjord.jp/ogp/ogp.png'), url: request.url })
    set_meta_tags(twitter: { image: image_url('https://bootcamp.fjord.jp/ogp/ogp.png'), url: request.url })
  end
  ```

**Comment by machida** [comment]
@syo-tokeshi 

## 1

デザインを入れるときに画像を用意するので、一旦、仮の画像で対応をお願いします。

![wsl2](https://github.com/fjordllc/bootcamp/assets/168265/710cd4b1-d9ec-4811-9815-a78c6c9451fc)

![javascript](https://github.com/fjordllc/bootcamp/assets/168265/5d86446f-602a-47aa-aa39-71636aeb5aa6)

**Comment by machida** [comment]
## 2

- og画像
- twitter(新X)画像

上記2つは同一にしてください。
og画像をTwitter画像にも使うということです。

ここで注意があります。

- og画像
- twitter(新X)画像

これらはどちらも相対パスではなく、https から始まるドメインを含んだ URL で指定する必要があります。
なので、画像は assets の下ではなく、public の中の ogp ディレクトリの中にあることが必要です。
（ assets/images の中の画像はアセッツプリコンパイルをするときに、ハッシュ値を含んだファイル名になってpublicに書き出されるので、書き出す度にファイル名が変わってしまうので、OGP Image には使えない 参考: https://techblog.kyamanak.com/entry/2017/10/13/003818）

**Comment by machida** [comment]
@syo-tokeshi 

今回の Issue を作った時点では、サムネイルが設定されていない場合のことを考えていませんでした。
以下のようにお願いします。

- 管理画面からサムネイルの設定無しに投稿することは不可能にしてください（ラジオボタンのデフォルトでなにかにチェックを入れておく。そうすればサムネイルの設定無しに投稿することは不可能になる）
- ただし、サムネイルの設定がされていない場合は、現状のまま、`https://bootcamp.fjord.jp/ogp/ogp.png` この画像を表示するようにしてください。サムネイルの設定がされていないブログ記事があってもエラーを出さないためです。すべてのブログ記事のサムネイル設定が完了したら、サムネイルの設定がされていない場合についてのコードは消そうと思います。

**Comment by toke04** [comment]
@machida 
@komagata 
お疲れ様です。
こちらのissueなのですが、入社が明後日からになってしまい、仕事の関係で対応するのが難しいのですが、他の方に引き継いで頂くこと可能でしょうか？

**Comment by machida** [comment]
@toke04 はい、大丈夫です。アサインを外しておきますー

**Comment by machida** [comment]
@Sasaco-JM こちらの作業を引き継いでいただきたいです。受講生レビューは通ってるので、駒形さんレビューを通るように作業をお願いします🙏

**Comment by komagata** [comment]
@Sasaco-JM 完了したらIssueのCloseをお願いします〜

**Comment by Sasaco-JM** [comment]
@komagata @machida 
すみません、先日discordで依頼させていただいたのですが、本番での動作確認をお願い出来ますでしょうか。


確認手順
1. https://bootcamp.fjord.jp/articles にアクセス
1. [PR](https://github.com/fjordllc/bootcamp/pull/6925)に記載の変更確認手順5からを参照

issueやPRでご連絡差し上げるべきところdiscordでのみの依頼となっており申し訳ありません。
お手数ですがよろしくお願いいたします。

**Comment by machida** [comment]
@Sasaco-JM こちら本番で確認できましたのでクローズしますー🎉

サムネイルがなかったこの記事に適用しました。
https://bootcamp.fjord.jp/articles/10

**Comment by Sasaco-JM** [comment]
@machida 
ご確認ありがとうございました 🙇
