### ISSUE TITLE
FooterのFBC Contributorsのリンクを外す。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6896]
ログインしたときの画面のフッターにあるFBC Contributorsを削除。

<img width="1873" alt="貼り付けた画像_2023_09_13_22_44" src="https://github.com/fjordllc/bootcamp/assets/168265/00616d13-b975-4219-b11a-f19b08a8034f">

**Comment by carlospazuzu** [comment]
I would like to work on this issue!

**Comment by komagata** [comment]
@carlospazuzu Thank you for your comment.
PR is always welcome!

**Comment by omochiumaiumai** [comment]
本番環境で動作確認を行いました！Issueをcloseしました。

**Comment by carlospazuzu** [comment]
ありがとう！お疲れ様でした！
