### ISSUE TITLE
お帰りなさいコメントなど、ピヨルドアカウントを作ってそれが発言するのがいいかも

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#6905]
休会復帰お帰りなさいコメントなど、「機械的にコメントされてたのかよ、裏切られた！」とならないようにピヨルドのアカウントを作ってそちらがコメントするようにした方がいいかも

**Comment by machida** [comment]
そっちの方がいいですね！

**Comment by machida** [comment]
@omochiumaiumai

すぐに bot とわかるアカウントを設定し、そこからの発言に変更します。
bot 用アカウント本番環境、開発環境、テスト環境に作る必要があります。
その辺の進め方は @komagata さんと連絡を取り合いながら進めるようお願いします。

**Comment by komagata** [comment]
@omochiumaiumai ピヨルド用のユーザーを作成してそこからの発言って感じになりそうですね。（FBCのユーザー）
seedに自分でそれ用のユーザーを作ってみてください〜

**Comment by omochiumaiumai** [comment]
@komagata
お疲れ様です！
> ピヨルド用のユーザーを作成してそこからの発言って感じになりそうですね。（FBCのユーザー）
seedに自分でそれ用のユーザーを作ってみてください〜
https://github.com/fjordllc/bootcamp/issues/6905#issuecomment-1883066464

seedにピヨルドのユーザーを作成しました。
以下のような内容で問題ないでしょうか？
```ruby
# db/fixtures/users.yml

pijord:
  login_name: pijord
  email: pijord@ fjord.jp
  crypted_password: $2a$10$n/xv4/1luueN6plzm2OyDezWlZFyGHjQEf4hwAW1r3k.lCm0frPK. # testtest
  salt: zW3kQ9ubsxQQtzzzs4ap
  name: ピヨルド
  name_kana: ピヨルド
  twitter_account: pijord
  facebook_url: https://www.facebook.com/fjordllc/pijord
  github_account: pijord
  blog_url: http://pijord.org
  description: "ピヨルドです。"
  course: course1
  job: office_worker
  os: mac
  experience: rails
  organization: Fijord Boot Camp
  admin: true
  mentor: false
  unsubscribe_email_token: Xw-T0PjrO2LTkCx1C8KA9w
  updated_at: "2021-02-01 00:00:30"
  created_at: "2021-02-01 00:00:30"
  sent_student_followup_message: true
  last_activity_at: "2021-02-01 00:00:30"
```
問題がなければこちらのユーザーから発言させるように進めていこうと思います。
ご確認をお願いいたします🙇‍♂

**Comment by komagata** [comment]
@omochiumaiumai 

> email: pijord@ fjord.jp

ここにスペースが入っちゃってるかもです。上記で基本的にOKです〜。

**Comment by komagata** [comment]
@omochiumaiumai 「komagataです」を抜いたってことですよね？
上記でOKです。ありがとうございます〜！

**Comment by omochiumaiumai** [comment]
@komagata 
お疲れ様です！
先日のMTGで挙げたフォローアップのメッセージが相談部屋に届かない件について、自力での解決が難しいと感じたため質問をさせてください。

## 質問部屋にフォローアップのメッセージが届かない問題
scheduler_daily_send_message_path(localhost:3000/scheduler/daily/send_message) にアクセスしてshowアクションを呼び出したのですが、入会30日目のユーザー(thirty)の相談部屋にメッセージが届きません。
メッセージが飛ぶまでの流れは以下のように捉えております。間違いがありましたら指摘をお願いいたします。
### 処理の流れ
```ruby
# app/controllers/scheduler/daily/send_message_controller.rb
  def show
    User.mark_message_as_sent_for_hibernated_student
    sent_student_followup_message
    head :ok
  end
```
```ruby
# /Users/mn/bootcamp/app/models/user.rb
def mark_message_as_sent_for_hibernated_student
      User.find_each do |user|
        if user.hibernated?
          user.sent_student_followup_message = true
          user.save(validate: false)
        end
      end
    end
```
```ruby
# app/controllers/scheduler/daily/send_message_controller.rb
  def sent_student_followup_message
    User.students.find_each do |student|
      next unless student.followup_message_target?

      User.create_followup_comment(student)
    end
  end
```
```ruby
  def followup_message_target?
    current_student? && !hibernated? && after_twenty_nine_days_registration? && !sent_student_followup_message
  end
```
```ruby
# /Users/mn/bootcamp/app/models/user.rb
    def create_followup_comment(student)
      User.find_by(login_name: 'komagata').comments.create(
        description: I18n.t('talk.followup'),
        commentable_id: Talk.find_by(user_id: student.id).id,
        commentable_type: 'Talk'
      )
      student.sent_student_followup_message = true
      student.save(validate: false)
    end
  end
```
1. showアクション呼び出し(localhost:3000/scheduler/daily/send_messageへのアクセス)
2. mark_message_as_sent_for_hibernated_studentメソッドが呼び出され、休会中のuserのsent_student_followup_messageをtrueに変更し保存
3. sent_student_followup_messageメソッドが呼び出され、followup_message_target?メソッドで現役生かつ休会中ではなく、登録から29日以上経過していてフォローアップメッセージを送信していないuserを検索
4. 上記のuserにcreate_followup_commentメソッドで相談部屋にフォローアップメッセージを送信、userのsent_student_followup_messageをtrueに変更し保存

フォローアップメッセージ関連のメソッドにはまだ手を加えていないため、変更によってメッセージが飛ばなくなったとは考えにくく、どこに原因があるのか掴めずにいます。
seedやテストの確認も行いましたが、どれも特に問題はなさそうでした。
よろしければご教示いただけますと幸いです🙇‍♂

**Comment by komagata** [comment]
@omochiumaiumai それぞれの段階をデバッグして、どこまでは処理が来ているのかを調べるのはいかがでしょうか。

**Comment by omochiumaiumai** [comment]
こちらのIssueはリリース完了のためcloseします。
