### ISSUE TITLE
分報チャンネルを自動で作成する際にユーザーの分報URLも自動で登録されてほしい

### ISSUE THREAD

**Issue by ogawa-tomo** [fjordllc/bootcamp#6907]
## 機能の説明
ユーザーの新規登録時に分報チャンネルを自動で作成するようになっていますが、その際にプロフィールページの分報URLは入力されません。ここも自動で入力されるようにすると便利かと思いました。

![image](https://github.com/fjordllc/bootcamp/assets/46841037/085a9b82-9a27-4906-bea6-b2ccc1aaa05e)

![image](https://github.com/fjordllc/bootcamp/assets/46841037/113c65fd-85e0-4f53-af58-78bfc41746a5)

## 補足
分報チャンネルを作成するときに何らかの方法でURLを取得し、ここでtimes_urlも一緒に登録するとよさそうです。
https://github.com/fjordllc/bootcamp/blob/3a31a334d41f50521be39590f014b87928f464d6/app/models/times_channel_creator.rb#L9

また、退会時に分報を削除する際もtimes_urlを削除する必要があります。
https://github.com/fjordllc/bootcamp/blob/6739439d096eeca58312faa307ad577b15d8cf62/app/models/times_channel_destroyer.rb#L8

**Comment by natsuto6** [comment]
本番環境で動作確認頂いたのでcloseします。
