### ISSUE TITLE
Q&Aの削除確認メッセージが受講生向けになっている

### ISSUE THREAD

**Issue by rira100000000** [fjordllc/bootcamp#6918]
![image](https://github.com/fjordllc/bootcamp/assets/99132547/e6bad50c-854c-427a-95e4-c6611575848c)

Q＆Aの削除機能はメンター/adminユーザー専用になったが、削除確認メッセージが受講生向けの内容のままになっているので修正したい。

**Comment by machida** [comment]
```
本当に削除しますか？質問はなるべく消さず、もし質問者が自己解決した場合も、質問者自身で解決した手段や手順を回答に記入し、それをベストアンサーにしてこの質問を解決することを即すようにしてください。
```

という文章に変更。

**Comment by natsuto6** [comment]
本番環境で動作確認いただいたのでcloseします
