### ISSUE TITLE
【メンター向け機能】日報にコメントをだけ入れて確認済みにしなかったらアラートを出す

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6928]
## 機能の説明

メンターが日報にコメントをだけ入れて確認済みにしないまま画面を離れようとしたらアラートを出す。

メッセージ例「日報を確認済みにしていませんがよろしいですか？」

## 何故この機能が必要なのか

本当はコメントを入れて日報を確認済みにすべきところを、コメントだけ入れて画面を離れてしまうことがたまにあるから。

ただし、確認済みにしなかったとしても致命的な問題ではないので、そこまで優先度の高い機能ではないかもしれない。

**Comment by machida** [comment]
📝 コメントのreact化が完了したらスタート。

**Comment by machida** [comment]
@unikounio ごめんなさい！これを見逃してました。別のIssueをアサインします🙇‍♂️

**Comment by unikounio** [comment]
@machida さん
迅速なご対応ありがとうございます🙏✨
該当Issueが完了するまでの間、本Issueのカンバンでの状態は現在のまま「作業中」とすべきでしょうか？👀

**Comment by machida** [comment]
@unikounio こちらアサインを外してやるに戻させていただきます🙇‍♂️

**Comment by su-su-su-su** [comment]
@machida 
お疲れ様です。確認したい点があります。
> 📝 コメントのreact化が完了したらスタート。

とあったのですが、#5122 を確認するとまだ作業中のとのことでした。
こちらまだ着手しない方が良いでしょうか？

**Comment by machida** [comment]
@su-su-su-su すいません、React化はまだ先になりそうなので、着手をお願いしますー🙏

**Comment by su-su-su-su** [comment]
@machida 
返信ありがとうございます。
かしこまりました！進めたいと思います🙇

**Comment by su-su-su-su** [comment]
@machida 

お疲れ様です。
メンターがコメントを投稿していて、かつその日報が確認されていない場合に、ページを離れる際にアラートを表示する機能を実装しようとしています。
現在`beforeunload`を使用して、ページを離れる際にカスタムメッセージを表示することを試みました。
以下が一部抜粋したコードです。

```Javascript
window.addEventListener('beforeunload', this.handleUnload)

handleUnload(e) {
  const userCommented = this.comments.some(
    (comment) => comment.user.id === this.currentUserId
  )
  const noConfirmed = !this.checkId;

  if (userCommented && noConfirmed) {
    e.preventDefault()
    e.returnValue = '日報を確認済みにしていませんがよろしいですか？'
  }
}
```
調べた結果、ブラウザの仕様により`beforeunload`イベントではカスタムメッセージを表示することができないことがわかりました。標準の警告メッセージが表示されてしまいます。
このためカスタムメッセージを表示することができない状況です。

またコメント途中にページを離れる際に出るアラートの部分(app/javascript/warning.js)も調べたのですが、こちらもカスタムメッセージがあるものの表示されるのは標準の警告メッセージが表示されてしまいます。

この問題に対して、カスタムメッセージを表示するための他のアプローチやブラウザの標準メッセージを利用するなど、何か他に解決方法がありましたら、ご教示いただけると幸いです。よろしくお願いいたします。

**Comment by machida** [comment]
@su-su-su-su 
調査ありがとうございます！！

「ページを離れる際に」だと、デフォルトのメッセージしか表示できなくなってしまったので、
コメントの投稿時にメッセージを表示するようにしたいです。

メンターのコメント欄は以下のようになってますが、

![Image](https://github.com/user-attachments/assets/24162ded-d0a1-4812-857d-41b54f1c22a5)

確認済になっていないとき、Bではなく、Aをクリックしたら、

「日報を確認済みにしていませんがよろしいですか？」

というメッセージが表示される、

というようにしたいです。

**Comment by su-su-su-su** [comment]
@machida 

ありがとうございます。画像も添付して頂き助かります！
> 確認済になっていないとき、Bではなく、Aをクリックしたら、
「日報を確認済みにしていませんがよろしいですか？」
というメッセージが表示される、
というようにしたいです。

承知しました。そのように変更したいと思います。

**Comment by su-su-su-su** [comment]
確認して頂いたcloseいたします。
