### ISSUE TITLE
みんなのブログが更新されない。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6929]
リリース時のまま止まっている。

**Comment by komagata** [comment]
@siso25 こちら確認いただければありがたいです〜

**Comment by siso25** [comment]
@komagata 
承知しました。
以下のissueが原因かと思いますので、こちらと一緒に対応いたします。

https://github.com/fjordllc/bootcamp/issues/6901

**Comment by ogawa-tomo** [comment]
@siso25 
横から失礼します:bow:
こちら、下記コントローラの定期処理が関係していますでしょうか？
https://github.com/fjordllc/bootcamp/blob/248b2e9016fd604618252a472dc48559d913df17/app/controllers/scheduler/daily/fetch_external_entry_controller.rb#L3
本番で動作していないのは、これがSchedulerControllerを継承していないからかもしれません。ベストアンサーなし通知で同じことが起きていました。
https://github.com/fjordllc/bootcamp/pull/6970
その場合、こちらのイシューの対応も必要となります。（一部は上記PRでも対応しています）
https://github.com/fjordllc/bootcamp/issues/6961
ご確認お願いします:pray:

**Comment by siso25** [comment]
@ogawa-tomo 
こちらに関しては以下のエラーで処理が止まっていることが原因のようですので、直接は関係ないかもしれません。
ただ、SchedulerControllerを継承するよう変更する必要はあるとおもいますので、対応いたします。
https://github.com/fjordllc/bootcamp/issues/6901

**Comment by JunichiIto** [comment]
> こちらに関しては以下のエラーで処理が止まっていることが原因のようですので、直接は関係ないかもしれません。

なんでこっちはユーザ認証をすり抜けて`fetch_and_save_rss_feeds`がキックされたんでしょうか？
https://github.com/fjordllc/bootcamp/issues/6901 で報告されたエラーはスケジューラの呼び出しによるものですか？
（誰かログイン済みのユーザーが該当URLにアクセスしたのではなく？）

この点を明確にしないとちょっと気持ち悪いですね。

**Comment by siso25** [comment]
@JunichiIto 
> こちらに関しては以下のエラーで処理が止まっていることが原因のようですので、直接は関係ないかもしれません。

上記のように記載したのですが、こちら勘違いをしておりました。申し訳ありません。
https://github.com/fjordllc/bootcamp/issues/6901 のエラーについては、本番での確認の際に私が誤って該当URLにアクセスした際に発生したものと思われます。

みんなのブログリリース後、スケジューラ上は正常系のHTTPステータスが返ってきているのに登録内容は更新されていなかったことから、本issueに関してはSchedulerControllerを継承していないために`fetch_and_save_rss_feeds`が実行されていないことが原因だと思います。

**Comment by JunichiIto** [comment]
ですよね！！

**Comment by machida** [comment]
本番で更新されているのが確認できたのでクローズします。

**Comment by siso25** [comment]
本番で正常に更新されていることが確認できました。また、https://github.com/fjordllc/bootcamp/issues/6901 のバグも発生していないとのことなので、本issueをクローズさせていただきます。
