### ISSUE TITLE
既読の通知を未読に戻す機能の追加

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6946]
## 機能の説明

一度既読にした通知を未読に戻せるようにする。
（例えば https://bootcamp.fjord.jp/notifications の各通知に「未読に戻す」ボタンを付ける等）

## 何故この機能が必要なのか

メンター業をするときに未読を一種のTODOリストとして使いたいときがある。
たとえば、未読の通知が数件ある状態で、未読の通知一覧から「未読の通知をすべて開く」をクリックし、各通知を確認していった結果、「これはちょっと対応に時間がかかりそうだからまたあとで時間のあるときにやろう」と思った通知があった場合、既読から未読に戻すことで、未読一覧を自分のTODOリストとして利用できる。

今は未読に戻せないため、一度既読にした通知であとで対応するものは、手元にあるTODOリストに該当ページのリンクを追加したりしている。

## 備考
bootcampの機能として用意しなくても運用でなんとかカバーできるので、対応は急ぎではありません。
また、実装に時間がかかりそうなら、費用対効果が悪いので「対応不要」でクローズしてしまうのもOKです。

**Comment by machida** [comment]
@JunichiIto 

僕はブックマーク機能でそれを補っているのですが、ブックマーク機能で今回の要望をカバーできたりしないでしょうか？ブックマーク機能試してみていただけると助かりますー🙏

**Comment by JunichiIto** [comment]
なるほど、じゃあそのやり方で運用してみます！
何か不都合が出てきたら再オープンさせてください〜。

**Comment by machida** [comment]
承知しました！
ブックマークの使い方を受講生にも知らせるためにプラクティスに書いておきますー
