### ISSUE TITLE
相談部屋の連絡通知がメールをオフにしても管理者にメールで届く。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6948]

**Comment by natsuto6** [comment]
@machida 
お世話になっております。
こちらのIssueですが、動作の再現は確認できましたがdiscriptionに何も記載がなく少し不安だったので以下確認させていただきたいです🙇‍♂️

## 再現手順
1. 管理者アカウントで**メール通知**を`OFF`にする
<img width="557" alt="_development__登録情報変更___FBC" src="https://github.com/fjordllc/bootcamp/assets/79001972/8fe7c125-fd2a-4cd1-92b7-804cd4e76874">

2. 例`kimura`でログインし、相談部屋からコメントをする。
3. `http://localhost:3000/letter_opener/`にアクセスすると、メールが届いてしまっている。

- Issueの内容については相違ないでしょうか？
- 「〜**メールをオフにしても管理者にメールで届く。**」の箇所ですが、管理者がメール通知をオフにする状況とは、管理者側にやむを得ない状況（体調不良やその他事情があった時）のような状況なのでしょうか？
修正すればよいだけかもしれませんが、受講生の立場の自分からすると少し背景が気になった次第です。
- そもそもdiscriptionが書かれていないことは往々にしてあることなのでしょうか？

お手数ですが、ご確認よろしくお願い致します。

**Comment by machida** [comment]
@natsuto6 
再現手順はそれで合ってます。

管理者はブートキャンプのアプリを開き放しなので、メールの通知は休日などブートキャンプを長時間開かないときがあるときだけ必要になります。

基本的にやりとりは書いてあることだけで終わらせようとはしていないので、Descriptionに何もないことありえます。詳しいところはコミュニケーションで確認したり決めたりしながら進めていこうとしています。

**Comment by natsuto6** [comment]
@machida 
承知いたしました。ありがとうございます！

**Comment by natsuto6** [comment]
本番環境で動作確認頂いたのでcloseします。
