### ISSUE TITLE
【メンター向け】「はじめての日報です！」の通知メールのリンクがおかしい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#6963]
## 概要

「○○さんのはじめての日報です！」の通知メールにある「この日報へ」ボタンのURLが http:///reports/82102 のようになっていて、クリックしても目的のページに遷移できない。（原因はなんとなく予想できるけど・・・w）

## 再現手順

（省略）

## 期待される振る舞い

該当の日報に遷移できる

## スクリーンショット

<img width="720" alt="fbc" src="https://github.com/fjordllc/bootcamp/assets/1148320/ef4f93d5-6c94-48fb-b3f3-9d3e03ba63c6">

**Comment by natsuto6** [comment]
@JunichiIto
いつもお世話になっております。 
こちらのIssueについて確認させていただきたいです。
間違っていましたらすみません。本番環境ではこちらのIssue#6963のようになっているよ、という認識でよろしかったでしょうか？
ローカルでまず動作確認を行ったところ、discriptionに記載いただいている内容と相違がありました。
1. `href="/reports/1066585819`のような相対URLになっている
2. 「日報へ」を押下すると、該当の日報に正しく遷移できる
https://gyazo.com/3a35f6cbfacae34cc18867b441dd9eea

動作確認した際の手順は以下です
1. `foreman start -f Procfile.dev`でローカル環境を立ち上げる
2. `nippounashi`でログイン
3. `http://localhost:3000/reports/new`で初めての日報を投稿
4. ログアウト
5. `komagata`でログイン
6. 「通知」に「nippounashiさんがはじめての日報を書きました！」が存在するか確認する
7. `http://localhost:3000/letter_opener/ `にアクセスし、メールが送られていることを確認する
8. 検証ツールで「この日報へ」ボタンのリンクを確認し遷移する

長くなりました。お手数ですがご確認よろしくお願い致します🙇‍♂️

**Comment by machida** [comment]
@natsuto6

メールの中のリンク先はどこかのサイト内ではないので、パスではなく、https://から始まるURLにする必要がありますが、現状はそうなっていないため、本番ではアクセスできないで状況です。

なぜ、ローカルではアクセスができているかは、ローカルではletter_opener_webというメールを確認するためのGemがあり、それを使ってブラウザからメールの内容を確認しているためです。

**Comment by JunichiIto** [comment]
原因は町田さんが説明されているとおりです。

「あるあるバグ」なので、もしかすると他にも同様のバグを抱えたメールがあるかもしれません。

**Comment by natsuto6** [comment]
@machida @JunichiIto 
ご連携いただきありがとうございます！
いただいた内容を元に対応を進めていきます🙇‍♂️

**Comment by natsuto6** [comment]
本番環境で動作確認いただいたのでcloseします

**Comment by JunichiIto** [comment]
@natsuto6 対応ありがとうございました！
