### ISSUE TITLE
Products.jsxのページネーションが連動しない

### ISSUE THREAD

**Issue by rira100000000** [fjordllc/bootcamp#6965]
## 概要
`/products`において、products.vueをProducts.jsxに置き換えると上下のページネーションが途中から連動しなくなる。

### 背景
Reactを使ったページのページネーションが途中から画面上下で連動しなくなるという不具合があり、[\#6952](https://github.com/fjordllc/bootcamp/issues/6952)で対応しています。
#6952対応当時の`/products`のページではProducts.jsxではなく、products.vueが使われており、Products.jsxの修正は行いませんでした。

## 再現手順
1. products.vueをProducts.jsxと置き換える。(置き換えの方法は[product\.vue, products\.vueのreact版コンポーネントを追加する　Pull Request \#6164 ](https://github.com/fjordllc/bootcamp/pull/6164)で確認してください)
2. Id:komagata でログイン
3. http://localhost:3000/products にアクセスする
4. ページネーションのリンク2をクリックする
5. ページネーションのリンク1をクリックする
6. 上下のページネーションが連動していないことを確認する

## 期待される振る舞い
ページネーションが上下で連動する。

## スクリーンショット
![ページネーション](https://github.com/fjordllc/bootcamp/assets/99132547/70ae4243-0a3f-469a-8fb6-b29f05cc5158)

**Comment by komagata** [comment]
@rira100000000 Issueの作成ありがとうございます！

**Comment by rira100000000** [comment]
@komagata 
お疲れ様です。
こちらのIssueについて、作業内容を確認しましたので報告します。

## 1.Products.jsxとproducts.vueの置き換え
###  コンポーネントのReact化
products.vueで使用している、まだReact化されていないコンポーネントをReact化します。
#### 対象ファイル
* ElapsedDays.vue
* product_checker.vue

### Products.jsxで経過日数と担当するボタンを表示させる
React化したコンポーネントをProducts.jsxに導入します。

### VueからReactへ置き換え
各indexファイルにてVueからReactへの置き換えをします。
* app/views/products/index.html.slim
* app/views/products/self_assigned/index.html.slim
* app/views/products/unassigned/index.html.slim
* app/views/products/unchecked/index.html.slim

## 2.Products.jsx内でのPaginationバグ修正
既に修正済みのPagination.jsxに対応させます。

## 当時置き換えなかった経緯について
LEFさんに確認したところ、影響範囲が大きかったためReact化したファイルの置き換えがされなかったようです。
現在はReactへのリプレースが進み、影響するファイルが2ファイルのみになっていますので十分対応可能かと思います。

**Comment by komagata** [comment]
@rira100000000 調査とまとめありがとうございます。非常に助かります〜！

**Comment by rira100000000** [comment]
@komagata @machida 
お疲れ様です。
メンター用ページの本番環境での確認にご協力をお願いいたします。

※任意の提出物にはID:rira100000000の「Vue.jsの基本の提出物」(11/16提出)を利用してください。

# 確認項目
## 全てページの確認
1. https://bootcamp.fjord.jp/products にアクセスする
2. wip、担当あり、担当なし、確認済みのそれぞれの提出物が表示されることを確認する
3. ページ最下部の一括で開くボタンが機能することを確認する

## ページネーションの確認
1. ページネーションのリンク2をクリックする
2. ページネーションのリンク1をクリックし、上下のページネーションのリンク1がアクティブになっていることを確認する

## 担当するボタンとトーストの確認
1. 担当者がいる提出物に担当者のアイコンと名前が表示されていることを確認する
2. 任意の提出物に対して担当するボタンをクリックし、担当になれること、トーストが表示されることを確認する
3. 担当から外れるボタンをクリックし、担当から外れられること、トーストが表示されることを確認する

## 未完了ページの確認
1. https://bootcamp.fjord.jp/products/unchecked にアクセスする
2. 任意の提出物タイトルをクリックする
3. 提出物ページでコメントする
4. https://bootcamp.fjord.jp/products/unchecked?target=unchecked_no_replied にアクセスし、コメントした提出物が一覧に表示されていないことを確認する
5. 任意の提出物タイトルをクリックする
6. 提出物ページで提出物を確認するボタンをクリックする
7. https://bootcamp.fjord.jp/products/unchecked にアクセスし、確認された提出物が一覧に表示されていないことを確認する
8. ページ最下部の一括で開くボタンが機能することを確認する

## 未アサインページの確認
1. https://bootcamp.fjord.jp/products/unassigned にアクセスする
2. 担当者のいない提出物だけが表示されることを確認する
3. 画面右、経過日数ごとのリンクが正常に機能することを確認する
4. ページ最下部の一括で開くボタンが機能することを確認する

## 自分の担当ページの確認
1. https://bootcamp.fjord.jp/products/self_assigned にアクセスする
2. 自分が担当している提出物が表示されていることを確認する
3. https://bootcamp.fjord.jp/products/self_assigned?target=self_assigned_no_replied にアクセスする
4. 未返信の提出物のみが表示されていることを確認する
5. 未返信の提出物にはユーザーアイコン左上に赤いドットが表示されることを確認する
6. ページ最下部の一括で開くボタンが機能することを確認する

## 未返信、全てボタンの確認
1. https://bootcamp.fjord.jp/products/self_assigned にアクセスする
2. 未返信ボタンをクリックする
3. https://bootcamp.fjord.jp/products/self_assigned?target=self_assigned_no_replied に遷移することを確認する
4. 全てボタンをクリックする
5. https://bootcamp.fjord.jp/products/self_assigned?target=self_assigned_all に遷移することを確認する

**Comment by komagata** [comment]
@rira100000000 下記のようなエラーが出ているみたいです。

<img width="1019" alt="スクリーンショット 2023-11-29 16 20 21" src="https://github.com/fjordllc/bootcamp/assets/16577/c619a41a-c72c-4c5c-aefe-d60a27c37e9a">

**Comment by rira100000000** [comment]
@komagata 

お疲れ様です。
現在発生している、https://bootcamp.fjord.jp/products/unchecked?target=unchecked_no_replied が表示できない問題についてですが、いただいたログから『commented_atが存在するが、コメントは無い提出物』が原因で発生していることがわかりました。
梅本さんとのペアプロでこのようなイレギュラーなデータが作られる原因を調べたのですが、コードからは原因を特定できませんでした。

検索クエリを修正することでエラー自体は回避できるため、エラー回避用のPRを作りましたので、確認をお願いいたします。
こちらの修正でイレギュラーなデータが存在しても影響を受けないようになり、本番環境でページが表示できない問題の解決と、現在既に作られてしまっているイレギュラーなデータへの対応が可能です。
https://github.com/fjordllc/bootcamp/pull/7087

## 今後の調査について
引き続き調査を進めるため、本番環境のrails consoleで以下のコマンドを実行し、結果を確認していただくことは可能でしょうか？

```ruby
products = Product.where.not(commented_at: nil).filter do |product|
  product.comments.last == nil
end
```

### 確認していただきたいこと
* そのようなデータは複数あるのか、1つなのか
* 複数ある場合、何か共通点はないか
* 提出物として正常なデータなのか、何か特徴が無いか

### 考えている事
ここで取得できたproductsが複数ある場合、コード自体に不具合が含まれている可能性が高いと思います。
1件しかないのであれば、コメントの削除には成功したがcommented_atの削除に失敗した、などのかなり特殊な状況もあるのではと考えています。

**Comment by komagata** [comment]
@rira100000000 

> 引き続き調査を進めるため、本番環境のrails consoleで以下のコマンドを実行し、結果を確認していただくことは可能でしょうか？

Cloud Runを使っている本番でrails consoleを使うことは難しいのですが、SQLを実行するのであれば簡単です。
できればSQLでもらえればありがたい感じです〜。

**Comment by rira100000000** [comment]
@komagata 
承知しました！こちらのSQLの実行をお願いします。

`SELECT * FROM Products WHERE commented_at IS NOT NULL AND NOT EXISTS (SELECT 1 FROM Comments WHERE Products.id = Comments.commentable_id)`

**Comment by komagata** [comment]
@rira100000000 SQLありがとうございます。非常に助かります。
結果は0件のようです。

![スクリーンショット 2023-12-10 17 43 22](https://github.com/fjordllc/bootcamp/assets/16577/d0e141bd-78b4-45a9-8cf1-12bb22578e24)

**Comment by rira100000000** [comment]
@komagata 
SQL実行ありがとうございます。
該当する提出物にコメントが付いた結果、当てはまるデータがなくなったのかと思います。
https://bootcamp.fjord.jp/products/unchecked?target=unchecked_no_replied ではまだ問題が発生していますでしょうか？

**Comment by komagata** [comment]
@rira100000000 

> うーん、『commented_atがあるのにcommentが無い提出物がある』のが原因だと思っていたのですが、該当するデータが無くてもエラーが出るということはそもそも問題点が違うのでしょうか…？

SQLが違うか、問題が違うのだと思います。
ちょっと僕も考えてみます。

**Comment by komagata** [comment]
@rira100000000 

#7145 を本番にリリースして直りました〜。
元の問題は #7144 にIssueを作ったのでこちらで修正したいと思います。（今スクラム中のどなたかに頼む感じになる予定です）

**Comment by rira100000000** [comment]
@komagata 
対応、確認ありがとうございます！
こちらのIssueは本番での確認が取れたためcloseします。
