### ISSUE TITLE
mention_usersとuser_icon_urlsのリクエストが多すぎるのでは？

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#7003]
提出物ページ（ https://bootcamp.fjord.jp/products/17756 等）を開いて、Networkタブを見ると、mention_usersとuser_icon_urlsへのリクエストが繰り返し発生していました。

しかも、レスポンスを見ると全Userのアカウント情報やアイコンURLを返しているように見えます。
304で返ってきているとはいえ、これはちょっとサーバーに対して負荷をかけすぎなのでは？と心配になりました

<img width="1275" alt="d1" src="https://github.com/fjordllc/bootcamp/assets/1148320/8e3ae061-5fbe-4502-8026-ad0450200537">
<img width="1274" alt="d2" src="https://github.com/fjordllc/bootcamp/assets/1148320/bf118445-5cec-4c3a-b7ac-431a7f0516dd">

あと、全Userの情報を返しているのもちょっと富豪的すぎるのではないかと思ったのですが、メンション機能を実現するにはこういう方法しかないのでしょうか？

（こういった点は考慮した上であえてこういう設計にしてあるとか、キャッシュを活用しているので問題ない、等々ので理由であれば、クローズしてもらって大丈夫です🙏）

**Comment by komagata** [comment]
:memo: 対応方法

1. ユーザーアイコンをユーザーIDから推測可能なURLにする。
2. user_icon_urlsを使わないようにする。

1は現在、Cloud Storageにアップしたファイル名を使ってるので、ファイル名を変えるなどが必要かも。
