### ISSUE TITLE
Docのページのtitleタグは、最初に Doc と表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7014]
## title タグと og:title を変更

Doc の個別ページ（pages/show）、例えばこの https://bootcamp.fjord.jp/pages/337 ページにアクセスすると、

現状 title タグは、

<img width="349" alt="貼り付けた画像_2023_11_01_22_35" src="https://github.com/fjordllc/bootcamp/assets/168265/9d723b59-c611-41fe-8961-a10bc3a19e82">

`<title>macOSの開発環境 | FBC</title>` となっている。

これを、`<title>Doc macOSの開発環境 | FBC</title>` としたい。

<img width="354" alt="貼り付けた画像_2023_11_01_22_40" src="https://github.com/fjordllc/bootcamp/assets/168265/78d6dd70-4d0c-4e6a-8caf-499c12e0950d">

また、`og:title` も同様に、現状は `macOSの開発環境 | FBC` となっていて、これも `Doc macOSの開発環境 | FBC` としたい。

## 注意 見出しはそのまま

しかし、ここで注意してほしいのが、

ページの中の見出しの表記、

![貼り付けた画像_2023_11_01_22_36](https://github.com/fjordllc/bootcamp/assets/168265/d8778b1d-2d50-4a95-967d-fe4bee09881e)

ここには、Doc という文字は入れないでほしい（見出しは現状のまま）。

**Comment by Sasaco-JM** [comment]
本番環境への反映を確認しましたのでクローズします。

**Comment by ham-cap** [comment]
@Sasaco-JM 
お疲れ様です。
こちらのissueは私のほうで現在作業中のものなのですが、別のissueとお間違えではないでしょうか？👀

**Comment by Sasaco-JM** [comment]
@ham-cap 
お疲れ様です。
大変申し訳ありません！別のissueと間違えております 🙇 
Reopenいたします。

**Comment by ham-cap** [comment]
@Sasaco-JM 
ありがとうございます😃
似たタイトルのissueがいくつかあって私も最初間違えそうになりましたのでお気になさらず👍

**Comment by ham-cap** [comment]
本番環境へ反映されておりましたのでクローズさせていただきます🙏
