### ISSUE TITLE
未読の通知一覧から未読項目が勝手に消えるのがちょっと不便

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#7017]
以下の操作をしたときに、未読の通知が見えなくなるのが地味に不便です。

未読の通知一覧を開く（★）
↓
「すべての未読を開く」ボタンをクリックする
↓
（未読の日報や提出物が別タブで開く）
↓
僕「この提出物、メンションも何もないし、なんで未読通知に上がってきたのかわからないなあ」
↓
ブラウザ上で未読の通知一覧のタブに戻る
↓
★で表示されていた未読通知がすべて消えて「未読の通知はありません」が表示される
（結局理由がわからない）

![Screenshot 2023-11-02 at 8 53 01](https://github.com/fjordllc/bootcamp/assets/1148320/d1d355da-2efa-47e6-80fe-ae7b957d238f)

以前は「すべての未読を開く」ボタンをクリックした後も、未読の通知一覧はそのまま残っていたと思います。
「全ての通知一覧」を開けばどういう理由で通知されたのか確認できなくはないですが、ちょっと不便なので、以前のように未読の通知一覧は残ったままになっている方が嬉しいです。

また、未読の通知から1クリックで全ての通知を表示できない点も不便に感じる理由の一つです。
https://github.com/fjordllc/bootcamp/issues/7016

## 実行環境
- macOS Sonoma 14.1
- ブラウザ Chrome Version 118.0.5993.117 (Official Build) (arm64)

**Comment by junohm410** [comment]
@JunichiIto 
CC: @komagata @machida 

お疲れ様です。本Issueをアサインいただいたshodanと申します。
取り組むにあたり、期待される挙動として確認させていただきたいことがあり、ご連絡いたしました。

## 期待される挙動の流れと、確認点
- 未読の通知一覧を開く（★）
- 「すべての未読を開く」ボタンをクリックする
- （未読の日報や提出物が別タブで開く）（◉）
  - 開かれた別タブのページでは、（未読のものをすべて開く処理がなされたため）右上の通知ベルに赤い丸がついておらず、すべてのお知らせが既読済みになっている
    - 確認点①: ↑これは現在もそのような挙動になっていますが、ここは変わらなくてよろしいでしょうか？
- ブラウザ上で未読の通知一覧のタブに戻る
  - このときに、未読の通知一覧は（★）の時点と同じ状態であってほしい（本Issueの主たる内容）
  - この未読の通知一覧タブを更新すると、「未読の通知はありません」になる（◉で未読通知をすべて開いたので、更新によってその結果が反映されたページに更新される）
    - 確認点②: ↑この更新時の挙動は、伊藤さんが望まれる挙動と一致していますでしょうか？


※確認点①は、現在の`main`で下の動画のように再現されるように、別タブで未読の日報等を一括で開いた際に、右上のベルの部分に赤丸がついていないのですが、それはそのままでいいでしょうか、という内容になります🙏
![kdIebS8e0J](https://github.com/fjordllc/bootcamp/assets/128765400/1861f99f-97ef-4956-a99c-7eb11d1410ea)



上で確認点①②とさせていただいた2つのことに関して、お手隙のタイミングでご確認いただき、お返事いただけるとありがたいです🙏
どうぞよろしくお願いいたします。

**Comment by JunichiIto** [comment]
@junohm410 
はい、基本的にその考えで合っています。

> ※確認点①は、現在のmainで下の動画のように再現されるように、別タブで未読の日報等を一括で開いた際に、右上のベルの部分に赤丸がついていないのですが、それはそのままでいいでしょうか、という内容になります🙏

右上のベルは非同期でデータを取得するので、件数はまちまちになると思います。そもそもベルの件数はあまり気にしていません。

shodanさんも書いてるとおり、「このときに、未読の通知一覧は（★）の時点と同じ状態であってほしい（本Issueの主たる内容）」が希望する内容です。
というか、以前はその動きだったと思うのですが、どこかのタイミングで挙動が変わって、即座に「未読の通知はありません」になってしまったと記憶しています。

**Comment by junohm410** [comment]
@JunichiIto 
ご返答、ありがとうございました。

> 右上のベルは非同期でデータを取得するので、件数はまちまちになると思います。そもそもベルの件数はあまり気にしていません。

すみません、ここで聞きたかったことの私の言語化がよくなかったです。
聞きたかったのはベルの件数についてではなく、『開かれた別タブの方では、開かれた（先ほどまで未読だった）日報などは、既読状態になっていることは正しい挙動でしょうか』ということでした。
ですが、これは現在の挙動と同じであり、今回の希望される内容とは異なる話でした。ややこしくしてしまい、すみませんでした🙇‍♂️

> どこかのタイミングで挙動が変わって、即座に「未読の通知はありません」になってしまったと記憶しています。

現時点の調査範囲では、下のPRによりお知らせ画面がVueからReactに書き換えられたタイミングで、以下のようなことが起きたからだと考えています。
https://github.com/fjordllc/bootcamp/pull/6979

- 未読お知らせのデータフェッチの方法が変わった（Reactの`SWR`フックを使うようになった）https://github.com/fjordllc/bootcamp/blob/33b4ffd5cb02dcfd30905eb50c03af71578d20e3/app/javascript/components/Notifications.jsx#L21
- それにより、タブ切り替えのタイミングで自動的にデータフェッチされるように設定に変わった（`SWR`のデフォルトの設定がそうなっている）

なので、新しく開いたタブから未読の通知一覧に戻った（＝タブ切り替え）際に、データフェッチが行われて、未読の通知が0の状態で表示される、という挙動になっているのではないかなと思います。

まずはこの線で、修正対応を試みたいと思います。
ご返答、ありがとうございました🙏

**Comment by komagata** [comment]
@JunichiIto (CC: @junohm410)

う〜ん、これって最新の情報と同期してるのは高機能化しているので、そうじゃなかった状態に戻すのはちょっと抵抗があります。

これを戻すとすると、そのために採用しているSWRを逆に使わない状態にする必要があって、それってイコールほとんどSWRはWebに要らないってことになっちゃいそうで今後の他の部分にも大きく影響しそうで気になっています。（今後SWRの自動フェッチしてくれるのはoffにして常に作るということになりそう）
[データ取得のための React Hooks ライブラリ – SWR](https://swr.vercel.app/ja)

> また、未読の通知から1クリックで全ての通知を表示できない点も不便に感じる理由の一つです。

これはわかります。これは直したいですね〜

**Comment by JunichiIto** [comment]
@komagata 

> う〜ん、これって最新の情報と同期してるのは高機能化しているので、そうじゃなかった状態に戻すのはちょっと抵抗があります。

技術者としては言いたいことはわかりますが、いちユーザーとしては高機能でも不便だったら意味ないやん、っていうのが正直な感想ですね。。。

https://github.com/fjordllc/bootcamp/issues/7150 にも書きましたが、何でもかんでも動的にデータをフェッチするのって、ユーザーの利便性から見ると常に最善とは限らないのではないでしょうか？
（チャットアプリとか、画面更新のリアルタイム性が求められるかどうかが判断基準？）

> これを戻すとすると、そのために採用しているSWRを逆に使わない状態にする必要があって、それってイコールほとんどSWRはWebに要らないってことになっちゃいそうで今後の他の部分にも大きく影響しそうで気になっています。（今後SWRの自動フェッチしてくれるのはoffにして常に作るということになりそう）

上のコメントと同じになりますが、ユーザーの利便性の観点からすると、適材適所で技術を使い分ける必要があるのではないでしょうか？
自動フェッチの必要性が薄い（もしくは利便性にマイナスに作用する）なら、SWRはデフォルトでオフ、という選択肢もあるんじゃないかなーと思います。

======

別の議論になりますが、この自動フェッチって、「未読の通知を一括で開く」ボタンと特に相性が悪いように感じます。
このボタンをクリックすると、元のタブに戻ってきたときに「未読の通知はありません」に変わってしまう点がUXとして良くないです。
ユーザーの操作と、得られる結果がユーザーの心理に一致していない感があります。
（未読の各ページを見たい、という心理に対して、画面上の「データが消える」という副作用が発生する。ユーザーとしては「見たい」だけであって、「消したい」わけではない）

bootcampアプリはもともと古き良きHTML/HTTPの作法に従ったUI設計になっているので、「タブを切り替えるたびに勝手に画面上のデータが増減する」というのはUI/UX的にマッチしていない気がします（ユーザーとしてそういう挙動を予想しづらい）。
SWRが有効に作用するのは、バリバリのSPAとか、最初からSWRの使用を前提としたUI/UX設計のwebアプリケーションになるのでは？と個人的には感じました。

**Comment by komagata** [comment]
@JunichiIto 

> 技術者としては言いたいことはわかりますが、いちユーザーとしては高機能でも不便だったら意味ないやん、っていうのが正直な感想ですね。。。

実際に記事を見たので意味的に既読なので、未読からなくなるのはおかしくないように思います。
僕は使い方が違うのだと思いますが特に不便に感じたことはありませんでした。
不便かどうかは使い方と各個人によるのではないのでしょうか。まだサンプルが１つなのでみんなにとって不便なことが自明ではないと思います。

**Comment by JunichiIto** [comment]
@komagata 

> 僕は使い方が違うのだと思いますが特に不便に感じたことはありませんでした。

今までできてたことができなくなった、という意味では僕はちょっとストレスを感じています。

> 不便かどうかは使い方と各個人によるのではないのでしょうか。まだサンプルが１つなのでみんなにとって不便なことが自明ではないと思います。

まあ、それはそうなので、他に意見が出てくるまでもう少し様子を見ますかねえ、、

**Comment by machida** [comment]
@komagata @JunichiIto 

未読表示のルールを変えるっていうのはどうでしょう？

未読を表示しても、

- 数時間以内は未読一覧に残る（すぐには消さない）
- 未読一覧には残るが、表示済のようなマークが付く

みたいな実装って可能ですか？

**Comment by JunichiIto** [comment]
@machida ご提案ありがとうございます！
komagataさんの返事待ちですが、かなり複雑性が増しそうな仕様に見えますね。。
僕が言うのもなんですが、「そこまで頑張らなくても」という感じです。

最近は慣れの問題かな、という気もしてきたので、（UXとして違和感は残るものの）他に困ってる人がいないならいったん今のままでもいいのかなーという気もしています。
