### ISSUE TITLE
提出物個別ページのtitleタグに提出物という文字を含めたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7043]
現在の提出物個別ページ（一覧ではなく個別ページ）では、

<img width="632" alt="貼り付けた画像_2023_11_08_17_17" 
src="https://github.com/fjordllc/bootcamp/assets/168265/d86365ff-33ba-4a13-bc79-ff00d01b5fdb">

titleタグが、

<img width="387" alt="貼り付けた画像_2023_11_08_17_19" src="https://github.com/fjordllc/bootcamp/assets/168265/3689423b-596d-41eb-9482-f9d27c3fde37">

`{プラクティス名} | FBC` となっている。

これを

`{プラクティス名}の提出物 | FBC` としたい。

変更するのは title タグの中だけで、ページ内の表示の変更は無しでお願いします。

**Comment by umizaru** [comment]
本番環境での動作確認が完了しましたのでCloseします！
