### ISSUE TITLE
Q&A個別ページのtitleタグは、最初に Q&Aと表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7044]
現在のQ&A個別ページ（一覧ではなく個別ページ）では、

<img width="908" alt="貼り付けた画像_2023_11_08_17_23" src="https://github.com/fjordllc/bootcamp/assets/168265/63da9ca0-9a69-458b-8943-662e9e61ff60">

titleタグが、

<img width="416" alt="貼り付けた画像_2023_11_08_17_23" src="https://github.com/fjordllc/bootcamp/assets/168265/33a2d3df-aa9d-4c69-b633-0bd81fe6d146">

`{Q&Aのタイトル} | FBC` となっている。

これを

`Q&A {Q&Aのタイトル} | FBC` としたい。

変更するのは title タグの中だけで、ページ内の表示の変更は無しでお願いします。

**Comment by 2525nicole** [comment]
本番環境での動作確認が完了したのでCloseいたします！

<img width="1404" alt="スクリーンショット 2023-11-16 19 45 37" src="https://github.com/fjordllc/bootcamp/assets/104631303/c268b6b9-7c9e-4e18-bc41-983a8e6a13bc">

レビューしてくださった皆様ありがとうございました🙇‍♀️
