### ISSUE TITLE
開発環境とステージング環境で５期生のユーザ一覧が表示されない

### ISSUE THREAD

**Issue by Kassy0220** [fjordllc/bootcamp#7057]
## 概要

開発環境とステージング環境で5期生のユーザー一覧ページ(`/generations/5`)にアクセスすると、次のような表示になり正しく表示されません。

## 再現手順

- 開発環境の場合
1. アプリを立ち上げる
2. `http://localhost:3000/generations/5`にアクセスし、読み込みの画面が表示され続けることを確認する

- ステージング環境の場合
1. ステージング環境(`https://bootcamp-staging.fjord.jp`)へアクセス
2. `https://bootcamp-staging.fjord.jp/generations/5`にアクセスし、ユーザー一覧が表示されないことを確認する

## 期待される振る舞い

5期生のデータは以下の通り22人分存在するはずなので、22人のユーザーが表示される。
<img width="975" alt="_development__期生別ユーザー一覧___FBC" src="https://github.com/fjordllc/bootcamp/assets/79003082/54d2fd2f-1ec5-4a6d-841c-7d701c3a8ede">

## スクリーンショット

- 開発環境では、ずっと読み込みの画面が表示されます
<img width="605" alt="_development__5期のユーザー一覧___FBC" src="https://github.com/fjordllc/bootcamp/assets/79003082/dc2f6247-ebf9-4d95-9269-1038862a118e">

- ステージング環境では、`5期生のユーザー一覧はありません`と表示されます
<img width="1004" alt="5期のユーザー一覧___FBC" src="https://github.com/fjordllc/bootcamp/assets/79003082/affc0063-7620-4f03-becf-0095040cabcc">

## 環境

 - OS: [macOS Sonoma バージョン14.1.1]
 - ブラウザ: [Chrome バージョン119.0.6045.123]

## エラーログ
ログを確認すると、次のようなログがありました。
<img width="1231" alt="fsevent_watch" src="https://github.com/fjordllc/bootcamp/assets/79003082/84f46e22-4f2b-41c6-b70c-4e9ccbb4034c">

おそらく、Discord情報が未登録のユーザーデータがエラーを引き起こしているものと思われます。

```
irb(main):005:0> user = User.find(320383523)
  User Load (0.8ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 320383523], ["LIMIT", 1]]
=>                                                   
#<User:0x000000010c02ea60                            
...                                                  
irb(main):006:0> user.name
=> "Discord 未登録"
irb(main):007:0> user.discord_profile
  DiscordProfile Load (0.7ms)  SELECT "discord_profiles".* FROM "discord_profiles" WHERE "discord_profiles"."user_id" = $1 LIMIT $2  [["user_id", 320383523], ["LIMIT", 1]]
=> nil 
irb(main):008:0> user.discord_profile.account_name
(irb):8:in `<main>': undefined method `account_name' for nil:NilClass (NoMethodError)
```

**Comment by junohm410** [comment]
修正により、ステージング環境でも5期生のユーザー一覧ページが正しく表示されることを確認しました。
本番環境には影響のないIssueのため、これを持ちまして本IssueはCloseといたします。

![image](https://github.com/fjordllc/bootcamp/assets/128765400/bde9b7e3-48b8-4e10-a809-a2286d7b7362)
