### ISSUE TITLE
ブラウザタブタイトルの改善

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#7062]
"Doc (タイトル)"のような表記だと、一瞬"Doc"も記事タイトルの一部であるように見えます。
![Screenshot 2023-11-18 at 9 41 34](https://github.com/fjordllc/bootcamp/assets/1148320/3fa87885-c8bf-46c2-8fee-9afb14e75e91)

"Doc: (タイトル)"のような形にして、記事のタイトルの一部ではないことを強調できるといいのでは？と思ったのですがどうでしょうか？
（Q&Aページ等も同様）
![Screenshot 2023-11-18 at 9 41 04](https://github.com/fjordllc/bootcamp/assets/1148320/4235a3bf-492b-4c0c-9523-7455383e04c5)

あと、Docページに関しては、Docなのか、Docsなのか、表記を統一した方がいいかもしれません。
<img width="550" alt="doc" src="https://github.com/fjordllc/bootcamp/assets/1148320/adcdb88d-0558-4dbc-9823-196a5e0a3b5c">

**Comment by machida** [comment]
📝 
- [ ] Docs （ https://github.com/fjordllc/bootcamp/issues/7084 ）
- [ ] Q&A（ https://github.com/fjordllc/bootcamp/issues/7085 ）
- [ ] 提出物 （ https://github.com/fjordllc/bootcamp/issues/7086 ）
