### ISSUE TITLE
grass.vueをreactに対応させる

### ISSUE THREAD

**Issue by natsuto6** [fjordllc/bootcamp#7070]
下記を参考にしてreactに変える。

- [react導入 \+ 管理画面のコース一覧をreact化 by komagata · Pull Request \#5515 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5515)

**Comment by komagata** [comment]
@natsuto6  こちら、ちょっと大変なのでポイントを２から３に変更しました〜

**Comment by natsuto6** [comment]
本番環境で動作確認頂いたのでcloseします。
