### ISSUE TITLE
コースごとの参考書籍一覧が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7105]
コーズごとに必要な書籍一覧が見たいというお問い合わせが多いので。

- プラクティス一覧：`/courses/1234/practices`
- プラクティス一覧：`/courses/1234/books` ← 新しいページとして作る。

**Comment by machida** [comment]
📝 

- 書籍一覧ページを作る。
- プラクティス一覧、書籍一覧にタブを付ける。

<img width="1785" alt="貼り付けた画像_2023_12_06_11_46" src="https://github.com/fjordllc/bootcamp/assets/168265/7dded070-f928-441b-a6d1-9001e7047e40">

---

書籍一覧は、`/books` のデザインを使う。

そのコースに所属する必須書籍、参考書籍が見れるようにする。
必須書籍だけで絞り込めるようにする。

<img width="952" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/f44af007-fdd4-451c-855e-cd73e0f493a2">

**Comment by 2525nicole** [comment]
## 仕様についてのメモ
### 2023/12/21 チーム開発MTGにて

「プラクティスで絞り込む」の機能は[要件](https://github.com/fjordllc/bootcamp/issues/7105#issuecomment-1842022787)に入っていなかったため、コース一覧（`/courses/1234/books`）には含めないことになりました✏️

![スクリーンショット 2023-12-21 8 36 23](https://github.com/fjordllc/bootcamp/assets/104631303/a1efb75b-45b3-45f9-801d-f218ae35fe0e)

**Comment by 2525nicole** [comment]
本番環境で動作することが確認できたのでcloseいたします🙇‍♀️
