### ISSUE TITLE
提出物 > 自分の担当 にある タブ の順序を逆にする。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7110]
メンターでログインし、
http://localhost:3000/products/self_assigned
にアクセス。

<img width="1108" alt="貼り付けた画像_2023_12_06_11_53" src="https://github.com/fjordllc/bootcamp/assets/168265/028a1704-e055-4509-99bd-b7faac6e871f">

**Comment by naokinaokiboo** [comment]
本番環境での動作確認でOKをいただいたのでclose致します。
