### ISSUE TITLE
自分が担当の未返信の提出物がないときに、全てに戻ることができない。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7111]
メンターでログインし、
http://localhost:3000/products/self_assigned
にアクセス。

<img width="1108" alt="貼り付けた画像_2023_12_06_11_53" src="https://github.com/fjordllc/bootcamp/assets/168265/dd00b1ac-dcb8-4c7b-8d2a-1a57863c4257">

この画面になる。

<img width="931" alt="貼り付けた画像_2023_12_06_11_59" src="https://github.com/fjordllc/bootcamp/assets/168265/c5f78202-e2ce-4060-a772-84c4b76da476">

↓が表示されないので、全てに戻れない。

<img width="176" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/940cf23e-f3ea-4282-80d7-d6defd1bbe0f">

未返信の提出物が0のときも、↑これを表示される。

**Comment by niikz** [comment]
@machida 
「未返信／全て」の表示に関して質問があります！お手すきの際にご確認お願いいたします🙏

1.
「自分の担当の提出物がある && 未返信0」の場合のみ追加する認識であっていますでしょうか？
自分の担当の提出物が0の場合、「未返信／全て」ともに表示しない認識です。

自分の担当の提出物ページ・提出物0（全て）
http://localhost:3000/products/self_assigned
<img width="600" alt="screenshot-2023-12-10-04" src="https://github.com/fjordllc/bootcamp/assets/60736158/b58cf632-cfdc-4ceb-835a-0208f4bbedee">

自分の担当の提出物ページ・提出物0（未返信）
http://localhost:3000/products/self_assigned?target=self_assigned_no_replied
<img width="600" alt="screenshot-2023-12-10-05" src="https://github.com/fjordllc/bootcamp/assets/60736158/2dab36b6-d275-4a62-99bf-7b7b2ae74194">

2.
「未返信／全て」の表示ですが、未完了の提出物ページにも存在します。
http://localhost:3000/products/unchecked
<img width="600" alt="screenshot-2023-12-10-03" src="https://github.com/fjordllc/bootcamp/assets/60736158/43bf1e39-b679-4e08-8400-a8cb8ed44f82">

未完了の提出物ページで、未返信0の場合も同様に修正したほうがよろしいでしょうか？
http://localhost:3000/products/unchecked?target=unchecked_no_replied
<img width="600" alt="screenshot-2023-12-10-01" src="https://github.com/fjordllc/bootcamp/assets/60736158/36fd7036-c120-43d4-9efc-db932c3709fc">

**Comment by niikz** [comment]
### 📝 2023/12/11(月) 質問タイムメモ

https://github.com/fjordllc/bootcamp/issues/7111#issuecomment-1848885129 について machida さんからの回答
- 未完了の提出物ページ・自分の担当の提出物ページにおいて、提出物のある／なしに関わらず常に「未返信／全て」を表示する

**Comment by niikz** [comment]
@komagata @machida
お疲れさまです。お手数ですが、本番環境での動作確認をお願いいたします🙏

**Comment by komagata** [comment]
@niikz 本番環境で動作することを確認しました〜！

**Comment by niikz** [comment]
@komagata
ご確認ありがとうございました！

本番環境で確認いただいたのでcloseします。
