### ISSUE TITLE
提出物の未完了タブの絞り込みの順番を逆にする。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7113]
メンターでログインし、
http://localhost:3000/products/unchecked
にアクセス。

どちらをクリックしても、順番は揃える。

<img width="1124" alt="貼り付けた画像_2023_12_06_12_30" src="https://github.com/fjordllc/bootcamp/assets/168265/4e1e80e7-a5b3-43c2-a1f3-0500390dade4">

**Comment by naokinaokiboo** [comment]
本番環境での動作確認OKをいただいたのでclose致します。
