### ISSUE TITLE
管理画面のユーザー一覧の忘年会タブから休会中のユーザーを外す。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7114]
管理者でログインし、
http://localhost:3000/admin/users?target=year_end_party
にアクセス。

ここで表示されている一覧、メールアドレス一覧に休会中のユーザーを含めないようにする。

**Comment by junohm410** [comment]
@komagata @machida 
お疲れ様です。
本Issueにつきまして、PRで行った改修内容の本番環境での動作確認をお願いいたします。

1. 管理者権限で、「管理ページ」の「ユーザー管理画面」（`/admin/users`）にアクセスする。
1. 「忘年会タブ」をクリックする（＝`/admin/users?target=year_end_party`にアクセスする）。
1. ユーザー一覧上に、うすい灰色の行（休会ユーザー）が含まれていないことを確認する。
1. ページ下部の「全員のメアド」欄に、休会者のメアドが含まれていないことを確認する（同ページの「休会」タブをクリックして出てくる休会ユーザーのメアドをランダムでピックアップいただき、ブラウザの検索機能で確認いただければと思います🙏）

お手数をおかけしますが、ご確認のほど何卒よろしくお願い申し上げます。

**Comment by junohm410** [comment]
2024/1/12にFBCのDiscordのチーム開発チャンネルにて、machidaさんに本番環境での動作を確認いただきましたので🙏、本IssueはCloseとさせていただきます。
