### ISSUE TITLE
ブログの投稿フォームにあるタグ入力の文言を変更。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7141]
メンターか管理者でログインし、
/articles/new
にアクセス。

<img width="708" alt="貼り付けた画像_2023_12_14_17_02" src="https://github.com/fjordllc/bootcamp/assets/168265/13b50ef1-5e54-4047-ac68-cb1438a8a3b3">

この部分を削除。

以下のコードをタグ入力フォームの下に設置。

```slim
.a-form-help
  p
    | 入力してエンターキーを押すとタグになります（スペースは入力できません）。
```

**Comment by nishitatsu-dev** [comment]
本番環境で動作確認できたのでcloseします
