### ISSUE TITLE
通知欄に表示されるフォローユーザーの「日報を書きました！」の日報タイトルを提出時のタイトルにしてほしい

### ISSUE THREAD

**Issue by kitarou888** [fjordllc/bootcamp#7151]
## 機能の説明

通知欄に表示される 「**日報＊＊＊を書きました！**」のタイトルが提出時のものでなくおそらく初回WIP時のものが反映されていそうなので、提出時のタイトルを反映してほしい

![Screenshot_20231216-191740](https://github.com/fjordllc/bootcamp/assets/85793702/f3546ecf-54a7-49c6-bde1-ac045f356a1d)

## 何故この機能が必要なのか

- タイトルを見て読みに行くかを判断することが多いため、正確な情報を表示してほしい。
- 私が日報を書く場合、頻繁にWIP保存しながらこつこつ書き進めていくことが多く、日の最初の方にはまだタイトルが決まっていないことが多いため。

**Comment by komagata** [comment]
@kitarou888 Issue作成ありがとうございます！
@kitarou888 さんがシステム開発のプラクティスに来たときにお願いするのにちょうどいいIssueになるかもですね！

**Comment by kitarou888** [comment]
> @kitarou888 Issue作成ありがとうございます！ @kitarou888 さんがシステム開発のプラクティスに来たときにお願いするのにちょうどいいIssueになるかもですね！

採用ありがとうございます🙏
はい、ぜひ僕のほうでやらせていただけたらうれしいです〜！
