### ISSUE TITLE
ブログ一覧の上部にもページャーを出したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7157]
<img width="1299" alt="貼り付けた画像_2023_12_20_15_23" src="https://github.com/fjordllc/bootcamp/assets/168265/fc28d722-4e1f-4a17-9d13-ddda8ddf3ab4">

ここにも、

<img width="471" alt="貼り付けた画像_2023_12_20_15_24" src="https://github.com/fjordllc/bootcamp/assets/168265/16c4a36f-f983-46ba-9735-a022b2e6c5ca">

これを表示したい。

**Comment by masyuko0222** [comment]
本番環境で確認が取れたのでCloseします。
