### ISSUE TITLE
testのrubocopの指摘点を修正する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7160]
現状無効化してるrubocop-minitestのルールを有効化して指摘点を修正する。

## やり方

現状は下記で複数のルールを無効化している。

https://github.com/fjordllc/bootcamp/blob/dcc042ccfb6b3eb10a6d9cc0be9b0260fc6653e1/.rubocop.yml#L31-L41

こちらを削除して

```
$ rubocop
````

すると指摘されるのでそちらを修正する。

関連: #7158

**Comment by naokinaokiboo** [comment]
リリースされたためクローズ致します。

**Comment by naokinaokiboo** [comment]
リリースされましたので、クローズ致します。
