### ISSUE TITLE
特別イベント一覧、定期イベント一覧に、直近のイベント一覧を表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7162]
現在、ダッシュボードに、

 このような近日開催のイベント一覧が表示されている。
<img width="568" alt="貼り付けた画像_2024_01_14_21_44" src="https://github.com/fjordllc/bootcamp/assets/168265/0a916ed6-a811-4f05-98e2-38c575063cfe">

これを、

<img width="1605" alt="貼り付けた画像_2024_01_14_21_45" src="https://github.com/fjordllc/bootcamp/assets/168265/88995e9e-ba84-480c-9be6-7475ddfd3b99">

特別イベント一覧、定期イベント一覧の右カラムにも表示したい。
デザインはダッシュボードのとは別の形で表示したい。

**Comment by masyuko0222** [comment]
@machida @komagata 
お疲れ様です！
こちらのイシューのポイントについて、開発中に3ptが妥当だと思い始めたのですが、いかがでしょうか…！

理由としては、
- 参考にする`home#index`上の「近日開催イベント一覧」は、一般的なMVCで表示している
  - ViewはSlim 
- 一方、今回実装先のページ、`events#index`はReactを利用している
  - そのため、「近日開催イベント一覧」もReactでコンポーネントとして用意する必要がある
  - current_userの値が必要となり、バケツリレーを避けるためuseContextの利用も考慮しなければならない

などと、自分的には3か5ポイントくらいの印象なのですが、いかがでしょうか…！
ご検討いただけますと幸いです🙇‍♀️

**Comment by machida** [comment]
@masyuko0222 
近日開催のイベントの部分はReactでの実装はしなくて大丈夫です。home#indexと同じようにReactを使わず書いてくださいー。

**Comment by masyuko0222** [comment]
@machida 
ありがとうございますー。
方針については初めに聞くべきでした😅‪‪

**Comment by masyuko0222** [comment]
新しいコンポーネントには、`.card-list-item`クラスを付与します。

そのため、今回の実装には直接関係はないですが、既存の「regular_eventsページで、`.card-list-item`の数をカウントする」テストを一部変更します。

具体的には下記のコードが対象です。
https://github.com/fjordllc/bootcamp/blob/0f732f3efeaa6c1c78f75a0ddb97f54190f39147/test/system/regular_events_test.rb#L174C1-L185C1

```ruby
# 変更前

  test 'show listing not finished regular events' do
    visit_with_auth regular_events_path(target: 'not_finished'), 'kimura'
    assert_selector '.card-list-item', count: 14
  end


  test 'show listing all regular events' do
    visit_with_auth regular_events_path, 'kimura'
    assert_selector '.card-list-item', count: 25
    visit regular_events_path(page: 2)
    assert_selector '.card-list-item', count: 8
  end
```

対象のコードは、親要素から確認をするように変更します。
```ruby
# 変更後
  test 'show listing not finished regular events' do
    visit_with_auth regular_events_path(target: 'not_finished'), 'kimura'
    within '[data-react-class="RegularEvents"]' do
      assert_selector '.card-list-item', count: 14
    end
  end

  test 'show listing all regular events' do
    visit_with_auth regular_events_path, 'kimura'
    within '[data-react-class="RegularEvents"]' do
      assert_selector '.card-list-item', count: 25
    end
    visit regular_events_path(page: 2)
    within '[data-react-class="RegularEvents"]' do
      assert_selector '.card-list-item', count: 8
    end
  end
```

**Comment by masyuko0222** [comment]
実装方針は、類似の機能を参考にしています。
具体的には下記のPRです。
https://github.com/fjordllc/bootcamp/pull/6454

**Comment by masyuko0222** [comment]
近日開催イベント関連は、全て`UpcominEventsGroup`クラスを利用することになりました。

**Comment by masyuko0222** [comment]
@komagata 
本番環境で確認が取れたのでCloseします～！
