### ISSUE TITLE
通知ベルをクリックして表示される通知一覧に、未読・既読のタブを付けたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7163]
https://github.com/fjordllc/bootcamp/issues/5130
notifications_bell.vue, pager.vueをreactに対応させるのと同時に仕様の変更をする。

## 現在の仕様

現在はヘッダにあるベルをクリックすると、

<img width="266" alt="貼り付けた画像_2023_12_21_10_42" src="https://github.com/fjordllc/bootcamp/assets/168265/945cf4e1-72f5-447d-9deb-c8121f61dedf">

このように未読の通知一覧がドロップダウンで表示される。
ベルの部分には未読の通知数が表示されている。

---

未読がない場合は、ベルの部分には未読の通知数は0ではなく、何も表示されない。
これをクリックすると、ドロップダウンは表示されず、`/notifications` に遷移する。

<img width="167" alt="貼り付けた画像_2023_12_21_10_43" src="https://github.com/fjordllc/bootcamp/assets/168265/d11a102c-fd95-4928-8ab8-9684bc1d4aab">

## 変更

下の図のように、ベルをクリックして表示されるドロップダウンの上部に、未読・全てのタブを付ける。

<img width="325" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/f6c7ca19-728c-4e0a-b291-e4b2b40713eb">

全てを選択した場合、直近10件の通知を表示させる。

---

全てのタブを選択した場合、最新の10件しか見れないので、もっと見るを設置し、`/notifications`へリンクを貼る。

<img width="336" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/df93fa18-0e86-450e-a54b-f4e6380b4665">

---

現在、未読がない場合はドロップダウンは表示されずに`/notifications` に遷移するが、変更後は遷移はせずに、未読がないことをドロップダウン内で知らせる。その下に、お知らせ一覧へのリンクを置き、そのリンクをクリックすると`/notifications`へ遷移する。

<img width="329" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/700bbbc0-a209-420a-b7b2-f9f59236fa6d">

---

現在は以下のリンクが用意されているが、

<img width="254" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/7e50ec2a-c0c4-47b0-adb7-9fbf0ef58de6">

そのうちの以下の2つは、未読タブを選択したときにだけ表示させる。

<img width="309" alt="貼り付けた画像_2023_12_21_11_05" src="https://github.com/fjordllc/bootcamp/assets/168265/ed7cb03f-e1bd-4311-84a4-87b40c382d1a">

以下の2つはなくし、

<img width="254" alt="貼り付けた画像_2023_12_21_11_05" src="https://github.com/fjordllc/bootcamp/assets/168265/0d0c8faa-f0cc-4070-9e3e-65c86621cc3f">

代わりに、以下のようにリストの上部にリンクを置く。

<img width="328" alt="貼り付けた画像_2023_12_21_11_21" src="https://github.com/fjordllc/bootcamp/assets/168265/4ed9bd78-f8ea-4bf3-903d-c99408eaa9e7">

<img width="335" alt="貼り付けた画像_2023_12_21_11_24" src="https://github.com/fjordllc/bootcamp/assets/168265/3d46bd79-bac9-440e-8d96-d30f7d37907a">

**Comment by machida** [comment]
ドロップダウンの表示、非表示をHTMLのinputを応用して実装しているが、これをJSでの実装に変えたい。この点はmachidaと話し合いながら行う。

**Comment by junohm410** [comment]
@komagata @machida 

※2024/1/17の質問タイムにて、本Issueについてご相談させていただいたことの記録です。

本Issueは、もともと「notifications_bell.vue, pager.vueをreactに対応させる」というReact化のIssueと紐づいておりました。
（上の方でmachidaさんがメンションなさっているものです。）

これに関連し、質問タイムにて下記のことを確認させていただきました。
- `pager.vue`はこのコメントを書いている時点ですでにReact化されているため、上のIssueは閉じる。
- `notifications_bell.vue`は、本Issueの中でReact化を行い、その上で「未読・既読タブ」機能を実現する。

こちらのベースに、作業を進めさせていただきます。
より細かな点は、今後また作業の途中でmachidaさんに相談させていただければと存じます。

どうぞよろしくお願いいたします🙏

**Comment by junohm410** [comment]
@machida 
お疲れ様です。本Issueにて確認させていただきたいことがあります。

下のイメージですが、全てタブにおける「すべての通知一覧へ」と「もっと見る」はどちらも`/notifications`へのリンクなので、どちらかは不要かなと考えています。
「未読タブには上部に未読一覧へのリンクがあること」との統一を考えると、上部の「すべての通知一覧へ」だけの設置でいいかなと個人t根際には思いますが、いかがでしょうか？

![image](https://github.com/fjordllc/bootcamp/assets/128765400/e43c5208-af3a-40c5-aa04-1db64e1672e3)

また別件ですが、

> ドロップダウンの表示、非表示をHTMLのinputを応用して実装しているが、これをJSでの実装に変えたい。この点はmachidaと話し合いながら行う。

こちらはReact化に従い、ベルボタンの開閉状態を`useState`で状態管理し、それに合わせてドロップダウンのDOMのレンダリングを操作するように実装します。
一旦実装を進めてpushし、動きを確認していただいて、問題なさそうであればそこでデザインの調整をお願いできればと思っています。

お手隙の際にご確認いただけますと幸いです。よろしくお願いします🙏

**Comment by machida** [comment]
@junohm410 リンクの件、提案の通りに行きたいと思いますー
動きの件も了解です。動きが見れる状態になりましたら連絡お願いします🙏

**Comment by junohm410** [comment]
本番環境にて、本Issueで追加した未読・全てタブの動作確認ができましたので、本Issueはクローズいたします。
