### ISSUE TITLE
未チェックの日報はありませんのアイコンが上にくっつきすぎている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7167]
![スクリーンショット 2023-12-27 16 06 49](https://github.com/fjordllc/bootcamp/assets/16577/80a55c7b-c18b-40aa-b8df-5c3533fa0183)

**Comment by nakamu-kazu222** [comment]
@komagata @machida

お疲れ様です

本番環境の管理者/メンターの権限がないため、以下の動作確認をしていただきたいです
- 未チェックの日報がない時のアイコンが、上の枠線から離れている
<img width="614" alt="スクリーンショット 2024-04-15 10 12 55" src="https://github.com/fjordllc/bootcamp/assets/126838748/8a9bcbbb-ab05-49c7-8531-1bff58760c04">


お手隙の際に、ご確認のほどよろしくお願いいたします

**Comment by komagata** [comment]
@nakamu-kazu222 本番環境で正しく動作することを確認しました～🎉

**Comment by nakamu-kazu222** [comment]
@komagata 

ご対応いただきありがとうございます！
動作確認が完了したので、本Issueはcloseします
