### ISSUE TITLE
企業研修の申し込みフォームがほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7171]
現在はお問い合わせフォームから研修申し込みをしてもらってますが、研修申し込み用のフォームの作成し、研修申し込みはそこから申し込むようにフローを変えたい。

フォームの項目は、

- 企業名
- 担当者名
- メールアドレス
- 研修打ち合わせ希望日時（日時を3つ登録できるようにする）
    - 1
    - 2
    - 3
- 研修を受ける方の人数
- 研修期間
- どこでフィヨルドブートキャンプを知りましたか？
- その他伝えておきたいこと

こんな感じで考えています。

info@lokka.jp に届くようにお願いします。

**Comment by omochiumaiumai** [comment]
リリース及びに本番確認が完了したため、Issueをcloseします。
