### ISSUE TITLE
ユーザー個別にも数字一覧を表示し、リンクにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7181]
ユーザー一覧にあるこれを

<img width="441" alt="貼り付けた画像_2024_01_10_20_56" src="https://github.com/fjordllc/bootcamp/assets/168265/a2458125-946e-41a6-aa83-9570ee0283a4">

ユーザー個別にも載せたい。

<img width="675" alt="貼り付けた画像_2024_01_10_20_57" src="https://github.com/fjordllc/bootcamp/assets/168265/ab6655ef-fc33-4b98-bb39-dfa24c4e0d3b">

これらは削除する。

<img width="597" alt="貼り付けた画像_2024_01_10_20_58" src="https://github.com/fjordllc/bootcamp/assets/168265/2185a9c1-34a5-49d8-b013-a6b27ad77e93">

さらに、数字をリンクにしたい。

<img width="441" alt="貼り付けた画像_2024_01_10_21_01" src="https://github.com/fjordllc/bootcamp/assets/168265/24c7a4de-e45a-4405-a999-902c00639230">

**Comment by nishitatsu-dev** [comment]
本番環境で動作確認できたのでcloseします。
