### ISSUE TITLE
ユーザー一覧にある数字一覧をリンクにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7182]
ユーザー一覧にある数字それぞれをリンクにしたい。

<img width="441" alt="貼り付けた画像_2024_01_10_21_01" src="https://github.com/fjordllc/bootcamp/assets/168265/bc20bc00-65f3-41b6-a09c-dd4075e9586a">

0 のときはリンクにしない。

**Comment by komagata** [comment]
@naokinaokiboo CloseされていないようなのでCloseお願いします〜

**Comment by naokinaokiboo** [comment]
@komagata 
失礼しました。😅Closeするコメントだけ残してClose押せていませんでした。💦
今、Closeしておきました〜
