### ISSUE TITLE
初日報投稿通知のメールが2通届いてしまう

### ISSUE THREAD

**Issue by 2525nicole** [fjordllc/bootcamp#7193]
## 概要
- はじめて日報が投稿された際の管理者/メンター宛のメール通知が2通届いてしまっている

## 再現手順

1. `muryou`（その他日報投稿が0件のユーザーでも可）でログインする
2. [日報作成](http://localhost:3000/reports/new)画面からはじめての日報を投稿する
3. `http://localhost:3000/letter_opener`にアクセスし、`komagata`（その他管理者またはメンターでも可）に「[FBC] muryouさんがはじめての日報を書きました！」というメール通知が2通届く

## 期待される振る舞い

- 初日報投稿時のメール通知が1通になる

## スクリーンショット

例：`muryou`がはじめての日報を投稿すると`komagata`さん宛にメール通知が2通飛んでいる

<img width="1132" alt="スクリーンショット 2024-01-12 22 44 00" src="https://github.com/fjordllc/bootcamp/assets/104631303/a8d2307e-133c-4dbf-b71d-9590cbf58b04">

## 環境

 - OS: [macOS Monterey 12.7.1]
 - ブラウザ: [chrome,]

## 関連Issue

Ref: #6204 
Ref: #5890

**Comment by machida** [comment]
@2525nicole 
Issueありがとうございます！
アサインしましたー

**Comment by 2525nicole** [comment]
## 【メモ】メールが2通届く原因

以下、2箇所で通知処理が行われているのが原因と考えられる

- [app/models/report_notifier.rbのReportNotifier#notify_first_report](https://github.com/fjordllc/bootcamp/blob/715f2be86bd00ce4729db9c34daa176e06359ac2/app/models/report_notifier.rb#L34-L38)

```ruby
class ReportNotifier
  def call(report)
    Cache.delete_unchecked_report_count

    return unless report.first_public?  # 日報が初公開でない場合は処理を中断する

    report.update_column(:published_at, report.updated_at) # rubocop:disable Rails/SkipsModelValidations

    notify_users(report) # この中でnotify_first_reportが呼ばれる
    notify_to_chat(report)
  end

  private

  def notify_users(report)
    notify_first_report(report) if report.first? # 初日報の時呼ばれる
    notify_advisers(report) if report.user.trainee? && report.user.company_id?
    notify_consecutive_sad_report(report) if report.user.depressed?
    notify_followers(report)
    report.notify_all_mention_user
  end

 def notify_first_report(report) 
   User.admins_and_mentors.each do |receiver| 
     ActivityDelivery.with(report: report, receiver: receiver).notify(:first_report) if report.sender != receiver # 投稿者以外の管理者とメンターにサイト内とメールで通知が飛ぶ
   end 
 end 
# 以下、省略
```

- [app/models/first_report_notifier.rb](https://github.com/fjordllc/bootcamp/blob/715f2be86bd00ce4729db9c34daa176e06359ac2/app/models/first_report_notifier.rb)

```ruby
# frozen_string_literal: true

class FirstReportNotifier
  def call(report)
    return if report.wip || !report.first? || Notification.find_by(kind: :first_report, sender_id: report.user.id).present?
# WIPの時、初日報でない時、投稿者の日報通知が既に存在する場合は処理を中断する

    User.admins_and_mentors.each do |receiver|
      ActivityDelivery.with(report: report, receiver: receiver).notify(:first_report) if report.sender != receiver  # 投稿者以外の管理者とメンターにサイト内とメールで通知が飛ぶ
    end
  end
end
```

※`ActivityDelivery`によってアプリ内通知は通知元のリンク（通知を発生させたオブジェクトのリンク）ごとに1件のみが表示される仕様のため、メールのみ2通届いてしまっている

**Comment by 2525nicole** [comment]
@komagata @machida 
こちらのIssueの対応方針を検討しており、一点ご相談があります！
お手数ですがご確認をお願いいたします🙏

## ご相談内容
2箇所で初日報投稿時の通知処理が記載されているのが本Issueの要因と考えられます。
（ご参考：本Issue内[メモ](https://github.com/fjordllc/bootcamp/issues/7193#issuecomment-1890263896)）
重複した処理の記述を削除することでバグが解消できると考えますが、どちらを残すかという点をご相談したいです。

**【こちらで考えた案】**
通知処理はすべて[`ReportNotifier.rb`](https://github.com/fjordllc/bootcamp/blob/715f2be86bd00ce4729db9c34daa176e06359ac2/app/models/report_notifier.rb)にまとめる（=[`FirstReportNotifier`](https://github.com/fjordllc/bootcamp/blob/715f2be86bd00ce4729db9c34daa176e06359ac2/app/models/first_report_notifier.rb)を削除する）方向で違和感はないかと思っているのですが、いかがでしょうか。

※一方で、以下に記載のとおり[`ReportCallbacks`](https://github.com/fjordllc/bootcamp/blob/26e633263ad6f6410218160686a0580d597f7df3/app/models/report_callbacks.rb)に日報の通知処置がまとまっていた状態で「初日報投稿通知をnewspaperに置き換える」というIssueを作成いただいているので、
「初日報投稿の通知はその他日報関連の通知から切り出すのが好ましい」というご判断によるものであった場合は
[`FirstReportNotifier`](https://github.com/fjordllc/bootcamp/blob/715f2be86bd00ce4729db9c34daa176e06359ac2/app/models/first_report_notifier.rb)を残す方向で進めようと思います。

お手数をおかけしますがご確認の程よろしくお願いいたします🙏

### 2箇所での初日報投稿時の通知処理が作成された経緯の調査結果
現在のように同じ処理が2箇所で行われている要因として、調査した結果以下のような経緯があるとお見受けしました。

- 当初「初日報投稿時の通知」も含め、日報の通知処理は[`ReportCallbacks`](https://github.com/fjordllc/bootcamp/blob/26e633263ad6f6410218160686a0580d597f7df3/app/models/report_callbacks.rb)にまとめて記載されていた

- 2023/2/11に作成された以下Issueとその[PR](https://github.com/fjordllc/bootcamp/pull/6345)によって、
初日報投稿時の通知処理（Discord以外）が[`FirstReportNotifier`](https://github.com/fjordllc/bootcamp/blob/715f2be86bd00ce4729db9c34daa176e06359ac2/app/models/first_report_notifier.rb)に切り出された
[\[newspaper\] 最初の日報作成通知をnewspaperに置き換えたい · Issue \#6204 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/6204)

- その後、以下のIssueの[PR](https://github.com/fjordllc/bootcamp/pull/6336)において、2023/5に初日報投稿時の通知処理を含む日報通知の処理を記載した[`RreportNotifier`](https://github.com/fjordllc/bootcamp/blob/715f2be86bd00ce4729db9c34daa176e06359ac2/app/models/report_notifier.rb)が作成されている

[涙マーク連続通知をactive\_delivery化したい · Issue \#5890 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/5890)

**Comment by machida** [comment]
@2525nicole こちらの件、駒形さんから回答してもらおうと思いますー

**Comment by komagata** [comment]
@2525nicole FirstReportNotifierを残す方法でお願いします〜。
（まとまってしまっていた処理を別々のクラスに分ける作業を続けているところだったので）

不具合を見つけてくださってありがとうございます〜！

**Comment by 2525nicole** [comment]
@machida 
早々にご確認いただきありがとうございました🙇‍♀️！

@komagata 
早速のご回答ありがとうございます🙇‍♀️！
承知いたしました！方針についても共有いただきありがとうございます🙏

たびたび恐れ入りますが、もう一点確認させてください🙏

[ReportNotifier.rb](https://github.com/fjordllc/bootcamp/blob/715f2be86bd00ce4729db9c34daa176e06359ac2/app/models/report_notifier.rb)の中に初日報投稿時のDiscrod通知処理が残っていたので
今回の対応でこの処理も[FirstReportNotifier](https://github.com/fjordllc/bootcamp/blob/715f2be86bd00ce4729db9c34daa176e06359ac2/app/models/first_report_notifier.rb)に移動させようかと考えておりますが問題ないでしょうか🙏

↓該当のコード
https://github.com/fjordllc/bootcamp/blob/715f2be86bd00ce4729db9c34daa176e06359ac2/app/models/report_notifier.rb#L25-L32

本Issueは「初日報投稿時のメールが2通届いてしまう」バグについてのものですが、
解決策として「初日報投稿時の**通知処理を適切な1箇所で行うように修正する**」という対応を行うので、
今回のPRで対応しても違和感がない気がしたのでご相談です🙇‍♀️

別Issueで対応するほうが好ましい等あればご教示いただけますと幸いです！

**Comment by komagata** [comment]
@2525nicole 

> [ReportNotifier.rb](https://github.com/fjordllc/bootcamp/blob/715f2be86bd00ce4729db9c34daa176e06359ac2/app/models/report_notifier.rb)の中に初日報投稿時のDiscrod通知処理が残っていたので
今回の対応でこの処理も[FirstReportNotifier](https://github.com/fjordllc/bootcamp/blob/715f2be86bd00ce4729db9c34daa176e06359ac2/app/models/first_report_notifier.rb)に移動させようかと考えておりますが問題ないでしょうか🙏

問題ないです〜。

**Comment by 2525nicole** [comment]
@komagata 
ご確認ありがとうございます😊！
承知いたしました！Discrod通知処理の移動も含めて進めてまいります🙌
引き続きよろしくお願いいたします🙇‍♀️

**Comment by 2525nicole** [comment]
@komagata @machida
## 【ご連絡】本番環境での動作確認について
こちらの動作確認ですが、管理者/メンターのみが確認できる内容ですので協力をいただけますと幸いです🙇‍♀️

尚、初めての日報投稿時の通知については #6617 **でご依頼している動作確認に含まれるため、
二度手間をおかけしないよう #6617 で確認いただきましたらこのIssueもclose**できればと考えております🙏

👇 [#6617のご連絡で記載している箇所](https://github.com/fjordllc/bootcamp/issues/6617#:~:text=%E5%88%9D%E3%82%81%E3%81%A6%E3%81%AE%E6%97%A5%E5%A0%B1%E3%81%8C%E6%8A%95%E7%A8%BF%E3%81%95%E3%82%8C%E3%82%8B%E3%81%A8%E7%AE%A1%E7%90%86%E8%80%85/%E3%83%A1%E3%83%B3%E3%82%BF%E3%83%BC%E3%81%AB%E3%83%A1%E3%83%BC%E3%83%AB/%E3%82%B5%E3%82%A4%E3%83%88%E5%86%85%E9%80%9A%E7%9F%A5%E3%81%8C%E5%B1%8A%E3%81%8F)
>初めての日報が投稿されると管理者/メンターにメール/サイト内通知が届く
メールは1通のみ届くこと（二度お手間をかけることのないよう、ここで https://github.com/fjordllc/bootcamp/issues/7193 の確認も兼ねられればと思います）


ご認識の程よろしくお願いいたします🙇‍♀️

**Comment by komagata** [comment]
@2525nicole 「初めての日報の通知」が１通だけ届いていることを確認しました〜！

**Comment by 2525nicole** [comment]
@komagata 
お忙しいところご確認いただきありがとうございます🙇‍♀️！

-----
ご協力いただき本番環境での動作確認が完了したので、closeいたします🙌
