### ISSUE TITLE
ブログのプレビューページを用意したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7199]
現在、ブログ記事の下書きとして保存されている未公開のものは、メンターか管理者でログインをしないと見れない。

インタビュー記事で先方の企業の担当者に確認をもらう場合、ログインしないと見れないのは面倒。ログインしなくても見れるようにしたい。

下書きの記事では、予測の付かない複雑なプレビューページURLが生成されていて、そのURLにアクセスすると、ログインをしなくてもその記事にアクセスできるようにする。

- プレビューページには、Googleなどの検索サイトでインデックスできないようにする。head に nofollow の meta タグを追加。
- プレビューページは記事が公開されたらアクセスできないようにしたい。

まだふわっとしてるので、どんどん仕様について質問してくださいー

**Comment by goruchanchan** [comment]
@machida お疲れ様です🙇‍♂️お手数おかけしますが、下記ご回答お願いしたいです🙇‍♂️

- > 下書きの記事では、予測の付かない複雑なプレビューページURLが生成

  下書き記事は２つある認識で良いでしょうか？

  - 既存下書き記事（`/articles/:id`）
  - 公開下書き記事（`/wip_articles/:random_id`）

  公開下書き記事のモデルは、`article` と関連付け、別モデルとしてランダム URL を管理するということでしょうか？
  別モデルで管理する属性は、 id, 関連articleID, ランダムURL みたいな管理とするということでしょうか？
[参考：Rails等でURLにランダムな文字列を使いたい時のアレ](https://qiita.com/ainame/items/eb9dcf7862630c44d5e9)

-  > ログインをしなくてもその記事にアクセスできる

   公開下書き記事用のURLは既存下書き記事内に表示する認識で良いでしょうか？

   [![Image from Gyazo](https://i.gyazo.com/a54d638d4b9c98f0d1ce712417d2cbd2.png)](https://gyazo.com/a54d638d4b9c98f0d1ce712417d2cbd2)

-  > プレビューページには、Googleなどの検索サイトでインデックスできないようにする。head に nofollow の meta タグを追加

   `noindex`, `nofollow` の両方を head に定義するという理解で良いでしょうか？

   ```html
   <meta name="robots" content="noindex,nofollow" />
   ```

**Comment by komagata** [comment]
@goruchanchan 

> 下書き記事は２つある認識で良いでしょうか？

NOです。

こういう感じはいかがでしょうか。

- /articles/:id : 公開記事URL
- /articles/:id?token=xxxxxxxxxxxx : WIP記事プレビューURL
- /articles/wip : WIP記事一覧

tokenは記事ごとにカラムを用意してランダムな値を生成しておくといいと思います。

[DHHはどのようにRailsのコントローラを書くのか \| POSTD](https://postd.cc/how-dhh-organizes-his-rails-controllers/)

> 公開下書き記事のモデルは、article と関連付け、別モデルとしてランダム URL を管理するということでしょうか？

NOです。

> 別モデルで管理する属性は、 id, 関連articleID, ランダムURL みたいな管理とするということでしょうか？

NOです。

> noindex, nofollow の両方を head に定義するという理解で良いでしょうか？

YESです。

僕はこんな感じがいいかなと考えてみたんですが @machida さんはいかがでしょうか？

**Comment by machida** [comment]
@komagata @goruchanchan それでお願いしたいですー🙆‍♂️

**Comment by goruchanchan** [comment]
`/articles/wip` へのリンクは `/articles` ページ内に配置しておく。デザインは machida  さんに実施いただく

**Comment by goruchanchan** [comment]
`/articles/:id?token=xxxxxxxxxxxx` の部分はアドレスバーの表示だけでよい

**Comment by goruchanchan** [comment]
@machida さんに本番環境での確認していただいたのでクローズします🙇‍♂️
