### ISSUE TITLE
登録ページに研修申し込みに誘導する文言とリンクを追加する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7206]
![スクリーンショット 2024-01-16 18 39 10](https://github.com/fjordllc/bootcamp/assets/16577/2e2e86a2-e45b-4c62-8314-20a96630c88a)

お問い合わせページURL：
https://bootcamp.fjord.jp/inquiry/new

現在研修申し込み専用のお問い合わせを作成中なので、それができたらそちらへのリンクに変更する。
（そちらが先に完了しちゃう場合もあるのでその辺りは確かめる）

**Comment by SuzukaHori** [comment]
本番環境で動作を確認できましたのでCloseします。

**Comment by SuzukaHori** [comment]
本番環境で動作を確認できましたのでCloseします。
