### ISSUE TITLE
書籍一覧の不要なボーダーを削除したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7227]
プラクティスの書籍一覧ページ。

<img width="554" alt="貼り付けた画像_2024_01_24_15_46" src="https://github.com/fjordllc/bootcamp/assets/168265/cd69d1af-a55e-4162-baeb-d346e11bf04b">

ここに不要なボーダーがある。

<img width="399" alt="貼り付けた画像_2024_01_24_15_47" src="https://github.com/fjordllc/bootcamp/assets/168265/f5466720-d141-4c61-9071-ddc891e5f555">

**Comment by SuzukaHori** [comment]
本番環境で動作確認できましたのでcloseします。

**Comment by SuzukaHori** [comment]
本番環境で動作確認できましたのでcloseします。
