### ISSUE TITLE
学習に使うマシン・OS を選択してください に文言追加

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7228]
/current_user/edit にアクセス。

<img width="598" alt="貼り付けた画像_2024_01_24_18_05" src="https://github.com/fjordllc/bootcamp/assets/168265/b41d7167-9a24-412a-a2d8-9c0dcc975c76">

この青線の部分に、

```
この情報は他のフィヨルドブートキャンプ参加者に公開されます。学習に使うマシン・OS が変わりましたら、この情報を更新してください。
```

という文章の追加をお願いします。

**Comment by reckyy** [comment]
動作確認できたのでclose。
