### ISSUE TITLE
学習に使うマシン・OS を非公開情報から公開情報へ移動したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7233]
<img width="649" alt="貼り付けた画像_2024_01_24_22_32" src="https://github.com/fjordllc/bootcamp/assets/168265/7a24629f-b748-404b-8faf-36568895f1b0">

**Comment by kyokucho1989** [comment]
@komagata 
お疲れ様です。こちら、プルリクまで作成しましたがCIが通りません。
[(slim-lint)](https://app.circleci.com/pipelines/github/fjordllc/bootcamp/8114/workflows/7326c5f8-4eec-4be5-a4ee-0fdf2b1d38d3/jobs/27790/parallel-runs/0/steps/0-108)
変更を加えていないファイルの箇所で `slim-lint`　の指摘が入ります。

これは issue #7255　が解決されてから、それを取り込み、再度プルリクを作成すれば良いでしょうか。

**Comment by komagata** [comment]
@kyokucho1989 基本的にはそのようにお願いします。

> それを取り込み、再度プルリクを作成すれば良いでしょうか。

プルリクはすでに作成されているので、再度作成はせずに、#7255 を取り込んでいただければと思います。

**Comment by kyokucho1989** [comment]
了解しました！
