### ISSUE TITLE
退会処理完了メールにあるメアドをlokkaに更新したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7234]
`/app/views/user_mailer/retire.text.erb`

<img width="633" alt="貼り付けた画像_2024_01_24_22_36" src="https://github.com/fjordllc/bootcamp/assets/168265/a6b62433-66c0-44e9-ac4f-d80233a9c520">

`info@lokka.jp` に変更する。

**Comment by kurumadaisuke** [comment]
@komagata 
こちら退会処理を本番環境でどのように確認すればいいでしょうか？

**Comment by komagata** [comment]
@kurumadaisuke 退会処理が本番であったら僕が確認しますのでこちらに連絡します〜

**Comment by kurumadaisuke** [comment]
@komagata 
よろしくお願いしますー

**Comment by komagata** [comment]
@kurumadaisuke info@lokka.jpにメールが来ることを確認しました〜。

**Comment by kurumadaisuke** [comment]
@komagata 
ご確認ありがとうございます！
本件クローズさせていただきます！
