### ISSUE TITLE
クレジットカードに関して問題があった場合の連絡先をlokkaにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7235]
`app/views/application/_card_notice.html.slim`

<img width="609" alt="貼り付けた画像_2024_01_24_22_37" src="https://github.com/fjordllc/bootcamp/assets/168265/d5d77da0-d767-4e69-9a56-b3606e324e86">

`info@lokka.jp` に変更する。

**Comment by kurumadaisuke** [comment]
本番環境でinfo@lokka.jp に変更されていることを確認いたしました。
本issueCloseさせていただきます。
