### ISSUE TITLE
自動退会のメールのメアドをlokkaに更新したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7236]
`/app/views/user_mailer/auto_retire.text.erb` 

<img width="618" alt="貼り付けた画像_2024_01_24_22_41" src="https://github.com/fjordllc/bootcamp/assets/168265/69847422-3356-49b3-a7eb-2d32d4afadbd">

`info@lokka.jp` に更新したい。

**Comment by reckyy** [comment]
@komagata @machida 
お疲れ様です。開発環境での確認について、行き詰まってしまったので、ご連絡させていただきました。

- 以下の確認方法が正しくて、何か不具合が生じている
- 自分の方法が間違っている

のいずれか自分で判断がつかなかったので、ご教示いただきたいです。
ご確認いただけますと幸いです 🙇 

## 困っていること
開発環境での確認（実際に退会時のメールで fjordからlokkaに変わっているかどうかをletter_opener_webで確認）ができない。
（この質問後も自分で考えてみますが、早めにHelpの意思を表明しておく方がいいと思ったので、質問させていただきました。）


## 試したこと
https://github.com/fjordllc/bootcamp/pull/7173
や
https://github.com/fjordllc/bootcamp/pull/6490
を参考にし、以下の方法で行いました。
ですが、5の段階で、まだnagai-kyuukaiが休会中になっています。

### 行なった確認手順
1. `bin/rails db:seed`
2. komagataでログイン
管理ページの休会ユーザー一覧ページ（/admin/users?target=hibernatedに遷移し、そこにnagai-kyuukai（Nagai Kyu kai）ユーザーとkyuukai（Kyu Kai）ユーザーがいるのを確認。また、nagai-kyuukai（Nagai Kyu kai）ユーザーの詳細ページで、休会日が6ヵ月以上前であることを確認する。

<img width="747" alt="スクリーンショット 2024-01-26 12 30 12" src="https://github.com/fjordllc/bootcamp/assets/106903482/4e8821b2-cc96-4d16-b042-bf3760e3112d">


<img width="747" alt="スクリーンショット 2024-01-26 12 30 20" src="https://github.com/fjordllc/bootcamp/assets/106903482/50b5e074-178c-434c-8bbc-d9d90e9d4a21">

3. Railsコンソールを操作し、kyuukai（Kyu Kai)ユーザーを削除しておく
※このユーザーにはダミーのサブスクリプション番号が登録されており、このユーザーを退会させようとすると定期支払い削除処理でエラーになるため
```
> user = User.find_by(login_name: 'kyuukai')
> user.destroy!
```

4. ブラウザでhttp://localhost:3000/scheduler/daily/auto_retireにアクセス（画面は表示されないが、処理が走る）

5. 管理ページをリロードし、先ほどのユーザーが休会ユーザー一覧に表示されておらず、退会ユーザー一覧に表示されることを確認
、、したいのだが、まだ休会中のユーザー。
<img width="747" alt="スクリーンショット 2024-01-26 12 34 59" src="https://github.com/fjordllc/bootcamp/assets/106903482/6243a8cf-2725-4ca2-8843-ea88aae0d1d1">

## 推測
参考にした2つのPRではスケジューラーを起動するために、アクセスするURLが異なっていました。
- `http://localhost:3000/scheduler/daily/auto_retire`
- `http://localhost:3000/scheduler/daily/auto_retire?token=hoge`

ただどちらにアクセスしても、自動退会のアクションは行われませんでした。
以下アクセスした際のログになりますが、ログを見ると
- 認証トークンがないため、処理を中断している

ように見えます。もしこの推測が正しければ、今の自分では解決できないと感じたのが、このコメントに至った経緯です。

**Comment by komagata** [comment]
@reckyy 

> 早めにHelpの意思を表明しておく方がいいと思ったので、質問させていただきました。

ナイス質問です〜。

```
12:33:49 rails.1     | Filter chain halted as :require_token rendered or redirected
12:33:49 rails.1     | Completed 401 Unauthorized in 23ms (ActiveRecord: 1.5ms | Allocations: 1909)
```

ページにアクセスして`Completed 401 Unauthorized`になっているので認証に失敗してるということになります。

> https://github.com/fjordllc/bootcamp/blob/b60e9b4127c5bffa057220e56a86656089e3a304/app/controllers/scheduler_controller.rb#L11

ここで認証しているので環境変数の`TOKEN`に自分で適当な値を設定して、同じ値をURLに指定してアクセスしてみてください。（下記の`hoge`の部分）

http://localhost:3000/scheduler/daily/auto_retire?token=hoge

**Comment by reckyy** [comment]
@komagata @machida 
お疲れ様です。

[休会から六ヶ月後に自動で退会されるようにする](https://github.com/fjordllc/bootcamp/pull/6490#top) でのやりとりを拝見しました。
こちらのIssueも同様に、本番で動作確認できてこちらにご連絡いただいたのを確認してからclose、という流れで問題ないでしょうか。
（本番では自動退会の処理が正常に行われていないことも拝見しました。）

**Comment by machida** [comment]
@komagata cc @reckyy 
退会ユーザーに送られたメールを確認することはできないので、今本番環境にあるテストユーザーを休会に入って6ヶ月にデータをいじって確認するのはどうでしょう？
それとは別に、この手のメールはcc にinfo@lokkaを追加しておきたいですね。

**Comment by komagata** [comment]
@reckyy 本番環境で正しく動作することを確認しました～🎉
