### ISSUE TITLE
`api/reports.json` のレスポンス速度を改善できそう

### ISSUE THREAD

**Issue by sinsoku** [fjordllc/bootcamp#7238]
## 概要

日報のページを表示するのが遅いので、高速化できないか調べました。

## 詳細

日報のページで使用している `api/reports.json` のAPIですが、インデックスの効いていないカラムを `ORDER BY` に指定しているため、 reports のフルスキャンが起きていそうです。

Controller で `Report.list` が呼ばれています。
https://github.com/fjordllc/bootcamp/blob/00ff7e03c5759c7d83f29e7746101028594d7d84/app/controllers/api/reports_controller.rb#L4-L11

`scope :list` で `default_order` が呼ばれている。
https://github.com/fjordllc/bootcamp/blob/00ff7e03c5759c7d83f29e7746101028594d7d84/app/models/report.rb#L55-L59
https://github.com/fjordllc/bootcamp/blob/00ff7e03c5759c7d83f29e7746101028594d7d84/app/models/report.rb#L45

しかし、 `:created_at` にはインデックスがありません。
https://github.com/fjordllc/bootcamp/blob/00ff7e03c5759c7d83f29e7746101028594d7d84/db/schema.rb#L595-L607

## 修正案

created_at の代わりに id を使うと速くなりそうです。

```ruby
scope :default_order, -> { order(reported_on: :desc, id: :desc) } 
````

もしくは created_at にインデックスを追加する方法でも効果があると思います。

## 備考

SQL の explain を調べているわけではなく、コードを読んでの推測になります。
実際に直す場合は、本番環境でSQLのexplainを見た方が良いです。

**Comment by komagata** [comment]
@sinsoku Issueありがとうございます。created_atにインデックスを貼る方向で進めたいと思います〜。

**Comment by komagata** [comment]
@sinsoku こちら #7277 で`created_at`にインデックスを貼ったのでCloseさせていただきます〜。
