### ISSUE TITLE
reports.created_atにインデックスを貼る

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7246]
関連: #7238

インデックスを貼るmigrationを作成してください。

**Comment by kyokucho1989** [comment]
@komagata 
お疲れ様です。インデックスを貼る作業を行いましたが、`shema.rb` に余計な差分が発生しました。
以下のように`staff` テーブルが発生します。


```ruby
  create_table "reports", id: :serial, force: :cascade do |t|
# 略
    t.index ["created_at"], name: "index_reports_on_created_at"
# 略
  end

  create_table "staff", id: { type: :string, limit: 4 }, force: :cascade do |t|
    t.text "name", null: false
    t.integer "age"
  end
```

- これはなぜ発生するのでしょうか。
- 発生を避ける方法はありますか。

**Comment by komagata** [comment]
@kyokucho1989 staffというテーブルは何の機能のためにあるのか、誰が作ったのかなどもう少し調べてみてください〜。

**Comment by kyokucho1989** [comment]
@komagata 
了解しました！調査します

**Comment by kyokucho1989** [comment]
@komagata 

こちら、確認しました。自分のローカル環境のデータベースを参照していました。

```
$ psql -d template1
psql (12.16)
Type "help" for help.

template1=# \dt;
         List of relations
 Schema | Name  | Type  |   Owner   
--------+-------+-------+-----------
 public | staff | table | kyokucho1989
(1 row)
```

このテーブルを削除して、再度`rails db:migrate` を行うと、`schema.rb` に余計な行が追加されなくなりました。

**Comment by kyokucho1989** [comment]
@komagata 

`shema.rb` の問題は解消されましたが、 CIのテストが通らなくなりました。3回実行して3回止まります。

CIテストのログ

https://app.circleci.com/pipelines/github/fjordllc/bootcamp/8169/workflows/7bee7125-daf0-4b26-a319-f43dde109d56/jobs/28037?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary

reportの書き込みに関するテストで毎回止まります。

```
Failure:
ReportsTest#test_canonicalize_learning_times_when_create_and_update_a_report [/home/circleci/project/test/system/reports_test.rb:240]:
expected to find text "23:00 〜 (翌日)00:00" in

Failure:
ReportsTest#test_register_learning_times_4h [/home/circleci/project/test/system/reports_test.rb:276]:
expected to find text "22:00 〜 (翌日)00:00" 
```

質問：
1.  インデックスを貼ったことで書き込みスピードが遅くなり、テストが通りにくくなったということは考えられますか？

2.  インデックスを貼る前と後で表示速度に差が見られません。このIssueは実施するべきでしょうか？

CIが通っていませんが、スクリーンショットと変更したコードを確認していただきたいので、プルリクをDraftから公開モードにしています。
https://github.com/fjordllc/bootcamp/pull/7277

**Comment by komagata** [comment]
@kyokucho1989 

> インデックスを貼ったことで書き込みスピードが遅くなり、テストが通りにくくなったということは考えられますか？

ちょっと考えられないです。実際にどういう画面になって落ちているのか確かめた方がいいかもです。（今自分が想像しているのと全く違うエラー・原因で落ちてるかもしれないので）

> インデックスを貼る前と後で表示速度に差が見られません。このIssueは実施するべきでしょうか？

パフォーマンスを感覚だけで判断するのは危険です。十分な量のデータ（本番と同じぐらい）と正確な計測をした上でないと答えられない感じです。

**Comment by komagata** [comment]
@kyokucho1989 

> このテーブルを削除して、再度rails db:migrate を行うと、schema.rb に余計な行が追加されなくなりました。

@kyokucho1989 さんが自身で作られたテーブルだったって感じですかね？

**Comment by kyokucho1989** [comment]
> kyokucho1989 さんが自身でtemplate1に作られたテーブルだったって感じですかね？

そうです。昔SQLの勉強をしていたときに作った記憶があります。

**Comment by kyokucho1989** [comment]
CIはもう少しトライしてます！
具体的にどこで落ちているかも確認します！

**Comment by kyokucho1989** [comment]
@komagata 

CIで落ちている箇所を確認しました。

```
Failure:
ReportsTest#test_register_learning_times_4h [/home/circleci/project/test/system/reports_test.rb:276]:

expected to find text "22:00 〜 (翌日)00:00" in "お知らせ\nプラクティス\n66\n日報・ブログ\n61\n提出物

略
nRaw\n学習時間:\n4時間\n00:30 〜 02:30\n22:00 〜 00:00...
```

と書いてあり、時間に　`(翌日)`の表記がされていないことがわかりました。ここをもう少し確認していきます。

**Comment by komagata** [comment]
@omochiumaiumai さんこの辺りを担当されていたと思いますが、何かわかる点があったら教えていただければありがたいです〜

> https://github.com/fjordllc/bootcamp/issues/7246#issuecomment-1919049914
