### ISSUE TITLE
「リンク切れを調べてメールを出す」機能の、メール宛先をlokkaに更新したい

### ISSUE THREAD

**Issue by nishitatsu-dev** [fjordllc/bootcamp#7256]
- 下記コード赤線部のアドレスを`info@lokka.jp` に変更する。
  `app/mailers/check_url_mailer.rb`

  ![image](https://github.com/fjordllc/bootcamp/assets/85104698/e7432435-f249-4534-a2c3-bfe136d32458)

- テストファイルも同様の変更を行う。
  `test/mailers/check_url_mailer_test.rb`

**Comment by a-terumoto-gs** [comment]
@komagata 
お疲れ様です。

こちらのissueについてですが、
「リンク切れを調べてメールを出す」機能というのは自動で実行されて、リンク切れを起こしているものがあればメールで通知が行くもので、画面としては存在しないという認識でよろしかったでしょうか？
画面のスクリーンショットを取ろうとして該当のものが見つからなかったため確認です。

合わせて、コード変更後の確認や、その後のステージングと本番環境でのチェックの仕方もいまいち想像がつかないのですが、どう行えばいでしょうか？
ご教示いただけますと幸いです。
よろしくお願いします。

**Comment by komagata** [comment]
@a-terumoto-gs こちら、ミーティングでお話ししたように機能としては今動いてないので動作チェックはしなくて大丈夫です。

## 経緯

厳密に説明するととても長くなってしまうのですが、Webからアクセスして動くプログラムではなく、Google Cloud Schedulerというcron的なプログラムに動かされる、コマンドラインから動くプログラム（のようなもの）になっています。

現在まともに動かしていないのですが、古いメールアドレスがコード中に存在すると、コードを全検索したときに古いメールアドレスが見つかり、みた人に要らぬ心配をかけてしまうのでこのIssueで変更できればと思いました。

**Comment by a-terumoto-gs** [comment]
@komagata 
こちらが聞き漏らしていたようでお手数おかけして申し訳ございません。
細かい経緯までありがとうございます。
さっそく取り組んでいこうと思います！
ありがとうございますm(__)m

**Comment by a-terumoto-gs** [comment]
本番環境に反映されたのでcloseします
