### ISSUE TITLE
日報に写真を添付すると、プレビューが表示されない時がある。

### ISSUE THREAD

**Issue by reckyy** [fjordllc/bootcamp#7262]
## 概要

日報作成時に、写真を添付しようとすると画面がスクリーンショット（下から2つ目の見出しです）のようになり、保存することもプレビューを確認することもできなくなります。
ただし、**毎回ではありません。** 普通に添付できる写真もあります。
今のところ、失敗しているのは **写真アプリからの添付**のみであり、それ以外の写真添付は問題ないです。（スクリーンショットなどのデスクトップの写真）
またChromeで試したところ、Arcでは添付すると不具合を起こしていた写真は漏れなく正常に添付できました。

## 再現手順

1. 日報作成（編集）画面にアクセス。
2.「 ファイルを挿入」をクリック。
3. 「写真」をクリックし、添付する写真を選択し「開く」をクリック。
<img width="143" alt="スクリーンショット_2024-01-26_22_28_23" src="https://github.com/fjordllc/bootcamp/assets/106903482/2048b926-72a4-4c9c-a1ca-2e38b9e76413">

4. プレビューが表示されると同時に、スクリーンショットの画面に**なることがある。**

## 期待される振る舞い

写真のプレビューが表示される。

## スクリーンショット
以下は、写真を添付後の不具合が起きている画面です。

<img width="1792" alt="スクリーンショット_2024-01-26_22_35_31" src="https://github.com/fjordllc/bootcamp/assets/106903482/5fd774f2-850c-42e0-b88c-3fe54b326fae">

## 環境

 - OS: macOS Sonoma ver14.2
 - ブラウザ: Arc
 - バージョン: ver1.21.2, Chromium engine ver 120.0.6099.129

**Comment by komagata** [comment]
@reckyy あ、すみません、これArcでだけ起こることなんですね。
Arcはbootcampの動作環境に含まないのでこちらはCloseしちゃいますね。

**Comment by reckyy** [comment]
@komagata 
了解しました！
ご確認いただきありがとうございました  🙇
