### ISSUE TITLE
ブログ記事にサムネイルを投稿にも表示というチェックボックスを追加。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7264]
メンターでログインし、
/articles/new
にアクセス。

<img width="1038" alt="貼り付けた画像_2024_01_31_16_12" src="https://github.com/fjordllc/bootcamp/assets/168265/f4781727-74bc-48bc-866d-1a9de6dc6677">

この項目を追加する。
チェックが入っていたときだけ、

<img width="850" alt="貼り付けた画像_2024_01_31_16_14" src="https://github.com/fjordllc/bootcamp/assets/168265/111155e3-373d-4893-8bba-fe75906ae653">

このように本文にサムネイルが表示されるようにしたい。
現在はこのチェックがないので、サムネイルが登録されているブログ記事は全て本文にサムネイルが表示されます。この機能を実装し、本文にサムネイルを表示するかしないかを選べるようにしたいです。

この機能を追加し、

今までの投稿には全てチェックを入れる処理も追加してください。

**Comment by masyuko0222** [comment]
@machida 
ご質問２点させてください。

- チェックボックスのデフォルトはONでよろしいですか？(既存記事がONのため)
- チェックボックスの説明（`.a-form-help`タグ)はいかがいたしましょう？
  - 提案「チェックを入れると、ブログ記事の本文内にもサムネイル画像が表示されます。」

**Comment by machida** [comment]
@masyuko0222 

質問ありがとうございます！

> チェックボックスのデフォルトはONでよろしいですか？(既存記事がONのため)

デフォルトはONにしましょう。

> チェックボックスの説明（.a-form-helpタグ)はいかがいたしましょう？
> 提案「チェックを入れると、ブログ記事の本文内にもサムネイル画像が表示されます。」

一旦提案通りのものを入れておいてくださいー。
僕の方であとで調整します。

**Comment by masyuko0222** [comment]
@machida 
[IMO]
チェックボックスのラベル、「サムネイル画像を記事に表示」だと個人的にちょっと分かりづらいかったかもですー。
『サムネイル画像を本文に表示/埋め込む』なんていかがでしょうか。

先の提案と合わせて、ご検討いただけるとありがたいです！

**Comment by machida** [comment]
@masyuko0222 いいですね！その文にしましょうー

**Comment by masyuko0222** [comment]
@machida 
ありがとうございます！
「サムネイル画像を本文に表示/埋め込む」だとさすがに冗長なので、「サムネイル画像を本文に表示」にしておきますー。

**Comment by machida** [comment]
@masyuko0222 了解ですー

**Comment by masyuko0222** [comment]
@komagata CC: @machida 
実装方針について、２点ご質問(相談)させてくださいー。

1
『サムネイル画像を本文に表示』するかどうかのboolean値を、Articleモデルのカラム追加する方針でよろしいでしょうか？
edit時は、保持しているbooleanをデフォルト値として利用したいからです。

2
1がOKの場合、「boolean値のカラム追加」「既存レコードは全てtrueにする」という２つのmigrationファイルを書く予定です。
※後者のカラムは、今までの投稿には全てチェックを入れる処理も追加する、という要望があるためです。

その際、単にmigrationファイルを用意するだけではなく、[data-migrate](https://github.com/ilyakatz/data-migrate)を利用する必要があるでしょうか？

[DBのデータをmigrateする方法](https://github.com/fjordllc/bootcamp/wiki/DB%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92migrate%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95)のWikiを見たものの、今回の方針が当てはまるかわからずご質問させていただきました。

お手数ですがよろしくお願いいたします。

**Comment by machida** [comment]
@masyuko0222 

1についてはその方針でお願いします！
2については @komagata さんから返答してもらおうと思います。

**Comment by komagata** [comment]
@masyuko0222 

> その際、単にmigrationファイルを用意するだけではなく、[data-migrate](https://github.com/ilyakatz/data-migrate)を利用する必要があるでしょうか？

必要ないです。

> 「boolean値のカラム追加」「既存レコードは全てtrueにする」

カラム追加するときに

「booleanでデフォルトがtrueのカラムを追加」

という書き方ができるので、これをやることによって既存のものは全てtrueという状態も実現できると思います。

**Comment by masyuko0222** [comment]
@machida 
チェックボックスにチェックを入れて、正常にサムネイルが表示されているかのテストは、既存のテストで賄えていると思っています。
そのため、上記についての新規テストは書かないつもりなのですが、よろしいでしょうか。

該当のテストは下記です。
https://github.com/fjordllc/bootcamp/blob/e24e51a78579d003104982781a1bd7fb42defef8/test/system/articles_test.rb#L274C1-L287C6

```ruby
  test 'if there is no featured image, the default image is set as the OGP image' do
    visit_with_auth "/articles/#{@article.id}", 'komagata'
    verify_default_ogp_image_used
  end

  test 'can set up prepared images for eye-catching image, the default OGP image will be used' do
    visit_with_auth edit_article_path(@article), 'komagata'
    find('label[for=article_thumbnail_type_ruby_on_rails]').click
    click_button '更新する'

    visit "/articles/#{@article.id}"
    verify_default_ogp_image_used
    assert_selector 'img[src$="ruby_on_rails.png"]'
  end
```

**Comment by masyuko0222** [comment]
@komagata @machida 
本番環境での確認をお願いしたいです～m(__)m

確認の手順は以下になります。

1. ブログ記事の編集ページ`/articles/:id/edit`に移動する(どの公開記事でも大丈夫です)
2. **「サムネイル画像を記事に表示」のチェックボックスONになっていることを確認する**
![無題](https://github.com/fjordllc/bootcamp/assets/111285341/4a79d6ad-79b4-40ee-8401-241fa7f6ceaf)
3. 「サムネイル画像を記事に表示」のチェックボックスをクリックし、OFFにする
4. 更新するボタンを押下する
5. **リダイレクト先のブログ本文内に、サムネイルが表示されていないことを確認する**
6. 内容修正ボタンを押下する
7. 「サムネイル画像を記事に表示」のチェックボックスをクリックしてONにして、再度更新するボタンを押下する
8. **リダイレクト先のブログ本文内に、サムネイルが表示されていることを確認する**

**Comment by komagata** [comment]
@masyuko0222 本番環境で確認してOKでした〜！

**Comment by masyuko0222** [comment]
@komagata 
ありがとうございます～！
本番環境で確認が取れたのでCloseします！
