### ISSUE TITLE
ユーザープロフィールに決済情報のリンクが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7273]
現在は管理画面のユーザー一覧にだけある「カード情報」へのリンクを一般のユーザープロフィールページに非公開情報として載せたい。

管理画面のユーザー一覧：

![スクリーンショット 2024-01-28 20 20 47](https://github.com/fjordllc/bootcamp/assets/16577/3c0d5027-77f6-41f0-81d8-ac3529aac74f)

ユーザープロフィール：

![スクリーンショット 2024-01-28 20 24 01](https://github.com/fjordllc/bootcamp/assets/16577/6d384121-b945-407e-9803-365a56969d91)

### 注意点

- 一般ユーザーは見れない非公開情報として表示すること
- リンク先はStripeの管理画面内なので作業者の人はアクセスできない状態でOKです。

**Comment by SuzukaHori** [comment]
@komagata @machida

お疲れ様です。
カード情報がない場合の文言を確認させていただきたいです。

現在カード情報のリンクがあるユーザ一覧の画面では、カードが登録されていればアイコン、登録されていない時はハイフンが表示されています。

新たにリンクを追加するプロフィールページでは、未登録の場合にハイフンを表示するのが違和感がある（すぐ上の「卒業後のゴール」がない場合、ハイフンでなく「未入力」となっている）ため、以下のような文言を考えました。

- カードが登録されている場合：
  <img width="155" alt="スクリーンショット 2024-01-29 16 58 10" src="https://github.com/fjordllc/bootcamp/assets/129706209/9992b967-bcd5-4cc9-82c2-524f09323e7a">

- されていない場合：
  <img width="129" alt="スクリーンショット 2024-01-29 16 58 46" src="https://github.com/fjordllc/bootcamp/assets/129706209/9575d872-bff7-48d0-afc2-c61a91211368">

しかしこの文言にすると、「カード情報が未登録」ではなく「決済情報が未登録」というようにも読めてしまい、「カード未登録」の人を「決済情報未登録」とイコールにして良いか判断がつきませんでした。

以下のどの文言にすれば良いか、確認したいです。

1. 「カード登録」 & 「未登録」
2. 「カード登録」 & 「カード未登録」
3. 「カード登録」＆ ハイフン（ユーザ一覧の画面と同じ）
4.  それ以外

よろしくお願いいたします🙇‍♀️

**Comment by komagata** [comment]
@SuzukaHori どれでも悪くわはいのですが、

「カード情報」＆「カード未登録」

でお願いします〜

**Comment by SuzukaHori** [comment]
@komagata
回答ありがとうございます🙏
「カード情報」＆「カード未登録」で進めます。引き続きよろしくお願いします🙇‍♀️

**Comment by komagata** [comment]
@SuzukaHori 本番環境で動作することを確認しました〜

**Comment by SuzukaHori** [comment]
@komagata 
確認ありがとうございます🙏

本番環境で動作を確認できましたのでCloseします。
