### ISSUE TITLE
お知らせ通知を高速化する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7279]
## 概要

お知らせを投稿した時の通知（サイト内通知・メール通知）が遅い。

原因は、たくさんのユーザーに通知を送っているのだが、１通＝１つのJob（ActiveJobのJob）として送っているため。
（１つのJobはかなり遅く、１つにつき１プロセス作成されるし、１レコード作成される）

これを１つのJobで全員に送れば早くなり、リソースを節約できる。

## やること

現状の`ActivityNotifier#post_announcemnt`の利用をやめて自前の処理で通知する。
- https://github.com/fjordllc/bootcamp/blob/3074feb17edfa0b5f1813a091712db2705d1aeb3/app/notifiers/activity_notifier.rb#L129

**Comment by naokinaokiboo** [comment]
@komagata
## ステージング環境、本番環境での動作確認について

本Issueについてのステージング環境、本番環境での動作確認について相談させてください。🙇‍♂️

動作確認について、確認内容を以下のように考えています。（**一部、動作確認の協力依頼も含んでいます**）

何かご意見等ありましたら、よろしくお願い致します。🙇‍♂️

### 確認事項
お知らせの作成時に
1. １つの`Job`だけがキューに追加されていること（ログから`PostAnnouncementJob`を確認）
```
// 以下、ログのサンプル
[ActiveJob] [PostAnnouncementJob] [b06939d2-4604-4856-94a2-ce648647c7e1] Performing PostAnnouncementJob (Job ID: b06939d2-4604-4856-94a2-ce648647c7e1) from GoodJob(default) enqueued at 2024-02-26T03:05:37Z with arguments:
```
2. メール通知が行われること（作成者以外）
3. サイト内通知が行われること（作成者以外）

### ステージング環境について
- [ ] **`確認事項1`についてお願いしたいです。** 🙏
- [ ] `確認事項2,3`については、以下の方針で私の方で確認を予定しています。
  - [ ] メール通知：お知らせを作成するユーザーと受信ユーザーについて、一時的に私が確認できるメールアドレスに変更して確認
  - [ ] サイト内通知：実際に複数名でログインして確認

### 本番環境について
- [ ] **`確認事項1`についてお願いしたいです。** 🙏
- [ ] `確認事項2,3`については、全員分の確認は不可能だと思いますので、以下の方針で考えています。
  - [ ] テスト用のお知らせを作成して、自身に通知が来ないことを確認
  - [ ] 自身にリリース時のお知らせ通知が来ることを確認

**Comment by komagata** [comment]
@naokinaokiboo 上記の通り進めていただいて大丈夫です〜

**Comment by naokinaokiboo** [comment]
@komagata 
お疲れ様です。
こちらのIssueの本番環境での動作確認をお願い致します。🙇‍♂️
`good_job`のダッシュボードから`PostAnnouncementJob`が`Succeeded`になっていることを確認して頂きたいです。
先週のリリース以降、現時点で以下の２件の`PostAnnouncementJob`が実行されていると思われます。

![image](https://github.com/fjordllc/bootcamp/assets/131861805/1d9ab9b3-3d1f-4d1b-b4e9-c8d9a599e13c)

**Comment by komagata** [comment]
@naokinaokiboo こちら、ステージング環境では上記の確認取れてたかんじでしょうか？

**Comment by naokinaokiboo** [comment]
@komagata 
はい。ステージングでは確認済みです。
経緯としましては、前回リリース前にステージング環境で不具合が出たため以下のPRで対応、ステージング確認後にリリースという流れです。
https://github.com/fjordllc/bootcamp/pull/7540

**Comment by komagata** [comment]
@naokinaokiboo 確認が遅くなり申し訳ありません。
本番環境で正しく動作することを確認しました～🎉
