### ISSUE TITLE
月を跨ぐと日報の学習時間に（翌日）　がつかない

### ISSUE THREAD

**Issue by kyokucho1989** [fjordllc/bootcamp#7294]
## 概要

日報で学習時間を記録する際に、月を跨ぐようにすると（翌日）がでない。

例：
`2024/1/31 23:00 ~ 2024/2/1 0:00`
で記録すると、
`23:00 ~ 00:00` となる。

## 再現手順

1. `foreman start -f Procfile.dev` で開発環境にアクセス
2. 任意のアカウントでログイン
3. 日報作成画面へうつる
4. 学習の日付を月末に設定
5. 学習時間を23:00 ~ 0:00 と設定

## 期待される振る舞い

月を跨いでも（翌日）が表示されること。

## スクリーンショット
<img width="420" alt="スクリーンショット 2024-02-01 4 34 52" src="https://github.com/fjordllc/bootcamp/assets/8443743/6707e7ab-450f-4e07-ab8b-e73b17e88be6">

## 環境

 - OS:  MacOS Ventura 13.4.1 [e.g. iOS]
 - ブラウザ: chrome  [e.g. chrome, safari]
 - バージョン: 119.0.6045.123 [e.g. 22]

## その他

`app/views/reports/_learning_times.html.slim` の条件式を変えれば
改善されるかと思います。

```
          | #{l learning_time.started_at, format: :time_only} 〜 #{'(翌日)' if learning_time.started_at.day < learning_time.finished_at.day}#{l learning_time.finished_at, format: :time_only}
```

現在は日について大小の比較を行なっているため、月を跨ぐと`（翌日）`が表示されないのだと思います。

## 関連Issue

Ref: #関連Issue番号

**Comment by komagata** [comment]
@omochiumaiumai さんこの辺りを担当されていたと思いますが、もし何かわかる点があったら教えていただければありがたいです〜

**Comment by omochiumaiumai** [comment]
@komagata @kyokucho1989 
お疲れ様です！こちらメンションに気づくのが遅れてしまい申し訳ございません。
> この辺りを担当されていたと思いますが、もし何かわかる点があったら教えていただければありがたいです〜

上でご指摘をいただいているように、`(翌日)`が表示される式の条件が日付の大小になっているために発生している現象です。
すでに@a-kuroki-gs さんに修正をしていただいておりますが、dayメソッドを使用せずに`started_at`と`finished_at`を比較すれば解決します。
```
 | #{l learning_time.started_at, format: :time_only} 〜 #{'(翌日)' if learning_time.started_at < learning_time.finished_at}#{l learning_time.finished_at, format: :time_only}
```
お手数をおかけしました🙇‍♂

**Comment by komagata** [comment]
@omochiumaiumai なるほどです、ありがとうございます〜！

**Comment by a-kuroki-gs** [comment]
本番環境で確認できたのでCloseします🙌
