### ISSUE TITLE
お問い合わせ一覧、個別ページがほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7302]
すでに、inquiries はあるが、メールで飛ばすだけでWeb用の画面がないので、Web用の画面を作って欲しい。

---

管理者でログインし、`/admin` にアクセス。管理ページ。

<img width="1032" alt="貼り付けた画像_2024_02_07_8_34" src="https://github.com/fjordllc/bootcamp/assets/168265/d7421bf5-ce7b-469a-b149-5d85eecaa99d">

タブにお問い合わせを追加。
お問い合わせ一覧ページを作成。

<img width="1442" alt="貼り付けた画像_2024_02_07_8_35" src="https://github.com/fjordllc/bootcamp/assets/168265/44753d85-10c9-4ad5-8b0c-3dd0b153f11c">

お問い合わせ個別ページを作成。

<img width="1442" alt="貼り付けた画像_2024_02_07_8_35" src="https://github.com/fjordllc/bootcamp/assets/168265/99400223-098f-48dd-950f-703f8e2b7fd8">

**Comment by a-kuroki-gs** [comment]
@komagata @machida 
お疲れ様です。
こちらのissueについて２点相談がございます。

１点目、<b>詳細画面への遷移方法</b>についてです。
多くの一覧画面(日報など)ではタイトルをクリックすると詳細画面に遷移するようになっておりますが、お問い合わせの内容にはタイトルがありません。
かと言って名前や本文をリンクにするのも自分の中ではしっくりきておらず、今回`開く`というボタンを配置してみました。
こちらどう実装するのがよいでしょうか？ご意見をお伺いできればと思います。

２点目、<b>画面の仕様</b>についてです。
現在添付の画像のように`名前：`などのキーワードとその内容を羅列しているだけの内容になっております。
![image](https://github.com/fjordllc/bootcamp/assets/133615511/3b6ec470-ebc3-4768-a688-2f8ece1fcd4c)

実装しているうちに思ったのですが、以下の実装は必要でしょうか？
- 確認したお問い合わせを一覧画面から排除する、`確認済` or `削除する`といったボタン等
- 確認済のものとそうでないものを分けるタブ？か何か
- ページネーション

お問い合わせの量が分からないので何とも言えないのですが、個人的には、メールも届くということなので確認済のものは削除するのも１つの手なのかな？と思ったり…でも一覧から消えるのが仕様上どうなのか？と思ったり…。
本issueの範囲でどこまでやるべきか、ご回答いただければと思います。

以上２点、お手すきの際にご確認よろしくお願いいたします。

**Comment by komagata** [comment]
@a-kuroki-gs (CC: @machida )
（画面の使い勝手の話なので @machida さんにご意見伺いたいです〜）

下記、一応の僕だったらどうするのがいいかと考えてみた結果になります。

> １点目、詳細画面への遷移方法についてです。

"一つのお問い合わせを表示しているエリア全体をクリックできるようにする"というのはどうかなと思いました。

> ２点目、画面の仕様についてです。

まずは"管理画面でお問い合わせが確認できる"というのがこのIssueの目的なので、他の機能はやるとしても別Issueでやるといいかなと思います。

**Comment by machida** [comment]
@a-kuroki-gs 

@komagata さんの提案のように実装しておいてくださーい。細かいデザインは僕がやるので、ざっくり簡単にで大丈夫です。

仕様は、今回のIssueでは問い合わせ内容が見れれば大丈夫です。削除も編集も不要です。未読既読管理やメモ機能などが欲しくなりそうですが、それらは別Issueでやります。

**Comment by a-kuroki-gs** [comment]
@komagata @machida 
> スマホアプリみたいに"一つのお問い合わせを表示しているエリア全体をクリックできるようにする"というのはどうかなと思いました。

> 仕様は、今回のIssueでは問い合わせ内容が見れれば大丈夫です。削除も編集も不要です。未読既読管理やメモ機能などが欲しくなりそうですが、それらは別Issueでやります。

承知しました！この方向性で進めようと思います。
ご回答ありがとうございました🙌

**Comment by machida** [comment]
こちら本番で確認したのでクローズにしますー

**Comment by komagata** [comment]
@a-kuroki-gs 本番環境で正しく動作することを確認しました～🎉
