### ISSUE TITLE
休会中／退会済の会員のプロフィールページが見える

### ISSUE THREAD

**Issue by ogawa-tomo** [fjordllc/bootcamp#7309]
ユーザのプロフィールページhttps://bootcamp.fjord.jp/users/{user_id} に直接アクセスすると、休会中や退会済の会員でもプロフィールページが見えてしまいます（日報や提出物なども）。ユーザIDは自然数の連番なので、簡単に推測できてしまいます。
休会中／退会済の会員は一覧ページhttps://bootcamp.fjord.jp/users での検索に引っかからないようになっているので、仕様上はプロフィールページへの直接アクセスもできないほうが望ましいと思われます。（管理者／メンターはアクセスできたほうがよさそう）

**Comment by kurumadaisuke** [comment]
@komagata 
すいません、実装する前にちょっと本issueの仕様について質問させてください🙏
休会中や退会済の会員の「プロフィールページ」が見えることに対して制限（メンターさん達は見えて、現役生は見れない）をかけるイメージでしょうか？
認識が間違っていたらご教示お願いしますmm

なので休会中や退会済の会員の日報や提出物に対しては制限かけない認識です🙏
会員のQ&Aや日報などはプラクティスを進めていく中で参考にする場合（プラクティスの中にも参考にしている場合もあるので）があるので制限かける範囲はあくまで「プロフィールページ」の認識です。

**Comment by kurumadaisuke** [comment]
@komagata 
現状、存在しないuser_idを指定した場合以下のようなスクリーンショットの画面になります🙏
なので本issueも休会中or退会中のuser_idが選択された場合以下のようなスクリーンショットにリダイレクトさせるイメージであっていますか？
`例：https://bootcamp.fjord.jp/users/20001`
<img width="907" alt="スクリーンショット 2024-02-15 21 22 02" src="https://github.com/fjordllc/bootcamp/assets/57862327/98b28da1-ee67-4842-811d-a96751404a01">

**Comment by komagata** [comment]
:memo: @machida さんとこちらのIssueについて話し合いました。
休会・退会ユーザーが見えても問題ないため、こちらのIssueは中止させていただければありがたいです。
ユーザー検索に休会・退会ユーザーが引っかからない件についてはこちら（ #7396 ）のIssueで変更したいと思います。

@kurumadaisuke 大変申し訳ありません、上記の経緯で、こちらのIssueは中止していただければありがたいです。
すでにかなり調査されていたと思いますのでこちらのポイントを1ptにしましたが、こちらはポイント獲得としてCloseしてしまって大丈夫です。

**Comment by kurumadaisuke** [comment]
@komagata 
ご連絡ありがとうございますmm
こちらのissueクローズの件承知いたしましたmm

**Comment by machida** [comment]
🙇‍♂️🙇‍♂️🙇‍♂️
