### ISSUE TITLE
ターゲットに関わらず、メンターにはお知らせの通知をするようにする。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7317]
https://bootcamp.fjord.jp/announcements/956#comment_156881

お知らせが作成されたら、お知らせのターゲットに関わらずメンターには通知をするように変更をする。
すっかり飛んでいると思っていたが、よく考えたら飛んでいなかった。
認識違いか、デグレが起きてしまったかもしれない。

**Comment by masyuko0222** [comment]
ステージング環境では、
- アプリ内通知
- メール通知

共にきていることを確認します。

特にメール通知に関しては、ユーザーのメールアドレスを、実際に自身が確認できるメールアドレスに変更することで確認を行います。

**Comment by masyuko0222** [comment]
@komagata 
ステージング環境で確認が取れたため、クローズいたします。

**Comment by masyuko0222** [comment]
@komagata 
誤ってステージング環境の確認でCloseしてしまっていました、すみません・・・。

本番環境での確認方法をお聞きしたいです。

自分が「現役生のみ」「就活希望者のみ」宛のお知らせを作成後、メンターにアプリ内通知・メール通知が来ていることを確認したいのですが、やり方をご教授いただいてもよろしいでしょうか。

**Comment by komagata** [comment]
> 自分が「現役生のみ」「就活希望者のみ」宛のお知らせを作成後、メンターにアプリ内通知・メール通知が来ていることを確認したいのですが、やり方をご教授いただいてもよろしいでしょうか。

@masyuko0222 さんはどうすればいいと思いますか？自分だったらどうするか考えてみてください〜。

**Comment by masyuko0222** [comment]
@komagata 
すみません、丸投げすぎる質問でした。。

一番簡単なのは、実際にメンターさんに確認してもらうやり方だと思っています。

お知らせ作成後、Discord等でお願いする、という流れで考えています。

**Comment by komagata** [comment]
@masyuko0222 最初はどういう温度感かわからないと思うので大丈夫ですよ〜。
ただ、新人プログラマーとしてはその辺りがどこまで自分事（自分のアプリ）として考えて作業しているかというのは色んなところに現れてしまって、そこをプログラマーの上司は見ていると思うのでその点で評価が下がってしまわないように気をつけてみるとグッとレベルアップするとおもいます。

https://bootcamp.fjord.jp/announcements/968

こちらのお知らせをリリース時に「現役生のみ」で公開したのでDiscordでメンターの方に確認をお願いしてみてください〜。
（その時は何を確認すればいいのかを、このissueの流れが分からなくてもできるようにお伝えしてみてください）

「就活希望者のみ」は滅多にできないので今回は確認しなくて大丈夫です。

**Comment by masyuko0222** [comment]
@komagata 
> プログラマーの上司は見ていると思うのでその点で評価が下がってしまわないように気をつけてみるとグッとレベルアップするとおもいます

アドバイスしていただきありがとうございます。サラリーマンとして働く上で、必ず意識した方がいいですね。気を付けます。

本番環境での確認方法も承知しました。

**Comment by komagata** [comment]
@masyuko0222 連絡ありがとうございます。
メンター権限があるアカウントが存在すると自動的に外部向けページのメンター一覧に表示されてしまうのでデモアカウントの追加は現状ではできないんですよね。

`@mentor` をつけてDiscordで発言するとメンター全員に届くと思うのでそちらでメール通知オンで協力してくださるメンターさんを探してもらっても良いでしょうか。

それとは別に上記のために特定の人をメンター一覧に表示させない機能も開発したいと思います。

**Comment by masyuko0222** [comment]
@komagata 
本番環境での確認が取れたので、closeいたします！
