### ISSUE TITLE
日報一覧の未チェックタブに未チェックの日報の数字を出したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#732]
<img width="669" alt="_2019_01_04_16_52" src="https://user-images.githubusercontent.com/168265/50678272-4058f080-1041-11e9-8eda-9a28b089611c.png">

**Comment by komagata** [comment]
CSSでのデザインは @machida さんがやるので適当なタグに数字を出すところまでをやる感じで。

PR上で machida さんに「デザインお願いしますー」という感じでいっておけば、そのPRにコミットを追加してくれるはずです。

**Comment by ryoh173** [comment]
数字を出すところまでやりました
@machida 
デザインをお願いします！

**Comment by machida** [comment]
@ryoh173 ありがとうございます！！デザイン入れますー！！
