### ISSUE TITLE
コース一覧に「コースのコピー」が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7321]
新しいコースを作るときにカテゴリーをたくさん選ぶのが大変なので、コースのコピー機能が欲しい。

対象のコースからコピーを選ぶと、元のコースの情報（カテゴリー情報だけで良い）が最初から入った形でコース選択画面に遷移してほしい。

![スクリーンショット 2024-02-06 20 16 28](https://github.com/fjordllc/bootcamp/assets/16577/546f59ac-097b-4c29-b636-d03e5cc55837)

![スクリーンショット 2024-02-06 20 19 39](https://github.com/fjordllc/bootcamp/assets/16577/6e60f5a0-f59a-482c-88d2-1e6551265772)

下記のようなURLにして、course_idからデータを取ってくるといいかも。

`/mentor/courses/new?course_id=1234`

**Comment by kurumadaisuke** [comment]
@komagata 
こちらのissueについてマージ後の本番環境の確認がメンターでないとできないため
お手数ですがご確認お願いいたします🙏

**Comment by komagata** [comment]
@kurumadaisuke 本番環境で確認してOKでした〜。

**Comment by kurumadaisuke** [comment]
@komagata 
ご確認ありがとうございます！
それではこちらcloseさせていただきます
