### ISSUE TITLE
管理者でユーザー情報を変更したときのリダイレクト先をそのユーザーのプロフィールページにしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7322]
現状は結構重い「管理画面　ユーザー一覧」へリダイレクトしているので。

**Comment by taco-nantai** [comment]
@komagata @machida 
お疲れ様です。
本Issueの作業内容がリリースされたので、本番環境での確認を行いたいのですが、確認に管理者ユーザーでのログインが必要なため、本番環境での確認をお願いしてもよろしいでしょうか。
お手数をおかけしますが、よろしくお願いいたします🙇‍♂️

**Comment by komagata** [comment]
@taco-nantai 本番環境で確認しました。OKでした〜！

**Comment by taco-nantai** [comment]
確認ありがとうございます🙇‍♂️
