### ISSUE TITLE
お帰りなさいメッセージが二つ送信されてしまう。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7325]
休会から帰ってきたときに相談部屋に流れるメッセージが、二回送信されているっぽい。

<img width="896" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/f1398bd0-86e5-4ecb-b930-0be1ad2caef5">

原因を調査し修正する。

---

お帰りなさいメッセージに関する別Issue
https://github.com/fjordllc/bootcamp/issues/6905

**Comment by komagata** [comment]
#7312 と重複してるためCloseします。
