### ISSUE TITLE
imagemagickからlibvipsに移行したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7330]
activestorageの画像変換・リサイズに使うライブラリを遅くて依存の多いimagemagickからlibvpsに移行したい。

参考URL：

[サムネイルは libvips ＋ WebP で生成するのがよいか？ \- ユニファ開発者ブログ](https://tech.unifa-e.com/entry/2022/11/17/100005)

**Comment by yocchan-git** [comment]
本番環境の確認OKでした〜
