### ISSUE TITLE
企業に"管理者メモ"が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7341]
企業情報に"メモ"欄が欲しい。

登録・編集できるようにして、企業情報のページに表示してほしい。

![スクリーンショット 2024-02-08 20 09 01](https://github.com/fjordllc/bootcamp/assets/16577/256e5609-5b7c-4f1f-874b-cd1b8d8c2bea)

![スクリーンショット 2024-02-08 20 11 30](https://github.com/fjordllc/bootcamp/assets/16577/e814a6ae-ede4-455c-a6f4-88d5cc59c696)

閲覧・編集・削除ができるのは管理者のみ。

ユースケースとしては下記などです。

- 研修全体の管理者（研修に問題があった時連絡する人）を記載する
- 企業特有の問題（内定者研修でのみ利用するなど）を記載する

**Comment by 88-99** [comment]
管理者の動作確認OKをいただきましたので、Issueをcloseします。
