### ISSUE TITLE
自動退会メールのBCCにinfo@lokka.jpを追加する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7342]
相手へのメールは本番確認できないのでこのメールで本番確認するため。

:memo: あとで変更するファイル名をここに書きます。

- [user_mailer.rb](https://github.com/fjordllc/bootcamp/blob/main/app/mailers/user_mailer.rb)

**Comment by taco-nantai** [comment]
@komagata 
アサインありがとうございます🙇‍♂️
こちらのIssueに関して、2点質問させていただきたいです。

- 自動退会メールのBCCにinfo@lokka.jpが追加されていることを検証するテストコードは書くべきでしょうか。
また、テストコードを書く場合、[user_mailer_test.rb](https://github.com/fjordllc/bootcamp/blob/main/test/mailers/user_mailer_test.rb)に追加する形でよいでしょうか。

- http://localhost:3000/letter_opener に届いたメールを確認することで、bccにアドレスが追加されていることを確認しようとしているのですが、ユーザーの自動退会を発生させるにはどうすればよいでしょうか。

お手数をおかけしますが、ご教授お願い致します🙇‍♂️🙇‍♂️

**Comment by komagata** [comment]
@taco-nantai 

> 自動退会メールのBCCに[info@lokka.jp](mailto:info@lokka.jp)が追加されていることを検証するテストコードは書くべきでしょうか。
> また、テストコードを書く場合、[user_mailer_test.rb](https://github.com/fjordllc/bootcamp/blob/main/test/mailers/user_mailer_test.rb)にauto_retireのテストを追加する形でよいでしょうか。

NOです。

> http://localhost:3000/letter_opener に届いたメールを確認することで、bccにアドレスが追加されていることを確認しようとしているのですが、ユーザーの自動退会を発生させるにはどうすればよいでしょうか。

こちらGood First Issueとしては確認方法が難しいのでコードの変更だけでOKです。

**Comment by taco-nantai** [comment]
了解しました！
回答ありがとうございます🙇‍♂️🙇‍♂️

**Comment by taco-nantai** [comment]
本番環境にマージしていただいたので、closeとさせていただきます。
