### ISSUE TITLE
日報提出のお祝いメッセージを複数回表示したい

### ISSUE THREAD

**Issue by SuzukaHori** [fjordllc/bootcamp#7344]
## 機能の説明
100回目に日報を提出した時に以下のような画面が出ます。

![スクリーンショット 2024-02-09 10 46 48](https://github.com/fjordllc/bootcamp/assets/129706209/feb89b44-9f67-4eb2-ac55-ac9edaee6771)

現在の実装では、お祝いメッセージが出るのが100回目のみになっています。
```ruby
# app/controllers/reports_controller.rb
CELEBRATING_COUNTS = [100].freeze
```
これをキリの良い回数（例えば100回ごと）で定期的に表示されるようにして欲しいです。

## 何故この機能が必要なのか

200日目の日報を提出した際に、お祝いが表示されるのを期待しましたが何も出ず、がっかりしました。

現在日報200回以内で卒業する方は少ないため、キリのいい回数ごとに表示された方が受講生のモチベーションアップにつながると考えます。

こちらのIssueでも「いずれ150回・200回などの節目のタイミングでお祝いを送る」ことが検討されていたようです。
- https://github.com/fjordllc/bootcamp/issues/3353

**Comment by SuzukaHori** [comment]
@machida 
お疲れさまです！
こちらのIssueについて、2点相談させてください🙇‍♀️

### お祝いを表示する日数について
原案として以下のように考えました。
   ```
   [100, 200, 222, 300, 333, 400, 500, 555, 600, 700, 777, 800, 900, 1000, 1111, 1500, 2000]
   ```

  考えた観点は以下の通りです：
  - 100の倍数の日はお祝いする。ただし、（該当者はほぼいないと思いますが）1000回以上は500回ごとにお祝いする。
  - 奇数のゾロ目はお祝いする。ただし、111回目・999回目は100回目・1000回目と接近し過ぎているのでお祝いしない。
  - 222回目は偶数だが、猫を連想させる数字であることや多くの人が提出すると思われることから、お祝いする。

  こちらについて、ご意見を伺いたいです🙇‍♀️

### 画像の有無による条件分岐について
開発ミーティングで「その日数用の画像があるものは日数あり画像、ないものは日数なし画像＋文字」というお話が出ていたと思いますので、以下のような実装を考えています。
  - 画像の有無を判定するヘルパーメソッドを作る。
  - 画像の有無によって条件分岐し、viewを書き換える。
 
もし認識に齟齬がありましたらご指摘ください🙇‍♀️よろしくお願いいたします。

**Comment by machida** [comment]
@SuzukaHori 原案ありがとうございます！！とてもいいと思いました👍これで進めたいと思います。お祝いはいくつあってもいいと思うので、さらにどんどん語呂合わせを増やしていってもいいかもですね。

**Comment by SuzukaHori** [comment]
@machida
ご確認ありがとうございます、こちらで進めます！
語呂合わせを増やしやすいよう、意識して実装します😊
