### ISSUE TITLE
管理ページでユーザーのロールと職業でソートできるようにする

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7348]
"学生"がどのくらいいるかを調べたいため。

サイトの上にある検索で、"ユーザー"に対して検索したときに（もちろん"全て"の場合も）プロフィールの職業欄の文字（学生やフリーターなど）が検索に引っかかるようにしたい。

ユースーケース：

ユーザーを"学生"と検索すると職業が学生の人が見つかる。

**Comment by reckyy** [comment]
@komagata 
お疲れ様です。
仕様について確認させていただきたいです。

## 想定している仕様
> ユーザーを"学生"と検索すると職業が学生の人が見つかる。
> （もちろん"全て"の場合も）


とありますが、こちらの「ユーザーを'学生'と検索すると」というのは、「検索時のセレクトでユーザーを選択して（もしくは全て）ワードは学生を入力する」ということで、

検索結果には職業検索にマッチした結果（学生で検索したら、職業が学生のユーザーのみ）のみを返せば良いですか？
というのも、例えば学生で検索すると日報や、自己紹介に学生という文字が含まれているものも出てきます。
そのため、確認させていただきました。
よろしくお願いいたします。

**Comment by komagata** [comment]
@reckyy 

> 検索結果には職業検索にマッチした結果（学生で検索したら、職業が学生のユーザーのみ）のみを返せば良いですか？

NOです。

職業がマッチしたユーザーやプロフィールにそのワード（"学生"など）が入っているユーザー全てを表示してください。

**Comment by reckyy** [comment]
@machida 
お疲れ様です。
仕様変更の旨、承知しました。2点お伺いします。
### 1点目
現在、
- サイトの上にある検索で、ログインユーザーが **管理者 or メンター**の時だけ職業検索も可能

という仕様で実装しています。
制限をかけているからいいというわけではなく、そもそも「サイトの上にある検索で検索できる状態がまずい」ということでしょうか。

### 2点目
上記の通り、管理者 or メンターが職業検索可能（メンターもユーザー非公開情報を閲覧可能なため）にしていました。
ですが今回の変更内容を拝見すると、「管理者のみが職業検索可能」と認識を改めても良いでしょうか。

以上、お手数をおかけしますがご確認いただけますと幸いです。
よろしくお願いいたします。

**Comment by machida** [comment]
@reckyy ごめんなさい！ユーザーの検索で職業での絞り込みに管理者、メンターだけが使えるということを考慮してくれてたのですね。でしたら、非公開な情報は守られるので、一旦OKとしたいと思います。ただ、管理者、メンターだけが職業で絞り込みができる、という機能をインクリメンタルサーチで行わずに、別の機能であるということがわかるUIにしたいと思います。

今日の昼前にUIをこちらに投稿するのでお待ちください🙏

**Comment by machida** [comment]
@reckyy 

お待たせしました。

ごめんなさい🙇‍♂️

やはり、ログインユーザーが 管理者 or メンターの時だけしか職業での検索はできないようにしていても、機能として複雑でわかりにくいものになってしまうため、職業での検索は検索ではなく絞り込みの形で管理者用のユーザー一覧に付けたいと思います。

![image](https://github.com/fjordllc/bootcamp/assets/168265/89af6b5e-8907-4ac5-850e-ca1a0a26cf04)

なぜそうするかについて説明しておきます。

> サイトの上にある検索で、ログインユーザーが 管理者 or メンターの時だけ職業検索も可能

この対応があることでユーザーの情報が守られるのは助かるのですが、実装的に「サイトの上にある検索で、ログインユーザーが 管理者 or メンターの時だけ職業検索も可能」としても、ユーザーがそのようになっていると把握しないと、「大変です！非公開情報のはずの職業が検索結果で表示されています！」という報告がメンターから僕のところへたくさん飛んでくることになります。そうならないようにするためには、どこかに「ユーザーで検索した際、ログインユーザーが 管理者 or メンターの時だけ職業検索もできます」と書くなどの対応が必要になりますが、その対応はイマイチですよね。。。

また、今回の仕様は複雑で、

- 管理者かメンターでログインしていてユーザーで検索したときだけ、職業も検索対象になる
- 職業名と同じ文字列（例えば「学生」）がプロフィール文にあった場合も検索結果に表示される

この仕様をユーザーに誤解なく伝えるのは難しいです。
また、この動作が不自然に感じます。多くの人は、職業はユーザーをカテゴライズする要素の一つなので、検索対象にするのではなく、絞り込むのが自然と感じます。今の仕様だと、「職業で学生で絞り込みたいときに、プロフィール文に学生という文字が含まれていたら、それも含めて検索結果に出てしまう」というバグ報告が来ることが予想できます。

**Comment by reckyy** [comment]
@machida 
コメントありがとうございます！
理由につきましても詳細に解説いただき、ありがとうございます。

委細承知しました。
管理ページのユーザータブ画面に絞り込みを作成する方針で進めます。

そのため、以下のPRはcloseして、ローカル、リモートブランチともに削除したいと思います〜。
- https://github.com/fjordllc/bootcamp/pull/7398

**Comment by machida** [comment]
@reckyy 本番で確認できましたー🙆

**Comment by reckyy** [comment]
@machida 
ご協力ありがとうございます！！

動作確認できたため、closeします〜。
