### ISSUE TITLE
ユーザ一覧の期生別ページを「現役生」で絞り込めるようにしたい

### ISSUE THREAD

**Issue by SuzukaHori** [fjordllc/bootcamp#7351]
## 機能の説明
ユーザ一覧の期生別のページ（`/generations`）では、「研修生」「アドバイザー」「卒業生」「メンター」で絞り込みができます。

ここに「現役生」を追加したいです。
<img width="1306" alt="スクリーンショット 2024-02-10 16 45 12" src="https://github.com/fjordllc/bootcamp/assets/129706209/a965954a-a742-43d9-8e52-180b4c26f215">

## 何故この機能が必要なのか
自分と同時期に入った人が誰かがわかると、人によってはモチベーションアップにつながると思います。
現在は「全員」で選択して見るしかなく、アドバイザー・研修生が含まれるのでわかりにくいです。

**Comment by machida** [comment]
## 現在の期生別

<img width="1018" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/973429d1-263a-4e2d-af1a-f00acd629e75">

## このように変更する

<img width="1135" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/c3fc1de5-89ed-4456-994c-e49268fc5a9a">

---

- 「現役 + 研修生」を追加する。
- 「現役生」を追加する。

関連Issue: https://github.com/fjordllc/bootcamp/issues/7614
