### ISSUE TITLE
Q&AページのQuestion部分を非Vue化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7356]
vueを使わないようにするためにタイトルになっているファイルを使っている箇所を普通のHTMLでの実装に変える。
（普通のscaffoldっぽいもの）

元々Reactに変更する予定でしたが、最終的にはHotwireにする予定なので、VueもReactも使わない実装にしたいです。（普通にviewに表示する方式）

Questionの下にAnswersがありますが、そちらは別のIssueやるのでそのままで大丈夫です。

**Comment by junohm410** [comment]
@komagata @machida 
お疲れ様です。一点確認いただきたいことがありメンションさせていただきました。お手数ですがご確認のほどよろしくお願いいたします🙏

## ご確認をお願いしたいこと
質問の作成・更新時のフラッシュメッセージについて、JS + Railsで対応していたものをRailsのみで処理するにあたり、それまでアドホック的に対応していた不具合対応の取り止めを含め、処理の統一による文言の変更が起こることになりそうです。

その対応について考えたものを下にまとめましたので、進め方の案のご確認をお願いしたいです。

## 現在のフラッシュメッセージの仕様
```
# 新規作成
新規作成（公開） -> 「質問を作成しました」
新規作成（WIP） -> 「質問をWIPとして保存しました」

# WIP -> 公開
新規WIP保存後の質問画面から画面遷移せず、そのまま更新して公開 -> 「質問を公開しました」
※Railsの処理で出したメッセージをJSで書き変え

WIP保存後の質問画面から一度以上画面遷移して、そのあとに更新して公開 -> 「質問を更新しました」
※JSのみの処理

# 公開 -> WIP
新規公開後の質問画面から画面遷移せず、そのまま更新してWIP -> 「質問をWIPとして保存しました」
※Railsの処理で出したメッセージをJSで書き変え

WIP保存後の質問画面から一度以上画面遷移して、そのあとに更新して公開 -> 「質問を更新しました」
 ※JSのみの処理

# 公開 -> 公開（内容のみ変更）
「質問を更新しました」

# WIP -> WIP（内容のみ変更）
「質問を更新しました」
```

新規作成後に画面遷移せず更新した際のみ、RailsとJSの混合の処理でメッセージを書き換えているのは、下のIssueによるためです。
- https://github.com/fjordllc/bootcamp/issues/6517

> 原因
フラッシュメッージが表示されたままになってしまうのは、保存済みの質問の編集操作はapp/controllers/questions_controller.rbが担っており、ブラウザとしてはページ遷移せずにJavascriptで操作しているためと思われます

> アドホックな対応になりますが、一時的な対応ということで、
「変更時にflashメッセージを直接書き換える」
ということでいきたいと思います。
document.querySelector('#flash').innerHtml = '質問を公開しました。'

> 根本的には「Q&Aの編集ページはSPA的なものじゃなくする（元に戻す）」とかが良いと思っていますが今回はアドホックな対応でお願いします。

## 対応について（案・確認いただきたい点）
このような入り組んだシナリオ分けが起きているのは、新規作成時はRailsのコントローラ・更新時はVueの画面書き換えという2つの異なる手法でフラッシュメッセージを出し分けているからです（上述のIssueで議論されている通り）。

本Issueで、フラッシュメッセージについては全てRails側で処理できるようになります。

- 上記のアドホック的な対応を排除する
- 他の非Vueな実装（ドキュメント・記事・イベント・日報など）を参考にする

これらを念頭に、以下のようなパターン分けがいいかなと考えましたが、いかがでしょうか？

```
# 新規作成
新規作成（公開） -> 「質問を作成しました」
新規作成（WIP） -> 「質問をWIPとして保存しました」

# WIP -> 公開
「質問を更新しました」

# 公開 -> WIP
「質問をWIPとして保存しました」

# 公開 -> 公開（内容のみ変更）
「質問を更新しました」

# WIP -> WIP（内容のみ変更）
「質問を更新しました」
```

#### （参考）他のリソース例
Pages・Articles・Eventsはこの案と同じ。ReportsはWIP以外は「WIPで保存」or 「保存」のみなので、よりシンプル。
```rb
#PagesController

  def notice_message(page, action_name)
    return 'ドキュメントをWIPとして保存しました。' if page.wip?

    case action_name
    when :create
      'ドキュメントを作成しました。'
    when :update
      'ドキュメントを更新しました。'
    end
  end
  
#ArticlesController

  def notice_message(article)
    case params[:action]
    when 'create'
      article.wip? ? '記事をWIPとして保存しました' : '記事を作成しました'
    when 'update'
      article.wip? ? '記事をWIPとして保存しました' : '記事を更新しました'
    end

#EventsController

  def notice_message(event)
    case params[:action]
    when 'create'
      event.wip? ? '特別イベントをWIPとして保存しました。' : '特別イベントを作成しました。'
    when 'update'
      event.wip? ? '特別イベントをWIPとして保存しました。' : '特別イベントを更新しました。'
    end
  end

# ReportsController

  def notice_message(report)
    report.wip? ? '日報をWIPとして保存しました。' : '日報を保存しました。'
  end
```

**Comment by machida** [comment]
@junohm410 提案ありがとうございます！！提案通りで行きたいと思います。reportsだけが同じパターンになっていないのが気になったので、別Issueを作りますー

**Comment by junohm410** [comment]
@machida 
ありがとうございます！それでは、本IssueのQuestionについては提案させていただいた内容で進めさせていただきます🙏
引き続きよろしくお願いいたします。

**Comment by junohm410** [comment]
@machida 
すみません、めちゃくちゃ細かいのですが一点だけ提案内容に誤りがありました🙇‍♂️
提案したい形は以下です。
```
# 新規作成
新規作成（公開） -> 「質問を作成しました」
新規作成（WIP） -> 「質問をWIPとして保存しました」

# WIP -> 公開
「質問を更新しました」

# 公開 -> WIP
「質問をWIPとして保存しました」

# 公開 -> 公開（内容のみ変更）
「質問を更新しました」

# WIP -> WIP（内容のみ変更）
×「質問を更新しました」
○「質問をWIPとして保存しました」
```
WIP -> WIP のシナリオに誤りがありました。
これが他のパターン（記事・イベント・ドキュメント）と同じ形です。
他パターンと合わせる形でOKというイメージだと思うので大丈夫だと思いますが、念の為これでよいかご確認いただいてもいいでしょうか？
何度も申し訳ないです🙏よろしくお願いします。

**Comment by machida** [comment]
@junohm410 なるほど！はい、WIPからWIPも他と同じでお願いしますー WIPという文字があった方が安心感がありそうです。

**Comment by junohm410** [comment]
ありがとうございます！
はい、他のパターン通りですが、submit後がWIPのときは以前がどのような形であれ、そのように表示された方がユーザとしても安心だと思います。
それでは、進めさせていただきます🙏

**Comment by junohm410** [comment]
@machida @komagata
お疲れ様です。本Issueの細部の進め方で、別件でもう一点ご確認いただきたいことがあります🙏
## 確認いただきたいこと
質問の作成・更新時の、「関連プラクティスを選択しない場合のプルダウンの選択肢」について伺いたいことがあります。
以下の「問題」のセクションで、進め方の提案とその理由を提示しております。

> - 質問追加・編集画面の両方で、「プラクティス選択なし」という選択肢を用意する（今の編集画面ベース）

そちらでよいかご確認をお願いしたいです。

## 関連プラクティスを選択しない場合のプルダウンの選択肢について
既存の仕様では、新規追加時と更新時で上についての扱いが異なっています。

### 既存の仕様
#### 編集画面
既存のVue上の編集画面では、「プラクティス選択なし」という選択肢を選ぶことができます。
（これを選択すると、`practice_id`が`nil`で質問が登録される）

![image](https://github.com/fjordllc/bootcamp/assets/128765400/9d4cb65d-15c1-4ec9-83d2-726dc02d1b4f)

#### 新規追加画面
既存のRailsのviewの新規追加画面では、「プラクティス選択なし」という選択肢を選ぶことができません。

![image](https://github.com/fjordllc/bootcamp/assets/128765400/eadcbf74-1f59-4f39-918e-91c70a05ae4a)

セットされたプラクティスの右端のバツボタンを押すと、選択なし状態にすることができます。

![gxkceqYoc4](https://github.com/fjordllc/bootcamp/assets/128765400/98d06572-e09f-4f60-8ea4-176a28d040d7)

編集画面で「プラクティス選択なし」と選択できるのは、Vue側でそのように実装されているからです。

https://github.com/fjordllc/bootcamp/blob/6dcc83786e9af3b2d965bd14360c382fa396e6d7/app/javascript/components/question-edit.vue#L130-L138

- https://github.com/fjordllc/bootcamp/pull/5160
こちらのPRで追加で実装されたようです。

### 問題
非Vue化により、編集時も新規追加時と同じ`questions/_form.html.slim`パーシャルを使うようになります。
現状のように、「編集時のみ『プラクティス選択なし』という選択肢を用意する」ということもできますが、新規追加時と編集時でUIが異なるのは少し変な気がします。

- 上記のPRで、編集画面に「プラクティス選択なし」という選択肢が後から機能として追加されていること
- bootcampアプリとしては、プラクティスに紐づかない質問も許容していること
- ↑を勘案すると、選択肢として「プラクティス選択なし」が新規画面にもあった方がユーザーにとって優しいと思われること
- 同じく単一の紐づくプラクティス選べる`pages`(Docs)でも、「関連プラクティスを指定しない」という選択肢があること

以上のことを勘案すると、

- 質問追加・編集画面の両方で、「プラクティス選択なし」という選択肢を用意する（今の編集画面ベース）

でスタイルを統一したほうがよいかなと考えますが、いかがでしょうか？

また、いったん現状の状態を維持し、別Issueでこのズレを直す方がいいなどあれば、ご教示いただけると幸いです。
よろしくお願いいたします🙏

**Comment by machida** [comment]
@junohm410 
ありがとうございます！！
プラクティス選択なしを選択できるようにお願いしたいです🙏
今もそうあるべきだと思うのですが、多分今使っているラブラリの関係か何かでそのようにするのが大変で現状のようになってるのかもしれないです。

**Comment by junohm410** [comment]
@machida 
早々にありがとうございます！承知しました。
実装を考えてみたのですが、Railsのフォームヘルパーのオプションで、選択肢が空（値が`nil`）の状態とその場合の文言を設定することができます。
今のDocがそのような形で実装されています。

https://github.com/fjordllc/bootcamp/blob/6dcc83786e9af3b2d965bd14360c382fa396e6d7/app/views/pages/_form.html.slim#L9-L10

質問においても試しに修正し、画面で触ったりテストを回す感じでは大丈夫そうなイメージです。

ただ質問に関しては、Docと異なり個別のプラクティスの「質問する」ボタンから`/questions/new?practice_id=...`のような新規画面に飛べて、その場合は飛んできたプラクティスが自動でセットされる、のような機能があります。
新規時と編集時で条件分けしつつ、選択なし状態も選択できるようにするのに、Docのそのままでは動かないので、その辺りを調整します。

ライブラリ周りで困難があったなどあれば、また別途相談させてもらいます🙏
引き続きよろしくおねがいいたします🙏

**Comment by junohm410** [comment]
@machida @komagata 
さっそくすみません🙏上記の対応の中で、一点だけ問題というか、**既存の**バグを発見しました。
本Issueで対応すべきか、別Issueにすべきかご確認いただきたいです。

## バグの詳細
- プラクティスを選択しない状態かつ、他のユーザーにメンションをした状態でQ&Aを新規作成・更新するとエラーになる。

![y77kqp8MAC](https://github.com/fjordllc/bootcamp/assets/128765400/1f8a4696-b7fc-4b0b-8fe1-144f6b421a71)

## 原因
Q&Aのメンション通知のタイトルは、プラクティスのタイトルが使われる。正常時↓

![image](https://github.com/fjordllc/bootcamp/assets/128765400/4ed7ce02-7c50-4d24-adb5-aa193342571e)

プラクティスが選択されていない時、下のメンション通知タイトルを生成するメソッドにおいて、`(question.)practie[:title]`の`practice`が`nil`になるためエラーになる。

https://github.com/fjordllc/bootcamp/blob/6dcc83786e9af3b2d965bd14360c382fa396e6d7/app/models/concerns/mentioner.rb#L14-L27

## 考えられるFIX方法
プラクティスが選択されてない時は、「プラクティス選択なし」という文言を使う。イメージ↓

![image](https://github.com/fjordllc/bootcamp/assets/128765400/dba9fb16-a810-44e8-a34d-c4b66efa73eb)

```rb
      practice_title = practice ? practice[:title] : 'プラクティス選択なし'
      "#{user.login_name}さんのQ&A「#{practice_title}」"
```

## 懸念
これは今の本番でも再現するバグです。
（プラクティス選択なしかつメンションするというケースがレアなので出てこなかったのかもです）
厳密にはこのIssueの変更で起きたバグではないですが、別Issueにしたほうがいいでしょうか？

その場合、「プラクティスを選択せずしない状態で質問を作りメンションを確認する」という1件のテストが通らなくなります（それでこのバグに気づきました）。
一時的な処置ではありますが、そのテストではプラクティスを選択する形に修正する必要がありそうです。

何度も申し訳ないです。ご確認のほど、よろしくお願いいたします🙏

**Comment by machida** [comment]
@junohm410 バグの発見ありがとうございます！！
可能であれば一緒に対応をお願いしたいです。
このバグ対応でリリースが大きく遅れる場合は別Issueでお願いしたいです🙏

**Comment by junohm410** [comment]
@machida 
ありがとうございます🙏バグ対応自体は上記のFIX方法で問題なさそうですので（他のテストも通りました）、本Issue内で進めるようにいたします。
また新たな問題が出てきたら、すみませんが相談させてください🙇‍♂️
引き続きよろしくお願いいたします！

**Comment by junohm410** [comment]
本番環境でテスト質問を作成し、以下のことを確認しました。

- 編集フォームに画面遷移すること（＝Vueでの実装でなくなったこと）
- 以下のコメントの通りのフラッシュメッセージが表示されること
    - https://github.com/fjordllc/bootcamp/issues/7356#issuecomment-1966035020
- 質問の作成・更新時のフォームで「プラクティス選択なし」が選択できること
- プラクティスを選択しない状態かつ、他のユーザーにメンションをした状態でQ&Aを保存してもエラーにならず、「プラクティス選択なし」という文言が使われてメンション通知が飛ぶこと
    - https://github.com/fjordllc/bootcamp/issues/7356#issuecomment-1973369119

（本番環境で他のメンバーに上の条件でメンションした際に飛んだ通知のスクショです↓）
![image](https://github.com/fjordllc/bootcamp/assets/128765400/222fb733-b1b0-4895-a67f-0b7f92aa87b1)

変更内容が問題なく動作していることを確認しましたので、本IssueはCloseいたします。
