### ISSUE TITLE
Fjord Choiceでjunohm410さんのポイントが食い違っている問題を修正する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7357]
https://github.com/fjordllc/bootcamp/pulls?q=is%3Apr+assignee%3Ajunohm410+-label%3Arelease+

↑食い違っている。

まずはバグとしてIssue登録をして、その後にPRの作成をお願いします。
PRはあちらのプロジェクトにお願いします。PRができたら僕の方でもSakiさんと連絡をとりつつ対応します。

[Saki\-htr/fjord\-choice: フィヨルドブートキャンプのチーム開発の状況を見える化するアプリ](https://github.com/Saki-htr/fjord-choice)

**Comment by SuzukaHori** [comment]
質問タイムで聞いたことのまとめ：
- 質問
バグの再現ができず。原因の特定よりも、「生じてしまったズレを修正する方法を考える」方向で進めても良いか。

- 答え
  - 「ズレの解消」についてはDBで直接操作すればいいので、こちらに重きは置かない。原因究明と再発予防に重きを置く。
  - ある程度調べたなら、Issueを立てるのが良い。
  - どのような操作が行われているか、ログファイルなどにログを残すようにすると、原因究明につながりそう。

**Comment by SuzukaHori** [comment]
チーム開発ミーティングで確認したことのまとめ：
### 状況
- bootcampのリポジトリが操作されると、GItHubワークフローが動きcurlコマンドが実行されるが、デタラメなURLでワークフローを作動させても「成功」と出てしまう。
![image](https://github.com/fjordllc/bootcamp/assets/129706209/faa0841e-8f9d-4881-a5c4-592373f3892c)
- ポイントが反映されていないワークフローのログを見ると、エラーは出ておらず成功状態だが、他のものより時間がかかっている。（10秒）
https://github.com/fjordllc/bootcamp/actions/runs/7141195745/job/19448013738 
- 同程度時間がかかっているワークフローの中に、500エラーが出ているものがあった。
https://github.com/fjordllc/bootcamp/actions/runs/7919447086/job/21620240383

### 質問したこと
以下の方針で進めて良いか。
- bootcamp側でcurlが失敗した時、GitHub WorkFlowの失敗とみなされるようにWorkFlowのコードを修正する。
- Fjord Choice側でバグが発生した&再現しなかった旨をIssueとして報告。
原因究明のため、ログを記録するPRを作る。

### 答え
- 上の方針でOK。
- ログの記録方法は、ファイルには記録せず、標準出力を使うとデプロイ先で確認できる。環境変数`RAILS_LOG_TO_STDOUT`を使うと設定できる。

**Comment by SuzukaHori** [comment]
（先週の）質問タイムで確認したことのメモ：

### bootcamp側
  - 変更確認方法はこれでいいか。
    - 今まで通り（Issue・レビュー依頼・Approveの）GitHub Actionが動くか確認する。
PRから修正後のコードでGitHub Actionsが実行されるので、このPRで行われているGitHub Actionsのログを確認をする。
     - GitHub Action失敗時に、GitHub Actionが「失敗」のステータスになるか確認する。
マージされて失敗が発生するまで確認できないので、意図的に失敗を発生させた検証用リポジトリのログを見てもらう。

   →この確認方法でOK。
  - レビューの方法は通常通り、受講生→komagataさんで問題ない？

   → 直接komagataさんでOK。

### Fjord Choice側
  - すでに 
config/environment/production.rbには環境変数：RAILS_LOG_TO_STDOUTが存在した場合にログを標準出力へアウトプットする設定がすでに存在するように見える。
```ruby
  if ENV["RAILS_LOG_TO_STDOUT"].present?
    logger           = ActiveSupport::Logger.new(STDOUT)
    logger.formatter = config.log_formatter
    config.logger    = ActiveSupport::TaggedLogging.new(logger)
  end
```
ログを見ると、リクエストとステータスコードが確認できるように見えるが、他に標準出力に出すべきログはあるか？
![スクリーンショット 2024-03-04 15.38.43.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXRsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cad9ac04b7f49c101c8db57bca1d5731724848d/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202024-03-04%2015.38.43.png)

→Railsの標準のログで確認できるので、Fjord Choice側での対応は今のところなしで良い。

**Comment by SuzukaHori** [comment]
本番環境での動作確認についてメモ：

3/13：スクラムチームにポイントのズレが発生した場合、報告をしてもらうようお願いした。

報告があったらActionsの履歴を確認する。
  - 履歴のステータスが「失敗」だった場合
  PRの意図通りに動いているのでOK。Issueをクローズする。
  - 履歴のステータスが「成功」だった場合
   PRの意図通りに動いていないので、本番環境のFjord Choiceのログを確認してもらう。
    - Fjord Choiceのログに該当Issueが存在している場合
    Fjord Choice側の問題なので、そちらの修正を試みる。
    - Fjord Choiceのログに該当Issueが存在していない場合
    curlコマンドでエラーが返ってきていないかつ、GItHubが「Actionが正常に動いている」と判断している状態。この場合、修正方法がわからないので相談する。
