### ISSUE TITLE
ユーザ一覧の期生別ページのそれぞれの期に人数を表示したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7364]
<img width="1337" alt="貼り付けた画像_2024_02_14_10_36" src="https://github.com/fjordllc/bootcamp/assets/168265/36fa5989-ed67-4328-b867-d4915bb1bb16">

現役生、卒業生、退会者の人数を、メンター or 管理者でログインしたときだけ表示したい。

**Comment by a-terumoto-gs** [comment]
@komagata 
お疲れ様です。
こちらのissueの言葉の定義について確認させて下さい。
「現役生」という言葉の定義なのですが、コードを確認していたところ2種類あるのでは？と思いいたりました。
1.個人でフィヨルドに取り組まれている方のユーザーページに表示される「現役生」という属性
2.1の意味の「現役生」と企業の「研修生」を合わせた今現在フィヨルドに取り組んでいる人という意味での「現役生」という属性

ユーザー一覧ページでの、すべてタグの現役生タグでは2の属性のユーザーが表示されるようになっていると思います。
今回のissueはおなじユーザー一覧ページの期生別タグの画面の変更であるため、その仕様に合わせて、後者の2の解釈での実装と考えたのですが、この認識で間違っていないでしょうか？

もし1の意味での現役生の実装であればその旨お伝えいただけると助かります。
よろしくお願いいたします。

**Comment by komagata** [comment]
@a-terumoto-gs 

> 今回のissueはおなじユーザー一覧ページの期生別タグの画面の変更であるため、その仕様に合わせて、後者の2の解釈での実装と考えたのですが、この認識で間違っていないでしょうか？

はい。そちらでお願いします。

**Comment by a-terumoto-gs** [comment]
@komagata @machida 
おつかれさまです！
現在こちらのissueについて、ユーザー一覧ページの期生別ページの`全員`のタブのみに各属性の人数表示をする仕様で実装を進めています。
特に深く考えずにこの仕様にしてしまっていたのですが、、期生別ページの他のタブにも人数表示をするべきかも？と思いまして…
テストを書いていて、この辺の仕様について詰めていなかったことに気づきましたので、コメントさせていただきました。
確認よろしくお願いいたしますm(__)m

**Comment by machida** [comment]
@a-terumoto-gs 
質問ありがとうございます！
今回のIssueは全員に留めておいて、別のタブは別のIssueで対応しようと思いますー

**Comment by a-terumoto-gs** [comment]
@komagata @machida 
おつかれさまです！
こちらのissueでの変更を加えたファイルについてなのですが、
他のissueで該当ファイルが削除されてしまっており、mainにマージ済みの状態になっていることに気づきました。
どう対処したらよいでしょうか？
確認よろしくお願いいたしますm(__)

該当ファイルを削除しているissue
- https://github.com/fjordllc/bootcamp/issues/7403

**Comment by a-terumoto-gs** [comment]
@komagata  @machida 
本番環境での動作確認をお願いしたいです！

**Comment by machida** [comment]
@a-terumoto-gs 本番で確認しました🙆

**Comment by a-terumoto-gs** [comment]
本番での動作確認できたのでcloseします！
