### ISSUE TITLE
ドキュメント作成フォームのタイトルに説明文を追加したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7367]
`/pages/new` このページに表示されている form の部分。

<img width="1242" alt="貼り付けた画像_2024_02_14_15_58" src="https://github.com/fjordllc/bootcamp/assets/168265/f9ef22a2-6433-4d85-8377-87dd6fa4d812">

この部分に、以下の文章を挿入する。

```
どんな内容が書かれているドキュメントかを予想できるタイトルを付けましょう。
また、それを探している人が検索するであろうワードを含めることをいしきしてください。
```

**Comment by hirano-vm4** [comment]
@machida @komagata 

お疲れ様です！
お忙しいところ、申し訳ありません。このIssueの確認と報告になります🙏

## 文言についての報告
このIssueはドキュメント作成フォームの「関連プラクティス」というタイトルのフォーム下に以下の説明書きを入れるIssueです。

```
どんな内容が書かれているドキュメントかを予想できるタイトルを付けましょう。
また、それを探している人が検索するであろうワードを含めることをいしきしてください。
```

この文言の中の`いしき`は文脈的に間違いなく`意識`であっていると思うので修正していますが問題ないでしょうか？🙏

勝手にこちらの認識だけで変更した場合、今回の場合は問題なくとも、別のIssueなどでチームの認識がずれてしまうなどの恐れがあると思い、勝手な変更はせず、念の為の報告になります😊


## デザインについて
デザインは町田さんにご相談かと思いますが、同ページにスラッグ設定のフォーム下に説明書きがあり、その文言にCSSが適用されています(クラス名は`.a-form-help`)。

**参考箇所**
<img width="399" alt="スクリーンショット 2024-03-01 11 52 01" src="https://github.com/fjordllc/bootcamp/assets/105143414/2a1ea4b7-8063-4bad-87c7-7673450a77de">

こちらもクラス名同様フォームの説明分になると思うので、
この文言にも仮として同クラスのCSSを適用させてあります。

**提案修正**
<img width="772" alt="スクリーンショット 2024-03-01 11 54 52" src="https://github.com/fjordllc/bootcamp/assets/105143414/cf164a15-7057-4be9-b000-8069eab47349">

デザイン的には問題なさそうでしょうか？
問題なければ町田さんの手間も減ると思っての提案・相談になります🙏

デザインには触れず、「勝手にデザインいじらない」「提案なしであくまで仕様通り変更し、デザインは町田さんに相談する」などルールなどがありましたらご指導ください！

問題なければこのデザインを適用させた上で、PRを作成いたします！

まだ温度感がわかっていない部分もあるかと思いますので、確認しました🙇‍♂️

**Comment by machida** [comment]
@hirano-vm4 デザインは入れられたら入れてもらえるほうが助かりますー
なので、今回は入れた状態でPRをお願いします🙏
Issueによっては大幅にデザインも変更するものも出てくるのですが、その場合は、事前に作業が終わったら machida にメンションするように伝えているので、そういうIssueのときはそのようにお願いします🙏

**Comment by hirano-vm4** [comment]
@machida 
ありがとうございます🙏では提案させていただいた方向性で進めたいと思います！

>Issueによっては大幅にデザインも変更するものも出てくるのですが、その場合は、事前に作業が終わったら machida にメンションするように伝えているので、そういうIssueのときはそのようにお願いします🙏

こちらの件についても承知いたしました💪

**Comment by hirano-vm4** [comment]
@komagata  @machida 

お疲れ様です！本番環境にこちらmergeされましたが、管理者権限でのみ確認ができる部分になります🙏いつでも大丈夫ですので、確認をお願いしてもよろしいでしょうか？🙇‍♂️

**Comment by komagata** [comment]
@hirano-vm4 本番環境で確認しました。OKでした～！

**Comment by hirano-vm4** [comment]
@komagata お忙しいところ、ありがとうございました🙏

**Comment by hirano-vm4** [comment]
こちら本番環境で確認がとれたため、closeします。
