### ISSUE TITLE
お知らせ作成フォームのタイトル部分に説明文を追加したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7368]
`/announcements/new` に表示されているフォーム。

<img width="1410" alt="貼り付けた画像_2024_02_14_16_13" src="https://github.com/fjordllc/bootcamp/assets/168265/443fa4df-5e24-4b2b-9f3c-401385aea852">

この部分に、以下の文章を追加したい。

```
お知らせの内容本文がタイトルから予想できる、具体的なタイトルを付けましょう。
悪い例: フィヨブーハウス
良い例: RubyKaigi 2024 フィヨブーハウス宿泊希望者申し込みを開始しました
```

**Comment by mousu-a** [comment]
@machida 
お疲れ様です！
こちら少ないですがデザインをお願いしたいです🙏

`app/views/announcements/_form.html.slim`の12〜17行目になります。
お手すきの際で構いませんのでよろしくお願いします🙇

**Comment by mousu-a** [comment]
本番環境で動作していることを確認しましたので、本IssueはCloseいたします。
