### ISSUE TITLE
お試し延長一覧ページのタイトルのマークアップ変更。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7369]
管理者でログイン。

`/admin/campaigns` にアクセス。

<img width="685" alt="貼り付けた画像_2024_02_14_16_22" src="https://github.com/fjordllc/bootcamp/assets/168265/29d4cb26-c979-4350-aad2-1f5fb2586fdf">

<img width="312" alt="貼り付けた画像_2024_02_14_16_22" src="https://github.com/fjordllc/bootcamp/assets/168265/3fae3931-0762-4ef2-8dcf-d138437b3fd3">

これを h1 に変更する。

**Comment by komagata** [comment]
@hirano-vm4 本番環境で確認しました。OKでした～！

**Comment by hirano-vm4** [comment]
@komagata お忙しいところ、ありがとうございました🙏

**Comment by hirano-vm4** [comment]
こちら本番環境で確認がとれたため、closeします。
