### ISSUE TITLE
管理ページトップのタイトルのマークアップ変更。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7370]
管理者でログイン。

`/admin/` にアクセス。

<img width="579" alt="貼り付けた画像_2024_02_14_16_24" src="https://github.com/fjordllc/bootcamp/assets/168265/01695c8b-368d-4aeb-96a8-aeac1d3aa586">

<img width="312" alt="貼り付けた画像_2024_02_14_16_22" src="https://github.com/fjordllc/bootcamp/assets/168265/3fae3931-0762-4ef2-8dcf-d138437b3fd3">

これを h1 に変更する。

**Comment by unikounio** [comment]
@komagata さん
@machida さん

お疲れ様です。
本Issueの作業内容がリリースされたので本番環境での確認をしたいのですが、管理者権限が必要なため、お手すきの際にご確認をお願いできますでしょうか🙏
よろしくお願いいたします。

**Comment by komagata** [comment]
@unikounio 本番環境で確認しました〜

**Comment by unikounio** [comment]
本番環境での確認が完了したため、本IssueはCloseさせていただきます。
