### ISSUE TITLE
管理ページユーザー一覧のタイトルのマークアップ変更。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7371]
管理者でログイン。

`/admin/users` にアクセス。

<img width="574" alt="貼り付けた画像_2024_02_14_16_27" src="https://github.com/fjordllc/bootcamp/assets/168265/421b457b-c433-4f59-af78-38e1b8679333">

<img width="312" alt="貼り付けた画像_2024_02_14_16_22" src="https://github.com/fjordllc/bootcamp/assets/168265/3fae3931-0762-4ef2-8dcf-d138437b3fd3">

これを h1 に変更する。

**Comment by machida** [comment]
@yocchan-git こちらのIssueをお願いします:pray:

**Comment by yocchan-git** [comment]
ありがとうございます！

**Comment by yocchan-git** [comment]
@komagata さん
@machida さん

こちらなのですが、本番環境で確認する術がなくて...
よろしければ本番で確認をお願いしたいのですがよろしいでしょうか？🙏

## 確認方法
1. 管理者としてログインしていただく
1. https://bootcamp.fjord.jp/admin/users にアクセスする
2. 検証で「管理ページ」のタグが`h1`なのを確認する(画像のような感じです)
3. このissueにコメントいただく

[![Image from Gyazo](https://i.gyazo.com/955633c610f1cc937578bf85c36d5905.png)](https://gyazo.com/955633c610f1cc937578bf85c36d5905)

何かありましたらぜひコメントください。お手隙でよろしくお願いいたします🙇‍♂️

**Comment by komagata** [comment]
@yocchan-git こちら本番環境で確認しました〜

**Comment by yocchan-git** [comment]
ありがとうございます！
またよろしくお願いいたします🙇‍♂️
