### ISSUE TITLE
提出物を更新した時の文面に句読点を追加したい

### ISSUE THREAD

**Issue by Kassy0220** [fjordllc/bootcamp#7374]
## 機能の説明

現在、ユーザーが提出物を再提出すると、`⚪︎⚪︎さんの「XXX」の提出物が更新されました`という通知がメンターやアドバイザーに飛ぶ様になっています。

<img width="240" alt="_development__ダッシュボード___FBC" src="https://github.com/fjordllc/bootcamp/assets/79003082/5427334b-e81c-412f-b0bd-3e32f34e0cb3">

この通知の文言の最後に句点を追加して、`⚪︎⚪︎さんの「XXX」の提出物が更新されました。`としたいです。

## 何故この機能が必要なのか

他の通知の文言は全て最後に句点やエクスクラメーションマークがついており、統一性を持たせたいため。

**Comment by mousu-a** [comment]
[github](@:https://github.com)

**Comment by mousu-a** [comment]
[bing](@:https://cn.bing.com)

**Comment by mousu-a** [comment]
@komagata 

お疲れ様です！お手数をお掛けいたしますが本issueの本番環境でのご確認をお願いしたいです🙏

**Comment by mousu-a** [comment]
ありがとうございます！🙏🙏

**Comment by mousu-a** [comment]
本番環境で動作していることを確認しましたので、本IssueはCloseいたします！
