### ISSUE TITLE
ポートフォリオのサムネイル画像を 1200px ✕ 630px にシステム側で強制したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7383]
ブログ記事のサムネイル画像は 1200px ✕ 630px にシステム側で強制されている。
https://github.com/fjordllc/bootcamp/issues/6415

それをポートフォリオのサムネイル画像にも適用したい。
（このページ `/works/new` でアップロードする画像）

<img width="956" alt="貼り付けた画像_2024_02_15_14_09" src="https://github.com/fjordllc/bootcamp/assets/168265/bdd4014e-cc73-4be0-991d-548a0d08e4f9">

**Comment by kyokucho1989** [comment]
参考

#7330

**Comment by kyokucho1989** [comment]
本番環境で動作確認ができましたのでcloseします。
