### ISSUE TITLE
入会時に届く welcome メールの bcc に info@lokka.jp を入れたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7393]
入会すると welcome メールが届くようになっている。

`/bootcamp/app/mailers/user_mailer.rb`

<img width="673" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/7ae9ee91-05c9-418b-83f1-8d47f1b74515">

これを管理者も受け取りたいので、メールの bcc に info@lokka.jp を入れたい。

**Comment by komagata** [comment]
@unikounio development環境での確認のお話でしょうか。
重ならない適当なメールアドレスで登録するのはダメでしょうか？

**Comment by unikounio** [comment]
@komagata さん
ご回答ありがとうございます🙏
> development環境での確認のお話でしょうか。

おっしゃる通りです。
新しいメールアドレスで登録するたび、プロジェクト全体で登録できないメールアドレスが増えていくのかなと思ったので確認させていただきました。
ご回答いただいた「適当なメールアドレスで登録する方法」で進めてみようと思います！

**Comment by komagata** [comment]
@unikounio 

> 新しいメールアドレスで登録するたび、プロジェクト全体で登録できないメールアドレスが増えていくのかなと思ったので確認させていただきました。

今まで過去に１回ぐらいはテスト環境のStripeのデータをクリアしたことがありますが、２〜３年の一度ぐらいのことなのでお気になさらずで大丈夫です。（クリアするは僕の方でやります）

**Comment by unikounio** [comment]
@komagata さん
ありがとうございます🙏
とてもスッキリしました😄
今後作業するIssueについてもStripeのデータについては触れないようにしようと思います！

**Comment by unikounio** [comment]
@komagata さん
お疲れ様です。
本Issueに関するコードが本番環境にデプロイされましたので、今後入会される方がいらっしゃった際に
1. `info@lokka.jp`にwelcomeメールが届いているか
2. 1のメールがBCCで送られているか

の2点の確認をお願いできますでしょうか🙏

**Comment by komagata** [comment]
@unikounio 本番環境で確認させていただきました。OKでした～👌

**Comment by unikounio** [comment]
@komagata さん
ありがとうございますー！🙏✨
本Issueは完了したものとしてCloseさせていただきます。
