### ISSUE TITLE
ユーザー検索で休会・退会ユーザーも引っかかるようにする

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7396]

**Comment by kurumadaisuke** [comment]
@komagata 

ユーザー検索ですが、右上の検索から「ユーザー」を指定した場合に休会・退会ユーザーが引っかかるようにすればいいんでしょうか🙏？
<img width="348" alt="スクリーンショット 2024-02-19 21 35 09" src="https://github.com/fjordllc/bootcamp/assets/57862327/6dfd0ab9-1419-445f-b8fd-653089ed773a">

もしくは、メンターログイン時の「全員」のカテゴリーから休会・退会ユーザーが引っかかるようにすればいいんでしょうか🙏？
<img width="1120" alt="スクリーンショット 2024-02-19 21 33 19" src="https://github.com/fjordllc/bootcamp/assets/57862327/68af4b3c-d588-4d32-9600-c9ea1ead73ff">

**Comment by komagata** [comment]
@kurumadaisuke 調べてみてください〜。
両方とも引っかかるようにしたいので引っ掛からなかったら両方修正お願いします。

**Comment by kurumadaisuke** [comment]
@komagata 
昨日調べてみた際には
右上の検索からは
休会ユーザー ⭕️（引っかかる）
退会ユーザー ❌（引っかからない）

メンターの検索からは
休会ユーザー ❌（引っかからない）
退会ユーザー ❌（引っかからない）

っとなっていたため両方対応いたします🙏🙏

**Comment by Judeeeee** [comment]
@komagata @machida 
ユーザー一覧ページの絞り込みからの検索ですが、こちら本番環境の動作確認に管理者・メンター権限が必要なため(受講生だと全員指定の検索ができない)、お手数ですがご確認いただけないでしょうか？🙇

### ユーザー一覧の絞り込みからの検索
### 修正後:
<img width="982" alt="スクリーンショット 2024-07-08 19 09 35" src="https://github.com/fjordllc/bootcamp/assets/43412616/0babc363-761a-4a80-ab3f-87e960b54bbe">
<img width="925" alt="スクリーンショット 2024-07-08 19 09 11" src="https://github.com/fjordllc/bootcamp/assets/43412616/0b5df0d7-746d-4189-9957-e231b54ce7b5">

**Comment by Judeeeee** [comment]
本番環境で動作確認したのでcloseします。
