### ISSUE TITLE
ユーザー一覧を非vue化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7403]
vueを撤廃して普通のページ（非SPA）にしたい。
kaminariでページングすることになると思う。

将来的にはこれを元にHotwire化する予定。

**Comment by yocchan-git** [comment]
@komagata さん
@machida さん

実装について相談があります！🙇‍♂️
ユーザ一覧の非vue化について、JSを使用してもよろしかったでしょうか？

というのも、フォローの実装について現状は非同期で処理をしているのですが、
JSのコードを使わないとページの先頭に戻ってしまい...😅

[![Image from Gyazo](https://i.gyazo.com/4100fe9459edd572ea8980ed9f814ce2.gif)](https://gyazo.com/4100fe9459edd572ea8980ed9f814ce2)

こういった場合JSを使って実装してもよろしかったでしょうか？
それとも、リダイレクトする感じにした方がいいでしょうか？🤔

お手隙でご回答いただけますと嬉しいです🙏

**Comment by komagata** [comment]
@yocchan-git バニラJSは使用しても大丈夫です〜

**Comment by yocchan-git** [comment]
ありがとうございます！
では、その方向性で行かせて頂きます💪

**Comment by yocchan-git** [comment]
@komagata さん
@machida さん

本番環境で確認いただいてもよろしいでしょうか？
具体的には、相談部屋一覧にアクセスして「[絞り込み](https://gyazo.com/b902c2a648f56e21e1d3b67a508189d8)」を確認していただきたいです。
- [ ] Enterを押して検索結果が表示されること(半角文字なら3文字以上・全角なら2文字以上で検索されます)

[こちらのコメント](https://github.com/fjordllc/bootcamp/issues/7404#issuecomment-2002650920)と同じ内容です！
よろしくお願いいたします🙏

**Comment by machida** [comment]
@yocchan-git @komagata 

> 本番環境で確認いただいてもよろしいでしょうか？
> 具体的には、相談部屋一覧にアクセスして「[絞り込み](https://gyazo.com/b902c2a648f56e21e1d3b67a508189d8)」を確認していただきたいです。

本番で確認しました👍

---

相談部屋の絞り込みは確認できたのですが、ユーザー一覧のページでユーザーアイコンに role に合わせた border の枠が付いていたのがなくなってしまっていました。

**Comment by yocchan-git** [comment]
@machida さん

指摘ありがとうございます！ちょっと確認します

**Comment by yocchan-git** [comment]
@machida さん
cc @komagata さん

1点まだ不具合がありまして、デザインなのでよろしければ対応いただけますと嬉しいです
対応して欲しい画面はユーザー一覧画面(`/users`)になります。

具体的には、一番下までスクロールした時に、ページネーションと「気になるユーザーをフォローしてみよう」の案内の下にフォローカードが来てしまうことです。
[![Image from Gyazo](https://i.gyazo.com/04aefe3c85c23a867fb8bb9f7276c84b.png)](https://gyazo.com/04aefe3c85c23a867fb8bb9f7276c84b)

お手数ですが、一番上に表示されるようにしていただけますでしょうか？

またページネーションがない場合(例えばフォロー一覧など`/users?target=followings`)はフォローしないの選択が表示されないのも修正いただけますと嬉しいです。

[![Image from Gyazo](https://i.gyazo.com/e9714e311ad737d3001c9af5b37ad109.png)](https://gyazo.com/e9714e311ad737d3001c9af5b37ad109)

**Comment by machida** [comment]
おお、下とのかぶりは未確認でした！対応しますー

**Comment by yocchan-git** [comment]
本番環境の動作確認OKでした！
Closeします👍

@machida さん
[こちら](https://github.com/fjordllc/bootcamp/issues/7403#issuecomment-2057949011)のお早い対応ありがとうございました🙏
