### ISSUE TITLE
相談部屋一覧を非vue化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7404]
下記の二つを非vue化したい。

- https://bootcamp.fjord.jp/talks
- https://bootcamp.fjord.jp/talks/action_uncompleted

JSを使わず普通のページ（kaminariとかを使ってページング）にしたい。
将来的にこちらを元にHotwire化するため。

**Comment by a-kuroki-gs** [comment]
@komagata @machida
お疲れ様です。
こちらのIssueの本番環境での動作確認をお願いしたいです。
大きな変更ではありませんが、
キーワード検索を行う際に、Enterを押下する必要がある点が変更となっています。
(なお、以前の仕様と同じように、半角英数字・`_`・`-`で構成されたものは3文字以上、それ以外は2文字以上で検索が行われます。)

よろしくお願いいたします。

**Comment by a-kuroki-gs** [comment]
@machida 
確認いただきありがとうございました～🙌
