### ISSUE TITLE
ニコニコカレンダーを非vue化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7406]
JSを使わず普通のページ（kaminariとかを使ってページング）にしたい。
将来的にこちらを元にHotwire化するため。

**Comment by reckyy** [comment]
@komagata @machida 
お疲れ様です。
実装の方針について、一点お伺いしたいです。
## 質問したいこと
現状のニコニコカレンダーURLの仕様は保持した方がいいか。

### 現状の仕様
現状はニコニコカレンダーの月の移動を実施すると、`https://bootcamp.fjord.jp/niconico_calendar=2024-01` のように現在表示している年月を保持しています。

### 質問の背景
今回非Vue化に伴い、paramsをcontrollerで受け取り表示する月を判断する仕様に変更したため、URLが
`/?year=2024&month=01/` になっています。
途中、URLが関係するテストが`test/system/home_test.rb`に複数あることに気づきました。（URLが一致しないので、テストは落ちます。）
例えば以下のようなテストです。
https://github.com/fjordllc/bootcamp/blob/d57bb4cdc3b45c577c21f651d6b51fe85df3f9ce/test/system/home_test.rb#L134-L137

対応方法として、
- テストを変える
- URLを変える

を考えました。ですが、以下のPRを拝見しました。
- https://github.com/fjordllc/bootcamp/pull/3112
- https://github.com/fjordllc/bootcamp/issues/2982

こちらの議論の中で、「将来イベントカレンダーが実装されるかもしれないから、パラメータ名は`year`と`month`で問題ないが、ニコニコカレンダーが関わっているとわかるURLがいい。」とありました。
ただ二年経過した今、イベントカレンダーは実装されていないため考慮の必要性が未だ変わりないか、判断がつきませんでした。
また、URLを現状の仕様に合わせるとなると、JSを用いることになります。
上記の事柄を含め、

- テストを変える
- URLを変える

のどちらで対応すべきか、ご教示いただければ幸いです。
よろしくお願いいたします。

**Comment by komagata** [comment]
@reckyy 

> 現状のニコニコカレンダーURLの仕様は保持した方がいいか。

質問に答えるために必要な前提情報に気になるところがあるのでこちらから質問させてください。

> 現状はニコニコカレンダーの月の移動を実施すると、https://bootcamp.fjord.jp/niconico_calendar=2024-01 のように現在表示している年月を保持しています。

[bootcamp/test/system/home_test.rb](https://github.com/fjordllc/bootcamp/blob/d57bb4cdc3b45c577c21f651d6b51fe85df3f9ce/test/system/home_test.rb#L134-L137)のテストを見る限り、`https://bootcamp.fjord.jp/?niconico_calendar=2024-01 ` の間違いではないでしょうか？（?が入っている）

> 今回非Vue化に伴い、paramsをcontrollerで受け取り表示する月を判断する仕様に変更したため、URLが
/?year=2024&month=01/ になっています。

上記が間違っているとすれば元々paramsで取得できる形であるように思います。だとしたら仕様を変更する意味はないように思います。

**Comment by reckyy** [comment]
@komagata 
コメントありがとうございます。

> 上記が間違っているとすれば元々paramsで取得できる形であるように思います。だとしたら仕様を変更する意味はないように思います。

おっしゃる通りでした。自分の勘違いでした。
paramsで取得でき、仕様の変更は不必要でした。申し訳ございません。
ご確認いただき、ありがとうございました 🙇

**Comment by reckyy** [comment]
本番環境で確認できたため、closeします〜。
