### ISSUE TITLE
Discord認証（GitHub認証みたいなやつ）

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7409]
machidaより。

現在、DiscordのユーザーIDの値はユーザーが手入力で入力しています。少し前にDiscordユーザーIDの仕様変更があり、今入力されているものの多くが間違ったものや古いものになってしまっており、信頼のできる情報ではありません。

DiscordのユーザーIDはTwitterIDのように誰でもすぐに見れるようになっていないので、それをユーザーに入力させるのはややこしいところがあります。また、ブートキャンプアプリからDiscordを使ってメンションをする機能を実装した場合（例えば https://github.com/fjordllc/bootcamp/issues/6986 これとか）、少しでもIDが間違えていたらメンションは飛ばなくなってしまいます。

自分で入力させるのは難しい、ミスはさせたくない、この2つの理由から、手入力をやめてDiscordアカウントとブートキャンプアカウントを連携させるようにしました。

---

`/current_user/edit` にいくと、

このような形で、GitHubアカウントのとの紐づけを行える。

<img width="593" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/57178bae-ff95-4a7c-81ba-de22daacdd22">

今の Discordの登録はこのようになっている。

<img width="591" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/5a8bc2b9-fb37-4f03-a019-4937c68219ec">

以下のように、手入力のinputは削除して、ボタンをクリックしてDiscordアカウントと連携をするようにしたい。

<img width="590" alt="貼り付けた画像_2024_02_20_16_23" src="https://github.com/fjordllc/bootcamp/assets/168265/95856d12-5691-470f-ad1a-439752811651">

---

これが参考になるかも。
https://qiita.com/masayoshi4649/items/46fdb744cb8255f5eb98

ブートキャンプアカウントとDiscordアカウントを連携することで、ブートキャンプユーザーのDiscordユーザーIDが把握できるようになり、ブートキャンプアプリからDiscordを使ってメンションをすることができるようになる。分報をブートキャンプに移行しても、Discordを使えばメンションが飛ばせるはず。

---

**Comment by machida** [comment]
@yocchan-git 
こちらをお願いしますー🙏

**Comment by yocchan-git** [comment]
ありがとうございます！助かります🙇‍♂️

**Comment by yocchan-git** [comment]
@komagata さん
@machida さん

developや本番環境の反映にあたり、Discordの設定をしていただきたいことがあります。
結論、「envファイルに下記の３つをを設定していただきたい」ということです🙇‍♂️
- `DISCORD_CLIENT_ID`
- `DISCORD_CLIENT_SECRET`
- `DISCORD_AUTHENTICATION_URL`

順を追って説明します！

## 設定の手順
 [Discord Developer Portal](https://discord.com/developers/applications)にアクセス&ログインしてください

[![Image from Gyazo](https://i.gyazo.com/eb5ee1affb47db73ea0dc7aa66bf07c2.png)](https://gyazo.com/eb5ee1affb47db73ea0dc7aa66bf07c2)

[![Image from Gyazo](https://i.gyazo.com/cc34fe4a8088b67eec440427813f5513.png)](https://gyazo.com/cc34fe4a8088b67eec440427813f5513)

[![Image from Gyazo](https://i.gyazo.com/e439af1f21fa20107e598469980ab48f.png)](https://gyazo.com/e439af1f21fa20107e598469980ab48f)

[![Image from Gyazo](https://i.gyazo.com/0ff1addfddddeecbddc4185639dc3051.png)](https://gyazo.com/0ff1addfddddeecbddc4185639dc3051)

[![Image from Gyazo](https://i.gyazo.com/9bff43110e04b08967f41889a3e75b7b.png)](https://gyazo.com/9bff43110e04b08967f41889a3e75b7b)

これでひとまず
- `DISCORD_CLIENT_ID`
- `DISCORD_CLIENT_SECRET`

は取得できました！🎉そちらをENVファイルに記述してください。
[![Image from Gyazo](https://i.gyazo.com/c7565f49b98c24121d07ebca94645df9.png)](https://gyazo.com/c7565f49b98c24121d07ebca94645df9)

---
次は`DISCORD_AUTHENTICATION_URL`を取得していきます👍
[![Image from Gyazo](https://i.gyazo.com/cf2e2ea4835c025f009ef2819566c1c8.png)](https://gyazo.com/cf2e2ea4835c025f009ef2819566c1c8)

リダイレクト先のURL
- 本番環境→`https://bootcamp.fjord.jp/discord_authentications/new`
- dev環境→ `https://bootcamp-staging.fjord.jp/discord_authentications/new`

でお願いいたします

[![Image from Gyazo](https://i.gyazo.com/464dc917581bbc5509f16ff178d39a63.png)](https://gyazo.com/464dc917581bbc5509f16ff178d39a63)

[![Image from Gyazo](https://i.gyazo.com/bb5f453c9d3b1ca07a856a748e4ad0cc.png)](https://gyazo.com/bb5f453c9d3b1ca07a856a748e4ad0cc)

[![Image from Gyazo](https://i.gyazo.com/1d626351846fc65ed84d9cdc1841d67a.png)](https://gyazo.com/1d626351846fc65ed84d9cdc1841d67a)

これで`DISCORD_AUTHENTICATION_URL`が取得できました🥳

こちらを`env`ファイルの一番下に記述をよろしくお願いいたします
以下はテンプレです！(=の空白は合わせていただけますと🙏)
```env
DISCORD_CLIENT_ID= 
DISCORD_CLIENT_SECRET= 
DISCORD_AUTHENTICATION_URL=
```

**Comment by komagata** [comment]
@yocchan-git かしこまりました。設定いたします。

> developや本番環境の反映にあたり、

環境の名前にちょっと認識違いがあるかもです。

developではなくステージング(staging)環境ですね。

ローカルでいつも開発してる環境がdevelopment環境なので`develop`という名前を使うととっても紛らわしくなってしまって色んなミス（リリースに絡みそうなので大きめのミス）に繋がりそうなので気をつけた方がいいかもです〜。

**Comment by yocchan-git** [comment]
komagataさん

間違えてました。失礼しました！
エスパーして教えていただきありがとうございます。助かりました🙇‍♂️

**Comment by komagata** [comment]
@yocchan-git 大変遅くなりました。
ステージング、本番共に環境変数を設定致しました。

**Comment by yocchan-git** [comment]
@komagata さん

`omniauth`を使うにあたって、ステージング・本番ともに[こちら](https://github.com/fjordllc/bootcamp/issues/7409#issuecomment-1962935498)で設定していただいた環境変数を修正していただきたく🙇‍♂️
二度手間で申し訳ないのですが、お手隙で環境変数を修正していただけますと嬉しいです🙏

### 修正の手順
#### 1. `DISCORD_AUTHENTICATION_URL`の削除
こちらは単純に`DISCORD_AUTHENTICATION_URL`の環境変数が
ステージング・本番ともに不要になったので、[こちら](https://github.com/fjordllc/bootcamp/pull/7511)で設定した環境変数を削除していただきたいです。🙇‍♂️

#### 2. リダイレクト先URLを`/auth/discord/callback`に修正する
先ほど、`DISCORD_AUTHENTICATION_URL`を削除したのですが
リダイレクト先URLが変更になりましたので、Developerのサイトから修正お願いいたします🙇‍♂️

 [Discord Developer Portal](https://discord.com/developers/applications)にアクセス&ログインしてください
1. ステージング(本番)環境のアプリケーションを選択

[![Image from Gyazo](https://i.gyazo.com/b242b0fc53f43666baf645798f4951cb.png)](https://gyazo.com/b242b0fc53f43666baf645798f4951cb)
2. OAuth2の設定に移動する

[![Image from Gyazo](https://i.gyazo.com/50acac88f086b57e43f0628be2dc2030.png)](https://gyazo.com/50acac88f086b57e43f0628be2dc2030)

3. リダイレクトURLの修正をする

[![Image from Gyazo](https://i.gyazo.com/1348ee2d6ff4a1df5c7c447213a6a9e1.png)](https://gyazo.com/1348ee2d6ff4a1df5c7c447213a6a9e1)

リダイレクト先のURLは
- 本番環境→`https://bootcamp.fjord.jp/auth/discord/callback`
- ステージング環境→ `https://bootcamp-staging.fjord.jp/auth/discord/callback`

でお願いいたします

[![Image from Gyazo](https://i.gyazo.com/653ff708cb320ddca1173d4ddf15216d.png)](https://gyazo.com/653ff708cb320ddca1173d4ddf15216d)

完了です！ありがとうございました🎉
こちらをステージング・本番環境ともで設定していただけますと嬉しいです

**Comment by komagata** [comment]
@yocchan-git すみません、内容をちゃんと理解していませんでした。
ただいまリダイレクトURLを修正しました～。

**Comment by yocchan-git** [comment]
本番環境の動作確認OKでした！
Closeします👍
