### ISSUE TITLE
ユーザー登録画面でプライバシポリシー等の設定がエラー時に残らない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7414]
入力エラー時（名前が未入力など）に"アンチハラスメントポリシに同意"と"利用規約に同意"にチェックしていても、それが外れた状態になる。

エラーとは言えないかもしれないが、ユーザーにとって不便で離脱の原因になるかもしれないので直したい。

![スクリーンショット 2024-02-21 6 19 48](https://github.com/fjordllc/bootcamp/assets/16577/10c3fc50-28c5-40ce-bc23-d08099f6dd16)

**Comment by naokinaokiboo** [comment]
本番環境での動作が確認できましたので、Close致します。
