### ISSUE TITLE
招待URL作成ページが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7424]
現状では管理画面の企業一覧ページにアドバイザー登録URLと研修生登録URLがあるが、他にもたくさん種類があるので、それら全てのURLを作ることができるページを用意したい。

![スクリーンショット 2024-02-22 10 34 19](https://github.com/fjordllc/bootcamp/assets/16577/9746862b-e549-4c9c-97ec-40933534e172)

![new-invitation-url](https://github.com/fjordllc/bootcamp/assets/16577/d5b1af9e-9e6b-42df-a312-cd7ebb4591ba)

プルダウンメニューを選択するとそれに相当するURLが下の領域に表示される。

ロールについては、"アドバイザー"と"研修生"、"メンター"だけが選択できる。

企業とコースは登録されているもの全てが選択できて良い。

## ユースケース

主に法人研修で利用される方向けに管理者が企業・ロール・コースをあらかじめ設定したURLをメールなどでお渡しして、そこから登録してもらっている。

**Comment by naokinaokiboo** [comment]
@komagata 
お疲れ様です。
仕様について１点確認させてください。🙇‍♂️

## 概要
- 各プルダウンメニュー内の項目の並び順について

## 確認点１
基本的に以下の参加登録画面、アドバイザー登録画面での順番に合わせる方針ですが問題ないでしょうか？
![image](https://github.com/fjordllc/bootcamp/assets/131861805/a428dfb1-d0fe-455e-88d2-7784a4d12b5a)

![image](https://github.com/fjordllc/bootcamp/assets/131861805/3352d1cf-3ef7-4fcd-ab9f-afca711be778)

## 確認点２
ただし、企業の順番に関しては現状以下のように`all`を使用した実装になっており、厳密には順番が保証されないのかなと思いますが、他の並び順にしたほうがよいでしょうか？

https://github.com/fjordllc/bootcamp/blob/5fe1098c5d3750654dbbc12f4864e5201bca14d1/app/helpers/companies_helper.rb#L3-L7

ちなみに、企業一覧ページは`id`順で並べているようです。
https://github.com/fjordllc/bootcamp/blob/5fe1098c5d3750654dbbc12f4864e5201bca14d1/app/controllers/api/admin/companies_controller.rb#L4-L10

**Comment by komagata** [comment]
@naokinaokiboo 

> 確認点１

はい。

> 確認点２

はい。

では`created_at`の降順でお願いします。
企業一覧ページその他に関しては別Issueとしてそれに合わせるためのIssueを作成していただければありがたいです。

**Comment by naokinaokiboo** [comment]
@komagata 
回答ありがとうございます。
以下に`Issue`を作成しておきました。
https://github.com/fjordllc/bootcamp/issues/7514

**Comment by komagata** [comment]
@naokinaokiboo ありがとうございます〜！

**Comment by naokinaokiboo** [comment]
@komagata @machida 
お疲れ様です。追加で１点確認させてください。🙇‍♂️
こちらのIssueについて、ロールの選択をメンターにした場合、登録画面側(`/users/new`)が未対応であるため、メンターが選択状態になりません。
![image](https://github.com/fjordllc/bootcamp/assets/131861805/e0feb7f0-4ea0-4a75-b9f2-21bfec5cf3fd)

登録画面側の対応は別のIssueという認識でよいでしょうか？（ユーザー属性の設定以外にはタイトル、h1等の変更が必要かもしれません）

**Comment by machida** [comment]
@naokinaokiboo 別Issueにしたいと思いますー
Issueの登録をお願いしたいです🙏

**Comment by naokinaokiboo** [comment]
@machida 
招待致しました👍
以下Issueを登録しておきました。
https://github.com/fjordllc/bootcamp/issues/7582

**Comment by komagata** [comment]
@naokinaokiboo こちら完了していましたらCloseをおねがいします～

**Comment by naokinaokiboo** [comment]
@komagata @machida 
お疲れ様です。
こちらのIssueの本番環境での動作確認をお願い致します。🙏

以下の手順で確認をお願いしたいです。
1. 管理ページの招待URLタブ（`/admin/invitation_url`）にアクセスし、た企業、ロール、コースを選択

2. 作成されたURLへ移動し、手順１で選択した企業、ロール、コースと一致していることを確認

※ただし、ロールとしてメンターを選択した場合は登録画面側が対応していないため現状反映されません。登録画面側の対応については以下のIssueで対応予定となっています。

https://github.com/fjordllc/bootcamp/issues/7582

**Comment by komagata** [comment]
@naokinaokiboo 本番環境で確認しました～！

**Comment by naokinaokiboo** [comment]
@komagata 
ありがとうございます〜。
本番環境で確認が取れたのでCloseします！
