### ISSUE TITLE
管理者メニューに各ページへのリンクが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7425]
![image](https://github.com/fjordllc/bootcamp/assets/16577/0ef486de-bc6a-4e8e-8e85-f90a66552f16)

メニューの"管理者メニュー"の欄に下記のそれぞれのページへのリンクがないので追加したい。

![image](https://github.com/fjordllc/bootcamp/assets/16577/c2769205-beaf-496d-9644-bbebeee3331b)

**Comment by unikounio** [comment]
@komagata さん、 @machida さん
お疲れ様です。
本Issueに関する本番環境での確認を行いたいのですが、管理者権限でのログインが必要な状況です。
お手数ですが、ご確認をお願いしてもよろしいでしょうか🙏

**Comment by machida** [comment]
@unikounio 本番で確認しましたー🙆‍♂️

**Comment by unikounio** [comment]
@machida さん
迅速なご対応ありがとうございます！
Closeさせていただきます～
