### ISSUE TITLE
memo.vueを非vue化する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7437]
vueを使わないようにするためにタイトルになっているファイルを使っている箇所を普通のHTMLでの実装に変える。

元々Reactに変更する予定でしたが、最終的にはHotwireにする予定なので、VueもReactも使わない実装にしたいです。（普通にviewに表示する方式）

**Comment by a-kuroki-gs** [comment]
@komagata @machida 

お疲れ様です！
本Issueについて２点質問です。

---

## １点目、`memo.vue`の存在意義について
`memo.vue`がどこで使われているかよくわからず、消去しても影響が見当たらなかったため、色々と調べてみました。
[こちら](https://github.com/fjordllc/bootcamp/blame/main/app/javascript/memo.vue)を見るとおそらく[MemoのAPI化](https://github.com/fjordllc/bootcamp/commit/a4dc6a219a41b0ae6cf830874186effab3f8cd75)のコミットでVueが作成されていることがわかり、それを使っていた部分は`app/javascript/reservations.vue`だと考えられます。
そしてそのファイルは[こちら](https://github.com/fjordllc/bootcamp/pull/3203)で削除されているので、現状使われていないのではないか？と考えておりますが、いかがでしょうか？
もし使われている部分があれば、教えていただけますと幸いです。

## ２点目、その他のメモ関連のVueについて
`memo.vue`について調べているうちに、その他のメモ関連のVueとして
`app/javascript/practice_memo.vue`・`app/javascript/components/user_mentor_memo.vue`は実際に使われていることがわかりました。
本Issueの目的はそちらを非Vue化することになりますでしょうか？

---

以上２点、ご確認よろしくお願いいたします。

**Comment by a-kuroki-gs** [comment]
:memo: <b>本Issueの方向性について</b>

上でコメントしている点について、MTGで確認したところ
私の推測通り`memo.vue`は現在使われていないはず、とのことでした。
(以前は座席予約システムがあり、そこで使われていたものだそうです。)

そのため本Issueの方向性は以下とします👍
- `memo.vue`を削除する
- `memo.vue`以外にも、`memo.vue`関連・座席予約システム関連のもので不要なものを削除する
