### ISSUE TITLE
お問い合わせがあったら管理者に通知してほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7457]
このブランチがmainにマージ前だったら、このブランチからブランチを作る。
https://github.com/fjordllc/bootcamp/pull/7387

メール通知はすでにあるが、サイト内通知（右上のベル）をしてほしい。

**Comment by goruchanchan** [comment]
@komagata @machida 
実装について相談させてください。

『サイト内通知』は `Notification` クラスで管理しており、FBC の `User` アカウントを所有している必要があると思っています。
[![Image from Gyazo](https://i.gyazo.com/4646e045edda0bb682703b83532f63f4.png)](https://gyazo.com/4646e045edda0bb682703b83532f63f4)
一方で、『問い合わせ』は `Inquiry`  クラスで管理しており、こちらは非ログインユーザからでも投稿できるため、`User` アカウントを所有していなくても投稿できます。
[![Image from Gyazo](https://i.gyazo.com/563fb5ada0a61f7e0b96b5e8b5685d75.png)](https://gyazo.com/563fb5ada0a61f7e0b96b5e8b5685d75)

現状構成で『サイト内通知』するには、`Inquiry` を `Notification` クラスへ移行する必要があると思っているのですが、理解は正しいでしょうか？その場合、`Notification` クラスのバリデーションに引っかかるため、`User` クラスのインスタンスが必要になると考えておりますが、どのようにすべきでしょうか？

**Comment by komagata** [comment]
> 現状構成で『サイト内通知』するには、Inquiry を Notification クラスへ移行する必要があると思っているのですが、理解は正しいでしょうか？

正しくないです。

しかしNotificationにはuser(sender)が必要なので、お問い合わせの送信者は管理者のピヨルドアカウントから送信されるようにお願いします。

ピヨルドアカウントはまだ存在しないのですが、他のissueでも必要になっているので、このissueで作る前提でお願いできればと思います。（development環境とstaging環境用にseedに作成してください）

ピヨルドアカウントの判別はlogin_nameが`pjord`であることを目印にするとdevelopmentでもproductionでも同じように扱えると思います。

本番環境のピヨルドアカウントは僕が作成します〜。

**Comment by komagata** [comment]
:memo: 本番環境のピヨルドユーザーを下記で登録しました〜
https://bootcamp.fjord.jp/users/2028

**Comment by goruchanchan** [comment]
@komagata ご回答ありがとうございます！承知しました🙇‍♂️

**Comment by goruchanchan** [comment]
メインブランチにて動作確認されたのでクローズ
