### ISSUE TITLE
みんなのブログを非Vue化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7458]
このページ：https://bootcamp.fjord.jp/external_entries

vueを使わないようにするためにタイトルになっているファイルを使っている箇所を普通のHTMLでの実装に変える。
（普通のscaffoldっぽいもの）

元々Reactに変更する予定でしたが、最終的にはHotwireにする予定なので、VueもReactも使わない実装にしたいです。（普通にviewに表示する方式）

Questionの下にAnswersがありますが、そちらは別のIssueやるのでそのままで大丈夫です。

**Comment by nishitatsu-dev** [comment]
本番環境で動作確認できたのでクローズします。
