### ISSUE TITLE
mentor-practices.vueを非vue化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7461]
vueを使わないようにするためにタイトルになっているファイルを使っている箇所を普通のHTMLでの実装に変える。
（普通のscaffoldっぽいもの）

元々Reactに変更する予定でしたが、最終的にはHotwireにする予定なので、VueもReactも使わない実装にしたいです。（普通にviewに表示する方式）

Questionの下にAnswersがありますが、そちらは別のIssueやるのでそのままで大丈夫です。

**Comment by taco-nantai** [comment]
@komagata @machida
お疲れ様です。
本Issueの作業内容がリリースされたので、本番環境での確認を行いたいのですが、確認に管理者ユーザーでのログインが必要なため、本番環境での確認をお願いしてもよろしいでしょうか。
お手数をおかけしますが、よろしくお願いいたします🙇‍♂️

**Comment by komagata** [comment]
@taco-nantai 

本番環境で確認しました。
上のpaddingがない問題があるかとおもいました～。

![image](https://github.com/fjordllc/bootcamp/assets/16577/f30bd3a0-77b7-4e78-bf74-56b4001c43e4)

**Comment by komagata** [comment]
@taco-nantai すみません、確認するページを間違えていました。
今度は問題ありませんでした。

**Comment by taco-nantai** [comment]
@komagata 
確認ありがとうございます🙇‍♂️

**Comment by taco-nantai** [comment]
本番環境で確認をいただいたので、closeとさせていただきます。
