### ISSUE TITLE
pages.vue, page.vueを非vue化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7462]
vueを使わないようにするためにタイトルになっているファイルを使っている箇所を普通のHTMLでの実装に変える。
（普通のscaffoldっぽいもの）

元々Reactに変更する予定でしたが、最終的にはHotwireにする予定なので、VueもReactも使わない実装にしたいです。（普通にviewに表示する方式）

**Comment by SuzukaHori** [comment]
@komagata 
お疲れさまです。
mainブランチで気になる挙動を見つけたので、対応をご相談したいです。

### 内容
`/pages`の並び順が**ローカル環境でのみ、正しく並ばない**ことがあります。
ステージング・本番環境では常に同じ順番に並んでおり再現しなかったので、私の環境の問題かもしれません。

↓2行目以降の並びが、更新すると変わります。
[![Image from Gyazo](https://i.gyazo.com/f2dea26146b545752168b1144775c497.gif)](https://gyazo.com/f2dea26146b545752168b1144775c497)

- 該当箇所のコード：app/controllers/pages_controller.rb
更新日時順に並び替えており、一見気になる点は見つかりませんでした。

   ```ruby
  def index
    @pages = Page.with_avatar
                 .includes(:comments, :practice, :tags,
                           { last_updated_user: { avatar_attachment: :blob } })
                 .order(updated_at: :desc)
                 .page(params[:page])
    @pages = @pages.tagged_with(params[:tag]) if params[:tag]
    @tag = ActsAsTaggableOn::Tag.find_by(name: params[:tag])
  end
   ```
テストデータの中に「`updated_at`が2024年03月05日(火) 20:38のもの」が複数あることが関係あるかもしれないです。ただ、同じようなテストデータを使っている日報・質問ページでは、並び順は一定でした。

### お聞きしたいこと
これがバグなのか、もしバグなら本Issueで対応が必要かを伺いたいです。

**Comment by komagata** [comment]
@SuzukaHori update_atが同じであることが原因だとしたらバグというほどではないかなと思います。
ただ、`ODER BY updated_at, id`みたいに並びが確定する方が望ましいので新しく実装するのであればその辺りが考慮されている方がいいなと思います。

**Comment by SuzukaHori** [comment]
@komagata
ご返信ありがとうございます！

`rails c`で確認したところ、ほぼ全てのデータが同じ`update_at`になっていた（fixturesファイルに更新日がなく自動でデータを作った時の日時が入るため）ので、正しく並ばなくて当然でした😅

orderにidも合わせて指定したら並び方を一つにできたので、そちらで実装します！

**Comment by SuzukaHori** [comment]
質問タイムで確認したこと：

ミニアイコンにroleを表す枠がないのは、仕様ではなくバグ。
<img width="425" alt="スクリーンショット 2024-03-11 17 15 07" src="https://github.com/fjordllc/bootcamp/assets/129706209/c79e6e22-910b-4e65-81c1-b8edccf051be">

このPRでは枠が出るよう実装する。また、日報ページなど他ページで枠が出ていないところはIssueを立てる。

**Comment by SuzukaHori** [comment]
本番環境で動作を確認できたので、クローズします。
