### ISSUE TITLE
通知ベル上の未読通知数のカウントが、未読通知が「100件以上」存在している場合でも「99」になってしまう

### ISSUE THREAD

**Issue by junohm410** [fjordllc/bootcamp#7467]
## 概要

画面右上の通知ベル上の未読通知数の表示について、未読通知が「100件以上」存在している場合でも、カウントは「`99`」となってしまいます。

### 詳細
実装では、未読通知が100件以上存在している場合は「`99+`」と表示されることが意図されています。

https://github.com/fjordllc/bootcamp/blob/6dcc83786e9af3b2d965bd14360c382fa396e6d7/app/javascript/components/NotificationsBell/BellButton.jsx#L11-L16

未読の通知を取得するAPIで使用される`Notifcation`モデルのスコープ`by_read_status`において、未読通知の最大取得数が99になっていることが原因と思われます。
https://github.com/fjordllc/bootcamp/blob/03e5c1ef175da7da65791008377da534c1ff5276/app/models/notification.rb#L47

## 再現手順

1. 特定のユーザーが、未読の通知を100件以上持つ状態を作る。
1. Railsコンソールで、`{1のユーザーオブジェクト}.notifications.unreads.count`の戻り値が`100`以上であることを確認する。
1. サーバーを立ち上げ、1のユーザーでログインする。
1. 画面右上の通知ベル上のカウント表示が、`99`であることを確認する。

## 期待される振る舞い

- 未読通知が1〜99件存在している場合のあるべき姿は、その数字（`1` 〜 `99`）
- 未読通知が100件以上の場合のあるべき姿は、`99+`

## スクリーンショット
`hatsuno`に未読通知が215件（100件以上）ある状態を用意。
```
irb(main):023:0> hatsuno = User.where(login_name: 'hatsuno').first
irb(main):023:0> hatsuno.notifications.unreads.count
   (0.7ms)  SELECT COUNT(*) FROM "notifications" WHERE "notifications"."user_id" = $1 AND "notifications"."read" = $2  [["user_id", 655153192], ["read", false]]
=> 215     
```

`hatsuno`でログインすると、通知ベル上のカウントが`99`になっている。
![image](https://github.com/fjordllc/bootcamp/assets/128765400/c7948a66-74b3-4a05-9060-63cbdde9f1e0)

## 環境

 - OS: MacOS Ventura 13.0
 - ブラウザ: chrome 122.0.6261.69

## 関連Issue

- https://github.com/fjordllc/bootcamp/issues/7163
- https://github.com/fjordllc/bootcamp/pull/7257

**Comment by masyuko0222** [comment]
@komagata @machida 
https://github.com/fjordllc/bootcamp/issues/7539#issuecomment-2036556546
こちらを基にCloseさせて頂きますー
