### ISSUE TITLE
label attributeのエラーを取る

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7471]
ダッシュボードのページをGoogle Chromeで見るとissue（consoleの右のタブ）にlabel attributeに関するエラーが出ているのでそれをなおす。

![image](https://github.com/fjordllc/bootcamp/assets/16577/e187f02d-d591-4b4c-9348-9ebb975eb379)

**Comment by unikounio** [comment]
@komagata さん
お疲れ様です。

Issueの再現を試みたところ、本番環境では確認できたのですが、ステージング環境と開発環境では確認できませんでした。
また、問題の原因と該当箇所の現状についても確認してみたのですが、もしかすると該当箇所のReact化によって解決されている問題かもしれないと思いました。

本件はこのまま進めていってよいのでしょうか？
念のため確認させてください🙏

**Comment by komagata** [comment]
@unikounio なるほどですね。
では今のステージングのコードが本番にデプロイされる木曜日以降にもう一度本番を確認してみてください。
それで直っていたらこのissueは完了にしちゃいましょう〜。

**Comment by unikounio** [comment]
関連コードのリリースに伴い本番環境での確認を行ったところ、label attributeに関するエラーが発生していないことを確認できました。
![スクリーンショット 2024-03-07 191015](https://github.com/fjordllc/bootcamp/assets/125527162/5b2e50d4-2697-43b9-85c7-dd2166b199ce)

上記より本Issueは解決したものと判断し、Closeさせていただきます。
