### ISSUE TITLE
企業一覧のアドバイザー・現役生にリンクをつけたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7473]
![スクリーンショット 2024-03-01 14 36 39](https://github.com/fjordllc/bootcamp/assets/16577/26706efc-a3b1-4606-b4de-ebababe55b58)

上記にそれぞれ企業のユーザー一覧のアドバイザーページ、現役生ページにリンクを貼りたい。

![image](https://github.com/fjordllc/bootcamp/assets/16577/b7a545f2-cab4-4253-90c6-85d4550ab627)

**Comment by mousu-a** [comment]
[github](http://aunkoaa.com)

**Comment by mousu-a** [comment]
本番環境で動作確認できましたのでcloseします！
