### ISSUE TITLE
日報がないユーザーの相談部屋において、ユーザーの日報の表示が崩れている

### ISSUE THREAD

**Issue by a-kuroki-gs** [fjordllc/bootcamp#7476]
## 概要

日報が登録されていないユーザーの相談部屋詳細において、
`ユーザーの日報`タブをクリックしたときに枠が表示されておらず、表示が崩れている。

## 再現手順

1. http://localhost:3000/talks にアクセス。
2. 日報がないユーザーの相談部屋をクリック。
3. `ユーザーの日報`タブをクリックすると、表示が崩れている。

## 期待される振る舞い

他のメモ欄のように枠が表示されてほしい。
(こちらは提出物詳細から見たプラクティスメモの画面)
![image](https://github.com/fjordllc/bootcamp/assets/133615511/b008d3f4-4ae7-49a1-99c0-b2e67510702e)

## スクリーンショット

![image](https://github.com/fjordllc/bootcamp/assets/133615511/fec32ecb-cdd9-4776-b861-b1b1c0f3e39d)

## 環境

 - OS: [Windows 10 Pro]
 - ブラウザ: [chrome]
 - バージョン: [122.0.6261.95]

**Comment by hirano-vm4** [comment]
本番環境での表示を確認したためcloseします！
