### ISSUE TITLE
研修生にもニコニコカレンダーを表示してほしい

### ISSUE THREAD

**Issue by a-kuroki-gs** [fjordllc/bootcamp#7477]
## 概要

ユーザーの詳細画面でニコニコカレンダーが表示されますが、
研修生のユーザーの場合は表示されません。

## 再現手順

1. http://localhost:3000/users?target=trainee にアクセス。
2. 任意のユーザーをクリック。(研修生)
3. ニコニコカレンダーが表示されない。

## 期待される振る舞い

通常のユーザーと同様にニコニコカレンダーが表示できると嬉しいです。

以下の条件式を変更すると表示できると思います。
https://github.com/fjordllc/bootcamp/blob/6dcc83786e9af3b2d965bd14360c382fa396e6d7/app/views/users/show.html.slim#L68-L69

## スクリーンショット

![image](https://github.com/fjordllc/bootcamp/assets/133615511/c0db4e46-7978-4248-8a83-321ddd266bcc)

## 環境

 - OS: [Windows 10 Pro]
 - ブラウザ: [chrome]
 - バージョン: [122.0.6261.95]

**Comment by a-terumoto-gs** [comment]
本番環境での動作が確認できたためcloseします
