### ISSUE TITLE
Flakyなテストを直したい

### ISSUE THREAD

**Issue by SuzukaHori** [fjordllc/bootcamp#7485]
## 概要
Flakyなテストが原因でCIが通りにくくなっているため、Issueを立てました。

特に「test_edit_user_tag」は、14日間で75回失敗しています。
<img width="859" alt="スクリーンショット 2024-03-04 10 42 28" src="https://github.com/fjordllc/bootcamp/assets/129706209/c009e80e-f5f1-4f5d-a918-e78b5f6e56d6">

その他、以下のテストの失敗回数が極端に多いため、直せるのであればCIの通過率が上がるのではないかと思います。
- test_company_logo_appear_when_adviser_belongs_to_the_company_post_comment
- test_update_user_tags
- test_attachment_company_icons_in_reports
- test_the_company_logo_is_shown_when_an_adviser_who_belongs_to_a_company_posts_an_answer

## 関連Issue
- https://github.com/fjordllc/bootcamp/issues/6760

**Comment by taco-nantai** [comment]
@SuzukaHori @komagata 
お疲れ様です。
現在 #7504 にて、こちらのissueで挙げられたテストの調査と修正を進めています。

挙げられているflakyなテストに関して、
「test_edit_user_tag」、
「test_update_user_tags」
については、追加するタグの文字列を入力する処理(`tag_input.set`)が不安定なことがテスト失敗の原因となっており、追加するタグの文字列を入力する前に、一度空文字を入力する処理を追加することで解決しました。

「test_company_logo_appear_when_adviser_belongs_to_the_company_post_comment」、「test_attachment_company_icons_in_reports」、
「test_the_company_logo_is_shown_when_an_adviser_who_belongs_to_a_company_posts_an_answer」
については、`company.rb`の企業ロゴ取得の処理で、`ActiveStorage::FileNotFoundError`が発生することがあり、期待される企業ロゴ(`2.png`)ではなく、デフォルトの企業ロゴ(`default.png`)が読み込まれてしまうことがテスト失敗の原因となっていると見られ、現在根本的な解決方法が見つかっていない状況です。

企業ロゴ表示関連のテストに関しては、ローカルでのテスト失敗が再現できず、CircleCIの実行環境特有の原因があるという可能性が考えられ、解決が難しいかもしれません。

上記を踏まえて提案させていただきたいのですが、企業ロゴ表示関連のテストに関して、テスト内容を[こちら](https://github.com/fjordllc/bootcamp/pull/7504/files)のように、"ファイル名が`2.png`であること"から、"ファイル名が`2.png`または`default.png`であること"に変更してもよいでしょうか。
テスト内容を改変してしまうことになりますが、少なくとも、一般ユーザーとは違って、ユーザーアイコンの下に企業ロゴ用の要素と画像が表示されていることは確認できます(`ActiveStorage::FileNotFoundError`が発生していてもパスするという形にはなりますが)

こちらのテスト内容の変更について、ご意見をお聞かせ願いたいです。
お手数をおかけしますが、よろしくお願いします🙇‍♂️

**Comment by SuzukaHori** [comment]
@taco-nantai
テストの修正、お疲れさまです！
私がIssueを立てたので、恐縮ですが考えを書かせていただきます。（CC:@komagata 見当違いでしたらご指摘ください🙇‍♀️）

- ファイルについて
「test_the_company_logo_is_shown_when_an_adviser_who_belongs_to_a_company_posts_an_answer」に従って、質問ページのimageタグを確認しました。

   私は「default.pngがデフォルトのユーザアイコン」「2.pngが企業ロゴ」かと思ったのですが、こちらはいかがでしょうか？？
   <img width="809" alt="スクリーンショット 2024-03-08 18 14 45" src="https://github.com/fjordllc/bootcamp/assets/129706209/26204277-df0c-4d7e-9c1f-d129037f40ba">

   もし間違っていたら、以下は見当違いなので無視してください🙏

- 上の理解があっていた場合、「ファイル名が2.pngまたはdefault.pngであること」にテストを変更した場合、「企業アイコン or デフォルトのユーザアイコンが表示されていること」がテストされると思います。
ユーザアイコンを確認するのは、企業ロゴ画像の存在をテストしたい元のテストの意図と異なるように思いました🤔
- 同じcompany-logをチェックしている、別のテストが参考になるかもと思いました👀（すでに検討されていたらすみません）
https://github.com/fjordllc/bootcamp/blob/5fe1098c5d3750654dbbc12f4864e5201bca14d1/test/system/talks_test.rb#L445-L448
参考にしたテストが頻繁に落ちていないかや、テストの意図通りチェックできるのかは調査が必要そうですが😅

**Comment by SuzukaHori** [comment]
@taco-nantai 
お返事ありがとうございます！
すみません、色々ちゃんと読んでなくて誤解していました🙇‍♀️

確かに'img.thread-comment__company-logo'を指定しているので、ユーザのデフォルトアイコンではないですね😅
CircleCI上で撮ったスクショを確認できるのも知らなかったです！大変勉強になりました🙏

個人的には、tacoさんのご提案通り、`assert_includes`に'default.png'を追加する or imgタグの存在だけを確認することで、テストが成功するようにするのも、やむを得ないかなと思いました。

komagataさんに確認して進められると良いと思いますが、以下に個人的な意見を書いておきます🙇‍♀️

---

ActiveStorage::FileNotFoundErrorが発生した時に画像がdefault.pngとなるのは、こちらのPRで「logo_urlに例外処理を追加することで、CIを通りやすくした」というコメントがあり、テスト失敗防止のために書かれた例外処理のように見えました。
- https://github.com/fjordllc/bootcamp/pull/5096#issuecomment-1179537893

本来、CI環境でActiveStorage::FileNotFoundErrorが発生しないよう修正するのが理想的ですが、上のPRで「例外処理なしでCIを通りやすくするのは難しい」と判断されているなら、`default.png`でテストを通過させるのもやむを得ないのかなと思いました。

**Comment by taco-nantai** [comment]
@SuzukaHori 
コメントありがとうございます🙇‍♂️
教えていただいたPR #5096 の会話内容参考になりました!
テスト内容に変更を加えてよいか、komagataさんに確認をとって進めたいと思います。
ありがとうございました👍

**Comment by komagata** [comment]
@taco-nantai (CC: @SuzukaHori )

上記通りで進めていただいて大丈夫です〜

**Comment by taco-nantai** [comment]
@komagata 
了解しました!
コメントありがとうございます🙇‍♂️
