### ISSUE TITLE
トップページの企業リンクをfjord.jpからlokka.jpに変えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7496]
![スクリーンショット 2024-03-05 19 37 53](https://github.com/fjordllc/bootcamp/assets/16577/3d132984-ede2-4354-a4e5-5f1280b034ca)

fjord.jpをlokka.jpに変えたい。文言とリンクを両方変えたい。

**Comment by nakamu-kazu222** [comment]
@komagata  さん、 @machida さん

お疲れ様です
変更する文言とリンク内容は以下でよろしいでしょうか？
- 文言
  - lokka.jp
- リンク
  - https://lokka.jp/

お手隙の際に、ご確認いただけると幸いです

**Comment by machida** [comment]
@nakamu-kazu222 はい！それで合ってます🙆そのように変更お願いします。

**Comment by nakamu-kazu222** [comment]
@machida さん

承知いたしました！
ご確認いただきありがとうございます

**Comment by nakamu-kazu222** [comment]
本番環境で動作確認完了しましたので、closeいたします
