### ISSUE TITLE
[Choices.js] Docs作成フォームのプラクティス選択をChoices.jsに置き換える。

### ISSUE THREAD

**Issue by junohm410** [fjordllc/bootcamp#7498]
## 概要
Docs作成フォームのプラクティス選択部分のセレクトボックスは、現状は`select2`というjQueryライブラリで実装されている。

![image](https://github.com/fjordllc/bootcamp/assets/128765400/b9f5080b-a780-4372-bb27-ef1d2873e0a7)

日報・Q&Aの作成フォームや、日報一覧のプラクティスによる絞り込みなどは、`Choices.js`というライブラリに置き換えられて実装されている。

![image](https://github.com/fjordllc/bootcamp/assets/128765400/853547a7-9b9f-454c-b009-226af879718d)

Docsの当該部分の実装を`Choices.js`に置き換える。

## 関連Issue
- https://github.com/fjordllc/bootcamp/issues/4582
- https://github.com/fjordllc/bootcamp/pull/4637

Docsで`select2`を置き換えるべきであるという議論が行われたのは、下のPRのコメントにおいてです。
- https://github.com/fjordllc/bootcamp/pull/7439#issuecomment-1979366039

**Comment by a-terumoto-gs** [comment]
本番環境での動作が確認できたのでcloseします～
