### ISSUE TITLE
メンター向けの「トップページに表示しない」というチェックボックスが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7500]
トップページにメンター全員が表示される一覧があります。
現状はmentor権限がある全ユーザーが表示されるのですが、表示されたくないメンターもいるため、「トップページに表示しない」というチェックボックスをユーザー情報に追加し、こちらがfalseのユーザーだけトップページに表示するようにする。

![スクリーンショット 2024-03-06 14 37 08](https://github.com/fjordllc/bootcamp/assets/16577/743b98a7-92f5-4226-800c-3fc77ec69def)

**Comment by hirano-vm4** [comment]
@komagata 

お疲れ様です！
お忙しいところ申し訳ありません。こちらのIssueを実装するにあたり、1点質問と提案になります🙏

## 現在考えている方向性
今回こちらのIssueは以下のような作業をしようと検討しています。

1. Userモデルに`hide_profile_from_toppage`のようなカラム名で真偽値を設定（デフォルトはfalseでトップページに表示する）
2. UsersControllerのuser_params メソッドに、`hide_profile_from_toppage`パラメータを許可リストに追加
3. トップページに表示するメンターを選択するロジックをビューに追加する（`hide_profile_from_toppage`が falseのユーザーのみをフィルタリングし表示する）

そこで以下の点について確認させてください。

## 【質問】 チェックボックスの設定場所について

>「トップページに表示しない」というチェックボックスを`ユーザー情報`に追加

このようにIssueの概要に説明がありましたが、この`ユーザー情報`が指しているのは、「登録情報変更」(http://localhost:3000/current_user/edit) の認識であってますでしょうか？


以下のように「登録情報変更」の画面であれば設定内容に「メンター紹介用公開プロフィール」の入力スペースがあるため、個人的にも自然だと感じました。


<img width="1028" alt="スクリーンショット 2024-03-07 21 48 52" src="https://github.com/fjordllc/bootcamp/assets/105143414/cc61260a-fc72-4bf4-a1a9-133ed3c598d5">

## 【提案】チェックボックス下に説明文を入れても良いか


「登録情報変更」の入力画面には以下のような「メール通知」のチェックボックスが存在し、同じようなイメージかな？と考えています。

<img width="523" alt="スクリーンショット 2024-03-07 21 53 03" src="https://github.com/fjordllc/bootcamp/assets/105143414/f11b86dc-f7ba-4581-a826-818c52e08d0e">

ここからは提案で、同じようにチェックボックス下に説明文をいれても問題なさそうでしょうか？


提案の意図は、プロフィールを表示しない設定をする方は、デリゲートな問題が絡むと考えたため（会社にばれたくないetc）です。

入力者が間違えないように、どこに表示され、だれかみれるものかを説明したほうが、より丁寧かなと個人的に感じたため提案させてもらいました🙏


`説明文のイメージ`
```
あなたのメンター紹介用公開プロフィールをトップページに表示させるか否かの設定です。
メンター紹介用公開プロフィールは誰でも閲覧できる場所に表示されます。
デフォルトではトップページに表示されるため、表示したくない場合はオンにしてください。
```

**Comment by komagata** [comment]
@hirano-vm4 

> このユーザー情報が指しているのは、「登録情報変更」(http://localhost:3000/current_user/edit) の認識であってますでしょうか？

はい。

> ここからは提案で、同じようにチェックボックス下に説明文をいれても問題なさそうでしょうか？

はい。

> Userモデルに`hide_profile_from_toppage`のようなカラム名で真偽値を設定（デフォルトはfalseでトップページに表示する）

メンターに限るので`hide_mentor_profile`とかの方がいいかもです。

**Comment by hirano-vm4** [comment]
@komagata 
>メンターに限るので`hide_mentor_profile`とかの方がいいかもです

おっしゃる通り、メンターさんに限るのでhide_mentor_profile`でカラム名は進めたいと思います！

確認いただきありがとうございました🙏

**Comment by hirano-vm4** [comment]
@komagata さんに本番環境の確認をしていただいたため、closeします！
