### ISSUE TITLE
プロフィールページに「請求書払いのユーザー」の項目が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7513]
![image](https://github.com/fjordllc/bootcamp/assets/16577/b37f6dad-7507-4451-b155-59da3a703214)

![image](https://github.com/fjordllc/bootcamp/assets/16577/44a6739b-f07e-4166-9cf1-1c8473122a9c)

ユーザー非公開情報の「決済情報」の下に表示したい。
どういう項目名・表示が良いかを考えて提案してみてください。

Ref: #6410

**Comment by Shrimprin** [comment]
@komagata @machida 
項目名・表示について案を2つ考えたのですがどちらが良いでしょうか？
私としては案1が他の項目とも統一感があり簡潔なので良いと考えています。

* 案1

| 項目名 | 表示 |
| ---- | ---- |
| 請求書払い | 利用中  or 未利用 |


* 案2

| 項目名 | 表示 |
| ---- | ---- |
| 請求書払いユーザー | はい or いいえ |

お手数ですがご回答をお願いします。

**Comment by komagata** [comment]
@Shrimprin 提案ありがとうございます。

一定期間利用するというものではなく、YESかNOかなので「利用中」という表現はちょっとそぐわないので、案2でお願いします〜。

**Comment by Shrimprin** [comment]
@komagata 
ご回答いただきありがとうございます。
案2で実装します

**Comment by Shrimprin** [comment]
@komagata 
先ほど作業ブランチをリモートにpushしたところCircle CIが走らず、対処方法をご助言いただけますでしょうか。
### お聞きしたいこと
Circle CIが実行されない原因またはその調査方法をご助言いただけますでしょうか。

### 状況の説明
#### プルリクエスト画面
プルリクエストを作成したところ、CIが実行されませんでした。
GitHubのプルリクエスト上の画面にもCIが動いているような表示がありません。
<img width="710" alt="image" src="https://github.com/fjordllc/bootcamp/assets/117491666/77e045be-738e-4209-9013-02d1d30ea8d8">

#### Checksタブ
`Checks`タブは以下のようになっており、CIを再実行するようなボタンも表示されていません。
![image](https://github.com/fjordllc/bootcamp/assets/117491666/1628470d-5a53-4fe1-992e-141699a8cbdf)

#### Circle CIダッシュボード
[Circle CIのダッシュボード](https://app.circleci.com/pipelines/github/fjordllc/bootcamp?filter=all)の`status`欄には`Unexpected server error processing config
Please contact support
Internal error ID: 0666941e-afe7-4660-93c5-54148e55614e`という警告メッセージが表示されています。
（↓のスクショは私のパイプラインのみに絞ったものです）
<img width="1915" alt="image" src="https://github.com/fjordllc/bootcamp/assets/117491666/61796a15-763e-4354-9e78-663af6ea5059">

### 自身の考え
[別のプルリクエスト](https://github.com/fjordllc/bootcamp/pull/7777)では問題なくCIが実行されているため、Circle CIのアカウントの紐づけは問題なくできていると考えています。
警告が内容が`Internal Error`であるため、Circle CIのサービス自体の問題なのかと推測もできますが、その場合はどのように対処すべきか悩んでいます。

お忙しいところお手数ですが、ご助言をお願いできますでしょうか。

**Comment by komagata** [comment]
@Shrimprin あたらしくコミットしてみたり、Ready for Reviewにしてみたらいかがでしょうか～

**Comment by Shrimprin** [comment]
@komagata 新しいコミットを作ってpushしたところCIが走り始めました！ありがとうございます 🙏

**Comment by Shrimprin** [comment]
@komagata @machida 
お疲れ様です！
こちらの機能がリリースされましたが、確認にはadmin権限が必要なため、本番環境での確認お願いできますでしょうか？ 🙏 
確認手順は[プルリクエスト](https://github.com/fjordllc/bootcamp/pull/7788)に記載しています。

お手数おかけしますがよろしくお願いいたします。

**Comment by Shrimprin** [comment]
@komagata 
ありがとうございます！
