### ISSUE TITLE
企業の並び順を一覧ページとプルダウンで揃えたい

### ISSUE THREAD

**Issue by naokinaokiboo** [fjordllc/bootcamp#7514]
## 概要

- 企業一覧ページと参加登録画面、アドバイザー登録画面での企業の並びを揃えたいです。
- 並び順は、以下の`Issue`で`created_at`の降順で並べることになったため、そちらに合わせてください。
  - https://github.com/fjordllc/bootcamp/issues/7424

### 企業一覧ページ
- 「管理者メニュー」→「管理ページ」→「企業タブ」
![image](https://github.com/fjordllc/bootcamp/assets/131861805/3acd9974-77f3-4f2d-8e2f-512c0f67bdf6)

### 参加登録、アドバイザー登録ページ
- 企業一覧の「アドバイザー招待リンク」、「研修生招待リンク」 
![image](https://github.com/fjordllc/bootcamp/assets/131861805/c471be25-8729-443b-9952-050eb3890982)

**Comment by komagata** [comment]
@naokinaokiboo Issue作成ありがとうございます〜！

**Comment by hirano-vm4** [comment]
merge後、@komagata さん挙動を確認いただき問題がなかったため、このIssueはcloseします。
