### ISSUE TITLE
roleを表す色枠が出ていないユーザアイコンがある

### ISSUE THREAD

**Issue by SuzukaHori** [fjordllc/bootcamp#7516]
## 概要
日報一覧ページ`/reports`のミニアイコンなど、一部のユーザアイコンでroleを表す色枠が表示されていません。

---

#### `/reports`のミニアイコン
<img width="706" alt="スクリーンショット 2024-03-11 17 19 19" src="https://github.com/fjordllc/bootcamp/assets/129706209/fbc9c31c-985d-4e0d-802e-f1118440ffae">

---

#### `products`のミニアイコン
<img width="547" alt="スクリーンショット 2024-03-11 17 42 43" src="https://github.com/fjordllc/bootcamp/assets/129706209/b12b4df9-0613-4309-90dc-bf233f956ca2">

---

#### `/external_entries`の普通のアイコン
<img width="708" alt="スクリーンショット 2024-03-11 17 49 33" src="https://github.com/fjordllc/bootcamp/assets/129706209/b1e38bf4-d260-41da-9b26-2f8f7c6995c0">

---

#### `/articles`のミニアイコン
<img width="695" alt="スクリーンショット 2024-03-11 17 46 32" src="https://github.com/fjordllc/bootcamp/assets/129706209/60a9a5fd-1ac7-40fd-9ad0-42fe56aa2b72">

※このページに関しては外の人向けなので、仕様のような気もします🤔

---

詳細には見れていないので、このほかにもあるかもしれません。

## 補足
こちらのIssueに取り組んでいる最中に、仕様ではなくバグであると確認しました。
- https://github.com/fjordllc/bootcamp/issues/7462

`/pages`のミニアイコンにも枠が表示されていませんが、こちらに関しては上のIssueで対応します。

## 環境
OS: MacOS
ブラウザ: chrome
chromeバージョン: 122.0.6261.69

**Comment by machida** [comment]
📝 
- reports は react
- products は react
- external_entries は vue

**Comment by hirano-vm4** [comment]
@komagata @machida 

お疲れ様です！こちら現在、取り組んでいますが、 @machida さんのコメントで以下のようにありますが

>現状の実装
reports は react
react を外したら実装
products は react
react を外したら実装
external_entries は vue
vue を外したら実装

現在は、React・Vueの状態ですが、現状のままバグを修正という認識で大丈夫でしょうか？言葉の通り`react を外したら実装` `vue を外したら実装`だと今はステイという捉え方もできたので念の為確認になります🙏

**Comment by machida** [comment]
@hirano-vm4 質問ありがとうございます！今回はvueとreactのままでお願いしますー

**Comment by hirano-vm4** [comment]
@machida 

ありがとうございます🙏承知いたしました！

**Comment by hirano-vm4** [comment]
こちら、本番環境での動作を確認したためcloseします。
