### ISSUE TITLE
ユーザー個別ページ、一覧ページのカウント数一覧にポートフォリオも追加したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7517]
## /users

<img width="440" alt="貼り付けた画像_2024_03_11_22_20" src="https://github.com/fjordllc/bootcamp/assets/168265/e04f621a-e8a2-4a0c-819c-3cfa9983cfb6">

## /users/show

<img width="808" alt="貼り付けた画像_2024_03_11_22_21" src="https://github.com/fjordllc/bootcamp/assets/168265/281b8270-8c20-482f-8fe9-48f1f2312aa1">

---

0 でない場合は、リンクにする。リンク先はそのユーザーのポートフォリオページにする。

**Comment by unikounio** [comment]
@komagata さん、 @machida さん
お疲れ様です。
リンクに関して１点質問させてください。

Issueの説明に
> 0 でない場合は、リンクにする。

とあります。
この点、**カウントが0の場合における既存項目のリンク状況**を確認したところ、ユーザー**一覧**ページはリンクされていませんでしたが、ユーザー**個別**ページではリンクされているようでした。
既存項目に合わせる形（個別ページでは0でもリンクあり）で実装してよろしいでしょうか？

**Comment by machida** [comment]
@unikounio では、他の部分もカウントがゼロのときはリンクをしない、一以上はリンクにする、で修正して統一するようお願いします。

**Comment by unikounio** [comment]
本Issueは本番環境での確認が完了したためCloseさせていただきます。
ご協力いただいた皆様ありがとうございました！
