### ISSUE TITLE
view_componentを導入する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7521]
https://github.com/ViewComponent/view_component を導入し、使うのにふさわしいと思う場所を一箇所view_component化する。

**Comment by komagata** [comment]
@reckyy 僕が言葉足らずでわかりずらかったですね、すみません。

基本的にview_componentを導入する効果が高いところをやりたいなとおもいます。

- そのview_componentが少なくとも二か所以上から使われる。（一か所からだとあまり使う意味がないので）
- インスタンス変数とviewのセットが他から切り離されている（そのcomponent以外のものをたくさん呼び出していたりせず、切り離しやすいもの）

とりあえず、ここをやろうとおもっているとおしえていただければそちらを見て判断します～。

**Comment by reckyy** [comment]
@komagata 
とんでもないです！コメントいただきありがとうございます。

現在、
- 2箇所以上でrenderされている
- 独立している

上記2点を満たすパーシャルを探すということですね。承知しました。
目星をつけたら、再度コメントにてお知らせいたします。

**Comment by reckyy** [comment]
@komagata 
お疲れ様です。ファイルを眺めて自分的に良さそうだと感じたファイルを共有します。
（この後にも出てくれば、追記しますが取り急ぎ。）

- `app/views/application/_errors.html.slim`
https://github.com/fjordllc/bootcamp/blob/033db0ed12ea2354cd2456213f8a3c0716b8ba8e/app/views/application/_errors.slim#L1-L9

  - 24箇所で使用されている
  - 渡すインスタンスが一つである

ことからポイントの作業量的にも妥当かなと感じました。
ご確認をよろしくお願いいたします。

**Comment by komagata** [comment]
@reckyy あまり影響が大きすぎないように2~3か所ぐらいで使われてるやつがいいかな～と思います。

**Comment by reckyy** [comment]
@komagata 
お疲れ様です。
少し確認なのですが、https://github.com/fjordllc/bootcamp/issues/7521#issuecomment-2003165568 では

> 基本的にview_componentを導入する効果が高いところをやりたいなとおもいます。
・そのview_componentが少なくとも二か所以上から使われる。（一か所からだとあまり使う意味がないので）
・インスタンス変数とviewのセットが他から切り離されている（そのcomponent以外のものをたくさん呼び出していたりせず、切り離しやすいもの）

とおっしゃっていますが、この2つの条件を満たすパーシャルであれば、view_componentの導入効果がそれほど高くなさそうでも問題ないということでしょうか。
それとも、この2つの条件を満たしつつ、導入効果が高いファイルを選択すべきでしょうか。

ご確認お願いいたします。

**Comment by komagata** [comment]
@reckyy 

> とおっしゃっていますが、この2つの条件を満たすパーシャルであれば、view_componentの導入効果がそれほど高くなさそうでも問題ないということでしょうか。

はい。

最終的には効果の高い場所に導入したいですが、まずはview_componentが導入できそうかを見たいので、影響範囲がそれほど大きくないところで試したいです。

その結果によってはやっぱり導入をやめるということもあるので。

そう考える理由としては、基本的にrailsプロジェクトに追加のライブラリ（gemでもnpmでも）を追加するとrailsやその他のライブラリのバージョンアップにかかるメンテナンスが大変になります。

最初にアプリを作っているときは便利なライブラリをたくさん導入したほうが楽ですが、メンテナンス時には標準以外のライブラリはなるべく使わないほうが楽です。（railsのメジャーバージョンアップ時などは特に）

最初の開発よりメンテナンスのほうが圧倒的に時間がかかるので、ライブラリは相当に効果があって、そのあともメンテし続けられる覚悟がないと導入できないものだからです。

**Comment by reckyy** [comment]
@komagata 
コメントありがとうございます。
ライブラリ導入の段階について、理解できました。ありがとうございます。
不安になったので確認なのですが、「ファイル（パーシャル）一つをコンポーネント化」であって、「ファイルの再利用可能な一部をコンポーネント化」ではない、という認識で大丈夫でしょうか。

条件を満たしつつ、影響範囲が小さいファイルをピックアップしました。
このファイルをコンポーネント化するのはどうでしょう。
https://github.com/fjordllc/bootcamp/blob/main/app/view/books/_form.html.erb

`/views/books/edit.html.erb` と `/views/books/new.html.erb` の2箇所でrenderされています。

**Comment by komagata** [comment]
@reckyy formはデータを変更するセンシティブなところなので避けたいです。

https://github.com/fjordllc/bootcamp/blob/main/app/views/works/_work.html.slim

こちらはいかがでしょうか。

**Comment by reckyy** [comment]
@komagata 
> formはデータを変更するセンシティブなところなので避けたいです。

条件ばかりに目が入ってました。申し訳ございません。

> こちらはいかがでしょうか。

条件も満たしており、良いと思います！
早速取り掛かります。

最終ご提案いただく形になり、お手数おかけし申し訳ないです。 🙇

**Comment by reckyy** [comment]
本番環境で確認できたので、closeします！
