### ISSUE TITLE
WSL2ユーザー向けにREADMEに vips インストールの手順を入れる。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7524]

**Comment by unikounio** [comment]
@komagata さん、@machida さん
お疲れ様です。
本Issueの作業方法について、3点お伺いさせてください。
- インストール手順の記載位置は[READMEの環境構築](https://github.com/fjordllc/bootcamp/blob/main/README.md#%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89)に記載されている[画像ライブラリの設定](https://github.com/fjordllc/bootcamp/wiki/%E7%94%BB%E5%83%8F%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E8%A8%AD%E5%AE%9A)ページに記載する形でよろしいでしょうか？
- 記載内容について現在は[公式Wiki](https://github.com/libvips/libvips/wiki/Build-for-Ubuntu)の内容に準じて最低限の記述にしていますが、その方向（`-y`や`--no-install-recommends`等のオプションについては書かない）で良いでしょうか？
- コマンドは`&&`で繋げた形で示しても問題ないでしょうか？
繋げた場合、最初のコマンドが失敗すると次のコマンドが実行されないと思うので、気になりました👀
（問題なければ一行の方がコピペが楽だと思うので、一旦その形で書いてあります。）

以上です。
お手数おかけしますが、ご確認のほどよろしくお願いいたします🙏

**Comment by machida** [comment]
@unikounio あー、ごめんなさい、画像ライブラリ設定ページがあったのを見逃してました🙇‍♂️そのページがあるのでREADMEには、vipsのインストールが必要であることを書いていただき、そのページにリンクをはるところまでで大丈夫です。
もし、今の画像ライブラリ設定ページでは足りない情報があれば追記をお願いしたいです🙏

**Comment by komagata** [comment]
@machida すみません、上記画像ライブラリ設定ページとそこへのリンクは @unikounio さんの投稿を受けて僕の方でつい先日作業したばかりです〜

**Comment by unikounio** [comment]
本Issueは本番環境での確認事項がありませんので、リリースに伴い完成したものと判断し、Closeさせていただきます。
