### ISSUE TITLE
ブログ（articles）が公開されたら、管理者、メンター、現役一般受講生、現役研修生に通知されてほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7534]

**Comment by hirano-vm4** [comment]
@machida 

割り当てありがとうございました！
こちらの通知は以下の2点をイメージしましたが合っていますでしょうか？

1. ページ右上のベル通知
2. メールによる通知

ご多忙の中、恐れ入りますがよろしくお願いいたします🙏

**Comment by hirano-vm4** [comment]
### メモ📝
駒形さんのレビューの際に以下の点について確認する

- 通知の文言を確認（タイトルに加えて、誰が投稿したかも含めるか）
案1：`body: "新しいブログ「#{article.titile}」を#{article.user.name}さんが投稿しました！"`
案2：`body: "新しいブログ「#{article.titile}」が投稿されました！"`

**Comment by hirano-vm4** [comment]
2024年4月25日に以下のブログがちょうど公開され、サイト内通知・メール通知をそれぞれ確認したためIssueをcloseします。

[Slerからフィヨルドブートキャンプへ。Web開発に必要な知識が学べて自信がついた【卒業生インタビューしくみ製作所様】 \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/articles/119)
