### ISSUE TITLE
WIPの日報を提出する際に内容にエラーがあると「すでに提出済み」のメッセージが表示される

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#7537]
## 概要

日報をWIP状態から編集して提出するとき、入力内容にエラーがある場合に本来のエラーメッセージに加えて、「`この日報はすでに提出済みです。`」と表示されます。

実際はエラーで提出されていないため不適切ではないでしょうか。

## 再現手順

1. 日報をWIPで保存する。
2. WIPの日報をエラー(学習時間の不正、内容の未入力など)が発生するように編集する。
3. 「提出」をクリック。
4. エラーが表示される。

## 期待される振る舞い

`この日報はすでに提出済みです。`のメッセージが出ない

## スクリーンショット

![image](https://github.com/fjordllc/bootcamp/assets/69447745/9d80859f-5921-494b-92fe-f841534a69a8)

**Comment by unikounio** [comment]
このIssueは本番環境で解消が確認できたためCloseさせていただきます。
ご協力いただいた皆様、ありがとうございました！
