### ISSUE TITLE
ステージング環境でお知らせを作成しても通知が飛ばない

### ISSUE THREAD

**Issue by naokinaokiboo** [fjordllc/bootcamp#7538]
## 概要

以下のPRで発生させてしまった不具合になります。
  - https://github.com/fjordllc/bootcamp/pull/7438

ステージング環境でメール送信時に、存在しないアドレスへのメール送信時に`Postmark::InactiveRecipientError`が発生します。
  - それにより`Job`が`Discarded`状態になり、以降の通知が送られていません。
  - 上記のPRでの変更前は、各通知が1つの`Job`として扱われていたため、特定の通知（`Job`）で`Error`が発生しても他の`Job`には影響が無かったと思われます。

## 期待される振る舞い

特定の通知で`Error`が発生しても、他の通知は送信される。

## 関連Issue

Ref: #7279

**Comment by naokinaokiboo** [comment]
@komagata 

不具合の修正方針について、事前にご相談させてください。🙏

以下のような方針で修正を考えています。
よろしくお願い致します。🙇‍♂️

1. `AcitivityDelivery`でまとめて呼び出すのをやめ、メール通知、サイト内通知をそれぞれ`ActivityMailer`と`ActivityNotifier`で個別に呼び出す
    - 理由：メール通知、サイト内通知の片方が失敗しても、もう片方の通知が行われるようにしたいため
2. `Postmark::InactiveRecipientError`だけでなく、`StandardError`も例外処理に含める
    - 理由：何らかのエラーが発生した時点で、以降誰にも通知が飛ばなくなるのを避けるため


```rb
# 参考イメージ

class PostAnnouncementJob < ApplicationJob
  queue_as :default

  def perform(announcement, receivers)
    receivers.each do |receiver|
      begin
        ActivityMailer.post_announcement(announcement:, receiver:).deliver_now
      rescue Postmark::InactiveRecipientError
        # ログ出力
      rescue StandardError
        # ログ出力
      end

      begin
        ActivityNotifier.post_announcement(announcement:, receiver:).notify_now
      rescue StandardError
        # ログ出力
      end
    end
  end
end
```

**Comment by komagata** [comment]
@naokinaokiboo 上記の方針で大丈夫です。そちらでお願いいたします〜！
