### ISSUE TITLE
期生別ユーザー一覧で43期のユーザーが表示されていない

### ISSUE THREAD

**Issue by eatplaynap** [fjordllc/bootcamp#7545]
## 概要

表題通り

## 再現手順

1. /generations にアクセス
2. 43期のユーザー一覧が他の期生と違いプレースホルダーの表示になっている

<img width="500" alt="Screenshot 2024-03-15 at 20 53 34" src="https://github.com/fjordllc/bootcamp/assets/63531341/97cc5244-53c9-4094-bdd6-0efb9591a548">

## 期待される振る舞い

43期生のユーザーも他の期生と同じく表示されて欲しい

## スクリーンショット
<img width="500" alt="Screenshot 2024-03-15 at 20 54 29" src="https://github.com/fjordllc/bootcamp/assets/63531341/b44a116d-1d37-4cb2-b837-20c94da52605">

## 環境
他の人の環境でも出てたので環境は関係ないと思います

 - OS: iOS 14.2.1 (23C71)
 - ブラウザ: Chrome
 - バージョン: 122

## 関連Issue

Ref: なし

**Comment by eatplaynap** [comment]
<img width="500" alt="Screenshot 2024-03-15 at 21 29 24" src="https://github.com/fjordllc/bootcamp/assets/63531341/3b96f7eb-7627-4d87-a211-43571f2022e4">

この期だけGETがうまくいってない

**Comment by komagata** [comment]
@eatplaynap 修正致しました～！
