### ISSUE TITLE
ユーザー一覧ページで43期生が表示されない

### ISSUE THREAD

**Issue by kyokucho1989** [fjordllc/bootcamp#7546]
## 概要

ユーザー一覧ページのうち、43期生が表示されません。

## 再現手順

1. https://bootcamp.fjord.jp/generations へアクセス

## 期待される振る舞い

43期生が表示される

## スクリーンショット

XXX

## 環境

あとで書きます。
 - ブラウザ: [e.g. chrome, safari]
 - バージョン: [e.g. 22]

## 関連Issue

Ref: #関連Issue番号

## 備考

https://bootcamp.fjord.jp/generations/43?page=2

このページだけ、ユーザー一覧はありません、と表示されます。

**Comment by kyokucho1989** [comment]
https://bootcamp.fjord.jp/users/1863

この方のページのみ表示されません。

**Comment by kyokucho1989** [comment]
@komagata  @machida 
この方の日報ページ、提出物ページ、この方が含まれるであろう検索結果も表示されません。

アイコンが関係しているかと思います。
連絡をとっていただき、アイコンを変えていただくか、一旦デフォルトに戻していただくことはできますか？

**Comment by komagata** [comment]
こちらと重複しているのでCloseします。（そっちの方がはやかったので。）
#7545
