### ISSUE TITLE
ブラウザのバックボタンで戻った時にユーザー登録ボタンが有効にならない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7553]
一度チェックボックスを外してまたチェックしないと登録ボタンが押せない。

![スクリーンショット 2024-03-18 145249](https://github.com/fjordllc/bootcamp/assets/16577/0c8f5c7b-9128-4971-9a2c-274c48fd2e40)

Ref: #7414

**Comment by naokinaokiboo** [comment]
こちらのIssueについて調査した結果を記載しておきます。

※`Edge`については、`Chromium`ベースであり、今回試した挙動も`Chrome`と同様であったため、記載していません。

## 本番環境での挙動

本番環境でそれぞれバックボタン押下時のチェックボックスと参加ボタンの状態です。

| ブラウザ | チェックボックスの状態 | 参加ボタンの状態 |
| ------- | ------- | ------- |
| Chrome | チェック状態 | 無効 |
| Safari | チェック状態 | 有効 |
| Firefox | チェック状態 | 有効 |

開発者ツールで確認したところ、`Safari`と`Firefox`に関してはバックボタン押下時にリクエストが出ておらず、`Back-Forward Cache`で表示されているのかと思います。

`Chrome`に関しては、リクエストが出ていましたし、開発者ツールの[Test back/forward cache](https://developer.chrome.com/docs/devtools/application/back-forward-cache?hl=ja)で`Back-Forward Cache`からの表示では無いことは確認済みです。

## 開発環境での挙動

| ブラウザ | チェックボックスの状態 | 参加ボタンの状態 |
| ------- | ------- | ------- |
| Chrome | チェック状態 | 無効 |
| Safari | チェック状態 | 有効 |
| Firefox | 未チェック状態 | 無効 |

- 開発環境では`Safari`も`Firefox`もバックボタン押下時にリクエストが出ていた。
- `Safari`:
  - これは、`JavaScript`が設定した状態も含めて復元しているのか、それとも`DOMContentLoaded`イベント時に既に以前の状態が復元されているのか？
  - →ログを出して確認したところ、`DOMContentLoaded`イベント時に`JavaScript`は以前の状態を取得できていた
- `Firefox`:
  - そもそも以前の状態を復元していない様子

## 別の簡単なフォームでの挙動

https://codepen.io/naoki-yoshikawa/pen/OJGWaWq

上記のように簡単なフォームの例を作成し、以下の操作をしました。

1. チェックボックスをチェック状態にする
2. 「Another page」をクリックする
3. ブラウザのバックボタンで戻る

各ブラウザでの結果は以下のようになりました。

| ブラウザ | チェックボックスの状態 | JavaScriptからの認識（DOMContentLoaded時）| Back-Forward Cache |
| ------- | ------- | ------- | ------- |
| Chrome | チェック状態 | 未チェック状態 | 無効 |
| Safari | チェック状態 | チェック状態 | 無効 |
| Firefox | チェック状態 | チェック状態 | 無効 |

- `Firefox`は開発環境とは異なり、状態を復元していていたが`DOMContentLoaded`イベント時に、`JavaScript`は以前の状態を取得できている

## 方針

- 以上から、`Back-Forward Cache`からの復元ではない場合は、`Chrome`と`Safari`,`Firefox`とでは以前の入力状態を復元するタイミングが異なるという認識です。
  - `Chrome`：`DOMContentLoaded`イベント時に以前の状態がまだ復元されていない
  - `Safari`,`Firefox`：`DOMContentLoaded`イベント時に以前の状態が復元されている
- 以下の理由から、`pageshow`イベント時にチェックボックスの状態から参加ボタンの状態を更新するように変更
  - ブラウザーのバックボタン押下時でも必ず呼ばれる
  - `DOMContentLoaded`よりも後のタイミングであり、`Chrome`の場合でも`JavaScript`からチェックボックスの以前の入力状態を正しく取得できた。

**Comment by naokinaokiboo** [comment]
本番環境で動作が確認できたのでclose致します。
