### ISSUE TITLE
プラクティス毎の提出物一覧がエラー

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7556]
https://bootcamp.fjord.jp/practices/53/products

ここがエラー

**Comment by kurumadaisuke** [comment]
@komagata 
こちら同じ事象を開発環境 / STG環境で確認することができずで、これは本番環境だけで起こっているエラーではないでしょうか🙏？

本番環境のプラクティスを調査したところ「ボウリングのスコア計算プログラム」より前の提出物で500番エラーを返していることを確認しました。
なので「ボウリングのスコア計算プログラム」より前でDBに正しくデータが保存されていないなどは考えられませんかね？🙏

この場合は、本番環境側のエラーログの内容を確認することなどは難しいのでしょうか？🙏

**Comment by komagata** [comment]
@kurumadaisuke 本番環境でだけ起こっているエラー（特定のデータでおこる）などだと思います。
本番環境のログを全部渡すといったことはできないです。

**Comment by kurumadaisuke** [comment]
@komagata 

> 本番環境のログを全部渡すといったことはできないです。

できない場合はどのようにしてこのエラー解決していけばいいのでしょうか😰？

**Comment by komagata** [comment]
@kurumadaisuke すみません、こちらのIssueは僕が担当したいとおもいます。お手間を取らせてしまってすみません。

**Comment by kurumadaisuke** [comment]
@komagata 
ご確認ありがとうございます🙇‍♂️
お手数ですがよろしくお願いいたします🙇‍♂️

**Comment by komagata** [comment]
@kurumadaisuke こちら上記のPRで修正いたしました～。

**Comment by kurumadaisuke** [comment]
@komagata 
ありがとうございます🙇‍♂️
