### ISSUE TITLE
メンター招待用の参加登録画面が欲しい

### ISSUE THREAD

**Issue by naokinaokiboo** [fjordllc/bootcamp#7582]
## 概要

Issue「招待URL作成ページが欲しい」(#7424) で企業・ロール・コースを選択して招待用URLを作成できるようになります。

ロールとして「アドバイザー」と「研修生」を選択した場合は作成されたURLにアクセスすると、それぞれ専用の登録画面が表示されますが、「メンター」を選択した場合、通常のフィヨルドブートキャンプ参加登録画面が表示されてしまいます。

ロールとして「メンター」を選択した場合に、作成されたURLにアクセスするとメンター用の参加登録画面が表示され、選択した企業・ロール・コースが参加登録画面に反映されてほしいです。

## 関連Issue

https://github.com/fjordllc/bootcamp/issues/7424

**Comment by komagata** [comment]
@naokinaokiboo これはどういうIssueでしょうか？

「参加登録画面のメンター招待時の対応」というタイトルと上記のDescriptionだとちょっと何を意味しているのかわかりませんでした。

**Comment by naokinaokiboo** [comment]
@komagata 
タイトルとDescriptionを修正致しました。🙇‍♂️

**Comment by komagata** [comment]
@naokinaokiboo ありがとうございます。よくわかるようになりました。

**Comment by MikotoMakizuru** [comment]
本番でメンター登録までの動作確認は行えないので komagata さんに確認したところ、この場合 Close して問題ないとのことでしたので Close します〜

**Comment by MikotoMakizuru** [comment]
本番でメンター登録までの動作確認は行えないので komagata さんに確認したところ、この場合 Close して問題ないとのことでしたので Close します〜
