### ISSUE TITLE
unconfirmed_link.vueとunconfirmed_links_+open_button.vueを非vue化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7590]
vueを使わないようにするためにタイトルになっているファイルを使っている箇所を普通のHTMLでの実装に変える。

元々Reactに変更する予定でしたが、最終的にはHotwireにする予定なので、VueもReactも使わない実装にしたいです。（普通にviewに表示する方式）

**Comment by naokinaokiboo** [comment]
@komagata @machida 

本Issueの対応方針について確認させて下さい🙏

## 調査内容

調査しましたところ、本Issueで対象になっている各vueファイルは現在使用されていないようです。

### unconfirmed_link.vue

現在、どこからも参照されておらず使用されていないと考えられます。

以下のPRで参照していたファイル(`app/javascript/components/reports.vue`)が既に削除されているようです。

[企業ページの日報一覧が重複して表示されている問題を修正した](https://github.com/fjordllc/bootcamp/pull/6827)



### unconfirmed_links_open_button.vue

現在、`app/javascript/products.vue`から参照されていました。

しかし、`unconfirmed_links_open_button.vue`の使用箇所は、以下のPRでReactに置き換えられているようです。
（`app/javascript/products.vue`はメンターのダッシュボードには使用されているが、提出物ページとしては使用されておらず不要なコードが残った状態）

[提出物ページのReact化](https://github.com/fjordllc/bootcamp/pull/6988)

## 方針

本Issueの目的としては、以下の２つのvueファイルを削除した上で、`app/javascript/products.vue`の使用されていない部分のコードを整理・削除するということでよいでしょうか？
  - unconfirmed_link.vue
  - unconfirmed_links_open_button.vue



以上、ご確認よろしくお願い致します。🙏

**Comment by komagata** [comment]
@naokinaokiboo 使われていない場合は削除でOKです～！

**Comment by naokinaokiboo** [comment]
こちら、本番環境で動作確認済みのためcloseします。
