### ISSUE TITLE
参考図書のスラスラ読める JavaScriptふりがなプログラミングを増補改訂版に差し替え

### ISSUE THREAD

**Issue by mh-mobile** [fjordllc/bootcamp#7593]
2022/8/23にスラスラ読める JavaScriptふりがなプログラミングの増補改訂版が発売されているので、
こちらに差し替える。

スラスラ読める JavaScriptふりがなプログラミング 増補改訂版 ふりがなプログラミングシリーズ
https://www.amazon.co.jp/dp/B0BCJN1V1M

ref. 参考図書
https://bootcamp.fjord.jp/books

**Comment by machida** [comment]
@mh-mobile Issue登録ありがとうございます！！差し替えましたー💪
