### ISSUE TITLE
相談部屋の上部のパーツを変更したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7595]
管理者ではないユーザーの相談部屋ページの上部は

<img width="1254" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/d5849f72-c645-4df2-8f1e-b16a65f29303">

このように表示されている。

これを、

<img width="1254" alt="貼り付けた画像_2024_03_26_3_28" src="https://github.com/fjordllc/bootcamp/assets/168265/edd42f28-e58c-420d-b611-7cb3231886cb">

このように変更したい。リンク先も変更する。

※管理者でログインした場合は変更なし。

**Comment by nakamu-kazu222** [comment]
こちらのIssueの本番環境での動作確認は管理者ではできないので、私の本番環境で動作確認を行いました

closeいたします

**Comment by unikounio** [comment]
@nakamu-kazu222 さん
お疲れさまです！
相談部屋だけでなく、ユーザーページ全体のヘッダーが変更されているかもしれません。
![スクリーンショット 2024-04-18 174727](https://github.com/fjordllc/bootcamp/assets/125527162/501b2c66-1835-4821-b0bd-fad1ca41ea82)

ご確認いただけますと幸いです🙏

**Comment by nakamu-kazu222** [comment]
@unikounio cc: @komagata @machida

お疲れ様です！
ご報告いただきありがとうございます！

私の方でも再現しました！
修正いたします

**Comment by nakamu-kazu222** [comment]
@komagata @machida

こちらの不具合を修正しますが、別のPRを作成して修正した方がよろしいでしょうか？
お手隙の際に、ご確認いただけると幸いです

**Comment by machida** [comment]
@unikounio @nakamu-kazu222 

ちょっと今出先でリンクが貼れないのですが、タイトルが長いと表示できないバグを修正するために今のように二段にしています。
なので、これはバグではないのでそのままで大丈夫ですー。

**Comment by machida** [comment]
@unikounio @nakamu-kazu222 
あ、違った。デザインではなく、すべてのこの部分が相談部屋になっているということですね！
これは早急に修正してhotfixとしてりりーすしたいです🙏

**Comment by nakamu-kazu222** [comment]
@machida 

お疲れ様です
下記PRで、修正しました
https://github.com/fjordllc/bootcamp/pull/7708

ご確認のほど、よろしくお願いいたします
