### ISSUE TITLE
学習の進んだパーセンテージのバーをユーザー一覧に出したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#760]

**Comment by matt-note** [comment]
- [ ] app/views/users/practices/_completed_practices_progress.html.slim でプログレスを出力している。

**Comment by matt-note** [comment]
ユーザー一覧ページにプログレスバーのみを出力。
![Screenshot from 2019-04-26 21-59-05](https://user-images.githubusercontent.com/39484102/56810660-cd82b800-6871-11e9-9571-64a5f9ca8eec.png)

![Screenshot from 2019-04-26 21-58-49](https://user-images.githubusercontent.com/39484102/56810659-cd82b800-6871-11e9-9717-0cc97b0f4f31.png)
