### ISSUE TITLE
提出物ページの見出しがおかしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7602]
<img width="747" alt="貼り付けた画像_2024_03_27_10_29" src="https://github.com/fjordllc/bootcamp/assets/168265/97735be2-aedc-4861-92da-7b10d9b9d3a6">

`提出物:` は不要。

<img width="747" alt="貼り付けた画像_2024_03_27_10_29" src="https://github.com/fjordllc/bootcamp/assets/168265/102189ff-f0f6-4793-b1e1-6cb49930208d">

title タグはそのまま。上記の画像の部分だけを修正する。

**Comment by nakamu-kazu222** [comment]
本番環境で動作確認完了しましたので、closeいたします
