### ISSUE TITLE
提出物詳細で管理者にも研修終了日を表示する

### ISSUE THREAD

**Issue by a-kuroki-gs** [fjordllc/bootcamp#7603]
## 概要

現在、提出物一覧・詳細画面において、企業研修生は研修終了日が表示されるようになっておりますが
表示対象が以下のようになっており、一覧と詳細でズレがあるため仕様を合わせたいです。
- 一覧画面：管理者・メンター
- 詳細画面：メンター

## 再現手順

1. 管理者でログインする(メンターではない)
2. /products にアクセスする
3. ( 一覧画面では、研修生に研修終了日が表示されることを確認する )
4. 任意の研修生の提出物をクリックする
5. 詳細画面では、研修終了日が表示されない

## 期待される振る舞い

詳細画面でも管理者とメンターに表示される。

## スクリーンショット
- 一覧画面(管理者・メンター共に)
![image](https://github.com/fjordllc/bootcamp/assets/133615511/951a2326-29a4-4d8b-9cf7-1bd6d6453fb7)

- 詳細画面(メンター)
![image](https://github.com/fjordllc/bootcamp/assets/133615511/24d48413-baab-49a0-a5fb-5e0be67d0489)

- 詳細画面(管理者)
![image](https://github.com/fjordllc/bootcamp/assets/133615511/9edd5f10-7f14-431c-80be-ef354332052f)

## 環境

- OS: [Windows 10 Pro]
- ブラウザ: [chrome]
- バージョン: [122.0.6261.95]

## 関連Issue

Ref: #6297 #6298

**Comment by unikounio** [comment]
Descriptionの概要部分を一部修正させていただきました。
![スクリーンショット 2024-04-24 152326](https://github.com/fjordllc/bootcamp/assets/125527162/4ff1dea5-7dbf-4743-8598-28af29db186f)

**Comment by unikounio** [comment]
本Issueは本番環境での確認が完了したためCloseします。
ご協力いただいた皆様、ありがとうございました！
