### ISSUE TITLE
ユーザー一覧の絞り込みのルールを変更。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7614]
## 現状

<img width="1251" alt="貼り付けた画像_2024_03_29_16_22" src="https://github.com/fjordllc/bootcamp/assets/168265/8fb10af6-36b0-4beb-b80b-18325c203bae">

## こうしたい

<img width="1320" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/eba428d0-fcf7-4fc2-b24b-9f539a6e0930">

---

- 現在、「現役生」は リンク先が`/users?target=student_and_trainee` になっているが、`/users?target=student`に変更する。
- 「現役 + 研修生」を追加する。リンク先を`/users?target=student_and_trainee`にする。（要するに、現在の「現役生」を「現役 + 研修生」にし、「現役生」を新たに追加する感じ）。

---

関連Issue: https://github.com/fjordllc/bootcamp/issues/7351

- 「現役生」は一般現役受講生 + 研修生を表していたが、わかりにくいので、「現役生」は一般現役受講生とすることにした。
- 「一般現役受講生 + 研修生」は「現役 + 研修生」と表すことに変更する。

**Comment by unikounio** [comment]
@komagata さん、@machida さん
お疲れさまです！
作業を進める中で次の点が気になったので確認させてください🙏
- 「現役＋研修生」への文言変更はロケールファイルで設定するという認識でよいか
	- ロケールファイルで`student_and_trainee`に対応する文字列を変更すると、`/admin/users`における絞り込みタブの表示も変更されるがよいか

お手すきの際にご回答いただけますと幸いです！
よろしくお願いいたします。

**Comment by komagata** [comment]
@unikounio ほかのタブと同じ方法でお願いします。

**Comment by unikounio** [comment]
@komagata さん、@machida さん
お疲れ様です。
本Issueについて本番環境での確認を行ったところ、「現役 + 研修生」タブで表示されるユーザ数が「現役生」タブと「研修生」タブの合計になっていませんでした。
**「現役 + 研修生」タブで表示されるユーザーは、「現役生」タブと「研修生」タブの合計でなくてもよいのでしょうか？**
ローカルやステージング環境のデータでは気づきにくい点だと感じたため、念のため確認させてください🙏

### 現状
「現役 + 研修生」タブの人数が「現役生」タブと「研修生」タブの合計になっていません。
具体的には、「[研修生」と「卒業生」ロールが付与されているユーザー](https://bootcamp.fjord.jp/users/1063)が、「現役 + 研修生」タブでは表示されず、「研修生」タブでは表示されています。
これは、「現役 + 研修生」タブの`scope`が『「現役生」と「研修生」以外のロールを持っていないこと』なのに対して、「研修生」タブの`scope`が『「研修生」ロールを持っていること』であることによります。

### 意見
- 「現役 + 研修生」タブが現在学習中の受講生を表示する形になっているのは直感的
- メンターモードでなければタブごとのユーザ数は表示されないので、一般受講生は気にならなそう

上記2点から、このままでも良いよう思いました。

**Comment by komagata** [comment]
@machida こちらいかがでしょう～？

**Comment by machida** [comment]
@unikounio @komagata 

ありがとうございます！
このままで大丈夫です。
現在、卒業生でかつ研修生の場合、手動で研修生フラグを消す対応を行っています。一人、抜けがあり数字にずれがありました。

研修生で卒業までやりきるのはイレギュラーなケースなので、当分は手動の対応でいいと考えていますが、例えば研修生一覧には現役の研修生だけを表示するなどの対応が必要になったら別Issueで対応したいと思いますー

**Comment by unikounio** [comment]
@komagata さん、 @machida さん
ご確認ありがとうございます✨このままにさせていただきます！
ご確認いただいた件を踏まえて、**本番環境での確認についてもお願いさせてください**🙏
メンターモードにした際、選択したタブ名の横に表示されるユーザ数をご確認いただけますと幸いです。
![スクリーンショット 2024-06-06 150600](https://github.com/fjordllc/bootcamp/assets/125527162/d3b7b23f-0e04-40ff-a344-bc3231d40ae7)

**Comment by machida** [comment]
@unikounio 本番で確認しましたー🙆

**Comment by unikounio** [comment]
@machida さん
ご確認ありがとうございます！
本番環境での確認が完了しましたので、本IssueはCloseさせていただきます。
