### ISSUE TITLE
BookmarkButtonがRules of Hooksに違反していてエラーが出る

### ISSUE THREAD

**Issue by dowdiness** [fjordllc/bootcamp#7629]
## 概要

自分の手元の開発環境でBookmarkButtonが含まれているページを開くとエラーが出てBookmarkボタンが表示されませんでした。

```sh
Warning: React has detected a change in the order of Hooks called by BookmarkButton. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useState                   useState
2. useContext                 useContext
3. useRef                     useRef
4. useRef                     useRef
5. useRef                     useRef
6. useRef                     useRef
7. useRef                     useRef
8. useRef                     useRef
9. useMemo                    useMemo
10. useCallback               useCallback
11. useState                  useState
12. useLayoutEffect           useLayoutEffect
13. useEffect                 useEffect
14. useDebugValue             useDebugValue
15. useRef                    useRef
16. useCallback               useCallback
17. useCallback               useCallback
18. useLayoutEffect           useLayoutEffect
19. useLayoutEffect           useLayoutEffect
20. useLayoutEffect           useLayoutEffect
21. useDebugValue             useDebugValue
22. undefined                 useEffect
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at BookmarkButton (http://localhost:3000/packs/js/application-18e7b40….js:2200:29)
```

実際に[BookmarkButton](https://github.com/fjordllc/bootcamp/blob/main/app/javascript/components/BookmarkButton.jsx)を確認してみると、[Rules of Hooks](https://react.dev/reference/rules/rules-of-hooks#:~:text=%F0%9F%94%B4%20Do%20not%20call%20Hooks%20after%20a%20conditional%20return%20statement.)で定義されているルールの

```
🔴 Do not call Hooks after a conditional `return` statement.
```

に違反しているコードがありました。

試しに手元でルールを守ったコードに変えたらエラーが出なくなりました。

ついでに`eslint-plugin-react-hooks`を使うようにeslintに設定を追加したいです。

https://www.npmjs.com/package/eslint-plugin-react-hooks

## 再現手順

1. 任意のユーザーでログインする
2. /reports/12168338 にアクセス
3.  Bookmarkボタンが表示されない

## 期待される振る舞い

[Rules of Hooks](https://react.dev/reference/rules/rules-of-hooks)を守る。

## スクリーンショット

<img width="1440" alt="スクリーンショット 2024-04-03 11 08 57" src="https://github.com/fjordllc/bootcamp/assets/1616717/8d3da647-e215-4485-8fff-7c1c28fa7d4f">

## 環境

 - OS: [Mac]
 - ブラウザ: [chrome]
 - バージョン: [122]

**Comment by kyokucho1989** [comment]
@dowdiness 
おはようございます。自分が担当していたIssueですね、、　申し訳ないです。
#5114 

上記Issueはまだ本番環境へリリースされていませんが、development環境では問題なく表示されています。

<img width="1065" alt="スクリーンショット 2024-04-04 5 33 38" src="https://github.com/fjordllc/bootcamp/assets/8443743/5a445576-3797-442f-9e06-5bd7aec32328">

なぜローカルのみでエラーが発生してしまうのかわかりませんが、報告まで。

**Comment by komagata** [comment]
@kyokucho1989 

> 上記Issueはまだ本番環境へリリースされていませんが、development環境では問題なく表示されています。

> なぜローカルのみでエラーが発生してしまうのかわかりませんが、報告まで。

上記は"development環境"と"ローカル"を同じ意味で使っていますでしょうか？
スクリーンショットはstaging環境だったのでちょっと混乱してしまいました。

**Comment by kyokucho1989** [comment]
@komagata 
すみません、言葉を間違えてました。
staging環境の誤りです。

**Comment by dowdiness** [comment]
@kyokucho1989 

すいません言葉不足で書いていませんでしたが、このエラーはmainではない下記のPRのコメントのブランチで起こりました。

https://github.com/fjordllc/bootcamp/pull/7449

エラーが起こるようになった原因はおそらく追加したコンポーネントで新たにuseSWRを呼び出しているからです。細かくは書きませんがuseSWRはkeyによってアプリ全体でデータ（とキャッシュ）の共有をしています。useSWRの呼ばれる数が増えた影響でhookの呼ばれる順番が変わってしまったのだと思います。

実際にエラーメッセージを見たところ、22番目のhookの前回のレンダーがundefinedなのに次のレンダーではuseEffectになっています。

**Comment by kyokucho1989** [comment]
@dowdiness 
なるほど。ありがとうございます。
今後、私は何かやらなくてはいけない作業はありますか？
