### ISSUE TITLE
Q&Aの質問の作成者をメンターと管理者だけ変更できるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7632]
<img width="532" alt="貼り付けた画像_2024_04_08_19_52" src="https://github.com/fjordllc/bootcamp/assets/168265/1f186d32-5e39-495c-8a27-6b98f869fae4">

インクリメンタルサーチでユーザーを検索指定したいです。

<img width="335" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/618a6eba-bdca-4b9f-a353-8d8b44636df6">

**Comment by nishitatsu-dev** [comment]
本番環境で動作確認できたのでクローズします。
