### ISSUE TITLE
「修了プラクティス」と「修了したプラクティス」の数字がずれている

### ISSUE THREAD

**Issue by SuzukaHori** [fjordllc/bootcamp#7635]
## 概要
個別プロフィールページ（`https://bootcamp.fjord.jp/users/:id`）で、右側の「修了したプラクティス」の数字と、左側の「修了プラクティス」の数字がずれています。
<img width="1336" alt="スクリーンショット 2024-04-04 12 03 23" src="https://github.com/fjordllc/bootcamp/assets/129706209/5433433d-695b-4c97-8ec0-153b6bc1d897">
他の人のプロフィールページも確認したところ、ほぼ全ての人が1~5ぐらいずれているように見えました。

## 期待される振る舞い
「修了したプラクティス」の数字と、「修了プラクティス」の数字が一致すること。

**Comment by kyokucho1989** [comment]
@komagata 
おはようございます。数が不一致となる原因がわかりました。また、今後の方針を確認したいため書き込みます。

**原因**：進捗率に含まないプラクティスを設定する機能があったため

下記のPRより、プラクティス作成時に、そのプラクティスを進捗の計算に含む/含まないを設定できるようになっています。
https://github.com/fjordllc/bootcamp/pull/1479

また、下記PRによって進捗率が%表記から「x/x」 という表記に変わったため、差異がわかりやすくなっています。
https://github.com/fjordllc/bootcamp/pull/3191

**方針の確認**
私は以下の二つうち、どちらかの方針で進めたいと思っています。

1. 「進捗の%に含まない~」 は考慮せずに「修了したプラクティス」の数字を「修了プラクティス」へ合わせる
2. 進捗バーの表示を%表記に戻す（個数はそのまま）

どちらが良いでしょうか。また、これとは別の方針をとったほうが良いでしょうか。

以上です。

**Comment by komagata** [comment]
@kyokucho1989 なるほどです。

@machida う～ん、これどうするのがいいですかね～？
どっちかといえば１かな～ぐらいです。

**Comment by machida** [comment]
@kyokucho1989 @komagata 

少しUIに手間がかかりますが、以下のようにお願いします。

修了したプラクティス合計数96…A
修了した必須プラクティス91…B
卒業までに必要な必須プラクティス合計数108…C

とします。

***

進捗バーの横の数字は % の表記にしつつ、進捗バーのエリア(数字部分も含む)クリックをすると、以下の数字が表示されるようにしたいです。クリックしたら表示されるところを実装してくれたら、デザインはmachidaがやります。

A(必須: B / C) 
96(必須: 91 / 198)

***

プロフィールページの修了プラクティスの数字は、

A(必須: B) としたいです。
96(必須: 91)

**Comment by kyokucho1989** [comment]
@machida @komagata 
ありがとうございます！
その方針で実装します！

**Comment by kyokucho1989** [comment]
本番環境で確認ができましたので、closeします。

**Comment by kyokucho1989** [comment]
@komagata  @machida 
すみません、こちらのIssueですが、ポイントが割り振られていませんでした。
ポイントの割り当てをお願いします。
個人的には2pt程度かと思います。

**Comment by komagata** [comment]
@kyokucho1989 ポイントを割り当てさせていただきました～

**Comment by kyokucho1989** [comment]
動作確認できましたのでクローズします。
