### ISSUE TITLE
Discord認証の解除ができるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7664]

**Comment by yocchan-git** [comment]
@machida さん

現状下記のようなDiscord連携解除リンクになっています。
Githubと似せたのですが、ご確認いただけますと嬉しいです🙇‍♂️

[![Image from Gyazo](https://i.gyazo.com/f759a76b6ba7e7860e30f6ca84588422.png)](https://gyazo.com/f759a76b6ba7e7860e30f6ca84588422)

[![Image from Gyazo](https://i.gyazo.com/347f69af46121db14099238e6511c331.png)](https://gyazo.com/347f69af46121db14099238e6511c331)

**Comment by machida** [comment]
@yocchan-git ありがとうございます！見た目、文言はそれでOKですー🙆対応ありがとうございます🙏これでレビューに進めていただきたいですー

**Comment by yocchan-git** [comment]
machidaさん
迅速な対応ありがとうございました！

**Comment by yocchan-git** [comment]
本番環境の動作確認OKでした！
Closeします
