### ISSUE TITLE
特定のページでの見出しが表示されていない

### ISSUE THREAD

**Issue by reckyy** [fjordllc/bootcamp#7673]
## 概要

ウィンドウサイズを半分にした時に、見出しが表示されない（隠れている？）状況が起きています。
ウィンドウサイズを大きくすると、正しく表示されます。
特定のユーザーの情報に関するページ（そのユーザーの日報、プラクティス一覧、ダッシュボード等）でこの状況が起きています。
一方、お知らせやQ&Aなど一般的なページでは正しく表示されています。

### 補足
ただし、このバグIssueを登録するにあたり、FBCのDocsを参照しようとしたら、そのページでも同様の状況が発生していたので、確かな再現条件は不明です。。（ユーザーがDocsを投稿しているから、ユーザーの投稿物 = ユーザーに関する情報という認識？）

## 再現手順

1. ウィンドウサイズを画面半分にする
2. ユーザーの個別の情報ページにいく。（プラクティスでも、ダッシュボードでも、相談ページでも）
3. 見出しが見切れている。

## 期待される振る舞い
正しく表示される。

## スクリーンショット
<img width="837" alt="スクリーンショット 2024-04-14 10 40 18" src="https://github.com/fjordllc/bootcamp/assets/106903482/4f1ec11f-8879-4ada-946f-4e24262c4011">

### 補足の写真（Docsの文字が表示されていない）
<img width="837" alt="スクリーンショット 2024-04-14 10 55 46" src="https://github.com/fjordllc/bootcamp/assets/106903482/d89ec637-0c34-4e44-8ac1-1abb143cc6cc">

**確かに見出しは存在している。**
<img width="837" alt="スクリーンショット 2024-04-14 10 56 11" src="https://github.com/fjordllc/bootcamp/assets/106903482/36b74787-6b13-492c-966c-ede11bc43a8a">

**また、その現象が起きていないページもある。**
<img width="823" alt="スクリーンショット 2024-04-15 16 26 32" src="https://github.com/fjordllc/bootcamp/assets/106903482/a74e00bc-07dc-476e-affc-479b960b5e97">

## 環境

 - OS: Sonoma 14.2（Macbook M1）
 - ブラウザ: chrome

**Comment by komagata** [comment]
@reckyy すみません、「ユーザーの情報に関する見出し」が何を意味しているのかわかりませんでした。
もうすこしご説明いただけますとありがたいです。

また、windowsサイズによってCSSを変えている（レスポンシブル）にしているのでスマホ用の見た目になっているのであればバグではないかもしれません。

**Comment by machida** [comment]
@reckyy 

> ウィンドウサイズを半分

人によって半分の値は変わるので、具体的なpxを教えていただけますでしょうか。

**Comment by reckyy** [comment]
> @reckyy すみません、「ユーザーの情報に関する見出し」が何を意味しているのかわかりませんでした。 もうすこしご説明いただけますとありがたいです。

タイトルと、概要を変更しました。

> また、windowsサイズによってCSSを変えている（レスポンシブル）にしているのでスマホ用の見た目になっているのであればバグではないかもしれません。

この状況が起きていないページもあるので（こちらも追記しています）、不具合だとは思います。

**Comment by reckyy** [comment]
@machida 

> 人によって半分の値は変わるので、具体的なpxを教えていただけますでしょうか。

840（幅）px
929（高さ）px

です。

ちなみにですが、幅を745pxまで狭めると見えるようになります。

[![Image from Gyazo](https://i.gyazo.com/64875d90ac2a7d739208791a1952c05e.gif)](https://gyazo.com/64875d90ac2a7d739208791a1952c05e)
また反対に、840pxから幅を広げていくと見えるようにもなります。

[![Image from Gyazo](https://i.gyazo.com/a9330ac960593719f641b024578664d8.gif)](https://gyazo.com/a9330ac960593719f641b024578664d8)

**Comment by machida** [comment]
@reckyy ありがとうございます！こちら対応します−

**Comment by komagata** [comment]
@reckyy 詳細情報ありがとうございます～！
