### ISSUE TITLE
提出物提出後のメッセージに「レビューをまたずに次に進むように」という内容を追加する。

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7676]
レビューが返ってくるのが遅いという連絡があり「７日以内に返す」というのが伝わってないようだったのと、「レビューを待たずに次に進む」ということがわかれば困りごとが減ると思うので。

**Comment by machida** [comment]
@komagata 

<img width="1417" alt="貼り付けた画像_2024_04_15_14_37" src="https://github.com/fjordllc/bootcamp/assets/168265/180bb477-6285-4ec2-a272-468b289fbee8">

すでに、そのようになってますー

**Comment by komagata** [comment]
@machida あ、ほんとですね！Closeしたいとおもいます‘
