### ISSUE TITLE
【メンター向け】提出物確認のデッドラインを変更する

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#7678]
メンターでログインすると現状はトップページに未アサインの提出物について

- 5日経過
- 6日経過
- 7日以上経過

のアラートが出ますが、これを1日ずつ早めて

- 4日経過
- 5日経過
- 6日以上経過

のようにしたいです。

（Discordの通知も同様）

## 背景
現状「7日以内にレビューする」というルールになっているが、これを少しずつ早めていきたいため。

## 歓迎要件
固定値でアラートを設定するのではなく、システム管理者権限で閾値を上げ下げできるとなおベター。
（今後はコードの修正無しにデッドラインを変更可能にする）

**Comment by nakamu-kazu222** [comment]
@komagata @machida 

お疲れ様です

本Issueで、未アサインの提出物のアラートの閾値をコードの修正無しに設定することを目指しています
そこで、以下の画像のように管理者のダッシュボードで閾値設定をテキストボックスでできるようにしようと考えていますが、
この方法でよろしいでしょうか？
- 例えば、5で設定すると、`5日経過、6日経過、7日以上経過`のアラートになるという動作です

![スクリーンショット 2024-04-19 22.43.53.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0NGQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--259825f0bd3fbba3f108e54c401ff4361cc37600/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202024-04-19%2022.43.53.png)

お手隙の際に、ご確認いただけると幸いです

**Comment by machida** [comment]
@nakamu-kazu222 ありがとうございます！いいですね👍数字はそこまで大幅に変えることはないのでselectタグが良さそうですー。

- 1, 2, 3
- 2, 3, 4
- 3, 4, 5
- 4, 5, 6
- 5, 6, 7

の選択肢を用意していただきたいです。

滅多に変えることはないと思うので、もっと目立たない場所に置きたいですが、その辺のデザインは僕がやります。

**Comment by machida** [comment]
選択肢の数字の表現はちゃんと考えたいと思いますー

**Comment by nakamu-kazu222** [comment]
@machida

ご回答いただきありがとうございます！

承知いたしました！
selectタグでご回答いただいた選択肢を選択できるように実装いたします

**Comment by nakamu-kazu222** [comment]
@komagata @machida

お疲れ様です

本Issueで、/products/unassignedの未アサインの提出物のアラートの対応はした方がよろしいでしょうか？

お手隙の際に、ご確認いただけると幸いです

<img width="1272" alt="スクリーンショット 2024-04-25 12 01 14" src="https://github.com/fjordllc/bootcamp/assets/126838748/7d04737d-e47a-449a-a619-0cd28235c0d3">

**Comment by machida** [comment]
@nakamu-kazu222 
すいません、

> /products/unassignedの未アサインの提出物のアラートの対応

とは何を指してますでしょうか？
可能であればキャプチャのその部分に目標を付けるなどお願いしたいです。

今回の提出物の確認締め切り日変更に関係するところでしたら対応をお願いしたいです🙏ポイントの追加についてはMTGのときに話し合いたいと思います。

**Comment by nakamu-kazu222** [comment]
@machida

申し訳ございません、説明不足でした
/products/unassignedの未アサインの提出物のアラートを`7日以上経過`から`6日以上経過`に変更する対応を指していました
- 以下が対応の具体です
  - `7日以上経過、6日経過、5日経過`の未アサインの提出物をアラートにしておりますが、これを、`6日以上経過、5日経過、4日経過`のアラートに変更する
  - `7日以上経過`ではなく、`6日以上経過`の提出物を表示するように閾値を低くする
<img width="1272" alt="スクリーンショット 2024-04-25 12 01 14" src="https://github.com/fjordllc/bootcamp/assets/126838748/320a25fa-586a-463e-8c99-e93b9302a5c3">


質問をしましたが、個人的には、今回の提出物の確認締め切り日変更に関係するところなので対応したいと思っております

**Comment by machida** [comment]
@nakamu-kazu222 すいません！メッセージを見逃してました🙇‍♂️

> 7日以上経過、6日経過、5日経過の未アサインの提出物をアラートにしておりますが、これを、6日以上経過、5日経過、4日経過のアラートに変更する

この対応でお願いしたいです🙏

-----

以下をselectタグで選択できる（selectの選択肢（option）は、数字だけじゃなくもっとわかりやすい言葉にしたい）。

- 1, 2, 3
- 2, 3, 4
- 3, 4, 5
- 4, 5, 6
- 5, 6, 7


現在は、

（赤）7日以上経過、（オレンジ）6日経過、（黄色）5日経過、4日経過、3日経過、2日経過、1日経過、今日提出

変更後、「3, 4, 5」を選択した場合、
（赤）5日以上経過、（オレンジ）4日経過、（黄色）3日経過、2日経過、1日経過、今日提出

変更後、「2, 3, 4」を選択した場合、
（赤）4日以上経過、（オレンジ）3日経過、（黄色）2日経過、1日経過、今日提出

となるようにお願いします。

**Comment by nakamu-kazu222** [comment]
@machida

お疲れ様です！
こちらこそ勝手に進めてしまい申し訳ございません🙇‍♂️

ご回答いただきありがとうございます！
ご回答いただいた仕様と私が想像していた仕様が一致していたので進捗に問題はございません

リファクタリング、テスト修正が終わり次第、デザインの依頼をさせていただきます！

**Comment by machida** [comment]
@nakamu-kazu222 いえいえ、返信が遅くなってすいませんでした🙇‍♂️想像通りで良かったですー✨

**Comment by komagata** [comment]
@machida , @JunichiIto （CC: @nakamu-kazu222 ）

こちらの仕様についてチェックできておらず申し訳ありません。
下記の実装をみて初めて気づきました。

https://github.com/fjordllc/bootcamp/pull/7732/files

こちら、このためだけにテーブルを作って設定を保存して、変更UIも作る方式ではなく、定数か設定ファイルで一つだけ値を指定しておく（`DEADLINE = 4`とか）の方がいいのではないかと思います。

理由はこの値は滅多に変えない値であって定数や設定ファイルといった最小限の実装でも十分だからです。

**Comment by JunichiIto** [comment]
@komagata 
そうですね、コードが必要以上に膨れ上がって複雑になるようなら定数で管理でも僕は全然いいと思います！

**Comment by nakamu-kazu222** [comment]
@JunichiIto (CC: @komagata, @machida)

お疲れ様です！
先ほど、開発ミーティングで @komagata さん、@machida さんと確認いたしまして、定数で管理するようにしたいと思います

ご回答いただきありがとうございました！

**Comment by komagata** [comment]
@JunichiIto ありがとうございます！

@nakamu-kazu222 よろしくおねがいします。（DEADLINEという名前はそれだけだとなんの数字を指しているのかわからないので他の名前を考えてみてください～）

**Comment by nakamu-kazu222** [comment]
@komagata

> DEADLINEという名前はそれだけだとなんの数字を指しているのかわからないので他の名前を考えてみてください～

承知いたしました

また、wikiに提出物確認のデッドラインを変更する方法(定数を変更する方法)を記載しようと考えておりますがよろしいでしょうか？

**Comment by komagata** [comment]
@nakamu-kazu222 そこまでやるのは大変ですが、良い作法だと思いますのでお願いします～。
