### ISSUE TITLE
[管理画面のユーザー一覧]管理画面のユーザー一覧 > アドバイザー から退会ユーザーは省き、退会したアドバイザーは退会者一覧に加えたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7685]
管理者でログインし、
/admin/users?target=adviser
にアクセスすると、アドバイザー一覧に遷移する。

今のアドバイザー一覧は退会したアドバイザーも含まれるが、これを変更し、退会したアドバイザーは
/admin/users?target=retired
このページの退会者一覧に表示されるようにしたい。

さらに、
/admin/users?target=retired
この退会者一覧はロール関係なく（研修生も）全ての退会者が表示されるようにしたい。

**Comment by nakamu-kazu222** [comment]
本番環境で動作確認完了しましたので、closeいたします
