### ISSUE TITLE
作品個別にリアクションがほしい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7695]
作品個別（ポートフォリオの個別ページ）

<img width="929" alt="貼り付けた画像_2024_04_16_12_08" src="https://github.com/fjordllc/bootcamp/assets/168265/72216906-0a14-4237-8fe8-5738babc2667">

これを

<img width="956" alt="貼り付けた画像_2024_04_16_12_09" src="https://github.com/fjordllc/bootcamp/assets/168265/63987dcb-59b3-4778-a2b7-075ab69dd06f">

ここに設置したい。

**Comment by komagata** [comment]
:memo: VueやReactを使わないVanilla JSでお願いしたいです〜（hotwireに移行予定のため）
