### ISSUE TITLE
日報一覧（全て、未読）を非JS化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7718]
タイトルになっているファイルを使っている箇所を普通のHTMLでの実装に変える。（普通のscaffoldっぽいもの）
最終的にはHotwireにする予定なので、VueもReactも使わない実装にしたいです。（普通にviewに表示する方式）

**Comment by naokinaokiboo** [comment]
@komagata @machida 
お疲れ様です。
こちらのIssueの本番環境での動作確認をお願い致します。🙏

未チェックの日報一覧ページ（`/reports/unchecked`）について、以下の各内容を確認頂きたいです。
- ページネーションが動作しているか
- 各テキスト・アイコンのリンク先が正しいか
- `未チェックの日報を一括で開く`ボタンが動作しているか

（※全ての日報一覧ページに関して確認済みです。）

**Comment by komagata** [comment]
@naokinaokiboo 本番環境で確認しました～。
