### ISSUE TITLE
ブログのX共有で記事のタイトルが入らない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7753]
![スクリーンショット 2024-05-03 015119](https://github.com/fjordllc/bootcamp/assets/16577/f4d48828-9fec-489f-b80c-85bb9a24a765)

**Comment by komagata** [comment]
@88-99 他のIssueが終わりましたらこちらをお願いできればありがたいです～

**Comment by 88-99** [comment]
@komagata 
先日ご連絡させていただきましたが、都合により休会させていただく予定ですので、他の方にお願いいたします🙏
誠に申し訳ございません。

**Comment by 88-99** [comment]
@komagata 
先日ご連絡させていただきましたが、都合により時間が取れず休会させていただく予定です。他の方にお願いいただけますでしょうか🙏
誠に申し訳ございません。

**Comment by komagata** [comment]
@88-99 かしこまりました～！

**Comment by Shrimprin** [comment]
@komagata @machida 
お疲れ様です！
仕様の確認とイシュー外で気になる箇所を見つけたため報告させていただけますでしょうか。

### 【仕様確認】Xの共有時にポストで表示するタイトルの文字数の上限は100文字で良いでしょうか？

#### 確認の意図
あまりないケースだとは思いますが、ブログのタイトルが140文字以上ある場合、ポスト可能な文字数をオーバーしてしまい、ポストができなくなってしまいます。
* タイトルの長いブログ
![image](https://github.com/fjordllc/bootcamp/assets/117491666/2d65d74e-09ce-4df5-99f4-6af46ba6069d)

* 文字数を減らさないとポストボタンが押せない
![image](https://github.com/fjordllc/bootcamp/assets/117491666/9916a81f-c11b-41e2-b7ed-9f4004ec91ca)

#### 実装のイメージ
* タイトルの100文字目以降は`...`とする
![image](https://github.com/fjordllc/bootcamp/assets/117491666/36ae58ff-c500-4487-8d91-4554d32adf01)

#### 上限100文字の根拠
* Xの無料アカウントでの文字数制限は100文字
* ブログのURLやユーザーが別途入力するコメントを加味すると100文字程度が適切であると考えられる

### 【報告】ブログのタイトルが長い際に、レイアウトからはみ出ている
以下のスクショのように文字がはみ出してしまっています。
本イシューの範囲外となると思ったため、ひとまず報告です。
<img width="485" alt="スクリーンショット 2024-06-01 175449" src="https://github.com/fjordllc/bootcamp/assets/117491666/a669b69b-dbdb-47e2-b1e1-466fb9b442c5">

以上、よろしくお願いいたします。

**Comment by Shrimprin** [comment]
@komagata 
ご回答いただきありがとうございます！仕様について承知いたしました👍

バグについてもissue登録いたしました～
https://github.com/fjordllc/bootcamp/issues/7841
