### ISSUE TITLE
ブログ記事にサムネイルを設定しても、一覧に表示されない。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7758]
<img width="418" alt="貼り付けた画像_2024_05_07_13_56" src="https://github.com/fjordllc/bootcamp/assets/168265/48d12c47-7eef-4ca6-8161-0a459ee8e4aa">

## 再現方法

メンターでログインし、 /articles/new にアクセス。

サムネイルは自分でアップロードせず選択する。

<img width="1319" alt="貼り付けた画像_2024_05_07_13_57" src="https://github.com/fjordllc/bootcamp/assets/168265/65069d1b-ccf1-4e43-bb90-c763eae7f196">

<img width="671" alt="貼り付けた画像_2024_05_07_13_58" src="https://github.com/fjordllc/bootcamp/assets/168265/937fe52a-21c0-4573-8a80-6a90a91f6da5">

サムネイルを本文に表示しないようにする。

**Comment by Shrimprin** [comment]
@komagata @machida 
お疲れ様です。仕様について2点確認させていただけますでしょうか。

### 1. 「サムネイル画像を本文に表示」のチェックは今回のバグに影響しますでしょうか？
試したところ、チェックのON, OFFに関わらず、最新記事一覧にはサムネイルが表示されませんでした。
今回のイシューは**サムネイル画像を自分でアップロードせずにサンプルから選択した際に、最新記事一覧にサムネイルが表示されないバグを修正する**という認識で良いでしょうか？

### 2. サムネイルの代替メッセージはブログ一覧ページ（[/articles](http://localhost:3000/articles)]）と同様にすればよいでしょうか？
最新記事一覧の代替メッセージを設定するにあたり、ブログ一覧ページの代替メッセージを参考にしようとしたところ、少々違和感があったため確認をさせてください。

### 現状のブログ一覧ページの代替メッセージ
| サムネイルの種類 | 代替メッセージ |
| ---- | ---- |
| 自分でアップロードした画像 | ブログ記事「`記事のタイトル`」のアイキャッチ画像 |
| サンプルから選択した画像 | ブログ記事のブランクアイキャッチ画像 |
| 何も画像を選択していない | ブログ記事「`記事のタイトル`」のアイキャッチ画像 |

サンプルから選択した画像の時に`ブランクアイキャッチ画像`となっていたり、何も画像を選択していないときに`ブランクアイキャッチ画像`となっているなど実際に表示されている内容と少し異なると感じました。

### 実装案
上記を踏まえて実装案を考えましたので、**どの実装にすべきがご助言いただけますでしょうか**。

#### 実装案 1
現状のブログ一覧ページのまま
| サムネイルの種類 | 代替メッセージ |
| ---- | ---- |
| 自分でアップロードした画像 | ブログ記事「`記事のタイトル`」のアイキャッチ画像 |
| サンプルから選択した画像 | ブログ記事のブランクアイキャッチ画像 |
| 何も画像を選択していない | ブログ記事「`記事のタイトル`」のアイキャッチ画像 |

#### 実装案 2
実際の表示に合わせる
| サムネイルの種類 | 代替メッセージ |
| ---- | ---- |
| 自分でアップロードした画像 | ブログ記事「`記事のタイトル`」のアイキャッチ画像 |
| サンプルから選択した画像 |  ブログ記事のサンプルアイキャッチ画像 |
| 何も画像を選択していない | ブログ記事のブランクアイキャッチ画像 |

#### 実装案 3
実際の表示に合わせ、さらにサンプルから選択した画像の場合は`Article.thumbnail_type`に応じたメッセージにする
（例: `thumbnail_type`が`ruby`なら`ブログ記事のrubyアイキャッチ画像`)
| サムネイルの種類 | 代替メッセージ | 
| ---- | ---- |
| 自分でアップロードした画像 | ブログ記事「`記事のタイトル`」のアイキャッチ画像 |
| サンプルから選択した画像 |  ブログ記事の`thumbnail_type`アイキャッチ画像 |
| 何も画像を選択していない | ブログ記事のブランクアイキャッチ画像 |

#### 実装案 4
全て記事のタイトルで統一
| サムネイルの種類 | 代替メッセージ |
| ---- | ---- |
| 自分でアップロードした画像 | ブログ記事「`記事のタイトル`」のアイキャッチ画像 |
| サンプルから選択した画像 | ブログ記事「`記事のタイトル`」のアイキャッチ画像 |
| 何も画像を選択していない | ブログ記事「`記事のタイトル`」のアイキャッチ画像 |

### 自身の考え
私としては以下2点の理由で`実装案4`が良いと考えています。
* 見る人としては何のブログのアイキャッチか示された方が直感的にわかりやすい
* 実装がシンプルになる

以上、お手数ですが誤解お願いいたします 🙏

**Comment by machida** [comment]
@Shrimprin 

## 1

その認識でOKですー。
サムネイルを選択した場合、自分でアップロードした場合、それが一覧で表示されることを期待しています。それは本文に表示・非表示は関係なく一覧では表示されるようにしてください。


## 2

4でお願いしますー

**Comment by Shrimprin** [comment]
@machida 
ご回答いただきありがとうございます！
承知いたしました！

**Comment by Shrimprin** [comment]
@komagata @machida 
お疲れ様です！
こちらのイシュー、ポイントが記載されていないのですが`ポイント1`であっていますでしょうか？

お手数ですがご確認よろしくお願いいたします 🙏

**Comment by komagata** [comment]
@Shrimprin 1ポイントで割り振りました～

**Comment by Shrimprin** [comment]
@komagata 
ありがとうございます！
