### ISSUE TITLE
Discordの通知チャンネルのURLプレビューをなくしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7760]
<>で囲うとプレビューがなくなるらしい。

**Comment by machida** [comment]
以下がDiscordに自動投稿されている。
自動投稿内容のURLを `< >` で囲う。

## 例

`https://bootcamp.fjord.jp/announcements/1011`
を
`<https://bootcamp.fjord.jp/announcements/1011>`
にする。

## 自動で通知しているもの（抜けがあるかも）

- 「お知らせ」チャンネル
  - イベントのお知らせ
  - お知らせ投稿
- 「通知」チャンネル
  - XXXさんが新たなメンバーとしてJOINしました🎉
  - プラクティス
  - Docs
  - 質問
- 「自己紹介」チャンネル
  - 🎉 XXXXさんがはじめての日報を書きました！
- 「日報」チャンネル
  - XXXXさんがXXXX年XX月XX日の日報を公開しました。
- 「メンターへのお知らせ」チャンネル
    - 未確認の日報の数をお知らせします。
    - 提出されてから日数が経っている提出物の数をお知らせします。
    - XXXさんの「XXXX」の提出物が、最後のコメントから5日経過しました。担当：@XXXXX さん

**Comment by ham-cap** [comment]
@komagata @machida 
お疲れ様です！
このissueについて、以下の通知については私のほうでは確認ができませんのでお願いできますでしょうか🙏

- 「通知」チャンネル
    - プラクティス関連
- 「メンターへのお知らせ」チャンネル
    - 未確認の日報の数をお知らせします。
    - 提出されてから日数が経っている提出物の数をお知らせします。
    - XXXさんの「XXXX」の提出物が、最後のコメントから5日経過しました。担当：@xxxxx さん

**Comment by komagata** [comment]
@ham-cap 

> 「通知」チャンネル
> プラクティス関連

「プラクティス関連」は具体的にどういったものか、代わりに確認をするためにもう少し詳細な情報をいただければありがたいです。

**Comment by ham-cap** [comment]
@komagata 
> 「プラクティス関連」は具体的にどういったものか、代わりに確認をするためにもう少し詳細な情報をいただければありがたいです。

こちら気が利かず失礼しました🙇‍♂️
プラクティスを「作成」した時と「編集」した時にDiscord通知が飛びますので、リンクプレビューが表示されないことをご確認いただければと思います🙏

**Comment by komagata** [comment]
@ham-cap 確認しました。OKです〜。

![image](https://github.com/user-attachments/assets/42109f5b-d121-48c3-976b-e43f00ed50ac)

**Comment by ham-cap** [comment]
@komagata 
ありがとうございます🙏🎉
