### ISSUE TITLE
Discord の「イベントのお知らせ」を開始時間順にする

### ISSUE THREAD

**Issue by cafedomancer** [fjordllc/bootcamp#7764]
## 機能の説明

タイトルどおり。

## 何故この機能が必要なのか

時系列順になっていたほうが時間的に参加できそうなイベントを探しやすいため。

**Comment by ham-cap** [comment]
@komagata @machida 
こちら本番環境での確認ができましたのでクローズします🙌

**Comment by machida** [comment]
@ham-cap 対応ありがとうございました🎉🎉🎉
