### ISSUE TITLE
メンターメニューの中身を追加する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7767]
↓現状のメンターメニュー

![image](https://github.com/fjordllc/bootcamp/assets/16577/08e305fc-6b0a-4843-8737-4bb1ad2f09e4)

↓の実際のメンターページにはもっとページがあるので、メンターメニューも同じようにリンクを作ってほしい。

![スクリーンショット 2024-05-08 223736](https://github.com/fjordllc/bootcamp/assets/16577/f9eb4c89-50de-4106-8010-fce7acac5434)

**Comment by komagata** [comment]
:memo: モバイル版のメニューデザインを調整するので完成したらまず @machida にメンションを送ること。

**Comment by Shrimprin** [comment]
@komagata 
承知しました！
ご回答ありがとうございます ☺️

**Comment by Shrimprin** [comment]
仕様についてDoscordにて確認した内容を記録としてこちらに記載します。

### 確認事項

ヘッダーリンクのメンターメニューにブログとブログ記事作成の両方のリンクを載せるか？

### 結論
ブログのリンクのみ残し、ブログ記事作成のリンクは消してよい

**Comment by komagata** [comment]
@Shrimprin 本番環境で確認しました～。

**Comment by Shrimprin** [comment]
@ありがとうございます！
