### ISSUE TITLE
メンターのプロフィール公開・非公開のチェックボックスが保存されない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7770]
![image](https://github.com/fjordllc/bootcamp/assets/16577/410758c5-261b-4429-83be-6385841c3965)

チェックして保存してもチェックされていない状態になる。

**Comment by Shrimprin** [comment]
@komagata @machida 

お疲れ様です！
本イシューのバグが手元の環境で再現できませんでした。
手元で確認した手順は下記の通りです。もしも確認手順やバグの認識に誤りがありましたらご教授いただけますでしょうか 🙏 

## 確認手順
1. ログイン前のトップページのメンター紹介欄を確認
![image](https://github.com/fjordllc/bootcamp/assets/117491666/706faae1-6886-43a4-ab96-fbacc2070d9d)

2. メンター権限のあるユーザー（今回は`mentormentaro`でサインイン`

3. 登録情報変更ページ([current_user/edit](current_user/edit))で`プロフィール非公開チェックボックス`を`ON`し`更新する`ボタンで保存
![image](https://github.com/fjordllc/bootcamp/assets/117491666/e8e021d9-41e5-4db6-8864-c62bc5994019)

4.  再度登録情報変更ページ([current_user/edit](current_user/edit))を確認すると`プロフィール非公開チェックボックス`は`ON`のまま

5. ログアウトしてトップページのメンター紹介欄を確認すると`mentormentaro`のプロフィールは表示されていない
![image](https://github.com/fjordllc/bootcamp/assets/117491666/da41c81c-638f-4457-b5e0-47a1ee747ae0)

**Comment by komagata** [comment]
@Shrimprin 

> 私の認識としては今回のバグは下記の通りですが、再現ができませんでした。
> 「手順4でチェックボックスがOFFに戻り、手順5ではプロフィールが公開されたままとなる」

本番環境だと上記の通りになりました。
ステージング環境なども調べてみてください～

**Comment by Shrimprin** [comment]
@komagata 
ご回答いただきありがとうございます 🙏 
ステージング環境でも同様に再現ができませんでした。
コードを確認して環境による差異が発生している原因等も含めて調べてみます 🤔

**Comment by Shrimprin** [comment]
@komagata 
他のユーザーの編集の際にバグを再現できました。
自身のユーザー登録情報編集時（/current_user/edit)に発生するとご認識していましたが、
正しくは**他のユーザー登録情報編集時（admin/users/{user_id}/edit}に発生する**という認識で合っていますでしょうか？

**Comment by komagata** [comment]
@Shrimprin 

> 正しくは他のユーザー登録情報編集時（admin/users/{user_id}/edit}に発生するという認識で合っていますでしょうか？

はい。

**Comment by Shrimprin** [comment]
@komagata @machida 
こちらの動作確認に管理者権限が必要なため、本番環境での確認をお願いできますでしょうか 🙏

**Comment by machida** [comment]
@Shrimprin 

本番で確認しましたー 対応ありがとうございます🙏
