### ISSUE TITLE
日報のタイトルを取りたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#778]
タイトルを考えるのが面倒なのと、みんな意味のないタイトルを入れてるようなので。

**Comment by wai-doi** [comment]
自分はタイトルはあったほうがいいと思います。

理由は
- 日報の一覧はタイトルが表示されてるので、目的の日報を探しやすいから
- 日報タイムラインを見て、他の人がやったことがすぐに知ることができて、日報を見てみようと思えるから

です。
今日やったことを一言にしてタイトルにするだけでもいいと思います。

**Comment by universato** [comment]
昔のIssueですし、クローズしていい内容だと思うのですが、備忘にコメントしておきます。

昔はどうだかわかりませんが、今は意味のあるタイトルを皆さん入れてるように思いますし、タイトルある前提で日報を書いてきたので、日報のタイトルがなくなるのは反対です。

#2034
上記のIssueなどでも、日報一覧などのタイトルからナンバリング等を確かめている事例もあるので、タイトルは必要です。

少し話変わりますが、日報に同名タイトルを入れることを許容して欲しいです。
同じプラクティスを続けてやるときに同じタイトルをつけたいですけど、サブタイトルをつけるのもナンバリングするのも個人的な流儀に反します。ナンバリングはちょっといいかもしれませんが、ユーザーごとの日報一覧にリンクがない現状なので少し煩わしく思います。

**Comment by ima1zumi** [comment]
@universato さんと同意見です。
現状の Issue ではないかなーと思うのでエイヤッと Close しちゃいます。何かあれば再 Open してください。

こちらは必要であれば別で Issue あげていただければ〜 🙏 
> 少し話変わりますが、日報に同名タイトルを入れることを許容して欲しいです。
同じプラクティスを続けてやるときに同じタイトルをつけたいですけど、サブタイトルをつけるのもナンバリングするのも個人的な流儀に反します。ナンバリングはちょっといいかもしれませんが、ユーザーごとの日報一覧にリンクがない現状なので少し煩わしく思います。
