### ISSUE TITLE
プラクティスに模範解答の欄が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7785]
特に画面の仕様については @machida と話しあいながら策定すること。

**Comment by masyuko0222** [comment]
- Story
  - Who : 受講生として
  - What : コードを書くプラクティス修了後に模範解答のコードが見たい
  - Why : 他の解法や、プロが書くコードを見て自分の学習に活かしたいから

**Comment by masyuko0222** [comment]
お疲れ様です。
文章

# 模範解答の定義について
1. 模範解答として用意するのは、プラクティスページで既にある「メンターの提出物」や出来がいいと思う「受講生の提出物」を案内する形になるでしょうか？

**Comment by masyuko0222** [comment]
# 画面仕様のご提案
## プラクティスページ
## プラクティス修了ページ
## 模範解答ページ
### 案1
- indexとしてすべての模範解答(提出物リンク)を貼っておく
### 案2
- practiceに紐づく形で、practiceごとに模範解答(提出物リンク)を貼っておく

**Comment by masyuko0222** [comment]
# 仕様

**Comment by machida** [comment]
@masyuko0222 ありがとうございます！
画面はイメージ通りですー

**Comment by masyuko0222** [comment]
@machida 
画面の追加で、`/mentor/practices`に以下のようにカラムを追加したいと思っています。

![image](https://github.com/fjordllc/bootcamp/assets/111285341/cbfa788c-d962-4b67-adf9-6456bfee678e)

あり/なしで、ありをクリックするとshowページに遷移する形にしたいと思うのですが問題なさそうでしょうか～？

**Comment by machida** [comment]
@masyuko0222 いいですね！そのリンクも設置お願いしますー

**Comment by masyuko0222** [comment]
@machida 
お疲れ様です。
模範解答のnew画面に行くためのボタンについて、`mentor/practices`の画面仕様を考え直しましたのでご確認いただけますと幸いです。

![image](https://github.com/fjordllc/bootcamp/assets/111285341/d13de290-c01f-410e-a1a4-c7ce29d3eaa4)

他にもnewページへ行くためのボタンを配置してほしいページがありましたらご教授ください。

※editに関しては、模範解答のshowページでメンターだけが見れる「編集」ボタンを配置しています。

**Comment by masyuko0222** [comment]
@komagata 
本番環境で確認がとれたのでCloseします！
