### ISSUE TITLE
管理者は自分以外のユーザーのGitHubアカウント情報を削除できるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7791]
管理者権限で自分以外のユーザーの編集画面にいき、このリンクをクリックしても、

<img width="597" alt="貼り付けた画像_2024_05_22_8_04" src="https://github.com/fjordllc/bootcamp/assets/168265/0c1cac77-343a-4634-91da-f5f5e76297bc">

自分のGitHubアカウントとの紐づけが解除されてしまう。
このユーザーのGitHubアカウントとの紐づけは解除できない。

このリンクをクリックして、自分以外のユーザーのGitHubアカウント情報を削除できるようにしたい。

**Comment by Shrimprin** [comment]
@komagata @machida 
お疲れ様です。本イシューの仕様について1点確認させていただけますでしょうか。

#### Discordの登録削除後の遷移先のページは、削除されたユーザーのプロフィールページとしてよいでしょうか？
現状、Discordの登録削除後の遷移先は`root_path`(=ダッシュボード)となっています。
他のユーザーの登録を削除した際は、そのユーザーのプロフィールページに遷移させた方が良いのではないかと考えています。
また、それに合わせてログインユーザー自身のDiscord登録削除した場合も、ログインユーザーのプロフィールページに遷移させた方が一貫性があると考えています。

下記のどちらが良いかご助言いただけますでしょうか。
* 登録削除されたユーザーに関わらず**ダッシュボード**とする
* **削除されたユーザーのプロフィールページ**とする

以上、よろしくお願いいたします。

**Comment by Shrimprin** [comment]
@komagata @machida 
お疲れ様です。本イシューの仕様について1点確認させていただけますでしょうか。

#### Discordの登録削除後の遷移先のページは、削除されたユーザーのダッシュボードとしてよいでしょうか？
現状、Discordの登録削除後の遷移先は`root_path`(=ログインユーザのダッシュボード)となっています。
他のユーザーの登録を削除した際は、そのユーザーのダッシュボードに遷移させた方が良いのではないかと考えています。

下記のどちらが良いかご助言いただけますでしょうか。
* 登録削除されたユーザーに関わらず**ログインユーザーのダッシュボード**とする
* **削除されたユーザーのダッシュボード**とする

以上、よろしくお願いいたします。

**Comment by machida** [comment]
@Shrimprin 質問ありがとうございます！

今回はGitHubだけにして、Discordは別Issueにしようと思います。

遷移先は確かに、そのユーザーのプロフィールページがいいですね。そのように対応お願いします🙏

**Comment by Shrimprin** [comment]
@machida 
ご回答いただきありがとうございます 🙏 
承知致しました！

**Comment by Shrimprin** [comment]
@machida 
度々申し訳ございません、もう1点質問です。

初期データ(seed)にある`users`はすべて`github_id`カラムが`nil`となっているため、動作の確認ができない状況です。
手元での動作確認は`rails c`で適当な`user`を作成すればできるのですが、プルリクエストでレビュアーに確認依頼をする際はどのように確認用のデータを用意すべきでしょうか？

下記のどちらが良いかご助言いただけますでしょうか。
私としては`seed`に追記して初期データを用意する方が親切と考えています。
* `rails c`で作成してもらう
* `seed`ファイルに`github_id`を入れたレコードを書いておき、初期データを用意する

お手数ですがご回答よろしくお願いいたします 🙏

**Comment by Shrimprin** [comment]
@machida 
ご返信ありがとうございます！
seedでのデータ作成と、testの作成承知いたしました。

**Comment by Shrimprin** [comment]
@komagata @machida 
こちらの動作確認に管理者権限が必要なため、本番環境での確認をお願いできますでしょうか 🙏

**Comment by machida** [comment]
@Shrimprin 本番で確認しました🙆対応ありがとうございます！！
