### ISSUE TITLE
外部公開ブログにRSSフィードを吐き出してほしい

### ISSUE THREAD

**Issue by sugiwe** [fjordllc/bootcamp#7792]
## 機能の説明

表題の通りですが、[外部公開しているブログ](https://bootcamp.fjord.jp/articles) がRSSフィードを吐き出してくれると大変嬉しいです。

## 何故この機能が必要なのか

フィードリーダー等に登録して、ブログ更新をタイムリーに漏れなくキャッチできるようになりたいため。

**Comment by komagata** [comment]
:memo: Atom1.0で配信してほしい。
厳密でなくてもいいので、実際に Feedlyで購読してみてほかのブログとそん色ないぐらいに実装してほしい。

**Comment by nishitatsu-dev** [comment]
@komagata , @machida 
AtomフィードのURLの表示について、下記ご相談したく、お願いします🙏
- 表示しますか？（あんまり見かけない気がするので…）
- 表示有の場合、
  - 表示場所（articlesのページの上の方でしょうか？）
  - その他、何か条件などあればお願いします

**Comment by machida** [comment]
目で見えるリンクは僕の方で設置するので、追加しなくて大丈夫ですー

**Comment by nishitatsu-dev** [comment]
@machida 
metaタグの件、目で見えるリンクの件、承知しましたー
機能を追加できたら、ご連絡します。よろしくお願いします🙏

**Comment by nishitatsu-dev** [comment]
Atomフィードに表示する記事数について
ミーティング（6/26）で相談の結果、ブログで１ページあたり表示されている件数（24件）と同じにすることになりました。
（フィードリーダー側に記事が溜まっていくので、あまり気にしなくて良いとのことです）

**Comment by nishitatsu-dev** [comment]
本番環境で動作確認できたのでクローズします。
