### ISSUE TITLE
開催前の定期イベントは次回開催日を表示しないようにしたい。

### ISSUE THREAD

**Issue by junohm410** [fjordllc/bootcamp#7798]
## 機能の説明

定期イベントで「初回開催日」を設定できるようにする。

## 何故この機能が必要なのか

現在は初回開催日の設定ができないため、WIP中（＝まだイベントを編集している途中、開催前）でも次回開催日が表示されてしまいます。

![image](https://github.com/fjordllc/bootcamp/assets/128765400/dd44199d-ccf9-4b02-a054-0c6b8a9350df)

- 上記のイベントは6/6開催予定で、イベントページ自体はWIP状態
- 開催されない5/27が次回開催日として表示されてしまっているのが個人的には不便に思います
- 現在は初回開催日については本文に補足として書く運用にしています

WIP中でページが存在しても開催前であることがはっきりとわかるようになっていると、よりユーザーに優しいかなと思いました。

※初回開催日を設定できなくても、ページがWIP状態であれば「次回開催日」の欄を「編集中のため次回開催日は未定です（例）」等の表示にするなどで、上記のわかりにくさを解消することはできると思います。このあたりはkomagataさん、machidaさんの判断にお任せしたいと思っています。

**Comment by machida** [comment]
@junohm410
Issue登録ありがとうございます！
なるほど、確かに公開前に次回イベント日時が表示されると混乱しますね。

WIPのときは、
「イベント編集中のため次回開催日は未定です」
と、表示したいと思います！！

**Comment by MikotoMakizuru** [comment]
本番環境で動作が確認できたので Close します。
