### ISSUE TITLE
プラクティス一覧のdescriptionのCSSがおかしい（line-hight?)

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7800]
![image](https://github.com/fjordllc/bootcamp/assets/16577/0fd4919e-cedc-4c25-8247-2141546a971a)

**Comment by machida** [comment]
📝 
https://github.com/fjordllc/bootcamp/issues/7829
このIssueで解決されるので、ポイントはそっちのIssueにマージし、こちらから外しておきます。

---

@motohiro-mm 
https://github.com/fjordllc/bootcamp/issues/7829
このIssueが完成になったら、このIssueも完成にしておいてくださいー

**Comment by motohiro-mm** [comment]
@machida 
承知しました！

**Comment by motohiro-mm** [comment]
#7829 
上記issueが完成しcloseになったので、こちらもcloseにします！
