### ISSUE TITLE
【メンター向け】退会済みユーザーの日報には、退会ユーザーの日報であることを表示する。

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#7810]
https://bootcamp.fjord.jp/reports/95411 にwelocmeコメントを書こうとしたが、このユーザーさんは退会済みだということに気付いた。

この場合、コメントを書いても本人に届くことはないので、たとえば退会済みユーザーの日報は「未チェックの日報」に載せない、というようなシステム側の対応があった方がいいかもしれない。

**Comment by machida** [comment]
📝 
退会者の日報には、管理者・メンターにだけ「このユーザーは退会しています。」というメッセージを表示する。

**Comment by machida** [comment]
@motohiro-mm アサインさせていただきました。表示ができたら僕がデザインを入れるのでメンションをお願いしますー

**Comment by motohiro-mm** [comment]
@komagata 
おつかれさまです。
お手隙の際に本番環境での確認をお願いいたします🙏

確認手順は以下です。
1. 管理者・メンター権限をもつユーザーでログイン
2. https://bootcamp.fjord.jp/reports/95411 （退会者の日報）にアクセスする
3. 「このユーザーは退会しています。」のメッセージが表示されることを確認する

**Comment by komagata** [comment]
@motohiro-mm 確認できました～！

**Comment by motohiro-mm** [comment]
ありがとうございました！

確認していただいたので、こちらのissueはcloseにします！

**Comment by JunichiIto** [comment]
@motohiro-mm 対応ありがとうございました！
