### ISSUE TITLE
画面右上のプルダウンメニューからマイプロフィールに移動したい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#7815]
現状、ダッシュボードにマイプロフィールへのリンクがあります。

![Screenshot 2024-05-30 at 8 27 49](https://github.com/fjordllc/bootcamp/assets/1148320/1a60f7ff-79d6-45b0-93f8-131be8ccaca8)

が、Qiitaなどでは画面右上のプルダウンメニューにマイページへのリンクがあります。

![Screenshot 2024-05-30 at 8 29 46](https://github.com/fjordllc/bootcamp/assets/1148320/3583a18a-e7e8-4531-a31a-b6d3f56fab7c)

Bootcampアプリでも同じようにプルダウンメニューがあった方が便利だと思います。
（というか、プルダウンメニューを探して「ない！ない！どこにもない！！」って思ってました）

![Screenshot 2024-05-30 at 8 28 07](https://github.com/fjordllc/bootcamp/assets/1148320/79c742e2-a3f4-4976-8fdf-ce69debcfbbc)

**Comment by su-su-su-su** [comment]
@machida 
お世話になっております。

ドロップダウンメニューにマイプロフィールの追加まではできたのですが、そのテストファイルを見つけることができなかった為、ファイルが存在するか確認させていただきたいです。

`dropdown`, `menu`, `user menu` などのキーワードで検索しても見つからず、
ドロップダウンメニューのコードは`app/views/application/_user_menu.html.slim`にあったので、
`find test/ -type f -name '*user_menu*'` コマンドを実行しても該当ファイルは見つけることができませんでした。

ドロップダウンメニューのテストが別のファイル名で存在しているのか？元々テストファイルが不要なのか？テストファイルは自分で作るなど考えたのですが、解決できなかったので質問をさせていただきました。
お手隙の際にご回答よろしくお願いいたします。

**Comment by machida** [comment]
@su-su-su-su 
ごめんなさい、これは僕ではなくkomagataさんから答えてもらおうと思います。

@komagata 回答お願いしますー

**Comment by su-su-su-su** [comment]
@machida 

コメントありがとうございます。承知いたしました。

**Comment by komagata** [comment]
@su-su-su-su システムテストは非常に重い（ユニットテストの100倍とか以上）ので大事なユースケースのみで、「リンクがあるかどうか」や「特定の要素が表示されているか」とかではシステムテストは作成しなくて大丈夫です。

**Comment by su-su-su-su** [comment]
@komagata 
かしこまりました。ご説明ありがとうございます。
引き続き作業を進めたいと思います。
