### ISSUE TITLE
ユーザープロフィールページの title タグ内の文字を修正

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7825]
自分以外のユーザーページに移動する。

例えば: hatsuno

<img width="778" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/5570333e-fff1-4ba5-9579-d67f98db2865">

title タグが　`hatsuno | FBC` となっていて、og:title は `hatsuno` になっている。
※(development) はローカル環境であるという印なだけで、本番には表示されないので無視します。

<img width="1019" alt="貼り付けた画像_2024_06_05_15_31" src="https://github.com/fjordllc/bootcamp/assets/168265/eae966aa-f3c9-49a2-b0da-4a2d9df510c8">

title タグを　`hatsunoさんのプロフィール | FBC` 、og:title は `hatsunoさんのプロフィール` となるように変更する。

**Comment by motohiro-mm** [comment]
本番環境で確認ができましたので、closeします！
