### ISSUE TITLE
ユーザーのポートフォリオページのtitleタグ内の文字を修正

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7826]
ユーザーのポートフォリオのページに行く。

<img width="555" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/1ddae2b2-9441-4e23-9fab-dd93ba66d4b7">

title タグが　`hatsunoのポートフォリオ | FBC` となっていて、og:title は `hatsunoのポートフォリオ` になっている。
※(development) はローカル環境であるという印なだけで、本番には表示されないので無視します。

<img width="969" alt="貼り付けた画像_2024_06_05_15_39" src="https://github.com/fjordllc/bootcamp/assets/168265/4bd14732-17be-418c-a5b7-9c5c44ab30bb">

title タグを　`hatsunoさんのポートフォリオ | FBC` とし、og:title は `hatsunoさんのポートフォリオ` にする。

**Comment by motohiro-mm** [comment]
本番環境で確認ができましたので、closeします！
