### ISSUE TITLE
カテゴリーの説明をMarkdownで出力する。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7829]
プラクティス一覧ページの各カテゴリーの説明文。

<img width="917" alt="貼り付けた画像_2024_06_06_12_30" src="https://github.com/fjordllc/bootcamp/assets/168265/94f56957-8c9f-487a-a10c-a541cc73c879">

これを Markdown で出力したい。

**Comment by motohiro-mm** [comment]
@machida 
実装の方針について質問があります🙏

各カテゴリーの説明文をマークダウンで表示する際、
特定のマークダウンを使用すると以下動画のようにEditボタンが反応しなくなりました。
（正確にはEditボタン上部のほんのわずかの部分だけが反応します）
どのように対応すべきか方向性を教えていただきたいです。

https://github.com/fjordllc/bootcamp/assets/104712009/7d4f1d34-91c8-4ecd-ad1d-11eb2bb3f966

該当するマークダウンは私が調べた限り以下3つです。
- `#`見出し　（`#`の個数は関係なし）
- `>`引用
- `:::message ~ :::`などのメッセージブロック
メッセージブロックの場合はEditボタンのpenの表示もなくなります。
（ボタンがあるであろう場所上部でのリンクの反応は他と同様にあります）

対応として以下の2つを考えました。
- Editボタンが最上部にくるようにする
`app/javascript/stylesheets/application/blocks/practice/_categories.sass`の`.categories-item__edit`に`z-index`を追加
```
.categories-item__edit
  float: right
  margin-left: .5rem
  +position(relative, top -.25rem)
  z-index: 100
```
- 該当するマークダウンを使えないようにする

上記の対応ではなくそれ以外の対応が適切な場合はそれもご指示いただきたいです。
お手隙の際にご回答のほどよろしくお願いいたします🙇‍♀️

**Comment by machida** [comment]
@motohiro-mm 

連絡ありがとうございます！
リンクが反応しないのはCSSのせいですね。
これ、すぐに直せるので一旦そのままで大丈夫ですー。作業が一通り終わったら、僕にメンションとアサインをお願いします。僕の方で直しますー

**Comment by motohiro-mm** [comment]
@machida 
回答ありがとうございます！🙏
承知しました！

**Comment by motohiro-mm** [comment]
@komagata 
お疲れ様です。
お手隙の際に本番環境での確認をお願いいたします🙏

確認手順は以下です。
1. メンター権限をもつユーザーでログイン
2. https://bootcamp.fjord.jp/courses/1/practices#category-1 (プラクティス一覧)へアクセスし、ペンマークのeditリンクをクリック
4. カテゴリーの説明をマークダウン形式で編集し、プレビューで見え方を確認して「更新する」をクリック
5. カテゴリーの説明がプレビューで表示されていた通りに更新されているかを確認する

**Comment by komagata** [comment]
@motohiro-mm 確認してOKでした～！

**Comment by motohiro-mm** [comment]
確認ありがとうございました！🙏
OKとのことなので、こちらのissueはcloseします！
