### ISSUE TITLE
DocsをWIP状態からの初回の公開を行った際のボタンの文言を違和感のない状態に変更したい

### ISSUE THREAD

**Issue by a-terumoto-gs** [fjordllc/bootcamp#7830]
## 機能の説明

Docsにおいて現在はアクション依存で、提出用のボタンの文言がnewとcreateでは「Docsを公開」、editとupdate では「内容を更新」になっていますが、
WIP状態からの初回の公開では「内容を更新」よりも「Docを公開」の文言のほうが違和感がないため、「Docを公開」が表示されるようにしたい

![image](https://github.com/fjordllc/bootcamp/assets/133624488/95676fab-90ad-4d6b-8174-bab1d57c16f4)
![image](https://github.com/fjordllc/bootcamp/assets/133624488/71f383e9-1745-44ff-9661-9410b07bc4de)

文言変更の提案のきっかけとなったissue 
- https://github.com/fjordllc/bootcamp/issues/7421

**Comment by Ryooo-k** [comment]
本番環境で動作確認が完了しましたのでCloseいたします。
