### ISSUE TITLE
メール下部にある「メールでの通知オフはこちらから」をクリックした時に確認画面を挟んでほしい

### ISSUE THREAD

**Issue by sugiwe** [fjordllc/bootcamp#7837]
## 機能の説明

![20240607](https://github.com/fjordllc/bootcamp/assets/25524188/53ac84b3-784a-41dc-ae95-ab270a7b7611)
![20240607_2](https://github.com/fjordllc/bootcamp/assets/25524188/1b99a65f-7789-43a9-8e84-291ed50db742)

上記に添付の通り、メール下部に設置してある「メールでの通知オフはこちらから」をクリックすると、確認画面等を挟むことなく自動的にメール配信設定がオフになってしまう仕様かと思いますが、一度確認画面を挟むなどしていただけると大変ありがたいです。

## 何故この機能が必要なのか

何気なくメールを触っていて間違えてこのボタンをクリックしてしまい、気づかないうちにメール通知がオフになっていたという経験が過去3回ほど発生したため。

**Comment by okuramasafumi** [comment]
海外だとよくあるのが各種メール（マーケティングメールや機能追加お知らせメールなど）にスイッチがついていて、最後に"Update"ボタンで設定を更新するやつですね。メールに種類がある場合はよくみかけます。1種類のみなら確認画面も見ることがありますね。

**Comment by JunichiIto** [comment]
> 何気なくメールを触っていて間違えてこのボタンをクリックしてしまい、気づかないうちにメール通知がオフになっていたという経験が過去3回ほど発生したため。

僕も昔1回やってしまったことがあります。
たしかに確認画面があった方がありがたいですね。

**Comment by komagata** [comment]
:memo: 「メール通知をオフにしますか？」というページを挟むようにする。

**Comment by motohiro-mm** [comment]
@machida 

仕様について3点確認・質問があります。

### 1. メール通知解除までの流れは以下で問題ないか
メール内の「メールでの通知オフはこちらから」をクリック
→確認ページに遷移し「オフにする」をクリック
→rootページに遷移し「メール配信を停止しました。」のメッセージが出る

### 2. 確認ページに実装する必要があるものは以下で合っているか
- 「メール通知をオフにしますか？」という文言
- 「オフにする」というリンク

他に必要なものがあれば教えてください。

### 3. 確認ページのデザインはmachidaさんに依頼してよいのか
2で必要とされたものを表示できるようにしてmachidaさんに依頼すればよいのでしょうか。もしそれ以外で書く必要があるものがあったら教えてください。
ちなみに、メール通知解除は未ログイン/ログイン中ともに可能なため、確認ページのデザインも未ログイン/ログイン中のどちらにも対応する必要がありそうです。

お手隙の際に回答いただければと思います。
よろしくお願いいたします。

**Comment by machida** [comment]
@motohiro-mm 

 1, 2, 3 どれもその認識でOKですー

> 3. 確認ページのデザインはmachidaさんに依頼してよいのか

の

> メール通知解除は未ログイン/ログイン中ともに可能なため、確認ページのデザインも未ログイン/ログイン中のどちらにも対応する必要がありそうです。

ですが、これは未ログイン/ログイン中どちらも同じデザインにしたいと考えています。
ヘッダーやフッターなどログインしていないと表示できないパーツのないlayoutを使いたいと思います。

**Comment by motohiro-mm** [comment]
@machida 
回答いただきありがとうございました！
2にある文言とリンクを表示するページを作成し、その後デザインの依頼をさせていただきます。
PRで再度ご連絡させていただきますので、よろしくお願いいたします！

**Comment by motohiro-mm** [comment]
本番環境で確認できましたのでこちらのissueはcloseします！
