### ISSUE TITLE
文字数が非常に多いタイトルのブログがレイアウトをはみ出す

### ISSUE THREAD

**Issue by Shrimprin** [fjordllc/bootcamp#7841]
## 概要
文字数が非常に多いタイトルのブログがレイアウトをはみ出します。

## 再現手順
1. [/articles/new](http://localhost:3000/articles/new)にアクセス
2. タイトルに以下の例のような長い文字列を設定する
`「長いタイトルのバグ確認」これは長ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああいタイトルです！！！！！！！！！！！！！！！！！！！！！！！！！！！`
3. 内容を適宜入力して`公開する`ボタンを押す
4. 遷移したブログ記事の詳細ページで、タイトルがレイアウトをはみ出している

## 期待される振る舞い
タイトルがレイアウトに適切に収まる

## スクリーンショット

<img width="592" alt="スクリーンショット 2024-06-09 161007" src="https://github.com/fjordllc/bootcamp/assets/117491666/a738f5df-0d58-4ca8-bf9a-aa0fd98d5b40">

## 環境

 - OS: Windows10
 - ブラウザ: Chrome
 - バージョン: 125.0.6422.142

**Comment by machida** [comment]
これはバグではないですね。
`！` が連続で続く場合、途中で改行されないという仕様があります。そのせいでデザイン崩れが起きていました。
実際、`！` の連続はなくし、別の文字で長文を入れてみるとデザインが崩れないことが確認できると思います。

同様に、`aaaaaaaaaaaaaaaaaaaaaaaaaaaaa` もデザイン崩れがおきます。理由は、これも途中で改行されないという仕様があるからです。アルファベットは通常、単語の途中で改行はされない言語だからです。

CSSでそのような場合も強制的に改行をさせることは可能なのですが、英単語の途中で改行がされると読みにくくなり、現実的にデザイン崩れが起きるような長い英単語は存在しないので、本文のタイトル部分にはCSSでの強制的に改行は入れないようにしたいと思います。

ただ、

<img width="442" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/8d29f1a8-e2f4-417d-8e91-c84ea1ad59e3">

これは見にくいので、

<img width="416" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/3bac113e-2baf-427d-ae7a-4d2d4f89905b">

このようにする修正のPRをマージしておきますー。

**Comment by Shrimprin** [comment]
@machida 
> これはバグではないですね。
！ が連続で続く場合、途中で改行されないという仕様があります。そのせいでデザイン崩れが起きていました。
実際、！ の連続はなくし、別の文字で長文を入れてみるとデザインが崩れないことが確認できると思います。

そのような仕様なのですね！
確認不足で申し訳ございません。

対応方法についても承知いたしました。

**Comment by machida** [comment]
@Shrimprin 全然申し訳なくないですよ😀これはマニアックなところなので、それに遭遇できて良かったです。テストデータはaaaaaとかではなくリアルなものでないと変なところでハマる場合があるんですよね。今回はそのいい例でした😄

**Comment by Shrimprin** [comment]
@machida 
ありがとうございます！勉強になりました 👏 
> テストデータはaaaaaとかではなくリアルなものでないと変なところでハマる場合があるんですよね。

テスト目的に合致していればなんでもいいというわけではないのですね！
今後の検証時には気を付けていきます～
