### ISSUE TITLE
提出物編集画面にキャンセルボタンが欲しい

### ISSUE THREAD

**Issue by unikounio** [fjordllc/bootcamp#7847]
## 概要

提出物編集画面に下記の画面へ遷移する`キャンセル`ボタンがあると嬉しいです。
- 編集中の提出物をWIPまたは提出する前：プラクティス画面
- 編集中の提出物がWIPまたは提出済：提出物詳細画面

## 何故この機能が必要なのか
WIPした提出物が提出物詳細画面でどのように見えるのかを気軽に確認できるようにしたいため。

![スクリーンショット 2024-06-11 132857](https://github.com/fjordllc/bootcamp/assets/125527162/94e8503b-e3fb-43e7-88f3-b0d0ea8cd914)

**Comment by motohiro-mm** [comment]
本番環境で確認ができましたのでこのissueはcloseします！
