### ISSUE TITLE
「直近の日報」を非Vue/React化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7849]
![image](https://github.com/fjordllc/bootcamp/assets/16577/8b1e42be-115b-42e5-b648-79c99b42b738)

普通のHTMLでの実装に変える。

元々Reactに変更する予定でしたが、最終的にはHotwireにする予定なので、VueもReactも使わない実装にしたいです。（普通にviewに表示する方式）

**Comment by nishitatsu-dev** [comment]
@komagata @machida 
お忙しい所すみませんが、こちらのissueの本番環境での動作確認をお願い致します🙏

**Comment by nishitatsu-dev** [comment]
9/4のチーム開発ミーティングで、本番環境での動作確認が完了したのでクローズします。
