### ISSUE TITLE
ブログ公開した際の通知が、WIPでも通知されてしまう。公開後もブログを編集すると通知されてしまう。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7862]
FBCの公式ブログを公開すると、みんなに通知が飛ぶ。

- ブログ公開した際の通知が、WIPでも通知されてしまう。
- 公開後もブログを編集すると通知されてしまう。

というバグがある。

- WIPで保存したときは通知をしない。
- 公開された記事をその後更新した際は通知をしない。

このように修正してください。
つまり、公開したとき一回だけ通知するようにしてください。
ブログ記事は publish_at という値があるので、それで公開前、公開後が判断できます。

**Comment by motohiro-mm** [comment]
@machida 

お疲れ様です。
issueについて伺いたいことがあります。

> ブログ公開した際の通知が、WIPでも通知されてしまう。

上記バグが再現できず、私が調べた範囲では現在WIPでは通知されていませんでした。

> 公開後もブログを編集すると通知されてしまう。

上記バグは、公開ボタンを押すたびに通知されていたので、再現できました。

いずれにしてもissueにあるように、
- WIPで保存したときは通知をしない。
- 公開された記事をその後更新した際は通知をしない。

となるように修正すれば良いという認識でよろしいでしょうか。
バグの再現が出来なかったことが不安だったので確認させていただきました。
お手隙の際に回答お願いいたします。

**Comment by machida** [comment]
@motohiro-mm
調査ありがとうございます！！
WIPでは通知されない、了解ですー
その認識でOKですー🙆‍♂️
では、そこはそのままで、「公開された記事をその後更新した際は通知をしない。」だけ対応をお願いします🙏

**Comment by motohiro-mm** [comment]
@machida 
回答ありがとうございます！🙏承知しました！

**Comment by motohiro-mm** [comment]
@komagata 
お疲れ様です。
お手隙の際に本番環境での確認をお願いいたします！

確認手順は以下です。

1. メンター権限をもつユーザーでログイン
2. `https://bootcamp.fjord.jp/articles/new`（ブログ新規作成）よりブログを作成しWIPとして保存する
3. 別ユーザーでログインし、通知が来ていないことを確認する
4. WIP記事を書いたユーザーで再度ログインし、WIP記事を公開にする
5. 別ユーザーでログインし、通知が来ていることを確認する
6. 記事を公開したユーザーで再度ログインし、公開した記事を内容修正して更新する
7. 別ユーザーでログインし、通知が来ていないことを確認する

煩雑な手順でお手数おかけいたします。
別ブラウザから別のユーザーでログインしておき、ブログの作成・公開のたびに通知の有無を随時確認していただくとログイン・ログアウトの手間を少なくできるかと思います。

よろしくお願いいたします！

**Comment by komagata** [comment]
@motohiro-mm 本番環境で確認できました〜！

**Comment by motohiro-mm** [comment]
@komagata 

ありがとうございます〜！🙌

**Comment by motohiro-mm** [comment]
本番環境での確認をしていただきましたので、こちらのissueはcloseにします！
