### ISSUE TITLE
ユーザーの「無料」フラグを削除する。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7869]
無料フラグは、FBCが無料でテスト運営していたときに使っていたもので、今は使っていないのでDBもUIも削除する。

---

admin でログインし、ユーザーの編集画面に入る。

<img width="604" alt="貼り付けた画像_2024_06_19_10_09" src="https://github.com/fjordllc/bootcamp/assets/168265/5274d3e2-f202-464f-928c-16915ef63446">

無料フラグを削除。
DBからも削除する。

---

ユーザープロフィールページに表示している無料の表示も削除する。

**Comment by Judeeeee** [comment]
@machida
 
お疲れ様です！一点だけ認識の確認をさせてください🙏

> ユーザープロフィールページに表示している無料の表示も削除する。

ユーザープロフィールページの表示とは、画像の赤枠で示した認識で問題ないでしょうか？👀
<img width="618" alt="スクリーンショット 2024-07-04 15 08 28" src="https://github.com/fjordllc/bootcamp/assets/43412616/03aa80cd-d505-4db7-bc1c-b1a2a115cf58">

**Comment by machida** [comment]
その部分で合ってますー。その部分は[無料]以外の表示がされることもあるので(念のためコードの確認をお願いします)、行は消さず、無料の表示だけを消すようにしてくださいー

**Comment by Judeeeee** [comment]
@machida 
早速の回答ありがとうございます🙏

承知しました！
コードを確認して無料の表示だけを消すようにしたいと思います🙆

**Comment by Judeeeee** [comment]
本番環境で確認できたのでcloseします。
