### ISSUE TITLE
「参考書籍一覧」を非Vue化したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7870]

**Comment by ham-cap** [comment]
@machida 
お疲れ様です！
こちらのissueの対象範囲について、`/books`の他に`/courses/:course_id/books`というページもあるのですが、そちらも対象になりますでしょうか？👀

**Comment by machida** [comment]
@ham-cap 質問ありがとうございます！今回は `/books` だけでお願いしますー

**Comment by ham-cap** [comment]
@machida 
ご回答いただきありがとうございます！
承知いたしました💪

**Comment by ham-cap** [comment]
本番環境で動作確認いたしましたのでクローズします。
