### ISSUE TITLE
招待URLを作成時、研修生の場合は「請求書」 or 「クレジット」カードの選択を必要にしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7871]
adminでログインし、`/admin/invitation_url` にアクセス。
招待URLを作成ページ。

<img width="331" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/1a8e3772-5612-4d03-9511-6abd7111b790">

これを、

<img width="334" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/6f845b66-341f-4637-b548-e4e7d8ceaa92">

このようにし、

----

## 会員登録ページの変更

研修生の場合のみ、請求書払い or クレジットカード払い のラジオボタンを設置する。

### 請求書払いを選択した場合

- 請求書払い or クレジットカード払い のラジオボタンの「請求書払い」が選択されている状態にする。
    -  請求書払い or クレジットカード払い のラジオボタンの選択はユーザーでは切り替えられないようにする。

現在、請求書払いはこのようなチェックボックスがあり、それをチェックすることになっている（このチェックボックスは管理者しか見れない）が、

<img width="609" alt="貼り付けた画像_2024_06_19_10_27" src="https://github.com/fjordllc/bootcamp/assets/168265/b5823d0a-ddd5-4c58-a89f-2b4e16f814e7">

- 上記のUI自体削除する。
    - しかし、ユーザーが持つ「請求書払い」フラグの値は、このUIに替わり、ラジオボタンの「請求書払い」が選択されている状態で「請求書払い」フラグの値を持つようにする。
- 「請求書払い」が選択されていて、クレジットカード情報が登録されていない場合はバリデーションエラーにはならないようにする（実際入力欄が表示されないのでクレジットカード情報の入力は不可能）。

### クレジットカード払いを選択した場合

- 請求書払い or クレジットカード払い のラジオボタンの「クレジットカード払い」が選択されている状態にする。
    -  請求書払い or クレジットカード払い のラジオボタンの選択はユーザーでは切り替えられないようにする。

<img width="610" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/ee2e0f84-9b61-4e4a-bb76-226a1ce50c69">

-「クレジットカード払い」が選択されているときは、上記キャプチャのクレカ番号入力欄が表示されるようにし、申込者がクレジットカード情報を登録できるようにする。
- 「クレジットカード払い」が選択されていて、クレジットカード情報が登録されていない場合はバリデーションエラーになるようにする。

### 「支払い方法を選択」を選択した場合

- 申込者が請求書払い or クレジットカード払い のラジオボタンを選択できるようにする。
    - 「クレジットカード払い」が選択されているときは、クレカ番号入力欄が表示されるようにし、申込者がクレジットカード情報を登録できるようにする。
    -「クレジットカード払い」が選択されていて、クレジットカード情報が登録されていない場合はバリデーションエラーになるようにする。
      - 「請求書払い」が選択されていて、クレジットカード情報が登録されていない場合はバリデーションエラーにはならないようにする（実際入力欄が表示されないのでクレジットカード情報の入力は不可能）。
    
---

## 会員登録ページの変更 2

<img width="590" alt="貼り付けた画像_2024_06_19_17_16" src="https://github.com/fjordllc/bootcamp/assets/168265/02ac913e-2cd0-47f9-bece-b57c3764e0f4">

このタイトルの部分、

- メンターの招待の場合
    - FBCメンター参加登録
- 研修生の招待の場合
    - FBC研修生参加登録
- アドバイザー招待の場合
    - FBCアドバイザー参加登録
- 一般受講生の場合
    - FBC参加登録

に変更する。

<img width="561" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/1290736c-f3d5-48f4-ad56-0bc3f9684a42">

title タグも同様に変更する。

**Comment by ham-cap** [comment]
@machida 
お疲れ様です！
本issueについて質問です。

請求書払い・カード払いのどちらを選択した場合でも、「請求書払い」と「クレジットカード払い」それぞれのラジオボタンが表示されるイメージだと思うのですが、例えば現在のUIを流用して以下のような項目が表示されるイメージで合っていますでしょうか？👀（画像は試しに私の手元で見た目をいじったものです）
<img width="509" alt="image" src="https://github.com/fjordllc/bootcamp/assets/66000707/c0b40c18-37b2-42c8-80bb-f9f2cdb145de">

また、現状では「請求書払いの設定」という項目は管理者用のメニューに含まれていますが、今後はユーザーの入力項目の一つになるかと思いますので、どの位置に挿入すればよいかご教示ください。
個人的には、支払い方法は事務的な性格の強い項目だと思いますので、SNSアカウント設定の下などでもいいのかなと思っています。

**Comment by machida** [comment]
@ham-cap 
位置についてはそれでお願いしますー🙏
見た目もそれでお願いします。
細かいところは僕の方で調整します。

一つ、お願いがあります。

> 請求書払い・カード払いのどちらを選択した場合でも、「請求書払い」と「クレジットカード払い」それぞれのラジオボタンが表示されるイメージだと思うのですが、

請求書払い・カード払いのどちらを選択した場合でも、「請求書払い」と「クレジットカード払い」それぞれのラジオボタンを表示したいのですが、登録するユーザーの方では切り替えができないようにしたいと思います。

何かしらのclass名を付けておいてくれれば、僕の方でクリックできない機能を追加しておきますので、メンションをいただけたらと思います。

**Comment by ham-cap** [comment]
@machida 

> 請求書払い・カード払いのどちらを選択した場合でも、「請求書払い」と「クレジットカード払い」それぞれのラジオボタンを表示したいのですが、登録するユーザーの方では切り替えができないようにしたいと思います。

はい。こちらについてはおっしゃる通りで認識しております👍
念のため確認ですが、
- 研修生（請求書払い）：「請求書払い」にチェック有り・**変更不可**
- 研修生（クレジットカード払い）：「クレジットカード払い」にチェック有り・**変更不可**
- 研修生（支払い方法を選択）：「請求書払い」、「クレジットカード払い」いずれもチェック無し・**選択可**

という形で間違いないでしょうか？👀

> 何かしらのclass名を付けておいてくれれば、僕の方でクリックできない機能を追加しておきますので、メンションをいただけたらと思います。

こちら承知いたしました！
選択されていないほうの選択肢になんらかのクラス名をつける形で考えています。
該当箇所の実装が固まった段階でお声がけいさせていただき、クリックできない機能の追加をしていただいた後にPRを作成するという流れで大丈夫でしょうか？

**Comment by ham-cap** [comment]
@machida 
お疲れ様です！
細かいことですが、念のために確認です。
会員登録ページのタイトルの変更については、
> - メンターの招待の場合
>     - FBCメンター参加登録
> - 研修生の招待の場合
>     - FBC研修生参加登録
> - アドバイザー招待の場合
>     - FBCアドバイザー参加登録
> - 一般受講生の場合
>     - FBC参加登録

とのことですが、「フィヨルドブートキャンプ」は「FBC」と略してしまってよいという理解で大丈夫でしょうか？👀
現状、アドバイザー以外の場合は「フィヨルドブートキャンプ参加登録」となっていますが、この文字列の「フィヨルドブートキャンプ」も「FBC」に置換する形でよろしいですか？

また、当初「請求書払い」と「クレジットカード払い」のボタンをユーザーの方で切り替えできないようにする部分は町田さんが実装してくださるとのことだったのですが、こちらの作業中にその部分だけ実装しないでおくと何かと都合が悪かったため私の方で実装してしまいました。事後報告となってしまいすみません。
動作については昨日の開発ミーティングでもデモさせていただいたとおりですので何かあればお知らせください。

**Comment by machida** [comment]
@ham-cap 確認ありがとうございます！はい、FBCと略してください🙏これからFBCという略もちょこちょこ使っていきたいと思います。また、10月から使う新しロゴはFBCという表記になります。

チェックボックスが変更できないの実装についても了解ですー🙆🏻‍♂️

**Comment by ham-cap** [comment]
@machida 
承知いたしました👍
FBCという表記が公式としてはどうなんだろうと気になっていたのでスッキリしました🙌

**Comment by ham-cap** [comment]
@komagata @machida 
お疲れ様です！
こちら手元での動作確認について質問です。
クレジットカード払いの場合に正常にユーザー登録ができるかどうかをdevelopment環境で試してみても問題ないでしょうか？👀
カード番号は[Stripeのサイト](https://docs.stripe.com/testing?testing-method=card-numbers#visa)に掲載されているものを参照する想定です。

**Comment by ham-cap** [comment]
@komagata @machida 
先日、一つ上で質問(https://github.com/fjordllc/bootcamp/issues/7871#issuecomment-2283037263) をさせていただきましたが、その後システムテストを確認したところStripeのサイトに掲載されている開発者向けのダミーのカード番号を使用してテストしているのを見つけて自己解決いたしましたので、上記の質問についてご回答には及びません。
確認不足で失礼いたしました🙇‍♂️

**Comment by ham-cap** [comment]
本番環境で確認ができたためクローズします🎉
