### ISSUE TITLE
都道府県別ユーザー一覧を非React化したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7873]
http://localhost:3000/users/areas
このページを非React化する。

現在、デフォルト（どの地域も選択していない場合）では東京の一覧が表示されているが、
非React化をするにあたって、デフォルト画面では東京を出すのではなく、都道府県を人数の多い順に並べて表示して欲しい。

**Comment by Shrimprin** [comment]
### 📝 メモ
もともとあったReactファイルは消してよい

**Comment by Shrimprin** [comment]
📝 関連するPR
* [https://github.com/fjordllc/bootcamp/pull/6958](https://github.com/fjordllc/bootcamp/pull/6958)
* [都道府県別ユーザー一覧の機能がエラーで動かない問題の修正 #7589
](https://github.com/fjordllc/bootcamp/pull/7589)

**Comment by Shrimprin** [comment]
@komagata @machida 
お疲れ様です。
本件の仕様について確認させてください。

> 現在、デフォルト（どの地域も選択していない場合）では東京の一覧が表示されているが、
非React化をするにあたって、デフォルト画面では東京を出すのではなく、都道府県を人数の多い順に並べて表示して欲しい。

これの仕様は以下の認識であっていますでしょうか？

* `タグ別ユーザー一覧`のタグの括りを都道府県に置き換えるようなイメージ
以下の画像の`30代`や`ゲーム`が`東京`や`大阪`に置き換わるイメージです。
![image](https://github.com/user-attachments/assets/101d7adc-2d83-42f1-be9d-4e41e020c4e3)

* 都道府県名をクリックした際も`タグ別`同様に別ページに遷移してユーザー一覧を表示させる
![image](https://github.com/user-attachments/assets/073e98ca-5281-4a5f-8db2-11ba6f1e6f79)

* 現在の`タグ別ユーザー一覧`のように、ユーザーを多い県を順番に並べる
ユーザーアイコンも`タグ別`と同様に表示する
* 現在の`都道府県別`の左側に表示されている地方別のカラムはそのまま残しておく

お手数ですがご回答よろしくお願いいたします。

**Comment by komagata** [comment]
@machida 上記いかがでしょうか？

**Comment by machida** [comment]
@Shrimprin (cc @komagata )

返信遅れてすいません。

デザインを考えました。

都道府県別トップは、

タグ別ユーザー一覧と同じで、都道府県ごとにアイコンが並んでる形にしたいと思います。
ただ、全てを表示すると表示に時間がかかるなどありましたら、別の表示を検討したいと思います。

都道府県個別は、

ユーザー一人ひとりをカードで表示する形にしたいと思います。

----

## 都道府県別トップ

<img width="1528" alt="貼り付けた画像_2024_07_31_15_44" src="https://github.com/user-attachments/assets/4073c5d7-b972-4b88-9c2e-0f44165ec9d2">

## 都道府県個別

<img width="752" alt="image" src="https://github.com/user-attachments/assets/f207b62b-e7a7-41c5-8207-0384e9ed5e39">

**Comment by Shrimprin** [comment]
@machida 
デザインのご提案ありがとうございます！
いただいたスクショをもとに進めさせていただきます 😆
