### ISSUE TITLE
admin権限をもつユーザーで、自身の登録情報変更を更新してもDBに反映されない項目がある。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7874]
admin と mentor の権限を持っている user 、machida でログインし、登録情報変更で mentor のチェックを外す。

<img width="576" alt="貼り付けた画像_2024_06_19_17_08" src="https://github.com/fjordllc/bootcamp/assets/168265/12ca3f95-3d6d-4e74-8f86-db12e9cde5fd">

再度、 mentor のチェックを入れて保存をしてもチェックされたことがDBに保存されていない。

**Comment by motohiro-mm** [comment]
@machida 
お疲れ様です！issueについて2つ質問があります。

1. issueに記載のバグを再現できなかったため、machidaさんの手元でのバグが同じであるかと、バグへの理解が正しいかを確認したいです。

再現できたバグは以下です。（`machida`でログインしてます）
- 「登録情報変更」から「メンター」のチェックを外して「更新する」をクリックしてもメンターのままになっている
- コンソールでmentorをfalseにした後、「メンター」のチェックを入れて「更新する」をクリックしてもメンターにならない

ちなみに、「登録情報変更」からは、「メンター」「請求書払いのユーザーである」「休会六ヶ月後に自動退会しない」の項目がチェックをつけ外しをしても変更できない状態でした。

2. issueへの理解が以下で正しいか確認させてください。
「管理者」としてログインし、「登録情報変更」で「メンター」へのチェックのつけ外しをDBに反映させる

上記の「請求書払いのユーザーである」「休会六ヶ月後に自動退会しない」に関してはそのまま変更できない状態で良いでしょうか？

お手隙の際に回答のほどよろしくお願いいたします。

**Comment by machida** [comment]
@motohiro-mm 調査ありがとうございます！！他の部分は未確認でした。他の部分も一緒に修正をお願いしたいです🙏Issueのタイトルもそれに合わせて修正をお願いします🙏

**Comment by motohiro-mm** [comment]
@machida 
ありがとうございます！承知しました！

**Comment by motohiro-mm** [comment]
@machida 
すみません上記3つ以外に、「サブスクリプションID」の項目もDBに反映されていませんでした。
他と同じように反映するよう一緒に修正したいと思います。

もしこちらの項目は同様に修正しなくて良い等ありましたら返信いただければと思います。

**Comment by motohiro-mm** [comment]
@komagata @machida 

お疲れ様です！
お手隙の際に本番環境での確認をお願いいたします🙏

確認手順は以下です。

1. 管理者権限をもつユーザーでログイン
2. [登録情報変更](https://bootcamp.fjord.jp/current_user/edit)をひらく
3. 以下の項目について情報を変更し「更新する」をクリック
・自動退会設定の「休会六ヶ月後に自動退会しない」
・請求書払いの設定の「請求書払いのユーザーである」
・サブスクリプションID
・特殊ユーザー属性の「メンター」
4. 再度[登録情報変更](https://bootcamp.fjord.jp/current_user/edit)をひらいて、上記項目の今行った変更が反映されているかを確認する

**Comment by machida** [comment]
@motohiro-mm
本番で確認できました:ok_man:
実装ありがとうございます！！

**Comment by motohiro-mm** [comment]
@machida 
ありがとうございます！🙏

**Comment by motohiro-mm** [comment]
本番環境で確認していただきましたので、こちらのissueはcloseします！
