### ISSUE TITLE
質問作成時にバリデーションエラーが発生すると、選択したプラクティスが「選択なし」になる

### ISSUE THREAD

**Issue by futa4095** [fjordllc/bootcamp#7881]
## 概要

質問作成時に何らかのバリデーションエラーを発生させると、
せっかく選択したプラクティスが「プラクティス選択なし」になってしまいます。

## 再現手順

1. 質問作成ページにアクセス。
2. 任意のプラクティスを選択、タイトルor質問文のどちらかを未入力にし「WIP」ボタンをクリック。
3. エラーが表示され「プラクティス選択なし」が選択される。

## 期待される振る舞い

エラー前に選択したプラクティスが選択されている。

## スクリーンショット

エラーになった後のスクショ
![image](https://github.com/fjordllc/bootcamp/assets/69447745/847caade-db34-47db-8993-6aeb607fcdbb)

**Comment by komagata** [comment]
@nishitatsu-dev `2`ポイントでOKだと思います〜。

**Comment by nishitatsu-dev** [comment]
@komagata 
ポイントの確認、ありがとうございます🙏

**Comment by nishitatsu-dev** [comment]
@komagata @machida 
お忙しい所すみませんが、以下の部分について、本番環境での動作確認をお願い致します🙏
（「メンターまたはadmin」だけ見れる部分のため）

1. [質問作成 \| FBC](https://bootcamp.fjord.jp/questions/new)にアクセスする
1. 作成者（初期値はログインユーザー）を「初期値以外」に変更する。
1. 「タイトル」と「質問文」は空欄のまま、WIPボタンを押し、バリデーションエラーを発生させる
1. 上記2で選択した「作成者」が初期値にならず、値が保持されていることを確認する

**Comment by machida** [comment]
@nishitatsu-dev 本番で確認しました！！OKでしたー🙆
実装ありがとうございます🙏

**Comment by nishitatsu-dev** [comment]
@machida 
ありがとうございました〜🙏

**Comment by nishitatsu-dev** [comment]
本番環境で動作確認できたのでクローズします。
