### ISSUE TITLE
特定の回数で表示される日報提出お祝いメッセージが、下書きの日報もカウントしている

### ISSUE THREAD

**Issue by sugiwe** [fjordllc/bootcamp#7885]
## 概要

100、777、800など特定の回数で表示される日報提出お祝いメッセージですが、下書きが1つある状態で799日目の日報を提出した時に「800」のお祝いメッセージが表示される現象を確認しました。

## 再現手順

チーム開発着手前で本番環境しか触っていないので再現性に乏しいかもしれませんが、一度発覚した後に、提出済みの日報を下書きに戻して以下の手順を実行して、同じ現象が起こることを再確認しました。

1. 日報の提出数を798にして、下書きを2つの状態にする（全部合わせて800の状態）
2. 下書きの日報のうち1つを提出する（提出完了が799、下書きが1の状態）
3. お祝いメッセージが表示されることを確認

## 期待される振る舞い

下書きを合わせた数ではなく、提出完了の数が800になった時にお祝いメッセージが表示される

## スクリーンショット

![20240624_fbc](https://github.com/fjordllc/bootcamp/assets/25524188/1d2265b3-5d1b-45ce-ad6b-437547917f33)

次の日（800日目）の日報を下書きで準備中の状態で、799日目の提出を出した際にお祝いメッセージが表示された時のスクリーンショットです。
（見づらいですが、左上の赤波線をつけたところが「799」となっています）

## 環境

 - OS: iOS 17.5.1
 - ブラウザ: safari

## 関連Issue, PR
Issue: https://github.com/fjordllc/bootcamp/issues/7344
PR: https://github.com/fjordllc/bootcamp/pull/7416
（777日目提出の時に、この機能とっても素敵だなと思いちょうどPRを拝見していたところでした）

**Comment by sugiwe** [comment]
追記になりますが、翌日に800日目の日報を提出した際にも800日のお祝いメッセージが表示されました。（＝つまり、私は2回連続で800日のお祝いが表示された）

さらに実験として、800日目の日報を再度下書きに戻して、「801日目の下書きを保存した状態で800日目の日報を提出」した場合には、800日目にもかかわらずお祝いメッセージは表示されませんでした。

以上のことから、提出時点でユーザーが保存（公開・下書きの合計）している日報数をもとにしてお祝いを出すかどうかを判断していると推測いたしました。

お祝い表示のトリガーは「提出」だと思います（下書き保存してもお祝いは表示されない）ので、日報数のカウントも「（下書きは含まずに）提出済みの数」にすると良いのではと考えました。

ご検討の程よろしくお願いいたします🙏

**Comment by Ryooo-k** [comment]
@komagata 
こちらのIssueを進めている最中に疑問点が出てきましたので、ご報告・質問させていただきます。

## 報告

お祝いメッセージの文言に違和感がある場合があります。

## 詳細

下記スクリーンショットの通り、９９日目の日報をwipとし、１００日目の日報を先に提出した後、９９日目を提出すると１００**日**目の日報提出としてお祝いメッセージが出力されます。

![Image](https://github.com/user-attachments/assets/3fa88cd9-2949-46f5-a747-d167ccc93cad)

![Image](https://github.com/user-attachments/assets/f1b9057d-0ea7-41a4-81b3-2885d3a80ffc)

## 対策

〇〇「日」目ではなく〇〇「回」目に文言を変更した方が違和感がないと感じました。

## 質問

Issueを進めていく中で、不具合や違和感を見つけた場合は、今回のようにこちらのコメントにて報告でもよいでしょうか。

## コメント

あまりこのような状況は少ないと思いますが、少し気になったので報告させていただきました。

**Comment by komagata** [comment]
@machida (CC: @Ryooo-k ) こちら僕もそうかなと思うんですが、町田さんはいかがでしょうか

**Comment by machida** [comment]
@Ryooo-k @komagata 
なるほど、確かに、最新の公開した日報より古い日報がWIPの場合を考慮すると、n回目の方がいいですね！
n回目に修正するのもこのIssueに含めていただきたいです🙏

**Comment by Ryooo-k** [comment]
@machida 
ご確認ありがとうございます！

> n回目に修正するのもこのIssueに含めていただきたいです🙏

承知しました！

**Comment by Ryooo-k** [comment]
@komagata 
お疲れ様です。不具合のような動作を確認しましたので対応方法のご相談です。


## 不具合の内容

お祝いメッセージを何度も表示させることが出来る

## 詳細

1. 100回目の日報提出を行い、お祝いメッセージを表示する 

<img width="895" alt="スクリーンショット 2024-10-11 19 32 41" src="https://github.com/user-attachments/assets/3608cb0d-c3e4-427b-a39c-cf769680986a">

2. 提出した100回目の日報を編集し、「内容変更」を押す

<img width="1025" alt="スクリーンショット 2024-10-11 19 35 54" src="https://github.com/user-attachments/assets/abe645fa-1f60-4ada-a4e1-ed1e061bb3e9">

3. 再びお祝いメッセージが表示される

<img width="893" alt="スクリーンショット 2024-10-11 19 38 01" src="https://github.com/user-attachments/assets/f4c87254-6fbf-4f6c-9770-b36e670718a9">


## 対応方法

対応方法は下記３つがあると考えてますが、どのような対応がよいでしょうか。

- 今回のissueで対応をする
- 別のissueで対応するので、今回のissueでは対応しない
- 不具合ではない！何度でもお祝いメッセージ表示するんだ！！！（対応しない）

**Comment by komagata** [comment]
@Ryooo-k それぞれ表示したかどうか保存するもの大変かつ今後も変わりそうで、まあお祝いがたくさんでて悪い意味ではないので対応しなくて大丈夫です。

**Comment by Ryooo-k** [comment]
@komagata 
ご確認ありがとうございます。
承知しました！

**Comment by Ryooo-k** [comment]
本番環境での動作確認が完了したためCloseいたします。

**Comment by Ryooo-k** [comment]
@komagata
本番環境の動作確認は完了しましたが、[テストデータ削除](https://github.com/fjordllc/bootcamp/pull/8150)がまだマージされてないようです。Closeは待っておいた方が良いでしょうか。

**Comment by Ryooo-k** [comment]
テストデータ削除のPRがマージされましたので、Closeいたします。
