### ISSUE TITLE
nishideさんのアイコン画像の透過部分が黒くなっている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#789]

**Comment by komagata** [comment]
@machida @nishide-h すいません、これ移行時にpngをjpgとして保存しちゃったからで、画面から再度アップしてもらうしか修正方法が無いかもです。

**Comment by machida** [comment]
なるほど、これはお客さんのプロジェクトのときの移行は怖いですね。
お知らせから告知するようにします。
