### ISSUE TITLE
ポートフォリオのページの見出しを変更したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7894]
https://bootcamp.fjord.jp/portfolios
ここにアクセスすると、みんなのポートフォリオ一覧が表示される。

このページの見出し、

<img width="509" alt="貼り付けた画像_2024_06_27_10_18" src="https://github.com/fjordllc/bootcamp/assets/168265/b995a66f-d91b-403a-b9a0-1bab4d1411ba">

これを `みんなのポートフォリオ` に変更したい。

<img width="509" alt="貼り付けた画像_2024_06_27_10_18" src="https://github.com/fjordllc/bootcamp/assets/168265/75dae0c1-8092-4833-a35a-a896cca6aed6">

**Comment by Judeeeee** [comment]
本番環境で動作確認したのでcloseします。
