### ISSUE TITLE
ポートフォリオページのタイトルタグを変更したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7895]
https://bootcamp.fjord.jp/portfolios
みんなのポートフォリオページ（作品一覧）の

- title タグは `ポートフォリオ | FBC`
- og:titleは `ポートフォリオ`

になっている。

<img width="968" alt="貼り付けた画像_2024_06_27_10_24" src="https://github.com/fjordllc/bootcamp/assets/168265/516b7d91-0efa-4487-b970-7371c7be622f">

これを

- title タグは `みんなのポートフォリオ | FBC`
- og:titleは `みんなのポートフォリオ`

にしたい。

**Comment by Judeeeee** [comment]
本番環境で動作確認したのでcloseします。
