### ISSUE TITLE
アイコンは正方形でトリミングされたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#790]

**Comment by komagata** [comment]
@machida これって検証したいのですが変になってることがわかるURLなどいただけるとありがたいですー

**Comment by machida** [comment]
@komagata 

https://bootcamp.fjord.jp/products/1074
例えばこのアイコンがそうです。
今はCSSで無理やり対応しています。

object-fit を外すと画像が縦長になっておかしくなるのが確認できます。
![image](https://user-images.githubusercontent.com/168265/52847598-fab73980-314f-11e9-9699-6c1446105b5a.png)

**Comment by komagata** [comment]
@machida なるほど、ありがとうございます！

**Comment by machida** [comment]
CSS対応していないものも見つけました。

![image](https://user-images.githubusercontent.com/168265/52848079-356da180-3151-11e9-8035-6c4fee941b2b.png)
