### ISSUE TITLE
【メンター向け】「○○さんが入会しました」の通知メールにコース名を載せてほしい

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#7914]
これまでと違い、7月からRailsエンジニアコースとフロントエンジニアコースの2パターンができたので、通知メールにどっちのコースなのか書いてあるとちょっと嬉しいです。

まあ、プロフィールページを見に行けばわかるのですが、なんとなくメールを見たタイミングでどっちのコースなのかがわかると嬉しいな〜という感じです。
緊急度は高くありません。

![Screenshot 2024-07-02 at 8 24 44](https://github.com/fjordllc/bootcamp/assets/1148320/c677c65e-6017-4bef-bc67-10e471defe15)

**Comment by machida** [comment]
@MikotoMakizuru 

確認しました！一旦、それでお願いします。
このタイミングでメール通知の中身をいじりたいと思います。実装が完了したら、machidaにメンションをお願いします。

**Comment by MikotoMakizuru** [comment]
@machida 
実装完了いたしましたのでご連絡いたします。

**Comment by MikotoMakizuru** [comment]
@komagata @machida 
デプロイされたので新しい受講生が参加したときにメンターに届くメールにコース名が記載されているか本番環境にて確認をお願いしたいです。

**Comment by machida** [comment]
@MikotoMakizuru 
本番で確認できました！！

**Comment by MikotoMakizuru** [comment]
本番環境で確認できたので Close します〜
