### ISSUE TITLE
大きな画像があると通知メールが横に大きくはみ出す

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#7915]
## 概要

大きな画像があると通知メールが横に大きくはみ出す

## 再現手順

1. Sun, Jun 30, 2024 at 7:38 AM に送信された「komagataさんがDocsに色んな質問方法を投稿しました」の通知メールをChrome内のGmailから開く
2. メール全体が大きく横にはみ出している（加えてヘッダー画像も巨大化する）

## 期待される振る舞い

大きすぎる画像は縮小するなどして、メール全体が画面に収まるように表示されてほしい

## スクリーンショット

![Screenshot 2024-07-02 at 8 31 54](https://github.com/fjordllc/bootcamp/assets/1148320/b41b835d-52e7-414f-a252-c76ced67bf5d)

## 環境

 - OS: macOS 14.5
 - ブラウザ: Chrome
 - バージョン: Version 126.0.6478.127 (Official Build) (arm64)

**Comment by machida** [comment]
@thmz337 

こちら、厄介なバグなのと、確認作業も大変なIssueだったので、僕の方で対応しました。

<img width="780" alt="image" src="https://github.com/user-attachments/assets/ce285bc4-a2e7-4580-992b-747a5b921c21">

代わりに別のIssueをアサインさせていただきます。
