### ISSUE TITLE
本の情報がはみ出る

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7937]
本の一覧（`/books`）で文字がはみ出る。
おそらく「必読」が付いた場合にはみ出る。

![スクリーンショット 2024-07-07 11 06 41](https://github.com/fjordllc/bootcamp/assets/16577/8f8bb403-f044-4bd3-9451-ba08535d551a)

**Comment by machida** [comment]
:memo:
説明にURLが含まれてたため。修正済。
