### ISSUE TITLE
worried-users.vue, worried-user.vueを非JS化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7952]

**Comment by motohiro-mm** [comment]
@komagata @machida

お疲れ様です。
1つ伺いたい点があります。

## worried-userが一人もいない場合の表示について
「worried-userが一人もいない場合」は、現状そのままテーブルの項目が表示されているのですが、条件分岐を追加してworried-userが一人もいない場合は「進捗が遅れている受講生はいません」と表示させたらどうかと考えました。
以下に既存のスクショと、今回提案させていただく表示のスクショを貼っておきますのでご確認いただければと思います。
（デザインは他の実装のコードを参考にしました）
この提案が不要であれば、既存の表示のままVue→viewへの変更をしていきたいと思います。
よろしくお願いいたします。

#### 既存の実装
- worried-userが存在する場合（参考）
<img width="1311" alt="スクリーンショット 2024-07-25 15 16 47" src="https://github.com/user-attachments/assets/c466db68-ee6d-4771-b06c-969165231a99">

  - worried-userが一人もいない場合
<img width="1285" alt="スクリーンショット 2024-07-26 15 57 52" src="https://github.com/user-attachments/assets/67fdd37b-6f3d-4276-befe-67a0a17d29c9">

#### 今回提案させていただく表示
  - worried-userが一人もいない場合
<img width="1317" alt="スクリーンショット 2024-07-25 17 22 20" src="https://github.com/user-attachments/assets/233fc385-4299-457f-baa0-a29f9f0aa869">

**Comment by motohiro-mm** [comment]
@komagata @machida 

お疲れ様です！
お手隙の際に、こちらのissueの本番環境での確認をお願いいたします。
また、進捗が遅れているユーザーが0人の状態のときの表示の確認は、本番環境では現在0人でなければ確認できないと思いますので、そちらの確認はなしでよろしいでしょうか？回答をお願いいたします🙏

確認手順を以下に示します↓
1. メンター権限のあるユーザーでログイン
2. メンターページへ遷移
3. メンターページトップに進捗が遅れているユーザーが以下のように表示されているかを確認
<img width="1311" alt="スクリーンショット 2024-07-25 15 16 47" src="https://github.com/user-attachments/assets/3b34ecf9-f785-4aaa-8a21-df537ffac84d">

**Comment by motohiro-mm** [comment]
本番環境で確認していただきましたので、こちらのissueはcloseにします！
