### ISSUE TITLE
test/helpers配下がテストファイルとして認識されていない。

### ISSUE THREAD

**Issue by reckyy** [fjordllc/bootcamp#7961]
## 概要

test/helpers配下のファイルが、`_test.rb`で終わっていないため、テストファイルとして認識されておらず、`rails test test:all`（ローカル）やCIで実行されていない。

実際、その拡張子を追加すると`rails test test:all`した時のアサーションが増える。
また、どれかヘルパーのテストファイルを削除してもアサーションの数は変わらない。

## 関連

下記PRの中で、失敗するはずのテストが通ってしまっていたことから発覚。
https://github.com/fjordllc/bootcamp/pull/7443#discussion_r1678189594

- https://github.com/fjordllc/bootcamp/pull/7443

**Comment by reckyy** [comment]
@machida 
以下、差し出がましいことにはなりますが、ご確認いただけますと幸いです。
こちらのIssueですが、単に拡張子を変更するだけなのでgood first Issueとして良さそうだと感じましたが、自分がやってしまっても大丈夫でしょうか。

**Comment by machida** [comment]
@reckyy 提案ありがとうございます！good first issueにしたいと思いますー
