### ISSUE TITLE
ログイン時のQ&A個別ページのtitleタグの文字数を制限したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7963]
ログインし、Q&A( localhost:3000/questions/  )に長いタイトルの質問を作成する。

<img width="820" alt="image" src="https://github.com/user-attachments/assets/9382b371-724d-46ab-91d8-d10bf16e3adc">

右クリックでページのソースを見る。
<img width="380" alt="貼り付けた画像_2024_07_17_22_46" src="https://github.com/user-attachments/assets/0503ac5c-6903-4a81-8c75-814801f98757">

HTMLのtitleタグを見る。（下のキャプチャ赤矢印）

<img width="1142" alt="貼り付けた画像_2024_07_17_22_48" src="https://github.com/user-attachments/assets/68521b81-f3fb-4844-8ca5-bb560f05dd58">

`<title>(development) Q＆A: 長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問 | FBC</title>`

このようになっている。

このtitleタグの中身を35文字くらいに抑えたい。
しかし、`og:title` 、`twitter:description`、`og:description` （緑矢印）はそのままにする。

---

> このtitleタグの中身を35文字くらいに抑えたい。

どのようにして、titleタグの中身を35文字くらいに抑えるか？

`<title>(development) Q＆A: 長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問 | FBC</title>`

これは、

`<title>(development) Q＆A: {質問タイトル} | FBC</title>`

このようにして表示している。

`(development) ` という文字は開発環境でしか表示されず、本番環境では表示されないので無視する。
`(development) ` という文字は35文字の中に含めない。

`Q＆A: {質問タイトル} | FBC` の `{質問タイトル} ` の部分を https://railsdoc.com/page/truncate を使うなどして省略する。

今回の場合は、

`<title>(development) Q＆A: 長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問 | FBC</title>`

これが、

`<title>(development) Q&A: 長いタイトルの質問長いタイトルの質問長いタイ... | FBC</title>`

こうなればOK。

---

このIssueを書いている間に別の問題も見つかったので、それも同時に対応をお願いします・

`Q＆A`が全角になっていました。半角に修正をお願いします。 

---

厳密に35文字でなくて大丈夫です。
大体35文字くらいで。

**Comment by machida** [comment]
> Q＆Aが全角になっていました。半角に修正をお願いします。

タブに表示される文字がちゃんとしていれば、HTMLを見た時にアンパサンドで表示されても問題無しです。

**Comment by MikotoMakizuru** [comment]
本番環境で動作が確認できたので Close します。
