### ISSUE TITLE
未ログイン時ののQ&A個別ページのtitleタグの文字数を制限したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7964]
ログインし、Q&A( localhost:3000/questions/  )に長いタイトルの質問を作成する。

その質問ページ（questions/show）にログアウトした状態でアクセス。

右クリックでページのソースを見る。

HTMLのtitleタグを見る。（下のキャプチャ赤矢印）

<img width="1034" alt="貼り付けた画像_2024_07_17_23_01" src="https://github.com/user-attachments/assets/c4a639d0-2855-4d79-a055-217bf5751806">

`<title>(development) 長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問 | FBC</title>`

このようになっている。

このtitleタグの中身を35文字くらいに抑えたい。
しかし、`og:title` 、`twitter:description`、`og:description` （緑矢印）はそのままにする。

---

> このtitleタグの中身を35文字くらいに抑えたい。

どのようにして、titleタグの中身を35文字くらいに抑えるか？

`<title>(development) 長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問 | FBC</title>`

これは、

`<title>(development) {質問タイトル} | FBC</title>`

このようにして表示している。

`(development) ` という文字は開発環境でしか表示されず、本番環境では表示されないので無視する。
`(development) ` という文字は35文字の中に含めない。

`{質問タイトル} | FBC` の `{質問タイトル} ` の部分を https://railsdoc.com/page/truncate を使うなどして省略する。

今回の場合は、

`<title>(development) 長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問長いタイトルの質問 | FBC</title>`

これが、

`<title>(development) 長いタイトルの質問長いタイトルの質問長いタイトルの質... | FBC</title>`

こうなればOK。

---

厳密に35文字でなくて大丈夫です。
大体35文字くらいで。

**Comment by MikotoMakizuru** [comment]
本番環境で動作が確認できたので Close します。
