### ISSUE TITLE
ユーザー一覧に「コース別」が欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7998]
<img width="577" alt="貼り付けた画像_2024_08_07_22_28" src="https://github.com/user-attachments/assets/dc329ca0-54d4-4409-89df-1378f4217629">

このタブを追加し、コース別のユーザー一覧ページを作成する。

<img width="1333" alt="image" src="https://github.com/user-attachments/assets/5758f851-d5f8-4991-a703-299f29549a59">

- Railsエンジニアコース
- フロントエンドエンジニアコース
- Railsエンジニアコース・フロントエンドエンジニアコース以外

でカテゴリー分けする。

対象は「現役生」と「現役研修生」のみにする。

**Comment by ham-cap** [comment]
@machida 
ご確認とご連絡ありがとうございます🙏
不具合を出してしまって申し訳ありません。
対応にあたって一点確認させていただきたいのですが、その他に分類されるコースはすべて非公開になっていると考えてよろしいでしょうか？👀
現在の実装では一般に公開されているコースを対象にユーザーの絞り込みを行っているため、その辺りを修正する必要があると考えています。

**Comment by machida** [comment]
@ham-cap なるほど！全部非公開のコースですね。非公開にしなくてはいけない情報ではないのですが、たくさんの企業の研修コースがあるので、それらを出すと企業研修以外のコースを探すのが大変になってしまうので非公開にしてるんですよね。

なので、その他には非公開のコースを選択している受講生も含めていただけるとありがたいです🙏

別issueで非公開コースではなく、企業研修用コースのようにフラグ名を変更したいと思います。

今出ているものが不具合ではなく、意図通りで良かったですー(不具合が起きててもhamcapさんのせいとかはないので全然謝る必要ないです)

**Comment by machida** [comment]
@ham-cap この変更については、緊急リリースするほどの緊急性はないですー。通常のリリースに載せていただけたらと思います。

とはいえ、早いリリースに越したことはないので、レビューは受講生のレビューは飛ばして @komagata さんレビューだけでお願いします🙏

**Comment by ham-cap** [comment]
@machida 
ありがとうございます！
通常リリースでもよい旨も承知いたしました！
そこまで複雑な修正にはならないと思うので、できる限り早めに仕上げてレビューをお願いしたいと思います🙏

ちなみに、非公開コースの実態としては企業別のオーダーメイドカリキュラムであり、研修としてFBCを利用する提携企業さんが増えればそれだけオリジナルのコースも増えるという理解で大丈夫でしょうか？
だとすると、私が当初想定していたよりも頻繁にコースが増減しそうなので、ユーザーを絞り込む際のコース名の取得方法も見直したいと思います。

**Comment by machida** [comment]
@ham-cap 

> ちなみに、非公開コースの実態としては企業別のオーダーメイドカリキュラムであり、研修としてFBCを利用する提携企業さんが増えればそれだけオリジナルのコースも増えるという理解で大丈夫でしょうか？

はい、1企業1コースではないこともあるので結構増えますね〜。
とはいえ、

- フロントエンドエンジニアコース
- Railsエンジニアコース
- それ以外

で絞り込むだけなので、フロントエンドエンジニアコースとRailsエンジニアコースだけが特別扱いされてる感じです。

---

ちなみにこのようなIssueを立てようかなと考えています。

今企業研修のコースは「非公開」フラグが付いています。
「非公開」フラグを名前を変えて「企業研修」フラグに変更します。

で、絞り込みは

- フロントエンドエンジニアコース
- Railsエンジニアコース
- その他→企業研修コース

とする。（というのも「その他」とは全て企業研修生なんですよね。）

コース一覧も変更する。

![貼り付けた画像_2024_10_31_11_24](https://github.com/user-attachments/assets/9be0661f-03c9-4383-986a-b3de386e33aa)

**Comment by ham-cap** [comment]
@machida 
なるほど👀
私もいま修正していて「公開/非公開」のフラグで分ける感じになったので、フラグの名称変更は実態に則していて分かりやすくなると思います😃

取り急ぎ、別ブランチを切って修正いたしましたので、後ほどPRを起案してレビューのお願いをしたいと思いますー🙏

**Comment by machida** [comment]
@ham-cap 修正ありがとうございます🙏

**Comment by ham-cap** [comment]
本番環境で動作確認いたしましたのでクローズします。
