### ISSUE TITLE
質問の新規投稿ができない

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/bootcamp#804]
## 状況
- 質問が新規投稿できない
  - 登録するボタンを押すと/questions/newが再レンダリングされる（エラーメッセージはなし）
  - ローカルで最新のmasterで再現しようとしたが同じ操作をしても正常に投稿できる
  - 投稿できないのはプラクティス詳細画面経由・質問一覧画面経由ともに同じ
- 質問の更新はできる
- その他新規作成系の機能も正常に動く（質問に対する回答投稿で確認）

**Comment by machida** [comment]
箇条書きが3階層まで深くなると読みにくい

**Comment by sanfrecce-osaka** [comment]
@machida すみません、修正しました。

**Comment by ima1zumi** [comment]
今は投稿できていると思うのでCloseします。
