### ISSUE TITLE
プラクティスなのにタイトルが"Q&A"になっている

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#8053]
未ログイン状態で https://bootcamp.fjord.jp/practices/168 にアクセスすると、ブラウザのタブに "Q&A" が表示されます。
（このページはQ&Aではなくプラクティス）

![Screenshot 2024-09-05 at 8 15 35](https://github.com/user-attachments/assets/2f2f3790-605a-4ded-a6aa-4c75cc5513c0)

詳しく調べていませんが、もしかすると他の種類のページでも正しくその種別をタイトルに表示できていないかもしれません。

**Comment by hagiya0121** [comment]
本番環境で確認できたのでクローズします。
