### ISSUE TITLE
他ユーザーのメール通知をOFFにできてしまう

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#8056]
- 関連 https://github.com/fjordllc/bootcamp/pull/7945

メール通知をOFFにする画面で、HTMLを変更することで他ユーザーのメール通知をOFFにできてしまいます。

## 例
machidaさんがkomagataさんにメンションする
![Screenshot 2024-09-07 at 12 06 00](https://github.com/user-attachments/assets/9177d3b3-8416-4fa4-b3eb-9b7f86cf48b2)

komagataさんがメールのリンクから通知OFF画面に遷移する
このとき、オフにするボタンのURLはkomagataさんのユーザーID
![Screenshot 2024-09-07 at 12 04 05](https://github.com/user-attachments/assets/d867e481-2703-4635-a526-644c35adaf96)

machidaさんのメール通知はON
![Screenshot 2024-09-07 at 12 04 31](https://github.com/user-attachments/assets/0153ad1d-ccdd-41d9-92a4-68f1fd0c64f7)

komagataさんはHTMLをいじってmachidaさんのユーザーIDに書き替え、それからオフにするボタンをクリックする
![Screenshot 2024-09-07 at 12 04 24](https://github.com/user-attachments/assets/9fbdf11d-c964-4c0a-b2f7-b8b6b2a32f12)

komagataさんはmachidaさんのメール通知をOFFにすることに成功する
![Screenshot 2024-09-07 at 12 05 50](https://github.com/user-attachments/assets/fbea3b58-f0cd-4a28-9b19-52f7a901ad67)

**Comment by Ryooo-k** [comment]
本番環境での動作確認が完了しましたのでCloseいたします。
