### ISSUE TITLE
ブログの公開済み記事が公開日順に並んでない（デグレ）

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#8058]
![image](https://github.com/user-attachments/assets/b0021cb4-bc25-4ede-9b04-923c6fd6a249)

公開済み一覧・WIP一覧が実装される前は公開日順に並んでいたのとこと via @ytogo

**Comment by machida** [comment]
![Image](https://github.com/user-attachments/assets/ca599045-767b-4c38-bd81-ff7152cbb793)

メンターでログイン。
公開済みタブを選択しているとき、記事は published_at 順で並ぶようにする。
現在は created_at か id 順など、それ以外の並び順になってしまっている。

**Comment by machida** [comment]
デグレなので、再発を防止するためにテストがほしい。

**Comment by MikotoMakizuru** [comment]
本番環境にて、公開日時降順で表示されていることが確認できたため Close します〜
