### ISSUE TITLE
GitHub Projectsへのリンクが切れている

### ISSUE THREAD

**Issue by kotakanazawa** [fjordllc/bootcamp#8063]
## 概要

GitHub Projectsへのリンクが切れています。

## 再現手順

1. フッターのGitHub Projectsをクリック

![CleanShot 2024-09-11 at 13 41 06@2x](https://github.com/user-attachments/assets/edd3e1de-edfc-49fe-89b2-43dfdcd3c914)

2. 404が表示される。

![CleanShot 2024-09-11 at 13 43 06@2x](https://github.com/user-attachments/assets/35e10728-f921-455a-8bae-477c78d2090e)

## 期待される振る舞い

フィヨルドブートキャンプアプリケーションのKanbanが表示されること。

2024/09/11現在だと、Kanbanは https://github.com/orgs/fjordllc/projects/7 でやっているようなのでそちらが適切かもしれません。（とはいえこれもproject idが変わればいずれまた404になりそう）

**Comment by machida** [comment]
こちら対応完了してますのでクローズにさせていただきますー
