### ISSUE TITLE
管理者は、参加者を削除できるようにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#8074]

**Comment by ayu-0505** [comment]
９月３０日（月）の質問雑談タイムで不明点を質問しました。
#### 定期イベントの管理者とは定期イベントの主催者のことで良いか
定期イベントの主催者のことで良い。
#### 具体的にどのような想定か
- MTGなどの「プラクティスの進行によって限定的に参加するイベント」にて、参加義務が終了したのちも参加者が参加登録を解除し忘れてそのまま残ってしまっている場合。
- 参加登録を行なったこと自体を忘れて実際には参加していない場合や、休会・退会時。（退会時は自動的に外れるように、別途issueで実装する可能性あり）

**Comment by ayu-0505** [comment]
お疲れ様です🍵

UIと実装方法について迷ったので質問させてください。
現在２つのUIが思い付いていますが、「想定された内容とかけ離れていないか」「実装方法として現実的なのか」
等々で判断に迷っています。
ご意見を伺えたらと思います。
### 案１
メンターの画面では、常に参加者アイコンの横に「削除する」というリンクが表示されている。
リンク先は`participations_controller.rb`の`destroy`アクションとし、アイコンの`user_id`をparamsとして送信する。

<img width="730" alt="スクリーンショット 2024-10-02 16 43 12" src="https://github.com/user-attachments/assets/d477882d-cac9-4e77-adba-aedbc771cd0c">

`participations_controller.rb`の`destroy`内の`current_user`を`user`に変更。
`user`をセットできるのは`user = current_user`または`current_user = メンター`の場合のみに制限する。

```rb
class RegularEvents::ParticipationsController < ApplicationController
  skip_before_action :require_active_user_login, raise: false
  before_action :set_regular_event

  def destroy
    # ここでuserを宣言する。
    # `user = current_user`または`current_user = メンター`の場合のみuserをセットできる。
    @regular_event.cancel_participation(current_user)  #current_user を user に変更する。
    redirect_to regular_event_path(@regular_event), notice: '参加を取り消しました。'
  end
```

#### 案１にて実際に想定される表示
<img width="730" alt="スクリーンショット 2024-10-03 10 43 51" src="https://github.com/user-attachments/assets/a21c358d-088b-4dc5-b93b-4da84714b850">

#### 案１の懸念点
メンターの立場で定期イベント参加者部分を見た時、画面表示がごちゃつく。
（イベントページ全体のスクショを撮る際などに、見た目が悪い）

### 案２
「参加者を編集する（削除する）」というようなボタンを設置し、クリックされたら削除リンクを表示する。
<img width="727" alt="スクリーンショット 2024-10-02 16 41 16" src="https://github.com/user-attachments/assets/50cf019b-f4ff-414f-9243-ddae62c2aea8">


<img width="731" alt="スクリーンショット 2024-10-03 10 58 07" src="https://github.com/user-attachments/assets/e50df801-af23-4693-93b2-efca418d0d19">

#### 案２の懸念点
現時点では具体的な実装方法が浮かんでおらず、模索の段階です。

**Comment by ayu-0505** [comment]
１０月７日（月）の質問雑談タイムで上記のUIと実装方法の件について質問しました。
### issueタイトルを変更してもよいか
issueという名前の通り、議論の場なので変更についての制限はない。

### UIと実装方法について
案１の形で作成を進める。
`user_id`を同時に表示する案があったが、`user_id`はアイコンホバーでも表示されるので、一旦現状のままで実装する。

**Comment by ayu-0505** [comment]
PR内で連絡があり、参加者削除機能の権限を「メンター」から「管理者」に変更しました。

**Comment by ayu-0505** [comment]
@komagata さん、@machida さん、お疲れ様です🍵
こちらのIssueの本番環境確認ですが、管理者権限のログインが必要ですのでお手隙の際にご確認をお願いできますでしょうか。

1. 定期イベントにアクセス（[bootcampアプリ開発MTG-昼の部](https://bootcamp.fjord.jp/regular_events/35)）
2. ご自身か私のアカウント（id:`ayu-0505` GitHubと同じ犬のアイコンです）の`削除する`リンクをクリック
3. クリックしたユーザーが参加者一覧から削除されているか確認
※ご自身のアカウントを削除した場合は再度参加登録をお願いします。

よろしくお願いいたします🙇🏻‍♀️

**Comment by machida** [comment]
自分のアカウントで確認しました。
本番で確認ができましたー🎉🎉🎉🎉🎉

**Comment by ayu-0505** [comment]
本番確認ありがとうございました！✨
