### ISSUE TITLE
フッターにリポジトリのリンクを追加

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#8077]
![Image](https://github.com/user-attachments/assets/8d3c53a5-0f67-4763-8fd3-985f97778396)

この部分に、

アンカーテキスト: リポジトリ
URL: https://github.com/fjordllc/bootcamp

を追加する。
target="_blank" と rel="noopener" を付けて、別タブで開くようにする。
（隣の GitHub Projects のリンクと同じ）

**Comment by ayu-0505** [comment]
本番環境で動作確認したのでcloseします。
