### ISSUE TITLE
PodCastのリンクがフッターに欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#8093]
下記のPodCast（フィヨルドブートキャスト）へのリンクがフッターに欲しい。

https://circlecast.net/groups/15

![Image](https://github.com/user-attachments/assets/fae731af-49fd-4b19-ae99-a79c53ffc268)

**Comment by sugiwe** [comment]
リンク先および表示する文字列について相談です🙏

リンク先が https://circlecast.net/groups/15 だと「CIRCLECAST内のフィヨルドブートキャンプグループ」ということになりますが、「フィヨルドブートキャスト」であれば https://circlecast.net/channels/9 のほうが適切なのではと考えましたがいかがでしょうか？

逆に、今後のことを見据えて複数の番組が立ち上がった際にもフィヨルドブートキャンプグループ内全ての番組情報が見られるということで https://circlecast.net/groups/15 に飛ばすのも良さそうですが、その場合はリンクを設定する文字列としては「フィヨルドブートキャスト」ではなく「Private Podcast」もしくは「CIRCLECAST」あたりが良いかなと思いました（「Podcast」だと個人的には外部公開されていることを期待するので避けたい気持ちがあります）

**Comment by sugiwe** [comment]
メモになりますが、上記の相談についてチーム開発MTGで相談して文字列は `フィヨルドブートキャスト`、リンク先URLは`https://circlecast.net/channels/9` ということで確認できましたのでそのように進めます！

**Comment by sugiwe** [comment]
本番環境で動作確認いたしましたのでcloseします。
