### ISSUE TITLE
自作サービス用に、輪読会一覧を取得するAPIの実装

### ISSUE THREAD

**Issue by masyuko0222** [fjordllc/bootcamp#8095]
FBC側で、自作サービス用にAPIの実装を行いたいです。
レビュー依頼は駒形さんにお願いすればよいでしょうか？

## 機能の説明
自作サービス(輪読会ノート)では、現在開催中or終了した輪読会の一覧を見ることのできる機能があります。
そのための過程として、FBC側で輪読会一覧のjsonデータを返すAPIを返す実装を行いたいです。

```
[
  {
    id: 21
    title: 'ブルーベリー本輪読会',
    finished: false,
  },
  {
    id: 31
    title: 'りアクト！輪読会',
    finished: true,
  },
  ...
]
```

### 詳細
- 自作サービス側では、クライアントは以下のURLで輪読会一覧画面を開きます。
  - `/reading_clubs?status=finished&page=1&per_page=20`

- APIで取得したreading_clubsのデータはそのまま使わず、自作サービス側で定義したReadingClubモデルに改めて保存されます。
  - このモデルはUserと双方向関連付けが行われます。
  - 輪読会一覧ページの出力も、この自作サービス側で定義したReadingClubモデルを利用して出力します。

- そのためAPIは、ユーザー操作が契機になるわけではなく、定期的(1回/1hとか)にデータを取得するバッチ処理によってよびだされます。
  - 新規登録された輪読会/更新/削除があった輪読会のみ、それを自作サービス側のreading_clubsテーブルに反映をさせます。

**Comment by komagata** [comment]
@masyuko0222 

> レビュー依頼は駒形さんにお願いすればよいでしょうか？

はい。
