### ISSUE TITLE
メンターダッシュボードに表示されている提出物一覧が、全て表示されてしまっている。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#8121]
以下の2つの機能がなくなってしまっているので、修正をしてください。

---

![Image](https://github.com/user-attachments/assets/4d4d051b-dedb-4c8e-b83e-c1f14de1dd98)

現在はこのように、全ての提出物が一覧で表示されています。
しかし、メンターダッシュボードに表示される提出物一覧は急いで対応しなくてはいけないものだけを表示する場所でした。

現在、4日経過、5日経過、6日以上経過 がカードのヘッダーに色が付きます。
メンターダッシュボードには、色が付いたカードに所属する提出物だけ表示するように修正をお願いします。
逆に言うと、3日経過を含むそれ以下の経過日数の提出物はそこに表示しないようにお願いします。

----

もう一点、メンターダッシュボードに表示する提出物一覧がないとき、
つまり、ヘッダーに色がついた提出物のカードがないとき（4日以上経過提出物がないとき）は、

```
しばらく4日経過に到達する
提出物はありません。
```

もしくは、

```
n件の提出物が、
8時間以内に4日経過にに到達します。
```

というメッセージを表示し、
そのメッセージには提出物一覧のページにリンク（`/products/unassigned#3days-elapsed`）を貼ってください。

その機能に該当する元の Vue.js のコードです。
変更前なので、元のコードはしきい値が4日ではなく5日になっています（リンク先は4日経過になっています）。

```
  .under-cards
    .under-cards__links.mt-4.text-center.leading-normal.text-sm
      a.divide-indigo-800.block.p-3.border.rounded.border-solid.text-indigo-800.a-hover-link(
        class='hover\:bg-black',
        href='/products/unassigned#4days-elapsed',
        v-if='countAlmostPassed5days() === 0')
        | しばらく5日経過に到達する<br>提出物はありません。
      a.divide-indigo-800.block.p-3.border.rounded.border-solid.text-indigo-800.a-hover-link(
        class='hover\:bg-black',
        href='/products/unassigned#4days-elapsed',
        v-else)
        | <strong>{{ countAlmostPassed5days() }}件</strong>の提出物が、<br>8時間以内に5日経過に到達します。
```

**Comment by nakamu-kazu222** [comment]
本番環境でバグが解消されたため、closeいたします
