### ISSUE TITLE
schema.rbに不要なテーブルが追加されているため削除する

### ISSUE THREAD

**Issue by Shrimprin** [fjordllc/bootcamp#8151]
## 概要
[都道府県別ユーザー一覧の非React化](https://github.com/fjordllc/bootcamp/pull/8034/files#top)の[ここ](https://github.com/fjordllc/bootcamp/pull/8034/files#diff-cbf8b25d6d853acf58fa9057841f407d29ffe90649c75cf9e3f51b2d6e3aa1d3R416-R422)で不要なテーブルが追加されている。
migrationもなく誤って追加された変更のため削除する。

**Comment by JunichiIto** [comment]
> 対応方法については別途GitHub上でご相談させてください。

もしかすると駒形さんはKaigi on Railsで返信が遅くなるかも？
なので代わりに返信しておくと、schema.rbを正しく修正するPRを作成すればそれでOKだと思いますー。

**Comment by Shrimprin** [comment]
@JunichiIto 
コメントありがとうございます 🙏 

> schema.rbを正しく修正するPRを作成すればそれでOKだと思いますー

承知いたしました！
