### ISSUE TITLE
インタビュー記事へのリンク先が別の記事になっている

### ISSUE THREAD

**Issue by kotakanazawa** [fjordllc/bootcamp#8187]
## 概要

インタビュー記事へのリンク先が期待通りではなかったので報告します。

## 再現手順

https://bootcamp.fjord.jp/alumni_voices へアクセスし、キャタル（辻田、安藤、川崎）の記事をクリックすると、この記事ではない別の記事 https://bootcamp.fjord.jp/articles/137 へ遷移する
![CleanShot 2024-11-12 at 16 51 48@2x](https://github.com/user-attachments/assets/c82f9e1f-5fc7-451e-bce2-f9584591157e)

## 期待される振る舞い

該当箇所をクリックすると、https://bootcamp.fjord.jp/articles/138 の記事が表示されるべき。

**Comment by kotakanazawa** [comment]
@machida
こちらフィヨルドのDiscord内でも10月初旬に指摘があったようですが、未修正のため起票しています。
新規ユーザー獲得に影響がありそうな箇所で緊急度は高めだと判断し、メンションさせていただきます！

**Comment by machida** [comment]
リリースされたのでクローズしますー
