### ISSUE TITLE
ユーザーに紐付くDOCsのような場所（MEMOs）を作りたい

### ISSUE THREAD

**Issue by sugiwe** [fjordllc/bootcamp#8191]
## 機能の説明

現在のDOCsは基本的にプラクティスに紐付くものとして存在しているかと思います。（「関連プラクティスを指定しない」も可能）
体裁としてはDOCsに似たような機能として、ユーザーに紐付いたドキュメントを残す場所（仮称「MEMOs」）があると嬉しいです。

## 何故この機能が必要なのか

特に私は毎日の学習時間が少ないため、日報が日ごとに分断された記録になってしまうことが多いです。そのため、以下などをはじめとする記録やメモを日報でなくドキュメント単位で保存しておきたいと思うケースがあります。
- チーム開発のissue単位の作業記録（それ以外のプラクティスの作業記録も？）
- 読書メモ、Gitコマンド、その他環境設定などで1箇所にまとめておきたい情報

「そういうのはブログでアウトプットしよう」という考えもありその考えには賛成ですが、最終的にブログでアウトプットするにせよ先にFBC内部で整理してまとめることはステップとして良さそうに思います。（MEMOsでまとめる→「これは有用なのでブログで外部公開しよう」という流れにもなりやすそう）

また、上述した例などにおいて、他の人がまとめたMEMOsはブログなどFBC外の様々なサービスに点在してしまうよりも発見しやすく、受講生全体にとってもメリットになるのではと思っています。

**Comment by komagata** [comment]
@sugiwe Getting Real的にコアでない機能については極力少なく、シンプルにしたいと考えています。
自分のためのドキュメントを貯めておく場所はPC内の自分のメモなどを使っても解決するのではないかと思いますがいかがでしょうか。

**Comment by sugiwe** [comment]
@komagata 
上記ありがとうございます🙏
チーム開発に入って、日報単位でなくissue単位での記録をできたら便利かなと思ったのですが、他の受講生の方もNotionや Cosense（旧Scrapbox）などを活用しているお話を聞き、自分もそういったツールを使いながら一旦まとめていこうと思います！

**Comment by machida** [comment]
@sugiwe

確かに、メモを取るのも一つの場所でできて、それが他の学習者の役立つようになったら理想なのですが、走り書きしたメモと有用な情報があるメモの選別や、そこへの導線をどこからどう繋ぐかを考えるとなかなか難しいですね〜。

あと、メモを見る第三者についても考慮しなくてはいけないので、プラクティスの正解を書いてはいけないなどの制限も発生してしまうので、メモを書く本人にとってはNotionやCosenseよりも面倒なものになってしまう可能性があるんですよね。

余談ですが、今のDocsはカテゴリー分けの機能はなく、基本的にはプラクティスに紐づいているので、プラクティスから情報を探しやすいというメリットがある反面、個人のメモなどは投稿できないですが、そうではないDocsの形もあったかなーというのは前から思ってたことでした。別の思想のDocsを選択してたら別の未来があったかもです。とはいえ、社内のesaですら常にメンテをしないとカオスになりがちなので、FBCでそのようなDocsを選択してたら手に負えないかもしれないですが、今のDocsにはない「いきいき」が得られたかもしれないですね〜。

**Comment by sugiwe** [comment]
@machida 
コメントありがとうございます！
確かに、情報の選別や検索性、さらにメンテナンス性など考えていくと、簡単に「欲しいから入れよう」というわけにはいかないですね…！ komagata さんも書いてくださった Getting Real 的な観点もちゃんと持っていないといけないなぁと改めて感じました。

DOCsの別の可能性についても記載いただきありがとうございます、思想によってサービスの広がり方も変わっていくのですね、とても興味深いです👀

一旦こちらのissueについてはcloseいたします！
