### ISSUE TITLE
リタイアしたユーザーの未チェックの提出物は削除されて欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#823]
多分UserCallbacksに書く感じにすれば管理画面からのリタイアと自分でのリタイアの両方に対応できる。

ARの機能でリタイアフラグの値がfalseからtrueに変化したかどうか分かる機能があるのでそれを使う。

参考：[Rails 5\.1 で attribute\_was, attribute\_change, attribute\_changed?, changed?, changed 等が DEPRECATION WARNING \- Qiita](https://qiita.com/htz/items/56798d53ec5988733fc6)

**Comment by lime1024** [comment]
@komagata @machida 本件、自分のほうでは確認ができないので本番環境での確認と、本 issue の close をお願いしても良いでしょうか。

**Comment by komagata** [comment]
@lime1024 ちょっと今立て込んでいるのでしばらく後になっちゃうかもですが、僕が確認しておきますー！
