### ISSUE TITLE
提出物のページで「確認を取り消すボタン」の表示がおかしい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#832]
[![Image from Gyazo](https://i.gyazo.com/4388fad730559c0237bf16eee7edfa96.png)](https://gyazo.com/4388fad730559c0237bf16eee7edfa96)

ボタンではなく、リンクになっている。

**Comment by machida** [comment]
@komagata すいません、これ、確認すると見た目が同じだとミスりそうなので、わざとこうしました。訂正のほうが頻度は少ないのであえて目立たない見た目にしてあります。

**Comment by komagata** [comment]
@machida あ、なるほど、問題ございません！
