### ISSUE TITLE
プラクティス > 日報 をユーザーで絞り込みたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#838]
プラクティス > 日報一覧のページャーの上のあたりに、ユーザーで絞り込める機能が欲しい

絞り込みはQ&A一覧にあるようなchoices.jsライブラリを使って欲しい

<img width="492" alt="スクリーンショット 2021-04-28 22 51 33" src="https://user-images.githubusercontent.com/16577/116415467-68a13480-a874-11eb-887f-fd9d262c363b.png">

**Comment by machida** [comment]
https://github.com/Choices-js/Choices
このライブラリを検討。
