### ISSUE TITLE
ユーザーに就活中フラグがほしい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#840]
- [ ] アカウント設定画面で就活中をONにできる（チェックボックス）
- [ ] 管理画面のアカウント設定画面で就活中をONにできる（チェックボックス）（これは上のとViewが共通のはず）

**Comment by kasumi8pon** [comment]
マージして、本番環境でアカウント設定画面から就職活動中をONにできることを確認しました。
![スクリーンショット 2019-04-10 16 58 03](https://user-images.githubusercontent.com/38184457/55861692-da38b800-5bb1-11e9-9c97-7816abb55dc7.png)

@komagata @machida 
お手数ですが、以下の確認をお願いします。
- 管理画面のアカウント設定画面で就職活動中をONにできること
- （可能であれば）卒業日・リタイア日を入力した時に就職活動中のフラグが外れること

**Comment by kasumi8pon** [comment]
ミーティング中に駒形さんに確認いただきましたので、このissueはcloseします。
