### ISSUE TITLE
現役生の場合、GitHubアカウント、slackアカウントが未入力の場合、ダッシュボードに警告を出したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#843]

**Comment by matt-note** [comment]
現役生か、GitHub アカウントと slack アカウントが未入力か、については
以下のメソッドで判別できそうだなと。（current_user で）
![Screenshot from 2019-03-20 18-57-36](https://user-images.githubusercontent.com/39484102/54678231-f95e9f80-4b47-11e9-830a-f7a5c2efcc6f.png)

alert については、Practice の 「127: チャットルームに入る」  と「137: SNSの登録」の提出物を出していて、
未入力だったら alert を出す、というふうになるのかなと。
![Screenshot from 2019-03-20 19-17-20](https://user-images.githubusercontent.com/39484102/54678346-4b072a00-4b48-11e9-8e7c-3a37f0b4d338.png)
