### ISSUE TITLE
管理者とアドバイザーのダッシュボードに就活中ユーザー一覧が欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#856]

**Comment by kasumi8pon** [comment]
町田さんにデザインを入れてマージしていただきました！
@machida @komagata 
管理者・アドバイザーのダッシュボードのみの表示なので、
お手数ですが本番環境での確認をお願いいたします🙏

**Comment by komagata** [comment]
@kasumi8pon 確認しました。ありがとうございますー！

**Comment by kasumi8pon** [comment]
@komagata ご確認ありがとうございます！
確認していただいたので、このissueはcloseします。
