### ISSUE TITLE
カレンダーで使ってる jsライブラリ flatpickr  を削除してブラウザデフォルトの日付入力にしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#880]

**Comment by matt-note** [comment]
- [ ] js ライブラリの flatpickr を削除する。
- [ ] flatpickr を使っているコードを削除する。

**Comment by matt-note** [comment]
削除する部分は以下の通り。
![Screenshot from 2019-04-24 20-55-32](https://user-images.githubusercontent.com/39484102/56657560-54e5f500-66d3-11e9-8e2b-aca94d205d3e.png)

**Comment by matt-note** [comment]
datepicker 部分も削除する。
![Screenshot from 2019-04-24 21-48-28](https://user-images.githubusercontent.com/39484102/56660582-c07f9080-66da-11e9-9b33-54b00ffdc622.png)

**Comment by matt-note** [comment]
![Screenshot from 2019-04-24 22-13-36](https://user-images.githubusercontent.com/39484102/56662192-61bc1600-66de-11e9-8b18-1fc740677be1.png)

**Comment by machida** [comment]
@matt-note これって終わってますか？

**Comment by matt-note** [comment]
@machida さん

手元では終わってます。
ただ、レビューでやり直す部分があるかもしれません。

**Comment by machida** [comment]
@matt-note 不要なCSSも削除するので終わったものをGitHubにあげるようお願いします。

**Comment by matt-note** [comment]
@machida 

> 不要なCSSも削除するので終わったものをGitHubにあげるようお願いします。

push していこうと思います。
