### ISSUE TITLE
通知一覧ページがほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#881]
理由：今は通知を開いてしまうと二度とわからなくなってしまうので。

- 通知一覧
- ページャーもほしい
- 今の通知のに「全て」のリンクがほしい

@machida とデザイン・レイアウトについては相談。

**Comment by matt-note** [comment]
TODO
* [ ] notifications_controller.rb に index アクションを追加する。
* [ ] view/application/_notification がドロップダウンの通知になっている。
* [ ] 通知の「全て」リンクを作成して、これをクリックすると通知一覧ページに移動できるようにする。

**Comment by matt-note** [comment]
db/schema.rb で属性を参考にする。
![Screenshot from 2019-04-10 23-11-17](https://user-images.githubusercontent.com/39484102/55886055-02420e80-5be6-11e9-8684-d66a6d1a7f23.png)
