### ISSUE TITLE
学習の進捗のステータスの仕様作成

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#902]
![image](https://user-images.githubusercontent.com/168265/56010843-3a4d6c80-5d20-11e9-9787-b5e8d58203c9.png)

## 仕様変更

- 開始は1つのプラクティスにのみ付けられるようにし、複数のプラクティスを開始にした場合はエラーを出す。

- ステータス
  - 未着手
  - 着手
  - 提出
  - 完了

- 着手のものは一つだけにする（バリデーション）
  - 提出していれば、次のプラクティスに進めるということ。

- 未完、開始、完了を、未完、開始、提出に変更。
    - ただし、提出物がないプラクティスは、未完、開始、完了にする。
- 提出物を作成したら「提出」がアクティブになる（プラクティス一覧にあるステータスボタンは自分でクリックしない（できなくする））。開始ボタンは自分でクリックする。
    - ただし、提出物がないプラクティスは、プラクティス個別ページの「完了」ボタンをクリックすることで完了がアクティブになる（プラクティス一覧にあるステータスボタンは自分でクリックしない（できなくする））。

**Comment by komagata** [comment]
それぞれをIssueとして作ったのでDone。
