### ISSUE TITLE
Slackのアカウントをユーザー一覧にも表示したい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#904]
@HouraiSyuto お待たせしました！次のissueです！

<img width="1142" alt="貼り付けた画像_2019_04_12_16_19" src="https://user-images.githubusercontent.com/168265/56019173-f0c04a00-5d3e-11e9-9779-bf67e18bb2e0.png">

**Comment by tararico** [comment]
本番環境で確認できたのでcloseします
