### ISSUE TITLE
はじめての日報にみんなが気づけるようにしたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#913]
はじめての日報を誰かが書いたら。みんなに通知を送る。

「はじめての日報をXXXさんが書いたよ！」

みたいな。

**Comment by lime1024** [comment]
本番環境で通知を確認できたのでクローズします。
![33E72DAA-CE99-42FE-B176-261FD8DD8829](https://user-images.githubusercontent.com/39685884/57370147-60084d00-71ca-11e9-99ae-c3bd459f0797.png)
