### ISSUE TITLE
会員登録にブートキャンプ参加の目的を追加

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#926]
- 主に一般ユーザー、アドバイザー（adviser）, 研修生（trainee）の三種類のユーザーがあるが、アドバイザーと研修生の登録・編集フォームでは非表示にしたい。
- 非必須項目
- booleanでいい（プログラマーとして就職したい　YES/NO）

**Comment by shoynoi** [comment]
@komagata issueについていくつか質問があります

usersテーブルに`job_seeker`カラム(boolean)を追加し、以下の画像のようにフォームにセレクトボックスを追加しました。

![スクリーンショット 2019-11-22 9 45 25](https://user-images.githubusercontent.com/37890305/69388857-a740d000-0d0d-11ea-8f86-c5d6e2cc20f5.png)

- 項目の説明の文言は何を記述すれば良いでしょうか
- 配置場所に問題はないでしょうか

**Comment by shoynoi** [comment]
本番環境で動作確認できたのでColseします
