### ISSUE TITLE
通知がメールでも飛ぶようにしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#931]

**Comment by matt-note** [comment]
* メール送信は、サインアップをマネして作る。

**Comment by matt-note** [comment]
質問です。
提出物の通知は管理者向けの通知ということで、これはリタイア率と関係ないと思います。  
提出物の通知については、メールしないということで、よろしいでしょうか？
```ruby
# app/models/product_callbacks.rb
def send_notification(product, message)
  User.admins.each do |user|
    Notification.submitted(product, user, message)
  end
end
```

**Comment by matt-note** [comment]
質問です。
通知のメールについて、件名やメール本文はすべて同じ内容にするということで、よろしいでしょうか？
それとも、通知の種類ごとに件名とメール本文を変更するのでしょうか？
よろしくお願いします。

**Comment by matt-note** [comment]
@komagata さん

質問です。
メール送信の実行は、private メソッドで別にした方が良いでしょうか？
下のメンションの例では、notify の意味にメールも含まれると考えると、メール送信をそのまま実行できて、すっきり書けるように思います。
よろしくお願いします。

```ruby
# app/models/comment_callbacks.rb
def notify_mention(comment)
  comment.new_mentions.each do |mention|
    reciever = User.find_by(login_name: mention)
    if reciever && comment.sender != reciever
      Notification.mentioned(comment, reciever)
      UserMailer.notification(receiver).deliver_now  # メール送信
    end
  end
end
```

**Comment by komagata** [comment]
@matt-note 

> 提出物の通知は、管理者へ向けた通知ということで、これはリタイア率と関係ないと思います。
提出物の通知については、メールしないということで、よろしいでしょうか？

特例を作るとルールが複雑になるので一旦、全部メールすることにしたいです。

> 通知のメールについて、件名やメール本文は「すべて同じ内容にする」ということで、よろしいでしょうか？

いいえ、個別の内容にしたいです。

> メール送信の実行は、private メソッドで別にした方が良いでしょうか？

一つ一つ、サイト内通知か、メール送信かを考えなくて住むように、

- Notification.xxx
  - InSiteNotification.xxx
  - NotificationMailer.xxx

みたいな作りの方がいいかも？

**Comment by matt-note** [comment]
@komagata さん

ご回答ありがとうござます。
メール送信については、特例はなく、すべての通知をメールするということで進めていこうと思います。
また、件名とメール本文については、通知の種類ごとに、個別で作成していこうと思います。

> Notification.xxx
        -> InSiteNotification.xxx
        -> NotificationMailer.xxx
みたいな作りの方がいいかも？

通知の種類ごとに件名とメール本文が異なるので、UserMailer ではなく、NotificationMailer でまとめる作りにしていこうと思います。Notification を InSiteNotification にすることについては、Slack への通知が SlackNotification なので、ありだと思います。
これは名前を変えるだけですが、この Issue だと変更の範囲が大きいのでは…。
別 Issue でやってもらうと良いのではと思いますが、いかがでしょうか？

**Comment by machida** [comment]
@matt-note 

リタイア率、これはですね、現状は bootcamp にログインをしないと通知が受け取れないんですよね。ということは、ログインをしていない人（サボリ気味の人）に対して通知を知らせられない、という問題が発生しています。メールでも通知が飛ぶことにより、ログインをしていなくても、自分へのメッセージが来ていることがわかり、それを確認するためにログインをします。ログインをすることで、リタイア率が下がる、というのを期待しています。

**Comment by komagata** [comment]
@matt-note 大した変更ではないのでこのIssueでやってしまって大丈夫ですー

**Comment by matt-note** [comment]
@machida さん

> メールでも通知が飛ぶことにより、ログインをしていなくても、自分へのメッセージが来ていることがわかり、それを確認するためにログインをします。ログインをすることで、リタイア率が下がる、というのを期待しています。

そういえば、私がリタイアしなかったのも、komagata さんからの一通のメールだったので、メールは効果あると思います。

@komagata さん
> 大した変更ではないのでこのIssueでやってしまって大丈夫ですー

このIssue で名前の変更を行おうと思います。

**Comment by matt-note** [comment]
@komagata 

質問です。
[test/fixtures/notifications.yml](https://github.com/fjordllc/bootcamp/blob/master/test/fixtures/notifications.yml) に、通知の種類ごとのフィクスチャを追加しても良いでしょうか？
通知の種類ごとにメールのテストをする時に、通知の種類ごとのフィクスチャが必要なためです。
現在、通知の種類は9つで、フィクスチャの種類は3つなので、6つ追加したいと考えています。
よろしくお願いします。

**Comment by matt-note** [comment]
@komagata 

テーブル名について、質問です。
既存の通知を InSiteNotification クラスに変更したので、テーブル名は in_site_notification と長くなり、モデルのファイル名が in_site_notification.rb と長くなります。この命名で大丈夫でしょうか？
よろしくお願いします。
