### ISSUE TITLE
確認ボタンをVue.js化する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#939]

**Comment by kasumi8pon** [comment]
本番環境で、スタンプが表示されていることを確認しました。
![FactoryBotで関連を扱う   FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/38184457/58812646-3f160900-865d-11e9-9007-791a5dccdbe3.png)

@komagata @machida 
確認ボタンが正常に動作することをご確認お願いします🙏

**Comment by kasumi8pon** [comment]
本日MTGにて、町田さんから確認した旨伺ったので、クローズします。
