### ISSUE TITLE
コメントをVue.js化する

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#942]

**Comment by kasumi8pon** [comment]
![スクリーンショット 2019-07-10 16 33 22](https://user-images.githubusercontent.com/38184457/60949732-c3307000-a330-11e9-92ce-10a3e1094f6f.png)

本番環境でコメント投稿・編集・削除・プレビュー・オートコンプリート機能について確認しました。
クローズします。

**Comment by komagata** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
