### ISSUE TITLE
無料ユーザー、有料ユーザーのコースを別のものにしたい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#949]
- 有料ユーザー
    - 就職活動、発展編 をなくしたい
    - jQuery、coffee script をなくしたい
        - 上記をなくした別コースを作成し、それをやるようにしたい。もしくは、無料ユーザーを別コースにするのでもOK。

**Comment by komagata** [comment]
@machida 今、サインアップ時にカード必須のブランチを作っているので（ほぼ行けそう）それがあれば新しい無料ユーザーはなくなるはずです。

上記をリリースしたあと、お試し期間の3日過ぎてしまえば、最近のユーザーでカード登録がない人は削除しちゃっていいかもです。
