### ISSUE TITLE
日報につけるプラクティスタグが編集画面と閲覧画面で順番が異なっているので、同じ順番にしてほしい

### ISSUE THREAD

**Issue by wai-doi** [fjordllc/bootcamp#959]
# 背景
日報編集で、その日報がどのプラクティスに対応した日報なのかがわかるように、プラクティスのタグのようなものをつけることができる機能について。

そのプラクティスタグが編集画面と閲覧画面で順番が異なる場合があります。
現状だと編集画面と閲覧画面で差異があるので不自然です。

以下の例では「Cookieについて理解する」と「nginxの基礎を理解する」の順番が異なっています。

- ### 編集画面のプラクティスタグ
![](https://user-images.githubusercontent.com/29339636/57680969-bdd4e300-7669-11e9-8ec2-1a2f77f62d6a.png)

- ### 閲覧画面のプラクティスタグ

![](https://user-images.githubusercontent.com/29339636/57681380-874b9800-766a-11e9-994e-4124f90fb5f9.png)

# 提案
編集画面と閲覧画面の両方で、プラクティス一覧の順番でプラクティスタグを並べて表示させると、学習順序と対応するのでわかりやすいと思います。

**Comment by wai-doi** [comment]
### 編集画面
<img width="1019" alt="日報編集___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/29339636/57680969-bdd4e300-7669-11e9-8ec2-1a2f77f62d6a.png">

---
### 閲覧画面
<img width="625" alt="HTTP___Nginx___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/29339636/57681154-215f1080-766a-11e9-9c2d-5b4bf96acad0.png">

**Comment by machida** [comment]
@wai-doi

> 両画面とも、プラクティス一覧の順番でプラクティスタグが表示された方がいいと思いました。

いいと思いました、についてもっと具体的に、なぜいいと思ったのかまでちゃんと共有をしたほうがいいです。

**Comment by wai-doi** [comment]
@machida 現状でよくない理由と提案方法がなぜよいと思うのかについての根拠を編集で付け加えました。

**Comment by machida** [comment]
@wai-doi ありがとうございます！確かに、学習した順番に登録してるのが無駄になってしまうのは勿体ないですね。

**Comment by wai-doi** [comment]
本番環境で確認できたので、closeします👍

<img width="533" alt="HTTP___Nginx___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/29339636/62269309-9eca3e00-b46d-11e9-93c8-358df0dee92d.png">
