### ISSUE TITLE
通知一覧も同じURLのものは表示を一つにしてほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#974]
右上の小さい通知と通知一覧の二つがある。
小さい通知はすでに同じものはまとめて表示している。通知一覧の方でも同じURLに対する通知の表示は一つにしたい。

**Comment by s4na** [comment]
## 作業
- [ ] 調査
  - 通知の種類を調査
  - 通知の方法・経路を調査
- [ ] テストを書く
  - [ ] 複数の通知を作成して、一つにまとまっているか確認するテストを作成
- [ ] 実装する
