### ISSUE TITLE
/users/new?training=trueでサインアップしたら研修フラグ・無料フラグをオンでサインアップしたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#975]
企業研修で来ている人なのに「クレジットカードを登録してください」と出てしまう。

もし `/users/new?training=true` のURLからサインアップしたらUserの`trainee`と`free`のフラグが`true`でサインアップしたい。

（freeフラグがtrueだとクレジットカードは必要ないようにすでに作られている）

**Comment by tararico** [comment]
本番環境で確認したのでclose
