### ISSUE TITLE
はじめての日報通知がWIPで送られている

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#987]

**Comment by s4na** [comment]
## 作業

**Comment by s4na** [comment]
## 確認事項まとめ

### komagataさんへの確認

- s4na: `ReportCallbacks.rb`内で`trainee`の日報作成時、`advisers`にメール通知が発生しているが、今回の対応でWIPの時は通知しないように修正するか？
- komagata: 今後 watch機能に統合予定なので、今は修正不要

**Comment by s4na** [comment]
## 作業
- [ ] 本番での確認
