### ISSUE TITLE
プラクティス > 提出物 のページにページャーがほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#991]

**Comment by akht** [comment]
@machida @komagata 
このissueへの対応で2点質問です。

1. [プラクティス > 提出物]以外に、[提出物]から直接遷移した場合でも
ページャーが表示されたほうがいいですか？(表示されて構わないですか？)
1. 両方に表示される場合、1ページあたりのアイテム数は同じでよいですか？

**Comment by komagata** [comment]
@akht 

> プラクティス > 提出物

↑この書き方は「プラクティス」から「提出物」へ遷移したとき
ではなくて、

`https://bootcamp.fjord.jp/practices/xxxx/products`

系のページのことです。

例：
https://bootcamp.fjord.jp/practices/131/products

> 両方に表示される場合、1ページあたりのアイテム数は同じでよいですか？

50件でお願いします。

**Comment by akht** [comment]
@komagata 
そういうことでしたか。失礼しました！
では50件で対応します！

**Comment by machida** [comment]
@akht
全然失礼じゃないです！！すいません、僕のissueの書き方が悪かったです。提出物の一覧ページはどのページでもページャーが出て構いません、というか出したいです。数も同じで大丈夫です。
