### ISSUE TITLE
リタイアした人のWIPの日報は削除されてほしい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#992]
リタイアした時、その人の日報にWIPのものがあったら削除したい。

### リタイアのタイミング

- ユーザー自身がリタイア（退会）画面からリタイア
- 管理画面で管理者がユーザー編集画面でリタイア

**Comment by komagata** [comment]
@tararico 先程話していた代わりのIssueです。こちらお願いできれば〜
ポイントは全員で見積もってないですが僕が考えました。

**Comment by tararico** [comment]
@komagata かしこまりました！

**Comment by tararico** [comment]
@komagata レビューありがとうございました。mergeいたしました。本番環境での動作確認はユーザーを作成して確認してよろしいでしょうか？

**Comment by tararico** [comment]
確認したのでclose
