### ISSUE TITLE
カテゴリーによってQ&Aが投稿できないものがある

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#999]

**Comment by matt-note** [comment]
@machida 
現在 komagata さんとペアプロしてこのissueに対応しています。
どのカテゴリー（プラクティス？）で投稿できないのしょうか？
よろしくお願いします。

**Comment by machida** [comment]
@mart-note 判明しないので一通りのカテゴリで試してもらえますか？

**Comment by matt-note** [comment]
@machida 
> 判明しないので一通りのカテゴリで試してもらえますか？

ペアプロを時に、iOS や Unity などのカテゴリでざっとQ&Aを投稿してみたところ、これらは投稿できました。すべてのカテゴリでは試していないので、確認してみようと思います。

**Comment by komagata** [comment]
@matt-note 本番だけの現象かもしれないですね。本番で試してみる必要があるかも（テスト投稿しちゃっても大丈夫です）

（ただ、このバグIssueはペアプロのあまり時間で取り掛かったものなので@matt-noteさんが必ずやらなきゃいけないというわけではないです。）

**Comment by matt-note** [comment]
@komagata コメント、ありがとうございます。理解が明確になりました。
